### ISSUE TITLE
RZ10012 ignores TreatWarningsAsErrors and WarningsAsErrors

### ISSUE THREAD

**Issue by janusko** [dotnet/aspnetcore#27570] opened 2020-11-06 08:56 UTC
RZ10012 is reported by the razor compiler when a component tag could not be resolved as a known razor component. The warning should be possible to turn to error by specifying TreatWarningsAsErrors and WarningsAsErrors in a project file. The warning is still threated as warning despite having these settings correctly set.

### To Reproduce

Have a simple razor components library project:
```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="3.1.4" />
  </ItemGroup>

</Project>
```

With one razor component containing just:
```razor
<NonExistingComponent />
```

Because of the project configuration, build error is expected, but the warning is raised by the compiler instead.

**Comment by mkArtakMSFT** [comment] 2020-12-03 17:47
Thanks for contacting us. This is a dupe of #12814

**Closed by mkArtakMSFT** 2020-12-03 17:47 UTC
Labels: area-razor.compiler
