### ISSUE TITLE
Error in Register link perhaps in RemoteAuthenticatorView Action="@Action" tag.

### ISSUE THREAD

**Issue by wbalzer** [dotnet/aspnetcore#20078] opened 2020-03-23 19:03 UTC
I don’t know if this is just me, but on two machines running VS 2019 v16.4.6, I create a Blazor WebAssembly project with Individual User Accounts option, ASP.Net Core Hosted, and PWA options checked. I’m using ASP.Net Core 3.1.200. Doing nothing more than just running the application (IIS Express), when I click the Register Link at the top of the page, the page says… Checking login state…. with an “An unhandled error has occurred. Reload” at the bottom.

`WASM: ﻿Unhandled exception rendering component:
blazor.webassembly.js (1,35601)
WASM: Microsoft.JSInterop.JSException: Invalid calling object
blazor.webassembly.js (1,35601)
WASM: TypeError: Invalid calling object
blazor.webassembly.js (1,35601)
WASM:    at Anonymous function (https://localhost:44308/_framework/blazor.webassembly.js:1:9733)
blazor.webassembly.js (1,35601)
WASM:    at Promise (native code)
blazor.webassembly.js (1,35601)
WASM:    at e.jsCallDispatcher.beginInvokeJSFromDotNet (https://localhost:44308/_framework/blazor.webassembly.js:1:9703)
blazor.webassembly.js (1,35601)
WASM:    at _mono_wasm_invoke_js_marshalled (https://localhost:44308/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js:1:162911)
blazor.webassembly.js (1,35601)
WASM:    at Module[_mono_wasm_invoke_method] (https://localhost:44308/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js:1:187078)
blazor.webassembly.js (1,35601)
WASM:    at BINDING.call_method (https://localhost:44308/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js:1:150813)
blazor.webassembly.js (1,35601)
WASM:    at Anonymous function (https://localhost:44308/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js:1:153153)
blazor.webassembly.js (1,35601)
WASM:    at beginInvokeDotNetFromJS (https://localhost:44308/_framework/blazor.webassembly.js:1:37610)
blazor.webassembly.js (1,35601)
WASM:    at s (https://localhost:44308/_framework/blazor.webassembly.js:1:8432)
blazor.webassembly.js (1,35601)
WASM:    at e.invokeMethodAsync (https://localhost:44308/_framework/blazor.webassembly.js:1:9502)
blazor.webassembly.js (1,35601)
WASM:   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2cb9260 + 0x0002c> in <filename unknown>:0 
blazor.webassembly.js (1,35601)
WASM:   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync (Microsoft.JSInterop.IJSRuntime jsRuntime, System.String identifier, System.Object[] args) <0x2aa1508 + 0x000e4> in <filename unknown>:0 
blazor.webassembly.js (1,35601)
WASM:   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1[TAuthenticationState].OnParametersSetAsync () <0x2d5f528 + 0x00550> in <filename unknown>:0 
blazor.webassembly.js (1,35601)
WASM:   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x2bffdd8 + 0x000e6> in <filename unknown>:0 
blazor.webassembly.js (1,35601)
WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2a11168 + 0x001fc> in <filename unknown>:0 
blazor.webassembly.js (1,35601)
WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2c00918 + 0x000c2> in <filename unknown>:0 
blazor.webassembly.js (1,35601)`

The Login link works just fine, and the Register link on the server page works fine. Returning back to the Client app, clicking my email address to take me to a profile page… that is also broken.
I am assuming the problem lies in the new tag…

`<RemoteAuthenticatorView Action="@Action" />`

[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/4371382/BlazorApp1.zip)

**Comment by javiercn** [comment] 2020-03-24 10:33
@wbalzer thanks for contacting us.

We'll take a look at this issue and get back to you.

**Comment by javiercn** [comment] 2020-03-26 13:57
@wbalzer You need to be using the 3.1.102 sdk. You can do so with `dotnet new globaljson --sdk-version 3.1.102` on your solution root.

**Comment by wbalzer** [comment] 2020-03-26 14:54
@javiercn For clarification, Do I need to downgrade my sdk to 3.1.102 because Preview 2 is targeting 3.1.102 sdk, and I have a mismatch, or is this a workaround to get my project working until Preview 3 or Preview 4 where the issue will be fixed using a later sdk (v3.1.200)...?

**Comment by wbalzer** [comment] 2020-03-26 16:50
@javiercn  Never mind...  I see the difference in sdk's targeting VS 2019 v16.4 vs v16.5.  I have both on one machine, but the other, just v16.4.

**Comment by wbalzer** [comment] 2020-03-26 21:12
@javiercn I am still having issues after upgrading to v16.5.1, sdk 3.1.201, and Preview 3.  I did follow your recommendation, which didn't help, neither on an old project, nor new project.

**Comment by danroth27** [comment] 2020-03-26 21:29
Reopening since the SDK version looks right.

**Comment by cmyers** [comment] 2020-03-26 23:34
I'm also experiencing this behavior with both the authentication/register and authentication/profile paths. However, this only seems to occur when using a custom OIDC configuration with AddOidcAuthentication in Program.cs of Blazor WebAssembly (3.2.0-preview2.20160.5).

**Comment by javiercn** [comment] 2020-03-30 16:01
I can't repro this with the latest template from VS and the 3.1.3 SDK. My version is `Version="3.2.0-preview3.20168.3"`

**Comment by javiercn** [comment] 2020-03-30 16:01
Closing since I can't reproduce it.

**Closed by javiercn** 2020-03-30 16:01 UTC
Labels: area-blazor, blazor-wasm, cost: XS
