### ISSUE TITLE
The DailyBuilds page does not contain any links to Linux installers

### ISSUE THREAD

**Issue by karolz-ms** [dotnet/aspnetcore#51176] opened 2023-10-06 00:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I wanted to install latest .NET 8 RC2 build on an Ubuntu 22.04 VM and was not able to because "ASP.NET Core Shared Framework" installer was nowhere to be found. See repro steps for details.

### Steps To Reproduce

1. I wanted to install latest .NET 8 RC2 build on an Ubuntu 22.04 VM and was directed to https://github.com/dotnet/installer#table
2. From there I looked at the 8.0 RC2 / Linux x64 cell of the table 
3. The reference note tells me I need to install some prerequisites before running the installer linked in the cell. OK. I clicked on the link that says “Host, Host FX Resolver, and Shared Framework” and downloaded all the packages there (there was actually 6 of them https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#daily-builds-table. Installed all
4. Came back to the main page, cand clicked on a link that was supposed to lead me to ASP.NET Core installation packages. It leads to this page https://github.com/dotnet/aspnetcore/blob/main/docs/DailyBuilds.md There is no reference to any installers on this page.

**Comment by wtgodbe** [comment] 2023-10-10 18:25
Thanks for the report - as of now, aspnetcore does not publish our nightly builds to an LKG location, which is tracked by https://github.com/dotnet/aspnetcore/issues/35457. I'm going to close this issue as a dupe of that one - we're hoping to get this fixed in .net 9.

**Closed by wtgodbe** 2023-10-10 18:25 UTC
Labels: area-infrastructure

**Comment by wtgodbe** [comment] 2023-10-20 20:32
Wanted to update you on the progress here - it will be fixed by https://github.com/dotnet/aspnetcore/pull/51534
