### ISSUE TITLE
Quic stream completion races with `Abort`

### ISSUE THREAD

**Issue by ManickaP** [dotnet/aspnetcore#43614] opened 2022-08-29 07:38 UTC
Discovered in https://github.com/dotnet/runtime/issues/72619

If I'm reading the code of `AbortCore` right:
https://github.com/dotnet/aspnetcore/blob/51ccce6d743dddf995b3661f07b0e1990b68dc7d/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs#L145-L184
It first completes the `PipeWriter` before calling `QuicStream.Abort`:
https://github.com/dotnet/aspnetcore/blob/51ccce6d743dddf995b3661f07b0e1990b68dc7d/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Stream.cs#L170-L172

And the `PipeWriter` completion will asynchronously attempt to "complete the writes" gracefully.

_Originally posted by @ManickaP in https://github.com/dotnet/runtime/issues/72619#issuecomment-1228815100_

cc @JamesNK

**Comment by JamesNK** [comment] 2022-08-30 02:39
I've investigated this and `_http3Output.Stop()` shouldn't have an impact on this. It stops the HTTP/3 output from writing HTTP/3, but it doesn't stop the transport.

As far as I can tell, `HttpContext.Abort()` will:
1. Call `QuicStream.Abort(QuicAbortDirection.Read, resolvedErrorCode)`
2. Call `QuicStream.Abort(QuicAbortDirection.Write, resolvedErrorCode)`
3. Call `QuicStream.CompleteWrites()`

These are all on the same thread. No multi-threading or race conditions are involved in Kestrel. If the bug is caused by calling CompleteWrites after Abort then it's simple enough to change.

**Comment by ManickaP** [comment] 2022-08-30 08:07
Doesn't it complete the pipewriter: https://source.dot.net/#Microsoft.AspNetCore.Server.Kestrel.Core/Internal/Http3/Http3OutputProducer.cs,288
which in turn completes the Output in `DoSendAsync`: https://source.dot.net/#Microsoft.AspNetCore.Server.Kestrel.Transport.Quic/Internal/QuicStreamContext.cs,536faecd1ca0eee4,references eventually calling `ShutdownWrite`: https://source.dot.net/#Microsoft.AspNetCore.Server.Kestrel.Transport.Quic/Internal/QuicStreamContext.cs,bc0a8335a509b38a

And since you have a pipe in the middle, it becomes asynchronous and thus creating a possibility for a race???

**Comment by JamesNK** [comment] 2022-08-30 10:38
That's a different pipe. They're all over the place in Kestrel.

The pipe stopped by `Http3OutputProducer.Stop()` is read here in [`Http3OutputProducer.ProcessDataWrites()`](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Servers/Kestrel/Core/src/Internal/Http3/Http3OutputProducer.cs#L405)

**Comment by adityamandaleeka** [comment] 2022-09-02 20:25
@JamesNK Assigning this to you since you're already looking at it.

**Comment by adityamandaleeka** [comment] 2022-09-09 20:45
Moving to 8 since RC2 is basically done at this point.

**Comment by JamesNK** [comment] 2022-09-10 00:24
Confirmed fix in an earlier change - https://github.com/dotnet/runtime/issues/72619

**Closed by JamesNK** 2022-09-10 00:24 UTC
Labels: area-runtime
