### ISSUE TITLE
Blazor WASM multiple components & free coding

### ISSUE THREAD

**Issue by efraimt** [dotnet/aspnetcore#24341] opened 2020-07-27 17:50 UTC
Hello everyone,

I need a site that is very sensitive to SEO, so I prefer a site that has several pages that are divided into different matters, compiled on the server, and provided to explore as HTML.
There are some components that I need to use them with Ajax.
I am not interested in working with WebSocekts and therefore neither SignalR, nor with Blazor Server.

I need components in different places on the pages (sometimes more than one place on each page), where people fill in several fields and send them to the server.

Blazor WASM is written in the head of components, and probably rightly so, but I sometimes want to write simple commands I would do with Jquery for example like server calls, and I no longer want to use JS, is it possible to write free C # code that does not depend on areas (where components are located)?
I do not want to write the Ajax in JS anymore, is it possible to perform the task with Blazor in C #.

Or maybe there is a way (even through areas) to get what I need?
That is:
1. Each page has an app that uploads a different component (the pages are different razor pages (not SPA) who share a layout, the pages are rendered from the server.
2. Is there a possibility to place different areas on the page, how do I tell each component where to enter?
**Edited: I just saw that I can add multiple RootComponents.
That can be kind of a work around, but it will mean that I will refer to  almost each component as a RootComponent and I will have to kind of "register" each one of them.** 
3. Is it planned to enable writing free C # code in the future with Blazor (without placing it in a component), just using http.Get() type of behaviour - without a component - like in Jquery or JS?

Thank you!

**Comment by javiercn** [comment] 2020-07-28 10:12
This is mostly a dupe of https://github.com/dotnet/aspnetcore/issues/14434

> 3\. Is it planned to enable writing free C # code in the future with Blazor (without placing it in a component), just using http.Get() type of behaviour - without a component - like in Jquery or JS?

This is not in our current plans as blazor webassembly requires the .net runtime to be downloaded into the browser and the code to be compiled to run on WebAssembly. Having that mixed in with the host web application would produce a poor experience as it would be confusing to handle references to other libraries and so on.

**Comment by javiercn** [comment] 2020-07-28 10:13
Closing this issue as we already have a separate tracking issue for this.

**Closed by javiercn** 2020-07-28 10:13 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
