### ISSUE TITLE
Namespace usings with aliases are not handled correctly in razor files

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/aspnetcore#24130] opened 2020-07-20 20:37 UTC
I try to use a third party library and unfortunately there's a namespace conflict. I would expect that I can use alias based usings in razor files to solve the conflict like this:

```
@using global::Blazor.DragDrop.Core
```
The using is accepted by the compiler, but the components in that namespace are still not resolved correctly.

![image](https://user-images.githubusercontent.com/5387192/87984033-a0a36c00-cad9-11ea-93cc-a79df38cd6f6.png)

**Comment by mkArtakMSFT** [comment] 2020-07-27 22:22
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/13090

**Closed by mkArtakMSFT** 2020-07-27 22:22 UTC
Labels: area-razor.tooling
