### ISSUE TITLE
Bind CascadingParameter multiple times in same component

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#46147] opened 2023-01-18 11:15 UTC
I have this:
````xml
<CascadingValue Value=_foo>
  ...content...
</CascadingValue>
````

Where `_foo` is this:
````cs
public class Foo : Bar, Baz
{
  //...
}
````

In some component I have this:
````cs
[CascadingParameter] public Foo Foo { get; set; }
[CascadingParameter] public Bar Bar { get; set; }
[CascadingParameter] public Baz Baz { get; set; }
````

And that worked! So I can bind one cascading parameter multiple times in the same component.

**Is this a side effect (which could change in the future), or is it a supported scenario?** The docs don't say.

**Comment by mkArtakMSFT** [comment] 2023-01-18 17:20
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

**Closed by mkArtakMSFT** 2023-01-18 17:20 UTC
Labels: area-blazor
