### ISSUE TITLE
"There is no event handler associated with this event" when an element is focused out

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#26838] opened 2020-10-13 05:09 UTC
### Describe the bug
An error is thrown:
>  Error: System.ArgumentException: There is no event handler associated with this event. EventId: '3'. (Parameter 'eventHandlerId')

when an element with focusout handler is removed from the DOM in a blazor wasm app (both 3.1 and 5.0).

### To Reproduce
1. Clone the https://github.com/Stamo-Gochev/blazor-net5-wasm-focusout repository
2. Set the [TestNet5Wasm.Server](https://github.com/Stamo-Gochev/blazor-net5-wasm-focusout/tree/master/TestNet5Wasm/TestNet5Wasm/Server) as a startup project. 
> **Note:** In order to test the 3.1 version of wasm, use the [TestNet31Wasm.Server](https://github.com/Stamo-Gochev/blazor-net5-wasm-focusout/tree/master/TestNet5Wasm/TestNet31Wasm)
3. Run the app (Ctrl + F5)
4. On the `Index.razor` page, click on `item 2` that has [@onfocusout](https://github.com/Stamo-Gochev/blazor-net5-wasm-focusout/blob/master/TestNet5Wasm/TestNet5Wasm/Client/Pages/Index.razor#L8) handler

> **Note:** The main logic is part of the [Index.razor](https://github.com/Stamo-Gochev/blazor-net5-wasm-focusout/blob/master/TestNet5Wasm/TestNet5Wasm/Client/Pages/Index.razor) page only and the [script.js](https://github.com/Stamo-Gochev/blazor-net5-wasm-focusout/blob/master/TestNet5Wasm/TestNet5Wasm/Client/wwwroot/script.js) file.

### Exceptions (if any)
> Error: System.ArgumentException: There is no event handler associated with this event. EventId: '3'. (Parameter 'eventHandlerId')

### Further technical details
- ASP.NET Core version 3.1, 5.0 RC1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

### Additional context
A similar problem is marked to be fixed in multiple cases like:
 https://github.com/dotnet/aspnetcore/issues/17926
https://github.com/dotnet/aspnetcore/issues/21241
https://github.com/dotnet/aspnetcore/issues/21366
https://github.com/dotnet/aspnetcore/issues/21874#issuecomment-632814894

but the problem is still reproducible in both the 3.1 and 5.0 versions.

**Comment by majorimi** [comment] 2020-10-20 08:54
With .NET5 RC2 it seems to be working even with Blazor WebAssembly. Did not get any error. But `VS 2019 Intelligense` does not show this event handler only `onfucus`:

![image](https://user-images.githubusercontent.com/7632824/96559039-d4e71e00-12bc-11eb-91a0-9dfa046d0d49.png)

**Comment by SteveSandersonMS** [comment] 2020-10-20 08:57
@majorimi It's not clear to me that what you're posting here is the same thing as this issue. Instead of posting here, could you please file a new issue giving a clear description of what you're doing (since it's likely totally different)?

**Comment by majorimi** [comment] 2020-10-20 13:53
@SteveSandersonMS: I was trying out `@onfocusout` event with a very similar code as your example above. Run it in a Blazor WebAssembly (not server side) project and I received the events without exceptions. So just confirmed bug was fixed...

Also my point was if this event is supported by Blazor and works perfectly, why Visual Studio 2019 Intelligense is not offering it when I'm typing `focus` keyword? 
As you can see on that screenshot Intelligense has 1 result for `@onfocus` however it should match with 2 items: `@onfocus` and  `@onfocusout` as well.

Sure lets post it to a new issue, however not sure if is it belongs to this repo or should be posted for VS team? Thanks.

**Comment by SteveSandersonMS** [comment] 2020-10-20 14:30
> Sure lets post it to a new issue

Yes please, in this repo.

**Comment by RobertBouillon** [comment] 2020-10-25 18:34
Just a note that this breaks data binding scenarios:

1. User enters data into text field
2. User navigates away, causing field to be destroyed by DOM
3. Event fires, causing bug. User data is lost.

I haven't found a reliable workaround. Changing the `bind:event` to `oninput` works, but only when binding is appropriate for that event. A workaround for this would be great.

**Comment by Indrajith-Sync** [comment] 2020-10-27 10:57
I am also facing the same script issue.

Any workarounds for resolving this ?

**Comment by SteveSandersonMS** [comment] 2020-10-27 10:59
@RobertBouillon @Indrajith-Sync If you could each post separate issues with your own minimal repro steps, we can figure out whether it’s the same issue or not. Thanks!

**Comment by Stamo-Gochev** [comment] 2020-10-29 12:13
@SteveSandersonMS Can you clarify if a potential fix will be backported to the 3.x branch or will it be part of the upcoming [5.0.1](https://github.com/dotnet/aspnetcore/milestone/131) release only? I need to support both 3.x and 5.0, so this information will be helpful to me beforehand.

**Comment by SteveSandersonMS** [comment] 2020-10-29 13:46
We don't have a decision about that yet, however as a caution, please note that 3.2.0 is not an LTS release and hence doesn't come with support beyond (I think) February 2021. Developers using Blazor WebAssembly should upgrade to 5.0 before February 2021.

**Comment by Stamo-Gochev** [comment] 2020-10-29 14:38
You are probably referring to the [6.0-preview1](https://github.com/dotnet/aspnetcore/milestone/122) milestone targeting February 10, 2021 for an end date for wasm 3.2.0, but are any fixes for wasm going to be part of any of the [3.1.x](https://github.com/dotnet/aspnetcore/milestone/77) releases? As far as I understand, Blazor WebAssembly 3.2.0 is not considered to be connected with the [3.1 LTS](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) (ending on December 3, 2022), but I cannot find any official statement about that, am I correct?

**Comment by SteveSandersonMS** [comment] 2020-10-29 14:56
You can find out more about support policy and roadmap at https://dotnet.microsoft.com/platform/support/policy/dotnet-core. You are correct that 3.2.x is *not* part of the 3.1.x LTS release (in fact, that's why we gave it the 3.2.0 version originally).

**Comment by PrinceOliver** [comment] 2020-11-27 14:11
Can anyone confirm which release version, will this fix be included?

**Comment by RobertBouillon** [comment] 2020-11-27 15:18
@SteveSandersonMS I've failed to create a minimal repro thus far. I've put a couple hours into it. Every simple scenario I create seems to work, so I've been unable to isolate the exact problem here. I can provide you with access to the repo, if you'd like, otherwise I'll try and take another stab at this sometime this month by stripping away functionality until the problem disappears, rather than trying to recreate something simple.

**Comment by JPtenBerge** [comment] 2020-11-29 00:34
@RobertBouillon @SteveSandersonMS I've run into this error and managed to reproduce it with this bit of code:

	@page "/counter"

	<h1>Reproduce error</h1>

	ShowInput: @ShowInput

	<button @onclick="ToggleInput">Toggle input</button>

	@if (ShowInput)
	{
		<input @bind-value="SomeText"
			   @bind-value:event="oninput"
			   @onkeydown="HideIfEnter"
			   @onblur="HandleBlur">
	}
	else
	{
		<p>Not showing input</p>
	}

	@code {
		public bool ShowInput { get; set; } = true;

		public string SomeText { get; set; }

		public void ToggleInput()
		{
			ShowInput = !ShowInput;

			if (ShowInput)
			{
				Console.WriteLine("showing input, so focussing");
			}
		}

		public void HandleBlur()
		{
			Console.WriteLine("Blurring");
		}

		public void HideIfEnter(KeyboardEventArgs args)
		{
			if (args.Key == "Enter")
			{
				ShowInput = false;
			}
		}
	}

The problem lies in the combination where I have a blur and a keydown event handler on an input field. The keydown event handler effectively removes an input field from the DOM, causing the blur event to -kinda- get triggered, but it can't find its associated element anymore.

Hope this helps.

**Comment by SteveSandersonMS** [comment] 2020-11-30 14:08
Thanks for the clarification. Yes, I believe this is a duplicate repro of this issue (#26838). It's in "Next spring planning" so we'll be evaluating it for a possible fix in 5.0.2.

**Comment by Stamo-Gochev** [comment] 2021-01-25 14:59
Is there any chance the priority of this issue is raised as it didn't make it to 5.0.2 and it is getting tedious to implement workarounds again and again?

**Comment by ghostinside** [comment] 2021-03-02 20:32
just got recently

`Uncaught (in promise) Error: Assertion failed - heap is currently locked
    at g (blazor.webassembly.js:1)
    at Object.beginInvokeDotNetFromJS (blazor.webassembly.js:1)
    at h (blazor.webassembly.js:1)
    at e.invokeMethodAsync (blazor.webassembly.js:1)
    at e.value (telerik-blazor.js:1)
    at e.value (telerik-blazor.js:46)
    at HTMLLIElement.i.onFocusOut (telerik-blazor.js:46)
    at e (blazor.webassembly.js:1)
    at Object.e [as removeLogicalChild] (blazor.webassembly.js:1)
    at e.applyEdits (blazor.webassembly.js:1)
g @ blazor.webassembly.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
value @ telerik-blazor.js:1
value @ telerik-blazor.js:46
i.onFocusOut @ telerik-blazor.js:46
e @ blazor.webassembly.js:1
e @ blazor.webassembly.js:1
e.applyEdits @ blazor.webassembly.js:1
e.updateComponent @ blazor.webassembly.js:1
t.renderBatch @ blazor.webassembly.js:1
window.Blazor._internal.renderBatch @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
wasm_invoke_iiiiii @ 00aba242:0xdda7f
ves_pinvoke_method @ 00aba242:0xdfb62
interp_exec_method @ 00aba242:0x44c08
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_invoke_checked @ 00aba242:0xf65d
mono_runtime_try_invoke_array @ 00aba242:0x10e831
ves_icall_InternalInvoke @ 00aba242:0xed492
ves_icall_InternalInvoke_raw @ 00aba242:0xecf57
do_icall @ 00aba242:0x194ddb
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
d @ blazor.webassembly.js:1
f @ blazor.webassembly.js:1
l @ blazor.webassembly.js:1
invokeJSFromDotNet @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.3.js:1
do_icall @ 00aba242:0x194e4e
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_invoke_checked @ 00aba242:0xf65d
mono_runtime_try_invoke_array @ 00aba242:0x10e831
ves_icall_InternalInvoke @ 00aba242:0xed492
ves_icall_InternalInvoke_raw @ 00aba242:0xecf57
do_icall @ 00aba242:0x194ddb
do_icall_wrapper @ 00aba242:0x79df9
interp_exec_method @ 00aba242:0x44ad3
interp_runtime_invoke @ 00aba242:0x12efff
mono_jit_runtime_invoke @ 00aba242:0x118e5f
do_runtime_invoke @ 00aba242:0x79d42
mono_runtime_try_invoke @ 00aba242:0x12982
mono_runtime_invoke @ 00aba242:0x10ec2b
mono_wasm_invoke_method @ 00aba242:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.3.js:1
call_method @ dotnet.5.0.3.js:1
(anonymous) @ dotnet.5.0.3.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
value @ telerik-blazor.js:1
value @ telerik-blazor.js:46
i.onClick @ telerik-blazor.js:46
Show 55 more frames`

**Comment by ghostinside** [comment] 2021-03-02 20:34
@Stamo-Gochev

**Comment by angelru** [comment] 2021-03-29 19:09
The same issue when i submit a form with enter key:
Uncaught (in promise) Error: System.ArgumentException: There is no event handler associated with this event. EventId: '711'. (Parameter 'eventHandlerId')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo eventFieldInfo, EventArgs eventArgs)
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.DispatchEvent(WebEventDescriptor eventDescriptor, String eventArgsJson)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (http://localhost:56826/_framework/blazor.webassembly.js:1:4191)
    at Object.invokeJSFromDotNet (http://localhost:56826/_framework/blazor.webassembly.js:1:3797)
    at Object.w [as invokeJSFromDotNet] (http://localhost:56826/_framework/blazor.webassembly.js:1:64301)
    at _mono_wasm_invoke_js_blazor (http://localhost:56826/_framework/dotnet.5.0.4.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
    at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
    at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7347]:0x118e5f)
    at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d42)

**Closed** 2021-04-09 09:45 UTC
Labels: affected-medium, area-blazor, blazor-wasm, bug, severity-major
