### ISSUE TITLE
NullReferenceException in IISHTTPServer.OnDisconnect()

### ISSUE THREAD

**Issue by tmelent** [dotnet/aspnetcore#20908] opened 2020-03-25 19:20 UTC
Sometimes when I start my app, I get a NullReferenceException:
```
 System.NullReferenceException
   HResult=0x80004003
   Message = Object reference not set to an instance of an object.
   Source = Microsoft.AspNetCore.Server.IIS
   Stack trace:
 at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer.OnDisconnect(IntPtr pvManagedHttpContext)
 
```
Why does it happen? What should I do or where can I find some info about it?

**Comment by Tratcher** [comment] 2020-04-16 19:13
There are two active issues we're investigating here.
- #17516 has a similar call stack, but does not exactly match. 
- The other one matches this call stack but had to do with an IIS Express update.

What version are you hitting this on?

Do you hit it in IIS or IIS Express?

**Comment by anurse** [comment] 2020-04-17 19:51
I think the call stack differences might be inlining. I propose we treat this as a duplicate of #17516 for now, but we can confirm in triage today.

**Closed** 2020-04-17 20:07 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers, servers-iis
