### ISSUE TITLE
Blazor Webassembly Signlar connection to Azure SignalR service via Funcations App fails to pass authorization token

### ISSUE THREAD

**Issue by simon-flanagan** [dotnet/aspnetcore#21399] opened 2020-05-01 14:16 UTC
Trying to connect to the Azure SignalR service through a Function App 'negotiate' endpoint using Blazor Webassembly fails. Using a .net core 3 console app is able to connect successfully.

The part of the process that appears to fail is the switch to websockets - the Azure SignalR server returns 401-Unauthorized. Comparing requests from the console and blazor apps shows that the authorization header is missing from this request:

```
GET https://<signalrResourceUrl>/client/?hub=test&id=QU...
HTTP/1.1
Host: <signalrResourceUrl>
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
Upgrade: websocket
Origin: http://localhost:62030
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Sec-WebSocket-Key: K28d...
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
```

The request from the console app for the same stage of the process:

```
GET https://<signalrResourceUrl>/client/hub=test&id=HPY... 
HTTP/1.1
Host: <signalrResourceUrl>
X-Requested-With: XMLHttpRequest
Authorization: Bearer eyJhb....Gcifi3oI
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 3vekB...

```

The functions app is as in [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-input?tabs=csharp](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-signalr-service-input?tabs=csharp)

In both console and blazor apps the connection is established using:

```
HubConnection connection = new HubConnectionBuilder()
.WithUrl("http://localhost:7071/api/")
.WithAutomaticReconnect()
.Build();
await connection.StartAsync();
```

Client package versions: 
- Microsoft.AspNetCore.Components.Webassembly.*: 3.2.0-rc1.20223.4
- Microsoft.AspNetCore.SignalR.Client: 3.1.3

Function app package versions:
- Microsoft.NET.Sdk.Functions: 3.0.3
- Microsoft.Azure.WebJobs.Extensions.SignalRService: 1.1.0

**Comment by anurse** [comment] 2020-05-01 19:45
Looks like a duplicate of https://github.com/dotnet/aspnetcore/issues/18697 which will be fixed in 3.1.4.

**Closed by anurse** 2020-05-01 19:45 UTC
Labels: area-signalr
