### ISSUE TITLE
Quarantine EnableCoreHostTraceLogging_FileCaptureNativeLogs

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#42820] opened 2022-07-19 19:38 UTC
## Failing Test(s)

- `StdOutRedirectionTests.EnableCoreHostTraceLogging_FileCaptureNativeLogs`

## Error Message

```text
System.AggregateException : Operation did not succeed after 15 retries (Site is started but no worker process found) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot)
---- System.InvalidOperationException : Site is started but no worker process found
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwB43F0A02	4d2a5d77e9ac4b4884a584d817e54eee Actual: %SystemDrive%inetpubwwwroot

   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.WaitUntilSiteStarted(String contentRoot) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 281
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.StartIIS(Uri uri, String contentRoot) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 220
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 120
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.DeployAsync(IISDeploymentParameters parameters) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/FunctionalTestsBase.cs:line 48
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.RunTest(IISDeploymentParameters deploymentParameters, Action`1 testCode) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/FunctionalTestsBase.cs:line 42
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.StdOutRedirectionTests.EnableCoreHostTraceLogging_FileCaptureNativeLogs(String path) in /_/src/Servers/IIS/IIS/test/IIS.Shared.FunctionalTests/StdOutRedirectionTests.cs:line 149
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #2 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #3 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #4 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #5 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #6 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #7 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #8 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #9 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #10 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #11 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #12 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #13 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #14 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #15 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
```

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1888898&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=1889148&view=results

**Comment by dougbu** [comment] 2022-07-19 20:27
Same root cause as #42658

**Comment by JamesNK** [comment] 2022-07-26 07:56
Add https://github.com/dotnet/aspnetcore/issues/42913 to the collection.

**Comment by HaoK** [comment] 2022-09-22 03:02
Looks Fixed by reverting the dispose change to the IIS functionals

**Closed** 2022-09-22 23:54 UTC
Labels: test-failure, area-runtime, test-fixed
