### ISSUE TITLE
Open IBrowserFile.OpenReadStream() for two different InputFiles leads to timeout

### ISSUE THREAD

**Issue by oiBio** [dotnet/aspnetcore#43112] opened 2022-08-05 13:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a blazor server page with two <InputFile> components.
On click on the "submit" Button we create two Stream variables with OpenReadStream() and send them to the backend to get proceeded. 

In the backend we want to read the stream and get stuck on a time out "System.TimeoutException: Did not receive any data in the allotted time."

### Expected Behavior

I know this code worked in the past. Would be great if this would work again - without a time out - but i would at least excpect an compiler warning/error.

When i proceed the the stream before the second OpenReadStream() (from another file) is called, everything goes fine. As you can see in the attached example code.

### Steps To Reproduce

Create new Blazor Server Template and replace index.razor with the code.

Select two different files (less than 500kb) and hit "Start Upload".
You will get the time out.
Repeat this and press "Start Upload (Working)" to get it working with a slightly different approach.

```razor
@page "/"

<PageTitle>Index</PageTitle>

<div>
    Pick two files (less than 500kb) and press Start Upload... You will get an Timeout!
</div>


<InputFile OnChange="File1">Pick File 1</InputFile>
<InputFile OnChange="File2">Pick File 2</InputFile>


<button @onclick="StartUpload">
    Start Upload (will time out)
</button>
<button @onclick="StartUpload_Working">
    Start Upload (working)
</button>


@code{
    IBrowserFile? _file1;
    IBrowserFile? _file2;

    private void File1(InputFileChangeEventArgs  obj)
    {
        _file1 = obj.File;
    }

    private void File2(InputFileChangeEventArgs obj)
    {
        _file2 = obj.File;
    }

    private async Task StartUpload()
    {
        if (_file1 == null || _file2 == null)
            return;

        var stream1 = _file1.OpenReadStream();
        var stream2 = _file2.OpenReadStream();
        
        // Read stream (ie, convert to MemoryStream) after two IBrowserFiles are open
        var ms1 = await ToMemoryStreamAsync(stream1);      // Does not Work... Timeout
        // You will never arrive at this line
        var ms2 = await ToMemoryStreamAsync(stream2);
    }
    
    
    
    private async Task StartUpload_Working()
    {
        if (_file1 == null || _file2 == null)
            return;

        var stream1 = _file1.OpenReadStream();
        var ms1 = await ToMemoryStreamAsync(stream1);
        var stream2 = _file2.OpenReadStream();
        var ms2 = await ToMemoryStreamAsync(stream2);
    }
    
    async Task<MemoryStream> ToMemoryStreamAsync(Stream stream)
    {
        var memoryStream = new MemoryStream();
        await stream.CopyToAsync(memoryStream);
        memoryStream.Position = 0;
        return memoryStream;
    }
    
}
```

### Exceptions (if any)

```
blazor.server.js:1 [2022-08-05T12:54:43.199Z] Error: System.TimeoutException: Did not receive any data in the allotted time.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.IO.Pipelines.PipeReaderStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.CopyFileDataIntoBuffer(Int64 sourceOffset, Memory`1 destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
```

### .NET Version

NET6

**Comment by TanayParikh** [comment] 2022-08-05 20:27
Hey @oiBio, I just tried repro'ing the app (and added a brief message line at the end). I'm not able to repro the timeout exception you're seeing. If you're still experiencing this issue, can you please provide a minimal, public, github repro for this issue? Which exact version of the .NET 6 SDK are you using (`dotnet --version`).

https://user-images.githubusercontent.com/14852843/183157546-a1a75789-dbf4-447c-af2b-f5c538866ec3.mov

Full repro:

<details>

```razor
@page "/"

<PageTitle>Index</PageTitle>

<div>
    Pick two files (less than 500kb) and press Start Upload... You will get an Timeout!
</div>


<InputFile OnChange="File1">Pick File 1</InputFile>
<InputFile OnChange="File2">Pick File 2</InputFile>


<button @onclick="StartUpload">
    Start Upload (will time out)
</button>
<button @onclick="StartUpload_Working">
    Start Upload (working)
</button>

@Message

@code{
    IBrowserFile? _file1;
    IBrowserFile? _file2;

    string Message {get;set;} = "";

    private void File1(InputFileChangeEventArgs  obj)
    {
        _file1 = obj.File;
    }

    private void File2(InputFileChangeEventArgs obj)
    {
        _file2 = obj.File;
    }

    private async Task StartUpload()
    {
        if (_file1 == null || _file2 == null)
            return;

        Message = "Uploading...";
        var stream1 = _file1.OpenReadStream();
        var stream2 = _file2.OpenReadStream();
        
        // Read stream (ie, convert to MemoryStream) after two IBrowserFiles are open
        var ms1 = await ToMemoryStreamAsync(stream1);      // Does not Work... Timeout
        Message = "Stream1: " + ms1.Length;
        // You will never arrive at this line
        var ms2 = await ToMemoryStreamAsync(stream2);
        Message += "Stream2: " + ms2.Length;
    }
    
    
    
    private async Task StartUpload_Working()
    {
        if (_file1 == null || _file2 == null)
            return;

        Message = "Uploading...";
        var stream1 = _file1.OpenReadStream();
        var ms1 = await ToMemoryStreamAsync(stream1);
        Message = "Stream1: " + ms1.Length;
        var stream2 = _file2.OpenReadStream();
        var ms2 = await ToMemoryStreamAsync(stream2);
        Message += "Stream2: " + ms2.Length;
    }
    
    async Task<MemoryStream> ToMemoryStreamAsync(Stream stream)
    {
        var memoryStream = new MemoryStream();
        await stream.CopyToAsync(memoryStream);
        memoryStream.Position = 0;
        return memoryStream;
    }
    
}
```

</details>

**Comment by oiBio** [comment] 2022-08-06 08:08
Hello Tanay,
thank you for your response. 
https://github.com/oiBio/BlazorServer_FileInputBug

The project itself is net6 (see csproj)

```
dotnet --version
7.0.100-preview.6.22352.1

dotnet --list-sdks
3.1.200-preview-014977 [C:\Program Files\dotnet\sdk]
3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]
3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]
3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.201 [C:\Program Files\dotnet\sdk]
5.0.301 [C:\Program Files\dotnet\sdk]
5.0.404 [C:\Program Files\dotnet\sdk]
6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]
6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.301 [C:\Program Files\dotnet\sdk]
6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]
7.0.100-preview.6.22352.1 [C:\Program Files\dotnet\sdk]
```

**Comment by Bluejanis** [comment] 2022-10-06 15:19
I am experiencing this error as well.
After some time looking into it, I noticed that this error does depend on the file size:
With very small files (200kb) this will work without any errors, but even 400kb files seem to trigger this bug.

**Comment by TanayParikh** [comment] 2022-10-06 17:15
Hey, thanks for reaching out. I'm closing this out as a duplicate of https://github.com/dotnet/aspnetcore/issues/38842.

**Closed by TanayParikh** 2022-10-06 17:15 UTC
Labels: investigate, area-blazor, feature-blazor-jsinterop, blazor-server
