### ISSUE TITLE
CS8103: combined length of user strings used by the program exceeds allowed limit

### ISSUE THREAD

**Issue by gr8tushar** [dotnet/aspnetcore#21788] opened 2020-05-13 16:57 UTC
This is related to issue #20224.

I have tried Visual Studio Pro 2019 (16.5.5) and .NET Core 3.1
`
As soon as I add few Views to an ASP.NET Core project, the build fails.

Its strange that no enterprise has reported this. I fail to understand how can an enterprise product be migrated to .NET Core if this issue is not resolved.
Having few hundred views in a enterprise project is a very common scenario.

I have started feeling that .NET Core is more of a playing ground for Microsoft. It's not meant or mature enough for enterprise development.

**Comment by mkArtakMSFT** [comment] 2020-05-15 17:45
This is a dupe of https://github.com/dotnet/aspnetcore/issues/21787

**Closed by mkArtakMSFT** 2020-05-15 17:45 UTC
Labels: area-mvc, enhancement

**Comment by gr8tushar** [comment] 2020-05-16 05:17
@mkArtakMSFT - Since you have closed this issue. 
Can you please move #21787 to [Next sprint planning](https://github.com/dotnet/aspnetcore/milestone/88)

**Comment by mkArtakMSFT** [comment] 2020-05-17 01:16
@gr8tushar we're still trying to find out where that should go. So not yet.
