### ISSUE TITLE
Unintended localization for DateTime strings

### ISSUE THREAD

**Issue by danzhu54** [dotnet/aspnetcore#56053] opened 2024-06-03 22:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We're seeing unintentional localization occuring on the marketing site. On the Blazor project, we do not have localization enabled.

The code that is causing this issue is [here](https://github.com/dotnet/website/blob/263b62768fa57565963c7d5befad1afcf2f16e6a/src/netlandingpage.Clients/netlive/Shared/Schedule.razor#L131):
`show.LocalScheduledStartTime?.ToString("hh:mmtt")`

It appears that converting a DateTime to a string is automatically also taking browser locale into consideration even though we do not have it enabled in our `Program.cs` [file](https://github.com/dotnet/website/blob/main/src/netlandingpage.Clients/netlive/Program.cs)

### Expected Behavior

The DateTime toString method should not automatically convert DateTimes to the browser locale when localization is not enabled on the project.

### Steps To Reproduce

Repo steps:
1. Set default browser language to Japanese
2. Navigate to [https://dotnet.microsoft.com/live](https://dotnet.microsoft.com/live)
3. Scroll to the bottom of the page and select `English (United States)` in the footer dropdown
4. Observe the page is still displaying the dates and times in Japanese

### .NET Version

8.0

**Comment by javiercn** [comment] 2024-06-04 16:21
@danzhu54 thanks for contacting us.

I think that if you have a different locale you need to set up that locale when the webassembly process starts in `Program.cs` on Thread.CurrentThread.UICulture and so on

**Comment by danzhu54** [comment] 2024-06-06 18:00
Thanks @javiercn that resolved the issue for us. However, I feel like it's not intutive to require setting this value by default. This behavior creates an inconsistent experience for a user visiting for example an english only site by having a mixture of english text and DateTime elements rendered into their browser locale.

**Comment by javiercn** [comment] 2024-06-07 07:31
@danzhu54 thanks for the additional details.

We have an item on the backlog to flow the culture from the server to webassembly and use that.

https://github.com/dotnet/aspnetcore/issues/26941

Closing this as a dupe of it.

**Closed by javiercn** 2024-06-07 07:31 UTC
Labels: area-blazor, Needs: Attention :wave:
