### ISSUE TITLE
Responsive Menu Control for Blazor in .NET 6

### ISSUE THREAD

**Issue by rodmac1** [dotnet/aspnetcore#26917] opened 2020-10-15 01:28 UTC
PROBLEM
I believe there’s a big gap 3rd party control vendors are struggling to fill e.g. there’s a need for a responsive menu control which is vertical on mobile and horizontal on desktop. I’ve found it a struggle altering Blazor’s menu and looking at StackOverflow, I’m not alone. Currently the 3rd party control vendors are fixed on things like grids for the finance industry. This one’s pretty essential to get devs started on creating intuitive and responsive apps that work both for mobile (vertical) and desktop (horizontal).

SOLUTION
MS need to create a multi-level and or templated menu control in .NET 6.

**Comment by mkArtakMSFT** [comment] 2020-10-15 16:35
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/11229

**Closed by mkArtakMSFT** 2020-10-15 16:35 UTC
Labels: area-blazor

**Comment by rodmac1** [comment] 2020-10-15 17:04
Artak, I went to the FluentUI website and I don't see anything about Blazor controls or MAUI. Am I missing something or have you just killed what should be MS's most important project? ;-) Rod
