### ISSUE TITLE
.Net Core Web API shows inexplicable behavior with Swagger UI and If-None-Match header

### ISSUE THREAD

**Issue by KillerBoogie** [dotnet/aspnetcore#40374] opened 2022-02-23 13:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bug is twofold. The issues seem to be connected. 

1) A method for `HttpGet ` uses If-None-Match header.  When I execute the GET in Swagger UI with an empty If-None-Macth header the response is returned in the body and the the ETag in the ETag header. When I just execute again the header parameter in the method is filled with the ETag value that was returned in the first execution, despite that the If-None-Match header field in Swagger UI was still empty. Also the curl section does not show an If-None-Match or other extra header. It seems that either the browser or Swagger UI changes the call, which is wired and unexpected.

2) For the resonse the calculated ETag is compared with the ETags from the If-None-Match header. If they match a 304 Not Modified http code is returned. Since the ETag from the first call was provided in the second call, isMatch is true and the method ends returning the 304 StatusCode. Surprisingly, Swagger UI does not(!) display code 304, but 200 with the body.

If I enter the ETag in the If-Non-Match header field in Swagger UI and execute, the code in the GET method takes the exact same path. The match is true and the method returns Status304NotModified. This time Swagger UI displays code 304 Not Modified!

### Expected Behavior

1) When a http call is made with an empty If-None-Match header the header parameter should be null.
2) When `StatusCode(StatusCodes.Status304NotModified)` is called a 304 response must be sent and not a 200.

### Steps To Reproduce

**Web API groups controller method**

```
[HttpGet]
[Route("")]
public ActionResult<List<GetGroupsDTO>> GetGroups([FromHeader(Name = "If-None-Match")] string? eTags, Guid? accountId, ...)
{
...
  if (eTagIsMatch) 
  {
     return StatusCode(StatusCodes.Status304NotModified);
  } 
  else 
  {
     return OK(List<groupDTO>)
  }
}
```

**Step 1: Execute in Swagger UI** 

```
curl -X 'GET' \
  'https://localhost:44356/api/groups' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer  xxxxx'
```

Visual Studio:
Debugging shows that the header variable `eTags is null`.
Therefore `eTagIsMatch is false `and `OK(List<groupDTO>)` is executed.

The response HTTP code is `200 OK`. The data is in the body. The returned headers are:

```
content-type: application/json; charset=utf-8  
date: Wed,23 Feb 2022 13:16:52 GMT  
etag: "38815511"  
server: Microsoft-IIS/10.0  
x-firefox-spdy: h2 
```

**Step 2: Execute again without changes**

curl is identical.

Visual Studio:
Debugging shows that the header variable `eTags == "38815511`.
Therefore `eTagIsMatch is true `and the line
     ` return StatusCode(StatusCodes.Status304NotModified);`
is executed.

Despite Status304NotModified is executed the response is identical to step 1 and leads to `200 OK `with data in the body. The returned headers are identically (except time).

```
content-type: application/json; charset=utf-8  
date: Wed,23 Feb 2022 13:17:24 GMT  
etag: "38815511"  
server: Microsoft-IIS/10.0  
x-firefox-spdy: h2 
```

**Step 3: Execute with ETag in If-None-Match header field**

```
curl -X 'GET' \
  'https://localhost:44356/api/groups' \
  -H 'accept: application/json' \
  -H 'If-None-Match: "38815511"' \
  -H 'Authorization: Bearer xxxxx'
```

Visual Studio:
Debugging shows that the header variable `eTags == "38815511"`.
Therefore `eTagIsMatch is true `and again the line
     ` return StatusCode(StatusCodes.Status304NotModified);`
is executed.

This time the response is `304 Not Modified`. The returned headers are:

```
date: Wed,23 Feb 2022 13:24:45 GMT 
server: Microsoft-IIS/10.0  
x-firefox-spdy: h2 
```

### .NET Version

6.0.101

### Anything else?

net6.0
Visual Studio version 17.0.5
Swashbuckle.AspNetCore 6.2.3
FireFox 97

**Comment by KillerBoogie** [comment] 2022-02-26 15:36
I tested the calls with Postman. Here the code works as expected. It must be a bug in Swashbuckle how it modifies the pipeline. Still don't know the cause. 
For Swagger UI its is servere bug because the API returns not the expected correct information making a user believe the API is faulty.

**Comment by rafikiassumani-msft** [comment] 2022-03-04 00:22
@KillerBoogie  Thanks for doing additional testing. We will close the issue since this is not a bug in ASPNET core. Do you mind creating an issue in the Swahsbuckle repository?

**Closed by rafikiassumani-msft** 2022-03-04 00:22 UTC
Labels: investigate, area-web-frameworks
