### ISSUE TITLE
[Blazor] Add support for TimeSpan to BindConverter

### ISSUE THREAD

**Issue by mathisloge** [dotnet/aspnetcore#17898] opened 2019-12-15 18:11 UTC
### Describe the bug
Before the update to version 3.1.0, I can use `<input type="time" @bind-value="@MyTimespan"/> `after the update, it fails with the error "cannot convert from 'System.TimeSpan' to 'System.DateTime' "

I dont quiet understand, why you have removed this type of usage.

### To Reproduce
https://blazorfiddle.com/s/uk47jfsz

### Further technical details
Functional:
v3.0.0
Not functional:
v3.1.0

**Comment by mkArtakMSFT** [comment] 2019-12-16 17:16
Thanks for contacting us, @mathisloge.
@pranavkm can you please look into this. In case this turns out to be real bug with no workarounds, we may need to patch this.

**Comment by adugasBID** [comment] 2019-12-20 14:18
I'm in the same situation as him.

It gives the error "cannot convert from 'System.TimeSpan' to 'System.DateTime'" inside the .razor (same error as him) AND it will give the error "cannot implicitly convert type 'System.DateTimeOffset?' to 'System.TimeSpan'" inside the .razor.g.cs

I'd like to point out this is in no way an "offset" to a datetime, this is just a time field. There is no notion of "date" here.

**Comment by mathisloge** [comment] 2019-12-20 15:55
Can confirm the second error message. Forgot about that.

**Comment by julienGrd** [comment] 2020-01-06 20:01
I can confirm, and the problem is if we bind on a datetime property, and on the other way we bind the same datetime on a custom component who manage the date part, the two bindings are in conflict and the input time crush the value with the old date.

Do you have a workaround for that ?

**Comment by mathisloge** [comment] 2020-01-17 21:25
Is there some progress and/or updates on this one?

**Comment by julienGrd** [comment] 2020-03-03 15:30
Hello guys, i'm worried about the milestone of this issue (5.0 preview).
I work on blazor at full time since one year by migrating an old silverlight app to blazor webassembly.
I'm suppose to deploy in production in may/june, i repeat this to my company since I know when webassembly will be production ready.
Actually my app not work at all on input time and i definitively can't wait the .net 5 to put my app in production. 
Please provide at least a workaround to make the input time usable, or consider correct it for a closest milestone

thank you very much !

**Comment by adugasBID** [comment] 2020-03-03 17:59
It would be nice to see some progress on this because we cannot migrate to 3.1 until this is fixed.

**Comment by pranavkm** [comment] 2020-04-29 17:20
Support for TimeSpan is missing in `BindConverter`. It attempts to do an implicit cast to `DateTime` which results in the spooky error. We would need add support for this as part of 5.0. @SteveSandersonMS \ @javiercn isn't there a way users could author a BindConverter \ EventCallback factories to workaround this in the meanwhile?

**Comment by mathisloge** [comment] 2020-04-29 18:07
@pranavkm Just as a side question:
What have changed between 3.0 and 3.1? Because in 3.0 the example given above was functional.

**Comment by pranavkm** [comment] 2020-04-29 23:33
@mathisloge not entirely sure. The API at the callsite hasn't changed since before 3.0 RTMed.

**Comment by adugasBID** [comment] 2020-06-03 16:46
Can somebody fix the title? It really sounds weirder/trickier than it really is.
"TimeZone" should be "TimeSpan".

**Comment by MackinnonBuck** [comment] 2022-10-18 23:01
We now support binding to `TimeOnly`, which is more appropriate than `TimeSpan` for `type="time"` inputs. Closing this out.

**Closed by MackinnonBuck** 2022-10-18 23:01 UTC
Labels: enhancement, area-blazor, triaged, severity-nice-to-have, affected-few, feature-blazor-component-model
