### ISSUE TITLE
Create BlazorWebAssemblyApp 5.0/3.1 project in M1 machine and use the command "dotnet run", meet error:"Unhandled exception".

### ISSUE THREAD

**Issue by v-wenkecheng** [dotnet/aspnetcore#39397] opened 2022-01-10 06:12 UTC
**Azure DevOps work item**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1426314

**INSTALL STEPS**
Install 6.0 arm64 Dec Servicing: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Install 5.0 x64 Dec Servicing: https://dotnet.microsoft.com/en-us/download/dotnet/5.0
Install 3.1 x64 Dec Servicing: https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Testcases Affected**
[[5.0/3.1]BlazorWebAssemblyWithPWANoAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore30/3x_BlazorWebAssemblyWithPWANoAuth.md)
[[5.0/3.1]SignalRWithBlazorWebAssembly](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore30/3x_SignalRWithBlazorWebAssembly_Mac.md)

**Platform**
  
- [ ] Windows
- [x] macOS
- [ ] Linux

**Repro Steps**
Due to bug [1429653](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1429653), We cannot create 5.0/3.1 projects with VS, only can create project with command line.
1. /usr/local/share/dotnet/x64/dotnet new blazorwasm --pwa -f net5.0  -o BlazorWebAssemblyApp50
2. cd BlazorWebAssemblyApp50
3. dotnet run.

**Note**: If use command "/usr/local/share/dotnet/x64/dotnet run"(Tried with the command line using the 5.0 SDK), this issue doesn't repro, can run successfully and can open correct page.

**Actual Result**
Using the command "dotnet run", we meet the following error:
![image](https://user-images.githubusercontent.com/69494255/148723639-4aca5d33-458c-46ed-9b9e-d8543c4afbed.png)

**EXPECTED**
Run(F5) successfully without any error.

**Comment by javiercn** [comment] 2022-01-10 14:56
From the error, it seems that the 6.0 runtime is being used to run the application (which shouldn't be the case) as its trying to load the 6.0 manifest and that code only exists in .NET 6.0

**Comment by v-wenkecheng** [comment] 2022-01-20 06:07
Hi @javiercn 
- Create BlazorWebAssemblyApp 6.0 project in M1 machine and use the command "dotnet build/bl", As shown below:
  ![image](https://user-images.githubusercontent.com/69494255/150265605-a62c0d4a-6cde-4dde-8cd1-8d3cf86e1621.png)
 After running the command "dotnet build /bl", the msbuild.binlog file will be created.The attachment has been uploaded, as follows:
 [msbuild.binlog.zip](https://github.com/dotnet/aspnetcore/files/7902071/msbuild.binlog.zip)

- The repro steps below are our simplest steps.

1.   /usr/local/share/dotnet/x64/dotnet new blazorwasm --pwa -f net5.0 -o BlazorWebAssemblyApp50
2.   cd BlazorWebAssemblyApp50
3.  dotnet run.

- In the terminal, run the "dotnet --info" command, only see the 6.0 SDK. If run the "/usr/local/share/dotnet/x64/dotnet --info", we will see the SDK5.0/3.1. As shown below:
![image](https://user-images.githubusercontent.com/69494255/150271953-edd74861-353c-49f4-8e8e-f90ca778ed98.png)

- We only have M1 x64 machines so can't verify x86.

We do not have permission to open this issue, please help to open it, thank you！

**Comment by javiercn** [comment] 2022-01-20 11:46
I added some info on the VSTS issue, but here are additional comments

```
I took a look and it seems to be an issue on the setup environment. It's not clear to me why this is happening, but it seems that the 3.1 app is trying to run with the .NET 6.0 runtime. I don't understand why the runtime is not blocking the roll forward to 6.0 from 5.0, but that seems to be the root cause of the issue.

I'm not 100% clear on how we can confirm this is the case. I imagine you can modify the app to print the runtime version or capture a dump of the process with dotnet-dump in order to analyze the dlls loaded in memory.
```

**Comment by javiercn** [comment] 2022-01-24 12:03
Closing as the behavior is by design as mentioned in the VSTS issue.

Rolling the runtime forward across major versions of the framework its not expected to work.

**Closed by javiercn** 2022-01-24 12:03 UTC
Labels: Needs: Author Feedback, area-blazor, blazor-wasm, Status: No Recent Activity, feature-static-web-assets, feature-razor-sdk
