### ISSUE TITLE
Identity override error in Blazor WebAssembly

### ISSUE THREAD

**Issue by bessobesso** [dotnet/aspnetcore#22306] opened 2020-05-28 15:25 UTC
In Blazor WebAssembly there is an issue when overriding Identity UI. After you add Identity as scaffolded item, you get the exception when running the application:

InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Pages/Shared/_Layout.cshtml': 'Scripts'. To ignore an unrendered section call IgnoreSection("sectionName").

**Comment by blowdart** [comment] 2020-05-28 16:42
Closing as dupe of https://github.com/dotnet/aspnetcore/issues/22058

**Closed by blowdart** 2020-05-28 16:42 UTC
