### ISSUE TITLE
Update template localization strategy in repo

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#38102] opened 2021-11-05 00:55 UTC
Derived from https://github.com/dotnet/aspnetcore/pull/38062#issuecomment-961208415.

Our current localization strategy for templates in the repo is outdated and requires copying generated assets from VS. .NET 6 and 7 introduce a new approach for localizing template values.

> Starting .NET 7, we have an [MSBuild task](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet7&package=Microsoft.TemplateEngine.Tasks&protocolType=NuGet&version=7.0.100-alpha.1.21554.1) to ease this process. This should be the way going forward. But since this PR is about .NET 6, I won't give details here. Let me know if you need to apply this to main branch and I can help you further.
> 
> Starting .NET 6, we have Template Localizer tool to help with this. You should:
> - Clone the repo to your local machine and create a branch for your changes
> - Install the TemplateLocalizer tool
> - Run the tool on your template folder (this will generate all the loc files on disk).
> - Commit and push the changes to the repo, then merge.
> - Loc team will automatically receive the loc files and provide the translations in a later PR.
> 
> You can install Template Localizer tool using:
> ```dotnetcli
> dotnet tool install -g Microsoft.TemplateEngine.TemplateLocalizer
> ```
> 
> Run it on the root template directory using:
> ```dotnetcli
> dotnet-template-localizer export <path_to_root_template_directory> --recursive
> ```

**Comment by vlada-shubina** [comment] 2021-11-05 10:04
Duplicate of https://github.com/dotnet/aspnetcore/issues/34412 - see more guidance in this issue.

**Closed** 2021-11-07 19:40 UTC
Labels: task, area-infrastructure, feature-templates
