### ISSUE TITLE
Possible account enumeration in reset password

### ISSUE THREAD

**Issue by jaoord** [dotnet/aspnetcore#54653] opened 2024-03-20 21:59 UTC
https://github.com/dotnet/aspnetcore/blob/38b8d1c392ca3581a070ec380e3f64d9275b296e/src/Identity/UI/src/Areas/Identity/Pages/V5/Account/ResetPassword.cshtml.cs#L126

this allows for account enumeration if the user enters an email that isn’t their own. They will receive an error that the code is invalid, which in a way is true because it was meant for their own email. But it basically means an account exists with this email address

**Comment by blowdart** [comment] 2024-03-28 23:41
Dupe of #44703.

What it boils down to is you can do the same via the registration form, if usernames are email addresses (which they are by default), so this isn't anything extra in that regard.

**Closed** 2024-03-29 00:26 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-identity
