### ISSUE TITLE
Blazor Server-Side Memory Leak

### ISSUE THREAD

**Issue by DapperMickie** [dotnet/aspnetcore#18556] opened 2020-01-24 13:12 UTC
### Describe the bug
We host our Blazor site in a Kubernetes cluster and noticed that after a while it crashed due to an OutOfMemory exception. We came to the conclusion that we might just have to increase the allocated memory for our app but before we actually went through with that we went to the profiler.

![image](https://user-images.githubusercontent.com/10809203/73071619-87678d00-3eb3-11ea-8970-91f4d472a689.png)

We noticed that every time we refresh the page or go to a new page and come back more memory is allocated but none is removed. We then force a garbage collection and it still doesn't go down. We thought that perhaps we aren't disposing of our DbContext but we are. Since the increase is in unmanaged memory we can't easily find out what it is but we assume it is some issue with Blazor itself. The reason we think this is because if we create a brand new Blazor template project and profile whilst refreshing we get the same issue. 

### To Reproduce
1. Create a new Blazor Server-Side project using the template
2. Run the app and attatch a profiler to it
3. Keep refreshing the page and watch the memory increase
4. Force a garbage collection and watch the memory not decrease

### Further technical details
- ASP.NET Core 3.1.1 (Also tested with 3.0)
- VS 2019

**Comment by javiercn** [comment] 2020-01-24 13:51
@DapperMickie thanks for contacting us.

I believe we need more information to analyze your case. 

Can you take a memory dump of the running process and take a look at the list of objects in memory that are taking more space and have the highest object count?

**Comment by mkArtakMSFT** [comment] 2020-01-24 17:21
@DapperMickie, can you please answer these questions to help us investigate this further:
- how long did it take for you to get to this state?
- what happens if you reserve more memory to the container?
- will it eventually outgrow a 1024Mb (as an example) too?
- can you actually reproduce this issue locally (not in a container), having the profiler attached?

**Comment by DapperMickie** [comment] 2020-01-24 17:55
@mkArtakMSFT 
how long did it take for you to get to this state? - The state in the above image took roughly 20 seconds.
can you actually reproduce this issue locally (not in a container), having the profiler attached? - That's what the above image is from.
also, how many refreshes, approximately, did it take to get to this state? - Roughly 20-30

Do you get the issue when you test it with the steps above?

Thanks for any help in advance :)

**Comment by mkArtakMSFT** [comment] 2020-01-27 17:45
@DapperMickie here what's going on:
- On every refresh a new circuit is being created by Blazor
- Note: Blazor holds on to existing circuits (max 3 minutes) in case the client reconnects later.
- Blazor holds on to up to 100 circuits max
- Because of this, Garbage Collection doesn't clean up the existing circuits and with every refresh your app's memory grows slightly.
- Eventually, due to some restrictions on your cluster / container your app runs out of memory when trying to create a new circuit and that results in the error you see observe.

Hope this helps to clarify what's going on and why you're seeing the error.

**Comment by mkArtakMSFT** [comment] 2020-01-27 17:47
One thing which is interesting is what's your cluster/container configuration? How much available memory does it have when you start your test?

**Comment by astevens8182** [comment] 2020-05-19 14:22
I believe I am having a similar memory leak issue. In my server side Blazor app, After launch, I will click on a few pages then go back to the main home page (which has only text) and then just let the app sit for while. When I come back the memory usage has gone up a considerable amount (about 1.mb a min). Any solutions for this issue?

**Comment by javiercn** [comment] 2020-05-19 14:45
> I believe I am having a similar memory leak issue. In my server side Blazor app, After launch, I will click on a few pages then go back to the main home page (which has only text) and then just let the app sit for while. When I come back the memory usage has gone up a considerable amount (about 1.mb a min). Any solutions for this issue?

Can you please file a separate issue to avoid mixing different concerns?

**Comment by astevens8182** [comment] 2020-05-19 15:10
@javiercn  I believe it is the same issue that was originally describe in the top of the issue?

**Comment by javiercn** [comment] 2020-05-19 15:22
@astevens8182 Having a separate issue makes it easier for as to deal with your specific case. 

Please file a separate issue and provide a minimal repro project as well as information indicating why you think there is a memory leak, what your expectation is, what actual behavior you are observing and how are you running the app and measuring this.

**Comment by csockman** [comment] 2020-06-27 23:03
Microsoft Visual Studio Professional 2019 / Version 16.6.2
.NET Core SDK 3.1.301 (x64)
Google Chrome / Version 83.0.4103.116 (Official Build) (64-bit)

Steps to reproduce
1) Start VS 2019 => File => New => Project (create a Blazor Server application).
2) Once the project has been created => Ctrl + Shift + B.
3) Debug => Start Debugging (use IIS Express/Chrome).
4) Bring up Task Manager and find the instance of Chrome that is servicing the Blazor Server application. Note the RAM usage.
5) Navigate to "Fetch data" from the navigation menu in the running application.
6) Hit F5, calling "Fetch data" repeatedly, until your memory footprint hits about 100 MB (or go higher if you are an achiever).
7) Walk away for an hour, come back, and note that GC has reclaimed some RAM, but it still is consuming much more RAM than when you started in Step 4 above (~12 MB RAM). IIS Express is coming back down to ~55 MB RAM (Debug mode)/~33 MB RAM (Release mode), Kestrel is coming back down to ~33 MB RAM (Release mode), and IIS is coming back down to ~33 MB (Release mode).

Alternatively, if you don't like hitting F5, spend about 5 minutes and build up RAM usage by alternating between Home, Counter, and Fetch Data. Then wait until you think GC should have come through and reclaimed your RAM. You will find that it doesn't, and I find that this method will actually make the memory leak worse.

Is this a SignalR memory leak that I am witnessing here?

**Comment by javiercn** [comment] 2020-06-29 13:37
@csockman thanks for contacting us.

I'm glad you were able to troubleshoot the issue. Client-side there can't be any memory leak in the app after you press F5 since that destroys the entire app. (As you pointed out, if you were to do that, it would be an issue on the Browser or any extension there).

On the server-side, as explained above memory will grow up until there is no more memory available, at which point the GC will run. If you were to spam the server as much as you could to create new circuits old (disconnected) circuits will be released and GC'ed.

We will only hold a maximum number of disconnected circuits in memory at a time. Any other circuit that is not active will be available for GC by the server.

I'm going to close this issue as there is not enough data for us to troubleshoot it and we don't think there is a leak here based on our own stress/perf testing.

**Closed by javiercn** 2020-06-29 13:37 UTC
Labels: area-blazor

**Comment by jeffreypalermo** [comment] 2020-07-07 21:09
I believe there is either a leak or a very easy user error that results in a leak.  I've experienced it as well.
