### ISSUE TITLE
Improve error handling in Blazor

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#14928] opened 2019-10-11 16:05 UTC
From @Sebazzz. See conversation here: https://devblogs.microsoft.com/aspnet/blazor-server-in-net-core-3-0-scenarios-and-performance/#comment-941

"I very much enjoy working with Blazor Server. I’m currently building a retrospective app in it (similar to retrium). I like the almost no-effort real-time UI and state broadcasting that’s possible with Blazor. It does some time getting rid of the classic request/response mindset. [However] error handling is cumbersome, and almost everything is destructive to the current session. And if something happens, the user doesn’t see any indication something happened. The need to litter every callback with a try/catch mechanism to contain errors and show an error message. Having a global or per-component error handling routine would be nice. Some errors, like errors during callbacks are recoverable. In addition to the above, in some conditions an unhandled error won’t be visible to the user anymore. The user interface will be unresponsive and there does not appear to be way to show a general message that something went wrong. I also like to be able to attach loading logic while a callback or event is performed (or are events performed synchronously?)."

**Comment by mkArtakMSFT** [comment] 2020-02-13 18:20
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/13452

**Closed by mkArtakMSFT** 2020-02-13 18:20 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Components Big Rock, Status: Resolved, area-blazor, enhancement
