### ISSUE TITLE
Cookie causes an unexpected redirect.

### ISSUE THREAD

**Issue by chris-briddock** [dotnet/aspnetcore#56057] opened 2024-06-04 06:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issue: Cookie adds redirect to /Account/Login. This works fine in Blazor, but if you wanted a different route, using the AddIdentity method, or AddApplicationCookie or you're using a web api, this would cause a redirect to /Account/Login.

Location:
IdentityCookieAuthenticationBuilderExtensions - AddApplicationCookie 

IdentityServiceCollectionExtensions - AddIdentity

### Expected Behavior

The cookie should not redirect the user, ideally this should be configurable in the appsettings.json or in code.

### .NET Version

8.0.301

**Comment by Tratcher** [comment] 2024-06-04 14:28
What should happen instead? A 401 response? Or are you just trying to change where it redirects to? That is configurable.

Cookie auth is designed for use with interactive clients where a 301 redirect is the standard flow.

**Comment by chris-briddock** [comment] 2024-06-10 01:06
To get around this, I had to use the ConfigureApplicationCookie method and set OnRedirectToLogin to return Task.Completed task, as I'm already using a LocalRedirect to use my returnUrl upon a successful authentication.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by halter73** [comment] 2024-06-11 16:50
Thanks for the report. This looks like a dupe of #9039. We hope to improve this soon.

**Closed by halter73** 2024-06-11 16:50 UTC
Labels: area-identity, Needs: Attention :wave:
