### ISSUE TITLE
[Blazor WASM] Debugging in docker-compose - configure clientport

### ISSUE THREAD

**Issue by Bjego** [dotnet/aspnetcore#49795] opened 2023-08-02 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Hi Blazor team,
I tried to scaffold my blazor environment via docker-compose, so that I can scaffold the blazor client, server, databases and also API mocks via docker-compose in my development environment (Visual Studio 2022).

As I added container-orchestrator support via the VS gui - on the first look everything worked great. Dockerfiles where created, a simple dockercompose with just my server app appeared and everything worked fine. 

I tried to fix the clients (webpage) port to a known port, to register that in my oauth server (as I did with the windows debugging as well), but I had no luck.

And when I restart debugging the client port is chaning all the time.

Is there any change to set a poperty in the dev-server to fix the client to spin up on a given port like 8080 ?

### Describe the solution you'd like

I'd like a simple config / environment setting to force the blazor server to spin up the web client on a specific port in debugging scenarios on docker-compose.

**Comment by javiercn** [comment] 2023-08-02 16:45
@Bjego thanks for contacting us.

This is likely a dupe of https://github.com/dotnet/aspnetcore/issues/37565, please upvote that issue instead.

**Closed** 2023-08-02 16:45 UTC
Labels: area-blazor

**Comment by Bjego** [comment] 2023-08-02 18:37
Hi, I just checked the linked issue. I think these are different things. The other issue is about vscode devcontainers and my issue is about the debugging .net within a docker container / or a docker compose orchestration. Which you can easily do with e.g webapi projects, but unfortunately not with blazor wasm, as there seems to be no way to configure the wasm client to run on a specific port. When you don't use oauth, it works straight out of the box. But when you need a specific client port - it looks like there is no obvious config setting .Cheers Sent from Android PhoneAm 02.08.2023 18:45 schrieb Javier Calvarro Nelson ***@***.***>:
@Bjego thanks for contacting us.
This is likely a dupe of #37565, please upvote that issue instead.
