### ISSUE TITLE
aspnetcore-runtime exe installers are missing shared/Microsoft.NETCore.App/

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/aspnetcore#4310] opened 2018-11-29 00:41 UTC
The latest 3.0 daily builds of aspnetcore-runtime-3.0.0-preview-(buildnumber).exe are not installing shared/Microsoft.NETCore.App/. They only contain shared/Microsoft.AspNetCore.App/

Spotted by @leecow in 3.0.0-preview-18572-0018

cc @joeloff

**Comment by muratg** [comment] 2019-01-08 22:39
@joeloff is this a known/fixed issue?

**Comment by joeloff** [comment] 2019-01-08 22:52
This came up last year some time. Let me see if I can find the thread.

**Comment by joeloff** [comment] 2019-01-08 22:55
Yup, it all depends on the zip. Back in November when this issue came up, the zip file we received during the build didn't contain that folder. Setup simply unzips and consumes the zip file content. My original suspicion was that we maybe received an intermediate zip file.

**Comment by muratg** [comment] 2019-01-08 22:56
Thanks @joeloff! 

@leecow I'm closing this issue. Hopefully this was just a temporary issue that won't repeat.

**Comment by natemcmaster** [comment] 2019-01-08 23:12
This issue hasn't been fixed. Unless omitting Microsoft.NETCore.App is by design, the installer has been busted since 2.1.

**Comment by joeloff** [comment] 2019-01-08 23:14
I think it's the zip that's busted. In the old build we only built setup once the runtime CI builds finished. I suspect that we're getting a copy of the zip with just the ASP.NET bits, before the NetCore app folder is added. I'll reply on the original email we had as that had a lot of details

**Comment by joeloff** [comment] 2019-01-09 16:00
We included it in 2.x so it does appear to be a regression. I don't recall that we made a decision in 3.x to remove it, though that's certainly possible.

**Comment by natemcmaster** [comment] 2019-01-09 16:57
http://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/2.1.0/aspnetcore-runtime-2.1.0-win-x64.exe

I think 2.x has this problem, too. When I run the 2.1.0 installer, I only get AspNetCore.App/All, not NETCore.App.

**Comment by Pilchie** [comment] 2019-07-23 17:51
@johnbeisner @joeloff @anurse Do you know if this is still an issue with the new product composition work?

**Comment by joeloff** [comment] 2019-07-23 18:04
I looked at a preview 8 internal build (from 7/20). I only see Microsoft.AspNetCore.App so my guess is yes, this is still an issue.

**Comment by Pilchie** [comment] 2019-08-07 00:37
Given that this has shipped in 2.1 and 2.2, I don't think it's critical to fix for 3.0.  Customers can install the .NET Core runtime as well as the Asp.NET one.

**Comment by JunTaoLuo** [comment] 2020-12-18 22:52
As we called out on the installer download page:
> On Windows, we recommended installing the Hosting Bundle, which includes the .NET Runtime and IIS support.

It looks like the aspnetcore-runtime-2.1.0-win-x64.exe installing only the aspnetcore runtime is by design.

Closing unless we hear objections.

**Closed by JunTaoLuo** 2020-12-18 22:52 UTC
Labels: area-installers
