### ISSUE TITLE
Blazor SSR incorrect DOM patching for checkbox/radio controls

### ISSUE THREAD

**Issue by schmellow** [dotnet/aspnetcore#53039] opened 2023-12-28 08:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Enhanced navigation patches in incorrect values when navigating between similarily structured pages in default SSR mode

### Steps To Reproduce

Minimal repro: https://github.com/schmellow/BlazorDomPatchingBugRepro

1) Navigate to Page1 and observe that nothing is selected
2) Navigate to Page2 and check any of the checkboxes. For example check Flag3
3) Navigate back to Page1 and observe that radio button, positionally corresponding to last checked checkbox is selected now.  For example, if you checked Flag3, then Baz option will be checked.

### .NET Version

8.0.100

### Anything else?

This does not seem to be happening if you set ```@rendermode InteractiveServer``` on one or both components: it seems that a slightly different html is generated in this case, with ```<!--!-->``` between elements, which seems to throw off diffing?

I cannot predict if this would work consistently, so a better workaround is welcome.

**Comment by MackinnonBuck** [comment] 2024-01-13 00:17
Hi @schmellow, thanks for opening the issue.

This seems to be a duplicate of https://github.com/dotnet/aspnetcore/issues/51707, so I'm going to close this out. Please open a new issue if you disagree and think there's a separate problem here.

**Closed by MackinnonBuck** 2024-01-13 00:17 UTC
Labels: area-blazor
