### ISSUE TITLE
Default ExceptionHandlerMiddleware should have an option to suppress log output

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#46962] opened 2023-03-01 17:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is has been reported before here: https://github.com/dotnet/aspnetcore/issues/42950

The suggested resolution was to set log level to `None` for `Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware`.  Whilst this kind of works, I think it's a pretty terrible solution.

First, it semantically looks - from a glance at log levels - like you don't want exceptions logged.  And this is just because you (in your custom exception handling middleware, registered in `app.UseExceptionHandler`) are logging exceptions in a way you want, instead of leaving it to `ExceptionHandlerMiddleware`.

Second, if some third-party exception handling middleware is registered in the pipeline, it can't control the log levels, so you'll have to manually suppress  `ExceptionHandlerMiddleware`'s logs via the log levels.  This is messy.

### Expected Behavior

Middleware registered via `app.UseExceptionHandler()` should have a way to completely suppress error logging made by `ExceptionHandlerMiddleware`, and considering a custom exception handler is quite likely to make its own logs, that suppression should maybe even be the default.  Nevertheless, it should be an option.

**Comment by Tratcher** [comment] 2023-03-01 17:28
This may be addressed by https://github.com/dotnet/aspnetcore/issues/46280. That adds a way to treat specific exceptions as known and reduce their log impact. Unknown/unexpected exceptions would continue to be logged as errors.

**Comment by adityamandaleeka** [comment] 2023-03-01 23:03
Cool, sounds like this is a duplicate of #46280 so I'll close this one.

**Closed by adityamandaleeka** 2023-03-01 23:03 UTC
Labels: area-runtime, diagnostics

**Comment by jez9999** [comment] 2023-03-02 12:07
> Cool, sounds like this is a duplicate of #46280 so I'll close this one.

Could someone confirm that that bug's solution will allow my code to put in place an error handler that handles *all* exceptions instead of the default handler?
