### ISSUE TITLE
Change status code 200 to 204 for DefaultApiConventions.Delete

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/aspnetcore#42468] opened 2022-06-28 12:55 UTC
## Background and Motivation
`DefaultApiConventions.Delete` includes the status code 200 OK and, 404 Not Found and 400 Bad Request but a HTTP DELETE usually results in a 204 No Content rather than a 200 OK.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.defaultapiconventions.delete?view=aspnetcore-6.0

## Proposed API
Change the attribute from 200 OK to 204 No Content.
```diff
[Microsoft.AspNetCore.Mvc.ApiExplorer.ApiConventionNameMatch(Microsoft.AspNetCore.Mvc.ApiExplorer.ApiConventionNameMatchBehavior.Prefix)]
[Microsoft.AspNetCore.Mvc.ProducesDefaultResponseType]
-[Microsoft.AspNetCore.Mvc.ProducesResponseType(200)]
+[Microsoft.AspNetCore.Mvc.ProducesResponseType(204)]
[Microsoft.AspNetCore.Mvc.ProducesResponseType(404)]
[Microsoft.AspNetCore.Mvc.ProducesResponseType(400)]
public static void Delete (object id);
```

**Comment by rafikiassumani-msft** [comment] 2022-06-29 01:57
Dupe of #42467

**Closed by rafikiassumani-msft** 2022-06-29 01:57 UTC
Labels: api-suggestion, area-web-frameworks

**Comment by vanillajonathan** [comment] 2022-06-29 09:35
But this is restfully incorrect!

Also, changing this wouldn't break anything since the behavior of the application would still be the same, only the OpenAPI definition would change.
