### ISSUE TITLE
Kestrel memory pool does not reliably decrease with load

### ISSUE THREAD

**Issue by GREsau** [dotnet/aspnetcore#24958] opened 2020-08-17 10:09 UTC
### Describe the bug
While load testing a new service using SignalR, we noticed that memory usage does not always decrease after connections drop off. Sometimes it decreases a minute or two after the connections end, but sometimes it just never recovers. This causes us two problems:
1. When an instance nears its memory limit, it will reject new connections (achieved using custom middleware that responds with a 503) in order to protect its existing connections. But since memory usage does not decrease, the instance will never accept new connections, even after most of its existing connections end
2. Our service autoscales on memory, but because memory usage stays high our service will rarely scale-down when under low load. This is less of a problem, it just costs a bit to run with extra capacity

This shows memory usage increasing with number of connections (tracked using the `OnConnectedAsync`/`OnDisconnectedAsync` methods of our `Hub`), but not reliably decreasing afterwards:

![image](https://user-images.githubusercontent.com/9611672/90380602-2fbd8880-e074-11ea-871d-edfbd2e37ac5.png)

The service is running in an Alpine 3.12 docker container, but we notice similar behaviour when running locally in Windows 10. We initially assumed this was a simple memory leak, but when making a large number of connections over time while keeping the number of concurrent connections low, memory usage does not increase.

When taking a heap dump, we see memory fairly dominated by `Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets!Buffers.MemoryPoolBlock`:

![image](https://user-images.githubusercontent.com/9611672/90383812-93e24b80-e078-11ea-8874-a672c3199c41.png)

### To Reproduce

1. Make a large number of concurrent connections to a SignalR Core service
2. End connections
3. Monitor memory - it should decrease, but _usually_ does not

### Further technical details
- ASP.NET Core version 3.1.6, using docker image based on `mcr.microsoft.com/dotnet/core/aspnet:3.1.6-alpine3.12`
- Built with SDK 3.1.302, using docker image based on `mcr.microsoft.com/dotnet/core/sdk:3.1.302-alpine3.12`
- Reproduced locally on Windows 10 using ASP.NET Core 3.1.6, SDK 3.1.202

**Comment by BrennanConroy** [comment] 2020-08-17 21:16
Kestrel will pool internal buffer up to a limit and will not let them go. We should consider having a settable limit or release strategy for the pool.

cc @halter73

**Comment by halter73** [comment] 2020-08-19 23:21
Related: https://github.com/aspnet/KestrelHttpServer/issues/609, https://github.com/aspnet/KestrelHttpServer/issues/2673

**Comment by adityamandaleeka** [comment] 2022-02-15 02:40
Closing this as a duplicate of https://github.com/dotnet/aspnetcore/issues/27394

**Closed by adityamandaleeka** 2022-02-15 02:40 UTC
Labels: enhancement, area-runtime, servers-kestrel, severity-nice-to-have, affected-very-few
