### ISSUE TITLE
[.NET 8 Blazor] HeadContent in .razor page should be APPENDED to, not replace any in the MainLayout

### ISSUE THREAD

**Issue by cactusoft** [dotnet/aspnetcore#51864] opened 2023-11-03 22:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the App.razor file, there is a  <HeadOutlet /> tag which allows additional head content to be added from MainLayout or .razor  pages in the following way:

```html
<HeadContent>
 some content
</HeadContent>
```
However, if you specify HeadContent in Page.razor, it will overwrite any you specified in MainLayout.razor.

It is not clear from the documentation if this is intended behaviour, but it seems counterintuitive.

### Expected Behavior

Any head content added in the .razor page should be APPENDED to any added within the parent MainLayout. It should not replace it. It seems reasonable to assume that one might add content such as CSS links to the header in a MainLayout, while also wanting to add content such as meta tags or a canonical tag to the page itself.

PageTitle works in this way at present, but this seems correct, in that a page can only have a single PageTitle, so the one specified at the more granular level (page) should take precedent.

### Steps To Reproduce

Add head content to the MainLayout

<HeadContent>
    <link href="someCSSfile" />
</HeadContent>

Add other head content to the page.razor:

<HeadContent>
    <meta name="description" content="some description">
    <link rel="canonical" href="/somepageURL" />
</HeadContent>

The HeadContent from the MainLayout loads up for a fraction of a second, but disappears as soon as the head content from the page loads.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by danirzv** [comment] 2023-11-04 04:00
As i remember it's a known behaviour, if you provide multiple head content only the last one gonna render, if you want to append to your head content, i think you need to use headOutlet

**Comment by cactusoft** [comment] 2023-11-04 11:59
> As i remember it's a known behaviour, if you provide multiple head content only the last one gonna render, if you want to append to your head content, i think you need to use headOutlet

I do have a <HeadOutlet /> in the App.razor. That is how the MainLayout and Page add content to the head section.

The problem is that you cannot add content at both MainLayout and the page level, because adding at the page will overwrite anything you add at the MainLayout.

I have tried putting a headoutlet into the HeadContent of MainLayout, or just outside it, but both generate errors. So it seems you can only use this at the App.razor, and then have to make a choice whether you add further head content at either the MainLayout or the page, because you cannot do both.

Looking at the docs, for web assembly there is a line that sets appending content in the program.cs:

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?view=aspnetcore-8.0

`builder.RootComponents.Add<HeadOutlet>("head::after");`

I got excited seeing this, as thought it may have worked in server too, but it doesn't.

If there is a way to set the HeadOutlet in server so that content is appended, I can't find documentation for it.

**Comment by cactusoft** [comment] 2023-11-04 15:15
I tested .NET 6, and it appears the behaviour now in .NET 8 is the same as it was in .NET 6. If you have a HeadOutlet in the _Layout.cshtml.

 <component type="typeof(HeadOutlet)" render-mode="Server" />

and then add HeadContent in the MainLayout.razor, and the Page.razor, only the Page.razor HeadContent appears.

 I just didn't really notice before as I had different Layout files for different sections and put CSS references into those, whereas now I have App.razor, I need to add section specific CSS references in the MainLayout instead.

So I am assuming that since it appears to have always been like this, this is how it is intended to work.

Although it would be a really nice addition to be able to add HeadContent to both MainLayout and a Page, and have both appear. Or even better, to have it as an option, maybe like this:

`<HeadContent mode="Append">This is added in a page and gets appended to any head content in the MainLayout</HeadContent>`

or old behaviour, which would continue to work like this by default, without the mode specified.

`<HeadContent mode="Replace">This will replace any head content in the MainLayout</HeadContent>`

so it would not break any existing code.

**Comment by cactusoft** [comment] 2023-11-05 11:49
Ok, I think I have a workaround using the new SectionContent functionality in .NET 8.

The App.razor stays how it is with the HeadOutlet section.

Add this to the _Imports.razor:

`@using Microsoft.AspNetCore.Components.Sections`

In the MainLayout.razor, add a section inside the HeadContent:

```
<HeadContent>
    <link href="staticfiles/stuff/skin.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="./_content/IntlTelInputBlazor/css/intlTelInput.css">
    <SectionOutlet SectionName="HeadContentFromPage" />
</HeadContent>
```

Then in pages, we can add content to this, which will appear in the MainLayout without overwriting the other

```
    <SectionContent SectionName="HeadContentFromPage">
        <link rel="canonical" href="/the-canonical-url" />
    </SectionContent>
```

It's slightly more complicated, but not much and it achieves exactly what I was after. It looks previously that this could be done in .NET 6 with cascading parameters, but this SectionContent functionality is simpler and neater. I can see this being useful in other places.

**Comment by mkArtakMSFT** [comment] 2023-11-06 17:57
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design and it seems you've understood how this works already on your own and were able to fix your code.

**Closed by mkArtakMSFT** 2023-11-06 17:57 UTC
Labels: area-blazor
