### ISSUE TITLE
Loading JavaScript files associated with Blazor components without giving full path.

### ISSUE THREAD

**Issue by ptrwis** [dotnet/aspnetcore#59320] opened 2024-12-04 20:56 UTC
To load a custom JavaScript file I need to pass the full path, like:

`var module = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./Components/Pages/PageA.razor.js");`

This is bad, because I need to change the path when moving component to different place.

Maybe this should work similarly to automatically loading css files named after component (in example "PageA.razor.css"),
but any solution allowing to load such JS files without providing full path would be better.

**Comment by mkArtakMSFT** [comment] 2024-12-05 17:35
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/45120

**Closed by mkArtakMSFT** 2024-12-05 17:35 UTC
Labels: area-blazor, feature-blazor-jsinterop
