### ISSUE TITLE
dotnet core 3.1 - package restore downgrades version of Microsoft.AspNetCore.Authentication.OpenIdConnect

### ISSUE THREAD

**Issue by bradtwurst** [dotnet/aspnetcore#21951] opened 2020-05-18 16:51 UTC
### Describe the bug
dotnet restore replaces version 3.1.4 of package with 3.0.0 version

### To Reproduce
1. create a new cs project - netcoreapp3.1

1. dotnet add Microsoft.AspNetCore.Authentication.OpenIdConnect
 csproj file indicates version 3.1.4
`<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="3.1.4" />`

1. project.assets.json indicates 3.1.4
`    ".NETCoreApp,Version=v3.1": {
      "Microsoft.AspNetCore.Authentication.OpenIdConnect/3.1.4": {
        "type": "package",
        "dependencies": {
          "Microsoft.IdentityModel.Protocols.OpenIdConnect": "5.5.0"
        },
        "compile": {
          "lib/netcoreapp3.1/Microsoft.AspNetCore.Authentication.OpenIdConnect.dll": {}
        },
        "runtime": {
          "lib/netcoreapp3.1/Microsoft.AspNetCore.Authentication.OpenIdConnect.dll": {}
        },
        "frameworkReferences": [
          "Microsoft.AspNetCore.App"
        ]
      },
`

1. perform dotnet restore on project

1.  csproj file still indicates version 3.1.4
`<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="3.1.4" />`

1. project.assets.json now indicates 3.0.0
`    ".NETCoreApp,Version=v3.1": {
      "Microsoft.AspNetCore.Authentication.OpenIdConnect/3.0.0": {
        "type": "package",
        "dependencies": {
          "Microsoft.IdentityModel.Protocols.OpenIdConnect": "5.5.0"
        },
        "compile": {
          "lib/netcoreapp3.0/Microsoft.AspNetCore.Authentication.OpenIdConnect.dll": {}
        },
        "runtime": {
          "lib/netcoreapp3.0/Microsoft.AspNetCore.Authentication.OpenIdConnect.dll": {}
        },
        "frameworkReferences": [
          "Microsoft.AspNetCore.App"
        ]
      },
`

1. perform a dotnet build on project

1. expected Microsoft.AspNetCore.Authentication.OpenIdConnect.dll in bin to be for version 3.1.4 (modify date - 4/16/2020)

1. instead the file is for version 3.0.0 (modify date - 9/15/2019)

### Further technical details
- ASP.NET Core version - preview 3.1.300-preview-015135
- dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015135
 Commit:    0b3c572e97

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015135\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015095 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  CLI, also occurs in VS2019preview

**Comment by Tratcher** [comment] 2020-05-18 21:50
@wtgodbe @JunTaoLuo ?

**Comment by wtgodbe** [comment] 2020-05-19 17:57
Hmm, that's surprising. Can you share the content of your nuget.config?

**Comment by bradtwurst** [comment] 2020-05-20 13:21
Additional information,
I've have another solution/project structure in different folder (same dev box) and it is not exhibiting this behavior.  I'm thinking it is environmental, but I don't know what next step is in order to track down cause



There is not a local nuget.config file within this project or any of its parent folders

In my appdata structure, the following config content is
`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="devexpress licensed feed" value="https://nuget.devexpress.com/<redacted>/api" />
    <add key="DevExpress 18.1 Local" value="C:\Program Files (x86)\DevExpress 18.1\Components\System\Components\Packages" />
    <add key="DevExpress 19.1 Local" value="C:\Program Files (x86)\DevExpress 19.1\Components\System\Components\Packages" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    <add key="DevServer" value="http://devServer:8080/nuget" />
    <add key="DevExpress .NET Core Desktop 19.2 Local" value="C:\Program Files (x86)\DevExpress 19.2\.NET Core Desktop Libraries\System\Components\Packages" />
  </packageSources>
  <disabledPackageSources>
    <add key="devexpress licensed feed" value="true" />
    <add key="DevExpress 18.1 Local" value="true" />
    <add key="DevExpress 19.1 Local" value="true" />
    <add key="Microsoft Visual Studio Offline Packages" value="true" />
  </disabledPackageSources>
  <packageManagement>
    <add key="format" value="1" />
    <add key="disabled" value="False" />
  </packageManagement>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
</configuration>
`


performing the following nuget command in the project directory 

>c:\NuGet\NuGet.exe sources list
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  devexpress licensed feed [Disabled]
      https://nuget.devexpress.com/<redacted>/api
  3.  DevExpress 18.1 Local [Disabled]
      C:\Program Files (x86)\DevExpress 18.1\Components\System\Components\Packages
  4.  DevExpress 19.1 Local [Disabled]
      C:\Program Files (x86)\DevExpress 19.1\Components\System\Components\Packages
  5.  Microsoft Visual Studio Offline Packages [Disabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  6.  DevServer [Enabled]
      http://DevServer:8080/nuget
  7.  DevExpress .NET Core Desktop 19.2 Local [Enabled]
      C:\Program Files (x86)\DevExpress 19.2\.NET Core Desktop Libraries\System\Components\Packages

**Comment by wtgodbe** [comment] 2020-11-12 20:34
Hi @bradtwurst - sorry that this issue fell off our radar. Were you able to find a workaround/solution?

**Comment by dougbu** [comment] 2020-11-16 19:37
It's possible the older 3.1.300-preview-015135 SDK overrode the versions in use or contained a problematic NuGet implementation. Suggest moving to the 3.1.404 SDK from https://dotnet.microsoft.com/download/dotnet-core/3.1.

We're curious about the root cause but believe the newer SDK will fix your issue. Please reopen this issue if we're wrong.

**Closed by dougbu** 2020-11-16 19:37 UTC
Labels: area-infrastructure
