### ISSUE TITLE
Is there a way to access `window` object in the Browser from Blazor Webassembly?

### ISSUE THREAD

**Issue by ibocon** [dotnet/aspnetcore#37790] opened 2021-10-23 12:27 UTC
I want to add 'onclick' event listener on `window.document` like below in Blazor Webassembly.

```js
document.addEventListener('onclick', function(e) {

});
```

I know I can use [Blazor JavaScript interoperability (JS interop)](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0) to do this.

However, I am curious there is a way to access global object from C# code.

For example,

```cs
@code {
    protected override void OnInintalized()
    {
        Document.Clicked += OnClicked;
    }

   public void Dispose()
   {
        Document.Clicked -= OnClicked;
   }
}
```

If accessing global object is not currently supported, is this a feature will be implemented in future? or is this impossible to implement?
__

**Comment by mkArtakMSFT** [comment] 2021-11-11 18:02
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/28820

**Closed by mkArtakMSFT** 2021-11-11 18:02 UTC
Labels: enhancement, area-blazor
