### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Testing is broken in SDK 6.0.201

### ISSUE THREAD

**Issue by philip-reed** [dotnet/aspnetcore#40614] opened 2022-03-09 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`ObjectDisposedException` thrown when trying to use the `WebApplicationClient` targeting SDK 6.0.201.  
When reverting to SDK 6.0.200, the issue goes away.

### Expected Behavior

`ObjectDisposedException` should not be thrown.

### Steps To Reproduce

Write any test that calls `WebApplicationFactory.CreateClient()`

### Exceptions (if any)

```
 System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ConfigurationManager'.
   at Microsoft.Extensions.Configuration.ReferenceCountedProviderManager.AddProvider(IConfigurationProvider provider)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.<>c__DisplayClass25_0.<Build>b__2(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in D:\GIT\Whds.Packing.App\src\Whds.Packing.StateMachine\Program.cs:line 53
   ```

### .NET Version

6.0.201

**Comment by philip-reed** [comment] 2022-03-09 15:09
https://github.com/dotnet/core/issues/7259

**Comment by martincostello** [comment] 2022-03-09 15:10
This might have been introduced by https://github.com/dotnet/runtime/pull/63816.

**Comment by martincostello** [comment] 2022-03-09 15:12
FWIW, a more detailed repro might be needed to narrow down what's different in your app that causes this. I use `Microsoft.AspNetCore.Mvc.Testing` extensively and didn't observe any issues with it when validating the fix or ingesting it yesterday with the 6.0.3 update.

**Comment by philip-reed** [comment] 2022-03-09 15:24
Fair enough. I'll see what I can do.

**Comment by philip-reed** [comment] 2022-03-09 16:06
Repro here.
Looks like an issue with Convey.

https://github.com/philip-reed/40614

**Comment by martincostello** [comment] 2022-03-09 16:10
> Does that framework reference take on the .NET version it was built with?

I believe it'll take a reference on whichever version of the shared framework for that major version at runtime. There's nothing specific shown in the [dependencies tab](https://www.nuget.org/packages/Convey/) for Microsoft.AspNetCore.App.

**Comment by mumby0168** [comment] 2022-03-09 16:11
> > Does that framework reference take on the .NET version it was built with?
> 
> I believe it'll take a reference on whichever version of the shared framework for that major version at runtime. There's nothing specific shown in the [dependencies tab](https://www.nuget.org/packages/Convey/) for Microsoft.AspNetCore.App.

Does it look like it's anything to do with `Configuration` something special `Convey` is doing maybe?

**Comment by martincostello** [comment] 2022-03-09 16:17
There's nothing in particular I can see from a quick glance at the code that's doing much with `IConfiguration` other than [this](https://github.com/snatch-dev/Convey/blob/eed6999d518c2bdc7014380d232ef75a000bc4c0/src/Convey/src/Convey/ConveyBuilder.cs#L17-L28), I'm not familiar with Convey though.

**Comment by mumby0168** [comment] 2022-03-09 16:18
I've spotted a dependency convey takes on Scrutor which is quite old looking at this -> 

https://www.nuget.org/packages/Scrutor/3.3.0

**Comment by mumby0168** [comment] 2022-03-09 16:19
I've asked the creators on `Convey` to see if they can add anything to this chat. Does seem odd that it would break given it's only a minor version bump 🤔

**Comment by martincostello** [comment] 2022-03-09 16:21
You can see in the issue I linked to that there was quite a large refactor done under the hood in 6.0.3 to fix a deadlock.

**Comment by philip-reed** [comment] 2022-03-09 16:23
Looks like the issue isn't related to only the WebHostFactory.
The exception is also thrown at runtime.

![image](https://user-images.githubusercontent.com/7798175/157484506-e3673828-ac14-481e-91cb-522d9269a36a.png)

**Comment by BrennanConroy** [comment] 2022-03-09 17:06
Minimal repro without Convey:
```csharp
var builder = WebApplication.CreateBuilder(args);

var sp = build.Services.BuildServiceProvider();
_ = sp.GetRequiredService<IConfiguration>();
sp.Dispose();

var app = builder.Build();
```

**Comment by bc3** [comment] 2022-03-09 21:11
we have a sort a like problem, and got a work around, see my findings in the other issue: https://github.com/dotnet/core/issues/7259#issuecomment-1063359412

**Comment by frankyuan** [comment] 2022-03-10 04:43
Looks like the issue is related to the below code

```
            using (var serviceProvider = services.BuildServiceProvider())
            {
                var config = serviceProvider.GetService<IConfiguration>();
                ... ...
            }
```

**Comment by BrennanConroy** [comment] 2022-03-10 04:44
If that's your scenario it's covered by my initial comment https://github.com/dotnet/aspnetcore/issues/40614#issuecomment-1063154634

**Comment by frankyuan** [comment] 2022-03-10 04:49
> If that's your scenario it's covered by my initial comment [#40614 (comment)](https://github.com/dotnet/aspnetcore/issues/40614#issuecomment-1063154634) and is fixed in a change coming in 6.0.4

Cool, thanks for your help!

**Comment by halter73** [comment] 2022-03-14 23:03
> ```C#
>             using (var serviceProvider = services.BuildServiceProvider())
>             {
>                 var config = serviceProvider.GetService<IConfiguration>();
>                 // ...
>             }
> ```


> If that's your scenario it's covered by my initial comment [#40614 (comment)](https://github.com/dotnet/aspnetcore/issues/40614#issuecomment-1063154634) and is fixed in a change coming in 6.0.4

I don't think this will be fixed in 6.0.4. In the above case `WebApplicationBuilder.Configuration` is being disposed before all sources were added.

This was already somewhat broken before 6.0.3 even though it didn't previously ODE. Even though you could previously add sources to `WebApplicationBuilder.Configuration` after disposing it, any providers from sources added prior to disposing the `ConfigurationManager` would be disposed before the web app even started breaking file change notifications. The same code would also break file change notifications for .NET 5 apps using `HostBuilder` and `ConfigurationBuilder`.

Maybe we could fix this by changing

https://github.com/dotnet/aspnetcore/blob/dafd01aa6c5d8bcf8d868154e2cf986739a5d610/src/DefaultBuilder/src/WebApplicationBuilder.cs#L103

to 

```C#
Services.AddSingleton<IConfiguration>(Configuration); 
```

so disposing an `IServiceProvider` built from `Services` doesn't dispose the `ConfigurationManager` if an `IConfiguration` instance was resolved. We'd then need something like the following:

```C#
Services.AddSingleton<SomeInternalType>(() => Configuration);
```

And 

https://github.com/dotnet/aspnetcore/blob/dafd01aa6c5d8bcf8d868154e2cf986739a5d610/src/DefaultBuilder/src/WebApplicationBuilder.cs#L225-L227

Would become something like

```C#
            // Resolve both the _hostBuilder's Configuration and builder.Configuration to mark both as resolved within the
            // service provider ensuring both will be properly disposed with the provider.
            _ = _builtApplication.Services.GetService<IEnumerable<IConfiguration>>();
            _ = _builtApplication.Services.GetService<SomeInternalType>();
```

Do we think this is worth trying to patch given the workaround?

**Comment by halter73** [comment] 2022-03-14 23:23
@BrennanConroy is right that https://github.com/dotnet/aspnetcore/pull/39836 which should be in 6.0.4 (or rather a close variation of this) should cause `WebApplicationBuilder.Build()` to add additional sources to the root `ConfigurationManager` less frequently. That might fix this specific issue. There will still be an issue with manually adding sources to the `ConfigurationManager` after resolving it from a `ServiceProvider` created by a manual call to `builder.Services.BuildServiceProvider()` and disposing it.

**Comment by BrennanConroy** [comment] 2022-04-12 18:15
Patch is out, original issue should be resolved.

**Closed** 2022-07-05 17:23 UTC
Labels: bug, feature-mvc-testing, area-web-frameworks
