### ISSUE TITLE
ASP.NET Core sources not showing in https://source.dot.net

### ISSUE THREAD

**Issue by ionmincu** [dotnet/aspnetcore#24364] opened 2020-07-28 13:11 UTC
### Describe the bug
Sources were once available in https://source.dot.net as per https://github.com/dotnet/aspnetcore/issues/7281 .
Today you can not see sources there.

### To Reproduce

https://source.dot.net/#Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs,9ec1a007b328ef6c

**Comment by dougbu** [comment] 2020-08-15 01:37
That URI works fine. So does e.g. https://source.dot.net/#Microsoft.AspNetCore.Mvc.Core/Builder/ControllerEndpointRouteBuilderExtensions.cs Was this a transient networking or server problem perhaps❔

**Comment by dougbu** [comment] 2020-11-18 20:31
@ionmincu thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2020-11-18 20:31 UTC
Labels: area-infrastructure
