### ISSUE TITLE
MinimalAPI - RequestDelegateFactory - IOException Generates Http StatusCode 200 (on FormReading)

### ISSUE THREAD

**Issue by houseofcat** [dotnet/aspnetcore#47578] opened 2023-04-05 20:40 UTC
## Summary

Related to issue #47525 . During an IOException the status code is not modified and returned out. I anticipate there is some more context as to why that maybe the case, but I feel - perhaps opinionatedly - the status code is 500 at this point.

## Motivation and goals

During an IOException when trying to read Form, I propose we modified the status code to:
```csharp
StatusCodes.Status500InternalServerError
```

## In scope

I believe the issue happens in a couple of a scenarios but usually when the Socket read times out for various transient condition or that the request body has surpassed the max allowable size as indicated by #47525. This is not to address the differentiation of issues, but to begin with changing all IOExceptions to 500 when trying to read the Form body from the `RequestDelegateFactory.cs`.

## Out of scope

None that I know of.

## Risks / unknowns

Without developer visibility it could still be difficult to triage MaxRequest size exceeded, but not more difficult than getting a 200 response.

## Examples
```csharp
// Consider the usage...
var response = await client.UploadFormDataAsync(request);

// ...returns 200 during an IOException.
if (!response.IsSuccessStatusCode) { ... };
```

## Detailed design
One line change.

Add on line 1424 before the return.

```csharp
httpContext.Response.StatusCode = StatusCodes.Status500InternalServerError
```

Similar behavior exists on [line 1429 in the RequestDelegateFactory.cs](https://github.com/dotnet/aspnetcore/blob/0b10e1349063b1b5b39dd0435509abb52cc81d90/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L1429)

```csharp
catch (IOException ex)
{
    Log.RequestBodyIOException(httpContext, ex);
    httpContext.Response.StatusCode = StatusCodes.Status500InternalServerError;
    return (null, false);
}
```

**Comment by mitchdenny** [comment] 2023-04-05 23:16
Hi @houseofcat I'm going to close this as a dupe of the issue that you already commented/on linked to:

Dupe: https://github.com/dotnet/aspnetcore/issues/47525#issuecomment-1497911507

I don't think we need a design proposal for this. We are already planning on address this in .NET 8.0. One thing left to discuss (over on the original issue is 400 vs. 500 error.

**Closed by mitchdenny** 2023-04-05 23:16 UTC
Labels: area-runtime, design-proposal
