### ISSUE TITLE
[SignalR][@microsoft/signalr (typescript client)] Add ConnectionState change notification/event

### ISSUE THREAD

**Issue by known-as-bmf** [dotnet/aspnetcore#25725] opened 2020-09-09 10:06 UTC
### Is your feature request related to a problem? Please describe.

I would like to be notified when the state of a `HubConnection` changes. It could be used to react to state changes on the consumer side.

### Describe the solution you'd like

Some kind of event mechanism for the connection state.

I implemented a very ugly patch for this purpose here: https://github.com/known-as-bmf/react-signalr/blob/feature/connection_state/src/useSignalr.ts#L71-L108

It basically highjacks the `this.connectionState` class property. It's an ugly hack and it would be nice to have this feture natively.

### Additional context

See related issue in one of my projects https://github.com/known-as-bmf/react-signalr/issues/4

**Comment by BrennanConroy** [comment] 2020-09-09 17:44
Dupe of https://github.com/dotnet/aspnetcore/issues/17900

What state are you wanting to observe that can't be done by observing `start`, `onclose`, and `onreconnecting`/`onreconnected`?

**Comment by known-as-bmf** [comment] 2020-09-09 20:47
I guess I was looking for a unique way of observing state changes (i.e. not having to subscribing to 4 event/promise).

```js
let theState = connection.state;
const updateState = () => { theState = connection.state; };

connection.onclose(updateState);
connection.onreconnecting(updateState);
connection.onreconnected(updateState);

connection.start().then(updateState);
updateState();
```

vs

```js
let theState = connection.state;

connection.onstatechanged((newState) => { theState = newState; });

connection.start();
```

**Comment by davidfowl** [comment] 2020-09-09 20:50
Why do you need that?

**Comment by known-as-bmf** [comment] 2020-09-09 20:59
I built a react hook wrapping a HubConnection and it was a feature request to expose the connection's state.

I guess it could be usefull to enable / disable some UI stuff or give some hints about connectivity depending on the state.

```jsx
const MyCmp = () => {
  const { state } = useSignalr('my hub url');
  
  return <span>The hub is {state === Connected ? 'connected!' : 'disconnected 😥'}</span>
}
```

Looks like it is doable with 4 callbacks, but I was hoping for a "cleaner" way (subjective).

Also, I don't think there is a way to unsubscribe from `onclose`, `onreconnecting` and `onreconnected`. That might be an issue (callbacks might still be called for unmounted components).

**Closed** 2020-09-11 21:06 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
