### ISSUE TITLE
Map Razor Components collides with MapFallbackToPage

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#50816] opened 2023-09-19 13:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If we use the new RazorComponents method and have MapFallbackToAreaPage, it bypasses _Host and area Management, so the subpages are displayed in App.razor from the RazorComponents definition. 

We should add the ability to use Area in RazorComponents.
```cs
        app.UseManagement();

        app.MapRazorComponents<Areas.Web.App>()
            .AddServerRenderMode();
```
UseManagement:
```cs
        builder.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapFallbackToAreaPage("Management/{*clientroutes:nonfile}", "/_Host", "Management");
        });
```

### .NET Version

.net 8 rc1

**Comment by Alerinos** [comment] 2023-09-26 17:56
I found another problem as well as a solution.
If we enter the correct link in ``Management`` then it displays the layout with ``App``. 
If we enter the not correct link in ``Management`` then it returns 404 but the layout is already correct with ``Management``, if we click from the navigation in the link then the panel is already correctly displayed.

**Comment by javiercn** [comment] 2023-09-27 11:04
@Alerinos thanks for contacting us.

We are not sure what you are trying to accomplish here. There is no area concept in Razor components, and `        app.MapRazorComponents<Areas.Web.App>()` will map all the Razor Component Pages in the assembly.

I suspect that what you are trying to achieve is simply not supported.

**Comment by Alerinos** [comment] 2023-09-27 11:14
@javiercn 
Currently, I have divided areas into user and administrator. How can I currently separate this? Each area has a different action, address, etc. 
Previously it was possible to use an area, now there is no such option due to which ``MapRazorComponents`` overlaps other areas.

**Comment by javiercn** [comment] 2023-09-27 11:21
@Alerinos thanks for the additional details.

Areas are an MVC context, not a Blazor Concept. The closest thing that will possibly work will be to move each "area" into its own assembly.

**Comment by Alerinos** [comment] 2023-09-27 11:30
@javiercn 
You mean create your own ``WebApplication.CreateBuilde`` separately for the user and separately for the admin panel?

**Comment by javiercn** [comment] 2023-09-27 11:42
@Alerinos No.

Move each "Area" into their own RCL, and call MapRazorComponent<AreaRoot> from it.

**Comment by Alerinos** [comment] 2023-10-02 16:12
@javiercn 
Is it something like this?
```cs

        app.MapRazorComponents<Areas.Web.App>()
            .AddAdditionalAssemblies(AssemblyProvider.Types<IAreaWeb>().ToArray())
            .AddServerRenderMode()
            .AddWebAssemblyRenderMode();

        app.MapRazorComponents<Areas.Manager.App>()
            .AddAdditionalAssemblies(AssemblyProvider.Types<IAreaManager>().ToArray())
            .AddServerRenderMode()
            .AddWebAssemblyRenderMode();
```

This causes an error like this:
```
[18:09:49 ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

Blazor web static files
Blazor web static files


   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.TryServeStaticFile(HttpContext context, String contentType, PathString subPath)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
[18:09:49 INF] Request finished HTTP/2 GET https://localhost:5001/_framework/aspnetcore-browser-refresh.js - 200 12701 application/javascript; charset=utf-8 27.4175ms
[18:09:49 ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:



   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
![image](https://github.com/dotnet/aspnetcore/assets/42449535/1cda1d96-cd95-4061-9a23-327d14d54d8d)

**Comment by Alerinos** [comment] 2023-10-02 16:34
The problem occurs here, it loads ``blazor.web.js`` twice, apart from that everything works fine. You should make an exception, check if there is more than one ``MapRazorComponents``, if so, it only loads the js once.

https://github.com/dotnet/aspnetcore/blob/2e7ce237f889b159d87ca9c6176a8f751984e6fb/src/Components/Endpoints/src/Builder/RazorComponentsEndpointRouteBuilderExtensions.cs#L57-L58

**Comment by Alerinos** [comment] 2023-10-04 19:21
@mkArtakMSFT Can you take a look at it? It seems to me that there is an error, if I am wrong it is worth giving such information in the documentation.

**Comment by gbthakkar** [comment] 2023-11-25 12:40
> @Alerinos thanks for the additional details.
> 
> Areas are an MVC context, not a Blazor Concept. The closest thing that will possibly work will be to move each "area" into its own assembly.

Dear Sir, 
I am triming down the existing Blazor-Server application created in Do.Net 6  haveing two similar areas.
and then was correctly working in production with the support of following lines.

app.MapFallbackToAreaPage("/admin/{*clientroutes:nonfile}", "/_AdminHost", "Admin");
app.MapFallbackToAreaPage("/Member/{*clientroutes:nonfile}", "/_MemberHost", "Member");
app.MapFallbackToPage("/_Host");

So Please do not say that it is MVC concept and not Blazor. May be that you have not tried or never needed that.

I am going to update this thread with GIThub link when my project trimming complete. So other can download the project, run and see how we used to mange the areas in blazor-6.

It is very easy to understand the need of it when we need to have separate/special logic per area ( like we used to do in MVC)

And importantly...when any MVC project is under consideration for upgrade/rewrite (to Blazor or React), the area concept can have major impact on decision and people can not move to Blazor 8 that easily. (my 2 cents.).

**Comment by gbthakkar** [comment] 2023-11-28 03:48
Hi As I said, I will upload the repository for demo,
Here it is

https://github.com/gbthakkar/Blazor6-Area-Demo-01

The point to note here are,

1. Have having _host.cshtml for each area. And one for root website.
2. have its own _layout and mainlayout pairs.
3. have PWA configuration for each area.
4. having route filter to prevent accidental load of admin area page into customer/member area.
5. having login check for each area. (you may have different option for the kind of implementation). But I am just tring to show the kind of customization in place for areas.

May be, it all gone with Blazor-8 !!

**Comment by mkArtakMSFT** [comment] 2023-12-20 17:40
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/51411

**Closed by mkArtakMSFT** 2023-12-20 17:40 UTC
Labels: area-blazor, Pillar: Complete Blazor Web
