### ISSUE TITLE
Very slow build - can't build project

### ISSUE THREAD

**Issue by mokshinpv** [dotnet/aspnetcore#54293] opened 2024-02-16 18:09 UTC
**Version Used**: 
8.0.200
Visual Studio 2022, 17.9.0

**Steps to Reproduce**:

After upgrading to .NET 8 I can't build my project.
Build doesn't finish (maybe infinite loop).
This project contains classes which are generated by Antlr4.
These classes are very large so maybe this causes problems.

I created small project with same problem:
[academitslearn.zip](https://github.com/dotnet/roslyn/files/14314416/academitslearn.zip)

Here build finishes but it takes about 10 seconds.
In previous versions build was immediate.

**Expected Behavior**:

Build finishes and build is fast.

**Actual Behavior**:

Build not finishes for real project.
Build is very slow for small project.

**Comment by cston** [comment] 2024-03-01 17:37
With the simplified repro from @jjonescz, it looks like 46% of the time is in `SyntaxNavigator.GetFirstToken()`.

<img width="878" alt="image" src="https://github.com/dotnet/aspnetcore/assets/10732005/fc2f17c3-8044-4e54-aa65-23564dba9ad9">

**Comment by mkArtakMSFT** [comment] 2024-03-06 18:50
Moving to the `minimal` are path. This is a potential dupe of https://github.com/dotnet/aspnetcore/issues/53899

**Comment by cston** [comment] 2024-03-06 19:08
@JamesNK, it looks like [`HasLanguageComment`](https://github.com/dotnet/aspnetcore/blob/main/src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs#L142C25-L142C43) may be walking up the parent chain for each token in the string concatenation.

**Comment by JamesNK** [comment] 2024-03-07 00:22
Is that a problem?

The code here:
https://github.com/dotnet/aspnetcore/blob/276e3fe165e299c090c5ff66394420d4ede15a8e/src/Framework/AspNetCoreAnalyzers/src/Analyzers/RouteEmbeddedLanguage/Infrastructure/RouteStringSyntaxDetector.cs#L142-L206

Is copied from Roslyn:
https://github.com/dotnet/roslyn/blob/891584232dc8112f33376e9ee9486051a1014b24/src/Features/Core/Portable/EmbeddedLanguages/EmbeddedLanguageDetector.cs#L67-L125

**Comment by cston** [comment] 2024-03-07 00:36
If the expression is as concatenation of N strings, that could be O(N) for each token in the expression.

**Comment by JamesNK** [comment] 2024-03-11 23:39
![image](https://github.com/dotnet/aspnetcore/assets/303201/2818ab4d-7a4e-459e-9998-73600b52429c)

**Comment by JamesNK** [comment] 2024-03-11 23:39
cc @CyrusNajmabadi

**Comment by JamesNK** [comment] 2024-03-11 23:41
I'm going to see if I can optimize walking up the nested string concat tree by remembering the last analyzed string.

For example, if "c" in the example below doesn't have a classification then "d" must not have one either:
```cs
var s = "a" + "b" + "c" + "d";
```

**Comment by cston** [comment] 2024-03-12 22:20
It looks like CSharpRegexDiagnosticAnalyzer has similar perf. In an expression `new Regex("a" + "b" + ...)` with a concatenation of N strings, the analyzer perf appears to be O(N^2). 

cc @CyrusNajmabadi

**Closed** 2024-03-22 01:39 UTC
Labels: area-minimal
