### ISSUE TITLE
razor class libraries including javascript files when consuming them via nuget in .net 6

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#38371] opened 2021-11-14 03:15 UTC
I have a repository here
https://github.com/musictopia2/BlazorBasicLibrariesSolution 
Under the library itself, if you run the pack command via visual studio, I can see that if somebody consumes the library, then all the javascript files show up on the projects which is wrong.

I had an old .net 5 project.  When compiling under .net 5, it worked fine.  However, in .net 6, then it would include those files.
Would be really disappointed if the razor class library if it had any javascript or other files in the wwwroot, then whoever uses it creates the folder and puts the files in which is not professional.

**Comment by javiercn** [comment] 2021-11-15 11:54
@musictopia2 thanks for contacting us.

What version of Visual Studio and .NET SDK are you using?

I see the expected results when I invoke pack on the project
![image](https://user-images.githubusercontent.com/6995051/141777609-f0a4557b-f601-4727-bf8c-6b6acdef28cb.png)

There was a bug in RC1/RC2 where the files got added to content and contentFiles in incremental builds, but that its addressed in RTM.

**Comment by musictopia2** [comment] 2021-11-15 13:08
For visual studio, I was using visual studio 2022 rtm version.  For the .net 6, I was using the released version of the .net.  Looks like the bug is still there in rtm.  If you use my nuget package, you will see that it put those files into the project.  A temporary workaround is to manually remove.  But then, it shows up under the project for the ones removed.

**Comment by javiercn** [comment] 2021-11-15 15:06
@musictopia2 I'm using the repo you provided with RTM versions of both, VS 2022 and .NET 6.0 and I'm not able to reproduce it. 

Can you use the project system tools extension [here](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools2022) to capture a binary log of the pack action from Visual Studio? 

You'll have to turn MSBuild logging to Diagnostics within the Visual Studio settings so that the log captures all the relevant information.

Could you also manually remove the bin and obj folders before packing and see if you still run into the same issue?

**Comment by musictopia2** [comment] 2021-11-15 18:18
if I remove the bin folders, then it would be unable to even pack because there is no release dll.
most of the time, a person would first do a build.  then later do pack via cli with no build since the build would have already been done.

**Comment by musictopia2** [comment] 2021-11-15 18:19
Do you see the problem when you install the nuget package from this location.
https://www.nuget.org/packages/BasicBlazorLibrary/

**Comment by javiercn** [comment] 2021-11-15 19:04
@musictopia2 thanks for the additional details.

I am able to reproduce the issue now. I would suggest you add `<IncludeContentInPack>false</IncludeContentInPack>` to your project file to avoid the files ending up as `content` items in the nuget package (which is what's causing them to appear on the referenced app folder) or use something like `<Content Update="wwwroot\**" Pack=false />`

**Comment by javiercn** [comment] 2021-11-15 19:05
It's not clear why this is happening since we have an explicit test for this [here](https://github.com/dotnet/sdk/blob/main/src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs#L1492)

**Comment by musictopia2** [comment] 2021-11-15 22:52
Would you like me to create a simple repository that would show the differences between .net 5 and .net 6.  This would be the most simple one I can do that would have a javascript file.  That way you can see the differences between the nuget packages that get generated from .net 5 and .net 6.

**Comment by javiercn** [comment] 2021-11-16 15:02
@musictopia2 no, don't worry, I have all we need. It's specific to pack --no-build.

I would suggest you use `dotnet pack` from the CLI

**Comment by javiercn** [comment] 2021-11-16 16:32
Did a bit more digging, 
the test contained the wrong assertion and were not checking on the right paths. https://github.com/dotnet/sdk/pull/22631 updates the tests and we'll use this issue to track fixing `pack --no-build` in a future release.

**Comment by musictopia2** [comment] 2021-11-16 17:21
For my stuff, I have to do nobuild because I have a process that i first do a build.  Then something detects the dll changes so it does a nuget pack.  However, if i did not use the nobuild, then it would do a build so it would be a never ending cycle.

**Comment by musictopia2** [comment] 2021-11-16 17:27
I do have one question.  If it gets released to an update to net 6, do i have to redownload the .net 6?  For projects, are there options to decide which patch to use for .net 6?  not sure how that part works.

**Comment by javiercn** [comment] 2021-11-16 17:29
SDKs release patches and normally they get installed with new Visual Studio versions. If you are running on a CI service, (like GH actions or Azure DevOps) I believe the patches get picked up automatically, if you are publishing from VS, when VS updates (for example 17.1) it will contain an updated SDK.

The SDK is also available as a standalone download after the patch version is released.

**Comment by javiercn** [comment] 2022-02-23 10:17
Using https://github.com/dotnet/aspnetcore/issues/40317 to track this issue moving forward

**Closed** 2022-02-23 11:24 UTC
Labels: bug, :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved, feature-static-web-assets
