### ISSUE TITLE
Published site fails to load (Internal Server Error 500) when publishing ASP.NET Core API to SCD.

### ISSUE THREAD

**Issue by v-wenkecheng** [dotnet/aspnetcore#48941] opened 2023-06-21 09:55 UTC
**Azure DevOps work item**:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1784967

### Version used
1. Install latest Dev17.7 Preview 3[[#main-33820.351](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7950335&view=ms.vss-build-web.run-extensions-tab)]
2. Install .NET 8.0 Preview 6 SDK from [GitHub - dotnet/installer](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fgithub.com%2fdotnet%2finstaller&data=04%7c01%7cv-meli4%40microsoft.com%7c7c321d6fae484b57ce0e08d9d41dde24%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637774047037391238%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=rVMCLxHkTMTRGwoiIwqnfihpuVCUMhuPn0KmnbnDKPQ%3D&reserved=0), main (8.0.x Runtime)
3. Feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json

### Steps To Reproduce

1. File > New Project > ASP.NET Core API > .NET 8.0 (Preview)
2. Build solution and publish to Azure App Service (Windows) > Self-contained

### Actual behavior
Published site failed to load.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
HTTP Error 500.30 - ASP.NET Core app failed to start

Common solutions to this issue:
The app failed to start
The app started but then stopped
The app started but threw an exception during startup

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more guidance on diagnosing and handling these errors, visit [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://go.microsoft.com/fwlink/?LinkID=2028526).

![image](https://github.com/dotnet/aspnetcore/assets/69494255/7c4e2e90-2e55-487a-8be9-2c046bd5841c)

### Expected Behavior

The published site loads correctly.

### Regression

ASP.NET Core API is new project template in .NET 8.0.
This issue is also reproduced in .NET 8.0 Preview 3 and later.

**Comment by martincostello** [comment] 2023-06-21 10:04
FYI the screenshot is of a 404, not a 500.

**Comment by v-wenkecheng** [comment] 2023-06-21 10:49
This issue is also reproduced in .NET 8.0 Preview 3.

**Comment by mitchdenny** [comment] 2023-06-21 13:31
Can you try replacing CreateSlimBuilder with CreateBuilder in Program.cs?

**Comment by Tratcher** [comment] 2023-06-21 17:27
Can you follow the initial debugging steps here:
https://learn.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-7.0#aspnet-core-module-debug-log-azure-app-service

**Comment by mitchdenny** [comment] 2023-06-22 01:51
I think the cause here is that the new ASP.NET Core API template was used which does not work with IIS because it uses ```CreateSlimBuilder(...)```.

**Comment by mitchdenny** [comment] 2023-06-22 01:52
Adding @DamianEdwards to consider the end to end scenario around the ASP.NET Core API template & usage within Azure Websites.

**Comment by DamianEdwards** [comment] 2023-06-22 01:58
Yep this is expected. The VS publish experience folks are aware of it but not clear if they intend to attempt to block it as it requires code introspection.

**Comment by adityamandaleeka** [comment] 2024-03-05 00:00
Closing since this is expected.

**Closed by adityamandaleeka** 2024-03-05 00:00 UTC
Labels: known-issue, area-networking
