### ISSUE TITLE
[Kestrel] Count all traffic per request, including headers

### ISSUE THREAD

**Issue by WhitePhoera** [dotnet/aspnetcore#46118] opened 2023-01-16 10:43 UTC
May be that must be feature request, but i hope it's possible to do that now as well.

I can count body, by replacing Request.Body and Response.Body with my own proxy.

But it is possible to count bytes for in/out for whole request?
in single request per connection that kinda possible via replacing transport.

But that will not work with keep-alive and http2 connections.

Any options exists?

**Comment by Tratcher** [comment] 2023-01-17 21:20
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/38918 and https://github.com/dotnet/aspnetcore/issues/38919.

**Closed** 2023-01-18 22:01 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Status: Resolved
