### ISSUE TITLE
SWA URLs reflect PackageId, not project name

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#26055] opened 2020-09-18 12:49 UTC
Let's consider the following Blazor project:

- BlazorApp1: is a server side Blazor app referencing "RazorClassLibrary1"
- RazorClassLibrary1: is a Razor Class Library with a custom JS file "exampleJsInterop.js"

With .Net5 Preview 8 referencing external components JS resources was like this (and it was working):
`<script src="./_content/RazorClassLibrary1/exampleJsInterop.js" defer></script>`

When Updated my project to .NET5 RC1 I started to get this error:
```
blazor.server.js:1 GET https://localhost:44347/_content/RazorClassLibrary1/exampleJsInterop.js net::ERR_ABORTED 404
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
beginInvokeJSFromDotNet @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:19 [2020-09-18T12:36:18.350Z] Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:44347/_content/RazorClassLibrary1/exampleJsInterop.js
TypeError: Failed to fetch dynamically imported module: https://localhost:44347/_content/RazorClassLibrary1/exampleJsInterop.js
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BlazorApp1.Pages.Index.OnAfterRenderAsync(Boolean firstRender) in C:\Users\Major\source\repos\BlazorApp1\BlazorApp1\Pages\Index.razor:line 17
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

I'm getting the same error with the new "imort" mechanism:
`await _runtime.InvokeAsync<JSObjectReference>("import", "./_content/RazorClassLibrary1/exampleJsInterop.js");`

According the documentation path should be: `_content/[LIBRARY NAME]/[PATH UNDER WWWROOT]`. Which looks good to me and was working before.

But turned out I'm also creating a Nuget package of the Razor Class Library "RazorClassLibrary1" on build. By updating the .csproj file with Nuget config. **Where I have changed the default value (assembly name) of the "PackageId" property.**

```
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>RazorClassLibrary.MyFirstComponent</PackageId>
  </PropertyGroup>
</Project>
```

**So it look like Nuget packaging a project with a different Package Id overrides resource importing. However I did not added the package as Nuget package still referencing the project itself from the same solution. Why is it happening?** 

And now it works like this (**note "RazorClassLibrary1" vs "RazorClassLibrary.MyFirstComponent"**):
`await _runtime.InvokeAsync<JSObjectReference>("import", "./_content/RazorClassLibrary.MyFirstComponent/exampleJsInterop.js");`

**Comment by nvmkpk** [comment] 2020-09-18 16:53
As far as I understand `[LIBRARY NAME]` in `_content/[LIBRARY NAME]/[PATH UNDER WWWROOT]` is the `PackageId` of the project. If you do not set `PackageId`, it defaults to the the `AssemblyName` value in csproj file. If `AssemblyName` is missing then it defaults to the project file name.

**Comment by majorimi** [comment] 2020-09-18 18:11
Yes, basically `[LIBRARY NAME]` changing its value when Project is packaged. However the assembly (.dll) and namespace was not changed. It is a bit confusing which name to use when this component referenced as a project or installed as a Nuget package?

**Comment by nvmkpk** [comment] 2020-09-19 20:41
It is just one name whether you reference it through a a project or as a nuget package. And that is what you set using PackageId property.

**Comment by majorimi** [comment] 2020-09-22 07:59
Ok so packaging the project and specifying custom PackageId will replace `[LIBRARY NAME]`. Got it.
However PackageId config gets written into the .csproj file when "Generate NuGet package on build" checkbox checked on the Properties tab of the project. And a custom PackageId supplied on the form. However the checkbox can be unchacked and custom PackageId is still configured. 

Should PackageId have any affect on `[LIBRARY NAME]` when Nuget packaging turned off?
`<GeneratePackageOnBuild>false</GeneratePackageOnBuild>`

Because it still renames `[LIBRARY NAME]`. Or it is totally independent of Nuget packaging?

**Comment by captainsafia** [comment] 2020-09-22 16:45
@javiercn Do we have docs clarifying how the library name is generated depending on how the PackageId property is set?

**Comment by SteveSandersonMS** [comment] 2020-10-07 10:35
Just to capture context, this is by design (since we want package and project references to behave the same, as it's more convenient not to force developers to switch between two different reference formats).

The remaining work here is to make sure this is mentioned in docs.

**Comment by javiercn** [comment] 2021-08-20 14:09
Filed a docs tracking issue, closing this one

**Closed by javiercn** 2021-08-20 14:09 UTC
Labels: task, Docs, area-blazor, feature-static-web-assets, affected-few, severity-minor
