### ISSUE TITLE
New Blazor client project from template in .Net 6.0 Preview 3 won't compile

### ISSUE THREAD

**Issue by joshmouch** [dotnet/aspnetcore#31810] opened 2021-04-14 19:12 UTC
I just installed the latest .Net 6.0 Preview 3, updated Visual Studio to the latest (16.9.4) and then created a new Blazor WebAssembly project from the Visual Studio template.

The resulting project will not compile.  The build window shows the following:

1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>CSC : warning CS8032: An instance of analyzer Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator cannot be created from C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
1>...\Program.cs(18,31,18,34): error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)

**Comment by mkArtakMSFT** [comment] 2021-04-14 19:33
Thanks for contacting us.
@captainsafia can you please take a look at this? Thanks!

**Comment by ByronAP** [comment] 2021-04-14 21:20
see also: #31788 worked out to be the same issue, occurs even on the latest nightly

**Comment by captainsafia** [comment] 2021-04-14 21:26
Are you able to reproduce the issues when building the same project in the CLI?

I wonder if this is particular to the build setup in VS.

**Comment by ByronAP** [comment] 2021-04-14 21:44
@captainsafia  CLI seems good so yes VS issue

**Comment by ByronAP** [comment] 2021-04-14 21:52
I do get a 404 on site.js but that may be something else

**Comment by mkArtakMSFT** [comment] 2021-04-15 16:32
Thanks for contacting us. Can you please try this out with the latest VS 2019 preview release and see whether you can still repro it.

**Comment by Keerthi-Mettu** [comment] 2021-04-16 19:07
Hi,

After installing the preview version, I got the target SDK mismatch error and I manually modified the version of SDK (from 5.0.201 to 6.0.100-preview.3.21202.5) in the global.json file in repos folder. 
Then I was getting the same error, warning messages, and not able to build the solution. 

After a while, the error seems to be gone (didn't modify anything) and this warning retains to fail the solution build. 
![image](https://user-images.githubusercontent.com/79932039/115069292-396bea00-9ea8-11eb-833c-567b140df2b2.png)

If I go ahead to run the project with this warning, it shows the following error page. 
![image](https://user-images.githubusercontent.com/79932039/115069667-c3b44e00-9ea8-11eb-9c0a-ecc487838e31.png)

I also tried to install the packages - Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.CSharp from Nuget, and still the warning persists. Here is my project specs file.
![image](https://user-images.githubusercontent.com/79932039/115072259-32df7180-9eac-11eb-9086-db509641e17a.png)


Help me out if anything looks solvable. Thanks

**Comment by captainsafia** [comment] 2021-04-16 19:10
@Keerthi-Mettu Are you using a preview version of VS along side the preview version of the SDK?

**Comment by Keerthi-Mettu** [comment] 2021-04-16 19:14
No, I'm using the latest VS Community version 16.9.4

**Comment by captainsafia** [comment] 2021-04-16 19:16
@Keerthi-Mettu Can you try using a preview of VS 16.10 to see if that resolves the issue?

**Comment by Keerthi-Mettu** [comment] 2021-04-16 19:43
I installed the VS Professional (Version 16.10.0 Preview 2.0) and created a Blazorwasm project. This time the build is successful but the following error is loading up.

HTTP Error 500.33 - ANCM Request Handler Load Failure

This is the output from the Build window:

Build started...
1>------ Build started: Project: BlazorWasmPreview3, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>BlazorWasmPreview3 -> C:\Users\KeerthiMettu\source\repos\BlazorWasmPreview3\BlazorWasmPreview3\bin\Debug\net6.0\BlazorWasmPreview3.dll
1>BlazorWasmPreview3 (Blazor output) -> C:\Users\KeerthiMettu\source\repos\BlazorWasmPreview3\BlazorWasmPreview3\bin\Debug\net6.0\wwwroot
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by captainsafia** [comment] 2021-04-16 19:45
@Keerthi-Mettu Yep -- that one is a different known issue with preivew3. It'll be resolved in preview4. In the meantime, it should be resolved if you use Kestrel to debug.

**Comment by nadavhury** [comment] 2021-04-20 19:33
Installing Hosting bundle and adding 
<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
under <PropertyGroup> like so >
![image](https://user-images.githubusercontent.com/1974430/115453376-3cf4cd80-a228-11eb-8bc4-a46f321ba13d.png)
fixed the ANCM Load Failure.

**Closed** 2021-04-29 01:00 UTC
Labels: External, Needs: Author Feedback, Status: No Recent Activity, area-blazor, blazor-wasm, feature-razor-sdk, investigate
