### ISSUE TITLE
Problem providing Access Token to HttpClient in Interactive Server mode

### ISSUE THREAD

**Issue by RobJDavey** [dotnet/aspnetcore#52390] opened 2023-11-27 11:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When making authenticated requests in InteractiveServer mode, a user's access token is required to talk to an external service. As the guidance is that it is not safe to use the `IHttpContextAccessor` when in server interactive mode, I have been following the documentation to try and add a token provider servicer.

I've followed the documentation guides below, however the access token on the token provider in interactive server mode always comes through as `null`. I'm unsure if I have misunderstood or missed something in these guides or if the guides do not currently lead to a complete solution.

* [Server-side ASP.NET Core Blazor additional security scenarios](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0)
  * [Pass tokens to a server-side Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#pass-tokens-to-a-server-side-blazor-app)
  * [Set the authentication scheme](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#set-the-authentication-scheme)
  * [Access AuthenticationStateProvider in outgoing request middleware](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#access-authenticationstateprovider-in-outgoing-request-middleware)
* [ASP.NET Core Blazor dependency injection](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0)
  * [Access server-side Blazor services from a different DI scope](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0#access-server-side-blazor-services-from-a-different-di-scope)

The sample project I have attached tries two different approaches to get this access token.

The first is the inject the `TokenProvider` into the `WeatherService`, and grab the token from it there. This works fine when using server side rendering, but the token is `null` when in interactive server mode.

The second is to try use a circuit handler to set the correct services for the circuit, allowing it to access the `TokenProvider` from inside other services by injecting the `CircuitServicesAccessor`. The circuit handler however never seems to get the `CreateInboundActivityHandler`, and so I have been unable to test whether the `TokenProvider` it would provide would contain a `null` access token or not.

### Expected Behavior

When a HttpClient request is made in InteractiveServer mode, the `TokenProvider` configured in the `App` component should be passed to the `WeatherService` class so it can be used to set the `Authentication` header.
Alternatively, the `AuthenticationStateHandler` class should get the `CircuitServicesAccessor` set by the `ServicesAccessorCircuitHandler`, which can then be used to access the `TokenProvider` class to get the token.

### Steps To Reproduce

I have created a sample solution which shows what I have attempted so far:
https://github.com/RobJDavey/BlazorTokenIssue

The [README](https://github.com/RobJDavey/BlazorTokenIssue/blob/main/README.md) explains how to run the solution. While there are 3 projects in the solution, 2 of them are purely there to support the demonstration, it's only the [BlazorApp](https://github.com/RobJDavey/BlazorTokenIssue/tree/main/BlazorApp) service that is at issue.

To authenticate, please user the either username and password `alice`/`alice` or `bob`/`bob` as these are the test users configured.

The SSR page always loads the data from the external service fine, however the Interactive Server page fails due to the missing token.

### Exceptions (if any)

A 401 is returned by the service when no valid access token is attached.
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BlazorApp.Services.WeatherForecastService.GetForecastAsync(Int32 skip, Int32 take) in ./BlazorApp/Services/WeatherForecastService.cs:line 34
   at BlazorApp.Components.Pages.WeatherInteractive.<OnInitialized>b__8_0(GridItemsProviderRequest`1 request) in ./BlazorApp/Components/Pages/WeatherInteractive.razor:line 47
```

### .NET Version

8.0.100

### Anything else?

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31113

**Comment by gragra33** [comment] 2023-11-27 12:51
Have you looked at using a [DelegatingHandler](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.delegatinghandler?view=net-8.0) to manage this? Here is a YouTube video by @m-jovanovic that shows you how: [Middleware Pattern For HttpClient With Delegating Handlers](https://www.youtube.com/watch?v=_u6v4D6qgDI).

**Comment by RobJDavey** [comment] 2023-11-27 13:48
@gragra33 yes I do have a DelegatingHandler in the project: https://github.com/RobJDavey/BlazorTokenIssue/blob/main/BlazorApp/AuthenticationStateHandler.cs
 
This does not appear to get given the configured `TokenProvider` when running in interactive mode though.

Based on [this guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#ihttpcontextaccessorhttpcontext-in-razor-components), as this handler could be called from an interactive context, it cannot just grab the token off the `HttpContext` which is why the `TokenProvider` approach appears to be necessary.

**Comment by gragra33** [comment] 2023-11-27 14:24
@RobJDavey based on your implementation `TokenProvider` will always have null values.

```cs
namespace BlazorApp.Services;

public class TokenProvider
{
    public string? AccessToken { get; set; }
    public string? RefreshToken { get; set; }
}
```

```cs
builder.Services.AddScoped<TokenProvider>();
```

You should have a `TokenProviderFactory` class to populate and return a `TokenProvider`, typically, values are stored in the `appsettings.json`. This is mentioned, in a more simpler way, in the above YouTube video. Here is the timestamped position in that video: [Middleware Pattern For HttpClient With Delegating Handlers @ 3:10](https://youtu.be/_u6v4D6qgDI?t=190)

Here is what your implementation should be:

```cs
public class TokenProviderFactory
{

    private IServiceProvider _serviceProvider;

    public TokenProviderFactory(IServiceProvider serviceProvider)
        => _serviceProvider = serviceProvider;

    public GenerateTokenProvider<TSettings>() where TSettings : IProviderSettings
    {
        var settings = _serviceProvider.GetRequiredService<IOptions<TSettings>>().Value;
        return new TokenProvider()
            {
                AccessToken  = settings.AccessToken;
                RefreshToken = settings.RefreshToken;
            };
    }
}
```

remove:

```cs
builder.Services.AddScoped<TokenProvider>();
```

and replace with:

```cs
builder.Services.AddScoped<TokenProviderFactory>();
```

now update:

```cs
var tokenProvider = _circuitServicesAccessor.Services?.GetRequiredService<TokenProviderFactory>().GetRequiredService<GitHubSettings>();;
```

*Note: the above code is typed freehand here and not tested but should work as-is. I am sure that there is enough there to help solve your issue.

**Comment by RobJDavey** [comment] 2023-11-27 14:31
@gragra33 the token provider is not for client access tokens, but user tokens retrieved at login via OpenIDConnect, so they cannot be stored in settings.

The token provider is configured to have the current user's access token in the [App component](https://github.com/RobJDavey/BlazorTokenIssue/blob/main/BlazorApp/Components/App.razor#L33) which is based on [this guide](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#pass-tokens-to-a-server-side-blazor-app).

This works fine in server side scenarios, but not in interactive.

**Comment by gragra33** [comment] 2023-11-27 14:41
@RobJDavey I have not run your code, so I did not dig that deeply. Now I have.

However, have you set a breakpoints in:
1. `WeatherForecastService` - when the `TokenPrivder` is being populated
2. `AuthenticationStateHandler` - when the `TokenPrivder` is being used

Is the `TokenProvider` being set before being used in `AuthenticationStateHandler`?

I would also add a constructor in the `TokenProvider`, with a breakpoint, to check when it is being created and if it is occurring more than once.

**Comment by gragra33** [comment] 2023-11-27 18:58
@RobJDavey I noticed that @mkArtakMSFT tagged your issue with `Doc`. It made me curious, so I downloaded your solution and ran it.

I set a breakpoint in the `OnInitializedAsync` method in the `App.razor` component, `OnInitialized` method in the `WeatherInteractive.razor` component, and in the `GetForecastAsync` method in `WeatherForecastService`. I then navigated to the page. and observe the order of breakpoints being hit.

What I observed was that the component was created twice. The first time, your token was passed correctly, the `OnInitialized` was called, and the data was collected from your server via the `WeatherForecastService`. The second time, the `OnInitialized` was called, as it was a new instance, no token was passed to the new `WeatherForecastService`  instance, and you obviously received a `401` response, as you should. So when you navigate to the `WeatherInteractive` page, I am seeing the following sequence of breakpoints being hit:

```text
App.razor                // new instance and sets token
WeatherInteractive.razor // initialised
WeatherForecastService   // set token is passed
WeatherInteractive.razor // initialised (again) / new instance
WeatherForecastService   // new instance and empty token is passed
```

This is happening when NavManager is used (via the NavLink component) and also with a regular anchor html element.

This does not happen with `StreamRendering`. So when you navigate to the `WeatherSsr` page, I am seeing the following sequence of breakpoints being hit:

```text
App.razor              // new instance and sets token
WeatherSsr.razor       // initialised
WeatherForecastService // set token is passed
```

If I set the render mode to no prerender:

```html
@rendermode @(new InteractiveServerRenderMode(prerender: false))
```

... then  I am seeing the following sequence of breakpoints being hit:

```text
App.razor                // new instance and sets token
WeatherInteractive.razor // initialised
WeatherForecastService   // new instance and empty token is passed
``` 

I have not isolated why this is happening with your code and there is no simple work-around that I can see. I am not sure if this is a bug or by-design. Someone from Microsoft will have to chime in.

**Comment by gragra33** [comment] 2023-12-06 21:46
@RobJDavey @wesleyscaldwell There is this recent blog post [Per-User Blazor 8 State](https://blog.lhotka.net/2023/11/28/Per-User-Blazor-8-State) by @rockfordlhotka. I have not tried this, due to a recent emergency that we are still resolving, however this looks like a possible interim solution until Microsoft releases one.

**Comment by wesleyscaldwell** [comment] 2023-12-06 22:18
I haven't read the full post but my understanding from the intro is that if I disable the prerender and use only interactive I should be good. 

This is a start up project and I'm just trying to get it going. Once we have more usage I can focus on optimizations. 

If this works I'll report back.

**Comment by wesleyscaldwell** [comment] 2023-12-07 12:34
@gragra33 I tested this by disabling prerendering in hopes of a quick solution and all that did was disable the rendering portion, but the underlying DI scopes remain the same. The initial scope is created and return the UI and then the socket scope starts up without the context. 

So the [Per-User Blazor 8 State](https://blog.lhotka.net/2023/11/28/Per-User-Blazor-8-State) by @rockfordlhotka option is exactly what i was thinking, but he has clearly covered this in a much more extensive way. 

But after reading it all, I find that when I'm this far down a rabbit hole on something that I have to imagine would be a common request, I have to think i'm missing something. 

**Is there any chance we have all missed some other option that makes it possible to share the scope between the prerender and the interactive session?**

In the meantime, I am going to make use of what @rockfordlhotka has started on and store user properties in a singleton.

**Comment by pockets3407** [comment] 2023-12-07 16:39
I just implemented a simplified version of [Per-User Blazor 8 State](https://blog.lhotka.net/2023/11/28/Per-User-Blazor-8-State) (I am not using wasm) and it seems to be working fine. I agree with @wesleyscaldwell that it feels like we are missing something about sharing scope between prerender and the interactive session.

**Comment by wesleyscaldwell** [comment] 2023-12-07 20:11
I implemented a similar process. But I decided to add unique session id user claim on the OIDC OnUserInformationReceived Event. This then enables to me get the session from the session service as in the repo you referenced. 

Having a unique session ID added by default would have saved a lot of the difficulty of this task.

My implementation is buried deep now in other code, but i can strip it out if anyone thinks it would be helpful to see.

**Comment by halter73** [comment] 2023-12-14 23:28
We'll look into how we can make it easier to retrieve saved access tokens from interactive server components in .NET 9, but I do think that reading the access token from the `HttpContext` using the `IHttpContextAccessor` is a reasonable approach for getting the access token during interactive server rendering. It won't update if the user authenticates after the circuit is established since the `HttpContext`, and its use of async local means that you have to be careful not to lose the execution context before reading it, but otherwise it should work fine.

I'll also look into updating the https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#pass-tokens-to-a-server-side-blazor-app doc to either use `IHttpContextAccessor` with caveats and/or use [PersistentComponentState](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#pass-tokens-to-a-server-side-blazor-app) to transfer the token retrieved from the cascading `HttpContext` during static rendering to the interactively rendered components.

**Comment by wesleyscaldwell** [comment] 2023-12-15 01:59
My opinion is that having a session token to be referenced between the signalr connection and the httpcontext would enable a lot of use cases beyond just the access token. 

In my case I wanted the session ID for an authenticated user. But I could even see an instance where you want a session ID synced between the two for non authenticated users. 

And I could also see the signalr connection starting before the authenticated context is available. But I might be recalling that you need to reload the UI after authenticating. 

I am relatively new to blazor. So I be overlooking some basic details in my response.

**Comment by rsandbach** [comment] 2023-12-15 05:37
@RobJDavey / @halter73 

Is not being able access the `TokenProvider` instance created during prerender related to `CreateInboundActivityHandler` not being being dispatched (#51934) and (#52379)? If the override was being called, couldn't the same pattern used by [AuthenticationStateProvider](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#access-authenticationstateprovider-in-outgoing-request-middleware) to get the `AuthenticationStateProvider` instance be used to get the initial `TokenProvider` instance?

**Comment by rockfordlhotka** [comment] 2023-12-15 14:42
> @RobJDavey / @halter73
> 
> Is not being able access the `TokenProvider` instance created during prerender related to `CreateInboundActivityHandler` not being being dispatched (#51934) and (#52379)? If the override was being called, couldn't the same pattern used by [AuthenticationStateProvider](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#access-authenticationstateprovider-in-outgoing-request-middleware) to get the `AuthenticationStateProvider` instance be used to get the initial `TokenProvider` instance?

Right now `AuthenticationStateProvider` isn't available (or usable) when using server-rendering. A runtime exception is thrown when you try to use this service in that context.

**Comment by halter73** [comment] 2023-12-16 01:34
> Right now `AuthenticationStateProvider` isn't available (or usable) when using server-rendering. A runtime exception is thrown when you try to use this service in that context.

If you're migrating from `AddServerSideBlazor()` to `.AddRazorComponents().AddInteractiveServerComponents()`, this is probably happening because `.AddRazorComponents()` doesn't call `services.TryAddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>()` for you [like `AddServerSideBlazor()` does](https://github.com/dotnet/aspnetcore/blob/1ee90c23a8f97065ea9eb60cca5271c4ff3845f9/src/Components/Server/src/DependencyInjection/ComponentServiceCollectionExtensions.cs#L85).

You can just call `builder.Services.TryAddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>()` yourself. [ServerAuthenticationStateProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.server.serverauthenticationstateprovider?view=aspnetcore-8.0) is a public type. That's what the templates do for local auth and static rendering only. Although the templates use custom AuthenticationStateProviders for interactive scenarios so it can revalidate the security stamp while the SignalR circuit is active and transfer AuthenticationState to the WASM renderer.

https://github.com/dotnet/aspnetcore/blob/1ee90c23a8f97065ea9eb60cca5271c4ff3845f9/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Program.cs#L39-L47

**Comment by rockfordlhotka** [comment] 2023-12-18 01:57
@halter73 then there's something missing in the Blazor Web App template, because it _does_ set up server-rendered, server-interactive, and wasm-interactive models. And in that template, if you try to access the `AuthenticationStateProvider` from server-rendered code you get a runtime exception saying that you can't use that type if you aren't in a Blazor interactive context.

**Comment by rockfordlhotka** [comment] 2023-12-19 17:47
Yes, like many (most?) people, I have assemblies that include business rules that depend on having access to the current user identity.

Putting such business logic directly in the UI is what has gotten us in trouble since VB3, and is a bad practice.

Until now, it has been possible to gain access to the current user from any code in an app - via the current thread, HttpContext, ApplicationStateProvider, or other means depending on which .NET environment is hosting the code.

This includes Blazor interactive modes, where `AuthenticationStateProvider` is a service that can be injected into any service to gain access to the user identity.

Right now, in Blazor 8, it appears that the solution (for server code) is to detect whether a circuit is active, so `AuthenticationStateProvider` is available, and to fall back to using `HttpContext` otherwise. 

This is my prototype solution: 

https://github.com/MarimerLLC/csla/blob/6d159d2d8bf1f515646caaac88971d053a3af3ba/Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs#L69

**Comment by mkArtakMSFT** [comment] 2024-01-11 18:09
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/52379

**Closed by mkArtakMSFT** 2024-01-11 18:09 UTC
Labels: bug, area-blazor, Pillar: Complete Blazor Web

**Comment by michelkommers** [comment] 2024-11-07 15:48
@halter73 I am struggling with setting up a Wasm + SSR (ExcludeFromInteractiveRouting) + prerender + Client Side MSAL Auth with AD B2C ( without Blazor server interactivity). 

In other words, a setup that runs on wasm only and is pre-rendered in SSR without auth working, but the auth must work on the client side only, so we can refresh tokens and etc etc without depending on the server side.

Right now, the issue seems that it never uses msal and tries to use the server side or gives error while attempting to convert one auth provider to other etc... this worked back in .net 5 with a super odd setup that i tried to put in .net 8 but doesn't work, tested with .net 9 RC 2 and same thing.

Can you provide a guide for this setup using .net 9?

Putting @guardrex because I didn't find that setup in any docs (and it was previously supported in .net 5 I think, and it seems that the docs that covered that were removed)

**Comment by clRecruitment21** [comment] 2025-01-13 10:11
I am here look at and reading this because we need to retrieve the access_token from httpContext and *some times* and only ever  in Firefox, http context isn't availible.

I have read that using http context isn't recommended, and am exploring the circuithandler solution.

The access token is not available in the AuthenticaitonStateProvider. I thought about capturing the token, it isn't clear which lifecyle i could use that starts off with a http context, and goes on to become a circuit handler. It also feels like i'd l'd need to call something like a 'settoken' in those early stages - and that feels icky.

Hopefully the Circuit Handler fix here helps - or if anyone can give a strong nudge on the Authentication State being able to help?
