### ISSUE TITLE
JSInvokableAttribute inheritance

### ISSUE THREAD

**Issue by DaRochaRomain** [dotnet/aspnetcore#19365] opened 2020-02-26 13:19 UTC
### Is your feature request related to a problem? Please describe.
Currently, the JSInvokableAttribute applied to an abstract method isn't applied to the implemented method. So, for each implementation, we have to add this attribute again to avoid a runtime exception.

### Describe the solution you'd like
Is it possible to add Inherited = true to the AttributeUsage in order to fix it?

**Comment by javiercn** [comment] 2020-02-26 13:32
@DaRochaRomain thank for contacting us.

This might work, but there might be some conflicts with regards to how we discover JSInvokable methods that might cause issues, as the method name needs to be unique across the assembly, but that is something that might only apply to static method calls.

@SteveSandersonMS any thoughts?

@mkArtakMSFT I'm putting this on 5.0.0-preview2 for discussion at that time.

**Comment by SteveSandersonMS** [comment] 2020-02-27 15:26
The name only has to be unique for static methods, so `abstract`/`virtual` isn't applicable there.

I can't immediately think of any clear and indisputable reason why it would be bad to do this, but we'd have to check carefully that it couldn't reasonably break anyone.

If someone was being extremely strict about it, they could argue that making this change might open up someone's code to unexpected JS invocations if, for some bizarre reason, they had chosen to put `[JSInvokable]` onto a virtual method but didn't really want it to be invocable on derived types.

**Comment by javiercn** [comment] 2020-02-27 15:49
@SteveSandersonMS yeah, you are right. We wanted the dev to be explicit as there are security implications here.

**Comment by javiercn** [comment] 2020-02-27 15:49
Closing this issue as the current behavior is by design.

**Closed by javiercn** 2020-02-27 15:49 UTC
Labels: area-blazor, enhancement
