### ISSUE TITLE
Regression: Blazor component type not generated when filename contains `{`

### ISSUE THREAD

**Issue by JeroenBos** [dotnet/aspnetcore#34694] opened 2021-07-25 11:25 UTC
### Describe the bug
In short: there's a regression in .NET 6 preview 2 in types generated by blazor when the file contains special characters (`{`, in my case). It seems the (generated) type representing the component does not exist in the assembly at all.

### To Reproduce
I've created a minimal project and [hosted it on GitHub](https://github.com/JeroenBos/bug_in_test_discovery).
You can clone it and run `dotnet test`. 

#### Explanation

The project targets both .NET 5 and .NET 6. In .NET 5 and .NET 6 preview 1, the tests run successfully. In .NET 6 preview 2 through 6 one test will fail, demonstrating the issue. 
The issue is that my blazor component is not even emitted to the assembly, I suspect (demonstrated by the test in `FindTest.cs`). A consequence of this issue is that the test `xunit_bug_testfilter.RazorTests` is not discovered in `dotnet test` or the test explorer.

Crucial to note is that the razor file contains the character `{`, which in preview 1 is translated into `_` for the generated type name. In the other previews any such type is missing. If I replace that character then everything works as expected.

#### Motivation

I run into this when upgrading my project from .NET 5.0 to .NET 6.0. I was using `.razor` files for testing (in the style of [BUnit](https://bunit.dev/)) with special characters in the file name, e.g. `{`. I noticted that those tests weren't being run in prevew 6, i.e. executing them from the test explorer resulted in no action, only the output `No test matches the given testcase filter "xunit_bug_testfilter.RazorTests"`. I initially thought it might have to do with test discovery, but ultimately test discovery is correct: there's not even a related type in the assembly (from preview 2 onwards). 

Furthermore, I can't find any mention that this would be by design in e.g. the [Preview 2 announcement](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-2/), hence this bug report. 

### Further technical details
- IDE version: VS 2019/16.10.4
- Output of `dotnet --info`
<details>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App

</details>

**Comment by mkArtakMSFT** [comment] 2021-07-26 16:23
Thanks for contacting us. This is a dupe of #33832

**Closed by mkArtakMSFT** 2021-07-26 16:23 UTC
Labels: area-blazor, area-razor.compiler
