### ISSUE TITLE
Roadmap for full implementation of Blazor WASM debugging

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/aspnetcore#30598] opened 2021-03-03 17:09 UTC
A roadmap of the current limitations of WASM debugging (and planned updates) would be great for making architectural decisions about when it's appropriate to adopt Blazor, and to properly estimate the additional costs that might be incurred until the debugging tools reach maturity. 

The current state of debugging tools for Blazor are inferior to alternatives and add significant cost to development and maintenance. We've come to rely on output traces as the primary means of debugging because it's the most reliable - getting the debugger to provide useful information is often more work than fixing the _actual_ bug. While there's some debugging functionality, it's too unreliable to use consistently. If Blazor is going to be a serious contender for desktop application frameworks, it must provide at least the same debugging experience as its predecessors (WPF, WinForms, etc).

We've run into too many issues to reasonably enumerate, but to highlight a few:
- Breakpoints take a few seconds to attach, meaning there are some things that happen too quickly to test because the debugger is not attached. When debugging, execution should pause until the debugger is attached.
- There are many instances where WASM will not respect the breakpoint (e.g. Expression-bodied-members) and VS doesn't communicate to the developer that the breakpoint can't / won't be hit (normally VS will show as a hollow circle at runtime).
- Many variables, fields, and members are inaccessible from watch / immediate / local. You can sometimes work around this by promoting the value to a local variable, but this requires the developer make code changes, rebuild, and restart debugging every time a new watch is added.

**Comment by mkArtakMSFT** [comment] 2021-03-03 17:51
Thanks for contacting us.
Blazor Desktop will not involve WebAssembly in any way so the concerns related to Blazor WebAssembly debugging aren't applicable to it and the experience will be very similar to debugging ASP.NET Core server apps.

As for your concerns regarding debugging Blazor WebAssembly apps, we are definitely interested in learning more about these. If you have a prioritized list of issues you've faced please share those in that order. We will follow up on these separately.

**Comment by daniel-p-tech** [comment] 2021-03-03 19:34
I have to concur - WASM debugging experience is frustrating and definitely not of the quality that developers expect from Microsoft. It has been almost a year since the official release with virtually no improvements in this fundamental aspect of Blazor development.

https://github.com/dotnet/aspnetcore/issues/26290

**Comment by RobertBouillon** [comment] 2021-03-03 20:48
@mkArtakMSFT Thanks for the prompt reply.

That's very disappointing to hear. 

The limitations of Razor component rendering forces us to rely on JavaScript to manipulate the DOM in many cases. This creates a myriad of problems as JS and Blazor can step on each other. This also introduces [interop marshalling constraints](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0), some of which we tried to avoid with sync JS calls in pure WASM, only to encounter debugging problems. 

The list of issues I provided is the best I have (i.e. the most time I'm willing to invest). I'm confident the individuals who implemented the current debugger could provide a more detailed view of its current limitations than me.

It may just be time for an architecture change; Blazor makes sense if C# is going to replace JS - but if Blazor Desktop is just going to be this ASP.NET Core stack, where the only way to directly manipulate the DOM is JS interop, Angular/Electron or WPF makes more sense. 

Ideally we would have an HTML presentation layer with a C# logic layer in the same process space. Is it really that difficult? Burying an ASP.NET web server in an browser with a dependency on JS seems inferior to pretty much every existing alternative.

**Comment by captainsafia** [comment] 2021-03-03 21:20
We're currently investigating/resolving a few different issues with Blazor WASM debugging. When it comes to reporting a bug, the best thing to do is open an issue identifying a failure with a repro and some information about the environment you ran into that bug in. This info will help us root cause/prioritize/resolve issues quickly.

We've shipped some improvements for debugging in .NET 5 and have plans for more fixes in .NET 6. At the moment, we document supported/unsupported scenarios in [our docs page](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio). If something looks missing from that list, filing a bug report with the complete details will help us get to the bottom of it quickly.

**Comment by RobertBouillon** [comment] 2021-03-03 23:46
#30628
#30625
#30623
#30622
#30620

I'll add some more tomorrow as I resume debugging our application.

**Comment by mkArtakMSFT** [comment] 2021-03-08 17:45
Thanks for all the individual issues.
We're closing this as we now have all the individual tracking ones instead.

**Closed by mkArtakMSFT** 2021-03-08 17:45 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-debugging
