### ISSUE TITLE
Issues with documented 'build from source' flow on Debian

### ISSUE THREAD

**Issue by kg** [dotnet/aspnetcore#13689] opened 2019-09-04 22:13 UTC
### Describe the bug
Since I can't build from source on Windows I'm trying to build from source on Debian. The currently documented steps don't appear to work for my configuration.

### Steps taken
https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md says I need all the linux prerequisites, listed at https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites. I attempted to follow the steps there and they failed.

### Screenshots
![image](https://user-images.githubusercontent.com/198130/64295438-f99bfd00-cf25-11e9-9dc0-2938a648340e.png)

### Additional context
I'll be updating this one based on my ongoing troubleshooting. Presently: 3 of the packages listed for ubuntu are missing (libssl1.0.0 has been deprecated and gone for a while...).
The prereqs only appear to go up to netcore 3.x, while building from source (as far as i can tell) needs 5.x.

```sudo ./dotnet-install.sh -c Current``` did work though, but it doesn't install the prereqs and I'm not sure it installed the correct sdk. It looks like it installed dotnet-sdk-2.2.301                                                   based on stdout.

Debian version:
```kate@reeir-debian2:~$ lsb_release -a                                                                     
No LSB modules are available.                                                                            
Distributor ID: Debian                                                                                   
Description:    Debian GNU/Linux 9.9 (stretch)                                                           
Release:        9.9                                                                                      
Codename:       stretch
```
The prereqs page lists the requirement as debian 9.

**Comment by kg** [comment] 2019-09-04 22:27
Some more notes:

The scripts don't identify outdated nodejs. Installing from packages doesn't give you a current node in PATH (not aspnetcore's fault, but maybe worth detecting) - you need to go download packages from the nodejs site and identify the right version.

The scripts also don't seem to notice a missing JDK on linux. Getting a current JDK on linux is kinda nonobvious, it may be worthwhile to link to the instructions (https://openjdk.java.net/install/)

Without carefully doing the above build.sh fails with a cryptic error about blazor part-way through the build, so it might be worthwhile to update the docs given that you can 'have' node and the JDK but accidentally not have a new enough build. The package manager versioning for node is weird and modern JDKs aren't always available in the OS package manager at all, they weren't for me.

After messing about with the above and some other things I got build.sh to succeed, so that's a good sign and I think all that's potentially necessary is documentation updates because I don't think the average user is necessarily going to figure out where to get the right netcore SDK, etc.

I'm going to continue testing all the important workflows to see if everything else is OK.

**Comment by kg** [comment] 2019-09-04 23:12
Tests seem to succeed on linux after all these steps, at least up until the point where the blazor tests start. Those hang/deadlock. So I think other than some gaps/errors in the instructions from-source builds on Linux are still working fine.

**Comment by Pilchie** [comment] 2019-09-06 03:33
Tagging @aspnet/build.  @mkArtakMSFT We'll probably need help from someone who understands the Blazor build and dependencies for some of those issues though.

**Comment by dougbu** [comment] 2019-09-06 04:02
> It looks like it installed dotnet-sdk-2.2.301 based on stdout.

The installation installs a .NET Core runtime or two in addition to the SDK.

----
Agreed that `build.sh` should just work in this repo. We also appreciate your comments about improving the documentation on NodeJS and JDK requirements. To help in that, could you please provide details on the following e.g. which tests hang?
> cryptic error about blazor

> up until the point where the blazor tests start. Those hang/deadlock

**Comment by dougbu** [comment] 2019-09-06 04:03
Forgot to ask: What branch are you building?

**Comment by kg** [comment] 2019-09-06 21:42
I'm building using a source checkout on the master branch.

I think the test that hangs is a libuv test, the blazor was a red herring (blazor tests were the last ones to run immediately before the hang).

```
  Libuv.BindTests -> /home/kate/Projects/AspNetCore/artifacts/bin/Libuv.BindTests/Debug/netcoreapp5.0/Libuv.BindTests.dll
  Running tests: /home/kate/Projects/AspNetCore/artifacts/bin/Libuv.BindTests/Debug/netcoreapp5.0/Libuv.BindTests.dll [netcoreapp5.0|x64]
```

ps auxf shows this as the hung process:
```
/home/kate/Projects/AspNetCore/.dotnet/dotnet exec --depsfile /home/kate/Projects/AspNetCore/artifacts/bin/Libuv.BindTests/Debug/netcoreapp5.0/Libuv.BindTests.deps.json --runtimeconfig /home/kate/Projects/AspNetCore/artifacts/bin/Libuv.BindTests/Debug/netcoreapp5.0/Libuv.BindTests.runtimeconfig.json /home/kate/.nuget/packages/xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll /home/kate/Projects/AspNetCore/artifacts/bin/Libuv.BindTests/Debug/netcoreapp5.0/Libuv.BindTests.dll -noautoreporters -xml /home/kate/Projects/AspNetCore/artifacts/TestResults/Debug/Libuv.BindTests_netcoreapp5.0_x64.xml -html /home/kate/Projects/AspNetCore/artifacts/TestResults/Debug/Libuv.BindTests_netcoreapp5.0_x64.html -notrait Flaky:All=true -nocolor
```

If I ctrl-c the hung tests I get this:
```
/home/kate/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19411.1/tools/XUnit/XUnit.targets(89,5): warning MSB5021: Terminating the task executable "sh" and its child processes because the build was canceled. [/home/kate/Projects/AspNetCore/src/Servers/Kestrel/test/Libuv.BindTests/Libuv.BindTests.csproj]
XUnit : error : Tests failed: /home/kate/Projects/AspNetCore/artifacts/TestResults/Debug/Sockets.FunctionalTests_netcoreapp5.0_x64.html [netcoreapp5.0|x64] [/home/kate/Projects/AspNetCore/src/Servers/Kestrel/test/Sockets.FunctionalTests/Sockets.FunctionalTests.csproj]
    1 Warning(s)
    1 Error(s)
```

**Comment by dougbu** [comment] 2019-09-07 02:38
@halter73 we have a fair number of internal issues about LibUV test failures. Are any of the current ones related to test hangs?

**Comment by jepperaskdk** [comment] 2020-07-12 13:27
While perhaps not related to the issues described above, is it possible to get more details on the installation steps at:
_"Run the installers produced in artifacts/installers/{Debug, Release}/ for your platform."_

(Ubuntu 18.04)

**Comment by dougbu** [comment] 2020-10-21 22:29
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2020-10-21 22:29 UTC
Labels: area-infrastructure
