### ISSUE TITLE
ASP00023 fails on multiple `HttpGet("[action]")]`

### ISSUE THREAD

**Issue by phatt-millips** [dotnet/aspnetcore#52770] opened 2023-12-12 18:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running dotnet format on our project (recently converted from .NET 7 to .NET 8) dotnet format throws `Unable to fix ASP0023. No associated code fix found.` This seems to be related to it finding multiple `HttpGet("[action]")]` annotations.

### Expected Behavior

Does not throw an error

### Steps To Reproduce

Set up a project with two endpoints with the annotation of `HttpGet("[action]")]` then run dotnet format

### .NET Version

8.0.100

**Comment by martincostello** [comment] 2023-12-12 19:38
Duplicate of #49777.

**Comment by captainsafia** [comment] 2023-12-12 20:25
@JamesNK I notice we keep getting bug reports on this. Do you think it is worth back porting the fix to 8.0?

**Comment by JamesNK** [comment] 2023-12-12 23:03
It will be in 8.0.1

https://github.com/dotnet/aspnetcore/pull/52034

**Closed** 2023-12-13 18:55 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-mvc, analyzer
