### ISSUE TITLE
Rate Limiting: Support for multiple policies on the same endpoint

### ISSUE THREAD

**Issue by cristipufu** [dotnet/aspnetcore#44907] opened 2022-11-06 13:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to be able to apply two or more policies on the same endpoint (for example I would like to limit the maximum of concurrent requests and at the same time allow only maximum X requests in a fixed window):

Right now he `RateLimitingMiddleware` only supports one policy per endpoint:
```C#
private PartitionedRateLimiter<HttpContext> CreateEndpointLimiter()
{
    ...
    var enableRateLimitingAttribute = context.GetEndpoint()?.Metadata.GetMetadata<EnableRateLimitingAttribute>();
    ....
    policy = enableRateLimitingAttribute.Policy;
    if (policy is not null)
    {
        return policy.GetPartition(context);
    }
    var name = enableRateLimitingAttribute.PolicyName;
    if (name is not null)
    {
        if (_policyMap.TryGetValue(name, out policy))
        {
            return policy.GetPartition(context);
        }
    ....     
}
```

In order to make this work right now, I think that one would have to:
- Create a new `CustomEnableRateLimiting` attribute.
- Create a new `CustomRateLimitingMiddleware` and copy paste most of the logic there.
- Create something to cache the partitions/rate limiters (the `DefaultPartitionedRateLimiter` only supports an expression for a single partition)
- Each time a request is invoked, maybe create a new `ChainedPartitionedRateLimiter` with the cached rate limiters based on the endpoint's policies

or 
- Create a new `CustomRateLimiter` on top of those built-in rate limiters + a new `CustomRateLimiterPolicy` that uses the rate limiter

Is there an easier/cleaner way to achieve this that maybe I'm missing?

### Describe the solution you'd like

```C#
[EnableRateLimiting("policy_fixed_window", "policy_concurrency")]
public class DemoController : ControllerBase
```

```C#
builder.Services.AddRateLimiter(options =>
{
    options.AddConcurrencyLimiter("policy_concurrency", (opt) =>
    {
        opt.PermitLimit = 2;
    });

    options.AddFixedWindowLimiter("policy_fixed_window", (opt) =>
    {
        opt.PermitLimit = 1;
        opt.Window = TimeSpan.FromSeconds(2);
    });
});
```

**Comment by Kahbazi** [comment] 2022-11-07 07:32
Possible Duplicate of https://github.com/dotnet/aspnetcore/issues/42691

**Closed** 2022-11-09 01:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Status: Resolved
