### ISSUE TITLE
Incompatible with UI client as angular version 16 with module federation plugin

### ISSUE THREAD

**Issue by RaneeshTK** [dotnet/aspnetcore#49775] opened 2023-08-01 16:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

localhost/:1 Uncaught TypeError: Failed to resolve module specifier "module". Relative references must start with either "/", "./", or "../".

with webpack module federation for bundling.

Issue for using the microsoft/signalR package in angular app version 16 with webpack module federation plugin

**Comment by RaneeshTK** [comment] 2023-08-03 10:20
@BrennanConroy Please find the attached link for the repository 
https://github.com/RaneeshTK/Angular16-MicroAppshell

The app is created with angular 16 and added micrtosoft/signalR library along with custom webpack configuration as below
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");
const share = mf.share;

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, 'tsconfig.json'),
  [/* mapped paths to share */]);

module.exports = {
  output: {
    uniqueName: "testModuleFrederation",
    publicPath: "auto"
  },
  optimization: {
    runtimeChunk: false
  },   
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    }
  },
  experiments: {
    outputModule: true
  },
  plugins: [
    new ModuleFederationPlugin({
        library: { type: "module" },

        // For remotes (please adjust)
        // name: "testModuleFrederation",
        // filename: "remoteEntry.js",
        // exposes: {
        //     './Component': './/src/app/app.component.ts',
        // },        
        
        // For hosts (please adjust)
        // remotes: {
        //     "mfe1": "http://localhost:3000/remoteEntry.js",

        // },

        shared: share({
          "@angular/core": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/common": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: 'auto' }, 
          "@angular/router": { singleton: true, strictVersion: true, requiredVersion: 'auto' },

          ...sharedMappings.getDescriptors()
        })
        
    }),
    sharedMappings.getPlugin()
  ],
};
GIves ther error for loading the module

**Comment by RakeshPawar** [comment] 2023-08-04 07:29
We are also facing same issue.

**Comment by chuma2150** [comment] 2023-08-04 08:57
i can confirm the behavior. did work with angular 16.0.X and started failing with angular 16.1.X.
When setting 'optimization' to true, it is possible to serve it locally again.

**Comment by HarmoniousHarmony** [comment] 2023-08-04 13:05
> What version of the client? (try the latest preview) Can you provide a minimal app as a GitHub repository so we can see the behavior?

I had this issue with both version `3.x` and the latest one available on npm, you can have a minimal app [here](https://github.com/angular-architects/module-federation-plugin/issues/350)

**Comment by alexandre-dev29** [comment] 2023-08-08 16:10
I am facing the same issue 😥😥 
any update on how to solve this?

**Comment by LeonieNFarmer** [comment] 2023-08-15 16:41
Hi, I am having this issue when using signalR with NX. I have tested with both React and Angular in the latest version of NX and neither will work. See link to my NX with React example [https://github.com/LeonieNFarmer/nxv16.5.3withsignalr](url)

**Comment by BrennanConroy** [comment] 2023-08-15 18:23
> (try the latest preview)

Like I suggested in my original comment on this issue, using the latest preview version of `@microsoft/signalr` does not have this issue. We completely changed how we handle node only dynamic dependencies which removes the use of `__webpack_require__`.

An RC version of the client will be released next month. It looks like your workarounds are:
* Use Angular 15
* Manually patch the code
* Figure out what broke the module resolution and get that fixed
* Use the preview version of `@microsoft/signalr`

**Comment by luii** [comment] 2023-09-06 12:58
> > (try the latest preview)
> 
> Like I suggested in my original comment on this issue, using the latest preview version of `@microsoft/signalr` does not have this issue. We completely changed how we handle node only dynamic dependencies which removes the use of `__webpack_require__`.
> 
> An RC version of the client will be released next month. It looks like your workarounds are:
> 
>     * Use Angular 15
> 
>     * Manually patch the code
> 
>     * Figure out what broke the module resolution and get that fixed
> 
>     * Use the 8.0 preview version of `@microsoft/signalr`

I had the exact same problem, upgrading it to the preview was the thing that fixed it for me. @BrennanConroy i really really thank you for your work you put into it! 😊

**Comment by BrennanConroy** [comment] 2023-10-12 22:14
Closing as this is fixed in the latest version of the client. RC2 is out and RTM is going to be released next month.

**Closed by BrennanConroy** 2023-10-12 22:14 UTC
Labels: area-signalr, Needs: Attention :wave:, Needs: Repro
