### ISSUE TITLE
why audio oncanPlay No response? and how get audioPlayer duration

### ISSUE THREAD

**Issue by CeciAc** [dotnet/aspnetcore#17526] opened 2019-12-02 18:14 UTC
@19chang19 commented on [Sun Dec 01 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/221)

[在此处输入反馈]
<audio @ref="audioPlayer" src="@AudioSrc" @oncanplay="oncanPlay">@ChildContent</audio>

1.why oncanPlay No response?
2.how get audioPlayer duration?
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [ASP.NET Core Blazor 入门](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sun Dec 01 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/221#issuecomment-560117750)

Hello, @19chang19
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@19chang19 commented on [Sun Dec 01 2019](https://github.com/aspnet/AspNetCore.Docs.zh-cn/issues/221#issuecomment-560123379)

<audio @ref="audioPlayer" src="@AudioSrc" oncanplay='audio_player.updataTimejs(this,@DotNetObjectReference.Create(this))'>@ChildContent</audio>

and error    Uncaught SyntaxError: Unexpected end of input

i see html is 
oncanplay="audio_player.updataTimejs(this,Microsoft.JSInterop.DotNetObjectReference`1[WebCore.Shared.AudioPlayer])"

**Comment by mkArtakMSFT** [comment] 2019-12-03 17:56
Thanks for contacting us.
We'll look into what can be done here and get back to you then. Please don't expect a quick resolution on this, as we don't plan to have anything earlier than late next year on this.

**Comment by 19chang19** [comment] 2019-12-04 00:55
Have you confirmed this question? Why is it so late?

**Comment by mkArtakMSFT** [comment] 2020-03-02 19:03
This is a dupe of #17552

**Closed by mkArtakMSFT** 2020-03-02 19:03 UTC
Labels: area-blazor, investigate

**Comment by SteveSandersonMS** [comment] 2020-03-02 19:04
In the meantime, I'd recommend using JS interop to register an event handler on your element, and also use JS interop to make a call back into .NET with whatever parameters you need when that event occurs.
