### ISSUE TITLE
Blazor: after upgrading to release version api call are failing

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#22099] opened 2020-05-21 20:36 UTC
I upgraded my blazor WebAssembly Hosted app to latest RTM, it is working fine on my developer machine, but runs into error
  "The page you are looking for cannot be displayed because an invalid method (HTTP verb) is being used." when published to Azure App Service.

Here under is the call from balzor webAssembly.
`
   var response = await _Http.PostAsJsonAsync<SignInUserModel>("api/Account/Login", _signInUser);`

here is the hosted api

```
  [AllowAnonymous]
        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> Login(SignInUserModel loginModel)
        {
}
```

again the code works fine on developer machine.

**Comment by nssidhu** [comment] 2020-05-21 22:21
in the browser console i see the following error
dotnet.3.2.0.js:1 POST https://XXXlazorapp1.azurewebsites.net/api/Account/Login 405 (Method Not Allowed)

**Comment by nssidhu** [comment] 2020-05-22 00:10
I tried a brand new blazor WebAssembly Hosted Project and seems like there is major break in functionality
1) on client Side the Microsoft.AspNetCore.Components.Authorization seems to be broken in release mode but works in debug mode.
2) all server api calls are running to into error.

I hope someone is watching this thread looks like major problem after upgrading or creating new Hosted WebAssembly apps.

**Comment by knight1219** [comment] 2020-05-22 00:54
So crazy question, but do you set your ASPNETCORE_ENVIRONMENT variable when you deploy your code?

**Comment by nssidhu** [comment] 2020-05-22 01:53
no

**Comment by knight1219** [comment] 2020-05-22 01:56
Try setting it to Development manually and see if it works. Not sure how you do that in azure but there has to be a way.

**Comment by nssidhu** [comment] 2020-05-22 02:02
did that(tried Production as well). still the same problem

**Comment by mkArtakMSFT** [comment] 2020-05-26 17:16
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/22128

**Closed by mkArtakMSFT** 2020-05-26 17:16 UTC
Labels: area-blazor
