### ISSUE TITLE
Potential regression in injection of IHttpContextAccessor in SignalR Hub.OnConnectedAsync

### ISSUE THREAD

**Issue by NinjaCross** [dotnet/aspnetcore#39095] opened 2021-12-17 10:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It seems that recently:
1. the behaviour of the injection/availabilty of IHttpContextAccessor into the Hub.OnConnectedAsync method changed
2. the injection behaviour is not the same among different OS/Platforms.

Unfortunately I'm not able to pinpoint the exact version of SignalR CORE when the behaviour changed, since our project targets NuGet packages through floating versions, and the problem has been signaled only yesterday.

These are the libraries referenced after the floating versions resolution obtained using the command `dotnet list MyProject.sln package --framework net5 --include-transitive --include-prerelease`:

- Microsoft.AspNetCore.SignalR.Client: Resolved 3.1.11    
- Microsoft.AspNetCore.SignalR.Client.Core: Resolved  3.1.21    
- Microsoft.AspNetCore.SignalR.Common: Resolved  5.0.12    
- Microsoft.AspNetCore.SignalR.Core: Resolved  1.1.0     
- Microsoft.AspNetCore.SignalR.Protocols.Json: Resolved  3.1.21    
- Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson: Requested 5.*  -> Resolved 5.0.12

Take this code as an example of the rountrip.
Let's ignore the fact that I'm starting with a HttpContext, to optain another HttpContext... it's just to explain the roundtrip taken by mi inner logics and injections

This still works everywere, and always worked before:

```csharp
var newHttpContext = Context.GetHttpContext().  // called in OnConnectedAsync

/* here newHttpContext  is NOT NULL */

```

This worked everywere (in the near past), but now just works into our Windows 10 development machines, and **do not** work into our Windows 2019 servers

```csharp
 // called by OnConnectedAsync
var httpContext1 = Context.GetHttpContext();

 // we obtain a service provider contextualized into OnConnectedAsync, in order to get the injected scoped services 
var serviceProvider = httpContext1.RequestServices.GetRequiredService<IServiceProvider>();

// the accessor is correctly resolved, but...
var accessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
var httpContext2 = accessor.HttpContext; // the http context is NULL !!!
```

So, when in OnConnectedAsync I use IServiceProvider to get a scoped service, and that scoped service tries to access IHttpContextAccessor.HttpContext (through constructor injection), the HttpContext is NULL.

### Expected Behavior

The HttpContext returned by IHttpContextAccessor in  Hub.OnConnectedAsync  or any call stack started from there, should be not null and identical to the HttpContext returned by  **Context.GetHttpContext()**

### Steps To Reproduce

1. Create a Hub
2. Create a Scoped Service "S1", having IHttpContextAccessor as a constructor dependency
3. Try to resolve the Scoped Service "S1" into the Hub.OnConnectedAsync
4. The Scoped Service "S1" will have a valid IHttpContextAccessor instance, but the HttpContext will be null. As I said, we are experiencing the problem only on Windows Server, and NOT on Windows 10

### .NET Version

Installed 6.0.100, but compiled for NET 5

### Anything else?

A potential workaround seems to be this:

```csharp

// first of all we obtain a valid instance of HttpContext from the Hub internal logics
var httpcontext = Context.GetHttpContext();

// ... then, we preemptively obtain a reference to IHttpContextAccessor in order to "fix" it
var serviceProvider = httpcontext.RequestServices.GetRequiredService<IServiceProvider>();
var httpCa = serviceProvider.GetRequiredService<IHttpContextAccessor>();
if (httpCa.HttpContext == null) // if the HttpContext is null, fix it !
{
  httpCa.HttpContext = httpcontext;
  Logger.LogWarning(
 @$"(Sanity Check 1) The current {nameof(IHttpContextAccessor)} returned a NULL {nameof(HttpContext)}. 
Fixing the anomaly by forcing the instance provided by {nameof(HubCallerContext)}");
}

/* now, any scoped service resolved by IServiceProvider
will get a  IHttpContextAccessor containing the
HttpContext obtained by Context.GetHttpContext(); */

```

**Comment by NinjaCross** [comment] 2021-12-23 21:41
Any news on this ?
The workaround I proposed seems to work, but many projects I'm handling are affected and my customers are concerned about it.

**Comment by BrennanConroy** [comment] 2022-01-03 23:01
Obligatory dislike of `IHttpContextAccessor`: `IHttpContextAccessor` is awful and you should try not to use it.

First off, your package versions are super interesting in a bad way. Microsoft.AspNetCore.SignalR.Core  1.1.0 is for ASP.NET Core 2.2 which has been out of support for years. If you're using 6.0 or 5.0 as you claim then please remove that reference as it isn't needed.

On to your actual issue, the Hub doesn't necessarily run in the context of an Http request (especially in the case of LongPolling) which means it's very possible for `IHttpContextAccessor` to return null when used in the Hub. When connecting with WebSockets I believe you should always have an `HttpContext` from `IHttpContextAccessor` but with LongPolling you probably wont, and the reason `Context.GetHttpContext()` works is because we create an `HttpContext` internally in the LongPolling case and set it on the connection to be accessed by the Hub, but `IHttpContextAccessor` uses a different mechanism for attempting to access the `HttpContext`.

Can you confirm that the `IHttpContextAccessor` behavior you're seeing is only for LongPolling connections?

**Comment by NinjaCross** [comment] 2022-01-05 07:36
Tnx for the feedback @BrennanConroy, I was losing hope to get an answer :)

> Obligatory dislike of IHttpContextAccessor: IHttpContextAccessor is awful and you should try not to use it.

This is a very peculiar sentence, since AFAIK the `IHttpContextAccessor` is the preferred way to access the current HTTP context by scoped services.
Could you elaborate more ? 
Are you talking about the specific SignalR topic, or in general for ASP.NET development ?
Why shouldn't I use it, and what's the suggested replacement (apart from the obvious `Context.GetHttpContext()` in SignalR) ?


> First off, your package versions are super interesting in a bad way. Microsoft.AspNetCore.SignalR.Core 1.1.0 is for ASP.NET Core 2.2 which has been out of support for years. If you're using 6.0 or 5.0 as you claim then please remove that reference as it isn't needed.

I'm targeting multiple frameworks (net core app 2.2, net core app 3.1, net 5, net 6), and that was the lowest version common to all of them.
I will try to change the dependencies chain in order to target higher NuGet packages versions for higher framework versions and I'll let you know.

> Can you confirm that the IHttpContextAccessor behavior you're seeing is only for LongPolling connections?

Unfortunately, no, the behaviour I'm seeing is for WebSocket, not Long Polling.

**Comment by BrennanConroy** [comment] 2022-01-05 21:30
> Unfortunately, no, the behaviour I'm seeing is for WebSocket, not Long Polling.

Would you be able to provide a github repo with a minimal app that reproduces the issue? Also, it would be nice if you could narrow down exact versions of libraries you're using and which OS(es) you're seeing the behavior on.

**Comment by NinjaCross** [comment] 2022-01-05 21:43
> > Unfortunately, no, the behaviour I'm seeing is for WebSocket, not Long Polling.
> 
> Would you be able to provide a github repo with a minimal app that reproduces the issue? Also, it would be nice if you could narrow down exact versions of libraries you're using and which OS(es) you're seeing the behavior on.

I'm not sure, but I'll try to create a repo.
The OS(es) are the one mentioned into the initial message.
As specified, the most important factor seems to be the fact that the behaviour is different from Windows 10 to Windows Server.

**Comment by NinjaCross** [comment] 2022-03-10 06:54
> > I'll try to create a repo.
> 
> Any progress here?
> 
> I created a Windows Server 2019 machine to try this out and the only thing I saw is that LongPolling + IHttpContextAccessor returns null which is expected.

Sorry, very busy period, I couldn't pursue this :(
We just "solved" the problem using the workaround mentioned into the first message, and since it works, we did not investigate further, nor had the time the create a reproduction test report.
I'm afraid I'll have to abandon the issue.
Feel free to close it if you believe it's not relevant.

Anyway, @BrennanConroy I'm still very interested in your answer about my question on your dislike for IHttpContextAccessor (https://github.com/dotnet/aspnetcore/issues/39095#issuecomment-1005448467) if you have the time :)

**Comment by BrennanConroy** [comment] 2022-03-10 17:48
We've seen numerous customer issues that have boiled down to them using `IHttpContextAccessor` on a background thread or outside of the request pipeline because it's very easy to do. It's fine if you understand how to use if properly but it's very error prone.

Closing for now, if more info arises, we can reopen/open a new issue.

**Closed by BrennanConroy** 2022-03-10 17:48 UTC
Labels: investigate, area-signalr, Needs: Attention :wave:

**Comment by NinjaCross** [comment] 2022-03-11 20:06
> We've seen numerous customer issues that have boiled down to them using `IHttpContextAccessor` on a background thread or outside of the request pipeline because it's very easy to do. It's fine if you understand how to use if properly but it's very error prone.
> 
> Closing for now, if more info arises, we can reopen/open a new issue.

I see, I thought there were "less obvious" motivations.
Thank you for you effort.
