### ISSUE TITLE
Hash routing to named element

### ISSUE THREAD

**Issue by MovGP0** [dotnet/aspnetcore#8393] opened 2019-03-10 22:29 UTC
### Describe the bug

I cannot use an html anchor to navigate to a specific html element of a page. 

### To Reproduce

Given there is a Blazor page that looks like the following: 

```razor
@layout MainLayout
@page "/foo"

<nav>
    <!-- One version I've tried -->
    <a href="#bar">Bar</a>

    <!-- Another version I've tried -->
    <NavLink href="#bar">Bar</NavLink>

    @* ... *@
</nav>

@* ... *@

<section>
    <h2 id="bar">Bar</h2>
     @* ... *@
</section>
```

When I click the link to Bar, i get redirected to the route `http://localhost:5000/foo#bar`, but will be at the top of the page. The fragment of the route is not used for selection of a specific HTML element. 

### Expected behavior

The browser should scroll down to the proper element, as specified by the [Element Selector](https://www.w3.org/TR/selectors-3/). 

In cases where the fragment of the URL is used for other purposes, ie. for OAuth, it should be possible to overwrite the default Blazor router behavior. The behavior should be set on a per-page and per-app level. 

### Workaround

The proposed workaround does not work, since the browser crashes and is only for illustration.

The current workaround is to write explicit code that interprets the URL. In the example above, we could use a little bit of JavaScript and then call that from our Blazor code: 

```html
<!-- in index.html -->
<script>
        window.scrollToElementId = (elementId) => {
            console.info('scrolling to element', elementId);
            var element = document.getElementById(elementId);
            if(!element)
            {
                console.warn('element was not found', elementId);
                return false;
            }
            element.scrollIntoView();
            return true;
        }
</script>
```

```razor
@inject Microsoft.AspNetCore.Components.Services.IUriHelper UriHelper

@functions {
    protected override void OnInit()
    {
        NavigateToElement();
        UriHelper.OnLocationChanged += OnLocationChanges;
    }

    private void OnLocationChanges(object sender, string location) => NavigateToElement();

    private void NavigateToElement()
    {
        var url = UriHelper.GetAbsoluteUri();
        var fragment = new Uri(url).Fragment;

        if(string.IsNullOrEmpty(fragment))
        {
            return;
        }

        var elementId = fragment.StartsWith("#") ? fragment.Substring(1) : fragment;

        if(string.IsNullOrEmpty(elementId))
        {
            return;
        }
    
        ScrollToElementId(elementId);
    }

    private static bool ScrollToElementId(string elementId)
    {
        return JSRuntime.Current.InvokeAsync<bool>("scrollToElementId", elementId).GetAwaiter().GetResult();
    }
}
```

### Additional context

`blazor 0.8.0-preview-19104-04`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by MovGP0** [comment] 2019-03-10 22:36
see also #6175

**Comment by Psimatrix** [comment] 2019-05-29 01:21
This also happens when using the basic functionality of a tabbed panel.
For example: paste into a blazor page
     <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
        <li><a data-toggle="tab" href="#menu1">Menu 1</a></li>
    </ul>

    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h3>HOME</h3>
            <p>Some content.</p>
        </div>
        <div id="menu1" class="tab-pane fade">
            <h3>Menu 1</h3>
            <p>Some content in menu 1.</p>
        </div>
    </div>

Clicking any of the panels will try to navigate you to a page instead of the named tab element.

**Comment by egil** [comment] 2019-08-16 10:31
I want to note that this is still an issue with Preview 8. Consider the following example

```
@page "/some/page"
<a href="#">#blank</a>
<a href="#example">#exmaple</a>
<h1 id="example">Example</h1>
```

Clicking either of the two links takes the browser to the url `/#` or `/#example`, which is clearly not the expected behaviour. The expected behaviour is to stay on the same page, e.g.  `/some/page#` or `/some/page#example`, but have the relevant "hash" section appended/replaced in the url.

**Comment by SQL-MisterMagoo** [comment] 2019-08-30 10:09
Here is a temporary workaround that seems to work for internal clicks, but not deep linking

`<a href="#Bar" onclick="event.stopPropagation();">Bar</a>
`

**Comment by egil** [comment] 2019-08-30 10:14
> Here is a temporary workaround that seems to work for internal clicks, but not deep linking
> 
> `<a href="#Bar" onclick="event.stopPropagation();">Bar</a> `

@SQL-MisterMagoo the problem with that workaround is that it also stops any other `@onclick=...` attached events from firing (they are listened to at the document level).

I do not know what the implications are, but it looks like a fix for this bug could be adding a check around [this line in NavigationManager.ts#L47](https://github.com/aspnet/AspNetCore/blob/725fa34cc801017294a805a6c0929992456de42a/src/Components/Web.JS/src/Services/NavigationManager.ts#L47), that checks if the anchor's href starts with a `#`, and if it does, don't trigger the navigation logic.

**Comment by SQL-MisterMagoo** [comment] 2019-08-30 10:39
@egil Yes, it does, but you can easily use @onmouseup or another event if you need Blazor code to fire as well as the internal browser scroll.

See this example https://blazorfiddle.com/s/jtufkw80

this is a workaround - of course the real fix is needed.

**Comment by Andrzej-W** [comment] 2019-08-31 00:18
I haven't tested this but I believe it should work:
https://community.devexpress.com/blogs/aspnet/archive/2019/08/28/blazor-components-free-anchor-navigation-tool.aspx

**Comment by TheGrandUser** [comment] 2019-10-27 16:50
This is still a problem in the release version

**Comment by SQL-MisterMagoo** [comment] 2019-11-28 00:22
I was just reading the source and realised if you simply include `target="_top"` in your anchor, it will avoid the navigation interception and just work - not found a workaround for deep linking yet though.

This line of code in NavigationManager returns directly out of the click handler before preventDefault can be called - if there is a `target` and it doesn't equal "_self".

https://github.com/aspnet/AspNetCore/blob/32a2cc594363672ccfe7644a649f77a8bfc9c4a8/src/Components/Web.JS/src/Services/NavigationManager.ts#L59

Example:

`<a id="bottom" href="#top" target="_top">Jump to top</a>`

**Comment by TheGrandUser** [comment] 2019-11-30 23:32
I just tried that in my project and it's still redirecting to the root url, not scrolling to the element.

**Comment by SQL-MisterMagoo** [comment] 2019-11-30 23:35
> I just tried that in my project and it's still redirecting to the root url, not scrolling to the element.

Can you share the link?

**Comment by TheGrandUser** [comment] 2019-11-30 23:53
It's <a href="#k28" target="_top">#28</a>

And the element it refers to on that page is

<h3 id="k28">...</h3>

It's as straight forward as it can be

**Comment by SQL-MisterMagoo** [comment] 2019-12-01 00:12
@TheGrandUser is this server side Blazor or web assembly?

**Comment by TheGrandUser** [comment] 2019-12-01 00:13
This is server side, using .net core 3.1 in the VS preview

**Comment by SQL-MisterMagoo** [comment] 2019-12-01 00:30
@TheGrandUser if the page is not the root of your site you will need to include the page route in the anchor href because Blazor uses root relative link resolution. Have you tried that? 
`href=mypage#k28`

**Comment by TheGrandUser** [comment] 2019-12-01 01:34
Ok, that works

**Comment by Grauenwolf** [comment] 2019-12-14 06:08
Updated work-around:

        window.scrollToElementId = (elementId) => {
            console.info('scrolling to element', elementId);
            var element = document.getElementById(elementId);
            if (!element) {
                console.warn('element was not found', elementId);
                return false;
            }
            element.scrollIntoView();
            return true;
        }

        async protected sealed override Task OnAfterRenderAsync(bool firstRender)
        {
            await NavigateToElementAsync();
        }

        async Task NavigateToElementAsync()
        {
            var fragment = new Uri(Navigation.Uri).Fragment;

            if (string.IsNullOrEmpty(fragment))
                return;

            var elementId = fragment.StartsWith("#") ? fragment.Substring(1) : fragment;

            if (string.IsNullOrEmpty(elementId))
                return;

            await JSRuntime.InvokeAsync<bool>("scrollToElementId", elementId);
        }

**Comment by ramkiranhota** [comment] 2020-07-03 04:18
> @TheGrandUser if the page is not the root of your site you will need to include the page route in the anchor href because Blazor uses root relative link resolution. Have you tried that?
> `href=mypage#k28`

This worked for me...than you so much

**Comment by chrdlx** [comment] 2020-07-05 13:49
> > @TheGrandUser if the page is not the root of your site you will need to include the page route in the anchor href because Blazor uses root relative link resolution. Have you tried that?
> > `href=mypage#k28`
> 
> This worked for me...thank you so much

Be careful with this.... if you use a component that uses anchors with this approach,  and that component is used in different routes, then you'll have a problem since the URL is not static anymore.
Regards

**Comment by SQL-MisterMagoo** [comment] 2020-07-05 14:15
Well obviously you don't hard code URLs...

**Comment by mark-at-tusksoft** [comment] 2020-07-23 17:22
> Updated work-around:
> 
> ```
>     window.scrollToElementId = (elementId) => {
>         // Omitted for brevity
>     }
> 
>     async protected sealed override Task OnAfterRenderAsync(bool firstRender)
>     {
>         await NavigateToElementAsync();
>     }
> 
>     async Task NavigateToElementAsync()
>     {
>         // Omitted for brevity
>     }
> ```

@Grauenwolf Where is that supposed to go? Does the javascript go into its own static file and the C# go into the razor component/layout we need to call it from?

**Comment by Grauenwolf** [comment] 2020-07-24 01:29
The JavaScript can go directly in index.html

**Comment by ahmed007boss** [comment] 2020-10-21 16:39
This will be very important feature when it comes to component design , hopefully  it could be there very soon

**Comment by MovGP0** [comment] 2020-10-25 23:40
Update for Workaround: 

*index.html*
```html
    <script>
        window.scrollToElementId = (elementId) => {
            console.info('scrolling to element', elementId);
            var element = document.getElementById(elementId);
            if (!element) {
                console.warn('element was not found', elementId);
                return false;
            }
            element.scrollIntoView();
            return true;
        }
    </script>
```

*MainLayout.razor*
(can also be in another base class, when not every page should have this)
```razor
@inherits LayoutComponentBase
@inject NavigationManager Navigation
@inject IJSRuntime JSRuntime

@Body

@functions {
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        Navigation.LocationChanged += OnLocationChanges;
    }
    
    protected void OnLocationChanges(object sender, LocationChangedEventArgs args) => NavigateToElement();

    protected void NavigateToElement()
    {
        NavigateToElementAsync().Wait();
    }

    async protected override Task OnAfterRenderAsync(bool firstRender)
    {
        await NavigateToElementAsync();
    }

    protected async Task NavigateToElementAsync()
    {
        var fragment = new Uri(Navigation.Uri).Fragment;

        if (string.IsNullOrEmpty(fragment))
            return;

        var elementId = fragment.StartsWith("#") ? fragment.Substring(1) : fragment;

        if (string.IsNullOrEmpty(elementId))
            return;

        await JSRuntime.InvokeAsync<bool>("scrollToElementId", elementId);
    }
}
```

**Comment by mkArtakMSFT** [comment] 2021-01-26 18:34
Moving this to 6.0-poreview2 to spend 1 days and see what can be done here. If turns out this is a large effort, we'll push it out to the future.

**Comment by mrlife** [comment] 2021-04-07 16:22
@mkArtakMSFT Possible to commit to this for 6.0?

**Comment by jonrmorgan99** [comment] 2021-05-07 08:44
@mkArtakMSFT Over two years have passed since the OP reported this issue.

You mentioned spending a day in January on the issue. 
Did it turn out to be "a large issue", and if so can you say where in the future a fix will be available ?

**Comment by truecrimson** [comment] 2021-12-09 18:18
This is literally one of the most basic things in HTML anchor elements and Blazor can't handle it. I would think the first step in designing a new framework would be to make sure it is compliant with common HTML no?

**Comment by gorums** [comment] 2022-08-22 17:34
Are we still having this issue without an odd solution like adding a component only for that?

**Comment by andrewschmidgit** [comment] 2022-09-19 18:42
Any news? This seems way to basic to wait for a whole new .NET version to fix

**Comment by Bosnianflajter2** [comment] 2022-11-09 17:17
Any news regarding hash routing?  I have many existing (from my previous project) html files containing anchor which I want to use in blazor ServerApp but as this doesn't work... have to stop my project...  
A simple approach would be OK as an additional future (update) to the existing net 6 version.  Waiting for 8 v.  -where it maybe will be implemented- could take years..

**Comment by fardarter** [comment] 2022-11-24 16:03
How has this still not been addressed?

**Comment by MarcelDevG** [comment] 2022-11-25 13:32
It's not just the scrolling to the html element, handling of the routing, but also synchronisation with the navigation. 
When the user hit back, it returns where it came from on the same page.
But indeed : "How has this still not been addressed?"

**Comment by fardarter** [comment] 2022-11-25 13:34
@MarcelDevG I take the point but every JS framework has figured this out. That's who Blazor is competing with.

**Comment by MarcelDevG** [comment] 2022-11-25 13:36
Why do I have to pull in (yet another JS framework) to fix this...

**Comment by zHaytam** [comment] 2022-12-26 10:05
I'm surprised the team still didn't address this...

**Comment by vflame** [comment] 2022-12-31 20:22
The proposed workaround has a shortcoming that can be hopefully be addressed--when the brower's DOM is mutating due to renders, the position of the target element may be stale when the JS is invoked to scroll.

The thinking is to somehow wait for everything in the browser's DOM to be "stable", and then scroll to the element. (How do you define what is "stable" per the brower's DOM?) You can try to design their pages to know the size of the content in advance so that the height/width is constant, but this isn't very realistic.

We ended up just adding an arbitrary delay before scrolling to ensure the DOM is "stable" enough. But even then, if a end-user has a very slow connection (blazor server)/slow device, the JS can still scroll before the DOM is "stable".

**Comment by MAghazade** [comment] 2023-01-09 17:36
I think this can be a temporary solution using this overload navigation manager:

`@page "/TestPage"
@inject NavigationManager Navigation

<a @onclick='(()=>Navigation.NavigateTo("/TestPage#sec1",true))'>Sec1</a>

<div class="row" style="margin-top:1000px">
    <div class="col-12">
        <h1>sec1</h1>
        <section id="sec1">
            <p>
                Lorem ipsum dolor sit amet. Ea quia autem id quia sunt sit laudantium optio 33 voluptate laborum. Est laudantium molestiae sit nisi voluptatem in dolorem dignissimos sed aliquid voluptatem id molestias omnis.

                Aut nisi itaque At dolores itaque ut enim reprehenderit qui totam incidunt sit consequatur fugiat! Ea minima veritatis qui inventore voluptas aut illum molestiae ut error aperiam aut provident dolor est placeat natus. Eum laboriosam magnam ex unde esse sit eaque galisum cum quis incidunt. Qui veniam maiores nam quia expedita qui minima incidunt est quibusdam magni?

                A asperiores molestias non sint earum et rerum eveniet. Ut dolor adipisci non voluptas fugiat sit architecto laboriosam est deserunt corrupti.
            </p>
        </section>
    </div>
</div>

`

**Comment by MarvinKlein1508** [comment] 2023-03-29 11:25
It would be great if this works out of the box for the `NavigationManager.Navigate` method as well.

**Closed** 2023-04-06 19:03 UTC
Labels: enhancement, area-blazor, triaged, affected-most, severity-minor, Priority:1, feature-blazor-builtin-components, webui-P1-JC, webui-P2-MB, webui-P2-TP, webui-P1-SS, webui-P1-DR
