### ISSUE TITLE
Allow customization of Identity Api Routes

### ISSUE THREAD

**Issue by dansiegel** [dotnet/aspnetcore#55142] opened 2024-04-15 13:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Currently the routes established when calling `MapIdentityApi` are hard coded values. This is a problem for a variety of reasons.

https://github.com/dotnet/aspnetcore/blob/81355450754f0e6471244b7f1f457b866e982a15/src/Identity/Core/src/IdentityApiEndpointRouteBuilderExtensions.cs#L57

1) This is not friendly for localization as some clients in non-English speaking countries may want their routes in their native language. For instance this route for a Spanish customer they may want to customize as `/registro`.
2) This is not friendly for scenarios where you may have a static web app sitting in front of the API. In this case I may want my webapp route to be `/register` which would conflict with the API's route.

### Describe the solution you'd like

Provide an options delegate that allows me to define routes or provide a prefix/area for the API routes.

```cs
app.MapIdentityUser<User>(o => {
    // This will prepend all routes
    o.Area = "/api/authentication";
});
```

Provide an ability to customize each route individually to additionally allow users to localize the route their native language.

```cs
app.MapIdentityUser<User>(o => {
    o.Routes.Register = "/registro";
    o.Routes.Login = "/acceso";
});
```

**Comment by mkArtakMSFT** [comment] 2024-04-25 16:57
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/50303

**Closed by mkArtakMSFT** 2024-04-25 16:57 UTC
Labels: area-identity
