### ISSUE TITLE
Blazor needs a JS library or functionality for common Js and DOM tasks

### ISSUE THREAD

**Issue by HolyOne** [dotnet/aspnetcore#54085] opened 2024-02-17 03:24 UTC
Blazor offers a JSRuntime to Interact with the page. But it offers too few functions. So people write their own functions to do simple tasks like include scripts/metatags etc to page and InvokeAsync them. These are simple and frequently used functions and everyone writes these and gives them different names.

### Solution

I offer these functionality as either JSRuntime methods or a common set of Js functions included in the blazor.js

```
IncludeScript(scriptPath)  // Provides a common way for developers to inject javascript files to the page
IncludeScript(scriptPath, cleanUpOnDispose)  //removes the script when user is navigated away from page
CleanupScript(scriptPath)  
```

<MetaTag></Metatag>  just like <PageTitle> tag,  it will be disposed after navigating away from page.

Chain loading scripts with easily describing order of them, Example:

`await IncludeScriptAsync("jquery.js").Then("jquery.select.js", "jquery-ui.js").Then("jquery-ui-dialog.js");`

I know Jquery is not something we want to use in blazor at 2024 but for the sake of example I used the most commonly known js library.

```
SetCookie(cookiename, cookievalue)
GetCookie(cookiename)
SetLocalStorage(key, value)
``` 

They are all easy to implement but the problem is everyone is writing their own functions for them and it makes blazor components harder to put together from different projects.

**Comment by javiercn** [comment] 2024-02-17 11:09
@HolyOne thanks for contacting us.

> They are all easy to implement but the problem is everyone is writing their own functions for them, and it makes blazor components harder to put together from different projects.

Dupe of https://github.com/dotnet/aspnetcore/issues/52273

**Closed** 2024-02-17 11:11 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor
