### ISSUE TITLE
Hot Reload with `--project <path>` arg does not start hot reload

### ISSUE THREAD

**Issue by johnkors** [dotnet/aspnetcore#33248] opened 2021-06-03 09:41 UTC
Not sure if it's just me, but hot reload does not work for me if using the `--project / -p` arg of `dotnet run`.

`dotnet watch run -p src/myproj` => no log statement saying hot reload is used, and it does not seem to work.

<img width=300 src=https://user-images.githubusercontent.com/206726/120623924-75f7a300-c460-11eb-8dd1-bc05d99af07e.png>

<img width=300 src=https://user-images.githubusercontent.com/206726/120624010-890a7300-c460-11eb-8c95-9d3ef1edb186.png>

**Comment by mkArtakMSFT** [comment] 2021-06-03 16:24
Thanks for contacting us. This is a dupe of #31365

**Closed by mkArtakMSFT** 2021-06-03 16:24 UTC
Labels: area-commandlinetools
