### ISSUE TITLE
IIS Applications hosting (in site-folder) is not working for Blazor Server deployment

### ISSUE THREAD

**Issue by LarsOutzen** [dotnet/aspnetcore#43160] opened 2022-08-09 12:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-6.0&tabs=visual-studio#app-base-path
Try to test "Option 1" OR "Option 2" on IIS for your Blazor Server template projects' Counter

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26667

### Expected Behavior

A working site/CoolApp/

### .NET Version

dotnet --info  Host (useful for support):   Version: 6.0.3   Commit:  c24d9a9c91

**Comment by javiercn** [comment] 2022-08-09 15:08
Dupe of https://github.com/dotnet/aspnetcore/issues/43161

**Closed by javiercn** 2022-08-09 15:08 UTC
Labels: area-blazor, feature-blazor-deployment, blazor-server
