### ISSUE TITLE
[Windows ARM64] with .net6 preview3 SDK installed, warning and error occurred when build and run mvc/razor project.

### ISSUE THREAD

**Issue by dandanmu** [dotnet/aspnetcore#31449] opened 2021-03-31 07:51 UTC
Repro steps:
1.	Download and install dotnet-sdk-6.0.100-preview.3.21180.8-win-arm64- from https://github.com/dotnet/installer
2.	dotnet new mvc or dotnet new razor in cmd.
3.	Dotnet build and dotnet run
Expected Result:
Build successfully.
Actual Result;
Waring occurred as below when building 
 
CSC : warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName of the added source file must be unique within a generator. (Parameter 'hintName')' [C:\Users\v-danche\60test\ProC#\danmvc\danmvc.csproj]
![image](https://user-images.githubusercontent.com/65638819/113109605-b7898900-9238-11eb-9d64-169baecc65d4.png)
Error occurred when run it
![image](https://user-images.githubusercontent.com/65638819/113109687-cc661c80-9238-11eb-9fcb-c157fb0201ab.png)

dotnet --info:
 
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21180.8
 Commit:    4488088cc5
 
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21180.8\
 
Host (useful for support):
  Version: 6.0.0-preview.3.21179.3
  Commit:  58cf4f2210
 
.NET SDKs installed:
  6.0.100-preview.3.21180.8 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.3.21179.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21179.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21179.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by captainsafia** [comment] 2021-04-05 23:07
Confirmed this as a dupe of https://github.com/dotnet/aspnetcore/issues/28794. Thanks for the bug report!

**Closed by captainsafia** 2021-04-05 23:07 UTC
Labels: area-razor.compiler, feature-source-generators, investigate

**Comment by dandanmu** [comment] 2021-04-06 09:33
@captainsafia It It can repro if project's name contains special characters e.g "#".
dotnet new mvc -o mymvc#

Note: It repro on windows and windows arm64  
![image](https://user-images.githubusercontent.com/65638819/113690373-e783d100-96fd-11eb-9a2a-c585e9fb3430.png)
