### ISSUE TITLE
Fix textarea with with large amounts of text data 

### ISSUE THREAD

**Issue by Liero** [dotnet/aspnetcore#54538] opened 2024-03-14 07:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When user enters longer text to input/textarea,  the signalr messages exceeds MaximumReceiveMessageSize limit and are ignored.

### Describe the solution you'd like

the event data should be streamed or split into multiple Signal R messages, so that there is not difference at application level.

The proposed workaround ([InputLargeTextArea](https://github.com/aspnet/samples/tree/main/samples/aspnetcore/blazor/InputLargeTextArea)) is not good enough, because any user input can be potentially large. If we accepted the workaround, it would mean the `input` `textarea` `InputText` and `InputTextArea` elements are not safe to use. 

### Additional context

These two issues were closed with unsatisfying "solution"
https://github.com/dotnet/aspnetcore/issues/30291 - does not solve the problem
https://github.com/dotnet/aspnetcore/issues/5623 - closed as duplicate

**Comment by mkArtakMSFT** [comment] 2024-03-14 17:09
Thanks for contacting us. For now, we recommend customers to utilize the sample that was provided in the linked issue: https://github.com/aspnet/samples/tree/main/samples/aspnetcore/blazor/InputLargeTextArea

As for your specific proposal, that's already something on our radar, so I'll close this issue as a dupe of it: https://github.com/dotnet/aspnetcore/issues/51080

**Closed by mkArtakMSFT** 2024-03-14 17:09 UTC
Labels: area-blazor

**Comment by SteveSandersonMS** [comment] 2024-03-14 17:14
> the event data should be streamed or split into multiple Signal R messages, so that there is not difference at application level.

The main reason we're not super keen on this is that, if it was truly transparent to application logic, that would completely undermine the whole reason why SignalR message size limits exist. You might as well just set the message size limit to "unlimited", since Blazor would have to hold however much server memory is needed to hold the reconstructed data in the end. A user could stream 50GiB of data to your server and it would have to allocate that much memory to hold it all.

The purpose of the SignalR message size limit is to stop a user from posting vast amounts of data that will cause your server to run out of memory and go down. If you feel that it's fine to accept a buffer of size 10MiB from anyone connected to your app, then you can set the message size limit to 10 MiB. If you feel that you trust your users to send you an unlimited amount of data, then you can set the message size limit to unlimited.

The proposed solution with `InputLargeTextArea` avoids the core problem by forcing application code to deal with the large data as a `Stream`. As such, you can buffer it all in memory if you want to, but you can also process it in a streaming way (e.g., line by line) without ever holding a large single block of server memory.

Does this make sense? If you think we're missing something, could you clarify? Thanks!

**Comment by Liero** [comment] 2024-03-15 08:31
@SteveSandersonMS:
Thanks for clarification, it makes sense.
However, silently ignoring the SignalR messages means textarea / InputTextArea are not safe to use as there is little I can do to prevent it.

This is recurring problem that hit me every time I put Blazor Sever app into production. Customers are not happy.

While I'm not keen to increase SignalR message size limit in general, `InputTextArea` component could handle it better out of the box.

1. Let developer to handle the "exception"
2. Set ValidationError automatically saying the length has been exceeded
3. Set maxlength attribute implicitly
4. If maxlength is set explicitly, than maybe its safe to split message into chunks and assume developer want it
5. Include InputLargeTextArea functionality directly into InputTextArea.

**Comment by SteveSandersonMS** [comment] 2024-03-15 09:56
Thanks for listing the other options. I do agree we could/should make this easier to manage.

> Include InputLargeTextArea functionality directly into InputTextArea

That's the approach I'm most inclined towards, as it fits within the existing abstractions.

**Comment by Liero** [comment] 2024-03-19 13:04
For me the most important is - don't silently swallow exception. It is unacceptable that users inputs something and something else is silently processed without any feedback.
Thanks
