### ISSUE TITLE
Broken Publish of Blazor app

### ISSUE THREAD

**Issue by kant2002** [dotnet/aspnetcore#19799] opened 2020-03-12 16:53 UTC
### Describe the bug
Clean publish broken. I have somewhat similar issue after build in CI, but this is simplest reproduction case.

```
Error:
  An assembly specified in the application dependencies manifest (BlazorIssue.Server.deps.json) was not found:
    package: 'BlazorIssue.Shared', version: '1.0.0'
    path: 'BlazorIssue.Shared.dll'
```

If everything start working, just clean bin/obj manually.

### To Reproduce
1. `dotnet new blazorwasm --hosted -o BlazorIssue`
2. `cd BlazorIssue`
3. Modify Client by including `<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking`
4. `cd Server`
5. `dotnet publish -c Release -r win-x64`
6. `cd bin\Release\netcoreapp3.1\win-x64\publish\`
7. `BlazorIssue.Server.exe`

### Further technical details
- ASP.NET Core version. Blazor 3.2.0 PReview 2

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by julienGrd** [comment] 2020-03-13 08:58
seem related to my issue, the dll already included in the client are not copy in the server app

https://github.com/dotnet/aspnetcore/issues/19768

**Comment by SteveSandersonMS** [comment] 2020-03-20 15:47
Duplicate of https://github.com/dotnet/aspnetcore/issues/19926

**Closed** 2020-03-20 17:10 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor, blazor-wasm, investigate
