### ISSUE TITLE
RCL template requires manual tweaks to support pages+views+components

### ISSUE THREAD

**Issue by hcanand** [dotnet/aspnetcore#23147] opened 2020-06-19 10:45 UTC
When creating a razor class library project, if we check the option 'Support Pages and views', the manual steps described at the following link:

https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.1&tabs=visual-studio

Should be automatically done by the VS tooling/by the Templates itself. This will prevent developer from having to do these manually and/or reduce potential errors.

### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by javiercn** [comment] 2020-06-19 10:54
@hcanand thanks for contacting us.

That is only if you want to have a RCL that has Razor pages and Views and want to author Razor components on the same library. We believe this is not as common as having a library for Pages and Views or a library for Components to be used in Blazor.

**Comment by hcanand** [comment] 2020-06-19 12:13
am trying to consume a components from another library in RCL pages library...but am not getting any intellisense for the components except in the blazor app projects....can u guide or share link to any existing doc resource for consuming components in RCL projects?

**Comment by mkArtakMSFT** [comment] 2020-06-22 17:01
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by hcanand** [comment] 2020-06-23 10:40
Consuming of Razor components in another RCL library or RazorPages project, should be similar to components usage in blazor webassembly/server side projects, and we should not use the component taghelper for rendering those components as it's not intuitive and prone to errors

**Comment by javiercn** [comment] 2022-03-29 15:06
The remaining ask [above](https://github.com/dotnet/aspnetcore/issues/23147#issuecomment-648061042) is a dupe of [this](https://github.com/dotnet/aspnetcore/issues/6348) issue. We suggest to up-vote that issue instead.

**Closed by javiercn** 2022-03-29 15:06 UTC
Labels: enhancement, area-blazor, affected-few, severity-minor, feature-templates
