### ISSUE TITLE
Fix setting nullable Action parameters on components

### ISSUE THREAD

**Issue by jontavakoli** [dotnet/aspnetcore#23892] opened 2020-07-13 04:56 UTC
When passing an Action from one Component to another component if the value is null the code throws the following exception: `System.ArgumentException: 'Delegate to an instance method cannot have null 'this'.'`

This is caused by the generated code, because it tries to create an instance of the Action delegate instead of just passing the value along as it is:

**Component A - Generated Code (A.razor.g.cs)**
```
public partial class A : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<B>(0);
            __builder.AddAttribute(1, "When", new System.Action(When));
            __builder.CloseComponent();
        }

	[Parameter]
	public Action When { get; set; }

}
```

**Component A (A.razor)**
```
@code{

	[Parameter]
	public Action When { get; set; }

}

<B When="@When" />

```

**Component B (B.razor)**
```
@code{

	[Parameter]
	public Action When { get; set; }

}

<span>Empty</span>
```

Is there a way to override the code generation logic to stop this `__builder.AddAttribute(1, "When", new System.Action(When));` and instead do `__builder.AddAttribute(1, "When", When);`.

**Comment by javiercn** [comment] 2020-07-13 15:02
@jontavakoli thanks for contacting us.

I'm not exactly sure what it is going on here, we'll take a look and update the issue accordingly. In general code generation is not an area where we provide knobs for users to tweak, I'm not an expert in the area, but I know we do all sort of tricks to make type inference and other things like that work, so if we need to change something here we'll have to look in more detail since it can have unexpected consequences.

**Comment by mkArtakMSFT** [comment] 2020-07-13 16:16
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment] 2020-09-21 22:23
Hi. Thanks for contacting us.
We're closing this issue as we haven't seen many reports of it.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by captainsafia** [comment] 2020-11-09 17:21
Re-opening since this was recently reported in https://github.com/dotnet/aspnetcore/issues/27578 and had a few thumbs up on it.

**Comment by MarkStega** [comment] 2020-11-09 18:33
Even though the codegen is a bit different now
```
            __builder.AddAttribute(4, "GroupExpression", new System.Func<TRowData, System.Object>( pGroupExpression));
```
the same issue occurs when the optional parameter is omitted.

**Comment by MarkStega** [comment] 2020-11-29 12:47
@mayur-ekbote In my case (#27578) what you suggested is not practical. The actual wrapped component has 5 expressions any of which could be null. I'd have to code for all of the various permutations with a series of @if statements in my razor files. I believe that math works out to 5! combinations. This is not practical to code.

**Comment by mayur-ekbote** [comment] 2020-12-02 12:13
@MarkStega I wasn't countering the original request. It's a valid feature request. However, when I faced the issue, I couldn't find a workaround. I posted it here so that if a poor soul needs a quick fix, he can find it.

**Comment by MarkStega** [comment] 2020-12-02 13:13
@mayur-ekbote Sorry if my response came off too negative. In fact, I have coded 4 specific instances of my wrapper leaving off certain combinations of the expressions for given use cases in my app. I look forward to corrected code generation though as this is such a hack. Your advice for a quick workaround is good for anyone who didn't consider this possibility.

**Comment by zHaytam** [comment] 2021-01-07 20:57
Hello,
I'm also having the same issue trying to pass a `RenderFragment` from a parent to a child.

```cs
__builder.AddAttribute(4, "ItemTemplate", new Microsoft.AspNetCore.Components.RenderFragment<MudBlazor.BreadcrumbItem>(
                                            ItemTemplate
));
```

This throws the same error if the parent doesn't receive the RenderFragment.

**Comment by mrlife** [comment] 2021-01-27 17:32
I have nested components with optional Func `Parameter`s. It would be great if null `Func`/`Action` parameter values were allowed through to avoid implementing a workaround. I have logic that handles if such a parameter is null.

A workaround I use is to pass a representative Func that matches the definition but doesn't do anything, and if it requires a return value, a basic version of that.

e.g.

```
<MyChildComponent MyFunc="@(MyFunc ?? MyFuncEmpty)" />

@code {
    [Parameter]
    public Func<int, string> MyFunc { get; set; }

    private MyFuncEmpty(int i)
    {
        return "";
    }
}
```

**Comment by kswoll** [comment] 2021-02-03 18:16
As discussed, this bug makes chaining nullable delegates from one component to another very difficult.  I believe it's a common pattern where the absence of the delegate indicates falling back to some default behavior.  (For example, a string formatter delegate that defaults to `.ToString()`)

The only viable workaround I could find is to create a shadow property of the delegate in the nested component.  For example, my "list view" component has a property named `ItemFormatter`:

```
[Parameter]
public Func<T, string>? ItemFormatter { get; set; }
```

The outer component also has this property, intending to chain it to the nested component.  When the value of the delegate in the outer component is null, this error occurs.  Therefore, I created a shadow property in the nested component:

```
[Parameter]
public object? ItemFormatterRaw
{
    get => ItemFormatter;
    set => ItemFormatter = (Func<T, string>?)value;
}
```

Then in the outer component, I set `ItemFormatterRaw` instead of `ItemFormatter` and this problem goes away (since blazor doesn't try to do the delegate creation since the property type is not declared as a delegate).

I think this bug is annoying, but hopefully this workaround can help others until it is fixed.

**Comment by ChristianWeyer** [comment] 2021-03-12 09:40
I am running into this right now :-)
Is there already some kind of planning for this item - what will happen with the issue?
.cc @captainsafia

Thanks!

**Comment by captainsafia** [comment] 2021-03-15 16:30
It's in our `Next sprint planning` bucket which we triage during milestone planning ([ref](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md#milestone-planning)). Depending on the importance of the issue (determine by number of votes/comments), we'll figure out whether or not it'll be done in the sprint.

The best thing to do to indicate the issue is important to you is to give it an upvote and comment with an impacting scenario if it hasn't been added already.

**Comment by Matthewsre** [comment] 2021-04-09 03:34
I have some scenarios that break from this bug where depending on how the user got to the component the parent gets notified of certain events if it passes a delegate. If there is a middle component this breaks and I am doing the following to temporarily resolve this in that middle component:

```
        [Parameter]
        public Func<Task> CompleteDelegate { get; set; } = () => Task.CompletedTask;

        [Parameter]
        public Func<Task> CancelDelegate { get; set; } = () => Task.CompletedTask;
```

In the component at the end of the chain I have null checks:


```
        [Parameter]
        public Func<Task> CompleteDelegate { get; set; }

        [Parameter]
        public Func<Task> CancelDelegate { get; set; }

	public async Task Submit()
        {
            // Do submission stuff

            if (success && CompleteDelegate != null) await CompleteDelegate.Invoke();
        }
		
	public async Task Cancel()
        {
            // Do cancellation stuff

            if (CancelDelegate != null) await CancelDelegate.Invoke();
        }
```

Some scenarios the parent might need to take an action, in other scenarios they don't care and don't pass a delegate.

**Comment by JHBonarius** [comment] 2021-04-20 18:06
I'm watching this now, my issue was closed because of this dupe. Really would like to see this fixed

**Comment by oiBio** [comment] 2021-04-21 06:20
same with mine #31940 
looking forward to preview 5 :-)

**Closed** 2021-05-05 15:03 UTC
Labels: Working, affected-medium, area-blazor, bug, feature-blazor-component-model, feature-rendering, severity-minor
