### ISSUE TITLE
Problem registering GET routing handler after using routing groups and adding a filter

### ISSUE THREAD

**Issue by wangfei9999** [dotnet/aspnetcore#56511] opened 2024-06-28 15:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
using WebApplication3;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapGroup("/").AddEndpointFilter<Filter>().MapGet("/jac", () => int.MaxValue);

app.Run();

internal record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}

public class Filter : IEndpointFilter
{
    public ValueTask<object?> InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)
    {
        return next(context);
    }
}
```
![image](https://github.com/dotnet/aspnetcore/assets/73685882/0af1a813-ec91-46ee-ad28-62ddd484f134)

### .NET Version

net8.0

**Comment by captainsafia** [comment] 2024-08-20 04:29
@wangfei9999 Thanks for filing this issue! In this particular case, the problem is unrelated to the order in which you call `MapGroup`, `AddEndpointFilterFactory`, and `MapGet`. I believe your issue is actually a dupe of https://github.com/dotnet/aspnetcore/issues/52128. Closing in favor of tracking there.

**Closed by captainsafia** 2024-08-20 04:29 UTC
Labels: area-web-frameworks
