### ISSUE TITLE
Multiple @Body(RenderFragment or sections) in blazor

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/aspnetcore#42880] opened 2022-07-23 09:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I've search in issues for this problem and found somethings about section's that's Handled by <Title/> and...
but how can i create Blazor Layout with multiple sections some thing like this :

 
```
<div>
     @Body
</div>
<div>
     @RightSidebar
</div>
```
 

this is very important to separate layout sections from others.
in the page we have static Header and Header values , static body and right sidebar(without values) we need to give them values from component that used this layout.
how we can create layout that support this!?

### Describe the solution you'd like

give us a way to make Custom Body or create a way to send RenderFragment parameters and params to Layout

**Comment by thecobblah** [comment] 2022-07-23 14:44
Custom body a must

**Comment by sajjadarashhh** [comment] 2022-07-24 09:29
@thecobblah we can take this Approach in current release!?

**Comment by knight1219** [comment] 2022-07-24 18:01
Why not separate into a component and just include that component in the Layout? What is special about your RenderFragment?

```
 <div>
     @Body
</div>
<div>
     <RightSidebar />
</div>
```

**Comment by sajjadarashhh** [comment] 2022-07-24 18:54
Right Side bar must be filled by pages each page have custom right-side bar and this not good to create repetition in project.
now I don't use layout for my project.

**Comment by javiercn** [comment] 2022-07-25 09:32
@sajjadarashhh thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/28182

**Closed by javiercn** 2022-07-25 09:32 UTC
Labels: area-blazor, feature-blazor-component-model
