### ISSUE TITLE
[BLAZOR] `<a href="#">` tag redirect to root page.

### ISSUE THREAD

**Issue by Drit-team** [dotnet/aspnetcore#33551] opened 2021-06-15 15:56 UTC
### Describe the bug
`<a href="#">` tag redirects us to `/` route.

In the image, I'm in `/Hi` route and I have an `<a href="#"` tag, its redirect me to root page of project.
What I expect is: redirect us to `/hi/#` without reloading page.
![image](https://user-images.githubusercontent.com/85952041/122085210-bd464200-ce17-11eb-8a72-925e6251fdb2.png)

### Further technical details
![image](https://user-images.githubusercontent.com/85952041/122085415-ef57a400-ce17-11eb-9c8b-eea4a74c0b4e.png)

**Comment by mkArtakMSFT** [comment] 2021-06-15 16:27
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/6175

**Closed by mkArtakMSFT** 2021-06-15 16:27 UTC
Labels: area-blazor, feature-routing
