### ISSUE TITLE
Give the BlazorWasmDebugging extension a proper name

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#46486] opened 2023-02-06 17:18 UTC
The BlazorWasmDebugging extension is currently called [Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.blazorwasm-companion). This makes the extension really difficult to search for. We should rename it to something like: "Blazor WebAssembly debugging".

**Comment by captainsafia** [comment] 2023-02-07 17:45
For some context here, the extension was given a bit of an incognito name because it was designed to be an accessory to the C# extension. The core Blazor WASM debugging functionality is still bundled into the C# extension, the one above is just the companion extension you need for remote debugging scenario.

I think renaming it is fine but it should be done in a way that makes it clear it's not the requirement for debugging Blazor WASM (the C# extension is still required) and that it is most helpful for remote debugging scenarios.

**Comment by Nick-Stanton** [comment] 2023-02-15 20:14
Obsoleted following the closure of https://github.com/dotnet/aspnetcore/issues/46485

**Comment by mkArtakMSFT** [comment] 2023-06-29 22:50
Closing as we don't have an extension any moire.

**Closed by mkArtakMSFT** 2023-06-29 22:50 UTC
Labels: enhancement, area-blazor, feature-blazor-debugging, Priority:1, feature-blazor-vscode-extension
