### ISSUE TITLE
New Blazor Server App has issues on .NET 6 Preview. 

### ISSUE THREAD

**Issue by kunaldas1997** [dotnet/aspnetcore#34727] opened 2021-07-26 18:29 UTC
With the image you might see the issue.

Occurance:

`dotnet new blazorserver -o WebApp --no-https` 

![image](https://user-images.githubusercontent.com/26971428/127039619-69934edd-f1d1-4ab3-bbf1-596d150dee3a.png)

The issue as on Terminal
![image](https://user-images.githubusercontent.com/26971428/127039961-7a0a11b1-c236-4792-be3c-dcf83851e0e7.png)

**Comment by pranavkm** [comment] 2021-07-27 16:30
Dupe of https://github.com/dotnet/aspnetcore/issues/33832. In the meanwhile consider using a path that does not have a # in it.

**Closed** 2021-07-27 16:43 UTC
Labels: area-blazor
