### ISSUE TITLE
ShadowCopy dir set inside current dir causes recursive copies of itself

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#31864] opened 2021-04-16 05:17 UTC
### Describe the bug
When enabling the new experimental shadowCopy, the startup time can be 2+ min.

### To Reproduce
Web.config:
```
               <handlerSetting name="experimentalEnableShadowCopy" value="true" />
               <handlerSetting name="shadowCopyDirectory" value="./ShadowCopyDirectory/" />
```

Repro code:

```
   [ApiController]
   public class MyController : ControllerBase
   {
      [HttpGet("Test")]
      public string Test() =>  "working";
   }
```

Published to "Folder", hosted in IIS in subfolder, "converted to application" on folder.

Occasionally after serving the first request (after the 2+min), it immediately shuts down and returns a 503 on the next request. The next request again triggers the 2+ min delay again.

The 503 might be a timing issue if requesting something right after making a change.

### Exceptions (if any)
Debug logs shows:
```
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN'
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] Stopping application '/LM/W3SVC/2/ROOT/CdnAdmin'
[aspnetcorev2_inprocess.dll] Stopping file watching.
[aspnetcorev2_inprocess.dll] Starting copy on shutdown in filewatcher, creating directory.
[aspnetcorev2_inprocess.dll] Copying new shadow copy directory to c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\7.
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Drained all requests, notifying managed.
[aspnetcorev2_inprocess.dll] Waiting for 0 requests to drain
[aspnetcorev2_inprocess.dll] Managed application exited with code 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 1
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN' has shutdown.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Canceling standard stream pipe reader
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] AspNetCore InProcess Recycle Process on Demand
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
```
or
```
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN'
[aspnetcorev2.dll] Stopping application '/LM/W3SVC/2/ROOT/CdnAdmin'
[aspnetcorev2_inprocess.dll] Stopping file watching.
[aspnetcorev2_inprocess.dll] Starting copy on shutdown in filewatcher, creating directory.
[aspnetcorev2_inprocess.dll] Copying new shadow copy directory to c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8.
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Drained all requests, notifying managed.
[aspnetcorev2_inprocess.dll] Waiting for 0 requests to drain
[aspnetcorev2_inprocess.dll] Managed application exited with code 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 1
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN' has shutdown.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Canceling standard stream pipe reader
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] AspNetCore InProcess Recycle Process on Demand
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
```

Then on the first request, this is added:
```
[aspnetcorev2.dll] Initializing logs for 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll'. Process Id: 14208.. File Version: 16.0.21092.0. Description: IIS ASP.NET Core Module V2. Commit: 718171eeb4bd236ab4f0d9b1ecd97ecc63ec0be1.
```
Here it hangs for 2+ min... Then continues with:
```
[aspnetcorev2.dll] Resolving hostfxr parameters for application: '.\CdnAdmin.exe' arguments: '' path: 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8'
[aspnetcorev2.dll] Known dotnet.exe location: ''
[aspnetcorev2.dll] Process path '.\CdnAdmin.exe' is not dotnet, treating application as standalone or portable with bootstrapper
[aspnetcorev2.dll] Checking application.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2.dll] Checking hostfxr.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll'
[aspnetcorev2.dll] hostfxr.dll not found at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll', treating application as portable with launcher
[aspnetcorev2.dll] Resolving absolute path to dotnet.exe from 'dotnet'
[aspnetcorev2.dll] Invoking where.exe to find dotnet.exe
[aspnetcorev2.dll] where.exe invocation returned: 'C:\Program Files\dotnet\dotnet.exe
C:\Program Files (x86)\dotnet\dotnet.exe
'
[aspnetcorev2.dll] Current process bitness type detected as isX64=1
[aspnetcorev2.dll] Processing entry 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Binary type 6
[aspnetcorev2.dll] Found dotnet.exe via where.exe invocation at 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll'
[aspnetcorev2.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll' arguments:
[aspnetcorev2.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2.dll] Argument[1] = 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2.dll] Loading hostfxr from location C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll
[aspnetcorev2.dll] Canceling standard stream pipe reader
[aspnetcorev2.dll] Loading request handler:  'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.0-preview.3.21201.13\aspnetcorev2_inprocess.dll'
[aspnetcorev2.dll] Creating handler application
[aspnetcorev2_inprocess.dll] Initializing logs for 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.0-preview.3.21201.13\aspnetcorev2_inprocess.dll'. Process Id: 38756.. File Version: 16.0.21092.0. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 718171eeb4bd236ab4f0d9b1ecd97ecc63ec0be1.
[aspnetcorev2_inprocess.dll] Waiting for initialization
[aspnetcorev2_inprocess.dll] Starting app_offline monitoring in application 'c:\src\Cdn\CdnAdmin\'
[aspnetcorev2_inprocess.dll] Starting file watcher thread
[aspnetcorev2_inprocess.dll] Starting in-process worker thread
[aspnetcorev2_inprocess.dll] Resolving hostfxr parameters for application: '.\CdnAdmin.exe' arguments: '' path: 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8'
[aspnetcorev2_inprocess.dll] Known dotnet.exe location: 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Process path '.\CdnAdmin.exe' is not dotnet, treating application as standalone or portable with bootstrapper
[aspnetcorev2_inprocess.dll] Checking application.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2_inprocess.dll] Checking hostfxr.dll at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll'
[aspnetcorev2_inprocess.dll] hostfxr.dll not found at 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\hostfxr.dll', treating application as portable with launcher
[aspnetcorev2_inprocess.dll] Resolving absolute path to hostfxr.dll from 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] hostfxr.dll located at 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll'
[aspnetcorev2_inprocess.dll] Parsed hostfxr options: dotnet location: 'C:\Program Files\dotnet\dotnet.exe' hostfxr path: 'C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll' arguments:
[aspnetcorev2_inprocess.dll] Argument[0] = 'C:\Program Files\dotnet\dotnet.exe'
[aspnetcorev2_inprocess.dll] Argument[1] = 'c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\8\.\CdnAdmin.dll'
[aspnetcorev2_inprocess.dll] Setting environment variable ASPNETCORE_IIS_HTTPAUTH=anonymous;
[aspnetcorev2_inprocess.dll] Setting environment variable ASPNETCORE_IIS_PHYSICAL_PATH=c:\src\Cdn\CdnAdmin\
[aspnetcorev2_inprocess.dll] Loading hostfxr from location C:\Program Files\dotnet\host\fxr\6.0.0-preview.3.21201.4\hostfxr.dll
[aspnetcorev2_inprocess.dll] Initial Dll directory: '', current directory: 'c:\windows\system32\inetsrv'
[aspnetcorev2_inprocess.dll] Setting dll directory to c:\windows\system32\inetsrv
[aspnetcorev2_inprocess.dll] Setting current directory to c:\src\Cdn\CdnAdmin\
[aspnetcorev2_inprocess.dll] In-process callbacks set
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'c:\src\Cdn\CdnAdmin\' started successfully.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Adding request. Total Request Count 1
[aspnetcorev2_inprocess.dll] Removing Request 0
```

log when getting the 503:
```
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalConfigurationChange 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN'
[aspnetcorev2_inprocess.dll] Detected dll change, resetting timer callback which will eventually trigger shutdown.
[aspnetcorev2.dll] Stopping application '/LM/W3SVC/2/ROOT/CdnAdmin'
[aspnetcorev2_inprocess.dll] Stopping file watching.
[aspnetcorev2_inprocess.dll] Starting copy on shutdown in filewatcher, creating directory.
[aspnetcorev2_inprocess.dll] Copying new shadow copy directory to c:\src\Cdn\CdnAdmin\ShadowCopyDirectory\9.
[aspnetcorev2_inprocess.dll] Stopping CLR
[aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
[aspnetcorev2_inprocess.dll] Drained all requests, notifying managed.
[aspnetcorev2_inprocess.dll] Waiting for 0 requests to drain
[aspnetcorev2_inprocess.dll] Managed application exited with code 0
[aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 1
[aspnetcorev2_inprocess.dll] Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/TESTCDN/CDNADMIN' has shutdown.' 
End Event Log Message.
[aspnetcorev2_inprocess.dll] Canceling standard stream pipe reader
[aspnetcorev2_inprocess.dll] Stopping in-process worker thread
[aspnetcorev2_inprocess.dll] AspNetCore InProcess Recycle Process on Demand
[aspnetcorev2.dll] Application went offline
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
[aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
```
It doesnt show the "startup" line with
`[aspnetcorev2.dll] Initializing logs for 'C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll'. Process Id: 14208.. File Version: 16.0.21092.0. Description: IIS ASP.NET Core Module V2. Commit: 718171eeb4bd236ab4f0d9b1ecd97ecc63ec0be1.` when showing the 503.

### Further technical details
- .net 6 preview 3

![image](https://user-images.githubusercontent.com/1201165/114974373-73d78600-9eac-11eb-8da4-a66f5fc1a56e.png)
![image](https://user-images.githubusercontent.com/1201165/114974396-7fc34800-9eac-11eb-815d-7cc2dfa54649.png)
![image](https://user-images.githubusercontent.com/1201165/114974845-5f47bd80-9ead-11eb-843e-cddc641cca37.png)

**Comment by davidfowl** [comment] 2021-04-16 06:25
How many files do you have?

**Comment by davhdavh** [comment] 2021-04-16 06:43
1 controller... It's just the default web api template with that controller and `app.UsePathBase("/CdnAdmin");`

**Comment by davhdavh** [comment] 2021-04-16 06:45
dump file while hanging. Hope that helps.
Also tested with ReadyToRun and single file deployment. No difference.

[w3wp.zip](https://github.com/dotnet/aspnetcore/files/6323037/w3wp.zip)

**Comment by davhdavh** [comment] 2021-04-16 06:55
Found the problem when cleaning up and starting over... The shadowcopy folder had 30k+ files.
A bit more investigation shows that the shadowcopy folder is not excluded from the shadowcopy, so it ends up doing a ton of copies of itself.

**Comment by davidfowl** [comment] 2021-04-16 07:15
Nice find, it did sound like that type of issue.

**Comment by davhdavh** [comment] 2021-04-16 08:54
I suggest 2 changes:
a. Exclude shadowCopy folder from the shadowCopy **OR** Give error 
b. Debug log should inform when copy starts and afterwards how many files copied and how long it took.

**Comment by BrennanConroy** [comment] 2021-04-16 20:22
Thanks for the great issue and diagnosis! This is a dupe of https://github.com/dotnet/aspnetcore/issues/31570, but we like this issue better so we'll close the other one ;)

**Closed** 2021-04-30 02:26 UTC
Labels: area-runtime, bug, servers-iis
