### ISSUE TITLE
Identity redirection doesn't respect route configuration

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/aspnetcore#18586] opened 2020-01-26 07:44 UTC
### Describe the bug
Using `Authorize` attribute redirect anonymous users to `/Account/Login?ReturnUrl=blah`. this redirect doesn't respect following configuration:

```cs
services.AddRouting(options => options.LowercaseUrls = true);
```

### To Reproduce
1. `dotnet new web -n test`
2. Add following to `Startup.cs`
```cs
services.AddRouting(options => options.LowercaseUrls = true);
services.AddControllersWithViews();

services.AddAuthentication();
services.AddAuthorization();
```
3. Also this guys:
```cs
app.UseAuthentication();
app.UseAuthorization();
```
4. Add `HomeController` to the project with following content _and you need to add empty `Index.cshtml` to_
```cs
public class HomeController : Controller
{
    [Authorize]
    public IActionResult Index() => View();
}
```
5. Hit `Ctrl+F5`, in the browser you will see `http://localhost:XXXX/Account/Login?ReturnUrl=%2F`

But it should be `http://ocalhost:15368/account/login?returnurl=%2F`, because of `options.LowercaseUrls = true` .

### Further technical details
- ASP.NET Core version _3.1.1_
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version. _Visual Studio 2019_

**Comment by Kahbazi** [comment] 2020-01-26 11:00
Possible duplicate of https://github.com/dotnet/aspnetcore/issues/4640

**Comment by tlaukkanen** [comment] 2020-02-04 13:20
Do you think this is related also to custom login URLs too?
I'm setting custom LoginUrl to IdentityServer with:
```
services.AddIdentityServer(options => options.UserInteraction.LoginUrl = "/login")
```
...but with `[Authorized]` Controller I'm still getting redirected to `https://localhost:5001/Account/Login?ReturnUrl=..` whereas I was expecting is to see redirect to `https://localhost:5001/login?...` path.

**Comment by dehghani-mehdi** [comment] 2020-02-04 13:59
@tlaukkanen  You should customize cookie settings, see [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-3.1#cookie-settings)

**Comment by blowdart** [comment] 2020-02-05 20:14
IdentityUI is a self contained package, so it can't respect casing for the rest of the app without an awful lot of redesign for what is very little benefit.

Closing as by design.

**Closed by blowdart** 2020-02-05 20:14 UTC
Labels: area-identity
