### ISSUE TITLE
Blazor WASM Issues VS Code 1.57.x

### ISSUE THREAD

**Issue by tomschrot** [dotnet/aspnetcore#34029] opened 2021-07-02 08:18 UTC
## Is this a Bug or Feature request?:
Bug

## Steps to reproduce
------------------- Please fill in this section -------------------------

## Description of the problem:
------------------- Please fill in this section -------------------------

Expected behavior:

Actual behavior:

#### OmniSharp
------------------- Please fill in this section -------------------------
To find the OmniSharp log, open VS Code's "Output" pane, then in the dropdown choose "OmniSharp Log".

#### Razor
<details><summary>Expand</summary>
<p>

```
[Client - 10:16:02] -- Starting Issue Data Collection-- 
[Client - 10:16:09] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\Pages\Counter.razor' changed 'opened'
[Client - 10:16:09] Updating the C# document for Razor file 'c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/Pages/Counter.razor' (1)
[Client - 10:16:09] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\Pages\Counter.razor' changed 'csharpChanged'
[Client - 10:16:09] Updating the HTML document for Razor file 'c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/Pages/Counter.razor' (1)
[Client - 10:16:09] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\Pages\Counter.razor' changed 'htmlChanged'
[Client - 10:16:12] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\Pages\Counter.razor' changed 'closed'
[Client - 10:16:22] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\_Imports.razor' changed 'opened'
[Client - 10:16:22] Updating the C# document for Razor file 'c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor' (1)
[Client - 10:16:22] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\_Imports.razor' changed 'csharpChanged'
[Client - 10:16:22] Updating the HTML document for Razor file 'c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor' (1)
[Client - 10:16:22] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\_Imports.razor' changed 'htmlChanged'
[Client - 10:16:31] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\Components\Name.razor' changed 'opened'
[Client - 10:16:31] Updating the C# document for Razor file 'c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/Components/Name.razor' (1)
[Client - 10:16:31] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\Components\Name.razor' changed 'csharpChanged'
[Client - 10:16:31] Updating the HTML document for Razor file 'c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/Components/Name.razor' (1)
[Client - 10:16:31] Notifying document 'c:\Users\anonymous\Desktop\dotnet\gRPC\gRPCApp\Components\Name.razor' changed 'htmlChanged'
[Client - 10:16:56] -- Stopping Issue Data Collection-- 
```

</p>
</details>

#### Razor document:
<details><summary>Expand</summary>
<p>

```Razor
@using System.Net.Http
@using System.Net.Http.Json
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Web.Virtualization
@using Microsoft.AspNetCore.Components.WebAssembly.Http
@using Microsoft.JSInterop
@using gRPCApp.Shared

```

</p>
</details>

#### Projected CSharp document:
<details><summary>Expand</summary>
<p>

```C#
////////////////////// Projected CSharp as seen by extension ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace __GeneratedComponent
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using gRPCApp.Shared;

#line default
#line hidden
#nullable disable
    public partial class AspNetCore_f7241efec46ec4b5fb9f7a4e1f011e594aade5bf : System.Object
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected void Execute()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591



////////////////////// Projected CSharp as seen by VSCode ///////////////////////
// <auto-generated/>
#pragma warning disable 1591
namespace __GeneratedComponent
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "c:/Users/anonymous/Desktop/dotnet/gRPC/gRPCApp/_Imports.razor"
using gRPCApp.Shared;

#line default
#line hidden
#nullable disable
    public partial class AspNetCore_f7241efec46ec4b5fb9f7a4e1f011e594aade5bf : System.Object
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected void Execute()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591

// 1
```

</p>
</details>

#### Projected Html document:
<details><summary>Expand</summary>
<p>

```Html
////////////////////// Projected Html as seen by extension ///////////////////////
~~~~~~ ~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~



////////////////////// Projected Html as seen by VSCode ///////////////////////
~~~~~~ ~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~~~~~~
~~~~~~ ~~~~~~~~~~~~~~

// 1
```

</p>
</details>

## Machine information

**VSCode version**: 1.57.1
**Razor.VSCode version**: 1.23.12
#### `dotnet --info`

<details><summary>Expand</summary>
<p>

```
.NET SDK (gem�� "global.json"):
 Version:   5.0.202
 Commit:    db7cc87d51

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

</p>
</details>

#### Extensions
<details><summary>Expand</summary>
<p>

|Extension|Author|Version|
|---|---|---|
|apexsql-power-tools|vs-publisher-988541|2021.1.81|
|auto-close-tag|formulahendry|0.5.10|
|auto-rename-tag|formulahendry|0.1.6|
|auto-using|Fudge|0.7.15|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|Bookmarks|alefragnani|13.1.0|
|comments|AlexCoderCorp|1.0.5|
|csharp|ms-dotnettools|1.23.12|
|csharpextensions|jchannon|1.3.1|
|csharpsortusings|jongrant|0.0.3|
|debugger-for-chrome|msjsdiag|4.12.12|
|docomment|k--kato|0.1.20|
|gistfs|vsls-contrib|0.2.9|
|git-graph|mhutchie|1.30.0|
|gitignore|codezombiech|0.7.0|
|hexeditor|ms-vscode|1.7.1|
|highlight-matching-tag|vincaslt|0.10.1|
|js-debug-nightly|ms-vscode|2021.6.1117|
|json|ZainChen|2.0.2|
|material-icon-theme|PKief|4.7.0|
|mysql-syntax|jakebathman|1.3.1|
|php-debug|felixfbecker|1.16.0|
|php-intellisense|felixfbecker|2.3.14|
|php-pack|felixfbecker|1.0.2|
|project-manager|alefragnani|12.2.0|
|sqltools|mtxr|0.23.0|
|sqltools-driver-mysql|mtxr|0.2.0|
|syncing|nonoroazoro|3.1.0|
|todo-tree|Gruntfuggly|0.0.213|
|vscode-dotnet-runtime|ms-dotnettools|1.1.0|
|vscode-highlight|fabiospampinato|1.5.0|
|vscode-icons|vscode-icons-team|11.5.0|
|vscode-intelephense-client|bmewburn|1.7.1|
|vscode-language-pack-de|MS-CEINTL|1.57.1|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-open-in-github|ziyasal|1.3.6|
|vscode-proto3|zxh404|0.5.4|
|vscode-solution-explorer|fernandoescolar|0.4.3|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|
|workbench|andrew-lis|0.1.7|
|zoombar-vscode|wraith13|1.4.0|;

</p>
</details>

**Comment by mkArtakMSFT** [comment] 2021-07-02 16:16
Thanks for contacting us. It's not immediately clear what's the concern that you're raising here? Can you please share more details regarding the issue and where you see it?

**Comment by tomschrot** [comment] 2021-07-03 07:33
Hi

Opening the folder of a fresh created blazorwasm project

dotnet new blazorwasm -o TestWasm

with VS Code always results with an error and leaves the Language Server
somewhat confused

please see screenshot

[image: VSCode Blazor.jpg]


Am Fr., 2. Juli 2021 um 18:16 Uhr schrieb Artak ***@***.***>:

**Comment by pranavkm** [comment] 2021-07-06 16:55
Thanks @tomschrot. This is a dupe of  #33858 and we'll use the other issue to track addressing this.

**Closed by pranavkm** 2021-07-06 16:55 UTC
Labels: Needs: Attention :wave:, area-blazor, blazor-wasm
