### ISSUE TITLE
.NET 6 Minimal API - WebApplicationFactory doesn't see custom settings json file values

### ISSUE THREAD

**Issue by djfoxer** [dotnet/aspnetcore#38435] opened 2021-11-16 15:32 UTC
### Describe the bug
I'm migrating .NET5 API to .NET 6 Minimal API and I run into small isue with `WebApplicationFactory` in testing.
I can't now add custom appsettings.Test.json for `WebApplicationFactory` (it works with .NET 5 API).

### To Reproduce

I have Minima API:

```csharp
var builder = WebApplication.CreateBuilder(args);

//by WebApplicationFactory data has always default value 
var data = builder.Configuration.GetSection("ReverseProxy").Get<CfgType>(); 


builder.Services
    .AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));


var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.MapReverseProxy();

app.Run();

public partial class Program { }
```

and when I run my test by `WebApplicationFactory` it can't see values from `appsettings.TEST.json` (I see only default ones from  `appsettings.json` )

```csharp

public class MyApiWebApplicationFactory : WebApplicationFactory<Program>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            base.ConfigureWebHost(builder);

            builder.UseEnvironment("TEST");
            builder.ConfigureAppConfiguration(config =>
            {
                config.AddJsonFile("appsettings.TEST.json");
            });
        }
    }

```

### Further technical details
- ASP.NET Core version: 6.0

**Comment by djfoxer** [comment] 2021-11-16 20:43
I now see that maybe it doesn't take into account data from appsettings.Test.json because value is took from Configuration before `builder.Build()`. But why it has such a strange flow only through `WebApplicationFactory` ?

**Comment by kristofferjalen** [comment] 2021-11-16 21:53
Here's my question on SO on the same issue: https://stackoverflow.com/questions/69986598/with-webapplicationfactory-add-configuration-source-before-program-cs-executes

**Comment by davidfowl** [comment] 2021-11-17 04:54
This is currently not possible with the way the code is written unfortunately. This is a dupe of https://github.com/dotnet/aspnetcore/issues/37680.

The WebApplicationFactory is currently unable to override configuration that is read before the call to build.

**Comment by djfoxer** [comment] 2021-11-17 07:25
@davidfowl Ok. Thank you for your answer. I'll try to write a workaround to access overridden config after build statement.

**Comment by kristofferjalen** [comment] 2021-11-17 12:58
@djfoxer A workaround could be to set environment:

```c#
public class CustomWebApplicationFactory<TProgram>
    : WebApplicationFactory<TProgram> where TProgram : class
{
    protected override IHost CreateHost(IHostBuilder builder)
    {
        builder.UseEnvironment("IntegrationTests");

        return base.CreateHost(builder);
    }    
}
```
and then in Program do:
```c#
var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddJsonFile($"appsettings.{builder.Environment.EnvironmentName}.json");
```

**Closed** 2021-11-17 15:18 UTC
Labels: investigate, feature-mvc-testing, area-web-frameworks

**Comment by djfoxer** [comment] 2021-11-17 15:19
@kristofferjalen Thank you for your workaround.
