### ISSUE TITLE
Adding a namespace called System will prevent Blazor applications to compile.

### ISSUE THREAD

**Issue by pekspro** [dotnet/aspnetcore#22139] opened 2020-05-22 15:21 UTC
### Describe the bug
Let say you have on Blazor application within the namespace Unicorn.Web. If you then add a file with the namespace Unicorn.System in that project, the project will no longer compile.

I know that having a namespace called System might be a bad idea :-) But I thought it should be possible to compile if I fix the default imports in _Imports.razor but it doesn't seem to be enough,

If you do the same in an MVC application it will work fine.

### To Reproduce
Create a new Blazor application:

``` 
dotnet new blazorserver --name Unicorn.Web
```

Create a new file new using then namespace Unicorn.System:
``` 
cd .\Unicorn.Web\
echo "namespace Unicorn.System {}" > test.cs
```

And then compile:
``` 
dotnet build
```

You will get errors like this:

```
obj\Debug\netcoreapp3.1\RazorDeclaration\App.razor.g.cs(12,18): error CS0234: The type or namespace name 'Collections' does not exist in the namespace 'Unicorn.System' (are you missing an assembly reference?) 
obj\Debug\netcoreapp3.1\RazorDeclaration\App.razor.g.cs(13,18): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'Unicorn.System' (are you missing an assembly reference?) 
obj\Debug\netcoreapp3.1\RazorDeclaration\App.razor.g.cs(14,18): error CS0234: The type or namespace name 'Threading' does not exist in the namespace 'Unicorn.System' (are you missing an assembly reference?)
```

### Further technical details
ASP.NET Core 3.1.5

**Comment by mkArtakMSFT** [comment] 2020-05-26 17:12
This is a dupe of https://github.com/dotnet/aspnetcore/issues/18757

**Closed by mkArtakMSFT** 2020-05-26 17:12 UTC
Labels: area-blazor, area-razor.tooling
