### ISSUE TITLE
Blazor Virtualize component doesn't render in vscode webview

### ISSUE THREAD

**Issue by maloo** [dotnet/aspnetcore#28277] opened 2020-12-01 15:22 UTC
### Describe the bug
I have a vscode extension that contains a webview panel. Scripting is enabled in the panel to allow Blazor to work inside of it. The webview html content is just an iframe pointing to localhost:5000 blazor project. This works just fine for every component in the project except the new Virtualize component. The resulting output is just empty space. If I open the same url in Edge/Firefox/Chrome on the same machine, it displays just fine.
The project is a basic Blazor Server app.

Is the new Virtualize component using some special features of modern browsers that are not available in vscode/electron webviews? Is it using WASM?

### To Reproduce
See above, or just create a sample vscode extension with a webview panel and add an iframe pointing to the blazor server page with a Virtualize component.

### Exceptions (if any)
None

### Further technical details
- ASP.NET Core version:
5.0.0
- Include the output of `dotnet --info`:
SDK 5.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Rider 2020.2.3 or dotnet cli

**Comment by mkArtakMSFT** [comment] 2020-12-01 17:34
Thanks for contacting us. This seems to be a dupe of #26790.

**Closed** 2020-12-01 17:34 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor

**Comment by maloo** [comment] 2020-12-01 18:30
No, this is not a dupe. I don't get any errors and I use Blazor Server, which works in vscode webview. This is about elements of Virtualize not getting rendered. Seems to be related to the space available in the view. Restricting the parent div and enabling overflow scroll seems to make the content render correctly.
