### ISSUE TITLE
Scaffold component with form or table for model class

### ISSUE THREAD

**Issue by michaelongithub** [dotnet/aspnetcore#32902] opened 2021-05-21 14:02 UTC
Like in ASP.NET core, scaffold **BLAZOR** components / forms for model class with appropriate html inputs.
Inclusive bindings in html elements.

### Describe the solution you'd like
Analogous to ASP.NET Mvc core to get and easy start for Html forms for Detail based on model class.
Or quickly get a html table for listing List<ModelClass>

**Comment by mkArtakMSFT** [comment] 2021-11-16 19:43
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/6921

**Closed by mkArtakMSFT** 2021-11-16 19:43 UTC
Labels: enhancement, area-blazor
