### ISSUE TITLE
ARM64 support in AspNetCoreModuleV2

### ISSUE THREAD

**Issue by ericstj** [dotnet/aspnetcore#36519] opened 2021-09-14 22:06 UTC
### Describe the bug

In reviewing code in dotnet that tries to locate dotnet.exe I came across https://github.com/dotnet/aspnetcore/blob/de277154511effa33f946a34ccc77deb074ce1c2/src/Servers/IIS/AspNetCoreModuleV2/CommonLib/HostFxrResolver.cpp#L273-L306

This doesn't seem like it will work well on ARM64.

1. It assumes all WOW processes are on an x64 machine.  If it needs to know the architecture of the machine it should use IsWow64Process2.
2. It assumes x64 runtime is under Program Files\dotnet, when we are going to put it under Program Files\dotnet\x64 on ARM64 machines https://github.com/dotnet/designs/blob/main/accepted/2021/x64-emulation-on-arm64/x64-emulation.md#install-location.

@shirhatti let me know that this doesn't yet support ARM64 (or presumably running in WOW or emulation on ARM64) but I wanted to file this so that you're aware of the limitation.

**Comment by adityamandaleeka** [comment] 2021-09-15 20:18
Thanks @ericstj . This will probably be addressed when we do this work: https://github.com/dotnet/aspnetcore/issues/8838

**Comment by HaoK** [comment] 2021-12-02 05:19
Resolving as dupe of #8838 as the HostFxrResolver.cpp will be deleted looking at the first iteration of using nethost in PR: https://github.com/dotnet/aspnetcore/pull/10829/files

**Closed by HaoK** 2021-12-02 05:19 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, servers-iis, area-runtime, Status: Resolved
