### ISSUE TITLE
ValidateNever applied to action parameters is not honored

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/aspnetcore#44279] opened 2022-09-30 12:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Documentation for `ValidateNeverAttribute` indicates that it can be applied to parameters. However, when applied to action parameters, the attribute has no effect and the parameter will continue to be validated.

Furthermore it appears that `ValidateNeverAttribute` is the _only_ way to actually disable model validation. There are some other approaches that _ignore_ the results of validation, but these do not disable it.

So the fact that it doesn't actually work for parameters means that in some cases the only way to use it is to apply it to a class. However if your intent is to disable automatic validation in order that you can later run the validation manually where you have more control over it, having to apply the attribute to a payload class also disables the ability to run the validation manually.

I have a scenario in which an endpoint may receive a payload consisting of a large number of complex messages. The specification requires that messages whose validatation succeeds are processed, while messages whose validation fails are not processed, and a response is returned which lists which messages failed along with any validation errors.

Since the only way to disable automatic validation at all is by adding `ValidateNever` to the payload type, then in cases where the messages do not have a containing class to which `ValidateNever` can be attached, there are no good solutions since this also prevents manual validation.

Fixing `ValidateNever` so that it works as the documentation states it does, enabling it to be applied to the action parameter would completely solve this and make the whole validation system far more flexible.

**Comment by brunolins16** [comment] 2022-09-30 20:52
@Neutrino-Sunset I agree the documentation gives a clear impression that it should work but the support to add the attribute in parameters was introduced to support `records` (https://github.com/dotnet/aspnetcore/pull/23976) but there is a known limitation to action parameters (https://github.com/dotnet/aspnetcore/issues/24241).

@dougbu Do you remember if there is any reason why we took a decision to not support this attribute for Action Parameters? I am asking because, in my opinion, this option make totally sense.

**Comment by dougbu** [comment] 2022-09-30 21:13
> @dougbu Do you remember if there is any reason why we took a decision to not support this attribute for Action Parameters? I am asking because, in my opinion, this option make totally sense.

No, I suspect we never figured out the root cause. What's strange is #23976 both added `AttributeTargets.Parameter` to the attribute's usage and added the (poorly named) `ActionParameter_WithValidateNever_DoesNotGetValidated()` test demonstrating the attribute doesn't work on parameters. We probably should have backed out both changes after confirming there be dragons.

**Comment by brunolins16** [comment] 2022-09-30 22:40
I think the root cause is the attribute is a `IPropertyValidatorFilter` and we only call `ShouldValidateEntry` when visiting a `complexType` child, never for the `top level parameter` or simple types. Of course, calling a IPropertyValidatorFilter.ShouldValidateEntry for a parameter does not make sense 😂

**Comment by brunolins16** [comment] 2022-09-30 23:25
@Neutrino-Sunset I am closing this issue as dup of #24241 since I am going to reopen it.

**Closed** 2022-09-30 23:25 UTC
Labels: area-web-frameworks

**Comment by Neutrino-Sunset** [comment] 2022-10-03 09:07
By all means close this as a dupe, but can you unlock #24241 for comments please, I may like to make some observations on the issue but it's locked for contributors only.
