### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.7.24407.12] Fail to build the app with error “System.ArgumentException: An item with the same key has already been added.”

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#57423] opened 2024-08-20 09:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When building third-party web assembly app with dotnet-sdk-9.0.100-preview.7.24407.12, we get error message:  "```error MSB4018: The "DefineStaticWebAssetEndpoints" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added. Key: E:\AppsSourceCode\radzen-blazor\RadzenBlazorDemos\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.dll```".

**Application Name:** radzen-blazor
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-9.0.100-preview.7.24407.12
**App & Source Location checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2223071

**Github Link:** 
https://github.com/radzenhq/radzen-blazor

Verify Scenarios:
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.401: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.4.24267.66: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.5.24307.3: Pass
4). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.6.24328.19: Pass
5). Windows 10 21H2 AMD64 + dotnet-sdk-9.0.100-preview.7.24407.12: Fail

### Expected Behavior

Build successfully.

### Steps To Reproduce

Minimal Repro steps: Demo attached: [Demo (1).zip](https://github.com/user-attachments/files/16672533/Demo.1.zip)

1. Create a NET 8.0 Blazor WebAssembly project.
2. Install ```Microsoft.CodeAnalysis.CSharp``` or ```Havit.Blazor.Components.Web.Bootstrap``` nuget package for Client project.
3. Navigate to .sln solution file folder, run "```dotnet new globaljson```" to enable the app build with dotnet-sdk-9.0.100-preview.7.24407.12
```
{
  "sdk": {
    "version": "9.0.100-preview.7.24407.12"
  }
}
```
5. Build the Client project.

### Exceptions (if any)

Build failed with below error:
```
E:\NugetPackageCaches\microsoft.net.sdk.webassembly.pack\9.0.0-preview.7.24405.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(347,5): error MSB4018:
      The "DefineStaticWebAssetEndpoints" task failed unexpectedly.
      System.ArgumentException: An item with the same key has already been added. Key: E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssetEndpoints.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLogging
      Context taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

### .NET Version

dotnet-sdk-9.0.100-preview.7.24407.12

### Anything else?

**Findings:**
1.When analysis the binlog ([Binlog.zip](https://github.com/user-attachments/files/16672605/Binlog.zip)) and compared with the successful binlog, these duplicated items are missing language related subfolder.

Duplicated Assets: (under ```DemoBasedRadzenBlazor.Client.csproj > Target_GenerateBuildWasmBootJson > Task DefineStaticWebAssetEndpoints > Parameters > CandidateAssets```)
```
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\Microsoft.CodeAnalysis.CSharp.resources.wasm
```
Successful build bin log:
```
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\cs\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\de\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\es\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\fr\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\it\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\ja\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\ko\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\pl\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\pt-BR\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\ru\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\tr\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\zh-Hans\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\zh-Hant\Microsoft.CodeAnalysis.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\cs\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\de\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\es\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\fr\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\it\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\ja\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\ko\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\pl\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\pt-BR\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\ru\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\tr\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\zh-Hans\Microsoft.CodeAnalysis.CSharp.resources.wasm
E:\Demos\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor\DemoBasedRadzenBlazor.Client\bin\Debug\net8.0\wwwroot\_framework\zh-Hant\Microsoft.CodeAnalysis.CSharp.resources.wasm
```
2. It seems introduced by this commit:
[[StaticWebAssets] Fix subpath issue on SWA dev manifest (#42227) · dotnet/sdk@79c270e (github.com)](https://github.com/dotnet/sdk/commit/79c270e9c0464a5a097b13f57e3faeacbaebbc20)

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment] 2024-08-20 09:14
@javiercn   Could you please help investigate this issue? Thanks.

**Comment by webprofusion-chrisc** [comment] 2024-08-20 10:16
See also related issue https://github.com/dotnet/aspnetcore/issues/56176

**Comment by robertmclaws** [comment] 2024-08-20 15:07
Thanks for looking into this!

While you're trying to fix it, if it's possible to modify the .targets file to mitigate the issue so we don't have to wait for the next preview, that would be awesome. Appreciate you!

**Comment by Andrzej-W** [comment] 2024-08-20 16:28
I have exactly the same problem on dotnet 8 WASM hosted project (it includes Devexpress components) after installing 9 preview 7. I added global.json to build this project without uninstalling 9 preview 7
```json
{
  "sdk": {
    "version": "8.0.400"
  }
}
```

**Comment by rockfordlhotka** [comment] 2024-08-21 19:27
Like @Andrzej-W, I have a Blazor 8 project that no longer builds on a machine where .NET 9 preview is installed. Hopefully the global.json workaround is the answer.

**Comment by javiercn** [comment] 2024-08-21 19:42
@rockfordlhotka @Andrzej-W this issue can happen for multiple reasons.

If you can provide individual repros for your cases as separate GH issues, that would be of great help in investigating.

**Comment by javiercn** [comment] 2024-08-21 19:53
@Junjun-zhao I just tried out with the latest nightly and can't reproduce the issue.

**Comment by robertmclaws** [comment] 2024-08-21 20:05
@javiercn How do I get that SDK installed on my machine so I can try it from here?

**Comment by javiercn** [comment] 2024-08-21 20:14
@robertmclaws rather than installing the SDK via MSI or similar, I recommend extracting the zip and setting up some environment variables. It makes it easier to test things out without polluting your machine.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script contains a one liner to do it.

I've tweaked it here to install a local copy on the `./.dotnet` folder. If you run it from the root of your repo it will just put it there.

```
# Run a separate PowerShell process because the script calls exit, so it will end the current PowerShell session.
&powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 9.0.1xx -InstallDir ./.dotnet"
```
Then just set the following:
```
$env:DOTNET_ROOT = Resolve-Path ./.dotnet
$env:Path = $env:DOTNET_ROOT + ";" + $env:Path"
```
If you run `dotnet --info` it'll print the version.

Then you can build from the command line or start Visual Studio from that shell (start `<<my-sln>>`) and VS will use that SDK version.

In any case, it'll be simpler to just use the command line for reproducing it.

**Comment by robertmclaws** [comment] 2024-08-21 20:52
Those instructions did not work. I get an error that says "failed to resolve the exact version number".

 Here's what did:

1) Download the nightly build MSI from the [nightly build table](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md) and execute the installer.
2) Since the problem is actually in the workloads and not the SDK, you need to be able to update the workload. Add this URL to your NuGet package feeds: `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json`
3) Open a Terminal window and type "dotnet workload update"

Doing this updated everything successfully, and I was able to build successfully... locally.

Now I have to figure out how to do this on our build servers.

Having said that, what should really happen here is the team should heavily consider backporting the fix to the Preview 7 branch and release an updated `wasm` workload. /cc @terrajobst @danroth27 @SteveSandersonMS

**Comment by javiercn** [comment] 2024-08-21 20:55
@robertmclaws sorry, I have a bunch of my own script helpers to do a bunch of these things, and I was trying to simplify things. You can pass `-Quality daily` I believe and that should work.

**Comment by javiercn** [comment] 2024-08-21 20:57
As for 

> Having said that, the team should heavily consider backporting the fix to the Preview 7 branch and release an updated wasm workload. /cc @terrajobst @danroth27 @SteveSandersonMS

We don't backport things to already released previews, there's a new preview every month and nightly builds are available for faster cadence if needed.

**Comment by robertmclaws** [comment] 2024-08-21 21:15
> You can pass `-Quality daily` I believe and that should work.

No worries! That did it, thanks!

> We don't backport things to already released previews, there's a new preview every month and nightly builds are available for faster cadence if needed.

I understand that is normally what happens. But this issue broke builds for earlier versions of .NET too. Since this broke WASM for anyone with the preview installed, couldn't an updated version of the workload be published? Doesn't seem like it would be that hard.

Now to get this working on Azure DevOps...

**Comment by javiercn** [comment] 2024-08-21 22:10
@robertmclaws when you mentioned that the workload broke stuff, do you mean when you use the preview7 SDK, isn't it? If you pin the SDK with `global.json` things continue to work. Is that not the case? Note that even though the SDK builds current and previous versions, previews are still previews and the support level is the same whether the app targets the preview runtime or an existing runtime.

Unless the workload broke existing apps compiling against older versions with older SDKs, it doesn't change anything, as you can always pin the SDK if you need to.

Getting this working on AzDo shouldn't be too hard. You can run the same script to install it and set the environment variables and you should be good to go.

**Comment by rockfordlhotka** [comment] 2024-08-21 22:17
@javiercn the `global.json` to peg the SDK to 8.0.400 is a workaround for my issue.

If you want to repro the issue, grab this commit:

https://github.com/MarimerLLC/csla/tree/e33c04563556f7fd2b7b707e21ddd40dc14e2acf

Remove the `global.json` and try to build the solution. The `.Client` project fails with the described issue on a machine with 9.0.100-preview.7.24407.12 installed (even though the projects target .NET 8).

**Comment by javiercn** [comment] 2024-08-21 22:43
@rockfordlhotka it works with the nightly.

![image](https://github.com/user-attachments/assets/6bb2afcd-6e4b-4a94-94c2-e5ad9ba3dd30)

```
.NET SDK:
 Version:           9.0.100-rc.2.24420.21
 Commit:            a16db5fadc
 Workload version:  9.0.100-manifests.f1d086e7
 MSBuild version:   17.12.0-preview-24415-04+f422d8d7d
```

**Comment by javiercn** [comment] 2024-08-21 22:46
I'm going to close this as fixed, since I'm pretty sure is the fix @maraf did on the runtime like 3 weeks ago.

**Closed by javiercn** 2024-08-21 22:46 UTC
Labels: area-blazor

**Comment by rockfordlhotka** [comment] 2024-08-22 00:42
I think the big thing is that there's a fix coming.

The urgent thing is that there's the global.json workaround for everyone who needs to be productive on their workstationa until the next v9 preview release.

**Comment by robertmclaws** [comment] 2024-08-25 17:51
To anyone looking to solve these problems in an Azure Pipelines build, here are the steps:

1) Add a Powershell command near the top of your build process, set it to "Inline", and paste in the following code:
```ps
&powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 9.0.1xx -InstallDir $(Agent.ToolsDirectory)/dotnet" -Quality daily

$(Agent.ToolsDirectory)/dotnet/dotnet.exe workload install wasm-tools --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" --include-previews
```

2) Go to your `dotnet restore` command and add the following to "Arguments":
```
-s https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json -s https://api.nuget.org/v3/index.json
```

You'll likely be able to take all this out when RC1 is released. But make sure you verify that it works first when that happens... the current Daily builds are for RC2, which is what will be installed on your build server if you use this script.

HTH!

**Comment by Junjun-zhao** [comment] 2024-08-26 02:42
Hi @javiercn, Yes, we verified it with dotnet-sdk-9.0.100-rc.1.24422.10, this issue has been fixed.

**Comment by BenTheBest69** [comment] 2024-09-09 18:01
> Hi @javiercn, Yes, we verified it with dotnet-sdk-9.0.100-rc.1.24422.10, this issue has been fixed.

I guess this is a stupid question but how can I use this version "24422.10", for what ever reason my VS keep adding a reference to 24405. I only using .Net 8 also and I've trying to resolve this issue for more when one day of work. If I'm not using any preview stuff why this package keep showing up and make my Blazor application fail to compile.

**Comment by rockfordlhotka** [comment] 2024-09-09 18:33
> > Hi @javiercn, Yes, we verified it with dotnet-sdk-9.0.100-rc.1.24422.10, this issue has been fixed.
> 
> I guess this is a stupid question but how can I use this version "24422.10", for what ever reason my VS keep adding a reference to 24405. I only using .Net 8 also and I've trying to resolve this issue for more when one day of work. If I'm not using any preview stuff why this package keep showing up and make my Blazor application fail to compile.

The answer appears to be that you create a `global.json` file in the folder with your .sln file, and use that to specify the version of .NET to use in the build.

I've been adding them all over the place now to specify the use of .NET 8 to avoid the .NET 9 bug.

**Comment by robertmclaws** [comment] 2024-09-09 18:54
If you leave the global.json reference to `9.0.100-rc.2`, you can install any version of the RC2 daily branch necessary.

This will need to change when the dailies move to the RTM branch.

**Comment by BenTheBest69** [comment] 2024-09-09 19:03
> > > Hi @javiercn, Yes, we verified it with dotnet-sdk-9.0.100-rc.1.24422.10, this issue has been fixed.
> > 
> > 
> > I guess this is a stupid question but how can I use this version "24422.10", for what ever reason my VS keep adding a reference to 24405. I only using .Net 8 also and I've trying to resolve this issue for more when one day of work. If I'm not using any preview stuff why this package keep showing up and make my Blazor application fail to compile.
> 
> The answer appears to be that you create a `global.json` file in the folder with your .sln file, and use that to specify the version of .NET to use in the build.
> 
> I've been adding them all over the place now to specify the use of .NET 8 to avoid the .NET 9 bug.

My problem is that my solution contains lots of project that are still using .net6 so the global.json won't work. I really hope this nasty bug will be fixed soon without all those klugs :).

**Comment by robertmclaws** [comment] 2024-09-09 19:06
@BenTheBest69 You can still have .NET 9 RC2 as the global.json and build to .NET 6. You just need to have `<TargetFrameworks>net6.0;</TargetFrameworks>` in the project files.

**Comment by BenTheBest69** [comment] 2024-09-10 11:11
> @BenTheBest69 You can still have .NET 9 RC2 as the global.json and build to .NET 6. You just need to have `<TargetFrameworks>net6.0;</TargetFrameworks>` in the other project files and `<TargetFrameworks>net9.0;</TargetFrameworks>` in the Blazor project.
> 
> For the BEST results, put this in the other projects: `<TargetFrameworks>net9.0;net6.0;</TargetFrameworks>`

Thanks @robertmclaws for this information, very useful. One more thing to add, when I build my Blazor project with VS Preview, I'm getting this DefineStaticWebAssetEndpoints exception, which I don't with the normal and latest version of VS. That make things harder to understand I think.
