### ISSUE TITLE
Completing the @... completion item in VS results in a yellow bar

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21258] opened 2020-04-27 20:06 UTC
Looks like the second you commit the `@...` completion item in VS everything falls over and things start getting wacky. My bet is that this is due to us returning a VSCode based completion item command to re-trigger completion.

Repro:
1. Open a Blazor app
1. Type `<input |` where your cursor is at the pipe (|)
1. Hit "Enter" on the `@...` completion item

**Comment by TanayParikh** [comment] 2020-04-27 20:44
This is possibly related to https://github.com/dotnet/aspnetcore/issues/21066

where I'm seeing:

```csharp
((Microsoft.AspNetCore.Razor.Language.TagHelperDocumentContext.DefaultTagHelperDocumentContext)(new System.Collections.Generic.Mscorlib_DictionaryDebugView<object, object>(((Microsoft.AspNetCore.Razor.Language.DefaultRazorCodeDocument)codeDocument).Items._inner).Items[6]).Value).TagHelpers {Microsoft.AspNetCore.Razor.Language.TagHelperDescriptor[0]}
```

aka, the code document doesn't have any tag helper descriptors and the `RazorCompletionEndpoint` isn't returning any values (only values are from the `CompletionHandler` for HTML based completions).

**Comment by TanayParikh** [comment] 2020-04-30 17:54
Just marking this as blocked on https://github.com/dotnet/aspnetcore/issues/21258 as they may share the same root cause.

**Comment by TanayParikh** [comment] 2020-05-05 18:15
Can't repro this. @NTaylorMullen are you still seeing this?

**Comment by NTaylorMullen** [comment] 2020-05-05 19:50
Nope!!

**Comment by TanayParikh** [comment] 2020-05-05 20:26
Great, thanks for checking! Closing out as no repro. Probably got fixed by a prior PR.

**Closed by TanayParikh** 2020-05-05 20:26 UTC
Labels: area-razor.tooling, bug, cost: S
