### ISSUE TITLE
HTTP/3: CompleteAsync and Reset/Abort race

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34915] opened 2021-08-01 02:31 UTC
When `CompleteAsync` and `Reset`/`Abort` are used together with HTTP/3 there will always be a race between them.

* CompleteAsync completes the request and sends the completed response on the QUIC stream.
* Reset aborts the stream which sends a QUIC RESET_STREAM instruction to the client. This tells the client to abort and ignore all request content.

```cs
async context =>
{
    await context.Response.CompleteAsync();

    context.Features.Get<IHttpResetFeature>().Reset(256); // or context.Abort()
});
```

Because QUIC doesn't guarantee operations are received in order, these can be reported out of order in the client. i.e. the client reading from the QUIC stream gets the notification of abort before reading the completed response. Instead of the client returning a completed HTTP response, an abort error is thrown.

This is different from HTTP/2 when CompleteAsync and Reset are used together. The client always reads the completed response frames, returns the HTTP response to user code, then reads the RST_STREAM frame.

Possible solution: If `CompleteAsync` has been called on the server then `Reset`/`Abort` aborts reading the QUIC stream only. Writing is not aborted. Writing the response is allowed to complete gracefully.

@halter73 @Tratcher

**Comment by Tratcher** [comment] 2021-08-02 23:11
Discussion notes: Since HTTP/2 and HTTP/3 use different error code values, the caller will likely need to check the protocol first anyways. In that case they can call the new IStreamAbortFeature.AbortRead API for HTTP/3.

**Comment by adityamandaleeka** [comment] 2021-09-30 22:34
Closing this as expected behavior.

**Closed by adityamandaleeka** 2021-09-30 22:34 UTC
Labels: area-runtime, HTTP3
