### ISSUE TITLE
href anchor in Blazor page with @page "/somepage" resolves to "/"

### ISSUE THREAD

**Issue by ionelanton** [dotnet/aspnetcore#16726] opened 2019-11-01 01:59 UTC
Hello,
I have the following Blazor page:

> `@page "/somepage"`
> `<a href="#">`Link`</a>`
> `@code {
> }`

When I go to https://server/somepage I expect to see the following link for the anchor: https://server/somepage/# but instead I see: https://server/#

Is this the expected behavior?

Thank you!

**Comment by javiercn** [comment] 2019-11-01 08:19
@ionelanton thanks for contacting us.

We'll look into it and get back to you.

**Comment by javiercn** [comment] 2019-11-01 11:04
This is a bug I believe. In HTML it only appends the `#` sign to the current route, in blazor it strips the current path (and likely the query too).

See attached for a repro:
* Visit /Page.html and click the link
* Visit /counter and click the link

[hashtaglink.zip](https://github.com/aspnet/AspNetCore/files/3797602/hashtaglink.zip)

**Comment by kevingates** [comment] 2019-11-12 18:10
@javiercn ,

I've noticed similar behavior.

Also, I'm using anchor tags for onsite navigation (think FAQ,). I want to jump down to a section and back up. And one of them works and the other doesn't

Something like this:
```
<h3 id='standard'>Standard Disbursements</h3>
<a href='disbursements#aggregate'>Jump to Aggregate</a>
...// CODE

<h3 id='aggregate'>Aggregate Disbursements</h3>
<a href='disbursements#standard'>Jump to Standard</a>
```

Essentially the bottom link works, but the top doesn't. For context, the bottom one is conditionally loaded (if aggregate disbursements are present.)

However, HTML should work to find something with the ID and just jump to that location. But currently I think Blazor is intercepting this behavior.

**Comment by kevingates** [comment] 2019-11-12 18:11
And for context, I should be able to just get away with `<a href="#standard">link text</a>

**Comment by kevingates** [comment] 2019-11-19 21:55
Any updates on my scenario also? Should I make a new issue?
@javiercn

**Comment by mkArtakMSFT** [comment] 2020-10-09 18:24
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.
This is controlled by how HTML resolves links against your page's `base href`.

**Closed by mkArtakMSFT** 2020-10-09 18:24 UTC
Labels: affected-few, area-blazor, bug, feature-routing, severity-blocking

**Comment by kevingates** [comment] 2020-10-09 19:10
@mkArtakMSFT si the design is to go against the normal HTML behavior?

What is the proposed solution for on page navigation like a frequently asked question page? 

JSInterop?

**Comment by ionelanton** [comment] 2020-10-10 02:31
Hi @mkArtakMSFT 
Your design decision conflicts with the **HTML 4.01 Specification** because you cannot create anymore destination anchors in the same document. Please see the section **12.1.1 Visiting a linked resource** https://www.w3.org/TR/2018/SPSD-html401-20180327/struct/links.html#h-12.1
