### ISSUE TITLE
Razor Component: 2 comments in a row, crashes VS2019

### ISSUE THREAD

**Issue by mythrz** [dotnet/aspnetcore#15160] opened 2019-10-18 17:33 UTC
### ctrl+e+c: two comments next to each other, crashes
when the @ tags from comments are next to each other, it crashes.
If the @ tags have a space between them, nothing happens.
Using VS Community 16.3.1. 1 Blazor Project, 1 RCL.

### To Reproduce
1. Open a Blazor Razor Component (mine was in a RCL)
2. Choose a portion of code/markup that is not inside @ code
3. Comment the word with two comments "oneWord": @*one*@@*Word*@ 
4. The issue in my machine is in red:
![image](https://user-images.githubusercontent.com/44119535/67114844-b5fb0b00-f1d4-11e9-8b69-c3730e94f5b2.png)

### Expected behavior
It shouldn't crash.

### Additional context
If you try to open the file again with VS2019, it crashes again. It can't recover.
To any one that happens, use the notepad to edit, for example add a space between the two comments, it no longer crashes. @*one*@ @*Word*@

**Comment by NTaylorMullen** [comment] 2019-10-18 17:46
I can reproduce. Marking appropriately.

**Comment by allisonchou** [comment] 2021-10-05 05:48
This seems to be fixed in the new Razor editor (VS 2022). Closing out for now, please let us know if the issue persists.

**Closed by allisonchou** 2021-10-05 05:48 UTC
Labels: bug, area-blazor, Tooling, severity-nice-to-have, affected-very-few, area-razor.compiler
