### ISSUE TITLE
service-worker-assets wrong content when using StaticWebAssetBasePath in hosted scenario

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#44678] opened 2022-10-21 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

service-worker-assets.js will contain this path if StaticWebAssetBasePath is set to UI:
```
  "assets": [
    {
      "hash": "sha256-Of3Y0on4uxJvMPl\/1J8MSn\/zMHf\/6VJ68goCBo79G6c=",
      "url": "UI\/css\/app.css"
    },
```
Using `<meta base="/UI/">` in the hosted file will cause new Request(url) (as used in the default service-worker.published.js) to be interpreted as 'https://site/UI/UI/app.css".
IE, the StaticWebAssetBasePath appears TWICE instead of ONCE!

Similar thing occurs for _content:
```
    {
      "hash": "sha256-+awgd91Xi0rWDvl6oNimnl2gP0wKZb6hlwYZRDC22C8=",
      "url": "UI\/_content\/BrowserInterop\/scripts.js"
    },
```
IE, the StaticWebAssetBasePath appears TWICE instead of **ZERO**!

https://github.com/dotnet/aspnetcore/issues/38690 might be related.

### Expected Behavior

Proper paths

### Steps To Reproduce

follow https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-6.0

### Exceptions (if any)

no

### .NET Version

7rc2

**Comment by mkArtakMSFT** [comment] 2022-11-01 17:04
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/38690

**Closed by mkArtakMSFT** 2022-11-01 17:04 UTC
Labels: bug, area-blazor, blazor-wasm, feature-static-web-assets, feature-pwa
