### ISSUE TITLE
Add item template for a Razor component with code-behind file

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/aspnetcore#21566] opened 2020-05-07 08:30 UTC
Add item template for a Razor component with code-behind file.

It would save developer some time not having to create a separate class file each time.

**Comment by SIkebe** [comment] 2020-05-07 08:41
Discussed in #9924 and #5463 ?

**Comment by robertsundstrom** [comment] 2020-05-08 07:50
@SIkebe This is not quite the same thing as it is an enhancement.

**Comment by javiercn** [comment] 2020-05-08 10:42
@robertsundstrom thanks for contacting us.

Closing as a dupe of #21566 since that's what we are using to track this issue.

**Closed by javiercn** 2020-05-08 10:42 UTC
Labels: area-blazor
