### ISSUE TITLE
.NET 8 Preview 7 - Possible form handling regression Blazor SSR 

### ISSUE THREAD

**Issue by dannykay1710** [dotnet/aspnetcore#49965] opened 2023-08-09 19:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Prior to .NET 8 preview 7, I had a form on a Server render mode, which contained a basic HTML form using the POST method.

The post was to a controller. This controller generated a stripe session and then redirected using a 302 redirect to the Stripe payment page.

This worded on preview 6, on updated to preview 7 I now see a CORS error 

![image](https://github.com/dotnet/aspnetcore/assets/1044153/29c1fb5c-166e-45c0-a839-35be5b42388a)

It appears that forms now get "upgraded" and instead of posting to an endpoint and being successfully redirected to the correct endpoint with a GET request some form of XHR request is being made instead.

### Expected Behavior

The form should issue a POST request, the page should do a full page load and redirect to the stripe checkout page as previous.

### Steps To Reproduce

A simple reproduction can be made as follows. On the razor component set to  `@attribute [RenderModeServer]`

```
<form class="flex flex-col gap-3 place-items-center" method="post" action="/checkout/placeorder">
    <input id="RequestVerificationToken" type="hidden" value="@_forgeryToken" />
    <button class="w-full bg-compliance-yellow hover:bg-compliance-yellow/80 rounded-md px-3.5 py-1.5 text-base font-semibold leading-7 text-zinc-900 shadow-sm" type="submit">Checkout</button>
    <PoweredByStripe></PoweredByStripe>
</form>
```

The checkout controller is as follows:

```
[Authorize]
public class CheckoutController : Controller
{
    private readonly IOrderPlacementService _orderPlacementService;

    public CheckoutController(IOrderPlacementService orderPlacementService)
    {
        _orderPlacementService = orderPlacementService;
    }

    [HttpPost]
    //[ValidateAntiForgeryToken]
    public async Task<ActionResult> PlaceOrder()
    {
        var order = await _orderPlacementService.CreateOrderFromCart();

        if (order == null)
            return LocalRedirect("checkout/error");

        var options = new SessionCreateOptions
        {
            LineItems = new List<SessionLineItemOptions>(),
            CustomerEmail = User.Identity?.Name,
            Mode = "payment",
            SuccessUrl = Url.ActionLink("Success", "Checkout", new { area = "" }) + "/{CHECKOUT_SESSION_ID}",
            CancelUrl = Url.ActionLink("Cancelled", "Checkout", new { area = "" }) + "/{CHECKOUT_SESSION_ID}",
            AutomaticTax = new SessionAutomaticTaxOptions { Enabled = false },
            Metadata = new Dictionary<string, string>
            {
                { "OrderId", order.Id.ToString() }
            }
        };

        foreach (var item in order.OrderItems)
        {
            options.LineItems.Add(new SessionLineItemOptions
            {
                PriceData = new SessionLineItemPriceDataOptions
                {
                    Currency = "GBP",
                    ProductData = new SessionLineItemPriceDataProductDataOptions
                    {
                        Name = item.Product.Name,
                        Description = item.Product.Description
                    },
                    UnitAmount = (long)item.Product.Price * 100
                },
                Quantity = item.Quantity,
            });
        }

        var service = new SessionService();
        Session session = service.Create(options);

        Response.Headers.Append("Location", session.Url);
        return new StatusCodeResult(302);
    }
}
```

### Exceptions (if any)

No server side exceptions, the following is shown in the browser console window

![image](https://github.com/dotnet/aspnetcore/assets/1044153/29c1fb5c-166e-45c0-a839-35be5b42388a)

### .NET Version

8.0.100-preview.7.23376.3

### Anything else?

Visual Studio Version 17.8.0 Preview 1.0

```
.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mkArtakMSFT** [comment] 2023-08-29 16:48
Thanks for contacting us.
@javiercn can you please look into this one? Thanks!

**Comment by javiercn** [comment] 2023-09-06 10:29
Dupe of https://github.com/dotnet/aspnetcore/issues/50384

**Closed by javiercn** 2023-09-06 10:29 UTC
Labels: area-blazor, feature-cors
