### ISSUE TITLE
Blazor-server app uses a fallback authorization strategy, In the Login.razor file, I used the @Attribute [AllowAnonymous] attribute, but I still can't interact with it. I can't enter my email or password, and the login button doesn't respond.Is there something wrong with it?

### ISSUE THREAD

**Issue by zuijiaoghb** [dotnet/aspnetcore#58505] opened 2024-10-18 08:06 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

[root@cpzljc jtpjsapp]# cat Program.cs
```csharp
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.FluentUI.AspNetCore.Components;
using jtpjsapp.Components;
using jtpjsapp.Components.Account;
using jtpjsapp.Data;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using jtpjsapp.Authorization;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorComponents()
.AddInteractiveServerComponents();
builder.Services.AddFluentUIComponents();
builder.Services.AddDataGridEntityFrameworkAdapter();

builder.Services.AddCascadingAuthenticationState();
builder.Services.AddScoped();
builder.Services.AddScoped();
builder.Services.AddScoped<AuthenticationStateProvider, IdentityRevalidatingAuthenticationStateProvider>();

builder.Services.AddAuthentication(options =>
{
options.DefaultScheme = IdentityConstants.ApplicationScheme;
options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
})
.AddIdentityCookies();

//var connectionString = builder.Configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
//builder.Services.AddDbContext(options =>
// options.UseSqlite(connectionString));
builder.Services.AddDbContextFactory(opt =>
opt.UseMySql("server=;port=;database=;user=;password=" , new MySqlServerVersion(new Version(8, 0, 31)) )
// The following three options help with debugging, but should
// be changed or removed for production.
.LogTo(Console.WriteLine, LogLevel.Information)
.EnableSensitiveDataLogging()
.EnableDetailedErrors() );
builder.Services.AddDatabaseDeveloperPageExceptionFilter();

builder.Services.AddIdentityCore(options => options.SignIn.RequireConfirmedAccount = true)
.AddRoles()
.AddEntityFrameworkStores()
.AddSignInManager()
.AddDefaultTokenProviders();

builder.Services.AddRazorPages();

builder.Services.AddAuthorization(options =>
{
options.FallbackPolicy = new AuthorizationPolicyBuilder()
.RequireAuthenticatedUser()
.Build();
});

builder.Services.AddSingleton<IEmailSender, IdentityNoOpEmailSender>();

// Authorization handlers.
builder.Services.AddScoped<IAuthorizationHandler,
RecbillIsOwnerAuthorizationHandler>();

builder.Services.AddSingleton<IAuthorizationHandler,
RecbillAdministratorsAuthorizationHandler>();

builder.Services.AddSingleton<IAuthorizationHandler,
RecbillManagerAuthorizationHandler>();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
var services = scope.ServiceProvider;
var context = services.GetRequiredService();
context.Database.Migrate();
// requires using Microsoft.Extensions.Configuration;
// Set password with the Secret Manager tool.
// dotnet user-secrets set SeedUserPW

var testUserPw = builder.Configuration.GetValue<string>("SeedUserPW");
await SeedData.Initialize(services, testUserPw);
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
app.UseMigrationsEndPoint();
}
else
{
app.UseExceptionHandler("/Error", createScopeForErrors: true);
// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
app.UseHsts();
}

app.UseHttpsRedirection();

//app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.UseStaticFiles();
app.UseAntiforgery();

app.MapRazorComponents()
.AddInteractiveServerRenderMode();

// Add additional endpoints required by the Identity /Account Razor components.
app.MapAdditionalIdentityEndpoints();

app.Run();
```

[root@cpzljc Pages]# cat Login.razor
```razor
@page "/Account/Login"
@Attribute [AllowAnonymous]

@using System.ComponentModel.DataAnnotations
@using Microsoft.AspNetCore.Authentication
@using Microsoft.AspNetCore.Identity
@using jtpjsapp.Data

@Inject SignInManager SignInManager
@Inject ILogger Logger
@Inject NavigationManager NavigationManager
@Inject IdentityRedirectManager RedirectManager

登录

登录
使用注册后的邮箱登录。
登录
忘记了你的密码?

{ ["ReturnUrl"] = ReturnUrl }))">注册新用户

再次发送邮箱确认

@*
Use another service to log in.
*@
https://github.com/code {
private string? errorMessage;

[CascadingParameter]
private HttpContext HttpContext { get; set; } = default!;

[SupplyParameterFromForm]
private InputModel Input { get; set; } = new();

[SupplyParameterFromQuery]
private string? ReturnUrl { get; set; }

protected override async Task OnInitializedAsync()
{
    if (HttpMethods.IsGet(HttpContext.Request.Method))
    {
        // Clear the existing external cookie to ensure a clean login process
        await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
    }
}

public async Task LoginUser()
{
    // This doesn't count login failures towards account lockout
    // To enable password failures to trigger account lockout, set lockoutOnFailure: true        
    var result = await SignInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
    if (result.Succeeded)
    {
        Logger.LogInformation("User logged in.");
        //RedirectManager.RedirectTo(ReturnUrl);
        RedirectManager.RedirectTo("home");
    }
    else if (result.RequiresTwoFactor)
    {
        RedirectManager.RedirectTo(
            "Account/LoginWith2fa",
            new() { ["returnUrl"] = ReturnUrl, ["rememberMe"] = Input.RememberMe });
    }
    else if (result.IsLockedOut)
    {
        Logger.LogWarning("User account locked out.");
        RedirectManager.RedirectTo("Account/Lockout");
    }
    else
    {
        errorMessage = "错误：无效的登录尝试。";
    }
}

private sealed class InputModel
{
    [Required]
    [EmailAddress]
    public string Email { get; set; } = "";

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; } = "";

    [Display(Name = "Remember me?")]
    public bool RememberMe { get; set; }
}
}
```

run:
![Image](https://github.com/user-attachments/assets/e9ce96d8-6d1a-473c-b3da-494c953e29d1)

### Expected Behavior

![Image](https://github.com/user-attachments/assets/c1f464e4-d030-4f18-ad8f-2a3a6accf216)

### Exceptions (if any)

no

### .NET Version

NET 8.0.301

### Anything else?

OS & Device: centos8 on PC
Browser [Microsoft Edge]
.NET 8.0.301 and Fluent UI Blazor library Version 4.10.2

**Comment by zuijiaoghb** [comment] 2024-10-22 01:26
> Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimal repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem without unnecessary code. Please share with us in a public GitHub repo because we cannot open ZIP attachments, and don't include any confidential content.

public GitHub repo: https://github.com/zuijiaoghb/jtpjsapp.git

**Comment by halter73** [comment] 2024-12-20 02:33
Normally we'd need a more minimal repro. I don't want to have to spin up a MySQL instance, and uncommenting the SQLite bit didn't help since the Migrations are incompatible. However, it was enough to see what's probably going on despite not being able to run it.

The problem with using `[AllowAnonymous]` on an interactive Blazor page when you supply a non-anonymous fallback policy is that the fallback policy still applies `/_framework/blazor.web.js` endpoint, just not the page itself. There are workarounds that apply `[AllowAnonymous]` to `blazor.web.js` too, but I think the more convenient solution in most cases is to put the `[Authorize]` attribute in your root `_Imports.razor` file. 

I see that you've already commented out your `options.FallbackPolicy =` logic and instead put the `[Authorize]` attribute on each Blazor page that needs it. This is right solution. Putting the `[Authorize]` in your root `_Imports.razor` instead will probably save you some lines of code. This is similar to what is already being done in the `Account/Pages/Manage/_Imports.razor`. `[AllowAnonymous]` on your login page will still override it like it would a fallback policy, but unlike a fallback policy `[Authorize]` in an `_Imports.razor` file will not applies to `blazor.web.js`.

I think this is a duplicate of #51836.

**Closed by halter73** 2024-12-20 02:33 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, investigate, area-identity, Status: Resolved
