### ISSUE TITLE
Blazor wasm apps always running in production mode

### ISSUE THREAD

**Issue by user72356** [dotnet/aspnetcore#37079] opened 2021-09-29 04:09 UTC
When debugging a Blazor wasm app in .Net 6.0 RC1, using F5 from Visual Studio 2022 Preview, the Kestrel window indicates that the hosting env is production. This is despite using the default template for wasm projects, which sets the ASPNETCORE_ENVIRONMENT variable to Development.

Under similar conditions, Blazor server apps do not display any message about the hosting env being production or development, so I'm assuming it's in dev mode?

**Comment by Xyncgas** [comment] 2021-09-30 10:49
#if DEBUG
Console.WriteLine("I am debugging");
#endif

**Comment by user72356** [comment] 2021-09-30 11:00
> #if DEBUG Console.WriteLine("I am debugging"); #endif

What I'm saying is that the app runs in production mode when in fact it should be running in development mode according to the Kestrel settings. This has implications, for example hot reload is disabled in production mode.

**Comment by mkArtakMSFT** [comment] 2021-09-30 16:57
Thanks for contacting us. We think this is a dupe of #25152

**Closed by mkArtakMSFT** 2021-09-30 16:57 UTC
Labels: area-blazor, blazor-wasm
