### ISSUE TITLE
Firefox temporarily shows reconnect dialog while navigating to new page

### ISSUE THREAD

**Issue by Bouke** [dotnet/aspnetcore#40425] opened 2022-02-26 10:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following issue appears when using Blazor inside an MVC application. It uses the [Render Blazor components from JavaScript](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#render-blazor-components-from-javascript) feature of .NET 6 to render Blazor components in MVC pages.

On Firefox the reconnect dialog temporarily appears while navigating to a new slow page and it disappears while the browser is still waiting on a response from the server. For example on a page that takes 3 seconds to render on the server side:

- Browser starts loading new page
- Reconnect dialog appears immediately
- After ~1 second the reconnect dialog disappears
- After ~3 seconds the new page appears

This is very confusing for the user, as the reconnect dialog makes no sense in the context of the page navigation: once the reconnect dialog appears the browser is still waiting for the new page.

### Expected Behavior

When navigating to a new page the reconnect modal dialog should not appear.

I _think_ the issue is with Firefox closing the websocket as soon as the browser starts the navigation. Blazor is still running on the current page and tries to reconnect. Then when the new page is loaded that connection is then dropped again. I believe the following log displays this:

```
XXXXXXXXXXXXXXXXX: Click link
11:29:45.929 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[108] Circuit id 'bYOUsdQV_5O78gYqsntQmxrRp8HtZfHbU6NFApbO_2w' disconnected from connection 'OEcFMozmbcaOhfh5U6t58w'.
11:29:45.945 info: Start request
11:29:48.972 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[107] Circuit id 'bYOUsdQV_5O78gYqsntQmxrRp8HtZfHbU6NFApbO_2w' connected using connection 'TvhQqWmFNYn0uPORbQKtUA'.
11:29:49.469 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[108] Circuit id 'bYOUsdQV_5O78gYqsntQmxrRp8HtZfHbU6NFApbO_2w' disconnected from connection 'TvhQqWmFNYn0uPORbQKtUA'.
11:29:49.474 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[103] Disposing circuit 'bYOUsdQV_5O78gYqsntQmxrRp8HtZfHbU6NFApbO_2w' started.
11:29:49.474 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[108] Circuit id 'bYOUsdQV_5O78gYqsntQmxrRp8HtZfHbU6NFApbO_2w' disconnected from connection 'TvhQqWmFNYn0uPORbQKtUA'.
11:29:49.474 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[109] Closing circuit with id 'bYOUsdQV_5O78gYqsntQmxrRp8HtZfHbU6NFApbO_2w'.
11:29:49.474 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[104] Disposing circuit 'bYOUsdQV_5O78gYqsntQmxrRp8HtZfHbU6NFApbO_2w' succeeded.
11:29:49.959 info: Finished response
11:29:50.047 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[100] Circuit initialization started.
11:29:50.047 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[106] Opening circuit with id '0tqOOyUw-MftrgH1PdbuHpqXV5VAeSoMo_v1AEiIrRo'.
11:29:50.047 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[107] Circuit id '0tqOOyUw-MftrgH1PdbuHpqXV5VAeSoMo_v1AEiIrRo' connected using connection 'WoXi8VQyGQ8okVbMP_U_bA'.
11:29:50.047 dbug: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[101] Circuit initialization succeeded.
```

### .NET Version

6.0.2

### Anything else?

I've worked around this by introducing a custom reconnect modal dialog that appears only after 5 seconds, but this is not an ideal situation.

**Comment by mkArtakMSFT** [comment] 2022-02-28 17:38
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/28592.
Please upvote the linked issue and provide additional comments about your scenario there if you need.

**Closed by mkArtakMSFT** 2022-02-28 17:38 UTC
Labels: area-blazor, blazor-server
