### ISSUE TITLE
Feature: Should identify Blazor component attributes that lack a matching property in the code block/code-behind at design-time

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/aspnetcore#34125] opened 2021-07-06 18:51 UTC
### Is your feature request related to a problem? Please describe.
At runtime, if there exists a non-standard attribute that would typically require a [Parameter] be defined in the component code, it will throw an InvalidOperationException indicating "Object of type 'X' does not have a property matching the name 'Y'".

According to my stack trace, this comes from `Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForUnknownIncomingParameterName(Type targetType, string parameterName)`

To prevent such exceptions, there should be an analyzer of sorts that can look at each component and verify that for each of the attributes, they're either expected (e.g. 'href' in the case of a NavLink) or defined in the code block/code-behind of the component and a warning should be shown if that's not the case. Additionally, perhaps consider adding a red squiggly to the text editor on the attribute name that doesn't have a matching property in the code-behind to draw attention pre-build.

### A clear and concise description of what the problem is.
Let's say I'm developing a component and I'd like to have the parent pass in a boolean value. I'll set up a parameter in the code-behind with:

```
[Parameter]
public bool MyVar { get; set; }
```

...and I need only pass in the expected value into the component attribute:

`
<MyComponent MyVar="@(true)"/>
`

But what if I later decide I no longer need the property in my component. I'll remove the boolean parameter from the code and its various references and I won't see any red squigglies indicating an issue. The coloring of the MyVar attribute on the MyComponent element will change slightly, but won't otherwise indicate any issue until runtime when we'll find out there's no matching property for it.

### Describe the solution you'd like
I'd ideally like to see two things:
1) Given this throws an exception at runtime, a red squiggly should be placed under the mismatched attribute on the component at design time when it doesn't match to a value in the code-behind/code block.

2) A warning (maybe an error) should be written to the build output indicating that this will introduce a runtime exception because of the lack of a matching property for the named attribute.

### Additional context
N/A

**Comment by NTaylorMullen** [comment] 2021-07-12 22:09
@mkArtakMSFT this would be a compiler issue where the expectation is you'd have a warning on an attribute if it was Pascal cased. Much like you do today for elements:
![image](https://user-images.githubusercontent.com/2008729/125362067-2049cc80-e323-11eb-88c6-1698d41b0ade.png)

**Comment by mkArtakMSFT** [comment] 2021-07-13 16:43
Thanks for contacting us. This is a dupe of #19791

**Closed by mkArtakMSFT** 2021-07-13 16:43 UTC
Labels: area-razor.compiler
