### ISSUE TITLE
How to inject some object in startup class

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/aspnetcore#20968] opened 2020-04-17 10:53 UTC
I have instance of a class which i wanted to inject in some singleton class at the time of startup.
How can i do that in .net core 3.1

**Comment by Tratcher** [comment] 2020-04-17 20:48
Duplicate of https://github.com/dotnet/aspnetcore/issues/9337.

**Closed by Tratcher** 2020-04-17 20:48 UTC
