### ISSUE TITLE
Response is 406 Not Acceptable instead of 404

### ISSUE THREAD

**Issue by andrey-rodin** [dotnet/aspnetcore#19093] opened 2020-02-17 09:45 UTC
The following action produces 406 response when Accept header is "text/plain". For "application/json" response is 404. I expected 404 in both cases, because if action returns Ok("some string") and Accept header is "text/plain", then result is correct. I do not use output formatters in startup.

[Route("foo")]
[HttpGet]
[Produces("text/plain", "application/json")]
public IActionResult GetString()
{
    return NotFound();
}

**Comment by mkArtakMSFT** [comment] 2020-02-18 17:50
Thanks for contacting us.
This is by-design. @pranavkm can you please share more details about why as well as let's get this documented.

Thanks!

**Comment by pranavkm** [comment] 2020-02-18 23:36
@andrey-rodin, could you share a minimal app that reproduces this issue? I would have expected a 406 in either case, if you haven't changed the default set of formatters.

**Comment by andrey-rodin** [comment] 2020-02-19 06:34
Hi @pranavkm,
It's a bit difficult to share all app, but you can try this on service created from scratch. My service has  call `AddNewtonsoftJson(...)` in startup.

Correct response should be 404.
As I mentioned, this action produces valid "text/plain" response:
`
[HttpGet]
public IActionResult GetString()
{
    return Ok("some string");
}
`

**Comment by pranavkm** [comment] 2020-02-24 17:27
@andrey-rodin I don't see this happening, not in a minimal app.

**Comment by andrey-rodin** [comment] 2020-03-02 13:39
Hmm... Then I should investigate why at all my app returns text/plain when action returns string. In all other cases response is application/json, of course

**Comment by andrey-rodin** [comment] 2020-03-03 09:32
My mistake. Response is 406 when Accept header is application/json. I expected 404 in all cases.
`
[HttpGet]
[Produces("text/plain")]
public IActionResult Foo()
{
    return NotFound();
}
`

**Comment by pranavkm** [comment] 2020-03-06 19:25
The 406 makes sense, since content negotiation failed. Closing this since it's by-design.

**Closed by pranavkm** 2020-03-06 19:25 UTC
Labels: Needs: Attention :wave:, area-mvc
