### ISSUE TITLE
Force Blazor WebAssembly Msal auth to redirect instead of popup

### ISSUE THREAD

**Issue by pheuter** [dotnet/aspnetcore#23621] opened 2020-07-02 17:27 UTC
### Describe the bug
MSAL.js [docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript) state that it is possible to sign users in using a popup window or a redirect. Blazor WebAssembly [Standalone Auth](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1) appears to use MSAL.js under the hood, and the default functionality is to attempt a popup window first, and if that fails fallback to a redirect. I would like to force the app to always redirect for auth, but not clear how to do that.

### To Reproduce

1. Start a new Blazor WebAssembly Standalone Auth project:
```
> dotnet new blazorwasm -au IndividualB2C --aad-b2c-instance "{AAD B2C INSTANCE}" --client-id "{CLIENT ID}" --domain "{TENANT DOMAIN}" -ssp "{SIGN UP OR SIGN IN POLICY}"
```

2. Navigate to `authentication/login` via a button click, which will trigger a popup window.

### Further technical details
`dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment] 2020-07-03 14:03
@pheuter thanks for contacting us.

This issue is a duplicate of https://github.com/dotnet/aspnetcore/issues/20374 so closing this one to track the request in the existing issue.

**Closed by javiercn** 2020-07-03 14:03 UTC
Labels: area-blazor, blazor-wasm
