### ISSUE TITLE
HttpLogging middleware should have an option to filter out endpoints

### ISSUE THREAD

**Issue by grzegorz-wittchen** [dotnet/aspnetcore#40950] opened 2022-03-30 08:16 UTC
I would suggest to implement a feature to filter requests for given endpoints which should be logged using that middleware. 
F.e. right now as I wanted to log only data related to my API endpoints it's not possible. Enabling this middleware will log also all requests like for static files etc. creating a mess in my log.

**Comment by Tratcher** [comment] 2022-03-30 20:36
For static files at least, you can address that by changing the order of your middleware so logging comes after static files.

One way to go about this would be to put opt-in or opt-out attributes on specific endpoints.  Another way (that we generally avoid) is having a callback, but people tend to re-invent routing in such callbacks.

**Comment by akhmolina** [comment] 2022-08-11 14:31
This feature will be useful for filter out healthchecks calls with 200 status code in kubernetes

**Comment by Tratcher** [comment] 2022-09-09 21:18
Making the middleware endpoint aware could address this. https://github.com/dotnet/aspnetcore/issues/43222

**Comment by stefer** [comment] 2022-11-18 16:12
It is possible to use UseWhen to selectively add http logging to only some endpoints, like so:
```
            app.UseWhen(
                context => context.Request.Path.StartsWithSegments("/api"),
                builder => builder.UseHttpLogging());
```

**Comment by Tratcher** [comment] 2023-02-24 21:29
I'm going to close this as a duplicate of two more specific proposals:
- https://github.com/dotnet/aspnetcore/issues/43222
- https://github.com/dotnet/aspnetcore/issues/39200

**Closed by Tratcher** 2023-02-24 21:29 UTC
Labels: Needs: Design, area-runtime
