### ISSUE TITLE
I really want a best and official .NET PDF library from dotnet team.

### ISSUE THREAD

**Issue by DEVBOX10** [dotnet/aspnetcore#53190] opened 2024-01-06 09:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Yes there are a bunch of .NET PDF libraries.
But it is not a free and not a streamlined approaches of APIs from other vendors for modern .NET developers and for many scenarios.

The Office documents are not a third-party solution, that's why I really want dotnet team offer official .NET PDF library.
I really hope to see the official .NET PDF library to be real as part of dotnet 9.0 releases from dotnet team.
It may looking good CommunityToolkit style of PDF library like out of box from dotnet itself.

### Describe the solution you'd like

Wish features: (CommunityToolkit style of PDF library)
- Convert the Office documents to PDF file, .doc, docx, .ppt, .pptx, .xls, xlsx, .one and more
- Merge pages and modify, append and more
- Implemented by fluent style of APIs, many modern dotnet style

**Comment by martincostello** [comment] 2024-01-06 09:38
This issue looks like it should be transferred to dotnet/runtime.

**Comment by martincostello** [comment] 2024-01-07 11:15
Dupe of https://github.com/dotnet/runtime/issues/96576.

**Closed** 2024-01-07 11:15 UTC
Labels: area-mvc
