### ISSUE TITLE
JWT Authentications always fail after upgrading from .NET to .NET 6

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#33811] opened 2021-06-24 17:51 UTC
www-authenticate: Bearer error="invalid_token"  401

Every Api method protected by [Auhtorize] is failing after i upgraded to .NET 6 from .NET 5.
I am using Blazor wasm hosted App.

Is there anything that i need to do additional when migrating ?

**Comment by Tratcher** [comment] 2021-06-24 17:59
Possible duplicate of https://github.com/dotnet/aspnetcore/issues/33634.

Enable application logging for details.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

**Comment by nssidhu** [comment] 2021-06-26 00:31
I just verified that if I remove [Authorize] attribute it works fine.
So this is something related to Upgrade.

**Comment by javiercn** [comment] 2021-06-28 15:53
@nssidhu thanks for contacting us.

We haven't changed anything significant in that area.

**Closed** 2021-07-05 17:00 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, area-blazor, blazor-wasm, feature-blazor-wasm-auth
