### ISSUE TITLE
API project or Api: DataAnnotation model bind failures to use JsonPropertyName name if provided

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/aspnetcore#31164] opened 2021-03-23 21:01 UTC
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by javiercn** [comment] 2021-03-24 16:51
Dupe of https://github.com/dotnet/aspnetcore/issues/31166

**Closed by javiercn** 2021-03-24 16:51 UTC
Labels: area-mvc
