### ISSUE TITLE
SignalR exception in OnDisconnectedAsync(Exception exception) is always null.

### ISSUE THREAD

**Issue by srzsantiago** [dotnet/aspnetcore#27545] opened 2020-11-05 11:03 UTC
### Describe the bug
As it has already been mentioned in #21796. The exception you get in the onDisconnectedAsync is always null. I noticed that this seems to be already fixed in #24408, but I still keep getting the same result. Exception is always null.

### To Reproduce

     public override async Task OnDisconnectedAsync(Exception exception)
           {
                 var httpContext = Context.GetHttpContext();

            var user = users.SingleOrDefault(u => u.ConnectionId == Context.ConnectionId);

            if(user != null)
            {
                //do something if user is founded and the exception is a deliberately disconnection.
            }

            await base.OnDisconnectedAsync(exception);
        }

### Exceptions (if any)

Exception saying something about the way the the client was disconnected. 

### Further technical details
- ASP.NET Core version: Netcore 2.0
- SignalR server side version: v2.4.1
- SignalR client side version: v3.1.9

**Comment by BrennanConroy** [comment] 2020-11-05 17:03
Dupe of https://github.com/dotnet/aspnetcore/issues/26701

**Closed** 2020-11-06 22:17 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
