### ISSUE TITLE
HealthCheckPublisherError and HealthCheckPublisherTimeout have the same EventId.Id = 104

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/aspnetcore#47348] opened 2023-03-21 05:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckPublisherHostedService.EventIds, both HealthCheckPublisherErrorId and HealthCheckPublisherTimeoutId are defined as 104:

<https://github.com/dotnet/aspnetcore/blob/6a6d775f49623bbd742c02f89d373630668547bb/src/HealthChecks/HealthChecks/src/HealthCheckPublisherHostedService.cs#L201-L202>

These are then used as LoggerMessageAttribute.EventId, whence they go to EventId.Id.

### Expected Behavior

Each event in the same logging category should have a distinct EventId.Id. That would allow the events to be recognized even after they are passed through a logger that uses only EventId.Id and discards EventId.Name, such as Microsoft.Extensions.Logging.EventLog.EventLogLogger.

### Exceptions (if any)

None

### .NET Version

6.0.15

### Anything else?

This bug has been there ever since the events were added in <https://github.com/aspnet/Diagnostics/pull/498>.

[Event IDs for some Microsoft.AspNetCore.Mvc.Core log messages changed](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/microsoft-aspnetcore-mvc-core-log-event-ids) is precedent for making event IDs unique even though it is a breaking change.

**Comment by mitchdenny** [comment] 2023-03-22 23:49
> Unfortunately I don't remember exactly why I suppressed the warning here. My initial thought is because it is a breaking change, and I didn't want to deal with breaking changes in that PR (since it was just refactoring to use the source generator).

This sounds reasonable. I possibly would have done the same thing ;) @KalleOlaviNiemitalo are you interested in submitting a PR to fix this up?

**Comment by eerhardt** [comment] 2023-03-23 01:26
Note the work involved isn't just fixing up the code, it is also documenting the breaking change.

**Comment by mitchdenny** [comment] 2023-03-23 01:29
Ah yes, that will probably require the team to march it through the process. Fair enough.

**Comment by eerhardt** [comment] 2023-03-27 14:59
Duplicate of https://github.com/dotnet/aspnetcore/issues/46099.

**Closed by eerhardt** 2023-03-27 14:59 UTC
Labels: area-healthchecks
