### ISSUE TITLE
Blazor 3.2.0 Preview 1 blazor.boot.json includes .pdb and .so files

### ISSUE THREAD

**Issue by dmarchant** [dotnet/aspnetcore#18844] opened 2020-02-06 01:41 UTC
First, thanks so much for this awesome project! I really like where Blazor is going.

I recently tried upgrading my asp.net core hosted client-side blazor project to Blazor 3.2.0 Preview 1. After upgrading and deploying the published app on CentOS 7, the client-side blazor app fails to load and gives me 404 errors in the Chrome DevTools console. The 404 errors look like this.
```
GET https://<hostname>/_framework/_bin/Project.Shared.pdb 404
GET https://<hostname>/_framework/_bin/System.Native.so 404
GET https://<hostname>/_framework/_bin/System.IO.Compression.Native.so 404
GET https://<hostname>/_framework/_bin/System.Native.a 404
GET https://<hostname>/_framework/_bin/System.Net.Http.Native.so 404
GET https://<hostname>/_framework/_bin/System.Security.Cryptography.Native.OpenSsl.so 404
```
I am publishing the project with a command like
```
dotnet publish -r centos.7-x64 -f netcoreapp3.1 -c Release --self-contained --nologo
```
Upon comparing the generated `blazor.boot.json` before and after the upgrade to 3.2.0 Preview 1, it looks like 3.2.0 Preview 1 is now putting `.so` files and `.pdb` files in `blazor.boot.json` versus before it wasn't. I'm assuming that the 404s are a result of the asp.net core web server not serving that file type because the files physically exist on disk. Is there a workaround for this?

**Comment by javiercn** [comment] 2020-02-06 09:15
@dmarchant thanks for contacting us.

We are aware of this issue. @pranavkm Is this note a dupe of something else?

**Comment by pranavkm** [comment] 2020-02-06 14:20
Yup - #18655

**Closed** 2020-02-06 14:20 UTC
Labels: area-blazor, blazor-wasm
