### ISSUE TITLE
KnownNetworks needs MapToIPv6?

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#30617] opened 2021-03-03 20:26 UTC
### Describe the bug
Sending challenge request ignores `https` protocol, setting the redirect_uri to `http` instead.

### To Reproduce
I use this code in my app. My app runs in `http` because it's behind a load balancer.

```
var redirectUrl = Url.Action("GithubCallback", "Auth", new { ReturnUrl = returnUrl }, protocol: "https");
_logger.LogInformation("Creates a ChallengeResult with {URL}", redirectUrl);
var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
_logger.LogInformation("Authentication property redirect uri: {URI}", properties.RedirectUri);
return Challenge(properties, provider);
```
The log indicates that the return url uses `https`

```
Creates a ChallengeResult with https://xxx.xxx/auth/github/callback?returnurl=%2F
Authentication property redirect uri: https://xxx.xxx/auth/github/callback?returnurl=%2F
```
In chrome I can see this request:
```
Request URL: https://github.com/login/oauth/authorize?client_id=xxx&scope=user&response_type=code&redirect_uri=http%3A%2F%2Fxxx.xxx%2Fsignin-github&state=CfDJ8G2W7vzaYyVOuPXcYRuX5308hgNngHsC8ne8KQrZngDwftnQFrEFwjSvoTgm6hYMkxq_nlUao9HYPPMQSqajyjwNz5qmREDLgAIPc8HwE9tOdnOwv8I71OpeDbAk59tXFFPuZHtEt1B0ZLB86aJ-9EA0JY-FiCIGFnQ0WhY-Q7EJrlzjJmd8kwgfk8Q7RxTD5otpDSwurU1wLdpQyADWgMLZaOpZeXC_CfPItOY_JlN2sarN5ftt_yyT_OeeDTXt1FIZfbplufAAbtP0gFQ676paGgJegaejQhXMK2EJXSHA
```
This will in turn generate the following problem but this does not seem to b the root cause 
```
warn: Microsoft.AspNetCore.Http.ResponseCookies[1]
The cookie '.AspNetCore.Correlation.mst-sU_nyZuKabrc4lPtSbVuw87umiUUbHv-ypk4rBs' has set 'SameSite=None' and must also set 'Secure'.
warn: Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1[[Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions, Microsoft.AspNetCore.Authentication.OAuth, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]][15]
'.AspNetCore.Correlation.mst-sU_nyZuKabrc4lPtSbVuw87umiUUbHv-ypk4rBs' cookie not found.
```

### Further technical details
dotnet --info

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by blowdart** [comment] 2021-03-03 21:55
rather than try this method does the [forwarding headers middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0) not work for you? That, when put in the right order, will allow the proxy to indicate the original protocol, and that is then reflected in the request instance and everything else that uses it.

**Comment by marcuslindblom** [comment] 2021-03-03 22:14
I think think that it should work just fine. I have had problems with forward headers before.
This is my kubernetes cluster cidr that I use in my config.

<img width="254" alt="Screenshot 2021-03-03 at 23 08 35" src="https://user-images.githubusercontent.com/319720/109879062-660bcf80-7c75-11eb-9786-350be3ec8bd8.png">

And this is my config.

```
public void ConfigureServices(IServiceCollection services)
    {
      services.AddResponseCaching();

      services.Configure<ForwardedHeadersOptions>(options =>
      {
        options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
        options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("10.244.0.0"), 16)); //10.244.0.0/16
      });

      ConfigureRavenDbDocStore(services);

      AddAuthentication(services);

      services.AddDataProtection()
          .SetApplicationName("SharedCookieApp")
          .PersistKeysToFileSystem(new DirectoryInfo(Configuration.GetValue<string>("DataProtection")));

      services.AddIdentityCore<User>(options =>
      {
        options.Password.RequireDigit = true;
        options.Password.RequiredLength = 8;
        options.Password.RequireNonAlphanumeric = false;
        options.Password.RequireUppercase = true;
        options.Password.RequireLowercase = true;
      })
        .AddRoles<Raven.Identity.IdentityRole>()
        .AddRoleStore<RoleStore<Raven.Identity.IdentityRole>>()
        .AddUserStore<UserStore<User, Raven.Identity.IdentityRole>>()
        .AddSignInManager()
        .AddDefaultTokenProviders()
        .AddTokenProvider("MyApp", typeof(DataProtectorTokenProvider<User>));

      services.AddHttpContextAccessor();

      services.AddHealthChecks();

      services.AddTransient<IAuthorizationHandler, TeamAuthorizationHelper>();
      services.AddTransient<IAuthorizationHandler, WorkspaceAuthorizationHandler>();

      services.AddAuthorization(options =>
      {
        options.AddPolicy("Workspace", policy => policy.Requirements.Add(new WorkspaceRequirement()));
      });

      services.Configure<RouteOptions>(options =>
      {
        options.LowercaseUrls = true;
        options.AppendTrailingSlash = false;
        options.LowercaseQueryStrings = true;
      });

      services.AddCors(options =>
      {
        options.AddPolicy("CorsPolicy", builder => builder.WithOrigins("https://xxx.xxx"));
      });

      services.AddControllersWithViews().AddNewtonsoftJson();

      services.AddScoped<Layout>();
      services.AddScoped<IsAuthenticatedAttribute>();
      services.AddSingleton<IAppVersionService, AppVersionService>();

      services.AddCsp();
    }
```
Should be fine I guess?

**Comment by Tratcher** [comment] 2021-03-04 01:56
Note the value you pass to Challenge (https://xxx.xxx/auth/github/callback?returnurl=%2F) is not the one that goes into the redirect_uri field (http%3A%2F%2Fxxx.xxx%2Fsignin-github), it's not just the scheme that's different. Your value is stored in the state field and used after the auth flow completes.

@blowdart's right that Forwarded Headers are the correct way to address this.

Can you share your Configure method as well to confirm UseForwardedHeaders is called in the right order?

When debugging forwarded headers it's helpful to log the x-forwarded-for and x-forwarded-proto headers and the HttpContext.Connection.RemoteIP fields on a request, before and after the forwarded headers middleware. The middleware has some logs today, but only for invalid values.

**Comment by marcuslindblom** [comment] 2021-03-04 08:06
Ok, I understand.

This is my configure method

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ICorsService corsService, ICorsPolicyProvider corsPolicyProvider, ILogger<Startup> logger)
    {
      app.UseForwardedHeaders();

      app.Use(async (context, next) =>
      {
        // Request method, scheme, and path
        logger.LogDebug("Request Method: {Method}", context.Request.Method);
        logger.LogDebug("Request Scheme: {Scheme}", context.Request.Scheme);
        logger.LogDebug("Request Path: {Path}", context.Request.Path);

        // Headers
        foreach (var header in context.Request.Headers)
        {
            logger.LogDebug("Header: {Key}: {Value}", header.Key, header.Value);
        }

        // Connection: RemoteIp
        logger.LogDebug("Request RemoteIp: {RemoteIpAddress}",
            context.Connection.RemoteIpAddress);

        await next();
      });

      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }
      else
      {
        app.UseStatusCodePagesWithReExecute("/Home/HandleError/{0}");
      }

      app.UseCors("CorsPolicy");

      app.UseStaticFiles(new StaticFileOptions
      {
        ContentTypeProvider = new ContentTypeProvider(),
        HttpsCompression = Microsoft.AspNetCore.Http.Features.HttpsCompressionMode.Compress,
        OnPrepareResponse = async ctx =>
        {
          var policy = await corsPolicyProvider.GetPolicyAsync(ctx.Context, "CorsPolicy");
          var result = corsService.EvaluatePolicy(ctx.Context, policy);
          corsService.ApplyResult(result, ctx.Context.Response);
          const double durationInSeconds = 60 * 60 * 24 * 365.25;
          ctx.Context.Response.Headers[HeaderNames.CacheControl] = "public,max-age=" + durationInSeconds;
        }
      });

      IHttpContextAccessor httpContextAccessor = app.ApplicationServices.GetRequiredService<IHttpContextAccessor>();

      app.UseCsp(csp =>
      {
        csp.ByDefaultAllow
          .FromSelf();

        csp.AllowFramin
          .From("https://encom.xxx.xxx");

        csp.AllowScripts
          .FromSelf()
          .From("https://static.xxx.xxx");

        csp.AllowWorkers
          .FromSelf()
          .From("https://static.xxx.xxx");

        csp.AllowStyles
          .FromSelf()
          .From("https://static.xxx.xxx");

        csp.AllowFonts
          .FromSelf()
          .From("https://static.xxx.xxx");

        csp.AllowConnections
          .ToSelf()
          .To("wss://sync.xxx.xxx")
          .To("https://api.xxx.xxx");

      });

      app.UseWebSockets();

      app.UseRouting();

      app.UseSentryTracing();

      app.UseCookiePolicy();

      app.UseAuthentication();

      app.UseAuthorization();

      app.UseEndpoints(endpoints =>
      {
        endpoints.MapHealthChecks("/healthz")
        endpoints.MapControllerRoute(
                  name: "default",
                  pattern: "{controller=home}/{action=index}/{id?}");
      });
    }
```

It seems to be a intermittent problem and I managed to get one deployment to work and one to fail.

This is the debug info from the forward headers middleware

This one works:
```dbug: Wieldy.Web.Startup[0]
 
Request Scheme: http
 
dbug: Wieldy.Web.Startup[0]
 
Request Path: /healthz
 
dbug: Wieldy.Web.Startup[0]
 
Header: Connection: close
 
dbug: Wieldy.Web.Startup[0]
 
Header: Accept: */*
 
dbug: Wieldy.Web.Startup[0]
 
Header: Host: 10.244.0.182:80
 
dbug: Wieldy.Web.Startup[0]
 
Header: User-Agent: kube-probe/1.20
 
dbug: Wieldy.Web.Startup[0]
 
Request RemoteIp: ::ffff:10.244.0.1
```

This one fails
```
dbug: xxx.xxx.Startup[0]
 
Request Method: GET
 
dbug: xxx.xxx.Startup[0]
 
Request Scheme: http
 
dbug: xxx.xxx.Startup[0]
 
Request Path: /healthz
 
dbug: xxx.xxx.Startup[0]
 
Header: Connection: close
 
dbug: xxx.xxx.Startup[0]
 
Header: Accept: */*
 
dbug: xxx.xxx.Startup[0]
 
Header: Host: 10.244.3.63:80
 
dbug: xxx.xxx.Startup[0]
 
Header: User-Agent: kube-probe/1.20
```

**Comment by Tratcher** [comment] 2021-03-05 23:30
I don't see how either of those examples could be working, the resulting request scheme is `http` for both of theme, not `https`. There's no indication your load balancer is including x-forwarded-proto or x-forwarded-for headers with the information you need. You'll need to check your load balancer config to ensure those are enabled.

**Comment by Tratcher** [comment] 2021-03-05 23:31
Are those traces from a health probe (/healthz) rather than external requests? Make sure you capture traces from an external request.

**Comment by marcuslindblom** [comment] 2021-03-06 06:16
@Tratcher Ok, I see what you mean. My bad.

I actually found in the docs that when you use `KnownNetworks` you should provide IP ranges using Classless Interdomain Routing (CIDR) notation. And that is done by using [IPAddress.MapToIPv6](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.maptoipv6). So with that said, I changed my config to

```
options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("10.244.0.0").MapToIPv6(), 16));
```

And this is a trace from an external request. Now it seems like the `MapToIPv6` method sets the correct format when I add a known network? I have done multiple deployments without breaking anything now so this seems to be a correct configuration for my setup?

```
2021-03-06T06:02:09.572937407Z Header: X-Scheme: https
2021-03-06T06:02:09.572941307Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572944807Z Header: X-Original-Forwarded-For: 155.4.110.139
2021-03-06T06:02:09.572948307Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572951807Z Header: CF-IPCountry: SE
2021-03-06T06:02:09.572955707Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572959107Z Header: CF-RAY: 62b95fa0ff760d52-ARN
2021-03-06T06:02:09.572962807Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572966207Z Header: CF-Visitor: {"scheme":"https"}
2021-03-06T06:02:09.572969807Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572973107Z Header: sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"
2021-03-06T06:02:09.572977106Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572980406Z Header: sec-ch-ua-mobile: ?0
2021-03-06T06:02:09.572984006Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572987606Z Header: sec-fetch-site: same-origin
2021-03-06T06:02:09.572991006Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.572995106Z Header: sec-fetch-mode: same-origin
2021-03-06T06:02:09.573016506Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.573025406Z Header: sec-fetch-dest: empty
2021-03-06T06:02:09.573029706Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.573033106Z Header: CF-Connecting-IP: 155.4.110.139
2021-03-06T06:02:09.573050406Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.573054006Z Header: CDN-Loop: cloudflare
2021-03-06T06:02:09.573058006Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.573084405Z Header: cf-request-id: 08a7ba189700000d52c30a6000000001
2021-03-06T06:02:09.573088605Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.573092505Z Header: X-Original-For: [::ffff:10.240.0.7]:40976
2021-03-06T06:02:09.573096405Z dbug: Wieldy.Web.Startup[0]
2021-03-06T06:02:09.573100305Z Request RemoteIp: 162.158.183.133```

**Comment by Tratcher** [comment] 2021-03-06 17:58
Ah, much better. I thought we fixed the MapToIPv6 issue all the way back in 2.2 (https://github.com/aspnet/BasicMiddleware/pull/359)? We should debug that.

**Comment by Tratcher** [comment] 2021-04-06 20:53
@fvoronin want to take a look at this one too?

**Comment by fvoronin** [comment] 2021-04-06 21:00
I'll try to figure it out.

**Comment by fvoronin** [comment] 2021-04-14 19:11
In the last example everything works because the subnet declared this way `new IPNetwork(IPAddress.Parse("10.244.0.0").MapToIPv6(), 16)` contains 2<sup>122</sup> IP addresses, i.e. the whole set of IPv4. So we're effectively marking any IP address as `KnownNetworks`. The subnet equivalent of `new IPNetwork(IPAddress.Parse("10.244.0.0"), 16)` in IPv6 format is `new IPNetwork(IPAddress.Parse("10.244.0.0").MapToIPv6(), 112)`.

Regarding the problem - it's not quite clear why there is no `X-Original-Proto` header in the last job log, only `X-Original-For`.  Is the proxy server not setting the `x-forwarded-proto` header? This may be the root cause of the `redirect_uri` being set to the wrong protocol.

@marcuslindblom, more detailed logging is needed to fully understand. Please try to do this:
1. Put the following logging code not only after the `app.UseForwardedHeaders()` call, but also before it, so that we can see what headers the request came with from the proxy
```cs
app.Use(async (context, next) =>
      {
        // Request method, scheme, and path
        logger.LogDebug("Request Method: {Method}", context.Request.Method);
        logger.LogDebug("Request Scheme: {Scheme}", context.Request.Scheme);
        Logger.LogDebug("Request Path: {Path}", context.Request.Path);

        // Headers
        foreach (var header in context.Request.Headers)
        {
            logger.LogDebug("Header: {Key}: {Value}", header.Key, header.Value;)
        }

        // Connection: RemoteIp
        logger.LogDebug("Request RemoteIp: {RemoteIpAddress}",
            context.Connection.RemoteIpAddress);

        {RemoteIpAddress}; }
      });
```
2. Turn on the `Debug` level logging for the `Microsoft.AspNetCore.HttpOverrides` category to see warnings from `ForwardedHeadersMiddleware`.

But in general, I did not find any problems in the `ForwardedHeadersMiddleware` work.

**Comment by Tratcher** [comment] 2021-04-20 02:31
@fvoronin thank you for investigating that, I'd overlooked that it was using the wrong network prefix length. Moving this to Discussions pending further information.

**Closed** 2021-06-19 08:00 UTC
Labels: area-runtime, feature-middleware
