### ISSUE TITLE
Blazor: ship .NET in browsers

### ISSUE THREAD

**Issue by ericmutta** [dotnet/aspnetcore#37720] opened 2021-10-20 20:35 UTC
Pasting this directly from https://github.com/dotnet/AspNetCore.Docs/issues/23568 (thanks @guardrex for directing me to the right team): 

The idea of replacing JavaScript with C# for in-browser code is so appealing that I have been _eagerly waiting_ for Blazor and checking on its progress every month for well over a year now!

I am starting a project where I would love to use Blazor so I went looking for demo sites to see how it performs and that's the first problem: there are very few demo sites! **To drive adoption of Blazor Microsoft needs to show something more complex than a counter incrementing button**.

While searching, I found https://www.mudblazor.com/ and came across the second problem: there's a _noticeable_ delay in loading the page (especially on Chrome mobile) probably because it's downloading the . NET runtime. This happens _all the time on all the pages_. **To drive adoption of Blazor Microsoft should ship the .NET runtime as part of the browser.**

Google and Apple may throw a fit at the suggestion but thankfully Microsoft has the Edge browser and if it came with the .NET runtime pre-installed the same way that the JavaScript runtime is a core part of the browser, then **Edge could become _the_ platform for modern high-performance Blazor-based apps.** 💪 

If Microsoft Edge started shipping with .NET pre-installed (and kept it evergreen with each browser update), many of us in the .NET ecosystem would start writing **works best with Microsoft Edge** on our Blazor-powered web apps and over time that may very well prompt Google and Apple to do the same!

Front-end development with JavaScript is not fun at all especially if you have been spoiled by the insane power and productivity that comes with .NET and Visual Studio tooling. Here's hoping Blazor will save the day by taking that final step to global adoption: _being pre-installed in every major browser_ 🔥

**Comment by mkArtakMSFT** [comment] 2021-10-20 21:03
Thanks for contacting us and sharing your thoughts about Blazor.
We'll look into your feedback more with the team. In  the meantime, have you seen [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) repo already? It is a collection of all things Blazor and will help you find other examples from the community that you may be interested in.

**Comment by TanayParikh** [comment] 2021-10-20 21:53
Thanks for reaching out, closing this issue as a duplicate of https://github.com/dotnet/aspnetcore/issues/37015.

**Closed by TanayParikh** 2021-10-20 21:53 UTC
Labels: area-blazor

**Comment by ericmutta** [comment] 2021-10-20 23:28
@mkArtakMSFT @TanayParikh many thanks to both of you for the prompt follow up :+1:

I will check out the links you provided for more research. I do note however this issue is closed as a duplicate of #37015 which was itself closed because it _"...is not directly Blazor specific."_. Despite this, I sincerely hope the team will look more into it (ever since Google started taking 15-30% of revenues for Android apps, I switched to ASP.NET for web development to avoid those fees and it has been an awesome experience so far...when Blazor apps are finally able to load as quickly as Javascript apps, it will be absolute heaven :smiley:)
