### ISSUE TITLE
ASP.Net Core MVC Validation at Model Level

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#43244] opened 2022-08-12 17:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNet-Core-MVC-Validation-at-Model-Lev/10118799)._

---
[severity:I'm unable to use this version]
using System.ComponentModel.DataAnnotations;

[Required]
[EmailAddress]
public string Address { get; set; }

I enter brian31sg@yahoo  and this is a valid email. Why?

---
#### Feedback Bot on 8/11/2022, 11:36 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by sabahshariq** [comment] 2022-08-14 19:13
This is the default feature of _EmailAddressAttribute_.

The purpose of **EmailAddressAttribute** was just to prevent "fat-fingering" errors - not to prevent every possible invalid email address. The algorithm that currently use is "must have at least one '@' and the '@' cannot be at the start or the end." 

If you look into the code implementation in the following address you will get an clear idea on how the attribute implementation works.

https://github.com/dotnet/runtime/blob/main/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs

          ` // only return true if there is only 1 '@' character
            // and it is neither the first nor the last character
            int index = valueAsString.IndexOf('@');

            return
                index > 0 &&
                index != valueAsString.Length - 1 &&
                index == valueAsString.LastIndexOf('@'); `

**Comment by MackinnonBuck** [comment] 2022-08-15 16:59
Closing as "by design".

**Closed by MackinnonBuck** 2022-08-15 16:59 UTC
Labels: :heavy_check_mark: Resolution: By Design, area-mvc, Status: Resolved, feature-blazor-form-validation
