### ISSUE TITLE
"Error: Cannot advance beyond the end of the Sibling array" appears when streaming rendering subcomponents

### ISSUE THREAD

**Issue by TimChen44** [dotnet/aspnetcore#52371] opened 2023-11-26 08:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

"Error: Cannot advance beyond the end of the Sibling array" appears when streaming rendering subcomponents, and the problem will be repeatedly displayed when opening the page again in the future.But adding HTML tags can avoid this problem
![Bug](https://github.com/dotnet/aspnetcore/assets/7581981/5c50060a-26fc-4bb8-a54f-a48a554bdaa4)

The following code will have an exception
```
@page "/StreamRenderingChild"

<SharedMessageStreamTrue Title="Level 1">
    <SharedMessageStreamTrue Title="Level 2" />
</SharedMessageStreamTrue>
```

The following code executes normally
```
@page "/StreamRenderingChild"

<SharedMessageStreamTrue Title="Level 1">
    <div>
        <SharedMessageStreamTrue Title="Level 2-1" />
    </div>
</SharedMessageStreamTrue>
```

SharedMessageStreamTrue component code
```
@attribute [StreamRendering(true)]

<div class="card">
    <div class="card-header">
        StreamRendering(true) : @Title
    </div>
    <div class="card-body">
        <p>
            @message
        </p>

        <p>@ChildContent</p>
    </div>
    <div class="card-footer">
        OSDescription:@RuntimeInformation.OSDescription
    </div>
</div>



@code {
    private string message = "没有点击";
    private int clickCount = 0;

    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    [Parameter]
    public string Title { get; set; } = "StreamRendering(true)";


    protected override async Task OnInitializedAsync()
    {
        message = $"{DateTime.Now.ToString()}\t载入中...";
        await Task.Delay(2000);
        message = $"{DateTime.Now.ToString()}\t载入完成";
    }
}
```

### .NET Version

8.0.100

### Anything else?

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

已安装 .NET 工作负载:
 Workload version: 8.0.100-manifests.71b9f198
没有要显示的已安装工作负载。

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

**Comment by MackinnonBuck** [comment] 2023-12-06 00:13
Thanks for reaching out.

It looks like the problem here is that the HTML in the component from your repro is not well-formed.

## Summary

According to the [HTML spec](https://html.spec.whatwg.org/#paragraphs), `<p>` elements should only contain [phrasing content](https://html.spec.whatwg.org/#phrasing-content-2). If this rule gets broken, browsers will attempt to "fix" the HTML by applying changes to make it well-formed. For example, try copy/pasting the following into an HTML file and opening it in a browser:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Can a &lt;div&gt; go in a &lt;p&gt;?</title>
</head>
<body>
    <p>
        Some phrasing content

        <div>
            What happens now?
        </div>
    </p>
</body>
</html>
```

If you inspect the DOM using the Dev Tools window, you'll see something like this:

![image](https://github.com/dotnet/aspnetcore/assets/10456961/30b6418a-c027-4cb3-b07b-90913337c7e3)

It's this type of transformation that's causing the error you're experiencing during stream rendering.

The component in your repro renders the `ChildContent` render fragment inside a `<p>`, and since the `ChildContent` contains non-phrasing content (like a `<div>`), the browser adapts by automatically inserting a closing `</p>` tag before the non-phrasing content starts. This results in matching streaming boundary marker comments getting placed on different levels of the DOM hierarchy for the same component. Blazor can't make sense of this, and so it throws an error when attempting to merge streamed content onto the page.

## Workaround

In your repro, if you change:
```razor
<p>@ChildContent</p>
```

to:
```razor
<div>@ChildContent</div>
```

...then you'll see that streaming works correctly.

## Potential fixes

We could make the error message clearer by indicating that the cause of the error is likely malformed/illegal HTML. I don't think it's reasonable to expect the framework to be able to adapt to malformed HTML to handle this scenario without erroring.

**Comment by TimChen44** [comment] 2023-12-10 08:01
Thank you for the answer. Thank you

**Comment by javiercn** [comment] 2023-12-12 15:34
@MackinnonBuck feel free to file a separate bug about the HTML bit

**Closed by javiercn** 2023-12-12 15:34 UTC
Labels: question, area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved
