### ISSUE TITLE
Cookies rejected while switching to minimal hosting model syntax

### ISSUE THREAD

**Issue by myrup** [dotnet/aspnetcore#38434] opened 2021-11-16 15:31 UTC
### Describe the bug
After switching to minimal hosting model syntax, unexpired cookies created with the old syntax are rejected.

### To Reproduce
For simplicity I've created a minimal hosting model example that uses the `Startup` class (where `Startup` includes cookie authentication).

#### Old syntax
```
Host.CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
    .Build()
    .Run();
```
#### Minimal hosting model syntax (from [here](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#new-hosting-model))
```
 var builder = WebApplication.CreateBuilder(args);
 var startup = new Startup(builder.Configuration);
 startup.ConfigureServices(builder.Services);
 var app = builder.Build();
 startup.Configure(app, app.Environment);
 app.Run();
```

Cookies that are created with these two syntaxes are not cross compatible. We do not wish to force our users to reauthenticate. Can anyone shed light on what could be the reason?

### Further technical details
- ASP.NET Core version: 6.0

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
</details>

**Comment by Tratcher** [comment] 2021-11-16 15:47
Duplicate of https://github.com/dotnet/aspnetcore/issues/38274

**Comment by myrup** [comment] 2021-11-16 16:09
@Tratcher I can confirm that adding the line
```
builder.Services.AddDataProtection().SetApplicationName(builder.Environment.ContentRootPath.TrimEnd('/'));
```
right after `builder` is created makes the cookies compatible.

**Comment by rafikiassumani-msft** [comment] 2021-11-19 21:16
Triage: Closing as a dup. see https://github.com/dotnet/aspnetcore/issues/38274

**Closed by rafikiassumani-msft** 2021-11-19 21:16 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-dataprotection, Status: Resolved
