### ISSUE TITLE
Hot Reload stops working when you edit the NavManager.razor file in the default blazorwasm template using WSL and VS Code

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#31923] opened 2021-04-18 21:31 UTC
Hot Reload stops working when you edit the NavManager.razor file in the default blazorwasm template using WSL and VS Code

### To Reproduce
- In WSL2 using Ubuntu 20.04
- Create a new blazorwasm project
- Now open the blazorwasm folder in VS Code using "code ."
- Use dotnet watch to start the site
- Make a change in the Index.razor file and see the HotReload working
- Next open the file /Shared/NavManager.razor and add a NavLink and save the file
- Nothing happens
- Now go back to the Index.razor file and make a change and you will notice that the Hot Reload feature is completely broken i.e it doesn't even refresh the browser, its almost like the browser link is completely terminated.
- **Also even if you refresh the browser your changes do not show up you need to manually stop the app and run dotnet watch again**
![image](https://user-images.githubusercontent.com/18366446/115161840-10d92100-a05d-11eb-8a02-1b0bbe5c45cb.png)

### Further technical details
ASP.NET Core version: 6.0.100-preview.3.21202.5
Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mac/dotnet/sdk/6.0.100-preview.3.21202.5/

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  6.0.100-preview.3.21202.5 [/home/mac/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/home/mac/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/home/mac/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- VS Code ( version 1.55.2 (user setup) )
![image](https://user-images.githubusercontent.com/18366446/115161422-ca82c280-a05a-11eb-82bd-9b4e8bbfc893.png)

**Comment by mkArtakMSFT** [comment] 2021-04-19 16:45
Thanks for contacting us. This is a dupe of https://github.com/dotnet/runtime/issues/50249

**Closed by mkArtakMSFT** 2021-04-19 16:45 UTC
Labels: area-blazor, blazor-wasm, feature-hot-reload
