### ISSUE TITLE
dotnet watch tests timing out

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#24841] opened 2020-08-12 17:43 UTC
Pattern: Failing on Win10 arm64 builds for the last three days. Quarantined.
https://dev.azure.com/dnceng/public/_build/results?buildId=765006&view=ms.vss-test-web.build-test-results-tab&runId=23772704&resultId=121076&paneView=debug
https://dev.azure.com/dnceng/public/_build/results?buildId=766216&view=ms.vss-test-web.build-test-results-tab&runId=23810024&resultId=121079&paneView=debug
https://dev.azure.com/dnceng/public/_build/results?buildId=766845&view=ms.vss-test-web.build-test-results-tab&runId=23842494&resultId=121106&paneView=debug

Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable
Microsoft.DotNet.Watcher.Tools.FunctionalTests.NoDepsAppTests.RestartProcessThatTerminatesAfterFileChange

Dumps are attached to the build results.

```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String predicateName, Predicate`1 predicate, CancellationToken cancellationToken) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 103
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 88
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable() in /_/src/Tools/dotnet-watch/test/DotNetWatcherTests.cs:line 53
--- End of stack trace from previous location ---
```
```
[xUnit.net 00:03:56.73]         8/11/2020 5:22:20 PM: recv: 'watch : Started'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: 'MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: 'MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: 'System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (0x80004005 (E_FAIL))'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at System.Runtime.InteropServices.GCHandle.InternalSet(IntPtr handle, Object value)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: 'System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (0x80004005 (E_FAIL))'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at System.Runtime.InteropServices.GCHandle.InternalSet(IntPtr handle, Object value)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at System.Runtime.InteropServices.GCHandle.set_Target(Object value)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.WeakStringCache.GetOrCreateEntry[T](T internable, Boolean& cacheHit)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.OpportunisticIntern.WeakStringCacheInterner.TryIntern[T](T candidate, String& interned)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.OpportunisticIntern.WeakStringCacheInterner.InterningToString[T](T candidate)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.OpportunisticIntern.InternableToStringImpl[T](T candidate)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at System.Runtime.InteropServices.GCHandle.set_Target(Object value)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.Evaluation.Expander`2.ItemExpander.ExpandItemVectorsIntoString[T](Expander`2 expander, String expression, IItemProvider`1 items, ExpanderOptions options, IElementLocation elementLocation)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.ItemGroupIntrinsicTask.ExpandItemIntoItems(ProjectItemGroupTaskItemInstance originalItem, Expander`2 expander, ISet`1 keepMetadata, ISet`1 removeMetadata)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.WeakStringCache.GetOrCreateEntry[T](T internable, Boolean& cacheHit)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.OpportunisticIntern.WeakStringCacheInterner.TryIntern[T](T candidate, String& interned)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.OpportunisticIntern.WeakStringCacheInterner.InterningToString[T](T candidate)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.OpportunisticIntern.InternableToStringImpl[T](T candidate)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.Evaluation.Expander`2.ItemExpander.ExpandItemVectorsIntoString[T](Expander`2 expander, String expression, IItemProvider`1 items, ExpanderOptions options, IElementLocation elementLocation)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.ItemGroupIntrinsicTask.ExecuteAdd(ProjectItemGroupTaskItemInstance child, ItemBucket bucket, ISet`1 keepMetadata, ISet`1 removeMetadata)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.ItemGroupIntrinsicTask.ExecuteTask(Lookup lookup)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.ItemGroupIntrinsicTask.ExpandItemIntoItems(ProjectItemGroupTaskItemInstance originalItem, Expander`2 expander, ISet`1 keepMetadata, ISet`1 removeMetadata)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteIntrinsicTask(ItemBucket bucket)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask, Dictionary`2 lookupHash)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.ItemGroupIntrinsicTask.ExecuteAdd(ProjectItemGroupTaskItemInstance child, ItemBucket bucket, ISet`1 keepMetadata, ISet`1 removeMetadata)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TaskExecutionMode mode, Lookup lookup)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.ItemGroupIntrinsicTask.ExecuteTask(Lookup lookup)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteIntrinsicTask(ItemBucket bucket)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TargetLoggingContext loggingContext, BuildRequestEntry requestEntry, ITargetBuilderCallback targetBuilderCallback, ProjectTargetInstanceChild taskInstance, TaskExecutionMode mode, Lookup inferLookup, Lookup executeLookup, CancellationToken cancellationToken)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask, Dictionary`2 lookupHash)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(ITaskBuilder taskBuilder, TargetLoggingContext targetLoggingContext, TaskExecutionMode mode, Lookup lookupForInference, Lookup lookupForExecution)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TaskExecutionMode mode, Lookup lookup)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TargetLoggingContext loggingContext, BuildRequestEntry requestEntry, ITargetBuilderCallback targetBuilderCallback, ProjectTargetInstanceChild taskInstance, TaskExecutionMode mode, Lookup inferLookup, Lookup executeLookup, CancellationToken cancellationToken)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(ITaskBuilder taskBuilder, TargetLoggingContext targetLoggingContext, TaskExecutionMode mode, Lookup lookupForInference, Lookup lookupForExecution)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(ITaskBuilder taskBuilder, BuildRequestEntry requestEntry, ProjectLoggingContext projectLoggingContext, CancellationToken cancellationToken)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(ITaskBuilder taskBuilder)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(ITaskBuilder taskBuilder, BuildRequestEntry requestEntry, ProjectLoggingContext projectLoggingContext, CancellationToken cancellationToken)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(ProjectLoggingContext loggingContext, BuildRequestEntry entry, IRequestBuilderCallback callback, String[] targetNames, Lookup baseLookup, CancellationToken cancellationToken)'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(ITaskBuilder taskBuilder)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: '   at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()'
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: post: ''
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(ProjectLoggingContext loggingContext, BuildRequestEntry entry, IRequestBuilderCallback callback, String[] targetNames, Lookup baseLookup, CancellationToken cancellationToken)'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:03:56.73]         8/11/2020 5:22:22 PM: recv: '   at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()'. Does not match condition '[msg == 'Started']'.
```
[console.5303f2bf.txt](https://github.com/dotnet/aspnetcore/files/5064655/console.5303f2bf.txt)

**Comment by pranavkm** [comment] 2020-08-12 17:52
@marcpopMSFT looks like an error executing msbuild on ARM64:

```
System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (0x80004005 (E_FAIL)). Does not match condition [msg == Started].
   at System.Runtime.InteropServices.GCHandle.InternalSet(IntPtr handle, Object value). Does not match condition [msg == Started].
   at System.Runtime.InteropServices.GCHandle.set_Target(Object value)
   at Microsoft.Build.WeakStringCache.GetOrCreateEntry[T](T internable, Boolean& cacheHit)
   at Microsoft.Build.OpportunisticIntern.WeakStringCacheInterner.TryIntern[T](T candidate, String& interned)
```

**Comment by marcpopMSFT** [comment] 2020-08-12 18:06
Did you change the version of msbuild that you were using before this happened?  @tommcdon as my team isn't doing arm64 work at the moment and given the error, I'm wondering if it's a runtime issue.

**Comment by tommcdon** [comment] 2020-08-12 18:09
@AntonLapounov do you have time to take a quick look?

**Comment by pranavkm** [comment] 2020-08-12 18:11
@marcpopMSFT we picked up a RC1 SDK very recently (we were on a preview7 SDK prior to that). This would coincide with this date.

**Comment by Tratcher** [comment] 2020-08-12 18:32
Looks like there were similar failures back in June in other tests that we have since skipped on ARM. https://github.com/dotnet/aspnetcore/issues/23360

**Comment by AntonLapounov** [comment] 2020-08-12 20:13
I think I fixed this issue in dotnet/runtime#39810.  Please ensure you have that fix.

**Comment by dougbu** [comment] 2020-08-13 19:36
@AntonLapounov that fix went in a long time ago and we're at `5.0.0-rc.1.20412.5` dependencies from dotnet/runtime. This seems like a recent regression that started when we moved from `5.0.0-rc.1.20406.11` runtime dependencies to  `5.0.0-rc.1.20409.3`. I'm not seeing another smoking gun in https://github.com/dotnet/aspnetcore/compare/fa0cb711864e4b70b90265edbe2daed5c4f67beb..3de55dfd2152d85b958c3f2f5e37fedf360f4753

Suggest looking at https://github.com/dotnet/runtime/compare/9b2f548c3b0da290bc57f1a0460cd0c5c408095e..ff01831094128fb9df0be61fd0e352bbcaeddf02

**Comment by dougbu** [comment] 2020-08-13 19:43
Just realized adding another dot switches to the commit list 😺

**Comment by AntonLapounov** [comment] 2020-08-13 20:17
@dougbu Thank you.  This issue looks very similar to what I fixed and I do not see anything suspicious in those commits.  How do I get the `coreclr.dll` that you are using with the corresponding `coreclr.pdb`?  If there is no crash dump, I may need instructions how to reproduce the failure.

**Comment by pranavkm** [comment] 2020-08-13 20:19
@AntonLapounov \ @dougbu these tests launch `dotnet msbuild`, so it's using the version of the runtime shipped in the SDK that our repo uses. In this case, that would be 5.0.100-rc.1.20379.10. If you grab that build of the SDK, you could verify if it has made it to it.

**Comment by BrennanConroy** [comment] 2020-08-19 16:47
Ping, how do we move forward here?

We also have a dump if that will help https://dev.azure.com/dnceng/public/_build/results?buildId=777741&view=ms.vss-test-web.build-test-results-tab&runId=24342110&resultId=121185&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by dougbu** [comment] 2020-08-19 17:29
@BrennanConroy I got nothing. @AntonLapounov❔

**Comment by AntonLapounov** [comment] 2020-08-19 20:48
According to the dump, `coreclr.dll`'s version is:
```
ProductVersion:   5,0,20,37113 @Commit: d8cf13e0ba9b369a15a83472b6b97463c6d07fe2
```
That corresponds to July 21st.  My fix for this issue was merged to dotnet/runtime on July 22nd and propagated to dotnet/sdk on August 1st.  Please update SDK version.

**Comment by BrennanConroy** [comment] 2020-08-20 17:39
@dougbu I don't remember, does arcade update our sdk automatically, or do we do it manually?

**Comment by pranavkm** [comment] 2020-08-20 17:40
SDK updates are manual. There is a brand new RC1 update available as of today. Could you try updating?

**Comment by BrennanConroy** [comment] 2020-08-20 17:41
Yep

**Comment by dougbu** [comment] 2020-08-20 17:46
/fyi Arcade updates _will_ update our .NET SDK but only when we let ourselves fall behind their minimum. Right now the Arcade minimum is just before the previous public preview (`5.0.100-preview.6.20310.4`).

**Comment by dougbu** [comment] 2020-08-25 21:28
Is this a dupe of #23360❔ Did #25081 successful at removing the problem i.e. did we run the validations enough to see if the tests remain flaky with a newer SDK❔

**Comment by pranavkm** [comment] 2021-01-27 00:53
These tests have unquarantined as part of migrating dotnet-watch tests to the SDK

**Closed by pranavkm** 2021-01-27 00:53 UTC
Labels: affected-very-few, area-commandlinetools, severity-minor, task, test-failure
