### ISSUE TITLE
Adding references and creating new razor pages in a Blazor project has been crashing all morning. 5 new crash dumps within the last hour

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22965] opened 2020-06-15 20:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1077541/adding-references-and-creating-new-razor-pages-in.html)._

---
Adding references and creating new razor pages in a Blazor project has been crashing all morning. 5 new crash dumps within the last hour

---
#### Visual Studio Feedback System on 6/14/2020, 11:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2020-06-15 20:15
Duplicate of https://github.com/dotnet/aspnetcore/issues/22276

**Closed by NTaylorMullen** 2020-06-15 20:15 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved
