### ISSUE TITLE
[5.0.0-preview.3] x86 MSBuild is failing due to x64 targeted Microsoft.NET.Sdk.Razor.Tasks.dll

### ISSUE THREAD

**Issue by CXuesong** [dotnet/aspnetcore#20679] opened 2020-04-09 14:30 UTC
### Describe the bug
After upgrading to .NET SDK 5.0.100-preview.4.20202.8, I found my ASP.NET Core application failed to build in VS 2019. I saw error messages like this
> C:\Program Files\dotnet\sdk\5.0.100-preview.4.20202.8\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets(54,5): error MSB4062: 未能从程序集 C:\Program Files\dotnet\sdk\5.0.100-preview.4.20202.8\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\..\..\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll 加载任务“Microsoft.AspNetCore.Razor.Tasks.FindAssembliesWithReferencesTo”。未能加载文件或程序集“Microsoft.NET.Sdk.Razor.Tasks, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60”或它的某一个依赖项。试图加载格式不正确的程序。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。

Basically it's caused by `System.BadImageFormatException` when loading `Microsoft.NET.Sdk.Razor.Tasks.dll`.

However, the compilation passes if I use `dotnet build` in with .NET CLI.

After checking the following file with corflags
```
C:\Program Files\dotnet\sdk\5.0.100-preview.4.20202.8\Sdks\Microsoft.NET.Sdk.Razor\tasks\net46\Microsoft.NET.Sdk.Razor.Tasks.dll
```
I saw something like this
![image](https://user-images.githubusercontent.com/11611687/78905220-3a598700-7ab0-11ea-9072-5dd9ddfdb318.png)

Then I think this dll is targeted on x64 platform only. [[1]](https://stackoverflow.com/a/23614024/4763572) This explains why MSBuild fails in Visual Studio, as they are using x86 MSBuild.

I'm not sure whether this is by design, but the same dll in [v5.0.0-preview.2](https://www.nuget.org/packages/Microsoft.NET.Sdk.Razor/5.0.0-preview.2.20160.3) targets at AnyCPU.

### Further technical details
- ASP.NET Core version
5.0.0-preview.3.20170.2
- Include the output of `dotnet --info`
```
.NET Core SDK（反映任何 global.json）:
 Version:   5.0.100-preview.4.20202.8
 Commit:    074b436c3d

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.4.20202.8\

Host (useful for support):
  Version: 5.0.0-preview.3.20169.1
  Commit:  bc28cbef85

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.800 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.3.20207.3 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.4.20202.8 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.3.20170.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.3.20169.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.4.20180.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 2019 (16.6.0 Preview 2.1)

**Comment by CXuesong** [comment] 2020-04-09 14:50
Just installed `Microsoft.NET.Sdk.Razor 5.0.0-preview.3.20170.2` from the [daily build](https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md) and the build succeeded in Visual Studio.

I think there might be something wrong with the ASP.NET SDK contained in .NET 5 SDK installer:
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100-preview.4.20202.8/dotnet-sdk-5.0.100-preview.4.20202.8-win-x64.exe (SHA-256: b751778c8c59d114f1abb7b5fd442dddd8b7905ece83968b671cadf488d0d5fa)

**Comment by mkArtakMSFT** [comment] 2020-04-09 15:00
Thanks for contacting us, @CXuesong.
@ajaybhargavb do you know what have changed here? i don't exclude this being caused by some underlying change in the SDK.
/cc @pranavkm

**Comment by pranavkm** [comment] 2020-04-09 16:59
I'll take over this issue.

**Comment by mkArtakMSFT** [comment] 2020-04-13 16:59
This is now fixed.

**Closed by mkArtakMSFT** 2020-04-13 16:59 UTC
Labels: area-mvc, investigate
