### ISSUE TITLE
Blazor WASM 3.2 release lifecycle methods breakpoints not working

### ISSUE THREAD

**Issue by kirill-zhukov** [dotnet/aspnetcore#22198] opened 2020-05-25 16:42 UTC
### Describe the bug
Debug session is not paused on breakpoints that are set inside lifecycle methods like:
protected override void OnInitialized()
protected override void OnAfterRender(bool firstRender)
and others including async methods

### To Reproduce
create the following method in any .razor component or its cs partial code behind:
``` C#
protected override void OnInitialized()
 {
//Set a break point at the following line:
     Console.Out.WriteLine("Initialized");
 }
```
Breakpoint will be set but the debug session will not be paused at line with the console output.
And if you open dev tools console you will see that the "Initialized" text has been printed. Means code is executed but not paused at breakpoint.

### Further technical details
- ASP.NET Core version 3.1.4 ?
- Include the output of `dotnet --info`
dotnet --info
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studion 2019 Community 16.6

**Comment by snerks** [comment] 2020-05-25 18:36
In my experience, it takes a relatively long time for the debugger to attach.

Have you tried the following?:

1. Launch the application under Debug
1. Wait for (approximately) 10 seconds
1. While waiting, watch the Visual Studio breakpoints, until they switch to red blobs
1. Switch from/to the Route/Component being debugged

I found that, at this point, breakpoints work as expected.

**Comment by kirill-zhukov** [comment] 2020-05-25 19:02
Indeed routing from the route and back worked. However it doesn't work when refresh is done with F5 that was what I've been trying when I saw red blobs are set. Thank you for help! Not sure still if this is an expected behavior, I think correct would be to wait for debugging session initialized and only start components initialization after this. Am I wrong?

**Comment by mkArtakMSFT** [comment] 2020-05-26 17:06
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/22212

**Closed by mkArtakMSFT** 2020-05-26 17:06 UTC
Labels: area-blazor, blazor-wasm
