### ISSUE TITLE
Warning when increasing IHttpMaxRequestBodySizeFeature.MaxRequestBodySize despite all IIS limits increased

### ISSUE THREAD

**Issue by cmeeren** [dotnet/aspnetcore#24555] opened 2020-08-04 07:56 UTC
I have an ASP.NET Core 3.1 web API running on IIS on-prem (IIS 10 on Windows Server 2016). In an operation, I set `IHttpMaxRequestBodySizeFeature.MaxRequestBodySize` to `262144000`. I have used the IIS Configuration Editor to
* modify `ApplicationHost.config` for my site by setting `system.webServer/security/requestFiltering/requestLimits/maxAllowedContentLength` to `4294967295`
  [![enter image description here][1]][1]
* modify `ApplicationHost.config` for my site by setting `system.webServer/serverRuntime/maxRequestEntityAllowed` to `4294967295`
  [![enter image description here][2]][2]
* modify `Root Web.config` for my site by setting `system.web/httpRuntime/maxRequestLength` to `2147483647`
  [![enter image description here][3]][3]

Those are the values I also see when I choose `Web.config` in the IIS Configuration Editor.

The site is behind another IIS site acting as a reverse proxy. I have made the same changes there.

I am able to upload files larger than the default ~30MB limit, but I consistently get the following warning whenever I set `IHttpMaxRequestBodySizeFeature.MaxRequestBodySize`:

   > Increasing the MaxRequestBodySize conflicts with the max value for IIS limit maxAllowedContentLength. HTTP requests that have a content-length greater than maxAllowedContentLength will still be rejected by IIS. You can disable the limit by either removing or setting the maxAllowedContentLength value to a higher limit.

I have even looked at the ASP.NET source code to verify that the warning only prints if you're trying to set the limit higher than the IIS settings:

https://github.com/dotnet/aspnetcore/blob/214df1c8ef0cce27b04fcc43d7df48b29964dee1/src/Servers/IIS/IIS/src/Core/IISHttpServer.cs#L85-L88

https://github.com/dotnet/aspnetcore/blob/df712cc4a97d0bc8d573979008a5a2cc381f8117/src/Servers/IIS/IIS/src/Core/IISHttpContext.FeatureCollection.cs#L370-L373

Am I doing anything wrong, or is this a bug in ASP.NET Core?

Please let me know if I can provide more information.

If it's relevant, I am publishing to IIS using Azure Pipelines. My repo does not contain a `web.config`, but for good measure I tried with the following `web.config` without luck:

    <configuration>
      <system.web>
        <httpRuntime maxRequestLength="2147483647" />
      </system.web>
      <system.webServer>
        <security>
          <requestFiltering>
            <requestLimits maxAllowedContentLength="4294967295" />
          </requestFiltering>
        </security>
      </system.webServer>
    </configuration>

  [1]: https://i.stack.imgur.com/6rMeM.png
  [2]: https://i.stack.imgur.com/1ytMu.png
  [3]: https://i.stack.imgur.com/Ow0iU.png

**Comment by davidfowl** [comment] 2020-08-04 08:10
The system.Web section is irrelevant in ASP.NET Core.

cc @jkotalik

**Comment by BrennanConroy** [comment] 2020-08-05 20:18
Dupe of https://github.com/dotnet/aspnetcore/issues/22834

**Comment by cmeeren** [comment] 2020-08-06 05:47
How? Are you saying that if `maxAllowedContentLength` is set to anything above `2147483647` then it's set to some default low value instead of `2147483647`, and that causes the warning?

**Comment by BrennanConroy** [comment] 2020-08-06 16:15
Whoops wrong issue, I believe https://github.com/dotnet/aspnetcore/issues/22950 is the correct one.

**Comment by cmeeren** [comment] 2020-08-06 20:39
Ah, great. It looks like a duplicate of that one, which also contains a workaround. Closing this.

**Comment by cmeeren** [comment] 2020-08-06 20:41
Wait a minute, I am already setting `IISServerOptions.MaxRequestBodySize` to `Int64.MaxValue`, but I still get the warning. What gives?

**Comment by BrennanConroy** [comment] 2020-08-07 21:10
Use `Int32.MaxValue` if you want to get rid of the warning.

**Comment by cmeeren** [comment] 2020-08-10 05:52
I just tried that, but I still get the warning. Do I need to use that value in web.config too?

**Comment by BrennanConroy** [comment] 2020-08-10 21:11
Part of https://github.com/dotnet/aspnetcore/issues/22950 work

**Comment by BrennanConroy** [comment] 2020-08-26 20:20
Fixed via https://github.com/dotnet/aspnetcore/pull/25096

**Closed by BrennanConroy** 2020-08-26 20:20 UTC
Labels: area-servers
