### ISSUE TITLE
Blazor attribute splatting : @bind-value

### ISSUE THREAD

**Issue by sroy2020** [dotnet/aspnetcore#26327] opened 2020-09-25 15:08 UTC
Hi,

### Describe the bug

I'm trying to do attribute splatting for @bind-value, unfortunately I can't do it. What am I doing wrong?

FYI, even though .Net 5.0 is available it is still based on ASP.Net Core 3.2.

### To Reproduce
Using a line like

`ReferenceAttributes.Add("@bind-value", "Model.ReferenceFile.Id");`

I get the following exception:

### Exceptions (if any)
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to execute 'setAttribute' on 'Element': '@bind-value' is not a valid attribute name.
      Error: Failed to execute 'setAttribute' on 'Element': '@bind-value' is not a valid attribute name.
          at e.applyAttribute (http://localhost:55555/_framework/blazor.webassembly.js:1:17233)
          at e.insertElement (http://localhost:55555/_framework/blazor.webassembly.js:1:16301)
          at e.insertFrame (http://localhost:55555/_framework/blazor.webassembly.js:1:15178)
          at e.insertFrameRange (http://localhost:55555/_framework/blazor.webassembly.js:1:19092)
          at e.insertElement (http://localhost:55555/_framework/blazor.webassembly.js:1:16258)
          at e.insertFrame (http://localhost:55555/_framework/blazor.webassembly.js:1:15178)
          at e.insertFrameRange (http://localhost:55555/_framework/blazor.webassembly.js:1:19092)
          at e.insertElement (http://localhost:55555/_framework/blazor.webassembly.js:1:16258)
          at e.insertFrame (http://localhost:55555/_framework/blazor.webassembly.js:1:15178)
          at e.insertFrameRange (http://localhost:55555/_framework/blazor.webassembly.js:1:19092)
```

### Further technical details
```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

![image](https://user-images.githubusercontent.com/61807678/94283199-b476ae80-ff1e-11ea-938f-a1d1998a507e.png)

Thanks

**Comment by mrpmorris** [comment] 2020-09-28 07:48
Any name starting with @ is not an attribute, it is a compiler directive to generate a special code pattern. That's why it won't work.

What are you trying to achieve?

**Comment by sroy2020** [comment] 2020-09-28 12:21
Thanks for the explanation.

Basically I was trying to find out a way to add dynamically @bind-value other than using an if/else in the Razor file. According to what you're saying I'll continue with the if/else.

Thanks again

**Comment by mrpmorris** [comment] 2020-09-28 13:29
If you want to discuss your requirements there are some clever people in here => https://gitter.im/aspnet/Blazor

**Comment by captainsafia** [comment] 2020-09-28 16:25
We don't currently support this feature but have placed it in the backlog to gauge interest in adding this.

**Comment by sroy2020** [comment] 2020-09-28 17:17
Thank you all

**Comment by SteveSandersonMS** [comment] 2020-10-07 10:23
Just realised this is a dupe of the more general issue https://github.com/dotnet/aspnetcore/issues/20560

**Closed by SteveSandersonMS** 2020-10-07 10:23 UTC
Labels: area-blazor, enhancement
