### ISSUE TITLE
@code directive missing colorization when adding .razor file to project

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22742] opened 2020-06-09 23:20 UTC
Repro steps:

- Create a new Blazor WebAssembly app
- Right-click on the Pages folder, Add > Razor Component
- Name the file *Test.razor*

Expected result:

- *Test.razor* is created and opened with correct colorization

Actual result:

- `@code` block and other Razor directives is missing colorization and completions

![image](https://user-images.githubusercontent.com/1874516/84210242-0f1df480-aa6d-11ea-8e69-ae392d36772f.png)

![image](https://user-images.githubusercontent.com/1874516/84210486-b13ddc80-aa6d-11ea-8c31-bd00c7ac3ce1.png)

Workaround:

- Close and reopen *Test.razor* to get colorization to kick in

![image](https://user-images.githubusercontent.com/1874516/84210274-20ff9780-aa6d-11ea-91ee-9b3cec73d93e.png)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by NTaylorMullen** [comment] 2020-06-11 23:41
Duplicate of https://github.com/dotnet/aspnetcore/issues/22594

**Closed by NTaylorMullen** 2020-06-11 23:41 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, bug
