### ISSUE TITLE
Support specifying a full certificate chain in HttpsConnectionAdapterOptions

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#21513] opened 2020-05-05 20:44 UTC
```diff
public class HttpsConnectionAdapterOptions
{
    public X509Certificate2 ServerCertificate { get; set; }
+   public X509Certificate2Collection ServerCertificateChain { get; set; }
}
```

Configuration: 

For configuration, we'll support the full cert chain in Path:

```diff
// "CertificateName": {
     //     "Path": "testCert.pem/pfx",
     //     "KeyPath": "key.pem",
```

This depends on https://github.com/dotnet/runtime/issues/35844

**Comment by Pilchie** [comment] 2020-09-02 18:32
Moving this to RC2, since the PR isn't ready yet, and we're out of time for RC1

**Comment by davidfowl** [comment] 2021-03-23 13:23
Closed PR https://github.com/dotnet/aspnetcore/pull/24935 (lack of tests)

**Comment by mkArtakMSFT** [comment] 2021-03-29 18:03
@davidfowl it'll be handier to review the PR. So not reviewing this yet.

**Comment by junsaw** [comment] 2021-04-16 23:42
Is this issue closed ? I am currently blocked.

**Comment by davidfowl** [comment] 2021-04-17 01:03
No the issue isn't closed. If you want to take a stab at this, you can revive this PR https://github.com/dotnet/aspnetcore/pull/24935 and write a test. We need to generate a valid certificate chain (@blowdart do you still have one)?

**Comment by blowdart** [comment] 2021-04-17 01:04
Hah no. I emailed you the instructions at one point. Not sure where they are now to be honest.

**Comment by davidfowl** [comment] 2021-04-17 01:10
Did you do it purely with an openssl configuration?

**Comment by jstachowiak** [comment] 2021-05-19 14:51
Love it! This will simplify a lot our use case where we generate dynamic certificates at schedule time with Vault and have a few intermediates in the bundle that need to be sent over as well.

**Comment by jstachowiak** [comment] 2021-05-19 19:46
@davidfowl, if having a test CA chain is a blocker then you can easily generate one with the help of HashiCorp Vault API. Just follow the steps from [here](https://www.vaultproject.io/docs/secrets/pki) and assume that:
- Root CA is setup at `pki/`
- Intermediate CA is setup at `pki_int/`

You can have as many intermediates as you want.

**Comment by davidfowl** [comment] 2021-09-07 14:48
Given https://github.com/dotnet/aspnetcore/issues/36202 issue I don't think we should add a chain field anymore. I think we should just support both a full chain like most other platforms. I updated the proposal to suit:

Workaround for .NET 6:

```C#
public static class TlsListenOptionsExtensions
{
    public static ListenOptions UseHttpsWithFullChain(this ListenOptions listenOptions, string certPath, string keyPath, string? password = null)
    {
        ArgumentNullException.ThrowIfNull(certPath);
        ArgumentNullException.ThrowIfNull(keyPath);

        var env = listenOptions.ApplicationServices.GetRequiredService<IWebHostEnvironment>();

        var fullCertPath = Path.Combine(env.ContentRootPath, certPath);
        var fullkeyPath = Path.Combine(env.ContentRootPath, keyPath);

        var leafCertWithKey = password switch
        {
            null => X509Certificate2.CreateFromPemFile(fullCertPath, fullkeyPath),
            _ => X509Certificate2.CreateFromEncryptedPemFile(fullkeyPath, password.AsSpan(), fullkeyPath)
        };

        // Import the full cert chain
        var fullChain = new X509Certificate2Collection();
        fullChain.ImportFromPemFile(certPath);

        // Skip the leaf cert
        var chain = new X509Certificate2Collection(fullChain.Skip(1).ToArray());

        var options = new SslServerAuthenticationOptions
        {
            // Don't go online to retrieve cert chain
            ServerCertificateContext = SslStreamCertificateContext.Create(leafCertWithKey, chain, offline: true)
        };

        return listenOptions.UseHttps(new TlsHandshakeCallbackOptions
        {
            OnConnection = context => new(options)
        });
    }
}
```

**Comment by davidfowl** [comment] 2021-09-07 14:55
BTW this utility https://github.com/dotnet/aspnetcore/issues/36202#issuecomment-914050621 looks super useful for testing.

**Comment by MarkCiliaVincenti** [comment] 2021-11-04 08:28
Thanks for that code @davidfowl. I used Certbot to create the files from Let's Encrypt and passed on the fullchain.pem as certPath (not sure if this is what you meant, because the cert.pem wasn't enough for Android) and the privkey.pem as the keyPath. That works, however when Certbot updates the keys we'd also want Kestrel to take note and 'refreshes'.

**Comment by MarkCiliaVincenti** [comment] 2021-11-04 08:46
Another thing... it seems this code is incompatible with HTTP/3.

**Comment by MarkCiliaVincenti** [comment] 2021-11-06 12:19
I got this working with Let's Encrypt (files created by Certbot) on .NET 6.0, fully valid SSL chain, compatible with HTTP/3 and allowing you to refresh the certificates from file without restarting the server.

````
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.AspNetCore.Server.Kestrel.Https;
using System;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;

namespace ListenOptionsExtensions
{
    public static class TlsCertificateLoader
    {
        private class SslCertificateCollection
        {
            public string FullChainPath { get; set; }
            public string PrivateKeyPath { get; set; }

            private X509Certificate2Collection _collection;

            internal X509Certificate2Collection X509Certificate2Collection
            {
                get { return _collection; }
                private set { _collection = value; }
            }

            internal X509Certificate2Collection GetX509Certificate2Collection()
            {
                var leaf = X509Certificate2.CreateFromPemFile(FullChainPath, PrivateKeyPath);
                var chain = new X509Certificate2Collection(leaf);
                chain.ImportFromPemFile(FullChainPath);
                return chain;
            }

            internal void RefreshX509Certificate2Collection()
            {
                X509Certificate2Collection = GetX509Certificate2Collection();
            }
        }

        private static SslCertificateCollection _sslCertificateDict = new();

        public static void RefreshX509Certificate2Collection()
        {
            _sslCertificateDict.RefreshX509Certificate2Collection();
        }

        public static X509Certificate2Collection X509Certificate2Collection()
        {
            return _sslCertificateDict.X509Certificate2Collection;
        }

        private static SslCertificateCollection Initialize(string fullChainPath, string privateKeyPath)
        {
            ArgumentNullException.ThrowIfNull(fullChainPath);
            ArgumentNullException.ThrowIfNull(privateKeyPath);

            if (_sslCertificateDict == null)
            {
                _sslCertificateDict = new SslCertificateCollection()
                {
                    FullChainPath = fullChainPath,
                    PrivateKeyPath = privateKeyPath
                };
                _sslCertificateDict.RefreshX509Certificate2Collection();
            }
            return _sslCertificateDict;
        }

        public static ListenOptions SetTlsHandshakeCallbackOptions(this ListenOptions listenOptions, string fullChainPath, string privateKeyPath)
        {
            var x509Certificate2Collection = Initialize(fullChainPath, privateKeyPath).X509Certificate2Collection;
            return listenOptions.UseHttps(new TlsHandshakeCallbackOptions
            {
                OnConnection = context => new(new SslServerAuthenticationOptions
                {
                    ServerCertificateContext = SslStreamCertificateContext.Create(x509Certificate2Collection[0], x509Certificate2Collection, offline: true)
                })
            });
        }

        public static ListenOptions SetHttpsConnectionAdapterOptions(this ListenOptions listenOptions, string fullChainPath, string privateKeyPath)
        {
            var x509Certificate2Collection = Initialize(fullChainPath, privateKeyPath).X509Certificate2Collection;

            return listenOptions.UseHttps(new HttpsConnectionAdapterOptions
            {
                ServerCertificateSelector = (context, dnsName) => new(x509Certificate2Collection[0])
            });
        }
    }
}
````

To use:
````
options.ListenAnyIp(433, o =>
{
     o.SetTlsHandshakeCallbackOptions(fullChainPath, privateKeyPath);
     o.SetHttpsConnectionAdapterOptions(fullChainPath, privateKeyPath);
     o.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
});
````

And to refresh (eg either on a Timer or watching a directory via PhysicalFileProvider):
````
TlsCertificateLoader.RefreshX509Certificate2Collection();
````

**Comment by MarkCiliaVincenti** [comment] 2021-11-06 12:25
^ might interest you @jack4it

**Comment by davidfowl** [comment] 2021-11-06 16:33
Why is it static? Why not just watch the files and update the collection referenced by the callback?

**Comment by MarkCiliaVincenti** [comment] 2021-11-06 16:50
> Why is it static? Why not just watch the files and update the collection referenced by the callback?

Isn't that what it's doing? It's static because it's an extension method, and from my tests I found out you can't load more than one certificate, eg you can't load mydomain.tld and www.mydomain.tld

**Comment by MarkCiliaVincenti** [comment] 2021-11-06 17:29
Added to NuGet.
https://www.nuget.org/packages/TlsCertificateLoader/1.0.0

**Comment by MarkCiliaVincenti** [comment] 2021-11-08 08:32
> Why is it static? Why not just watch the files and update the collection referenced by the callback?

Actually I realized the code is buggy. Refreshing is not working and I'm not really sure what needs to be done.
https://github.com/MarkCiliaVincenti/TlsCertificateLoader/blob/master/TlsCertificateLoader/TlsCertificateLoader.cs

**Comment by MarkCiliaVincenti** [comment] 2021-11-09 18:31
Completely rewritten the library, @davidfowl. It's not using static now. I am keeping an instance of TlsCertificateLoader in a property on a singleton, calling the 2 ListenOptions extension methods SetTlsHandshakeCallbackOptions and SetHttpsConnectionAdapterOptions and then using a PhysicalFileProvider to identify changes and call the TlsCertificateLoader's instance's RefreshCertificates method which updates the collection.

The problem is that Kestrel still outputs the certificates that were present when it started... it doesn't refresh them.

**Comment by Tratcher** [comment] 2021-11-09 18:35
There's one trick when testing this scenario: The client and server will use TLS session resumption by default, which keeps using the old cert. Only new sessions get new certs. We our tests use GUIDs for the SNI field to avoid this.

**Comment by MarkCiliaVincenti** [comment] 2021-11-09 18:46
> There's one trick when testing this scenario: The client and server will use TLS session resumption by default, which keeps using the old cert. Only new sessions get new certs. Our tests use GUIDs for the SNI field to avoid this.

I'm not sure what you mean. When I tested even with online SSL checkers, the old certificate got served. It can't (just) be related to TLS session resumption.

**Comment by Tratcher** [comment] 2021-11-09 18:55
Oh, I see your issue, you're capturing the X509Certificate2Collection once at startup. Your refresh logic creates a new collection, but that's not referenced by Kestrel.
https://github.com/MarkCiliaVincenti/TlsCertificateLoader/blob/fdaa2e39025e349e6ec9db783cf82bcfd76dcb74/TlsCertificateLoader/Extensions/ListenOptionsExtensions.cs#L24

You need to change the code here to directly access the TlsCertificateLoader inside the OnConnection callback so it can get a new collection when things change.
https://github.com/MarkCiliaVincenti/TlsCertificateLoader/blob/fdaa2e39025e349e6ec9db783cf82bcfd76dcb74/TlsCertificateLoader/Extensions/ListenOptionsExtensions.cs#L17

**Comment by MarkCiliaVincenti** [comment] 2021-11-09 19:17
@Tratcher, thanks so much! Fixed and released the NuGet package TlsCertificateLoader 1.0.4 with working refresh :)

**Comment by halter73** [comment] 2021-11-11 01:26
```C#
options.ListenAnyIp(433, o =>
{
     o.SetTlsHandshakeCallbackOptions(fullChainPath, privateKeyPath);
     o.SetHttpsConnectionAdapterOptions(fullChainPath, privateKeyPath);
     o.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
});
```

Only the first call to UseHttps() should have [any impact](https://github.com/dotnet/aspnetcore/blob/1111cb5bdf72ffa351da80fac8baed434de1e25a/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L137-L141). I don't think `o.SetHttpsConnectionAdapterOptions(fullChainPath, privateKeyPath);` does anything in the example.

I'd consider removing SetHttpsConnectionAdapterOptions. The TlsHandshakeCallbackOptions UseHttps() overload should be preferred wherever possible.

**Comment by MarkCiliaVincenti** [comment] 2021-11-11 06:35
> ```cs
> options.ListenAnyIp(433, o =>
> {
>      o.SetTlsHandshakeCallbackOptions(fullChainPath, privateKeyPath);
>      o.SetHttpsConnectionAdapterOptions(fullChainPath, privateKeyPath);
>      o.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
> });
> ```
> 
> Only the first call to UseHttps() should have [any impact](https://github.com/dotnet/aspnetcore/blob/1111cb5bdf72ffa351da80fac8baed434de1e25a/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L137-L141). I don't think `o.SetHttpsConnectionAdapterOptions(fullChainPath, privateKeyPath);` does anything in the example.
> 
> I'd consider removing SetHttpsConnectionAdapterOptions. The TlsHandshakeCallbackOptions UseHttps() overload should be preferred wherever possible.

With all due respect, this is incorrect. It didn't work on 6.0rc2 and I thought maybe you're right let me check it out on 6.0 on my app and tried disabling it. The site wouldn't load and was giving a ERR_QUIC_PROTOCOL_ERROR. You absolutely need both lines if you want to use HTTP/3, at least on my environment (Ubuntu). Haven't tested on Windows.

**Comment by Tratcher** [comment] 2021-11-11 17:08
Yeah, HTTP/3 is a special case because some of the callbacks don't work yet.

> The only thing you can't do, and I'm not convinced is possible by Kestrel, is to load multiple certificates and serve the appropriate one depending on the hostname. For example serving a certificate for mydomain.tld and a different one for www.mydomain.tld or myotherdomain.tld. HttpsConnectionAdapterOptions allows you that flexibility but TlsHandshakeCallbackOptions doesn't seem like it does, and you absolutely need the latter because the former doesn't allow the full chain anyway.

This is possible. The TlsHandshakeCallbackOptions.OnConnection callback gives you a TlsHandshakeCallbackContext. That has the SslClientHelloInfo on it with the ServerName.

**Comment by MarkCiliaVincenti** [comment] 2021-11-11 17:10
But how would you go about putting logic there so it picks up the
appropriate certificate collection from a dictionary?

**Comment by Tratcher** [comment] 2021-11-11 17:18
That dictionary lookup goes here:
https://github.com/MarkCiliaVincenti/TlsCertificateLoader/blob/6f1b4ff27c320fa14ec990b2408b367d81f2553d/TlsCertificateLoader/Extensions/ListenOptionsExtensions.cs#L25

**Comment by MarkCiliaVincenti** [comment] 2021-11-27 11:43
I've made some big changes to TlsCertificateLoader. I've now added middleware for Certbot certificates.

https://github.com/MarkCiliaVincenti/TlsCertificateLoader
https://www.nuget.org/packages/TlsCertificateLoader

**Comment by davidfowl** [comment] 2021-11-27 15:24
Why is it 2 method cals?

**Comment by MarkCiliaVincenti** [comment] 2021-11-27 15:35
What do you mean?

**Comment by davidfowl** [comment] 2021-11-28 00:33
These 3 calls. It's not clear to me which calls are required. I see AddTlsCertificateLoader, UseTlsCertificateLoader, and the middleware (UseTlsCertificateLoader). The middleware doesn't seem like something usable in an existing application (https://github.com/MarkCiliaVincenti/TlsCertificateLoader/blob/377ff452f1bbf1d835a233534be4a4286f6d7248/TlsCertificateLoader/Extensions/TlsCertificateLoaderMiddlewareExtensions.cs#L107-L146), it kinda assumes it can add these middlewares to an existing pipeline without consequence.

https://github.com/MarkCiliaVincenti/TlsCertificateLoader/blob/e5f4fc31f1f29b3c5bf084aa04a0736cbc78b69d/Samples/CertbotSampleUsingMiddleware/Program.cs#L8-L10

**Comment by MarkCiliaVincenti** [comment] 2021-11-28 07:00
I understand what you mean and later I will make the library more flexible
because currently it does the following:

- enable HSTS (only this is configurable)
- enable static files (needed to use with Certbot webroot)
- redirect HTTP traffic to HTTPS
- redirect www.mydomain.tld traffic to mydomain.tld (definitely next in
line to be configurable)

Of course, one can also do without the middleware as per the other sample
and have more control. The most important thing is that this is the only
library I found that allows you to use HTTP/3 with Kestrel on Ubuntu with
fully valid SSL.

**Closed** 2022-08-14 04:53 UTC
Labels: enhancement, area-runtime, api-approved, affected-very-few
