### ISSUE TITLE
PathString.FromUriComponent encoding forward slash makes no difference

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2696] opened 2018-01-02 02:47 UTC
_From @Tratcher on Wednesday, August 2, 2017 7:08:13 AM_

_From @PawelTroka on August 2, 2017 10:17_

It was already shortly discussed in https://github.com/aspnet/Mvc/issues/2826 where @davidfowl suggested that the issue I am encountering is only happening on TestHost. And yes, he is right - it works correctly when hosted and invoked through web browser or any web client for that matter. 

It is failing however in my integration tests where I am using Microsoft.AspNetCore.TestHost v1.1.2 and Microsoft.AspNetCore.WebUtilities v1.1.2. Please notice that my WebApi and WebApi.IntegrationTests are AspNetCore 1.1 but are targeting net461 (due to some of my libraries not yet ported).

Repro:
Unit test:
https://github.com/PawelTroka/Computator.NET/blob/master/Computator.NET.WebApi.IntegrationTests/CalculateApiTests.cs#L49
Should go through route:
real/{equation}/{x} from method:
https://github.com/PawelTroka/Computator.NET/blob/master/Computator.NET.WebApi/Controllers/CalculateController.cs#L32
But because encoding forward slash makes no difference it is going through different route:
real/{equation}/{x}/{customFunctionsCode} from the same method

In images:
When run through browser everything is ok:
![image](https://user-images.githubusercontent.com/11928766/28869021-a7dc70ac-777b-11e7-914a-cda7eddf54f4.png)
![image](https://user-images.githubusercontent.com/11928766/28868995-934b15a8-777b-11e7-9b47-5edbfea9680a.png)

But when run on TestHost, encoding forward slash really makes no difference:
![image](https://user-images.githubusercontent.com/11928766/28869103-f6594174-777b-11e7-857d-61a99ac2d914.png)

_Copied from original issue: aspnet/Hosting#1155_

_Copied from original issue: aspnet/HttpAbstractions#912_

**Comment by aspnet-hello** [comment] 2018-01-02 02:47
_From @Tratcher on Wednesday, August 2, 2017 7:08:14 AM_

Here's the code causing the un-escaping:
https://github.com/aspnet/Hosting/blob/44272ca2ba7082dd31c3de0ef9d5b5a400db1b78/src/Microsoft.AspNetCore.TestHost/ClientHandler.cs#L140
https://github.com/aspnet/HttpAbstractions/blob/057fc816fab1062700959cdaad2a32e9d85efca6/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs#L191
I'll move this bug over to HttpAbstrations. There should be a better way to unescape everything but %2F.

**Comment by aspnet-hello** [comment] 2018-01-02 02:47
_From @muratg on Monday, October 30, 2017 10:39:13 AM_

Backlogging this issue.

**Comment by aspnet-hello** [comment] 2018-01-02 02:47
_From @PawelTroka on Sunday, November 12, 2017 3:42:58 AM_

I'm about to change code a bit, so please use permalinks instead:
https://github.com/PawelTroka/Computator.NET/blob/c1061e722f366c59fa2cfa5047dcccba6a8267df/Computator.NET.WebApi.IntegrationTests/CalculateApiTests.cs#L49
https://github.com/PawelTroka/Computator.NET/blob/c1061e722f366c59fa2cfa5047dcccba6a8267df/Computator.NET.WebApi/Controllers/CalculateController.cs#L32

**Comment by linuxchata** [comment] 2018-06-12 07:16
This issue is still reproducible with Microsoft.AspNetCore.TestHost v2.1.0. Any updates on this issue? Any workarounds available? When is it planned to have the fix delivered for this issue?

**Comment by davidfowl** [comment] 2021-03-28 18:10
Marked up for grabs

**Comment by Tratcher** [comment] 2021-03-28 19:48
Duplicate of #2686

**Closed by Tratcher** 2021-03-28 19:48 UTC
Labels: affected-few, area-servers, bug, feature-HttpAbstractions, help wanted, severity-minor
