### ISSUE TITLE
KeepAliveInterval doesn't work as expected on Kestrel

### ISSUE THREAD

**Issue by onetsmr** [dotnet/aspnetcore#17201] opened 2019-11-18 18:18 UTC
Move my comment into the new issue from https://github.com/aspnet/AspNetCore/issues/2464

So, I have a asp.net core web api server with sockets. It is based on https://radu-matei.com/blog/aspnet-core-websockets-middleware

``` C#
app.UseWebSockets(new WebSocketOptions
{
    KeepAliveInterval = TimeSpan.FromSeconds(10)
});
```

I process web socket requests in the controller

``` C#
[HttpGet]
[Route("connect")]
public async Task Connect()
{
   if (HttpContext.WebSockets.IsWebSocketRequest == false)
      throw new BadRequestException();

   var socket = await HttpContext.WebSockets.AcceptWebSocketAsync();
   await _webSocketHandler.OnConnected(socket);

   await Receive(socket, async (result, buffer) =>
   {
      if (result.MessageType == WebSocketMessageType.Close)
      {
         await _webSocketHandler.OnDisconnected(socket);
      }
      else
      {
         await _webSocketHandler.ReceiveAsync(socket, result, buffer);
      }
   });
}

private async Task Receive(WebSocket socket, Action<WebSocketReceiveResult, byte[]> handleMessage)
{
   try
   {
      var buffer = new byte[1024 * 4];

      while (socket.State == WebSocketState.Open)
      {
         var result = await socket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);

         handleMessage(result, buffer);
      }
   }
   catch (Exception exception)
   {
      Log.Debug(exception, $"On Receive Exception: {exception.Message}");

      try
      {
         await _webSocketHandler.OnDisconnected(socket);
      }
      catch (Exception innerException)
      {
         Log.Debug(innerException, $"On Receive Inner Exception: {innerException.Message}");
      }
   }
}
```

My test:
1. I set KeepAliveInterval=10 seconds on the server
2. Then I set break point in the client code
3. Then run and I see "ping" messages from server every 10 sec in the client code debugger. Client sends "pong" message in reply each time.
4. Then I terminate internet connection on the client, but the server does not know that the client has fallen off either after 10-20 seconds or after a minute.

I see in the documentation that I should send ping/pong (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.0#handle-client-disconnects). But KeepAlive is the ping/pong. So I expected:
1. Server should send "ping"
2. Server should wait "KeepAliveInterval" x2 seconds 
3. And if it doesn't receive "pong" from the client - terminate connection and set aborted (?) state for the socket.

But it doesn't work like that. No exception, no aborted state, nothing...

I researched the code https://github.com/aspnet/WebSockets/blob/c65e8681c4a50fc33c263d1f42dfcf007cb5c035/src/Microsoft.AspNetCore.WebSockets/Internal/fx/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ManagedWebSocket.cs

So:
1. It has not a way to handle ping/pong messages in my code at a higher level. It has loop back to while (true) here https://github.com/aspnet/WebSockets/blob/c65e8681c4a50fc33c263d1f42dfcf007cb5c035/src/Microsoft.AspNetCore.WebSockets/Internal/fx/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ManagedWebSocket.cs#L647. So I can handle only text/binary messages.
2. keepAliveInterval is used only for running timer, but not for the waiting pong message

ASP.NET Core version is 2.2
System.Net.WebSockets version is 4.1.1.0

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by halter73** [comment] 2019-11-19 00:19
@onetsmr I notice you include "on Kestrel" in the title of the issue? Have you happened to try and see if the KeepAliveInterval works with other servers (e.g. HttpSys, IIS in-proc)?

**Comment by halter73** [comment] 2019-11-19 00:30
I'm pretty sure this is by design. So I expect the behavior is the same on all servers.

In the meantime, if you want to timeout clients more quickly, I recommend doing what https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.0#handle-client-disconnects suggests. By my reading, that doc isn't trying to say that the server will timeout the connection if the client doesn't send a ping within 2x the timeout. That doc is recommending developers do that themselves at the app layer with regular WebSocket messages.

**Comment by onetsmr** [comment] 2019-11-19 14:36
@halter73 
> Have you happened to try and see if the KeepAliveInterval works with other servers (e.g. HttpSys, IIS in-proc)?

No, I've tested only on kestrel.

> That doc is recommending developers do that themselves at the app layer with regular WebSocket messages.

So that means double work and looks like a crutch. Server sends system ping messages and I will send custom ping mssages. Nay, I can't use ping/pong opcodes, because WebSocketMessageType enum doesn't contain them.

**Comment by anurse** [comment] 2019-11-20 22:20
Generally, both the client and server WebSocket implementations have not used the keep-alive feature to detect disconnected clients. It's just to keep proxies from terminating the connection (and has _some_ benefit in detecting disconnection because OSes usually don't manifest a disconnection until the app reads or writes on the socket).

> Nay, I can't use ping/pong opcodes, because WebSocketMessageType enum doesn't contain them.

This is also a reason why ASP.NET Core can't really do this, since the `WebSocket` API in .NET Core doesn't expose them.

I'd suggest moving this discussion to an issue on dotnet/corefx.

**Closed** 2020-11-12 02:05 UTC
Labels: area-servers
