### ISSUE TITLE
User isn't logged in after registering a new user in a Blazor Web App with Identity

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#51179] opened 2023-10-06 04:14 UTC
Repro steps:
- Install .NET 8 RC2
- Create a new Blazor Web App, Individual user accounts, server interactivity mode enabled locally
- Run migrations from the command line (see #51178)
- Run the app
- Register a new user
- Click on email confirmation link
- Navigate to the Auth Required page

Expected result: The user is logged in after completing registration and navigation to Auth Required page is successful
Actual result: Navigating to the Auth Required page redirects to the login page
Workaround: Login with the registered user

**Comment by danroth27** [comment] 2023-10-09 16:19
It looks like the Razor Pages default identity UI also has this behavior.

**Comment by mkArtakMSFT** [comment] 2023-10-09 16:52
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

**Closed by mkArtakMSFT** 2023-10-09 16:52 UTC
Labels: area-blazor, feature-identity-ui
