### ISSUE TITLE
Node.js processes don't quit after stopping debugging

### ISSUE THREAD

**Issue by chesteryang** [dotnet/aspnetcore#5204] opened 2018-06-25 22:21 UTC
Please refer to https://github.com/OmniSharp/omnisharp-vscode/issues/2387 for details.

If there has been a fix, let me know how.

**Comment by pakrym** [comment] 2019-01-23 18:36
You can use job objects. We do this for IIS Express tests  (https://github.com/aspnet/AspNetCore/blob/3477daf3c4f530dff80f197e0642cb39a26fb07b/src/Servers/IIS/IntegrationTesting.IIS/src/ProcessTracker.cs)

**Comment by loop-evgeny** [comment] 2019-03-13 11:20
This happens for me in VS 2017 Pro 15.9.9 and VS 2019 Preview 4.2. When I start an ASP.NET Core 2.1 or 2.2 React app from VS (with debugging) and stop debugging the node.ex processes remain. If I run outside of VS using `dotnet run` and kill that with Control+C the node.exe processes exit.

**Comment by ChristopherHaws** [comment] 2019-10-01 17:17
This also occures when running in IIS Express without debugging and changing C# code so the process restarts automatically. I find myself going into task manager multiple times per day and cleaning up 10s of orphaned processes.

**Comment by astashko** [comment] 2019-11-25 12:23
It seems like Search Results Microsoft.AspNetCore.SpaServices.Extensions doesn't specify parent process id:
https://github.com/aspnet/AspNetCore/blob/9e67b7b22e92f3f4550d0efc2737d072405f0190/src/Middleware/SpaServices.Extensions/src/Npm/NodeScriptRunner.cs#L56
Is it planned to be resolved?

**Comment by Patrick-Ullrich** [comment] 2019-12-13 21:00
Can confirm, having this issue with:
DotNetCore v3.1.100
Visual Studio 2019 v.16.4.0

`                if (env.EnvironmentName == "Development")
                {
                    spa.UseReactDevelopmentServer(npmScript: "start");
                }
`

**Comment by grbd** [comment] 2020-01-14 22:36
I ran across this bug recently after looking at the below announcement
since UseWebpackDevMiddleware is going away
  * https://github.com/dotnet/aspnetcore/issues/12890

## Testing

after a bit of testing it looks like this cropped up sometime between version 2.2 and 3.0

  * .net core 2.1 / extensions - 2.1.1 okay
  * .net core 2.2 / extensions - 2.2.0 okay
  * .net core 3.0 / extensions - 3.0.0 broken
  * .net core 3.1 / extensions - 3.1.0 broken

Something about the way it's opening the process is leaving the process open after the debug session closes / visual studio quits.

For testing I found a repo online that was already setup to use UseReactDevelopmentServer
This works / doesn't leave anything behind in memory by default since it's targeting .net core 2.1
```
git clone https://github.com/ElHavas666/test-fianl.git
cd test-fianl
npm install
```

## webpack / vue equivilent

I've been looking at creating a webpack equivalent since that's what I'm interested in but it looks like the webpack dev server has the same issue if I copy / paste the code from

  * https://github.com/dotnet/aspnetcore/tree/master/src/Middleware/SpaServices.Extensions/src/ReactDevelopmentServer

There's also been one or two Vue dev server implementations floating around on the web that have run into the same problem.

## Cause

I'm not sure of the cause but there's some suggestion that running stuff via "npm start" might not be such as good idea if it's not passing on SIGKILL, SIGTERM and SIGINT

  * https://github.com/npm/npm/issues/4603
  * https://lisk.io/blog/tutorial/why-we-stopped-using-npm-start-child-processes

another approach might be to use npx instead to launch the dev server which might be more direct / better so I'll be trying that next in my own implementation for webpack.

These are some other links I came across the top one lists a possible better way which involves proxying via the dev server first then the asp .net host second, although I haven't looked into that yet.

  * https://www.dotnetcurry.com/aspnet-core/1500/aspnet-core-vuejs-template
  * https://blogs.taiga.nl/martijn/2019/10/11/goodbye-spaservices-it-was-fun-while-it-lasted/
  * https://github.com/martijnboland/LeanAspNetCore-React/commit/52c2fa0f00bc23a7507ee077d5fa88f0325b9686
  * https://www.c-sharpcorner.com/article/getting-started-with-vue-js-and-net-core-32/

**Comment by grbd** [comment] 2020-01-15 01:51
hmm so I just ruled out npm as the issue
launching the following within NodeScriptRunner
```
cmd /c echo hello
```
leaves nothing open after quitting as that's not a loop / terminates by iteself
launching this which is a simple ping on an infinite loop
```
cmd /c ping -t 127.0.0.1
```
keeps the cmd open after stopping debugging / quitting studio so same issue / never terminates
also tried adding in
```
AppDomain.CurrentDomain.DomainUnload += (s, e) => { process.Kill(true); process.WaitForExit(); };
AppDomain.CurrentDomain.ProcessExit += (s, e) => { process.Kill(true); process.WaitForExit(); };
AppDomain.CurrentDomain.UnhandledException += (s, e) => { process.Kill(true); process.WaitForExit(); };
```
but that didn't do anything / stop it so it must be further up

**Comment by mkArtakMSFT** [comment] 2020-01-29 19:26
Related https://github.com/dotnet/aspnetcore/issues/11597

**Comment by superlazycoder** [comment] 2020-01-30 23:31
Annoying......

I created a bat file

kill-node.bat
`taskkill /f /im node.exe`

and added a postbuild event

`call kill-node.bat`

set to run post build event "Always"

Ill be left with a lingering node between builds, but a pretty good middle ground.

**Comment by ryanbrandenburg** [comment] 2020-01-30 23:52
This was resolved with https://github.com/dotnet/aspnetcore/issues/11597.

**Closed by ryanbrandenburg** 2020-01-30 23:52 UTC
Labels: area-mvc, bug, feature-spa

**Comment by grbd** [comment] 2020-02-01 23:42
I'm not sure if this has fixed it, I tried copying the contents of 

```
Npm/
Util/
ReactDevelopmentServer/
```

https://github.com/dotnet/aspnetcore/tree/master/src/Middleware/SpaServices.Extensions/src

into my own class library to see if the applicationStoppingToken stuff which had been added in was working
but it seems to have the same problem when testing against the default react template with stuff being left open in the background
Maybe this has been tested against newer VStudio code or updated code in other libs, so will need to wait for it to be released officially to see

**Comment by grbd** [comment] 2020-02-02 00:47
Update it looks like this does work as long as you don't use IISExpress while debugging
with IISExpress selected I think it runs into this old problem
https://github.com/aspnet/AspNetCoreModule/issues/38

Avoiding IISExpress shouldn't be an issue so cool beans

**Comment by drdamour** [comment] 2020-02-05 08:35
@ryanbrandenburg  any chance this makes it into a 3.x release?

**Comment by mkArtakMSFT** [comment] 2020-02-10 06:30
> 
> 
> @ryanbrandenburg any chance this makes it into a 3.x release?

@drdamour we won't be patching 3.x for this.
