### ISSUE TITLE
IIS AspNetCore Module V2 returns 10s of 503 error and "Failed to gracefully shutdown applicaiton" warning when recycling a Hello world demo

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [dotnet/aspnetcore#49350] opened 2023-07-12 02:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1.There is a demo adding a simple function manageloop() in a helloworld.cs. 
2.When using .net framework 4.7.2, everything is good.
3.When using .net core 6, it returns around 10s of 503 error and "Failed to gracefully shutdown applicaiton" warning when recycling.

### Expected Behavior

The asp.net core 6 app should shut down gracefully and returns 200.

### Steps To Reproduce

I have the demo running in my lab. 
1.Publish the web app demo to IIS.
2.keep sending Get requests to the IIS site.
3.Recycle the appilcation pool.

Then 503 is got in the postman which sends reuqests. "Failed to gracefully shutdown applicaiton" shows in the event viewer log.

### Exceptions (if any)

No exception.

### .NET Version

I target it to .NET 6. I have .NET 7.0.203 as the runtime

### Anything else?

This is the event viewer warning.
![image](https://github.com/dotnet/aspnetcore/assets/45751478/de64fa46-d72f-4466-9b95-d143de0e211e)

This is the 503 returned by postman
![image](https://github.com/dotnet/aspnetcore/assets/45751478/2bec4d4c-d5e0-43f2-94db-550e97041e32)

This is the freb of 503, which indicates the 503 is returned from IIS
![image](https://github.com/dotnet/aspnetcore/assets/45751478/3fddada5-0e94-41b2-a9d8-c62ef5a7ba6a)

I have the demo and lab. Please contact me to demo it. If any further information is needed. Please let me know.

**Comment by AlexChongMicrosoft** [comment] 2023-07-12 02:26
Searched and found a similar report as https://github.com/dotnet/aspnetcore/issues/41340.

**Comment by AlexChongMicrosoft** [comment] 2023-07-13 01:20
@adityamandaleeka thanks a lot for your prompt reply. 

@BrennanConroy I have the demo and lab to show the issue. If you wish, we can have a discussion. Let me know if something I can do.

**Comment by AlexChongMicrosoft** [comment] 2023-07-14 01:38
@adityamandaleeka @BrennanConroy how are you? Look forward to your feedback. Please let me know if some informtion is needed.

**Comment by AlexChongMicrosoft** [comment] 2023-08-28 08:52
Thanks for your warm hands ASP.net core team. It has been confirmed a design of ASP.net core.

**Comment by cun-dp** [comment] 2023-08-28 11:38
> Thanks for your warm hands ASP.net core team. It has been confirmed a design of ASP.net core.

Hi Alex,

I'm coming from #41340. Does that mean that this is an **intended** design of ASP.net core? 
Will there be any fix for this issue? Or will overlapped apppool recycle never be supported by ASP.net core on IIS?

Thanks and best regards

**Comment by BrennanConroy** [comment] 2024-01-03 22:55
This looks like a dupe of https://github.com/dotnet/aspnetcore/issues/41340, closing.

**Closed by BrennanConroy** 2024-01-03 22:55 UTC
Labels: investigate, area-networking
