### ISSUE TITLE
Custom web API convention + nullable = exception

### ISSUE THREAD

**Issue by Leon99** [dotnet/aspnetcore#17761] opened 2019-12-11 04:12 UTC
When a custom web API convention is placed in a project with nullable enabled, this exception is thrown on startup:
```
System.ArgumentException: 'Method MyApiConventions.Get is decorated with the following attributes that are not allowed on an API convention method:
System.Runtime.CompilerServices.NullableContextAttribute
The following attributes are allowed on API convention methods: ProducesResponseTypeAttribute, ProducesDefaultResponseTypeAttribute, ApiConventionNameMatchAttribute. (Parameter 'conventionType')'
```
Wrapping ApiConventions inside _#nullable disable/restore_ fixes it, but the error is clearly unexpected and requires knowledge about underlying implementation details of nullable to apply the workaround.

**Comment by javiercn** [comment] 2019-12-11 11:27
@Leon99 thanks for contacting us.

@pranavkm this sounds like a bug on the analyzer, doesn't it?

**Comment by git-fudge** [comment] 2023-05-12 09:48
I was able to reproduce this bug but there was a strange behavior. This bug is only occurring if my custom web API convention has only one method.

**Comment by danielcrabtree** [comment] 2023-07-09 01:58
I also ran into this bug and can confirm wrapping it in #nullable disable/restore fixes it. I think it should be fixed, as we shouldn't need to disable nullable to write conventions.

**Comment by mitchdenny** [comment] 2023-07-10 00:12
Looks like this could be a simple fix:

https://github.com/dotnet/aspnetcore/blob/be566b1f4ed1ab24765a3a4a2d1751dc73e7fcfc/src/Mvc/Mvc.Core/src/ApiConventionTypeAttribute.cs#L82

Sadly, the NullableContextAttribute is compiler generated so we can't do an ```is``` check on it. So, we'll need to look at the actual attribute type and look at the name - but we already use reflection here so it shouldn't be an issue.

**Closed** 2023-07-11 02:51 UTC
Labels: bug, area-mvc, analyzer, feature-openapi, affected-few, severity-minor, Priority:2
