### ISSUE TITLE
Blazor Wasm hosted pre-render with authentication

### ISSUE THREAD

**Issue by fayewong6198** [dotnet/aspnetcore#32751] opened 2021-05-16 13:36 UTC
I followed this [guide](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0) to pre-render my wasm app and get the error

![image](https://user-images.githubusercontent.com/55927484/118399210-4b4ad380-b686-11eb-9190-027be7bfa0b1.png)

I tried to google but seems nothing working.

**Comment by fayewong6198** [comment] 2021-05-16 15:20
I followed the [doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#support-prerendering-with-authentication) to make it work. However I ran to another problem.

1. The counter does not working
![image](https://user-images.githubusercontent.com/55927484/118402181-07aa9680-b693-11eb-9d9d-6c62c67b2d91.png)

2.  Authentication/login not working
![image](https://user-images.githubusercontent.com/55927484/118402261-57895d80-b693-11eb-8232-e18a759f9367.png)

3.  Identity/account/login seems work. 
![image](https://user-images.githubusercontent.com/55927484/118402349-c797e380-b693-11eb-9320-9908eb7d5c40.png)

However, the login function seems failed. The below image is when I login success.

![image](https://user-images.githubusercontent.com/55927484/118402416-0463da80-b694-11eb-849a-ecffe78ac7d3.png)

When I tried to access private route

![image](https://user-images.githubusercontent.com/55927484/118402489-40973b00-b694-11eb-9305-81eeaaff07bb.png)

4. The browser seems lag in the pre-render mode.

**Comment by javiercn** [comment] 2021-05-17 09:20
@fayewong6198 thanks for contacting us.

In order for us to better understand your issue we need a minimal repro project and detailed steps to reproduce the issue.

**Comment by javiercn** [comment] 2021-05-17 10:48
Potential duplicate of https://github.com/dotnet/aspnetcore/issues/29634

**Closed** 2021-05-24 12:00 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, area-blazor, blazor-wasm, feature-blazor-wasm-auth
