### ISSUE TITLE
ASP.Net 6 Namespace issue

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#38204] opened 2021-11-09 10:19 UTC
I'm doing a POC for a server prerendered web assembly project.

Here's the structure of the project:
![image](https://user-images.githubusercontent.com/23618436/140905836-be5c3d3b-6348-44ea-9a62-c6a3cfa77b43.png)

In my server project index.cshtml:
![image](https://user-images.githubusercontent.com/23618436/140906053-6c560a7b-615b-4806-82a0-14f6fce5823c.png)
![image](https://user-images.githubusercontent.com/23618436/140906121-d5493b82-e896-4343-94ab-c33c3767cb83.png)

So I tried to force namespace in Counter.razor, but nothing to do. It doesn't find the namespace.
Here's the counter component:
![image](https://user-images.githubusercontent.com/23618436/140906409-3aef6b54-3a4b-4f16-b5d0-d941c4292495.png)

**Comment by javiercn** [comment] 2021-11-09 11:16
@JulienM28 thanks for contacting us.

It might be that the `Components` part is causing issues with the imported namespaces. I believe we have an issue for this to sprinkle `global::` more liberally. Could you try a different "namespace"? (BTW, this issue has existed since the beginning of Blazor)

**Comment by mkArtakMSFT** [comment] 2021-11-09 17:53
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by JulienM28** [comment] 2021-11-15 09:33
@javiercn @mkArtakMSFT Here is the repo to reproduce:
https://github.com/JulienM28/DotNet6NamespaceIssue

**Comment by mkArtakMSFT** [comment] 2021-12-08 19:39
Thanks for the repro. This is a dupe of #18757

**Closed by mkArtakMSFT** 2021-12-08 19:39 UTC
Labels: investigate, area-blazor, triaged, Priority:2
