### ISSUE TITLE
RCL template either supports MVC OR supports Components

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#17870] opened 2019-12-13 22:01 UTC
Related to feedback here: https://github.com/aspnet/AspNetCore/issues/17809

The RCL template includes either:
- The boilerplate for Components (SupportPagesAndViews == false)
- The boilerplate for MVC (SupportPagesAndViews == true)

https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/RazorClassLibrary-CSharp/.template.config/template.json#L24

It's not clear from UX that this is a binary choice, supports pages and views sounds additive, but it's replacative.

**Comment by danroth27** [comment] 2020-09-26 00:03
The issue isn't RCL specific. We also don't generate an *_Imports.razor* file with the `@using Microsoft.AspNetCore.Components.Web` directive in any of our other ASP.NET Core projects except for the Blazor ones. We could add this *_Imports.razor* file everywhere (at least for the UI related projects?), but that seems a bit clunky. @pranavkm @SteveSandersonMS Is there a better way?

**Comment by sebandraos** [comment] 2021-05-11 15:47
This isn't a particularly helpful comment but I just wanted to echo @rynowak - the language in the template checkbox is semantically ambiguous at best and realising that "that little checkbox I happened to tick in the template UI" (why wouldn't I want Pages?) could cause issues was only brought to light by [this comment](https://github.com/dotnet/aspnetcore/issues/17809#issuecomment-565623641) and I now see that it's documented as of #16684 but the workflow feels so intuitive - create an RCL, copy your components into it, reference in your Blazor project and you're off to the races - that I didn't feel the need to RTFM. In my case components from the RCL appeared to load just fine but bindings just weren't working which is a really opaque "bug" to try and track down.
Even just "Support Pages and Views instead of Components" would make people think twice, particularly as Blazor continues to pick up steam.

P.S. Thanks to the whole team, amazing work across the board.

**Comment by mkArtakMSFT** [comment] 2022-10-19 22:43
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2022-10-19 22:43 UTC
Labels: enhancement, area-blazor, severity-nice-to-have, affected-very-few, feature-templates

**Comment by sebandraos** [comment] 2022-10-25 13:55
Is this no longer a binary choice when creating an RCL? If it still is, it looks like whoever wrote the tooltip came to the same conclusion as us.

![image](https://user-images.githubusercontent.com/6084391/197792792-ca368785-2333-4d6c-b321-69c559c53a82.png)
