### ISSUE TITLE
DotNet.createJSObjectReference TS Type (transfer from DotNet.createJSObjectReference, Issue #530))

### ISSUE THREAD

**Issue by RaoulRSV** [dotnet/aspnetcore#53944] opened 2024-02-11 10:31 UTC
**Is your feature request related to a problem? Please describe.**
TS type for DotNet.createJSObjectReference() function

**_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
While developping Blazor Addin with TS it is necessary to use the DotNet.createJSObjectReference() function but I couldn't find any TS type for it

**Describe the solution you'd like**
An upgrade of the NPM DotNet type library or a turnaroud to use this function in TS

**Comment by danroth27** [comment] 2024-02-12 05:18
Originally reported in https://github.com/OfficeDev/Office-Add-in-samples/issues/530

**Comment by javiercn** [comment] 2024-02-12 10:23
Dupe of https://github.com/dotnet/aspnetcore/issues/10124 as per https://github.com/dotnet/aspnetcore/issues/53944, we'll use https://github.com/dotnet/aspnetcore/issues/10124 to track it.

**Closed by javiercn** 2024-02-12 10:23 UTC
Labels: area-blazor
