### ISSUE TITLE
The Blazor Server Side blazor-error-ui Div is displayed in Mobile Browsers after ~ few hours of inactivity, but there is no error

### ISSUE THREAD

**Issue by lucianparvu** [dotnet/aspnetcore#25951] opened 2020-09-16 10:58 UTC
We have notice that in Mobile Browsers The blazor-error-ui Div is displayed after a few hours of inactivity ( sometimes after 30 minutes). 

We have tested in Chrome & Edge on Android .
 
We have tried to use Chrome Inspection For Mobile, but we can't see the error in console because after a while that tool will close the connection .

This is strange because the components-reconnect-modal Div is not displayed in this situation, only  blazor-error-ui Div. Of course in a case of connection lost the  components-reconnect-modal Div is displayed.

The project where this is happens is complex one and a starter kit for  : Web Shops, B2B systems, CRMs and don't know if this is related to our project or is a general issue . We have upgraded it from Net Core 2.2 to Blazor Server Side (3.1.8) .

**Comment by lucianparvu** [comment] 2020-10-08 06:19
I want to mention something else : Sometimes : on mobile devices, after inactivity, when the browser tab is in background and you open it again, the Blazor is not connected and everything you do (click a button, or click to a link) will do a full page refresh . 

This is good because the GUI is not frozen  , but bad in the same time because Blazor is not connected and you don't have the result you expect when you click something .

I this cases I can't see div error .

**Comment by SteveSandersonMS** [comment] 2020-10-08 09:49
I don't have a repro for this myself, but one way you might make it easier to know the underlying error is as follows. Add this to your `_Host.cshtml` file:

```
<script>
window.onerror = function(message, source) {
    alert('Error in ' + source + '\n' + message);
};
</script>
```

Then if you cause the error to occur, you should see a message on the screen saying what it is. Of course the normal easier way to do that is to look in the browser's developer console, but I understand you've not been able to do that on these particular devices.

Please let us know what error it turns out to be.

**Comment by lucianparvu** [comment] 2020-10-08 10:07
> I don't have a repro for this myself, but one way you might make it easier to know the underlying error is as follows. Add this to your `_Host.cshtml` file:
> 
> ```
> <script>
> window.onerror = function(message, source, lineno, colno, error) {
>     alert('Error in ' + source + '\n' + message + '\n' + error);
> };
> </script>
> ```
> 
> Then if you cause the error to occur, you should see a message on the screen saying what it is. Of course the normal easier way to do that is to look in the browser's developer console, but I understand you've not been able to do that on these particular devices.
> 
> Please let us know what error it turns out to be.

Hi,

We already did something like this to check the console error "component records is not valid":
```
 var observerErr = new MutationObserver(function (mutations) {
            mutations.forEach(function (mutation) {
                if (mutation.attributeName == "style") {
                    var currentClassStateErr = mutation.target.style != null && mutation.target.style.display != null && mutation.target.style.display == 'block';
                    var shouldReload = false;
                    if (!document[hidden] || document.visibilityState === 'visible') {
                         ....
                     
                        if (currentClassStateErr && console.errors.filter(v => v.includes('component records is not valid')) != null) {
                            shouldReload = true;                           
                        }
                        if (shouldReload == true) {
                            var errorDiv = document.getElementById('blazor-error-ui');
                            if (errorDiv != null) {
                                errorDiv.style.display = 'none';
                            }
                            mutation.target.display = 'none';
                            location.reload();                           
                        }
                    }
                }
            });
        });       
        observerErr.observe(elemToObserveEror, { attributes: true });

       console.defaultError = console.error.bind(console);
       console.errors = [];
       console.error = function () 
      { 
         console.defaultError.apply(console, arguments);     
         console.errors.push(Array.from(arguments));
       }
```
But of course this is not a final solution and doesn't work on all devices and will reload the application. Maybe a solution comes from next releases .

**Comment by SteveSandersonMS** [comment] 2020-10-08 10:09
Ah, I see. In that case this is a duplicate of #26174. I'm already in process of writing some suggested steps there.

**Closed by SteveSandersonMS** 2020-10-08 10:09 UTC
Labels: Needs: Attention :wave:, affected-few, area-blazor, bug, investigate, severity-major
