### ISSUE TITLE
Changing the date / time format reflect to the CurrentCulture all the time

### ISSUE THREAD

**Issue by hishamco** [dotnet/aspnetcore#44285] opened 2022-09-30 17:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Changing the culture date/time format reflect to the default culture, there's no way in the current APIs to allow the user doesn't rely on the system settings

### Expected Behavior

The API should support a way to allow the user whether rely on the system culture ot user-selected culture

### Steps To Reproduce

- Create an app with localization enabled
- Set default culture to `en-US`
- Run the app, the date format should be 
- Close the app
- Change the date format to yyyy-MM-dd
- Run the app again, the date format will be applied whenever you change the system settings

**Comment by TanayParikh** [comment] 2022-09-30 18:18
Duplicate of https://github.com/dotnet/aspnetcore/issues/44286.

**Closed by TanayParikh** 2022-09-30 18:18 UTC
