### ISSUE TITLE
Accessing AuthenticationStateProvider from DbContext or Startup.cs

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#30982] opened 2021-03-16 20:39 UTC
Is it possible to access Blazor's `AuthenticationStateProvider` from a DbContext or in `Startup.Configure()`?

I receive this error:

> GetAuthenticationStateAsync was called before SetAuthenticationState.

@Blackleones, did you ever get this line to work in your DbContext? ref https://github.com/dotnet/aspnetcore/issues/17442#issuecomment-600222301

```
var userId = await _currentUserService.GetUserId();
```

**Comment by javiercn** [comment] 2021-03-17 16:24
@mrlife thanks for contacting us.

I'm not sure what you are trying to achieve, but the answer in general is no, since it needs to be accessed within the scope/lifetime of a Blazor application.

**Comment by mrlife** [comment] 2021-03-17 18:16
@javiercn Thanks for getting back to me. What ultimately may help is to understand why accessing a scoped service in `Startup.Configure()` appears to be a different instance of the service that is created when the Blazor app is loaded. I have a `Guid` that's set in the service's constructor, and it's different when accessed within the Blazor workflow and within `Startup.Configure()`. Aren't scoped services created once per HTTP request?

**Comment by javiercn** [comment] 2021-03-17 18:32
@mrlife Blazor creates its own scope every time a new session is established (when you start a circuit) and is not associated with an HTTP request. You can only operate within the context of the Blazor scope either inside a component or a circuit handler.

In addition to that, If your component inherits from `OwningComponentBase<T>` the T in the Service property has it's own independent scope.

**Comment by mrlife** [comment] 2021-03-17 21:09
@javiercn Thank you for letting me know about these specifics of service scope in a Blazor application. I didn't get out of [the docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-5.0&pivots=server#service-lifetime) what you explained... perhaps it's a good candidate to be added there?

**Comment by mkArtakMSFT** [comment] 2021-03-18 16:30
Thanks for your feedback, @mrlife.
Moving this to `Backlog` so that we can evaluate later whether the current documentation is misleading for others too or not. If yes, we will try to improve it then.

**Comment by Bobetti** [comment] 2022-03-08 10:22
I don't know where to write, but I have a similar problem, so I will describe my situation.

In short -> I need to get logged in user Id from dbcontext, why ->

Inside dbcontext class I have the following method:

 ```
public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
        {            

            foreach (var entry in ChangeTracker.Entries<AuditableEntity>())
            {
                switch (entry.State)
                {
                    case EntityState.Added:
                        entry.Entity.CreatedBy = _loggedUserService.UserId;
                        entry.Entity.Created = _dateTime.Now;
                        break;
                    case EntityState.Modified:
                        entry.Entity.LastModifiedBy = _loggedUserService.UserId;
                        entry.Entity.LastModified = _dateTime.Now;
                        break;
                }
            }
            var res = await base.SaveChangesAsync(cancellationToken);            

            return res;
        }
```

loggedUserService previously worked fine and looks like this -> 

 ```
public class LoggedInUserService : ILoggedInUserService
    {
        public LoggedInUserService(IHttpContextAccessor httpContextAccessor)
        {
            var id = httpContextAccessor.HttpContext?.User?.FindFirstValue(ClaimTypes.NameIdentifier);
	 if (!string.IsNullOrEmpty(id))
            {
                UserId = Guid.Parse(id);
            }
        }

        public Guid? UserId { get; }
    }
```

Now, in .Net 6 - httpContextAccessor is not working anymore. 

Rewriting the loggedUserService to start using AuthenticationStateProvider doesn't bring results because I get the exception in this case: GetAuthenticationStateAsync was called before SetAuthenticationState.

So, what should I do? Any help?

**Comment by mrlife** [comment] 2022-03-15 17:59
Not having a way to access user-level data on code that runs on the server (outside of Blazor's scope) is an ongoing issue that I hope will be addressed one day.

@SteveSandersonMS @danroth27 @shanselman

**Comment by danroth27** [comment] 2022-03-18 00:10
@mrlife @Bobetti The user identity established on the server is typically stored on the HttpContext. AuthenticationStateProvider is used for getting the authentication state on the client, which doesn't operate in the context of a request.

What prevents you from flowing the user from the HttpContext to where you need to do your user specific database queries?

**Comment by mrlife** [comment] 2022-03-18 11:54
Hi @danroth27, I really appreciate you jumping in on this. I am currently pulling the user from the initial HttpContext into Blazor's scope through Host.cshtml.cs -> App.razor. That is working great.

The issue is kind of in the other direction. With the [Audit.NET](https://github.com/thepirat000/Audit.NET) audit framework package, there is a configuration that's set up once in Startup.cs. There's code in that configuration that runs on the server after EF Core's SaveChanges completes that needs to access the user in order to log who made the change. Currently, the only option is to use HttpContextAccessor, which is [not recommended](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#blazor-and-shared-state-1) because it is not guaranteed to work in Blazor apps.

**Comment by mrlife** [comment] 2022-05-06 13:17
@danroth27 Possible to have an official response so we know whether to hold out or look for an alternative to Audit.NET?

**Comment by javiercn** [comment] 2022-05-06 13:42
@mrlife You can't access the AuthenticationStateProvider in Startup.

AuthenticationStateProvider is a scoped service that is only valid in the context of the Blazor session (circuit).

The issue is similar as trying to access the HttpContext outside of an HTTP request using IHttpContextAccessor.

**Comment by mrlife** [comment] 2022-05-06 13:53
@javiercn Thanks for writing. I'm not asking for AuthenticationStateProvider to be available in Startup, explicitly. Any solution would be helpful.

> Not having a way to access user-level data on code that runs on the server (outside of Blazor's scope) is an ongoing issue that I hope will be addressed one day.

**Comment by javiercn** [comment] 2022-05-06 14:07
@mrlife what you are asking is fundamentally impossible. There are not users when Startup is running.

I'm not sure what you are trying to accomplish here. The only thing that you could do today to access user-level data from outside of the circuit scope would be to register a singleton service on DI and have the circuit (maybe via a circuit handler) notify that service that a new circuit has been created.

If that's what you are looking for, that's something you can already do today and not something we plan to offer out of the box.

**Comment by danroth27** [comment] 2022-05-06 18:22
> The issue is kind of in the other direction. With the [Audit.NET](https://github.com/thepirat000/Audit.NET) audit framework package, there is a configuration that's set up once in Startup.cs. There's code in that configuration that runs on the server after EF Core's SaveChanges completes that needs to access the user in order to log who made the change. Currently, the only option is to use HttpContextAccessor, which is [not recommended](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#blazor-and-shared-state-1) because it is not guaranteed to work in Blazor apps.

@mrlife Does your configured Audit.NET code always run in the context of a request? If it does, then I think using `IHttpContextAccessor` should be fine for this scenario. The recommendation in the Blazor docs is really about code running in the context of Blazor components. Blazor components are for client UI and are intended to be hosting model agnostic (Server/WebAssembly/Hybrid), so you shouldn't assume they run in the context of a request. But given that this is for auditing DB access, it doesn't sound like the Blazor restriction applies to your scenario.

**Closed** 2022-05-07 19:00 UTC
Labels: question, Docs, area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved, blazor-server, feature-blazor-server-auth

**Comment by Bobetti** [comment] 2022-05-09 06:59
> @mrlife @Bobetti The user identity established on the server is typically stored on the HttpContext. AuthenticationStateProvider is used for getting the authentication state on the client, which doesn't operate in the context of a request.
> 
> What prevents you from flowing the user from the HttpContext to where you need to do your user specific database queries?

@danroth27  Daniel, it would be a great help if you could guide how to do this. I do not really understand how to pass user data into dbconext.
