### ISSUE TITLE
[Blazor/WASM] Watch Window does not group / hide non-public members

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/aspnetcore#30777] opened 2021-03-09 18:06 UTC
### Describe the bug
Members that are not reflected as part of the object's API should be hidden under a "Non-Public members" node in the watch window.

### To Reproduce
1. Create a new Blazor / WASM project in VS 2019
2. Add a new class called `Bar` using the code below
3. Update `FetchData.razor` using the code below.
4. Add a breakpoint after the `foo` variable is initialized
5. Add `foo` to the watch window
6. Expand the `foo` variable in the watch window

### Expected Results
Private members will be grouped under a "Non-Public members" node

### Actual Results
Private members (`_count`) and members used for internal functionality (`CountForDebugger`)  are displayed with public members.

#### WASM Output
![image](https://user-images.githubusercontent.com/612152/110516153-362a5500-80d7-11eb-902e-e3320abfdbec.png)

#### .NET Core Output
![image](https://user-images.githubusercontent.com/612152/110516255-54905080-80d7-11eb-85a2-451c0c1f3549.png)

**Comment by mkArtakMSFT** [comment] 2021-03-10 17:35
Thanks for contacting us. This is a dupe of https://github.com/dotnet/runtime/issues/43184

**Closed by mkArtakMSFT** 2021-03-10 17:35 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-debugging
