### ISSUE TITLE
Cannot select .net 8 preview 6 in Blazor Server even though installed.

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#49446] opened 2023-07-16 12:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I cannot select .net 8 in a balzor server project however I can in a blazor wasm project.

### Expected Behavior

I should be able to Choose a blazor server project and select .net 8

### Steps To Reproduce

1.  Install .net 8 preview 6 from here https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
2 Go into VS2022 Preview select new blazor server project
![image](https://github.com/dotnet/aspnetcore/assets/5619229/c4c4c154-e5c1-47df-a211-41ea752bf337)
U will see with the above that there is no option to select .net 8 preview 6
Even though its clearly installed 
![image](https://github.com/dotnet/aspnetcore/assets/5619229/e1d4e14f-5b62-4ec1-b993-f4bace55a8bf)
But you see here it is when a select blazor web assembly
![image](https://github.com/dotnet/aspnetcore/assets/5619229/4c0d2b17-5fd8-41ee-9c35-4da8d6f9d38c)
You will see am on preview 3 here so may be that is the issue

![image](https://github.com/dotnet/aspnetcore/assets/5619229/a68a4236-ae6e-4358-b824-d4930d2e8a98)

### Exceptions (if any)

I should be  able to select any .net blazor project and select version 8 preview 6?

### .NET Version

8.0.100-preview.6.23330.14

**Comment by davidbuckleyni** [comment] 2023-07-16 12:51
[17.0_c722fcfbActivityLog - Copy.zip](https://github.com/dotnet/aspnetcore/files/12064063/17.0_c722fcfbActivityLog.-.Copy.zip)

I have enclosed my both activity logs for your refrerence

![image](https://github.com/dotnet/aspnetcore/assets/5619229/388f9a58-6a51-4509-9657-663bf9ab2df3)

**Comment by lanedirt** [comment] 2023-07-16 14:44
Hi @davidbuckleyni,

I just wanted to confirm: I also have this same issue. When creating a *new* Blazor Server App project, there is no way to choose .NET 8.0. It only shows the option up to .NET 7.0, as seen here:

![blazor_server_app_create](https://github.com/dotnet/aspnetcore/assets/6917405/5dc44376-b942-4d35-afaa-5cd78d751638)

However, after creating the project with .NET 7.0, I am able to go into the project properties and change it to .NET 8.0 from there. See this screenshot:

![blazor_server_app_properties](https://github.com/dotnet/aspnetcore/assets/6917405/b4669ac0-f1ac-4918-a901-bbc0d4f1e0f1)

Just like you I am on Visual Studio 17.7.0 preview 3 and my dotnet --version is also "8.0.100-preview.6.23330.14".

**Comment by davidbuckleyni** [comment] 2023-07-16 14:45
> Hi @davidbuckleyni,
> 
> 
> 
> I just wanted to confirm: I also have this same issue. When creating a *new* Blazor Server App project, there is no way to choose .NET 8.0. It only shows the option up to .NET 7.0, as seen here:
> 
> 
> 
> ![blazor_server_app_create](https://github.com/dotnet/aspnetcore/assets/6917405/5dc44376-b942-4d35-afaa-5cd78d751638)
> 
> 
> 
> However, after creating the project with .NET 7.0, I am able to go into the project properties and change it to .NET 8.0 from there. See this screenshot:
> 
> 
> 
> ![blazor_server_app_properties](https://github.com/dotnet/aspnetcore/assets/6917405/b4669ac0-f1ac-4918-a901-bbc0d4f1e0f1)
> 
> 
> 
> Just like you I am on Visual Studio 17.7.0 preview 3 and my dotnet --version is also "8.0.100-preview.6.23330.14".
> 
> 

In my case it dont show it as option in your second area you showed thanks anyway.

**Comment by davidbuckleyni** [comment] 2023-07-17 15:54
> @davidbuckleyni thanks for contacting us.
> 
> 
> 
> It's a bit confusing based on the screenshots that you provided, but I hope this helps clarify things. There is no `Blazor Server` template in .NET 8.0. It's been subsumed/unified into the Blazor Web template. You should be able to get the same Blazor Server experience if you select Blazor Web + Server components.

@javiercn so does that me well always have sep apps now client and server or still just the one. 

The docs really not clear should been explained on blog post

**Comment by davidbuckleyni** [comment] 2023-07-17 23:30
@danroth27 the legend himself :-) Hi dan watch you all the time on YouTube bit of a hero of mine.

**Comment by danroth27** [comment] 2023-07-18 00:24
> so does that me well always have sep apps now client and server or still just the one.

You can still have just one project and you can stick with just Blazor Server if that's what you want to do. 

For new projects, we now provide the Blazor Web App template which can be used for both Blazor Server and Blazor WebAssembly based development. You don't need to use Blazor WebAssembly at all if you don't want to. The Blazor Web App template will by default use the new server-side rendering (SSR) support in .NET 8 and enable full interactivity just for the Counter page. But you can turn the whole app into a Blazor Server app if that's what you want to do. You can find a sample that shows what this looks like here: https://github.com/danroth27/Net8BlazorServer.

**Comment by davidbuckleyni** [comment] 2023-07-18 00:27
Thank you @danroth27 loved how someone described it as webforms for this generation behing web form's developer back in day see it especially love the muti form support was always a pain point in web forms

**Comment by danroth27** [comment] 2023-07-18 00:27
We announced the Blazor template changes as part of the release of [.NET 8 Preview 6](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-6/#blazor-template-consolidation), but we probably didn't say enough there to clarify the user experience and how you can recreate the existing Blazor Server and Blazor WebAssembly models if that's what you want to do. I've assigned this to myself to get that clarified.

**Comment by davidbuckleyni** [comment] 2023-07-18 02:25
@danroth27 a noticed that solution didnt have a csproj a we moving away from that structure again thanks.

**Comment by davidbuckleyni** [comment] 2023-07-18 21:00
@danroth27 plz go ahead and close this issue after your direction am satisfied. But if docs are being updated leavethis up to check the amendments

**Comment by angoudjou** [comment] 2023-07-19 13:03
It is the same for MAUI projects? I can't see the .NET 8 SDK with MAUI template .
Thanks

**Comment by danroth27** [comment] 2023-07-19 23:40
> It is the same for MAUI projects? I can't see the .NET 8 SDK with MAUI template.

@BethMassi Are you able to reproduce this?

**Comment by BethMassi** [comment] 2023-07-19 23:51
To get the MAUI templates to show up, you need to select ".NET 8 (Preview)" in the optional components of the MAUI workload in the VS Installer: 

![](https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2023/06/vs17.7-p2-installer.png)

**Comment by danroth27** [comment] 2023-10-04 17:18
As stated above, we have removed the Blazor Server template in .NET 8 because the scenario is now handled by the new Blazor Web App template. If you have .NET 7 still installed, then the .NET 7 version of the Blazor Server template will still show up but won't have a .NET 8 version, which is expected. In .NET 8 RC2 we are also adding an option to the Blazor Web App template that allows you to create a Blazor Web App with server interactivity enabled globally for the app, just like a Blazor Server app.

**Closed by danroth27** 2023-10-04 17:18 UTC
Labels: task, area-blazor
