### ISSUE TITLE
Better error log for: "No .NET call dispatcher has been set."

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/aspnetcore#48164] opened 2023-05-10 10:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have added sentry to my website and i notice there are some errors with "No .NET call dispatcher has been set.". But i do not have the same issue locally and based on the exception (stack trace) i wasn't able to resolve this issue. The only hint is that it is happening only on iOS devices so far.

Stack trace
```
Error: No .NET call dispatcher has been set.
  at w(/_framework/blazor.webassembly.js:1:2110)
  at b(/_framework/blazor.webassembly.js:1:1995)
  at ? (/_framework/blazor.webassembly.js:1:60337)
  at asyncFunctionResume([native code])
  at ? (/_framework/blazor.webassembly.js:1:28875)
  at asyncFunctionResume([native code])
  at ? (/_framework/blazor.webassembly.js:1:27678)
  at asyncFunctionResume([native code])
  at ? (/_framework/blazor.webassembly.js:1:28990)
  at asyncFunctionResume([native code])
```

### Describe the solution you'd like

It would be nice if there was some hint in error message which make debugging easier.

**Comment by javiercn** [comment] 2023-05-10 11:13
@jirisykora83 thanks for contacting us.

Is this happening when the app is booting up?

**Comment by javiercn** [comment] 2023-05-10 11:21
If that's the case, it's very likely that the culprit is that you are trying to issue a JS interop call before Blazor is loaded. Use a JS initializer instead to initialize your library at the right time once blazor has started.

**Comment by jirisykora83** [comment] 2023-05-10 11:25
> @jirisykora83 thanks for contacting us.
> 
> Is this happening when the app is booting up?

I don't think but as i say i cannot replicate it It locally so I have just stacktrace. I read the issue here that it maybe that blazor is not initialized but i should not call any JS -> .NET before initialization.

**Comment by javiercn** [comment] 2023-05-10 11:28
> I don't think but as i say i cannot replicate it It locally so I have just stacktrace. I read the issue here that it maybe that blazor is not initialized but i should not call any JS -> .NET before initialization.

Yes. Using an initializer will make sure that you are able to make the call at the right time https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#javascript-initializers

**Comment by jirisykora83** [comment] 2023-05-10 11:32
I mean i think i do not call any JS before .NET (Blazor) is initialized) because i only call JS from .NET (and then my app can receive callback) but this only happen after i call JS from .NET and I assume that in that time .NET must be read (running) or it is not true?

**Comment by javiercn** [comment] 2023-05-10 11:35
@jirisykora83 are you using something like ConfigureAwait or similar in your codebase?

**Comment by jirisykora83** [comment] 2023-05-10 11:38
Yes, I do.

**Comment by javiercn** [comment] 2023-05-10 11:40
@jirisykora83 try removing that. 

You should not use that within Blazor applications.

**Comment by jirisykora83** [comment] 2023-05-10 11:43
Ok thank you for your help. I am going to remove `ConfigureAwait` from blazor/RCL projects. Can I ask what you mean by "or similar"?

**Comment by javiercn** [comment] 2023-05-10 12:34
@jirisykora83 sorry, my English broke 😄. 

Avoid running things that interact with JS or Blazor state from background threads, and so on.

Blazor uses a synchronization context and things like ConfigureAwait break it.

**Comment by jirisykora83** [comment] 2023-05-10 20:23
I already deploy 'fix' where i try to remove `ConfigureAwait` (i hope i do not miss anything). But I still see the error in sentry. Is there anything else what could cause it? Or is there something that I can do to get more information about the error (without access to real devices where error happen)?

**Comment by anthonn** [comment] 2023-10-10 13:42
I think this issue might be related the my own problem: #51258

**Comment by mkArtakMSFT** [comment] 2023-12-21 17:59
Closing as we were unable to reproduce this issue. If you manage to get a reliable minimal repro project for this issue, please file a new issue and provide the repro as a publicly hosted GitHub project.

**Closed by mkArtakMSFT** 2023-12-21 17:59 UTC
Labels: area-blazor, feature-blazor-wasm, Needs: Attention :wave:, Needs: Repro, Pillar: Dev Experience
