### ISSUE TITLE
HotReload Takes minutes to process when updating a CSHTML file.

### ISSUE THREAD

**Issue by KonnectSalon** [dotnet/aspnetcore#39677] opened 2022-01-18 02:42 UTC
**Describe the bug:**
HotReload takes minutes to process when updating a CSHTML file.

**Version used:**
VS2022 17.0 Preview 2 - Been happening since VS2022 17.0 Release 

1. Open a CSHTML view
2. Change some text
3. Click Save (Which Triggers HotReload)
4. Wait 1-5 minutes
5. Page Reloads.

Expected behavior:
Like it use to be in VS2017 - Save the CSHTML and then refresh the browser and see the instant change.

Actual behavior:
Slow - Quicker to close and restart/rebuild the application.

https://user-images.githubusercontent.com/17169917/149862406-67fc3605-a4ac-41f1-88f9-59ea553d1328.mp4

**Comment by DamianEdwards** [comment] 2022-01-21 21:25
Dupe of #32867

**Closed by DamianEdwards** 2022-01-21 21:25 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-commandlinetools, Status: Resolved, feature-dotnetwatch, feature-hot-reload
