### ISSUE TITLE
dotnet-sdk-3.1 reports unable to find any compatible framework version on Fedora after installing

### ISSUE THREAD

**Issue by craigjbass** [dotnet/aspnetcore#19163] opened 2020-02-19 21:07 UTC
3.1.2 has been released, but I cannot install it via the official repos

Inspecting the file index here https://packages.microsoft.com/fedora/31/prod/ shows it as missing.

### To Reproduce

```
dnf install dotnet-sdk-3.1 -y
```

~In a 3.1.2 project:~ 

Anywhere

```
> $ dotnet --version
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.2' was not found.
  - The following frameworks were found:
      3.0.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      3.1.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.2&arch=x64&rid=fedora.31-x64
```

I also tried to install 3.1.2

```
> $ sudo dnf install dotnet-sdk-3.1.2                                                                                                                                                                                              
[sudo] password for cbass: 
[..snip...]
Last metadata expiration check: 0:07:54 ago on Wed 19 Feb 2020 20:58:15 GMT.
No match for argument: dotnet-sdk-3.1.2
Error: Unable to find a match: dotnet-sdk-3.1.2
```

### Other info

Has the Linux release process been open-sourced yet?

*Update: 19/02/2020 21:13:34* my install actually is broken, and is unusable in any project

**Comment by craigjbass** [comment] 2020-02-19 22:01
I tried to reproduce this in a fresh docker container, but the packages resolved very differently

```Dockerfile
FROM fedora:31

RUN dnf install -y wget
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN wget -q -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/31/prod.repo

RUN dnf install dotnet-sdk-3.0 -y
RUN dnf install dotnet-sdk-3.1 -y
```

## Fresh docker image (working)

```
dotnet-apphost-pack-3.0.x86_64        3.0.3-1                          @packages-microsoft-com-prod
dotnet-apphost-pack-3.1.x86_64        3.1.2-1                          @packages-microsoft-com-prod
dotnet-host.x86_64                    3.1.2-1                          @packages-microsoft-com-prod
dotnet-hostfxr-3.0.x86_64             3.0.3-1                          @packages-microsoft-com-prod
dotnet-hostfxr-3.1.x86_64             3.1.2-1                          @packages-microsoft-com-prod
dotnet-runtime-3.0.x86_64             3.0.3-1                          @packages-microsoft-com-prod
dotnet-runtime-3.1.x86_64             3.1.2-1                          @packages-microsoft-com-prod
dotnet-runtime-deps-3.0.x86_64        3.0.3-1                          @packages-microsoft-com-prod
dotnet-runtime-deps-3.1.x86_64        3.1.2-1                          @packages-microsoft-com-prod
dotnet-sdk-3.0.x86_64                 3.0.103-1                        @packages-microsoft-com-prod
dotnet-sdk-3.1.x86_64                 3.1.102-1                        @packages-microsoft-com-prod
dotnet-targeting-pack-3.0.x86_64      3.0.1-1                          @packages-microsoft-com-prod
dotnet-targeting-pack-3.1.x86_64      3.1.0-1                          @packages-microsoft-com-prod
```


## Broken Host machine packages

```
dotnet-apphost-pack-3.0.x86_64                     3.0.2-1                                                @packages-microsoft-com-prod
dotnet-apphost-pack-3.1.x86_64                     3.1.2-1                                                @packages-microsoft-com-prod
dotnet-host.x86_64                                 3.1.1-1                                                @packages-microsoft-com-prod
dotnet-hostfxr-3.0.x86_64                          3.0.2-1                                                @packages-microsoft-com-prod
dotnet-hostfxr-3.1.x86_64                          3.1.1-1                                                @packages-microsoft-com-prod
dotnet-runtime-3.0.x86_64                          3.0.2-1                                                @packages-microsoft-com-prod
dotnet-runtime-3.1.x86_64                          3.1.1-1                                                @packages-microsoft-com-prod
dotnet-runtime-deps-3.0.x86_64                     3.0.2-1                                                @packages-microsoft-com-prod
dotnet-runtime-deps-3.1.x86_64                     3.1.2-1                                                @packages-microsoft-com-prod
dotnet-sdk-3.0.x86_64                              3.0.102-1                                              @packages-microsoft-com-prod
dotnet-sdk-3.1.x86_64                              3.1.102-1                                              @packages-microsoft-com-prod
dotnet-targeting-pack-3.0.x86_64                   3.0.1-1                                                @packages-microsoft-com-prod
dotnet-targeting-pack-3.1.x86_64                   3.1.0-1                                                @packages-microsoft-com-prod
```

**Comment by craigjbass** [comment] 2020-02-19 22:06
Running this on the host machine resolved the issue.

```
sudo dnf update dotnet-apphost-pack-3.0 dotnet-host dotnet-hostfxr-3.0 dotnet-hostfxr-3.1 dotnet-runtime-3.0 dotnet-runtime-3.1 dotnet-runtime-deps-3.0 dotnet-sdk-3.0
```

There is something not quite right about how these packages are surfacing inside Fedora / how the packages interact with each other.

My expectations are that these requirements would be resolved automatically.

**Comment by dougbu** [comment] 2020-11-02 19:28
Thank you for contacting us.

To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve❔ In particular, it's not clear what issue, if any, is currently seen when using Fedora Docker images.

**Comment by dougbu** [comment] 2020-11-14 04:21
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2020-11-14 04:21 UTC
Labels: area-infrastructure
