### ISSUE TITLE
RedisCache Broken in .NET 6 Web Application

### ISSUE THREAD

**Issue by oONoobMasterOo** [dotnet/aspnetcore#38866] opened 2021-12-07 17:38 UTC
after updating my Web App from .Net 5 to .Net 6 i keep getting redis cache error ( @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script ) while using get or set cache.

### Further technical details
- ASP.NET Core version: .Net 6.0
- Visual Studio 2022 Current
- Redis-Server version : 3.2.100 ( x64 ) msi

**Comment by adityamandaleeka** [comment] 2021-12-07 17:43
@oONoobMasterOo This is a duplicate of https://github.com/dotnet/aspnetcore/issues/38715.

**Closed** 2021-12-07 17:44 UTC
Labels: area-runtime
