### ISSUE TITLE
Unhandled exception when duplicating a tab or when pressing back button in chrome

### ISSUE THREAD

**Issue by FrancisValade** [dotnet/aspnetcore#24626] opened 2020-08-06 18:27 UTC
### Describe the bug
When I debug a Blazor server-side application in Visual Studio 2019, there is an error when I try to duplicate a tab in chrome and sometime when I press the back button. 

### To Reproduce
Clone the following repo: [https://github.com/FrancisValade/IssueDuplicateTab](url). Open the solution with visual studio 2019 (It's a normal server side blazor project with two files added : TestLayout.razor and TestComponent.razor, the Counter page is using the TestLayout file as a layout). Run the app in debug with IIS Express in Google Chrome. Navigate to the counter page by using the menu and try to duplicate the tab. There should be an unhandled exception in the new tab. If there's no exception, close Visual Studio, reopen the project and try to run it again. 

### Exceptions (if any)
In the chrome console: 
blazor.server.js:15 [2020-08-06T17:58:58.567Z] Error: The list of component records is not valid

Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at e.connectionClosed (blazor.server.js:1)
    at e.connection.onclose (blazor.server.js:1)
    at e.stopConnection (blazor.server.js:1)
    at e.transport.onclose (blazor.server.js:1)
    at e.close (blazor.server.js:1)
    at e.stop (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at a (blazor.server.js:1)

### Further technical details
- ASP.NET Core version  3.1
- Visual Studio version 16.5.0 and 16.6.5

**Comment by FrancisValade** [comment] 2020-08-07 13:56
The error doesn't seem do appear the first time the app run. To make the bug appear, I added a new Blazor project in the solution,  tried to run it one time and then then I deleted it.  I also opened the Startup file and some other files from the project in Visual Studio. Eventually the bug appeared and once it appears, it will reappear every time the app run.

**Comment by pranavkm** [comment] 2020-08-10 16:53
@FrancisValade we think this might be because the browser is caching some state. You could try applying no-cache meta tags \ headers to the `_Host.cshtml` file (or any other file that's hosting your blazor component):

```
<meta http-equiv="Cache-Control" content="no-store" />
```

**Comment by FrancisValade** [comment] 2020-08-10 18:02
> @FrancisValade we think this might be because the browser is caching some state. You could try applying no-cache meta tags \ headers to the `_Host.cshtml` file (or any other file that's hosting your blazor component):
> 
> ```
> <meta http-equiv="Cache-Control" content="no-store" />
> ```
Hi, I tried to add the no-cache meta tag in the `_Host.cshtml` file but the problem is still there.

**Comment by mkArtakMSFT** [comment] 2020-10-09 18:13
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/26474

**Closed by mkArtakMSFT** 2020-10-09 18:13 UTC
Labels: affected-most, area-blazor, bug, investigate, severity-major
