### ISSUE TITLE
Add a way to control DOM update timing to Blazor Enhanced Navigation

### ISSUE THREAD

**Issue by bryanwood** [dotnet/aspnetcore#54128] opened 2024-02-20 02:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to implement view transitions using the View Transitions API (https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API). 

There's no Blazor js api/hook that lets you control the timing of the DOM updates when using enhanced navigation.

### Describe the solution you'd like

Ideally it would be nice if there was a way to set a callback that let you control the timing of the DOM update.

Naively something akin to:
```
Blazor.onCallbackForWhenDOMNeedsUpdating(performDOMUpdate => {
    const transition = document.startViewTransition(() => {
       performDOMUpdate();
    });
    // any additional transition handling
});
```

### Additional context

As a workaround I'm listening for enhanced navigations by monkey patching the global fetch and starting the view transition there and completing it on the `enhancedload` event.

**Comment by javiercn** [comment] 2024-02-20 09:31
Dupe of https://github.com/dotnet/aspnetcore/issues/53887

**Closed by javiercn** 2024-02-20 09:31 UTC
Labels: area-blazor
