### ISSUE TITLE
Passing null RenderFragment as component parameter

### ISSUE THREAD

**Issue by hultqvist** [dotnet/aspnetcore#32197] opened 2021-04-26 20:07 UTC
## Is your feature request related to a problem? Please describe.
I've spent hours trying to identify errors such as 

    System.ArgumentException: Delegate to an instance method cannot have null 'this' (Parameter 'this')    
    Project.Components.Dialogs.DialogWrapper.BuildRenderTree	\Components\Dialogs\DialogWrapper.razor 22:17 [0xF9]

It turns out that the generated `BuildRenderTree` does something when passing `RenderFragments` as an argument.

In the following example there is no problem in example 1, 2 and 3, but in 4 we get exceptions inside the generated `BuildRenderTree`. Example 5 is workaround that I don't see the reason for it being needed.

The property inside the component can be null without any problems.

**Background**

I'm building a dialog infrastructure with multiple dialogs and where the content inside the dialogs can be dynamically generated.
Because of timing issues the problem I've received did not trigger in simple examples because the body was set before the dialog was rendered. But when combining multiple dialogs, one triggering another, the timing caused one dialog to render before the body was set. I could work around this by not rendering the dialog until all parameters are not null.

### Example 1. Works: Passing a RenderFragment as an argument to a regular C# function.

```
RenderFragment body = null;
Test(body)
```

### Example 2. Works: Using a RenderFragment in blazor

```
@{
RenderFragment body = null;
}
@body
```

### Example 3. Workaround: Using a RenderFragment in the body of a component parameter

```
@{
RenderFragment body = null;
}
<MyComponent>
    <Body>
        @body
    </Body>
</MyComponent>
```

### Example 4. Throws exception: Using a RenderFragment as a component attribute

```
@{
RenderFragment body = null;
}
<MyComponent Body="body"></MyComponent>
```

### Example 5. Workaround: Wrapping `RenderFragment`

```
@{
RenderFragment body = null;
}
<MyComponent Body="(builder)=>body?.Invoke(builder)"></MyComponent>
```

What I've tried to demonstrate here is that a null RenderFragment is in most places acceptable, except for when used as a parameter to a component.
This exception is unclear, does it have to be that way?

The workarounds adds more code, make it more complex, and most importantly, are easy to forget.
Such a simple "error" as passing a RenderFragment that can be null, where null renderfragments are OK in all other situations they cause hard to debug exceptions.

## Describe the solution you'd like

I would like to be able to pass a RenderFragment as a parameter to a component without requiring it to be not null.

If I don't pass that parameter at all the component property will be null without any issues, therefore I should be able to pass null as a parameter.

**Comment by SteveSandersonMS** [comment] 2021-04-27 10:03
I think this is a duplicate of #23892, but please let us know if not.

**Closed by SteveSandersonMS** 2021-04-27 10:03 UTC
Labels: area-blazor, area-razor.compiler, feature-razor.language

**Comment by hultqvist** [comment] 2021-04-27 11:48
Yes looks like the same.
