### ISSUE TITLE
Components with render attribute in the `LayoutComponentBase` are being recreated with each navigation

### ISSUE THREAD

**Issue by IvanDmitriev1** [dotnet/aspnetcore#50766] opened 2023-09-18 03:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Components with render attribute in the `LayoutComponentBase` are being recreated with each navigation. And `NavLink` incorrectly displays the currently selected page.

### Expected Behavior

Behavior like in dotnet 7, where components in  `LayoutComponentBase` are created once for lifetime of the app.

### Steps To Reproduce

Download git repo: https://github.com/IvanDmitriev1/BlazorIssue

1. Place breakpoints in `OnInitialized` and `Dispose` methods in `NavMenu`, which is in two project with net7 blazor server and net8 blazor server interactive.
2. See the difference between two projects.

### .NET Version

8.0.100-rc.2.23462.28

### Anything else?

.NET SDK:
 Version:   8.0.100-rc.2.23462.28
 Commit:    5e71ffbd44

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23462.28\

.NET workloads installed:
 [android]
   Installation Source: VS 17.8.34112.27
   Manifest Version:    34.0.0-rc.1.432/8.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.sdk.android\34.0.0-rc.1.432\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34112.27
   Manifest Version:    8.0.0-rc.1.9171/8.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.sdk.maui\8.0.0-rc.1.9171\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34112.27
   Manifest Version:    16.4.8825-net8-rc1/8.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.sdk.maccatalyst\16.4.8825-net8-rc1\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34112.27
   Manifest Version:    16.4.8825-net8-rc1/8.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.sdk.ios\16.4.8825-net8-rc1\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.0-rc.2.23431.9
  Architecture: x64
  Commit:       3c48925a6c
  RID:          win-x64

.NET SDKs installed:
  6.0.414 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23462.28 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23455.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23431.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23454.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

**Comment by gragra33** [comment] 2023-09-18 13:06
Related to issue [#50724](https://github.com/dotnet/aspnetcore/issues/50724)

**Comment by mkArtakMSFT** [comment] 2023-09-19 17:03
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/50404

**Closed by mkArtakMSFT** 2023-09-19 17:03 UTC
Labels: area-blazor
