### ISSUE TITLE
Provide error message when using WebAssembly render mode but AddWebAssemblyRenderMode() hasn't been called

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49305] opened 2023-07-10 19:18 UTC
When I ran the https://github.com/mkArtakMSFT/BlazorWasmClientInteractivity sample app with .NET 8 Preview 6 I got a bunch of 404 and integrity check errors in the browser dev console when it tries to download the client PDB file and the ICU data file:

![image](https://github.com/dotnet/aspnetcore/assets/1874516/c99f255e-4f3f-4c4d-9f41-55918e46d3a1)

Looks like this was because I had removed the call to `AddWebAssemblyRenderMode()`. Could we provide a better error message if your missing the call to `AddWebAssemblyRenderMode()` but you have components setup to use the WebAssembly render mode?

**Comment by danroth27** [comment] 2023-07-10 20:58
Looks like this was because I was missing the call to `AddWebAssemblyRenderMode()`. Could we provide a better error message if your missing the call to `AddWebAssemblyRenderMode()` but you have components setup to use the WebAssembly render mode?

**Comment by mkArtakMSFT** [comment] 2023-08-21 15:59
This is a dupe of #49312

**Closed by mkArtakMSFT** 2023-08-21 15:59 UTC
Labels: bug, area-blazor
