### ISSUE TITLE
Blazor: Auto (implicitly) declare component @ref property

### ISSUE THREAD

**Issue by jhudler** [dotnet/aspnetcore#40972] opened 2022-03-31 11:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Would it be possible to drop the need of manually declaring the referenced property? 
Such as:

```razor
<MyComponent @ref=MyComponentReference />

@code {
    // Remove the need to manually declare the variable/property
    // MyComponent MyComponentReference = default!;

   private void MyMethod() =>
      MyComponentReference.DoStuff(); // MyComponentReference auto declared as inferred type MyComponent
}
```

If the variable/property is already manually declared, then such is used.
This would fit for backward compatibility and the possibility to declare the @ref destination as a base type / interface.

*PS: Sorry if I misplaced this suggestion - I believe this would better fit in the https://github.com/dotnet/razor-tooling, but there is no Issues tab available there.*

**Comment by javiercn** [comment] 2022-03-31 12:07
@jhudler thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/13099

This is something we considered but decided against as explained [here](https://github.com/aspnet/Announcements/issues/381)

**Closed** 2022-03-31 12:08 UTC
Labels: question, area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved, area-razor.compiler
