### ISSUE TITLE
Option to skip negotiation option for SignalR C++ client

### ISSUE THREAD

**Issue by wegylexy** [dotnet/aspnetcore#21386] opened 2020-04-30 23:36 UTC
To avoid using sticky sessions, the client needs to skip negotiation and uses WebSockets. Since the C++ client only supports WebSockets anyway, there should also be a way to skip negotiation.
It could be `.skip_negotiation(true)` with the hub connection builder.

**Comment by anurse** [comment] 2020-05-03 04:30
We have an item tracking work to get the C++ client up-to-speed with the options in the other clients. I'm going to close this as a duplicate of that one (but I made sure to call out "skip negotiation" specifically since it's definitely an important one).

Duplicate of #8716

**Closed by anurse** 2020-05-03 04:30 UTC
Labels: area-signalr
