### ISSUE TITLE
ComponentHubReliabilityTest are unreliable

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19666] opened 2020-03-07 01:08 UTC
```
Microsoft.AspNetCore.SignalR.HubException : Unable to complete handshake with the server due to an error: Handshake was canceled.
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 1057
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 433
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 441
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 255
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in /_/src/SignalR/common/Shared/ForceAsyncAwaiter.cs:line 40
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 232
   at Ignitor.BlazorClient.ConnectAsync(Uri uri, Boolean connectAutomatically) in /_/src/Components/Ignitor/src/BlazorClient.cs:line 359
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ComponentHubReliabilityTest.ComponentLifecycleMethodThrowsExceptionTerminatesTheCircuit(String id) in /_/src/Components/test/E2ETest/ServerExecutionTests/ComponentHubReliabilityTest.cs:line 295
--- End of stack trace from previous location -
```

**Comment by BrennanConroy** [comment] 2020-03-07 01:12
Three more in https://dev.azure.com/dnceng/internal/_build/results?buildId=548860&view=ms.vss-test-web.build-test-results-tab&runId=17341550&paneView=attachments&resultId=118921

**Comment by mkArtakMSFT** [comment] 2020-04-24 21:13
@BrennanConroy, @anurse I believe there was some internal issue which has caused many issues to fail with this `handshake failed` issue a while ago. That issue was, if I'm not mistaken, root caused to some runtime issue, which was later resolved. I'm going to un-quarantine this test.

**Comment by BrennanConroy** [comment] 2020-04-24 21:15
Don't know any details about that, but I'm assuming this hasn't failed for a while?

**Comment by mkArtakMSFT** [comment] 2020-04-24 22:19
I haven't been able to find any of these tests in the `Quarantined Tests` view in WhatsBroken. Was thinking about unquarantining this.

**Comment by BrennanConroy** [comment] 2020-04-24 22:26
These tests aren't running in Helix, so you can't use WhatsBroken to see if they are failing or not.

**Comment by javiercn** [comment] 2020-04-29 18:13
The issue is still there.

**Comment by pranavkm** [comment] 2020-11-02 17:22
@BrennanConroy recently reported that nearly all of the tests in this type are currently quarantined. We should revisit this type to determine if there's a fundamental test / product issue.

**Comment by Tratcher** [comment] 2021-01-14 22:51
We're seeing more timeouts:
https://dev.azure.com/dnceng/public/_build/results?buildId=951468&view=ms.vss-test-web.build-test-results-tab&runId=30028766&resultId=100004&paneView=debug

https://github.com/dotnet/aspnetcore/issues/29326

**Comment by captainsafia** [comment] 2021-01-21 19:54
Update on this. We placed some fixes for this issue in https://github.com/dotnet/aspnetcore/pull/29056.

Following this, some of the test cases are seeing better pass rates.

* `DispatchedEventsWillKeepBeingProcessed_ButUpdatedWillBeDelayedUntilARenderIsAcknowledged`
* `ComponentDisposeMethodThrowsExceptionTerminatesTheCircuit`

But not for others. :/

We should monitor this for another week then compare the first half of the 30-day analytics and the second-half to see what effect the changes above had.

**Comment by BrennanConroy** [comment] 2021-02-19 17:27
`DispatchedEventsWillKeepBeingProcessed_ButUpdatedWillBeDelayedUntilARenderIsAcknowledged` has a 55% pass rate
`ComponentDisposeMethodThrowsExceptionTerminatesTheCircuit` has a 78% pass rate
`ComponentLifecycleMethodThrowsExceptionTerminatesTheCircuit` has a 4% pass rate (**this is our lowest passing rate test**)

**Comment by captainsafia** [comment] 2021-04-27 15:52
Round #2: put another fix for this in https://github.com/dotnet/aspnetcore/pull/32189.

Let's monitor status over the next two weeks to see how this changes reliability.

**Comment by captainsafia** [comment] 2021-05-05 03:03
Current status

| Test | 14-day Pass Rate | Notes |
|---|---|---|
| CannotStartMultipleCircuits | 100% ||
| CannotStartCircuitWithNullData | 100% || 
| StartCircuitCausesInitializationError | 100% | |
| CannotInvokeJSInteropBeforeInitialization | 100% ||
| CannotInvokeJSInteropCallbackCompletionsBeforeInitialization | 98.5% | Recent failures seem to be related to data protection stuff and not (1) | 
| CannotDispatchBrowserEventsBeforeInitialization | 100% | |
| CannotInvokeOnRenderCompletedBeforeInitialization | 100% | |
| CannotInvokeOnLocationChangedBeforeInitialization | 100% | |
| OnLocationChanged_ReportsDebugForExceptionInValidation | 100% | | 
| OnLocationChanged_ReportsErrorForExceptionInUserCode | 91.55% | Recent failures seem to be related to the `Invalid state previous task not completed` issue |
| ComponentLifecycleMethodThrowsExceptionTerminatesTheCircuit | 6.49 | No improvement since the change |


(1) 
```
System.Exception : 1 error(s) logged.\r\nMicrosoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider - ErrorOccurredWhileReadingKeyRing - An error occurred while reading the key ring.\r\n===================\r\nSystem.IO.IOException: The process cannot access the file 'C:\\Users\\vsagent\\AppData\\Local\\ASP.NET\\DataProtection-Keys\\key-1a9fc521-1369-4d85-afb2-62e55b474fdf.xml' because it is being used by another process.
```

**Comment by BrennanConroy** [comment] 2021-05-05 16:04
For the DataProtection issue, you can try adding https://github.com/dotnet/aspnetcore/blob/a6c7f768ef10b8bce34f5db7c8a8594106efb8a5/src/SignalR/server/SignalR/test/Startup.cs#L69-L72 to avoid parallel test issues

**Comment by BrennanConroy** [comment] 2021-06-11 17:42
What is this tracking, didn't you effectively remove this class and the tests are now a. unquarantined, b. very different?

**Comment by captainsafia** [comment] 2021-06-11 17:48
I moved out some of the tests that were quarantined to a different infrastructure. If that infrastructure proves to be stable (aka none of them get quarantined), then we'll migrate the rest. We still have tests quarantined with this label (those are the ones that will need to be migrated).

**Comment by BrennanConroy** [comment] 2021-06-11 17:50
Gotcha, this is tracking https://github.com/dotnet/aspnetcore/search?q=19666

**Comment by dougbu** [comment] 2021-07-20 19:01
Note these tests don't run on Helix and aspnetcore-quarantined-tests only runs Helix tests. See [analytics for aspnetcore-quarantined-pr](https://dev.azure.com/dnceng/public/_test/analytics?definitionId=869&contextType=build) for these tests. To make things a bit more annoying, only individual test names show up in the analytics (they aren't qualified). Searching for a test in each quarantined class shows they are **not** doing well at all -- the best is running at about 46% success. Removing the test-fixed label&hellip;

**Comment by captainsafia** [comment] 2021-07-26 23:04
Yep -- the "test-fixed" label was to indicate that action was taken on this.

The action we took and future work is written out in https://github.com/dotnet/aspnetcore/issues/19666#issuecomment-859742472.

**Comment by BrennanConroy** [comment] 2022-01-11 19:49
Closing, `ComponentHubReliabilityTest` no longer exists (I think tests were moved to different classes/re-written elsewhere).

**Closed by BrennanConroy** 2022-01-11 19:49 UTC
Labels: task, test-failure, area-blazor, blazor-server, feature-infrastructure-improvements
