### ISSUE TITLE
Blazor: Unable to pass Renderfragments to wrapped component 

### ISSUE THREAD

**Issue by oiBio** [dotnet/aspnetcore#31940] opened 2021-04-19 18:27 UTC
### Describe the bug
We have a base component with several optional renderfragments. these optional renderfragments do have a fallback implementation if they are "null".
Unfortunatly we cant wrap these components with renderframents and pass these down...

You will get an runtime error of 
**ArgumentException: Delegate to an instance method cannot have null 'this'.**

### To Reproduce
To reproduce use this repo: https://github.com/oiBio/BazorRenderfragment
or
create a component with a renderframent and wrap this in another component, also with a renderframent.
use the second component without defining the renderfragment -> Error

### Exceptions (if any)
ArgumentException: Delegate to an instance method cannot have null 'this'.

### Further technical details
Blazor ServerSide, 
net 5.0

**Comment by mkArtakMSFT** [comment] 2021-04-20 16:44
Thanks for contacting us.
This is a dupe of #30663

**Closed by mkArtakMSFT** 2021-04-20 16:44 UTC
Labels: area-blazor
