### ISSUE TITLE
[asp.net core 7] [feature request] Multi-thread support for blazor

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/aspnetcore#38160] opened 2021-11-07 19:58 UTC
So I can run compute heavy works in another thread.

**Comment by Xyncgas** [comment] 2021-11-08 07:05
Although there's .NET MAUI Blazor APP already, which runs in native .NET process then using webUI to render web stuffs

**Comment by Xyncgas** [comment] 2021-11-08 07:06
but it still would be nice to have threads in the blazer wasm

**Comment by javiercn** [comment] 2021-11-08 12:18
@Xyncgas thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/17730

**Closed by javiercn** 2021-11-08 12:18 UTC
