### ISSUE TITLE
Update SPA templates to remove all deprecation warnings

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#43094] opened 2022-08-04 16:03 UTC
I tried out the react template with .NET 7 Preview 7 and I'm getting a bunch of deprecation warnings that we should clean up:

![image](https://user-images.githubusercontent.com/1874516/182894451-e38f2d5c-058b-4174-b13b-3f2a10335d4d.png)

**Comment by MackinnonBuck** [comment] 2022-08-30 17:43
These warnings are caused by `react-scripts`, and there are a few open issues/PRs in [create-react-app](https://github.com/facebook/create-react-app) regarding them. So, this should get "automatically" resolved in a dependency update in the future.

**Closed** 2022-08-31 21:40 UTC
Labels: area-mvc, feature-spa
