### ISSUE TITLE
Referencing Blazor WASM project from Server project with Blazor Server breaks hot-reload

### ISSUE THREAD

**Issue by jburman** [dotnet/aspnetcore#44833] opened 2022-11-02 02:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- Existing ASP.NET Core project where I use Blazor Server on several different pages (via component tag helper)
- Running dotnet watch run and hot-reload works fine
- Added a Blazor WASM client project and referenced it from the ASP.NET Core project and the hot-reload on the pages using Blazor Server stops working (I notice in the console that it logs the that the file changed, but then it logs "Not hot reload changes to apply".  Then there is a 404 request for service-worker.js)
- If I remove the package reference to Microsoft.AspNetCore.Components.WebAssembly.DevServer from the WASM client project, then hot-reload starts working again on the Blazor Server pages. **UPDATE**: After more testing, the previous statement is not true. Hot-reload is still broken for server components (works fine on the WASM components though). Once I remove the reference to the WASM client project it starts working again. (also, service-worker does not appear related)

### .NET Version

6.0.401

### Anything else?

.net 6 asp.net core project and .net 6 wasm project

**Comment by mkArtakMSFT** [comment] 2022-11-03 16:49
@tmat can you please look into this? Thanks!@

**Comment by crui3er** [comment] 2022-11-13 20:05
I have the same issue. Is there any progress on the issue?

**Comment by timeshift92** [comment] 2022-11-21 08:10
I have the same issue. Is there any progress on the issue?

**Comment by usmonovdilshod** [comment] 2022-11-21 08:24
I have the same issue

**Comment by alexyakunin** [comment] 2022-12-14 12:28
Same issue.

**Comment by timeshift92** [comment] 2022-12-14 16:15
I have the same issue. Is there any progress on the issue?

**Comment by tmat** [comment] 2023-04-19 17:38
@jburman @timeshift92 @alexyakunin Have you tried with .NET 8 Preview 3? I can't reproduce the issue with the latest SDK.

**Comment by tmat** [comment] 2023-09-25 16:08
Closing due to lack of repro.

**Closed** 2023-09-25 16:08 UTC
Labels: area-commandlinetools, feature-dotnetwatch, feature-hot-reload
