### ISSUE TITLE
Accessing hosted Blazor WebAssembly solution in Chrome Android browser resulted in error

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/aspnetcore#41064] opened 2022-04-06 15:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Accessing hosted Blazor WebAssembly solution in the Chrome Android browser resulted in an error.

Refer to the attached screenshot that details the error: Failed to execute 'arrayBuffer' on 'Response': body stream already read

This issue is faced only in the Chrome browser whereas the same hosted solution works fine in the Edge browser on the same device.

Device details:

Android OS: 10
Chrome browser ver.: 99.0.4844.88

<img width="960" alt="Blazor-Wasm-Android-Chrome-Issue" src="https://user-images.githubusercontent.com/81947404/162004763-e68223d4-1a10-464d-83b4-e4d0240942a2.png">

### Expected Behavior

Blazor JS script should load without any issues like any other browser does on the same device.

### Steps To Reproduce

Using the Chrome browser on any Android device (try in the one with the same spec that causes the error, if possible), navigate to this hosted URL https://egvijayanand.github.io/WeeklyXamarinBlazor/

### Exceptions (if any)

The same hosted solution works fine on the Edge browser on the same device.

### .NET Version

6.0.201

### Anything else?

Hosted in GitHub Pages, solution built with the latest stable .NET 6 version on Ubuntu.

**Comment by TanayParikh** [comment] 2022-04-06 17:03
Hello @egvijayanand, thanks for contacting us. This is a duplicate of https://github.com/dotnet/aspnetcore/issues/40547 & https://github.com/dotnet/aspnetcore/issues/40548. Fixes will be tracked there, feel free to leave a 👍 on the issue so we can better gauge community impact.

**Closed by TanayParikh** 2022-04-06 17:03 UTC
Labels: area-blazor, blazor-wasm

**Comment by egvijayanand** [comment] 2022-04-06 17:12
Atleast a workaround needs to made available at the earliest, the hosted solution is completely unusable in Chrome browser on Android devices. We can't go and ask the user to install another browser for this.

**Comment by TanayParikh** [comment] 2022-04-06 17:25
This is the workaround: https://github.com/dotnet/runtime/issues/58569#issuecomment-914372294

**Comment by egvijayanand** [comment] 2022-04-06 17:31
Thanks for sharing the link. Let me try the workaround.
