### ISSUE TITLE
CookieHeaderParserShared throws exception when last cookie contains invalid character

### ISSUE THREAD

**Issue by JmlSaul** [dotnet/aspnetcore#45014] opened 2022-11-11 01:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cookie String: keya=valuea; keyb=valueb; errorcookie=dd,:("sa;
the last part of cookie string above is an invalid cookie and the whole cookie string ends with `;`，this will throw exception like below, and all cookies fails to be read.

Exception: Nullable object must have a value.

   at Microsoft.Net.Http.Headers.CookieHeaderParserShared.TryParseValues(StringValues values, IDictionary`2 store, Boolean enableCookieNameEncoding, Boolean supportsMultipleValues)
   at Microsoft.AspNetCore.Http.RequestCookieCollection.ParseInternal(StringValues values, Boolean enableCookieNameEncoding)
   at Microsoft.AspNetCore.Http.Features.RequestCookiesFeature.get_Cookies()
... try get value from cookies

Cookie String: keya=valuea; keyb=valueb; errorcookie=dd,:("sa
the last part of this cookie string above is an invalid cookie and the whole cookie string ends without `;`，this will not throw exception, the parser will ignore `errorcookie`

### Expected Behavior

error cookie be ignored, and normal cookie still readable.

### Exceptions (if any)

Nullable object must have a value.

   at Microsoft.Net.Http.Headers.CookieHeaderParserShared.TryParseValues(StringValues values, IDictionary`2 store, Boolean enableCookieNameEncoding, Boolean supportsMultipleValues)
   at Microsoft.AspNetCore.Http.RequestCookieCollection.ParseInternal(StringValues values, Boolean enableCookieNameEncoding)
   at Microsoft.AspNetCore.Http.Features.RequestCookiesFeature.get_Cookies()

### .NET Version

7.0

### Anything else?

visual studio 2022 17.4.0

**Comment by Tratcher** [comment] 2022-11-11 19:12
It's probably coming from this line:
https://github.com/dotnet/aspnetcore/blob/860b12b64d49aa7ffae534601844dd54d0363ebf/src/Http/Shared/CookieHeaderParserShared.cs#L32

I wonder why TryParseValue didn't return false?

Would you like to contribute a fix for this?

**Comment by korteksz** [comment] 2022-11-11 22:12
Hi @Tratcher,

I would like to try to fix it as my first contribution if it is not a problem.

**Comment by Tratcher** [comment] 2022-11-11 22:36
@korteksz sure, first write the test and use that to figure out what the root issue is.

**Comment by korteksz** [comment] 2022-11-12 18:05
> It's probably coming from this line:
> 
> https://github.com/dotnet/aspnetcore/blob/860b12b64d49aa7ffae534601844dd54d0363ebf/src/Http/Shared/CookieHeaderParserShared.cs#L32
> 
> I wonder why TryParseValue didn't return false?

I think the problem is that if you have a cookie like `errorcookie=dd,:("sa;` then it gets parsed currently like:
Key: errorcookie Value: dd  -> because it parses the cookie until it doesn't find a non-cookie character, in this case the ',' char. Then the while loop keeps iterating further until the last character which is a ';'. As far as this is a separator and we are at the end of the input value and because supportsMultipleValues is true we return true at the end, however our parsedName and parsedValue is null. 

I've got a possible fix for that but I am not 100% convinced about its correctness.

**Comment by adityamandaleeka** [comment] 2022-11-14 23:16
@korteksz If you've got questions about the implementation, feel free to drop them here. Or you can just open a pull request with your proposed change (and include a test) and the team will review it and give you feedback. Guidance for how to do that is here: https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md#how-to-submit-a-pr

Thanks for contributing!

**Closed** 2022-12-01 19:06 UTC
Labels: bug, help wanted, area-runtime, good first issue

**Comment by cnblogs-dudu** [comment] 2022-12-17 01:12
Same issue in .NET 7.0.1.

**Comment by cnblogs-dudu** [comment] 2022-12-17 01:14
The PR #45127 disappeared in the release .NET 7.0.1, please see [CookieHeaderParserShared.cs#L29](https://github.com/dotnet/aspnetcore/blob/v7.0.1/src/Http/Shared/CookieHeaderParserShared.cs#L29)

**Comment by Tratcher** [comment] 2022-12-17 02:37
@cnblogs-dudu this was only fixed in 8.0, not 7.0. Bug fixes are not automatically backported, you'd need to demonstrate that this issue is blocking your development. Do you understand why this cookie has invalid data, and how to avoid it or work around it?

**Comment by cnblogs-dudu** [comment] 2022-12-17 03:11
@Tratcher There are lots of  `Nullable object must have a value` error logs in our asp.net core app when upgrading from .NET 6 to .NET 7.

```log
System.InvalidOperationException: Nullable object must have a value.
   at Microsoft.Net.Http.Headers.CookieHeaderParserShared.TryParseValues(StringValues values, IDictionary`2 store, Boolean enableCookieNameEncoding, Boolean supportsMultipleValues)
   at Microsoft.AspNetCore.Http.RequestCookieCollection.ParseInternal(StringValues values, Boolean enableCookieNameEncoding)
   at Microsoft.AspNetCore.Http.Features.RequestCookiesFeature.get_Cookies()
   at Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager.GetRequestCookie(HttpContext context, String key)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.ReadCookieTicket()
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by kchinburarat** [comment] 2022-12-19 04:08
I got same issue 
![image](https://user-images.githubusercontent.com/488464/208345438-63758582-f77a-4962-997f-a103d27a26c0.png)
```
eventdata.Exception.StackTraceString: at Microsoft.Net.Http.Headers.CookieHeaderParserShared.TryParseValues(StringValues values, IDictionary`2 store, Boolean enableCookieNameEncoding, Boolean supportsMultipleValues)
   at Microsoft.AspNetCore.Http.RequestCookieCollection.ParseInternal(StringValues values, Boolean enableCookieNameEncoding)
   at Agoda.Webgate.Services.MessageSender.CookieNamesHelper.GetIncomingCookieCollectionNames(HttpContext httpContext) in /build/Src/Agoda.Webgate.Services/MessageSender/WebgateMessage/CookieNamesHelper.cs:line 69
   at Agoda.Webgate.Services.MessageSender.WebgateMessageBuilder.BuildWebgateMessage(Int64 elapsedTime, HttpContext httpContext) in /build/Src/Agoda.Webgate.Services/MessageSender/WebgateMessage/WebgateMessageBuilder.cs:line 31
   at Agoda.Webgate.Services.MessageSender.WebgateMessageSender.Send(Int64 latency, HttpContext httpContext) in /build/Src/Agoda.Webgate.Services/MessageSender/WebgateMessage/WebgateMessageSender.cs:line 48
   
eventdata.Exception.Source: System.Private.CoreLib

System.Private.CoreLib: Nullable object must have a value.
  
```
Could you please release a fix version in .NET 7!!
