### ISSUE TITLE
A Blazor component that has inherited from another Blazor component, when used is interpreted as bare html

### ISSUE THREAD

**Issue by mrakgr** [dotnet/aspnetcore#48496] opened 2023-05-28 13:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For some reason Blazor inheritance is broken for me. Check out the video.

https://github.com/dotnet/aspnetcore/assets/6266635/62f097bf-6c3f-4fc1-af39-8e05a3775406

The error I get is: 

E:\Webdev\Fable\CFR-In-Fable\src\Blazor.Client\Pages\Index.razor(5,1): warning RZ10012: Found markup element with unexpected name 'TrainUI'. If this is intended to be a component, add a @using directive for its namespace. [E:\W
ebdev\Fable\CFR-In-Fable\src\Blazor.Client\Blazor.Client.csproj]

### Expected Behavior

I expected that using a component that inherits from another would work.

It shows up correctly in the IDE, so I am surprised at this kind of error. Maybe it is intended to be like this, but I'd think that would be extremely unlikely.

### Steps To Reproduce

Repo: https://github.com/mrakgr/CFR-In-Fable/tree/dotnet_watch_bug

Just run the project with `dotnet run` or `dotnet watch run`.

### .NET Version

7.0.302

### Anything else?

Link: https://github.com/dotnet/aspnetcore/issues/48447

I did a search a bit too late, and it is the same as this one which was opened 2 days ago. Feel free to close my own.

**Comment by mrakgr** [comment] 2023-05-28 15:29
Let me just add, I think I've gotten it to compile without the warning showing up a few times somehow, so when triaging don't just look for the warning in the terminal, also check how it runs in the browser.

**Comment by ScarletKuro** [comment] 2023-05-28 17:27
Hi.

Duplicate of this https://github.com/dotnet/aspnetcore/issues/48281

This is known regression in the new SDK version 7.0.302 that is documented here https://github.com/dotnet/razor/issues/8718

To address this problem, the current solution is to pin the SDK version to 7.0.203 using the `global.json` file. I've already tested your reproduction and can confirm that it works correctly on the previous SDK version.

**Comment by mrakgr** [comment] 2023-05-28 17:28
Thank you for telling me this, I'll use a previous version.

**Closed** 2023-05-30 16:48 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved
