### ISSUE TITLE
Blazor wasm - Make the location of "blazor.boot.json" configurable

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [dotnet/aspnetcore#25903] opened 2020-09-15 13:02 UTC
As reported on this comment in file "aspnetcore/src/Components/Web.JS/src/Boot.WebAssembly.ts":

    async function fetchBootConfigAsync() {
      // Later we might make the location of this configurable (e.g., as an attribute on the <script>
      // element that's importing this file), but currently there isn't a use case for that.
      const bootConfigResponse = await fetch('_framework/blazor.boot.json', { method: 'Get', credentials: 'include' });
      return bootConfigResponse.json() as Promise<BootJsonData>;
    }

The feature will help to allow multiple blazor wasm application **on the same page**.

**The case**

The final goal is to be able to put inside a single html page more than one blazor application. Why? Because in this way blazors wasm applications can be integrated in existing websites piece by piece, replacing (gradually) an existing solution (obviously written in javascript, jquery, angular, vue or anything else).

We are already able to:

- [1] put the SAME blazor application multiple times in the same page (see the solution for https://github.com/dotnet/aspnetcore/issues/20855)

- [2] serve two blazor applications inside a single .net core MVC service, but with different urls (see https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#hosted-deployment-with-multiple-blazor-webassembly-apps)

But because of the blazor.boot.json being "absolute", we can not load two blazor applications in the same page at the same time.

In fact, if we configure a solution as for [2] but without the split-routes and then we create a single html page (result of a controller-view interaction by instance) where we try to load the two projects:

    <script src="prjA/_framework/blazor.webassembly.js"></script>
    <script src="prjB/_framework/blazor.webassembly.js"></script>

The browser will fail because it will try to load (two times) the url "/_framework/blazor.boot.json" instead of the desired "/prjA/_framework/blazor.boot.json" and "/prjB/_framework/blazor.boot.json".

Setting a 

  < base href = "/...." / > 

will work only for one of the two projects.

This is a very hard limitation if you want to create a modular system and also if you have your application behind some "hard-to-manage" reverse proxy.

**Comment by mkArtakMSFT** [comment] 2020-09-15 16:39
Thanks for contacting us. This is a dupe of #22220

**Closed by mkArtakMSFT** 2020-09-15 16:39 UTC
Labels: area-blazor
