### ISSUE TITLE
[Blazor] Component Helper tag support Client-Side

### ISSUE THREAD

**Issue by Asherslab** [dotnet/aspnetcore#22062] opened 2020-05-21 02:13 UTC
### Problem:
Currently i'm trying to use Blazor Client-Side in an MVC project, i have it all setup and the JS loading, however i'm unable to actually put the components into the Views, Usually with Server-Side blazor i'd use the `<component/>` helper tag, however that's not currently supported in Client-Side .

### The Solution I'd like
I would like some way, possibly through simply adding another value to the RenderMode enum, to be able to specify Client-Side (WASM) rendering only, and for Client-Side to support it.

Thanks for the awesome work.

**Comment by mkArtakMSFT** [comment] 2020-05-21 16:39
Thanks for the issue report.
We'll look into this during our next sprint-planning meeting.

**Comment by Asherslab** [comment] 2020-05-22 01:14
Was thinking about this further and was wondering.

From what i know, if done right, this could allow a dev to select specific components to use Server-Side, or components to use Client-Side Blazor (Obviously assuming both client and server side JS are loaded) within the same page?

If so, this would be great for allowing devs to have simpler components such as hover-over text run on the client, while having "heavier" or other server related components run on the server within the same page. 

Am i correct in this thought?

**Comment by mkArtakMSFT** [comment] 2020-07-24 17:23
This is a dupe of #14434

**Closed by mkArtakMSFT** 2020-07-24 17:24 UTC
Labels: area-blazor, blazor-wasm, enhancement
