### ISSUE TITLE
UserStoreBase.SetTokenAsync not updating TUserToken when AutoDetectChanges is false

### ISSUE THREAD

**Issue by yang-er** [dotnet/aspnetcore#29426] opened 2021-01-19 14:13 UTC
### Describe the bug
When using `Microsoft.AspNetCore.Identity.EntityFrameworkCore` with `AutoDetectChanges` of `IdentityDbContext` set to false, `UserManager`'s `SetAuthenticationTokenAsync`/`ResetAuthenticatorKeyAsync` / `GenerateNewTwoFactorRecoveryCodesAsync` doesn't persist the entity to the database.

Since AutoDetectChanges is disabled, we must call Context.Update(entity) here at
https://github.com/dotnet/aspnetcore/blob/1d2bb105cb713eb17e3bc56f678c2fc90fd3def8/src/Identity/Extensions.Stores/src/UserStoreBase.cs#L934

So, something like `protected abstract Task UpdateUserTokenAsync(TUserToken token);` is needed in this case.

By the way, maybe we can mark this function virtual.
https://github.com/dotnet/aspnetcore/blob/1d2bb105cb713eb17e3bc56f678c2fc90fd3def8/src/Identity/EntityFrameworkCore/src/UserStore.cs#L146

### To Reproduce

```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace ReplayDemo
{
    public class Program
    {
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                    webBuilder.UseStartup<Program>());

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<IdentityDbContext>();

            services.AddDbContext<IdentityDbContext>(options =>
                options.UseInMemoryDatabase("HelloWorld"));
        }

        public void Configure(IApplicationBuilder app)
        {
            app.Run(context => Task.CompletedTask);
        }

        public static async Task Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();
            const string MyLoginProvider = nameof(MyLoginProvider);
            const string MyTokenName = nameof(MyTokenName);
            IdentityResult result;

            using (var scope = host.Services.CreateScope())
            {
                // this feature may be set in the constructor of this DbContext.
                var context = scope.ServiceProvider.GetRequiredService<IdentityDbContext>();
                context.ChangeTracker.AutoDetectChangesEnabled = false;

                var userManager = scope.ServiceProvider.GetRequiredService<UserManager<IdentityUser>>();
                var user = new IdentityUser("admin@admin.com") { Email = "admin@admin.com" };
                result = await userManager.CreateAsync(user, "Admin12345!@#$");
                Debug.Assert(result.Succeeded);

                result = await userManager.SetAuthenticationTokenAsync(user, MyLoginProvider, MyTokenName, "abcdefg");
                Debug.Assert(result.Succeeded);
            }

            using (var scope = host.Services.CreateScope())
            {
                // this feature may be set in the constructor of this DbContext.
                var context = scope.ServiceProvider.GetRequiredService<IdentityDbContext>();
                context.ChangeTracker.AutoDetectChangesEnabled = false;

                var userManager = scope.ServiceProvider.GetRequiredService<UserManager<IdentityUser>>();
                var user = await userManager.FindByNameAsync("admin@admin.com");
                Debug.Assert(user != null);

                result = await userManager.SetAuthenticationTokenAsync(user, MyLoginProvider, MyTokenName, "1234567");
                Debug.Assert(result.Succeeded);
            }

            using (var scope = host.Services.CreateScope())
            {
                // this feature may be set in the constructor of this DbContext.
                var context = scope.ServiceProvider.GetRequiredService<IdentityDbContext>();
                context.ChangeTracker.AutoDetectChangesEnabled = false;

                var userManager = scope.ServiceProvider.GetRequiredService<UserManager<IdentityUser>>();
                var user = await userManager.FindByNameAsync("admin@admin.com");
                Debug.Assert(user != null);

                var lastResult = await userManager.GetAuthenticationTokenAsync(user, MyLoginProvider, MyTokenName);
                if (lastResult != "1234567")
                {
                    throw new Exception("Hit!!!!!!");
                }
            }
        }
    }
}
```

### Further technical details
- ASP.NET Core version 2.1+

**Comment by HaoK** [comment] 2021-01-22 17:31
Is there a particular reason why you need to set AutoDetectChanges to false?

**Comment by yang-er** [comment] 2021-01-23 03:51
When

- lots of entities (~1K, 10 field more each) are tracked by EFCore
- AutoDetectChanges is not set to false
- frequently calling SaveChanges

In this case, SaveChanges will detect changes for all entities every time, which is extremely slow. Disabling AutoDetectChanges will be quick.

**Comment by HaoK** [comment] 2021-01-25 21:03
Ok fix for this is likely just needing a call to UpdateUesr in the SetToken method in usermanagerbase

**Comment by HaoK** [comment] 2021-02-08 23:04
@ajcvickers question, if AutoDetectChanges is set to false, is it up to the user to call DetectChanges() for SaveChanges to work?  I'm not sure this is something identity would (or should) handle gracefully as this is a specific concern with only the EF store

**Comment by ajcvickers** [comment] 2021-02-09 00:08
@HaoK In general, DetectChanges is needed, although there can be specific cases where it is not needed. That being said, if the application is disabling auto-DetectChanges, then I would say it is up to the application to either re-enable it or make explicit calls as needed.

**Comment by HaoK** [comment] 2021-02-09 00:56
Thanks, so @yang-er this behavior is by design, if you turn off AutoDetectChanges such that SaveChanges doesn't pick up your changes anymore, its up to you to ensure that changes you make to the poco are picked up and updated.  You seem to have worked around most of the issues here already, was there anything else that you were still blocked on?

**Comment by yang-er** [comment] 2021-02-09 02:43
@HaoK Should it work well when NoTracking? I think this doesn't work too.

This query tracking behavior can be easily set with DbContextOptionsBuilder.UseQueryTrackingBehavior(...), and this is mentioned at https://docs.microsoft.com/en-us/ef/core/performance/efficient-querying#tracking-no-tracking-and-identity-resolution

```
context.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
```

Only this part can't work with AutoDetectChanges=false or QueryTrackingBehavior=NoTracking.

**Comment by yang-er** [comment] 2021-02-09 02:48
As for this comment,

> then I would say it is up to the application to either re-enable it or make explicit calls as needed.

I think other implementations using UserStoreBase without auto-change-detect or EF wouldn't get to know that this entity of IdentityUserToken is changed.

**Comment by HaoK** [comment] 2021-02-09 17:10
AutoDetect/ChangeTracking is an EF specific thing, the manager calls Update and its expectation is that the store persists the changes, its up to the store to ensure that changes are persisted properly.

**Closed by HaoK** 2021-02-09 17:10 UTC
Labels: area-identity

**Comment by yang-er** [comment] 2021-02-10 03:43
**I insist that this is a bug.**

The UserStoreBase has several generic arguments

- `TUser` has a *UpdateAsync* to notice the real store that this entity is updated
- `TRole`, `TRoleClaim` is handled by RoleStore
- `TUserRole`, `TUserLogin` only need to Add/Delete/Find, update operation is not needed
- `TUserClaim` has Add/Delete/Find and **Replace**, and its update requests notify the store implementation by *ReplaceClaimAsync*
- **`TUserToken` has Add/Find/Remove functions now, but without a update**

Here, *SetTokenAsync* is implemented by changing the property of entity poco directly, but without a update notification.

Yes, as you said
> AutoDetect/ChangeTracking is an EF specific thing

But here, the **`Microsoft.AspNetCore.Identity.UserStoreBase`** implementation of **SetTokenAsync** is depending on the EF's auto-change-detecting feature from change tracking system. This is not **`Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`**.

People can make overrides on this class and add other implementations on stores like mongodb, restful api... These implementation may not provide the auto-change-detecting feature.

Even if `Microsoft.AspNetCore.Identity.UserStoreBase` is only designed for EFCore, this is still a bug.

You use `Context.Update(user);` in *UpdateAsync* in EFCore Store, which means the EF implementation doesn't rely on the auto change detecting. Other parts of the store don't rely on change tracking system.

But you didn't call `Context.Update(userToken);`. In normal situations (developers didn't change the settings of change tracking system), the change of user token poco is detected by EF, that's all right, it works well. But in this situation, it doesn't work, it relies on auto-change-detecting, which is turned off.

So I think,

EITHER you update the document of identity announcing that the identity features relies on EF's auto-change-detecting, and the `UserStoreBase` is only designed for systems supporting auto-change-detecting

OR you add the function *UpdateUserTokenAsync* to the `UserStoreBase`

**Comment by HaoK** [comment] 2021-02-10 03:59
Isn't update equivalent to just Remove(token) + Add(token)?

**Comment by HaoK** [comment] 2021-02-10 04:03
But in the UserManager, we call UpdateUser after a call to SetAuthenticationToken.

https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/UserManager.cs#L2170

**Comment by yang-er** [comment] 2021-02-10 05:40
> Isn't update equivalent to just Remove(token) + Add(token)?

Yes, but implementation for *SetTokenAsync* in `UserStoreBase` isn't remove+add. It is modifying poco property.

> But in the UserManager, we call UpdateUser after a call to SetAuthenticationToken.
> 
> https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/UserManager.cs#L2170

`TUserToken` doesn't have any navigation with `TUser`, and *UpdateUser* only requires the context to update the user entity, not the userToken entity.
