### ISSUE TITLE
Passing null to NavigationManager.GetUriWithQueryParameter requires a cast

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#36411] opened 2021-09-11 17:56 UTC
If you want to remove a single query parameter, you can pass null to `NavigationManager.GetUriWithQueryParameter`, but then you get an ambiguous method error. To workaround this error, you have to cast null to a nullable type.

```csharp
// Doesn't work - ambiguous method match compilation error
var newUri = NavigationManager.GetUriWithQueryParameter("page", null);

// Works
 var newUri = NavigationManager.GetUriWithQueryParameter("page", (int?)null);
```

**Comment by javiercn** [comment] 2021-09-13 09:54
@danroth27 good catch

I believe that's a limitation on how C# works, since it can't pick the right overload for you.

/cc: @SteveSandersonMS

**Comment by SteveSandersonMS** [comment] 2021-09-13 10:32
Yes, that's correct.

I was hoping this situation doesn't come up very often in real-world code. The two most common cases I expect are:

* Adding/updating to current URL a single parameter to generate links while rendering (e.g., `page`)
* Generating an entire URL by combining multiple query values (e.g., in an event handler, representing the state of a component as a URL)

In neither of these cases would you be *removing* a single value from the existing URL. But if this case does come up a lot, we could have an explicit `GetUriWithoutQueryParameter`.

Closing as by design.

**Closed by SteveSandersonMS** 2021-09-13 10:32 UTC
Labels: area-blazor, feature-blazor-builtin-components

**Comment by javiercn** [comment] 2021-09-13 10:33
@SteveSandersonMS how do you feel about using a "special value" here to signal removal?

**Comment by SteveSandersonMS** [comment] 2021-09-13 10:42
That's kind of what `(string)null` or `(int?)null` is. I don't think `GetUriWithQueryParameter("name", QueryParameterValues.None)` is more discoverable than ``GetUriWithoutQueryParameter("name")`.

But I don't feel hugely troubled by this anyway. I'd prefer to wait and see what customer feedback we get here before considering a refinement in 7.0. There's nothing unusual about `(string)null` (or whatever type a given parameter usually is).

In many cases people will be doing ``GetUriWithQueryParameter("somename", myVariable)`, where `myVariable` is sometimes `null`, which will work naturally.
