### ISSUE TITLE
Improve prerendering and authentication experience in Blazor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#27592] opened 2020-11-06 19:33 UTC
Enabling pre-rendering on a Blazor WASM app with authentication is difficult.

Related issues:
- https://github.com/dotnet/aspnetcore/issues/26270
- https://github.com/dotnet/aspnetcore/issues/27407
- https://github.com/dotnet/aspnetcore/issues/28025

**Comment by javiercn** [comment] 2021-05-18 09:23
@captainsafia this is a dupe of https://github.com/dotnet/aspnetcore/issues/29634 feel free to close one or the other.

This has a combined 15 upvotes

**Comment by captainsafia** [comment] 2021-05-18 16:36
Ah, I see. I'll close the other one since it's newer.

**Comment by ChristianWeyer** [comment] 2021-07-20 17:52
Does this mean we cannot use pre-rendering with SPA authN flows in a feasible and reasonable way?
This renders (pun intended ;-) ) this features unusable @captainsafia.

Thanks!

**Comment by javiercn** [comment] 2021-07-20 17:58
We are grooming our backlog and we don't think this issue will make the cut, while painful, there are ways around it (even if not trivial)

We might reconsider this one if we get time, however is not a trivial issue and requires design, which why we are hesitant about tackling it now, (hence the backlog)

**Comment by ChristianWeyer** [comment] 2021-07-20 18:01
Hi @javier - thanks for answering.
It would help *a lot* if you would show people the ways around it :-)

Thanks.

**Comment by javiercn** [comment] 2021-07-20 18:02
@ChristianWeyer I believe there are some docs about it, but in general involves skipping prerendering over any url that might require auth, which is why it is so painful.

**Comment by ChristianWeyer** [comment] 2021-07-20 18:04
Which in reality renders it unusable, sorry. been there, done that :-)

**Comment by keerthirajap** [comment] 2022-01-18 04:55
I temporarily resolved by using prerender.io

https://github.com/dotnet/aspnetcore/issues/39137#issuecomment-998916073

**Comment by cirrusone** [comment] 2022-08-18 15:18
May I ask if this issue is likely to help with seamless switching between Blazor Server and Blazor WebAssembly at runtime whilst authenticated?

The AllinOne sample here https://github.com/ShaunCurtis/AllinOne is an excellent example which switches between Blazor modes but when attempting to add authentication lots of issues arise that prevent authentication state being recognized.

I would like to 
1/ Start with Blazor Server and require login to standard ASP.NET Core Identity using cookies
2/ Blazor Server can pre-fetch the WASM assets after server side loaded whilst user is logging in.
Eg 
```
    <script>
        window.addEventListener('load', () => {
            fetch('/wasm/_framework/dotnet.wasm')
            fetch('/wasm/_framework/blazor.webassembly.js');
            fetch('/wasm/_framework/blazor.boot.json');
        });
    </script>
```
3/ Once authenticated on Server, user can seamlessly switch to Blazor WASM which maintains authenticated state on both Blazor Server and Blazor WebAssembly

Is something like this currently possible and/or will this be possible in the near future?

**Comment by yugabe** [comment] 2022-09-02 07:07
Hey all! It's been a while since this issue first surfaced, and it seems it's still on the way for .NET 7. Can someone please confirm?

I also don't quite understand _how_ this is supposed to work when:
- **Not using cookies**: on a full postback, only the cookies are a native solution for the server to identify the user by as the Blazor WASM app hasn't started that sends AJAX requests with additional headers instead of cookies. What is the proposed scenario? When using tokens, the app won't try to prerender components that require authentication?
- **Using cookies**: this should be essentially working out of the box; if the cookies are present, they should be available both during prerendering and when the client sends AJAX requests to the API.

So is the proposed change here to disallow prerendering when it's tied to authentication? Hopefully there will be a way to opt-out of this behavior, as it'll quite possibly break already working prerender+auth solutions.

Thanks!

**Comment by modigithub** [comment] 2023-01-14 08:47
Ok, is there a site where you can vote? I think that is an extremely important part. Without pre-rendering with authentication-dependent content, many projects fail. I would like to advocate that it be integrated into the planning for .net 8. However, I didn't quite understand what "it's very rare and low-impact issue, we will close it" means. Do you think that in this ticket the people have to participate? Or is there a voting page as mentioned above?

I'm very excited about blazor. However, the initial loading time and the loading symbol right at the beginning of a page is a no-go for me. The prerendering would solve exactly these problems and would be a reason for me to only do all my projects with Blazor WASM.

**Comment by chassq** [comment] 2023-01-30 13:49
Any good way to get involved other than responding to this issue? This needs a resolution in order for Blazor Wasm to be usable in the near and far future. Pre-rendering and Authentication need to play well together. Also, we need to be able to have a well-documented method for pre-rending wasm without a Host site. Can it be built so that, for example, pre-rendering is done for bots/facebook posts, etc. and not "user" requests?

**Comment by ChristianWeyer** [comment] 2023-07-17 08:01
Hi @captainsafia - could you please update us on where we are with this feature? This is still a very important part of using Blazor WASM in the 'real world' :-)

Thank you!

**Comment by mkArtakMSFT** [comment] 2023-12-12 17:23
A lot of the initial pain points have been addressed during .NET 8 in this space. The remaining work here is to simply passing authentication state from server to client which we will address as part of https://github.com/dotnet/aspnetcore/issues/52769

**Closed by mkArtakMSFT** 2023-12-12 17:23 UTC
Labels: enhancement, area-blazor, feature-blazor-wasm, affected-few, severity-major, Priority:1, design-proposal, feature-blazor-wasm-auth, Pillar: Technical Debt
