### ISSUE TITLE
OpenApi: The IEndpointParameterMetadataProvider is not used for Controllers

### ISSUE THREAD

**Issue by DavidBal** [dotnet/aspnetcore#58178] opened 2024-10-01 10:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to  generate a OpenApi json for my Controller based Api. 

I have the following controller Code:

```c#
[Route("api/[controller]")]
[ApiController]
public class TestController : ControllerBase
{
    [HttpPost("test")]
    public async Task<IActionResult> PostTest([FromBody] XmlPlaceholder? xmlPlaceholder = null)
    {
        return Ok();
    }
}
```

The XmlPlaceholder class looks like this:
```c#
public class XmlPlaceholder : IEndpointParameterMetadataProvider
{
    public static void PopulateMetadata(ParameterInfo parameter, EndpointBuilder builder)
    {
        builder.Metadata.Add(new AcceptsMetadata(["application/xml", "text/xml"], typeof(XmlPlaceholder)));
    }
}
```

The generated OpenAPI json looks like this:
````json
 "/api/Test/test": {
      "post": {
        "tags": [
          "Test"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/XmlPlaceholder"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/XmlPlaceholder"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/XmlPlaceholder"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
````

### Expected Behavior

I  would expect the same behavior as for minimal apis.

There the metadata is used and produces the following output:

```json
    "/minimalTest": {
      "post": {
        "tags": [
          "WebApplication2"
        ],
        "operationId": "Minimal Test",
        "requestBody": {
          "content": {
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/XmlPlaceholder"
              }
            },
            "text/xml": {
              "schema": {
                "$ref": "#/components/schemas/XmlPlaceholder"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
```

### Steps To Reproduce

https://github.com/DavidBal/-Demo_IEndpointParameterMetadataProvider_for_Controller/tree/master

### .NET Version

9.0.100-rc.1.24452.12

### Anything else?

````xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0-rc.1.24452.1" />
  </ItemGroup>

</Project>
````

**Comment by captainsafia** [comment] 2024-10-02 04:56
@DavidBal Thanks for reporting this issue! I believe this is a dupe of https://github.com/dotnet/aspnetcore/issues/44988. If you'd like to give that issue a thumbs up and add a comment with your scenario there that would help keep all the information in one place.

For now, closing this as a dupe.

**Closed by captainsafia** 2024-10-02 04:56 UTC
Labels: feature-openapi, area-minimal
