### ISSUE TITLE
Azure webapps rewriting backslash to slash

### ISSUE THREAD

**Issue by ioantoader** [dotnet/aspnetcore#40538] opened 2022-03-04 08:49 UTC
Here is my controller sample code:

`using Microsoft.AspNetCore.Mvc;

namespace TestRoute.Controllers
{
    [Route("api/[controller]")]
    [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
    [ApiController]
    public class TestRouteController : ControllerBase
    {
        [HttpGet("{*documentId}", Name = "Get")]
        public IActionResult Get([FromRoute] string documentId)
        {
            return Ok(new { documentId });
        }

    }
}
`

when I enter for the documentId **abc\xyz** (https://testrouteit1.azurewebsites.net/api/TestRoute/abc%5Cxyz) the method return **abc/xyz** value

**Comment by adityamandaleeka** [comment] 2022-03-04 22:41
Closing as a duplicate of #40532

**Closed by adityamandaleeka** 2022-03-04 22:41 UTC
Labels: untriaged
