### ISSUE TITLE
Blazor .NET 5 Cannot Change ServiceWorkerAssetsManifest Path

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#30551] opened 2021-03-01 16:55 UTC
### Describe the bug
Using anything other than `<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>` breaks build.

### To Reproduce
Create a blazor wasm app with pwa support in visual studio. 
Replace the ServiceWorkerAssetsManifest property with
`<ServiceWorkerAssetsManifest>wwwroot\offline-server\service-worker-assets.js</ServiceWorkerAssetsManifest>`

### Exceptions (if any)

Results in the following build error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '[Omittted]\obj\Debug\net5.0\wwwroot\offline-server\service-worker-assets.js'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateServiceWorkerAssetsManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AppPotion.Bd.Client	C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets	68	
```

### Further technical details
- ASP.NET Core version
5.0.3
- Include the output of `dotnet --info`
- .NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- Visual Studio 16.8.6

**Comment by javiercn** [comment] 2021-03-02 12:01
@groogiam thanks for contacting us.

In this case I think the issue is that you are using a file path. I would suggest trying 'offline-server/service-worker-assets.js`. I believe that property refers to the base relative path on the app

**Comment by groogiam** [comment] 2021-03-02 15:48
This does not seem to work. Below property results in the following msbuild error still.
   
 `<ServiceWorkerAssetsManifest>offline-server/service-worker-assets.js</ServiceWorkerAssetsManifest>`

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '[omitted]\obj\Debug\net5.0\offline-server\service-worker-assets.js'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateServiceWorkerAssetsManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	PWATest.Client	C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets	68

**Comment by SteveSandersonMS** [comment] 2021-08-03 17:45
We think this is resolved in .NET 6. Could you please try the latest .NET 6 preview release and let us know if the issue still affects your application? Thanks!

**Closed** 2021-08-12 01:00 UTC
Labels: bug, Needs: Author Feedback, area-blazor, blazor-wasm, Status: No Recent Activity, feature-razor-sdk, feature-pwa
