### ISSUE TITLE
Blazor: Default template and wrong reference count

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#15190] opened 2019-10-19 12:02 UTC
Using the default template and looking at the Code Lense reference count:

![image](https://user-images.githubusercontent.com/8482283/67144616-b6e57880-f278-11e9-88a5-40a7f0e1d22c.png)

**Comment by javiercn** [comment] 2019-10-21 11:56
@Postlagerkarte Thanks for contacting us.

@NTaylorMullen @ajaybhargavb I believe this would have something to do with FindAllReferences? 

Can this be caused by `@inject WeatherForecastService` being present in the design and implementation files for the component?

**Comment by NTaylorMullen** [comment] 2019-10-21 18:17
Yas there was a duplicate VSTS issue for this that I can't for the life of me find now. I asked @jasonmalinowski to take this over.

**Comment by mkArtakMSFT** [comment] 2020-02-13 19:15
Closing as we track this as an external issue

**Closed by mkArtakMSFT** 2020-02-13 19:15 UTC
Labels: PRI: 2 - Preferred, area-blazor, bug
