### ISSUE TITLE
[SignalR][TS Client] Typesafe connection

### ISSUE THREAD

**Issue by MrCodingB** [dotnet/aspnetcore#43144] opened 2022-08-08 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When I create web applications I mostly use angular in combination with ASP.Net Core and when needed I use SignalR for real-time apps. For this I use the @microsoft/signalr package. The server side (c# / .net) implementation of SignalR is strict (= one can specify all the client methods and parameters etc.), the client (js / ts) however is currently lacking this feature. So I had to create my own type specification which just adds a layer of type security to the hub connections. It is not a lot of effort and it improves code quality and security by a lot, so I don't quite understand the reasons for not creating such a specification when it has been done in other implementations (e.g. c# / .net).

### Describe the solution you'd like

I would like a type safe / strict version of the `HubConnection` object. I have something quite similar to how it's done in c# / .net in mind.

```ts
interface IServerMethods {
  SubscribeToUserMessages(userId: string): string[];
  ChangeStatus(status: string): void;
}

interface IClientMethods {
  UserStatusChanged(status: string): void;
  ReceiveUserMessage(userId: string, message: string): void;
}

const connection = new HubConnectionBuilder().build<IServerMethods, IClientMethods>();

// The types could also be specified with the connection builder
const connection = new HubConnectionBuilder<IServerMethods, IClientMethods>().build();

connection.on('ReceiveUserMessage', (userId, message) => { ... });
connection.on('UserStatusChanged', (status) => { ... });

const oldMessages = await connection.invoke('SubscribeToUserMessages', 'a398fj');

await connection.send('ChangeStatus', 'inactive');

// Throws compiler error, because no such method was specified
await connection.send('UpdateStatus', 'inactive');

// Throws compiler error, because of the wrong type
await connection.send('ChangeStatus', 123);
```

**Comment by BrennanConroy** [comment] 2022-08-09 22:49
This is effectively a dupe of https://github.com/dotnet/aspnetcore/issues/15198 which is tracking adding strongly-typed to all clients.

**Closed** 2024-03-02 00:49 UTC
Labels: area-signalr
