### ISSUE TITLE
[SignalR/Java clients] - null object reference on transportenum

### ISSUE THREAD

**Issue by NunoPontes** [dotnet/aspnetcore#29765] opened 2021-01-29 15:05 UTC
### Is your feature request related to a problem? Please describe.
I'm trying to build an Android app that receives messages from SignalR.
The problem that I am having is that after the server timeout, which the default is 30 seconds, I won't receive anymore information and have to reconnect manually, meanwhile I might have missed data.

Example: I am trying to do a list that gets a new item when signalR sends the object to the app, however the interval between messages isn't constant, it can be 30 seconds or 1 hour. 

### Describe the solution you'd like
I would like a flag where we can disable server timeout, meaning that while we don't stop the connection the client is always listening for messages from SignalR. Perhaps the setServerTimeout can receive a null, and when it does it never timesout

### Additional context
When we try to reconnect manually we might lose information.
I'm currently using version 3.1.11, because the 5.0.2 causes my app to constantly crash and this is the only version where I can make SignalR work

**Comment by BrennanConroy** [comment] 2021-01-29 17:25
> after the server timeout, which the default is 30 seconds, I won't receive anymore information

Is the connection getting closed? Did you modify the server-sides `KeepAliveInterval`?

> 5.0.2 causes my app to constantly crash

Are you getting the errors described in https://github.com/dotnet/aspnetcore/issues/29457?

**Comment by NunoPontes** [comment] 2021-02-01 08:29
Hello @BrennanConroy,

I dont' have access to the server side, so I only changed on the Java client, by changing serverTimeout.


```
val timeout: Long = 100000
        hubConnection = HubConnectionBuilder.create(
            URL
        )
            .shouldSkipNegotiate(true)
            .withHandshakeResponseTimeout(timeout)
            .withTransport(TransportEnum.WEBSOCKETS)
            .build()
        hubConnection?.serverTimeout = timeout
        hubConnection?.keepAliveInterval = timeout

        hubConnection?.start()
        hubConnection?.onClosed { exception: Exception ->
            Timber.e("onClosed " + exception.message.toString())
            runOnUiThread {
                Toast.makeText(
                    this,
                    hubConnection?.connectionState?.name,
                    Toast.LENGTH_LONG
                ).show()
            }
            runOnUiThread(Runnable {
                Toast.makeText(this, "signalr " + exception.message.toString(), Toast.LENGTH_LONG)
                    .show()
            })
            hubConnection?.stop()
            startHub()
        }
```

Using the 5.0.2 I get the following crash, it's not the one you referenced:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.microsoft.signalr.TransportEnum.ordinal()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.microsoft.signalr.TransportEnum.ordinal()' on a null object reference
        at com.microsoft.signalr.HubConnection.lambda$start$10$HubConnection(HubConnection.java:267)
        at com.microsoft.signalr.-$$Lambda$HubConnection$l-M-k_a4jmA6PuMbiVuiDtdeomw.apply(Unknown Source:8)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:83)
        at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
        at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onComplete(SingleDelayWithCompletable.java:69)
        at io.reactivex.subjects.CompletableSubject.subscribeActual(CompletableSubject.java:157)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.single.SingleDelayWithCompletable.subscribeActual(SingleDelayWithCompletable.java:36)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable.subscribeActual(SingleFlatMapCompletable.java:44)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.Completable.subscribe(Completable.java:2383)
        at com.microsoft.signalr.HubConnection.start(HubConnection.java:328)
```

**Comment by BrennanConroy** [comment] 2021-02-01 17:47
So you've set the server timeout to 100 seconds and the server is only sending keep alives every 180 seconds. It's recommended for the server timeout to be double the keep alive interval, and definitely not lower than the interval.

I've never seen that null reference before. I'll need to look into how that's possible.

**Comment by dsuresh-ap** [comment] 2021-02-03 20:13
We have been `Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.microsoft.signalr.TransportEnum.ordinal()' on a null object reference` as well in our non-fatal logging from users. Not sure what is causing it.

**Comment by BrennanConroy** [comment] 2021-03-10 17:50
Done via https://github.com/dotnet/aspnetcore/pull/30482
Will be in 6.0-preview3 and 5.0.5

**Closed by BrennanConroy** 2021-03-10 17:50 UTC
Labels: area-signalr, investigate
