### ISSUE TITLE
Cosmos Provider for Identity

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/aspnetcore#21108] opened 2020-04-22 19:20 UTC
### Is your feature request related to a problem? Please describe.

Existing libaries for using Identity Core with a Cosmos backend are not (or barely) maintained.

### Describe the solution you'd like

With CosmosDB introducing the free tier, I thought I could finally get rid of my SQL Database (which is currently being used _just_ for Identity. All existing projects are retired or direct to https://github.com/codekoenig/AspNetCore.Identity.DocumentDb (where the NuGet package hasn't been updated since 2017).

I've also looked at MongoDB providers (these seem to be more active), but it seems silly to build a new app with Mongo on Cosmos instead of just using DocumentDB.

### Additional context

I'd be happy with a Microsoft or a .NET Foundation project, but there needs to be at least one option.

**Comment by blowdart** [comment] 2020-04-22 20:18
This is something we leave to the community, it's not something we want to develop ourselves I'm afraid. We will only provide entity framework based providers.

Given that Entity Framework has a [CosmosDB](https://docs.microsoft.com/en-us/ef/core/providers/cosmos/?tabs=dotnet-core-cli) provider the existing entity framework code should work.

**Comment by MisinformedDNA** [comment] 2020-04-22 21:06
That's fair. I hadn't put the pieces together that there is a Cosmos Provider for EF and a EF provider for Identity, so I should be able to use `Microsoft.AspNetCore.Identity.EntityFrameworkCore` with `Microsoft.EntityFrameworkCore.Cosmos`, right?

Well I span up a new ASP.NET Core Web app and replaced the package `Microsoft.EntityFrameworkCore.SqlServer` with `Microsoft.EntityFrameworkCore.Cosmos`. And then updated the `AddDbContext()`, replacing `UseSqlServer()` with `UseCosmos()`. Finally, I had to delete the migrations code as that was SQL specific.

So now I'm getting an error

> CosmosException: Response status code does not indicate success: 404 Substatus: 0 Reason: (Message: {"Errors":["Resource Not Found"]}
ActivityId: cfc434f3-6e11-4e03-9da9-99ecc9e50b18, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats:
RequestStartTime: 2020-04-22T20:47:41.3904425Z, RequestEndTime: 2020-04-22T20:47:41.3934267Z, Number of regions attempted:1
ResponseTime: 2020-04-22T20:47:41.3934267Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 32, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#32, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
ResponseTime: 2020-04-22T20:47:41.3934267Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 32, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#32, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
, SDK: Microsoft.Azure.Documents.Common/2.9.2, Windows/10.0.17134 cosmos-netstandard-sdk/3.3.0).

Do I need to redo migrations somehow? Do I need to manually create the collections (though I don't know what they should be named)?

Thanks.

**Comment by MisinformedDNA** [comment] 2020-04-23 02:56
OK. Weird step. If I override `OnModelCreating` and remove the `base` call, then that error goes away, but then it starts complaining about primary keys not being defined:

> InvalidOperationException: The entity type 'IdentityUserLogin<string>' requires a primary key to be defined.

Would this just use the same conventions as used in SQL server? Is there a sample project of this working? I can't find any.

**Comment by blowdart** [comment] 2020-04-23 12:22
I doubt there's a sample. @ajcvickers / @HaoK if someone has time can they look at this?

**Comment by ajcvickers** [comment] 2020-04-23 14:38
@blowdart We've thought about it, but Cosmos doesn't seem to be a great fit for the Identity model. @MisinformedDNA Can you provide some more details on why Cosmos is a good fit for this?

**Comment by MisinformedDNA** [comment] 2020-04-23 15:46
I have a lot of pet projects. The websites I create don't always get users or revenue. I have been using Table storage to avoid SQL/Cosmos costs, but the Identity aspect has always left me with SQL costs anyway. Now that there is a free tier to Cosmos, it made sense for me (I thought) to move all storage to Cosmos. Use the free tier until something takes off.

@ajcvickers Why is Cosmos not a good fit for Identity?

Also, what would be the cloud solution cloud solution for auth (i.e. not SQL Database)?

**Comment by ajcvickers** [comment] 2020-05-13 18:20
@MisinformedDNA That's not unreasonable, but the priority is still going to be very low unless there is a large number of people who want to do. It would likely require at least tweaks to the model, and possibly bigger changes, since it is pretty relational-specific in its design.

**Comment by blowdart** [comment] 2020-05-13 18:21
Closing as "by design". Until we get a lot more requests this isn't going to happen due to the model changes needed.

**Closed by blowdart** 2020-05-13 18:21 UTC
Labels: area-identity
