### ISSUE TITLE
Deadlock in integration tests after upgrading to ASP.NET Core 6

### ISSUE THREAD

**Issue by angularsen** [dotnet/aspnetcore#38649] opened 2021-11-26 13:39 UTC
### Describe the bug
After upgrading from ASP.NET Core 5 to 6, our integration tests would hang indefinitely on Azure Pipelines with `ubuntu-20.04`.

After analyzing dumps with `dotnet test --blame-hang-timeout`, we found a deadlock on `WebApplicationFactory.Dispose()` and concurrent tests calling the API.

**The root cause**
- Single `WebApplicationFactory` instance per test class, reused by its test methods to call the API.
- Hosted service with `Task.Delay(TimeSpan.FromSeconds(5), ct)` in its `IHostedService.StopAsync()`, which is used to flush logs and telemetry before the API is allowed to shut down.
- The delay seems to create a deadlock for shared factories, only on Linux/Ubuntu and only on .NET6.

**Workaround**
Do not delay `IHostedService.StopAsync()` for "Test" environment.

**Investigation**
- `dotnet test` on Azure Pipelines `ubuntu-20.04` would hang indefinitely after upgrading to ASP.NET Core 6
- Could not reproduce on Azure Pipelines `windows-2019`
- Could not reproduce on Windows, with Rider or Visual Studio 2022
- Could not reproduce on Windows with `dotnet test`
- Could not reproduce on ASP.NET Core 5
- Could not reproduce on ASP.NET Core 6 when creating individual factories per test method

### To Reproduce

Detailed description and repro integration tests here:
[Repro hang of integration tests after upgrading to ASP.NET Core 6 - Pull Request #1 · angularsen/NET6-Testing](https://github.com/angularsen/NET6-Testing/pull/1)

### Exceptions (if any)

On Ubuntu, deadlock.
On Windows (as expected):
```
[Test Class Cleanup Failure (Test.Net6WebApi.Repro_RED_ConcurrentTestsOnSharedFactory+TestClass3)]: System.AggregateException : One or more hosted services failed to stop. (A task was canceled.)
---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
----- Inner Stack Trace -----
   at Test.Net6WebApi.Setup.MySlowStoppingHostedService.StopAsync(CancellationToken cancellationToken) in C:\dev\digma\NET6-Testing\src\Test.Net6WebApi\Setup\MySlowStoppingHostedService.cs:line 30
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
```

### Further technical details
- ASP.NET Core version: 6.0.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Rider 2021.2.2, VS 2022 17.1.0 Preview 1.0
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

WSL Ubuntu 20.10:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  21.10
 OS Platform: Linux
 RID:         ubuntu.21.10-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [/usr/share/dotnet/sdk]
  5.0.403 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Windows:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by halter73** [comment] 2021-12-01 00:28
> Hosted service with Task.Delay(TimeSpan.FromSeconds(5), ct) in its IHostedService.StopAsync(), which is used to flush logs and telemetry before the API is allowed to shut down.

I'm surprised this doesn't hang in .NET 5. Why should `WebApplicationFactory.Dispose()` not wait for `StopAsync()` to complete on the `IHost` and all its `IHostedServices`? if the issue is just the blocking, `WebApplicationFactory` implements `IAsyncDisposable` as well.

**Comment by angularsen** [comment] 2021-12-01 08:47
@halter73 It is not the 5 second hang that is the problem, that is naturally expected as shown in Windows logs above. What is unexpected is deadlock and infinite hang on Ubuntu, only on .NET6.

**Comment by BrennanConroy** [comment] 2021-12-02 19:53
Could you try using a Noop IHostLifetime implementation and see if the hang still occurs.
See https://github.com/dotnet/aspnetcore/pull/23761/files for reference.

**Comment by angularsen** [comment] 2021-12-02 20:07
@BrennanConroy I am certain that a Noop IHostLifetime works, because the workaround I described was to remove the Task.Delay in StopAsync of our IHostedService implementation. This fixed our tests. I believe this is effectively the same as the Noop implementation, because our implementation did little beyond logging and waiting on stop.

**Comment by mitchdenny** [comment] 2023-06-26 03:10
Looks like @BrennanConroy's change merged in, I'm assuming this is the long term fix for this issue. Re-open if it isn't Brennan.

**Closed by mitchdenny** 2023-06-26 03:10 UTC
Labels: investigate, area-mvc, Needs: Attention :wave:, feature-mvc-testing, area-minimal

**Comment by gdoron** [comment] 2023-07-16 08:00
@mitchdenny which change were you referring to? Can you kindly add a link so I could see if it would fix our issue as well?
