### ISSUE TITLE
[Blazor Wasm] How should I configure the project so that Manifest Version changes with each release?

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#22934] opened 2020-06-14 12:57 UTC
### Describe the bug
How should I configure the project so that Manifest Version changes with each release? Now when I publish, the version has not changed, so the PWA's cache cannot be updated.

### To Reproduce

My project Ant Design Blazor: https://github.com/ant-design-blazor/ant-design-blazor
Published files is here: https://github.com/ant-design-blazor/ant-design-blazor.github.io

### Further technical details
- ASP.NET Core version 
    3.1
- Include the output of `dotnet --info` 
    3.1.301
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version 
    vs 16.6

**Comment by javiercn** [comment] 2020-06-15 11:32
@ElderJames thanks for contacting us.

We had an issue in this area that we have addressed and will be released in a future patch update, so you won't have to do anything (it'll auto-update). In the meantime, you can update a version manually in service-worker.published.js and that will force the update.

Dupe of #22353

**Closed by javiercn** 2020-06-15 11:32 UTC
Labels: area-blazor
