### ISSUE TITLE
DataProtection aka.ms link go to the repo

### ISSUE THREAD

**Issue by kant2002** [dotnet/aspnetcore#41029] opened 2022-04-04 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I receive exception about data protection. In the message there link http://aka.ms/dataprotectionwarning That link redirect to GitHub instead of docs webstite

### Expected Behavior

I assume that aka.ms link should point to the article which can help troubleshoot the issue.

**Comment by blowdart** [comment] 2022-04-04 14:45
There is, I just haven't had the time. 

Dupe of https://github.com/dotnet/aspnetcore/issues/22029

**Closed by blowdart** 2022-04-04 14:45 UTC
