### ISSUE TITLE
Blazor Webassembly Project Template unable to run with container orchestration docker-compose

### ISSUE THREAD

**Issue by timmi-on-rails** [dotnet/aspnetcore#23715] opened 2020-07-06 21:18 UTC
When adding the container orchestrator docker-compose to the current Blazor Webassembly Template (3.2.0),
the app does not show and I get a 404 not found.

When debugging the problem I found out that adding the setting:
```<DockerDevelopmentMode>Regular</DockerDevelopmentMode>```
solves the problem.

The reason seems to be that the DockerDevelopmentMode=Fast (Default) does not copy the BlazorApp1.Client project into the container.

However, when running the BlazorApp1.Server with the docker launchSetting directly it works without "DockerDevelopmentMode=Regular". Inside the container the "/src" directory holds the complete solution root. (contrary to the container orchestrator variant)

This seems inconsistent.

Can somebody confirm?

Here is the **not working** solution: https://github.com/timmi-on-rails/grpc/raw/master/BlazorApp1.zip

**Comment by javiercn** [comment] 2020-07-07 10:47
@timmi-on-rails thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/21828. The reason is that when using orchestration the server project is not the main project anymore and that confuses static web assets.

**Closed** 2020-07-07 10:47 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor, blazor-wasm
