### ISSUE TITLE
[BLAZOR] EditForm tag does not work correctly in .Net6-preview4

### ISSUE THREAD

**Issue by taha-ghadirian** [dotnet/aspnetcore#33432] opened 2021-06-10 15:44 UTC
### Describe the bug
EditForm built in Blazor component does not work correctly in .Net6-preview4. It works correctly in .Net 5.0.6

### To Reproduce
```
@page "/My/Custom/Page"

<EditForm Model="Test">
        <div class="form-group">
            <label>name</label>
            <InputText @bind-Value="Test.Name" class="form-control" />
        </div>
</EditForm>

@code {

    public class test
    {
        public string Name { get; set; }
    }

    public test Test { get; set; }
}
```

### Exceptions (if any)
```
dotnet.6.0.0-preview.4.21253.7.js:1 * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1373, condition `<disabled>' not met
```
![image](https://user-images.githubusercontent.com/36773254/121555224-0f5a2280-ca28-11eb-8bed-4d6a2146805d.png)

### Further technical details
![image](https://user-images.githubusercontent.com/36773254/121555434-40d2ee00-ca28-11eb-97fc-a5c6c31edffc.png)

**Comment by mkArtakMSFT** [comment] 2021-06-10 16:33
Thanks for contacting us.
Are you running this using `dotnet watch`?

**Comment by taha-ghadirian** [comment] 2021-06-10 17:40
> Thanks for contacting us.
> Are you running this using `dotnet watch`?

Yes, I run the application with `dotnet watch run` for Hot reload in new preview version of dotnet.

**Comment by pranavkm** [comment] 2021-06-10 20:11
This is likely a dupe of https://github.com/dotnet/aspnetcore/issues/33319. We had an issue in Blazor and hot reload that should be remedied in the preview6 release.

**Closed** 2021-06-11 07:30 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Needs: Attention :wave:, Status: Resolved, area-blazor
