### ISSUE TITLE
Razor Conditional Css not being bundled in Maui RCL

### ISSUE THREAD

**Issue by John0x** [dotnet/aspnetcore#43772] opened 2022-09-06 09:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It seems like the isolated css is not being bundled if your razor component library is using Maui, or has it enabled.
Usecase: I do have a component library that contains both razor components and some maui specific code, therfore I need maui support.

### Expected Behavior

isolated css should be bundled and delivered to the referencing project

### Steps To Reproduce

Create a project using the RCL template and add the following to the project file to enable maui:
```

        <UseMaui>true</UseMaui>
```

There is no bundled css for the isolated css to be found in the obj directory after building and it's not being provided to referencing projects.

### .NET Version

6.0.400

### Anything else?

IDE (not relevant thhough): Jetbrains Rider
OS: Mac M1
Output of info:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  /Users/redacted/code/ash-money/AshMoney/global.json

Host:
  Version:      6.0.8
  Architecture: arm64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]


```

**Comment by javiercn** [comment] 2022-09-06 09:47
@John0x thanks for contacting us.

This is not something we currently support. Razor class libraries need to only contain C# and Razor code. We recommend you split your razor code in a regular razor class library and consume it from your Maui class library.

**Comment by javiercn** [comment] 2022-09-06 09:52
Duplicate of https://github.com/dotnet/maui/issues/3288

**Closed** 2022-09-06 09:52 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor
