### ISSUE TITLE
Globalization for Server/Auto Resets After Initial Load

### ISSUE THREAD

**Issue by beowulf29a** [dotnet/aspnetcore#52885] opened 2023-12-18 21:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following the documentation on https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization I was able to get I18N working.  However after further testing using Auto/Server I found odd behavior.

using either:
```
@rendermode RenderMode.InteractiveAuto
@rendermode RenderMode.InteractiveServer
```
(my example test was the "Weather.razor" template page but expanded to use N2 formatting for numbers and moved the int(s) to double(s))
When the data loads (a quick flicker) I see the data in the expected formatting on the table, but then the component reloads and the culture formatting is gone (note: in the case of the InteractiveAuto, the reinit doesn't happen until interacting with the component).

### Expected Behavior

The globalization is respected in Server render modes.

### Steps To Reproduce

1. Follow localization setup in: https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization
2. Set weather render mode to:
`@rendermode RenderMode.InteractiveServer`

3. Begin debug
4. Set sensor to Chilean Spanish (es-CL)
5. Refresh page

### .NET Version

8.0.100

**Comment by javiercn** [comment] 2023-12-20 10:41
Likely related to https://github.com/dotnet/aspnetcore/issues/26941

**Comment by javiercn** [comment] 2023-12-20 10:42
We don't automatically flow the culture, so that's something you need to do yourself via any of the existing mechanisms available (pass it as a parameter, prerrendered component state, or similar)

**Comment by mkArtakMSFT** [comment] 2024-01-11 17:48
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/26941

**Closed by mkArtakMSFT** 2024-01-11 17:48 UTC
Labels: enhancement, area-blazor, Pillar: Complete Blazor Web
