### ISSUE TITLE
Some nullable fields should not be nullable [Identity]

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/aspnetcore#18679] opened 2020-01-30 06:43 UTC
Hi,

I think `AspNetRoleClaims` table doesn't do anything without `ClaimType` and `ClaimValue`, am I right or I missed something?

__Update__: There are other `nullable` columns too but they should not be. for example `Name` in `AspNetRoles` table.

**Comment by blowdart** [comment] 2020-01-30 20:11
You can have claims without values. But given the cross platform nature of EF, and the potential for lack of nullability in some targets it does no harm. Name is also optional, so it can and should be nullable.

**Comment by dehghani-mehdi** [comment] 2020-01-31 04:56
You mean we can have Role without name? it doesn't make sense.

**Comment by blowdart** [comment] 2020-02-05 20:12
Making them not nullable would be a schema change. Our managers do null checks before writing. Unless you're writing your own managers this isn't really an issue.

Closing as this is by design.

**Closed by blowdart** 2020-02-05 20:12 UTC
Labels: area-identity

**Comment by dehghani-mehdi** [comment] 2020-02-06 04:43
I think your design has some serious issues.

If I do something like this issue and [this one](https://github.com/dotnet/aspnetcore/issues/18680) in my code, my boss will fire me immediately.

> Our managers do null checks before writing. 

Really?! so make all the columns `NVARCHAR(MAX)` and then in your managers do all checks and converting stuff.
