### ISSUE TITLE
WebAssembly compilation fallback logic is wrong. May need some further docs about configuring memory limits.

### ISSUE THREAD

**Issue by Edivad99** [dotnet/aspnetcore#42055] opened 2022-02-09 10:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I developed my own PWA application using Blazor. The app works normally on my computer and phone. But on my second phone the application doesn't have time to load and an error appears.
I connected my phone to the pc and through the chrome devtools I went to see the log on the console and I found the following errors.
```
Streaming compilation failed. Falling back to ArrayBuffer instantiation.  RangeError: WebAssembly.instantiate(): Out of memory: wasm memory

blazor.webassembly.js:1 TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
await in (anonymous) (async)		
(anonymous)	@	blazor.webassembly.js:1
createWasm	@	dotnet.6.0.2.hy3rmx5lfa.js:1
(anonymous)	@	dotnet.6.0.2.hy3rmx5lfa.js:1

blazor.webassembly.js:1 Uncaught (in promise) TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
    at blazor.webassembly.js:1:36928
    at async blazor.webassembly.js:1:36900
    at async blazor.webassembly.js:1:36636
(anonymous)	@	blazor.webassembly.js:1
await in (anonymous) (async)		
(anonymous)	@	blazor.webassembly.js:1
createWasm	@	dotnet.6.0.2.hy3rmx5lfa.js:1
(anonymous)	@	dotnet.6.0.2.hy3rmx5lfa.js:1
```

The PWA is distributed as AzureStaticApps.
Some specifics about the phone having these problems:
- Phone model: Samsung Galaxy J5 (2016)
- Android version: 7.1.1
- Chrome version: 98.0.3758.87
- Edge version: 97.0.1702.78

I attach some photos of the console and network traffic

![Schermata 2022-02-09 alle 11 09 33](https://user-images.githubusercontent.com/25778604/153178212-a0997725-76e2-421a-b2cb-73ad04f42b57.png)
![Schermata 2022-02-09 alle 11 09 53](https://user-images.githubusercontent.com/25778604/153178219-e515b52d-be84-4c6a-b404-1f969100d14c.png)
![Schermata 2022-02-09 alle 11 10 04](https://user-images.githubusercontent.com/25778604/153178226-5643e5ee-6227-4929-ba16-d24ffa275f18.png)
![Schermata 2022-02-09 alle 11 16 02](https://user-images.githubusercontent.com/25778604/153178231-9fc35341-7833-4973-9da9-954328c1ca1f.png)

### Expected Behavior

The PWA should work just as well as it does on the PC and other phones

### Steps To Reproduce

Simply, create a PWA project and try it out on low-end phones.

### .NET Version

6.0.102

**Comment by TanayParikh** [comment] 2022-06-06 16:39
@pavelsavara should this issue be duped against https://github.com/dotnet/aspnetcore/issues/40547?

**Comment by pavelsavara** [comment] 2022-06-06 16:45
Yes, both of them are same area, so they could be unified. I updated my comment here, but each of them have some good details too.

**Comment by TanayParikh** [comment] 2022-06-06 20:27
Cross-linking: https://github.com/dotnet/aspnetcore/issues/5617

**Comment by SteveSandersonMS** [comment] 2022-06-07 16:46
@TanayParikh Reading the comments above, it sounds like there are three separate issues:

 * In some cases people may have the wrong content-type on the .wasm response. Action: we should check the content-type, and not attempt streaming if it's wrong.
 * In other cases, even when the content-type is wrong, the browser might give an OOM error during module instantiation. Action: we should try to get a repro of this, and figure out if there's a way to change the compilation settings to set a different memory limit to fix it. If so, we can then document that solution, or even consider changing the default.
 * Regardless of all this, our fallback logic is nonsensical as it would never work. Action: stop attempting fallback - just use either streaming or non-streaming compilation based on the content-type.

What do you think? Does that match you interpretation?

**Comment by SteveSandersonMS** [comment] 2022-06-07 16:59
@TanayParikh Thanks for confirming.

@mkArtakMSFT I've updated this issue title to reflect our newer understanding. This is something we should try to address in .NET 7 if we can, as it's relatively cheap (~2 days I'd guess).

**Comment by sehlers2112** [comment] 2022-06-14 01:20
@SteveSandersonMS I ran into this problem after I updated a .NET 5 project to .NET 6. Many of my users have low-end devices so they started getting the issue popping up en-masse. I was able to get it to reproduce like clockwork using the boiler plate Blazor Web Assembly project with PWA and Host Site enabled.

If you keep refreshing the homepage on a low end android device with chrome it will periodically fail with the  "Out of memory: wasm memory" error, However, I found that if you add an <input> to the Blazor page and click into the field before refreshing it causes the page to continually get the error and never load. The only way to recover is to close the browser and relaunch. This is a death sentence for authentication and data entry workflows that use redirects in the blazor application as the user will be unable to continue.

I confirmed by downgrading my project to .NET 5 that the issue is only present in .NET 6.

I am concerned that this is being addressed in .NET 7, as you know we have already reached end of support for .NET 5 on May 11th and .NET 7 is currently slated for November. What is your recommendation for us in the mean time?

I can provide additional repro information if needed, i set up a test site here that is the blazor pwa template with an input field added to the index page. [](https://blazordotnet6lowendoom.azurewebsites.net/)

**Comment by StephenEhlers** [comment] 2022-06-14 05:16
Following up on my last post, I did some testing in chrome memory profiling and I think there is a memory leak in the .NET 6 implementation of web assembly compared to .NET 5.

I have 3 snapshots from this blazor webpage using .NET 6.

Snapshot 1: Taken right after initial load in the browser.
Snapshot 2: Taken after an F5 refresh of the page. 
Snapshot 3: Taken after selecting an input field in the webpage and then refreshing.

![image](https://user-images.githubusercontent.com/4857673/173494657-63105940-3130-406a-98bb-e5ca71fc572c.png)

as you can see the memory doubled when an input field was selected.

Here is the exact same test in .NET 5.

![image](https://user-images.githubusercontent.com/4857673/173498524-c4a6056a-dd01-4ad6-a13b-6d31b08025b0.png)

So yes, although the logic behind retry after memory failure is a problem, the real problem, and why this code is executing so frequently on old devices is that it seems there is a memory leak between refreshes.

**Comment by StephenEhlers** [comment] 2022-06-15 02:04
One more follow up from me, I discovered that my production deployment was taking up about 8x the memory than my local development instance for a total of 512MB, with the refresh memory leak it caused devices to go over 1GB. 

Testing locally out of my visual studio debugger I could not reproduce the memory issue. So I set up a local IIS server and deployed to it with a local file publish process. With this IIS instance I was able to reproduce the 500MB issue. I then compared the output of the visual studio debug instance to the IIS published instance. I found that the generated _framework/dotnet.6.0.x.js files were substantially different and found the root of my problem:

![image](https://user-images.githubusercontent.com/4857673/173716640-005a6743-263c-42f9-ba29-927fb5af4eab.png)

looking into this INITIAL_MEMORY property I found some github forum posts saying that for Development environments it will default to 16777216 (16MB) and Production environments will default to 536870912 (512MB). Normally this is not a huge deal but with the Memory Leak in .NET 6 and chrome after refresh it is a major problem. 

In C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.4\Sdk\WasmApp.targets it says the following in the documentation section:

![image](https://user-images.githubusercontent.com/4857673/173717748-c302e2b3-6778-4eb1-b14d-6de2ad42f2a2.png)

Knowing this, I then tried adding the referenced EmccTotalMemory property to my Blazor.Client csproject file.

`<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EmccTotalMemory>16777216</EmccTotalMemory>
  </PropertyGroup>`

I rebuilt and published to my local IIS site and thankfully the 512MB was now down to ~50MB. I then published to a public test instance and re-tested all of my failing devices and they are now all working great, even with the refresh memory leak because it goes from 50-60MB to 120MB instead of 512MB to 1GB.

@SteveSandersonMS For me anyway the priority of fixing this Refresh Memory Leak is reduced as I found the workaround to reduce total inital memory, but I feel it is still important to fix this sooner than later. This could be causing lots of random issues during app use, granted mostly for low end devices, but this is quite a bit of a difference from the total memory use of the same app running on .NET 5. 

Additionally, I do not like the logic behind having 16MB for Development builds and 512MB as the initial memory size for Production. I get that you may want development instances to show "True Memory Usage" so it starts small and then auto expands to what it needs so Devs can more easily see what their app is utilizing. And I get that allocating memory on the fly might result in poorer performance, so for Production builds it auto allocates 512MB. However, to me this falls into the category of pre-optimization. I would rather that both my Development and Production instances behaved the same for memory allocation until I choose to optimize it. This difference in behavior caused a problem to only represent in a production instance with no natural way to diagnose it in a dev environment without tearing apart the OOB Microsoft publish process. 

Anyway sorry for the book and hopefully if anyone else is running into this they can take the same steps as me to work around it for now.

**Comment by kg** [comment] 2022-06-15 02:29
> So yes, although the logic behind retry after memory failure is a problem, the real problem, and why this code is executing so frequently on low-end devices is that it seems there is a memory leak between refreshes.

Any memory leak across refreshes is a different issue, so it would be great if you filed a report about it. That way it won't get lost if this issue is closed as resolved.

Under normal circumstances a browser app shouldn't be able to "leak" memory between page refreshes, so if it happens it's almost always a browser bug. A browser bug that can cause an OOM for production applications is pretty bad! It's good that lowering the default memory size has mitigated it for you, but I'd be concerned that the bug will cause problems again if your app ever starts using more memory, so it would be great if we could get an issue opened for that so it can be investigated separately and tracked.

**Comment by Norsotec** [comment] 2022-07-06 00:14
@StephenEhlers which version of the sdk did you use? Trying to find a workaround the last couple of days but failed.

<EmccTotalMemory>16777216</EmccTotalMemory> causes an error
initial memory too small, 21366208 bytes needed

so i tried 24576000 which can be published successfully but shows up same OOM problems on my 2GB Ram Android Devices. (tried all common web browsers)

on my 6GB Android it works on every browser.

same problem with SDK 6.0.101, 6.0.301 or 7.0.100-preview.5

same problem with changing value in WasmApp.Native.targets gloably.

can't wait for future releases, my customer needs AOT asap. hope this will be fixed soon. :-(

**Comment by StephenEhlers** [comment] 2022-07-06 01:36
@Norsotec From the details you provided it sounds like you are running into a different issue than me. 

My issue was that VS publish process defaults to allocating 500MB of ram up front and then doubling to 1GB with the input field highlight refresh issue I reported (which occurs when someone types in their username and password and then gets redirected to an authentication pipeline). But my app never actually needed anywhere near 500MB. After initialization my entire app was only consuming a total of ~68MB. 

Your issue is that .NET says it needs 21366208 bytes to initialize or about ~20MB and it cannot and runs into an OOM error. Presumably on a 2GB Ram Android device about 50% is taken up by the OS or other running apps. So you probably have a working memory set of about 1GB, so the 20MB that your blazor app is asking for should be easily allocated, but since it is not that means that either there is not enough free memory available on the device, or something else in your web app is eating up all the memory before .NET has a chance to finish initializing itself.

My recommendation would be to try and publish a sample client-side web assembly blazor app and see if that loads on your low-end device. If it does then you will have to dig into what the rest of your app is doing before .NET loads to see where all the memory is going.

**Comment by Norsotec** [comment] 2022-07-06 20:57
@StephenEhlers thanks for the recommendation. You were right, i am able to compile AOT EmccTotalMemory = 24576000 and i works even on 1GB Android devices with chrome browser.

trying now to dig into my app to find the reason for my problem. - thanks!

**Closed** 2022-07-29 09:19 UTC
Labels: bug, area-blazor
