### ISSUE TITLE
A compatible installed .NET Core SDK for global.json version [3.1.201] from [D:\local\repository\global.json] was not found

### ISSUE THREAD

**Issue by jozefizso** [dotnet/aspnetcore#20982] opened 2020-04-18 08:25 UTC
### Describe the bug
The .NET Core SDK for latest LTS release (3.1.3, SDK 3.1.201) does not exists on Azure App Services.

### To Reproduce
Use **global.json** with latest LTS SDK:
```
{
  "sdk": {
    "version": "3.1.201"
  }
}
```

Azure deployment log:
```
Handling ASP.NET Core Web Application deployment.
A compatible installed .NET Core SDK for global.json version [3.1.201] from [D:\local\repository\global.json] was not found
  1.1.14 [D:\Program Files (x86)\dotnet\sdk]
Install the [3.1.201] .NET Core SDK or update [D:\local\repository\global.json] with an installed .NET Core SDK:
  2.1.509 [D:\Program Files (x86)\dotnet\sdk]
  2.1.513 [D:\Program Files (x86)\dotnet\sdk]
  2.2.109 [D:\Program Files (x86)\dotnet\sdk]
  3.1.103 [D:\Program Files (x86)\dotnet\sdk]
Failed exitCode=-2147450735, command=dotnet restore 
```

### Further technical details
- ASP.NET Core version **3.1.3** (SDK 3.1.201)
- Include the output of `dotnet --info`
- Visual Studio 2016 16.5.4

**dotnet --info**

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.103
 Commit:    6f74c4a1dd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\3.1.103\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  1.1.14 [D:\Program Files (x86)\dotnet\sdk]
  2.1.509 [D:\Program Files (x86)\dotnet\sdk]
  2.1.513 [D:\Program Files (x86)\dotnet\sdk]
  2.2.109 [D:\Program Files (x86)\dotnet\sdk]
  3.1.103 [D:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.2 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.2 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment] 2020-04-19 04:02
@shirhatti is .NET Core 3.1.201 already available in Azure AppService?

**Comment by shirhatti** [comment] 2020-04-20 16:46
No. App Services has the 3.1.103 SDK.

3.1.201 and 3.1.103 carry the same runtime, but carry different versions of MSBuild (16.5 vs 16.4).
This is described on the .NET Core donwload page- https://dotnet.microsoft.com/download/dotnet-core/3.1

@jozefizso is there any reason you need exactly 3.1.201?

cc @bradygaster

**Comment by jozefizso** [comment] 2020-04-21 14:13
The 3.1.201 SDK is what I see on the .NET SDK download page. And I use Visual Studio 2019 16.5, therefore I have this SDK. When I change the **global.json** to use **3.1.103**, Visual Studio cannot open project as the SDK is not compatible with it.

![image](https://user-images.githubusercontent.com/287778/79875929-a7dbb080-83ea-11ea-9743-5761b72eb4c4.png)

As the release of both VS 16.5 and SDK 3.1 was a month ago, I would except I can use the latest SDK on Azure. Especially when it is required by the Visual Studio. 

PS: This is the latest LTS SDK which I would expect is available immediately in the Azure for use by customers.

**Comment by bradygaster** [comment] 2020-04-23 17:12
@jozefizso - as @shirhatti mentioned, the latest SDK running on App Service is 3.1.103. If you need a different SDK you can always use self-containment, which would give you the ability "pin" your SDK. Then, when you publish your code you'll publish everything it needs with it and you control your own destiny from an SDK and runtime perspective. 

Self-contained deployments are supported in the VS tooling as well. 

Does this help? Our team doesn't know a firm ETA on the arrival of the newer SDK in App Service. I could check with our partners but, if you use self-contained deployment, you're good.

**Comment by jozefizso** [comment] 2020-04-23 17:20
Nope, this breaks our deployment script. I don't understand why the SDK available to build applications is not available on the Azure service?

**Comment by Pilchie** [comment] 2020-04-23 19:19
There are two current, supported SDKs for the latest runtime.  That's because one is for an LTS version of Visual Studio (16.4) and has tooling components that match what's in that version of Visual Studio, and the other is for the latest version of Visual Studio.

App Service today has the one which supports the LTS version of Visual Studio.

Is the problem that you have global.json?  Why do you need one if so?

**Comment by jozefizso** [comment] 2020-04-23 19:33
We use **global.json** because Visual Studio nor Azure App Service cannot resolve the correct SDK from the project file. Therefore we must manually pin it.

When 16.4 is the LTS of Visual Studio, why I'm forced to upgrade to 16.5?

**Comment by Pilchie** [comment] 2020-04-23 19:41
The SDK is designed to be compatible.  Normally the latest SDK will be used, but should have support for any older runtimes.  Except in exceptional circumstances, you shouldn't *need* to use a global.json.

As for VS updating policy - default installations are on the current servicing train, you have to opt into being on a "Servicing Baseline" (the VS term for LTS).  See https://docs.microsoft.com/en-us/visualstudio/install/update-servicing-baseline?view=vs-2019 for details.

**Comment by jozefizso** [comment] 2020-04-23 19:48
On several occasions the Azure App Service did not select the correct SDK from the project file and I was forced to use **global.json**

The same for Visual Studio - it is clueless about the correct SDK version without help from **global.json**

**Comment by Pilchie** [comment] 2020-04-23 20:59
You don't (can't) specify an SDK version in the project file.  You choose the Target Framework that the app will run against (and the references to compile against that represent that runtime).

Both VS and App Services will pick the newest SDK in the absence of a global.json, which is the by design behavior. However, at least as of the 3.0.100 SDK (and likely before), the newest SDK should be able to compile projects targeting any version of the runtime.

If there are examples where that is NOT working, I suggest filing them with details on https://github.com/dotnet/sdk.

In general, rolling out new SDKs to App Service is quite a difficult endeavor already, while we're working on improving that, it's likely that there will always be periods of time where the latest SDK isn't available on App Services, and there is no guarantee that every patch version of the SDK will be present.  If you need precise control of the SDK that your app is built with, I suggest deployed already built assets to Azure App Services, either using a CI/CD system (like GitHub [Actions](https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions), or Azure DevOps Pipelines), or WebDeploy/[VS Publish](https://docs.microsoft.com/en-US/visualstudio/deployment/quickstart-deploy-to-azure?view=vs-2019).

Closing, as I don't think there is an immediate action for us to take here.

**Closed by Pilchie** 2020-04-23 20:59 UTC
Labels: area-platform

**Comment by Pilchie** [comment] 2020-04-23 21:13
You still haven't described why you need Visual Studio and App Services to use the same SDK?  What problems are you running into?

**Comment by jozefizso** [comment] 2020-04-23 21:15
The issue is Visual Studio does not recognise 3.1.103 SDK and the Azure service does not know about 3.1.201 SDK. So I'm stuck with non-functional build on either side.

**Comment by Pilchie** [comment] 2020-04-23 21:17
But if you remove the global.json, and let each use the SDK it has, what problems do you run into?

**Comment by jozefizso** [comment] 2020-04-23 21:24
Azure service will compile the project with random SDK (eg. my 2.0 project was compiled with 1.0 SDK, or 2.1 LTS got compiled with 2.2 SDK - this is utter nonsense to let build project and have no control over how it will be compiled).

On the Visual Studio side it may not even open the project when it cannot determine correct SDK based on project file.

**Comment by Pilchie** [comment] 2020-04-23 21:27
As I said above, if you need absolute control over what SDK builds your project, you shouldn't be relying on Azure App Services automatic build support through Kudo.  Instead, manage that yourself using a CI/CD pipeline, or by publishing compiled artifacts using VS or web deploy.

As for the VS issue, please file a bug on https://github.com/dotnet/projects-system if you have a repo of a case where VS is failing to open a project with the latest SDK.

**Comment by tolu** [comment] 2020-05-11 11:33
Just ran into the same issue, are there any plans on supporting SDK 3.1.201 on AppServices?
