### ISSUE TITLE
Server Side Typescript Hub

### ISSUE THREAD

**Issue by Javaman2** [dotnet/aspnetcore#22869] opened 2020-06-12 11:23 UTC
Please create a Typescript Hub implementation.

It will be a industry disrupter. 

No more routing when using the proxy method. Servers and clients have direct access to methods instead.

Full duplex and secure, what's not to love.

It could be MSFTs entry into Isomorphic architecture. 

The open source community would love this once they see the possibilities.

Just say no to Express et. al.

**Comment by BrennanConroy** [comment] 2020-06-12 21:06
Dupe of https://github.com/dotnet/aspnetcore/issues/15198

**Closed by BrennanConroy** 2020-06-12 21:06 UTC
Labels: area-signalr
