### ISSUE TITLE
Unknown error occurred while trying to verify Failed to find a valid digest in the 'integrity' attribute for resource wth computed SHA-256 integrity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36993] opened 2021-09-26 22:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unknown-error-occurred-while-trying-to-v/1502096)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.10.4]
When publishing a Blazor server project, I get these errors

Unknown error occurred while trying to verify integrity.
<domain>l/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://<domain>/_framework/System.Runtime.Caching.dll' with computed SHA-256 integrity 'pOMx6F1i+JIor9vj4eAFonjR3VSGug3IieZs0PUZIcs='. The resource has been blocked.

When publishing the same project (unchanged) with VS 2019, there is no issue.

---
#### Feedback Bot on 8/12/2021, 10:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/13/2021, 00:42 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-09-27 16:39
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/36994

**Closed by mkArtakMSFT** 2021-09-27 16:39 UTC
Labels: area-blazor, Author: Migration Bot :robot:
