### ISSUE TITLE
[Blazor-WASM 3.2 Preview 2] Deployment to Github pages not working

### ISSUE THREAD

**Issue by chanan** [dotnet/aspnetcore#19775] opened 2020-03-11 18:43 UTC
I deploy my CSB / WASM Blazor projects to Github pages, but it seems to no longer working.

Running a web server locally loads up the CSB fine, but once deployed to Github pages I get the following error:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://chanan.github.io/BlazorTypography/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js' with computed SHA-256 integrity 'FJC7gQVpQ5ZmLsci9Oxg/MIH96sVbWXaxI5G3fM7Doc='. The resource has been blocked.
```

The CSB is here: https://chanan.github.io/BlazorTypography/
And the source folder is: https://github.com/chanan/BlazorTypography/tree/master/docs

**Comment by javiercn** [comment] 2020-03-12 14:01
@chanan thanks for contacting us.

It is likely that what's going on here is that when you upload the output is transforming the LF into CRLF or viceversa.

I suggest you add a .gitattributes file to the source folder with `autocrlf=false` to prevent the automatic conversion for the lines

**Comment by SteveSandersonMS** [comment] 2020-03-12 14:35
Closing as a duplicate of https://github.com/dotnet/aspnetcore/issues/19796, since that one now has more info. Thanks for reporting this, @chanan!

**Closed by SteveSandersonMS** 2020-03-12 14:35 UTC
Labels: area-blazor, blazor-wasm

**Comment by chanan** [comment] 2020-03-12 16:04
Just in case anyone finds this issue. The above doesn't work. This does: https://github.com/dotnet/aspnetcore/issues/19796#issuecomment-598269333
