### ISSUE TITLE
C# Semantic Colorization not complete in some diagnostic instances

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#26646] opened 2020-10-06 21:17 UTC
```razor
<button class="btn btn-primary" @onclick="@IncrementCount">Click me</button>

@functions {
    int currentCount = 0;

    void IncrementCount(string parameter)
    {
        currentCount++;
    }
}
```

If you do the above currently you won't get correct colors for `IncrementCount` on line 1, but if you remove the offending `parameter` from that method it shows. My best guess is C# isn't passing us that particular region or we're not remapping it correctly.

**Comment by NTaylorMullen** [comment] 2021-03-29 19:58
Duplicate of:
- https://github.com/dotnet/aspnetcore/issues/26975
- https://github.com/dotnet/aspnetcore/issues/26753

**Closed by NTaylorMullen** 2021-03-29 19:58 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, bug, feature-razor.languageserver, feature-razor.vs
