### ISSUE TITLE
Blazor WebAssembly not refreshing on IOS

### ISSUE THREAD

**Issue by nss12** [dotnet/aspnetcore#23372] opened 2020-06-26 02:27 UTC
I am running into a problem where my PWA blazor webassembly app that was added to IOS home screen is way too old and not refreshing.
I tried deleting and re-adding it several time but it always bring up old app.

When browsing my blazer app using chrome on IOS it shows the latest one.

when browsing using Safari it is still showing the old one, how do a clear the cache on iphone? 
using IPhone XS Max with v 13

**Comment by javiercn** [comment] 2020-06-26 10:10
@nss12 thanks for contacting us.

You might be running into an issue that we fixed recently with our [PWA](https://github.com/dotnet/aspnetcore/issues/22353#issuecomment-636765665) support. 

I would check to see if applying the workaround described there works. If that doesn't work, let us know.

**Comment by javiercn** [comment] 2020-06-29 14:16
Closing this issue since it is a dupe of #22353

**Closed by javiercn** 2020-06-29 14:16 UTC
Labels: area-blazor, blazor-wasm
