### ISSUE TITLE
Why `Result.ValidationProblem` requires `IDictionary<string, string[]>` instead of `IReadOnlyDictionary<string, string[]>`?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/aspnetcore#46689] opened 2023-02-15 20:38 UTC
## Background and Motivation

It does not allow me to pass an immutable dictionary or F# dictionary as is

## Proposed API

Add overload that takes `IReadOnlyDictionary<string, string[]>` and deprecate `IDictionary<string, string[]>`

**Comment by brunolins16** [comment] 2023-02-16 18:05
Duplicate of #41899

**Closed by brunolins16** 2023-02-16 18:05 UTC
Labels: api-suggestion, area-web-frameworks
