### ISSUE TITLE
[Blazor] Include mouse position in page coordinates in UIDragEventArgs

### ISSUE THREAD

**Issue by SamVogelskamp** [dotnet/aspnetcore#7182] opened 2019-02-01 08:43 UTC
Expand the current UIDragEventArgs by `pageX` and `pageY` variables.

**Comment by mkArtakMSFT** [comment] 2019-02-10 04:51
@danroth27, FYI regarding the milestone and priority assignment.

**Comment by rynowak** [comment] 2019-02-22 04:01
This would include providing extra information on the event args in addition to what the DOM provides. While this is probably the most straightforward way to proceed, we've considered it in the past and didn't do it right away.

Doing something like this would involved a more thorough look at the events in general and trying to understand what else we would want to polyfill because there are a few notable cases (scrolling is similar).

**Comment by pranavkm** [comment] 2020-07-06 20:53
Dup of https://github.com/dotnet/aspnetcore/issues/17552

**Comment by KristianMariyanov** [comment] 2020-07-24 07:08
It will be nice to expose `PageX` and `PageY` properties in the `MouseEventArgs` too. Currently, it's impossible to calculate the absolute position of the visible part of the screen.

**Comment by SteveSandersonMS** [comment] 2020-10-14 14:23
We already have `ScreenX`/`ScreenY` and `ClientX`/`ClientY` and  `OffsetX`/`OffsetY`. I think these will cover typical use cases.

If there are needs for even more types of coordinate, we'd handle that through #17552, so I'll close this as a duplicate of that.

**Closed by SteveSandersonMS** 2020-10-14 14:23 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor, enhancement
