### ISSUE TITLE
System.ArgumentException in RouteHandlerAnalyzer with Minimal API

### ISSUE THREAD

**Issue by malcartwright** [dotnet/aspnetcore#41794] opened 2022-05-23 05:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have started seeing exceptions reported by the RouteHandlerAnalyzer when building our Minimal API projects that built fine for the past 6 months. The projects use a separate class with appropriate static methods to act as the delegates from `app.Map{method}` calls. These errors did not occur previously.

In the GitHub repo linked in the Steps to Reproduce section we see the problem occurs whenever the class used to delegate methods is in a file other than `Program.cs`, regardless of whether the class has no namespace definition.

The warning raised during build is:
`CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'.`

### Expected Behavior

Static or instance methods contained in files external to `Program.cs` can be used to execute Minimal API route delegates.

### Steps To Reproduce

I've created a sample project using the default Minimal API template at https://github.com/malcartwright/minimal-api-routehandleranalyzer

1. Create a Minimal API using the default template
2. Create one or more classes within the Program.cs to hold delegate methods (either instance or static) to execute from an API Map{method} call and wire up
3. Create an external file to hold the delegate methods (instance or static) to execute from an API Map{method} call

Note that the first two app.MapGet calls in `Program.cs` do not give the error. The other calls that use external class files do.

### Exceptions (if any)

During the build:
CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Analyzers.RouteHandlers.RouteHandlerAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Syntax node is not within syntax tree'.

### .NET Version

6.0.300

### Anything else?

IDE: Happens whether using Visual Studio or Rider, or executing build from the command line

Output from `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.120 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.419 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  6.0.105 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by AraHaan** [comment] 2022-05-23 06:03
You plan to uninstall the .NET Core 3.1 and 5 SDK’s (and their runtimes) since 5 is now EOL?

**Comment by malcartwright** [comment] 2022-05-23 06:05
I can do so; this doesn't impact the issue as others in our business do not have these installed and receive the same error.

**Comment by gerry-eagle** [comment] 2022-05-25 02:55
Similar issue. Outsourced Map{Method} implementations to another class (so that swashbuckle/swagger can see the method comments!). Get seven of these little warnings, they don't seem to mess up the program. Sadly I cannot hide them with a _#pragma warning disable AD0001_ anywhere.

**Comment by egil** [comment] 2022-05-25 16:02
A workaround for now is to create an .editorconfig and add the following to it:

```
dotnet_diagnostic.ASP0003.severity = none
dotnet_diagnostic.ASP0004.severity = none
dotnet_diagnostic.ASP0005.severity = none
dotnet_diagnostic.ASP0006.severity = none
```

This disables the analyzer completely.

**Comment by malcartwright** [comment] 2022-05-25 23:19
@egil Thanks for the suggestion. This will avoid the issue when building in the IDE, however the .editorconfig isn't used when building in CI/CD using msbuild.

**Comment by jgrosic** [comment] 2022-05-26 00:12
Using method groups triggers the warning, for example:

```
	app.MapGet("check_warns_AD0001", Lib.Check);
	app.MapGet("check_works", () => Lib.Check());
```

**Comment by gerry-eagle** [comment] 2022-05-26 02:21
@jgrosic  That works for me. Changing something like "_app.MapGet("/ep", Method)_" to "app.MapGet("/ep", _(type x, type y) => Method(x,y)_" fixes the warning - but it does make the code much uglier paticularly when there are parameters. I think I would prefer that the analyzer could handle this use case.
Unfortunately Swagger loses all the method-level comments in the _Method_ source file if I do things that way, so I guess I'll implement @egil's suggestion, or just learn to live with the warning.

**Comment by egil** [comment] 2022-05-26 07:32
> @egil Thanks for the suggestion. This will avoid the issue when building in the IDE, however the .editorconfig isn't used when building in CI/CD using msbuild.

This should also work if you do a `dotnet build -c release`.

**Comment by jzs11** [comment] 2022-05-28 23:20
It's a regression right in 6.0.300 right?

**Comment by CollinAlpert** [comment] 2022-05-31 21:34
@gerry-eagle Have you tried adding `<NoWarn>AD0001</NoWarn>` to the `PropertyGroup` of your .csproj file? This removed the warnings for me.

**Comment by gerry-eagle** [comment] 2022-05-31 22:00
@CollinAlpert Aha, the simplest solution. Thank you, that works for me too and is also a more focused workaround.

**Comment by captainsafia** [comment] 2022-08-18 20:36
Just merged a fix for this into .NET 7 RC 1.

**Closed by captainsafia** 2022-08-18 20:36 UTC
Labels: bug, investigate, area-web-frameworks
