### ISSUE TITLE
Detect invalid route such as `@page "/fhir{system}" in Blazor component

### ISSUE THREAD

**Issue by lbcsy** [dotnet/aspnetcore#49445] opened 2023-07-16 08:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I was trying to add a dynamic route to my Blazor server app (the out of box one created by VS 2022 with .net core 6 ), the dynamic route suppose to be @page "/fhir/{system}" but I missed the second "/", thus the route had a typo and became @page "/fhir{system}", it passed the compile time but threw a System.NullReferenceException at the last line in _Host.cshtml when launched the app:
```c#

<component type="typeof(App)" render-mode="ServerPrerendered" />

``` 

### Describe the solution you'd like

The problem was that I had no way to had any clue for what was the cause from the Call Stack or anything else as a beginner of Blazor. If this kind of route will definitely failed the app's launch, why don't we failed it at the compiling time?

### Additional context

The full component source which can cause this issue:
```c#
@page "/fhir{system}/"
<h3>FHIR</h3>
<p> You have chosen system: @system </p>
@code {
    [Parameter]
    public string? system { get; set; }
}

```

**Comment by javiercn** [comment] 2023-07-17 14:48
Dupe of https://github.com/dotnet/aspnetcore/issues/45401

**Closed by javiercn** 2023-07-17 14:48 UTC
Labels: area-blazor
