### ISSUE TITLE
WasmBrowser and RCL projects fail based on alphabetic ordering of names

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#55105] opened 2024-04-12 18:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WasmBrowser-and-RCL-projects-fail-based-/10627677)._

---
[severity:It's more difficult to complete my work]
- Create a project using WebAssembly Browser App template(also known as wasmbrowser)
- Create/add a Razor Class Library project
- Add a project reference from the WebAssembly project to the RCL project.
- Set the web assembly project as the startup project.
- Compile and run

If the RCL project is named such that it is alphabetically before the WebAssembly project then the web app will fail to respond.  If you renamed the RCL project to appear after, then it will succeed.  

I recorded and attached a video to demonstrate the problem.

---
#### Feedback Bot on 3/29/2024, 00:44 AM: 

(private comment, text removed)
#### Aaron Shumaker on 3/29/2024, 08:11 AM: 

(private comment, text removed)
#### Mackinnon Buck [MSFT] on 4/5/2024, 10:45 AM: 

(private comment, text removed)
#### Aaron Shumaker on 4/5/2024, 07:11 PM: 

(private comment, text removed)
#### Aaron Shumaker on 4/11/2024, 01:06 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by SerratedSharp** [comment] 2024-04-12 19:04
Duplicate of https://github.com/dotnet/runtime/issues/100631

**Comment by halter73** [comment] 2024-04-12 19:44
@maraf I'm closing this as a dupe of https://github.com/dotnet/runtime/issues/100631. Let me know if there's anything you need from us.

@SerratedSharp Can you post your `RclNameBug` repro that you submitted through https://developercommunity.visualstudio.com/t/WasmBrowser-and-RCL-projects-fail-based-/10627677 publicly to a github repo and link to it in a comment to https://github.com/dotnet/runtime/issues/100631?

**Closed by halter73** 2024-04-12 19:44 UTC
Labels: investigate, area-blazor, Author: Migration Bot :robot:
