### ISSUE TITLE
Micro Frontends with Blazor

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#58021] opened 2024-09-22 19:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to include Components(Razor Class Library or even Full Blazor App (Server/Wasm) specific component into another Blazor App.
This would allow to re-use Blazor component from other apps.
Somehting very similar to iFrame, but with stricter security, where the included component should not be able to access anything from host application other than what was passed to it during invocation.

### Describe the solution you'd like

`<RemoteBlazorComponent URL="https://OtherrunningBlazorApp/ComponentName">`

### Additional context

Also flow the Auth token to the called app.
The idea is to allow using already prebuilt pages/component to be used from new applications.

**Comment by javiercn** [comment] 2024-09-23 14:14
@nssidhu thanks for contacting us.

We are going to mark this as a dupe of https://github.com/dotnet/aspnetcore/issues/52216

**Closed by javiercn** 2024-09-23 14:14 UTC
Labels: area-blazor
