### ISSUE TITLE
JsonSourceGenerationOptions does not Integrate with ASP. NET Core correctly

### ISSUE THREAD

**Issue by Kumima** [dotnet/aspnetcore#52642] opened 2023-12-07 21:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Consider the following code:
```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateSlimBuilder(args);

builder.Services.ConfigureHttpJsonOptions(
    options => { options.SerializerOptions.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default); });

var app = builder.Build();

var sampleTodos = new Todo[]
{
    new(1, Color.Red, "Walk the dog"),
    new(2, Color.Red, "Do the dishes", DateOnly.FromDateTime(DateTime.Now)),
    new(3, Color.Orange, "Do the laundry", DateOnly.FromDateTime(DateTime.Now.AddDays(1))),
    new(4, Color.Blue, "Clean the bathroom"),
    new(5, Color.Red, "Clean the car", DateOnly.FromDateTime(DateTime.Now.AddDays(2)))
};

var todosApi = app.MapGroup("/todos");
todosApi.MapGet("/", () => sampleTodos);
todosApi.MapGet(
    "/{id}",
    (int id) => sampleTodos.FirstOrDefault(a => a.Id == id) is
        { } todo ?
        Results.Ok(todo) :
        Results.NotFound());

app.Run();

public record Todo(int Id, Color Color, string? Title, DateOnly? DueBy = null, bool IsComplete = false);

public enum Color
{
    Red,
    Blue,
    Orange
}

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    Converters =
    [
        typeof(CamelCaseJsonStringEnumConverter<Color>)
    ])]
[JsonSerializable(typeof(Color))]
[JsonSerializable(typeof(Todo[]))]
internal partial class AppJsonSerializerContext : JsonSerializerContext;

public class CamelCaseJsonStringEnumConverter<TEnum>() : JsonStringEnumConverter<TEnum>(JsonNamingPolicy.CamelCase)
    where TEnum : struct, Enum;
```
OUTPUT:
```json
[
    {
        "id": 1,
        "color": 0,
        "title": "Walk the dog",
        "dueBy": null,
        "isComplete": false
    },
    {
        "id": 2,
        "color": 0,
        "title": "Do the dishes",
        "dueBy": "2023-12-08",
        "isComplete": false
    },
    {
        "id": 3,
        "color": 2,
        "title": "Do the laundry",
        "dueBy": "2023-12-09",
        "isComplete": false
    },
    {
        "id": 4,
        "color": 1,
        "title": "Clean the bathroom",
        "dueBy": null,
        "isComplete": false
    },
    {
        "id": 5,
        "color": 0,
        "title": "Clean the car",
        "dueBy": "2023-12-10",
        "isComplete": false
    }
]
```
Both `PropertyNamingPolicy` and `JsonStringEnumConverter` don't work.
This leads to parameter binding fails if the front-end sends the request with enum as string.

### Expected Behavior

Expected:
```json
......
{
        "id": 5,
        "color": "red",
        "title": "Clean the car",
        "due_by": "2023-12-10",
        "is_complete": false
}
```

**Comment by captainsafia** [comment] 2023-12-11 04:52
@Kumima I believe that this is a dupe of https://github.com/dotnet/aspnetcore/issues/52088. I did discuss this with @eiriktsarpalis but didn't follow-up on the resolution. Will close this in favor of keeping all the information in the other thread. If you'd like, you can add your scenario as a comment in that issue.

**Closed** 2023-12-11 05:15 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-networking
