### ISSUE TITLE
Blazor WebAssembly Add Identity Scaffolding

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#22712] opened 2020-06-09 16:36 UTC
### Describe the bug
After creating a new Blazor WebAssembly app then adding Identity Scaffolding.  Next, run the app and goto the Fetch page and receive exception:
An unhandled exception occurred while processing the request.
InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Pages/Shared/_Layout.cshtml': 'Scripts'. To ignore an unrendered section call IgnoreSection("sectionName").

### To Reproduce
1) Create a new Blazor WebAssembly app
2) Change Authentication to 'Individual User Accounts'; select 'Store user accounts in-app'
3) ASP.Net Core hosted is checked (true)
4) Create the app
5) Right click on Server Project and select Add --> New Scaffold Item
6) Select 'Identity'
7) Select all pages
8) Build and run
9) Goto the Fetch page and receive exception
An unhandled exception occurred while processing the request.
InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Pages/Shared/_Layout.cshtml': 'Scripts'. To ignore an unrendered section call IgnoreSection("sectionName").

### Exceptions (if any)
An unhandled exception occurred while processing the request.
InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Pages/Shared/_Layout.cshtml': 'Scripts'. To ignore an unrendered section call IgnoreSection("sectionName").

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
PS C:\Users\Roy> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015151
 Commit:    0755a9e324

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015151\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\Users\Roy>
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS2019 16.6.1 on Windows 10

Is there any workaround right now to fix up so we can customize the Identity pages?

**Comment by danroth27** [comment] 2020-06-13 01:18
Duplicate of https://github.com/dotnet/Scaffolding/issues/1325

**Comment by danroth27** [comment] 2020-06-13 03:41
@mkArtakMSFT The issue here is that we add a default minimalistic Razor Page layout in the Blazor WebAssembly server project that doesn't render the Scripts section, which is needed for the scaffolded Identity UI. 

The server project also includes a *wwwroot/css/site.css* file that isn't used by the layout in the server project, which is a bit odd. The layout in the server project links to *app.css* from the client project instead. It seems like *wwwroot/css/site.css* should just be removed.

Here's the current layout:

```cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/app.css" rel="stylesheet" />
</head>

<body>
    <div class="main">
        <div class="content px-4">
            @RenderBody()
        </div>
    </div>
</body>

</html>
```

I think we should just remove the layout from the ASP.NET Core hosted Blazor WebAssembly template. It's only used for the Error.cshtml page. We can remove _Layout.cshtml and instead make Error.cshtml a simple standalone page.

**Comment by danroth27** [comment] 2020-06-13 03:51
Proposed new *Error.cshtml*:

```cshtml
@page
@model BlazorApp1.Server.Pages.ErrorModel

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Error</title>
    <link href="~/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/app.css" rel="stylesheet" />
</head>

<body>
    <div class="main">
        <div class="content px-4">
            <h1 class="text-danger">Error.</h1>
            <h2 class="text-danger">An error occurred while processing your request.</h2>

            @if (Model.ShowRequestId)
            {
                <p>
                    <strong>Request ID:</strong> <code>@Model.RequestId</code>
                </p>
            }

            <h3>Development Mode</h3>
            <p>
                Swapping to the <strong>Development</strong> environment displays detailed information about the error that occurred.
            </p>
            <p>
                <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
                It can result in displaying sensitive information from exceptions to end users.
                For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
                and restarting the app.
            </p>
        </div>
    </div>
</body>

</html>
```

**Comment by jvallejoa** [comment] 2020-06-14 22:36
Hi guys, adding  @RenderSection("Scripts", required: false) in _Layout.cshtml helped to solve this issue for me. However the best approach perhaps is removing Pages/Shared/_Layout.cshtml from the ASP.NET Core hosted Blazor WebAssembly template if It's only used for the Error.cshtml page.

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/app.css" rel="stylesheet" />
</head>

<body>
    <div class="main">
        <div class="content px-4">
            @RenderBody()

            @*This line is added to correct Scripts Error in Identity pages*@
            **_@RenderSection("Scripts", required: false)_**
        </div>
    </div>
</body>

</html>

**Comment by danroth27** [comment] 2020-08-19 22:47
@javiercn @pranavkm It looks like we still haven't removed the layout from Error.cshtml in the Blazor WebAssembly template when ASP.NET Core hosted. We had discussed doing this as part of https://github.com/dotnet/aspnetcore/pull/22777 but it looks like the change wasn't done before the PR got merged. Seems like a quick fix to do as part of RC1.

**Closed** 2020-09-11 13:46 UTC
Labels: Done, area-blazor, blazor-wasm, bug

**Comment by JeepNL** [comment] 2020-10-08 12:28
Okay, still got an error after scaffolding when logging in (RC1/ SQLite) but I see here https://github.com/dotnet/aspnetcore/pull/25706#issuecomment-690533196 it's approved for RC2.

**Comment by IT-LCEC** [comment] 2020-10-22 13:29
Using VS 16.8.0 Preview 5.0 with .NET 5 RC.

I get this popup error when trying to add Identity scaffolding to a new Blazor server-side project:

Method not found: 'EnvDTE.Project Microsoft.WebTools.Scaffolding.Core.FactoryConfig.IScaffolderFactoryConfigEvaluationContext.get_ActiveProject()'.

**Comment by IT-LCEC** [comment] 2020-10-22 14:34
I found the issue with my problem in last post. It was the Syncfusion extensions as noted in this forum:

https://forums.asp.net/t/2169754.aspx?Adding+new+scaffolded+item
