### ISSUE TITLE
Blazor's InputNumber component should include the DisplayAttribute name in the ParsingErrorMessage

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/aspnetcore#17027] opened 2019-11-12 14:07 UTC
### Is your feature request related to a problem? Please describe.

I have a model class with DisplayAttribute and RangeAttribute annotations and use the InputNumber component in a form.

```cs
class Model
{
    [Range(0, int.MaxValue), Required, BindRequired, JsonProperty(Required = Required.Always)]
    [Display(Name = "Gross Counts Preset")]
    public int GrossCountsPreset { get; set; }
}
```
```razor
<InputNumber @bind-Value="model.GrossCountsPreset"/>
<ValidationMessage For="()=>model.GrossCountsPreset" />
```

When I leave the input empty, there are two validation messages:

```
The field Gross Counts Preset must be between 0 and 2147483647.
The GrossCountsPreset field must be a number.
```
Where the first one generated from the data annotations uses the DisplayAttribute while the second one shows the property's name instead.

### Describe the solution you'd like
The validation messages should both use the DisplayAttribute for a consistent user experience.

**Comment by javiercn** [comment] 2019-11-12 14:20
@Tragetaschen thanks for contacting us.

We'll take a look at this and get back to you.

**Comment by javiercn** [comment] 2019-11-12 17:34
We believe this is a behavior of data annotations.
You could specify an explicit error message in the validation attribute to workaround it.

@SteveSandersonMS Can you confirm this? If that's the case, should we get a bug on corefx to fix it?

**Comment by SteveSandersonMS** [comment] 2019-11-12 17:41
@javiercn We don’t control this. The message comes from DataAnnotations.

**Comment by SteveSandersonMS** [comment] 2019-11-12 17:43
Oh no wait, please disregard that. I think this message is ours. However we can’t couple our logic to DataAnnotations.

**Comment by javiercn** [comment] 2019-11-12 17:44
@SteveSandersonMS Should we close this as by design there? Or do you think there is a reasonable enhancement to be made. I'll leave it up to you to close the issue or follow-up.

**Comment by mkArtakMSFT** [comment] 2020-06-05 16:52
There is nothing we plan to do here.

**Closed by mkArtakMSFT** 2020-06-05 16:52 UTC
Labels: area-blazor, investigate
