### ISSUE TITLE
DATA_Received_TooSlowlyOnSecondStream_AbortsConnectionAfterNonAdditiveRateTimeout

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#34903] opened 2021-07-31 16:12 UTC
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3TimeoutTests.DATA_Received_TooSlowlyOnSecondStream_AbortsConnectionAfterNonAdditiveRateTimeout

## Error Message

```text
System.InvalidOperationException : No data received.
```

## Stacktrace

<details>

```text
at Microsoft.AspNetCore.Testing.Http3StreamBase.ReceiveFrameAsync(Boolean expectEnd, Boolean allowEnd, Http3FrameWithPayload frame) in /_/src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:line 495
   at Microsoft.AspNetCore.Testing.Http3RequestStream.ExpectHeadersAsync(Boolean expectEnd) in /_/src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:line 650
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3TimeoutTests.DATA_Received_TooSlowlyOnSecondStream_AbortsConnectionAfterNonAdditiveRateTimeout() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TimeoutTests.cs:line 520
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.001s] [TestLifetime] [Information] Starting test DATA_Received_TooSlowlyOnSecondStream_AbortsConnectionAfterNonAdditiveRateTimeout at 2021-07-31T03:17:41
[0.007s] [Microsoft.AspNetCore.Testing.Http3InMemory] [Information] Initializing stream 3
[0.007s] [Microsoft.AspNetCore.Testing.Http3InMemory] [Information] Initializing stream 4
[0.018s] [Microsoft.AspNetCore.Server.Kestrel.Http3] [Verbose] Connection id "null" received HEADERS frame for stream ID 4 with length 68.
[0.018s] [Microsoft.AspNetCore.Server.Kestrel.Http3] [Verbose] Connection id "null" received DATA frame for stream ID 4 with length 16384.
[0.019s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "null", Request id "TEST:4": started reading request body.
[0.019s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "null", Request id "TEST:4": done reading request body.
[0.019s] [Microsoft.AspNetCore.Server.Kestrel.Http3] [Verbose] Connection id "null" sending HEADERS frame for stream ID 4 with length 38.
[0.019s] [Microsoft.AspNetCore.Server.Kestrel.Http3] [Verbose] Connection id "null" sending DATA frame for stream ID 4 with length 1.
[0.020s] [Microsoft.AspNetCore.Testing.Http3InMemory] [Information] Disposing stream 4
[0.025s] [Microsoft.AspNetCore.Testing.Http3InMemory] [Information] Initializing stream 8
[0.030s] [Microsoft.AspNetCore.Server.Kestrel] [Information] Connection id "null", Request id "TEST:8": the application completed without reading the entire request body.
[0.031s] [Microsoft.AspNetCore.Testing.Http3InMemory] [Information] Disposing stream 8
[0.048s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3TimeoutTests] [Error] Test threw an exception.
System.InvalidOperationException: No data received.
   at Microsoft.AspNetCore.Testing.Http3StreamBase.ReceiveFrameAsync(Boolean expectEnd, Boolean allowEnd, Http3FrameWithPayload frame) in /_/src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:line 495
   at Microsoft.AspNetCore.Testing.Http3RequestStream.ExpectHeadersAsync(Boolean expectEnd) in /_/src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:line 650
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3TimeoutTests.DATA_Received_TooSlowlyOnSecondStream_AbortsConnectionAfterNonAdditiveRateTimeout() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TimeoutTests.cs:line 520
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[0.049s] [TestLifetime] [Information] Finished test DATA_Received_TooSlowlyOnSecondStream_AbortsConnectionAfterNonAdditiveRateTimeout in 0.0474257s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1269732&view=results

**Comment by JamesNK** [comment] 2021-08-09 21:41
I think this is fixed now. There have been many changes in this area and I can't reproduce it.

**Closed** 2021-09-04 04:05 UTC
Labels: test-failure, area-runtime, HTTP3, test-fixed
