### ISSUE TITLE
Kestrel assumes a valid http1.1 host name even for a http/2 connection over an unix domain socket

### ISSUE THREAD

**Issue by Zetanova** [dotnet/aspnetcore#18533] opened 2020-01-23 04:55 UTC
### Describe the bug
The spec changes a bit for the Host header field in HTTP/2 
It is now inside the ":authority" pseudo - header field.

CLI Applications like kubelet from kubernetes connecting to a unix domain socket 
hosted by kestrel will specify the full SocketPath in the http/2 ":authority" pseudo - header.

Kestrel assumes and checks for a regular http1.1 host name at:
https://github.com/dotnet/aspnetcore/blob/4144eeb459d9ba956fc0d84d8d5a3e0408e88a09/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs#L274

### To Reproduce
Host Kestrel on a LinuxDomainSocket with http/2 and try to connect with an 
CLI app (golang or something else) directly to the socket path.

Exception is sown only in Debug like:
```
dbug: Microsoft.AspNetCore.Server.Kestrel[35]
      Trace id "0HLSVMN5PK7LL:00000001": HTTP/2 stream error "PROTOCOL_ERROR". A Reset is being sent to the stream.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: Invalid Host header: '/var/lib/kubelet/plugins/eu.zetanova.csi.hyperv/csi.sock'
```

### Further technical details
- ASP.NET Core version 3.1

**Comment by Zetanova** [comment] 2020-01-23 05:09
https://github.com/dotnet/aspnetcore/issues/18522

**Comment by JamesNK** [comment] 2020-01-23 05:51
Duplicate of https://github.com/dotnet/aspnetcore/issues/18522

**Closed by JamesNK** 2020-01-23 05:51 UTC
