### ISSUE TITLE
JsonPatch - Tests on empty string throws exception

### ISSUE THREAD

**Issue by Kjelli** [dotnet/aspnetcore#28019] opened 2020-11-20 13:57 UTC
### Describe the bug
I want to overwrite an existing json property that is an empty string `""`, and beforehand a test operation is performed. When testing that the value at path `/foo` is equal to `""` - an exception is thrown with the following error message: `The value at 'foo' cannot be null or empty to perform the test operation.`

According to [RFC6902 section 4.6](https://tools.ietf.org/html/rfc6902#section-4.6), I believe it is incorrect to disallow values to be tested in this case.

### To Reproduce
```csharp
// Object with empty string property foo
dynamic myObject = new ExpandoObject();
myObject.foo = "";

// Create patch document with test operation
var doc = new JsonPatchDocument();
doc.Test("foo", "");

doc.ApplyTo(myObject); // <-- throws JsonPatchException
```

### Exceptions (if any)
```csharp
 Microsoft.AspNetCore.JsonPatch.Exceptions.JsonPatchException : The value at 'foo' cannot be null or empty to perform the test operation.

<.cctor>b__1_0(JsonPatchError error)
    ObjectAdapter.Test(Operation operation, Object objectToApplyTo)
    Operation.Apply(Object objectToApplyTo, IObjectAdapter adapter)
    JsonPatchDocument.ApplyTo(Object objectToApplyTo, IObjectAdapter adapter)
    JsonPatchDocument.ApplyTo(Object objectToApplyTo)
    UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
```
Throw location: [/src/Microsoft.AspNetCore.JsonPatch/Internal/DictionaryAdapterOfTU.cs ](https://github.com/aspnet/JsonPatch/blob/860e2bd46b2d3c8a3901409e76563a2f7b2f15b6/src/Microsoft.AspNetCore.JsonPatch/Internal/DictionaryAdapterOfTU.cs#L164)

### Further technical details
- ASP.NET Core version 3.1
- Microsoft.AspNetCore.JsonPatch 3.1.8

```md
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]       
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]        
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]       
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by henriksen** [comment] 2020-11-20 14:13
Same result on .NET 5
```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7
```

**Comment by TanayParikh** [comment] 2021-10-19 22:45
Thanks, closing as duplicate of https://github.com/dotnet/aspnetcore/issues/25942

**Closed by TanayParikh** 2021-10-19 22:45 UTC
Labels: bug, investigate, area-mvc, feature-JSONPatch, affected-few, severity-blocking
