### ISSUE TITLE
FolderBrowserDialog crashes WPF Blazor Hybrid apps

### ISSUE THREAD

**Issue by JakubTracz** [dotnet/aspnetcore#49516] opened 2023-07-19 13:42 UTC
When using a FolderBrowserDialog in a razor component, it randomly crashes the application. Try-catch doesn't work, the app shuts down silently.

```
@using DialogResult = System.Windows.Forms.DialogResult
@using System.Windows.Forms

<MudText Typo="Typo.caption">@Label</MudText>
<MudPaper Style="display: flex; padding: 10px; margin: 5px 0 20px 0" Elevation="3">
    <StringTextField 
        BoundValue="@BoundValue"
                     ValidationAttribute="ValidationAttribute"
                     HelperText="@HelperText"
                     HelperTextOnFocus="true"
                     FieldInputType="InputType.Text"
                     OnValueChanged="OnValueChanged"
                     Label="@string.Empty"/>
    <MudIconButton Icon="@Icons.Material.Filled.Folder" OnClick="SelectFolder" Style="width: 10%"/>
</MudPaper>

@code {

    [Parameter]
    public EventCallback<string> OnValueChanged { get; set; }
    
    [Parameter]
    public string Label { get; set; }

    [Parameter]
    public string BoundValue { get; set; }

    [Parameter]
    public string HelperText { get; set; }

    [Parameter]
    public object? ValidationAttribute { get; set; }

    private async Task SelectFolder()
    {
        var folderPath = await Dispatcher.CreateDefault().InvokeAsync(() =>
        {
            using var dialog = new FolderBrowserDialog
            {
                InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Desktop)
            };
            var result = dialog.ShowDialog();
            var path = result == DialogResult.OK ? dialog.SelectedPath : string.Empty;
            return path;
        });
        BoundValue = folderPath;
        await OnValueChanged.InvokeAsync(BoundValue);
        StateHasChanged();
    }
    
}
```

### Expected Behavior

App should not crash.

### Steps To Reproduce

- Create a new WPF Blazor Hybrid app
- Inside a page/component, use a FolderBrowserDialog class to fetch a path to the selected folder (e.g. after clicking a button),
- In some tries the app will shut down

### .NET Version

.NET 7

**Comment by marinasundstrom** [comment] 2023-07-19 14:29
I'm not sure this is related to Blazor in the context of the Web. This is MAUI.

But in WPF you can use the global exception handler to catch the exception:

```csharp
	public partial class App : Application
	{
		private void Application_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
		{
			MessageBox.Show("An unhandled exception just occurred: " + e.Exception.Message, "Exception Sample", MessageBoxButton.OK, MessageBoxImage.Error);
			e.Handled = true;
		}
	}
```

MAUI repo: https://github.com/dotnet/maui

**Comment by mkArtakMSFT** [comment] 2023-08-11 21:50
@JakubTracz did you try @marinasundstrom 's suggestion about adding a global exception handler in a WPF app and see if that can handle the exception?

/cc @Eilon

**Comment by Eilon** [comment] 2023-08-11 22:19
@JakubTracz I also see that the code calls `Dispatcher.CreateDefault`, and that could be the cause of the problem. That's going to create the default Dispatcher that Blazor would normally use, but in Blazor Hybrid WPF it uses a custom dispatcher. I think you can just call `await InvokeAsync(...)` from anywhere in your Razor component and that will use the "current" dispatcher (which in Blazor Hybrid is usually a custom one).

**Comment by lif-enable** [comment] 2023-08-24 10:32
> 我还看到代码调用，这可能是问题的原因。这将创建 Blazor 通常使用的默认调度程序，但在 Blazor 混合 WPF 中，它使用自定义调度程序。我认为你可以从 Razor 组件中的任何位置调用，这将使用“当前”调度程序（在 Blazor Hybrid 中通常是自定义调度程序）。`Dispatcher.CreateDefault``await InvokeAsync(...)`

```
await InvokeAsync(() =>
        {
            using var dialog = new FolderBrowserDialog
            {
                InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Desktop)
            };
            var result = dialog.ShowDialog();
    
        });
```

crashing after 1-2 minutes  :(

**Comment by Eilon** [comment] 2023-09-01 17:48
@lif-enable said:

> crashing after 1-2 minutes :(

Can you share more info about what's crashing and how? Is the folder dialog box left open and then you wait 1-2 minutes and then it crashes? Or has the dialog been dismissed and the app works normally for 1-2 minutes and then it crashes?

It could be that the code needs to follow the guidance here about how to queue/post work items to execute after the current code completes: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#re-entrancy

**Comment by Eilon** [comment] 2023-09-12 18:25
Closing because it's not clear what the issue is. I suggest following the guidance in the previous comment from me because it's the specific recommendation for WebView2 scenarios.

There's another related possibility to this cause, which is that specifically during debugging there is this bug that can cause a crash: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3551

**Closed by Eilon** 2023-09-12 18:25 UTC
Labels: investigate, area-blazor, feature-blazor-hybrid
