### ISSUE TITLE
Design Review: Startup code for client apps (Blazor)

### ISSUE THREAD

**Issue by rynowak** [dotnet/aspnetcore#8000] opened 2019-02-27 17:33 UTC
We created an experience oriented around the startup pattern and `IComponentsAppBuilder` for client-side apps - so that we could align it with the experience for components on the server.

We ended up coming up with something different on the server, so we should think again about what to do on the client.

**Comment by mkArtakMSFT** [comment] 2020-01-10 18:15
This is a dupe of https://github.com/dotnet/aspnetcore/issues/16874

**Closed by mkArtakMSFT** 2020-01-10 18:15 UTC
Labels: Needs: Design, area-blazor
