### ISSUE TITLE
HttpSys Not Support IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by li-zhixin** [dotnet/aspnetcore#42549] opened 2022-07-02 01:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. Using HttpSys to listen `http://*:5274`.
2. Access site using IPv4-mapped IPv6 addresses.
3. The browser cannot access, prompting HTTP Error 400. The request hostname is invalid.

### Expected Behavior

I hope it can be accessed normally.

### Steps To Reproduce

```c#
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.WebHost.UseHttpSys();
builder.WebHost.UseUrls("http://*:5274");
builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();

```

Access this url: [swagger](http://[::ffff:7f00:1]:5274/swagger/index.html)

### .NET Version

6.0.400-preview.22301.10

### Anything else?

WinVer: `Win11 22H2(OS Build 22621.105)`

**Comment by Tratcher** [comment] 2022-07-05 19:08
I can reproduce this with Edge and HttpClient. The rejection is coming from the Windows Http.Sys layer, I'll report this issue to them.

For the given url: `http://[::ffff:127.0.0.1]:5000/`
HttpClient sends a host header like this: `Host: [::ffff:127.0.0.1]:5000`
Edge reformats the IP address as: `Host: [::ffff:7f00:1]:5000`

**Comment by Tratcher** [comment] 2022-07-06 17:40
The Windows team has acknowledged the issue and found the cause. There's a check that makes sure IPs in the Host header match the version of the socket. In this scenario the sockets are using IPv4, but the host header appears to be IPv6. The check is not aware of IPv4 mapped IPv6 addresses.

They will investigate and decide how to best fix this for a future Windows release. If you need this patched in a current Windows version then please contact Microsoft Support.

The workaround: Don't do that 😁. How did you run into this scenario?

**Comment by li-zhixin** [comment] 2022-07-07 01:03
It happened in the testing of our product for ipv6 support. Do I need to close this issue?

**Comment by Tratcher** [comment] 2022-07-07 21:28
Feel free to close it if your questions have been answered.

**Closed** 2022-07-07 23:13 UTC
Labels: External, area-runtime, servers-httpsys, :heavy_check_mark: Resolution: Answered, Status: Resolved
