### ISSUE TITLE
Cannot Debug Blazor WebAssembly with embedded symbols

### ISSUE THREAD

**Issue by fuocor** [dotnet/aspnetcore#26877] opened 2020-10-14 03:21 UTC
### Describe the bug
if the `<DebugType>` for a blazorwasm project is set to `embedded` then the code cannot be debugged in VS, VSCode, or in the Browser

### To Reproduce
In the `.csproj` add `<DebugType>embedded</DebugType>` and try to debug with your tool of choice...

### Workaround
`<DebugType>portable</DebugType>`

### Exceptions (if any)
depending on the tool you will be notified that the code does not support debugging

### Further technical details
- ASP.NET Core version:  5.0.0-rc.2.20475.5
```
PS D:\dummy> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment] 2020-10-14 16:17
Thanks for contacting us.
@lewing is this something the Debugger supports?

@fuocor can you share more details about why you're trying to change the setting?

**Comment by thaystg** [comment] 2020-10-14 19:17
I have just tested it again on mono and it's working.

The problem is here: https://github.com/dotnet/aspnetcore/blob/628ce6114bd426c80e57f637234fe94cf9b37c7d/src/Components/Web.JS/src/Platform/Mono/MonoDebugger.ts#L10

To enable debugger it needs to have pdb's, but this is not right, we can debug without PDB's in the case of embedded PDB's.

I think this PR will fix the issue: 
https://github.com/dotnet/aspnetcore/pull/26899

**Comment by mkArtakMSFT** [comment] 2020-10-27 19:48
@captainsafia I assume this is resolved already?

**Comment by captainsafia** [comment] 2020-10-27 19:50
@mkArtakMSFT Yes, the fix was merged into master. We can close this issue.

**Closed by captainsafia** 2020-10-27 19:50 UTC
Labels: area-blazor, blazor-wasm, bug, feature-blazor-debugging
