### ISSUE TITLE
.NET 5 FORM multipart/form-data not working correclty

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#29373] opened 2021-01-16 03:24 UTC
For some reason my form is refusing to post I have a controller with the method. I am using a base controller but its not overidden any of those methods just a few properties.
   
    [HttpPost]
    [ValidateAntiForgeryToken] 
    public IActionResult Put(FileManagerViewModel fileManager) {
        FileClient client = new FileClient();
        FileInfo info = new FileInfo(fileManager.File.FileName);
        var remoteIpAddress = _httpContextAccessor.HttpContext.Connection.RemoteIpAddress;
         var t = Task.Run(() =>
            client.UploadFileAsync(_context, "username", "password", fileManager.File.FileName, info.Extension.ToLower(), UserId.ToString(), remoteIpAddress.ToString()
          ));

            return View(fileManager);
    }

Here is the form

 
    @model MSFSAddons.Models.ViewModels.FileManagerViewModel

    @{
       ViewData["Title"] = "Upload";
       Layout = "~/Themes/FrontEnd/_MyProfile.cshtml";
     }

    <form method="post" enctype="multipart/form-data" asp-controller="FileManager" asp-action="UploadFiles">
 
    <dl>
        <dt>
            <label asp-for="File"></label>
        </dt>
        <dd>
            <input asp-for="File" type="file">
            <span asp-validation-for="File"></span>
        </dd>
    </dl>
     <input asp-page-handler="Upload" class="btn" type="submit" value="Upload" />
    </form>

Startup class

 public void ConfigureServices(IServiceCollection services)
        {
            AppConfig.WebRootPath = _hostingEnvironment.WebRootPath;
            AppConfig.ContentRootPath = _hostingEnvironment.ContentRootPath;

            services.AddControllersWithViews();
            services.AddMvc().AddNToastNotifyToastr(new ToastrOptions()
            {
                ProgressBar = false,
                PositionClass = ToastPositions.TopRight,
                ToastClass = "alert",

            });
           
    services.AddIdentity<ApplicationUser, IdentityRole>(config =>
    {
        config.SignIn.RequireConfirmedEmail = true;
        config.Tokens.AuthenticatorTokenProvider = TokenOptions.DefaultAuthenticatorProvider;
        config.User.RequireUniqueEmail = true;

    })
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<MSFSAddonDBContext>()
        .AddDefaultTokenProviders()      
        .AddRoles<IdentityRole>();

  services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>,
AdditionalUserClaimsPrincipalFactory>();
    services.AddSession(opts =>
    {
        opts.Cookie.IsEssential = false; // make the session cookie Essential
        opts.IdleTimeout = TimeSpan.FromMinutes(30);

    });
            services.Configure<FileTransferConfig>(Configuration.GetSection("FileTransferConfig"));

            services.AddDbContext<MSFSAddonDBContext>(options =>
               options.UseSqlServer(
                   Configuration.GetConnectionString("DefaultConnection")));
                    services.AddHttpContextAccessor();
            services.Configure<FormOptions>(options =>
            {
                options.MultipartBodyLengthLimit = 6000000000;
            });

            services.AddAuthorization(options =>
        options.AddPolicy("TwoFactorEnabled",
        x => x.RequireClaim("amr", "mfa")));
            services.AddAntiforgery(o => o.HeaderName = "XSRF-TOKEN");
            services.Configure<IdentityOptions>(options =>
            {

                // Default Lockout settings.
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;
                

            });
    services.ConfigureApplicationCookie(config =>
    {
        config.Cookie.Name = "Identity.Cookie";
        config.LoginPath = "/Identity/Account/Login";
    
    });

            services.AddMvc().AddNToastNotifyToastr(new ToastrOptions()
            {
                ProgressBar = false,
                PositionClass = ToastPositions.TopRight,
                ToastClass = "alert",

            });
            services.AddTransient<IEmailSender, EmailSender>(i =>
                new EmailSender(
                    Configuration["EmailSender:Host"],
                    Configuration.GetValue<int>("EmailSender:Port"),
                    Configuration.GetValue<bool>("EmailSender:EnableSSL"),
                    Configuration["EmailSender:UserName"],
                    Configuration["EmailSender:Password"]
                )
            );
       
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
                options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
                options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
                
            });

   

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseDeveloperExceptionPage();

                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
    app.UseHttpsRedirection();
    app.UseStaticFiles();
            
    app.UseRouting();

    app.UseAuthorization();
    app.UseAuthentication();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
        name: "areas",
        pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");

        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
        endpoints.MapRazorPages();
    });
        }
    }

**Comment by javiercn** [comment] 2021-01-18 14:17
@davidbuckleyni thanks for contacting us.

We can't see exactly what's going on with the code you produce. Could you create a minimal repro project and upload it to a GH repo so that we can try and help you?

There are several things that I'm not sure make sense in your code.
* Why are you using IHttpContextAccessor? You shouldn't need that in a controller since it's available already.
* Doing Task.Run is likely problematic since you are not waiting for the request body to be consumed before you start sending the response, it's likely that your app doesn't get to consume the entire body of the request before the existing httpcontext gets disposed/recycled.

I would start by making the code async and awaiting the task to see if that fixes things.

I presume you are trying to notify the client while the files are being uploaded, but I don't think the way you are trying to do this is correct/possible in a traditional web application.

**Comment by javiercn** [comment] 2021-01-18 14:58
This was a dupe of https://github.com/dotnet/aspnetcore/issues/29372 which has been resolved

**Closed by javiercn** 2021-01-18 14:58 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-mvc, question
