### ISSUE TITLE
Minimal API: Route Handler Filter does not show errors list

### ISSUE THREAD

**Issue by JohnyL** [dotnet/aspnetcore#42044] opened 2022-06-05 13:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Say, I have this simple route handler filter which uses Fluent Validation:
```csharp
public class ValidationFilter<T> : IRouteHandlerFilter where T : class
{
  private readonly IValidator<T> validator;
  public ValidationFilter(IValidator<T> validator) => this.validator = validator;

  public async ValueTask<object> InvokeAsync(RouteHandlerInvocationContext context, RouteHandlerFilterDelegate next)
  {
    var validatable = context.Parameters.SingleOrDefault(p => p.GetType() == typeof(T)) as T;
    if (validatable is null)
    {
      return Results.BadRequest("Could not find validatable object.");
    };
    var validationResult = await validator.ValidateAsync(validatable);
    if (!validationResult.IsValid)
    {
      return Results.ValidationProblem(validationResult.ToDictionary());
    }
    return await next(context);
  }
}
```
When I use ApiController, then I receive correct response:
![image](https://user-images.githubusercontent.com/7391680/172053798-a2162b2e-a04f-47c8-a9b2-90db1ed986cc.png)

However, when I use Minimal API, I get empty list of errors:
![image](https://user-images.githubusercontent.com/7391680/172053863-618afd96-e08b-4171-8dee-c2fb9a14cc30.png)

### .NET Version

7.0.100-preview.4.22252.9

**Comment by martincostello** [comment] 2022-06-05 21:27
Dupe of #41686?

**Closed** 2022-06-06 15:33 UTC
Labels: area-web-frameworks
