### ISSUE TITLE
Playwright based BlazorTemplates.Tests skipped on helix

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#38818] opened 2021-12-03 21:42 UTC
Seeing intermittent hangs in these tests:

Added `<BuildHelixPayload>false</BuildHelixPayload>` to take this out of the aspnetcore-ci checks since all tests were quarantined anyways

Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=1495934&view=ms.vss-test-web.build-test-results-tab&runId=42705898&resultId=121679&paneView=debug

Console logs:
```
Console log: 'BlazorTemplates.Tests--net7.0' from job 869db767-1c21-489c-8aca-77d1593dcd0e workitem ecc85496-07ff-46eb-9808-b21e67bdfa4c (windows.11.amd64.clientpre.open) executed on machine a002VD2

C:\h\w\A89D0986\w\B2F209E8\e>set PATH=C:\h\w\A89D0986\p\dotnet-cli;C:\python3.9.1\Scripts\;C:\python3.9.1\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\runner\AppData\Local\Microsoft\WindowsApps 

C:\h\w\A89D0986\w\B2F209E8\e>set DOTNET_ROOT=C:\h\w\A89D0986\p\dotnet-cli 

C:\h\w\A89D0986\w\B2F209E8\e>set DOTNET_CLI_TELEMETRY_OPTOUT=1 

C:\h\w\A89D0986\w\B2F209E8\e>set DOTNET_CLI_HOME=C:\h\w\A89D0986\w\B2F209E8\e\.dotnet 

C:\h\w\A89D0986\w\B2F209E8\e>set NUGET_PACKAGES=C:\h\w\A89D0986\w\B2F209E8\e\.nuget 

C:\h\w\A89D0986\w\B2F209E8\e>call RunPowershell.cmd mssql\InstallSqlServerLocalDB.ps1   || exit /b 1 
"PS: Running 'C:\h\w\A89D0986\w\B2F209E8\e\mssql\InstallSqlServerLocalDB.ps1' "
Installing SQL Server 2016 Express LocalDB

Downloading 'SqlLocalDB.msi' to 'C:\h\w\A89D0986\w\B2F209E8\e\mssql\obj\SqlLocalDB.msi'.
GET https://download.microsoft.com/download/9/0/7/907AD35F-9F9C-43A5-9789-52470555DB90/ENU/SqlLocalDB.msi
Download of 'https://download.microsoft.com/download/9/0/7/907AD35F-9F9C-43A5-9789-52470555DB90/ENU/SqlLocalDB.msi' complete, saved to C:\h\w\A89D0986\w\B2F209E8\e\mssql\obj\SqlLocalDB.msi...

Running 'msiexec /package "C:\h\w\A89D0986\w\B2F209E8\e\mssql\obj\SqlLocalDB.msi" /NoRestart /Passive IACCEPTSQLLOCALDBLICENSETERMS=YES HIDEPROGRESSBAR=YES'.
```

**Comment by TanayParikh** [comment] 2021-12-08 17:30
We have a high degree of overlap in our selenium and playwright tests.

Selenium:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/14852843/145254937-dc467d1f-efa6-4a9f-acb6-1221ffa3ecd0.png)

Playwright:
<img width="857" alt="Screen Shot 2021-12-08 at 9 28 10 AM" src="https://user-images.githubusercontent.com/14852843/145255056-0896a263-19f7-42f5-8fd4-f25f1a8318b0.png">

In the interest of improving maintainability, perhaps we should just remove the playwright test suite entirely. This we mean we would no longer have playwright within this repo and eliminate that dependency entirely. As it stands, the selenium template tests have been very reliable.

**Comment by TanayParikh** [comment] 2022-12-22 00:15
Note we aren't currently sure whether we want to run the Blazor Template Playwright tests on helix due to platform specific issues with Playwright. Focus is on the build agents. 

If we do decide to enable helix, we'll have to subsequently complete: https://github.com/dotnet/aspnetcore/issues/30825

**Comment by TanayParikh** [comment] 2023-02-01 00:41
> Note we aren't currently sure whether we want to run the Blazor Template Playwright tests on helix due to platform specific issues with Playwright. Focus is on the build agents.



We're running the tests specifically on the build agents for now due to issues with Helix compatibility. Backlogging this until we decide we'd like these tests running on helix.

**Comment by mkArtakMSFT** [comment] 2024-02-20 17:24
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/46430

**Closed by mkArtakMSFT** 2024-02-20 17:24 UTC
Labels: test-failure, area-blazor, Priority:0, feature-playwright 🎭, Pillar: Technical Debt
