### ISSUE TITLE
[NETE2ESDK][Loc]The hyperlink for contents on NET 7.0.0 windows server hosting installer UI on loc OS is EN not loc link.

### ISSUE THREAD

**Issue by vdanche** [dotnet/aspnetcore#44613] opened 2022-10-18 06:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
The hyperlink for contents on windows hosting bundle installer UI on loc OS is EN link not loc link. 

### Expected Behavior

The link should be loc link.

### Steps To Reproduce
Double-click on NET7.0.0 dotne-hosting installer .exe on Loc OS e.g Russian OS.
On installation UI, Click the link for "here" "license term" "privacy statement"

Actual Result:
e.g RU:
![image](https://user-images.githubusercontent.com/65637796/196355437-2437c159-d47c-47b5-a856-84b96f8c333f.png)
here: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0
license term : https://dotnet.microsoft.com/en-us/dotnet_library_license.htm
privacy statement: https://privacy.microsoft.com/en-us/privacystatement/

EN:
![image](https://user-images.githubusercontent.com/65637796/196355816-66684ea8-ed1a-47f3-8064-6336d23e1d71.png)
here: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0
license term : https://dotnet.microsoft.com/en-us/dotnet_library_license.htm
privacy statement: https://privacy.microsoft.com/en-us/privacystatement/

**Comment by dougbu** [comment] 2022-10-18 19:40
Is this a regression from 6.0.x? I doubt it because the relevant code hasn't changed in a while.

That said, the use of `...?view=aspnetcore-6.0` could be considered a regression from 6.0.x because the same link would have been perfect then.

**Comment by dougbu** [comment] 2022-10-18 19:49
@cristianosuzuki77 is there a way to have the correct locale identifiers substituted for `en-us` during the loc process for WXL files❔

**Comment by mkArtakMSFT** [comment] 2022-11-29 19:27
Ping @cristianosuzuki77

**Comment by dougbu** [comment] 2022-12-01 01:02
Will see if we can use language-neutral links for these parts of the UI. Will require more work in main because I need to add loc comments there. So, I'll do a manual release/7.0 change and double check release/6.0 as well (because that's LTS).

**Comment by dougbu** [comment] 2022-12-01 01:15
Oh, I think I see&hellip;

@mkArtakMSFT I don't know how to validate `fwlink`s (I of course land on en-us pages) and would appreciate you checking the following
- <https://go.microsoft.com/fwlink/?LinkId=329770> should forward to <https://dotnet.microsoft.com/dotnet_library_license.htm>
- <https://go.microsoft.com/fwlink/?LinkId=786378> should forward to <https://privacy.microsoft.com/privacystatement/>
- <https://go.microsoft.com/fwlink/?LinkId=798277> should forward to <https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/?view=aspnetcore-7.0>

That is, none of the above should forward to a local-specific URI e.g., <https://dotnet.microsoft.com/en-us/dotnet_library_license.htm>

**Comment by mkArtakMSFT** [comment] 2022-12-01 05:20
Ok, the first link is owned by @terrajobst, the second one is owned by @ChrisSfanos and the third one is owned by @danroth27.

@dougbu how safe is it to simply change those links? Maybe they're used somewhere else? Can we instead create new aka.ms links to the targets that you need them to point to?

**Comment by dougbu** [comment] 2022-12-01 05:29
> @dougbu how safe is it to simply change those links? Maybe they're used somewhere else? Can we instead create new aka.ms links to the targets that you need them to point to?

I don't know about whether these `fwlink`s can be changed nor other uses but hope the owners do. `aka.ms` links would be fine if we can't change them.

To cover 6.0.x (`...?view=aspnetcore-6.0`) for #44615 as well, would actually need 4 distinct locale-independent links of either type.

**Comment by mkArtakMSFT** [comment] 2022-12-01 17:46
I think creating new links is easier. So if it's easy for you to change them, I'd be happy to create those.

**Comment by dougbu** [comment] 2022-12-01 18:29
Up to you, @terrajobst, and @ChrisSfanos. It may be a general problem if those links are `en-us`-only.

Side question: You could see the ownership @mkArtakMSFT. Could you see the redirect targets❔ I'm now pretty sure at least the privacy statement link redirects to the en-us page; when I head to <https://privacy.microsoft.com/privacystatement/>, I land on <https://privacy.microsoft.com/en-CA/privacystatement/> 😀

**Comment by ChrisSfanos** [comment] 2022-12-01 18:49
I'm looking at link 786378 (Privacy link) - it points to the standard privacy page, but does have en-us in the link target.  Is the ask to change it to something more generic?  Not exactly sure that the ask is here

**Comment by dougbu** [comment] 2022-12-01 18:54
> Is the ask to change it to something more generic?

Yes, exactly. We use that `fwlink` in localized installers and this issue is about going to the correct page for the user running the installers. <https://privacy.microsoft.com/privacystatement/> is perfect because it detects browser settings and chooses the correct (locale-specific) page for the user. @mkArtakMSFT's hesitation was because some other uses of that `fwlink` may _expect_ the US English link.

**Comment by dougbu** [comment] 2022-12-01 19:19
> Fair concern, but since the web is handling the redirects, that should cover any concerns about an expected/forced en-us version right?

If we were using the local-independent link in the `fwlink`, that's correct. As is, the `fwlink` goes to the en-us page unconditionally. (Once you hit an en-us page on microsoft.com, you stay there.)

**Comment by dougbu** [comment] 2022-12-01 19:20
And, if your comment was negating @mkArtakMSFT's concern, we're loudly agreeing 😉

**Comment by ChrisSfanos** [comment] 2022-12-01 19:36
Laughing - yep I think it should be handled automagically and I'm not concerned.  If everyone wants, I can change the privacy link to https://privacy.microsoft.com/privacystatement/ and see if anyone loudly complains :-)

**Comment by dougbu** [comment] 2022-12-01 19:38
I'd be glad if you made that change. Then we just need to hear from @terrajobst on the license link.

**Comment by ChrisSfanos** [comment] 2022-12-01 21:24
Change made

**Comment by dougbu** [comment] 2023-03-10 17:49
/ping @terrajobst 

This problem is _almost_ fixed in all installers. However the following bullet has not changed
> https://go.microsoft.com/fwlink/?LinkId=329770 should forward to https://dotnet.microsoft.com/dotnet_library_license.htm

(See list in https://github.com/dotnet/aspnetcore/issues/44613#issuecomment-1333006299)

It will be much simpler and help a broader number of customers to remove en_us from the fwlink destination than to fix only the installers (e.g. using new aka.ms links).

/cc @wtgodbe @mkArtakMSFT

**Comment by terrajobst** [comment] 2023-03-10 18:47
I checked the FWLink configuration and it points to `https://www.microsoft.com/net/dotnet_library_license.htm`; there is another field that for locale that is set to EN-US which can't be changed to anything neutral. I assume FWLink somehow injects `en-us` into the URL. I have changed the URL to `https://dotnet.microsoft.com/dotnet_library_license.htm` now, might take a few minutes to update in caches.

**Comment by terrajobst** [comment] 2023-03-10 19:12
@mairaw said it's working for her now.

**Comment by mairaw** [comment] 2023-03-10 19:22
To clarify, it works for the locales we support on dot.net. It won't work for Russian and other locales we don't support on dot.net for now.

Can't the installer include the clcid parameter so we have proper redirection to the correct language?

Once we have all languages supported, then we could have a single link.

**Comment by terrajobst** [comment] 2023-03-10 19:36
Looks like we addressed all links then, so closing.

**Comment by terrajobst** [comment] 2023-03-10 19:37
Ah, GitHub caching for the win. Didn't see @mairaw before refreshing the page. Sigh.

**Comment by dougbu** [comment] 2023-03-10 21:40
Up to everyone but in my opinion, we should close this issue. To do anything about it in the installer other than (say) using a new aka.ms link that goes to the neutral page would require a custom WiX extension to rewrite the links. That's not a simple project.

Or, worse, we'd need to manually update the translated WXL files and hope the loc team doesn't accidentally regress them later. This would be worse because those regressions seem likely and we'd need to update them whenever the set of available page translations increases.

From an old Teams conversation I had w/ @joeloff (not exactly about this issue):
> WiX doesn't offer anything. Assuming you were to cycle through those version strings, the best option would be to have those strings in a DLL that's localized, then have some custom build task that pulls them out and writes them to a wxl that's included in the compilation and you'd do the string selection off something like property that's set to different values like Alpha, Release Candidate, etc, but I'm just through ideas out.
>
> Well, WiX technically can support it. In Dev10, we had custom wix extensions (you can write custom preprocessor, compiler, linker, etc) extensions. Not sure if there's one for dealing with localization content, but it allows you to hook into the process. A binder extension might allow you to change a value during the final linking to modify the generated installer. They're not too difficult to write, but documentation is scarce. I wrote a compiler extension for ASP.NET long ago to modify web.config content for Razor that's in one of the old MVC/WSR branches

**Comment by terrajobst** [comment] 2023-03-21 00:46
> Up to everyone but in my opinion, we should close this issue. To do anything about it in the installer other than (say) using a new aka.ms link that goes to the neutral page would require a custom WiX extension to rewrite the links. That's not a simple project.

Agreed. I think letting the dot.net handle the redirect is largely fine.

**Closed** 2023-03-21 16:33 UTC
Labels: area-infrastructure, feature-installers
