### ISSUE TITLE
Quarantine Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcEnabled_Upgrade

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#42967] opened 2022-07-28 16:29 UTC
## Failing Test(s)

- Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcEnabled_Upgrade
- Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcDisabled_NoUpgrade

## Error Message

```text
System.Net.Quic.QuicException : The local address is already in use.
```

## Stacktrace

<details>

```text
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.QuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.QuicListener.ListenAsync(QuicListenerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.CreateListenerAsync() in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 72
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(EndPoint endpoint, IFeatureCollection features, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/QuicTransportFactory.cs:line 69
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, MultiplexedConnectionDelegate multiplexedConnectionDelegate, ListenOptions listenOptions, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 63
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 225
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 89
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/ListenOptions.cs:line 189
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 206
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 311
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 231
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Hosting/Hosting/src/GenericHost/GenericWebHostService.cs:line 137
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 141
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcEnabled_Upgrade() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 177
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.005s] [TestLifetime] [Information] Starting test Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcDisabled_NoUpgrade at 2022-07-28T00:56:55
[0.010s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.055s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests] [Error] Test threw an exception.
System.Net.Quic.QuicException: The local address is already in use.
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.QuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.QuicListener.ListenAsync(QuicListenerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.CreateListenerAsync() in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 72
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(EndPoint endpoint, IFeatureCollection features, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/QuicTransportFactory.cs:line 69
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, MultiplexedConnectionDelegate multiplexedConnectionDelegate, ListenOptions listenOptions, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 63
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 225
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 89
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/ListenOptions.cs:line 189
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 206
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 311
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 231
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Hosting/Hosting/src/GenericHost/GenericWebHostService.cs:line 137
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 141
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcDisabled_NoUpgrade() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 245
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[0.059s] [TestLifetime] [Information] Finished test Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcDisabled_NoUpgrade in 0.0546952s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1908015&view=ms.vss-test-web.build-test-results-tab&runId=49558196&resultId=108887&paneView=debug

**Comment by JamesNK** [comment] 2022-07-29 02:20
This seems like a System.Net.Quic bug. The test is using port 0 so the connection should be assigned an unused port.

Created issue: https://github.com/dotnet/runtime/issues/73036

**Comment by JamesNK** [comment] 2022-07-29 03:17
Investigated more and the problem is in Kestrel. New issue: https://github.com/dotnet/aspnetcore/issues/42982

**Comment by BrennanConroy** [comment] 2022-08-08 22:17
Tracking removing tests from https://github.com/dotnet/aspnetcore/blob/main/eng/test-configuration.json

**Comment by HaoK** [comment] 2022-09-02 17:31
@BrennanConroy is this actually fixed now so I should remove the tests from retry?

**Comment by BrennanConroy** [comment] 2022-09-02 17:33
I assume so, you would know the query to run to see if it's needed the retries or not.

**Comment by HaoK** [comment] 2022-09-02 22:46
Fixed by https://github.com/dotnet/aspnetcore/pull/43718

**Closed by HaoK** 2022-09-02 22:46 UTC
Labels: area-runtime, test-fixed
