### ISSUE TITLE
Analyzers should be invoked only in a single phase when compiling Razor projects 

### ISSUE THREAD

**Issue by mavasani** [dotnet/aspnetcore#25703] opened 2020-09-08 18:23 UTC
@pranavkm - should we move this aspnetcore to adjust the targets?

_Originally posted by @Pilchie in https://github.com/dotnet/roslyn/issues/47350#issuecomment-687458061_

**Comment by mavasani** [comment] 2020-09-08 18:23
See https://github.com/dotnet/roslyn/issues/47350#issuecomment-687398014 for details

**Comment by mkArtakMSFT** [comment] 2020-09-09 16:40
Thanks for contacting us. This is a dupe of #25365

**Closed by mkArtakMSFT** 2020-09-09 16:40 UTC
Labels: area-mvc
