### ISSUE TITLE
Missing Package targeting multiple frameworks

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#33747] opened 2021-06-22 08:37 UTC
I have a projet targeting both .Net 5 and .Net 6 preview

in csproj file I have:

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="5.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="5.0.7" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="6.0.0-preview.5.21301.17" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.0-preview.5.21301.17" />
  </ItemGroup>
```

When Compiling I get this error:

Error	CS0006	Metadata file 'C:\Users\Julien\.nuget\packages\microsoft.extensions.logging.abstractions\5.0.0\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll' could not be found

So  tried to add Microsoft.Extensions.Logging.Abstractions package for both targetframework.
But it doesn't change anything.

I found this workaround from @eilon :

```xml
<Target Name="RemoveLoggingAnalyzer" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)" Condition="%(FileName) == 'Microsoft.Extensions.Logging.Generators'" />
    </ItemGroup>
  </Target>
```

but it still doesn't work

**Comment by pranavkm** [comment] 2021-06-22 16:33
@Eilon did you file an issue for this with the SDK?

**Comment by pranavkm** [comment] 2021-06-22 16:37
Looks like a dupe of https://github.com/dotnet/sdk/issues/18148. We'll use the other issue to track resolving this.

**Closed by pranavkm** 2021-06-22 16:37 UTC
Labels: area-blazor
