### ISSUE TITLE
PlatformNotSupported exceptions in WindowsARM infrastructure for release/6.0

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#49061] opened 2023-02-28 19:26 UTC
These errors cause more issues down the road in Helix test runs for release/6.0 branch. For more details see: https://dev.azure.com/dnceng-public/public/_build/results?buildId=187657&view=ms.vss-test-web.build-test-results-tab&runId=3604263&resultId=120253&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

```log
2023-02-28T09:54:48.4281273Z  | System.PlatformNotSupportedException: EventLog access is not supported on this platform.
2023-02-28T09:54:48.4281453Z  |    at System.Diagnostics.EventLog..ctor(String logName, String machineName, String source)
2023-02-28T09:54:48.4281523Z  |    at Microsoft.Extensions.Logging.EventLog.WindowsEventLog..ctor(String logName, String machineName, String sourceName)
2023-02-28T09:54:48.4281704Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogSettings.CreateDefaultEventLog()
2023-02-28T09:54:48.4281771Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogSettings.get_EventLog()
2023-02-28T09:54:48.4281815Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogLogger..ctor(String name, EventLogSettings settings, IExternalScopeProvider externalScopeProvider)
2023-02-28T09:54:48.4282067Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogLoggerProvider.CreateLogger(String name)
2023-02-28T09:54:48.4282137Z  |    at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(String categoryName)
2023-02-28T09:54:48.4282184Z  |    at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
2023-02-28T09:54:48.4282368Z  |    at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory factory)
2023-02-28T09:54:48.4282438Z  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2023-02-28T09:54:48.4282626Z  |    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-02-28T09:54:48.4282844Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4283723Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4283984Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4284075Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4284273Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4284591Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4284665Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4284862Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4284933Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2023-02-28T09:54:48.4285122Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
2023-02-28T09:54:48.4285202Z  |    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2023-02-28T09:54:48.4285384Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2023-02-28T09:54:48.4285453Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2023-02-28T09:54:48.4285634Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2023-02-28T09:54:48.4285702Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2023-02-28T09:54:48.4286004Z  |    at Microsoft.Extensions.Hosting.HostBuilder.<CreateServiceProvider>b__28_2(IServiceProvider _)
2023-02-28T09:54:48.4286073Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4286257Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4286475Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4286546Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4286738Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2023-02-28T09:54:48.4286810Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
2023-02-28T09:54:48.4286997Z  |    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2023-02-28T09:54:48.4287066Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2023-02-28T09:54:48.4287350Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2023-02-28T09:54:48.4287459Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2023-02-28T09:54:48.4287655Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2023-02-28T09:54:48.4287725Z  |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
2023-02-28T09:54:48.4287770Z  |    at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
2023-02-28T09:54:48.4287953Z  |    at AspNetCore.Ogrwgduu3god.Program.Main(String[] args) in C:\h\w\AF430994\w\B61409EA\e\Templates\BaseFolder\AspNetCore.Ogrwgduu3god\Program.cs:line 23
2023-02-28T09:54:48.4288033Z  | --- End of stack trace from previous location ---
2023-02-28T09:54:48.4288079Z  |    at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
2023-02-28T09:54:48.4288257Z  |    at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
2023-02-28T09:54:48.4288324Z  |    at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass13_0.<ResolveServiceProviderFactory>b__3(String[] args)
2023-02-28T09:54:48.4288513Z  |    at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
2023-02-28T09:54:48.4288582Z  | An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: EventLog access is not supported on this platform.
2023-02-28T09:54:48.4288899Z  | No application service provider was found.
```

```json
{
  "ErrorMessage": "System.PlatformNotSupportedException: EventLog access is not supported on this platform.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=321995
**Result validation: :white_check_mark:** Known issue matched with the provided build.

**Comment by wtgodbe** [comment] 2023-06-27 19:45
Moved to aspnetcore. This failure is only happening in the helix-matrix pipeline, where we test on an expanded set of queues - it doesn't impact the main CI jobs. If the answer is that these tests won't be able to run on those arm queues for the foreseeable future, we could consider skipping them.

**Comment by dougbu** [comment] 2023-06-27 19:54
thanks @wtgodbe, that might be the best choice

we checked internally and @AlitzelMendez confirmed the tests should be running as an administrator. no idea what would be special on this platform &mdash; unless Windows ARM64 or windows.11.arm64.open is special in some other (unknown) way

**Comment by wtgodbe** [comment] 2023-06-27 19:56
> confirmed the tests should be running as an administrator.

Does this mean "We expect that the tests are currently running as admin", or "The reason the tests are failing is that they are not running as admin"?

**Comment by dougbu** [comment] 2023-06-27 19:57
> > confirmed the tests should be running as an administrator.
> 
> Does this mean "We expect that the tests are currently running as admin", or "The reason the tests are failing is that they are not running as admin"?

the first

**Comment by wtgodbe** [comment] 2023-06-27 20:32
In that case, we don't understand why the tests are failing. I just queued a run against `main` with the tests unskipped to see if that gives us more info: https://dev.azure.com/dnceng-public/public/_build/results?buildId=322883&view=results

**Comment by wtgodbe** [comment] 2023-06-27 23:20
`BlazorWasmHostedTemplate_IndividualAuth_Works_WithLocalDB` passed on `windows.11.arm64.open` in `main`, so something is different between there and 6.0. Open question is if that something is in aspnetcore or runtime. In any case, it doesn't seem to be an issue for core-eng

**Comment by wtgodbe** [comment] 2023-06-27 23:21
One notable difference is that the tests run on Playwright in main, rather than selenium

**Comment by mkArtakMSFT** [comment] 2023-06-28 15:00
> it doesn't seem to be an issue for core-eng

Does this mean we have to move this over to the dotnet/aspnetcore then ?

**Comment by wtgodbe** [comment] 2023-07-18 18:34
This looks like a real issue, not related to Selenium/Playwright - the same tests pass on 7.0, which (like 6.0) also runs on Selenium.

**Comment by ViktorHofer** [comment] 2023-07-19 14:26
I don't think that that's related. TargetsWindows was the old way for a managed library to target a TFM platform RID in runtime, while TargetPlatformIdentifier is the new common way to condition on a platform on managed code. That shouldn't make a difference.

**Comment by wtgodbe** [comment] 2023-07-19 15:50
@ViktorHofer how could a PNSE get thrown here then (only on win11-arm64, only in 6.0)? I don't see `https://github.com/dotnet/runtime/blob/3b204ac0f9894cddd95f7cc9e4ae66e53f60d222/src/libraries/System.Diagnostics.EventLog/src/Resources/Strings.resx#L212-L214` referenced anywhere except in the .csproj where I linked, nor do I see `GeneratePlatformNotSupportedAssemblyMessage` used in any meaningful way repo-wide other than for determining if a library is eligible for Intellisense or CodeOptimization. And the only place I see a PNSE being thrown in that library is here, which doesn't appear to be platform specific: https://github.com/dotnet/runtime/blob/3b204ac0f9894cddd95f7cc9e4ae66e53f60d222/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogEntry.cs#L451-L454

**Comment by wtgodbe** [comment] 2023-07-19 16:09
@DamianEdwards these template tests fail in 6.0 on Win11-arm64 because (presumably) they're not running as admin on the Helix queue. Is it possible https://github.com/dotnet/aspnetcore/pull/41563 could be the reason that they pass on that queue in 7.0? It doesn't port cleanly to 6.0 at all, so I want to make sure it's plausible that it could fix the issue before I start trying to port it manually.

**Comment by DamianEdwards** [comment] 2023-07-19 16:42
@wtgodbe honestly I have no idea, it was so long ago I went deep on that. I don't recall admin being the root of any issues, rather it was almost all about test project factorings causing timeouts. IIRC most of my changes were just improving logging of timeout issues and refactoring into more test projects with less tests in them so the Helix jobs were smaller.

**Comment by wtgodbe** [comment] 2023-07-25 17:05
@ViktorHofer @buyaa-n could you tell me more about how the `notsupported.cs` files get generated? These failing tests are all Web template tests, so I wonder if it could be that the `TargetPlatformIdentifier` is `browser` and not `windows` (though I'm not sure yet why that'd cause the failure only in 6.0 and not 7.0/main)

https://github.com/dotnet/runtime/blob/4bc0fe951dc90c5af58631f23f194ab7985892d5/src/libraries/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj#L25

**Comment by danmoseley** [comment] 2023-10-05 02:59
Just came across this.

I don't think this can be caused by not running as admin (although of course a test may fail for that, if it's not conditioned, but it won't produce this message).

I also don't think this can be caused by a call into the OS returning an error. Eg., on Nano the OS will error because there's no event logs, but it won't be this message.

This message comes only from the facades, as Victor says. All versions of Windows OS should have concrete implementations. Somehow the System.Diagnostics.EventLog.dll that the tests are loading is the facade. It would be good to see the repro machine.

**Comment by danmoseley** [comment] 2023-10-05 03:01
@carlossanlop does this still fail for you on your arm box?
`dotnet build -a arm64 /t:test /p:TargetFramework=net6.0 .src\libraries\Microsoft.Extensions.Logging\tests\Common\Microsoft.Extensions.Logging.Tests.csproj`

If so perhaps @ViktorHofer can look. (Hopefully he can remember how things worked in 6.0!)

**Comment by carlossanlop** [comment] 2023-10-05 16:52
@danmoseley I tried building 6.0 in my arm64 laptop again, but I formatted it not too long ago and I'm getting lots of errors preventing a successful build. I would have to investigate them so that I can run those tests. Not sure when can I get an answer though.

**Comment by wtgodbe** [comment] 2023-10-11 20:16
I got access to a Win11-arm64 box & was able to build & run the templates w/ a 6.0 SDK without any issue (webapi, mvc), so that points to a test issue rather than a real product issue. Going to see if I can run the tests now.

**Comment by wtgodbe** [comment] 2023-10-11 21:49
I think I figured out why this is happening, and now feel pretty silly. In 6.0, we have two jobs in the helix matrix - a job that builds on Windows and sends tests to x64 queues, and a job that builds on Linux that sends tests to arm64 queues. Whereas in 7.0 and above, we build everything on Windows only. So the reason for the PNSE is likely that the bits we're running on win11-arm64 in 6.0 were built on Linux. To be honest I'm not entirely sure how that works, but it makes me feel more comfortable about skipping those tests on that queue in 6.0. I'm spinning up a branch for that now.

**Comment by danmoseley** [comment] 2023-10-12 18:58
woo hoo Will -- so glad you figured that out.

**Comment by dougbu** [comment] 2023-10-12 19:02
>  To be honest I'm not entirely sure how that works

Perhaps release/6.0 doesn't disable crossgen❔ If that's the case, would expect broader failures however.

**Comment by danmoseley** [comment] 2023-10-12 19:05
Yeah, I would expect that in more cases than this library it is restoring the PNSE assemblies because there are numerous Windows-only libraries. Eg., performance counters.

**Comment by wtgodbe** [comment] 2024-01-24 21:14
Done by https://github.com/dotnet/aspnetcore/pull/51311

**Closed by wtgodbe** 2024-01-24 21:14 UTC
Labels: test-failure, area-infrastructure, Known Build Error
