### ISSUE TITLE
Blazor StateHasChanged not working

### ISSUE THREAD

**Issue by ScottKane** [dotnet/aspnetcore#31408] opened 2021-03-31 06:53 UTC
Sorry for the below code dump.

I have the following page, it passes a `List<Order>` to my `Table<TItem>` component. The old table was my first draft using a bit of reflection to allow a form inside the component to pass a new TItem back to the page via an OnCreated delegate. It worked in a very rough way, where I could create a simple POCO class without any depth and pass it back to the page. The only real difference is in my second version, rather than looping through the list of TItems, I flatten all of the objects into a `List<Dictionary<string, object>>` and use that instead, So that I have access to all of the properties no matter the depth.

When I add an Item in v1, the object is returned to the page, the list is updated and the component automatically re-renders without calling `StateHasChanged()`.

In v2 the object is returned and added to the page in the same way, the list is updated but the component never re-renders. I've tried calling `StateHasChanged()` after the delegate call in the component and also in the page. Neither with any luck. If I navigate away from the page and back again, the newly added value appears in the component, so there's no reason why `StateHasChanged()` isn't updating the component.

The second version creates the object differently so I've included my Utilities to be thorough.

Orders Page:
```razor
@page "/orders"

@inject FakeOrders Fake

@if (_created)
{
    <div class="success" role="alert">@($"{_order.FirstName} {_order.LastName} created!")</div>
}

<Table TItem="Order" Items="@Fake.Orders" Sortable="true" Filterable="true" Editable="true" OnCreated="@OnCreated" />

@code {
    private bool _created;
    private Order _order;

    public void OnCreated(Order order)
    {
        _order = order;
        Fake.Orders.Add(order);
        _created = true;
        StateHasChanged();
    }
}
```

Old Table:
```razor
@using System.Linq
@using System.Reflection 

@typeparam TItem

@if (Items is null || _filteredItems is null)
{
    <fast-progress></fast-progress>
}
else if (Items.Count.Equals(0))
{
    <text>Nothing to display.</text>
}
else
{
    if (_properties is not null)
    {
        if (Editable && OnCreated.HasDelegate)
        {
            if (_showCreate)
            {
                <Modal>                   
                    <EditForm Model="_item" OnValidSubmit="CreateItem" Context="form">
                        <DataAnnotationsValidator />
                        <ValidationSummary />
                        @foreach (var property in _properties)
                        {
                            var propertyInfo = _type.GetProperty(property.Name);
                            <div>
                                @if (propertyInfo.PropertyType.IsEnum)
                                {
                                    var values = Enum.GetValues(propertyInfo.PropertyType);
                                    if (values is not null && values.Length > 0)
                                    {
                                        _itemProperties[property.Name].Value = values.GetValue(0).ToString();

                                        <fast-select>
                                            @foreach (var value in values)
                                            {
                                                <fast-option value="@value.ToString()" @onclick="@(() => _itemProperties[property.Name].Value = value.ToString())">@value.ToString()</fast-option>
                                            }
                                        </fast-select>
                                    }
                                }
                                else if (propertyInfo.PropertyType == typeof(Guid)) { }
                                else
                                {
                                    <ValidationMessage For="@(() => _itemProperties[property.Name].Value)" />
                                    <FormInputText Type="text" Id="@property.Name.ToLower()" Placeholder="@property.Name" @bind-Value="_itemProperties[property.Name].Value"></FormInputText>
                                }
                            </div>
                        }
                        <fast-button type="submit" appearance="accent">Add</fast-button>
                    </EditForm>
                </Modal>
            }
        }

        <div class="table">
            <div class="table-head table-row">
                @foreach (var property in _properties)
                {
                    <div class="table-head-col">
                        @if (Filterable)
                        {
                            <div class="table-head-col-start@(GetFilterStyle(property.Name))" @onclick="@(() => ToggleFilter(property.Name))"><div><i class="fas fa-search"></i></div></div>
                        }
                        @if (Sortable)
                        {
                            <div class="table-head-col-middle" @onclick="@(() => SortTable(property.Name))"><div>@property.Name</div></div>
                            <div class="table-head-col-end" @onclick="@(() => SortTable(property.Name))">@*<i class="@GetSortStyle(property.Name)"></i></div>*@
                                @if (_currentSortColumn == property.Name)
                                {
                                    <div>
                                        @if (_sortedAscending)
                                        {
                                            <svg class="svg-inline--fa fa-chevron-up fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-up" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M240.971 130.524l194.343 194.343c9.373 9.373 9.373 24.569 0 33.941l-22.667 22.667c-9.357 9.357-24.522 9.375-33.901.04L224 227.495 69.255 381.516c-9.379 9.335-24.544 9.317-33.901-.04l-22.667-22.667c-9.373-9.373-9.373-24.569 0-33.941L207.03 130.525c9.372-9.373 24.568-9.373 33.941-.001z"></path></svg>
                                        }
                                        else
                                        {
                                            <svg class="svg-inline--fa fa-chevron-down fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-down" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M207.029 381.476L12.686 187.132c-9.373-9.373-9.373-24.569 0-33.941l22.667-22.667c9.357-9.357 24.522-9.375 33.901-.04L224 284.505l154.745-154.021c9.379-9.335 24.544-9.317 33.901.04l22.667 22.667c9.373 9.373 9.373 24.569 0 33.941L240.971 381.476c-9.373 9.372-24.569 9.372-33.942 0z"></path></svg>
                                        }
                                    </div>
                                }
                            </div>
                        }
                        else
                        {
                            <div class="table-head-col-middle"><div>@property.Name</div></div>
                        }
                    </div>
                }
                @if (Editable)
                {
                    <div class="table-head-col">
                        <div class="table-head-col-middle">
                            <div><fast-button appearance="accent" @onclick="ToggleCreate">Add</fast-button></div>
                        </div>
                    </div>
                }
            </div>

            @if (_filteredColumns.Any())
            {
                <div class="table-filter table-row">
                    @foreach (var property in _properties)
                    {
                        if (_filteredColumns.ContainsKey(property.Name))
                        {
                            <fast-text-field type="text" class="table-filter-item" placeholder="Filter @property.Name" value="@_filteredColumns[property.Name]" @oninput="@((input) => SetFilter(property.Name, input.Value.ToString()))"></fast-text-field>
                        }
                        else
                        {
                            <div></div>
                        }
                    }
                </div>
            }

            @foreach (var item in _filteredItems)
            {
                <div class="table-row">
                    @foreach (var property in _properties)
                    {
                        <div>@item.GetType().GetProperty(property.Name)?.GetValue(item)</div>
                    }
                </div>
            }
        </div>
    }
}

@code {
    [Parameter] public IList<TItem> Items { get; set; }
    [Parameter] public bool Sortable { get; set; }
    [Parameter] public bool Filterable { get; set; }
    [Parameter] public bool Editable { get; set; }
    [Parameter] public EventCallback<TItem> OnCreated { get; set; }

    private IQueryable<TItem> _filteredItems;

    private string? _currentSortColumn;
    private bool _sortedAscending;
    private bool _showCreate;

    private TItem _item = new TItem();
    private Type _type;
    private PropertyInfo[] _properties;
    private Dictionary<string, FormResponse> _itemProperties = new Dictionary<string, FormResponse>();

    private readonly Dictionary<string, string> _filteredColumns = new Dictionary<string, string>();

    public void ToggleCreate()
    {
        _showCreate = !_showCreate;
        ShouldRender();
    }

    private void CreateItem()
    {
        foreach (var property in _properties)
        {
            var propertyInfo = _type.GetProperty(property.Name);
            if (propertyInfo is not null)
            {
                switch (propertyInfo.GetValue(_item))
                {
                    default:
                        if (propertyInfo.PropertyType.IsEnum)
                        {
                            var values = Enum.GetValues(propertyInfo.PropertyType);
                            foreach (var value in values)
                                if (value.ToString().Equals(_itemProperties[property.Name].Value))
                                    propertyInfo.SetValue(_item, value);
                        }
                        else propertyInfo.SetValue(_item, _itemProperties[property.Name].Value);
                        break;
                    case Guid:
                        propertyInfo.SetValue(_item, Guid.NewGuid());
                        break;
                }
            }
        }

        OnCreated.InvokeAsync(_item);
        ToggleCreate();
    }

    private string GetSortStyle(string columnName)
    {
        if (_currentSortColumn != columnName) return string.Empty;
        ShouldRender();
        return _sortedAscending ? "fas fa-chevron-up" : "fas fa-chevron-down";
    }

    private void SortTable(string columnName)
    {
        if (columnName != _currentSortColumn)
        {
            _filteredItems = _filteredItems.OrderBy(item => item.GetType().GetProperty(columnName).GetValue(item));
            _currentSortColumn = columnName;
            _sortedAscending = true;
        }
        else
        {
            _sortedAscending = !_sortedAscending;
            _filteredItems = _sortedAscending
                ? _filteredItems.OrderBy(item => item.GetType().GetProperty(columnName).GetValue(item))
                : _filteredItems.OrderByDescending(item => item.GetType().GetProperty(columnName).GetValue(item));
        }
    }

    private string GetFilterStyle(string columnName) => _filteredColumns.ContainsKey(columnName) ? string.Empty : " muted";

    private void ToggleFilter(string columnName)
    {
        if (_filteredColumns.ContainsKey(columnName)) _filteredColumns.Remove(columnName);
        else _filteredColumns.Add(columnName, null);
        ApplyFilter();
        ApplySort();
    }

    private void SetFilter(string columnName, string filter)
    {
        if (!_filteredColumns.ContainsKey(columnName)) return;
        _filteredColumns[columnName] = filter;
        ApplyFilter();
        ApplySort();
    }

    private void ApplyFilter()
    {
        _filteredItems = Items.AsQueryable();

        foreach (var (key, value) in _filteredColumns)
        {
            if (string.IsNullOrWhiteSpace(value)) continue;

            if (value.StartsWith('"') && value.EndsWith('"'))
                _filteredItems = _filteredItems
                    .Where(item => item
                        .GetType()
                        .GetProperty(key)
                        .GetValue(item)
                        .ToString()
                        .ToUpper()
                        .Equals(value.Trim('"').ToUpper()));
            else _filteredItems = _filteredItems
                    .Where(item => item
                        .GetType()
                        .GetProperty(key)
                        .GetValue(item)
                        .ToString()
                        .ToUpper()
                        .Contains(value.ToUpper()));
        }
    }

    private void ApplySort()
    {
        if (_currentSortColumn is null) return;
        _sortedAscending = !_sortedAscending;
        SortTable(_currentSortColumn);
    }

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        _filteredItems = Items?.AsQueryable();
        _properties = Items.FirstOrDefault()?.GetType().GetProperties();
        _type = _item.GetType();
        _itemProperties = _properties.ToDictionary(
            x => x.Name,
            x => new FormResponse(string.Empty, x.PropertyType));
    }
}
```

New Table:
```razor
@using static Components.Utilities;

@typeparam TItem

@if (Items is null || _filteredItems is null)
{
    <fast-progress></fast-progress>
}
else if (Items.Count.Equals(0))
{
    <text>Nothing to display.</text>
}
else
{
    if (_properties is not null)
    {
        if (Editable && OnCreated.HasDelegate)
        {
            if (_showCreate)
            {
                <Modal>
                    <EditForm Model="_item" OnValidSubmit="CreateItem" Context="form">
                        <DataAnnotationsValidator />
                        <ValidationSummary />
                        @foreach (var (key, value) in _formProperties)
                        {
                            var property = GetPropertyFromKey(key, _item);
                            if (!Attribute.IsDefined(property, typeof(CreateIgnoreAttribute)))
                            {
                                var propertyType = property.PropertyType;
                                if (propertyType.IsEnum)
                                {
                                    var enumValues = Enum.GetValues(propertyType);
                                    if (enumValues is not null && enumValues.Length > 0)
                                    {
                                        _formProperties[key].Value = ((int)Enum.Parse(propertyType, enumValues.GetValue(0).ToString())).ToString();
                                        <fast-select>
                                            @foreach (var enumValue in enumValues)
                                            {
                                                <fast-option value="@enumValue.ToString()" @onclick="@(() => _formProperties[key].Value = ((int)Enum.Parse(propertyType, enumValue.ToString())).ToString())">@enumValue.ToString()</fast-option>
                                            }
                                        </fast-select>
                                    }
                                }
                                else if (propertyType == typeof(Guid))
                                {
                                    _formProperties[key].Value = Guid.NewGuid().ToString();
                                }
                                else
                                {
                                    <ValidationMessage For="@(() => _formProperties[key].Value)" />
                                    <FormInputText Type="text" Id="@property.Name.ToLower()" Placeholder="@property.Name" @bind-Value="_formProperties[key].Value"></FormInputText>
                                }
                            }
                        }
                        <fast-button type="submit" appearance="accent">Add</fast-button>
                    </EditForm>
                </Modal>
            }
        }

        <div class="table">
            <div class="table-head table-row">
                @foreach (var property in _properties)
                {
                    <div class="table-head-col">
                        @if (Filterable)
                        {
                            <div class="table-head-col-start@(GetFilterStyle(property.Key))" @onclick="@(() => ToggleFilter(property.Key))"><div><i class="fas fa-search"></i></div></div>
                        }
                        @if (Sortable)
                        {
                            <div class="table-head-col-middle" @onclick="@(() => SortTable(property.Key))"><div>@property.Key.Split('.').Last()</div></div>
                            <div class="table-head-col-end" @onclick="@(() => SortTable(property.Key))">
                                @*<i class="@GetSortStyle(property.Name)"></i></div>*@
                                @if (_currentSortColumn == property.Key)
                                {
                                    <div>
                                        @if (_sortedAscending)
                                        {
                                            <svg class="svg-inline--fa fa-chevron-up fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-up" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M240.971 130.524l194.343 194.343c9.373 9.373 9.373 24.569 0 33.941l-22.667 22.667c-9.357 9.357-24.522 9.375-33.901.04L224 227.495 69.255 381.516c-9.379 9.335-24.544 9.317-33.901-.04l-22.667-22.667c-9.373-9.373-9.373-24.569 0-33.941L207.03 130.525c9.372-9.373 24.568-9.373 33.941-.001z"></path></svg>
                                        }
                                        else
                                        {
                                            <svg class="svg-inline--fa fa-chevron-down fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-down" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M207.029 381.476L12.686 187.132c-9.373-9.373-9.373-24.569 0-33.941l22.667-22.667c9.357-9.357 24.522-9.375 33.901-.04L224 284.505l154.745-154.021c9.379-9.335 24.544-9.317 33.901.04l22.667 22.667c9.373 9.373 9.373 24.569 0 33.941L240.971 381.476c-9.373 9.372-24.569 9.372-33.942 0z"></path></svg>
                                        }
                                    </div>
                                }
                            </div>
                        }
                        else
                        {
                            <div class="table-head-col-middle"><div>@property.Key</div></div>
                        }
                    </div>
                }
                @if (Editable)
                {
                    <div class="table-head-col">
                        <div class="table-head-col-middle">
                            <div><fast-button appearance="accent" @onclick="ToggleCreate">Add</fast-button></div>
                        </div>
                    </div>
                }
            </div>

            @if (_filteredColumns.Any())
            {
                <div class="table-filter table-row">
                    @foreach (var property in _properties)
                    {
                        if (_filteredColumns.ContainsKey(property.Key))
                        {
                            <fast-text-field type="text" class="table-filter-item" placeholder="Filter @property.Key.Split('.').Last()" value="@_filteredColumns[property.Key]" @oninput="@((input) => SetFilter(property.Key, input.Value.ToString()))"></fast-text-field>
                        }
                        else
                        {
                            <div></div>
                        }
                    }
                </div>
            }

            @foreach (var item in _filteredItems)
            {
                <div class="table-row">
                    @foreach (var (key, value) in _properties)
                    {
                        var property = GetPropertyFromKey(key, _item);
                        if (property.PropertyType.IsEnum)
                        {
                            <div>@Enum.GetName(property.PropertyType, item[key])</div>
                        }
                        else
                        {
                            <div>@item[key]</div>
                        }
                    }
                </div>
            }
        </div>
    }
}

@code {
    [Parameter] public IList<TItem> Items { get; set; }
    [Parameter] public bool Sortable { get; set; }
    [Parameter] public bool Filterable { get; set; }
    [Parameter] public bool Editable { get; set; }
    [Parameter] public EventCallback<TItem> OnCreated { get; set; }

    private IList<Dictionary<string, object>> _items;
    private IQueryable<Dictionary<string, object>> _filteredItems;

    private string _currentSortColumn;
    private bool _sortedAscending;
    private bool _showCreate;

    private TItem _item;
    private Dictionary<string, object> _properties;
    private Dictionary<string, FormResponse> _formProperties;
    private readonly Dictionary<string, string> _filteredColumns = new Dictionary<string, string>();

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        _item = CreateDefaultItem<TItem>();
        _items = new List<Dictionary<string, object>>();
        foreach (var item in Items) _items.Add(GetItemProperties(item));
        _filteredItems = _items.AsQueryable();
        _properties = GetItemProperties(_item);
        _formProperties = GetFormItemProperties(_properties);
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        if (!firstRender)
        {
            _items = new List<Dictionary<string, object>>();
            foreach (var item in Items) _items.Add(GetItemProperties(item));
        }
    }

    private void ToggleCreate() => _showCreate = !_showCreate;

    private async Task CreateItem()
    {
        _item = CreateFormItem<TItem>(_formProperties);
        ToggleCreate();
        await OnCreated.InvokeAsync(_item);
    }

    private string GetSortStyle(string columnName)
    {
        if (_currentSortColumn != columnName) return string.Empty;
        return _sortedAscending ? "fas fa-chevron-up" : "fas fa-chevron-down";
    }

    private void ApplySort()
    {
        if (_currentSortColumn is null) return;
        _sortedAscending = !_sortedAscending;
        SortTable(_currentSortColumn);
    }

    private void SortTable(string columnName)
    {
        if (columnName != _currentSortColumn)
        {
            _filteredItems = _filteredItems.OrderBy(item => item[columnName]);
            _currentSortColumn = columnName;
            _sortedAscending = true;
        }
        else
        {
            _sortedAscending = !_sortedAscending;
            _filteredItems = _sortedAscending
                ? _filteredItems.OrderBy(item => item[columnName])
                : _filteredItems.OrderByDescending(item => item[columnName]);
        }
    }

    private string GetFilterStyle(string columnName) => _filteredColumns.ContainsKey(columnName) ? string.Empty : " muted";

    private void ToggleFilter(string columnName)
    {
        if (_filteredColumns.ContainsKey(columnName)) _filteredColumns.Remove(columnName);
        else _filteredColumns.Add(columnName, null);
        ApplyFilter();
        ApplySort();
    }

    private void SetFilter(string columnName, string filter)
    {
        if (!_filteredColumns.ContainsKey(columnName)) return;
        _filteredColumns[columnName] = filter;
        ApplyFilter();
        ApplySort();
    }

    private void ApplyFilter()
    {
        _filteredItems = _items.AsQueryable();

        foreach (var (key, value) in _filteredColumns)
        {
            if (string.IsNullOrWhiteSpace(value)) continue;

            var property = GetPropertyFromKey(key, _item);
            if (property.PropertyType.IsEnum)
            {
                if (value.StartsWith('"') && value.EndsWith('"'))
                    _filteredItems = _filteredItems
                        .Where(item => Enum.GetName(property.PropertyType, item[key])
                            .ToUpper()
                            .Equals(value.Trim('"').ToUpper()));
                else _filteredItems = _filteredItems
                        .Where(item => Enum.GetName(property.PropertyType, item[key])
                            .ToUpper()
                            .Contains(value.ToUpper()));
            }
            else
            {
                if (value.StartsWith('"') && value.EndsWith('"'))
                    _filteredItems = _filteredItems
                        .Where(item => item[key]
                            .ToString()
                            .ToUpper()
                            .Equals(value.Trim('"').ToUpper()));
                else _filteredItems = _filteredItems
                        .Where(item => item[key]
                            .ToString()
                            .ToUpper()
                            .Contains(value.ToUpper()));
            }
        }
    }
}
```
Utilities:
```c#
using JsonFlatten;
using Newtonsoft.Json.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.Json;

namespace Components
{
    public static class Utilities
    {
        public static object SetPropertyValueFromKey(string key, object item, object value, string[] properties = null)
        {
            var propertyNames = properties is null ? key.Split('.').ToList() : properties.ToList();
            var type = item.GetType();
            if (propertyNames.Count == 1)
            {
                type.GetProperty(propertyNames.FirstOrDefault()).SetValue(item, value);
                return item;
            }

            var names = key.Split('.')[1..];
            item = type.GetProperty(propertyNames.FirstOrDefault()).GetValue(item);

            return SetPropertyValueFromKey(string.Join('.', names), item, value, names);
        }

        public static object GetPropertyValueFromKey(string key, object item, string[] properties = null)
        {
            var propertyNames = properties is null ? key.Split('.').ToList() : properties.ToList();
            var type = item.GetType();
            if (propertyNames.Count == 1) return type.GetProperty(propertyNames.FirstOrDefault()).GetValue(item);

            var names = key.Split('.')[1..];
            item = type.GetProperty(propertyNames.FirstOrDefault()).GetValue(item);

            return GetPropertyValueFromKey(string.Join('.', names), item, names);
        }

        public static PropertyInfo GetPropertyFromKey(string key, object item, string[] properties = null)
        {
            var propertyNames = properties is null ? key.Split('.').ToList() : properties.ToList();
            var type = item.GetType();
            if (propertyNames.Count == 1) return type.GetProperty(propertyNames.FirstOrDefault());

            var names = key.Split('.')[1..];
            item = type.GetProperty(propertyNames.FirstOrDefault()).GetValue(item);

            return GetPropertyFromKey(string.Join('.', names), item, names);
        }

        public static Dictionary<string, FormResponse> GetFormItemProperties(Dictionary<string, object> properties) => properties.ToDictionary(x => x.Key, x => x.Value is string ? new FormResponse(x.Value.ToString(), x.Value.GetType()) : new FormResponse(JsonSerializer.Serialize(x.Value), x.Value.GetType()));
        public static Dictionary<string, object> GetItemProperties(object item) => (Dictionary<string, object>)JObject.Parse(JsonSerializer.Serialize(item)).Flatten();
        public static TItem CreateFormItem<TItem>(Dictionary<string, FormResponse> formProperties) => (TItem)CreateFormItem(typeof(TItem), formProperties);
        public static TItem CreateDefaultItem<TItem>() => (TItem)CreateDefaultItem(typeof(TItem));

        public static object CreateFormItem(Type type, Dictionary<string, FormResponse> formProperties, object result = null)
        {
            static object FormResponseToObject(string value, Type type)
            {
                if (type == typeof(string)) return value;
                if (type.Name.Contains("EmptyPartition")) type = typeof(List<object>);
                return JsonSerializer.Deserialize(value, type);
            }

            var properties = formProperties.ToDictionary(x => x.Key, x => FormResponseToObject(x.Value.Value, x.Value.Type));

            return JsonSerializer.Deserialize(properties.Unflatten().ToString(), type);
        }

        public static object CreateDefaultItem(Type type, object item = null)
        {
            void SetProperty(PropertyInfo property, object instance)
            {
                if (property.PropertyType.IsPrimitive || property.PropertyType.IsEnum || property.PropertyType == typeof(string))
                {
                    if (!type.IsAssignableTo(typeof(IList)) && !type.IsInterface)
                    {
                        if (property.PropertyType.IsPrimitive) property.SetValue(instance, Activator.CreateInstance(property.PropertyType));
                        if (property.PropertyType == typeof(string)) property.SetValue(instance, string.Empty);
                    }
                }
                else
                {
                    property.SetValue(item, Activator.CreateInstance(property.PropertyType));
                    CreateDefaultItem(property.PropertyType, property.GetValue(item));
                }
            }

            if (item is null) item = Activator.CreateInstance(type);

            foreach (var property in type.GetProperties())
                if (property.GetSetMethod() is not null)
                    SetProperty(property, item);

            return item;
        }
    }
}

```

Using latest stable versions of everything for .NET 5.

**Comment by mkArtakMSFT** [comment] 2021-03-31 16:47
Thanks for contacting us.
This is a lot of code and we don't have capacity to look into customer apps. Instead, we recommend minimizing a repro to only the bits which are essential for the repro and sharing it as a publicly hosted GitHub repository.
We'll wait for you to share that instead.

**Comment by ScottKane** [comment] 2021-03-31 18:00
Here is a project showing the issue in it's simplest form: https://github.com/ScottKane/ComponentDoesntReRender

1. Run project.
2. Note names on index page.
3. Add a new person with the form.
4. Notice message proving the newly created person exists in the list in index, but isn't actually rendered in the component.
5. Navigate to counter and then back to index.
6. Notice the added person is now in the list.

I have tried both with/without StateHasChanged() calls in both the page and component.

Page:
```c#
public void OnCreated(Person person)
{
    _person = person;
    _created = true;
    Fake.People.Add(person);
    StateHasChanged();
}
```

Component:
```c#
private async Task CreateItem()
{
    _item = CreateFormItem<TItem>(_formProperties);
    await OnCreated.InvokeAsync(_item);
    StateHasChanged();
}
```

**Comment by SteveSandersonMS** [comment] 2021-04-01 16:37
I don't know for certain since it would take a while to investigate this much code, but is it possible that you were expecting that calling `StateHasChanged` in one component would cause some other component also to re-render? If so that would be a misunderstanding of what `StateHasChanged` does.

Another way to make progress with this enquiry might be asking on StackOverflow, particularly if you can give a more concise description. Generally the team here tries not to debug community code since our capacity is limited, especially in cases like this where the API in question is extremely well established and known to behave as designed. Hope that seems reasonable!

**Comment by campersau** [comment] 2021-04-01 17:17
The `Items` are copied to `_items` in `OnInitialize` which is only called once. You need to create that copy in `OnParametersSet` so it will get updated when the state and thus the parameters changes.

See https://github.com/ScottKane/ComponentDoesntReRender/pull/1

**Comment by enetstudio** [comment] 2021-04-01 18:16
I've answered your question in [stackoverflow](https://stackoverflow.com/a/66909598/6152891). Please don't fail to upvote the answer.

**Comment by SteveSandersonMS** [comment] 2021-04-01 18:24
Thanks, commmunity! Closing as answered.

**Closed by SteveSandersonMS** 2021-04-01 18:24 UTC
Labels: Needs: Author Feedback, area-blazor

**Comment by ScottKane** [comment] 2021-04-01 18:32
Brilliant! Thanks so much for taking the time guys. Upvoted on stack 👍
