### ISSUE TITLE
Extending TypedResults static class functionality

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnetcore#47642] opened 2023-04-11 12:20 UTC
Hi,
I want to extend functionality `TypedResults` class and add some other methods like `InternalProblem()` related to #47623, but because this class is not partial it is not possible.

**Comment by mitchdenny** [comment] 2023-04-12 10:52
@mehdihadeli is this a dupe of the issue you referenced? If so its not necessary to create another issue. Please consider closing this if it is a dupe to avoid fragmenting the conversatation.

**Closed** 2023-04-12 11:04 UTC
Labels: Needs: Author Feedback, area-web-frameworks
