### ISSUE TITLE
Cannot debug Blazor Wasm application on .Net 6: Unable to attach to browser

### ISSUE THREAD

**Issue by Hastaroth1** [dotnet/aspnetcore#41443] opened 2022-04-29 18:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When launching a Blazor wasm application in debug, the browser (either Chrome or Edge) tab will open and the application will crash with "got exception System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '500' when status code '101' was expected."

By setting `"launchBrowser": false`, I can open a Chrome tab to the application but the debugging still doesn't work.

If I use `Shift-Alt-D`, I get a page that says `Unable to find debuggable browser tab. Could not get a list of browser tabs from http://localhost:9222/json. Ensure your browser is running with debugging enabled.`.
I can however navigate to `http://localhost:9222/json` and see the document.

This is very similar to https://github.com/dotnet/aspnetcore/issues/26824 but the fix does not work for me.

I have uninstalled every other .Net sdk version and have tried with my proxy disabled.

This happens with every Blazor Wasm app I can launch including the default project template.

This issue does not happen with Firefox but it shows a message that debugging is explicitly not supported

### Expected Behavior

The application should open in the browser all allow breakpoints to be set in the code.

### Steps To Reproduce

- Install .Net 6
- Create a new project with `dotnet new blazorwasm`
- Open the project in Visual Studio 2022
- Launch the application either with IIS or Kestrel targetting Chrome or Edge

### Exceptions (if any)

got exception System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '500' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
   at Microsoft.WebAssembly.Diagnostics.DebugExtensions.<>c__DisplayClass2_0.<<UseDebugProxy>g__ConnectProxy|5>d.MoveNext()

### .NET Version

6.0.202

### Anything else?

I'm using Visual Studio Professional 2022 v17.1.6
Using Chrome Version 101.0.4951.41 (Official Build) (64-bit)
Using Edge Version 100.0.1185.50 (Official build) (64-bit)

`dotnet --info` output:

F:\temp>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

![image](https://user-images.githubusercontent.com/12807348/165998882-d2b14db5-f828-4363-9194-5b4f465307bc.png)

What Chrome shows before crashing:

![image](https://user-images.githubusercontent.com/12807348/165998956-906213a4-712f-40fa-b72a-67384b2c360f.png)

The debug tab:

![image](https://user-images.githubusercontent.com/12807348/165999408-f24d81c9-b079-4083-9d65-93ee948b6e9b.png)

Log in visualstudio-js-debugger.txt:

`{"tag":"runtime.launch","timestamp":1651256875766,"message":"Launch returned error","metadata":{"error":{"message":"Unable to attach to browser","stack":"Error: Unable to attach to browser\n    at h.target [as prepareLaunch] (c:\\program files\\microsoft visual studio\\2022\\professional\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:124:19)\n    at h.result (c:\\program files\\microsoft visual studio\\2022\\professional\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:168:15)\n    at t.Binder.captureLaunch (c:\\program files\\microsoft visual studio\\2022\\professional\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\binder.js:248:13)\n    at t.Binder._launch (c:\\program files\\microsoft visual studio\\2022\\professional\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\binder.js:224:9)\n    at async Promise.all (index 5)\n    at t.Binder.result [as _boot] (c:\\program files\\microsoft visual studio\\2022\\professional\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\binder.js:172:9)\n    at t.default._onMessage (c:\\program files\\microsoft visual studio\\2022\\professional\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\dap\\connection.js:145:27)"},"wasCancelled":false,"name":"h"},"level":2}`

**Comment by mkArtakMSFT** [comment] 2022-04-29 20:27
Thanks for contacting us, @Hastaroth1.
@thaystg can you please take a look at this? Thanks!

**Comment by thaystg** [comment] 2022-04-29 21:27
I think I need more information to help you. Can you please help me?

First thing to test that I have a different behavior when I tested locally:
- Open a chrome passing these parameters: "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222
- Then open any URL like: www.microsoft.com
- Then in another tab open http://localhost:9222/json
- Paste here the content of the json.

For me trying to view content of http://localhost:9222/json doesn't work anymore as it's disabled by chrome for security reasons.

My second question is can you paste the full content of: visualstudio-js-debugger.txt.

**Comment by Hastaroth1** [comment] 2022-04-29 21:59
Thank you for the very fast response.

Here is the full content of http://localhost:9222/json:

```json
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/CD8A6D3F7258E91BE133FED64B0054BD",
   "id": "CD8A6D3F7258E91BE133FED64B0054BD",
   "title": "New Tab",
   "type": "page",
   "url": "http://localhost:9222/json",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/CD8A6D3F7258E91BE133FED64B0054BD"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/5763436CF7381E8A8A19CFE2601472F9",
   "id": "5763436CF7381E8A8A19CFE2601472F9",
   "parentId": "CD8A6D3F7258E91BE133FED64B0054BD",
   "title": "chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=",
   "type": "iframe",
   "url": "chrome-untrusted://new-tab-page/one-google-bar?paramsencoded=",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/5763436CF7381E8A8A19CFE2601472F9"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/D0A51793D1CEEA13D243659C7F0711A9",
   "id": "D0A51793D1CEEA13D243659C7F0711A9",
   "parentId": "5763436CF7381E8A8A19CFE2601472F9",
   "title": "https://ogs.google.com/u/0/widget/app?origin=chrome-untrusted%3A%2F%2Fnew-tab-page&amp;origin=chrome%3A%2F%2Fnew-tab-page&amp;cn=app&amp;pid=1&amp;spid=243&amp;hl=en",
   "type": "iframe",
   "url": "https://ogs.google.com/u/0/widget/app?origin=chrome-untrusted%3A%2F%2Fnew-tab-page&origin=chrome%3A%2F%2Fnew-tab-page&cn=app&pid=1&spid=243&hl=en",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/D0A51793D1CEEA13D243659C7F0711A9"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/103DEB7223115B727C90F47CBFB925E6",
   "faviconUrl": "https://c.s-microsoft.com/favicon.ico?v2",
   "id": "103DEB7223115B727C90F47CBFB925E6",
   "title": "Microsoft – Nuage, ordinateurs, Applications et jeux",
   "type": "page",
   "url": "https://www.microsoft.com/fr-ca/",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/103DEB7223115B727C90F47CBFB925E6"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/F440302FC1485F93B2317B45C6D40685",
   "id": "F440302FC1485F93B2317B45C6D40685",
   "title": "Privacy Badger",
   "type": "background_page",
   "url": "chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/F440302FC1485F93B2317B45C6D40685"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/7292BDC81AC43392BF5FBBE13E47EDD5",
   "id": "7292BDC81AC43392BF5FBBE13E47EDD5",
   "title": "Square",
   "type": "background_page",
   "url": "chrome-extension://nadebckkcfbjaddfpcklodnmokipjlli/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/7292BDC81AC43392BF5FBBE13E47EDD5"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/92B2C67BAFA4A554BC73ADA379150CA5",
   "id": "92B2C67BAFA4A554BC73ADA379150CA5",
   "title": "uBlock Origin",
   "type": "background_page",
   "url": "chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/background.html",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/92B2C67BAFA4A554BC73ADA379150CA5"
} ]
```
Here is the full debugger file

[visualstudio-js-debugger.txt](https://github.com/dotnet/aspnetcore/files/8594985/visualstudio-js-debugger.txt)

**Comment by thaystg** [comment] 2022-04-29 22:06
If you go to this PATH: `C:\.nuget\packages\microsoft.aspnetcore.components.webassembly.devserver\6.0.2\Tools\BlazorDebugProxy\`
And execute: `dotnet BrowserDebugHost.dll`

Do you see something like this?
```
Content root path: T:\Users\Thays\.nuget\microsoft.aspnetcore.components.webassembly.devserver\6.0.4\tools\BlazorDebugProxy
Now listening on: http://127.0.0.1:55581
Application started. Press Ctrl+C to shut down.
```

**Comment by Hastaroth1** [comment] 2022-04-29 22:09
Yes I got more of less the same thing:

`
C:\.nuget\packages\microsoft.aspnetcore.components.webassembly.devserver\6.0.2\tools\BlazorDebugProxy>dotnet BrowserDebugHost.dll
Hosting environment: Production
Content root path: C:\.nuget\packages\microsoft.aspnetcore.components.webassembly.devserver\6.0.2\tools\BlazorDebugProxy
Now listening on: http://127.0.0.1:52856
Application started. Press Ctrl+C to shut down.
`

**Comment by thaystg** [comment] 2022-04-29 22:16
Okay, let's try step by step debug without using Visual Studio:

- Create a new project with dotnet new blazorwasm (as you have already done)
- dotnet run
- Open a chrome passing these parameters: "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222
- Then open the url that was printed in the console when you ran your BlazorApp
- Press Shift-Alt-D
- If you see an error paste here the error and also the console of the BlazorApp

**Comment by Hastaroth1** [comment] 2022-05-02 14:12
Hello,

The full output of the console is:
```cmd
C:\Users\wawaUser\Desktop\BlazorDebug>dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7216
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5124
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\wawaUser\Desktop\BlazorDebug
```

The tab opened with `Shift-Alt-D` shows

```text
Unable to find debuggable browser tab
Could not get a list of browser tabs from http://localhost:9222/json. Ensure your browser is running with debugging enabled.

Resolution
If you are using Google Chrome for your development, follow these instructions:
Press Win+R and enter the following:

chrome --remote-debugging-port=9222 --user-data-dir="C:\Users\wawaUser\AppData\Local\Temp\blazor-chrome-debug" https://localhost:7216/

If you are using Microsoft Edge (80+) for your development, follow these instructions:
Press Win+R and enter the following:

msedge --remote-debugging-port=9222 --user-data-dir="C:\Users\wawaUser\AppData\Local\Temp\blazor-edge-debug" --no-first-run https://localhost:7216/

This should launch a new browser window with debugging enabled..
Underlying exception:
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (cannotconnect).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.WebAssembly.Server.TargetPickerUi.GetOpenedBrowserTabs()
   at Microsoft.AspNetCore.Components.WebAssembly.Server.TargetPickerUi.Display(HttpContext context)
```

**Comment by thaystg** [comment] 2022-05-02 14:39
If you do the same test on edge you get the same error?:

**Comment by thaystg** [comment] 2022-05-02 14:44
Also if you try to open the http url and not the https? Same error?

**Comment by Hastaroth1** [comment] 2022-05-02 14:59
Yes I get the same error with Edge and Chrome in both https and http

**Comment by Hastaroth1** [comment] 2022-05-02 15:09
The output in the console is:

```

DevTools listening on ws://127.0.0.1:9222/devtools/browser/1dada8af-0edf-49de-b699-921eae166c8a
[54888:19588:0502/110715.312:ERROR:device_event_log_impl.cc(214)] [11:07:15.312] USB: usb_device_win.cc:67 Failed to open \\?\usb#root_hub30#4&2006862c&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8}: Access is denied. (0x5)
[54888:19588:0502/110715.325:ERROR:device_event_log_impl.cc(214)] [11:07:15.324] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.
```

**Comment by thaystg** [comment] 2022-05-02 15:11
After you open the WASM App and press Shift-Alt-D you don't see any new error on console?

**Comment by Hastaroth1** [comment] 2022-05-02 15:15
There are no new errors directly after opening that app.

After a while this gets logged but I don't think it's related:

```
[15736:60412:0502/111319.033:ERROR:util.cc(126)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
[42308:57308:0502/111419.275:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
```

**Comment by thaystg** [comment] 2022-05-02 15:28
Okay, one last try:
Can you try to run chrome with these parameters: --remote-debugging-port=9222 --disable-extensions --enable-logging 
And check if Shift-Alt-D works? Or you still see error 502?

**Comment by Hastaroth1** [comment] 2022-05-02 15:32
I still have the same 502 error page.

**Comment by thaystg** [comment] 2022-05-02 15:36
@mkArtakMSFT as we can see in the error description, this code, is returning HTTP Code 502.
https://github.com/dotnet/aspnetcore/blob/e059629e5e8ce395d24a9a4582772ce88be766dc/src/Components/WebAssembly/Server/src/TargetPickerUi.cs#L205

So it's not related with the debugger, it's before that, it's when AspNetCore is trying to do a http request to chrome and it's returning 502 bad gateway. 

I saw some things searching in the internet, but I'm not sure what could be the reason, maybe you can help him better then me.

Also @Hastaroth1 in the mean time if you want to try some of this: 
https://www.lifewire.com/502-bad-gateway-error-explained-2622939
https://www.keycdn.com/support/502-bad-gateway

**Comment by mkArtakMSFT** [comment] 2022-05-02 16:19
Thanks for investigation, @thaystg .
We'll take it over from here.

**Comment by mkArtakMSFT** [comment] 2022-06-22 17:02
@Hastaroth1 we think there is potentially some software which prevents the calls to localhost and result in Bad Gateway error that you're getting. If you believe this is something caused by the framework, we will need to have a complete repro project hosted as a public GitHub repo, as well as the exact steps that you've used to get it to repro.

**Comment by SteveSandersonMS** [comment] 2022-06-22 17:04
@Hastaroth1 I know this is really inconvenient, but since the repro steps don't work when we try it, we would need to have repro steps based on a completely fresh OS install. If you set up a new machine, for example as a VM, does it still repro? What extra software or configuration is needed in this VM to make it repro?

**Comment by jan-johansson-mr** [comment] 2022-07-03 05:42
@SteveSandersonMS, @mkArtakMSFT, @thaystg,

The debugging from VS2022 do not work, since upgrading to `7.0.0-preview.5.22303.8` of a brand new BlazorWasm project (clean slate project).

When I downgrade to `7.0.0-preview.4.22251.1`, the debugging works great! Updating to `7.0.0-preview.5.22303.8` causes the following output

> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: No output has been recevied from the application.
         at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
         at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

With the `Failed to launch debug adapter` message in the dialog after the debugger gives up.

Steps to reproduce:

`dotnet new blazorwasm -o BlazorApp1`

Use VS2022 in the created app and run debugger, and it fails.

Downgrade from version `7.0.0-preview.5.22303.8` to `7.0.0-preview.4.22251.1`, and run debugger, now it succeeds.

Thanks

**Comment by amr-twashing** [comment] 2023-10-03 20:22
I am having the issue as well. This started very suddenly on a new WAM project and showed up on an existing WAM project. The problem is seen on both Edge and Chrome.

**Comment by mkArtakMSFT** [comment] 2023-12-13 18:08
Can sombody confirm if this is still an issue with latest .NET 8 release? If we hear no further feedback / concerns here, we'll close this issue.

**Comment by xperiandri** [comment] 2023-12-14 12:25
It is.
It happens sometimes and persists until you rebuild the project and remove a browser profile in the browser setting

**Comment by xperiandri** [comment] 2023-12-19 23:37
Which input required?

**Comment by randolphscott99** [comment] 2023-12-27 21:20
I have occasionally been able to reproduce this issue.   

A fix for me was found on SO here ...   https://stackoverflow.com/questions/72037423/cannot-debug-blazor-wasm/72037574#72037574 .   

I'm unable to debug in https on localhost, but that's not really necessary with development.

**Comment by MackinnonBuck** [comment] 2024-01-10 17:47
We were unable to prioritize this issue because we have not received a reliable repro. Furthermore, this issue was reported as a .NET 6 issue and a lot has changed since then. If someone is able to come up with a reliable repro for a .NET 8 version of this bug, please submit a new issue. Thanks!

**Closed by MackinnonBuck** 2024-01-10 17:47 UTC
Labels: investigate, area-blazor, feature-blazor-wasm, feature-blazor-debugging, Pillar: Technical Debt

**Comment by kolyanet** [comment] 2025-01-17 05:18
To solve the issue of launching debugging through the browser in Visual Studio/Rider/Visual Studio Core on Windows 11, I checked the value of a parameter in the registry at:

`HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome`
The `RemoteDebuggingAllowed` parameter must be set to `1`

Here are the steps to open the registry editor and check/update this parameter:
1. Open the Run dialog by pressing `Win + R`.
2. Type `regedit` in the box and hit Enter to open the Registry Editor.
3. Navigate to the path:  
   `HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome`.
4. Look for the parameter named RemoteDebuggingAllowed.  
   - If it doesn't exist, create it:  
     - Right-click in the right panel, select `New -> DWORD (32-bit) Value`.  
     - Name it `RemoteDebuggingAllowed` and set its value to `1`.  
   - If it already exists, ensure its value is set to `1`.
