### ISSUE TITLE
Blazor WASM Client - Page Navigation with # anchor tags not working

### ISSUE THREAD

**Issue by ramkiranhota** [dotnet/aspnetcore#23522] opened 2020-06-30 17:48 UTC
When I have a page with # anchor href tags, the control is not navigating to that section instead it will navigate to home page.  Below is the example link.

` <a class="nav-link" href="#item-1">Item 1</a>`

**More Details:**
Github Sample Project - https://github.com/ramkiranhota/AnchorSample
Project type - Blazor WASM Client
Visual Studio Version - VS2019 v16.6.2

**About the sample application I created**
Anchor Sample Application to test the in page section navigation.

_Steps to reproduce:_

1. Click on AnchorTest link on the left menu
2. Once navigated to this page, click on any link like Item 1, observe that the app is navigating to home page
3. Ideally it should navigate to a section in the same "AnchorTest" page.
4. I'm using a sample from this page (Example with nested nav)- https://getbootstrap.com/docs/4.5/components/scrollspy/#how-it-works

**Comment by mkArtakMSFT** [comment] 2020-06-30 21:38
Thanks for contacting us. This is a dupe of #8393

**Closed by mkArtakMSFT** 2020-06-30 21:38 UTC
Labels: area-blazor

**Comment by ramkiranhota** [comment] 2020-07-03 04:19
Below is the fix - <a class="nav-link" href="testpage#item-1" target="_top">Item 1</a>
