### ISSUE TITLE
2FA sign in only returns locked out after n+1 failed attempts.

### ISSUE THREAD

**Issue by ovidiupop88** [dotnet/aspnetcore#26429] opened 2020-09-29 15:58 UTC
### Describe the bug
When using TwoFactorSignInAsync(), what should be the last failed sign in attempt does not return a LockedOut result.
Behavior is different when using SignInManager.TwoFactorSignInAsync() vs SignInManager.PasswordSignInAsync() - see code below.
 
### To Reproduce
Have LockoutOptions.MaxFailedAccessAttempts with a setting of **3(n)**.
Attempt to perform a TwoFactorSignIn **3(n)** times. SignInResult.Failed is returned.
SignInResult.LockedOut is returned after **4(n+1)** failed attempts.

### Code in SignInManager.TwoFactorSignInAsync()

```    // If the token is incorrect, record the failure which also may cause the user to be locked out
            await UserManager.AccessFailedAsync(user);
            return SignInResult.Failed;
```

### Code in SignInManager.CheckPasswordSignInAsync:()

```    if (UserManager.SupportsUserLockout && lockoutOnFailure)
            {
                // If lockout is requested, increment access failed count which might lock out the user
                await UserManager.AccessFailedAsync(user);
                if (await UserManager.IsLockedOutAsync(user))
                {
                    return await LockedOut(user);
                }
            }
            return SignInResult.Failed;
```

**Comment by blowdart** [comment] 2020-09-30 18:43
Dupe of https://github.com/dotnet/aspnetcore/issues/17184

Closing.

**Closed by blowdart** 2020-09-30 18:43 UTC
Labels: area-identity

**Comment by ovidiupop88** [comment] 2020-10-01 11:25
IMHO, Issue [#17184](https://github.com/dotnet/aspnetcore/issues/17184) is about recovery codes, and the discussion is whether it should Lock Out or not.  I've created this issue specifically for logging in with a 2FA code (not recovery code) which does result in a LockOut, but not immediatly after the user is locked out.

**Comment by jose-arias** [comment] 2020-10-03 03:57
I just found this same error, I'm trying to figure out what I have wrong but looks like it's a bug.
