### ISSUE TITLE
[Blazor] MSB4018 -  "ApplyCompressionNegotiation". - .Net 9.0.100-preview.7.24407.12

### ISSUE THREAD

**Issue by fabiohcnobre** [dotnet/aspnetcore#57487] opened 2024-08-22 00:43 UTC
### 
Error in Blazor 

## Version
.Net 9.0.100-preview.7.24407.12

### Description
Microsoft.NET.Sdk.WebAssembly.targets

Falha inesperada da tarefa "ApplyCompressionNegotiation".
System.InvalidOperationException: Endpoints not found for related asset: C:\Users\fabio\source\repos\metanetsistemas\MetaNetBI.Web\bin\Debug\net8.0\wwwroot\_framework\blazor.boot.json
   em Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
   em Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   em Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by halter73** [comment] 2024-08-23 17:38
@javiercn This looks static web asset related.

**Comment by javiercn** [comment] 2024-08-23 18:40
@fabiohcnobre are you using webassembly?

If that's the case, it likely is a dupe of https://github.com/dotnet/aspnetcore/issues/57423.

If that's not the case and you can provide a minimal repro project, that would help us with the investigation.

Trying with the nightly version will help us also know if this is something that has already been fixed. You can see instructions on how to do so on the linked issue.

**Comment by fabiohcnobre** [comment] 2024-08-23 18:53
Hello @javiercn 
Yes, it would be a copy. I apologize, I hadn't identified the problem when I opened mine.

The problems that gave an error are from webassembly.

I checked and will follow up on the other issue.
Thanks again.

Att

**Comment by javiercn** [comment] 2024-08-23 20:10
@fabiohcnobre no worries.

We prefer people open different issues with their specific scenarios and we can take care of duping them.

**Closed by javiercn** 2024-08-23 20:10 UTC
Labels: area-blazor, Needs: Attention :wave:
