### ISSUE TITLE
JsonSerializerContext not called for some api endpoints

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#39628] opened 2022-01-19 12:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

JSON encoding depends on the return type used in the API definition:

Return value of JsonResult: {"Whatever":0}
Return value of Model: {"whatever":0}

Documentation clearly states that using AddContext is sufficient to get it working, but it seems not.

### Expected Behavior

Return value of JsonResult: {"Whatever":0}
Return value of Model: {"Whatever":0}

### Steps To Reproduce

```
[Route("api/[controller]/[action]")]
[ApiController]
[AllowAnonymous]
public class SomethingController : ControllerBase {
   [HttpGet]   public IActionResult JsonResult() => new JsonResult(new Status());
   [HttpGet]   public Status Model() => new Status());
}

public class Status{
public int Whatever {get;set;}
}

[JsonSerializable(typeof(Status))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified)]
internal partial class StatusSerializer: JsonSerializerContext { }

...
in program.cs

services.AddMvc()
        .AddJsonOptions(o => o.JsonSerializerOptions.AddContext<StatusSerializer>());

```

### .NET Version

6.0.100

**Comment by pranavkm** [comment] 2022-01-19 14:14
Sounds like a dupe of https://github.com/dotnet/aspnetcore/issues/38720. We can continue discussing it in the other issue.

**Closed by pranavkm** 2022-01-19 14:14 UTC
