### ISSUE TITLE
ModelBinder adds parameter name as prefix for key matching, if any one of the model's property name is same as parameter name

### ISSUE THREAD

**Issue by MohanVijayakumar** [dotnet/aspnetcore#23953] opened 2020-07-15 12:53 UTC
### Describe the bug
When the request made with form data 
ModelBinder is not binding the form data keys with model ,if any one of the model's property name is same as action's parameter name

### To Reproduce

**Dto**
```
public class ProfileDto
{
    public int ID {get;set;}
    public Name {get;set;}
}
```
**Model**

```
public class ProfileInputModel
{
    public ProfileDto Profile {get;set;}
    public int SomeNumber {get;set;}
}
```
**Controller action**

```
public IActionResult Create([FromForm]ProfileInputModel profile)
{
    return Ok();
}
```
**Form Data Keys**

```
Profile.ID = 1
Profile.Name = "Test"
SomeNumber = 1
```

When the request made "Create" action with above form data keys, the parameter becomes null
but if i change the parameter name other than "profile" then the model binder binds the form data properly.
it seems model binder adds the prefix as parameter name to match the keys in request, if any one of the model's property name is same as action's parameter name

### Further technical details
- ASP.NET Core version - 3.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - VS Code 1.47.1

**Comment by mkArtakMSFT** [comment] 2020-07-15 16:22
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

**Closed by mkArtakMSFT** 2020-07-15 16:22 UTC
Labels: area-mvc, feature-Model-Binding
