### ISSUE TITLE
Flaky test: IncrementallyUpdatesCache

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#22922] opened 2020-06-13 20:28 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=685006&view=results

```
Assert.Collection() Failure\r\nCollection: []\r\nExpected item count: 1\r\nActual item count: 0
at Microsoft.AspNetCore.Components.E2ETest.Tests.BootResourceCachingTest.IncrementallyUpdatesCache() in /_/src/Components/test/E2ETest/Tests/BootResourceCachingTest.cs:line 96
```

**Comment by SteveSandersonMS** [comment] 2020-10-22 15:07
Duplicate of https://github.com/dotnet/aspnetcore/issues/20154

**Closed by SteveSandersonMS** 2020-10-22 15:07 UTC
Labels: Working, area-blazor, investigate, task, test-failure
