### ISSUE TITLE
Will calling HttpResponse.WriteAsync() cause HttpResponse.HasStarted to be set to true

### ISSUE THREAD

**Issue by orange-puff** [dotnet/aspnetcore#45719] opened 2022-12-21 23:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am observing the following behavior when running my webapp in using dotnet core 3.1

```
var b = response.HasStarted // b is false
response.WriteAsync("hello").Wait();
b = response.HasStarted // b is true
```
where `response` is of type `Microsoft.AspNetCore.Http.HttpResponse`

Is this the intended behavior? Is this how .Net Framework worked?

According to
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?view=aspnetcore-7.0
"A response is started by flushing the response body or calling HttpResponse.StartAsync"

Yet if I step through the code it looks like I am doing neither.

### Expected Behavior

`response.WriteAsync` does not cause `response.HasStarted` to be true

### .NET Version

dotnet core 3.1

**Comment by Tratcher** [comment] 2022-12-22 00:23
Yes this is the intended behavior. AspNetCore does not buffer responses by default, (.NET Framework did in some cases). If you don't want this behavior you need to buffer the response generation.

**Comment by orange-puff** [comment] 2022-12-22 00:40
Thank you for the response. Can you link to any documentation related to this as well as how to buffer the response?

**Comment by davidfowl** [comment] 2022-12-22 01:16
Do our system web adapters do anything here @Tratcher?

**Comment by orange-puff** [comment] 2022-12-22 01:23
Some more context; We create a wrapper around the `HttpContext` (`System.Web` or `Microsoft.AspNetCore.Http` object that will implement different behavior if the runtime is .net framework or .net core. In many places, we follow the pattern of writing the body of the response and then in a finally block setting headers for the response. This works fine on asp.net where the response appears to be buffered by [default](https://learn.microsoft.com/en-us/dotnet/api/system.web.httpresponse.bufferoutput?view=netframework-4.8#property-value), but this does not work on asp.net core where the response is flushed when `WriteAsync` is called, and the headers become immutable. 
Any guidance on how to proceed would be greatly appreciated. 

The two options appear to be
1. Do response buffering on our asp.net core app
2. refactor the code to set headers before the body of the response is written

**Comment by davidfowl** [comment] 2022-12-22 01:26
2. Would be better (since it would just work in both cases). There's also a 3, which is register the HttpResponse.OnStarting event and write headers in there. I don't know what your code looks like. Response buffering is tricky because of the potential performance problems.

**Comment by orange-puff** [comment] 2022-12-22 01:29
Given the structure of our code `HttpResponse.OnStarting` might end up being really ugly and more work than 2. So I'll go with that. Thank you very much for the response. I think this issue can be closed now

**Comment by Tratcher** [comment] 2022-12-22 01:42
@orange-puff take a look at https://github.com/dotnet/systemweb-adapters

**Comment by davidfowl** [comment] 2022-12-22 02:02
@Tratcher it's worth updating this document https://learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?view=aspnetcore-7.0#httpresponse to add a section on buffering.

**Comment by adityamandaleeka** [comment] 2023-01-09 23:28
Triage: update doc to mention why we don't recommend response buffering, and perhaps a simple example of inserting a MemoryStream to accomplish buffering.

**Comment by adityamandaleeka** [comment] 2023-12-07 01:30
Addressed in https://github.com/dotnet/AspNetCore.Docs/pull/30919

**Closed by adityamandaleeka** 2023-12-07 01:30 UTC
Labels: Docs, area-networking, net8_docathon
