### ISSUE TITLE
HttpContext.User is not set in production unless using https

### ISSUE THREAD

**Issue by scottjreece** [dotnet/aspnetcore#28481] opened 2020-12-07 18:11 UTC
### Describe the bug
Using dotnet core 3.1 a user logs in. On subsequent requests, the aspnet cookie is sent, and the session variables work, but HttpContext.User is always null if the following are true:
- production build (using dotnet publish)
- using http instead of https

### Expected behavior:
- The User should not be null, or at least there should be a way to override this behavior.
- There should be a meaningful error message written to the console warning the user of why the User isn't being set

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
# dotnet --version
3.1.404
# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
#
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
This is built and run in a docker container, but I'm using VS.Net 2019 on a Windows 10 machine. The dotnet --info is from the docker container.

**Comment by davidfowl** [comment] 2020-12-08 20:19
Can you provide a project that reproduces the issue?

**Comment by Tratcher** [comment] 2020-12-09 01:57
And a Fiddler network trace of the repro. Most likely the cookies are being marked as `secure`.

As a rule, auth should always take place over https.

**Comment by WeihanLi** [comment] 2020-12-09 07:37
Deployed more than one instance? Maybe data-protection problem

**Comment by scottjreece** [comment] 2020-12-09 17:14
I can't upload the project in question, so I'm working on building a minimal project that demonstrates the issue. I'll see if I can get that Fiddler trace too. In production there will be an Apache reverse proxy providing https to the client, but the application itself is not currently using https behind the reverse proxy for the sake of simplicity.

**Comment by Tratcher** [comment] 2020-12-09 17:17
Make sure you follow the proxy guidelines here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0

**Comment by javiercn** [comment] 2020-12-11 17:26
@scottjreece thanks for contacting us.

We believe this issue is caused by the fact that the cookie is marked as "secure" by default, so you can't use it over HTTP unless you change that (which we **REALLY, REALLY, REALLY** discourage.

**Closed** 2020-12-11 17:26 UTC
Labels: :heavy_check_mark: Resolution: By Design, Status: Resolved, area-identity

**Comment by scottjreece** [comment] 2020-12-15 15:05
Note for those who have similar issues in the future: the only way I could get it to work was to ditch the Apache reverse proxy and use Kestrel on the edge providing HTTPS directly without a reverse proxy. I used LettuceEncrypt for the TLS cert and it worked perfectly the first time.
