### ISSUE TITLE
CORS with SignalR (.NET 7.0.12) does not work in Blazor WebAssembly App

### ISSUE THREAD

**Issue by pilotshamn** [dotnet/aspnetcore#51433] opened 2023-10-17 08:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

CORS with SignalR (.NET 7.0.12) does not work in Blazor WebAssembly App (APS.NET Core Hosted) but works in Blazor Server App.
Both are run in IIS and on Chrome

### Expected Behavior

Expected to work in both situations

### Steps To Reproduce

The definition to use CORS are the same and the Razor page is the same.
Razor code:
 ``` 
@using Microsoft.AspNetCore.SignalR.Client;
@using TestBlazorServerApp.Data
@inject WeatherForecastService ForecastService

<PageTitle>Weather forecast</PageTitle>

<h1>Weather forecast</h1>

<p>This component demonstrates fetching data from a service.</p>

@if (forecasts == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Temp. (C)</th>
                <th>Temp. (F)</th>
                <th>Summary</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var forecast in forecasts)
            {
                <tr>
                    <td>@forecast.Date.ToShortDateString()</td>
                    <td>@forecast.TemperatureC</td>
                    <td>@forecast.TemperatureF</td>
                    <td>@forecast.Summary</td>
                </tr>
            }
        </tbody>
    </table>
}

@code {
    private WeatherForecast[]? forecasts;
    const string SigRServerURI = "http://xxxxx.se:5590/yyyyyyy";
    protected override async Task OnInitializedAsync()
    {
        forecasts = await ForecastService.GetForecastAsync(DateOnly.FromDateTime(DateTime.Now));
       var  signalrConnection = new HubConnectionBuilder().WithUrl(SigRServerURI)
               .WithAutomaticReconnect(new[] { TimeSpan.Zero, TimeSpan.Zero, TimeSpan.FromSeconds(10), TimeSpan.FromSeconds(30), TimeSpan.FromMinutes(2),
                        TimeSpan.FromMinutes(10), TimeSpan.FromMinutes(30), TimeSpan.FromHours(1), TimeSpan.FromHours(5), TimeSpan.FromHours(10), TimeSpan.FromHours(24) })
             .ConfigureLogging(logging =>
             {
  
                 logging.AddDebug();
                 logging.SetMinimumLevel(LogLevel.Trace);
             })
            .Build(); //logging.AddConsole();
        await signalrConnection.StartAsync();
        //Debug.Assert(signalrConnection.State == HubConnectionState.Connected);
        Console.WriteLine(DateTime.Now.ToString("dddd, dd MMMM yyyy HH:mm:ss") + " ConnectWithRetryAsync:" + SigRServerURI);
    }
}
 ``` 
The Program.cs in Server App: This works
 ``` 
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddSingleton<WeatherForecastService>();
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(
        builder =>
        {
            builder.WithOrigins(http://xxxxx.se:5590/yyyyyyy")

        .AllowAnyHeader()
        .WithMethods("GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD", "PATCH")
        .AllowCredentials();
        });
});
var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
}
app.UseStaticFiles();
app.UseRouting();
app.UseCors();
app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();

 ``` 
The Program.cs in Core Hosted Blazor WebAssembly App: This does not work se exeption
 ```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(
        builder =>
        {
            builder.WithOrigins(http://xxxxx.se:5590/yyyyyyy")
       .AllowAnyHeader()
        .WithMethods("GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD", "PATCH")
        .AllowCredentials();
        });
});

builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();


var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
    app.UseWebAssemblyDebugging();
}
else
{
    app.UseExceptionHandler("/Error");
}

app.UseBlazorFrameworkFiles();
app.UseStaticFiles();

app.UseRouting();

app.UseCors();
//app.UseCors(MyAllowSpecificOrigins);
app.UseAuthorization();

app.MapRazorPages();
app.MapControllers();
app.MapFallbackToFile("index.html");

app.Run();
 ```
Exeption:
 Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch

### Exceptions (if any)

 Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> TypeError: Failed to fetch
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|55_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at HostedWasmBlazor.Client.Pages.FetchData.OnInitializedAsync() in C:\ProjectSKIA\HostedWasmBlazor\HostedWasmBlazor\Client\Pages\FetchData.razor:line 58
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### .NET Version

.NET SDK:  Version:   7.0.402  Commit:    791db8e2d8

**Comment by pilotshamn** [comment] 2023-10-17 08:37
In Chrome Console ( Blazor Server App) I get:
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Starting HttpConnection.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Establishing connection with server at 'http://liveais.se:5590/RadarHub'.
Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler: Trace: Sending HTTP request POST 'http://xxxxx.se:5590/yyyyyyy/negotiate?negotiateVersion=1'.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Established connection 'OuzqoeWf-e4YJLxH6fmc_Q' with the server.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Starting transport 'WebSockets' with Url: http://liveais.se:5590/RadarHub.
Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport: Information: Starting transport. Transfer mode: Text. Url: 'ws://liveais.se:5590/RadarHub?id=5G55yaExbrMucDtyZwrv1g'.



In Chrome Console ( Blazor WebAssembly App) I get:
Why do I not get the same error in Blazor Server App what am I missing.

Access to fetch at 'http://xxxxx.se:5590/yyyyyyy/negotiate?negotiateVersion=1' from origin 'http://localhost:20200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

POST http://xxxxx.se:5590/yyyyyyy/negotiate?negotiateVersion=1 net::ERR_FAILED

<html>
<body>


(anonymous) | @ | dotnet.7.0.12.hz63z85m2w.js:5
-- | -- | --
  | _t | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | ia | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | _bound_js_INTERNAL_http_wasm_fetch | @ | _bound_js_INTERNAL_http_wasm_fetch:13
  | Ss | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | _mono_wasm_invoke_bound_function | @ | dotnet.7.0.12.hz63z85m2w.js:7672
  | $do_icall | @ | 0553fbee:0x610601
  | $do_icall_wrapper | @ | 0553fbee:0x60f5b2
  | $interp_exec_method | @ | 0553fbee:0x5ffc2e
  | $interp_runtime_invoke | @ | 0553fbee:0x5fea13
  | $mono_jit_runtime_invoke | @ | 0553fbee:0x7f7ea3
  | $do_runtime_invoke | @ | 0553fbee:0x696c1f
  | $mono_runtime_try_invoke | @ | 0553fbee:0x6973b2
  | $mono_runtime_invoke | @ | 0553fbee:0x699677
  | $mono_wasm_invoke_method_bound | @ | 0553fbee:0x86088b
  | Module._mono_wasm_invoke_method_bound | @ | dotnet.7.0.12.hz63z85m2w.js:8659
  | Ws | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | b.javaScriptExports.complete_task | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | (anonymous) | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | Promise.then (async) |   |  
  | Kr | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | _bound_js_INTERNAL_http_wasm_get_response_length | @ | _bound_js_INTERNAL_h…t_response_length:8
  | Ss | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | _mono_wasm_invoke_bound_function | @ | dotnet.7.0.12.hz63z85m2w.js:7672
  | $do_icall | @ | 0553fbee:0x610601
  | $do_icall_wrapper | @ | 0553fbee:0x60f5b2
  | $interp_exec_method | @ | 0553fbee:0x5ffc2e
  | $interp_runtime_invoke | @ | 0553fbee:0x5fea13
  | $mono_jit_runtime_invoke | @ | 0553fbee:0x7f7ea3
  | $do_runtime_invoke | @ | 0553fbee:0x696c1f
  | $mono_runtime_try_invoke | @ | 0553fbee:0x6973b2
  | $mono_runtime_invoke | @ | 0553fbee:0x699677
  | $mono_wasm_invoke_method_bound | @ | 0553fbee:0x86088b
  | Module._mono_wasm_invoke_method_bound | @ | dotnet.7.0.12.hz63z85m2w.js:8659
  | Ws | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | b.javaScriptExports.complete_task | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | (anonymous) | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | Promise.then (async) |   |  
  | Kr | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | _bound_js_INTERNAL_http_wasm_fetch | @ | _bound_js_INTERNAL_http_wasm_fetch:14
  | Ss | @ | dotnet.7.0.12.hz63z85m2w.js:5
  | _mono_wasm_invoke_bound_function | @ | dotnet.7.0.12.hz63z85m2w.js:7672
  | $do_icall | @ | 0553fbee:0x610601
  | $do_icall_wrapper | @ | 0553fbee:0x60f5b2
  | $interp_exec_method | @ | 0553fbee:0x5ffc2e
  | $interp_runtime_invoke | @ | 0553fbee:0x5fea13
  | $mono_jit_runtime_invoke | @ | 0553fbee:0x7f7ea3
  | $do_runtime_invoke | @ | 0553fbee:0x696c1f
  | $mono_runtime_invoke_checked | @ | 0553fbee:0x696ba7
  | $mono_runtime_try_invoke_span | @ | 0553fbee:0x69b7ac
  | $mono_runtime_invoke_span_checked | @ | 0553fbee:0x69ba19
  | $ves_icall_InternalInvoke | @ | 0553fbee:0x66ae0e
  | $ves_icall_InternalInvoke_raw | @ | 0553fbee:0x67240e
  | $do_icall | @ | 0553fbee:0x6106a6
  | $do_icall_wrapper | @ | 0553fbee:0x60f5b2
  | $interp_exec_method | @ | 0553fbee:0x5ffc2e
  | $interp_runtime_invoke | @ | 0553fbee:0x5fea13
  | $mono_jit_runtime_invoke | @ | 0553fbee:0x7f7ea3
  | $do_runtime_invoke | @ | 0553fbee:0x696c1f
  | $mono_runtime_try_invoke | @ | 0553fbee:0x6973b2
  | $mono_runtime_invoke | @ | 0553fbee:0x699677
  | $mono_wasm_invoke_method_ref | @ | 0553fbee:0x860782
  | Module._mono_wasm_invoke_method_ref | @ | dotnet.7.0.12.hz63z85m2w.js:8654
  | _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet | @ | _Microsoft_AspNetCor…eginInvokeDotNet:29
  | beginInvokeDotNetFromJS | @ | blazor.webassembly.js:1
  | b | @ | blazor.webassembly.js:1
  | e.invokeMethodAsync | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | ke | @ | blazor.webassembly.js:1
  | Ie | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | onGlobalEvent


</body>
</html>

**Comment by javiercn** [comment] 2023-10-17 13:40
@pilotshamn thanks for contacting us.

Dupe of https://github.com/dotnet/aspnetcore/issues/22767#issuecomment-642117636.

HttpClient on webassembly is constrained by the browser sandbox, as opposed to HttpClient running on server. You need to setup the cors options accordinly.

**Closed by javiercn** 2023-10-17 13:40 UTC
Labels: area-blazor
