### ISSUE TITLE
.NET 8 migration from WASM to Blazor Web App - environment not set correctly

### ISSUE THREAD

**Issue by Stra1ghter** [dotnet/aspnetcore#53832] opened 2024-02-06 10:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have followed the [migration guide](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#convert-a-hosted-blazor-webassembly-app-into-a-blazor-web-app) from Blazor WebAssembly to Blazor Web App. After migrating, `IWebAssemblyHostEnvironment` always returned that I'm running the Production environment.

From what I have tested, I can see that < .NET 8 the response to `blazor.boot.json` always returned a `Blazor-Environment` header. With the changes described in the migration guide, this is no longer the case and the client cannot determine its environment.

I propose:
- to include a hint regarding this in the migration guide.
- to add a middleware that sets this header again.

My team is totally dissatisfied with the options in the [Blazor environment docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-8.0). Because they have big disadvantages:
- setting in startup environment doesn't work as described in the docs with the changed `App.razor` in the Server project. (It now hase a Routes component on the server and there is no script tag as in the code example.) Additionally, it is just a heuristic based on the URL instead of a correct way of setting the environment.
- setting the environment header via `web.config` is not dynamic.

### Expected Behavior

`IWebAssemblyHostEnvironment` should return the correct environment after following the migration guide.

### Steps To Reproduce

Create a Blazor WebAssembly app that uses `IWebAssemblyHostEnvironment` on the client and follow the migration guide to a Blazor Web App.

### .NET Version

8

**Comment by Stra1ghter** [comment] 2024-02-06 10:18
Setting the environment after `src="_framework/blazor.web.js" ` works, but I would highly emphasize to improve the documentation there.

As discussed above it's also a heuristic and no real solution for our team.

**Comment by javiercn** [comment] 2024-02-06 15:08
![image](https://github.com/dotnet/aspnetcore/assets/6995051/61a936d3-b4b6-46ce-9967-2914589e651c)

![image](https://github.com/dotnet/aspnetcore/assets/6995051/adc36676-17f2-4aff-9c34-d5275e184988)

![image](https://github.com/dotnet/aspnetcore/assets/6995051/f8c8ac12-bf36-4951-ae56-ce200c7b4bbf)

Just fired up a new version of the template and this seems to work correctly, can you provide a minimal repro project?

**Comment by guardrex** [comment] 2024-02-06 18:09
BTW @Stra1ghter ... The *Environments* article was revised for 8.0. Take a look at the guidance there ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-8.0

... especially this section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-8.0#read-the-environment-client-side-in-a-blazor-web-app

I've opened an issue to add a cross-link that article in that section of the migration article.

**Comment by Stra1ghter** [comment] 2024-02-12 09:02
Sorry for the delay.

@javiercn  [Here](https://github.com/Stra1ghter/blazor-migration-sample/tree/main) is a minimal repo. The main branch is the .NET 6 WASM template that is correctly displaying the Hosting environment client-side. In the update-branch I followed your migration guide and the environment is always displayed as "Production".

As stated in the issue:
Some middleware of the .NET 6 template (guess `UseBlazorFrameworkFiles`) provides the `Blazor-Environment` as a header to `blazor.boot.json`. This is removed during migration to a Blazor Web App. Hence, the `IWebAssemblyHostEnvironment ` defaults to `Production`.

Before migration:
![image](https://github.com/dotnet/aspnetcore/assets/32710436/ddf88458-df83-41b4-97a1-33df9e16a791)
 After migration:
![image](https://github.com/dotnet/aspnetcore/assets/32710436/539f6fc9-1e97-4e0f-9121-94c244c6d93a)

**Comment by Stra1ghter** [comment] 2024-02-12 09:10
@guardrex Sorry for the delay.
I have read the blazor environment doc, I have even linked the article in my report above!
However
1. Even if your specific section reads "Read the environment client-side in a Blazor Web App", it creates a server-side component. At least from my "newbie" .NET 8 Blazor knowledge that was not usable in the client project itself. And prerendering etc. is not discussed in the migration guide itself.

2. The other means discussed in the article such as [this](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-8.0#set-the-client-side-environment-via-startup-configuration) is a heuristic and no real solution (setting the environment via URL). I don't like this approach at all, URLs can change.  
  I also want to note that I find the src `{BLAZOR SCRIPT}` in that example rather confusing. Why not name it specifically `_framework/blazor.web.js`  as discussed in the migration guide?

**Comment by guardrex** [comment] 2024-02-12 11:22
> it creates a server-side component

That section explains how to inject `IWebAssemblyHostEnvironment` into interactive WASM or Auto components, which can cause failures in those components when the service doesn't exist on the server during prerendering or before the Blazor bundle downloads. I think where you stated "it" in your last remark you were referring to your sample app (and interactive Server components), but I didn't think that your opening post clarified what type of components you were having trouble with. Of course, that section won't help if you discovered a real 🪲 or if we're lacking some piece of important information in the guidance. I'm 👂 here for what the investigation uncovers.

> it is just a heuristic based on the URL

That's just an example for a very specific scenario, which is called out in the heading, ***via startup configuration***.

... and this isn't the primary article for setting the environment in a BWA. As the guidance in the opening remarks indicates ...

> For general guidance on setting the environment for a Blazor Web App, see [Use multiple environments in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-8.0).

I'll highlight that line, possibly in its own new section, because BWA render mode coverage in the introduction that was added for 8.0's release now crowds out that critical point and makes it seem less important. You set the environment for a BWA using the same approaches as you would for any ASP.NET Core app. Again, that might not have any bearing on the issue here, but I'll update the article to make that clearer.

> src {BLAZOR SCRIPT} in that example rather confusing. Why not name it specifically _framework/blazor.web.js as discussed in the migration guide?

That migration guide section is specific for a particular type of Blazor app migration scenario ... hosted WASM to BWA. Other places in reference docs must cater to additional types of Blazor apps that don't use the same script or have the same script location, so a placeholder is used with a cross-link to a section that indicates the script name is and where the script is found. Although the reference docs can version the exact names and locations into place, we have a weak documentation versioning system given the amount of churn in the framework, and this approach of calling out the script name and location in a separate section with links to it from around the reference docs is a compromise to make the docs manageable to maintain.

**Comment by guardrex** [comment] 2024-02-12 12:03
BTW @Stra1ghter .... It looks like your app isn't fully migrated ... you must follow **Step 1** ...

> Follow the guidance in the first three sections of this article:

... and update the target framework and package reference versions.

**Comment by Stra1ghter** [comment] 2024-02-13 07:52
@guardrex I understand your points, especially the `{BLAZOR SCRIPT}` point.

The `IWebAssemblyHostEnvironment` injecting does work for the new template using interactive server and client components, but not after following the migration guide. (There the service does already exist, but defaults to production as outlined above.)

> .... It looks like your app isn't fully migrated ... you must follow Step 1 ...

What are you referring to?

**Comment by guardrex** [comment] 2024-02-13 11:56
> There the service does already exist

The service won't be available in the server app after full migration.

Step 1 is to update the target framework and the package references. Your repro app is on 6.x, so those need to be updated to 8.x. For example in the server project ...

```diff
<TargetFramework>net6.0</TargetFramework>
<TargetFramework>net8.0</TargetFramework>
```

... and ...

```diff
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="6.0.26" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.1" />
```

Same thing for the `.Client` project.

BTW ... You're probably are already aware of the roll-forward behavior for minor and patch versions, but the latest template uses `8.0.1`, so I showed that instead of `8.0.0`, which will work, too.

I just discovered a pair of steps to add to the migration doc. There are two MS Build props to add to the `.Client` project ...

```xml
<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
```

There's a final item to address with your repro app that I don't think is causing a problem: Remove the `Microsoft.AspNetCore.Components.WebAssembly.DevServer` package reference from the `.Client` project. I don't think that's causing a problem here, but it really shouldn't be there.

I'll get a PR in now to address these additional steps and ping you on it.

**Comment by Stra1ghter** [comment] 2024-02-13 12:52
@guardrex I don't think you've read my comment.
> The main branch is the .NET 6 WASM template that is correctly displaying the Hosting environment client-side. In the update-branch I followed your migration guide and the environment is always displayed as "Production".

The update branch is and has been updated 1:1 according to your migration guide as far as I can tell.

**Comment by guardrex** [comment] 2024-02-13 12:56
Oh ... sorry about that. I have like ... ***1,000 things*** going on here 😩 at the moment ... I'm working down a large backload of issues. I (obviously) merely clicked your repro link without giving it a second thought.

Anyway ... it's good that we had the discussion thus far. Although the problem isn't fixed yet, we did update the migration steps with important content.

I'll take a look at ***the correct repro solution*** 🙈 in a minute after I deal with another 🔥 in docs 🚒🚓🚑.

**Comment by Stra1ghter** [comment] 2024-02-13 13:19
No worries.

I think it really comes down to the `Blazor-Environment` header for `blazor.boot.json`. That has worked wonderfully before, like a "battiers-included" approach and is just lacking a similar alternative (e.g. a middleware) when migrating to a BWA.

**Comment by Stra1ghter** [comment] 2024-02-26 12:32
@guardrex I have identified another missing piece in the migration guide. One has to adjust the link-href for the isolated css from `{App}.Client.styles.css` to `{App}.Server.styles.css`.

**Comment by Stra1ghter** [comment] 2024-04-15 11:04
@guardrex are there any news regarding the environment setup for Blazor with the upgraded .NET 8 setups?

**Comment by guardrex** [comment] 2024-04-15 11:34
This issue is marked for investigation/resolution at Preview 7 of 9.0, which I think will be the August preview release.

The guidance that we're still maintaining without additional updates at this time (they may tell me to change it later) is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-8.0#read-the-environment-client-side-in-a-blazor-web-app

... and the whole article is referenced in the *Migration Guide* here ...

https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#update-service-and-endpoint-option-configuration

Until I receive further information, that's all I'll have on it in the docs at the moment. I'm 👂 here for further developments.

**Comment by philippedurocher** [comment] 2024-04-25 18:42
Here's the translation:

---

I have exactly the same problem! I upgraded from 7.x to 8.x, followed the upgrade guide, implemented the ServerHostEnvironment class as explained in the guide, but I still have 'Production' as the environment name.

What I did to work around it, I consider it a hack and I don't really like it: I added 'Environment' as a key in the client's appsettings.json and implemented ServerHostEnvironment in the client, with an adjustment to read the value of the key in the client's appsettings.json. Then, I change the value at deployment time with the pipeline.

I think this is a major oversight on Microsoft's part. The fact that the WASM client no longer has an environment, or that it depends on an undocumented appsettings key, is very frustrating and I am really annoyed that we're aiming for a fix in dotnet 9. Why not fix this in version 8? It's clearly a regression!

Or at the very least, document a valid workaround please!

**Comment by MackinnonBuck** [comment] 2024-10-23 21:57
In the repro project, removing the call to `UseRouting()` seems to have fixed the problem.

Maybe we should suggest doing so in the upgrade guidance? I've seen other issues in this repo that are caused by explicitly calling `UseRouting()` ([example](https://github.com/dotnet/aspnetcore/issues/52339), possibly related root cause).

**Comment by guardrex** [comment] 2024-10-23 23:33
I'll get on that update tomorrow (Thursday).

**Comment by MackinnonBuck** [comment] 2024-10-31 22:54
Closing since the docs change has been made.

Also opened https://github.com/dotnet/aspnetcore/issues/58733 to track investigating the root cause of the problem and fixing it if necessary.

**Closed by MackinnonBuck** 2024-10-31 22:54 UTC
Labels: Docs, area-blazor, migration
