### ISSUE TITLE
HTTP/3: Investigate flakey interop tests

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#35699] opened 2021-08-25 09:19 UTC
The HTTP/3 in-memory tests are all solid.

The HTTP/3 interop tests and QUIC tests use System.Net.Quic. System.Net.Quic has some reliability issues. These tests were quarantined to ensure they don't impact other devs.

We need to keep an eye on these quarantined tests, and investigate any that are flakey. If flakey issues are caused by System.Net.Quic then we need to report problems to that team. If they are caused by Kestrel then we need to fix them.

**Comment by adityamandaleeka** [comment] 2021-09-13 22:08
Revisit this around 10/11 once we have history in the quarantined runs.

**Comment by adityamandaleeka** [comment] 2021-09-30 22:40
Closing as duplicate of #35070

**Closed by adityamandaleeka** 2021-09-30 22:40 UTC
Labels: test-failure, area-runtime, HTTP3
