### ISSUE TITLE
Move back to NPM

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#37398] opened 2021-10-08 15:07 UTC
Nodejs 16 ships with NPM 7 which solves a lot of the issues with previous versions of NPM (speed, reliability, shared dependencies) and offers a way for us to manage our shared dependencies centrally. We agreed on DoI to give this a try and report back.

**Comment by dougbu** [comment] 2022-02-28 22:55
What's the implication of that loss @BrennanConroy❔

More generally, @javiercn and @BrennanConroy is this something the Blazor or SignalR teams should own and fix❔ Would rather not leave unassigned `area-infrastructure` issues around, especially if they're not visible in one of our projects.

**Comment by javiercn** [comment] 2022-03-01 11:43
@BrennanConroy NPM now also has resolutions FYI.

@dougbu sure, lets come up with some way to hide them from your projects.

**Comment by dougbu** [comment] 2022-03-01 18:22
> @dougbu sure, lets come up with some way to hide them from your projects.

@javiercn @wtgodbe and I don't triage assigned issues or those on the DoI project board. Putting this on someone's plate or that project board would help 😸

**Comment by dougbu** [comment] 2022-04-25 23:25
@mkArtakMSFT @rafikiassumani-msft who should this be assigned to❔

**Comment by wtgodbe** [comment] 2022-06-06 23:23
Any update on this @mkArtakMSFT @rafikiassumani-msft?

**Comment by wtgodbe** [comment] 2022-08-04 23:18
@javiercn assigning this one to you as you said you'd be starting on this.

**Comment by javiercn** [comment] 2023-01-19 20:14
We have been wanting to move back to npm for a while for several reasons:
* Comes built-in with NPM.
* Centralized dependency versions.
* We can get rid of npmproj and companion SDK.
* Makes our life easier with source build.

I took a stab at it today during my build ops rotation and actually managed to make some significant progress.

You can run npm install at the root of the repo and it'll restore all the projects.
You can run npm run build --workspaces --if-present and it will run the `build script` for those apps that have it.

Over the course of doing this I took several shortcuts:
* Removed the @microsoft/dotnet-js-interop package.
  * We are the only ones that consume it and we do not push it to npm.
* Changed packages to use npx instead of invoking the script from node_modules.
* Had to adjust some paths in other tools too.
* I had to disable the .npmrc because it did not allowed me to restore locally.
* Some other things in the build output have changed paths and I have adjust them to continue going.
  * We should ideally produce the same output or have a good understanding 
* I disabled the signalr functional tests because I could not get them to work.

You can see the changes in this branch:
https://github.com/dotnet/aspnetcore/tree/javiercn/move-to-npm

Stuff that I have not done:
* I have not integrated this with our build system.
* I have not moved the common dependencies to the project on the root.
* I have not integrated the project-to-project references via typescript project references.
* I have not figured out the dev experience, other than you run a command at the root of the repo to build and produce the appropriate outputs.
  * This `npm run build --workspace path/to/package.json`.
  * Its easy enough for us to add scripts at the workspace package.json to trigger individual builds parts.

At this point, I think we can start working on the remaining things little by little until we can do the switch.

**Comment by BrennanConroy** [comment] 2023-01-19 20:51
> Removed the @microsoft/dotnet-js-interop package.
> * We are the only ones that consume it and we do not push it to npm.

https://www.npmjs.com/package/@microsoft/dotnet-js-interop?activeTab=versions

**Comment by dougbu** [comment] 2023-01-19 22:54
> I had to disable the .npmrc because it did not allowed me to restore locally.

This is a significant problem and means your changes must not be checked in. If your experiments w/ `vsts-npm-auth` are also not working, the workaround (which will break the experiments I requested in our Build channel) is likely to add `always-auth=true` to the .npmrc files at least temporarily.

**Comment by dougbu** [comment] 2023-01-19 22:57
Oh, in addition, `npm` is supposed to be able to handle yarn.lock files. Might be worth trying `npm ci` (which should be like `yarn install --frozen-lockfile`) instead of `npm install`.

**Comment by javiercn** [comment] 2023-01-20 10:11
> > Removed the @microsoft/dotnet-js-interop package.
> > 
> > * We are the only ones that consume it and we do not push it to npm.
> 
> https://www.npmjs.com/package/@microsoft/dotnet-js-interop?activeTab=versions

We can bring it back or deprecate it's usage. We certainly have never encouraged people to use it.

**Comment by javiercn** [comment] 2023-01-20 10:13
> This is a significant problem and means your changes must not be checked in. If your experiments w/ `vsts-npm-auth` are also not working, the workaround (which will break the experiments I requested in our Build channel) is likely to add `always-auth=true` to the .npmrc files at least temporarily.

https://docs.npmjs.com/cli/v9/configuring-npm/npmrc?v=true#global-config-file

We would change this on the agents to configure it globally for the machine or per user https://docs.npmjs.com/cli/v9/configuring-npm/npmrc?v=true#per-user-config-file

We can also generate the file as a build step when building on the CI before running restore. I do not believe this is a big deal.

**Comment by javiercn** [comment] 2023-01-20 10:15
> Oh, in addition, npm is supposed to be able to handle yarn.lock files. Might be worth trying npm ci (which should be like yarn install --frozen-lockfile) instead of npm install.

I'm at the stage of determining how to get basic things to work and how much work is left. In the end the CI/dev loop will run `npm ci` not install, and we will get rid of the yarn.lock files. There is no value nor point on relying on an interop feature in favor of the native one. Specially since there is going to be a single packages-lock.json file.

**Comment by wtgodbe** [comment] 2023-03-21 20:38
I'm working on this now when I have time, but I expect I won't be done before some time in May. Will let people know if anything changes.

**Comment by wtgodbe** [comment] 2024-01-09 19:16
Closing as dupe of https://github.com/dotnet/aspnetcore/pull/52914

**Closed by wtgodbe** 2024-01-09 19:16 UTC
Labels: task, area-infrastructure
