### ISSUE TITLE
ConnectionClosedTokenFiresOnClientFIN fails due to timeout

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#23043] opened 2020-06-17 17:29 UTC
ConnectionClosedTokenFiresOnClientFIN fails due to a time out.

**Ref:** https://dev.azure.com/dnceng/public/_build/results?buildId=691787&view=results

```
  âˆš HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate [4s 429ms]
[xUnit.net 00:00:33.17]     ConnectionClosedTokenFiresOnClientFIN(listenOptions: http://127.0.0.1:0) [FAIL]
[xUnit.net 00:00:33.17]       System.TimeoutException : The operation at /_/src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:27 timed out after reaching the limit of 30000ms.
[xUnit.net 00:00:33.17]       Stack Trace:
[xUnit.net 00:00:33.18]         /_/src/Testing/src/TaskExtensions.cs(57,0): at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
[xUnit.net 00:00:33.18]         /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs(527,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnClientFIN(ListenOptions listenOptions)
[xUnit.net 00:00:33.18]         --- End of stack trace from previous location ---
  X ConnectionClosedTokenFiresOnClientFIN(listenOptions: http://127.0.0.1:0) [30s 26ms]
  Error Message:
   System.TimeoutException : The operation at /_/src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:27 timed out after reaching the limit of 30000ms.
  Stack Trace:
     at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Testing/src/TaskExtensions.cs:line 57
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnClientFIN(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 527
--- End of stack trace from previous location ---
  âˆš LargeUpload(contentLength: 2147483648, checkBytes: False) [1s 761ms]
  âˆš LargeUpload(contentLength: 10485760, checkBytes: True) [117ms]
  âˆš ConnectionResetBetweenRequestsIsLoggedAsDebug [7ms]
  âˆš ThrowsOnReadAfterConnectionError [8ms]
  âˆš ServerCanAbortConnectionAfterUnobservedClose(listenOptions: http://127.0.0.1:0) [10ms]
  âˆš ServerCanAbortConnectionAfterUnobservedClose(listenOptions: http://127.0.0.1:0) [7ms]
  âˆš RemoteIPv6Address [17ms]
  âˆš AbortingTheConnectionSendsFIN [7ms]
  âˆš RemoteIPv4Address [5ms]
  âˆš RequestAbortedTokenFiredOnClientFIN [8ms]
  âˆš ConnectionClosedTokenFiresOnServerAbort(listenOptions: http://127.0.0.1:0) [8ms]
  âˆš ConnectionClosedTokenFiresOnServerAbort(listenOptions: http://127.0.0.1:0) [5ms]
  âˆš ConnectionResetPriorToRequestIsLoggedAsDebug [6ms]
  âˆš ConnectionResetMidRequestIsLoggedAsDebug [8ms]
  âˆš ConnectionClosedTokenFiresOnServerFIN(listenOptions: http://127.0.0.1:0) [8ms]
  âˆš ConnectionClosedTokenFiresOnServerFIN(listenOptions: http://127.0.0.1:0) [5ms]
  âˆš DoesNotHangOnConnectionCloseRequest [9ms]
  âˆš CanHandleMultipleConcurrentRequests [8ms]
  âˆš RequestsCanBeAbortedMidRead(listenOptions: http://127.0.0.1:0) [20ms]
  âˆš RequestsCanBeAbortedMidRead(listenOptions: http://127.0.0.1:0) [6ms]
  âˆš ClientCanReceiveFullConnectionCloseResponseWithoutErrorAtALowDataRate [15s 99ms]
  âˆš ThrowsOnWriteWithRequestAbortedTokenAfterRequestIsAborted(listenOptions: http://127.0.0.1:0) [9ms]
  âˆš ThrowsOnWriteWithRequestAbortedTokenAfterRequestIsAborted(listenOptions: http://127.0.0.1:0) [5ms]
  âˆš ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure [4s 350ms]
  âˆš WriteAfterConnectionCloseNoops(listenOptions: http://127.0.0.1:0) [7ms]
  âˆš WriteAfterConnectionCloseNoops(listenOptions: http://127.0.0.1:0) [4ms]
  âˆš ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [16s 133ms]
  âˆš AppCanHandleClientAbortingConnectionMidResponse(listenOptions: http://127.0.0.1:0) [4s 484ms]
[xUnit.net 00:01:12.37]   Finished:    Libuv.FunctionalTests
  âˆš AppCanHandleClientAbortingConnectionMidResponse(listenOptions: http://127.0.0.1:0) [5s 41ms]
```

**Comment by BrennanConroy** [comment] 2020-06-17 20:36
Dupe of https://github.com/dotnet/aspnetcore/issues/20163

**Comment by captainsafia** [comment] 2020-06-17 21:17
Let's keep this one open since it's referenced in the `QuarantinedTest` attribute.

**Comment by BrennanConroy** [comment] 2020-06-17 23:18
Test seems to fail only on OSX?
```
[0.001s] [TestLifetime] [Information] Starting test ConnectionClosedTokenFiresOnClientFIN-http_127.0.0.1_0 at 2020-06-01T22:46:27
[0.002s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting starting
[0.005s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting started
[0.005s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Libuv.FunctionalTests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
[0.005s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] TestServer is listening on port 63015
[0.006s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HM06FMF76B3K" received FIN.
[0.006s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM06FMF76B3K" accepted.
[0.006s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM06FMF76B3K" started.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM06FMF76B3K" disconnecting.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HM06FMF76B3K" sending FIN because: "The client closed the connection."
[0.007s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM06FMF76B3K" stopped.
[30.024s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting shutdown
[30.027s] [TestLifetime] [Information] Finished test ConnectionClosedTokenFiresOnClientFIN-http_127.0.0.1_0 in 30.0267181s
```

**Comment by halter73** [comment] 2020-06-18 00:50
Is it also libuv only?

**Comment by BrennanConroy** [comment] 2020-06-18 00:51
Idk, didn't think to check.

**Comment by davidfowl** [comment] 2020-06-19 13:53
Hopefully we’ll have dumps soon for OS X. Also we don’t get dumps on timeouts here yet

**Comment by sebastienros** [comment] 2020-10-08 22:15
This test is now at 100% success rate. I'd like to unquarantine it, any objection?

**Comment by BrennanConroy** [comment] 2020-10-08 22:16
Yes objection, there has been no work to fix the test

**Comment by sebastienros** [comment] 2020-10-08 22:18
Sorry, didn't see the PR was abandoned

**Comment by BrennanConroy** [comment] 2021-10-14 15:46
That PR shouldn't have affected these tests reliability

**Comment by Tratcher** [comment] 2021-11-02 17:12
This appears to be libuv specific and libuv has now been removed. Ready for unquarantine.

**Closed** 2021-11-02 19:58 UTC
Labels: task, test-failure, area-runtime, severity-major, affected-very-few, test-fixed
