### ISSUE TITLE
Blazor Router cannot load Page from Razor Class Library

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#53534] opened 2024-01-22 16:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Router-cannot-load-Page-from-Razo/10520790)._

---
To Reproduce:
1. Create Solution with .net8 Blazor Web App and a  .net8 Razor Class Library
2. add Dependency to Razor Class Library
3. add @using RazorClassLibrary to _Imports.razor of to Blazor App
4. add @page "/component1" to Component1.razor in RazorClassLibrary
5. add <Component1></Component1> to Home.razor of Blazor App
6. add  AdditionalAssemblies="new[] { typeof(RazorClassLibrary.Component1).Assembly }" to Router.razor
7. build, run => all works fine, Component1 show on Home page
8. navigate to  https://localhost:XXXX/component1 (or using component1 in NavMenu) results in a HTTP ERROR 404

This is a very annoying bug. Please help!
[BlazorHybridDemo2.zip](https://aka.ms/dc/file?name=B9fe3a6f3a58b4873b66464fc7684e6ed638360787594766535_BlazorHybridDemo2.zip&tid=9fe3a6f3a58b4873b66464fc7684e6ed638360787594766535)

---
#### JR on 11/20/2023, 04:07 AM: 

(private comment, text removed)
#### Jurgen Reichert (3P) on 11/20/2023, 04:14 AM: 

(private comment, text removed)
#### Feedback Bot on 11/20/2023, 06:47 PM: 

(private comment, text removed)
#### Jurgen Reichert (3P) on 11/21/2023, 01:16 AM: 

(private comment, text removed)
#### Jurgen Reichert (3P) on 11/21/2023, 01:23 AM: 

(private comment, text removed)
#### Jurgen Reichert (3P) on 11/21/2023, 02:41 AM: 

(private comment, text removed)
#### Joona Luoma on 12/4/2023, 01:05 PM: 

(private comment, text removed)
#### DJ Sures on 12/9/2023, 11:29 AM: 

(private comment, text removed)
#### Danny Nieuwlaat on 1/22/2024, 03:00 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment] 2024-01-23 11:18
Dupe of https://github.com/dotnet/aspnetcore/pull/52331, https://github.com/dotnet/aspnetcore/pull/52351, fixed in 8bf4d2de209577d15306635402a594de02fa4d53, and verified with 8.0.1, please update to use 8.0.1

**Closed by javiercn** 2024-01-23 11:18 UTC
Labels: area-blazor, feature-blazor-routing

**Comment by joost00719** [comment] 2024-03-08 14:58
I'm also facing this issue, but slightly different.
I dynamically load the DLL files because we're using a plugin system.
It works fine, but as soon as I add a nuget package dependancy, I get a 404. I'm not even using the dependancy.

It's really frustrating and I don't know how to temp-fix this.
