### ISSUE TITLE
Unable to build components

### ISSUE THREAD

**Issue by tomaswesterlund** [dotnet/aspnetcore#35192] opened 2021-08-09 19:38 UTC
### Description
I have been following the instructions as stated under [BuildFromSource.md](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md) but I receive these errors when calling `build.cmd` located under `Componens\src\`
```
Build FAILED.

C:\GitHub\aspnetcore\eng\targets\Npm.Common.targets(79,5): error : Command failed with exit code 2. [C:\GitHub\aspnetcore\src\JSInterop\Microsoft.JSInterop.JS\src\Microsoft.JSInterop.JS.npmproj]
C:\GitHub\aspnetcore\eng\targets\Npm.Common.targets(79,5): error : Command failed with exit code 1. [C:\GitHub\aspnetcore\src\SignalR\clients\ts\signalr\signalr.npmproj]
C:\GitHub\aspnetcore\src\Components\WebAssembly\WebAssembly.Authentication\src\Microsoft.AspNetCore.Components.WebAssembly.Authentication.csproj(67,5): error : Command failed with exit code 127.
C:\GitHub\aspnetcore\.dotnet\sdk\6.0.100-rc.1.21401.2\Microsoft.Common.CurrentVersion.targets(1777,5): error MSB4181: The "MSBuild" task returned false but did not log an error. [C:\GitHub\aspnetcore\src\Components\test\E2ETestMigration\Microsoft.AspNetCore.Components.Migration.E2ETests.csproj]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:02:14.25
Build failed with exit code 1. Check errors above.
build.cmd completed
```

### My steps are:

1. Call `restore.cmd` from root with no errors reported
2. Call `. .\activate.ps1 code .` (might be unnecessary as I use Visual Studio 2019)
3. Call `.\src\Components\build.cmd` from root (as described in [this](https://github.com/dotnet/aspnetcore/issues/24830#issuecomment-672938219) issue) with errors reported above

**Full logs can be found here**

- [build.log](https://github.com/dotnet/aspnetcore/files/6956943/build.log)
- [restore.log](https://github.com/dotnet/aspnetcore/files/6956944/restore.log)

**Comment by SteveSandersonMS** [comment] 2021-08-11 09:56
@javiercn I also just got this error on build, along with another one that suggests it might relate to SWA:

```
C:\git\dotnet\aspnetcore\.dotnet\sdk\6.0.100-rc.1.21401.2\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(669,7): error : Unable to find a project reference for manifest item 'C:\git\dotnet\aspnetcore\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net6.0\StaticWebAssets.build.json' with project file 'c:\git\dotnet\aspnetcore\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj' [c:\git\dotnet\aspnetcore\src\Components\WebAssembly\WebAssembly.Authentication\src\Microsoft.AspNetCore.Components.WebAssembly.Authentication.csproj]
C:\git\dotnet\aspnetcore\.dotnet\sdk\6.0.100-rc.1.21401.2\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(669,7): error : Unable to find a project reference for manifest item 'C:\git\dotnet\aspnetcore\artifacts\obj\Microsoft.AspNetCore.Components.Authorization\Debug\net6.0\StaticWebAssets.build.json' with project file 'c:\git\dotnet\aspnetcore\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj' [c:\git\dotnet\aspnetcore\src\Components\test\testassets\BasicTestApp\BasicTestApp.csproj]
C:\git\dotnet\aspnetcore\.dotnet\sdk\6.0.100-rc.1.21401.2\Microsoft.Common.CurrentVersion.targets(2024,5): error MSB4181: The "MSBuild" task returned false but did not log an error. [c:\git\dotnet\aspnetcore\src\Components\test\E2ETestMigration\Microsoft.AspNetCore.Components.Migration.E2ETests.csproj]
```

This was after updating `main` to latest and running `build.cmd` from `src/Components`.

**Comment by javiercn** [comment] 2021-08-11 10:00
@SteveSandersonMS checking, I think I already fix this last week (sunday) but it might not have made it to ASP.NET Core

**Comment by SteveSandersonMS** [comment] 2021-08-16 11:10
@javiercn What SDK version contains the fix? The `main` branch is on 6.0.100-rc.1.21401.2 which still hits a lot of errors with this.

Running `eng\build.cmd` from the repo root leads to a bunch of these:

```
C:\repopath\.dotnet\sdk\6.0.100-rc.1.21401.2\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(325,5): error : System.ArgumentNullException: Value cannot be null. (Parameter 'source') [C:\repopath\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj]
```

**Comment by SteveSandersonMS** [comment] 2021-08-23 11:52
@javiercn Running `build.cmd` from `src\Components` just now using the latest code in `main`, I'm getting one of these:

```cs
C:\git\dotnet\aspnetcore\.dotnet\sdk\6.0.100-rc.1.21415.3\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(714,5): error : Unable to find a project reference for project configuration item 'c:\git\dotnet\aspnetcore\src\Components\Authorization\src\Microsoft.AspNetCore.Components.Authorization.csproj' [C:\git\dotnet\aspnetcore\src\Components\WebAssembly\WebAssembly.Authentication\src\Microsoft.AspNetCore.Components.WebAssembly.Authentication.csproj]
```

I'm sure it wouldn't happen if I completely reset the working copy back to a known state, but it hits productivity too much to have to keep doing that. There's something wrong in the incrementalism or build ordering. Perhaps you're already aware of it but this is another data point.

Do items in `area-infrastructure` get triaged into a particular milestone?

**Comment by javiercn** [comment] 2021-08-23 12:37
@SteveSandersonMS I'll check, however if you capture an MSBuild binlog of the issue it would be of great help.

**Comment by javiercn** [comment] 2021-08-23 13:20
The Components.slnf solution filter also looks wrong

**Comment by javiercn** [comment] 2021-08-23 13:27
I'm not able to reproduce this. Here is my environment and what I did.
```console
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21415.3
 Commit:    8e5e77d8c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   <<Base>>.dotnet\sdk\6.0.100-rc.1.21415.3\

Host (useful for support):
  Version: 7.0.0-alpha.1.21419.1
  Commit:  59b6c36b35

.NET SDKs installed:
  6.0.100-rc.1.21415.3 [<<Base>>.dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.14 [<<Base>>.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21413.12 [<<Base>>.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-dev [<<Base>>.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [<<Base>>.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [<<Base>>.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21414.4 [<<Base>>.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.21419.1 [<<Base>>.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21414.3 [<<Base>>.dotnet\shared\Microsoft.WindowsDesktop.App]
```

* `build.cmd` from `src/Components`
* open `src/Components/ComponentsNoDeps.slnf`
* build solution.

Everything works for me.

**Comment by SteveSandersonMS** [comment] 2021-08-23 14:12
It definitely depends on particular states of the working tree, not being in a clean state. For me it happened today when I did a git pull to get an updated SDK.

**Comment by javiercn** [comment] 2021-08-24 10:40
We found out this is because of a casing conversion in GetMetadata("%FullPath") we are doing a case-sensitive comparison always and we need to switch to use a casing that is based on the OS we are running on.

**Comment by dougbu** [comment] 2021-10-05 23:36
@javiercn @mkArtakMSFT I cleared the milestone because it's unclear this issue has been fixed and I don't know, if it was fixed, the appropriate milestone. Please add the issue where it belongs.

**Comment by javiercn** [comment] 2021-10-06 08:44
This was fixed in https://github.com/dotnet/sdk/pull/20603 as mentioned above

**Closed by javiercn** 2021-10-06 08:44 UTC
Labels: area-infrastructure
