### ISSUE TITLE
SpaProxy doesn't work with dotnet watch

### ISSUE THREAD

**Issue by hez2010** [dotnet/aspnetcore#34925] opened 2021-08-01 15:06 UTC
### Describe the bug
I'm using `Microsoft.AspNetCore.SpaProxy` for SPA web project, it works fine if I use `dotnet run` to run my project, but not with `dotnet watch` so that I cannot use hot reload with `SpaProxy`.

### To Reproduce
```
dotnet new react
dotnet watch
```

And you will find no SPA project being launched.

### Further technical details
- ASP.NET Core version: .NET 6 Preview 6
- The IDE: command line

**Comment by javiercn** [comment] 2021-08-17 11:34
@hez2010 thanks for contacting us.

@mkArtakMSFT I suspect this is a regression in dotnet-watch.

I know for sure this worked since I fixed a bug @LadyNaggaga discovered while trying it out.

I'll do a quick investigation to see if I detect what's going on and can make a quick fix, otherwise, I will move it to RC2.

**Comment by javiercn** [comment] 2021-08-17 11:47
This seems to be a dotnet-watch issue stomping over the SPA templates.

https://github.com/dotnet/aspnetcore/issues/35410

Closing this issue in favor of the issue above which has all the details.

**Closed by javiercn** 2021-08-17 11:47 UTC
Labels: investigate, area-commandlinetools, feature-spa
