### ISSUE TITLE
Extract a generic AddStackExchangeRedis into its own package

### ISSUE THREAD

**Issue by alrz** [dotnet/aspnetcore#30342] opened 2021-02-21 08:17 UTC
Currently `Microsoft.AspNetCore.SignalR.StackExchangeRedis` and `Microsoft.Extensions.Caching.StackExchangeRedis` both maintain a separate Redis connection management.

This portion could be extracted to its own package and be exposed as a generic API. A user service (like health check or a rate limiter middleware) could make use of that instead of reimplementing its own.

(this might interact with some of [existing issues related to Redis](https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+is%3Aopen+redis+in%3Atitle))

**Comment by BrennanConroy** [comment] 2021-02-21 18:26
Dupe of https://github.com/dotnet/aspnetcore/issues/28379

**Comment by alrz** [comment] 2021-02-22 07:08
> injecting IConnectionMultiplexer

While it does address this scenario, still you have to duplicate the `EnsureRedisServerConnection` logic. I was thinking more of a self-contained helper to register Redis servers, just like what we have for `HttpClient`. An additional feature could be adding `LoadedLuaScript`. For instance:
```cs
services.AddStackExchangeRedis(config).AddLuaScript("name", "script")

var factory = provider.GetService<IRedisConnectionFactory>();
var connection = factory.GetConnection("name?");
connection.RunScriptAsync("name", parameters);
```
From there, you could imagine a way to set it up for existing services like Caching, SignalR, and DataProtection.

**Comment by BrennanConroy** [comment] 2021-02-24 21:23
Closing, continue discussion on the other issue :)

**Closed by BrennanConroy** 2021-02-24 21:23 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers
