### ISSUE TITLE
Compilation error in in .NET 5 Preview 8 with attributes without value, in some cases

### ISSUE THREAD

**Issue by sjohag** [dotnet/aspnetcore#25267] opened 2020-08-26 07:11 UTC
Compilation error with attributes without value, in some cases

### To Reproduce
In any Razor component, add:
&lt;video src="@videoSrc" autoplay&gt;&lt;/video&gt;
@code{
    string videoSrc = string.Empty;
}

In .NET 5 Preview 8, 
error CS1503: Argument 2: cannot convert from 'string' to 'in Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame'

&lt;video src="movie.mp4" autoplay&gt;&lt;/video&gt;
Compiles without error

dotnet --info

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

**Comment by as-srandall** [comment] 2020-08-26 07:56
Yep, I'm getting exactly the same error with a Blazor Server Side app.
Most Visual Studio releases seem to break something these days, seriously, I'm not impressed! More wasted time.
Using Microsoft Visual Studio Community 2019 Preview Version 16.8.0 Preview 2.0

**Comment by as-srandall** [comment] 2020-08-26 08:00
The following two lines are common amongst the errors I'm getting in the xxx.razor.g.cs files:
 __builder.AddAttribute(15, "selected");
 __builder.AddAttribute(12, "disabled");

**Comment by as-srandall** [comment] 2020-08-26 08:18
In the code fragment below, its generating the error on the line in bold:

    <select id="pageSizeSelector" class="form-control-sm" FullWidth="false" @onchange="OnPageSizeChanged">
        @foreach (var pageSize in AvailablePageSizes)
        {
            var isSelected = pageSize == PageSize;
            @if (isSelected)
            {
                **<option value="@pageSize" selected>**
                    @pageSize
                </option>
            }
            else
            {
                <option value="@pageSize">
                    @pageSize
                </option>
            }
        }
    </select>

**Comment by SteveSandersonMS** [comment] 2020-08-26 14:09
Thanks for reporting this. I'm trying to track this down but so far haven't managed to reproduce the issue. Here's what I've tried:

 1. In an empty directory, ran:
    * `dotnet --version` and verified the output is `5.0.100-preview.8.20417.9`
    * `dotnet new blazorserver`
    * `dotnet run` (and verified it works in a browser)
 1. Using VS Code, edited `Pages/Index.razor` to contain the following:

```razor
@page "/"

<video src="@videoSrc" autoplay></video>

@code{
    string videoSrc = string.Empty;
}
```

 3. Back on the command line, ran `dotnet build`, which completed without errors. Also `dotnet run` works.
 4. Now also tried editing `Pages/Index.razor` to contain:

```razor
@page "/"

<select id="pageSizeSelector" class="form-control-sm" FullWidth="false" @onchange="OnPageSizeChanged">
    @foreach (var pageSize in AvailablePageSizes)
    {
        var isSelected = pageSize == PageSize;
        @if (isSelected)
        {
            <option value="@pageSize" selected>
                @pageSize
            </option>
        }
        else
        {
            <option value="@pageSize">
                @pageSize
            </option>
        }
    }
</select>

@code {
    void OnPageSizeChanged() {}

    int[] AvailablePageSizes = new[] { 1, 2, 3 };

    int PageSize = 1;
}
```

 5. Back on the command line, ran `dotnet build`, which completed without errors. Also `dotnet run` works.

So I'm not sure how to reproduce the problem. I also tried building in VS 2019 16.8.0 Preview 1.0 which worked fine too. I'll try Preview 2 later.

@sjohag @as-srandall Do either of you have further suggestions on how to reproduce the issue? If you follow the steps I listed above, does the error occur for you, or does it only happen in some specific project?

If it only happens in an existing project, can you try deleting your project's `obj`/`bin` directories and building again?

**Comment by sjohag** [comment] 2020-08-26 14:36
Using Visual Studio Version 16.8.0 Preview 2.0, File - New - Project - Blazor App - Blazor Server App
In .csproj target framework is netcoreapp3.1 and the problem can be reproduced.
Changing to net5.0 solves the problem.

**Comment by 23min** [comment] 2020-08-26 15:21
I had 
`<td "table-primary"` that I changed to <td class="table-primary" and one of the errors went away.
The other errors seemd non-legit.

Threw away obj and bin and built successfully.

**Comment by 23min** [comment] 2020-08-26 15:22
Woops, spoke too early. It built but it didn't run! Same errors again. (What's that all about?)

**Comment by 23min** [comment] 2020-08-26 15:27
Upon further analysis :)

The other five errors were actually legit, but the error message is misleading to say the least.

I had several `td class=""`
When I removed the empty class attribute, the errors went away.

**Comment by SteveSandersonMS** [comment] 2020-08-26 15:44
@23min it's a little difficult to keep track of what you're saying. Could you clarify by posting a complete example of something that fails to compile with the `Argument 2: cannot convert from 'string' to 'in Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame'`, if you saying you have such an example? Thanks!

Also, if you're getting a different error, then please post it as a different issue instead of here.

**Comment by jeffrey-caldwell** [comment] 2020-08-26 15:44
I had the same issue.

Each file with an error contained a html tag which had class="" in it.  Once I removed all of those, my program is running again.

**Comment by 23min** [comment] 2020-08-26 15:49
@SteveSandersonMS to sum it up:

In each case, I had a table definition `<td>` with an invalid class or an attribute that was not recognized.

For example (invalid class)
![image](https://user-images.githubusercontent.com/1111124/91326030-25159880-e7c4-11ea-85f4-f45de5db1fd7.png)

and (empty class)
![image](https://user-images.githubusercontent.com/1111124/91326138-470f1b00-e7c4-11ea-8fe0-2c59b88ba436.png)

Does that clarify?

**Comment by Zelif** [comment] 2020-08-27 04:34
Just ran into this as updating to Version 16.8.0 preview 2
As @jeffrey-caldwell and @23min pointed out any blank attribute will trigger this. This also include stuff like
`<option value=""> ` 

For @23min's example if you need to keep the custom attribute you could just assign a string to it to keep it. 
`<td table-primary="table-primary">`

Cheers to @jeffrey-caldwell and @23min for pointing this out. 👍

**Comment by kaizen365** [comment] 2020-08-27 07:15
@Zelif I just encountered this issue with VS 2019 16.8.0 preview 2.

For the <textarea readonly> (and disabled attributes) which was causing build errors for me i have changed this to valid xhtml by setting readonly="readonly" and disabled="disabled" to get my build working again...

**Comment by conficient** [comment] 2020-08-27 08:57
> Thanks for reporting this. I'm trying to track this down but so far haven't managed to reproduce the issue

I've figured out what the cause is - if you've updated to .NET Core 5.0 Preview 8 SDK, but build an .NET Core 3.1 Blazor app that has value-less attributes, it creates the error. I had the same issue yesterday.

Steps to reproduce:

1. Create new Blazor Server app (select .NET core 3.1)
2. Ensure `<TargetFramework>netcoreapp3.1</TargetFramework>` in project file
3. Add the following in Index.razor:
```
<input type="text" @bind="value" required />
@code {
    string value = "hello";
}
```
4. Try to build 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'string' to 'in Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrame'	BlazorApp2	C:\Users\Howard\Source\Repos\BlazorApp1\BlazorApp2\obj\Debug\netcoreapp3.1\Razor\Pages\Index.razor.g.cs	84	Active
```
## Fix
If you then edit the target framework to 5.0 it fixes the error.

You can also assign values as a workaround, e.g. ` required="required" ` although that's not ideal

**Comment by conficient** [comment] 2020-08-27 09:58
Another fix I've just tested, which avoids any changes to the HTML is to add a `global.json` file to force use of the .NET 3.1 SDK for the build:
1. Add a text file `global.json` to the root of the solution folder (assuming you don't already have one)
2. Edit the file to set the SDK version you have installed and wish to compile against. Mine is currently 3.1.401
```
{
  "sdk": {
    "version": "3.1.401",
    "rollForward": "latestMinor"
  }
}
```
If you don't know what SDK version you have installed, use
```
dotnet --list-sdks
```
at the command line

**Comment by TomaszGrzmilas** [comment] 2020-08-27 10:24
I have project:
<TargetFramework>netcoreapp3.1</TargetFramework>

I think I got this error after updating to Microsoft Visual Studio Community 2019 Preview Version 16.8.0 Preview 2.0

Helpfully workaround is working 💯 :)

**Comment by SteveSandersonMS** [comment] 2020-08-27 11:57
Thanks everyone for the reports and the additional info.

We now have a fix pending for this at https://github.com/dotnet/aspnetcore/pull/25307. I expect this will ship in the 5.0 RC1 release.

Until then, the workaround I'd recommend is what @conficient suggested [here](https://github.com/dotnet/aspnetcore/issues/25267#issuecomment-681850250), i.e., add a `global.json` file to tell `dotnet` to use the 3.x SDK (or a 5.0-preview7 or earlier one). This way you don't have to edit your code at all.

The other good solution is to update fully to 5.0-preview8, i.e., change your `TargetFramework` to 5.0, though that's a more dramatic fix as then you're really using a prerelease framework at runtime.

**Comment by SteveSandersonMS** [comment] 2020-08-28 15:44
Fixed in https://github.com/dotnet/aspnetcore/pull/25307

**Closed by SteveSandersonMS** 2020-08-28 15:44 UTC
Labels: Working, area-blazor
