### ISSUE TITLE
Blazor WASM InteractiveRequestOptions is ignored when deployed to Azure

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet/aspnetcore#45289] opened 2022-11-26 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a default blazor wasm project in .net7 with authentication. I added the InteractiveRequestOptions with a returnURL to counter page. This works with no issues locally. However, if I deploy this to Azure web app (hosted or not hosted), the interactiverequestoptions are being completely ignored. It just redirects it to the home page. Is there some additional configuration required to maintain the HistoryEntryState once deployed to Azure
![image](https://user-images.githubusercontent.com/45796558/204084000-522ff4f8-02a7-457a-a698-8fe83d02a4fc.png)

### .NET Version

7

**Comment by javiercn** [comment] 2022-11-26 11:10
@darena-pjindal thanks for contacting us.

This is a known issue with regards to trimming in .NET 7.0. We have addressed the issue in 7.0.1 which will be available in a few weeks. In the mean time, you can disable trimming for the assembly. See https://github.com/dotnet/aspnetcore/issues/44973#issuecomment-1312058110 for details.

Dupe of https://github.com/dotnet/aspnetcore/issues/44973

**Closed by javiercn** 2022-11-26 11:10 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-wasm-auth
