### ISSUE TITLE
System.Text.Json Wrong serialization after Newtonsoft migration

### ISSUE THREAD

**Issue by AnTiiK** [dotnet/aspnetcore#56686] opened 2024-07-09 12:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The serialization result of decimal, double and float are wrong with System.Text.Json.  
With the following data:

```c#
    public class TestExample
    {
        public required int Int { get; set; }
        public required decimal Decimal { get; set; }
        public required float Float { get; set; }
        public required double Double { get; set; }
    }

    var data = new TestExample
    { 
        Decimal = 1m, 
        Double = 1, 
        Float = 1f, 
        Int = 1 
    };
``` 

After serialization with  Newtonsoft.Json.JsonConvert we are the folling result

```json
{ "Int":1, "Decimal":1.0, "Float":1.0, "Double":1.0 }
``` 

And the following result with System.Text.Json.JsonSerializer

```json
{ "Int":1, "Decimal":1, "Float":1, "Double":1 }
``` 

The result should be same as Newtonsoft.Json

### Expected Behavior

When we serialize this data with System.Text.Json

```c#
    var data = new TestExample
    { 
        Decimal = 1m, 
        Double = 1, 
        Float = 1f, 
        Int = 1 
    };
``` 

The result should be

```json
{ "Int":1, "Decimal":1.0, "Float":1.0, "Double":1.0 }
``` 

### Steps To Reproduce

Use this code into dotnet application

```c#
    public class TestExample
    {
        public required int Int { get; set; }
        public required decimal Decimal { get; set; }
        public required float Float { get; set; }
        public required double Double { get; set; }
    }

            var data = new TestExample
            { 
                Decimal = 1m, 
                Double = 1, 
                Float = 1f, 
                Int = 1 
            };

            string newtonsoft = Newtonsoft.Json.JsonConvert.SerializeObject(data);
            string systemTextJson = System.Text.Json.JsonSerializer.Serialize(data);

``` 

### .NET Version

8.0.302

**Comment by chrisoverzero** [comment] 2024-07-09 12:43
> The result should be same as Newtonsoft.Json

Why?

**Comment by AnTiiK** [comment] 2024-07-09 12:56
> > The result should be same as Newtonsoft.Json
> 
> Why?

To keep same type on deserialization. 
In my case, a have an API who receive anonymous data (list of objects) and the first element of the list determine the type needed to deserialize all data, if I have "1" instead of "1.0" all others values will be round and converted to Integer

**Comment by martincostello** [comment] 2024-07-09 13:37
1. This isn't an issue with ASP.NET Core, System.Text.Json is part of the [dotnet/runtime](https://github.com/dotnet/runtime) repository.
2. It's not a bug with System.Text.Json, it's by design.

If you want to force the serialization to be the same with the decimal point, you can use a custom converter to do something like this for each type (`float`, `double`, `decimal`) you want to change the serialization for:

```csharp
public sealed class JsonConverterDoubleWithFraction : JsonConverter<double>
{
    public override double Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => reader.GetDouble();

    public override void Write(Utf8JsonWriter writer, double value, JsonSerializerOptions options)
        => writer.WriteNumberValue(new decimal(value) + 0.0m);
}
```

**Comment by BrennanConroy** [comment] 2024-07-09 18:41
Looks like https://github.com/dotnet/runtime/issues/35195 on the runtime side. Closing as it's not an ASP.NET Core issue.

**Closed by BrennanConroy** 2024-07-09 18:41 UTC
Labels: area-mvc
