### ISSUE TITLE
Blazor and project level Nullable directive

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#37090] opened 2021-09-29 09:59 UTC
SDK .Net 5.0.401

when I use Nullable directive at projet level on a Blazor WASM Application, I get an error with partial classes:

BillAddress.razor.cs
![image](https://user-images.githubusercontent.com/23618436/135246839-30e06d82-793f-440a-888b-ad344a224c6f.png)

BillAddress.razor
![image](https://user-images.githubusercontent.com/23618436/135247010-f71fb5c8-4500-4b4a-ab49-8a8ac32c59e3.png)

Base Class is the same

Without Nullable directiv, there's no issue.

**Comment by mkArtakMSFT** [comment] 2021-09-30 16:53
Thanks for contacting us. This is a dupe of #30531

**Closed by mkArtakMSFT** 2021-09-30 16:53 UTC
Labels: area-blazor
