### ISSUE TITLE
Blazor Base URI comparison is case sensitive

### ISSUE THREAD

**Issue by SPWizard01** [dotnet/aspnetcore#52288] opened 2023-11-22 10:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you host blazor server app inside IIS under an application path(i.e. some_website/myapppath) you have to define a `<base href="/myapppath/" />` inside you app.razor and using `app.UsePathBase("/myapppath");`

And everything seems to work fine, until you actually go to your website but miss the case sensitivity i.e. `http://customsite.company.com/MyAppBase` you will get circuit initialization failure.

This is due to case sensitivity here:
https://github.com/dotnet/aspnetcore/blob/c187bb1dc18de5b5b0afcfef0c7c14dd67415c61/src/Components/Components/src/NavigationManager.cs#L554C14-L554C41

Similar issue:
https://github.com/dotnet/aspnetcore/issues/22494

### Expected Behavior

The app should load properly

### Steps To Reproduce

Setup a base path for the app and miss case sensitivity.

### Exceptions (if any)

2023-11-22 12:08:59.272 +02:00 [DBG] Circuit initialization failed
System.ArgumentException: The URI 'http://customsite.company.com/MyAppBase' is not contained by the base URI 'http://customsite.company.com/myappbase/'.
   at Microsoft.AspNetCore.Components.NavigationManager.Validate(Uri baseUri, String uri)
   at Microsoft.AspNetCore.Components.NavigationManager.Initialize(String baseUri, String uri)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitFactory.CreateCircuitHostAsync(IReadOnlyList`1 components, CircuitClientProxy client, String baseUri, String uri, ClaimsPrincipal user, IPersistentComponentStateStore store)
   at Microsoft.AspNetCore.Components.Server.ComponentHub.StartCircuit(String baseUri, String uri, String serializedComponentRecords, String applicationState)

### .NET Version

8.0.100

**Comment by mkArtakMSFT** [comment] 2023-12-18 17:56
We'll see if adding an option for the developers to choose whether to loosen the checks regarding case sensitivity.

**Comment by SteveSandersonMS** [comment] 2024-01-18 17:21
Seems to be a duplicate of https://github.com/dotnet/aspnetcore/issues/6818

**Closed by SteveSandersonMS** 2024-01-18 17:21 UTC
Labels: enhancement, area-blazor, Pillar: Dev Experience
