### ISSUE TITLE
hotreload breaks blazor webassembly with asp and user defined base path - missing blazor-hotreload.js returns 404

### ISSUE THREAD

**Issue by elylv** [dotnet/aspnetcore#38267] opened 2021-11-10 20:18 UTC
Release version of VS2022 and .NET 6 still has the bug described in #35555 (which was closed, and supposed to have been fixed in RC2)
Any application with a base path that is not root / will not run because it can't find the blazor-hotreload.js file.  It's looking in /_framework rather than /BasePath/_framework, despite the <base> being set in index, and app.UsePathBase() being set to the base path.

**Comment by elylv** [comment] 2022-01-06 21:20
Any update on this?  As it stands, I can't use .NET 6/VS2022 to deploy anything.

**Comment by mkArtakMSFT** [comment] 2022-05-20 16:20
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/40971.

**Closed by mkArtakMSFT** 2022-05-20 16:20 UTC
Labels: investigate, area-blazor, blazor-wasm, feature-hot-reload
