### ISSUE TITLE
Email Generation Using Blazor

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/aspnetcore#40758] opened 2022-03-17 14:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am creating a Blazor WASM application, and as a part of that application, I want to send HTML emails using the same styling and components that we use throughout our Blazor WASM application, rather than write the same components in a separate email-sending service.

### Describe the solution you'd like

In an ideal world, the flow to do this would be as easy as possible, where:

- A page is generated using the Blazor/Razor rendering engine, and instead of CSS files linked, they are inlined into the DOM.
- The page is essentially "prerendered" on the server, and the HTML output to a string to be sent in the body of an email.

I am wondering if prerendering is/would be, the right tool for this?

### Additional context

Are there other approaches people use to "_reuse_" components that they've written when generating emails?

**Comment by javiercn** [comment] 2022-03-17 16:24
@taylorchasewhite thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/38114, so we will track it there. I would suggest that you up-vote that issue instead.

**Closed** 2022-03-17 16:24 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved
