### ISSUE TITLE
.net 6 rc2 identity login page return 500

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38132] opened 2021-11-05 18:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/net-6-rc2-identity-login-page-return-50/1570815)._

---
I use vs 2022 rc .net 6 rc2. 
create blazor with asp.net core identity and scaffold all Identity page.

when click fetch data blazor page, [There was an error trying to log you in: ' (500)'] is displayed.

---
#### Feedback Bot on 11/3/2021, 02:28 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment] 2021-11-05 19:08
Hello, thanks for contacting us. To allow us to investigate further, could you please provide a minimal public GitHub repro project.

**Comment by yueyaoxu** [comment] 2021-11-06 06:38
Hello, TanayParikn.

Thanks for your response. It's just a default solution created by vs 2022 RC. I post the solution at
https://github.com/yueyaoxu/BlazorApp1

When I run this solution with vs 2022 RC at debug mode. blazor page show normally, but when I click [Fetch data] or [Log in] link, [There was an error trying to log you in: ' (500)'] is displayed.

Please check it and thank you.

**Comment by jinzhao1127** [comment] 2021-11-08 03:06
@mkArtakMSFT @TanayParikh , This issue same as an existing issue (819) that we file on AspNetCore-ManualTests. The reason is:  if you create the project using localdb(create via VS), you will need to apply ef migrations to your local db to have the correct schema. Hope this will help for you.

**Comment by yueyaoxu** [comment] 2021-11-09 01:52
@jinzhao1127 I try it, it works! Thank you for helping me can jump over this issue to do next work.

**Comment by mkArtakMSFT** [comment] 2021-11-23 19:47
@HaoK @adityamandaleeka can you please look into this?

> @mkArtakMSFT @TanayParikh , This issue same as an existing issue (819) that we file on AspNetCore-ManualTests Repo. The reason is: if you create the project using localdb(create via VS), you will need to apply ef migrations to your local db to have the correct schema. Hope this will help for you.

**Comment by mkArtakMSFT** [comment] 2021-11-23 19:48
We talked about this in as we didn't first know what this issue is about. After realizing what this is one idea came up as to run the migrations as part of project creation. Just something to consider @HaoK , @adityamandaleeka

**Comment by HaoK** [comment] 2022-10-17 19:33
Dupe of https://github.com/dotnet/aspnetcore/issues/37324

**Closed by HaoK** 2022-10-17 19:33 UTC
Labels: investigate, area-identity, blazor-wasm, Author: Migration Bot :robot:, Priority:1, feature-blazor-wasm-auth
