### ISSUE TITLE
Cannot debug Blazor WASM demo app - issues with extensions

### ISSUE THREAD

**Issue by Mapiarz** [dotnet/aspnetcore#39584] opened 2022-01-17 17:43 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I'm running Blazor standalone demo app in dev container in VS Code. I can start the app just fine using `dotnet` but I cannot start a debugging session.

Whenever I open the dev container, I get message about requiring additional set up for Blazor WASM debugging. Blazor WASM debugging extension and .NET Install Tool for Extension Authors are both installed.

If I try to run a debugging session, I get the following prompts in VSCode:
- Cannot activate the 'Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension' extension because it depends on the '.NET Install Tool for Extension Authors' extension, which is not loaded. Would you like to reload the window to load the extension?
- command 'blazorwasm-companion.launchDebugProxy' not found

### Expected Behavior

I would expect the debugging session to start, with properly attached debugger.

### Steps To Reproduce

Clone repository in container volume: https://github.com/Mapiarz/blazor-standalone-demo.git

### .NET Version

6.0.101

### Anything else?

VS Code: 1.63.2
ms-dotnettools.blazorwasm-companion: 1.1.0
ms-vscode-remote.remote-containers: 0.209.6
ms-vscode-remote.vscode-remote-extensionpack: 0.21.0
See devcontainer.json in repo for other extensions - all latest.

[info.txt](https://github.com/dotnet/aspnetcore/files/7883810/info.txt)

**Comment by javiercn** [comment] 2022-01-18 10:58
@Mapiarz thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/37565 so we are using that issue to track it. Please up-vote that issue instead.

**Closed by javiercn** 2022-01-18 10:58 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-debugging, docker
