### ISSUE TITLE
SignalR throws error on interface type method parameters (both client and server side)

### ISSUE THREAD

**Issue by zorgoz** [dotnet/aspnetcore#53001] opened 2023-12-25 11:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Having a hub method (or client method) with a polymorphic interface type argument results in `InvalidDataException: Error binding arguments.` exception even if that type is seamlessly handled directly by the `System.Text.Json` library, or even by SignalR if it is not the _top-level type_ of the argument.

Example:
```
[JsonPolymorphic()]
[JsonDerivedType(typeof(C1), nameof(C1))]
[JsonDerivedType(typeof(C2), nameof(C2))]
public interface III
{
}

public record W(III Data);

public class MyHub() : Hub
{
    public void HubMethodWillFail(III message) {}
    public void HubMethodOk(IEnumerable<III> message) {}
    public void HubMethodStillOk(W message){}
}
```

### Expected Behavior

Should be able to deserialize the argument

### Steps To Reproduce
(only from client to server, but the opposite direction is the same)
https://github.com/zorgoz/SignalR-Interface-Argument-Deserialization-Issue

### Exceptions (if any)

Server side: 
```
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[22]
      Parameters to hub method 'HubMethodThatWillFail' are incorrect.
      System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
       ---> System.NotSupportedException: Deserialization of interface types is not supported. Type 'SignalR_Interface_Argument_Deserialization_Issue.III'. Path: $ | LineNumber: 0 | BytePositionInLine: 5.
       ---> System.NotSupportedException: Deserialization of interface types is not supported. Type 'SignalR_Interface_Argument_Deserialization_Issue.III'.
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader& reader, IReadOnlyList`1 paramTypes)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader& reader, IReadOnlyList`1 paramTypes)
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)
```

Client side:
```
Microsoft.AspNetCore.SignalR.HubException: Failed to invoke 'HubMethodThatWillFail' due to an error on the server. InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
```

### .NET Version

8.0.100 - but 7 also

### Anything else?

https://stackoverflow.com/questions/77678288/signalr-binding-error-on-polymorphic-data

[info.txt](https://github.com/dotnet/aspnetcore/files/13765776/info.txt)

**Comment by BrennanConroy** [comment] 2023-12-27 18:45
Dupe of https://github.com/dotnet/aspnetcore/issues/52342

**Comment by zorgoz** [comment] 2023-12-27 20:32
> Dupe of #52342

Similar, but I don't think it is a duplicate.

**Closed** 2024-01-03 21:42 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-signalr
