### ISSUE TITLE
Performance problem with localhost instead of 127.0.0.1

### ISSUE THREAD

**Issue by wima75** [dotnet/aspnetcore#22864] opened 2020-06-12 08:39 UTC
Could you make this configurable?
https://github.com/dotnet/aspnetcore/blob/c16eddc33d195c0dab0c392ed19ea0ed95ac9329/src/Middleware/SpaServices.Extensions/src/AngularCli/AngularCliMiddleware.cs#L57
On my system every call to the Angular Live Development Server with localhost will take about 4 seconds. If the call would be 127.0.0.1 instead of localhost it will take some milliseconds.

**Comment by Tratcher** [comment] 2020-06-12 14:39
Localhost resolves to both ::1 and 127.0.0.1. IPv6 is tried first, times out after 5s, and falls back to IPv4.

Why is the development server listening only on IPv4?.

**Comment by javiercn** [comment] 2020-06-15 12:44
@Tratcher this is a dupe of another issue. The problem apparently is that node only listens on IPv4

**Comment by javiercn** [comment] 2020-06-15 12:53
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/18062

**Closed by javiercn** 2020-06-15 12:53 UTC
Labels: area-mvc, feature-spa
