### ISSUE TITLE
CreateAppHost task failed unexpectedly

### ISSUE THREAD

**Issue by MCCshreyas** [dotnet/aspnetcore#29670] opened 2021-01-27 11:53 UTC
Recently, while building the Mvc solution and `MvcSandbox` project am getting below error at the end!

![image](https://user-images.githubusercontent.com/17148381/105987373-368d0480-60c4-11eb-9293-fa6fe2299c68.png)

**Comment by Tratcher** [comment] 2021-02-02 18:17
https://github.com/dotnet/sdk/issues/15225
https://github.com/dotnet/runtime/issues/47426

**Comment by Pilchie** [comment] 2021-02-08 04:49
Closing as a duplicate of https://github.com/dotnet/sdk/issues/12125.  Should be fixed for preview 2 builds.

**Closed by Pilchie** 2021-02-08 04:49 UTC
Labels: area-infrastructure
