### ISSUE TITLE
Split blazor.web.js into dynamically-loadable bundles

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#48771] opened 2023-06-13 12:40 UTC
Ideally, people using SSR only (with progressive enhancement etc) would get a very small `blazor.web.js` that doesn't include any of the SignalR parts or any of the .NET WebAssembly runtime JS support library.

Then, if an interactive component was used, we'd use an ES module dependency to dynamically load the JS library needed for it. We could potentially split the "server" and "webassembly" bundles though they would have a lot in common. It might suffice just to split out the "interactive" parts from the "static" ones.

**Comment by mkArtakMSFT** [comment] 2023-12-20 18:19
Close as a dupe of https://github.com/dotnet/aspnetcore/issues/52819

**Closed by mkArtakMSFT** 2023-12-20 18:19 UTC
Labels: enhancement, area-blazor, feature-full-stack-web-ui, Pillar: Complete Blazor Web
