### ISSUE TITLE
Visual Studio crash using Blazor Web Assembly App

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/aspnetcore#24806] opened 2020-08-11 19:56 UTC
Using Microsoft Visual Studio Enterprise 2019 Preview - Version 16.8.0 Preview 1.0

Create a new Blazor WebAssembly App 
Open "FetchData.razor" ( **Important! otherwise no crash**)
Rename to "MyFetchData.razor"

Confirm the rename dialog :
![image](https://user-images.githubusercontent.com/8482283/89942464-e5c04700-dc1c-11ea-9eff-57759e02d4bf.png)

VS Studio Crash:

![image](https://user-images.githubusercontent.com/8482283/89942498-f96bad80-dc1c-11ea-8648-9e5201441178.png)

Stack Trace:

```
StreamJsonRpc.RemoteInvocationException : Unexpected false
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
---> (Remote Exception) {
  "type": "System.InvalidOperationException",
  "message": "Unexpected false",
  "stack": "   at Roslyn.Utilities.Contract.Fail(String message)\r\n   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateDocumentInfoAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateDocumentAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateDocumentsAsync>d__11.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectsAsync>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<UpdateProjectsAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionCreator.<CreateSolutionAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionService.<CreateSolution_NoLockAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.SolutionService.<GetSolutionAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.<>c__DisplayClass31_0.<<RenameSymbolAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.ServiceBase.<RunServiceAsync>d__15`1.MoveNext()",
  "code": -2146233079,
  "inner": null
} <--- 
```

**Comment by TanayParikh** [comment] 2020-08-14 17:55
Thanks for reporting this issue, I'm seeing it as well. 

For an immediate resolution, the new Razor experimental editor doesn't face this and is available here:
https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/

To enable the new experimental Razor editor in Visual Studio 2019 16.7 Preview 4 or later:

1. Install the latest Visual Studio preview
2. Go to Tools > Options > Environment > Preview Features and select the Enable experimental Razor editor option:
![image](https://user-images.githubusercontent.com/14852843/90278609-7d3fb880-de1c-11ea-86b3-b9174b2b664a.png)

3. Select OK and restart Visual Studio

**Comment by NTaylorMullen** [comment] 2020-08-17 22:19
Duplicate of https://github.com/dotnet/roslyn/issues/46580

**Closed by NTaylorMullen** 2020-08-17 22:19 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, bug
