### ISSUE TITLE
Deprecate MaxResponseBufferSize and MaxRequestBufferSize

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#12222] opened 2019-07-16 04:58 UTC
These settings have been moved to the transport and should be deprecated as they are no longer read by the server.

cc @anurse @halter73 @jkotalik

**Comment by anurse** [comment] 2019-07-16 22:10
We'll put `[Obsolete]` on them for now.

As part of doing this work, please open a new issue in the Backlog to *remove* the properties completely.

**Comment by anurse** [comment] 2019-07-16 23:41
> These settings have been moved to the transport and should be deprecated as they are no longer read by the server.

You sure about that? I see some places still reading the value on `KestrelServerLimits`:

* [Http2Connection does so when calling `TimeoutControl.StartDrainTimeout`](https://github.com/aspnet/AspNetCore/blob/6c80c425114e81b1976f7680f272228c5ebe3adc/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs#L292)
* [as does Http1Connection](https://github.com/aspnet/AspNetCore/blob/6c80c425114e81b1976f7680f272228c5ebe3adc/src/Servers/Kestrel/Core/src/Internal/Http/Http1Connection.cs#L71)

**Comment by davidfowl** [comment] 2019-07-16 23:57
Ah hmm

**Comment by halter73** [comment] 2019-07-17 01:42
That's tricky. Today, if you increase your MaxResponseBufferSize, we increase you're drain timeout, because the time between the server observing the completion of PipeWriter.FlushAsync() and the transport actually flushing the data could take longer the larger the MaxResponseBufferSize even though the client is reading at the same rate.

The problem is that the default MaxRequestBufferSize is so large (64KB) and the default MinResponseDataRate is so small (240 bytes/second) that the default drain timeout winds up being about 267 seconds which is nearly 5 minutes. That said, to enforce a smaller drain timeout would either mean reducing the MaxRequestBufferSize, counting the actual number of undrained bytes, requiring the client read at a faster-than-normally-required-rate at the end of a connection, or enforcing the rate limit on the transport side of the pipe.

Each of these solutions has problems.
1. A smaller MaxRequestBufferSize would likely reduce performance in some scenarios as this is reducing the size of the write-behind-buffer.
2. Counting the actual number of undrained bytes becomes tricky when there can be multiple levels of connection middleware which can be running the output through things like SslStream which changes the number of bytes the server thinks it wrote vs the number of bytes the transport actually wrote.
3. Requiring the client to read faster than it normally has to at the end of the connection also seems user hostile to me. If I configure Kestrel so that clients only need to read at a minimum of 240 bytes/second, clients should not have to read faster at the end of the connection in order to avoid a truncated response.
4. Enforcing rate limits on the transport side of the pipe seems like the most reasonable option. The real problem here is that we already support the IHttpMinResponseDataRateFeature and the IHttpMinRequestBodyDataRateFeature as ways to change the rate limit on a per-response/request basis, and the transports do not know which bytes belong to which response/request.

I think one solution is to make "ConnectionDrainTimeout" a configurable TimeSpan on KestrelServerLimits that defaults to 5 minutes which is pretty close to what it is today for the default configuration. If we do that, we should add docs to our response rate APIs to indicate that if you increase or decrease the min response rate, you should probably make a corresponding change to the ConnectionDrainTimeout.

**Comment by halter73** [comment] 2019-07-17 02:39
This highlights a bug that is introduced by moving the MaxResponseBufferSize to the transport options. Now, even if the client reads continuously above the minimum data rate it can still see truncated responses due to a drain timeout. Less importantly, the drain timeout is not as aggressive as it could be when the buffer size is reduced.

There should already be tests for this, but they would modify the MaxResponseBufferSize on KestrelServerOptions, not the transport options, so they wouldn't catch the regression.

**Comment by anurse** [comment] 2019-07-22 16:04
> This highlights a bug that is introduced by moving the MaxResponseBufferSize to the transport options.

Is this something we should consider critical for 3.0? If so, can you file a bug with some notes and we can triage. It'll probably have to land in preview 9 but if it's important, we can definitely get it through ask mode.

**Comment by anurse** [comment] 2019-07-26 20:53
We'll investigate this in preview9 but if the issue isn't high impact it'll probably bounce to 3.1

**Comment by halter73** [comment] 2019-07-26 21:20
> Is this something we should consider critical for 3.0?

Sorry for the late reply on this. I don't think it's critical. It's true that the drain timeout doesn't properly adjust with the MaxResponseBufferSize now, but that's rarely configured, and even if it is at least there's sill *a* drain timeout.

**Comment by anurse** [comment] 2019-07-30 22:23
I'll create a new issue for @halter73 's bug. Moving this to 5.0 since it's a breaking change proposal and we're too late for 3.0

**Comment by halter73** [comment] 2020-05-11 21:48
> I think one solution is to make "ConnectionDrainTimeout" a configurable TimeSpan

Having a connection feature that exposes the MaxResponseBufferSize might be a better solution.

**Closed** 2021-03-23 15:49 UTC
Labels: affected-very-few, area-servers, enhancement, severity-nice-to-have
