### ISSUE TITLE
"dotnet watch" Hot Reload doesn't work if passing arguments

### ISSUE THREAD

**Issue by ionoy** [dotnet/aspnetcore#39572] opened 2022-01-17 08:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running 'dotnet watch' with any arguments, like `dotnet watch run --urls https://localhost:5123 -v` disables hot reload for some reason. 
Here is the first line of debug output: 
`watch : Did not find a HotReloadProfile or running a non-default command. Watching with legacy behavior.`

When running the same command without any additional arguments (`dotnet watch run -v`), hot reload is enabled

`watch : Project supports hot reload and was configured to run with the default run-command. Watching with hot-reload`

I couldn't find any documentation describing this behaviour

### Steps To Reproduce

* Create a default Blazor Server app
* Run it with the following command `dotnet watch run --urls https://localhost:5123 -v`
* You should see `watch : Did not find a HotReloadProfile or running a non-default command. Watching with legacy behavior.`

### .NET Version

6.0.101

**Comment by majorimi** [comment] 2022-01-18 08:46
Yes I have exactly the same issue. In my case I **need to host a Blazor application as a "Child site"**. Which is possible with Blazor in `Startup.cs` needed to setup the child site path: `app.UsePathBase("/test");`

And `dotnet watch` also needs to know about this child path by passing argument: `dotnet watch run --pathbase=/test`. You can test it with your default Blazor Server project template also. Very simple to break Hot reload only add 1 line above call `watch` with args and Hot reload gone... Basically `watch` falling back to a "Cold Reload" which is taking much longer.

**@mkArtakMSFT @SteveSandersonMS Is there a quick solution for this please?** Since I'm convincing a client to use Blazor in favour of Angular, etc. Since latest .NET 6 is bringing all the goodness (e.g. super fast Dev cycle with Hot Reload) what JS based frameworks already have. And in my case this kind of annoying issues causing problems and other collegues loosing trust in Blazor forcing back to Angular etc...

Thanks.

**Comment by SteveSandersonMS** [comment] 2022-01-18 10:55
@pranavkm Do you know if there are intentional reasons for disabling hot reload when other CLI parameters are given, or a workaround?

**Comment by pranavkm** [comment] 2022-01-18 14:54
We would have to understand what some of these parameters mean and use them accordingly e.g. we'd have to know which ones are MSBuild parameters, or ones like `-c`, `--framework` etc so that they can be used when setting up the Roslyn workspace. It seemed tenuous to have to bake in dotnet-run's CLI parsing in to watch, so the current implementation falls back back to legacy watching. That said, this is a reasonable request. Also a dupe of https://github.com/dotnet/aspnetcore/issues/31365 so I'll close this issue.

**Closed by pranavkm** 2022-01-18 14:54 UTC
Labels: area-commandlinetools, feature-dotnetwatch
