### ISSUE TITLE
Source code build Issue

### ISSUE THREAD

**Issue by fadelsahmarani** [dotnet/aspnetcore#46285] opened 2023-01-27 10:48 UTC
- Operating system: Windows 11 Pro
- Visual studio: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.4.4 
- Node version: v18.13.0  for v7.0.2 and v19.4.0 for latest main branch (On both build failed)
- yarn version : 3.3.1
- npm version: 8.19.3

After following all the steps and running powershell **.\restore.cmd** following error appears :

D:\Workspace\OpenSource\aspnetcore\eng\targets\Npm.Common.targets(45,5): error : ..\..\..\..\package.json: No license f
ield [D:\Workspace\OpenSource\aspnetcore\src\Components\Web.JS\Microsoft.AspNetCore.Components.Web.JS.npmproj]
D:\Workspace\OpenSource\aspnetcore\eng\targets\Npm.Common.targets(45,5): error : ..\..\..\..\..\package.json: No licens
e field [D:\Workspace\OpenSource\aspnetcore\src\SignalR\clients\ts\client-ts.npmproj]
D:\Workspace\OpenSource\aspnetcore\eng\targets\Npm.Common.targets(45,5): error : ..\..\..\..\..\..\package.json: No lic
ense field [D:\Workspace\OpenSource\aspnetcore\src\SignalR\clients\ts\common\common.npmproj]
D:\Workspace\OpenSource\aspnetcore\eng\targets\Npm.Common.targets(45,5): error : ..\..\..\..\..\..\package.json: No lic
ense field [D:\Workspace\OpenSource\aspnetcore\src\SignalR\clients\ts\FunctionalTests\SignalR.Npm.FunctionalTests.npmpr
oj]
D:\Workspace\OpenSource\aspnetcore\eng\targets\Npm.Common.targets(45,5): error : ..\..\..\..\..\..\package.json: No lic
ense field [D:\Workspace\OpenSource\aspnetcore\src\SignalR\clients\ts\signalr-protocol-msgpack\signalr-protocol-msgpack
.npmproj]
D:\Workspace\OpenSource\aspnetcore\eng\targets\Npm.Common.targets(45,5): error : ..\..\..\..\..\..\package.json: No lic
ense field [D:\Workspace\OpenSource\aspnetcore\src\SignalR\clients\ts\signalr\signalr.npmproj]
D:\Workspace\OpenSource\aspnetcore\eng\targets\Npm.Common.targets(45,5): error : ..\..\..\..\..\package.json: No licens
e field [D:\Workspace\OpenSource\aspnetcore\src\JSInterop\Microsoft.JSInterop.JS\src\Microsoft.JSInterop.JS.npmproj]

**Comment by wtgodbe** [comment] 2023-01-31 19:10
This may be an issue with the newer version of Yarn, could you try it with 1.22? That's what we use in this repo

**Comment by fadelsahmarani** [comment] 2023-02-02 11:28
Same error when changing to Yarn 1.22

![image](https://user-images.githubusercontent.com/41676532/216312383-8ab103c1-0b7e-49c6-8359-f58adb9bc8f8.png)

**Comment by wtgodbe** [comment] 2023-02-07 23:14
Given that our devs do not see the same issue, nor does it reproduce in CI, I'm going to close this as it seems to be something specific to your setup. Having said that, the only notable difference I see is that we install node version 16.19 for our builds - using that instead of 18/19 could solve your problem.

**Closed by wtgodbe** 2023-02-07 23:14 UTC
Labels: question, area-infrastructure
