### ISSUE TITLE
Indentation in new Web API project

### ISSUE THREAD

**Issue by eslamisepehr** [dotnet/aspnetcore#40401] opened 2022-02-24 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello :wave:
I've created a new **ASP.NET Core Web API** project on Visual Studio 2022 .NET 6, and I saw that indentation is not observed.

![image](https://user-images.githubusercontent.com/13395542/155615871-7e66bcd2-bcaa-4954-a9cc-3eac68b1a7fc.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/13395542/155615962-4303aeaa-80d9-4eb1-8aa3-e138ee74f0cb.png)

### .NET Version

6

### Anything else?

Visual Studio 2022

**Comment by TanayParikh** [comment] 2022-02-24 22:24
Hmm, this seems odd, the templates look like they have the correct spacing:

https://github.com/dotnet/aspnetcore/blob/release/6.0/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/WeatherForecastController.cs#L30-L33

**Comment by TanayParikh** [comment] 2022-02-24 22:26
Confirmed the behavior:

![image](https://user-images.githubusercontent.com/14852843/155617821-e80a3f03-ef38-44ca-84f8-2220b8cb6de7.png)

Thanks @eslamisepehr!

**Comment by TanayParikh** [comment] 2022-02-24 22:29
Okay there's a divergence somewhere. The release/6.0 template is using a file scoped namespace:

https://github.com/dotnet/aspnetcore/blob/release/6.0/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/WeatherForecastController.cs#L18

However, the new project I got in VS (screenshot above) doesn't use file scoped namespaces. Is this a versioning thing, do we need to reship the templates somehow? @pranavkm

**Comment by javiercn** [comment] 2022-02-25 10:20
@phenning is there some VS magic going on here?

**Comment by phenning** [comment] 2022-02-25 13:48
@javiercn I think there are two things going on here:

1. VS has a code fixer that is trying to convert to block scope. This is set to block-scoped by default. If I switch this setting to file scoped, then create a WebAPI project, everything is as expected.

![image](https://user-images.githubusercontent.com/2433750/155725093-2e0bfb5f-80e4-4ae3-934a-ad5779d9cf15.png)

Additionally, if you notice when the project gets created as it is shown in the repro, you would expect CTRL-K CTRL-D to align the braces, but I believe this isn't happening due to https://github.com/dotnet/roslyn/issues/9702

**Comment by javiercn** [comment] 2022-02-25 14:43
@phenning I see, thanks for the additional details.

Does the template engine automatically run the code fixers when it creates the project for the first time? Meaning this is a combination of VS running the code fixers + the issue you point out?

**Comment by phenning** [comment] 2022-02-25 14:49
Essentially, yes. 

Although, the template engine doesn't explicitly run the fixer.  It gets run automatically when the project gets added to the solution or an item gets added to a project.

When the fixer reformats the .cs file to change from file scope to block scope all the braces to get realigned except for the one on the array initializer.

**Comment by javiercn** [comment] 2022-02-25 14:54
@phenning thanks again for the clarification.

I guess then this will be addressed when the underlying Roslyn issue is addressed? Is that issue this one? https://github.com/dotnet/roslyn/issues/9702

**Comment by phenning** [comment] 2022-02-25 15:00
There are actually several issues in the roslyn repo that are related, including about introducing a setting for the array initializer behavior on https://github.com/dotnet/roslyn/issues/779 and https://github.com/dotnet/roslyn/issues/8269.

**Comment by TanayParikh** [comment] 2022-02-25 18:23
Thanks for the details Phil. I'm closing this issue out as external / dup of : https://github.com/dotnet/roslyn/issues/9702 / https://github.com/dotnet/roslyn/issues/779 / https://github.com/dotnet/roslyn/issues/8269

**Closed by TanayParikh** 2022-02-25 18:23 UTC
Labels: External, area-blazor, feature-templates

**Comment by pranavkm** [comment] 2022-02-25 18:31
Just to confirm - is the current state that our templates default to using block scoped namespaces even though we (mostly @DamianEdwards) did a bunch of work to use file scoped ones? I tried my local VS and it had namespace declarations defaulted to block scope.

**Comment by phenning** [comment] 2022-02-25 18:39
Correct, the behavior is designed to be based on that setting or through .editorconfig 

There were threads about this back in August, and as recently as last week.
