### ISSUE TITLE
Static web assets not being included with NuGet package

### ISSUE THREAD

**Issue by stsrki** [dotnet/aspnetcore#36847] opened 2021-09-22 16:59 UTC
The original issue is reported here https://github.com/Megabit/Blazorise/issues/2958

Basically, we are targeting both .Net 5 and .Net 6 with the Blazorise library. The problem occurs after we upgraded to the latest version of VS2022 and .Net 6 RC1. When we run `dotnet pack` command on any project it will not include `staticwebassets` in the final NuGet package. After further investigation, I have discovered that it might work BUT only the first time `dotnet pack` is executed. If you try to run `dotnet pack` after the first operation has ended, it will not include the `staticwebassets` folder.

I have created a simple project to reproduce the issue: https://github.com/stsrki/BlazorSWANuget

Once you clone it, navigate into the NuGet subfolder and do the following

1. `$ dotnet-pack.bat`
2. open `BlazorSWANuget.1.0.0.nupkg` and confirm you see the `staticwebassets` folder
3. now run `$ dotnet-pack.bat` again
4. open `BlazorSWANuget.1.0.0.nupkg` and you can see that `staticwebassets` folder is not included this time

**Comment by Pilchie** [comment] 2021-09-22 18:04
@javiercn ?

**Comment by javiercn** [comment] 2021-09-23 08:43
@stsrki thanks for contacting us.

This was fixed in RC2

```console
Archive:  /home/jacalvar/work/repros/BlazorSWANuget/BlazorSWANuget/bin/Debug/BlazorSWANuget.1.0.0.nupkg
  Length      Date    Time    Name
---------  ---------- -----   ----
      504  2021-09-23 01:41   _rels/.rels
      662  2021-09-23 01:41   BlazorSWANuget.nuspec
     7680  2021-09-23 08:41   lib/net5.0/BlazorSWANuget.dll
     7680  2021-09-23 08:41   lib/net6.0/BlazorSWANuget.dll
     2834  2021-09-23 08:41   build/Microsoft.AspNetCore.StaticWebAssets.props
       89  2021-09-23 08:41   build/BlazorSWANuget.props
       76  2021-09-23 08:41   buildMultiTargeting/BlazorSWANuget.props
       90  2021-09-23 08:41   buildTransitive/BlazorSWANuget.props
      213  2021-09-23 08:41   staticwebassets/BlazorSWANuget.bundle.scp.css
      378  2021-09-23 08:40   staticwebassets/background.png
      241  2021-09-23 08:40   staticwebassets/exampleJsInterop.js
      708  2021-09-23 01:41   [Content_Types].xml
      617  2021-09-23 01:41   package/services/metadata/core-properties/7cdd81d62f83447b96bc0937a2c626b0.psmdcp
---------                     -------
    21772                     13 files
```

**Comment by javiercn** [comment] 2021-09-23 08:44
@stsrki can you try the latest RC2 build and let us know if you still run into problems?

**Comment by stsrki** [comment] 2021-09-23 08:45
@javiercn This was tested with RC2 night build installed.

**Comment by stsrki** [comment] 2021-09-23 08:46
Version 6.0.100-rc.2.21471.21

**Comment by javiercn** [comment] 2021-09-23 10:17
@stsrki I literally cloned your repo and run `dotnet pack` with 6.0.100-rc.2.21472.55

**Comment by javiercn** [comment] 2021-09-23 10:22
@stsrki for us to make progress we need a binlog of the build producing the wrong package (use an SDK with the version I provided or higher) since I'm not able to reproduce the issue locally

**Comment by stsrki** [comment] 2021-09-23 10:29
I have now installed `6.0.100-rc.2.21472.55` and tried again. and it is still not working for me. It only works if I clean `bin/obj` prior to running `dotnet pack`.

**My clean.bat**

```
@ECHO off
cls

ECHO Deleting all BIN and OBJ folders...
ECHO.

FOR /d /r . %%d in (bin,obj) DO (
	IF EXIST "%%d" (		 	 
		ECHO %%d | FIND /I "\node_modules\" > Nul && ( 
			ECHO.Skipping: %%d
		) || (
			ECHO.Deleting: %%d
			rd /s/q "%%d"
		)
	)
)

ECHO.
ECHO.BIN and OBJ folders have been successfully deleted. Press any key to exit.
```

**Comment by stsrki** [comment] 2021-09-23 10:33
Can this help you?

```
Microsoft (R) Build Engine version 17.0.0-preview-21470-01+cb055d28f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 23.9.2021. 12:32:38.
     1>Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" on node 1 (Restore target(s)).
     1>_GetAllRestoreProjectPathItems:
         Determining projects to restore...
       Restore:
         Restoring packages for D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj...
         Committing restore...
         Assets file has not changed. Skipping assets file writing. Path: D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\project.assets.json
         Restored D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj (in 141 ms).

         NuGet Config files used:
             C:\Users\Mladen\AppData\Roaming\NuGet\NuGet.Config
             C:\Program Files (x86)\NuGet\Config\DevExpress 19.2.config
             C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

         Feeds used:
             https://api.nuget.org/v3/index.json
             C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
             https://nuget.devexpress.com/qfQbKbQxjPikSWRCMPLF2ySBkizTt1JUu5wCtCWWxliAhNYENh/api
             C:\Program Files (x86)\DevExpress 19.2\Components\System\Components\Packages
             https://www.myget.org/F/blazorise/api/v3/index.json
     1>Done Building Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (Restore target(s)).
  1:15>Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" on node 1 (pack target(s)).
  1:15>Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:15) is building "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:16) on node 2 (Build target(s)).
     1>_CheckForNETCoreSdkIsPreview:
         You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
       ResolveProjectStaticWebAssets:
         Rejected asset 'Component1.razor' for pattern 'wwwroot/**'
         Rejected asset '_Imports.razor' for pattern 'wwwroot/**'
         Accepted asset 'wwwroot\background.png' for pattern 'wwwroot/**' with relative path 'background.png'
         Accepted asset 'wwwroot\exampleJsInterop.js' for pattern 'wwwroot/**' with relative path 'exampleJsInterop.js'
       _ResolveJsModuleInputs:
         RelativePath 'background.png' normalized to 'background.png' found for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\wwwroot\background.png' and will be used for matching.
         Skipping 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\wwwroot\background.png' becasue the relative path 'background.png' did not match the filter '**/BlazorSWANuget.lib.module.js'.
         RelativePath 'exampleJsInterop.js' normalized to 'exampleJsInterop.js' found for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\wwwroot\exampleJsInterop.js' and will be used for matching.
         Skipping 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\wwwroot\exampleJsInterop.js' becasue the relative path 'exampleJsInterop.js' did not match the filter '**/BlazorSWANuget.lib.module.js'.
         Rejected asset 'Component1.razor' for pattern '**/*.razor.js'
         Rejected asset '_Imports.razor' for pattern '**/*.razor.js'
         Rejected asset 'wwwroot\background.png' for pattern '**/*.razor.js'
         Rejected asset 'wwwroot\exampleJsInterop.js' for pattern '**/*.razor.js'
         Rejected asset 'Component1.razor.css' for pattern '**/*.razor.js'
         Rejected asset 'Component1.razor' for pattern '**/*.cshtml.js'
         Rejected asset '_Imports.razor' for pattern '**/*.cshtml.js'
         Rejected asset 'wwwroot\background.png' for pattern '**/*.cshtml.js'
         Rejected asset 'wwwroot\exampleJsInterop.js' for pattern '**/*.cshtml.js'
         Rejected asset 'Component1.razor.css' for pattern '**/*.cshtml.js'
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreGenerateAssemblyInfo:
       Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
       CoreCompile:
       Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
       _ComputeScopedCssStaticWebAssets:
         RelativePath 'Component1.razor.rz.scp.css' normalized to 'Component1.razor.rz.scp.css' found for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\Component1.razor.rz.scp.css' and will be used for matching.
         Identity for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\Component1.razor.rz.scp.css' is 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\Component1.razor.rz.scp.css' because it starts with content root 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\'.
       _AddScopedCssBundles:
         RelativePath 'BlazorSWANuget.styles.css' normalized to 'BlazorSWANuget.styles.css' found for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\bundle\BlazorSWANuget.styles.css' and will be used for matching.
         Identity for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\bundle\BlazorSWANuget.styles.css' is 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\bundle\BlazorSWANuget.styles.css' because it starts with content root 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\bundle\'.
         RelativePath 'BlazorSWANuget.bundle.scp.css' normalized to 'BlazorSWANuget.bundle.scp.css' found for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\projectbundle\BlazorSWANuget.bundle.scp.css' and will be used for matching.
         Identity for candidate 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\projectbundle\BlazorSWANuget.bundle.scp.css' is 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\projectbundle\BlazorSWANuget.bundle.scp.css' because it starts with content root 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\projectbundle\'.
       GenerateStaticWebAssetsManifest:
         Skipping manifest updated because manifest version 'qvki4J/hdSG11trLlmM30I+W2AWpycH+YxwtE3iJbnk=' has not changed.
         "Skipping candidate asset '{0}' because asset mode is '{2}'"
         System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
            at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
            at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
            at System.String.Format(IFormatProvider provider, String format, Object[] args)
            at Microsoft.Build.Framework.LazyFormattedBuildEventArgs.FormatString(CultureInfo culture, String unformatted, Object[] args)
         Skipping manifest updated because manifest version '2IdQP/MpXnEvpiCTAV3W7w9enwjqH6ACnHRszYYFn68=' has not changed.
       _GenerateScopedCssFiles:
       Skipping target "_GenerateScopedCssFiles" because all output files are up-to-date with respect to the input files.
       _SplitStaticWebAssetsByCopyOptions:
         Skipping asset 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\bundle\BlazorSWANuget.styles.css' since copy to output directory option is 'Never'
         Skipping asset 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\projectbundle\BlazorSWANuget.bundle.scp.css' since asset mode is 'Reference'
         Skipping asset 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\obj\Release\net6.0\scopedcss\projectbundle\BlazorSWANuget.bundle.scp.css' since copy to output directory option is 'Never'
         Skipping asset 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\wwwroot\background.png' since copy to output directory option is 'Never'
         Skipping asset 'D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\wwwroot\exampleJsInterop.js' since copy to output directory option is 'Never'
       _BuildCopyStaticWebAssetsPreserveNewest:
       Skipping target "_BuildCopyStaticWebAssetsPreserveNewest" because it has no outputs.
  1:15>Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:15) is building "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:17) on node 1 (Build target(s)).
     1>_CheckForNETCoreSdkIsPreview:
         You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
     1>_CopyOutOfDateSourceItemsToOutputDirectory:
       Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.
       GenerateBuildDependencyFile:
       Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
       CopyFilesToOutputDirectory:
         BlazorSWANuget -> D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\bin\Release\net6.0\BlazorSWANuget.dll
     1>Done Building Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (Build target(s)).
     1>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreGenerateAssemblyInfo:
       Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
       RazorGenerateComponentDeclaration:
       Skipping target "RazorGenerateComponentDeclaration" because all output files are up-to-date with respect to the input files.
       RazorCompileComponentDeclaration:
       Skipping target "RazorCompileComponentDeclaration" because all output files are up-to-date with respect to the input files.
       ResolveTagHelperRazorGenerateInputs:
       Skipping target "ResolveTagHelperRazorGenerateInputs" because all output files are up-to-date with respect to the input files.
       RazorCoreGenerate:
       Skipping target "RazorCoreGenerate" because all output files are up-to-date with respect to the input files.
       CoreCompile:
       Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
       _GenerateScopedCssFiles:
       Skipping target "_GenerateScopedCssFiles" because all output files are up-to-date with respect to the input files.
       GenerateStaticWebAssetsManifest:
       Skipping target "GenerateStaticWebAssetsManifest" because all output files are up-to-date with respect to the input files.
       _CopyOutOfDateSourceItemsToOutputDirectory:
       Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.
       GenerateBuildDependencyFile:
       Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
       CopyFilesToOutputDirectory:
         BlazorSWANuget -> D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\bin\Release\net5.0\BlazorSWANuget.dll
     1>Done Building Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (Build target(s)).
  1:15>Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:15) is building "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:20) on node 1 (_GetTfmSpecificContentForPackage target(s)).
     1>GenerateStaticWebAssetsPackTargets:
       Skipping target "GenerateStaticWebAssetsPackTargets" because all output files are up-to-date with respect to the input files.
     1>Done Building Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (_GetTfmSpecificContentForPackage target(s)).
  1:15>Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:15) is building "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (1:21) on node 2 (_GetTfmSpecificContentForPackage target(s)).
     1>GenerateStaticWebAssetsPackTargets:
       Skipping target "GenerateStaticWebAssetsPackTargets" because all output files are up-to-date with respect to the input files.
     1>Done Building Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (_GetTfmSpecificContentForPackage target(s)).
     1>GenerateNuspec:
         Successfully created package 'D:\Projects\Issues\BlazorSWANuget\NuGet\BlazorSWANuget.1.0.0.nupkg'.

         Attempting to build symbols package for 'BlazorSWANuget.csproj'.
         Successfully created package 'D:\Projects\Issues\BlazorSWANuget\NuGet\BlazorSWANuget.1.0.0.snupkg'.
     1>Done Building Project "D:\Projects\Issues\BlazorSWANuget\BlazorSWANuget\BlazorSWANuget.csproj" (pack target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.33
```

**Comment by javiercn** [comment] 2021-09-23 10:34
@stsrki `dotnet pack /bl` is what we need

**Comment by stsrki** [comment] 2021-09-23 10:40
@javiercn sorry, never used binlog :)

Is this OK now?

[msbuild.binlog.zip](https://github.com/dotnet/aspnetcore/files/7216922/msbuild.binlog.zip)

**Comment by javiercn** [comment] 2021-09-23 10:51
@stsrki thanks for the additional details.

This seems to be some sort of incrementalism issue we are running into with multi-targeting package. It seems we still have some issues after the fixes we applied in this area.

I'll file a separate issue and see if this meets the bar for 6.0. In the meantime, I would suggest you clean the folder before packing if that works around it.

![image](https://user-images.githubusercontent.com/6995051/134494586-b1a6e207-caf7-4b2d-b66e-df34ea70ccac.png)

**Comment by stsrki** [comment] 2021-09-23 10:55
Yes, cleaning folders before packing works and I can use it as a workaround. But I think other people would have a similar problem and they would have to figure it for themself. So if you could make it work that would be great.

Also, thanks for the tip regarding the https://msbuildlog.com/

**Comment by SteveSandersonMS** [comment] 2021-09-23 16:47
@javiercn Should we close this issue in favour of the other one about multitargeting that you are going to file?

**Closed** 2021-09-29 10:28 UTC
Labels: Needs: Author Feedback, area-mvc, blazor-wasm, Status: No Recent Activity, feature-static-web-assets
