### ISSUE TITLE
Allow to re-connect even in case of session has already deleted on server (create a new one)

### ISSUE THREAD

**Issue by danieldegtyarev** [dotnet/aspnetcore#52733] opened 2023-12-11 17:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Now it is the most annoing behavior. For example, you are returned to the tab in your browser and what you see is "connection lost" message.

### Describe the solution you'd like

I would like to have an API in javscript to be able reconnect with a new session creation. The page will refreshed seamlessly, similar to connect after pre-rendering (user will not loose the context on page, no white screen, etc.)

**Comment by javiercn** [comment] 2023-12-11 18:28
@danieldegtyarev thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/30344

**Closed by javiercn** 2023-12-11 18:28 UTC
Labels: area-blazor
