### ISSUE TITLE
SignalR Json error, seems to cut serialized object (from net core 3.2 to net 5.0)

### ISSUE THREAD

**Issue by KevinValmo** [dotnet/aspnetcore#27774] opened 2020-11-12 15:09 UTC
Hello,

i'm having an error upgrading to .net 5.0 from .net core 3.2.

When i was using net core 3.2 this exception was not being thrown.

The code i wrote is simple: 
I added in the Index.razor a number of component i created and each one make a call to the hub with the `InvokeAsync` Method.

`await Hub.InvokeAsync<TagValue>("SubscribeComponentTag", tagName)`

```
    <CircleLed TagName="a" Size="50"></CircleLed>
    <CircleLed TagName="b" Size="50"></CircleLed>
    <CircleLed TagName="c" Size="50"></CircleLed>
    <CircleLed TagName="d" Size="50"></CircleLed>
    <CircleLed TagName="e" Size="50"></CircleLed>
    <CircleLed TagName="f" Size="50"></CircleLed>
    <CircleLed TagName="g" Size="50"></CircleLed>
    <CircleLed TagName="h" Size="50"></CircleLed>
    <CircleLed TagName="i" Size="50"></CircleLed>
    <CircleLed TagName="l" Size="50"></CircleLed>
    <CircleLed TagName="m" Size="50"></CircleLed>
    <CircleLed TagName="n" Size="50"></CircleLed>
    <CircleLed TagName="o" Size="50"></CircleLed>
    <CircleLed TagName="p" Size="50"></CircleLed>
    <CircleLed TagName="q" Size="50"></CircleLed>
    <CircleLed TagName="r" Size="50"></CircleLed>
    <CircleLed TagName="s" Size="50"></CircleLed>
    <CircleLed TagName="t" Size="50"></CircleLed>
    <CircleLed TagName="u" Size="50"></CircleLed>
    <CircleLed TagName="v" Size="50"></CircleLed>
    <CircleLed TagName="z" Size="50"></CircleLed>
    <CircleLed TagName="aa" Size="50"></CircleLed>
    <CircleLed TagName="bb" Size="50"></CircleLed>
    <CircleLed TagName="cc" Size="50"></CircleLed>
    <CircleLed TagName="ee" Size="50"></CircleLed>
    <CircleLed TagName="ff" Size="50"></CircleLed>
    <CircleLed TagName="gg" Size="50"></CircleLed>
    <CircleLed TagName="hh" Size="50"></CircleLed>
    <CircleLed TagName="ii" Size="50"></CircleLed>
    <CircleLed TagName="ee" Size="50"></CircleLed>
    <CircleLed TagName="ll" Size="50"></CircleLed>
    <CircleLed TagName="mm" Size="50"></CircleLed>
    <CircleLed TagName="nn" Size="50"></CircleLed>
    <CircleLed TagName="oo" Size="50"></CircleLed>
    <CircleLed TagName="pp" Size="50"></CircleLed>
    <CircleLed TagName="rr" Size="50"></CircleLed>
    <CircleLed TagName="ss" Size="50"></CircleLed>
    <CircleLed TagName="tt" Size="50"></CircleLed>
    <CircleLed TagName="uu" Size="50"></CircleLed>
    <CircleLed TagName="vv" Size="50"></CircleLed>
    <CircleLed TagName="zz" Size="50"></CircleLed>
    <CircleLed TagName="aaa" Size="50"></CircleLed>
    <CircleLed TagName="bbb" Size="50"></CircleLed>
    <CircleLed TagName="ccc" Size="50"></CircleLed>
    <CircleLed TagName="eed" Size="50"></CircleLed>
    <CircleLed TagName="ffe" Size="50"></CircleLed>
    <CircleLed TagName="ggf" Size="50"></CircleLed>
    <CircleLed TagName="hhg" Size="50"></CircleLed>
    <CircleLed TagName="iih" Size="50"></CircleLed>
    <CircleLed TagName="eei" Size="50"></CircleLed>
```

**(Open images in other tab if you can't read)**

Error in ASP.net Core server Kestrel Console (this is happening even in IIS Expess) in .net 5.0
![image](https://user-images.githubusercontent.com/55260200/98954642-49992b00-24fe-11eb-80b7-8d69124a1715.png)

Error in Browser (Chrome) using Blazor WebAssembly in .net 5.0
![image](https://user-images.githubusercontent.com/55260200/98955071-c7f5cd00-24fe-11eb-9b3a-fa91b6b5447e.png)

SignalR request:
![image](https://user-images.githubusercontent.com/55260200/98955423-2458ec80-24ff-11eb-93be-d413677b6bb4.png)

In the below image you can see the JSON is wrong becouse it start with a "]"
![image](https://user-images.githubusercontent.com/55260200/98955544-4d797d00-24ff-11eb-873d-8ba8ec7f6c24.png)
![image](https://user-images.githubusercontent.com/55260200/98956145-fb852700-24ff-11eb-8694-bdea430b4840.png)

### Exceptions
```
System.IO.InvalidDataException: Error reading JSON.
 ---> System.Text.Json.JsonReaderException: ']' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.CheckRead(Utf8JsonReader& reader)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.TryParseMessage(ReadOnlySequence`1& input, IInvocationBinder binder, HubMessage& message)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```

### Further technical details
```
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.0" />
    <PackageReference Include="Microsoft.JSInterop" Version="5.0.0" />
```

**Comment by BrennanConroy** [comment] 2020-11-12 17:02
Dupe of https://github.com/dotnet/runtime/issues/44551. You should be able to workaround it by switching to LongPolling for now.

**Closed** 2020-11-16 22:13 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr

**Comment by KevinValmo** [comment] 2020-11-16 22:36
> Dupe of [dotnet/runtime#44551](https://github.com/dotnet/runtime/issues/44551). You should be able to workaround it by switching to LongPolling for now.

Ok. Workaround done! 🤞
