### ISSUE TITLE
Feature request: reliable way to send SignalR messages on shutdown

### ISSUE THREAD

**Issue by kjkrum** [dotnet/aspnetcore#13266] opened 2019-08-19 23:25 UTC
My web app runs background tasks that prevent IIS from gracefully shutting down until they complete. (This works well; code [here](https://github.com/aspnet/Extensions/issues/805#issuecomment-515129687).) The tasks poll `IApplicationLifetime.ApplicationStopping.IsCancellationRequested` in their innermost loops and try to send cancellation messages to SignalR clients when shutdown is detected. But SignalR has usually disconnected the clients before the tasks get a chance to notify them.

I don't know enough about the framework to suggest a solution.

**Comment by halter73** [comment] 2019-08-20 21:10
The problem seems to be that SignalR starts closing the connection as soon as ApplicationStopping fires. It might be interesting to have something like BeforeApplicationStopping that could be "blocked" with a task for users to send messages to clients. @Tratcher

**Comment by Tratcher** [comment] 2019-08-20 23:26
BeforeBeforeBefore* 😁 That way lies madness.

Hmm, StopApplication is the very first signal from Host.StopAsync.
https://github.com/aspnet/Extensions/blob/7005708d7a26e5f6ed4bcb0271f052241033b8a6/src/Hosting/Hosting/src/Internal/Host.cs#L62-L71

> The problem seems to be that SignalR starts closing the connection as soon as ApplicationStopping fires. 

What if SignalR notified the app before it started closing connections?

**Comment by kjkrum** [comment] 2019-08-21 22:27
Compare [`IRegisteredObject.Stop`](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.iregisteredobject.stop) from Framework. It seems that cancelling `IApplicationLifetime.ApplicationStopping` is analogous to calling `Stop(true)`, or at least SignalR treats it that way. Maybe `IApplicationLifetime` could expose two tokens analogous to `Stop(false)` and `Stop(true)`.

**Comment by halter73** [comment] 2019-08-22 16:41
@kjkrum The problem with having SignalR wait for ApplicationStopped to disconnect is that by the point ApplicationStopped fires, the server should have already aborted every connection. AFAIK ApplicationStopping is SignalR's last chance to gracefully close its connections.

Having SignalR fire its own event from its ApplicationStopping handler prior to it closing its connections like @Tratcher suggested should give SignalR app developers the hook they need to send a final message before server shutdown.

**Comment by BrennanConroy** [comment] 2021-07-29 18:48
Dupe of https://github.com/dotnet/aspnetcore/issues/25069

**Closed by BrennanConroy** 2021-07-29 18:48 UTC
Labels: affected-very-few, area-signalr, enhancement, severity-minor
