### ISSUE TITLE
Create New Blazor WASM Project - Namespace compiler errors off the bat - VSCode

### ISSUE THREAD

**Issue by garfbradaz** [dotnet/aspnetcore#33486] opened 2021-06-11 20:02 UTC
### Describe the bug
When I create a new Blazor WASM project using the following:

`dotnet new blazorwasm -n FruitCartUI `

I receive errors off the bat (without touching anything) when opening up the Project in _Visual Studio Code_:

> The type or namespace name 'Shared' does not exist in the namespace 'FruitCartUI' (are you missing an assembly reference?) [FruitCartUI]

>The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [FruitCartUI]

And a lot more:

![image](https://user-images.githubusercontent.com/959766/121740635-4813fd80-caf5-11eb-9836-5f393601c650.png)

Interestingly though when I  `dotnet build` no errors are reported. When I open the project in Visual Studio 2019 Community (v16.10.0) again no problems reported.

### To Reproduce

1. Target .NET 5 SDK
2. `dotnet new blazorwasm -n FruitCartUI `
3. Open the project in Visual Studio. Wait for Omnisharp to load and do its jazz
4. Click on the `Program.cs` or `_Imports.razor`
5. In the `PROBLEMS` tab should get errors similar to the above.

I've also published everything I have here for you if you need to pull it down.

https://github.com/garfbradaz/Repo-For-MS-Blazor-Issue-In-VSCode

Also I have copied some logs from my Visual Studio Code workspace:

* [Omnisharp Razor Logs](https://gist.github.com/garfbradaz/002946d99f395afcf8be4373549047a5)
* [Omnisharp Log](https://gist.github.com/garfbradaz/358a9988b1ef81c2f6123e0a9c776ac1)

### Further technical details
- Include the output of `dotnet --info`:

> .NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

> Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

> Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

> .NET SDKs installed:
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

> .NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE  is Visual Studio Code v1.57.0 (user setup):

>Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

- C# Extension in use is version 1.23.12

- Visual Studio Community 16.10 and Preview 16.8.

**Comment by garfbradaz** [comment] 2021-06-17 20:52
@NTaylorMullen  do you need anything else from me?

**Comment by NTaylorMullen** [comment] 2021-06-17 23:02
> @NTaylorMullen do you need anything else from me?

Sorry for the delay! Hadn't gotten around to triaging this yet 😄. But ya if you could provide your OmniSharp Log's as well that'd be supper helpful!

**Comment by NTaylorMullen** [comment] 2021-06-17 23:39
@JoeRobich is this the source generator bit biting us? I looked at the O# log with trace enabled but nothing jumped out: [omnisharptracelog.txt](https://github.com/dotnet/aspnetcore/files/6673711/omnisharptracelog.txt)

**Comment by JoeRobich** [comment] 2021-06-18 01:21
@NTaylorMullen Is this bit normal? Seeing it right before the requests and responses begin.
```
[dbug]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: c:\GitHub\Repo-For-MS-Blazor-Issue-In-VSCode\Pages\Index.razor__virtual.cs removed from workspace
```

**Comment by NTaylorMullen** [comment] 2021-06-18 04:07
Oh interesting, so we don't migrate those files from Misc -> non-Misc as far as I can remember. That definitely seems off

**Comment by garfbradaz** [comment] 2021-06-18 07:59
> > @NTaylorMullen do you need anything else from me?
> 
> Sorry for the delay! Hadn't gotten around to triaging this yet 😄. ~But ya if you could provide your OmniSharp Log's as well that'd be supper helpful!~
> 
> Edit: just saw you provided this

Thanks for looking fella. Shout if you need me.

**Comment by NTaylorMullen** [comment] 2021-06-30 05:00
Found the root cause but tracking work here: https://github.com/dotnet/aspnetcore/issues/33858

Closing this as duplicate.

**Closed by NTaylorMullen** 2021-06-30 05:00 UTC
Labels: area-razor.tooling, bug, feature-razor.vscode
