### ISSUE TITLE
Error when trying to debug Blazor WebAssembly in Chrome, with Windows Authentication turned on

### ISSUE THREAD

**Issue by elylv** [dotnet/aspnetcore#22958] opened 2020-06-15 17:13 UTC
When I create a Blazor WebAssembly project, set with a DotNetCore server, and I turn on Windows Authentication on the Server project (and turn off Anonymous Authentication), when I try to Debug the project from VS2019 (16.6.2) with Chrome (83), the application builds, Chrome launches, but the application does not load, and eventually I get an error that it "failed to launch debug adapter".

![image](https://user-images.githubusercontent.com/33698323/84685874-e39a7e80-af32-11ea-9657-bbf6619c5386.png)

![image](https://user-images.githubusercontent.com/33698323/84685937-f9a83f00-af32-11ea-8a80-90c2898ef51a.png)

If I switch Anonymous Authentication back on, it builds fine (but I can't access HttpContext.User.Identity info on the server).
If I debug in Edge (44) rather than Chrome, it works correctly (although I have to input my NTLM credentials every time).

As an aside, I am trying to implement Windows Authentication in a Blazor WebAssembly app, which seems to be harder than it should be, and I'm surprised a template exists for this for Server projects, but not for WebAssembly.

**Comment by javiercn** [comment] 2020-06-15 18:21
@elylv thanks for contacting us.

We are aware of this issue. This is a result of the debug proxy running on the same process as the hosting app. We have plans to make the debug proxy a standalone process.

Closing as a dupe of #21466

**Closed by javiercn** 2020-06-15 18:21 UTC
Labels: area-blazor, blazor-wasm
