### ISSUE TITLE
Blazor Razor pages have broken intellisense

### ISSUE THREAD

**Issue by deanchalk** [dotnet/aspnetcore#33350] opened 2021-06-07 20:00 UTC
### Describe the bug
When creating a brand new blazorwasm project with the cli, then load it into vs code, the component intellisense is broken by default.

### To Reproduce
use the cli with the following command, then load the output into vs code:
dotnet new blazorwasm -o TestBlazor -ho --no-https

load it into vs code and you get this (see image)
![image](https://user-images.githubusercontent.com/11065294/121080139-f3117800-c7d2-11eb-8bd6-73336f149aa6.png)

as you can see razor components are no longer recognised. However, the code runs correctly

I have the latest VS Code with up to date C# extension. I have the latest VS 2019 installed (16.10) so MSBuild is up to date. I have tried with ,net Core 5.0.300 and the latest .net Core 6 preview - neither work.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by NTaylorMullen** [comment] 2021-06-07 22:06
@deanchalk could you validate the following:
1. Your project builds
2. In your obj directory there is a project.razor.json within the hierarchy
3. Your project.razor.json is not empty


Assuming all the above checks out could you please do the "Report a Problem" action in VSCode:
![image](https://user-images.githubusercontent.com/2008729/121093404-d741ae00-c7a1-11eb-88d4-2176c02e4ec9.png)

Also please include your `OmniSharp Log`s as well.

**Comment by rfrancisco** [comment] 2021-06-07 22:26
I see many similar issues in VS Code and Visual Studio for Mac. I'm using .Net 5.0.203 with the latest versions of VS Code and Visual Studio for Mac.
- Both IDEs become very very slow when working in Blazor projects
- Both IDEs have lots issues with intellisense (more so in VS Code in my case)
- Both IDEs routinely highlight perfectly valid code as invalid (more so in VS Code in my case)

**Comment by deanchalk** [comment] 2021-06-08 06:22
1) My project builds
2) No project.razor.json file anywhere in either obj hierarchy (server or client project)
3) VS Code version 1.56.2

Could item 2 be the issue ?

**Comment by deanchalk** [comment] 2021-06-08 06:24
I dont know how to get the Omnisharp log

**Comment by deanchalk** [comment] 2021-06-08 07:15
I think this might be the same issue as detailed here
https://github.com/OmniSharp/omnisharp-vscode/issues/4580

**Comment by deanchalk** [comment] 2021-06-08 07:25
I have added this work-around to the above omnisharp isue:

_Hi All, had the same issue. I found a work-around in VS Code by downgrading the C# extension from the current version 1.23.12 to 1.23.11. You can do this in the the extensions panel by clicking on the config button for the C# extension and click 'Install another version', then select the previous version. Version 1.23.12 was released about 12 days ago, and obviously has broken razor intellisense_

**Comment by NTaylorMullen** [comment] 2021-06-09 03:49
Could you all verify if this is what you're running into: https://github.com/OmniSharp/omnisharp-vscode/issues/4573

Specifically the mentioned NRE in the OmniSharp log:
![image](https://user-images.githubusercontent.com/2008729/121289339-9d53d300-c899-11eb-9da0-e407b79fbbc9.png)

**Comment by deanchalk** [comment] 2021-06-09 04:36
Where would I find this?

**Comment by NTaylorMullen** [comment] 2021-06-30 04:58
Found the root cause but tracking work here: https://github.com/dotnet/aspnetcore/issues/33858

Closing this as duplicate.

**Closed by NTaylorMullen** 2021-06-30 04:58 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Needs: Attention :wave:, Status: Resolved, area-razor.tooling
