### ISSUE TITLE
Blazor - Form Validation Exception when Refreshing

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [dotnet/aspnetcore#35000] opened 2021-08-03 18:31 UTC
### Describe the bug
Exception thrown when using DataAnnocationsValidator AND ValidationsSummary.

### To Reproduce
After selectively adding and removing code for a few hours to track down a very unhelpful exception- I have identified a potential bug with form validations.

## Code To Reproduce
```csharp
@page "/admin/test"

<EditForm Model="@Model">
    <DataAnnotationsValidator />
    <ValidationSummary />
</EditForm>>



@code {
    public object Model { get; set; } = "hi";
    protected override void OnInitialized()
    {
        Console.WriteLine("OnInitialized()");
        base.OnInitialized();
    }
    protected override Task OnInitializedAsync()
    {
        Console.WriteLine("OnInitializedAsync()");
        return base.OnInitializedAsync();
    }
    protected override void OnParametersSet()
    {
        Console.WriteLine("OnParametersSet()");
        base.OnParametersSet();
    }
    protected override Task OnParametersSetAsync()
    {
        Console.WriteLine($"OnParametersSetAsync()");
        return base.OnParametersSetAsync();
    }
    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine($"OnAfterRender(firstRender: {firstRender})");
        base.OnAfterRender(firstRender);
    }
    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        Console.WriteLine($"OnAfterRenderAsync(firstRender: {firstRender})");
        return base.OnAfterRenderAsync(firstRender);
    }

}
```

Produces this output when refreshing the page.

```text
OnInitialized()
OnInitializedAsync()
OnParametersSet()
OnParametersSetAsync()
OnAfterRender(firstRender: True)
OnAfterRenderAsync(firstRender: True)
OnInitialized()
OnInitializedAsync()
OnParametersSet()
OnParametersSetAsync()
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMAMLBE4R35K", Request id "0HMAMLBE4R35K:0000001B": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
         at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess() in Microsoft.AspNetCore.Components.dll:token 0x60000b2+0x12
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in Microsoft.AspNetCore.Components.dll:token 0x6000231+0x0
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in Microsoft.AspNetCore.Components.dll:token 0x6000098+0x48
         at Microsoft.AspNetCore.Components.Forms.ValidationSummary.<.ctor>b__14_0(Object sender, ValidationStateChangedEventArgs eventArgs) in Microsoft.AspNetCore.Components.Web.dll:token 0x600021b+0x0
         at Microsoft.AspNetCore.Components.Forms.EditContextDataAnnotationsExtensions.DataAnnotationsEventSubscriptions.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x6000067+0x57
         at Microsoft.AspNetCore.Components.Forms.DataAnnotationsValidator.System.IDisposable.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x600000d+0x18
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing) in Microsoft.AspNetCore.Components.dll:token 0x6000241+0x10c
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000070+0x0
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing) in Microsoft.AspNetCore.Components.dll:token 0x6000241+0x10c
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DisposeAsync() in Microsoft.AspNetCore.Components.dll:token 0x6000243+0x1a1
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|21_0(Int32 i, ValueTask vt, List`1 toDispose) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000117+0x6e
         at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt) in Microsoft.AspNetCore.Http.dll:token 0x6000232+0x5b
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<FireOnCompleted>g__ProcessEvents|227_0(HttpProtocol protocol, Stack`1 events) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x6000b24+0xe5
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
      System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender() in Microsoft.AspNetCore.Components.dll:token 0x6000237+0x17
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in Microsoft.AspNetCore.Components.dll:token 0x6000231+0x0
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in Microsoft.AspNetCore.Components.dll:token 0x6000098+0x48
         at Microsoft.AspNetCore.Components.Forms.ValidationSummary.<.ctor>b__14_0(Object sender, ValidationStateChangedEventArgs eventArgs) in Microsoft.AspNetCore.Components.Web.dll:token 0x600021b+0x0
         at Microsoft.AspNetCore.Components.Forms.EditContextDataAnnotationsExtensions.DataAnnotationsEventSubscriptions.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x6000067+0x57
         at Microsoft.AspNetCore.Components.Forms.DataAnnotationsValidator.System.IDisposable.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x600000d+0x18
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing) in Microsoft.AspNetCore.Components.dll:token 0x6000241+0x10c
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'gr5pxhRrMGqrBZgI8eA6F0mw_SitS_pjZzcGVgEcodc'.
      System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender() in Microsoft.AspNetCore.Components.dll:token 0x6000237+0x17
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in Microsoft.AspNetCore.Components.dll:token 0x6000231+0x0
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in Microsoft.AspNetCore.Components.dll:token 0x6000098+0x48
         at Microsoft.AspNetCore.Components.Forms.ValidationSummary.<.ctor>b__14_0(Object sender, ValidationStateChangedEventArgs eventArgs) in Microsoft.AspNetCore.Components.Web.dll:token 0x600021b+0x0
         at Microsoft.AspNetCore.Components.Forms.EditContextDataAnnotationsExtensions.DataAnnotationsEventSubscriptions.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x6000067+0x57
         at Microsoft.AspNetCore.Components.Forms.DataAnnotationsValidator.System.IDisposable.Dispose() in Microsoft.AspNetCore.Components.Forms.dll:token 0x600000d+0x18
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing) in Microsoft.AspNetCore.Components.dll:token 0x6000241+0x10c
OnInitialized()
OnInitializedAsync()
OnParametersSet()
OnParametersSetAsync()
OnAfterRender(firstRender: True)
OnAfterRenderAsync(firstRender: True)
```

Removal of EITHER  DataAnnotationsValidator OR ValidationSummary will make the exception go away.

Based on the documentation: https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0

This shouldn't cause issues.

##Remarks

This is the minimal amount of code I could leverage to reproduce this issue. The actual code base has proper data annotations for validations, yet, exhibits the same behaviour. 

I am leveraging 6.0.100-preview.6.21355.2, with Visual Studio 2022 17.0.0 Preview 2.1.

**Comment by XtremeOwnageDotCom** [comment] 2021-08-03 18:36
To also note- I performed another test, using a nearly identical example provided with the .net 6.0 form validation example.

```csharp
@page "/admin/test"
@using System.ComponentModel.DataAnnotations

<EditForm Model="@starship" OnValidSubmit="@HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <p>
        <label>
            Identifier:
            <InputText @bind-Value="starship.Identifier" />
        </label>
    </p>
    <p>
        <label>
            Description (optional):
            <InputTextArea @bind-Value="starship.Description" />
        </label>
    </p>
    <p>
        <label>
            Primary Classification:
            <InputSelect @bind-Value="starship.Classification">
                <option value="">Select classification ...</option>
                <option value="Exploration">Exploration</option>
                <option value="Diplomacy">Diplomacy</option>
                <option value="Defense">Defense</option>
            </InputSelect>
        </label>
    </p>
    <p>
        <label>
            Maximum Accommodation:
            <InputNumber @bind-Value="starship.MaximumAccommodation" />
        </label>
    </p>
    <p>
        <label>
            Engineering Approval:
            <InputCheckbox @bind-Value="starship.IsValidatedDesign" />
        </label>
    </p>
    <p>
        <label>
            Production Date:
            <InputDate @bind-Value="starship.ProductionDate" />
        </label>
    </p>

    <button type="submit">Submit</button>

    <p>
        <a href="http://www.startrek.com/">Star Trek</a>,
        &copy;1966-2019 CBS Studios, Inc. and
        <a href="https://www.paramount.com">Paramount Pictures</a>
    </p>
</EditForm>



@code {
    public class Starship
    {
        [Required]
        [StringLength(16, ErrorMessage = "Identifier too long (16 character limit).")]
        public string Identifier { get; set; }

        public string Description { get; set; }

        [Required]
        public string Classification { get; set; }

        [Range(1, 100000, ErrorMessage = "Accommodation invalid (1-100000).")]
        public int MaximumAccommodation { get; set; }

        [Required]
        [Range(typeof(bool), "true", "true",
            ErrorMessage = "This form disallows unapproved ships.")]
        public bool IsValidatedDesign { get; set; }

        [Required]
        public DateTime ProductionDate { get; set; }
    }
    private Starship starship = new() { ProductionDate = DateTime.UtcNow };

    private void HandleValidSubmit()
    {
        Console.WriteLine("HandleValidSubmit()");
    }

    protected override void OnInitialized()
    {
        Console.WriteLine("OnInitialized()");
        base.OnInitialized();
    }
    protected override Task OnInitializedAsync()
    {
        Console.WriteLine("OnInitializedAsync()");
        return base.OnInitializedAsync();
    }
    protected override void OnParametersSet()
    {
        Console.WriteLine("OnParametersSet()");
        base.OnParametersSet();
    }
    protected override Task OnParametersSetAsync()
    {
        Console.WriteLine($"OnParametersSetAsync()");
        return base.OnParametersSetAsync();
    }
    protected override void OnAfterRender(bool firstRender)
    {
        Console.WriteLine($"OnAfterRender(firstRender: {firstRender})");
        base.OnAfterRender(firstRender);
    }
    protected override Task OnAfterRenderAsync(bool firstRender)
    {
        Console.WriteLine($"OnAfterRenderAsync(firstRender: {firstRender})");
        return base.OnAfterRenderAsync(firstRender);
    }

}
``` 
The exact same exception occurs.

**Comment by pranavkm** [comment] 2021-08-05 16:54
Thanks for the issue report. This is a dupe of https://github.com/dotnet/aspnetcore/issues/32411. We'll use the other issue to track fixing this.

**Closed by pranavkm** 2021-08-05 16:54 UTC
Labels: area-blazor, feature-blazor-form-validation
