### ISSUE TITLE
.NET Core Debug Blazor Web Assembly in Chrome leads to forever spinning chrome page with about:blank in address bar

### ISSUE THREAD

**Issue by Arrowana** [dotnet/aspnetcore#20427] opened 2020-04-01 21:25 UTC
### Describe the bug
In VS Code after starting ".NET Core Launch (Blazor Standalone)" then starting
".NET Core Debug Blazor Web Assembly in Chrome" leads to forever loading chrome page with about:blank in the address bar.

### To Reproduce
I followed the tutorial to get started with the template Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-preview3.20168.3
https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code

Then moved on to debugging instruction
https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1

The project is the one created by
```dotnet new blazorwasm -o WebApplication1```
Without a single change

In VS Code after starting ".NET Core Launch (Blazor Standalone)" standalone then ".NET Core Debug Blazor Web Assembly in Chrome", it opens a chrome page with about:blank which spins forever and never lead to the website.

Putting a breakpoint in the razor pages (for instance, FetchData.razor on currentCount++;) shows "Unbound breakpoint".

At this point if i press F12 in chrome, the page loads, but still debugging does not work.
Breakpoint start to show the message "No symbols have been loaded for this document"

### Further technical details
- dotnet --info
```.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- IDE VS Code 1.43.2
- Chrome Version 80.0.3987.162 (Official Build) (64-bit)

**Comment by javiercn** [comment] 2020-04-02 09:06
@Arrowana thanks for contacting us.

We'll look into your issue and get back to you.

**Comment by mkArtakMSFT** [comment] 2020-04-02 16:45
@NTaylorMullen can you please have a look at this? Thanks!

**Comment by nlz242** [comment] 2020-04-09 16:32
Same here.
Stuck on "about:blank" spinning. If i look at VS Code's call stack window, i can see ".NET Core Debug Blazor Web Assembly in Chrome" with "blank" under it.
After a while (i'm guessing debug timeout), the page does load but the call stack in vs code still says "blank" and breakpoint are obviously not being hit.

I also tried with an hosted app created using this : dotnet new blazorwasm --hosted -o TestApp

Same result. 

Maybe interesting: if i open up the Dev tools in chrome (f12), the page does load. I'm guessing that it requeries the page and thus doesn't wait after the debugger to attach ?

But yeah, debugging is unusable with VS Code for now and i'd rather not install a preview version of Visual Studio, i've had too many issues with Preview version "sticking" around and creating issues, in the past. So i'm kinda stuck, debugging wise.

**Comment by NTaylorMullen** [comment] 2020-04-09 17:27
@Arrowana / @nlz242 how are you running the VSCode bits? Aka, which launch configurations are you invoking and in what order?

@danroth27 the debugging instructions on the get started page for Blazor WASM VSCode aren't great. Could we get those updated?

**Comment by NTaylorMullen** [comment] 2020-04-09 17:56
@connor4312 do you have any idea why opening chrome dev tools would then allow the Debug Enabled chrome instance to load? Is there something @Arrowana can do to capture more log information to diagnose further?

**Comment by connor4312** [comment] 2020-04-09 18:42
Yep: setting `trace: true` in the launch.json will cause the extension to capture verbose logs. The file location will be printed to the debug console, sharing that should shed some light.

**Comment by nlz242** [comment] 2020-04-10 03:09
> 
> @nlz242 how are you running the VSCode bits? Aka, which launch configurations are you invoking and in what order?
> 
I'm following the instructions found at https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/

So i'm starting .NET Core Launch (Blazor Standalone) first, then once that's running, i'm starting .NET Core Debug Blazor Web Assembly in Chrome

Here's the verbose log i grabbed by adding "trace": true, hopefully it is what you need.
[verbose log.txt](https://github.com/dotnet/aspnetcore/files/4459686/verbose.log.txt)

**Comment by connor4312** [comment] 2020-04-10 04:14
The normal process is that we get a target for about:blank, attach to it, and issue a Page.navigate, and then when it loads we're ready to go. We try to do this in the log that nlz sent, but notice that there's never a response to the Page.navigate CDP call. The request/response pair should look like:

![](https://memes.peet.io/img/20-04-dd799e6c-6ffb-4ad4-aed3-e7753b24fc14.png)

Looking at the logs, I wonder if something isn't quite connecting right inside the Blazor proxy. I also noticed that none of the requests (like Runtime.enable, Debugger.enable, which should have an empty successful replies) issued to the page's target after Page.navigate have responses. The requests/responses that nlz has appear to be equivalent to the ones I have up until Page.navigate.

Is there a way to retrieve telemetry/trace logs from the proxy @NTaylorMullen?

**Comment by Arrowana** [comment] 2020-04-12 01:47
I went back to the exact same project and after deleting obj and bin it works. I can now debug blazor webassembly from visual studio code. This is weird...

**Comment by NTaylorMullen** [comment] 2020-04-13 19:06
> Is there a way to retrieve telemetry/trace logs from the proxy @NTaylorMullen?

Sadly I'm not familiar with the proxy side of things. @SteveSandersonMS could you assist?

**Comment by nlz242** [comment] 2020-04-14 13:55
For the record, i tried deleting the obj/bin folders as suggested by @Arrowana and this did NOT fix it for me. 
I'll be happy to help with whatever is needed (logs, troubleshooting, etc).

**Comment by alfkonee** [comment] 2020-04-14 22:05
Same issue here but with Visual Studio Preview Version shown below
![image](https://user-images.githubusercontent.com/3909521/79278188-c1d13c80-7e9a-11ea-847d-461361c46d71.png)
With the following launchSettings Profile
![image](https://user-images.githubusercontent.com/3909521/79278362-15438a80-7e9b-11ea-965c-17e1b305850f.png)
With this Exceptions after 30 s wait 
 ```
      Request starting HTTP/1.1 GET http://localhost:56261/_framework/debug/ws-proxy?browser=ws%3A%2F%2Flocalhost%3A27931%2Fdevtools%2Fbrowser%2F4a007c8e-3691-43b1-885e-ccdb38c71e2d
WsProxy Starting on ws://localhost:27931/devtools/browser/4a007c8e-3691-43b1-885e-ccdb38c71e2d
WsProxy: IDE waiting for connection on ws://localhost:27931/devtools/browser/4a007c8e-3691-43b1-885e-ccdb38c71e2d
WsProxy: Client connected on ws://localhost:27931/devtools/browser/4a007c8e-3691-43b1-885e-ccdb38c71e2d
WsProxy::Run: Exception System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host.
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WsProxy.WsProxy.ReadOne(WebSocket socket, CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at WsProxy.WsProxy.Run(Uri browserUri, WebSocket ideSocket)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 31351.1739ms 101
```
With this popup
![image](https://user-images.githubusercontent.com/3909521/79278602-88e59780-7e9b-11ea-9153-be3a58647f7d.png)

Output of 'dotnet --info'
![image](https://user-images.githubusercontent.com/3909521/79278771-f09be280-7e9b-11ea-859d-ac94b34b59c7.png)

**Comment by danroth27** [comment] 2020-04-14 22:08
@alfkonee It looks like the debugging proxy may be crashing. Is this by any chance a PWA?

**Comment by alfkonee** [comment] 2020-04-15 15:31
No please it's not a PWA

**Comment by SteveSandersonMS** [comment] 2020-04-15 15:35
@alfkonee Could you try following the steps for "[debug in the browser](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#debug-in-the-browser)" and let us know whether that works in your environment? If not, is there any error message? This might help us pinpoint whether the problem is to do with VS connecting, or whether it's to do with launching the debug proxy.

**Comment by SteveSandersonMS** [comment] 2020-04-15 15:36
@nlz242 Could you also try my suggestion above and let us know the result?

**Comment by nlz242** [comment] 2020-04-15 17:42
> 
> 
> @nlz242 Could you also try my suggestion above and let us know the result?

@SteveSandersonMS following the debug in the browser steps, i'm able to debug from the browser. That works, i see my assembly and i can break (from chrome) into it. Debugging from VS Code still says the symbols aren't loaded. No error messages.
Debugging from Chrome is better than nothing, but it's obviously less... nice ... than from VS / VS Code.

**Comment by alfkonee** [comment] 2020-05-01 16:27
Hello there I think I figured out why this was occuring It seems I was using the wrong libraries ie `Microsoft.AspNetCore.Blazor`  instead of the newer libraries `Microsoft.AspNetCore.Components.WebAssembly`
 @nlz242  could you check to see if your Nuget Pacakges in your the Client Project and Shared Project Use the Correct Packages

After the Switch Debugging started working fine for me

**Comment by danroth27** [comment] 2020-05-01 17:42
@alfkonee Awesome! I'm glad you were able to get it working!

**Comment by mkArtakMSFT** [comment] 2020-05-22 19:23
Closing as it seems all the concerns brought up in this thread has been resolved.

**Closed by mkArtakMSFT** 2020-05-22 19:23 UTC
Labels: area-blazor, blazor-wasm, investigate
