### ISSUE TITLE
Embedded Views don't work with RazorViewToStringRenderer

### ISSUE THREAD

**Issue by alextof** [dotnet/aspnetcore#15046] opened 2019-10-16 06:32 UTC
I have a solution with .NET Core 2.2 that is able to render razor views from a Razor Class Library on a console application, but once I try to upgrade my solution towards .NET Core 3.0 I'm unable to make my RazorViewToStringRenderer see the views from the Razor Class Library that is referenced as a dependecy.

### To Reproduce
To reproduce the issue, please run this code. There is a folder CoreV2 where the app is fully functional, and CoreV3 where I can't get it to work.
https://dev.azure.com/okyselov/_git/ConsoleAppEmbeddedRazorViews

### Expected behavior
Work with .NET Core 3.x

### Additional context
I think I'm missing some configuration for the Razor Engine or some Razor Options. I also have some doubts regarding if IWebHostEnvironment is the culprit of this, as in .NET Core 3.0 IHostingEnvironment is deprecated.

To be able to inject IWebHostEnvironment I needed to run the WebHost asynchronous. Is there a way to obtain it without running a webhost?

**Comment by javiercn** [comment] 2019-10-16 10:21
@alextof Thanks for contacting us.

From inspecting the source I can tell you need to reference the Web SDK here: https://dev.azure.com/okyselov/_git/ConsoleAppEmbeddedRazorViews?path=%2FCoreV3%2FConsoleAppV3%2FConsoleAppV3.csproj&version=GBmaster&line=1&lineStyle=plain&lineEnd=2&lineStartColumn=1&lineEndColumn=1

So Microsoft.NET.Sdk.Web instead of Microsoft.NET.Sdk

I believe after that, it should work. I'm closing the issue for now, but if you still run into issues leave us a comment and we'll take another look to see if something is missing.

I would also recommend that if you still run into issues, you create a 3.0 webapp with razor pages or mvc, a razor class library and look at the differences between the ones created from 3.0 and the ones you are having problems with.

**Comment by javiercn** [comment] 2019-10-16 10:29
I jumped the gun, seems your question is deeper than just getting it to work. I'll try to address it here:
In essence:
* In 3.0 we changed the way we discover MVC primitives like controllers, actions, etc. So you need to be referencing the web SDK for the build to stamp the right metadata into the assembly that allows discovery to work in MVC.
* Alternatively, you need to discover the application parts manually, which can be done with the default application part factory.
  @pranavkm can provide more details here.
* With regards to your last comment, you don't need to use IWebHostEnvironment and you should be using the new host. That means you'll have to change your code accordingly.
  @pranavkm Is there an alternative way of doing this?

**Comment by jjxtra** [comment] 2019-10-16 23:44
I'd love more guidance on "Alternatively, you need to discover the application parts manually, which can be done with the default application part factory."...

**Comment by alextof** [comment] 2019-10-18 06:01
I'm also curious regarding the "Alternatively, you need to discover the application parts manually, which can be done with the default application part factory."

**Comment by alextof** [comment] 2019-11-21 18:59
Any news regarding this issue?

**Comment by alextof** [comment] 2019-11-21 19:06
@pranavkm

**Comment by toralux** [comment] 2019-12-02 22:19
Any news about this? My Dotnet Core 3.0 console application cannot find the "views" when rendering e-mail bodies using the Razor Engine after being ported from Dotnet Core 2.2, so this is holding me back from porting my application. A bugfix or a good example would be very helpful.

**Comment by toralux** [comment] 2019-12-05 14:17
I have been able to make a small example that reproduce that dotnet core 3.x (3.1) don't find the view while dotnet core 2.2 finds the view. 

[Rendering.zip](https://github.com/aspnet/AspNetCore/files/3927210/Rendering.zip)

Can anyone enlighten me why my code is broken when the only thing I have done running in a newer framework (<TargetFramework>netcoreapp3.1</TargetFramework> instead of <TargetFramework>netcoreapp2.2</TargetFramework>) and upgrading one nuget package (to <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="3.1.0" /> from <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.2.0" />)

`            var viewEngineResult = _viewEngine.FindView(actionContext, name, false);

            if (!viewEngineResult.Success) // <-- here 2.2 has found the view and 3.1 has not
            {
                throw new InvalidOperationException(string.Format("Couldn't find view '{0}'", name));
            }`

**Comment by pranavkm** [comment] 2020-01-03 23:10
Hi @alextof I tried your app out and it looks like it's working fine. Is this still an ongoing problem for you?

For all the rest commenting here, our sample for rendering a view to string is here: https://github.com/aspnet/samples/tree/f46e4c6ff99816499a2a06dc279136f25bf099fc/samples/aspnetcore/mvc/renderviewtostring. If you have specific questions or are running in to issues updating, please file a separate issue.

**Closed** 2020-01-15 23:00 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, area-mvc, question

**Comment by alextof** [comment] 2020-01-16 07:47
> 
> 
> Hi @alextof I tried your app out and it looks like it's working fine. Is this still an ongoing problem for you?
> 
> For all the rest commenting here, our sample for rendering a view to string is here: https://github.com/aspnet/samples/tree/f46e4c6ff99816499a2a06dc279136f25bf099fc/samples/aspnetcore/mvc/renderviewtostring. If you have specific questions or are running in to issues updating, please file a separate issue.

Hey @pranavkm !

I was able to fix the issue by changing the console application csproj sdk towards web sdk as @javiercn  said

> In 3.0 we changed the way we discover MVC primitives like controllers, actions, etc. So you need to be referencing the web SDK for the build to stamp the right metadata into the assembly that allows discovery to work in MVC.

And the previous behaviour that I had by switching to web sdk I could fix it.

> If I change the reference towards web sdk, my console application gets converted towards a Web Application, and this is not desired, I would like to keep it as a Console Application. I'm curious how I can impement a similar solution as I do have already at .NET Core 2.2 without breaking the application state such as converting my console app towards web app.

I fixed it by disabling the browser autostart at the properties of the project.


Thanks!
