### ISSUE TITLE
Hotreload does not show updated value from ViewBag

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/aspnetcore#41220] opened 2022-04-16 15:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As the title hints, let's say I am setting a `ViewBag` value in controller action and returning it to the user in JSON form, while debugging in VS, if I change the value, then when calling the action again, it doesn't return the updated value instead I get an exception like the below. 

![image](https://user-images.githubusercontent.com/17148381/163679817-36e92447-ee41-47b2-a1cb-ca9ced1dd4fc.png)

### Expected Behavior

I should see an updated value on the page the instead of the exception. 

### Steps To Reproduce

It's a simple repro. 
Create action and return ViewBag value. The first time it will return the value, then change the value and then hot reload and hit the same action again. You will receive the exception. 

![image](https://user-images.githubusercontent.com/17148381/163680138-8d943cff-5a54-4dfc-ad00-37fef9960135.png)

### .NET Version

7.0.100-preview.1.22110.4

**Comment by javiercn** [comment] 2022-04-18 10:18
@mkArtakMSFT I don't think this is related to MVC in any way, this is likely something to do with `dynamic` and hot reload in general.

Also, it is impossible for us to know that hot reload is correctly setup on the session.

@ShreyasJejurkar did other changes you made were correctly applied?

**Comment by ShreyasJejurkar** [comment] 2022-04-19 05:31
Hi @javiercn, I can confirm that Hot reload is working correctly for razor pages and C# code in VS. But when I change something that ViewBag holds and click save (it applies hot reload delta), and if I hit the corresponding action in the browser, I am getting above exception. 

From my point of view, we are not gathering deltas from ViewBag I guess to patch it. 


cc @pranavkm

**Comment by javiercn** [comment] 2022-04-19 10:08
@ShreyasJejurkar thanks for the additional details.

@tmat this seems to be a hot reload issue with regards to `dynamic`. Should this be transferred to the runtime repo?

**Comment by pranavkm** [comment] 2022-04-19 13:27
Dupe of https://github.com/dotnet/runtime/issues/59494

**Comment by javiercn** [comment] 2022-04-19 13:54
@pranavkm thanks!

**Closed by javiercn** 2022-04-19 13:54 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, External, area-mvc, Status: Resolved, feature-hot-reload
