### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource Blazor Wasm

### ISSUE THREAD

**Issue by brentminder** [dotnet/aspnetcore#38668] opened 2021-11-27 19:16 UTC
Can anyone publish a new blazor wasm app and publish it to a domain successfully? I'm publishing within VS 2022 via FTP directly to my domain (not using CLI).

Fails:
.Net 6 blazor wasm app (vs2022) throws errors:
https://bugmonitor.com/blazor/
http://bugmonitor.com/blazor/

I'm getting:
Uncaught TypeError: Cannot read properties of undefined (reading 'register') at index.html:26
index.html:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://bugmonitor.com/blazor/wwwroot/_framework/dotnet.6.0.0.7vke5xwy70.js' with computed SHA-256 integrity '6+0cHoWrocTZHsJlI4Vt1HRaRoOkZ5m6QDd36EAAHxc='. The resource has been blocked.

Line 26 is the service-worker.js file which gets read, then blocked using https, but loads via http (looking at network files in F12/dev browser tools).

For reference, here's the page:
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>BlazorApp3</title>
    <base href="./" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link href="BlazorApp3.styles.css" rel="stylesheet" />
    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
    <link rel="apple-touch-icon" sizes="192x192" href="icon-192.png" />
</head>

<body>
    <div id="app">Loading...</div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
</body>

</html>

```
Works:
.Net 5 blazor wasm app (vs2019) on same domain works with https or http:
https://bugmonitor.com/mysleep
http://bugmonitor.com/mysleep

**Comment by pranavkm** [comment] 2021-11-28 00:26
Have you had a look at this: https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#resolve-integrity-check-failures?

**Comment by brentminder** [comment] 2021-11-29 16:46
Hi Pranav,

Thanks for your prompt reply.

Regarding the article you sent, I've gone thru it as best I can. The HTTP request has only 200 responses but still has the offending error. I now have a bat file that deletes the bin/obj folders and does a publish. Then I ftp the files in the wwwroot folder into the \blazor folder on the website (which I don't control).

Here's the HTTP call:
![integrity issue HTTP screenshot](https://user-images.githubusercontent.com/8215758/143908068-f36b31a1-5b3f-4186-b1f4-705e9589b0ef.png)

And its wasm Response Content:
![dotnetwasm screenshot](https://user-images.githubusercontent.com/8215758/143908222-8dd3e4d9-26d5-45c6-8335-715ed2623f32.png)

I'm using Hostinger.com to host this website which is successfully rendering my .net 5 blazor wasm that I referenced before, so I wouldn't think it's a problem on the hosting site itself (unless they do something different for .net 6.

As far as HTTPS goes, there are many more errors including the one plaguing both request types, so we can just focus on getting HTTP to work first.

Here's the HTTPS call:
![integrity issue screenshot](https://user-images.githubusercontent.com/8215758/143908135-651e64e5-2393-41eb-a537-95b421e2a6ff.png)

**Comment by brentminder** [comment] 2021-12-05 19:04
I finally solved it!

I had tried all of the things mentioned here and elsewhere, and none of it worked. What did work was using my ftp client (filezilla) and changing the transfer type from "auto" to "binary" (Transfer > Transfer Type > Binary). I don't see an option for doing this in VS2022, so I guess I'll use my manual ftp client solution for now.

**Comment by mkArtakMSFT** [comment] 2021-12-07 17:47
> I finally solved it!
> 
> I had tried all of the things mentioned here and elsewhere, and none of it worked. What did work was using my ftp client (filezilla) and changing the transfer type from "auto" to "binary" (Transfer > Transfer Type > Binary). I don't see an option for doing this in VS2022, so I guess I'll use my manual ftp client solution for now.

Thanks @brentminder . This helps a lot.
@vijayrkn looks like this is publishing related. Can you please take a look? Thanks!

**Comment by alex-oswald** [comment] 2021-12-07 17:51
I'm having this exact same issue. 

My difference, deployment is performed using the `IIS web app deploy` task in Azure Pipelines. It could be this task is causing issues if this is publishing related.

**Comment by TanayParikh** [comment] 2021-12-07 20:07
> I'm having this exact same issue.
> 
> My difference, deployment is performed using the `IIS web app deploy` task in Azure Pipelines. It could be this task is causing issues if this is publishing related.

Are you able to attempt a **binary** deployment like @brentminder? I'm basing this off of the following in the docs:

> If some aspect of the deployment process modified the files. For example if you use a Git-based deployment mechanism, bear in mind that Git transparently converts Windows-style line endings to Unix-style line endings if you commit files on Windows and check them out on Linux. Changing file line endings change the SHA-256 hashes. To avoid this problem, consider using .gitattributes to treat build artifacts as binary files.

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#diagnosing-integrity-problems

**Comment by alex-oswald** [comment] 2021-12-08 17:08
@TanayParikh I can't find a way to do a binary deployment using the `IIS web app deploy` task. If there is a way, does someone mind pointing me in the right direction?

**Comment by TanayParikh** [comment] 2021-12-08 23:24
> Publishing to a folder from Visual Studio on my workstation works fine. Is there a potential workaround to this for using the `IIS web app deploy` task?

So publishing to prod from VS is working, but publishing to prod from IIS Web App Deploy results in integrity check failures?

To confirm, have your reviewed https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#resolve-integrity-check-failures?

**Comment by alex-oswald** [comment] 2021-12-09 00:08
>So publishing to prod from VS results in a working app, but publishing to prod from IIS Web App Deploy results in integrity check failures?
Correct. Yes, I've viewed the page, but have not ran the script yet. I plan to do that tomorrow.

**Comment by TanayParikh** [comment] 2021-12-09 22:05
Thanks @alex-oswald. @guardrex have you had any issues with the script, is this something needing an update? Note:

> Customization of the script might be required for your apps, including if running on version of PowerShell later than version 6.2.7.


@alex-oswald so the results show those files are in your IIS Deployed publish assets on the server, but not in the `service-worker-assets.js`. I wonder if those could be stale files from a prior deployment? Have you tried clearing out the folder before running the IIS task?

**Comment by guardrex** [comment] 2021-12-09 22:18
The script was provided to me for publication on ...

https://github.com/dotnet/AspNetCore.Docs/issues/20852

I haven't used/tested it. I don't recall any error reports on it until now. @alex-oswald ... You can submit a PR against the script by editing ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly/_samples/integrity.ps1

... or else I'll open an issue and take care of it on Friday.

**Comment by alex-oswald** [comment] 2021-12-12 01:16
> @alex-oswald so the results show those files are in your IIS Deployed publish assets on the server, but not in the `service-worker-assets.js`. I wonder if those could be stale files from a prior deployment? Have you tried clearing out the folder before running the IIS task?

Yes, I've tried clearing out the folder before deploying. It did not make a difference.
I'm not sure what I can do to fix this for my project, but I'm glad I was able to fix a bug in your script. :)

**Comment by EquiAvia** [comment] 2021-12-16 10:19
Hi All,

I am experiencing the same problem since switching to .Net 6. I have an asp.net core 6 web app which prerenders WASM components. 

I deploy the application via VS2022 web deploy to an Azure App service.

![image](https://user-images.githubusercontent.com/3167321/146352606-d07b2950-827d-4b37-a12e-3d57c2a1026c.png)

I get the same error since updating to the version of VS2022

![image](https://user-images.githubusercontent.com/3167321/146352648-aaa62c70-b5fb-4d6a-97ec-021c026eef84.png)

I have manually cleared the files on the FTP site using filezilla, I have checked that the file is returned with a status 200 from the server, and I have referenced the article you posted earlier. I am stuck, please help.

![image](https://user-images.githubusercontent.com/3167321/146353231-988fe889-d8ea-4f94-9f18-1d23d0f4d8c7.png)

**Comment by brentminder** [comment] 2021-12-16 12:52
Try uploading the files with filezilla in binary mode as I stated earlier.

**Comment by EquiAvia** [comment] 2021-12-17 23:01
Thanks Brentminder, that is okay for a one off, but we have a large number of deployments to do and we rely on the functionality.

**Comment by vijayrkn** [comment] 2022-04-04 17:43
Can someone please confirm if the issue is specific to FTP & IIS Deploy scenarios from VS?  

Is publishing to a folder from VS generating the correct artifacts?

If this is the case, can someone please share a binary log/ verbose msbuild log where the deployment fails to help with the investigation? Please remember to remove any sensitive content from the logs before uploading. Thanks!

**Comment by brentminder** [comment] 2022-04-14 00:20
@TanayParikh What further feedback do you need from me? You didn't ask me anything.

**Comment by TanayParikh** [comment] 2022-04-14 00:44
> Can someone please confirm if the issue is specific to FTP & IIS Deploy scenarios from VS?  
> 
> 
> 
> Is publishing to a folder from VS generating the correct artifacts?
> 
> 
> 
> If this is the case, can someone please share a binary log/ verbose msbuild log where the deployment fails to help with the investigation? Please remember to remove any sensitive content from the logs before uploading. Thanks! 

@brentminder @EquiAvia @alex-oswald would you be able to answer @vijayrkn's question above?

**Comment by TanayParikh** [comment] 2022-04-14 00:45
> I just upgraded VS2022 (2022-04-12) with latest bits, created a new blazor wasm project, and published via the FTP server option within VS, and it works. I don't know about publishing thru the IIS path in VS.

Just to clarify, after you still facing this issue?

**Comment by brentminder** [comment] 2022-04-14 02:11
As I stated, I can verify the FTP path which I originally posted about, but I cannot state anything about the IIS path since I'm not using it, and someone else posted about it. You can close the issue as far as I'm concerned. Thanks.

**Comment by vijayrkn** [comment] 2022-04-14 02:38
Thanks @brentminder . If any one else is running into this issue with IIS please share a binlog and I will be happy to take a look. 

We will go ahead and close this issue since you were the original poster and the issue is addressed for you. Thanks for the confirmation.

**Closed by vijayrkn** 2022-04-14 02:38 UTC
Labels: External, area-blazor, blazor-wasm, feature-integrity-check
