### ISSUE TITLE
[blazor] Remove reference to BINDING api in global namespace

### ISSUE THREAD

**Issue by maraf** [dotnet/aspnetcore#47878] opened 2023-04-25 09:38 UTC
The blazor hotreload feature expects BINDING api to be exported to global namespace in the https://github.com/dotnet/sdk/blob/main/src/BuiltInTools/BrowserRefresh/BlazorHotReload.js.

The https://github.com/dotnet/aspnetcore/pull/46693 rewrote the invoke as a JSImport and with that we can call directly the async function `receiveHotReloadAsync`.

With the resolution of this issue we can remove `disableDotnet6Compatibility: false` from https://github.com/maraf/aspnetcore/blob/99a1d2c0cb39cbddb0e771d76c15fa96cae46261/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L347

**Comment by pavelsavara** [comment] 2023-04-25 09:58
`disableDotnet6Compatibility: false` is there also for 3rd party code which uses those global objects. 
Let's flip it together with legacy interop when we link it out by default in the next major version (Net9).

**Comment by pavelsavara** [comment] 2023-04-25 09:59
I agree that hotreload should be simplified.

**Comment by mkArtakMSFT** [comment] 2023-04-25 16:40
@maraf is this something you plan to take care of?

**Comment by mkArtakMSFT** [comment] 2023-04-25 16:42
@maraf based on our current understanding it seems it's ok to leave this to preview5 and nothing will break in preview4 because of this. Can you please confirm this is correct?

**Comment by pavelsavara** [comment] 2023-04-25 17:05
Confirmed, this is not necessary to be fixed in preview4.

**Closed** 2023-05-01 21:11 UTC
Labels: task, area-blazor, blazor-wasm
