### ISSUE TITLE
Uploading 5 new crash dumps from working on a Blazor project this morning

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22966] opened 2020-06-15 20:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1077514/uploading-5-new-crash-dumps-from-working-on-a-blaz.html)._

---
Uploading 5 new crash dumps from working on a Blazor project this morning.

Not sure if they will all be duplicates or not, but inlcuding the 5 crashes I have had this morning hoping it can provide more information on the issues I am having working with Blazor Projects.

---
#### Visual Studio Feedback System on 6/14/2020, 11:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2020-06-15 20:15
Duplicate of https://github.com/dotnet/aspnetcore/issues/22276

**Closed by NTaylorMullen** 2020-06-15 20:15 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved
