### ISSUE TITLE
Request and response logging

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27471] opened 2020-11-02 22:54 UTC
Less verbose than Kestrel connection logging.

* Structured logging, headers, body, etc
* Options to filter headers/query string (sensitive data can be logged)

**Comment by JunTaoLuo** [comment] 2021-03-26 20:35
Is this a duplicate of https://github.com/dotnet/aspnetcore/issues/3700?

**Comment by BrennanConroy** [comment] 2021-03-26 22:57
Does look similar, @davidfowl

**Comment by davidfowl** [comment] 2021-03-26 23:38
Yea, mine is 😄

**Closed by davidfowl** 2021-03-26 23:38 UTC
Labels: affected-most, area-servers, enhancement, feature-middleware, severity-minor
