### ISSUE TITLE
AddRazorRuntimeCompilation breaks global using statements  

### ISSUE THREAD

**Issue by nglessner** [dotnet/aspnetcore#47051] opened 2023-03-06 15:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.cshtml pages (MVC) in .net 6.0 ignores all Global Using statements when AddRazorRuntimeCompilation is enabled. Many error message such as the following are displayed.

'List<FooBar>' does not contain a definition for 'IsNullOrEmpty' and no accessible extension method 'IsNullOrEmpty' accepting a first argument of type 'List<FooBar>' could be found (are you missing a using directive or an assembly reference?)

If you disable AddRazorRuntimeCompilation this works again.

### Expected Behavior

Global Using statements should not be effected by the AddRazorRuntimeCompilation flag. 

### Steps To Reproduce

1. Create a simple .net MVC project. 
2. Create a second project in you solution called Constants, in it create a class with a public constant in it.
3. Create a class called GlobalUsings.cs and include your constant's class namespace
4. On Home/index.cshtml use a razor statement to refer to your constant. I.e. @constant
5. Enable AddRazorRuntimeCompilation in your program.cs
```
 var builder = services.AddControllersWithViews()
       .AddRazorRuntimeCompilation();
```

### Exceptions (if any)

'List<FooBar>' does not contain a definition for 'IsNullOrEmpty' and no accessible extension method 'IsNullOrEmpty' accepting a first argument of type 'List<FooBar>' could be found (are you missing a using directive or an assembly reference?)

### .NET Version

.Net 6.0

### Anything else?

Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation Version="6.0.11"

**Comment by javiercn** [comment] 2023-03-06 19:34
@nglessner thanks for contacting us.

This is a duplicate of https://github.com/dotnet/aspnetcore/issues/42839

**Closed by javiercn** 2023-03-06 19:34 UTC
