### ISSUE TITLE
Flaky test: Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#22451] opened 2020-06-02 02:25 UTC
```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.6.20278.9 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-3.20271.4 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:_RazorBuildServerPipeName="0898a527-6313-4137-a883-f5c7b643744b" /t:Build /p:Configuration=Release ' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20258-02+26f6d1d87 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.6.20266.3\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.6.20278.9 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-3.20271.4 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:_RazorBuildServerPipeName=0898a527-6313-4137-a883-f5c7b643744b /p:Configuration=Release /t:Build .\AppWithPackageAndP2PReference.csproj
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview

```

**Comment by javiercn** [comment] 2021-01-15 11:35
Looked into the last instance of this test, it seems like its caused by MSBuild hanging.

**Comment by javiercn** [comment] 2021-01-15 11:37
The test is no longer quarantined which makes me think it possibly has been in and out of quarantine. We'll need to figure out what can we do to capture a dump of the process for investigation. That said, these tests have moved to the SDK repo, so I'm closing this issue for the time being.

**Closed by javiercn** 2021-01-15 11:37 UTC
Labels: area-mvc, investigate, task, test-failure
