### ISSUE TITLE
Using custom Identity Options isn't working

### ISSUE THREAD

**Issue by DerStimmler** [dotnet/aspnetcore#28661] opened 2020-12-15 09:43 UTC
### Describe the bug
I'm using Identity in an ASP.NET Core Web API application and want to use custom Identity options. I pass them in the `Startup.cs` when registering Identity. But these options doesn't change anything.

For example when I set passwords required minimum length to 4 and add a user's password with the length of 5 I get an IdentityError which says that the minimum length is 8.
That seems strange for me because the documentations of Identity states that the default value is 6?
So where does the 8 come from and why isn't it 4 as I configured it?

### To Reproduce

Im registering Identity in `Startup.cs` like this:

```
Action<IdentityOptions> configureOptions = options =>
   {
    options.Password.RequireDigit = false;
    options.Password.RequiredLength = 4;
    options.Password.RequireLowercase = false;
    options.Password.RequireUppercase = false;
    options.Password.RequireNonAlphanumeric = false;
    options.SignIn.RequireConfirmedAccount = true;
    options.SignIn.RequireConfirmedEmail = true;
  };

services
 .AddIdentityCore<ApplicationUser>(configureOptions)
 .AddDefaultTokenProviders()
 .AddEntityFrameworkStores<ApplicationDbContext>()
 .AddErrorDescriber<CustomIdentityErrorDescriber>();
```

Then I try to set my password in a Controller like this:

`await _userManager.AddPasswordAsync(user, request.Password);`

### Further technical details

- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`

```
.NET SDK (gemäß "global.json"):
 Version:   5.0.100
 Commit:    5044b93829

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: JetBrains Rider 2020.2.4

**Comment by HaoK** [comment] 2020-12-16 18:54
This is a dupe of https://github.com/dotnet/aspnetcore/issues/25788 basically there's a set of data validation attributes hardcoded in the UI, they need to match the server side (identity option values)

**Comment by DerStimmler** [comment] 2020-12-18 15:38
I've seen that issue but I'm not using the Identity UI. I have an Aspnet Web Api and get the password from an angular app. But when I try to set that password in my controller via the user manager my problem occurs.

**Comment by HaoK** [comment] 2020-12-18 16:41
You'll need to attach a repro that demonstrates the issue

**Closed** 2020-12-22 09:08 UTC
Labels: Needs: Author Feedback, area-identity
