### ISSUE TITLE
AutomaticReconnect on Java

### ISSUE THREAD

**Issue by aluzme** [dotnet/aspnetcore#20762] opened 2020-04-12 00:08 UTC
When method withAutomaticReconnect implement on java or android client

**Comment by BrennanConroy** [comment] 2020-04-12 00:32
Dupe of https://github.com/dotnet/aspnetcore/issues/8711

**Comment by anurse** [comment] 2020-04-13 18:57
Closing as duplicate

**Closed by anurse** 2020-04-13 18:57 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr

**Comment by aluzme** [comment] 2020-04-13 19:04
When library which support automaticereconnect on java release?

**Comment by anurse** [comment] 2020-04-13 19:48
We have no committed date to ship this feature, it will be considered for a future release. The issue I linked is in the backlog meaning it isn't planned for the next release.
