### ISSUE TITLE
Renaming a property in a backing cs file will sometimes corrupt the associated razor file

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#31369] opened 2021-03-29 22:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Renaming-a-property-in-a-backing-cs-file/1383428)._

---
[regression] [worked-in:16.9.2]
Create a razor component xyz.razor & a backing cs file of xyz.razor.cs

Create a property in the cs file as in 'private string proprtyName {get;set;}'. Use this property on a component in the razor file. Rename 'proprtyName' to 'propertyName' using F2 or the right click menu. Not alway, but fairly often the razor file is 'scrambled' and many property names and other markup is total random garbage.

This occurs in VS 2019 16.10 P1, reverting to VS 2019 16.9.2 'fixes' the issue.

---
#### Feedback Bot on 3/28/2021, 11:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2021-04-01 04:54
Notes from planning: Sync with @ryzngard on why rename could be exploding Razor worlds here.

**Comment by allisonchou** [comment] 2021-05-05 01:28
I've tried repro-ing this about a dozen or so times but can't seem to reproduce the issue.
@NTaylorMullen is there a way to ask the user for more information? I noticed the original issue is closed but I think a repro file would be helpful here.

**Comment by MarkStega** [comment] 2021-05-05 18:39
@allisonchou I opened the original issue. It is frustrating because it is intermittent. I am still seeing this in 16.9.4; Of course, in trying to get a repro just now I can't get a failure. I will keep trying, however, all I will be able to provide is the before & after razor file. It is not just on my system or anything like that. Two other developers who work on Material.Blazor have also experienced this issue.

Rename does not work at all in 16.10.0 P2 so I can't tell if it is an issue.

**Comment by MarkStega** [comment] 2021-05-08 13:56
I just got a repro in 16.9.4

I renamed the property for the @ref in the CustomValidation component backing .razor.cs file

The razor file had the ref in the GCDialog component destroyed, and the last component's pOnCompletion parameter appears to have been filled with 'stuff' from the generated razor file.

This is the resulting razor file:

```
@namespace Optimiser.Views

<GCDialogNB pButtonSelection="eDialogButtonSelections.None"
            pDialogTitle="@pDialogTitle"
            @ref="__og">

    <pBody>
        <EditForm Model="@pUserDTO"
                  OnValidSubmit="@ValidateSubmission">
            <CustomValidation @ref="pCustomValidation" />
            <ValidationSummary />

            <div style="display:flex; flex-direction: column; justify-content: left;">

                <GCTextField @bind-pValue="pUserDTO.pUserID"
                             pLabel="User abbreviation"
                             pTextInputStyle="eTextInputStyle.Outlined"
                             pAdditionalStyles="margin-top: 0.75em;"
                             pDisabled="@pIsModifyUserOp"
                             pValidationMessageFor=@( () => pUserDTO.pUserID ) />

                <GCTextField @bind-pValue="pUserDTO.pUserName"
                             pLabel="User name"
                             pTextInputStyle="eTextInputStyle.Outlined"
                             pAdditionalStyles="margin-top: 0.75em;"
                             pValidationMessageFor=@( () => pUserDTO.pUserName ) />

                <GCTextField @bind-pValue="pUserDTO.pEMail"
                             pLabel="eMail"
                             pAdditionalStyles="margin-top: 0.75em;"
                             pTextInputStyle="eTextInputStyle.Outlined" />

                <GCCheckbox @bind-pValue="pUserDTO.pIsActive"
                            pLabel="Is active" />

                <GCTextField @bind-pValue="pUserDTO.pPhone"
                             pLabel="Voice #"
                             pAdditionalStyles="margin-top: 0.75em;"
                             pTextInputStyle="eTextInputStyle.Outlined" />

                <GCTextField @bind-pValue="pUserDTO.pTextPhone"
                             pLabel="Text #"
                             pAdditionalStyles="margin-top: 0.75em;"
                             pTextInputStyle="eTextInputStyle.Outlined" />

                <GCCheckbox @bind-pValue="pUserDTO.pNotifyEMAIL"
                            pLabel="Notify by eMail" />

                <GCCheckbox @bind-pValue="pUserDTO.pNotifyTEXT"
                            pLabel="Notify by text" />

                <FlowDivider pDividerStyle="FlowDivider.eFlowDividerStyle.Small"
                             pTitle="Recipients" />

                <GCGrid pColumnConfigurations="@pRecipientColumnConfigurations"
                        pGroupedOrderedData="@pGroupedOrderedRecipientData"
                        pHighlightSelectedRow="@true"
                        pKeyExpression="@(recipients => recipients.pRowGuid.ToString())"
                        pLogIdentification="Recipients"
                        pMeasurement="@MB_Grid_Measurement.FitToData"
                        pOnMouseClick="@GridRecipientsRowClicked"
                        TRowData="@Recipient_DD" />

                <div class="periop-flow-flex-row" style="margin-top: 10px;">
                    <GCButton pAdditionalStyles="width: 100px; margin-right: 10px;"
                              pButtonId="AddRecipient"
                              pButtonText="Add"
                              pOnClickAsync="@OnButtonClickAsync" />
                    <GCButton pAdditionalStyles="width: 100px; margin-right: 10px;"
                              pButtonId="EditRecipient"
                              pButtonText="Edit"
                              pDisabled="@pDisableRecipientEditDelete"
                              pOnClickAsync="@OnButtonClickAsync" />
                    <GCButton pAdditionalStyles="width: 100px; margin-right: 10px;"
                              pButtonId="DeleteRecipient"
                              pButtonText="Delete"
                              pDisabled="@pDisableRecipientEditDelete"
                              pOnClickAsync="@OnButtonClickAsync" />
                </div>

                <FlowDivider pDividerStyle="FlowDivider.eFlowDividerStyle.Small"
                             pTitle="Available roles" />

                <GCCheckboxGroup pItemList="@pAvailableRoleList" />

                <GCSelect @bind-pValue="pUserDTO.pUserDefaultRole"
                          pAdditionalStyles="margin-top: 0.75em;"
                          pGCItems="@pCurrentRoleList"
                          pGCSelectInputStyle="@eSelectInputStyle.Outlined"
                          pLabel="Default role" />

                <GCCheckbox @bind-pValue="pUserDTO.pIsProviderRestricted"
                            pLabel="Is provider restricted" />

                <FlowDivider pDividerStyle="FlowDivider.eFlowDividerStyle.Small"
                             pTitle="Authorized providers" />

                <GCGrid pColumnConfigurations="@pProviderColumnConfigurations"
                        pGroupedOrderedData="@pGroupedOrderedProviderData"
                        pKeyExpression="@(Providers => Providers.pRowGuid.ToString())"
                        pLogIdentification="AuthorizedProviders"
                        pMeasurement="@MB_Grid_Measurement.FitToData"
                        TRowData="@Provider_DD" />

                <div class="periop-flow-flex-row" style="margin-top: 10px;">
                    <GCButton pButtonId="ChangeAuthorizedProviders"
                              pButtonText="Change authorized providers"
                              pOnClickAsync="@OnButtonClickAsync" />
                </div>

                <div class="form-group">
                    <GCTextField @bind-pValue="pUserDTO.pPassword"
                                 pAdditionalStyles="margin-top:.75em; "
                                 pLabel="Password"
                                 pTrailingIcon="lock_outline"
                                 pType="password" />
                    <ValidationMessage For=@( () => pUserDTO.pPassword ) />
                </div>

                <div class="form-group">
                    <GCTextField @bind-pValue="pUserDTO.pPasswordConfirmation"
                                 pAdditionalStyles="margin-top:.75em; "
                                 pLabel="Password confirmation"
                                 pTrailingIcon="lock_outline"
                                 pType="password" />
                    <ValidationMessage For=@( () => pUserDTO.pPasswordConfirmation ) />
                </div>

                <GCSelect @bind-pValue="pUserDTO.pAssociatedPractice"
                          pAdditionalStyles="margin-top: 0.75em;"
                          pGCItems="@pCurrentAssociatedPracticeList"
                          pGCSelectInputStyle="@eSelectInputStyle.Outlined"
                          pLabel="Associated practice" />

            </div>

            <footer>
                <div class="form-group mdc-dialog__actions">
                    <GCButton pAdditionalStyles="margin-right: 1em; width: 10em;"
                              pButtonType="submit"
                              pButtonId="ok"
                              pButtonText="Save" />

                    <GCButton pOnClickAsync="@CancelClick"
                              pAdditionalStyles="margin: 0; width: 10em;"
                              pButtonId="cancel"
                              pButtonText="Cancel" />
                </div>
            </footer>
        </EditForm>
    </pBody>
</GCDialogNB>

<CommunicationRecipientDialog pCommunicationRecipientAction="@pCommunicaticipientAction"
                              pOnCompletion="@(Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                                              }
                    ));
#nullable restore
#line 95 "C:\Solutions\OHI\Optimiser\Optimiser.2021\Views\Settings\Security\AddOrModifyUserDialog.razor"
                              __o = typeof(FlowDivider);

#line default
#line hidden
#nullable disable
                              __o = typeof(
#nullable restore
#line 103 "C:\Solutions\OHI\Optimiser\Optimiser.2021\Views\Settings\Security\AddOrModifyUserDialog.razor"
                                   Provider_DD

#line default
#line hidden
#nullable disable
                    );
                              __o = Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Collections.Generic.IEnumerable<Material.Blazor.MBGridColumnConfiguration<Provider_DD>>>(
#nullable restore
#line 98 "C:\Solutions\OHI\Optimiser\Optimiser.2021\Views\Settings\Security\AddOrModifyUserDialog.razor"
                                                pProviderColumnConfigurations

#line default
#line hidden
#nullable disable
                    );
                              __o = Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, Provider_DD>>>>>(
#nullable restore
#line 99 "C:\Solutions\OHI\Optimiser\Optimiser.2021\Views\Settings\Security\AddOrModifyUserDialog.razor"
                                              pGroupedOrderedProviderData

#line default
#line hidden
#nullable disable
                    );
                              __o = new System.Func"
                              @ref="pCommunicationRecipientDialogReference"
                              pRecipient="@pRect" />
```

**Comment by allisonchou** [comment] 2021-05-13 05:08
@MarkStega Thank you for the repro! A fix has been pushed for the issue and you should see it in an upcoming release (likely 17.0 preview 2).

> I can't get a repro as rename does not work at all in 16.10.0 P2. You right click on a property name, pick rename, and nothing happens.

Would you mind filing an additional issue for this? We'd be interested in tracking this issue to try to figure out what's going on here.

Closing out this particular issue as it has been resolved.

**Closed by allisonchou** 2021-05-13 05:08 UTC
Labels: Author: Migration Bot :robot:, area-razor.tooling, bug, feature-razor.vs
