### ISSUE TITLE
[Blazor] Development and debug

### ISSUE THREAD

**Issue by Timka654** [dotnet/aspnetcore#26366] opened 2020-09-27 22:29 UTC
Hi, i'm have problem but don't known this issue must be created in dotnet, asp.net or other repo, sorry

Blazor - 5.0.0-rc.1.20451.17
.NET - 5.0

For develop application i'm use "dotnet watch run -c Debug" in powershell, and after work i'm open windows task manager and see >50 process ".Net Host", i'm see this problem very long time, and my 16 Gb Ram used on 90-98%
![image](https://user-images.githubusercontent.com/12096914/94377414-13f4da00-012a-11eb-807d-d72ba5a3a4c6.png)

If i'm try debug (button "> project name" Visual Studio ), at first time - is normal, but after stop console not dropped and other times at start i'm receive exception, on start debugging by IIS Express i'm have this problem too, but cannot see this exception
```
Unhandled exception. System.IO.IOException: Failed to bind to address http://127.0.0.1:9300: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт).
 ---> System.Net.Sockets.SocketException (10048): Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт).
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Microsoft.WebAssembly.Diagnostics.Program.Main(String[] args)

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: No output has been recevied from the application.
         at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
         at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by mkArtakMSFT** [comment] 2020-09-28 02:57
Thanks for contacting us.
Looks like there are two issues here.
1. The fact that the debug proxy is using the same port every time. **This issue has been fixed already and will be released in .NET 5 RC2 release.**
2. The fact that these many processes stay open. I think this is also something we've addressed already but maybe I'm not remembering correctly. @pranavkm do you remember?

**Comment by BruceHunter** [comment] 2020-09-28 14:12
@mkArtakMSFT When are they releasing .NET 5 RC2?

**Comment by boukenka** [comment] 2020-09-28 15:00
@BruceHunter .NET  5 RC2 is planned for October 13, 2020.

**Comment by captainsafia** [comment] 2020-09-28 15:06
> The fact that these many processes stay open. I think this is also something we've addressed already but maybe I'm not remembering correctly. @pranavkm do you remember?

We did have a variant of this issue. We were leaving behind BrowserDebugHost.dll processes. This will be resolved in RC2.

However, based on the screenshot above, the processes seem to be msbuild processes, not BrowserDebugHost.dll processes so there might be something more here.

**Comment by pranavkm** [comment] 2020-09-28 17:45
@Timka654 do you have steps that reproduce the problem you're seeing with all of those msbuild processes running? I'm not seeing it locally but perhaps I'm missing something that triggers this behavior.

**Comment by Timka654** [comment] 2020-09-28 18:33
@pranavkm 
- create solution Blazor (Asp.Net hosted, other default)
- create ps1 file in solution dir
```
cd <...projectName (asp.net host, maybe this is problem)>
dotnet watch run -c Debug
```
and now i'm using modules structure - for one component or project module(user, wiki, project and other) i'm create Razor Components library project and append to solution, and link, after change one file anywhere you dotnet rebuild project, and you can have this  problem

- Solution
-- ps1 file
-- project Asp.Net hosted
-- project blazor
-- project Api (Asp.Net core api)
-- project models
-- razor components projects (for custom input. select)
-- razor components projects (for partial large project)

maybe this problem have Api project (i'm not sure) this run code is copy code for start blazor project

**Comment by pranavkm** [comment] 2020-09-28 19:48
Still not seeing it. I tried a hosted app with a dozen referenced RCLs but I don't see msbuild processes sticking around. 

@rainersigwald have you come across this before? `dotnet watch run` spawns `dotnet run` when it detects file changes. The previous `dotnet run` process gets cleaned up when we spawn a new one. Even if we had an issue there, it's strange to see soo many `dotnet msbuild` processes sticking around.

**Comment by Timka654** [comment] 2020-09-28 19:59
@pranavkm i'm find problem, if you drop console window, processes not dropped(at now i'm have exceptions and i'm close window), i'm must drop this window on day 2-20 times for publish beta releases,

UPD: processes dropped, but after 1-5 minutes after closing
![image](https://user-images.githubusercontent.com/12096914/94479314-4ad7f800-01dd-11eb-8ac2-89ca91cb41cb.png)

**Comment by Timka654** [comment] 2020-09-28 20:14
i think
dotnet watch, watched my file changes, try rebuild, run process dotnet(> 1 times for multithreading build, this i'm dont known, maybe 1 time), catched exceptions, and wait next update files, and before new try - not dropping exists processes, and this cycled action

and another scenario - i'm visibling my exceptions, fast change this and save files, dotnet - run build, but not ending and after save changes try build again, not dropping exists processes

**Comment by rainersigwald** [comment] 2020-09-28 20:22
`dotnet run` runs `dotnet build` which calls `dotnet msbuild -m` which will start `NUMBER_OF_PROCESSORS` worker processes. After the build is complete, those processes stay around, idle, for up to 15 minutes. That's a perf optimization--it's noticeably faster to connect to an existing process than to start a new one.

On the second and subsequent builds, MSBuild should find and connect to those preexisting processes. So there _shouldn't_ be dramatic growth in the number of MSBuilds over time in a `dotnet watch` scenario--it should hit a steady state.

@Timka654, how many logical processors does your machine have?

**Comment by Timka654** [comment] 2020-09-28 20:24
@rainersigwald 8 logical processors

**Comment by rainersigwald** [comment] 2020-09-28 22:20
@Forgind fyi, another maybe-a-handshake-problem thing.

@Timka654 Can you set these two environment variables, let the problem happen for a while, and then share the contents of the log folder?

```cmd
set MSBUILDDEBUGCOMM=1
set MSBUILDDEBUGPATH=C:\MSBuildCommLogs26366
mkdir %MSBUILDDEBUGPATH%
```

**Comment by Timka654** [comment] 2020-09-28 22:24
@rainersigwald I'm append results after see this problem, maybe you must wait 1-2 days

**Comment by Timka654** [comment] 2020-09-29 21:40
@rainersigwald 
[MSBuildCommLogs26366.zip](https://github.com/dotnet/aspnetcore/files/5301997/MSBuildCommLogs26366.zip)
![image](https://user-images.githubusercontent.com/12096914/94619400-86de8c00-02b5-11eb-99ab-2dd81246366d.png)

**Comment by Forgind** [comment] 2020-09-29 21:49
Thanks!

I saw both successful connections with newly-created nodes and failures to connect with preexisting nodes. I think it's interesting that a couple of the pids in the list are _not_ present in the comm traces you provided, yet they're mentioned by providers as nodes they tried to connect to before ultimately failing. @rainersigwald, does the comm logging only pick up nodes that are of the same build as the entry point node? As an example, 2784 is in the list above and mentioned in the trace for 14780 but doesn't have its own trace.

**Comment by Timka654** [comment] 2020-09-29 21:53
@Forgind This problem maybe exists, i'm not appended @rainersigwald code in first run time

**Comment by pranavkm** [comment] 2020-10-12 17:30
@Forgind do you think this is better tracked in a different repo since the issue isn't specific to `dotnet watch`

**Comment by Forgind** [comment] 2020-10-12 18:04
I suspect this is another version of [AB#1217887](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1217887) and possibly also tracked by https://github.com/dotnet/sdk/issues/13984. If so, I've found a few things I think are feasible candidates for what's going wrong, but I haven't been able to repro it, so I'm not sure.

**Comment by pranavkm** [comment] 2020-10-12 22:02
Thanks. Closing this issue. We can use the other issues to track additional work here.

**Closed by pranavkm** 2020-10-12 22:02 UTC
Labels: External, area-blazor, area-commandlinetools, feature-dotnetwatch, investigate
