### ISSUE TITLE
Publish .Net Framework 2.1 project to App service, failed with error "HTTP Error 502.5 - Process Failure" after install.Net6.0 Preview1.

### ISSUE THREAD

**Issue by jodieliu** [dotnet/aspnetcore#30419] opened 2021-02-24 02:21 UTC
**REPRO CONFIGURATION:** Win 10 20H2 ENU + 16.9 Preview 4 VSE + .NET 6.0 + Feed for 6.0

**.NET Core SDK (CLI) Version:** 6.0.100-preview.1.21077.9
**Latest .NET Core runtime Version:** 6.0.0-Preview.2.21077.2
 
**INSTALL STEPS**

1. Clean machine: Win 10 20H2 ENU
2. Install 16.9 Preview 4 [main-30927.236] VSE
Run preinstall: \\vspreinstall\preinstall\preinstall.cmd 
Install Dev16.9 Preview 4 from: https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/0d6117ace82b0ee3ec0d4f27019c51df7815bf62/f3fb1a11-4dfb-fcc3-1b01-1bc61e081f2c%3bchannels/internal/Preview/bootstrappers/fixed/Enterprise/vs_Enterprise.exe
Select Web workload
3. Install .NET 6.0 from:https://aka.ms/dotnet/net6/dev/Sdk/dotnet-sdk-win-x64.exe
4. Apply feed:  https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

**REPRO STEPS**
1. After .NET 6.0 Preview 1 SDK insatlled, open VS and sign in with account.
2. File > New project> ASP.NET Core Empty > .NetCore 2.1 with check "Run on .Net Framework" checkbox.
3. Right-click project > Publish to App service, the Web App display"HTTP Error 502.5 - Process Failure" in browser.

**ACTUAL**
![image](https://user-images.githubusercontent.com/39819602/108580794-13beda80-7368-11eb-9f49-e9d38dae1cd9.png)

**Comment by jodieliu** [comment] 2021-02-24 02:21
As the below table shows, It does not repro with clean install 16.8

VS configuration | Target framework in csproj after project creation | Does publish work successfully?
-- | -- | --
16.8 (latest released build) | net461 | works
16.9 Preview 4 (clean install) | net461 | works
16.9 Preview 4 + 6.0 Preview 1 | net461 | failed

**Comment by dougbu** [comment] 2021-06-07 21:20
@jodieliu does this issue remain with the latest 6.0 preview release❔

**Comment by v-elenafeng** [comment] 2021-06-16 10:37
@dougbu Yes, this issue reproduces with latest 6.0 Preview 6

**Comment by dougbu** [comment] 2021-07-01 19:07
@halter73

**Comment by dougbu** [comment] 2021-07-01 19:17
@dotnet/aspnet-build @wli3 @dsplaisted @marcpopMSFT I can't think what would be going on here. Not much changed in the 'ASP.NET Core Empty' template between 5.0.0 and 6.0.0-preview1. For example, @halter73's use of new language features came later. Since the template, the target framework, and the VS version aren't changing, that leaves the SDK. But, what about the newer SDK could cause these problems❔

@v-elenafeng is anything similar happening w/ other 6.0 ASP.NET Core templates e.g. 'ASP.NET Core Web App'❔

**Comment by Pilchie** [comment] 2021-07-01 23:18
Can we get the content of the System Event Logs as described in the message?  @shirhatti - any other ideas here?

**Comment by Pilchie** [comment] 2021-07-01 23:20
Maybe the template doesn't set the out of process flag for 2.1 on .NET Framework and it should?

**Comment by BrennanConroy** [comment] 2021-07-01 23:26
Looks like the same issue as https://github.com/dotnet/sdk/issues/18642#issuecomment-871591815

**Comment by dougbu** [comment] 2021-07-01 23:39
> Looks like the same issue as https://github.com/dotnet/sdk/issues/18642#issuecomment-871591815

Should we make this a tracking issue for dotnet/sdk#18642 or close it outright❔

**Comment by v-elenafeng** [comment] 2021-07-02 10:44
@dougbu This issue happening with all the .NET Framework 2.1 projects, including 'ASP.NET Core Empty' template and 'ASP.NET Core Web App' with .NET 6.0 installed, and it works for 6.0 ASP.NET Core templates.
This issue is still repro with .NET 6.0 Preview 6 installed and not a regression from .NET 6.0 Preview 1.

**Comment by dougbu** [comment] 2021-07-02 17:38
> not a regression from .NET 6.0 Preview 1

It is however a regression from .NET 5.0.

**Closed** 2021-07-09 19:00 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, area-infrastructure, feature-installers
