### ISSUE TITLE
Two scroll bars appear at 400% zoom on the page.

### ISSUE THREAD

**Issue by v-akr** [dotnet/aspnetcore#42361] opened 2022-06-23 06:46 UTC
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS;#A11yWCAG2.1;#A11yTCS;#.NET Core[aspnetcore]-Win32-June2022;#.NET Core;#A11ySev2;#WCAG1.4.10;#DesktopApp;#Win11;#Benchmark;#Zoom

### Environment Details:
.NET Core
ASP.NET Core
Operating System: Windows 11 Enterprise 21H2

### Prerequisite:
Set resolution to 1280*1024

### Steps to Reproduce:

1. Open command prompt
2. Create a folder using command "mkdir foldername" e.g. "mkdir BlazorServer"
3. Move to the created directory using command "cd foldername"
4. Run the following command "dotnet new angular -au Individual" and hit enter.
5. Run the following command "dotnet run"
6. Copy the First URL link from Command prompt and copy it
7. Paste it in URL section of Browser and hit Search
8. Browser page will open with above template loaded
9. Register account then login.
10. Tab till "Hello with the userid" and click on it
11. Navigate to Personal data and click on it.
12. Zoom the screen to 400% and observe that there are two scroll bars.

### Actual:
Two scroll bars appear at 400% zoom on the page.

### Expected:
Two scroll bars should not appear at 400% zoom on the page.

### User Impact:
Low vision users will face difficulty to get the information.

**Comment by gfoidl** [comment] 2022-06-23 07:38
Same as https://github.com/dotnet/aspnetcore/issues/42345?

**Comment by HaoK** [comment] 2022-06-24 19:43
Yeah dupe of https://github.com/dotnet/aspnetcore/issues/42345 thanks @gfoidl

**Closed by HaoK** 2022-06-24 19:43 UTC
Labels: area-identity, feature-accessibility
