### ISSUE TITLE
How can I host multiple web apps in one kestresl on Linux?

### ISSUE THREAD

**Issue by ndensan2029arai** [dotnet/aspnetcore#51667] opened 2023-10-26 00:17 UTC
I'm thinking of running multiple web apps from RazorPages on Linux. However, the realization is that the web app needs to be launched with 1Kestrel in one project and assigned a Port. How can I run multiple web apps in one kestrel?

**Comment by Tratcher** [comment] 2023-10-26 15:50
How would you decide which request goes to which app, check the Host name, some header, etc.?

If you must share a port+ip, your choices are either to combine the apps and use Routing to sort it out, or to proxy using something like YARP.
https://microsoft.github.io/reverse-proxy/articles/getting-started.html

**Comment by davidfowl** [comment] 2023-10-26 15:53
@Tratcher do we have a set of samples for YARP? This would be a good one.

**Comment by En3Tho** [comment] 2023-10-26 16:11
I guess this totally depends on what kind of apps you're trying to host together. Obviously you can extract all the relevant hosting parts into extensions, use a single unified project as host, call those extensions etc.

But this only works if those apps do not interfere with each other.

For example one might expect middlewares to run in A -> B sequence and other in B -> A
They can try to add same types to service provider or add with different lifetimes
Or they might use different types but a unified interface

It works only if those aren't apps in fact but carefully written modules which do follow unified requirements and so on.

If you just want to use 1 port only then using YARP as reverse proxyand hosting other apps in standalone modes behind it is a better choice imo.

**Comment by ndensan2029arai** [comment] 2023-10-30 02:35
It seems possible to achieve this by creating a main project for Kestrel and referencing each project of the web application.

**Comment by surayya-MS** [comment] 2023-11-01 16:27
@Tratcher, looks like this is a documentation ask for YARP. Where should we transfer this issue?

**Comment by Tratcher** [comment] 2023-11-01 17:01
@surayya-MS YARP discussion was only conjecture, the original creator @ndensan2029arai wants to solve the issue in a different way using razor class libraries.

**Comment by ndensanmpn** [comment] 2023-11-01 22:36
I've verified and confirmed that it can be realized with Areas. Please close it with this.

**Closed** 2023-11-01 22:41 UTC
Labels: area-blazor
