### ISSUE TITLE
build the solution, can not download the preview sdk

### ISSUE THREAD

**Issue by w152013768** [dotnet/aspnetcore#11461] opened 2019-06-22 01:58 UTC
When I am going to build the solution with the restore.ps, It  will go to error : can not download from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview5-011568/dotnet-sdk-3.0.100-preview5-011568-win-x64.zip. I am in China.
 
Can anyone tell me how to do?

**Comment by mkArtak** [comment] 2019-06-22 05:44
Why are you trying to download the preview5 SDK? Try to download the latest from: https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by w152013768** [comment] 2019-06-23 13:12
> Why are you trying to download the preview5 SDK? Try to download the latest from: https://dotnet.microsoft.com/download/dotnet-core/3.0

I had installed the preview5 SDK, but it still download it and fail to build the solution. What I should do？how do I alter the script named dotnet-install.ps1?

**Comment by mkArtak** [comment] 2019-06-23 19:27
I see now. You were getting the error from the build scripts, and not trying to download the SDK manually.
So you're actually trying to follow https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md and having trouble with that.

@aspnet/build team, any suggestions here?

**Comment by dougbu** [comment] 2019-06-23 19:47
@mkArtak sorry, I have no idea whether we have alternate download locations for https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview5-011568/dotnet-sdk-3.0.100-preview5-011568-win-x64.zip

@w152013768 if you attempt to reach that URL in your browser, what error does it show? (If it succeeds, expand it into the .dotnet/ folder in your clone of this repo.)

**Comment by w152013768** [comment] 2019-06-24 00:30
@mkArtak @dougbu 

I had download the preview5 sdk by reaching that URL in my brower, and expand it into the .dotnet/folder in my clone of this repo, but when I restart run the restore.ps1, it remain going to show the error: downloading the preview5 failed, the process stop again.
Should I alter the dotnet-install.ps1 after expand the zip of preview5 sdk into the .dotnet/folder?

**Comment by dougbu** [comment] 2019-06-24 02:02
@w152013768 changing the dotnet-install.ps1 script should not be necessary as long as the SDK is correctly located in `${repoRoot}/.dotnet`. For this repo, https://github.com/aspnet/AspNetCore/blob/master/eng/common/tools.ps1 checks for `${repoRoot}/.dotnet/sdk/3.0.100-preview5-011568` and will not attempt to download or run dotnet-install.ps1 for the x64 SDK if that folder exists.

This repo actually expects _two_ runtimes. Is restore.cmd now failing to download https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview5-011568/dotnet-sdk-3.0.100-preview5-011568-win-x86.zip (which will be placed in `${repoRoot}/.dotnet/x86`)? You could do the same manual download / install trick to avoid that too.

That said, I'm surprised the scripts (with their 20 minute timeout and 3 retries) fail while a manual download succeeds. Just a guess but is your browser configured with different proxy settings than your system default? (The scripts use the system default proxy -- if any.)

**Comment by w152013768** [comment] 2019-06-24 06:05
@dougbu thank you for your patient answer, I tried to download the sdk for many times in the browser, only one download succeeded.

**Comment by dougbu** [comment] 2020-08-15 00:37
Closing as it seems the problem is a general networking issue

**Closed** 2020-08-16 01:01 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-infrastructure
