### ISSUE TITLE
built-in support for Input file(s) upload

### ISSUE THREAD

**Issue by AhmedAbuelnour** [dotnet/aspnetcore#17056] opened 2019-11-13 07:48 UTC
Blazor really missing an important feature which is the native support for uploading file(s).

**Comment by javiercn** [comment] 2019-11-13 10:12
@AhmedAbuelnour thanks for contacting us.

We know this is a gap, but its also something that can be implemented as a third party component. for reference, see @SteveSandersonMS blog post where he showcases a solution that is published as an external package that can be used until/if we decide to add this to the core framework. https://blog.stevensanderson.com/2019/09/13/blazor-inputfile/

We'll consider this feature during the next release planning period and update the status of this issue accordingly.

**Comment by etherealjoy** [comment] 2020-01-10 07:17
I tried the one from the blog post of @SteveSandersonMS and it is intuitive, but it is not yet migrated to net core 3.1 LTS.

We can continue to use this until the built in solution is ready.

**Comment by mkArtakMSFT** [comment] 2020-01-10 18:27
This is a dupe of https://github.com/dotnet/aspnetcore/issues/12205, which we will be considering for 5.0.

**Closed by mkArtakMSFT** 2020-01-10 18:27 UTC
Labels: area-blazor, enhancement
