### ISSUE TITLE
Invalid project created when name has `&` (ampersand) or ` ` (space) in it

### ISSUE THREAD

**Issue by Eilon** [dotnet/aspnetcore#56765] opened 2024-07-12 21:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. From command line create a template with a name that has an `&` in it, for example:
   * `dotnet new blazor -o "dogscats & web"`
   * `dotnet new blazor -o "dogscatsweb & wasm" -int Auto`
2. And you'll immediately get an error about an invalid project, such as:
   ```
   ...\dogscats & web.csproj(7,30): error MSB4025: The project file could not be loaded. An error occurred while parsing EntityName. Line 7, position 30.
   ```
4. But, even if you fix that, there's a problem with the assets file reference in the generated `App.razor` because it mentions `<link rel="stylesheet" href="@Assets["dogscatsweb & wasm.styles.css"]" />`, which is apparently invalid, and should instead be `<link rel="stylesheet" href="@Assets["dogscatsweb_&_wasm.styles.css"]" />` (note the spaces in the path were changed to underscores)

And then it seems everything is fine.

### Expected Behavior

Any valid template name character should work

### Steps To Reproduce

See above

### Exceptions (if any)

See above

### .NET Version

9.0.100-preview.6.24328.19

**Comment by javiercn** [comment] 2024-07-13 10:41
@Eilon This is a dupe of https://github.com/dotnet/aspnetcore/issues/52196

**Closed by javiercn** 2024-07-13 10:41 UTC
Labels: area-blazor
