### ISSUE TITLE
ASP.NET web core API - incorrect default xml serialization in Swagger

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39064] opened 2021-12-15 19:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ASPNET-web-core-API---incorrect-default/1614627)._

---

I'm using swagger/index page for testing my API. I need both JSON and XML serialization. Json is working fine but the xml serialization generated by swagger contains non-capital letters of node names for capital letter started properties of my [DataContract]. 

```C#
Steps:
1) Add XML serialization formatters:
builder. Services.AddControllers(). AddXmlSerializerFormatters();
2) Data contract class:
    [DataContract]
    public class DataRequest
    {
        [DataMember]
        public DateTime FromDate { get; set; }
        [DataMember]
        public DateTime ToDate { get; set; }
    }
3) Add EF controller with only one Post method:
  [HttpPost]
        public async Task<ActionResult<IEnumerable<DataReply>>> Request(DataRequest dataReply)
        {
            return await _context. DataReply.ToListAsync();
        }

Set break-point on return await at post-method.

4) Run (F5) and Try it out:
Json request (application/json):

{
  "fromDate": "2021-11-13T00:12:13.725Z",
  "toDate": "2021-11-13T00:12:13.725Z"
}

As result, request instance is correct (see attached picture "json serialization in swagger.png")

Xml request (application/xml):
<?xml version="1.0" encoding="UTF-8"?>
<DataRequest>
	<fromDate>2021-11-13T00:09:20.021Z</fromDate>
	<toDate>2021-11-13T00:09:20.022Z</toDate>
</DataRequest>

```
As result, request instance is incorrect - all dates are 01.01.0001 ... (see attached picture "xml serialization in swagger.png")

Obviously, the problem is a incorrect node names - fromDate and toDate. The correct names must be FromDate and ToDate accordingly. The workout is rename these tags manually but much more better to fix the swagger behaviour for XML serialization. 

Thanks a lot.

---
#### Feedback Bot on 11/14/2021, 11:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/15/2021, 11:52 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

**Comment by rafikiassumani-msft** [comment] 2021-12-15 22:59
I tried to reproduce the issue.  Below is an API setup that does not properly render an xml response document in the swagger-ui.  There are two problems: 

1. The Swagger-ui does not generate proper xml response for return of array types
2. API request does not bind properly due to CamelCasing of dates fields

```C#
         // POST api/<ValuesController>
        [HttpPost]
        [Produces("application/xml")]
        [Consumes("application/xml")]  
        public async Task<ActionResult<IEnumerable<DataReply>>> Post([FromBody] DataRequest dataRequest)
 
        {
 
            _dbContext.DataReplies.Add(new DataReply
 
            {
                FromDate = dataRequest.FromDate,
                ToDate = dataRequest.ToDate,
 
            });

            await _dbContext.SaveChangesAsync();
            return await _dbContext.DataReplies.ToListAsync();
        }
 
// Models

    [DataContract]
    public class DataReply
    {
        public int DataReplyId { get; set; }

        [DataMember]
        public DateTime? FromDate { get; set; }

        [DataMember]
        public DateTime? ToDate { get; set; }
    }

    [DataContract]
    public class DataRequest
    {
        [DataMember]
        [Required]
        public DateTime? FromDate { get; set; }

        [DataMember]
        [Required]
        public DateTime? ToDate { get; set; }
    }
```
This results in the following issue in swagger-ui : 

![image](https://user-images.githubusercontent.com/87031580/146277078-a335a7ab-7b0a-4ba9-b43c-292631a4f0ad.png)

I tried to track down the swagger-ui issue and it appears that it's an existing issue with the dependency that Swashbuckle is using for the UI. See the following issue: https://github.com/swagger-api/swagger-ui/issues/4650 · 
The problem happens when the user is expecting an array of objects to be serialized to xml. This is something we might need to figure out a fix by allowing the user to set the main node attribute for lists or Arrays return types. 

For the second issue of CamelCasing in the request that results in improper binding, from my preliminary research, this might be a bug.  When you add the `[Required] attribute, there are validation failures. 

![image](https://user-images.githubusercontent.com/87031580/146277506-6e0446bc-b609-49bd-b205-94b1a3c61bc6.png)

After removing the `[Required]` attribute, the following binding issue happens: 

![image](https://user-images.githubusercontent.com/87031580/146277974-c88a70fa-e692-4ec8-a49d-ddaaa1d9f9c5.png)

**Comment by rafikiassumani-msft** [comment] 2021-12-27 17:47
After some further investigations we found that the binding failures are due to the fact that XML is case sensitive. In the case above Shashbuckle is using the JSON camelCase serialization. You can change the behavior globally by adding the following configuration: 

```c#

builder.Services.Configure<Microsoft.AspNetCore.Mvc.JsonOptions>(opts =>
{
    opts.JsonSerializerOptions.PropertyNamingPolicy = null;

});

```
I will close this issue since there is no further action on our side.

**Closed by rafikiassumani-msft** 2021-12-27 17:47 UTC
Labels: Author: Migration Bot :robot:, area-web-frameworks
