### ISSUE TITLE
Blazor WASM Server Hosted with Azure Signal R errors on WSS connection

### ISSUE THREAD

**Issue by mandalorianbob** [dotnet/aspnetcore#20714] opened 2020-04-10 02:33 UTC
I tried to follow the guidelines for switching from a basic SignalR connection for testing to an actual Azure Signal R Service in a Blazor WASM Hosted app using the Preview 3 bits. This app is just a single page where my users put in results, and these results are sent to a SignalR hub. Whenever I start up the app, it immediately tries to connect to a hub, and all of this works in the normal SignalR scenario.

However, when I switch to Azure Signal R Service, I get the following error in console:
"WebSocket connection to 'wss://[servicename]/client/?hub=resultshub&asrs.op=%2FResultsHub&negotiateVersion=1&asrs_request_id=[requestId]&id=[id]' failed: HTTP Authentication failed; no valid credentials available"

And the connection appears to not work. I'm not trying to authenticate, I don't want to have any authentication. I did try to add some earlier - but I've looked pretty thoroughly and I believe scoured any references to authentication or authorization from my app.

I've tried all manner of combination of different configuration calls, but I'll go through them.
Under ConfigureServices
`services.AddSignalR().AddAzureSignalR();`
I also tried it with ServerStickyMode = required, which I've since turned off, since I'm not sure it's something I need.

In terms of what's in Configure
`app.UseAzureSignalR(routes =>
            {
                routes.MapHub<ResultsHub>("/ResultsHub");
            });`

 
`app.UseEndpoints(endpoints =>
`            {
`                endpoints.MapControllers(); 
`
`                endpoints.MapHub<ResultsHub>("/ResultsHub");  
`
`                endpoints.MapFallbackToFile("index.html");  
`
            });

I've tired not having the UseAzureSignalR, having the MapHub only in UseAzureSignalR, having it in both, not having the routes in UseAzureSignalR but still making the call, etc. 

Nothing seems to stop this strange WSS error.

Thanks!

**Comment by BrennanConroy** [comment] 2020-04-10 02:38
This is a dupe of https://github.com/dotnet/aspnetcore/issues/18697

Auth is needed when connecting to the Azure SignalR Service. The client gets it during negotiate and handles that automatically for you. (Except for this bug where it doesn't). As a "workaround" you can use LongPolling until the issue is fixed.

**Closed** 2020-04-13 13:41 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
