### ISSUE TITLE
"Minimal API" does not handle static files

### ISSUE THREAD

**Issue by JohnyL** [dotnet/aspnetcore#33113] opened 2021-05-28 10:06 UTC
As announced [here](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#introducing-minimal-apis), ASP.NET Core introduces minimal API for creating web apps. I decided to try it out with two simple test apps.

## 1. Serving plain `index.html` file
Here's the [sample project](https://github.com/JohnyL/minapi_index_html). Does not work. I get error: `This localhost page can't be found`.
Upon investigation I found out that `WebRootPath` is the same as `ContentRootPath` (according to [web root definition](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-5.0&tabs=windows#web-root), web root path is, by default, content path plus `wwwroot`):
```csharp
var builder = WebApplication.CreateBuilder(args);
var contentRootPath = builder.Environment.ContentRootPath; // C:\minapi
var webRootPath = builder.Environment.WebRootPath;         // C:\minapi
```
Changing `WebRootPath` to `C:\minapi\wwwroot` didn't work:
```csharp
builder.Environment.WebRootPath = Path.Combine(builder.Environment.ContentRootPath, "wwwroot");
```
## 2. Razor Pages
This time I have included Razor Pages ([sample project](https://github.com/JohnyL/minapi_razor_pages)). This time things got interesting: the razor page was successfully generated, it appeared in browser, but neither Bootstrap file nor JavaScript file were served!
![image](https://user-images.githubusercontent.com/7391680/119964401-d9418b00-bfb1-11eb-9cd5-8160087c5347.png)
![image](https://user-images.githubusercontent.com/7391680/119964451-e8283d80-bfb1-11eb-9952-26cf77098da8.png)

### Further technical details
- ASP.NET Core version: 6.0.100-preview.4.21255.9
- Include the output of `dotnet --info`
  <details>
  <summary>Output</summary>

  > .NET SDK (reflecting any global.json):
     Version:   6.0.100-preview.4.21255.9
     Commit:    950e4949a7

  > Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19043
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\

  > Host (useful for support):
    Version: 6.0.0-preview.4.21253.7
    Commit:  bfd6048a60

  > .NET SDKs installed:
    5.0.102 [C:\Program Files\dotnet\sdk]
    5.0.202 [C:\Program Files\dotnet\sdk]
    5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
    6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

  > .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.0-preview.4.21254.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

- The IDE (VS / VS Code/ VS4Mac): Visual Studio Community 2019 Preview 16.11.0 Preview 1.0

**Comment by DamianEdwards** [comment] 2021-05-28 16:58
Likely dupe of #32415. See that issue for workaround until a preview with the fix ships.

**Comment by JohnyL** [comment] 2021-05-28 19:42
@DamianEdwards Thanks, Damian, the workaround worked perfectly! 😎

**Closed** 2021-05-28 20:46 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime
