### ISSUE TITLE
 Why is Configuration a public property in Startup class in asp.net core?

### ISSUE THREAD

**Issue by YongqingYu-qq** [dotnet/aspnetcore#23139] opened 2020-06-19 08:43 UTC
### Is your feature request related to a problem? Please describe.
As [Microsoft's official tutorial](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.1#the-startup-class), the **IConfiguration** class will be injected into the starup.cs class in asp.net core. 

Usually, unless we have special needs when injecting fields, the **private** modifier is generally used by default, but the template of asp.net core is used by **public** modifier. 

### Describe the solution you'd like
What I want to know is, why should it be set to public instead of private, is there any special manifestation and demand?

### Additional context
```
  public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

     }
```

**Comment by javiercn** [comment] 2020-06-19 10:06
Dupe of https://github.com/dotnet/aspnetcore/issues/23144

**Closed by javiercn** 2020-06-19 10:06 UTC
