### ISSUE TITLE
File blazor.boot.json contains different hashes after recompile project in Release Mode

### ISSUE THREAD

**Issue by abbatepabloo** [dotnet/aspnetcore#20524] opened 2020-04-03 19:21 UTC
### Describe the bug
I'm investigating how Blazor handles assembly caching and I'm not sure if there is a bug or not.

Every time I recompile an Assembly Blazor project  (in **RELEASE** mode) all hashes contained in **\bin\Release\netstandard2.1\wwwroot_framework\blazor.boot.json** file are updated with new values, no matter if I modified the source code or not.
This modification forces **WebAssemblyResourceLoader** to reload all cached assemblies in the browser after a build.

I would like to know if I'm the only one facing this behaviour (because of my environment) or if someone is having the same results. 
If the last case: _Is this a normal behaviour? I think assemblies should be cached while they don't change their content._

Thanks in advance!

### To Reproduce
a) Using Visual Studio, create new Blazor Assembly App (not ASP.NET Core hosted)
b) Build it using **RELEASE** mode.
c) Check file **\bin\Release\netstandard2.1\wwwroot_framework\blazor.boot.json**. For example: hash for assembly **“Microsoft.AspNetCore.Blazor.HttpClient.dll”** is (in my case) **“sha256-rG0but8jR1vtYFE5orZy51QUgLfssOF1zj+GBQWaCE8=”**
d) Recompile the project
e) Now, the same assembly has a new hash: **“sha256-qGCGcP51kxvi3yGHDnmKeMiQscwABPurn9CPyzz7jqA=”**

If you execute the application, all assemblies will be cached (because this is your first load). But, if you rebuilt this project and executed again all cached assemblies will be ignored (because new hash in blazor.boot.json) and downloaded again in the browser. You can verify this watching the network monitor in the browser.

### Further technical details
- ASP.NET Core version: 3.1.2
- Include the output of `dotnet --info`

SDK de .NET Core (reflejando cualquier global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio for Windows 16.6.0 - Preview 2.1 - Spanish 
Windows 10 Pro - 64 bits - version 1909

**Comment by javiercn** [comment] 2020-04-03 20:11
@abbatepabloo thanks for contacting us.

That is expected. If you switch from debug to release, you are switching from debug assemblies to release assemblies. The contents of the assemblies change and that causes the manifest to change.

Does that make sense?

**Comment by javiercn** [comment] 2020-04-03 20:12
Nevermind, I misunderstood what you were talking about.

The reason the hashes change is that the linker produces new outputs in release with a slightly different content and that makes the hashes different.

**Comment by abbatepabloo** [comment] 2020-04-03 20:25
Hi Javier,

Thanks for your fast response. I understand what you are saying.
One thing I did was to calculate the hash of both assemblies (before and after building) and, according to my test, they have the same hash. I'm only taking into account the file content (not any attribute)

Please, take a look of this:

```
byte[] tempFile = File.ReadAllBytes(@"C:\Preserved\ClassLibrary1.dll");
byte[] hashTemp = MD5.Create().ComputeHash(tempFile);

byte[] binFile = File.ReadAllBytes(@"C:\Users\Pablo\source\repos\BlazorApp1\BlazorApp1\bin\Release\netstandard2.1\wwwroot\_framework\_bin\ClassLibrary1.dll");
byte[] hashBin = MD5.Create().ComputeHash(binFile);

Console.WriteLine($"Hash File 1:{Convert.ToBase64String(hashTemp)}");
Console.WriteLine($"Hash File 2:{Convert.ToBase64String(hashBin)}");
var equals = tempFile.SequenceEqual(binFile);
Console.WriteLine($"Are equals:{equals}");
```

The potencial problem I see here is that the cache is not going to work effectively because any minimal change in your code will force browser to download the whole package, including framework assemblies. 

Do you agree? 
Maybe I missing something here.

**Comment by captainsafia** [comment] 2020-04-13 22:24
Thanks for reporting this issue. I attempted to repro this with the latest developments bits of Blazor and was not able to do so.

I created a new blazorwasm project.

```
$ dotnet new blazorwasm -o bootjsontest
```

I ran the build step in a release configuration twice in a row.

```
$ dotnet build -c Release
$ dotnet build -c Release
```

The SHAs generated for the DLLs in both these builds were the same. See [this](https://gist.githubusercontent.com/captainsafia/1e16804a923ba8cd1fe44ab4c135c3a8/raw/7cd3ff6a370ae014d822447f9dc4e99af8ef58c1/blazor.boot.1.json) and [this](https://gist.githubusercontent.com/captainsafia/1e16804a923ba8cd1fe44ab4c135c3a8/raw/7cd3ff6a370ae014d822447f9dc4e99af8ef58c1/blazor.boot.2.json).

I'm going to go ahead and close this as no-repro for now. When preview4 is released (soon!), please see if you can reproduce the issue in that version and re-open this bug.

**Closed by captainsafia** 2020-04-13 22:24 UTC
Labels: area-blazor, blazor-wasm, investigate
