### ISSUE TITLE
Automatically upload VS nupkgs for 2.1 and 2.2.

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#13153] opened 2019-08-15 00:48 UTC
Part of VS SDK simplification, we should upload these packages automatically to the correct VS feed.
cc @johnbeisner

**Comment by dougbu** [comment] 2020-10-12 18:26
Dupe of dotnet/aspnetcore-internal#3387

**Closed by dougbu** 2020-10-12 18:26 UTC
Labels: area-infrastructure
