### ISSUE TITLE
build.cmd fails on Windows 10 for release/5.0

### ISSUE THREAD

**Issue by neeraj9** [dotnet/aspnetcore#35369] opened 2021-08-16 06:44 UTC
I don't know if there is a better way to build aspnetcore from source on Windows 10. I followed the following steps, while the build fails on my system.

System Information:
```
OS: Windows 10
Visual Studio Installed: VS 2019, VS 2022 (preview-3)
dotnet: v5.0.206

```

```powershell
git clone https://github.com/dotnet/aspnetcore ac
cd ac
git checkout release/5.0
.\build.cmd
```

Errors:

````
Build FAILED.

C:\d\ac\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj(31,3): error MSB4019: The imported project "C:
\d\ac\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm t
hat the expression in the Import declaration "C:\d\ac\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v160\\Micr
osoft.Cpp.Default.props" is correct, and that the file exists on disk.
C:\d\ac\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj(31,3): error MSB4019: The imported project "C:
\d\ac\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm t
hat the expression in the Import declaration "C:\d\ac\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v160\\Micr
osoft.Cpp.Default.props" is correct, and that the file exists on disk.
C:\d\ac\src\Servers\IIS\AspNetCoreModuleV2\CommonLibTests\CommonLibTests.vcxproj(33,3): error MSB4019: The imported pro
ject "C:\d\ac\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. C
onfirm that the expression in the Import declaration "C:\d\ac\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VC\v1
60\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
...
````

Interestingly there following folder exists, but the props mentioned is do not exist and neither the leaf folders.

````powershell
C:\d\ac\.tools\msbuild\16.5.0-alpha\tools\MSBuild\Microsoft\VisualStudio\v16.0
````

**Comment by BrennanConroy** [comment] 2021-08-16 15:32
Did you follow the build instructions that help you install visual studio with the correct components (like C++)?
https://github.com/dotnet/aspnetcore/blob/release/5.0/docs/BuildFromSource.md

**Comment by neeraj9** [comment] 2021-08-18 16:27
Thanks @BrennanConroy, I did see that and as per https://github.com/dotnet/aspnetcore/blob/release/5.0/docs/BuildFromSource.md#building-on-command-line tried to run build.cmd (as suggested) without success. There is some dependency issue. Take a look at the last part of my description (earlier) and note that the MSBuild path is bit different.

**Comment by wtgodbe** [comment] 2022-02-07 22:41
@neeraj9 sorry for the delayed response - can you try running https://github.com/dotnet/aspnetcore/blob/release/5.0/eng/scripts/InstallVisualStudio.ps1 from the command line? This error usually means you're missing a native component that comes from VS.

**Comment by dougbu** [comment] 2022-02-24 22:36
@neeraj9 thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2022-02-24 22:36 UTC
Labels: area-infrastructure
