### ISSUE TITLE
Cannot trigger blazor events with elements

### ISSUE THREAD

**Issue by MichaelAGill** [dotnet/aspnetcore#54423] opened 2024-03-08 01:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Events on elements aren't triggering. I can't hit a breakpoint in the event function and the console log doesn't write. I have isolated this issue to a default .net 8 blazor web app project. I added a button to the Home.razor with an onclick event. That event just outputs to the console a string... However this does not trigger when I run the app and click the button.

![image](https://github.com/dotnet/aspnetcore/assets/46706721/4bdc7cfa-e82d-4028-a346-a560acc15db0)

I have reinstalled visual studio. Restarted my machine and tried with numerous elements. But currently I cannot get events to work at all.

### Expected Behavior

When I click the button, the event should trigger and I hit my break point and then I should also see the console.writeline appear in the console.

### Steps To Reproduce

Create a default .NET 8 blazor web app project.
Go to Home.razor
add a button with an onclick event.
set the event to write to the console
add a breakpoint to the function
run the application on localhost
click the button

### Exceptions (if any)

No exception. Just nothing happens where it should.

### .NET Version

8.0.200

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/46706721/ee554482-aa7e-4f97-b5d0-b02f621271f3)
![image](https://github.com/dotnet/aspnetcore/assets/46706721/63a4a663-adb9-4126-b247-8ad2f6a8878e)

I have tried clicking the button within Vivaldi, Chrome and Edge. No difference between any browser.

**Comment by MichaelAGill** [comment] 2024-03-08 01:28
I will also show you my csproj and list of sdks installed
![image](https://github.com/dotnet/aspnetcore/assets/46706721/474cfbe0-3061-4bc2-a524-a2c0071d143c)

**Comment by MackinnonBuck** [comment] 2024-03-11 16:33
Thanks for reaching out.

In order for event handlers to run, the app needs to be configured to use one of the interactivity modes (Server, WebAssembly, or Auto). These options are available when you create a project from the "Blazor Web App" project template, or from the `dotnet` CLI via the `-int` option.

For more information, please see https://learn.microsoft.com/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0.

Closing as by design.

**Closed by MackinnonBuck** 2024-03-11 16:33 UTC
Labels: area-blazor

**Comment by Yashuaa** [comment] 2025-04-05 15:49
Shitty answer and shitty design by Microsoft. This should not be designed to default to static rendering. What moron at MSFT decided that was a good idea?
