### ISSUE TITLE
The error does not reported in console

### ISSUE THREAD

**Issue by kant2002** [dotnet/aspnetcore#5606] opened 2018-10-08 04:25 UTC
I attempt to create simple Blazor JS interop for vibration API. During testing in Edge I encounter following problems:
1. If proxy function could not be accessed via `window` then error silently eaten.
2. Since I use `navigator.vibrate` which is not supported by Edge it produce error `SCRIPT438: Object doesn't support property or method 'vibrate'` which again silently eaten. 

In Chrome, 
1. the first error is properly captured and displayed in the browser console. 
2. I attempt to simulate second error in Chrome by calling `navigator.vibrate2`, it properly reported as `Error: Microsoft.JSInterop.JSException: navigator.vibrate2 is not a function`

Initially I thought that this is due to https://github.com/dotnet/jsinterop/blob/master/src/Microsoft.JSInterop.JS/src/Microsoft.JSInterop.ts#L159 not bening wrapped in try/catch but this properly wrapped in the `_mono_wasm_invoke_js_marshalled` and in Edge this code is working. So seems to be any unhandled exception in the WASM is swallowed by the Edge. I have experience similar error when playing with different application.

**Comment by aguacongas** [comment] 2019-06-13 06:27
JsRuntime deserialization exception are'nt reported too

### To Reproduce
1. Using Version 3.0.0-preview6
2. For sample. create an API returning a null-able bool
    Create a class mapping the API result but with a non null-able bool instead of the null-able one
3. Call the API returning a null bool
4. Nothing is logged, nothing is returned

### Expected behavior
The exception should be logged in the browser console

### Additional context
The exception wasn't throw in previous version and false was return

**Comment by SteveSandersonMS** [comment] 2020-10-14 14:19
Since the supported version of Edge is now based on Chromium, it's no longer feasible for this still to exist as an Edge-specific problem, so I'll close this.

If anyone can still repro it on a supported browser please let us know.

**Closed by SteveSandersonMS** 2020-10-14 14:19 UTC
Labels: area-blazor, bug
