### ISSUE TITLE
Blazor Navigation Manager browsing back

### ISSUE THREAD

**Issue by elamje** [dotnet/aspnetcore#19487] opened 2020-03-02 02:05 UTC
### Describe the bug
When using NavigationManager to move between pages, with <base href="~/"/> set in the layout <head>, every single navigation action has a brief flash back to the home page before it successfully loads the next page. It is almost imperceptible, but it certainly isn't the expected behavior of a production app.

### Further technical details
.Net core 3.1.100

**Comment by mkArtakMSFT** [comment] 2020-03-02 17:28
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by elamje** [comment] 2020-03-02 21:23
I don't have the capacity to reproduce this. I will point you to an issue raised by a Microsoft person that seems to be the only person aware of this issue. https://github.com/dotnet/AspNetCore.Docs/issues/15271

The issue is exactly as he described, but the only guidance we get as users is a huge amount boiler plate to prevent this from happening. I want to resolve the issue and help if possible, but I simply cannot try to strip down my 30 page app to the essentials right now. I hope that makes sense.

Thanks

**Comment by mkArtakMSFT** [comment] 2020-03-03 17:38
Without a repro we won't be able to do much here, as we can't reproduce this. Closing for now. If others will hit the same issue we'll get new issues filed and will investigate then.

**Closed by mkArtakMSFT** 2020-03-03 17:38 UTC
Labels: Needs: Attention :wave:, area-blazor, investigate
