### ISSUE TITLE
Microsoft.NET.Sdk.StaticWebAssets.targets unable to publish when static web assets been removed after build phase

### ISSUE THREAD

**Issue by doggy8088** [dotnet/aspnetcore#56755] opened 2024-07-12 03:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have an ASP․NET Core Web API project. I'd like to add front-end files to the `wwwroot` folder during publish the project to the output directory.

1. Assume that I have a `wwwroot\.gitkeep` file in the project.
2. During `dotnet build`, no files will be copy to the `wwwroot\` folder.
3. I defined a Target to remove all files from `wwwroot\` folder and copy all related files from another folder to the `wwwroot\` folder which run before `StaticWebAssetsPrepareForPublish` target.

    ```xml
    <Target Name="NpmInstall" BeforeTargets="NpmRunBuild" Inputs="Client\package.json" Outputs="Client\node_modules\.package-lock.json">
      <Exec Command="npm install --force" Condition="'$(RestorePackagesWithLockFile)' != 'true'"
        WorkingDirectory="./Client" />
    </Target>
    <Target Name="NpmRunBuild" BeforeTargets="StaticWebAssetsPrepareForPublish" Inputs="Client\package.json" Outputs="wwwroot\index.html">
      <Exec Command="npm run build:dev" WorkingDirectory="./Client" Condition="'$(Configuration)' == 'Release' and '$(EnvironmentName)' == 'Development'" />
      <Exec Command="npm run build" WorkingDirectory="./Client" Condition="'$(Configuration)' == 'Release' and '$(EnvironmentName)' == 'Production'" />
    </Target>
    ```

4. When I run `dotnet publish`, I will get an error like this: `error MSB3030: Could not copy the file "D:\a\1\s\my-project\wwwroot\.gitkeep" because it was not found. [D:\a\1\s\my-project\my-project.csproj]`.

It seems all files existed in the build phase can't be removed during publish.

### Describe the solution you'd like

I'd like to have a feature that can add/remove static files to the `wwwroot` folder during publish.

### Additional context

N/A

**Comment by javiercn** [comment] 2024-07-13 10:47
@doggy8088 thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/38445

We don't recommend putting the outputs from your build where the inputs live, that causes serious problems to the build.

You can use the JavaScript project in Visual Studio to have all your JavaScript and build logic in one place and have ASP.NET Consume it. This is an old project that I have https://github.com/javiercn/EsProjRclIntegrationWebApp and might need some tweaking, but it's the most straightforward way to do this.

**Comment by doggy8088** [comment] 2024-07-13 15:07
@javiercn The https://github.com/javiercn/EsProjRclIntegrationWebApp project seems closed. I see HTTP 404 for the link.

**Closed** 2024-07-14 17:58 UTC
Labels: question, area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved
