### ISSUE TITLE
ValueTask EventCallback Support

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspnetcore#55154] opened 2024-04-16 01:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Just That i don't have anything just valueTask cause i hate this

```razor
<MyButton OnClick="async () await ValueTaskMethod()">Content</MyButton>
<button @onclick="async () await ValueTaskMethod()">Content</button>
```

### Describe the solution you'd like

```razor
<MyButton OnClick="ValueTaskMethod">Content</MyButton>
<button @onclick="ValueTaskMethod">Content</button>
```

**Comment by javiercn** [comment] 2024-04-16 09:29
@wisamidris7 thanks for contacting us.

This is not something we plan to add for the time being. It doesn't improve much because we need to wrap the ValueTask inside a Task (so no perf gains) and can be done just by calling `.AsTask()` no need for the async/await bits.

If you really want it, you can add this yourself in your app as in the issue mentioned below.

Dupe of https://github.com/dotnet/aspnetcore/issues/41946

**Closed** 2024-04-16 09:30 UTC
Labels: question, area-blazor, :heavy_check_mark: Resolution: Answered
