### ISSUE TITLE
An assembly specified in the application dependencies manifest (appname.deps.json) was not found:     package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'

### ISSUE THREAD

**Issue by ghost** [dotnet/aspnetcore#3215] opened 2018-06-10 02:23 UTC
I'm trying to run this brand new aspnet 2.1 app -- that I built -- on WIndows bash using .netcore 2.1. And I get the following error:

An assembly specified in the application dependencies manifest (AutoFaqRestApi.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'

I do not have anything to do with ApplicationInsights. And I have not explicitly added it anywhere to my project. How can I get rid of it? Or is this references by the aspnet itself?

**Comment by jesaremi** [comment] 2018-06-10 16:21
Seems to be a duplicate of https://github.com/dotnet/coreclr/issues/13542

**Comment by vlmironoff** [comment] 2018-06-16 16:47
I have the same issue.
I have installed Core SDK v2.1.300, Core Runtime v2.1.0 and Core Hosting Environment on the brand new target server (Windows Server 2012 R2).
Deploying my .Net Core v2.0 app (Microsoft.AspNetCore.All v2.0.8)

Figured temporary workaround - choose target runtime to anything else other than 'Portable':

![image](https://user-images.githubusercontent.com/17910418/41500589-980bfa94-7162-11e8-9bf9-0d74dd2811f0.png)

This will inflate your app size however.
Microsoft, please double check the .Net Core SDK v2.1.300 build for missing libs that should have been included.

**Comment by Kritner** [comment] 2018-07-03 17:47
Having this issue as well on a console application with the following command:

`dotnet publish -c Release`

Target server `dotnet --info`:

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Getting the following error at runtime:

```
Error:
  An assembly specified in the application dependencies manifest (MyProject.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml
```

**Comment by Eilon** [comment] 2018-07-13 23:30
@pakrym - any idea on this?

**Comment by warren-lockhart** [comment] 2018-07-20 10:56
I have a very similar issue on an Amazon EC2 running WIndows Server 2016, where if I do anything other than publish a self-contained app (i.e. with runtime win-x64) I receive an error. This is even the case when I deploy with <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>, and in this case the error is:

An assembly specified in the application dependencies manifest (XTag.API.deps.json) was not found:
    package: 'System.Security.Cryptography.Cng', version: '4.5.0'
    path: 'runtimes/win/lib/netcoreapp2.0/System.Security.Cryptography.Cng.dll'

I don't know why the deps.json has specified this runtimes path, since I can see this exact dll in the site root. The deps.json file is generated, so is there any way to force it to look in the local directory first?

It's possible that installing the sdk on the server will allow me to ship a smaller package, but I'm a bit confused as to why you would need to install _an sdk_ when you're not doing any development on the server - why does the sdk give you dlls which the runtime doesn't?

Deploying a self contained app works, but it's very frustrating to be forced to deploy a much larger package just because somehow the dotnet core runtime on the Server is incomplete. Is there any clean solution for this, or do we have to wait for a later version of dotnet core for these bugs in common deployment scenarios to be fixed?

Just to emphasise, the publish command which works is:
dotnet publish XTag.API.csproj -c Release -f netcoreapp2.0 -r win-x64 -o site

and the one which doesn't is:
dotnet publish XTag.API.csproj -c Release -f netcoreapp2.0 -o site

Also note that I'm not doing anything specific with cryptography.

**Comment by exlnt** [comment] 2018-07-29 20:58
I am running into this exact same error message!

I have been building a Asp.Net Core 2.1 MVC web app for several months on two differnt windows PCs. I have been able to code, debug and test this app hundreds of times on both PCs without issue. On the same PC where I was coding and testing all day Friday without any issues, Saturday all of a sudden I keep getting  HTTP Error 502.5 - Process Failure error when I build and run the app from VS and IIS. I have read so many postings for this error, nothing seems to work! This has happened in the past a few times and all I did was restart my PC and then it seemingly went away. I am completely stumped as to how to get past this error. I have now lost two days and counting to this issue! 

I published the app to my local IIS instance and ran the app there and I get the same error message from there too! The other real frustrating part is, I cannot get the AspNetCore logs to generate anything from IIS site. Here is the web.config setting for logs:

`aspNetCore processPath=".\Remodel21.Web.Mvc.exe" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />`

When I look at the event viewer on my PC, I keep seeing the error message below each time I get the 502.5 error.

`Application 'MACHINE/WEBROOT/APPHOST/DOTNETCORE21' with physical root 'C:\inetpub\wwwroot' failed to start process with commandline 'C:\inetpub\wwwroot\Mvc.exe ', ErrorCode = '0x80004005 : 0.`

I get this error, when I run my app from IIS or VS2017. I have tried the following "solutions" others have used and NONE of them have fixed my issue!!
1) Edit csproj file with below setting:
`<PropertyGroup>
  <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
</PropertyGroup>`
2) Update Windows .Net Core SDK version. I installed  .NET Core SDK 2.1.302 and retried. No change!
3) I have completed deleted my IIS app, folder and all contents. I also completely deleted my all my source code and took a fresh copy from my GIT repo. Then did a clean solution and build solution. Then I published the app to my local IIS folder and I still get the exact same error! 

Again let me reiterate everything thing was working perfectly on Friday July 27 on this same PC. I was coding and testing on this very PC all day long on Friday and not a single issue running the app! Since Saturday morning, I cannot for the life of me get past this error! To say I am completely exasparated is an understatement!! I am an independent developer and work alone so I dont have a "Team" or anyone else to turn to.

**Comment by exlnt** [comment] 2018-07-29 21:15
I just tried the solution on my other PC and I'm getting the exact same error message logged on that PC too. :-(

**Comment by mmulhearn** [comment] 2018-10-23 14:02
I'm seeing this as well running ASP.NET Core 2.1.  Running locally through IIS.  I have two apps using the same nugets.  One works fine, the other gives me this in my log file:

`Error:
  An assembly specified in the application dependencies manifest (Users.Web.Api.deps.json) was not found:
    package: 'AutoMapper', version: '7.0.1'
    path: 'lib/netcoreapp2.0/AutoMapper.dll'
`

**Comment by dropsonic** [comment] 2019-01-28 00:43
Have the same issue with Windows Server 2016 on AWS and a console app on .NET Core 2.0 / 2.2.
Tried to publish it for win-x64, but that didn't help.

**Comment by yanniskonstas** [comment] 2019-02-04 12:12
I'm trying to deploy to GCP and I get a similar error: (**dotnet --version: 2.1.500**)

`Updating service [default] (this may take several minutes)...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
Error: An assembly specified in the application dependencies manifest (MY-APP-NAME.deps.json) was not found:
    package: 'AspNetCoreRateLimit', version: '2.1.0'
    path: 'lib/netstandard1.6/AspNetCoreRateLimit.dll'`

My MY-APP-NAME.csproj:

`<Project Sdk="Microsoft.NET.Sdk.Web"> 
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>    
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App"/>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All"/>
   ...
    <PackageReference Include="AspNetCoreRateLimit" Version="2.1.0"/>
   ...
  </ItemGroup>
</Project>`

**Comment by Eilon** [comment] 2019-02-05 17:08
@pakrym / @pranavkm - any ideas on what might cause this or how to diagnose?

**Comment by pakrym** [comment] 2019-02-05 17:14
@Eilon I remember seeing similar issues a long time ago but can't remember the cause. `csproj` looks reasonable. Repro app would help to diagnose the issue here.

**Comment by y123321** [comment] 2019-03-27 18:34
something that resembles that happened to me, there was another project (.net framework) in the solution and it was referenced by the .net core project. I've deleted the project from the solution, and after that I've started seeing this error when trying to publish. It was solved by re-adding the other project to the solution, referencing it again, removing the reference from the references window and only then deleting the project from the solution explorer. It appears that there is an issue with removing the referenced project from the manifests when dependencies are deleted. In a case of a nuget like application insights, I would try removing it using the nuget manager or the package manager console. Anyway, at least in my case it looks more like a bug in visual studio more than a bug in .net core.

**Comment by tomRedox** [comment] 2019-05-21 07:51
I had this with an IIS deployment on a Windows Server 2016 VM after installing .NET Core 3 Preview and running my first Core 3 web app.  After lots of IIS restarts and a huge amount of faffing with code (because I thought the issue was there) it finally occurred to me to restart the server, which then magically fixed it.   

I could here the words "have you tried turning it off and on again" ringing in my ears...

**Comment by stevebroshar** [comment] 2019-11-13 20:51
Had similar error:
Error: An assembly specified in the application dependencies manifest (ISS.API.deps.json) was not found: package: 'System.Diagnostics.DiagnosticSource', version: '4.5.1' path: 'lib/netstandard1.3/System.Diagnostics.DiagnosticSource.dll'

Problem was due to a small change to dependencies in csproj file. That resulted in more files to deploy. Modified installer to include the new files.

**Comment by BrennanConroy** [comment] 2021-06-02 20:09
Closing as this issue is old and hasn't had any traffic.

**Closed by BrennanConroy** 2021-06-02 20:09 UTC
Labels: area-runtime
