### ISSUE TITLE
[Blazor] Using the Blazor event syntax with deeply nested tags does not parse correctly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32502] opened 2021-05-07 19:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Using-the-Blazor-event-syntax-w/1411195)._

---
[severity:It bothers me. A fix would be nice]
Japanese people who are not good at English, so I will write both the original and translated English.
(original:Japanese)
If you use the {@on DOM EVENT}="{DELETE}" syntax on four or more nested tags, the entire file will not parse correctly.
(translation:English)
If use the @on {DOM EVENT} = "{DELEGATE}" syntax for 4 or more nested tags, the entire file will not be parsed correctly.
! Screenshot 2021-04-30 101457.png] (https://aka.ms/dc/image?name=B451a915055274a549f1c3ce8b8e5c8ce637553424357198336_%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88_2021-04-30_101457.png&tid=451a915055274a549f1c3ce8b8e5c8ce637553424357198336)
(Japanese)
Nests below 3 are parsed successfully.
(English)
Nests of 3 or less will parse normally.
! Screenshot 2021-04-30 101526.png] (https://aka.ms/dc/image?name=Bdbf365aa6bc54f03a3a502857c022685637553425066570964_%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88_2021-04-30_101526.png&tid=dbf365aa6bc54f03a3a502857c022685637553425066570964)
(Japanese)
Compilation and execution seem to be normal even if it is deeply nested, so we recognized it as a bug in the analysis function.
I want to use it for deeply nested tags in my project, so it's a problem that the analysis doesn't go right.
(English)
Since compilation and execution seem to be normal even if they are deeply nested, I recognized it as a bug in the analysis function.
I want to use it for deeply nested tags in my project, so improper parsing can be annoying.

---
#### Feedback Bot on 4/29/2021, 08:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ka-jpn** [comment] 2021-05-09 09:11
I created https://github.com/ka-jpn/BugDescription
There is a project with minimal changes.

**Comment by javiercn** [comment] 2021-05-10 10:49
This is the translation for the readme in the repo according to Bing maps
```
Project to explain the defect

Blazor webassembly project created with hosted only Index.razor.

An error in the Index.razor syntax appears in the error list window. If you delete @onkeyup line 3 = "KeyUp" or delete the div on line 5, the error disappears.

@onkeyup instead of @onkeydown, you will get an error as well. The @on is not valid in the {DOM EVENT}="{DELETE}" syntax. The same is not true for non-Blazor webassembly + hosted.
```

**Comment by mkArtakMSFT** [comment] 2021-05-10 16:41
We've looked into your repro app and VS shows invalid syntax error. It looks like you have an invalid self-closing div tag `</div>`. Removing it fixes the issues.
Unfortunately we couldn't see the errors that you observe so maybe something is wrong with your VS. We recommend updating to the latest release of VS.

**Closed by mkArtakMSFT** 2021-05-10 16:41 UTC
Labels: Author: Migration Bot :robot:, Needs: Attention :wave:, area-blazor, area-razor.compiler, feature-razor.language, investigate

**Comment by ka-jpn** [comment] 2021-05-11 01:35
The root cause seems to be that I didn't know that "`<div />`is not valid".
However, if you didn't use the @on{DOM EVENT}="{DELEGATE}" syntax, wouldn't get an error, and if did, would get an error. the cause was hard to understand.

In my project I was trying to use `<div ~~ />` as an area with size and color. 
By changing to `<label ~~ />`, the error no longer occurs.

There was a misunderstanding due to my lack of study,
I want output an error even if don't use @on{DOM EVENT}="{DELEGATE}".

I updated https://github.com/ka-jpn/BugDescription#readme

I'm sorry, and thanks.
I am looking forward to further development in the future.
