### ISSUE TITLE
Blazor WebAssembly release-published app still tries to load a .pdb

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#18712] opened 2020-01-31 16:29 UTC
I don't know why, but for hosted apps (maybe standalone too if you reference some other class library, didn't check), after publishing in release mode it still tries to fetch `MyApp.Shared.pdb` at runtime, causing the server to return a 404. It correctly does *not* try to fetch `MyApp.Client.pdb`, so I don't know why it does try to fetch `MyApp.Shared.pdb`.

This is problematic because:

 * It's an unnecessary HTTP request
 * It's distracting to see what appears to be an error in the dev tools

Also, the build output places `MyApp.Shared.pdb` in `_framework\_bin` on disk, even though the web server is (correctly) configured not to serve it.

Looks like something is mistaken in our publish process. In release builds, there should be no `.pdb` files emitted to the publish output, and none referenced from `blazor.boot.json`.

**Comment by mkArtakMSFT** [comment] 2020-01-31 17:25
Dupe of https://github.com/dotnet/aspnetcore/issues/18655

**Closed by mkArtakMSFT** 2020-01-31 17:25 UTC
Labels: area-blazor, blazor-wasm
