### ISSUE TITLE
Dotnet watch run broken with arguments

### ISSUE THREAD

**Issue by garrettlondon1** [dotnet/aspnetcore#51921] opened 2023-11-07 19:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/sdk/issues/32233

dotnet run --launch-profile "Profile"

- Works fine, no hot reload

dotnet watch run --launch-profile "Profile"

- Does not work, fails to pickup launch profile

### Expected Behavior

Dotnet watch should work with run properties as highlighted in the MSFT documentation

![image](https://github.com/dotnet/aspnetcore/assets/3959577/728dd361-17e5-485a-9c3f-374c90dd913b)

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch

### Steps To Reproduce

Setup a launch profile

use dotnet watch run
use dotnet watch

### .NET Version

7.0.400, 8.0.100-rc.2.23502.2

**Comment by garrettlondon1** [comment] 2023-11-08 04:07
Holy cow, I think I found the weirdest bug..

"profiles": {
    "watch": {
      "applicationUrl": "https://localhost:7046;http://localhost:5046",
      "commandName": "Project",
      "environmentVariables": {
        "VaultUri": "https://abc.vault.azure.net/",
        "ASPNETCORE_ENVIRONMENT": "Development",
      }
    },
}

Notice how Development env variable has an extra comma, the launch profile will not be recognized.. And the application will start on port 5000 http.

There is no error, or warning, in the launchsettings. Took me way too long to figure it out. **I think this is a separate issue, I just tested and the launch profile does work**

**Comment by martincostello** [comment] 2023-11-08 07:58
Was the launch profile generated by something with those extra commas, or are those an artifact from you manually editing it?

**Comment by garrettlondon1** [comment] 2023-11-08 14:18
@martincostello artifact from manually editing, I removed an env var, and didn't remove the comma

**Comment by martincostello** [comment] 2023-11-08 14:30
As far as I can tell, the code that parses the `launchsettings.json` file is [tolerant](https://github.com/dotnet/sdk/blob/f52240f11ad291e6ee3cff86e83c0f7a21b60370/src/Cli/dotnet/commands/dotnet-run/LaunchSettings/LaunchSettingsManager.cs#L34) of trailing commas in the JSON for `dotnet run`, but [isn't](https://github.com/dotnet/sdk/blob/f52240f11ad291e6ee3cff86e83c0f7a21b60370/src/BuiltInTools/dotnet-watch/LaunchSettingsProfile.cs#L33-L35) for `dotnet watch`.

That would be a bug for the dotnet/sdk repo, which looks like it would be pretty easy to fix.

**Comment by garrettlondon1** [comment] 2023-11-08 14:31
https://github.com/dotnet/sdk/issues/32233

Please see linked issue. It's been open since May, no input from SDK team unfortunately.

**Comment by martincostello** [comment] 2023-11-08 14:34
I'm going to look at submitting a PR to fix it now.

Other than bringing this to my attention to go do that, this isn't an ASP.NET Core issue though as it's just a duplicate of that issue.

**Closed by martincostello** 2023-11-08 14:34 UTC
Labels: area-commandlinetools

**Comment by martincostello** [comment] 2023-11-08 15:37
https://github.com/dotnet/sdk/pull/36744
