### ISSUE TITLE
Kestrel is leaving the sockets in CLOSE_WAIT state after running the server for a while

### ISSUE THREAD

**Issue by rajsell** [dotnet/aspnetcore#29621] opened 2021-01-26 09:27 UTC
We have small agent that's hosted in a container running in Linux VM where we have a ASP.NET web api running. What we are observing over is that over a period of time the CLOSE_WAIT socket keeps building up and eventually the process itself goes to a hung state where all the requests would start to fail eventually. 

This we are observing this recently after we have added some certificate chain validations in our Authentication and authorization middleware. We have configured to validate the chain using the supplied store.

We have a ping actor that continuously monitors these VM's by connecting to this agent for every minute and performs all the required authentication based.  We are seeing this CLOSE_WAIT sockets are building up slowly over the period.

Threadpool queue has been filled up with 
0x00007F504070CCD0 System.Threading.QueueUserWorkItemCallbackDefaultContext<Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection>
0x00007F504070CF48 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection

And for each of the corresponding thread i am seeing the below Task
0x00007FA0F88F1D70 Task | System.Net.Dns+<>c.<HostResolutionBeginHelper>b__10_0

### Further technical details
- ASP.NET Core version : 3.1
- Include the output of `dotnet --info`
Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Tratcher** [comment] 2021-01-26 17:28
Duplicate of https://github.com/dotnet/aspnetcore/issues/21183.

**Comment by halter73** [comment] 2021-01-26 17:31
> Threadpool queue has been filled up with
> 0x00007F504070CCD0
> System.Threading.QueueUserWorkItemCallbackDefaultContext<Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection>
0x00007F504070CF48 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection

I'm guessing that's the following:

https://github.com/dotnet/aspnetcore/blob/df37a7b0e077439bbefd7eb779583e16455f875b/src/Servers/Kestrel/Transport.Sockets/src/Internal/SocketConnection.cs#L311-L329

If the ThreadPool is starved this could prevent the `ConnectionClosed` CancellationToken from firing which would [stop Kestrel from closing the half-open connection](https://github.com/dotnet/aspnetcore/blob/df37a7b0e077439bbefd7eb779583e16455f875b/src/Servers/Kestrel/Core/src/Internal/HttpConnection.cs#L101)). The question becomes: why is the ThreadPool starved?

https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_termination

@rajsell Looking at VS's parallel-stacks window when debugging the dump should help you get to the bottom of this. `!clrstack -all` in WinDbg should give the same info. If you need more help you can comment on #21183

**Comment by davidfowl** [comment] 2021-01-27 01:08
I'm discussing with @rajsell and it does look like #21183

**Closed** 2021-01-29 22:30 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers
