### ISSUE TITLE
High CPU Load after stopping blazor WASM project.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22881] opened 2020-06-12 17:32 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1075142/high-cpu-load-after-stopping-blazor-wasm-project.html)._

---
At least from verion 16.6.0 I`m noticed that sometimes when I stop my Blazor WASM app after debug my VS use almost all my CPU. 85% usage usually in idle.
In the screenshot, more than 10 minutes have passed since the debugging stopped. I don’t notice this problem on old ASP.NET Core projects.

---
#### Visual Studio Feedback System on 6/11/2020, 11:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2020-06-12 17:33
Thanks for contacting us. This is a dupe of #22276

**Closed by mkArtakMSFT** 2020-06-12 17:33 UTC
Labels: Author: Migration Bot :robot:, area-blazor
