### ISSUE TITLE
Allow dotnet watch to run tools

### ISSUE THREAD

**Issue by TomasHubelbauer** [dotnet/aspnetcore#10256] opened 2019-05-15 07:47 UTC
I'd like to request support be added for `dotnet watch` to run globally installed .NET CLI tools.

My use-case it to be able to run `dotnet-script` in a watch, like: `dotnet watch script test.csx`. See filipw/dotnet-script#453. I looked around and haven't seen this request placed yet, hence this issue.

This would require for .NET watch to not require a CSPROJ be present as `dotnet-script` can run any CSX file and there may be other such tools which do not require a full project be bootstrapped. If `dotnet watch` uses the CSPROJ file to figure out what files to watch, in case it is missing, it seems reasonable to me that it would watch all `*.cs` and `*.csx` (+ VB .NET and F# extensions?) files in the directory instead.

### Describe alternatives you've considered

An alternative would be to implement the watch functionality as a command of each .NET CLI tool that could benefit from it. I consider this to be an inferior approach as the watch functionality is already in place and sharing it would ensure all the tools are consistent in how their watching works. Generally, file watching is not easy to get right, so if each tool had to implement it separately, it would probably result in varying quality of the watch experience.

**Comment by atifaziz** [comment] 2019-05-15 13:27
Sort of duplicate of #4108?

**Comment by atifaziz** [comment] 2019-05-15 13:32
> If `dotnet watch` uses the CSPROJ file to figure out what files to watch, in case it is missing, it seems reasonable to me that it would watch all `*.cs` and `*.csx` (+ VB .NET and F# extensions?) files in the directory instead.

Instead of hard-coding this, `dotnet watch` could probe the tool/binary/script with a switch along the lines of `--dotnet-watch-list` and which would cause the tool to return the list of file to watch. If the tool doesn't support the switch then one would expect it to fail with a non-zero exit code, due to the argument being unknown (something any good citizen console application would do).

**Comment by TomasHubelbauer** [comment] 2019-05-15 13:37
I am not sure how I feel about asking the tools about the extensions they want to watch through their CLI interface… Running tools with unknown arguments to me sounds like it could trigger unintended side effects which would be hard to track back to `dotnet watch`.

I think this is very close to #1408 but I'd like to leave open so that this mechanism of extension list to watch can be fleshed out here. #1408 to me reads like they are content with the watch behavior as it is (must have CSPROJ) and just want to be able to run any arbitrary command (which is also something I want, but by itself is not sufficient to enable this).

**Comment by TomasHubelbauer** [comment] 2019-05-15 13:55
Maybe `dotnet watch $tool`, when it detects a CSPROJ is not present, could ask you to enter the extension list at the CLI:

`dotnet watch *.csx? script main.csx` would watch CS and CSX files.

Or it could support some other type of config. Heck, I'd even add the CSPROJ if it could be just:

``xml
<Project>
  <WatchExts>*.csx?</WatchExts>
</Project>
```

**Comment by mkArtakMSFT** [comment] 2020-01-28 18:30
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

**Closed by mkArtakMSFT** 2020-01-28 18:30 UTC
Labels: area-commandlinetools
