### ISSUE TITLE
ViewComponents with parameters that collide with keywords

### ISSUE THREAD

**Issue by bzd3y** [dotnet/aspnetcore#11868] opened 2019-07-03 20:00 UTC
When creating a ViewComponent with a parameter that collides with a keyword the argument to Invoke/InvokeAsync can be prefixed with the @ glyph to resolve the collision and the ViewComponent tag in Razor maps to the parameter correctly and doesn't complain. But when the code builds, a number of syntax errors are generated with only one of them vaguely indicating what is causing the build to fail. (The secondary errors are also repeated for every place the ViewComponent is used in code, which can be overwhelming.)

A solution would seem to be to compile the generated property with the @ glyph just like a user would when making their own class and as they had to do to pass the parameter into Invoke/InvokeAsync in the first place. This should probably just be done always (I'm surprised it isn't the default behavior for generated code) just to be safe and forward compatibility.

If the @ glyph can't be used for some reason, one or more _ characters would also work and then could be translated between the generated class and the Razor code, similar to the PascalCase/CamelCase -> kebob-case translation that is already done.

Another option would be to just convert the parameter to PascalCase in the generated code as it probably would be defined in a user-defined class.

If none of these are feasible, it would help if the AspNetCore analyzer handled the collision and produced a more explicit error that points to the case instead of generated code.

**Comment by mkArtakMSFT** [comment] 2019-07-08 17:01
Thanks for contacting us, @bzd3y.
This is now fixed and will roll out as part of Preview 7 release.
Dupe of https://github.com/aspnet/AspNetCore/issues/8645

**Comment by bzd3y** [comment] 2019-07-08 17:18
Okay, thanks @mkArtakMSFT . I tried looking for existing issues, but didn't find any. In looking at the conversation and code related to that issue, I'm not sure it is a duplicate. Or, at least, I'm not sure that the fix would also fix the problem I was encountering. It looks like underscores are being hard coded to some internal variable names so that users can use those same names for parameters, but unless I am missing something that won't help with C# reserved words in general.

**Comment by mkArtakMSFT** [comment] 2019-07-09 04:36
Thanks @bzd3y.
Sorry, seems like I've overlooked this.
So is the issue you're emphasizing here a situation, where you would use a C# reserved word and that would caused unclear errors down the road?

**Comment by bzd3y** [comment] 2019-07-09 12:47
You're welcome and no problem. Thanks for looking into it. They are essentially the same problem, but I think the causes are slightly different. And yes, that describes it pretty well, although the unclear errors might be secondary. To me, it would be more important to just be able to use the C# keyword and have no errors.

For example, I'm working on an app with a case management component and I had a view component that took "case" as a parameter. So Invoke/InvokeAsync has a @case argument, which worked fine and the tag helper recognizes it as a parameter "case" to pass in to the view component. So no squiggly underlined compile errors/warnings/etc. But when it gets built there are syntax errors from the generated code that don't point to my code. I just changed it back to make sure I was giving you correct information and there are actually errors that do point to my code, although they don't really clearly indicate the problem since the code causing the problem is being generated.

1 use of the tag helper in one file generates 33 syntax errors, mostly having to do with expected/unexpected ; and }. Using it multiple times/in other files duplicates the errors. Some of them do mention 'case' being the problem, though, so maybe the errors generated are adequate and not worth streamlining.

But I do think it would be nice to be able to use C# keywords in view components (and tag helpers in general if the problem is actually there).

**Comment by mkArtakMSFT** [comment] 2019-07-09 18:41
Thanks for confirming. Given this is very easy to work around by simply choosing non-keyword names for your properties, I'm moving it to `Backlog`. However, we;ll happily consider a PR, so feel free to send one.

**Comment by bzd3y** [comment] 2019-07-09 18:45
Okay, thanks. If I have time I might look at the code more to see what it would take. Thanks again.

**Comment by mkArtakMSFT** [comment] 2022-10-19 22:33
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2022-10-19 22:33 UTC
Labels: enhancement, area-mvc, affected-few, severity-minor, Priority:3, feature-mvc-razor-views
