### ISSUE TITLE
High CPU & Memory when editing Blazor WASM files

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23102] opened 2020-06-18 20:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1080470/high-cpu-memory-when-editing-blazor-wasm-files.html)._

---
Visual Studio consumes 40% CPU and 2GB Ram when editing a small Blazor Project (<10 pages). VS is very slow. IntelliSense is not working anymore. After 3 min CPU consumption goes down however each edit will increase it again.

---
#### Visual Studio Feedback System on 6/17/2020, 03:49 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2020-06-18 20:34
Thanks for contacting us. This is a dupe of #22276

**Closed by mkArtakMSFT** 2020-06-18 20:34 UTC
Labels: Author: Migration Bot :robot:, area-razor.tooling
