### ISSUE TITLE
Unexpected exception when editing new class file

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#27622] opened 2020-11-08 04:46 UTC
### Describe the bug
I receive a gold bar after creating a new C# class in my application.

### To Reproduce

1. Create a new C# file for a class in the app.
2. Begin defining the class members.
3. Observe the crash below.

![image](https://user-images.githubusercontent.com/1857993/98457274-25be9980-213a-11eb-9d7a-b02c6693c252.png)

#### Activity log (only needed if VS crashes)
https://gist.github.com/captainsafia/7d9ae57692498e69ac84f25a56056800

### Further technical details
- VS version: Version 16.9.0 Preview 2.0 [30706.124.main]
- Scenario: Local

**Comment by NTaylorMullen** [comment] 2020-11-11 00:46
Duplicate of: https://github.com/dotnet/aspnetcore/issues/27620

**Closed by NTaylorMullen** 2020-11-11 00:46 UTC
Labels: area-razor.tooling, feature-razor.vs
