### ISSUE TITLE
[Java][SignalR] NPE occurs during connection to a WS if .skipNegotiate(true) for the field: chosenTransport

### ISSUE THREAD

**Issue by Grendelius** [dotnet/aspnetcore#30142] opened 2021-02-12 14:40 UTC
v.5.0.3

**Steps to reproduce:**

- Create the hubConnection:

```
HubConnection hubConnection = HubConnectionBuilder
                .create("wss://api.host.net/hub")
                .withAccessTokenProvider(Single.defer(() -> Single.just(token)))
                .shouldSkipNegotiate(true)
                .withTransport(TransportEnum.WEBSOCKETS)
                .build();
```

- Start the connection using .blockingAwait(): 

`hubConnection.start().blockingAwait();`

**Expected result:**
- The hub connection gets the CONNECTED status.

**Actual result:**
- NPE occurs:

HubConnection.class (row: 255) -> switch(negotiateResponse.getChosenTransport()) ...

P.S. The 'chosenTransport' is null for the  `negotiate.flatMapCompletable((negotiateResponse) -> {...` (HubConnection.class, row:220) due to it wasn't initialized due to the 'startNegotiate' method is not run for a reason '.skipNegotiate(true)'. Other ways for that variable initialization are absent in the code.

**Comment by BrennanConroy** [comment] 2021-03-15 16:30
Dupe of https://github.com/dotnet/aspnetcore/issues/29765 and fixed.

**Closed by BrennanConroy** 2021-03-15 16:30 UTC
Labels: area-signalr, investigate
