### ISSUE TITLE
Reconnect modal displays immediately in Firefox upon navigation

### ISSUE THREAD

**Issue by Bouke** [dotnet/aspnetcore#40414] opened 2022-02-25 14:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following issue appears when using Blazor inside an MVC application. It uses the [Render Blazor components from JavaScript](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#render-blazor-components-from-javascript) feature of .NET 6 to render Blazor components in MVC pages.

In #24137 a delay was added before showing the "reconnection modal", especially for the case where users were navigating away from a page. However in my application I still see the "reconnect modal" appear as soon as I navigate away to another page.

The commit #24566 moves the code around to this location:

https://github.com/dotnet/aspnetcore/blob/1dcf7acfacf0fe154adcc23270cb0da11ff44ace/src/Components/Web.JS/src/Platform/Circuits/DefaultReconnectDisplay.ts#L95-L101

The problem seems to be that Firefox executes both `this.modal.style.visibility="hidden"` and `this.modal.style.visibility="visible"` in the same reflow. As a result, the css transition is _not_ triggered. When I change the `setTimeout` delay from 0 to 10 ms the transition is triggered and the delay of 500ms (+10) is respected.

### Expected Behavior

When navigating to a new page the reconnect modal dialog should not appear.

### Possible solution

By having the modal dialog element already in the DOM the `setTimeout` workaround to trigger the CSS animation is not needed.

### .NET Version

6.0.2

### Anything else?

I've worked around this by introducing a custom reconnect modal dialog that appears only after 5 seconds, but this is not an ideal situation.

**Comment by mkArtakMSFT** [comment] 2022-02-28 17:38
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/28592.
Please upvote the linked issue and provide additional comments about your scenario there if you need.

**Closed by mkArtakMSFT** 2022-02-28 17:38 UTC
Labels: area-blazor, blazor-server
