### ISSUE TITLE
UseWindowsService + produce single file = configuration files loaded from C:\Windows\ServiceProfiles\<user>\AppData\Local\Temp\.net

### ISSUE THREAD

**Issue by smapelli** [dotnet/aspnetcore#23228] opened 2020-06-22 19:06 UTC
Created a windows service that self-hosts asp.net core 3.1 and everything worked fine. I then tried publishing my application by merging all assemblies in a single exe with "produce single file" in visual studio and suddenly configuration json files are being searched in a folder such as the following C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\.net\NetCoreApp\513cgjpl.0nf

LocalService is the windows service identity and NetCoreApp is the service name.

Providing the exception thrown when the config file is not found as it contains the .net core version.

```
Application: TestNetCore.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: The configuration file 'TEST.json' was not found and is not optional. The physical path is 'C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\.net\NetCoreApp\513cgjpl.0nf\CONFIG.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at TestNetCore.Program.Main(String[] args)

```

**Comment by Tratcher** [comment] 2020-06-22 19:47
Duplicate of https://github.com/dotnet/runtime/issues/36065

**Closed by Tratcher** 2020-06-22 19:47 UTC
Labels: area-servers
