### ISSUE TITLE
disable kestrel at runtime

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/aspnetcore#31399] opened 2021-03-30 20:34 UTC
I've the need to disable kestrel (stop it from listening) but I haven't find a way, is it possible?

Let me try to put this into a context:
my solution is quite complex and is built from a `new HostBuilder` and I can dinamically add features (called Shard), each Shard has a companion setting class and I'm mapping these setting classes using IOptions<> pattern

One of these shard is WebApiShard, that allow to register custom Controllers, use swagger, etc...
I've described it in my documentation website (work in progress, just WebApiShard is quite complete) <https://mithrilshards.mithrilman.com/shards/web-api/>

My app can be assembled like this

```
await new ForgeBuilder()
   .UseForge<DefaultForge>(args, settings)
   .UseSerilog(logSettings)
   .UseBedrockNetwork<ExampleNetworkProtocolMessageSerializer>()
   .UseStatisticsCollector(options => options.DumpOnConsoleOnKeyPress = true)
   .UseApi(options => options.ControllersSeeker = (seeker) => seeker.LoadAssemblyFromType<ExampleDev>())
   .UseDevController()
   .UseExample(KnownVersion.V1, protocolVersion)
   .RunConsoleAsync()
   .ConfigureAwait(false);
```

each `Use***` is basically an injection of a shard, and `UseApi` is the shard where I inject kestrel stuff

here the lines where I add kestrel calling UseKestrel
https://github.com/MithrilMan/MithrilShards/blob/a55fef271e6b60b9d872b9a543b38e0d0ec6d328/src/MithrilShards.WebApi/ForgeBuilderExtensions.cs#L96-L103

```
   ...
         }, preBuildAction: (iHostBuilder) =>
         {
            iHostBuilder.ConfigureWebHost(configure =>
            {
               configure.UseKestrel(serverOptions => {
                     var logger = serverOptions.ApplicationServices.GetService<ILogger<WebApiShard>>();
```

Now everything is working, but if I want to disable the whole WebApiShard by setting Enabled property of my `IOptions<WebApiSettings>`, I cannot access it before calling UseKastrel because there isn't a way to access the hostbuilder `IServiceCollection` to build a temporary serviceProvider, and so I was hoping there was a way to "disable" kestrel within its `UseKestrel` parameter (configuration action)

If you follow my repo link, you'll see that I've this code to listen to user defined endpoints:

```
if (webApiSettings.Enabled)
{
   serverOptions.Listen(webApiSettings.GetIPEndPoint(), options =>
      {
         if (webApiSettings.Https)
         {
            options.UseHttps();
         }
      });
...
```

the problem is that when `webApiSettings.Enabled` is set to false, Kestrel listen on its default 5000 and 5001 ports while I want instead to prevent it to listen at all

How can I achieve it without nasty hacks?
And what if I want to be able to stop kestrel to listen at runtime?

I can think about register myself kestrel by copying UseKestrel code and call then be able to manually call KestrelServer StopAsync and StartAsync but I'd like to know if there is a better option.

Thanks

**Comment by MithrilMan** [comment] 2021-03-31 00:14
@Tratcher 
> You won't be able to rely on Options to make that decision, it's too early. You'll need to pull the setting from an alternate source like your own IConfiguration instance.

that's exactly what I'd like to avoid: having to get these information from a custom configuration source
Anyway it would solve one problem, the other one is being able to pause/stop kestrel at runtime, like a `StopListening()` and `ResumeListening`


Moving back on IOptions, I find it confusing not being able to rely on them during host building process.
How the host building is designed highlight a desing problem,because during that task you often need some settings that are in your .json/environment/args etc... and the fact that you can't use IOptions consistently is a problem.

I can use IOptions in 2 ways:
- Injected in constructor resolved by DI
- building a temporary serviceProvider within ConfigureServices

If you need it out of these 2 scenario (e.g. within ConfigureWebHost or in other Configure* methods) you can't.
Maybe a better API that allows you to configure IOptions and resolve them earlier is possible?



One thing that may not be obvious is that I splitted my registration process in two:
when AddShard is called I register some services in DI (the Shard itself and its Setting class) and then I allow to call a "preBuild" action that gets queued into a list of actions and called before building and running the Host

``` c#
 public Task RunConsoleAsync(CancellationToken cancellationToken = default)
      {
         EnsureForgeIsSet();

         foreach (var preBuildAction in _preBuildActions)
         {
            preBuildAction.Invoke(_hostBuilder);
         }

         try
         {
            return _hostBuilder.RunConsoleAsync(cancellationToken);
 ```        
in one of these `preBuildAction` there is the code that calls ConfigureWebHost and thus UseKestrel and unluckily my settings aren't registered yet at that point.
Technically at that point I've already defined all needed services so if I were able to access to the IServiceCollection of the hostBuilder I would have solved the problem.
Unluckily HostBuilder doesn't exposes the service collection so I should create my own, but before going so deep or copy and modify the code, I'd prefer to see if there is any viable (built-in) way to achieve the same result


Actually I committed some changes on my repo to resolve IOptions as soon as I register them, putting them into `HostBuilderContext.Propertie` but unluckily this doesn't solve my problem because anyway I do that withing ConfigureServices that gets called after the block that calls UseKestrel.

ref: <https://github.com/MithrilMan/MithrilShards/blob/404f4e14ae5e984f6331c83d3dcc9c1cce45c477/src/MithrilShards.Core/Forge/ForgeBuilder.cs#L126-L151>

Maybe tomorrow with a fresh mind I can solve this issue, the other one ("pausing" kestrel) remains.
I'm starting to ramble and I revised this post too much, probably just adding confusion, need to sleep :)
thanks for your input

**Comment by BrennanConroy** [comment] 2021-03-31 20:17
Clsoing as dupe of  https://github.com/dotnet/aspnetcore/issues/21244

**Closed by BrennanConroy** 2021-03-31 20:17 UTC
Labels: Needs: Attention :wave:, area-runtime
