### ISSUE TITLE
Merge AspNetCore-Tooling repo into AspNetCore

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#18252] opened 2020-01-10 00:18 UTC
As part of the work described [here](https://github.com/dotnet/announcements/issues/127) the `dotnet/aspnetcore-tooling` repo should merge into `dotnet/aspnetcore`

**Comment by JunTaoLuo** [comment] 2020-12-10 23:06
I think this is a duplicate of https://github.com/dotnet/aspnetcore/issues/21145. Closing as done since we've consolidated as much as we planned.

**Closed by JunTaoLuo** 2020-12-10 23:06 UTC
Labels: area-infrastructure, task
