### ISSUE TITLE
ASP .NET 8 RC1 Routing & UseStaticFiles

### ISSUE THREAD

**Issue by Github-Butler** [dotnet/aspnetcore#50707] opened 2023-09-14 16:06 UTC
breaking change from preview 7 to RC1:
using the page Weather.razor with route wildcard @page "/{weather?}" worked perfectly and the static file /bootstrap/bootstrap.min.css was delivered as expected.
After upgrade to RC1 the static file route /bootstrap/bootstrap.min.css was ignored.

**Comment by Bartmax** [comment] 2023-09-14 22:14
catchall routes also looks like are having this problem too.

**Comment by Github-Butler** [comment] 2023-09-14 22:44
Minimal repro project: https://github.com/Github-Butler/Issue50707

**Comment by krompaco** [comment] 2023-09-15 18:17
I'm seeing same issue going from Preview 7 to RC 1 with no other code changes.

My controller route with this pattern now catches requests for physical files that I'm certain are in the wwwroot folder.

```
app.MapControllerRoute(
    name: "files",
    pattern: "{**path}",
    defaults: new { controller = "Content", action = "Files" });
```

**Comment by javiercn** [comment] 2023-09-27 11:16
This seems to be caused by the global implicit router running before the static files middlware.

@captainsafia you did fix something in this area recently, didn't you?

**Comment by captainsafia** [comment] 2023-09-28 23:05
Yes, this issue was resolved in https://github.com/dotnet/aspnetcore/pull/50864. You can try the .NET 8 nightlies in github.com/dotnet/installers to see if that resolves the issue for your scenarios.

**Comment by Github-Butler** [comment] 2023-10-12 08:51
Problem resolved in ASP .NET Core 8 RC2

**Comment by captainsafia** [comment] 2023-10-25 11:27
Thanks for following up! Closing this issue now.

**Closed by captainsafia** 2023-10-25 11:27 UTC
Labels: feature-minimal-hosting, area-hosting
