### ISSUE TITLE
MSB4113	Specified condition - Failed to properly account for ' in string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18199] opened 2020-01-08 19:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/869736/msb4113-specified-condition-failed-to-properly-acc.html)._

---
[regression]
You guys haven't properly escaped/enclosed the strings you're using in the following build targets:

Microsoft.NET.Sdk.Razor.StaticWebAssets.targets

It should be Copy("%(Identity)") instead of Copy('%(Identity)' by the look if it. 

I had to delete/rename the file to get it to work.
Don't you have automated code checks for this kind of thing?

Error	MSB4113	Specified condition "$([System.String]::Copy('%(Identity)'). StartsWith('wwwroot'))" evaluates to "$([System.String]::Copy('ClientApp\assets\img\flags\Cote d'Ivoire.png'). StartsWith('wwwroot'))" instead of a boolean.		C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets	276

---
#### Visual Studio Feedback System on 12/30/2019, 10:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/3/2020, 00:02 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Andrewx991** [comment] 2020-02-10 16:01
This causes a big problem for users that have an ' in their name because their user directory will contain a ' and cause this to happen, effectively preventing them from building. And renaming a user directory isn't well documented from what I can see.

**Comment by mkArtakMSFT** [comment] 2020-06-09 21:28
This is a dupe of https://github.com/dotnet/aspnetcore/issues/21990

**Closed by mkArtakMSFT** 2020-06-09 21:28 UTC
Labels: area-mvc, investigate
