### ISSUE TITLE
Hosting Blazor App behind an MVC app

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#26488] opened 2020-10-01 13:24 UTC
I have a Frontend MVC Application called "Authentication"

and its backend called  "Authentication.Administration" which is a Blazor WebAssembly App

I want my Authentication application responding on https://authentication.xxx.com
and the backend responding on https://authentication.xxx.com/Administration

So I tried exemples shown in this page https://docs.microsoft.com/fr-fr/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1

I tried several approches to achieve that, But nothing to do.

Thanks for your help.

**Comment by pranavkm** [comment] 2020-10-01 16:39
@JulienM28 it's not very clear what the issue is. Going by past feedback in these sort of issues, it's likely that you do not have the base href configured correctly in your Blazor app. Please follow the sample at https://github.com/javiercn/BlazorMultipleApps/blob/master/BlazorMultipleApps/Server/Startup.cs to see if it helps in your case. 

Feel free to respond if this does not help.

**Comment by JulienM28** [comment] 2020-10-02 06:27
I already tried that.

Basically I want my Blazor app responding on mydomain.com/Administration
instead of mydomain.com which is the default case.

But I can't achieve this.

Here is may actuel pipeline:

```
app.UseHttpsRedirection();

            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{controller=Account}/{action=Login}");
                endpoints.MapFallbackToFile("/Administration/{*path:nonfile}", "index.html");
```

and in index.html I set
```html
 <base href="/Administration/" />
```

**Comment by pranavkm** [comment] 2020-10-05 16:53
@JulienM28 you're missing the call to `app.UseBlazorFrameworkFiles`. See https://github.com/javiercn/BlazorMultipleApps/blob/master/BlazorMultipleApps/Server/Startup.cs#L55

**Comment by JulienM28** [comment] 2020-10-06 08:29
It still give me a 404.

Here's may solution:
![image](https://user-images.githubusercontent.com/23618436/95172242-52883580-07b7-11eb-9c58-97cf1c913ca4.png)

Authentication is the MVC project and authentication.administration the blazor Wasm project.

Startup.cs from server project:
```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment() || env.IsStaging())
            {
                app.UseDeveloperExceptionPage();
                app.UseMigrationsEndPoint();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles("/Administration");
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute("default", "{controller=Account}/{action=Login}");
                endpoints.MapFallbackToFile("/Administration/{*path:nonfile}", "index.html");
            });
        }
```
Blazor WASM index.html:
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Authentification.Administration</title>
    <base href="/Administration/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
</head>

<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
    <script src="_framework/blazor.webassembly.js"></script>
</body>

</html>
```

When I call /Account/Login I get my page from MVC Website.
but /Administration respond with a 404

**Comment by mkArtakMSFT** [comment] 2023-11-06 04:29
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2023-11-06 04:29 UTC
Labels: bug, investigate, area-blazor, feature-blazor-wasm, affected-very-few, severity-blocking, Blazor ♥ MVC
