### ISSUE TITLE
[Blazor] [WASM] Not being able to configure a custom query parameter on Login

### ISSUE THREAD

**Issue by TonyRdz** [dotnet/aspnetcore#40826] opened 2022-03-22 19:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to pass a custom querystring parameter from a Blazor WASM application to the Azure B2C login experience through the AddMsalAuthentication method but I do not see an option. 
Could this functionality be provided?

### Describe the solution you'd like

Being able to configure additional query string parameters as part of the B2C authentication configuration.

**Comment by javiercn** [comment] 2022-03-23 13:54
Dupe of https://github.com/dotnet/aspnetcore/issues/40826

**Closed by javiercn** 2022-03-23 13:54 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-msal

**Comment by javiercn** [comment] 2022-03-23 14:21
@tonyruco updated the issue. I'm terrible at copy&paste apparently.
