### ISSUE TITLE
EditForm not working with css isolation

### ISSUE THREAD

**Issue by longinos10** [dotnet/aspnetcore#28675] opened 2020-12-15 19:25 UTC
I don't know if it is a bug or a missing feature, EditForm works well with css classes on the global css file, but not in the css isolation file

Example

In the Index.razor

with EdtiForm

    <EditForm class="editform" Model=product  >
        <InputText class="name"  @bind-Value=product.Name />

    </EditForm>

---------------------
without EditForm

    <form   class="editform" >

        <input class="name"   />
    </form>

----------------------------------------------------

In the isolation  Index.razro.css or in the global css file
.layout{
    display: grid;
    grid-template-columns: 1fr;
    place-items: center;
     width:100%;
     height: 500px;
     background-color: blanchedalmond;
 }
 .editform{
     display: grid;
     grid-template-columns: 1fr;
     place-items: center;
     width: 100%;
     height: 200px;
     background-color: blueviolet;
 }
 .name{
     width: 95%;
     height: 2rem;
 }

If I use only the global css file both EditFrom and Form work
But if you use the Index.razor.css isolation file, then it only form wroks, and not EditForm

I am using Net 5.0 Framework

**Comment by mkArtakMSFT** [comment] 2020-12-16 17:32
Thanks for contacting us. This is a dupe of #26137.

**Closed by mkArtakMSFT** 2020-12-16 17:32 UTC
Labels: area-blazor, feature-blazor-css-isolation
