### ISSUE TITLE
Design time identity migration fails with custom code in startup

### ISSUE THREAD

**Issue by jeffreyln101** [dotnet/aspnetcore#14696] opened 2019-10-03 09:51 UTC
![indentity_migrations_fail_1](https://user-images.githubusercontent.com/55372140/66116976-3578bf80-e5c3-11e9-8b34-115eedc362f0.png)
![indentity_migrations_fail_2](https://user-images.githubusercontent.com/55372140/66116987-390c4680-e5c3-11e9-9a88-23da8472bff5.png)

**Comment by blowdart** [comment] 2019-10-03 12:28
@ajcvickers This appears to be an EF thing

**Comment by jeffreyln101** [comment] 2019-10-05 00:33
Played with this more today, it is looking like if you scaffold identity into a project you must hard code a connection string into appsettings.json for design time migration to work. IdentityHostingStartup gets called before startup and there does not seem to be a good way to mess with public static void Main to make things work. 

Maybe i am not seeing something?

**Comment by ajcvickers** [comment] 2019-10-15 20:42
@blowdart This looks like an Identity scaffolding thing to me, especially given the second comment. But without actual code it's hard to be sure what is going on.

**Comment by jeffreyln101** [comment] 2019-11-15 08:49
build a new project 

1. set appsettings.json (http://json.schemastore.org/appsettings) to

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}

2. set appsettings.Developement.json (http://json.schemastore.org/appsettings) to

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}

3. Add an environment variable to the system the application is running on called my_DATABASE and put your connection string in it. 

4. Read the connection string from your system to connect to your database.

example add this to application startup.cs

                var config = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables("my_")
                .Build();

        myDatabase.CONNECTION = config.GetValue<string>("DATABASE");

Your application will run fine, but at design time it will not longer be able to scaffold because it can't find the connection string.

**Comment by jeffreyln101** [comment] 2019-11-15 10:11
ps I don't like appSecrets to much typing, I hide things else where and remove things like connection strings from my projects.

**Comment by HaoK** [comment] 2020-04-27 22:58
@blowdart this behavior is expected the scaffolding won't know how to find connection strings if they are doing something non standard

**Comment by blowdart** [comment] 2020-04-28 00:40
We're closing this issue as the behaviour discussed seems to be by design.

**Closed** 2020-10-02 16:15 UTC
Labels: :heavy_check_mark: Resolution: By Design, Status: Resolved, area-identity
