### ISSUE TITLE
Publish v6 packages in a way that works with the reality of NuGet today, rather than working against it

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/aspnetcore#38336] opened 2021-11-12 16:52 UTC
I get this problem:-

https://github.com/dotnet/aspnetcore/issues/38256

This person gets the same problem:-

https://github.com/NuGet/Home/issues/11372

And again:-

https://github.com/dotnet/aspnetcore/issues/38333

Obviously I could go on.

@Tratcher has stated "It's a limitation of the tooling, it doesn't account for TFM limitations before offering upgrades. The error message is the current guard to prevent upgrading when incompatible." https://github.com/dotnet/aspnetcore/issues/38333#issuecomment-967240077

It has also been suggested that:- https://github.com/dotnet/aspnetcore/issues/38256#issuecomment-967227288

I have raised two worries about this problem:- https://github.com/NuGet/Home/issues/5725#issuecomment-967219320

**Suggestion**

The ASP.NET team, and indeed every .NET team, publishes their v6 packages in a way that works with the reality of NuGet today, and stops people falling into this trap.

**Comment by pranavkm** [comment] 2021-11-12 17:06
FYI @Pilchie

**Comment by Bellarmine-Head** [comment] 2021-11-12 17:40
Say that the ASP.NET team has to put out new 5.0.12 versions of the Blazor WebAssembly packages next week, because of some serious vuln that's just been detected.

If I click on my solution's `Manage NuGet Packages for Solution...` menu item in VS 2019, will I see the available 5.0.12 updates?

I think not, because they will be occluded by the incompatible 6.0.0 versions.  

This may be a "limitation" of NuGet UI, but it's also a reality, and (it seems) it's well known.

**Comment by Pilchie** [comment] 2021-11-12 21:39
Given that we're now in servicing for .NET 6, we aren't going to change the entire versioning scheme for packages as part of a servicing release. So, I don't see this changing in .NET 6 versions, though it's something I'll bring up with some others for .NET 7, as well as coordinating with the NuGet team on when their plans will land.

Though this issue can be frustrating, it has been the case that NuGet and .NET Core have worked this way since .NET Core 1.0 shipped.  Given that it's been around for several years and several versions, I'm not how we would justify the risk to change everything as part of a servicing request.

**Comment by Bellarmine-Head** [comment] 2021-11-13 08:11
@Pilchie 

> though it's something I'll bring up with some others for .NET 7

This seems to me to be a wise move.

> as well as coordinating with the NuGet team on when their plans will land

And this is even wiser.

> Though this issue can be frustrating

This issue is more confusing than frustrating (confusion is, of course, worse).  I couldn't understand what was going on - why `Manage NuGet Packages for Solution...` in VS 2019 was giving me the option to update WebAssembly packages to net6 versions in a net5 project.

> I'm not how we would justify the risk to change everything as part of a servicing request.

Understood.  But if you're now starting to plan for dealing with this problem in the future, that's great.  On that basis, I'm happy that I opened this issue.

--

Incidentally, I wrote above:-

```
Say that the ASP.NET team has to put out new 5.0.12 versions of the Blazor WebAssembly packages next week, because of some serious vuln that's just been detected.

If I click on my solution's Manage NuGet Packages for Solution... menu item in VS 2019, will I see the available 5.0.12 updates?

I think not, because they will be occluded by the incompatible 6.0.0 versions.
```

I now see that 5.0.12 versions **do** actually exist!  You have to click on the `Version:` dropdown to see them.  This is something I haven't done before - or - something that I have done on occasion in the past but forgot about completely.  I discovered or re-discovered this just now!  Well, at least that's a good solution for now - I just have to remember to do it.  When you're updating packages in your solution, you're thinking about your solution, not about the niceties of the NuGet UI or "TFMs" etc.  (I had never heard of "TFM" before yesterday.)

Thanks for taking this on.

**Comment by joemey** [comment] 2021-11-15 07:36
@Pilchie 

> Though this issue can be frustrating, it has been the case that NuGet and .NET Core have worked this way since .NET Core 1.0 shipped. 

This is a known problem since at least .NET Core 2.1 (see https://github.com/NuGet/Home/issues/5725#issuecomment-492871401) and has been ignored since then.

> Given that it's been around for several years and several versions, I'm not how we would justify the risk to change everything as part of a servicing request.

I doubt there is anything which can be fixed by servicing ASP.NET, it's the way how NuGet is only looking at the package version during updates.

It would be fantastic if this could be fixed for .NET 7.

**Comment by wtgodbe** [comment] 2022-08-04 23:22
@Pilchie do you know if there's any plan on the dotnet/nuget level to make this experience any better?

**Comment by wtgodbe** [comment] 2022-08-04 23:25
Also @rrelyea in case you know anything about any such plans

**Comment by rrelyea** [comment] 2022-08-05 01:03
I'm on leave. Please reach out to nuget repot via issue.

**Comment by Bellarmine-Head** [comment] 2022-10-26 12:08
> though it's something I'll bring up with some others for .NET 7, as well as coordinating with the NuGet team on when their plans will land

It's nearly a year later, and .NET 7 is just around the corner.

@Pilchie - has anything been done in this regard?  anything discussed?

If not, I'm fully expecting for my .NET 6 projects to be offered package updates to .NET 7 versions... which presumably would be an unwise offer to take.  I'm expecting just as much confusion for folks as a year ago.

News of some progress would be nice, but I'm not hopeful.

**Comment by Bellarmine-Head** [comment] 2022-11-08 15:46
There we go!!!!

![image](https://user-images.githubusercontent.com/3470891/200610076-468709d4-74f0-41b9-b1f5-2a7ea17413d8.png)

One year on... same problem.

Here we have version 7.0.0 packages:-

* being offered for a .NET 6 project, which is unlikely to work
* hiding the fact that I could legitimately update my `6.0.10` packages to `6.0.11`

**Comment by Bellarmine-Head** [comment] 2022-11-09 09:05
I attempted to update my 3 WebAssembly packages (see above) to .NET 7 (in Visual Studio Pro 17.4.0) to see what the experience was like.  They didn't update (as expected), and afterwards the `Error` window was shown, which was empty.  I eventually found that the `Output` window (not shown by VS after the failure) held the error messages...

```
NU1202: Package Microsoft.AspNetCore.Components.WebAssembly 7.0.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.Components.WebAssembly 7.0.0 supports: net7.0 (.NETCoreApp,Version=v7.0)
NU1202: Package Microsoft.AspNetCore.Components.WebAssembly 7.0.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / browser-wasm. Package Microsoft.AspNetCore.Components.WebAssembly 7.0.0 supports: net7.0 (.NETCoreApp,Version=v7.0)
```

Now I know, but some folks out there may not know, that for my .NET 6 projects from this day forth and until support for .NET 6 ends in November 2024, I have to do the following extra work to see if there are *valid* updates for my .NET 6 packages...

![image](https://user-images.githubusercontent.com/3470891/200783491-d5ac6456-44eb-48f4-9b4c-38a11f06cb2e.png)

I.e. per package, click on the `Version` dropdown and look for the highest `6.*.*` version that is listed.

So the **real problem** with this NuGet shortcoming and/or the way that .NET packages are published (take your pick) is that it's hiding legitimate .NET 6 updates, or making them harder to find.  Obviously NuGet should offer (by default) the latest stable versions for your project's .NET version.  Seems simple and obvious, but for some reason the two sides (Microsoft and NuGet) can't connect the dots and make it happen (for over 5 years now).

Now .NET 6 is LTS, and supported for the next two years (!!) from the time I write this.  Thanks to this problem, which raised its head last year (and before), .NET 7 (and later 8 potentially) has degraded the .NET 6 experience - a supported version!

Microsoft published .NET 7 *knowing this would happen* and will likely again blame the problem on "tooling".

If this comment helps people who otherwise wouldn't know where to find their legitimate .NET 6 updates, then I'm glad.

Here's the issue in the NuGet repo: https://github.com/NuGet/Home/issues/5725

**Comment by Bellarmine-Head** [comment] 2022-11-09 09:32
Say that you're on Windows 10, and `Windows Update` started offering you Windows 11 updates that failed to install, and obscured genuine Windows 10 updates that you needed for security... wouldn't you conclude that Microsoft had lost its mind?

**Comment by japui-coder** [comment] 2022-11-10 11:47
Publish v6 packages in a way that works with the reality of NuGet today, rather than working against it #38336

**Comment by wtgodbe** [comment] 2022-11-17 23:30
@Bellarmine-Head thanks for continuing to push on this issue - I agree we should find a solution for it. I'm not optimistic about us changing our branding scheme at this point, but I do think there can be a solution on the nuget side to allow us to specify a version range for package management tools to offer upgrades within. I've opened [this](https://github.com/NuGet/Home/issues/12254) issue to track that, and have engaged with the nuget team offline about it as well. It's already on their radar, so hopefully we can have a solution for this in the .net 8 time frame. I'm going to close this issue as a dupe of the one I linked, and encourage you to continue discussion there with any further suggestions.

**Closed by wtgodbe** 2022-11-17 23:30 UTC
Labels: area-infrastructure

**Comment by Bellarmine-Head** [comment] 2022-11-18 08:18
@wtgodbe yes, I agree that the solution really should be on the NuGet side.  I opened this issue mainly to see if I could get Microsoft to at least pause and reflect before simply pushing out .NET vNext _knowing_ that these problems would arise, and blaming it each time on tooling limitations.  Also I wanted ppl to consider that maybe the real problem here is not that incompatible versions are offered, but that they hide genuine and valid versions that the unknowing might not know how to find.  Happy to continue to push on the NuGet side.

**Comment by vbjay** [comment] 2022-11-27 18:15
> Say that you're on Windows 10, and `Windows Update` started offering you Windows 11 updates that failed to install, and obscured genuine Windows 10 updates that you needed for security... wouldn't you conclude that Microsoft had lost its mind?

AMEN!!!!

**Comment by wtgodbe** [comment] 2022-11-28 17:29
@vbjay please thumbs-up https://github.com/NuGet/Home/issues/12254 if you agree this should be fixed, the more engagement we get there the more likely we are to get an improved experience for this in .Net 8
