### ISSUE TITLE
Support custom graphics from Blazor components across all hosting models

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#42216] opened 2022-06-15 19:32 UTC
We've seen user requests to support custom graphics in Blazor components that can be reused across all Blazor hosting models: Server, WebAssembly, Hybrid. For example: https://github.com/mono/SkiaSharp/issues/1834

SkiaSharp provides some level of custom graphics support for Blazor WebAssembly apps, but additional work is required to support Server and Hybrid scenarios where the canvas memory is not directly accessible.

Microsoft.Maui.Graphics provides a common graphics abstraction for .NET MAUI apps. It supports using a skia-based backend when can also work in Blazor WebAssembly apps: https://github.com/jonlipsky/MauiGraphics.Sample.Blazor.WebAssembly. But again, no support for Server or Hybrid.

Various community projects existing for interacting with the HTML canvas API: https://github.com/excubo-ag/Blazor.Canvas, https://github.com/BlazorExtensions/Canvas.

To support Blazor Server and Blazor Hybrid we need to decide on a mechanism to transfer the graphics commands to the browser and then handle them. See https://github.com/mono/SkiaSharp/issues/1834#issuecomment-1155725897 for some options.

**Comment by RChrisCoble** [comment] 2022-06-20 17:47
Thanks for this nice writeup @danroth27.  I know @jonlipsky mentioned in an email conversation he already had code to serialize and deserialize drawing commands with a binary format for MAUI.Graphics which might be helpful is that behavior is ever committed.

**Comment by danroth27** [comment] 2022-06-20 20:55
Related Microsoft.Maui.Graphics issues:

- https://github.com/dotnet/Microsoft.Maui.Graphics/issues/243
- https://github.com/dotnet/Microsoft.Maui.Graphics/issues/244
- https://github.com/dotnet/Microsoft.Maui.Graphics/issues/245

**Comment by sulivanganter** [comment] 2024-03-07 20:27
Many great projects require this to function in a Server or Hybrid environment. I hope that one day this will be moved out of the backlog

**Comment by xcaptain** [comment] 2024-06-10 17:18
Any progress? I found an awesome project(https://github.com/DominikNITA/Blazor3D-Playground) using canvas to draw 3D graphics, hope one day we can use canvas directly in blazor app without adding https://github.com/BlazorExtensions/Canvas.

**Comment by RChrisCoble** [comment] 2024-06-10 17:46
We ended up using SkiaSharp to do our 2D rendering on WASM and this has been extremely successful for us, and fast.

The only gotcha is this rendering bypasses the JS/Interop layer so it will not work in "Blazor Hybrid" scenarios.

**Comment by sulivanganter** [comment] 2024-06-14 18:38
Indeed, rendering in WASM is fast. Libraries for generating charts such as ScottPlot5 and LiveCharts2 use SkiaSharp and are available for Blazor only in WASM. I know with .NET 8, I can keep some components on client-side. The problem is that you need to send all the data to the client to perform the rendering, instead of just sending the rendered output and events. When dealing with a larger amount of data, this makes everything slow. Additionally, it is not possible to reuse the code in Blazor Hybrid because there is no option to run a component on the "client" side.

**Closed** 2024-10-29 21:27 UTC
Labels: enhancement, area-blazor
