### ISSUE TITLE
Obtain feedback from resource downloads on Blazor startup

### ISSUE THREAD

**Issue by KieranDevvs** [dotnet/aspnetcore#10106] opened 2019-05-09 10:20 UTC
### Is your feature request related to a problem? Please describe.
Im trying to display to the user, the progress of the download of the Blazor assemblies and any other resources that are required to run the app. 

### Describe the solution you'd like
I would like a way of exposing the progress events of file downloads so that I can obtain information such as:
1) The a of resources that are required to be downloaded before the app can boot.
(I think `blazor.boot.json` has this information however it would be nice to have access to the data within `blazor.webassembly.js` without having to request it again)
2) The progress of any given file download (file name, bytes received, bytes left)

### Describe alternatives you've considered
I think this might be as simple as providing a way to set the `XHR.onprogress` event within `285:asyncLoad(url):MonoPlatform.ts` (perhaps via an event handler) as well as a function to get the boot resource configuration that is obtained on `28:fetchBootConfigAsync():Boot.WebAssembly.ts`.

After investigating solutions for this, I found that the files aren't served from the web server thus they don't have a `Content-Length` in the header. I believe this is due to compression. I have a few solution's to this but they all require access to the assemblies on the server at run time, to which isn't made easy to change or access. If we are given the option to control where the output of the builds go and where kestrel hosts them from, its possible to pre-load some of this information into the client before sending it to the user.

**Comment by mkArtakMSFT** [comment] 2019-05-10 16:51
Thanks for contacting us, @KieranDevvs.
We're moving this issue to the backlog. In the meantime a possible solution you can use here is to provide your custom `fetch` wrapper, which would include progress tracking logic.

**Comment by SteveSandersonMS** [comment] 2020-10-14 14:48
Duplicate of https://github.com/dotnet/aspnetcore/issues/25165

**Closed by SteveSandersonMS** 2020-10-14 14:48 UTC
Labels: area-blazor, enhancement
