### ISSUE TITLE
Blazor does not passes typeparam TItem into EventCallback through attribute [CascadingTypeParameter(nameof(TItem))]

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#39847] opened 2022-01-28 21:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-does-not-passes-typeparam-TItem-i/1649567)._

---
.net 6 Blazor can not pass typeparam TItem=UserCommonDto into EventCallback<ColumnCellChangeEventArgs<UserCommonDto, int, IntEdit>> through attribute [CascadingTypeParameter(nameof(TItem))] (first screenshot) but everething works fine if i declare TItem=UserCommonDto explicitly (second screenshot)

Component signature where i'm trying to pass typeparam: TNCRGridIntColumn<TItem>

Compiler error:
Pages_DataGridTestPage_razor.g.cs(406,62,414,30): error CS1503: Argument 11: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback' to 'Microsoft.AspNetCore.Components.EventCallback<TNCR.AspNetCore.Razor.Grids2.Events.ColumnCellMouseEventArgs<TNCR.Playground.Shared.UserCommonDto, int, TNCR.AspNetCore.Razor.Edits.IntEdit>>'
Pages_DataGridTestPage_razor.g.cs(414,36,422,30): error CS1503: Argument 13: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback' to 'Microsoft.AspNetCore.Components.EventCallback<TNCR.AspNetCore.Razor.Grids2.Events.ColumnCellChangeEventArgs<TNCR.Playground.Shared.UserCommonDto, int, TNCR.AspNetCore.Razor.Edits.IntEdit>>'

! [1.png] (https://aka.ms/dc/image?name=B5fa553532c8f4070a24b5d59fa77bdc9637789417968285126_20220128-124315-1.png&tid=5fa553532c8f4070a24b5d59fa77bdc9637789417968285126)
! [2.png] (https://aka.ms/dc/image?name=B9a837ed3199a4cc69846e6ae17f10f79637789418019970397_20220128-124321-2.png&tid=9a837ed3199a4cc69846e6ae17f10f79637789418019970397)

---
#### Feedback Bot on 1/27/2022, 11:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2022-01-28 22:01
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by javiercn** [comment] 2022-01-31 10:56
Thanks for contacting us.

This issue is a dupe of https://github.com/dotnet/aspnetcore/issues/37569

**Closed by javiercn** 2022-01-31 10:56 UTC
Labels: Needs: Author Feedback, area-blazor, Author: Migration Bot :robot:

**Comment by ch3l** [comment] 2022-02-02 12:29
Hi. Reproduction repo: https://github.com/ch3l/39847
