### ISSUE TITLE
The idempotency issue with UserManager

### ISSUE THREAD

**Issue by grahamthesmith** [dotnet/aspnetcore#19165] opened 2020-01-16 17:12 UTC
We are using transactions when we use UserManager alongside standard EF Core database updates. We are considering options 3 and 4 for the idempotency issue, however there is nothing in the article to explain how we can do that, due to the fact that UserManager has its own SaveChanges (which will not use acceptAllChangesOnSuccess: false).

Can the documentation be updated to explain either how to avoid this issue, or to clarify whether this will work when using UserManager methods within ExecuteInTransaction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 876c88d4-2972-d905-28d7-56f9e589f309
* Version Independent ID: 29002343-fa42-2f49-3362-53592039b26d
* Content: [Connection Resiliency - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#feedback)
* Content Source: [entity-framework/core/miscellaneous/connection-resiliency.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/connection-resiliency.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by blowdart** [comment] 2020-03-18 19:17
UserManager wraps all its individual methods with autocommit, you can't do it realistically inside a single transaction.

**Comment by blowdart** [comment] 2020-03-25 18:59
We're closing this issue as the behaviour discussed seems to be by design.

**Closed by blowdart** 2020-03-25 18:59 UTC
Labels: area-identity, discussion
