### ISSUE TITLE
Failed to authenticate HTTPS connection

### ISSUE THREAD

**Issue by chengyanbing** [dotnet/aspnetcore#35117] opened 2021-08-06 16:59 UTC
### Describe the bug
Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.

### To Reproduce
Use Visual Studio Community 2019(V16.10.4) with .net5 to create a Asp.Net Core empty project(use empty project template), in order to get more logs I change "Microsoft": "Warning" to "Microsoft": "Debug" in  the "appsettings.Development.json" file , then run it! To my surprise output shows a exception like this:
......
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
.......
What happened? I don't know at all as a beginner. And I try to search it on internet, but I don't find any similar problem and answers.
Then I test swapping sequence of "applicationUrl": "https://localhost:5001;http://localhost:5000" in the "launchSettings.json" file, become "applicationUrl": "http://localhost:5000;https://localhost:5001", then run it again, the  exception disappears this time. 
Am I doing the right thing?

### Further technical details
.NET SDK:
 Version:   5.0.302
 Commit:    c005824e35

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

**Comment by adityamandaleeka** [comment] 2021-08-06 20:16
If you navigate to that https address in a browser, does it work? If so, the error may just be a tooling issue that could be ignored.

**Comment by adityamandaleeka** [comment] 2021-08-06 20:16
This may be a duplicate of https://github.com/dotnet/aspnetcore/issues/26771

**Comment by chengyanbing** [comment] 2021-08-07 02:51
First, sorry for duplicate of this subject.  I'm not familiar with using search in the github.
This exception infomation appears only when we use  "Project" to run it. It doesn't appear when we use "IISExpress".
After I swapped sequence of ` "applicationUrl": "https://localhost:5001;http://localhost:5000"` in the file "launchSettings.json", both "http://localhost:5000" and "https://localhost:5001" still work very well. 
And even we can add a item `"launchUrl": "https://localhost:5001"` in the file "launchSettings.json", so "https://localhost:5001"  will be opened in the browser when you run project just like before I swap sequence of it.

**Comment by adityamandaleeka** [comment] 2021-08-09 20:10
It sounds like this is a harmless debug-level log, so closing this issue. Please comment if this is actually causing other issues for you.

**Closed** 2021-08-09 20:10 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Needs: Attention :wave:, Status: Resolved
