### ISSUE TITLE
Unable to publish project with resx files since 17.12.0 Preview 1.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57619] opened 2024-08-30 18:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-publish-project-with-resx-file/10725151)._

---
[regression] [worked-in:17.11]
Since i updated my visual studio to 17.12.0 Preview 1.0, im unable tu publish projects which contains resx files (blazor webapp .net8.0, the publish target linux) , they all finish with this error
System.InvalidOperationException: Can't find the original satellite assembly in the list of resolved files to publish for asset 'C:\Users\julie\source\repos\BlazorAppTestPublishRessource\BlazorAppTestPublishRessource\BlazorAppTestPublishRessource.Client\bin\Release\net8.0\wwwroot\_framework\fr\BlazorAppTestPublishRessource.Client.resources.wasm'. ...

You will find a reproductible project here : https://github.com/julienGrd/BlazorAppTestPublishRessource
- checkout the project with a 17.12.0 Preview 1.0 visual studio
- publish the BlazorAppTestPublishRessource project
- the publish will finish in error

thanks !

---
#### Feedback Bot on 8/19/2024, 09:24 AM: 

(private comment, text removed)
#### Feedback Bot on 8/20/2024, 10:18 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment] 2024-08-30 18:44
Dupe of https://github.com/dotnet/runtime/issues/105399

**Closed by javiercn** 2024-08-30 18:44 UTC
Labels: area-blazor, Author: Migration Bot :robot:
