### ISSUE TITLE
Can not debug Blazor WASM page with enum as attribute parameter

### ISSUE THREAD

**Issue by sjohag** [dotnet/aspnetcore#31749] opened 2021-04-13 13:22 UTC
### Describe the bug
When an enum is used as parameter to an attribute on a page, debugging is not working.

### To Reproduce
Create a new project (Blazor WASM, .NET 5, hosted).
In the **shared project** create an attribute MyAttribute (code snippet).
Create an enum MyEnum (code snippet).
Add a constructor to the attribute taking the enum as parameter.

In the **client project**, add the attribute to the Counter page.

If the constructor with enum is used, debugging **is not** working.
If the constructor with string is used, debugging **is** working.

The page works functionally correct with both constructors, it is just debugging that is not working.

Small repo at https://github.com/sjohag/WASMDebugProblem.git

The actual use case I have is a custom AuthorizeAttribute with roles in an enum.

### Further technical details
- ASP.NET Core version 5.0.5, SDK 5.0.202
- VS 2019 16.9.3

**Comment by captainsafia** [comment] 2021-04-13 15:35
@sjohag It looks like you are running into a dupe of https://github.com/dotnet/runtime/issues/47792.

This issue was resolved in .NET 6 Preview 3.

**Closed by captainsafia** 2021-04-13 15:35 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-debugging
