### ISSUE TITLE
Only one thing if you could fix in 2020 - Deployment Experience

### ISSUE THREAD

**Issue by naveedahmed1** [dotnet/aspnetcore#17878] opened 2019-12-14 15:50 UTC
### Describe the bug
Its not that difficult and painful to make changes in code to upgrade to a new version of .net core than to be able to successfully deploy it on server.

I don't remember any single version of .net/.net core in which I made changes to my code to upgrade, published project, uploaded contents to the server and it worked in first attempt.

1. In case of failed deployment, the error messages are unclear and unfriendly.
2. IIS often locks dll/web.config and other application files and when we have a busy application, we have to wait for ~15-30 min for IIS to release the lock, which results in website downtime. Even `app_offline.htm` doesn't help.

Honestly this is the only thing I want your team to fix in 2020. If you ask me if I want .Net 5 or a fix for this issue, my response would defiantly be a fix for this issue.

I know there are other issues on this repository, that refers to the same or almost similar issues. But I am still posting it as a new issue so that it can get some priority.

Ideally I want the same deployment experience that we had for Classic ASP about 2 decades ago, in which we just uploaded the files on the server and it always worked.  

.Net/Core team has done an excellent job in case of performance and features but unfortunately, deployment experience has become more and more painful with each new release.

### Further technical details
- ASP.NET Core version: Its same for all version, even worse with .Net Core 3.x

**Comment by JunTaoLuo** [comment] 2020-09-30 17:27
@jkotalik Not sure if we did or plan to do any work in deployment. Putting this in discussion for now since there's no clear work item at the moment.

**Comment by jkotalik** [comment] 2020-09-30 17:49
I think this is something we'd like to reevalutate in 6.0.

**Comment by jkotalik** [comment] 2021-02-18 19:22
Duplicate of https://github.com/dotnet/aspnetcore/issues/3793. We are actively working on a PR https://github.com/dotnet/aspnetcore/pull/28357 that will fix this. We'd appreciate feedback once this feature is available in preview.

**Closed** 2021-02-18 19:26 UTC
Labels: External, affected-medium, area-servers, enhancement, servers-iis, severity-nice-to-have
