### ISSUE TITLE
Updating from 2.1 to 3.1 - HTTP Error 500.0 - ANCM In-Process Handler Load Failure

### ISSUE THREAD

**Issue by johnwc** [dotnet/aspnetcore#24612] opened 2020-08-06 03:44 UTC
Trying to use a [MS sample code for Azure Ad/OpenID](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp#option-2-register-and-manually-configure-your-application-and-code-sample), I received this error when changing the version of .Net Core to 3.1. Looking through #6111, I could not find any solutions. I deleted the .vs folder thinking that the IIS Express .config file just needed to be recreated correctly for the new version because of the new InProcess module, still nothing. Then I ran across some post on asp.net site about someone having this issue and found that it was caused because of a space in the project name. I tested if that was the issue, and it seemed to fix it. Even though I had no spaces. I rename the project from `WebApp-OpenIDConnect-DotNet` to just simply `WebApp`, low and behold it started as expected. There seems to be an issue with the length of the assembly name, as I renamed it back and changed the assembly name to be `WebApp`, and it successfully started again. To rule out file path being to long, I moved the project to the root of the drive and left the assembly name long, same error.

**Comment by BrennanConroy** [comment] 2020-08-07 21:16
This is caused by having "dotnet" in the project name
Dupe of https://github.com/dotnet/aspnetcore/issues/17393 which is fixed in 5.0.

**Closed** 2020-08-12 20:08 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers
