### ISSUE TITLE
SSR/server interactivity Error Boundary not working with Blazor Web App Pre6/7

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#49679] opened 2023-07-27 13:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error boundary seems dysfunctional in ordinary use in Pre6 (i.e., not just with Forms, which was a fix for Pre7 on #47903). The circuit is lost, and the normal Blazor error UI is shown ...

> [2023-07-27T13:37:59.374Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'.

![image](https://github.com/dotnet/aspnetcore/assets/1622880/a16cfcaa-f363-4db9-aa5c-3efd6e718c92)

### Expected Behavior

Normal Error Boundary processing. The following is from a Blazor Server 7.0 app ...

![image](https://github.com/dotnet/aspnetcore/assets/1622880/0a9ea5bf-0536-48e4-8a65-d27a00ccdef5)

### Steps To Reproduce

In `Shared/MainLayout.razor` ...

```razor
<article class="content px-4">
    <ErrorBoundary>
        @Body
    </ErrorBoundary>
</article>
```

In `Pages/Counter.razor` ...

```csharp
private void IncrementCount()
{
    currentCount++;

    if (currentCount > 5)
    {
        throw new InvalidOperationException("Current count is too big!");
    }
}
```

... with `AddServerComponents` + `AddServerRenderMode`.

### Exceptions (if any)

No exception. The error boundary is dysfunctional.

### .NET Version

8.0.100-preview.6.23330.14

***UPDATE***: Still broken in Pre7 (8.0.0-preview.7.23375.6).

**Comment by SteveSandersonMS** [comment] 2023-08-23 12:42
@guardrex You didn't mention what you're doing to make the `ErrorBoundary` itself interactive. If it's not interactive, it's not running in the interactive circuit, so it can't have any effect on exceptions thrown in the interactive circuit.

If you were to make the whole app interactive from the `Router` downwards (e.g., in the Blazor Web template, go into `Routes.razor` and put `@attribute [RenderModeServer]` at the top) then the layout and all its contents, including `ErrorBoundary`, would be interactive and hence it would work as you expected.

I'll close this as by design, but please let me know if you think I'm missing anything!

**Closed by SteveSandersonMS** 2023-08-23 12:42 UTC
Labels: bug, area-blazor

**Comment by guardrex** [comment] 2023-08-23 13:03
.... *almost good!* 😄

> make the whole app interactive from the Router downwards

I'm concerned about this because devs might not want SSR applied to the whole app. Let me know if there's something special that needs to be called out about this ... or some other approach. Are we going to say that error boundaries can't be enabled via `MainLayout` unless they commit to taking this drastic step?
