### ISSUE TITLE
SystemTextJsonOutputFormatter WriteAsync returns an empty string

### ISSUE THREAD

**Issue by mattfrear** [dotnet/aspnetcore#23285] opened 2020-06-24 03:34 UTC
I am the author of a NuGet package Swashbuckle.AspNetCore.Filters, which has been around for a few years. It supports Newtonsoft's JSON.NET and I am trying to make it work with System.Text.Json. https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/149

The issue is that when calling `SystemTextJsonOutputFormatter.WriteAsync(outputFormatterContext)`, it doesn't use the WriterFactory on the passed in `OutputFormatterWriteContext`.

See
https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/Formatters/SystemTextJsonOutputFormatter.cs#L59
vs
https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonOutputFormatter.cs#L120
and
https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Formatters.Xml/src/XmlDataContractSerializerOutputFormatter.cs#L233
(Ctrl+f for WriterFactory)

### To Reproduce
I have uploaded a simple repro here (a Console app).
https://github.com/mattfrear/SystemTextJsonOutputFormatterFail

The code is:
```csharp

private static void Main()
{
    var person = new Person { Title = Title.Mr, FirstName = "Matt", Age = 99, Income = 1234 };

    // Serialize using XmlDataContractSerializerOutputFormatter - works
    var xmlFormatter = new XmlDataContractSerializerOutputFormatter();
    var result = Serialize(person, xmlFormatter, ApplicationXml);
    Console.WriteLine("Xml: " + result);

    // Serialize using NewtonsoftJsonOutputFormatter - also works
    var newtonsoftFormatter = new NewtonsoftJsonOutputFormatter(new Newtonsoft.Json.JsonSerializerSettings(), ArrayPool<char>.Shared, new MvcOptions());
    result = Serialize(person, newtonsoftFormatter, ApplicationJson);
    Console.WriteLine("Newtonsoft Json: " + result);

    // Serialize using SystemTextJsonOutputFormatter - returns empty string :-(
    var systemTextJsonFormatter = new SystemTextJsonOutputFormatter(new System.Text.Json.JsonSerializerOptions());
    result = Serialize(person, systemTextJsonFormatter, ApplicationJson);
    Console.WriteLine("System.Text.Json: " + result);

    Console.ReadLine();
}

private static string Serialize<T>(T value, IOutputFormatter formatter, MediaTypeHeaderValue contentType)
{
    using (var stringWriter = new StringWriter())
    {
        var outputFormatterContext = GetOutputFormatterContext(
            stringWriter,
            value,
            value.GetType(),
            contentType);

        formatter.WriteAsync(outputFormatterContext).GetAwaiter().GetResult();
        stringWriter.FlushAsync().GetAwaiter().GetResult();
        return stringWriter.ToString();
    }
}
```

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
```
C:\code\github\SystemTextJsonOutputFormatterFail>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.607 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\code\github\SystemTextJsonOutputFormatterFail>
```
- VS 2019 16.6.2

**Comment by davidfowl** [comment] 2020-06-24 08:29
This is by design because System.Text.Json doesn't use the StreamWriter (in the API doesn't even support UTF16!). You need to wrap the stream directly to intercept writes.

**Comment by javiercn** [comment] 2020-06-24 08:50
@mattfrear thanks for contacting us.

@davidfowl answer is correct, this is by design.

We're closing this issue as the behavior discussed is by design.

**Closed** 2020-06-24 08:50 UTC
Labels: :heavy_check_mark: Resolution: By Design, Status: Resolved, area-mvc, question

**Comment by pranavkm** [comment] 2020-06-24 14:14
Thanks for the issue report @mattfrear. `WriterFactory` is only used when a formatter has char data to write, that is writes to a `TextWriter`. The `WriterFactory` is primarily about efficiently managing encoding the chars to bytes . System.Text.Json produces binary output (writes to a `Stream`) API which is why it does not use this API.

You could replace the `HttpResponse.Body` with a and that should work in either case.

**Comment by mattfrear** [comment] 2020-06-25 06:08
Thanks everyone for the quick response! Much appreciated.

@pranavkm I didn't quite understand your reply, 'You could replace the HttpResponse.Body with a and that should work in either case.' What did you mean?
