### ISSUE TITLE
The type initializer for 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception.

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#36965] opened 2021-09-25 08:03 UTC
xamarin.forms ios  error 
The type initializer for 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception.
Visual Studio Professional 2019 for Mac
Version 8.10.9 (build 3)
Installation UUID: d6992803-fd76-4737-ac3a-329c56a55aca
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

Mono Framework MDK
Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

Xamarin Designer
Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

Roslyn (Language Service)
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

NuGet
版本: 5.9.0.7134

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK 版本:
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	3.1.413
	3.1.412
	3.1.411
	3.1.410
MSBuild SDK: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core 运行时
运行时: /usr/local/share/dotnet/dotnet
运行时版本:
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	3.1.19
	3.1.18
	3.1.17
	3.1.16

.NET Core 3.1 SDK
SDK: 3.1.413

Xamarin.Profiler
版本: 1.6.15.68
位置:/Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
版本: 11

Xamarin.Android
版本: 11.3.0.4 (Visual Studio Professional)
提交:xamarin-android/d16-10/ae14caf
Android SDK: /Users/xuzhibin/Library/Developer/Xamarin/android-sdk-macosx
	受支持的 Android 版本:
		未安装任何内容

SDK Tools 版本: 26.1.1
SDK 平台工具版本: 30.0.4
SDK 生成工具版本: 30.0.2

生成信息:
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Microsoft OpenJDK for Mobile
Java SDK: /Users/xuzhibin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL 代码在此处提供:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

Android Device Manager
Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

Apple Developer Tools
Xcode 13.0 (19234)
Build 13A233

Xamarin.Mac
Version: 7.14.0.24 (Visual Studio Professional)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

Xamarin.iOS
Version: 15.0.0.6 (Visual Studio Professional)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

Build Information
Release ID: 810090003
Git revision: 156eb53c9c668cb7ff4311ae3d1dab894549848b
Build date: 2021-09-08 07:26:54-04
Build branch: release-8.10

Operating System
Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:27 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 x86_64

**Comment by BrennanConroy** [comment] 2021-09-25 16:46
This looks like this is a dupe of https://github.com/mono/mono/issues/20805. Does [this workaround](https://github.com/mono/mono/issues/20805#issuecomment-791440473) solve your issue?

**Closed by BrennanConroy** 2021-09-25 16:46 UTC
Labels: area-signalr

**Comment by bbhxwl** [comment] 2021-09-26 01:36
The article discusses a lot. My English is not good. Is the following code the solution?


<ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.4">
      <IncludeAssets>none</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Buffers" Version="4.5.1">
      <IncludeAssets>none</IncludeAssets>
    </PackageReference>
  </ItemGroup>

**Comment by BrennanConroy** [comment] 2021-09-26 02:04
> Is the following code the solution?

That's what a lot of people have been saying.

**Comment by bbhxwl** [comment] 2021-09-26 05:48
> > Is the following code the solution?
> 
> That's what a lot of people have been saying.

iOS.csproj Is this the file?
