### ISSUE TITLE
__virtual.html files showing in warnings

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#27128] opened 2020-10-22 22:32 UTC
### Describe the bug
We see the virtual.html file inside some warnings in the error-list.

### To Reproduce
1. New BlazorServer with AspNetCore hosting.
1. Replace contents of `Index.razor` with:
```
@page "/"
@using Microsoft.AspNetCore.SignalR.Client
@inject NavigationManager NavigationManager;
```
1. See 
![image](https://user-images.githubusercontent.com/14987221/96936578-30f7a100-147b-11eb-8704-76ebef2304b1.png)

#### Language Server logs
[Razor Language Server Client-20201021172005.log](https://github.com/dotnet/aspnetcore/files/5426274/Razor.Language.Server.Client-20201021172005.log)

### Further technical details
- VS version: 16.9.0 Preview 2.0 [30622.150.main]
- Local

**Comment by NTaylorMullen** [comment] 2020-11-11 00:08
Duplicate of: https://github.com/dotnet/aspnetcore/issues/26830

**Closed by NTaylorMullen** 2020-11-11 00:08 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, feature-razor.vs
