### ISSUE TITLE
@on{Event}:preventDefault should work without handler

### ISSUE THREAD

**Issue by MikeIxTech** [dotnet/aspnetcore#28663] opened 2020-12-15 12:33 UTC
### Bug
In some cases, you only want to prevent the default actions on an event without any handling actions.
Using **only** ```@on{Event}:preventDefault``` on a HTML tag will do nothing at all.
Using ```@on{Event}:preventDefault``` and  ```@on{Event}="Handler"``` will prevent default html behavior.
Strangely: Other elements with **only** ```@on{Event}:preventDefault``` will prevent default actions if there is a  ```@on{Event}="Handler"``` on a different HTML tag somewhere in the file!

Would be solved if the ```@on{Event}:preventDefault``` will always prevent the default actions as expected, regardless of using ```@on{Event}="Handler"```.
Another solution would be to raise a compile warning: ```@on{Event}:preventDefault``` will not have any effect, please use standard html attribute ```on{Event}="event.preventDefault()"```

#### This works as expected 
(for drop-zone default cursor and preventing keyboard input on input tag)
```
<div class="drop-zone" @ondragover="@HandleDragOver" @ondragover:preventDefault>
    <div class="drag-item" draggable="true">
        <h2>Item</h2>
    </div>
</div>
<input type="text" @onkeypress:preventDefault @onkeypress="@HandleKeyPress"/>
```

#### This does not prevent default actions 
(when not mixed with the above code in same file)
```
<div class="drop-zone" @ondragover:preventDefault>
    <div class="drag-item" draggable="true">
        <h2>Item</h2>
    </div>
</div>
<input type="text" @onkeypress:preventDefault/>
```

#### HTML/JS Workaround
```
<div class="drop-zone" ondragover="event.preventDefault()">
    <div class="drag-item" draggable="true">
        <h2>Item</h2>
    </div>
</div>
<input type="text" onkeypress="event.preventDefault()"/>
```

### Exceptions (if any)
Only checked at @ondragover (e.g. prevent cursor from becoming 'not-allowed' when dragging over an element) and @onkeypress (e.g. preventing key input on input element)

### Further technical details
Default template ```dotnet new blazorwasm -o <ProjectName>```
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.1" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
  </ItemGroup>

</Project>
```

**Comment by mkArtakMSFT** [comment] 2020-12-15 17:34
Thanks for contacting us. This is a dupe of #18449

**Closed by mkArtakMSFT** 2020-12-15 17:34 UTC
Labels: area-blazor
