### ISSUE TITLE
404, IExceptionHandlerFeature And Response.WriteAsync: Prefixed (Corrupted) Output on .NET 5

### ISSUE THREAD

**Issue by warappa** [dotnet/aspnetcore#35469] opened 2021-08-18 19:07 UTC
### Description
I have an ASP.NET Core exception handler that writes a custom exception info as JSON (see below).
If a resource is _not found_ I throw an exception indicating that the requested resource is not found.

**Only if the status code is 404, then the output is scrambled.**

If I **only change the target-framework** to .NET 6 Preview 7, **it works** also for 404.

It seems as if ASP.NET Core has an optimization, that disposes or reuses 404 response objects immediately, or does not initialize/prepare them correctly.

Sample response (raw, copied from Fiddler (Fiddler does not impact this bug))
```
HTTP/1.1 404 Not Found
Date: Wed, 18 Aug 2021 18:42:13 GMT
Content-Type: application/json
Server: Kestrel
Cache-Control: no-cache,no-store
Pragma: no-cache
Transfer-Encoding: chunked
Expires: -1

18
{error: "error message"}
```
`18` appears out of nowhere (the value can change but it is always 2 characters).

### To Reproduce
1. Create a new .NET 5 Web API project with an API controller.
2. In the controller **throw an exception**, i.e.:
```
[Route("test")]
    [ApiController]
    public class TestController : ControllerBase
    {
        [HttpGet]
        public void Test()
        {
            throw new Exception("Error test");
        }
    }
```
3. Add this **exception handler to the request pipeline**:
```
 app.UseExceptionHandler(options =>
            {
                options.Run(async httpContext =>
                {
                    var ex = httpContext.Features.Get<IExceptionHandlerFeature>();
                    if (ex.Error != null)
                    {
                        var error = ex.Error;

                        httpContext.Response.StatusCode = 404; // i.e. 400 works
                        httpContext.Response.ContentType = "application/json";

                        await httpContext.Response.WriteAsync("{error: \"error message\"}"); // write dummy json
                    }
                });
            });
```
4. Extra: to see prefix garbage: install and start [Fiddler](https://www.telerik.com/fiddler)
5. Run the project and open the url of the controller action throwing the exception in a browser
6. Get no output in browser
7. Extra: check the request in Fiddler and see the prefix
8. Now stop web application
9. Change **target framework to `net6.0`** _**OR**_ change the `StatusCode` to something else but not `404`
10. Rebuild
11. Open url again and see the correct json output

### Exceptions (if any)
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The response ended prematurely.

### Further technical details
Compiled on SDK 5.0.400 and 6.0.100-preview.7.212979.14 - same results (= SDK does not matter)
- ASP.NET Core 5.0.9 broken
- ASP.NET Core 6.0.0-preview.7.21378.6 works
- Visual Studio 2022 P3.1

#### dotnet --info
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  2.1.807 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by davidfowl** [comment] 2021-08-18 19:16
The output isn't scrambled, 18 is the length prefix of a chunked response. 

Looks like a duplicate of this bug https://github.com/dotnet/aspnetcore/issues/32046. It's fixed in .NET 6.

cc @Tratcher @adityamandaleeka

**Comment by warappa** [comment] 2021-08-18 19:21
Thanks @davidfowl, this is indeed a duplicate.
I'm closing this one.

**Comment by warappa** [comment] 2021-08-18 19:45
Using the `RequestDeletate` override of `UseExceptionHandler(...)`, I cannot set `AllowStatusCode404Response`. Also using `services.Configure<ExceptionHandlerOptions>(...)` is not picked up.

It feels like there is an **overload missing**, allowing to provide a custom `ExceptionHandlerOptions` parameter. Or querying the DI for the options.

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerExtensions.cs#L59-L78

For now I have to use the `UseExceptionHandler(ExceptionHandlerOptions options)` override to set the flag and the delegate.

**Comment by Tratcher** [comment] 2021-08-18 19:52
One solution is for that overload to default AllowStatusCode404Response to true. The 404 detection was mainly targeted at the path overload.

**Comment by adityamandaleeka** [comment] 2021-08-18 20:24
Triage: we should disable the 404 detection logic for this overload which takes an app builder.

**Comment by warappa** [comment] 2021-08-18 21:27
A small note as this was added to a .NET **_6_** milestone and not to a .NET **_5_** milestone:
On **.NET 6 preview 7 it works out-of-the-box** using the original extension method - **only .NET 5** requires using a different extension method to workaround (see initial description).

**Comment by Tratcher** [comment] 2021-08-18 21:29
Good point. We fine tuned it in 6.0 so that 404 responses with bodies don't trigger this warning. Given that, we can probably close this.

**Comment by adityamandaleeka** [comment] 2021-08-18 21:36
Thanks @warappa, closing issue.

**Closed by adityamandaleeka** 2021-08-18 21:36 UTC
Labels: area-runtime
