### ISSUE TITLE
Why .Net 5 Web API dll update requires stopping iis app pool while .Net framework dll update just works seamless and applied silently?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29364] opened 2021-01-15 20:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Why-Net-5-Web-API-dll-update-requires-s/1309659)._

---
[severity:I'm unable to use this version] [regression] [worked-in:4.6.1]
We have bunch of ASP.Net Web API (built on .Net Framework 4.x) and have custom CI-CD jobs to push changes to TEST/PROD IIS. These jobs work seamless for past many years. When we started building newer Web API using .Net 5 (using unmanaged app pool CLR version) it works fine on DEV/TEST/PROD but when we push changes via CI-CD it seems we need to stop IIS App Pool for those web API in order to apply the changes unless it prompts the Lock Error. Is this a known issue with .Net 5 Web API dll deployment on IIS or am I missing anything? 
With the extreme automated environment of API deployment we typically push changes to PROD in middle of the day without any issues. All changes pushed (.Net framework 4.x Web API dlls) was seamlessly picked up by IIS until we started with .Net 5 Web API. Restarting App Pool in middle of a business day is out of question. Looking for a feasible solution w/o requiring the IIS / app pool rest.
Please help! 

thanks!
DB

---
#### Feedback Bot on 1/14/2021, 00:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/14/2021, 00:47 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jkotalik** [comment] 2021-01-19 17:03
I believe this is a duplicate of https://github.com/dotnet/aspnetcore/issues/3793, which we are currently prototyping here: https://github.com/dotnet/aspnetcore/pull/28357.

We'd love to get feedback once we have this feature in a preview release.

**Closed by jkotalik** 2021-01-19 17:03 UTC
Labels: Author: Migration Bot :robot:, area-servers
