### ISSUE TITLE
Blazor 8 SSR cannot change Pagetitle when StreamRendering is true or when in rendermodeserver prerendering is false

### ISSUE THREAD

**Issue by SandroRiz** [dotnet/aspnetcore#52689] opened 2023-12-09 17:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is impossibile to set the PageTitle of a blazor page dynamically, based on something that is calculated in the OnInitialized or OnParameterSet

### Steps To Reproduce

Repro Page:

[testpage.razor.txt](https://github.com/dotnet/aspnetcore/files/13625109/testpage.razor.txt)

### .NET Version

8.0.100

**Comment by SandroRiz** [comment] 2023-12-15 13:41
Here you are..
https://github.com/SandroRiz/BlazorPageTitle

**Comment by MackinnonBuck** [comment] 2024-01-13 00:27
Thanks for reaching out. After looking at the repro, this appears to be a duplicate of https://github.com/dotnet/aspnetcore/issues/50268, possibly with the added detail that stream rendering should be accounted for as well. Going to close out this issue in favor of that one.

**Closed by MackinnonBuck** 2024-01-13 00:27 UTC
Labels: area-blazor, Needs: Attention :wave:, Needs: Repro
