### ISSUE TITLE
Rendering issue with Virtualize when scrolled right.

### ISSUE THREAD

**Issue by ctodd1** [dotnet/aspnetcore#29558] opened 2021-01-23 00:45 UTC
### Describe the bug
I have a grid control that I am developing that uses Virtualize. The grid has overflow and when the grid is scrolled right and then scrolled down, the content is not rendered until the user scrolls all of the way back to the left.

### To Reproduce
I have a video illustrating the issue. I can share code if necessary, but I think the issue is on any data repeated with horizonal overflow.

https://www.screencast.com/t/QUnPiLs4rl

I would be a little embarrassed to provide the grid project, but I'll provide it if necessary.

Thanks,
Chris.

**Comment by mkArtakMSFT** [comment] 2021-01-25 17:25
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/28813

**Closed by mkArtakMSFT** 2021-01-25 17:25 UTC
Labels: area-blazor, feature-blazor-virtualization
