### ISSUE TITLE
Scaffolding using Razor Pages using Entity Framework (CRUD) uses antiquated bootstrap classes

### ISSUE THREAD

**Issue by bobopolis** [dotnet/aspnetcore#50090] opened 2023-08-15 20:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When scaffolding using Razor Pages using Entity Framework (CRUD), html is created using "form-group" which is not included in Boostrap 5.1, which the project type automatically includes.  According to Bootstrap examples, "mb-3" is typically used in forms to provide adequate spacing between form controls.

### Expected Behavior

I expected that the scaffolded results should look presentable as a great starting place, using the most up-to-date bootstrap classes that pertain to the version of bootstrap included in the project when created.

### Steps To Reproduce

In Visual Studio, create a new ASP.NET Core Web App.  Create a model, such as following the steps here: [(https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-7.0&tabs=visual-studio)]

Scaffold on that model.  Note the created HTML uses 'form-group' when the included Bootstrap version is 5.1.

### .NET Version

6

**Comment by mkArtakMSFT** [comment] 2023-09-14 16:56
Closing as a dupe of https://github.com/dotnet/Scaffolding/issues/1985

**Closed by mkArtakMSFT** 2023-09-14 16:56 UTC
Labels: area-ui-rendering
