### ISSUE TITLE
Enable Razor Components constructor injection

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/aspnetcore#20776] opened 2020-04-12 19:41 UTC
Hi,

The current method of DI in Razor Components is by decorating the target properties with `TargetAttribute`.

This is not the traditional method of injection using the constructor, and in addition, makes it uncertain for the compiler whether these fields are gonna be null.

When using null reference types of C# 8, the compiler will issue a warning for all those fields, marking them nullable (`?`), they will issue warnings in the UI side of the page, as Razor doesn't seem to support the [null conditional operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-) (`?.` or `?[]`).

One solution could be suppressing the warnings manually or on top of page, like:
```c#
[Inject]
[SuppressMessage("Compiler", "CS8618")]
protected AppDbContext DbContext { get; set; }
```

But the only solution that worked for me was to disable `#nullable` manually in each Razor page with injected properties.

My suggestion is that you extend the Razor generator so that it generate non-parameterless constructors in the same signature as the base-class code-behind.

cc: @guardrex.

**Comment by javiercn** [comment] 2020-04-13 14:38
@weitzhandler thanks for contacting us.

Closing this issue as it is a dupe of #18088. we'll be using that issue to track it.

**Closed by javiercn** 2020-04-13 14:38 UTC
Labels: area-blazor

**Comment by weitzhandler** [comment] 2020-04-13 15:59
Self reference: another alternative is to set the property to `default!` or `null!`.
