### ISSUE TITLE
staticwebassets.runtime.json also includes files from referenced RCL NuGet package

### ISSUE THREAD

**Issue by BasBakker91** [dotnet/aspnetcore#40317] opened 2022-02-19 19:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have the following structure:

- base RCL with shared components, let's call it `base`
- sub RCL module that referenced the `base` RCL, these contain specific components for that project, let's call it `Portal`
   - this is a Blazor app for the Portal module (the user Portal)
- a consuming Blazor app that consumes both RCLs
   - this is a Blazor app for the Admin module (the admin Portal, that also uses user Portal components)

Since .NET 6.0 we've moved to use `staticwebassets.runtime.json` instead of the xml predecessor.

Since we've updated our Blazor app to .NET 6.0, only our admin project does not want to publish anymore.
Building works fine.

It throws the following error (for each static web asset you've got in the referenced RCL):

`C:\Program Files\dotnet\sdk\6.0.102\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(616,5): Error MSB3030: Could not copy the file "C:\Users\{user}\.nuget\packages\Portal\{version}\staticwebassets\{filename}.{extension}" because it was not found.`

Now if we look in the `staticwebassets.runtime.json` in Portal, it has the following structure:

```JSON
{
	"ContentRoots": [
		"Portal.Components\\wwwroot\\",
		"Base.Components\\{version}\\staticwebassets\\",
		"Portal.Components\\obj\\Debug\\net6.0\\scopedcss\\bundle\\"
	],
	"Root": {
		"Children": {
			"app.css": {
				...
			},
			"_content": {
				"Children": {
					"Base.Components": {
						"Children": {
							"app.css": {
								...
							}
						}
					}
				}
			}
		}
	}
}
```

> I've removed bunch of data for brevity

Now, Portal does not have any `wwwroot` files of its own, VS2022 does however show the files from `Base.Components`, with the "linked" file icon. (If I remove the package, those files also go away).

As you can see the `staticwebassets.runtime.json` just assumes that we also have the `app.css` file in the portal's `wwwroot`. This is not the case. It looks like the code that generates the `staticwebassets.runtime.json` does not filter out the "linked" files?

So when we publish `Admin`, who references `Portal`, it tries to copy files from the `Portal`'s staticwebassets, even though they only live in the `Base` nuget package.

> The Portal reference is also a nuget package reference btw

### Expected Behavior

The expected behavior would be to not have the referenced RCL files in the in the `[Root].[Children]` of the referencing project's `staticwebassets.runtime.json`.

They should be in the `[Root].[Children].[_content].[rcl_name].[Children]`.

### Steps To Reproduce

Not really easy to reproduce. =(

### .NET Version

6.0.102

### Big note

With the previous XML version of the `staticwebassets` it all worked fine.

**Comment by SteveSandersonMS** [comment] 2022-02-21 18:01
Thanks for the report. Are you able to supply a minimal repro project as a GitHub issue? We will then investigate.

**Comment by BasBakker91** [comment] 2022-02-22 09:20
> Thanks for the report. Are you able to supply a minimal repro project as a GitHub issue? We will then investigate.

Hey @SteveSandersonMS, I will try to replicate it with public NuGet packages.

**Comment by javiercn** [comment] 2022-02-22 11:10
@BasBakker91 On a second look, I think what is likely happening here has to do with `Link`.

We added support for `Link` in static web assets on .NET 6.0, so we will treat that file as if it was part of the wwwroot folder. 

Without more details I can't suggest an alternative as it's not clear to me what you are trying to do with the linking.

**Comment by BasBakker91** [comment] 2022-02-22 16:55
Hey @javiercn . Yeh that is something weird. Because we just added the NuGet package, and then it adds those files to the `wwwroot` as linked files. If we remove the package again, they're removed from the `wwwroot` again.

So here without the package:

![image](https://user-images.githubusercontent.com/6542546/155179955-0f17a50c-fdcc-4e40-bd78-01573f15245f.png)

Here with the package:

![image](https://user-images.githubusercontent.com/6542546/155180039-13c73195-ed4e-4617-9cbf-183c5b5dde24.png)

I didn't find any weird properties in neither of the projects (the referencing package or the referenced package).

Got any ideas?

**Comment by javiercn** [comment] 2022-02-22 16:57
@BasBakker91 the key would be to identify where those linked files are coming from.

**Comment by BasBakker91** [comment] 2022-02-22 18:18
@javiercn That is what I thought. Got any idea where I should start looking?

**Comment by javiercn** [comment] 2022-02-22 19:02
@BasBakker91 capture an MSBuild binlog `(dotnet build /bl or dotnet publish /bl)` and look at it with MSBuildStructuredLogViewer

**Comment by BasBakker91** [comment] 2022-02-22 22:02
Took me a while, but I figured it out

I added a zip file that contains all the files you need to reproduce this.
As also stated in the readme, I am not sure if this is a bug or a feature. 

@javiercn If you need any more information, let me know!

[LinkedFilesTest.zip](https://github.com/dotnet/aspnetcore/files/8120460/LinkedFilesTest.zip)

For people that stumble on this issue in the future, here is a the content of the readme, this might help you:

---

The issue is that we have a nuget package with content in it,
that is recognized as staticwebassets, but it also added a content to the nuget package.

Since it is content, the consuming projects adds it as linked resources.
(see `file-from-library-1.js` in RCL2)
This confuses something in the MS builder/publisher/packer (I dunno?) 
when copying RCL2 content to BlazorApp1, it tries to copy `file-from-library-1.js` from RCL2,
but that does not exist.

## Reproduce

In RCL1:

- dotnet restore
- dotnet build -c release --no-restore
- dotnet pack --include-symbols --no-restore --no-build -c Release

Upload package to NuGet (or any other package manager)

> I did NuGet, see: https://www.nuget.org/packages/LinkedFilesTestRCL1/1.1.0

In RCL2:

- Add package reference
- in wwwroot you now have a linked `file-from-library-1.js` file.
- dotnet restore
- dotnet build -c release --no-restore
- dotnet pack --include-symbols --no-restore --no-build -c Release

Upload package to NuGet (or any other package manager)

> I did NuGet, see: https://www.nuget.org/packages/LinkedFilesTestRCL1/1.1.0

Add package RCL2 to the BlazorApp1, try to publish BlazorApp1.

You will now get the error message that it can't copy `file-from-library-1.js` while building RCL2.

```
Could not copy the file "C:\Users\Bas\.nuget\packages\linkedfilestestrcl2\1.1.0\staticwebassets\file-from-library-1.js" because it was not found
```

## Related issue

It looks like this issue: https://github.com/dotnet/aspnetcore/issues/36740#issuecomment-942026683
However, we're not using `GeneratePackageOnBuild`.

I don't know if this is a feature or a bug. =)

**Comment by javiercn** [comment] 2022-02-23 10:16
@BasBakker91 thanks for taking the time.

This helps clarify things a lot. From your description, this is a dupe of an existing issue. https://github.com/dotnet/aspnetcore/issues/38371#issuecomment-970448018

I'm going to close the existing issue for this one as it has more context on it.

**Comment by BasBakker91** [comment] 2022-02-23 12:14
@javiercn You're very welcome! It was a fun bug hunt.

If you need any more information, please let me know.

**Comment by musictopia2** [comment] 2022-03-05 14:54
Any possibility of this problem being fixed before .net 7.  Because i discover that for now, if I create a nuget package without also doing a build, then if others use it, then sometimes don't even work.  If a person is forced to do a build, then it interferes with figuring out if there was any changes in the files.

**Comment by Timmoth** [comment] 2022-04-03 08:48
What worked for me was to remove 

`<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`

 from the csproj as well as `--no-restore --no-build`  from the `dotnet pack` as suggested by @BasBakker91

**Comment by musictopia2** [comment] 2022-04-03 12:59
The only problem with adding the extra generatepackageonbuild is everytime i build the project, it will generate a nuget package.  However, sometimes i need an extra process to do it so it can increment the version number and even post to nuget.  For now, the temporary solution is i had to take out the nobuild.  which means i have to do that project by itself, otherwise, the autoupdate system will always think there is an update when there is not when running the process.

**Comment by javiercn** [comment] 2022-04-22 14:07
This is likely addressed https://github.com/dotnet/sdk/pull/25011 here since the original issue was that some assets were being incorrectly packed as content.

**Comment by javiercn** [comment] 2022-05-13 13:11
We are going to use https://github.com/dotnet/aspnetcore/issues/36880 to track these changes in https://github.com/dotnet/sdk/pull/25011 that will fix this issue.

**Closed by javiercn** 2022-05-13 13:11 UTC
Labels: bug, area-blazor, triaged, feature-static-web-assets, Priority:1, feature-razor-sdk
