### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by hultqvist** [dotnet/aspnetcore#21239] opened 2020-04-27 15:24 UTC
### Describe the bug

Change in `<input value="">` that triggers `@onchange` is not reflected in the virtual DOM. 
Value in virtual DOM is not sent to DOM unless the value is different from previous in virtual DOM.

When the user changes the value in an input field there is no simple way to restore the value with a simple operation.

We need som way to tell the virtual dom that this value has change in the real DOM and needs to be updated to the same value as last time.

#### Expected behavior

* Enter "::4" and leave field
* Field changes to "4"
* Enter "::4" and leave field
* Field changes to "4"
* Enter "123" and leave field
* Field changes to ""
* Enter "123" and leave field
* Field changes to ""

Place the script tag in the static HTML to compile.

``` HTML
<script>
    function only4(input) {
        if (input.value == '::4') {
            input.value = '4';
            return;
        }
        input.value = '';
    }
</script>
<input onchange="only4(this)">
```

#### Actual behavior

* Enter "::4" and leave field
* Field changes to "4" - correct
* Enter "::4" and leave field
* Field remains "::4" - unexpected
* Enter "123" and leave field
* Field changes to ""
* Enter "123" and leave field
* Field remains "123" - unexpected

``` C#
<input value="@Text"
       @onchange="TextChanged" />

@code{
    public string Text { get; set; } = "";

    void TextChanged(ChangeEventArgs args)
    {
        Debug.WriteLine("Changed: " + args.Value);
        if (args.Value as string == "::4")
        {
            Text = "4";
            return;
        }

        Text = "";
    }
}
```

**Entering "::4"**
First time entering "::4" the event is triggered and the field is modified.
Second time entering "::4" the event is not triggered and the text "::4" is left.

**Entering anything else**

First time entering: Input is reverted back to empty string.
Second time, Input text remains whatever was entered.

### Workaround

The second issue can be mitigated by slightly modifying the value.
With an empty value switching between null and "" is ok, when the value is anything else we need to add other characters such as space.

``` C#
            //Text = "4";
            if (Text == "4")
                Text = "4 ";
            else
                Text = "4";

        //Text = "";
        if (Text == "")
            Text = null;
        else
            Text = "";

```

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by mkArtakMSFT** [comment] 2020-04-27 16:25
Thanks for contacting us. This is a dupe of #17281

**Closed by mkArtakMSFT** 2020-04-27 16:25 UTC
Labels: area-blazor
