### ISSUE TITLE
For Blazor wasm hosted App, ability to run server side component for some sensitive page

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#33691] opened 2021-06-20 13:12 UTC
For Blazor wasm hosted app, is it possible to also run the server side Blazor component ?
I have a some sensitive logic that only need to be run on server and just display output, since wasm already has server side Blazor is it possible to run some component on server. The server side component does not need any interactivity so no Signal R needed, but ability to be invoked via URL and output the generated results.

**Comment by rogihee** [comment] 2021-06-21 04:51
You could use the tag helper <component RenderMode="static" />

**Comment by javiercn** [comment] 2021-06-21 09:49
@nssidhu thanks for contacting us.

This is not something you can do today.

**Comment by danroth27** [comment] 2021-10-14 17:52
Duplicate of https://github.com/dotnet/aspnetcore/issues/37131

**Closed by danroth27** 2021-10-14 17:52 UTC
Labels: area-blazor, blazor-server
