### ISSUE TITLE
Breakpoints not being hit in hosted Blazor WASM project in Visual Studio 2019Pro /2019 Pro Preview

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30501] opened 2021-02-26 18:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Breakpoints-not-being-hit-in-hosted-Blaz/1345897)._

---
I have a Hosted Blazor WASM app (.net 5) and am unable to hit any breakpoints in Visual Studio. Note that I can hit breakpoints in the API.

I have tried repairing/reinstalling VS but still no dice. Every now and then (maybe like once a week) I'm able to hit a breakpoint but other than that it never works.

---
#### Feedback Bot on 2/22/2021, 07:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-02-26 18:35
Thanks for contacting us.
@captainsafia can you please work with the customer to collect all the necessary information to understand what's causing this? Thanks1

**Comment by devlife** [comment] 2021-03-04 19:41
Hi all. Any movement on this?

**Comment by sharpninja** [comment] 2021-03-15 21:58
Any word on this?  I can replicate this in VS 2019 16.9 and 16.10.  With VS Code, I am able to debug just fine using this launch config:

        {
            "name": "Attach Blazor WASM",
            "type": "blazorwasm",
            "request": "attach",
            "cwd": "${workspaceFolder}/CareTeam/Client",
            "browser": "edge",
            "url": "https://localhost:5001",
            "internalConsoleOptions": "openOnSessionStart"
        }

In both cases, the app is being launched like this before debugging in VS2019 or VS Code:

```powershell
dotnet watch run ${workspaceFolder}/src/Project.Server.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
```

**Comment by captainsafia** [comment] 2021-03-17 22:57
I took a look at the debugger logs provided in the original issue. It seems to indicate that the user was able to successfully debug. There's a `loadSource` event emitted for the DLLs in the app and a paused in breakpoint event. Would recommend reproing the issue and sharing the `%TEMP/visualstudio-js-debugger.txt` file generated after the failure.

@sharpninja Your report seems to suggest that things work in VS Code but not in VS. For that case, I'd recommend using the `Report feedback` tool in VS so we can get the logs to determine what's going on.

**Comment by adrianwright109** [comment] 2021-03-18 18:47
I too am having the same issue.  

I set breakpoints in a component of a Blazor Web Assembly hosted app and the breakpoints initially look set and bound as they are solid red as shown below:
![image](https://user-images.githubusercontent.com/47532258/111679194-f53de900-8818-11eb-9fd7-7d6acecfa0e3.png)

When I press `F5` to launch Visual Studio (16.10.0 Preview 1.0) debugging using an IIS Express profile the breakpoints change and become unbound as shown below:
![image](https://user-images.githubusercontent.com/47532258/111679621-46e67380-8819-11eb-8668-7391752c45f1.png)

It is very annoying.  Let me know if there is any other information I can give you to help investigate the issue.

I did try submitting a bug report via Visual Studio but said my bug was a duplicate and it sent me to this github issue.

**Comment by adrianwright109** [comment] 2021-03-19 23:17
@captainsafia - think this issue could be the same as one I've just raised, #31063.  In that issue you'll see that I be submitted the bug report through VS so you should behave all the logs to help with investigation.  Thanks

**Comment by devlife** [comment] 2021-03-23 19:59
@adrianwright109 I also submitted the feedback via Visual Studio and they moved it here.

**Comment by captainsafia** [comment] 2021-03-23 22:19
@adrianwright109 I posted a response to the issue you reference. I believe we might've recently fixed the bug you've run into and posted instructions on how to verify this for your solution.

@devlife I've triaged a few issues that came from VS feedback. Can you point me to your so I can confirm that it's gotten triaged?

**Comment by devlife** [comment] 2021-03-24 14:23
Here you go @captainsafia: https://developercommunity2.visualstudio.com/t/Breakpoints-not-being-hit-in-hosted-Blaz/1345897

**Comment by captainsafia** [comment] 2021-03-24 16:24
@devlife Thanks! It looks like the issue we are currently having this discussion on is yours.

I looked through the logs from your session. It looks like you might be using a Blazor component with a partial class. Can you confirm?

I do see that the debugger is able to load the C# sources for the Client side of your app correctly. Are you able to set the breakpoints in the `.razor` files?

And finally: what version of .NET 5 are you on? I assume latest patch release?

**Comment by devlife** [comment] 2021-03-24 18:47
@captainsafia I am indeed using partial classes for the code behind. `Index.razor` and `Index.razor.cs` where with `public partial class Index`. 

I will try to set a breakpoint in `.razor` files and get back to you. 

```
dotnet --version
5.0.201
```

**Comment by devlife** [comment] 2021-06-08 20:41
I think I might have identified the issue. Asking other members of my team to confirm. At least for Visual Studio.

**Comment by devlife** [comment] 2021-06-08 20:50
Oh my gosh. It turned out to be the `launchSettings.json`. They were missing a few of the properties here. 

```

**Comment by mkArtakMSFT** [comment] 2021-07-27 17:24
Glad that you've found the issue in your code. Closing as there is no further action pending here.

**Closed by mkArtakMSFT** 2021-07-27 17:24 UTC
Labels: Author: Migration Bot :robot:, area-blazor, blazor-wasm, feature-blazor-debugging, investigate
