### ISSUE TITLE
Correlation failure although dataprotection services are configured.

### ISSUE THREAD

**Issue by doogdeb** [dotnet/aspnetcore#13000] opened 2019-08-09 13:33 UTC
I have an ASP.NET Core 2.2 MVC app deployed to azure as a web app. It is deployed within an ASE and there are 3 instances running within the plan. I have configured dataprotection services as below, but I'm still seeing lots of "Message: '.AspNetCore.Correlation.OAuth cookie not found" errors. At least 500 a day.

        var storageAccount = 
        CloudStorageAccount.Parse(dataProtectionOptions.StorageAccountConnectionString);
            
            var tokenProvider = new AzureServiceTokenProvider();
            var keyVaultClient = new KeyVaultClient(
                new KeyVaultClient.AuthenticationCallback(
                    tokenProvider.KeyVaultTokenCallback));

            services.AddDataProtection()
                .PersistKeysToAzureBlobStorage(storageAccount, $@"{dataProtectionOptions.ApplicationName.ToLower()}\keys.xml")
                .ProtectKeysWithAzureKeyVault(keyVaultClient,
                    $"{dataProtectionOptions.KeyVaultBaseUrl}keys/dataprotection")
                .SetApplicationName(dataProtectionOptions.ApplicationName);

As you can see the dataprotection services is using keyvault for the key and is backed by blob storage which is as per Microsoft documentation. I can see the keys.xml file being created in blob storage with relevant keys but I'm still experiencing correlation issues.

**Comment by blowdart** [comment] 2019-08-10 12:43
What authentication service(s) are you using? What browsers see this error?

**Comment by doogdeb** [comment] 2019-08-10 17:14
Using our own STS hosted in azure using OAuth. Looking at the logs, it's all types of devices and browsers. Someone internally was having issues signing in with their iPhone although other iPhone's we tested were fine. I confirmed they were having correlation issues but in this instance it was because they'd set their phone 25mins in the future. Once set to correct time it worked as expected. Other than that, we've never been able to replicate these correlation issues we're seeing so many of in our logs.

**Comment by HaoK** [comment] 2020-03-30 18:11
@blowdart ok closing this?  Phone having future time seems like reasonable failure behavior

**Comment by blowdart** [comment] 2020-03-30 18:14
Closing as by design, as the window on TOTP is 15 minutes

**Comment by doogdeb** [comment] 2020-03-30 18:14
> @blowdart ok closing this? Phone having future time seems like reasonable failure behavior

As I mentioned, that was the only time we could replicate it ourselves. But we're seeing at least 1-1500 of these errors a day.

**Comment by blowdart** [comment] 2020-03-30 18:14
Oh hmm

**Comment by blowdart** [comment] 2020-03-30 18:15
Is it only on phones? Or browsers as well? Are the times all synced on the servers?

**Comment by doogdeb** [comment] 2020-03-30 18:16
The logs show that it's from all types of device and browser.

**Comment by doogdeb** [comment] 2020-03-30 18:17
Were wondering if bots would cause this?

**Comment by mkArtakMSFT** [comment] 2020-10-30 16:26
Thanks for additional details, @doogdeb.
Unfortunately we are unable to reproduce this issue and without a repro we can't investigate further. We're closing this issue as we haven't seen similar feedback.
If you happen to get a small repro project we would be happy  to investigate then. For now, closing this issue.

**Closed by mkArtakMSFT** 2020-10-30 16:26 UTC
Labels: area-dataprotection
