### ISSUE TITLE
Blazor: changing CascadingValue calls SetParametersAsync/OnParametersSet multiple times using nested components

### ISSUE THREAD

**Issue by Garios** [dotnet/aspnetcore#45713] opened 2022-12-21 16:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

First of all, I don't know, if it's really a bug. At least it could lead to performance problems.

I used the default server-side blazor template and added a cascadingvalue with two custom components (C1, C2).

```razor
<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

<CascadingValue Name="Counter" Value="currentCount">
    <Component1>
        <Component2></Component2>
    </Component1>
</CascadingValue>
```

Component1:
```razor
<h3>Component1 @Counter</h3>

@ChildContent

@code {
    [CascadingParameter(Name = "Counter")]
    public int Counter { get; set; }

    [Parameter]
    public RenderFragment ChildContent { get; set; }

    private int dbgCounter;
    protected override void OnParametersSet()
    {
        Console.WriteLine("C1: " + ++dbgCounter);
    }
}

```

Component2:
```razor
<h3>Component2: @Counter</h3>
   
@code {
    [CascadingParameter(Name = "Counter")]
    public int Counter { get; set; }

    private int dbgCounter;
    protected override void OnParametersSet()
    {
        Console.WriteLine("C2: " + ++dbgCounter);
    }
}

```

#### Behavior:
If I click on the increment button, then OnParameterSet is called on C1, then on C2 and it's called once again on C1.

I assume that C1 is called, because C2 is a RenderFragment-Parameter of C1 and this RenderFragment (C2) is changed on C1 through the cascading-value. Is this assumption right? If it's right, do you think it performs good? Couldn't it be better, to set the cascading-value from buttom-up (C2, C1), instead of top-down (C1, C2)?

### Expected Behavior

If I click on the increment button, then OnParameterSet should only get called once on C1

**Comment by mkArtakMSFT** [comment] 2022-12-21 17:25
Thanks for contacting us.
This is indeed by design.

Your reasoning about the order of the events is correct. I'm sure there has been good reasons for the current design but I am not remembering them. Moving this to the Discussions in case someone else from the team remembers and can comment about it.

**Comment by mkArtakMSFT** [comment] 2022-12-21 17:25
@dotnet/aspnet-blazor-eng FYI

**Closed** 2023-02-19 20:00 UTC
Labels: area-blazor
