### ISSUE TITLE
High CPU Load and bad editor responsiveness in blazor server project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23095] opened 2020-06-18 17:20 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1068764/high-cpu-load-and-bad-editor-responsiveness-in-bla.html)._

---
Working with a solution containing razor components (Blazor server app) shows increasing memory usage of VS2019 processes (devenv.exe and ServiceHub.RoslynCodeAnalysisService32.exe) and correlated bad VS editing performance (typing, intellisense, parameter suggestions, etc).

The bad performance starts after some minutes (!) working with the solution and worsens to a state that is not usable anymore. Often, VS eventually auto-closes and -restarts (crash). I see RAM usages of several GB of both aforementioned processes in such situations.

Working with solutions not containing razor components on the same machine with the same VS2019 does NOT show these symptoms.

This problem makes work with VS2019 very unproductive, as it becomes unbearably slow after mere minutes of usage, and needs (or enforces) VS restarts several times a workday.

---
#### Visual Studio Feedback System on 6/9/2020, 00:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Riccardo Zucchetto on 6/10/2020, 01:39 AM: 

Hi,<br>I experience the same problem. The only difference is that one of the two processes using tons of memory is ServiceHub.Host.CLR.x86 (32 bit).<br>I can confirm everything that Dr. Tim dos Santos stated, I have experienced every kind of behavior he highlighted.<br><br>Just an addition: when I kill ServiceHub.Host.CLR.x86 (32 bit) process, Visual Studio becomes a bit more responsive. Sometimes I can use it for hours, but sometimes it becomes unusable since Intellisense and other features are gone. When killed, a yellow strip appears, with the indication that a fatal error happened and it should be better to close and reopen visual studio. The call stack is the following:<br><br>StreamJsonRpc.ConnectionLostException : La connessione JSON-RPC con la parte remota &#232; andata persa prima del completamento della richiesta.<br>   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(&lt;Parametri sconosciuti&gt;)<br>   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Parametri sconosciuti&gt;)<br>   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync(&lt;Parametri sconosciuti&gt;)<br>   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<br><br>I hope it may be helpful to identify and fix the issue.<br>Riccardo
#### Visual Studio Feedback System on 6/10/2020, 11:14 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Dr. Tim dos Santos on 6/17/2020, 10:19 PM: 

<p>Short update to this: I found out that the slowdown is NOT dependent on whether I actually OPEN / EDIT the .razor files. Every solution containing .razor files shows the performance problems, even when only editing .cs files; solutions without .razor files don't.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2020-06-18 17:20
Duplicate of https://github.com/dotnet/aspnetcore/issues/22276

**Closed by NTaylorMullen** 2020-06-18 17:20 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved
