### ISSUE TITLE
Error parsing handshake response: TypeError using "@microsoft/signalr": "5.0.0"

### ISSUE THREAD

**Issue by patolax** [dotnet/aspnetcore#28398] opened 2020-12-04 02:29 UTC
I am using angular 7 to connect to Azure SinglaR service backend.

Everything works fine if I use "@aspnet/signalr": "1.0.4". However any version after and even the latest version "@microsoft/signalr": "5.0.0" I get following error on the client side.

How can I get rid of this error.

Error: Error parsing handshake response: TypeError: Right-hand side of 'instanceof' is not callable

core.js:14597 ERROR Error: Error parsing handshake response: TypeError: Right-hand side of 'instanceof' is not callable at HubConnection.push../node_modules/@microsoft/signalr/dist/esm/HubConnection.js.HubConnection.processHandshakeResponse (HubConnection.js:550) at HubConnection.push../node_modules/@microsoft/signalr/dist/esm/HubConnection.js.HubConnection.processIncomingData (HubConnection.js:501) at WebSocketTransport.HubConnection.connection.onreceive (HubConnection.js:73) at WebSocket.webSocket.onmessage [as __zone_symbol__ON_PROPERTYmessage] (WebSocketTransport.js:110) at WebSocket.wrapFn (zone.js:1188) at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421) at Object.onInvokeTask (core.js:16147) at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420) at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188) at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496) defaultErrorLogger @ core.js:14597 Utils.js:198 [2020-12-04T02:20:45.060Z] Error: Connection disconnected with error 'Error: Error parsing handshake response: TypeError:

**Comment by BrennanConroy** [comment] 2020-12-04 04:14
Likely dupe of https://github.com/dotnet/aspnetcore/issues/27290

**Comment by patolax** [comment] 2020-12-04 05:13
@BrennanConroy do you have a solutions for now? or do we have to wait for the next version?

**Comment by BrennanConroy** [comment] 2020-12-04 06:06
> do you have a solutions for now?

Yeah, remove the `var Buffer = Buffer || [];` that Angular adds.

**Comment by jkotalik** [comment] 2020-12-04 22:15
Closing as dup.

**Closed by jkotalik** 2020-12-04 22:15 UTC
Labels: area-signalr

**Comment by patolax** [comment] 2020-12-06 22:56
I am sorry, I am not sure what the solution is. I don't have any  Buffer references in my code, they are there in the node_modules folder. Are you asking me to update those files manually? 
How do we do it in CI+CD pipelines, where node packages are downloaded for every build? 

In any case, when can I expect a new version with these issues fixed?

**Comment by BrennanConroy** [comment] 2020-12-07 00:17
Angular apps usually have an index.html file with the `var Buffer` code I mentioned.

**Comment by patolax** [comment] 2020-12-08 00:00
Thanks that resolved it.

For others, removing   _var Buffer = Buffer || [];_  from index.html resolved this issue. 

 var global = global || window;
    //var Buffer = Buffer || [];
    var process = process || {
      env: { DEBUG: undefined },
      version: []
    };
