### ISSUE TITLE
Problem validators langage use when there is a decimal field in a form

### ISSUE THREAD

**Issue by Adeniel** [dotnet/aspnetcore#42014] opened 2022-06-03 14:32 UTC
# Describe the bug 

With a model that contains a `decimal` property, this doesn't work with a locale that uses a decimal comma:

```
<input asp-for="Number">
<input asp-for="Number" type="number">
```

Code: 
I am used a modal for display my form and a ViewModel: 
 ```
class ViewModel 
{
            [StringLength(56)]
            public string Speciality { get; set; }

            [StringLength(128)]
            public string StructureLinked { get; set; }

            [Required]
            [AbpRadioButton(Inline = true)]
            public RateType RateSelected { get; set; }

            [HiddenInput]
            public decimal RateGeneral { get; set; }

            public decimal RateSpecific { get; set; }
}
 ```
The first issue is that the rest of the form return french validator langage as expected, but for all the properties which use `decimal` the validator is in English. 
The second issues is that we give a data without comma it's send and receive correctly. But if we respect the `English format` as `9.8`  we receive `0`.

I tried to force the loading of the file jqueryvalidator/message_fr.js or some differents fix find on web without success

**Comment by javiercn** [comment] 2022-06-06 09:05
@Adeniel thanks for contacting us.

We believe this is a duplicate of https://github.com/dotnet/aspnetcore/issues/6566

**Closed by javiercn** 2022-06-06 09:05 UTC
Labels: area-mvc, feature-mvc-razor-views
