### ISSUE TITLE
EventForDotNet.ts - DataTransfer event object is not parsed

### ISSUE THREAD

**Issue by Ellested** [dotnet/aspnetcore#18839] opened 2020-02-05 21:51 UTC
The DataTransfer field is always null and data is never passed to the .net code.
I assume that the dataTransfer property has to be a clone of the DOM event, in order for the data to be passed to Blazor. It's actually also necessary to return the dataTransfer object, if you want .net code to modify the dropEffect and effectAllowed. I'm not sure whether Blazor JSInterop supports modifcation off the event and pass it back to JS - but it would be nice :-)

function parseDragEvent(event: any) {
  return {
    ...parseMouseEvent(event),
    **dataTransfer: event.dataTransfer,**
  };
}

**Comment by javiercn** [comment] 2020-02-06 14:14
@Ellested thanks for contacting us.

We likely don't have support for this as it would involve marshalling the list of files automatically and that's not something we are likely to support out of the box due to the complexity of the requirements.

A better approach for this is to build whatever logic you need for your control in JS and use JS interop to talk to the .NET side

**Comment by mkArtakMSFT** [comment] 2020-02-06 17:41
This looks like a dupe of https://github.com/dotnet/aspnetcore/issues/17552

**Closed by mkArtakMSFT** 2020-02-06 17:41 UTC
Labels: area-blazor

**Comment by Ellested** [comment] 2020-02-07 09:38
Yes, I already took the JS approach. I still believe it would be a good idea to send the full details, but maybe throttle the dragover event. It is actually fairly measurable on the CPU, when this event is handled today (without the full payload), so it's not a perfect solution either. But, it's a luxury problem :-)

**Comment by mkArtakMSFT** [comment] 2020-02-09 20:27
> ...but maybe throttle the dragover event

@Ellested, we plan to handle that as part of https://github.com/dotnet/aspnetcore/issues/10522
