### ISSUE TITLE
Blazor Server - InvokeAsync(StateHasChanged) does not work correctly with UI streaming.

### ISSUE THREAD

**Issue by Sharaf-Mansour** [dotnet/aspnetcore#56474] opened 2024-06-27 04:19 UTC
## Some Context
I am using AI to build an agentic workflow using blazor on Dotnet 8 and ``` Microsoft.SemanticKernel``` Everything is working fine from the backend side.
I am creating a text completion functions that stream the ```StreamingChatMessageContent``` To the UI
Think of it like a GPT / Copilot Clone for a chat site but you have more than 1 AI that chat with each other to finish tasks.
## My Agents
```razor
@inject AIAgents AIAgents
<div>(MarkupString)Response </div>
```
```cs
//Agent 1
  async ValueTask<string> SeniorAI(string Message)
  {
      var CodeAgent= AIAgents.SrCodeAgent(Message);
      var chatMessage = "";
      Response += Environment.NewLine;
      await foreach (var content in CodeAgent)
      {
          chatMessage += content.Content;
          Response += content.Content;
          await InvokeAsync(StateHasChanged);
          await _js.InvokeVoidAsync("scrollToEnd");

      }
      AIAgents.SrChatMessages.AddAssistantMessage(chatMessage);
      ProcessedString = ParseHtmlContent(Response);

      return chatMessage;
  }
//Agent 2
  async ValueTask<string> JunoirAI(string Message)
  {
      var CodeAgent= AIAgents.JrCodeAgent(Message);
      var chatMessage = "";
      Response += Environment.NewLine;
      await foreach (var content in CodeAgent)
      {
          chatMessage += content.Content;
          Response += content.Content;
          await InvokeAsync(StateHasChanged);
          await _js.InvokeVoidAsync("scrollToEnd");

      }
      AIAgents.JrChatMessages.AddAssistantMessage(chatMessage);
      ProcessedString = ParseHtmlContent(Response);
      return chatMessage;
  }
```
## Agentic Workflow trigger
```cs
async Task DoAiStuff()
{
 var SrAnswer = await SeniorAI(Message ?? ""); // <-- Updates UI Correctly (Stream word by word)

 while (true)
 {
     Response += Environment.NewLine + "<hr/>" + Environment.NewLine + "JR AI: ";
     var JrAnswer = await JunoirAI(SrAnswer); // <-- Only Updates if the whole text is complete
     if (IsTaskComplete(JrAnswer)) break;

     Response += Environment.NewLine + "<hr/>" + Environment.NewLine + "SR AI: ";
     SrAnswer = await SeniorAI(JrAnswer); // <-- Only Updates if the whole text is complete
     if (IsTaskComplete(SrAnswer)) break;
 }
}
 ```
 ## Expected Behavior
 I expect that every single Agent triggers a UI refresh with every word it generates, The very 1st agent (Outside of the loop) does that.
 But the rest does not. even though it is the exact same function and code. 
It ignores ```await InvokeAsync(StateHasChanged);```
And then refresh the UI after the whole text is generated.

**Comment by SteveSandersonMS** [comment] 2024-06-27 17:45
Thanks for providing this, however I'm afraid we're looking for a minimal repro. This means that it includes only the smallest possible number of lines of code needed to reproduce the issue, and without any 3rd-party dependencies.

The reason we ask for this is because the team doesn't have time capacity to debug arbitrary code, so we need you to reduce the repro to the smallest possible thing. In many cases (perhaps most), in the process of doing this you may discover an issue in your own code.

Hope that's OK!

**Comment by Sharaf-Mansour** [comment] 2024-06-27 17:49
@SteveSandersonMS  The issue with  text streaming (UI render( not Semantic Kernel but I will try to simulate a live text generation with minimal code. 
You can check the GIF until I provide the repo. 
Thanks for the immediate response

**Comment by Sharaf-Mansour** [comment] 2024-06-27 18:07
@SteveSandersonMS  Here is the code for minimal repo.
https://github.com/Sharaf-Mansour/Blazor-Bug-InvokeAsync
Also here is another GIF of how it behaved. 
![ezgif-5-e8abb97c7c](https://github.com/dotnet/aspnetcore/assets/55330747/605d3b86-5356-4669-beab-5e48bf6587e8)

**Comment by SteveSandersonMS** [comment] 2024-06-28 11:36
Thanks for simplifying the repro.

Your code behaves exactly like I would expect given how it's written. What are you expecting to happen differently?

Did you want each of the numbers to appear separately? If so the reason it doesn't that you're merging them all into one word, so when it splits on spaces, it just gets a single word. Try changing `StreamTextAsync` to look like this:

```cs
    static async IAsyncEnumerable<string> StreamTextAsync(string text)
    {
        string[] words = text.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        foreach (var word in words)
        {
            yield return word + " ";
            await Task.Delay(1000);
        }
    }
```

I'm confident enough this is not a Blazor bug so I'll close this. Please let us know if you are convinced there's something wrong in the framework, and if so, what further reason there is for thinking that.

Sidenote: you don't need to write `await InvokeAsync(StateHasChanged);` in your code here, since your code never leaves the sync context. You can just write `StateHasChanged();` and it will behave the same.

**Closed by SteveSandersonMS** 2024-06-28 11:36 UTC
Labels: area-blazor, Needs: Attention :wave:, Needs: Repro

**Comment by Sharaf-Mansour** [comment] 2024-06-28 14:05
@SteveSandersonMS It is a mistake from my part to do a repro. Because the context I am using is Generative AI that uses an API endpoint stream.
I tried using ```Microsoft.SemanticKernel``` and also ```OmniSharp``` and the issue exists. 

```cs
async ValueTask<string> SeniorAI(string Message)
{
  var CodeAgent = AIAgents.SrCodeAgent(Message);
  await foreach (var content in CodeAgent)
  {
      Response += content.Content;
      await InvokeAsync(StateHasChanged);
  }
  return chatMessage;
}
```
I call it multiple times inside the same function  something like this.
```cs
while (true)
{
  Response += Environment.NewLine + "<hr/>" + Environment.NewLine + "JR AI: ";
  var JrAnswer = await SeniorAI(SrAnswer);
  Response += Environment.NewLine + "<hr/>" + Environment.NewLine + "SR AI: ";
  SrAnswer = await SeniorAI(JrAnswer);
}
```
The 1st time I call the function it prints 1 word by 1 word. after that any other call. does not render and prints the whole thing when completed. 
I have no clue how to make a simplified repo of this... any suggestions ?

**Comment by SteveSandersonMS** [comment] 2024-06-28 14:33
I'm sorry, but this does look like a bug in your application code rather than in the framework. I don't know why it would happen but you'll need to debug it yourself. If you find evidence there's a framework bug and can provide a minimal repro showing that please let us know. Sorry I can't solve this for you!
