### ISSUE TITLE
Blazor: Bind-Value fails at runtime rather than at compile time if the bound property doesn't exist

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#20312] opened 2020-03-30 14:55 UTC
### Describe the bug
If you have a component (Component1) that has a property defined as a parameter called 'Value' you can use that property in a page or component referencing Component1 as
```
<Component1 Value="xyzzy"/>
```
and if you type the name of the parameter, the color changes in VS and an error is generated.
If, on the other hand, you try to use the parameter in a bind, and type the name incorrectly as 'Valeu'
```
<Component1 @bind-Valeu="pSourceProperty"/>
```
no error is raised, the code generated in the g.cs file is not correct, and a run time error occurs with the component is first rendered.

If we are going to have what amounts to code fragments in the cshtml I believe that they need to be syntax checked as rigorously as they are in a '.cs' file.

### To Reproduce
See problem description

### Further technical details
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.803 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment] 2020-03-30 14:59
@MarkStega thanks for contacting us.

I believe the compiler is simply not smart enough to detect this situation and colors anything that goes after `bind-` expecting that there is a matching property there.

Keep in mind that `bind-` can't in the general case know the set of properties/attributes that are applicable to a given component.

**Comment by MarkStega** [comment] 2020-03-30 15:04
@javiercn 
I understand that the compiler is not 'smart' enough at the current time. My point is that letting something invalid through a compiler is just wrong and needs to be addressed.

**Comment by mkArtakMSFT** [comment] 2020-03-30 16:18
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by bachratyg** [comment] 2022-04-14 17:24
Please at least provide a better error message! Even if I know what to look for (because it already happened 137 times today) I'm still clueless which component/property is the culprit.

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.NotSupportedException: ValueType arguments are not supported.
         at System.Runtime.InteropServices.JavaScript.Runtime.GetCallSignature(IntPtr methodHandle, Object objForRuntimeType)
      Error: System.NotSupportedException: ValueType arguments are not supported.
         at System.Runtime.InteropServices.JavaScript.Runtime.GetCallSignature(IntPtr methodHandle, Object objForRuntimeType)
          at Object._convert_exception_for_method_call (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:180229)
          at Object._handle_exception_for_call (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:182198)
          at Object._handle_exception_and_produce_result_for_call (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:182519)
          at Object._call_method_with_converted_args (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:183593)
          at Object.call_method (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:181988)
          at Object.mono_method_get_call_signature (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:171695)
          at Object._wrap_delegate_gc_handle_as_function (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:158238)
          at Object._wrap_delegate_root_as_function (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:157149)
          at Object._unbox_mono_obj_root_with_known_nonprimitive_type (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:163790)
          at Object._unbox_mono_obj_root (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:165110)
Microsoft.JSInterop.JSException: System.NotSupportedException: ValueType arguments are not supported.
   at System.Runtime.InteropServices.JavaScript.Runtime.GetCallSignature(IntPtr methodHandle, Object objForRuntimeType)
Error: System.NotSupportedException: ValueType arguments are not supported.
   at System.Runtime.InteropServices.JavaScript.Runtime.GetCallSignature(IntPtr methodHandle, Object objForRuntimeType)
    at Object._convert_exception_for_method_call (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:180229)
    at Object._handle_exception_for_call (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:182198)
    at Object._handle_exception_and_produce_result_for_call (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:182519)
    at Object._call_method_with_converted_args (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:183593)
    at Object.call_method (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:181988)
    at Object.mono_method_get_call_signature (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:171695)
    at Object._wrap_delegate_gc_handle_as_function (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:158238)
    at Object._wrap_delegate_root_as_function (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:157149)
    at Object._unbox_mono_obj_root_with_known_nonprimitive_type (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:163790)
    at Object._unbox_mono_obj_root (https://localhost:7195/_framework/dotnet.6.0.4.dckq00jdfr.js:1:165110)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by mkArtakMSFT** [comment] 2023-12-21 17:21
Moving to .NET 9 planning

**Comment by mkArtakMSFT** [comment] 2024-01-22 17:46
Closing as a dupe of https://github.com/dotnet/razor/issues/7660

**Closed by mkArtakMSFT** 2024-01-22 17:46 UTC
Labels: enhancement, area-blazor, feature-razor.language, severity-blocking, affected-medium, area-razor.compiler, Pillar: Dev Experience
