### ISSUE TITLE
Cannot browse source code in Visual Studio

### ISSUE THREAD

**Issue by ygoe** [dotnet/aspnetcore#24008] opened 2020-07-16 14:36 UTC
### Describe the bug
When opening the source code from this repository in Visual Studio, there are two issues. First, the packages cannot be restored fully which is probably the reason why all code files are mostly underlined in red. Second, I repeatedly get modal Microsoft login dialogs that want me to login somewhere. When I do log in, it has no effect at all. Visual Studio is completely unusable with these dialogs popping up all the time!

### To Reproduce
1. Check out the source code from this repository.
2. Switch to the tag v3.1.6
3. Change global.json to match the installed .NET SDK version
4. Open src\Mvc\Mvc.sln in Visual Studio 2019 Community Edition 16.6.4

### Exceptions (if any)
This is the package manager output:

```
Alle Pakete sind bereits installiert. Nichts muss wiederhergestellt werden.
Verstrichene Zeit: 00:01:46.2440102
========== Abgeschlossen ==========


Fehler beim Wiederherstellen von NuGet-Paketen: Der Dienstindex für die Quelle "https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-extensions-be18161f/nuget/v3/index.json" konnte nicht geladen werden.
```

### Further technical details
dotnet --info:

```
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.302
 Commit:    41faccf259

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by dougbu** [comment] 2020-11-18 20:43
My translation of the important message is
``` text
Failed to restore NuGet packages: The service index for the source "https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-extensions-be18161f/nuget/v3/index.json" failed Loading.
```
The problem is the tags show _exactly_ what was built for that release and it was an MSRC build. Remove the `darc-int...` feeds from NuGet.config before building. Or, better, use the `release/3.1` branch instead of the `v3.1.6` tag.

**Comment by dougbu** [comment] 2020-11-18 20:44
@ygoe thank you for your feedback. We're closing this issue as the questions asked here have been answered.

**Closed by dougbu** 2020-11-18 20:44 UTC
Labels: area-infrastructure
