### ISSUE TITLE
Treat records as known immutable types for parameters

### ISSUE THREAD

**Issue by BerndNK** [dotnet/aspnetcore#29489] opened 2021-01-21 12:27 UTC
### Is your feature request related to a problem? Please describe.
In .Net 5.0 Blazor WebAssembly, as defined in [the blazor docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-5.0), a sub component is rerendered, if there are any non-immutable parameters bound.

For example, this will only rerender the "RenderTest" component:

```razor
// RenderTest component:
<SubRenderTest MyParameter="@_someString"></SubRenderTest>
<button @onclick="OnClick"/>

@code {

    private string _someString = string.Empty;

    private void OnClick()
    {
        // unused method, only required to simulate a state change
    }

    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        Console.WriteLine("Main component rendered");
    }
}

// SubRenderTest component:
<h1>Value: @MyParameter </h1>

@code {
    [Parameter]
    public string MyParameter { get; set; }
    
    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        Console.WriteLine("Sub component rendered");
    }

}
```

As all bound parameters are known immutable primitive types (in this case `string`) and have not changed, only the main component is rendered when an UI event is executed. When clicking the button, the output will be
`"Main component rendered"`
as expected. 

However, take the same example, but this time with an immutable C#9 record type:

```razor
// RenderTest component:
<SubRenderTest Model="@_model"></SubRenderTest>
<button @onclick="OnClick"/>

@code {

    private ImmutableModel _model = new();

    private void OnClick()
    {
        // unused method, only required to simulate a state change
    }

    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        Console.WriteLine("Main component rendered");
    }
}

// SubRenderTest component:
<h1>Value: @Model.SomeName</h1>

@code {
    [Parameter]
    public ImmutableModel Model { get; set; }
    
    protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        Console.WriteLine("Sub component rendered");
    }

}

// ImmutableModel:
public record ImmutableModel
    {
        public string SomeName { get; init; } = string.Empty;
    }

```

This time the output will be:

`"Main component rendered"`
`"Sub component rendered"`

### Describe the solution you'd like
Implement the same "Don't rerender sub components if parameters haven't changed" logic for immutable record types.

I believe this is a relatively easy implementation and will improve performance without specific `ShouldRender` implementations.

**Comment by captainsafia** [comment] 2021-01-21 17:39
This issue is a dupe of #19840 and #13610 which tracks improving support for immutable types in Blazor.

**Closed by captainsafia** 2021-01-21 17:39 UTC
Labels: area-blazor
