### ISSUE TITLE
Warning when doing RenderFragment closures

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/aspnetcore#47662] opened 2023-04-12 09:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Imagine this code:
```razor
@{
    int index = 0;
    foreach (string i in items)
    {
        <div>foreach: @index</div>
        <TestComponent>
            <TabTemplate>
                <div>@i, @index</div>
                @{index++;}
            </TabTemplate>
        </TestComponent>
    }
}

@code {
    string[] items = new[] { "1", "2", "3" };
}
```

where TestComponent is simply:
```razor
@if (TabTemplate is not null)
{
    <div>@TabTemplate</div>
}

@code {
    [Parameter]
    public RenderFragment? TabTemplate { get; set; }
}
```

This code would output:
foreach: 0
1, 0
foreach: 0
2, 1
foreach: 0
3, 2
Which is not something you'd expect (index is always 0 at foreach) just from simple look at the code.

### Describe the solution you'd like

Perhaps an analyzer warning would be useful in such case as it is not obvious/misleading from code that index doesn't increment outside closure. Even worse, the RenderFragment part work as expected from this perspective.

**Comment by javiercn** [comment] 2023-04-12 11:10
@MihaMarkic thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/22515 (amongst others).

This is not something that we can easily address with an analyzer. It's something that we've already considered. The best we can do for now is to offer docs (which we do) to avoid using `for` and use `foreach` instead, since `foreach` captures the variable in the body scope as opposed to the external scope.

Detecting incorrect usages of closures is not a feature we think we can do at the analyzer level without expending significant resources on it.

**Closed** 2023-04-12 11:16 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor
