### ISSUE TITLE
On M1 machine, build 5.0 / 3.1 Grpc project show an error: Google.Protobuf.Tools cannot determine host OS and CPU".

### ISSUE THREAD

**Issue by v-linyuancui** [dotnet/aspnetcore#39394] opened 2022-01-10 02:48 UTC
**Azure DevOps work item:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1451871

**INSTALL STEPS**
Install 6.0 arm64 Dec Servicing ：https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Install 5.0 x64 Dec Servicing: https://dotnet.microsoft.com/en-us/download/dotnet/5.0
Install 3.1 x64 Dec Servicing: https://dotnet.microsoft.com/en-us/download/dotnet/3.1 

**Testcases Affected**
[[5.0] SimpleWebAppWithgRPCService](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore30/30_SimpleWebAppWithgRPCService_Mac.md)
[[3.1] SimpleWebAppWithgRPCService](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VSforMac/AspNetCore30/30_SimpleWebAppWithgRPCService_Mac.md)

**Platform**

- [ ]   Windows
- [x]   macOS
- [ ]   Linux

**Repro Steps**
Execute the following command from terminal

- /usr/local/share/dotnet/x64/dotnet new grpc -o GrpcGreeter -F net5.0
- cd GrpcGreeter
- dotnet  build

**Actual Result**
Show an error: Google.Protobuf.Tools cannot determine host OS and CPU".
![image](https://user-images.githubusercontent.com/82508939/148712848-d28a10bf-86ad-4dbc-ab16-e90db6d58359.png)

**Note:** If use "/usr/local/share/dotnet/x64/dotnet build", this issue doesn't reproduce.
![image](https://user-images.githubusercontent.com/82508939/148712873-2e7dda07-4a42-4ba4-849f-46ba5bf2e902.png)

**Comment by mrward** [comment] 2022-01-19 11:54
I suspect this is because the .NET 5/3.1 gRPC project templates are using an older gRPC.Tools NuGet package 2.27.0 which only contains x64 tools. The .NET 6 project templates are using gRPC.Tools NuGet package version 2.40.0 has Arm64 tools.

If updating the gRPC.Tools NuGet package fixes the problem, and there are no plans to update this package version in the .NET 5/3.1 project templates then we can close this as by design.

**Comment by rafikiassumani-msft** [comment] 2022-02-08 03:32
Since .NET 3.1/5.0 will be out of support soon. We think it's not worth the efforts to service the templates and fix the issue. The workaround is to update `gRPC.Tools` to the new version as suggested by @mrward.

**Closed by rafikiassumani-msft** 2022-02-08 03:32 UTC
Labels: :heavy_check_mark: Resolution: Won't Fix, area-grpc, Status: Resolved
