### ISSUE TITLE
Usability: PathString.StartsWithSegments() with a trailing slash is not intuitive behavior

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2713] opened 2018-01-02 02:53 UTC
_From @NickCraver on Sunday, January 15, 2017 7:34:28 AM_

I was trying to do effectively this yesterday:
```C#
new PathString("/profiler/test").StartsWithSegments(new Path("/profiler/");
```
This was, to me, unexpectedly false. And I spent over an hour being an idiot. Once I was in source, I finally realized that a starts-with check of `"/profiler"` works, while including a trailing slash of `"/profiler/"` does not. Is this intended behavior? [The `PathString` tests](https://github.com/aspnet/HttpAbstractions/blob/622d112372ed11075af160b1fb5a11a7637ff516/test/Microsoft.AspNetCore.Http.Abstractions.Tests/PathStringTests.cs) don't actually include a case testing it either way.

**Current** behavior examples:
```c#
	new PathString("/a/b").StartsWithSegments(new PathString("/a/"));  // false
	new PathString("/a/b").StartsWithSegments(new PathString("/a"));   // true
	new PathString("/a//b").StartsWithSegments(new PathString("/a/")); // true
```

Currently the check of `value1[value2.Length] == '/'` means whatever's checked against must match or have a trailing slash *after* it, unless it matches exactly. It seems to be that a `/path/` should work here. Is there any objection to this working?

The check could change from:
```c#
value1.Length == value2.Length || value1[value2.Length] == '/'
```
to:
```c#
value1.Length == value2.Length || value1[value2.Length] == '/' || value2[value2.Length-1] == '/'
```
and in the remainder methods, it'd be slightly different with an additional `if` instead:
```c#
if (value2[value2.Length - 1] == '/')
{
    remaining = new PathString(value1.Substring(value2.Length - 1));
    return true;
}
```

Thoughts? Is there a reason it doesn't behave like this already, or just an ambiguous case? I'd be happy to submit a PR if it's a welcomed change.

_Copied from original issue: aspnet/HttpAbstractions#756_

**Comment by aspnet-hello** [comment] 2018-01-02 02:53
_From @Tratcher on Wednesday, January 18, 2017 1:32:34 PM_

Fuzzy matching like this creates ambiguity that leads to subtle bugs. We may be able to do this, but I'd want a lot of test cases. Give it a try.

**Comment by fleed** [comment] 2018-03-09 14:18
Any update on this?

`httpContext.Request.Path.StartsWithSegments(segment)` with `Path` value of **/index.html** and `segment` set to **/** returns `false`.
Is it the expected behavior? then, how can I match the root and still have the `segment` configurable as variable, eventually root?

**Comment by Tratcher** [comment] 2018-03-16 22:48
@fleed all PathStrings are required to be empty or start with a slash, so StartsWithSegments("/") doesn't tell you much. You may as well check for Empty.

**Comment by davidfowl** [comment] 2021-03-28 18:26
This seems like something we should add a bunch of tests for and better define the behavior. That *is* very subtle. Marked as help wanted.

**Comment by FabianAronsson** [comment] 2023-11-16 14:23
Recently ran into this issue when trying to match a path with, for example, `/hubs/`. 

Removing the trailing slash fixes it, but I am posting this comment so other people can find it when searching for it.

**Comment by jonmest** [comment] 2023-11-29 21:34
Encountered this as well. As a user, I don't see any particular problems with it behaving this way, but believe it is subtle enough to warrant a mention in the documentation.

**Comment by ace90210** [comment] 2024-02-08 10:56
hit this today, i disagree with jonmest that its not an issue but regardless, even if it is valid, it *needs* mentioning in the documentation because its not remotely easy to spot the bug and the behaviour is directory contrary to the methods name and description in this use case. 

given how easy it is to update the method comments to at least note this and the complete lack of a downside to doing so i fail to understand why its sat for years and not been done or at least acknowledged and put on the backlog.

**Closed** 2024-02-12 20:27 UTC
Labels: enhancement, feature-http-abstractions, severity-minor, affected-very-few, area-networking, help candidate
