### ISSUE TITLE
InputNumber razor component short(Int16) type provided.

### ISSUE THREAD

**Issue by Qorxi** [dotnet/aspnetcore#20103] opened 2020-03-24 16:35 UTC
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example: I am trying to do [...] but [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

**Comment by Qorxi** [comment] 2020-03-24 16:39
Hello again, there was a problem with a related issue for the InputSelect component, but the problem disappeared by finding sample code from github. Since the InputNumber component does not support the short type, the problem disappears when it is converted to an int type, so it can work in the database model table on the database side, so it works, but it is not the solution. Due to unnecessary data type conversions between DTOs and not converted to data type between database and model.

**Comment by mkArtakMSFT** [comment] 2020-03-24 21:24
Thanks for contacting us. This looks like a dupe of https://github.com/dotnet/aspnetcore/issues/8203

**Closed by mkArtakMSFT** 2020-03-24 21:24 UTC
Labels: area-blazor
