### ISSUE TITLE
_ViewImports.cshtml is read very often

### ISSUE THREAD

**Issue by ryzngard** [dotnet/aspnetcore#35313] opened 2021-08-12 23:01 UTC
As part of perf investigations we found that `_ViewImports.cshtml` is read often for small changes. For example, changing an `Index.cshtml` file that requires multiple background files.

Talking to @NTaylorMullen  this sounds like an area we can easily improve by caching either the syntax tree or file contents itself.

**Comment by ryanbrandenburg** [comment] 2021-09-29 23:49
@ryzngard I'm not able to reproduce this by hand and currently the Test it was created from isn't building on my local machine. Is there an automated process y'all used to generate this that I could check to see if it still repros?

**Comment by ryzngard** [comment] 2021-09-30 17:20
@ryanbrandenburg since this comes from automated testing it should be in the artifacts from test runs. For example on this: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/354864 

When I have a minute I'll pull the artifacts and run them through tooling to see if it still reports this issue.

**Comment by ryanbrandenburg** [comment] 2021-10-01 16:10
This did not replicate in actual usage. I can confirm the test causes this behavior though, my hypothesis is that something about the test framework overrides an existing cache mechanism in VS.

Regardless, if we can't replicate the issue in actual usage it's not worth the danger and complexity of adding a new cache, so I'm closing this without action. If someone finds a real-life repro in the future consider using https://github.com/dotnet/aspnetcore-tooling/pull/4281 as a starting point for your fix.

**Closed by ryanbrandenburg** 2021-10-01 16:10 UTC
Labels: Perf, area-razor.tooling, feature-razor.vs, snappyjr
