### ISSUE TITLE
Signalr - Problem with "@types/node" dependency

### ISSUE THREAD

**Issue by john-larson** [dotnet/aspnetcore#26087] opened 2020-09-19 01:33 UTC
I am using `@microsoft/signalr` package in a typescript project. This project is going to run in the browser. Why is there a mandatory "`@types/node`" dependency for it? It conflicts with "`@types/requirejs`".

**Comment by BrennanConroy** [comment] 2020-09-21 04:45
Dupe of https://github.com/dotnet/aspnetcore/issues/13805

**Closed** 2020-09-25 21:40 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
