### ISSUE TITLE
Support rendering multiple components using Blazor WebAssembly from an MVC/Razor Pages app

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22638] opened 2020-06-07 03:30 UTC
It seems reasonable that you might want to augment an MVC or Razor Pages app with Razor components that run client-side using Blazor WebAssembly. However, there doesn't appear to be a good way to do this currently.

You can register multiple root components, but if the selector for any given root component doesn't match anything then we throw. So you can't really setup a Counter component to be embedded on one page, and then a FetchData component to be embedded on another page.

The proposal here is to have a way where you can setup multiple Razor components that can be setup on different pages, but all run using the same runtime and framework that get downloaded once. Ideally, there would be a way to do this using the existing component tag helper.

**Comment by mkArtakMSFT** [comment] 2020-07-24 17:14
Dupe of #14434

**Closed by mkArtakMSFT** 2020-07-24 17:14 UTC
Labels: area-blazor, blazor-wasm, enhancement
