### ISSUE TITLE
Error while setting render mode on Generic Blazor Component

### ISSUE THREAD

**Issue by CrahunGit** [dotnet/aspnetcore#54058] opened 2024-02-15 15:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I set render mode on generic blazor component it throws the error

![imagen](https://github.com/dotnet/aspnetcore/assets/12015993/96d87933-0067-4638-a767-61bbe147d342)

Error CS0305 Using the generic type 'TwSelect<TItem>' requires 1 type arguments.

Removing the render mode works as expected.

### Expected Behavior

Compile fine

### Steps To Reproduce

Create any blazor component with generic type

### .NET Version

8.02

**Comment by MackinnonBuck** [comment] 2024-02-15 17:51
Thanks for reaching out, @CrahunGit.

This looks like a dupe of https://github.com/dotnet/razor/issues/9683, so I'm going to close this issue out.

**Closed by MackinnonBuck** 2024-02-15 17:51 UTC
Labels: area-blazor
