### ISSUE TITLE
JsonHubProtocol has isolated gson instance

### ISSUE THREAD

**Issue by lepicekmichal** [dotnet/aspnetcore#40535] opened 2022-03-04 10:02 UTC
JsonHubProtocol is creating its own Gson instance for parsing json string.
This is not usable because gson can have our own params and most importantly custom serializers which are now not working.

Please make JsonHubProtocol accept gson instance inside cosntructor (with default to new instance of course).

**Better yet:** Make the class extendable and allow us to implement our own json (de)serializer. For example via _kotlinx.serialization_ instead of gson.

[Android]

**Comment by BrennanConroy** [comment] 2022-03-04 16:00
Looks like a dupe of https://github.com/dotnet/aspnetcore/issues/17519

**Closed** 2022-03-05 16:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, api-suggestion, Status: Resolved
