### ISSUE TITLE
Like other .net solutions, it is expected from blazor that if .net was uploaded from one app and it was available in the browser cache, there is no need to load .net in another program.

### ISSUE THREAD

**Issue by aminsharifi** [dotnet/aspnetcore#46123] opened 2023-01-16 12:25 UTC
Like other .net solutions, it is expected from blazor that if .net was uploaded from one app and it was available in the browser cache, there is no need to load .net in another program.

_Originally posted by @aminsharifi in https://github.com/dotnet/aspnetcore/issues/46119#issuecomment-1383975382_

**Comment by javiercn** [comment] 2023-01-16 13:30
Dupe of https://github.com/dotnet/aspnetcore/issues/46119

**Closed by javiercn** 2023-01-16 13:30 UTC
