### ISSUE TITLE
[Blazor] Download attribute in anchor tags not respected

### ISSUE THREAD

**Issue by fabianschurz** [dotnet/aspnetcore#20360] opened 2020-03-31 14:19 UTC
### Describe the bug
In firefox download anchors are not working. 

### To Reproduce
`<a href="fileInWwwroot.extension" download>Download</a>`
Then start the application and click the anchor. Try in firefox and edge.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

IDE is VS.

dotnet --info output:
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.101
 Commit:    b377529961

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment] 2020-03-31 14:45
@xFirestorm thanks for contacting us.

* Does this work in other browsers?
* Does this work if you have a plain HTML document served from the host where blazor is not involved at all?

**Comment by xFirestorm** [comment] 2020-03-31 15:05
> 
> 
> @xFirestorm thanks for contacting us.
> 
>     * Does this work in other browsers?
> 
>     * Does this work if you have a plain HTML document served from the host where blazor is not involved at all?

It works in edge while it's not in firefox.

Plain HTML is working.

**Comment by barahonajm** [comment] 2020-04-02 01:12
I tried to reproduce this with both latest preview and 3.1 but I was unable to, unless Blazor team has already reproduce it, could you please provide more details? A minimal project would be great

**Comment by xFirestorm** [comment] 2020-04-02 07:57
> 
> 
> I tried to reproduce this with both latest preview and 3.1 but I was unable to, unless Blazor team has already reproduce it, could you please provide more details? A minimal project would be great

If blazor team has not already reproduce it i can set up a project and provide more details about firefox version etc.

@javiercn Please let me know if this is needed

**Comment by drearyrainDeng** [comment] 2020-04-03 06:07
open new blazor project. then add logo.png and code in index.razor like that 
`<a href="/images/logo.png" download="/images/logo.png">
<img border="0" src="./images/logo.png" alt="download Logo" >
</a>` . it not work!

**Comment by barahonajm** [comment] 2020-04-03 13:50
Yes you are completely right, I misunderstood the idea behind donwload, to add a extra detail, it correctly works on an MVC or Razor pages project, but not on a Blazor one

**Comment by captainsafia** [comment] 2020-05-04 23:26
I was able to reproduce this issue on Edge (v81.0.416.68), Firefox (75.0), and Chrome (81.0.4044.129), so it's unlikely that this is browser specific.

```
// Index.razor
@page "/"

<h1>Hello, world!</h1>

Welcome to your new app.

<a href="./images/ms-logo.png" download>Download image</a>

<SurveyPrompt Title="How is Blazor working for you?" />
```

The same code works if used in an HTML file served by standalone HTTP server so something is afoot here. Something in our navigation logic might be triggering the navigation to the image instead of triggering the browser's download functionality. 

As a workaround for this, you can try [adding a custom page for downloads](https://stackoverflow.com/a/59614377/2657102) or programmatically triggering the download.

**Comment by gulbanana** [comment] 2020-05-05 02:42
i've found that in Firefox, but not Chrome, using a link like `<a href="/mystaticfile.zip" download>` will cause a Blazor Server circuit to disconnect

**Comment by campersau** [comment] 2020-07-23 21:42
The problem is with the router which intercepts all link clicks for routing purposes:
https://github.com/dotnet/aspnetcore/blob/8b7972064f068f76452eff7994263a5e4ee3ca46/src/Components/Web.JS/src/Services/NavigationManager.ts#L57-L70
As a workaround you can e.g. specify `target="_blank"` so it wouldn't be handled by the router.

Should there also be special handling for ignoring links with `download` attribute or is the workaround sufficient?

**Comment by barahonajm** [comment] 2020-08-19 03:57
Yes, that is a working workaround although I still believe we will need a check to stop processing `anchor` with `download` attribute

**Comment by javiercn** [comment] 2020-09-10 15:01
@SQL-MisterMagoo of course!

Go for it!

**Comment by SQL-MisterMagoo** [comment] 2020-09-10 15:04
@javiercn Do you have any thoughts on tests for this change?

**Comment by javiercn** [comment] 2020-09-10 15:07
@SQL-MisterMagoo Add a middleware mapped to the download url, and validate that the middleware is called. Similar to what we do to validate PWAs caching behavior.

**Comment by SQL-MisterMagoo** [comment] 2020-09-10 15:08
@javiercn  That sounds good - do you have a link to the PWA caching test I can look at please?

**Comment by javiercn** [comment] 2020-09-10 15:10
https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/E2ETest/Tests/BootResourceCachingTest.cs

**Comment by SQL-MisterMagoo** [comment] 2020-09-10 16:15
I'll leave this - I don't have the experience with E2E tests to figure this out.

If someone else wants to pick it up, please do.

**Comment by pranavkm** [comment] 2020-09-10 16:18
@SQL-MisterMagoo we might be happy to take a code change without a test for this. I don't think we have ones for some of the other combinations that we do not intercept.

**Comment by mrdav1111** [comment] 2020-10-21 17:36
I would like to make the changes suggested by @SQL-MisterMagoo and write an E2E test too.

**Comment by captainsafia** [comment] 2020-10-21 17:38
@mrdav1111 Thanks for offering to help. This issue is still available to work on. You can take a look at our [contributing docs](https://github.com/dotnet/aspnetcore/blob/master/CONTRIBUTING.md) for info on how to get started.

**Comment by garfbradaz** [comment] 2021-06-23 09:23
Does https://github.com/dotnet/aspnetcore/pull/27104 now resolve this issue?

**Comment by captainsafia** [comment] 2021-06-27 17:57
Closing as resolved.

**Closed by captainsafia** 2021-06-27 17:57 UTC
Labels: affected-medium, area-blazor, bug, feature-blazor-builtin-components, feature-rendering, good first issue, help wanted, severity-major
