### ISSUE TITLE
Request Delegate Generator fails to compile code with CS0246 error for endpoint with generic type parameter

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#49384] opened 2023-07-13 09:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an internal application that has a user interface where various properties of a configuration object can be changed independently. To reduce duplication for this operations, various HTTP PATCH endpoints with different URLs call through a generic method that maps the endpoint based on a code pattern.

The method is essentially this where boilerplate wraps the invocation of a delegate with a generic parameter:

```csharp
private static RouteHandlerBuilder MapRepositoryUpdate<T>(
    this IEndpointRouteBuilder endpoints,
    string pattern,
    Func<IConfigurationRepository, RepositoryId, T, CancellationToken, Task<bool>> operation)
{
    return endpoints.MapPatch(pattern, async (
        long installationId,
        long repositoryId,
        [FromBody] Payload<T> request,
        InstallationService service,
        IConfigurationRepository repository,
        CancellationToken cancellationToken) =>
    {
        if (!await service.UserHasAccessToRepositoryAsync(installationId, repositoryId))
        {
            return Results.NotFound();
        }

        await repository.EnsureRepositoryAsync(repositoryId, cancellationToken);

        return await operation(repository, new(repositoryId), request.Value, cancellationToken) switch
        {
            false => Results.Conflict(),
            true => Results.NoContent(),
        };
    }).RequireAuthorization();
}
```

When attempting to compile this application with the Request Delegate Generator enabled the compilation fails with the following errors:

```
src\MyApplication\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(43,118): error CS0246: The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?) [src\MyApplication\MyApplication.csproj]
src\MyApplication\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs(58,140): error CS0246: The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?) [src\MyApplication\MyApplication.csproj]
```

It appears that the generator is not correctly taking into account the use of generics and is trying to use the identifier `T` literally as a type named `T` rather than as a generic parameter with that name.

When I tried to make the smallest repro I could with a one file application the endpoint would compile, so I think the issue may be related to the way the code is structured in the original application in terms of namespaces etc.

I've added an application that reproduces the error in [this repository](https://github.com/martincostello/rdg-generics-repro). There's probably more code that needed, but it's relatively minimal.

Note that the application will not actually run as I've stripped it down to just compiling so is 
missing various services registrations etc. It's just enough required to compile it successfully if the Request Delegate Generator is disabled.

### Expected Behavior

The application compiles and the endpoints behave at runtime as expected.

### Steps To Reproduce

1. Clone the [martincostello/rdg-generics-repro](https://github.com/martincostello/rdg-generics-repro) repository
2. Run `dotnet build`

### .NET Version

8.0.100-preview.6.23330.14

**Comment by captainsafia** [comment] 2023-07-13 16:08
It looks like this might be a dupe of https://github.com/dotnet/aspnetcore/issues/47338.

We're punting this to .NET 9 since there are some things that need to be adjusted with the interceptors feature before we can accommodate this. For .NET 8, the plan is to fallback to runtime-based source generation for endpoints with type parameters.

**Closed** 2023-07-17 21:50 UTC
Labels: feature-rdg, area-minimal
