### ISSUE TITLE
Default fallback culture not working in 3.0 after upgrading from 2.2

### ISSUE THREAD

**Issue by wstaelens** [dotnet/aspnetcore#17227] opened 2019-11-19 11:34 UTC
### Describe the bug
I had localization implemented in my asp.net core 2.2 app using IStringLocalizer. 
I've updated the app to 3.0 and localization is broken.

My "default" culture is "en". 

I have only 2 files: `SharedResources.nl.resx` and `SharedResources.resx`  

As you can see, my default .resx file doesn't include the `.en.` culture part in the filename.

In my asp.net core 2.2 app this fallback worked. Now it doesn't seem to work anymore. I can only get localization working when I add a file called `SharedResources.en.resx` containing my resources.

According to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#culture-fallback-behavior   the fallback should also search for SharedResources.resx, but this isn't the case. I tried to set my assembly NeutralResourcesLanguage to "en" (English) but this also doesn't do the trick.

Should anything extra be done to get the fallback working in asp.net core 3.0, compared to 2.2?

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

```
PM> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.1.202 [C:\Program Files (x86)\dotnet\sdk]
  2.2.108 [C:\Program Files (x86)\dotnet\sdk]
  2.2.401 [C:\Program Files (x86)\dotnet\sdk]
  3.0.100 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PM> 
```
VS 2019 16.3.9 
.net 4.8.03752

**Comment by javiercn** [comment] 2019-11-19 15:06
@wstaelens thanks for contacting us.

@ryanbrandenburg can you take a look at this/tell what's going on?

@wstaelens could you share a minimal repro project that helps us investigate the issue?

**Comment by wstaelens** [comment] 2019-11-19 15:19
I can't share much code (company project) but I can say that I followed the documentation from the ms docs website on first to upgrade from 2.2 to 3.0.  I've already upgrated 3 sites but only this one uses localization.

files:

- SharedResource.cs (just so that we can reference the class/type!)

- SharedResource.resx

- SharedResource.nl.resx

- SharedResource.fr.resx

- SharedResource.en.resx <-- the one I had to add to get my default "en" culture working.


my default culture is defined in a json config file. As customers can choose what their default is by setting ` "defaultsiteculture": "en",`  this value in the .json.

I also add cultures from database at runtime (when content is added in another culture it gets added in a combobox to switch language).

in ConfigureServices:
```
      var fooCfgDefaultCulture = Configuration.GetValue<string>("fooconfig:defaultsiteculture");
      services.Configure<RequestLocalizationOptions>(
        options =>
        {
          var supportedCultures = new List<CultureInfo> {
            new CultureInfo(fooCfgDefaultCulture)
          };
          options.DefaultRequestCulture = new RequestCulture(culture: fooCfgDefaultCulture, uiCulture: fooCfgDefaultCulture);
          options.SupportedCultures = supportedCultures; // Formatting numbers, dates, etc.
          options.SupportedUICultures = supportedCultures; // UI strings that we have localized.
        });

// ...

      }).SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
      .AddViewLocalization(Microsoft.AspNetCore.Mvc.Razor.LanguageViewLocationExpanderFormat.SubFolder) // localization .AddViewLocalization(Microsoft.AspNetCore.Mvc.Razor.LanguageViewLocationExpanderFormat.SubFolder)
        .AddDataAnnotationsLocalization(); 

      services.AddRazorPages();

}
```


in Configure:

```
{
      var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
      app.UseRequestLocalization(locOptions.Value);
// ...
```


all this worked fine in 2.2. but in 3.0 code seems to execute correctly, but doesn't fallback to the .resx file. the .en.resx (the default one) is required.

**Comment by javiercn** [comment] 2019-11-19 15:27
@wstaelens We are not asking for you to share your code, but to create a new separate project and add the minimal amount of code that reproduces the issue.

**Comment by javiercn** [comment] 2019-11-19 17:37
@ryanbrandenburg Can you take a look? This might be a regression.

**Comment by GeorgyOkov** [comment] 2020-01-15 14:33
@wstaelens After switching from 2.2 to 3.1, I have the same problem with IStringLocalizer, have you fixed it or made a custom solution?

**Comment by wstaelens** [comment] 2020-01-15 14:42
> @wstaelens After switching from 2.2 to 3.1, I have the same problem with IStringLocalizer, have you fixed it or made a custom solution?


I had to add the specific resx file for the default culture, in my case: Resources\SharedResources.**en**.resx

no idea why this is broken.

**Comment by GeorgyOkov** [comment] 2020-01-15 14:56
ok. thanks. But this didn't help in my case.
I have in appStrings.resx for example, sting1 and string2, but in AppStrings.fr.resx only string1. When I try to get string2 from fr, it returns nothing (. In 2.2 everything works fine.

**Comment by ryanbrandenburg** [comment] 2020-01-16 17:56
Hard to judge without a repro project, but I suspect you're running into https://github.com/dotnet/aspnetcore/issues/17269. If that doesn't solve your issue please supply a repro project so I can understand the full context.

**Comment by wstaelens** [comment] 2020-01-17 09:54
@GeorgyOkov  does this work for you?
https://github.com/microsoft/msbuild/issues/4806#issuecomment-541018341

**Comment by GeorgyOkov** [comment] 2020-01-17 10:14
> @GeorgyOkov does this work for you?
> [microsoft/msbuild#4806 (comment)](https://github.com/microsoft/msbuild/issues/4806#issuecomment-541018341)

@wstaelens  Yes, it works like magic. Thanks.

**Comment by ryanbrandenburg** [comment] 2020-01-17 17:27
@wstaelens did it work for you too? If so I'll close this out.

**Comment by wstaelens** [comment] 2020-01-20 08:33
> @wstaelens did it work for you too? If so I'll close this out.

@ryanbrandenburg I had time to look at it now and yes it fully works again in 3.1 by opting out.

 I removed my .en.resx again ('en' is my default language) and edit the csproj file and added:

```xml
  <PropertyGroup>
    <!-- Work around https://github.com/microsoft/msbuild/issues/4740 -->
    <!-- https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-known-issues.md -->
    <!-- https://github.com/dotnet/aspnetcore/issues/17227 -->
    <!-- https://github.com/microsoft/msbuild/issues/4806#issuecomment-541018341 -->
    <EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>  
```

now the localization works again the same as in 2.x releases!

**Comment by ryanbrandenburg** [comment] 2020-01-21 20:48
Cool, I'll close this then since other issues track the work related to this.

**Closed by ryanbrandenburg** 2020-01-21 20:48 UTC
Labels: Needs: Attention :wave:, area-mvc, investigate
