### ISSUE TITLE
Application not working when upgrading from RC2 to the final version 

### ISSUE THREAD

**Issue by amramin** [dotnet/aspnetcore#52190] opened 2023-11-19 07:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I got this error when i upgraded from RC2 to the final version and try to run the app
, i use auto render mode blazor

blazor.web.js:1 Error: One or more errors occurred. (The JSON value could not be converted to Microsoft.AspNetCore.Components.RootComponentOperation[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
at Jn (marshal-to-js.ts:349:18)
at Ul (marshal-to-js.ts:306:28)
at 00b1e8b6:0x1faca
at 00b1e8b6:0x1bf8b
at 00b1e8b6:0xf172
at 00b1e8b6:0x1e7e4
at 00b1e8b6:0x1efda
at 00b1e8b6:0xcfec
at 00b1e8b6:0x440ad
at e. (cwraps.ts:338:24)

### Expected Behavior

The application should launch

### Exceptions (if any)

blazor.web.js:1 Error: One or more errors occurred. (The JSON value could not be converted to Microsoft.AspNetCore.Components.RootComponentOperation[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
at Jn (marshal-to-js.ts:349:18)
at Ul (marshal-to-js.ts:306:28)
at 00b1e8b6:0x1faca
at 00b1e8b6:0x1bf8b
at 00b1e8b6:0xf172
at 00b1e8b6:0x1e7e4
at 00b1e8b6:0x1efda
at 00b1e8b6:0xcfec
at 00b1e8b6:0x440ad
at e. (cwraps.ts:338:24)

### .NET Version

8.0.100

**Comment by zaneclaes** [comment] 2023-11-19 14:26
+1, my application that worked great on RC1 and RC2 exhibits this behavior with the 8.0.100 final release. It no longer works in either Development or Production modes.  Tried cleaning everything and even building on a different machine (which has only ever had the final version of dotnet 8.0.100 installed) just in case, but nothing fixes it. 

<img width="1274" alt="Screenshot 2023-11-19 at 7 24 59 AM" src="https://github.com/dotnet/aspnetcore/assets/2084821/b9a5b6f4-3a8e-46de-8b05-727806195822">

**Comment by zaneclaes** [comment] 2023-11-21 13:54
I've been trying to find a work-around and can't seem to get anywhere. I downgraded the `Microsoft.AspNetCore.Components.*` packages back to RC2, but that did not fix the issue. This suggests to me that the issue is upstream, i.e., perhaps related to `wasm-tools` wich generates `blazor.web.js`. I thought perhaps wasm tools was outdated, but it seems fine:

```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
wasm-tools                 8.0.0/8.0.100         SDK 8.0.100 
```

Re-installing the workload yields the same version, so nothing too suspicious there:

```
sudo dotnet workload install wasm-tools                                                                                ✔  06:51:12 AM 

Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.100

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, run 'dotnet dev-certs https --trust'
Learn about HTTPS: https://aka.ms/dotnet-https

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Checking the state of installed workloads...
Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0...
Pack Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0...
Installing pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.0...
Pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.0...
Installing pack Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.browser-wasm version 8.0.0...
Pack Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.browser-wasm version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.browser-wasm version 8.0.0...
Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.0...
Pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.0...
Installing pack Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.0...
Pack Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Node.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Node.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Node version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Python.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Python.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Python version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Cache.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Cache.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Cache version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Sdk version 8.0.0...
----------------

Workload(s) 'wasm-tools' are already installed.
Skipping NuGet package signature verification.
Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0...
Pack Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.0...
Installing pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.0...
Pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.0...
Installing pack Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.browser-wasm version 8.0.0...
Pack Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.browser-wasm version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.Cross.browser-wasm version 8.0.0...
Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.0...
Pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.0...
Installing pack Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.0...
Pack Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Node.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Node.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Node version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Python.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Python.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Python version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Cache.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Cache.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Cache version 8.0.0...
Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.osx-arm64 version 8.0.0...
Pack Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.osx-arm64 version 8.0.0 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.Emscripten.Sdk version 8.0.0...
Garbage collecting for SDK feature band(s) 6.0.100 7.0.300 7.0.400 8.0.100-rc.2 8.0.100...

Successfully installed workload(s) wasm-tools.

dotnet workload search                                                                                           ✔  13s  06:51:36 AM 

Workload ID                 Description                                             
------------------------------------------------------------------------------------
android                     .NET SDK Workload for building Android applications.    
aspire                      .NET Aspire SDK (Preview)                               
ios                         .NET SDK Workload for building iOS applications.        
maccatalyst                 .NET SDK Workload for building MacCatalyst applications.
macos                       .NET SDK Workload for building macOS applications.      
maui                        .NET MAUI SDK for all platforms                         
maui-android                .NET MAUI SDK for Android                               
maui-desktop                .NET MAUI SDK for Desktop                               
maui-ios                    .NET MAUI SDK for iOS                                   
maui-maccatalyst            .NET MAUI SDK for Mac Catalyst                          
maui-mobile                 .NET MAUI SDK for Mobile                                
maui-tizen                  .NET MAUI SDK for Tizen                                 
maui-windows                .NET MAUI SDK for Windows                               
mobile-librarybuilder       workloads/mobile-librarybuilder/description             
tvos                        .NET SDK Workload for building tvOS applications.       
wasi-experimental           workloads/wasi-experimental/description                 
wasm-experimental           workloads/wasm-experimental/description                 
wasm-experimental-net7      .NET WebAssembly experimental tooling for net7.0        
wasm-tools                  .NET WebAssembly build tools                            
wasm-tools-net6             .NET WebAssembly build tools for net6.0                 
wasm-tools-net7             .NET WebAssembly build tools for net7.0                 

dotnet workload list                                                                                                   ✔  06:51:41 AM 

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
wasm-tools                 8.0.0/8.0.100         SDK 8.0.100        

Use `dotnet workload search` to find additional workloads to install.
```

**Comment by javiercn** [comment] 2023-11-24 13:17
@amramin @zaneclaes thanks for contacting us.

Could you provide a minimal repro project as a public GitHub repository that demonstrates the issue?

**Comment by zaneclaes** [comment] 2023-11-24 14:12
@javiercn sure, pretty easy to do. Just try to convert a new Server + Client app into WebAsm render mode. Simply [attempting to follow the interactive web assembly docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0) yields the error. Here's a zip repro: 
[Archive 2.zip](https://github.com/dotnet/aspnetcore/files/13459925/Archive.2.zip)

All I did was create 2 new apps, reference the client app from the server, and switch to interactive mode.

We also keep running into surprising new 8.0.0 gachyas that stall us for hours or days, even in simple tasks. 

In attempting to create this repro, I noticed that the following bug still exists (as others have reported): 
 https://github.com/dotnet/aspnetcore/issues/49167 ... here is a repro: 
[Archive.zip](https://github.com/dotnet/aspnetcore/files/13459894/Archive.zip)

In another case, we tried to add the `Microsoft.AspNetCore.Components.WebAssembly.DevServer` to a brand new template project and immediately started getting 404 errors on every page. It took us a while to realize that despite being named `DevServer`, this is a package for blazor CLIENTS.

**Comment by zaneclaes** [comment] 2023-11-24 14:35
Related: it has never been clear to me if we are still supposed to have 2 projects (client/server) in the new `RenderMode` paradigm, as we did before with a hosted blazor app. If I was wrong about this and they are supposed to be one project, then it opens up many many new problems for us. For example, how do we achieve code isolation and limit build size when all the dependencies are compiled into web assembly? We spent a lot of effort making sure our Client app was small and loaded quickly, but if we try to merge it with the Server app we end up with a `100,000%` larger web build (not joking), due to all the dependencies used by the server which are not needed by the client.

**Comment by felipepassion** [comment] 2023-11-26 22:16
I'm having the same issue after upgrading to .net8 version

**Comment by Cyber5an** [comment] 2023-11-27 12:29
Same here. The recompilation of a well-working released version does not function properly.

**Comment by SigurdEEspersen** [comment] 2023-11-28 15:25
I'm getting the same issue. Trying to add MudBlazor using their template. Everything works the first time starting the app, but starting the app again after that causes the issue. Please fix quickly this is stopping me from using .NET 8

**Comment by felipepassion** [comment] 2023-11-29 00:31
I downgraded to RC2 and it's working now.

Just waiting for some updates to reintegrate .net 8 new version

**Comment by zaneclaes** [comment] 2023-11-29 15:32
@javiercn can we get some triage on this? It seems prudent to issue a warning on the 8.0.0 release not to attempt to use the new RenderMode feature with Web Assembly, since this issue occurs even with new projects that attempt to follow the docs.

**Comment by zaneclaes** [comment] 2023-12-01 00:03
Whoops. I had meant to detail a 3rd issue, but confused the post by including a zip + screenshots from the 3rd issue, and not from the main issue. Sorry about that @MackinnonBuck ; I was rushed trying to post that in the middle of the holidays.

I actually just "fixed" my team's project by deleting the **Client** app entirely and rebuilding it from scratch (copying each file over). Now with the exact same code and _not a single code change in the git diff_, it is working fine. As @SigurdEEspersen hinted, the problem seems to get triggered by some external circumstances, because the same applies to the "repro" projects I created (I unzipped the actual repro from earlier, and it worked fine).

All this obviously points at some kind of lingering build artifact... but that theory is busted by the fact that I had already tried removing the `bin` and `obj` folders, cleaning, and rebuilding the project. So I'm at a loss as to what could be causing this apparently nondeterministic behavior.

**Comment by zaneclaes** [comment] 2023-12-01 00:11
@MackinnonBuck also re:
> If you create a new Blazor Web app with WebAssembly or Auto interactivity selected, the project will be set up this way.

FWIW, I use Rider and the templates do not have this option... I know Rider hasn't updated for 8.0.0 yet, but I thought templates' would still be supported... the Blazor Web App template always creates a single project for me:

<img width="594" alt="Screenshot 2023-11-30 at 5 10 57 PM" src="https://github.com/dotnet/aspnetcore/assets/2084821/a7c68ae8-1192-451b-8e35-c53ccc638bbc">

**Comment by MackinnonBuck** [comment] 2023-12-01 16:29
Thanks for all the info, @zaneclaes. This seems like the type of thing that might be caused by a caching issue, but you mentioned that the issue repro'd across browsers and in incognito windows, so it's probably not that.

I see that this issue is getting notable engagement, so we want to determine as quickly as possible if there is a product issue here that needs fixing.

To anyone else experiencing the issue - it would be massively appreciated if you could provide a minimal repro project that demonstrates the issue, hosted as a public GitHub repository for us to investigate. It's critical that we get this information so we can reproduce the and debug the issue, because we haven't been able to reproduce it on our end so far.

Thanks!

**Comment by MackinnonBuck** [comment] 2023-12-01 16:31
@zaneclaes:

> FWIW, I use Rider and the templates do not have this option...

You could also create a project using the `dotnet` CLI, and then open it in Rider. For example, to create a Blazor Web app that uses WebAssembly interactivity, you can do:

```text
dotnet new blazor -int WebAssembly
```

**Comment by patrickgod** [comment] 2023-12-15 22:03
@amramin @zaneclaes @MackinnonBuck 

Hey guys,

I've successfully replicated the issue. It turns out that the cause was not updating all packages to version 8.0.0.

Here's a screenshot for reference:

![2023-12-15 22_52_08-BlazorCrudDotNet8 - Microsoft Visual Studio](https://github.com/dotnet/aspnetcore/assets/23096494/a00aec16-7907-4442-940a-67f4b8db911a)

While the SDK and all the packages in the Server project were updated, I overlooked the package in the Client project. This oversight led to the encountered problem when trying to use the Auto or WebAssembly rendermode.

The issue was resolved by updating the package in the Client project and then performing a **clean** and **rebuild** of the project.

Hope this helps.

Take care,

Patrick

**Comment by MackinnonBuck** [comment] 2023-12-19 00:45
Glad you were able to figure this out, @patrickgod!

I'm going to close out this issue, since it's not a product bug and we have upgrade guidance in our [docs](https://learn.microsoft.com/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#update-package-references) that mentions this as a requirement. If others keep experiencing the problem and Patrick's suggestion doesn't help, please feel free to open a new issue 🙂

**Closed** 2023-12-19 00:45 UTC
Labels: investigate, Needs: Author Feedback, area-blazor
