### ISSUE TITLE
add ability to specify domain_hint for MSAL AD B2C

### ISSUE THREAD

**Issue by Ma3yTa** [dotnet/aspnetcore#30688] opened 2021-03-05 10:03 UTC
https://docs.microsoft.com/en-us/azure/active-directory-b2c/direct-signin?pivots=b2c-user-flow
https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-generic-openid-connect#response-mode

**Comment by javiercn** [comment] 2021-03-05 11:04
@Ma3yTa thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/29440

**Closed** 2021-03-05 11:04 UTC
Labels: area-blazor, blazor-wasm
