### ISSUE TITLE
[CRITICAL BUG] [REGRESSION] Problem when variables have the same name with differnt casing in blazor/net8

### ISSUE THREAD

**Issue by AbstractionsAs** [dotnet/aspnetcore#53520] opened 2024-01-21 20:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have had this issue appear in multiple projects (at multiple customer sites) after the projects have been upgraded to net8.

After net8, when the model in an `EditContext` has a name that differs only in casing from another variable, and that variable is `null`, the all controls inside the `EditContext` that use `FieldIdentifier `crash with an `ArgumentNullException` stating that `model` cannot be `null`.

This is a very common case, at least it is in my projects. Usually, this occurs because I have a component that can either create or edit an object. Typically, if the component parameter `Model` is `null` it would set the EditForm model variable `model` to a new instance. If it is not `null`, it would set the `EditForm` `model `variable to a clone of the original `Model`.

The problem applies to all rendermodes.

### Expected Behavior

I expect it to not crash. This worked in `net7.0` and earlier

### Steps To Reproduce

Given the example class `BugExampleModel.cs`

```csharp
 public class BugExampleModel
 {
     public string Name { get; set; } 
 }
```

and example Component `BugExampleComponent.razor`

``` razor
<h3>BugExampleComponent</h3>

<EditForm Model="model">
    <InputText @bind-Value="model.Name" />
</EditForm>

@code {
    private BugExampleModel model;

    [Parameter]
    public BugExampleModel Model { get; set; }


    protected override void OnParametersSet() 
        => model = Model == null ? new() : new() { Name = Model.Name };
}
```

You can reproduce the problem by putting the following on a page:

``` razor
<BugExampleComponent  />
```

This, however, will not crash

``` razor
<BugExampleComponent Model="@(new BugExampleModel { Name = "Bob" })" />
```

### Exceptions (if any)

System.ArgumentNullException: Value cannot be null. (Parameter 'model')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier..ctor(Object model, String fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[String](Expression1 accessor)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)

### .NET Version

8.0.200-preview.23624.5

### Anything else?

As far as I've been able to tell, this occurs in all versions of net8.0, but not before.

**Comment by javiercn** [comment] 2024-01-22 12:53
Dupe of https://github.com/dotnet/aspnetcore/issues/52755

**Closed by javiercn** 2024-01-22 12:53 UTC
Labels: area-blazor
