### ISSUE TITLE
Refactoring support for Razor (.cshtml and .razor) files

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#10480] opened 2019-05-22 23:56 UTC

**Comment by mkArtakMSFT** [comment] 2020-01-10 19:07
@NTaylorMullen can you please dupe this with the work we do to cover this? Thanks.

**Comment by NTaylorMullen** [comment] 2020-01-10 21:26
This is too broad an issue to begin with. Closing given it's not clear as to which refactoring scenarios we were trying to track without a dup

**Closed by NTaylorMullen** 2020-01-10 21:26 UTC
Labels: area-blazor, enhancement

**Comment by mkArtakMSFT** [comment] 2020-02-29 21:59
This was a dupe of https://github.com/dotnet/aspnetcore/issues/6112
