### ISSUE TITLE
JSInterop for properties and element methods

### ISSUE THREAD

**Issue by hultqvist** [dotnet/aspnetcore#24734] opened 2020-08-10 10:00 UTC
### Background

I can directly call global methods such as `window.history.back` like this

    JSRuntime.InvokeVoidAsync("history.back");

But without custom JavaScript I can't get/set properties such as

    navigator.language

And not call/get/set element methods and properties

    element.focus()
    element.clientHeight

### Current work

I found this contribution that add [ElementReference.FocusAsync()](https://github.com/dotnet/aspnetcore/pull/23316/files)

Which made me wonder why we need custom infrastructure for each call.

### Workaround

I've made this general code for accessing properties in both the `window` hierarchy as well as methods and properties on `ElementReference`

```JavaScript
function windowPath(path) {
    if (path == null || path == "")
        return window;
    var parts = path.split(".");
    var p = window;
    for (var n = 0; n < parts.length; n++)
        p = p[parts[n]];
    return p;
}
window.BlazorDOM = {
    get: function (path) {
        var p = windowPath(path);
        return p;
    },
    set: function (path, value) {
        var parts = path.split(".");
        var p = window;
        for (var n = 0; n < parts.length - 1; n++)
            p = p[parts[n]];
        p[parts[parts.length - 1]] = value;
    },
    element: {
        get: function (element, method) {
            if (element)
                return element[method];
        },
        set: function (element, method, value) {
            if (element)
                element[method] = value;
        },
        apply: function (element, method, args) {
            if (element) {
                var m = element[method];
                if (m)
                    m.apply(element, args);
            }
        },
    },
};

```

Then the following C# code can access any method and property

```C#
static class Window
{
        public static IJSRuntime Runtime;

        public static ValueTask<T> Get<T>(string property)
        {
            return JSRuntime.InvokeAsync<T>("BlazorDOM.get", property);
        }
        public static ValueTask Set<T>(string property, T value)
        {
            return JSRuntime.InvokeVoidAsync("BlazorDOM.set", property, value);
        }
}

public static class ElementExtensions
{
        static IJSRuntime Runtime => Window.JSRuntime;

        public static ValueTask Apply(this ElementReference element, string method, params object[] args)
        {
            return Runtime.InvokeVoidAsync("BlazorDOM.element.apply", element, method, args);
        }

        public static ValueTask<T> Get<T>(this ElementReference element, string property)
        {
            return Runtime.InvokeAsync<T>("BlazorDOM.element.get", element, property);
        }

        public static ValueTask Set<T>(this ElementReference element, string property, T value)
        {
            return Runtime.InvokeVoidAsync("BlazorDOM.element.set", element, property, value);
        }
}
```

Which makes the following code possible.

```C#
var hidden = await Window.Get<bool>("document.hidden");
ElementReference e;
e.Apply("blur");
e.Apply("focus");
e.Apply("select");
var width = await e.Get("clientHeight")
```

### Feature suggestion

Would something like the above code be integrated together with `JSRuntime.InvokeAsync`?

The recent contribution [ElementReference.FocusAsync()](https://github.com/dotnet/aspnetcore/pull/23316/files) also tries to manage a reference to IJSRuntime. Why can't Blazor Webassembly have one single static reference to it rather than having to grab it using [Inject].

**Comment by SteveSandersonMS** [comment] 2020-08-10 14:55
We're looking at the ability to make JS interop calls to JS object instances in #24434, so I'd regard this as a duplicate of that.

Thanks for the suggestion!

**Closed** 2020-08-19 16:20 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
