### ISSUE TITLE
SignalR Clients connection

### ISSUE THREAD

**Issue by PirasathLuxchumykanthan** [dotnet/aspnetcore#44489] opened 2022-10-12 07:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Well i dont know how to say this there are 2 system of signal core and not core.. i use core..

i don't know how many client can connect.. I'm afraid to use it.. bce. i don't know how many.. connection it can handler..

Can any body explain me.. ?

i try this redis but Im serious not a linux fan... and azure noway.. serious..

is there any windows software that can handler that..

**Comment by davidfowl** [comment] 2022-10-12 07:39
Potentially a dupe of https://github.com/dotnet/aspnetcore/issues/5281. It's not clear what you're asking but I think maybe that issue related.

**Comment by PirasathLuxchumykanthan** [comment] 2022-10-12 08:19
almost.. thx for answe.. i just want my signalr can handler more then 100000 clients
but I cant get it work

**Comment by davidfowl** [comment] 2022-10-12 14:39
What does can't get it to work mean? Are you running into problems? If so, can you describe them?

**Closed** 2022-10-27 19:01 UTC
Labels: Needs: Author Feedback, area-signalr, Status: No Recent Activity
