### ISSUE TITLE
Application Razor pages not authenticated when using Angular template with Individual Accounts

### ISSUE THREAD

**Issue by paviad** [dotnet/aspnetcore#18602] opened 2020-01-27 17:15 UTC
# Summary

When using the dotnet Angular template with individual account authorization, application Razor pages are not authenticated by default, and setting a default authentication scheme doesn't have any effect.

# Minimal Reproduction

## Setup

```
md repro
cd repro
dotnet new angular -au individual
(echo @page
echo @model TestModel
echo ^<partial name="Shared/_LoginPartial.cshtml" /^>
echo ^<h1^>Test^</h1^>)>Pages\Test.cshtml
(echo using Microsoft.AspNetCore.Mvc.RazorPages;
echo using Microsoft.AspNetCore.Authorization;
echo namespace repro.Pages
echo {
echo    // [Authorize(AuthenticationSchemes = "Identity.Application"^)]
echo    public class TestModel : PageModel
echo    {
echo    }
echo })>Pages\Test.cshtml.cs
dotnet restore
dotnet run
```

As an alternative to the `echo` commands above, create these files:

### Pages/Test.cshtml
```
@page
@model TestModel
<partial name="Shared/_LoginPartial.cshtml" />
<h1>Test</h1>
```

### Pages/Test.cshtml.cs
```
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace repro.Pages
{
   // [Authorize(AuthenticationSchemes = "Identity.Application")]
   public class TestModel : PageModel
   {
   }
}
```

## Execution Procedure

Navigate to https://localhost:5001, register as a new user, then navigate to https://localhost:5001/Test and observe that the login indicator indicates no user is logged in.

Now, remove the comment from the line `// [Authorize(AuthenticationSchemes = "Identity.Application")]` in `Pages/Test.cshtml.cs` and retry, see that this time the page request is authenticated.

Now comment the line again, and try to set a default authentication scheme by changing line 39 in `Startup.cs` from:

`services.AddAuthentication()`

to

`services.AddAuthentication("Identity.Application")`

And recheck, see that the page request is, again, not authenticated.

## Expected result
One of two, either:

1. New razor pages should be included in the identity server authentication scheme, similar to the ones in the `Identity` area.

or

2. Setting a proper default authentication scheme should affect new Razor pages.

## Environment
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
```

**Comment by mkArtakMSFT** [comment] 2020-01-27 17:39
Thanks for contacting us, @paviad.
@HaoK can you please look into this?
Feel free to sync up with @javiercn if there are any question.

**Comment by HaoK** [comment] 2020-03-18 21:34
@blowdart thoughts?  Shouldn't an [Authorize] be required on the page model for the expectation that the page requires authentication?  Identity pages are under an /Identity which are secured by Area I believe.

**Comment by blowdart** [comment] 2020-03-18 21:36
Yup, you need to mark the page as needing authentication

**Comment by HaoK** [comment] 2020-03-18 22:41
Ok closing this as by design then

**Closed by HaoK** 2020-03-18 22:41 UTC
Labels: area-identity, investigate

**Comment by paviad** [comment] 2020-03-19 07:24
Why did you close this? [Authorize] Is on the page model, and it doesn't work.
