### ISSUE TITLE
XML response formatted differently

### ISSUE THREAD

**Issue by joacar** [dotnet/aspnetcore#22196] opened 2020-05-25 12:49 UTC
### Describe the bug
`ProblemDetails` are serialized differently depending on how the XML output formatter is configured.
`AddControllers().AddXmlSerializerFormatters()` vs `AddControllers(o => o.OutputFormatters.Add(new XmlSerializerOutputFormatter()));`

The former produces `<problem xmlns="..">..</problem>` while the latter produces `<ProblemDetails>..</ProblemDetails>`, which can be deserialized using `XmlSerializer`.

### To Reproduce
[WebApplication4.zip](https://github.com/dotnet/aspnetcore/files/4677207/WebApplication4.zip)

### Further technical details
- ASP.NET Core version: 3.1.300
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015115 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: Microsoft Visual Studio Professional 2019 Version 16.5.5

**Comment by javiercn** [comment] 2020-05-25 13:56
@joacar thanks for contacting us.

I believe that is expected, since AddXmlFormatters will configure the underlying formatter with a set of default options.

**Comment by joacar** [comment] 2020-05-25 14:42
Those default options breaks "default" XML serialization which doesn't feel right. If it was the other way around, I buy it.

**Comment by javiercn** [comment] 2020-05-26 10:48
Hi,

I believe the current behavior is by design and intentional. If you want to deserialize the problem details I think you'll have to configure the serializer or use a different type to do so.

I don't have any insights into why this was done this way, but @pranavkm might have some other insights.

**Comment by pranavkm** [comment] 2020-05-26 16:08
The XML schema is listed here: https://tools.ietf.org/html/rfc7807#appendix-A. MVC tailors the `ProblemDetails` XML response based on this.

**Comment by javiercn** [comment] 2020-05-26 16:10
@pranavkm thanks for the details.

Closing this issue since the behavior is to match the spec.

**Closed by javiercn** 2020-05-26 16:10 UTC
Labels: area-mvc

**Comment by joacar** [comment] 2020-06-01 12:33
@pranavkm @javiercn Can you please point me to some documentation how to deserialize to XML nicely?

Current code doesn't look appealing. Although it's just one extra line of code, this introduces much more complexity and leaks implementation details I think that the caller of an API should be aware of.
```c#
var serializer = new XmlSerializer(typeof(ProblemDetailsWrapper));
var problemDetailsWrapper = (IUnwrappable)serializer.Deserialize(responseStream);
var problemDetails = (ProblemDetails)problemDetailsWrapper.Unwrap(typeof(ProblemDetails));
```

of course it's possible to construct the `XmlReader` and call `ProblemDetails.ReadXml(XmlReader)`

**Comment by pranavkm** [comment] 2020-06-01 15:13
That looks like the code you would need to write when using `XmlSerializer`. If you're using the data contract serializer, you might be able to use https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iextensibledataobject?view=netcore-3.1 to deserialize `ProblemDetails`. 

Btw, if this feature is problematic, you could consider disabling it:

* https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.1#disable-problemdetails-response
* https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1#validation-failure-error-response

**Comment by joacar** [comment] 2020-06-02 07:23
@pranavkm I wrote this small class 

```c#
// Xml serialization doesn't check for attributes on inherited parent and Namespace is internal
[XmlRoot("problem", Namespace = "urn:ietf:rfc:7807")]
public sealed class ProblemDetailsRfc7807 : ProblemDetailsWrapper
{
    private ProblemDetailsRfc7807()
    {
    }
    
    public static implicit operator ProblemDetails(ProblemDetailsRfc7807 problemDetails) => Unwrap(problemDetails);
    
    private static ProblemDetails Unwrap(IUnwrappable unwrappable) => (ProblemDetails) unwrappable.Unwrap(typeof(ProblemDetails));
}
```
Would you be open for a PR simply adding an implicit operator to `ProblemDetailsWrapper` that converts it to `ProblemDetails` just by calling `Unwrap`? Then one can just write

```c#
var serializer = new XmlSerializer(typeof(ProblemDetailsWrapper));
ProblemDetails problemDetails = (ProblemDetailsWrapper)serializer.Deserialize(responseStream);
```

Thanks

**Comment by pranavkm** [comment] 2020-06-02 13:30
> Would you be open for a PR simply adding an implicit operator to ProblemDetailsWrapper that converts it to ProblemDetails just by calling Unwrap? 

Mvc wouldn't be the right place to put this - we would not expect clients consuming APIs produced by ASP.NET Core to reference the framework. Publishing this as a community driven NuGet package sounds like much more tenable solution.

**Comment by joacar** [comment] 2020-06-02 13:46
Sounds perfectly reasonable!
