### ISSUE TITLE
Blazor WASM hosted with IdentityServer4 can't connect to authorized SignalR hubs and <img> sources not working

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#20810] opened 2020-04-14 14:43 UTC
Hello I updated my Blazor WASM application to use IdentityServer4 based on the following documentation:

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1

This works fine for the http API requests.

The problem I run into is that I also have a `[Authorize]` SignalR hub and I have API controllers that provide  img sources. When I try to connect to the SignalR hub I see a 401 error in the browser console. The same errors you see for the image sources. In the old situation I used to have a authorization policy for both Bearer and Cookies, but when using the IdentityServer4 JWT logic this doesn't work.

Anybody got an idea how to resolve this?

This is my code for connecting to the SignalR hub:

```
            var connection = new HubConnectionBuilder()
                .WithUrl(Navigation.ToAbsoluteUri("/hubs/test"), options =>
                {
                    options.AccessTokenProvider = () => Task.FromResult(token.Value);
                })
                .Build();

            await using (connection)
            {
                await connection.StartAsync();

                await connection.SendAsync("SendMessage", "Niek", "Hallo");
            }
```

**Comment by javiercn** [comment] 2020-04-14 15:05
@njannink thanks for contacting us.

If you are able to get a token and call an API I think the issue might be either on the signalr side client configuration or in the way the hub is secured?

I believe SignalR sends the access token in a query parameter during the connect/negotiate phase. If that's the case, it's likely that the default auth middleware won't pick it up, as it expects it to be on the Authorization header.

I'll let the SignalR comment on this but there are several ways this can be approached.
* Put a middleware in the request pipeline to intercept requests to the hub, grab the token and set it up on the authorization header before the auth middleware tries to authenticate the user.
* Register an event handler in the authentication handler to do the same see [here](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L51-L55) for details.

Of the different options, 2 is my preferred choice.

@anurse giving this to signalr so that you make a decision on the guidance here.

**Comment by njannink** [comment] 2020-04-14 15:16
In the browser console log you see the following error: 

> WebSocket connection to 'wss://localhost:5001/hubs/test?id=swZ6XmBUxYtjAVbnOodkTg' failed: HTTP Authentication failed; no valid credentials available

When using Fiddler I see the following events:
200	HTTPS	localhost:5001	/hubs/test/negotiate?negotiateVersion=1
200	HTTP	Tunnel to	localhost:5001
401	HTTPS	localhost:5001	/hubs/test?id=swZ6XmBUxYtjAVbnOodkTg

So it looks like the initial connection to SignalR succeeds but the websocket connection seems to fail

**Comment by BrennanConroy** [comment] 2020-04-14 17:07
This is a dupe of https://github.com/dotnet/aspnetcore/issues/18697 which will be fixed in an upcoming release.

**Closed** 2020-04-14 17:08 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr, blazor-wasm

**Comment by njannink** [comment] 2020-04-14 17:29
I tried the workaround:
.WithUrl(NavigationManager.ToAbsoluteUri("/chatHub?access_token=XXXX"))

But that doesn't work for me. I still get a 401 for Bearer header

**Comment by anurse** [comment] 2020-04-14 19:10
Did you see [this comment](https://github.com/dotnet/aspnetcore/issues/18697#issuecomment-613580421) in the other issue thread?

**Comment by njannink** [comment] 2020-04-15 13:00
Yes I found a workaround that works for me can you have a look at it? It's in the other thread
