### ISSUE TITLE
Blazor WebAssembly Project - Doesn't show page until F12 pressed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26077] opened 2020-09-18 22:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1162284/blazor-webassembly-project-doesnt-show-page-until.html)._

---
[severity:Other] [regression] [worked-in:16.7.2]
To the default Blazor WebAssembly Template Project, I added a new component and included that in the Counter.razor page and ran the project. The browser shows blank page (tab shows spinner icon). Pressing F12 to open the developer tools, immediately show the home page.

---
#### Feedback Bot on 8/26/2020, 02:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by captainsafia** [comment] 2020-09-18 22:46
Thanks for reporting this issue! I'm closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/24706 which was opened previously.

**Closed by captainsafia** 2020-09-18 22:46 UTC
Labels: Author: Migration Bot :robot:
