### ISSUE TITLE
Test failure: EmptyWebTemplateCSharp

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#20162] opened 2020-03-25 22:48 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=573012&view=ms.vss-test-web.build-test-results-tab&runId=17967354&resultId=120456&paneView=debug

<details>
<summary>Error</summary>

```
Process exited with code 134

StdErr: malloc_consolidate(): invalid chunk size

StdOut: Usage: new [options]

Options:

-h, --help Displays help for this command.

-l, --list Lists templates containing the specified name. If no name is specified, lists all templates.

-n, --name The name for the output being created. If no name is specified, the name of the current directory is used.

-o, --output Location to place the generated output.

-i, --install Installs a source or a template pack.

-u, --uninstall Uninstalls a source or a template pack.

--nuget-source Specifies a NuGet source to use during install.

--type Filters templates based on available types. Predefined values are "project", "item" or "other".

--dry-run Displays a summary of what would happen if the given command line were run if it would result in a template creation.

--force Forces content to be generated even if it would change existing files.

-lang, --language Filters templates based on language and specifies the language of the template to create.

--update-check Check the currently installed template packs for updates.

--update-apply Check the currently installed template packs for update, and install the updates.

Templates Short Name Language Tags
Console Application console [C#], F#, VB Common/Console

Class library classlib [C#], F#, VB Common/Library

WPF Application wpf [C#], VB Common/WPF

WPF Class library wpflib [C#], VB Common/WPF

WPF Custom Control Library wpfcustomcontrollib [C#], VB Common/WPF

WPF User Control Library wpfusercontrollib [C#], VB Common/WPF

Windows Forms (WinForms) Application winforms [C#], VB Common/WinForms

Windows Forms (WinForms) Class library winformslib [C#], VB Common/WinForms

Unit Test Project mstest [C#], F#, VB Test/MSTest

NUnit 3 Test Project nunit [C#], F#, VB Test/NUnit

NUnit 3 Test Item nunit-test [C#], F#, VB Test/NUnit

xUnit Test Project xunit [C#], F#, VB Test/xUnit

Razor Component razorcomponent [C#] Web/ASP.NET

Razor Page page [C#] Web/ASP.NET

MVC ViewImports viewimports [C#] Web/ASP.NET

MVC ViewStart viewstart [C#] Web/ASP.NET

TypeScript file tsfile Web/Script

LESS Style Sheet less Web/Style

SCSS Style Sheet (SASS) scss Web/Style

Protocol Buffer File proto Web/gRPC

Examples:

dotnet new xunit

dotnet new winforms

dotnet new --help

Expected: True

Actual: False
```

</details>

<details>
<summary>Stacktrace</summary>

```
   at Templates.Test.Helpers.TemplatePackageInstaller.InstallTemplatePackages(ITestOutputHelper output) in /_/src/ProjectTemplates/test/Helpers/TemplatePackageInstaller.cs:line 150
   at Templates.Test.Helpers.TemplatePackageInstaller.EnsureTemplatingEngineInitializedAsync(ITestOutputHelper output) in /_/src/ProjectTemplates/test/Helpers/TemplatePackageInstaller.cs:line 63
   at Templates.Test.Helpers.ProjectFactoryFixture.GetOrCreateProject(String projectKey, ITestOutputHelper output) in /_/src/ProjectTemplates/test/Helpers/ProjectFactoryFixture.cs:line 40
   at Templates.Test.EmptyWebTemplateTest.EmtpyTemplateCore(String languageOverride) in /_/src/ProjectTemplates/test/EmptyWebTemplateTest.cs:line 41
   at Templates.Test.EmptyWebTemplateTest.EmptyWebTemplateCSharp() in /_/src/ProjectTemplates/test/EmptyWebTemplateTest.cs:line 30
--- End of stack trace from previous location ---
```

</details>

**Comment by javiercn** [comment] 2020-05-08 11:42
@mkArtakMSFT I'm not sure where these tests are coming from. It's not something that we own AFAIK.

@dotnet/aspnet-build might know where the sources for these tests are `Templates.Test.EmptyWebTemplateTest.EmptyWebTemplateCSharp`

I would suggest as a first step we take them out of the automation, since they add no value given that we have CTI runs for these types of things.

**Comment by dougbu** [comment] 2020-05-10 04:09
Why was this issue closed? The problem is in src\ProjectTemplates\test\EmptyWebTemplateTest.cs and that's source code everyone owns.

Do we actually know the `malloc` failure was due to a problem in the SDK? And, if it was an SDK problem, did someone open an issue?

**Comment by mkArtakMSFT** [comment] 2020-05-18 06:08
@javiercn I remember there was a reason for closing this. If I remember correctly it was related to the fact that filing an issue for this will require a repro and getting a repro would be a lot of work, while the assumpiton is that the issue (whatever it was) have been fixed already as the test passed. Did I remember it right?

**Closed** 2020-06-01 18:22 UTC
Labels: area-mvc, test-failure
