### ISSUE TITLE
type or namespace 'App' could not be found

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#49690] opened 2023-07-27 20:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the same issue as [this](https://github.com/dotnet/razor/issues/8674) closed one, though I am working on later versions of VS and .Net.   It is not clear why the previous issue was closed since no fix or fix timeframe were mentioned, though a command line build (which I don't know how to do) apparently gets around the problem.  My app built correctly before I upgraded from VS 17.5.5 and .Net 6.

In particular, I am using VS Community 2022 v17.6.5, .Net SDK 8.0.100-preview.6.23330.14 (x64), and .Net Core 8.0.0 Preview 6 Build preview.6.23329.11 - Shared Framework (x64).  

I upgraded to all of this based on a previous performance [issue I reported](https://github.com/dotnet/runtime/issues/45363) with a Blazor WASM app.  That issue was closed  a couple of days ago with the observation that improvements have been made in .Net 8 that I should try so I can report back what I am seeing.  Unfortunately, I can't get past the 'App' could not be found issue so I can try .Net 8.   This is happening with more than one app.

### Expected Behavior

The apps should Build and Run.

### .NET Version

.Net SDK 8.0.100-preview.6.23330.14 (x64), and .Net Core 8.0.0 Preview 6 Build preview.6.23329.11 - Shared Framework (x64)

**Comment by wtgodbe** [comment] 2023-08-08 18:10
Does this repro after updating to the latest .Net 8 preview/VS release? We just shipped preview7 earlier today

**Comment by CincySteve** [comment] 2023-08-09 19:38
Thanks for reaching out.  Preview 7 fixed the problem.

**Comment by wtgodbe** [comment] 2023-08-09 20:59
Good to hear! Closing this as the issue is resolved

**Closed by wtgodbe** 2023-08-09 20:59 UTC
Labels: area-infrastructure, Needs: Attention :wave:
