### ISSUE TITLE
"Unobserved task exception in sender" in Asp.net core SignalR server

### ISSUE THREAD

**Issue by dannyhaak** [dotnet/aspnetcore#46706] opened 2023-02-16 11:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are not sure whether this is a bug or not, but we are not able to fix it. We get the following in our logs on the server, especially on connection interruptions. This happens quite regularly.

```
Unobserved task exception in sender "System.Threading.Tasks.Task"

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Stream canceled by client.)
 ---> System.Exception: Stream canceled by client.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+MoveNext()
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at HarmonyBackend.Hubs.ReaderDeviceV1Hub.MetricsStream(IAsyncEnumerable`1 stream) in /builds/nedap-harmony/harmony/HarmonyBackend/Hubs/ReaderDeviceV1Hub.cs:line 283
   at HarmonyBackend.Hubs.ReaderDeviceV1Hub.MetricsStream(IAsyncEnumerable`1 stream) in /builds/nedap-harmony/harmony/HarmonyBackend/Hubs/ReaderDeviceV1Hub.cs:line 283
   --- End of inner exception stack trace ---
```

The code that is referred to is:
```
public async Task MetricsStream(IAsyncEnumerable<ReadPointMetrics> stream)
      {
          var readerId = Context.Items["readerId"]?.ToString();
          var log = (ILogger) Context.Items["log"];
          
          if (string.IsNullOrEmpty(readerId))
          {
              log?.Warning("ReaderId is null or empty");
              return;
          }
          
          try
          {
              await foreach (var metrics in stream)
              {
                  try
                  {
                      await readerDeviceHub.StoreMetrics(readerId, metrics);
                  } catch (Exception e)
                  {
                      log?.Error(e, "Error in storing metrics");
                  }
              }
          } catch (OperationCanceledException)
          {
              log?.Information("Metrics stream was cancelled");
          } catch (Exception e)
          {
              if (e.Message == "Stream canceled by client.")
              {
                  log?.Information("Metrics stream was cancelled");    
              } else
              {
                  log?.Warning(e, "Exception in metrics stream");
              }
          }
      }
```

We cannot understand how we can catch those exceptions.

### Expected Behavior

Not have any unobserved task exceptions.

### Steps To Reproduce

We can sometimes reproduce this with local connections that get disrupted.

### .NET Version

7.0.102

**Comment by BrennanConroy** [comment] 2023-02-16 16:42
Looks like a dupe of https://github.com/dotnet/aspnetcore/issues/46169

**Comment by dannyhaak** [comment] 2023-02-17 08:06
Yes, you're right. I did not find this issue on first search. If that's the case, please consider this case closed, and we await dotnet 8.

**Closed** 2023-02-17 15:40 UTC
Labels: area-signalr
