### ISSUE TITLE
Need to have a way to indicate whether a component uses attribute-splatting or not

### ISSUE THREAD

**Issue by mkArtak** [dotnet/aspnetcore#21564] opened 2020-05-07 05:58 UTC
Trying to set a non-existing property on a component doesn't produce a compiler error. Instead, I end up getting an error during runtime (build succeeds).

If we have a way to distinguish between components which use attribute splatting, we can identify situations, where non-existing properties are being set for components, which don't use attribute splatting, which is an obvious error and we can fail the build.

The specific scenario I've felt a need for this is when I updated a NuGet package for a component I'm using to a newer version, and it had breaking changes, where some of the properties got renamed.  My build still passed, but the page failed to load with an error that a specific property doesn't exist. Turned out some properties were renamed.

**Comment by javiercn** [comment] 2020-05-07 10:19
@mkArtak I don't think there's anything we can do in this space. Splatting is a compiler feature and causes the parameters to be passed down to the underlying component. That needs to work with `IComponent` so we can't make this into an error.

**Comment by mkArtak** [comment] 2020-05-07 15:02
Why can't we look up for any parameters with 'CaptureUnmatched=true' at compile time and if it doesn't exist, yet parameters are set which aren't explicitly declared, fail ?

**Comment by javiercn** [comment] 2020-05-07 15:06
> Why can't we look up for any parameters with 'CaptureUnmatched=true' at compile time and if it doesn't exist, yet parameters are set which aren't explicitly declared, fail ?

Because that's a convention that `ComponentBase` has not a convention that `IComponent` has and people can override `SetParametersAsync` to provide whatever behavior they want, so you would be preventing legitimate scenarios from working.

**Comment by mrpmorris** [comment] 2020-05-12 07:48
@javiercn it could be a warning though couldn't it? The largest version of vs gives me all sorts of new warnings.

**Comment by SteveSandersonMS** [comment] 2020-10-13 14:24
One way we could approach this would be having the Razor compiler emit a new attribute if it sees you've *not* got any `CaptureUnmatchedAttributes` parameters:

```cs
[ParameterConvention(ParameterDeclaration.Explicit)]
public class MyComponent : ComponentBase
{
    ...
}
```

This would happen in the first phase of compilation, from which we generate the set of component tag helpers. Then in the second phase of compilation the Razor compiler could throw errors if any `Explicit`-convention component is being passed unrecognized parameters.

Components implemented manually or with `IComponent` wouldn't have this attribute by default and so would retain their existing behaviors.

Since there have been quite a few requests for this, I'm going to tweak the severity rating. Hope that's OK!

**Comment by mkArtakMSFT** [comment] 2021-11-02 18:53
This is a dupe of #37298

**Closed by mkArtakMSFT** 2021-11-02 18:53 UTC
Labels: enhancement, area-blazor, severity-minor, affected-all, feature-blazor-component-model, ss-p1
