### ISSUE TITLE
Error when using custom HTTPS certificate from pem file

### ISSUE THREAD

**Issue by Vake93** [dotnet/aspnetcore#40020] opened 2022-02-06 07:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have configured my application to load a custom HTTPS certificate from a PEM file on disk. The server starts up ok but when I navigate to the URL, it throws the following exception: 
`no credentials are available in the security package`

This is a minimal code to reproduce this issue:
[custom-certificate-https.zip](https://github.com/dotnet/aspnetcore/files/8009641/custom-certificate-https.zip)

However, if I use the same pem file and configure it with appsettings.json it works fine. Also if I export this as a pfx and reimport it works fine as well.

### Expected Behavior

The webserver to use the pem files to server HTTPS connections

### Exceptions (if any)

```
Microsoft.AspNetCore.Server.Kestrel[0]
      Unhandled exception while processing 0HMF9837BOM92.
      System.ComponentModel.Win32Exception (0x8009030E): No credentials are available in the security package
         at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(X509Certificate2 certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
         at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
         at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
         at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
```

### .NET Version

6.0.100

### Anything else?

Operating system: Windows 11  - 22000.469

**Comment by adityamandaleeka** [comment] 2022-02-07 21:41
You'll want to get an X509Certificate2 using this API: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.createfrompemfile?view=net-6.0

and then pass that to Kestrel in [`UseHttps`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.listenoptionshttpsextensions.usehttps?view=aspnetcore-6.0#microsoft-aspnetcore-hosting-listenoptionshttpsextensions-usehttps(microsoft-aspnetcore-server-kestrel-core-listenoptions-system-security-cryptography-x509certificates-x509certificate2))

**Comment by Vake93** [comment] 2022-02-08 02:33
Yes that is the api I'm using. 

'''C#
using System.Security.Cryptography.X509Certificates;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureKestrel(options =>
{
    options.ConfigureHttpsDefaults(httpsOptions =>
    {
        var certPath = Path.Combine(builder.Environment.ContentRootPath, "certificate", "demo-cert.pem");
        var keyPath = Path.Combine(builder.Environment.ContentRootPath, "certificate", "demo-key.pem");

        httpsOptions.ServerCertificate = X509Certificate2.CreateFromPemFile(certPath, keyPath);

        // if the code is changed to the following it works:
        // var buffer = X509Certificate2.CreateFromPemFile(certPath, keyPath).Export(X509ContentType.Pfx, null as string);
        // httpsOptions.ServerCertificate = new X509Certificate2(buffer);
    });
});

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
'''

**Comment by Vake93** [comment] 2022-02-08 03:15
Since you suggested UseHttps extension method I tried that as well still, the same exception is thrown. 

```C#
using System.Security.Cryptography.X509Certificates;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureKestrel(options =>
{
    var certPath = Path.Combine(builder.Environment.ContentRootPath, "certificate", "demo-cert.pem");
    var keyPath = Path.Combine(builder.Environment.ContentRootPath, "certificate", "demo-key.pem");

    options.ConfigureEndpointDefaults(l => l.UseHttps(X509Certificate2.CreateFromPemFile(certPath, keyPath)));
});

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

**Comment by vader1986** [comment] 2022-02-08 10:11
I've got the same issue when I create a pem certificate with separate key file using [mkcert](https://github.com/FiloSottile/mkcert).

**Comment by HaoK** [comment] 2022-02-09 21:50
Here's another blog post basically talking about this exact scenario/error: https://www.scottbrady91.com/c-sharp/pem-loading-in-dotnet-core-and-dotnet and why it fails, there's an issue with ephemeral keysets I guess: https://github.com/dotnet/runtime/issues/45680

Looks like this is worked around by using the configuration loader:

```
{
  "Kestrel": {
    "Endpoints": {
      "HttpsFromPem": {
        "Url": "https://localhost:5001",
        "Certificate": {
          "Path": "../cert.pem",
          "KeyPath": "../ecc.pem"
        }
      }
    }
  }
}
```

**Comment by HaoK** [comment] 2022-02-09 23:44
Closing this issue since this is external to us https://github.com/dotnet/runtime/issues/23749 is the root cause

**Closed by HaoK** 2022-02-09 23:44 UTC
Labels: External, area-runtime, :heavy_check_mark: Resolution: Answered, Status: Resolved
