### ISSUE TITLE
SignalR Message Pack Client Library not running in browser when using Angular Cli

### ISSUE THREAD

**Issue by QuinntyneBrown** [dotnet/aspnetcore#9687] opened 2019-04-23 17:28 UTC
After importing MessagePackHubProtocol from @aspnet/signalr-protocol-msgpack inside of an Angular app using the Angular cli, the application will no longer run in the browser.

You will see the following exception in the console.

![image](https://user-images.githubusercontent.com/1749159/56602015-8757fb00-65ca-11e9-97a6-14e22f7ab75d.png)

### Steps to reproduce the behavior:

Clone and run the following app:
https://github.com/QuinntyneBrown/ng-signalr-protocol-msgpack-issue

or 

1. Create an angular app using the angular cli
2. npm install @aspnet/signalr and @aspnet/signalr-protocol-msgpack
3. In the app component, import HubConnectionBuilder from @aspnet/signalr
4. In the app component, import MessagePackHubProtocolfrom @aspnet/signalr-protocol-msgpack
5. In the app component, add a method called ngOnInit
6. Inside the ngOnInit method, add the following code

    var connection = new HubConnectionBuilder()
    .withUrl("")
    .withHubProtocol(new MessagePackHubProtocol())
    .build();
  
7. run the app with the console open, and you should see the error. The UI will be blank.

### Expected behavior
You should see the standard angular cli default page.

**Comment by QuinntyneBrown** [comment] 2019-04-24 11:14
I created the following duplicate issue with angular-cli.

https://github.com/angular/angular-cli/issues/14253#event-2296275783

I was asked to look at the following comment. https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Comment by BrennanConroy** [comment] 2019-04-24 15:35
Take a look at https://github.com/aspnet/SignalR/issues/2736#issuecomment-411144971 for a workaround.

@**triage** we can investigate using a newer `Buffer` package that doesn't rely on global being defined.

**Comment by DAllanCarr** [comment] 2019-04-24 22:57
Angular broke this intentionally.

**Comment by mhosman** [comment] 2019-04-29 21:05
Same error here!!!

**Comment by anurse** [comment] 2019-04-30 21:06
We'll look and see if there's a good option here. We might end up dropping polyfills for some of these altogether so that each environment can bring an appropriate polyfill.

**Comment by anurse** [comment] 2019-05-30 22:47
We aren't going to be able to get to this in 3.0. Moving to the backlog.

**Comment by mhosman** [comment] 2019-05-31 14:50
So... You're gonna release a version that is not working with Angular?

**Comment by anurse** [comment] 2019-05-31 16:21
Is the linked workaround insufficient for you? If so we can bump the priority of this.

**Comment by mhosman** [comment] 2019-05-31 18:55
Sorry, @anurse I didn't see that workaround!

**Comment by cyraid** [comment] 2019-12-20 18:18
The workaround worked for me after I added the package "buffer" to package.json.

**Comment by davidfowl** [comment] 2021-04-06 08:17
Does this repro with the latest changes? @BrennanConroy  We changed the msg pack library so I wonder if the same issue exists.

**Comment by BrennanConroy** [comment] 2021-04-06 16:47
This might be fixed, I'll try it out and see if the issue is gone.

**Comment by BrennanConroy** [comment] 2021-07-30 18:17
Doesn't look like the issue repros with the new messagepack library.

**Closed by BrennanConroy** 2021-07-30 18:17 UTC
Labels: affected-few, area-signalr, bug, severity-minor
