### ISSUE TITLE
Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

### ISSUE THREAD

**Issue by vinguan** [dotnet/aspnetcore#30743] opened 2021-03-08 16:12 UTC
A simple dotnet restore fails in my **Docker** build and in my local machine with the following error :  **Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json**

### To Reproduce

Run `dotnet restore` on terminal and see the following error : 

```
$ dotnet restore
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [C:\GitClones\Aiko\trackit-server\src\Aiko.TrackIt.Server\Aiko.TrackIt.Server.csproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [C:\GitClones\Aiko\trackit-server\src\Aiko.TrackIt.Server\Aiko.TrackIt.Server.csproj]
C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [C:\GitClones\Aiko\trackit-server\src\Aiko.TrackIt.Server\Aiko.TrackIt.Server.csproj]
```
### Further technical details
``` 
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by blowdart** [comment] 2021-03-08 17:53
Dupe of https://github.com/dotnet/runtime/issues/49277 - we haven't used that feed URL in quite a while, so you must have it added somewhere manually in your project.

(and not an asp.net issue, so closing)

**Closed by blowdart** 2021-03-08 17:53 UTC
Labels: area-infrastructure
