### ISSUE TITLE
The Angular CLI process did not start listening for requests within the timeout period of 0 seconds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22883] opened 2020-06-12 17:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1069299/the-angular-cli-process-did-not-start-listening-fo-1.html)._

---
<p>When upgrading our Angular 8 project to Angular 9 this became an issue. Before the upgrade the project was running just fine.</p> <p>Visual Studio Enterprise 2019 Version 16.5.5 (Windows 10 - 1903)</p><p>.NET Core 3.1</p><p>Angular 9.1.9</p><p>It seems to be an issue that is active for some months now, but all the solutions seems to be a workaround and not an actual fix:</p><p>https://github.com/angular/angular-cli/issues/16961</p><p>https://stackoverflow.com/questions/55406292/timeoutexception-the-angular-cli-process-did-not-start-listening-for-requests-w</p><p>We've tried to edit the package.json and updated &quot;start&quot;: &quot;ng serve&quot;, to &quot;start&quot;: &quot;ng serve --host 0.0.0.0&quot;,</p><p>This seems to fix the issue if you're using 'Start without Debugging', but when you use 'Start Debugging' it fails again.</p>

---
#### Visual Studio Feedback System on 6/9/2020, 03:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2020-06-12 17:45
Potentially related to https://github.com/dotnet/aspnetcore/issues/17277 and https://github.com/dotnet/aspnetcore/issues/18820

**Comment by mkArtakMSFT** [comment] 2020-06-15 18:30
This is a dupe of https://github.com/dotnet/aspnetcore/issues/18062

**Closed by mkArtakMSFT** 2020-06-15 18:30 UTC
Labels: Author: Migration Bot :robot:, area-mvc, feature-spa

**Comment by Knordy** [comment] 2020-06-16 12:01
The edit in #17277 ("start": "echo hello && ng serve",) seems to be a valid workaround for now. Will monitor it and reply if it fails again.

We are using `UseAngularCliServer` and not `UseProxyToSpaDevelopmentServer` as #18062 is suggesting, but could have potentialy similar underlying issues.

Still hope this gets fixed.

**Comment by Knordy** [comment] 2020-06-16 14:06
Unfortunately `start": "echo hello && ng serve` isn't a stable workaround. It still produces the mentioned error.

**Comment by Knordy** [comment] 2020-06-19 08:24
So I've tried several things now, as what is indicated in #18820
- removing aspnet-prerendering, as it seems to be deprecated (#12890)
- Updating `Microsoft.AspNetCore.SpaServices.Extensions` to 3.1.5
- using `echo Starting... && ng serve --host 0.0.0.0`

All fails when using Start Debugging in Visual Studio. So the only possible fix is the suggested fix in the `AngularCliMiddleWare` as suggested in #18062?
