### ISSUE TITLE
@page directive: allow string constant

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#23958] opened 2020-07-15 15:32 UTC
I know this was brought up in #15977, but since that was closed/locked I want to add another voice in favor of this feature.  

We use constants for our page routes which give us better visibility into references to each route.  For our controllers, we can already use these constants in the `RouteAttribute` and it would be great if we could likewise use them when specifying the `@page` directive.

Perhaps I can at least mess with the Razor tooling and see if I can wrap my head around a way to do this.  I can use this issue to track it.  No promises as I'm not familiar with the tooling and I'm sure it's quite complicated.

**Comment by captainsafia** [comment] 2020-07-21 17:01
Thank you for your feedback. We're closing this issue as the behavior discussed is by design.

**Closed** 2020-07-21 17:01 UTC
Labels: area-mvc
