### ISSUE TITLE
ASP.NET Core assemblies should participate in member-level trimming

### ISSUE THREAD

**Issue by mthalman** [dotnet/aspnetcore#29508] opened 2021-01-21 21:54 UTC
When using the [`TrimMode=Link`](https://docs.microsoft.com/dotnet/core/deploying/trimming-options#trimming-granularity) publish option, none of the ASP.NET Core assemblies are affected.  They all remain at their full size even if members within those assemblies are never accessed by a code path in the application.

Because of the quantity and size of the ASP.NET Core assemblies, there is a big opportunity to reduce the size of a deployed app if these assemblies participated in member-level trimming.

As an example, this [sample ASP.NET Core application](https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp) has the following trimmed container image sizes on Alpine Linux:

| TrimMode | Size |
| - | - |
| &lt;Default&gt; | 98.5 MB |
| Link | 80 MB |

If the ASP.NET Core assemblies participated in assembly-level trimming, this reduction would be even greater.

Repro steps:
1. `git clone https://github.com/dotnet/dotnet-docker.git`
2. `cd dotnet-docker/samples/aspnetapp`
3. `docker build -t default-trimming -f Dockerfile.alpine-x64-slim .`
4. Modify `Dockerfile.alpine-x64-slim` to include `/p:TrimMode=Link` in the `dotnet publish` call
5. `docker build -t link-trimming -f Dockerfile.alpine-x64-slim .`
6. `docker inspect --format "{{ .Size }}" default-trimming`
7. `docker inspect --format "{{ .Size }}" link-trimming`

**Comment by mthalman** [comment] 2021-01-21 21:54
cc @davidfowl, @eerhardt

**Comment by eerhardt** [comment] 2021-01-21 21:59
Duplicate of #27384?

**Comment by davidfowl** [comment] 2021-01-21 21:59
Yes

**Closed by davidfowl** 2021-01-21 21:59 UTC
