### ISSUE TITLE
Error using Microsoft.Extensions.Caching.StackExchangeRedis 6.0.0

### ISSUE THREAD

**Issue by davitgr** [dotnet/aspnetcore#38606] opened 2021-11-23 20:56 UTC
After upgrading from .NET 5 to .NET 6, we are unable to write to the Redis cache using IDistributedCache.SetAsync in our WebAoi project. It works in in .NET 5 but not .NET 6. Below is the error message and also the code (`_cache` is `IDistributedCache`). Please advise, as this is breaking our application currently.

```
    private async Task CacheSet(string key, object value, TimeSpan? expiration = null)
    {
        await _cache.SetAsync(key, value.ToByteArray(),
            new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = expiration ?? _cacheExpiration
            }).ConfigureAwait(false);
    }
```

> 2021-11-23 15:20:32.7672||ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request. ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script 
> 2021-11-23 15:20:32.7750||ERROR|LoggerService.LoggerManager|Something went wrong:    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)

**Comment by Tratcher** [comment] 2021-11-23 23:34
Duplicate of https://github.com/dotnet/aspnetcore/issues/38254. This is caused by using an outdated/unsupported version of redis.

**Comment by davitgr** [comment] 2021-11-24 00:04
Thank you. I've been using a custom version for windows because that's all
we could find. Do you have any recommendations for what to use on a windows
machine?

**Comment by Tratcher** [comment] 2021-11-24 00:12
Hmm, I haven't tried that in a long time. Have you tried WSL? https://redis.com/blog/redis-on-windows-10/

**Comment by davitgr** [comment] 2021-11-24 02:19
That worked. Thank you so much. Didn't even cross my mind to use redis with
WSL

**Closed** 2021-11-25 04:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Status: Resolved, feature-caching
