### ISSUE TITLE
Blazor Webassembly: Unable to supress URL rewriting

### ISSUE THREAD

**Issue by xanth** [dotnet/aspnetcore#38251] opened 2021-11-10 10:39 UTC
### Is your feature request related to a problem? Please describe.
I need navigation but sadly the URL must not be modified and as far as I can see there is no hook to disable this functionality.

### Describe the solution you'd like
I'd like the ability to disable url rewriting.

**Comment by javiercn** [comment] 2021-11-10 10:51
@xanth thanks for contacting us.

Are you asking for hash based routing?

**Comment by javiercn** [comment] 2021-11-10 10:54
This issue is a dupe of https://github.com/dotnet/aspnetcore/issues/6175

**Closed** 2021-11-10 10:54 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved

**Comment by xanth** [comment] 2021-11-10 11:48
@javiercn no I want entirely virtual routing stored in some internal state object.

**Comment by xanth** [comment] 2021-11-10 11:51
Totally open to alternative/elegant solutions but at the moment the best solution I can see is embedding it in an iframe as a means of cordoning the real URL off.

**Comment by javiercn** [comment] 2021-11-10 11:52
@xanth thanks for the additional details. 

That's not something we have plans to support.

**Comment by xanth** [comment] 2021-11-10 11:53
@javiercn how would one nest a Blazor app besides some other app without conflicting with the other apps routing?

**Comment by javiercn** [comment] 2021-11-10 12:54
@xanth you wouldn't use our routing system for that.

Our routing system requires a piece of observable state in the URL, and that's a core feature of the system, so its not something we plan to change.

If you want to have a widget that can be in multiple states, then you can track that yourself, within local storage, a cookie or whatever solution you see fit.

**Comment by xanth** [comment] 2021-11-10 13:00
Wouldn't it be better if the routing subsystem was plugable in such a way that the URL sourcing and syncing was configurable?
