### ISSUE TITLE
Debug blazor in vscode prompted "cannot launch browser: The URL's protocol must be one of "ws","wss:, or "ws+nuix;""" 

### ISSUE THREAD

**Issue by LZD121** [dotnet/aspnetcore#45257] opened 2022-11-24 06:28 UTC
My launch.json:
![image](https://user-images.githubusercontent.com/59716053/203710364-b0d08b3a-760a-4f63-854b-158f1807a694.png)

The chrome is opened, but displays blank page.

**Comment by javiercn** [comment] 2022-11-24 13:38
@LZD121 thanks for contacting us.

@TanayParikh can you take a look at this?

**Comment by j0t4pe** [comment] 2022-11-24 23:38
I have the same problem since time ago. I assumed it was a local problem. In VS2022 everything works fine. In VSCODE the debug does not work well. I had the problem with .NET6, I upgraded to .NET7 and the problem is still the same.

With edge there is no difference.

While I wait for a solution I debug with the chrome developer tools. It more or less meets my needs, at moment.
Workarround steps in windows command line:
dotnet run
"_chrome-path_\chrome.exe" --remote-debugging-port=9222 --user-data-dir="_user-data-path_\AppData\Local\Temp\blazor-chrome-debug" _scheme_://localhost:_port_/
And now in chrome: **shift+alt+D**. Then debug blazor in **file://**

Thanks @LZD121 !

**Comment by TanayParikh** [comment] 2022-12-01 23:10
You'll need to add the `inspectUri` property. Please see the documentation [here](https://learn.microsoft.com/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio#debug-a-standalone-blazor-webassembly-app) for more information. 

Marking this as resolved. Please let us know if you're still experiencing this issue after following the guidance in the documentation above.

**Comment by j0t4pe** [comment] 2022-12-02 01:40
Hi, @TanayParikh thanks. I have followed all the steps of the documentation but it does not solve the problem.

I do the tests by creating a clean project.

![image](https://user-images.githubusercontent.com/86976958/205195217-470d04dc-9914-4ab2-b7ae-f9b6998ebd62.png)

**Comment by j0t4pe** [comment] 2022-12-02 02:15
More info,

With Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension v1.1.0 and v1.0.1 the same error happens.

But, with Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension v1.0.0 apparently it launches the browser fine, and the proxy debug connects. 
I only comment this in case it helps you, since version 1.0.0 fails for other reasons.

**Comment by TanayParikh** [comment] 2022-12-02 06:26
cc/ @thaystg in case you have context on this issue

**Comment by thaystg** [comment] 2022-12-02 12:16
Yes, this is fixed in this PR: https://github.com/dotnet/razor/pull/7929

**Comment by j0t4pe** [comment] 2022-12-02 12:26
Thanks @thaystg

**Closed** 2022-12-03 19:00 UTC
Labels: External, area-blazor, blazor-wasm, :heavy_check_mark: Resolution: Answered, Status: Resolved, feature-blazor-debugging

**Comment by Ruoruni** [comment] 2022-12-19 01:01
I don't believe this issue is resolved because I am experiencing it now in VSCode using the blazorwasm template with no modifications. I get the same "Unable to launch browser" issue.

**Comment by TanayParikh** [comment] 2022-12-19 05:43
The issue has been resolved via the PR mentioned above. The code hasn't yet shipped so you'll still be seeing the older behavior.

**Comment by gbelenky** [comment] 2022-12-22 15:26
I have the same issue. 

- I start Edge in the debugger - no page is loaded
- I provide manually the url of my project
- Blazor wasm app loads
- After a short time the Edge in debugger stops working and quits.

When will be the fix released?
