### ISSUE TITLE
Blazor WASM Redirect after Auth

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#32580] opened 2021-05-11 14:58 UTC
During the authentication this url is called:

https://localhost:5006/admin/authentication/login?returnUrl=https%3A%2F%2Flocalhost%3A5006%2Fadmin

The application Hangs on checking Login state

and I get this error:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Invalid return url. The return url needs to have the same origin as the current page.
System.InvalidOperationException: Invalid return url. The return url needs to have the same origin as the current page.
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetReturnUrl(RemoteAuthenticationState state, String defaultReturnUrl)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<OnParametersSetAsync>d__82[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by JulienM28** [comment] 2021-05-12 07:37
It will be complicated to share the projects.

The auhentication is our SSO based on Identity Server 4. The configuration is ok, ID Server doesn't report any error.

The SSO URL is www.foo.com et application url is www.foo.com/admin

Both are independant applications runing on Kestrel, no IIS

**Comment by JulienM28** [comment] 2021-05-12 10:06
I found something interesting:

I I call https://localhost:5006/admin it doesn't work but https://localhost:5006/admin/ does.

The error is still here but I'm correctly redirected to te SSO

**Comment by captainsafia** [comment] 2021-05-18 00:18
@JulienM28 Ah -- it looks like you might be running into a dupe of https://github.com/dotnet/aspnetcore/issues/24316.

I'll close this issue in favor of that one but you can give the other issue a thumbs up and post your repro to help us with prioritization!

**Closed by captainsafia** 2021-05-18 00:18 UTC
Labels: area-blazor, question
