### ISSUE TITLE
Preview version 3 is not compatible with the path of special characters. The project cannot run

### ISSUE THREAD

**Issue by sln162** [dotnet/aspnetcore#31643] opened 2021-04-09 17:46 UTC
We have updated to preview version 3, but the project cannot be run and an error is reported:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
```

After testing, it was found that the problem was that the project’s upper-level folder had special characters and could not run, but the generation was no problem, and it could also be packaged, but the deployment was also unable to run in the past.

These characters include:【】、丶°   

In other words, when your directory is D:\【abd丶】\project, then this project will not run.

**Comment by sln162** [comment] 2021-04-09 17:47
<img width="1169" alt="1617990437" src="https://user-images.githubusercontent.com/11196986/114220543-b70e9200-999e-11eb-8748-4edc7fcc6434.png">

**Comment by captainsafia** [comment] 2021-04-09 18:01
@sln162 It looks like you're running into a dupe of https://github.com/dotnet/aspnetcore/issues/28794.

We'll be addressing this in preview4.

**Closed by captainsafia** 2021-04-09 18:01 UTC
Labels: area-mvc

**Comment by sln162** [comment] 2021-04-10 01:50
It should be noted that we started from. Net core 3 Preview 1, and every time we updated with the preview version, the folder always contained special characters, but we encountered this problem for the first time in two years.
