### ISSUE TITLE
Better error for "Attempting to return wrong pooled instance"

### ISSUE THREAD

**Issue by uecasm** [dotnet/aspnetcore#42433] opened 2022-06-27 02:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I was not the original author of that issue, but this is perhaps a reproduction for #30020.

1. Clone https://github.com/uecasm/TreeTest
2. Open the dev tools console
3. Click the Refresh Tree button once
4. Observe that a tree populates above just fine
5. Click the Refresh Tree button again
6. Observe that the tree appears "correctly" but an unhandled console error is logged:
   ```
   Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Attempting to return wrong pooled instance. Get/Return calls must form a stack.
   ```

### Describe the solution you'd like

The "wrong pooled instance" issue is ultimately due to a bug in the code relating to the `@key` -- on the second click it is adding duplicate copies of the same node (and thus duplicate `@key` values).  But the error message is not helpful in discovering this error.

Interestingly, if the duplication occurs at the top level (or in a flat list rather than a recursive tree) then it does report an error about duplicate key values as expected; it's something specific to the use of a tree (or perhaps `RenderFragment`s) that causes this other error, despite this duplication only actually occurring at a single level of the tree.

Also interestingly, with the `@key` present it will only render the children once (as expected if the duplication didn't exist, which further conceals the mistake).  Removing the `@key` from the markup reveals the duplicate child nodes, which is what led to discovery of the actual user bug.

### Additional context

An additional oddity in this example is that the Razor compiler appears to be unable to infer the `TNode` type, despite that it ought to be able to (given how it can infer generic types for form components, etc).  Removing the `TNode="Node"` parameter results in generating code that does not compile:

```
TreeTest\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Index_razor.g.cs(265,29,265,34): error CS0449: The 'class', 'struct', 'unmanaged', 'notnull', and 'default' constraints cannot be combined or duplicated, and must be specified first in the constraints list.
```

(As a side note, when there is a compiler error like this, the source generator output is not visible under Analyzers in VS as usual, which makes it annoying to find the actual problem.  But I used a different method and found that it was generating the constraint as `where TNode : , class`, which is obviously incorrect and different from the component's `@typeparam`.  When the type is specified explicitly it doesn't generate this "TypeInference" block at all.)

**Comment by javiercn** [comment] 2022-06-27 10:52
@uecasm thanks for contacting us.

A couple of notes:
The compiler error was fixed in .NET 7.0.

The error with @key is something that I’m not sure we can improve without incurring in additional runtime cost, which we are unlikely to do.

In general, keys are required to be unique by design and the behavior when keys are duplicated is undefined.

we try our best to produce an reasonable error, but in the end we don’t want to tax the happy path with additional validation.

**Closed** 2022-06-28 13:01 UTC
Labels: question, area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved, feature-rendering
