### ISSUE TITLE
Windows Service does not take settings from appsettings.json

### ISSUE THREAD

**Issue by JasonDWilson** [dotnet/aspnetcore#38870] opened 2021-12-07 18:09 UTC
I followed the pattern established in the article: https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service.

If I run my service from the command line it runs great, but if I run it as service it doesn’t seem to see the settings in appsettings.json. Would love some direction on this as there are several thing in the config that I don’t want to have to hard code.

Example of my my program.cs
``` csharp
var context = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("hosting.json", optional: true)
    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
    .AddJsonFile("appsettings.Development.json", optional: true, reloadOnChange: true)
    .AddCommandLine(args)
    .AddEnvironmentVariables()
    .Build();

var key = context[Constants.CONFIG_KEY_APPLICATION_INSIGHTS];

IHost host = Host.CreateDefaultBuilder(args)
    .UseWindowsService(options => options.ServiceName = Constants.SERVICE_NAME)
    .ConfigureWebHostDefaults(
        webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
            webBuilder.UseUrls(context[Constants.CONFIG_KEY_HUB_URL]);
        })
    .ConfigureServices(
        services =>
        {
            services.AddSignalR();
            services.AddHostedService<LprWindowsService>();

            services
        .AddDbContext<FlashvaletContext>(
            optionsBuilder => optionsBuilder.UseSqlServer(
                    Constants.FLASHVALET_CONNECTIONSTRING,
                    sqlOptions =>
                    {
                        sqlOptions.CommandTimeout(120);
                        sqlOptions.EnableRetryOnFailure();
                    }),
            ServiceLifetime.Singleton);

            services.AddSingleton<IFileSystemService, FileSystemService>();
            services.AddSingleton<IGenericRepository, FlashValetRepository>();
            services.AddSingleton<IKioskService, KioskService>();
            services.AddSingleton<ILprStrategyFactory, LprStrategyFactory>();
            services.AddSingleton<IVerificationService, VerificationService>();
        })
    .ConfigureLogging(
        logging =>
        {
            logging.ClearProviders();
            logging.AddConfiguration(context.GetSection("Logging"));
            logging.AddConsole();
            //var key = context[Constants.CONFIG_KEY_APPLICATION_INSIGHTS];
            if(string.IsNullOrEmpty(key) == false)
                logging.AddApplicationInsights(key);

            if (EventLog.SourceExists(Constants.SERVICE_NAME) == false)
                EventLog.CreateEventSource(Constants.SERVICE_NAME, Constants.SERVICE_NAME);

            EventLogSettings eventLogSettings = new EventLogSettings
            {
                SourceName = Constants.SERVICE_NAME,
                LogName = Constants.SERVICE_NAME
            };

            logging.AddConsole();
            logging.AddDebug();
            logging.AddEventLog(eventLogSettings);
        })
    .Build();

await host.RunAsync();
```

**Comment by MariovanZeist** [comment] 2021-12-07 18:23
@JasonDWilson when you run this as a service the ```Directory.GetCurrentDirectory()``` will probably return something like `` 'C:\Windows\System32\'``  and not the location of your service. So it will not find your configuration files

**Comment by JasonDWilson** [comment] 2021-12-07 19:18
> @JasonDWilson when you run this as a service the `Directory.GetCurrentDirectory()` will probably return something like ` 'C:\Windows\System32\'` and not the location of your service. So it will not find your configuration files

You are absolutely right.  What's the best way to get the executable directory in a windows service?

**Comment by JasonDWilson** [comment] 2021-12-07 19:38
I tried AppDomain.CurrentDomain.BaseDirectory, but resolved to a temp directory C:\Windows\TEMP\.net\FlashParcs.LprService\KjczqXHLAT4R5e+bxTHIRZ62tKLFiLQ=\appsettings.json

I also tried 
Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location), but it resolved to a temp directory.

**Comment by MariovanZeist** [comment] 2021-12-07 19:44
You can use ```AppContext.BaseDirectory```

**Comment by JasonDWilson** [comment] 2021-12-07 19:51
AppContext.BaseDirectory resolved to C:\Windows\TEMP\.net\FlashParcs.LprService\6CkioS3rxdpUDGw7xfqmmjZqR_w38wA=\

**Comment by JasonDWilson** [comment] 2021-12-07 20:42
This ended up working for me:

``` csharp
        var path = Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName);
        Directory.SetCurrentDirectory(path);
```

**Comment by adityamandaleeka** [comment] 2021-12-08 21:18
Closing since this is by design.

**Closed by adityamandaleeka** 2021-12-08 21:18 UTC
Labels: :heavy_check_mark: Resolution: By Design, area-runtime

**Comment by JasonDWilson** [comment] 2021-12-08 21:58
@davidfowl  - @IEvangelist indicated my workaround might not be a good idea -- is there a better way to provide settings through appsettings.json (I realize that Environment variables offer a viable alternative).

**Comment by davidfowl** [comment] 2021-12-09 07:44
> AppContext.BaseDirectory resolved to C:\Windows\TEMP.net\FlashParcs.LprService\6CkioS3rxdpUDGw7xfqmmjZqR_w38wA=\

@JasonDWilson what version of .NET are you running and are you doing self contained deployments that are compressed?

**Comment by JasonDWilson** [comment] 2021-12-09 16:51
@davidfowl >net 6 Microsoft Visual Studio Professional 2022 (64-bit)

**Comment by davidfowl** [comment] 2021-12-09 17:52
The other question is relevant as well.

**Comment by JasonDWilson** [comment] 2021-12-09 20:44
Sorry -- yes its published as self contained.
