### ISSUE TITLE
Owner is null (`Owner should never be null` Debug.Fail keeps occurring)

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#24781] opened 2020-08-11 06:26 UTC
The `Owner should never be null` keeps occurring. This issue is to investigate why & resolve appropriately.

Tried taking a look into it, however not able to get a repro at the moment (neither Windows nor MacOS).

cc/ @ajaybhargavb

**Comment by NTaylorMullen** [comment] 2020-09-01 21:13
Time box to 1 day of playing around with bits.

**Comment by NTaylorMullen** [comment] 2020-09-22 18:40
Closing out since we haven't seen this in a while.

**Comment by ryanbrandenburg** [comment] 2020-10-22 00:24
![image](https://user-images.githubusercontent.com/14987221/96803860-4230a700-13c2-11eb-8e5f-59210ec38e46.png)
Hate to be the downer. Happened exactly when I hit the '='.

**Comment by ryanbrandenburg** [comment] 2021-01-05 22:13
This doesn't seem to reproduce anymore, has anyone else seen it since then?

**Comment by TanayParikh** [comment] 2021-01-05 22:15
Nope.

**Closed** 2021-01-06 19:46 UTC
Labels: area-razor.tooling, bug
