### ISSUE TITLE
InvalidOperationException on POST of form with large data

### ISSUE THREAD

**Issue by bronthulke** [dotnet/aspnetcore#38462] opened 2021-11-17 03:06 UTC
In a .NET 5 MVC application, I am consistently able to reproduce an error where the POST of a form that includes data from an uploaded image is throwing an error:

InvalidOperationException: The examined position cannot be less than the previously examined position.

The situation I have is that a user uses a file upload component to select an image, and then before submitting the form I set a hidden field value to contain the data (base64) of that image.  The issue ONLY seems to occur when the data for that image gets beyond a certain size.  That size seems to be around 2MB.

This same functionality has worked in the past in .NET Framework.

Here is the full stack:

```
InvalidOperationException: The examined position cannot be less than the previously examined position.
System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_InvalidExaminedPosition()
System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, int consumedIndex, BufferSegment examinedSegment, int examinedIndex)
System.IO.Pipelines.Pipe.AdvanceReader(ref SequencePosition consumed, ref SequencePosition examined)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.AdvanceTo(SequencePosition consumed, SequencePosition examined)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.AdvanceTo(SequencePosition consumed)
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.AdvanceTo(SequencePosition consumed)
Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I can see previous discussions about this here https://github.com/dotnet/runtime/issues/37176 and https://github.com/dotnet/aspnetcore/issues/19476 but they didn't contain any solutions that I could see for my case.  One person did say they thought it may have been related to content request size, but in their case they decided that wasn't the cause.

The reason I feel at the moment like it's related to content size is that I can successfully submit a form with the exact same image but just a reduced size.  It seems anything above around 2MB gets this error, but around 1.5MB works.

### To Reproduce
Here is a github repo that you can use to reproduce the issue.  If you select the file "large-file.jpg" from the base directory, it should throw the error.  The small-file.jpg will not have the issue.

https://github.com/bronthulke/ReproducingFileUploadIssue

I've also noted that this issue only occurs when running the site using `dotnet run` (I can't recall what that web host is called?) -- when running in IIS Express it works.

The "fileinput" javascript library is being used to select the file, turn it into a preview, and then the actual image data is pulled out from that and stored in the 

### Exceptions (if any)
InvalidOperationException: The examined position cannot be less than the previously examined position.

### Further technical details
- ASP.NET Core version: .NET 5
- VS 2022

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.300 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
</details>

**Comment by Vake93** [comment] 2021-11-17 03:58
This is because the ValueLengthLimit is been exceeded when you upload the larger file. One way around this is to add the following to increase the limits in your ConfigureServices method.

```C#
services.Configure<FormOptions>(options =>
 {
    options.ValueLengthLimit = int.MaxValue;
 });
```

But I think it's better if you convert this into an IFormFile and upload it using a stream.

**Comment by davidfowl** [comment] 2021-11-17 04:41
That error message looks suspicious. Can you reproduce that error on demand.

cc @halter73 @adityamandaleeka @Tratcher

**Comment by bronthulke** [comment] 2021-11-17 04:51
> That error message looks suspicious. Can you reproduce that error on demand.
> 
> cc @halter73 @adityamandaleeka @Tratcher

Yes it happens every time I do a POST with this content.

The change suggested by @Vake93 does resolve it, so it sounds like it is definitely being caused by the limit on the length.

I guess it could just be helpful if the errors that is thrown gives better explanation of why it is happening.

**Comment by Vake93** [comment] 2021-11-17 05:00
@davidfowl This is the error that is thrown. 

![image](https://user-images.githubusercontent.com/8337494/142137701-70437c16-ed92-4a73-b3bd-28ccd00c20a6.png)

**Comment by davidfowl** [comment] 2021-11-17 05:01
Where did this come from?

```
InvalidOperationException: The examined position cannot be less than the previously examined position.
```

**Comment by Vake93** [comment] 2021-11-17 05:06
Ok, I think what happens is when the validation throws the following:
![image](https://user-images.githubusercontent.com/8337494/142138226-24cd54c1-c91d-43da-b823-e25f7240d9bc.png)

but still, the request processing continues, then it throws the above error.
![image](https://user-images.githubusercontent.com/8337494/142138138-b49212f1-d229-49d0-808a-8787709e50b6.png)

**Comment by bronthulke** [comment] 2021-11-17 05:36
I see, so a more useful error is tucked away, but by the time it gets thrown up to the browser, it has that pipeline error.

I had tried to get it to break on the error in VS, but hadn't been able to - I assume it's occurring before it gets to my code, and I mustn't have the right exception "break when thrown" settings.

**Comment by Vake93** [comment] 2021-11-17 06:35
> I see, so a more useful error is tucked away, but by the time it gets thrown up to the browser, it has that pipeline error.

yeah.

**Comment by Tratcher** [comment] 2021-11-17 15:35
Looks like a duplicate of https://github.com/dotnet/aspnetcore/issues/27585 which has already been fixed in 6.0. Can you try this on 6.0?

**Comment by bronthulke** [comment] 2021-11-18 01:08
> Looks like a duplicate of #27585 which has already been fixed in 6.0. Can you try this on 6.0?

Indeed it does work in .NET 6!  Wonderful, and the amazing power of all this is that I can literally just change my target framework in my .csproj file, and with a rebuild it all works. 

So I will upgrade to .NET 6 now on my other app (I was lagging behind a bit). 

Thank you to all involved in this resolution!

**Comment by bronthulke** [comment] 2021-11-18 01:44
Actually, the update to .NET 6.0 in my sample repo did fix it in there, but in my main app, I now get a 400 error. Once again, having that change to the FormOptions ValueLengthLimit fixes it.

If I debug the app I see nothing, no exception gets caught.

Is there anything I can do to help troubleshoot the issue there?

**Comment by davidfowl** [comment] 2021-11-18 05:21
The 400 I believe is the right behavior to expect as MVC converts the exception into a 400 (bad request) response.

**Comment by Tratcher** [comment] 2021-11-18 05:51
If you enable debug logging you should see the form length issue reported.

**Comment by bronthulke** [comment] 2021-11-18 23:24
> If you enable debug logging you should see the form length issue reported.

OK so I THOUGHT I had debug logging is enabled, as I was seeing debug type output in my terminal where I'm running `dotnet watch run`, including output from `_logger.LogDebug()`.  However, then I checked in my `appSettings.json` (and actually my `appSettings.Development.json` override file) and found that "Microsoft" was only set to "Warning".  When I changed that to "Debug" I started seeing a plethora of helpful information (including routes debug info! Woot!).  This then included the actual cause of this 400 error (Form value length limit 4194304 exceeded) - WONDERFUL! Thank you @Tratcher for that hot tip (I just had to hunt around to find where to set it).

@davidfowl @pranavkm So it seems that with the right level of debugging turned on, you CAN find out what the cause is, and now in .NET 6 it returns a nice 400 error rather than that InvalidOperationException exception, and for me the solution of setting the ValueLengthLimit does resolve the underlying issue.  So I'm happy with that. Thank you!

**Closed** 2021-11-20 01:00 UTC
Labels: area-runtime, :heavy_check_mark: Resolution: Answered, Status: Resolved
