### ISSUE TITLE
OmniSharp Razor Extension in VS Code is reporting System.IO.DirectoryNotFoundException 

### ISSUE THREAD

**Issue by RonaldGHempel** [dotnet/aspnetcore#24117] opened 2020-07-20 16:59 UTC
I am using OmniSharp Version 1.22.1 in Visual Studio Code Version 1.47.2.

After restructuring one of my projects in VS Code I can see some exceptions like this one:
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'xxx\Components\PflegeLeerstellen\PflegeLeerstellen.razor'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.AspNetCore.Razor.LanguageServer.Common.DefaultRemoteTextLoaderFactory.RemoteTextLoader.LoadTextAndVersionAsync(Workspace workspace, DocumentId documentId, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs:line 82
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultProjectSnapshotManager.<>c__DisplayClass17_0.<DocumentAdded>b__0() in /_/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs:line 152
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.GetTextVersionAsync() in /_/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs:line 131
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(DefaultProjectSnapshot project, DocumentSnapshot document) in /_/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs:line 352
   at Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync() in /_/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultDocumentSnapshot.cs:line 63
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.PublishDiagnosticsAsync(DocumentSnapshot document) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 161
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorDiagnosticsPublisher.WorkTimer_Tick(Object state) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs:line 204
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

The mentioned directory does not exist anymore but existed in a previous version of this project. It looks to me like the extension is using some stale information at this point thus generating the exception.

**Comment by NTaylorMullen** [comment] 2020-07-20 17:15
O# original issue: https://github.com/OmniSharp/omnisharp-vscode/issues/3825#issuecomment-661191762

**Comment by TanayParikh** [comment] 2020-07-20 20:37
I believe this may be a duplicate of https://github.com/dotnet/aspnetcore/issues/22795. A fix for this was inserted into `omnisharp-vscode` on July 10 and should be a part of the next release.

**Comment by NTaylorMullen** [comment] 2020-07-20 21:20
Looks like we already fixed this after all. Thanks @TanayParikh

**Closed by NTaylorMullen** 2020-07-20 21:20 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, bug, feature-razor.languageserver

**Comment by niem94** [comment] 2020-07-21 12:25
I can confirm that it is fixed 🚀
