### ISSUE TITLE
DataAnnotationsValidator The current thread is not associated with the Dispatcher. 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#34238] opened 2021-07-09 20:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DataAnnotationsValidator-The-current-thr/1471242)._

---
When trying to use <DataAnnotationsValidator/> on .net Blazor 6 (preview), an error is displayed by Kestrel, I have added a video of the problem.

---
#### Feedback Bot on 7/8/2021, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-07-12 16:51
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/32411

**Closed by mkArtakMSFT** 2021-07-12 16:51 UTC
Labels: Author: Migration Bot :robot:, area-blazor
