### ISSUE TITLE
Blazor Web Assembly Force Refresh Programtically.

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#22361] opened 2020-05-29 17:28 UTC
I developed Blazor Web Assembly PWA App.

When i publish updated version to Azure App Service, the browser still continues to display the Cached Version.

Now as a developer i can do F12 on Desktop/laptop and then do "Empty cache and Hard Reload". But what about users, i can't expect each user of the site to know this trick, which again i dependent on the browser used.

Now for Mobile scenario,I browsed a Page on my Iphone and can't see a way to force update it, it keeps on showing very old version of app. How do i handle such mobile user scenarios?
can't even use F12 option here.

Is there a way to provide a button, which when clicked loads the newer version ?

Or is there any other techniquie which lets user know that there is new version or better if it automatically updates itself.

**Comment by mrpmorris** [comment] 2020-05-30 08:03
Is this a duplicate of this other ticket https://github.com/dotnet/aspnetcore/issues/22353

**Comment by mkArtakMSFT** [comment] 2020-06-01 16:29
Thanks! This is indeed a dupe, so closing this one.

**Closed** 2020-06-15 13:04 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
