### ISSUE TITLE
Test Collection Cleanup Failure

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#49615] opened 2023-07-25 01:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
[Collection("Tests Collection")]
public class AuthorizeEndpointIntegrationTests
{
    private readonly HttpClient _client;
    public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory) => _client = factory.CreateClient();
}
```
```
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup>, IDisposable where TStartup : class
{
    public void Dispose()
    {
        using (var scope = Services.CreateScope())
        {
            var scopedServices = scope.ServiceProvider;
            var myDb = scopedServices.GetRequiredService<MyDbContext>();
            SeedData.CleanUpTestData(myDb);
        }
        base.Dispose(); // XXX Throws
        GC.SuppressFinalize(this);
    }
}
```
Sometime it passes, sometime it fails.

### Expected Behavior

No exception

### Exceptions (if any)

```
      Message: 
        [Test Collection Cleanup Failure (Tests Collection)]: System.AggregateException : One or more hosted services failed to stop. (Object reference not set to an instance of an object.) (Not started. Call Start first.)
        ---- System.NullReferenceException : Object reference not set to an instance of an object.
        ---- System.InvalidOperationException : Not started. Call Start first.

      Stack Trace: 
        Host.StopAsync(CancellationToken cancellationToken)
        WebApplicationFactory`1.DisposeAsync()
        WebApplicationFactory`1.Dispose(Boolean disposing)
        WebApplicationFactory`1.Dispose()
        CustomWebApplicationFactory`1.Dispose() line 77
        ----- Inner Stack Trace #1 (System.NullReferenceException) -----
        ServerSideSessionCleanupHost.StopAsync(CancellationToken cancellationToken) line 70
        Host.StopAsync(CancellationToken cancellationToken)
        ----- Inner Stack Trace #2 (System.InvalidOperationException) -----
        TokenCleanupHost.StopAsync(CancellationToken cancellationToken) line 67
        Host.StopAsync(CancellationToken cancellationToken)
```

### .NET Version

7.0.304

### Anything else?

.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by khteh** [comment] 2023-07-25 07:39
Please provide more info / reference for ` // Force the server to start`

**Comment by khteh** [comment] 2023-07-25 07:41
Is `public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory) => _factory;` a mistake or this is a new C# syntax?

**Comment by martincostello** [comment] 2023-07-25 07:52
> Please provide more info / reference for ` // Force the server to start`

Calling any of the methods that create an `HttpClient` will call the `EnsureServer()` method inside the factory, which will ensure that the HTTP server in the fixture is running before any tests methods are executed.

https://github.com/dotnet/aspnetcore/blob/1bda10b33b6cc6f3bbaceabbadb4ddd18ca6e68e/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L139

> Is `public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory) => _factory;` a mistake or this is a new C# syntax?

Which bit do you think is a mistake? It's the same syntax as your code, except I'm assigning the fixture into a field instead of the result of calling `CreateClient()`.

**Comment by khteh** [comment] 2023-07-25 07:55
Isn't it done in my code? Please check the original post:
```
    public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory) => _client = factory.CreateClient();
```

There is no assignment in your constructor. You just referenced the field. I expected `_factory = factory;`. What do I miss?

**Comment by martincostello** [comment] 2023-07-25 08:01
> [Collection("Tests Collection")]
> public class AuthorizeEndpointIntegrationTests
> {
>     private readonly HttpClient _client;
>     public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory) => _client = factory.CreateClient();
> }

Here's the code from your original post. I just amended it. It's using a [C# expression-bodied constructor](https://learn.microsoft.com/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members#constructors) to set the value of the `_client` field with the value of result of calling `factory.CreateClient()`. My code just adapts this.

If you're not familiar with this syntax, it's the same as:

```csharp
public class AuthorizeEndpointIntegrationTests : IAsyncLifetime
{
    private readonly CustomWebApplicationFactory<Program> _factory;

    public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory)
    {
        factory = _factory;
    }
}
```

Having written the above, I can now see it was just a minor typo in the GitHub written (not IDE written, so no compiler error checking) code example.

**Comment by khteh** [comment] 2023-07-25 08:04
I don't get the point of your answers / posts here. My original post already calls `factory.CreateClient`. Doesn't it "ensure that the HTTP server in the fixture is running before any tests methods are executed."?

**Comment by martincostello** [comment] 2023-07-25 08:10
I'm suggesting moving it out of the constructor and keeping the fixture in the class, so that if it fails it's easier to separate out as it would happen in a dedicated method. The rationale being that sometimes constructors throw, and then the class is disposed, but a bug in the dispose code called via a finalizer might assume the constructor never fails, and then throw. Refactoring the fixture as I suggested would help with determining whether that is the case.

Whether you think that suggestion has merit or not, the exceptions appear to be coming from IdentityServer code, so if there's an issue in ASP.NET Core a fully-reproducible example is likely going to be needed to show that that is indeed the case.

**Comment by khteh** [comment] 2023-07-25 08:17
What's the diff betwee `CreateClient` and `CreateDefaultClient`? I tried both:
```
[Collection("Tests Collection")]
public class AuthorizeEndpointIntegrationTests : IAsyncLifetime
{
    private HttpClient _client;
    private readonly CustomWebApplicationFactory<Program> _factory;
    public AuthorizeEndpointIntegrationTests(CustomWebApplicationFactory<Program> factory) => _factory = factory;

    public Task DisposeAsync()
    {
        return Task.CompletedTask;
    }

    public Task InitializeAsync()
    {
        _client = _factory.CreateDefaultClient(); // Also tried CreateClient()
        return Task.CompletedTask;
    }
    [Fact]
    public async Task ValidParametersShouldPassTest()
    {
        RequestUrl ru = new RequestUrl("https://localhost:5001/connect/authorize");
        string url = ru.CreateAuthorizeUrl(
            clientId: "sellerportal",
            responseType: "code",
            redirectUri: "https://app.com/callback",
            scope: IdentityServerConstants.StandardScopes.Profile);
        HttpResponseMessage response = await _client.GetAsync(url);
        response.EnsureSuccessStatusCode();
    }
}
```
but to no avail.

**Comment by martincostello** [comment] 2023-07-25 08:20
> What's the diff betwee `CreateClient` and `CreateDefaultClient`?

They're just different overloads, but I suggested using that one because it's the default 😄

https://github.com/dotnet/aspnetcore/blob/1bda10b33b6cc6f3bbaceabbadb4ddd18ca6e68e/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L454-L473

> but to no avail.

So it doesn't fix it, but are the exceptions being thrown the same?

If it's still not working, please provide a self-contained repro including the IdentityServer parts where the exceptions are coming from.

**Comment by khteh** [comment] 2023-07-25 08:22
```
      Message: 
[Test Collection Cleanup Failure (Tests Collection)]: System.AggregateException : One or more hosted services failed to stop. (Object reference not set to an instance of an object.)
---- System.NullReferenceException : Object reference not set to an instance of an object.

      Stack Trace: 
Host.StopAsync(CancellationToken cancellationToken)
WebApplicationFactory`1.DisposeAsync()
WebApplicationFactory`1.Dispose(Boolean disposing)
WebApplicationFactory`1.Dispose()
CustomWebApplicationFactory`1.Dispose() line 77
----- Inner Stack Trace -----
TokenCleanupHost.StopAsync(CancellationToken cancellationToken) line 71
Host.StopAsync(CancellationToken cancellationToken)
```

**Comment by martincostello** [comment] 2023-07-25 08:26
> If it's still not working, please provide a self-contained repro including the IdentityServer parts where the exceptions are coming from.

**Comment by khteh** [comment] 2023-07-25 08:32
When is the `DisposeAsync` called vs the `Dispose` function defined in the `CustomWebApplicationFactory`?
```
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup>, IDisposable where TStartup : class
{
    public void Dispose()
    {
        using (var scope = Services.CreateScope())
        {
            var scopedServices = scope.ServiceProvider;
            var appDb = scopedServices.GetRequiredService<MyDbContext>();
            SeedData.CleanUpTestData(appDb);
        }
        base.Dispose();
        GC.SuppressFinalize(this);
    }
}
```
I only want to clean up and dispose after all the tests in the "Test Collection" completes.

**Comment by martincostello** [comment] 2023-07-25 08:39
Using `DisposeAsync()` would just be an improvement if you wanted to use async code in your clean up method, but that's a different topic. `IAsyncLifetime` was just a suggestion of a refactor to see if it made any difference. Apparently it doesn't, so we're back to the original issue of why are the exceptions being thrown. Let's set aside those parts of my suggestion.

> I only want to clean up and dispose after all the tests in the "Test Collection" completes.

I understand what you're trying to do, but the call to `base.Dispose()` is throwing exceptions from IdentityServer related code. Without a repro, trying to find out _why_ that is happening is going to be difficult. Finding the root cause will also clarify whether the issue is with your application code, ASP.NET Core or IdentityServer (or something different entirely).

**Closed** 2023-08-03 01:00 UTC
Labels: Needs: Author Feedback, area-runtime, Status: No Recent Activity, Needs: Repro
