### ISSUE TITLE
AddEndpointFilterFactory not working?

### ISSUE THREAD

**Issue by cheng93** [dotnet/aspnetcore#53855] opened 2024-02-06 21:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A simple passthrough filter factory doesn't work.

### Steps To Reproduce

```c#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapPost("/foo", (Request request) => request.Id)
    .AddEndpointFilterFactory((context, next) => async c => await next(c));

app.Run();

public record Request(int Id);
```

```shell
curl  -X POST  http://localhost:5212/foo -H "Content-Type: application/json" -d '{"id":2}'
```

### Exceptions (if any)

```
System.ArgumentException: Expression of type 'System.Int32' cannot be used for parameter of type 'System.Object' of method 'System.Threading.Tasks.ValueTask`1[System.Object] WrapObjectAsValueTask(System.Object)' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateFilterPipeline(MethodInfo methodInfo, Expression targetExpression, RequestDelegateFactoryContext factoryContext, Expression`1 targetFactory)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateTargetableRequestDelegate(MethodInfo methodInfo, Expression targetExpression, RequestDelegateFactoryContext factoryContext, Expression`1 targetFactory)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Create(Delegate handler, RequestDelegateFactoryOptions options, RequestDelegateMetadataResult metadataResult)
   at Microsoft.AspNetCore.Routing.RouteEndpointDataSource.CreateRouteEndpointBuilder(RouteEntry entry, RoutePattern groupPrefix, IReadOnlyList`1 groupConventions, IReadOnlyList`1 groupFinallyConventions)
   at Microsoft.AspNetCore.Routing.RouteEndpointDataSource.get_Endpoints()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.CreateEndpointsUnsynchronized()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.EnsureEndpointsInitialized()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.get_Endpoints()
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|10_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0.101

**Comment by cheng93** [comment] 2024-02-06 21:41
I stumbled upon this because I was trying to investigate why my endpoint, which requires body, did not return a 400, and instead entered the route handler, with the following

```shell
curl  -X POST  http://localhost:1234/some-api -H "Content-Type: application/json"
```

After removing the FilterFactories, the 400 returned. Could this be also related?

**Comment by shanerogers** [comment] 2024-06-14 08:09
I also get the following issue when I use the following with a filter on the Map() or MapGroup() functions
**public record GetByIdRequest(int Id, int? PageNumber);**

**Comment by captainsafia** [comment] 2024-08-20 04:30
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/52128.

I'll see if we can get a fix for this as part of the next servicing release....

**Closed by captainsafia** 2024-08-20 04:30 UTC
Labels: area-web-frameworks
