### ISSUE TITLE
Integration Challenge: ASP.NET Core Identity Crashes with reCAPTCHA in Blazor Web App (rendermode InteractiveServer)

### ISSUE THREAD

**Issue by sinand** [dotnet/aspnetcore#52809] opened 2023-12-13 22:43 UTC
## Issue Summary:

I am using .NET 8 and Blazor with the new "Blazor Web App" template. In the template, there are default pages for login, register, etc., provided by ASP.NET Core Identity.

By default, everything works fine. However, when I try to add reCAPTCHA to my login page by creating a component, the reCAPTCHA component works fine with `@rendermode InteractiveServer`. But, when I set the `rendermode` of `login.razor` to "InteractiveServer," ASP.NET Core Identity crashes because `HttpContext` is null.

## Steps to Reproduce:

1. Create a new Blazor Web App using .NET 8.
2. Add a reCAPTCHA component to the login page.
3. Set the `rendermode` of `login.razor` to "InteractiveServer."
4. Observe the crash in ASP.NET Core Identity due to a null `HttpContext`.

## Expected Behavior:

The reCAPTCHA component should work on the login page without affecting the functionality of ASP.NET Core Identity.

## Actual Behavior:

Setting the `rendermode` of `login.razor` to "InteractiveServer" causes ASP.NET Core Identity to crash due to a null `HttpContext`.

## Additional Information:

- ReCAPTCHA component is working fine with `@rendermode InteractiveServer`.
- ASP.NET Core Identity crashes when `rendermode` of `login.razor` is set to "InteractiveServer."

## Environment Details:

- .NET Version: 8.0
- Blazor Web App Template

**Comment by mkArtakMSFT** [comment] 2024-02-13 20:12
Thanks for contacting us. This looks like more of an issue with the `reCaptcha` component that you're referring to. Specifically, the fact that it is relying on the `HttpContext` is the issue. If you think I misunderstood something here, and the reCaptcha is not the one to cause this, please share with us a minimal repro project so that we can investigate.

**Comment by sinand** [comment] 2024-02-19 14:25
> Thanks for contacting us. This looks like more of an issue with the `reCaptcha` component that you're referring to. Specifically, the fact that it is relying on the `HttpContext` is the issue. If you think I misunderstood something here, and the reCaptcha is not the one to cause this, please share with us a minimal repro project so that we can investigate.


You can see the Repro project here https://github.com/sinand/Repro52809
All I do is add @rendermode InteractiveServer to the login page.
I get an error which you can see in the errormessage.txt file

**Comment by MackinnonBuck** [comment] 2024-02-22 17:15
Thanks for reaching out, @sinand.

The Blazor Identity UI pages aren't designed to run interactively. For example, they rely on a cascading `HttpContext`, which is only available during static server rendering.

Closing this out as by design.

**Closed by MackinnonBuck** 2024-02-22 17:15 UTC
Labels: area-identity, Needs: Attention :wave:, Needs: Repro

**Comment by heidi70** [comment] 2025-01-02 18:26
I have the same issue. The Google Recaptcha V2 and V3 get stocked in "Loading..."
This is a .Net 8 security flow; how are we going to stop the automatic request? Account creation, logins, etc.
