### ISSUE TITLE
Blazor WASM with Azure AD auth hangs on 'Completing login' due to CORS errors

### ISSUE THREAD

**Issue by richardhauer** [dotnet/aspnetcore#27941] opened 2020-11-18 15:31 UTC
### Describe the bug
We have a Blazor app that, under `netcoreapp3.1` was using the standard documented approach for AzureAD auth, with the AAD Application setup under "Web Platform Configuration".

We migrated recently to `net5` and went through the new documentation, which included adding the default scope and altering the Platform Configuration for the AAD App to "SPA" instead of "Web".  I understand this makes use of the Auth Code PKCE grant flow instead of the Implicit flow used in the previous version.  Also the Javascript file in the index.html was upgraded according to instructions.

When logging in the flow seems to execute properly, in that all the AAD screens display and control is returned to the application, however the login process never completes, stopping with the message "Completing login" displayed.

Console shows a CORS error against the request to `login.microsoftonline.com/{tenant}/v2.0/token`.
This can't be an issue with the  Authentication config in the AAD App because if that were wrong I wouldn't have even got that far.

Workaround for the moment is to revert the JS in index.html to the previous version from `netcoreapp3.1` and revert the AAD App's authentication config back to Web instead of SPA.  That seems to re-engage the Implicit flow.

I suspect, but cannot prove, that the issue is in how the JS handles the Auth Code flow.

### To Reproduce
If this were an OOTB issue, I would have expected many people to hit this, but I haven't found and other tickets. I haven't tried to repro from scratch but for us, the issue occurs just following the documented steps for setup at [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0) ... noting that we actually upgraded our project from the previous version first, though it's not clear whether that's material to the issue.

### Further technical details
- IDE is VS16.8.1
- .NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment] 2020-11-18 17:37
Thanks for contacting us.
It looks like you're missing one small configuration on the AAD side. We are going to update our docs to explicitly call it out. We track that as part of https://github.com/dotnet/AspNetCore.Docs/issues/20657
Please fix your configuration and confirm whether that solves your issue.

**Comment by richardhauer** [comment] 2020-11-18 20:17
@mkArtakMSFT  I did try with the Implicit Grant boxes both ticked and unticked. I assumed it would be _possible_ to have Implicit enbled, just not _necessary_.

I don’t think there was any mention of the `Allow Public Clients` setting which is probably off. 

I can try changing that as well?
Is there a different change you’re referring to? Hard to tell from the linked issue.

**Comment by richardhauer** [comment] 2020-11-19 01:32
@mkArtakMSFT  I have done some more testing - the additional migration instructions linked in have no effect on the outcome, neither does setting "Allow Public Client Flows".

The exact error from the browser console is:

````
Access to fetch at 'https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token' from origin 'https://localhost:44356' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.  login-callback#:1

POST https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token net::ERR_FAILED
AuthenticationService.js:32 
````
In terms of the request sequence, I can see:
GET 200 https://localhost:44356/
GET 200 https://login.microsoftonline.com/{tenantId}/v2.0/.well-known/openid-configuration
GET 302 https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize?...
GET 200 https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/authorize?...
GET 302 https://login.microsoftonline.com/{tenantId}/reprocess?...
GET 200 https://login.microsoftonline.com/{tenantId}/reprocess?...
GET 200 https://localhost:44356/authentication/login-callback
GET 200 https://login.microsoftonline.com/{tenantId}/v2.0/.well-known/openid-configuration
BLOCKED https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token

**Comment by guardrex** [comment] 2020-11-19 15:46
@richardhauer ... We had an issue (from @adds39939) that was machine-specific. Can you also test from a different machine to see if your issue is similar? I don't think an issue was opened (is that right @adds39939?), but the closed docs issue (linked to comment) is ...

https://github.com/dotnet/AspNetCore.Docs/issues/20482#issuecomment-725015546

**Comment by danroth27** [comment] 2020-11-19 17:29
Possible theory from @hamiltonha:

> Some users are running into CORS issues when using msal.js 2x auth code w/pkce. I believe in these particular cases the issue is caused by having both "Web" and "Single-page application" added as platforms in app registration, as the issue is resolved when "Web" is removed and references to ReplyUrlsWithType: "Web" are eliminated from the app manifest.

**Comment by guardrex** [comment] 2020-11-19 17:35
@adds39939 tried it, but it didn't seem to resolve it ...

https://github.com/dotnet/AspNetCore.Docs/issues/20482#issuecomment-724976315

**Comment by danroth27** [comment] 2020-11-19 17:50
@richardhauer Can you please also verify?

**Comment by javiercn** [comment] 2020-11-19 17:53
This is likely an issue in the app registration in the portal.

I would suggest you validate that you only have a redirect url registered as SPA and if that still causes you issues you try with a new app registration to see if it makes a difference.

I would suggest if you make sure you only have the SPA redirect URL registered and that you removed the Web Application redirect url, just in case.

**Comment by richardhauer** [comment] 2020-11-20 09:17
@danroth27 

Can confirm that if I configure the Application with **only** an SPA callback URL then it does function correctly.
With both SPA and Web callback URLs we get the hang behaviour.

Appreciate the fix but this is not intuitive at all and still seems like a bug to me.
If nothing else it should be noted in the documentation - if there is a requirement to use these features exclusive of each other then the UI should not allow them to be used at the same time.

**Comment by richardhauer** [comment] 2020-11-20 09:17
@javiercn   ^^

**Comment by richardhauer** [comment] 2020-11-20 09:19
@mkArtakMSFT  ^^

**Comment by guardrex** [comment] 2020-11-20 13:01
> If nothing else it should be noted in the documentation

It's already noted. The migration doc calls for the dev to **remove** the **Web** platform config. The WASM security topics in the main doc set avoid any mention of the **Web** platform config (for 5.0+) and only guide the use of the **SPA** config.

Example: https://docs.microsoft.com/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#standalone-blazor-webassembly-app-with-microsoft-accounts

However, I placed a *Troubleshoot* section into the migration topic, and this could be added there and to the *Troubleshoot* INCLUDES file easily enough for the Blazor WASM security topics. @mkArtakMSFT or @javiercn ... shall I proceed with that?

**Comment by javiercn** [comment] 2020-11-20 14:03
@richardhauer thanks for the confirmation.

This is an issue with the Azure AD B2C Service not sending the right response headers in this case. I'm not sure if this is a scenario they support (and then a bug) or if this is not intended to be supported (by design).

IMO its weird to have the same url configured for both a web app and a SPA, so I would suggest not having the same redirect url configured for both cases.

**Comment by javiercn** [comment] 2020-11-20 14:04
/cc: @danroth27 in case you want to follow up with the Azure AD B2C team.

I'm closing this issue since there's nothing else for us to do there

**Closed** 2020-11-20 14:04 UTC
Labels: External, area-blazor, blazor-wasm
