### ISSUE TITLE
Auto-complete places message in the wrong place

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#35392] opened 2021-08-16 17:08 UTC
When Auto-complete triggers it seems to do so from the current cursor position rather from where the cursor was when the completion was triggered. See the below gif, which moved "Click me" outside of the `button` arbitrarily.
![BackTyping](https://user-images.githubusercontent.com/14987221/129601568-0dab07ee-b1da-4f8b-ac9c-71f368e4eccc.gif)

This may be partially (or entirely) because of how slow that completion was to fire (I wasn't typing particularly fast but was able to complete two words).

@NTaylorMullen this might also be related to https://github.com/dotnet/roslyn/pull/55615.

**Comment by NTaylorMullen** [comment] 2021-08-16 18:59
> @NTaylorMullen this might also be related to [dotnet/roslyn#55615](https://github.com/dotnet/roslyn/pull/55615).

Could definitely be related

I have this as well: https://github.com/dotnet/aspnetcore/issues/33678

And I think the platform also has a tracking issue for this. @milopezc / @matteo-prosperi do you have that tracking issue on hand / know when it's planned?

**Comment by NTaylorMullen** [comment] 2021-08-31 23:56
Closing as duplicate of: https://github.com/dotnet/aspnetcore/issues/33678

**Closed by NTaylorMullen** 2021-08-31 23:56 UTC
Labels: area-razor.tooling, feature-razor.vs
