### ISSUE TITLE
Quarantine CacheTagHelper_AllowsVaryingByUICulture

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#55930] opened 2024-05-28 22:53 UTC
## Failing Test(s)

- Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationWithCultureTest.CacheTagHelper_AllowsVaryingByUICulture

## Error Message

```text
Assert.Equal() Failure
           ↓ (pos 1)
Expected: 10
Actual:   14
           ↑ (pos 1)
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationWithCultureTest.CacheTagHelper_AllowsVaryingByUICulture() in /_/src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationWithCultureTest.cs:line 116
```
</details>

## Logs

<details>

```text

```
</details>

## Build

aspnetcore-ci 5/24/2024, 12:42:15 PM

**Comment by halter73** [comment] 2024-05-29 03:11
This seems to be related to #4907. It seems my attempted fix didn't really fix it considering it looks both tests use the same `CacheTagHelper_VaryByCulture.cshtml`.

**Comment by amcasey** [comment] 2024-05-29 15:56
@halter73 Do you want to dup this against #4907?  I had too many tests (see https://github.com/dotnet/aspnetcore/pull/55935) to quarantine to do backlog searches for each - I just took for granted that an unquarantined test was not also covered by a bug.

**Comment by halter73** [comment] 2024-05-29 17:45
Sure. Closing as dupe of #4907

**Closed by halter73** 2024-05-29 17:45 UTC
Labels: test-failure, area-mvc
