### ISSUE TITLE
Firefox shows "attempting to reconnect to server" after using NavManager.NavigateTo(ContinueUrl, true);

### ISSUE THREAD

**Issue by The-Nutty** [dotnet/aspnetcore#16739] opened 2019-11-01 12:56 UTC
# Describe the bug
I have a simple server side blazor page that when you click a button redirects away to another page. Once the button is clicked the page should redirect without any noticeable interruption from the users point of view. Instread when using firefox after clicking the button the page goes white and shows attempting to reconnect to server as if it has lost connection to the server.

### To Reproduce
1. Using ASP.NET core 3.0/3.1
2. Create a new server side blazor project and add the page at https://gist.github.com/The-Nutty/efab2574eb72615ece6403df0d0ccc75
3. Run the program and goto https://localhost:5001/test in firefox
4. Click continue

### Expected behavior
From the users point of view they should be redirected and they should not see "attempting to reconnect to server" error message/

### Additional context
Tested on firefox developer and stable, tested on latest .net core 3.1 and 3.0 stable.

**Comment by mkArtakMSFT** [comment] 2019-11-01 16:20
Thanks for contacting us. One of our team members will look into this during 5.0 timeframe.

**Comment by mkArtakMSFT** [comment] 2020-02-13 19:18
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by barahonajm** [comment] 2020-04-01 21:00
This also happens every time you hit "F5" on "Firefox", it does not happen on edge and chrome 
![image](https://user-images.githubusercontent.com/15148088/78186114-2ec7e980-743a-11ea-8286-64ccbc6df71f.png)

**Comment by lovaszvencel** [comment] 2020-04-02 21:19
> We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

I aggree, that there are many higher priority features/bugs. But until you do not fix the bug we cannot use blazor with MVC in production (MVC site with same blazor components on same pages). I think it is really annoying for the visitor to see the error message on every page load/page navigation.
Do you have any workaround, until the fix is ready?

**Comment by captainsafia** [comment] 2020-06-13 02:44
Closing this as a dupe of #19050 which has already been triaged.

**Closed by captainsafia** 2020-06-13 02:44 UTC
Labels: area-blazor, bug, help wanted
