### ISSUE TITLE
Microsoft.AspNetCore.DataProtection PersistKeysToDbContext : unable to retrieve decryption key.

### ISSUE THREAD

**Issue by ahmedkamal-TeraByte** [dotnet/aspnetcore#31786] opened 2021-04-12 09:01 UTC
I am working with encryption some data using ceritificate. 
i have been using following method to encrypt and decrypt data with a certificate that was already added in windows Certificate store. 

```
services.AddDataProtection()
                    .ProtectKeysWithCertificate(thumbprint)
                    .PersistKeysToDbContext<CloudDbContext>();
```
it was working completely fine.. but then we decide to move our server from windows to linux. Hence, i exported that certificate from windows cert manager and put it in linux machine and used the following code.

```
services.AddDataProtection()
                    .ProtectKeysWithCertificate(new X509Certificate2(certificateDetails.GetValue<string>("filePath"), certificateDetails.GetValue<string>("password")))
                    .PersistKeysToDbContext<CloudDbContext>();
```

as it is the same certificate so it is supposed to be working fine. because keys are stored in the database. and i've verified that keys are present in database. but everytime i try to decrypt my data, i get the following exception..

 ```
An exception occurred while processing the key element '<key id="07dabe64-845f-4f2f-8e1d-e63ae1ee4b08" version="1" />'.
System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
```

Now this key " id="07dabe64-845f-4f2f-8e1d-e63ae1ee4b08" is present in my db.. but somehow it is unable to retrieve.. 

The new data is being encrypted and decrypted properly using this certificate and a new key is also being generated and stored in the database. but the older data can't be decrypted.. How can i decrypt the older data???

**Comment by blowdart** [comment] 2021-04-15 14:33
Dupe of https://github.com/dotnet/aspnetcore/issues/31706

**Closed by blowdart** 2021-04-15 14:33 UTC
Labels: area-dataprotection
