### ISSUE TITLE
Can't use hotReloadProfile with additional arguments

### ISSUE THREAD

**Issue by dustinlacewell** [dotnet/aspnetcore#39739] opened 2022-01-24 22:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm running the command
```
dotnet watch run --verbose -- foo bar
```

And I see:

```
watch : Did not find a HotReloadProfile or running a non-default command. Watching with legacy behavior.
```

### Expected Behavior

HotReload works.

### .NET Version

6.0.100

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     nixos
 OS Version:  22.05
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /nix/store/0w5pnrf9zg8lws2a5hxw0wc9q7mmxl3k-dotnet-sdk-6.0.100/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/nix/store/0w5pnrf9zg8lws2a5hxw0wc9q7mmxl3k-dotnet-sdk-6.0.100/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/nix/store/0w5pnrf9zg8lws2a5hxw0wc9q7mmxl3k-dotnet-sdk-6.0.100/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/nix/store/0w5pnrf9zg8lws2a5hxw0wc9q7mmxl3k-dotnet-sdk-6.0.100/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by pranavkm** [comment] 2022-01-24 22:57
Thanks for the issue report. This is a dupe of https://github.com/dotnet/aspnetcore/issues/31365. We'll use the other issue to track further work here.

**Closed by pranavkm** 2022-01-24 22:57 UTC
