### ISSUE TITLE
How to debug aspnetcore source code?

### ISSUE THREAD

**Issue by jackletter** [dotnet/aspnetcore#18435] opened 2020-01-18 02:39 UTC
I'like debug source code,but how debug this code in vs2019

**Comment by Ronkiro** [comment] 2020-01-18 03:03
Just set breakpoints and then run your application

**Comment by jackletter** [comment] 2020-01-18 03:09
I mean debugging the source code of aspnetcore, not my code

**Comment by xsoheilalizadeh** [comment] 2020-01-18 08:34
@jackletter, Currently you could debug the ASP.NET Core source code, take a look at these links:

[Debugging ASP.NET Core 2.0 Source Code](https://www.stevejgordon.co.uk/debugging-asp-net-core-2-source)
[Debugging third-party code with Rider](https://blog.jetbrains.com/dotnet/2017/12/20/debugging-third-party-code-rider/)

**Comment by jackletter** [comment] 2020-01-18 08:49
I try to use symbols to debug the source code, but the prompt is:
Https://msdl.microsoft.com/download/symbols: no symbols found on the symbol server.
Https://symbols.nuget.org/download/symbols: no symbols found on the symbol server.
Here are my project settings:
![image](https://user-images.githubusercontent.com/15626065/72661158-12f3a080-3a12-11ea-9577-6a1f68ba2037.png)
![image](https://user-images.githubusercontent.com/15626065/72661175-361e5000-3a12-11ea-8b74-1df8864738d1.png)

![image](https://user-images.githubusercontent.com/15626065/72661196-6bc33900-3a12-11ea-82d6-4e065a85f8cb.png)

**Comment by Pilchie** [comment] 2020-01-19 01:06
@dotnet/aspnet-build - how is this currently supposed to be working?  Also, @jackletter, it looks like you're running on .NET Core 2.0 which has been out of support for a long time. I recommend upgrading to 3.1, or if that is too big a jump immediately, at least 2.1.  Both 2.1 and 3.1 are LTS releases.

See https://dotnet.microsoft.com/platform/support/policy/dotnet-core for details.

**Comment by dougbu** [comment] 2020-01-19 01:29
> how is this currently supposed to be working?

For 2.0, the instructions at https://www.stevejgordon.co.uk/debugging-asp-net-core-2-source look reasonable. I suspect the out-of-support 2.0 symbols have simply expired and been removed from MSDL.

For anything recent (3.0.0 and on), all of the symbols should be available on MSDL.

There's a symbol checker somewhere in Arcade we might be able to use to confirm the 2.1 symbols are still where we expect (MSDL or perhaps the old NuGet symbol server).

**Comment by jackletter** [comment] 2020-01-19 02:08
When I tried version 3.1, the same thing happened：
![image](https://user-images.githubusercontent.com/15626065/72673274-f6ec0f80-3aa2-11ea-9e20-4d4c1aca7b47.png)
![image](https://user-images.githubusercontent.com/15626065/72673283-0d926680-3aa3-11ea-99d3-5212a78161b2.png)
![image](https://user-images.githubusercontent.com/15626065/72673311-82fe3700-3aa3-11ea-9e97-f5e2e9116d8a.png)
Does the symbol not exist on the server?

**Comment by dougbu** [comment] 2020-01-19 06:12
It's possible the issue is geo-distribution of the symbol files but I'm not positive. Could you please provide the exact version information of the files you're checking? I'll check in the next couple of days.

**Comment by jackletter** [comment] 2020-01-19 06:34
I look for assemblies in this order:
![image](https://user-images.githubusercontent.com/15626065/72676097-47c22f00-3ac8-11ea-8dcb-fdb5b98eb9f1.png)
What is a reference assembly? Can't find a symbol related to it?

**Comment by jackletter** [comment] 2020-01-19 06:37
I look for assemblies in this order:
![image](https://user-images.githubusercontent.com/15626065/72676168-29106800-3ac9-11ea-80a2-0189eea24c32.png)

What is a reference assembly? Can't find a symbol related to it?

**Comment by dougbu** [comment] 2020-01-19 20:15
> What is a reference assembly? Can't find a symbol related to it?

See https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies

The information I asked for is only available at runtime. Check the Modules window (Debug -> Windows -> Modules aka Ctrl+D, M) when debugging your application. I can't read the complete Version or Timestamp columns in the screenshots provided earlier.

**Comment by jackletter** [comment] 2020-01-20 01:05
![image](https://user-images.githubusercontent.com/15626065/72691925-dd5ecc80-3b63-11ea-84d3-bda497d9f864.png)

**Comment by dougbu** [comment] 2020-01-22 18:57
I checked everything in the 3.1.1 shared framework and all looks well here in Redmond e.g.
```
Checking file  C:\Temp\SymbolTest\8cfd4d4d-149a-44d7-9272-1078a500d005\content\shared\Microsoft.AspNetCore.App\3.1.1\Microsoft.Extensions.Hosting.dll ... Symbols found on MSDL (NGen PDB) and SymWeb (NGen PDB)
```

I'll check 2.1 later today.

**Comment by dougbu** [comment] 2020-01-22 22:53
Did a spot check of our 2.1 and 2.2 packages and confirmed their symbols are also available on MSDL. (Minor detail: You don't need the NuGet symbol source for our symbols.)

I also debugged a default ASP.NET Core MVC application and successfully downloaded all of the symbols:
![image](https://user-images.githubusercontent.com/6431421/72941822-c3b9b280-3d26-11ea-82fc-631f49343056.png)

The issue you're having @jackletter is likely a networking problem, either geo-location (as I mentioned earlier) or an intervening proxy refusing to connect to the symbol servers and (oddly) returning a 404.

**Comment by Pilchie** [comment] 2020-01-28 01:17
Closing as we can't seem to reproduce this issue locally.

**Closed by Pilchie** 2020-01-28 01:17 UTC
Labels: area-platform, question

**Comment by fangqifan** [comment] 2020-02-08 09:02
@jackletter  you need SS or V2ray  to bypass GFW
