### ISSUE TITLE
Inconsistent behavior in HttpContext.RequestAborted.IsCancellationRequested

### ISSUE THREAD

**Issue by avparuch** [dotnet/aspnetcore#35407] opened 2021-08-17 05:22 UTC
### Describe the bug
When a client disconnects, I expect HttpContext.RequestAborted.IsCancellationRequested to return true. On Kestrel, this is indeed the case. However on HttpSysServer, HttpContext.RequestAborted.IsCancellationRequested returns false despite the client disconnecting.

### To Reproduce
1) Fire up any Kestrel sample project in Visual Studio: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/servers/kestrel/samples/5.x/KestrelSample
2) Fire up any HttpSysServer sample project in Visual Studio: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/servers/httpsys/samples/3.x/SampleApp
3) Send requests to both servers and abruptly disconnect your client. I've attached a simple TCPClient I used.
[TCPClient.zip](https://github.com/dotnet/aspnetcore/files/6997261/TCPClient.zip)

4)  HttpContext.RequestAborted.IsCancellationRequested returns true on Kestrel, returns false on HttpSysServer.

### Further technical details
- ASP.NET Core version : 5.0.9

**Comment by Tratcher** [comment] 2021-08-17 15:23
Duplicate of https://github.com/dotnet/aspnetcore/issues/17278

**Closed by Tratcher** 2021-08-17 15:23 UTC
Labels: area-runtime, servers-httpsys
