### ISSUE TITLE
RequestDelegateGenerator throws NullReferenceException in ASP.NET Core 8 preview 2

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspnetcore#47202] opened 2023-03-14 18:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Building an existing .NET 7 solution with .NET 8 preview 2 fails with the following error:

```
CSC : error CS8785: Generator 'RequestDelegateGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.' [/home/runner/work/lambda-test-server/lambda-test-server/src/AwsLambdaTestServer/MartinCostello.Testing.AwsLambdaTestServer.csproj::TargetFramework=net8.0]
```

### Expected Behavior

The solution compiles and tests pass.

### Steps To Reproduce

1. Clone the [martincostello/lambda-test-server](https://github.com/martincostello/lambda-test-server) repository
2. Checkout the repository at https://github.com/martincostello/lambda-test-server/pull/361/commits/e47cc131af7c9fa92bd988cf3c3e3ce89fc3738f
3. Run `build.ps1`

### Exceptions (if any)

```
CSC : error CS8785: Generator 'RequestDelegateGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.' [/home/runner/work/lambda-test-server/lambda-test-server/src/AwsLambdaTestServer/MartinCostello.Testing.AwsLambdaTestServer.csproj::TargetFramework=net8.0]
```

### .NET Version

8.0.100-preview.2.23157.25

**Comment by danmoseley** [comment] 2023-03-14 19:51
Should we be including callstack in these warning messages for any exception that shouldn't occur from user error?

**Comment by captainsafia** [comment] 2023-03-14 20:41
> Should we be including callstack in these warning messages for any exception that shouldn't occur from user error?

Unfortunately, we don't control the way these callstacks show up. The compiler does.

@martincostello The issue that you've described is a dupe of https://github.com/dotnet/aspnetcore/issues/47148 and should be resolved in the latest preview3 nightly.

By the way, the RequestDelegateGenerator is intended to be _off_ by default in applications. However, the logic to turn it off by default lives in the Web SDK. I notice that you are referencing the ASP.NET runtime using a framework reference. Unfortunately, there is a known limitation with our current approach for turning it off that should be resolved in preview3. Check out [this issue](https://github.com/dotnet/sdk/issues/30872) for more info.

For now, you can manually remove the generator from your compilation using this [MSBuild target](https://github.com/dotnet/sdk/blob/c6ef9d7ff80918921d77323c925454126fafeaed/src/WebSdk/Web/Sdk/Sdk.props#L64-L75).

**Closed** 2023-03-15 22:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Status: Resolved
