### ISSUE TITLE
IBrowserFile Relative Path property for Blazor Input File

### ISSUE THREAD

**Issue by jbeubi** [dotnet/aspnetcore#31567] opened 2021-04-06 17:47 UTC
### Is your feature request related to a problem? Please describe.

Hello, we are currently working on a file uploader where the user picks a folder and, based on certains rules, we generate a Zip from the file list. Unfortunately the current built-in InputFile component returning a list of IBrowserFile only contains a "Name" property and not any "RelativePath" property which prevent us from generating a proper ZipFile, however it is available in JS and i saw the property inside the BrowserFile class.

### Describe the solution you'd like

Add a **RelativePath** property in the IBrowserFile interface

### Additional

Has someone found a workaround when using this component or shall we use a custom solution ?
I tried to get a value by reflection but the property doesn't seems filled

Thanks !

**Comment by jbeubi** [comment] 2021-04-06 18:22
Yes it seems like it is not populated but why is the property existing in the [`BrowserFile`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile/BrowserFile.cs#L10)  class then  ? I guess for a future implementation maybe..

And yes you're right, it refers to `webkitRelativePath`, is there any workaround i could go on ? Or should we just use a custom component ?

**Comment by javiercn** [comment] 2021-04-07 09:49
@jbeubi thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/30867. In short, this is not a standard property. See the details [here](https://github.com/dotnet/aspnetcore/issues/30867#issuecomment-799560554)

**Closed by javiercn** 2021-04-07 09:49 UTC
