### ISSUE TITLE
HTTP.SYS returns 400 - BadRequest with certain Accept-Encoding values.

### ISSUE THREAD

**Issue by jimnkey** [dotnet/aspnetcore#20388] opened 2020-03-31 23:51 UTC
Given a web app (netcoreapp3.0 hosted in IIS) -- any requests with certain (IMO, acceptable) values for Accept-Encoding header never gets to the application. http.sys parses and spits out a 400 - BadRequest.

i.e., A request with a header: 
`Accept-Encoding: application/gzip, gzip, deflate`
Results in a 400 - BadRequest.

The issue seems to be the '/' character.

Although the [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3) says allowed values are 'tokens', shouldn't it allow delimiters (i.e., '/')?  It obviously allows the ',' delimiter.

**Expect/Want** - http.sys to not reject it (`Accept-Encoding: application/gzip, gzip, deflate`) and allow the application to handle the request.

Additional Info: I am not in control of the client/request.  It is not possible to ask for a change on the (legacy) client application.

**Comment by Tratcher** [comment] 2020-04-01 17:30
No, token does not allow slashes, only alpha-numeric characters. `application/gzip` is the format for a content-type, not an encoding. `application/gzip` belongs in the [Accept](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1) header, not the Accept-Encoding header.

I'll have to verify, but I expect this is happening at the Windows (Http.Sys) or IIS layer and is not something ASP.NET has any control over. That would mean needing to go through Microsoft Support to request an OS patch.

The main workaround you could try is disabling / uninstalling the IIS response compression module.

What client is this?

**Comment by anurse** [comment] 2020-04-01 20:13
Kestrel and ASP.NET Core shouldn't reject this, and we're not in direct control over Http.sys behavior here. The best next step would be to engage Microsoft Support and/or file Windows Feedback on this.

If this reproduces in Kestrel, we could investigate further. Moving this to discussions since we don't have actionable work we can take here.

**Comment by jimnkey** [comment] 2020-04-01 20:52
@Tratcher, @anurse , thanks for the reponses... I have tested and I'm pretty sure it's http.sys and it never gets to IIS.  I believe the client is an old java client that we have no control over.  There are more than several client systems that reach our service with the offending java library.  I've tried using Kestrel with an nginx reverse proxy and on the surface seems to be ok; although there's more to manage/test for uptime.

Is there a way to use just Kestrel on its own?

But I'll try going through Microsoft Support for the OS patch if you agree http.sys shouldn't spit out bad request just because of the '/' character.
Thanks!

**Comment by Tratcher** [comment] 2020-04-01 21:07
> Is there a way to use just Kestrel on its own?

Yes, kestrel is supported on its own, but again you need to manage things like lifetime.

> But I'll try going through Microsoft Support for the OS patch if you agree http.sys shouldn't spit out bad request just because of the '/' character.

On the contrary, the client is clearly violating the spec. You're going to have a tough time convincing Windows that this is appropriate to patch (but you're welcome to try). I expect you'd have more luck fixing the client no matter how painful that may be.

**Comment by jimnkey** [comment] 2020-04-01 21:40
I was thinking more that 'application/gzip' would be considered as two tokens because '/' is a delimiter just as ',' is.
But I do agree, those clients should be fixed...
Thanks.

**Comment by Tratcher** [comment] 2020-04-01 21:45
',' is the standard delimiter used between all HTTP header values. '/' is only allowed in complex values like media types, and there it's meaning is quite different from ','.

**Comment by jimnkey** [comment] 2020-04-01 22:09
Sure, I agree with that's for complex values ... it's just that I don't believe that should be the job of http.sys to distinguish.  From how I read the spec, `Accept-Encoding` should allow similar content as `Accept`, maybe it's the part that says "but restricts the content-codings" part that is confusing me - cause I don't see how that should matter if '/' is there (for http.sys).

**Comment by Tratcher** [comment] 2020-04-01 22:31
The server is free to enforce validation on any field it's going to use to process the request.

The format for Accept-Encoding is more restrictive than Accept. The updated spec is a bit easier to read. https://tools.ietf.org/html/rfc7231#section-5.3.4

     Accept-Encoding  = #( codings [ weight ] )
     codings          = content-coding / "identity" / "*"
     content-coding   = token
     token          = 1*tchar
     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

     Accept = #( media-range [ accept-params ] )

     media-range    = ( "*/*"
                      / ( type "/" "*" )
                      / ( type "/" subtype )
                      ) *( OWS ";" OWS parameter )

     media-type = type "/" subtype *( OWS ";" OWS parameter )
     type       = token
     subtype    = token

Accept explicitly allows "token/token" where Accept-Encoding only allows "token".

**Comment by jimnkey** [comment] 2020-04-01 22:33
I think I understand now... I think you're correct in that it would be difficult to ask for such a patch.
I did read it incorrectly -- it's not 'similar content', it's just 'similar' and like you said only token.
Why are they putting 'application/gzip'? ... sigh.

Thanks for the discussion!

**Comment by jimnkey** [comment] 2020-04-01 22:46
That updated spec confused me, too... because both should allow token delimiter token, and I thought '/' is a delimiter.  I guess i'm just going in circles.  It is what it is.  And I don't think I would be able to convince to get http.sys patched.
Thanks again.

**Closed** 2020-11-12 02:04 UTC
Labels: External, area-servers, investigate, servers-iis
