### ISSUE TITLE
Blazor Webassembly Project Template no longer works

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#44880] opened 2022-11-04 17:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Webassembly-Project-Template-no-l/10188069)._

---
[severity:I'm unable to use this version] [regression]
Open a new WebAssembly project

Select .Net 7 Preview and Individual Accounts

Click F5 to run.

When the project runs click on Fetch Data 

    Message : There was an error trying to log you in: ' (500)'

Click on Log in 

    Message : There was an error trying to log you in: ' (500)'

Click on Register

Apply Migrations

Refresh and Click on Register

    Account is successfully registered.

Try to log in

    Invalid login attempt.

Many thanks

---
#### Mike Wood on 11/2/2022, 06:36 AM: 

(private comment, text removed)
#### Feedback Bot on 11/2/2022, 08:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment] 2022-11-07 22:23
I was able to reproduce the issue by following the repro steps precisely. But the login only appears to be broken because after applying migrations, you aren't redirected to the page that lets you confirm the account. Besides that, the app works as intended after applying migrations.

FWIW, I tested the .NET 6 template and observed the exact same behavior.

@javiercn is this the expected behavior for this template?

**Comment by MackinnonBuck** [comment] 2022-11-09 22:19
I was just trying this again on the latest VS public preview (17.5.0 Preview 1) and I no longer observe the broken redirect behavior. The 500's still happen before migrations are applied, but I'm guessing this is by design.

To the author of this ticket: Could you try the latest VS public preview and see if you still experience the issue (specifically not being able to log in)? Thanks!

**Comment by Forestf3a** [comment] 2022-11-10 08:49
Microsoft Visual Studio Community 2022
Version 17.5.0 Preview 1.0
VisualStudio.17.Preview/17.5.0-pre.1.0+33103.201
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools   17.5.90.43013
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.90.43013
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.5.90.43013
Azure Functions and Web Jobs Tools

C# Tools   4.5.0-1.22528.5+77904ac785bbddb853161aed9eac6ca03aba0ddf
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2255201+5530de5c8323cd1ecacb497bbab5637907d0fc02
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.31026.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.11026.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-1.22528.5+77904ac785bbddb853161aed9eac6ca03aba0ddf
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.22525.1+90f5b1ed0befe8337b923860d29dcd62d4735aef
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.


Thanks for looking into this.

**Comment by Forestf3a** [comment] 2022-11-15 23:59
I reinstalled Visual Studio and all is now well.

**Comment by MackinnonBuck** [comment] 2022-11-17 22:18
Closing this out, since the issue appears to have been resolved. We can reopen if we get more feedback that this is still a problem.

**Closed by MackinnonBuck** 2022-11-17 22:18 UTC
Labels: investigate, area-blazor, Author: Migration Bot :robot:
