### ISSUE TITLE
Add Blazor SSR css stylesheet link append-version component

### ISSUE THREAD

**Issue by Markz878** [dotnet/aspnetcore#49678] opened 2023-07-27 13:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Since Blazor SSR doesn't have tag helpers, there should be some components to help the move from Razor pages.
Please add a component to replace the 'append-version' option in the link-tag helper.

### Describe the solution you'd like

Add a <StyleSheet> component, that takes the href parameter, and appends a version to it automatically or based on a boolean flag.

### Additional context

Here is a crude example I hacked together:
```
@using System.Security.Cryptography;
@using Microsoft.Extensions.Caching.Memory;
@inject IWebHostEnvironment environment;
@inject IMemoryCache cache;

<link href="@GetHref()" rel="stylesheet" />

@code {
    [Parameter][EditorRequired] public required string Href { get; set; }

    private string GetHref()
    {
        string? href = cache.GetOrCreate(Href, (_ =>
        {
            string filePath = Path.Combine(environment.WebRootPath, Href);
            string version = GetVersion(filePath);
            return $"{Href}?v={version}";
        }));
        return href ?? Href;
    }

    private string GetVersion(string filePath)
    {
        try
        {
            using SHA1 sha1 = SHA1.Create();
            using FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
            byte[] hash = sha1.ComputeHash(fs);
            return Convert.ToBase64String(hash);
        }
        catch (Exception)
        {
            byte[] hash = new byte[16];
            Random.Shared.NextBytes(hash);
            return Convert.ToBase64String(hash);
        }
    }
}
```

**Comment by Bartmax** [comment] 2023-10-16 18:50
I think this is very much needed. Blazor SSR needs many quality of life improvements like this one before being ready for production.

**Comment by Bartmax** [comment] 2023-10-16 20:30
Here's my implementation:

{ProjectName}.csproj:
```
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.0-*" />
```

Program.cs:
```c#
builder.Services.AddMvcCore().AddRazorViewEngine();
```


Link.razor
```C#
@using Microsoft.AspNetCore.Mvc.ViewFeatures
@inject NavigationManager NavigationManager
@inject IFileVersionProvider FileVersionProvider
@code {
    [Parameter] public bool AppendVersion { get; set; } = true;
    [Parameter] public required string Href { get; set; }

    [Parameter(CaptureUnmatchedValues = true)] public Dictionary<string, object> AdditionalAttributes { get; set; } = default!;
    string href = "";

    protected override void OnInitialized()
    {
        href = AppendVersion ? FileVersionProvider.AddFileVersionToPath("/", Href) : Href;
    }
}

<link href="@href" @attributes="AdditionalAttributes" />
```

Usage:

```Html
<Link Href="/css/app.css" rel="stylesheet" AppendVersion="true" />
```

**Comment by Bartmax** [comment] 2023-10-16 21:36
Or a more reusable version:

```razor
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
namespace {APP};

public abstract class AppendableVersion : ComponentBase
{
    [Inject] public IFileVersionProvider FileVersionProvider { get; set; } = default!;
    [Parameter] public bool AppendVersion { get; set; } = true;
    [Parameter(CaptureUnmatchedValues = true)] public Dictionary<string, object> AdditionalAttributes { get; set; } = default!;

    protected string Source { get; set; } = "";

    protected string Result { get; private set; } = "";

    protected override void OnInitialized()
    {
        base.OnInitialized();
        Result = AppendVersion ? FileVersionProvider.AddFileVersionToPath("/", Source) : Source;
    }

}
```

Link.razor:
```razor
@inherits AppendableVersion

@code {
#pragma warning disable BL0007 // Auto property
    [Parameter] public required string Href { get { return base.Source; } set { base.Source = value; } }
#pragma warning restore BL0007
}

<link Href="@base.Result" @attributes="AdditionalAttributes" />
```
Script.razor:
```razor
@inherits AppendableVersion

@code {
#pragma warning disable BL0007 // Auto property
    [Parameter] public required string Src { get { return base.Source; } set { base.Source = value; } }
#pragma warning restore BL0007 // Auto property
}
<script src="@base.Result" @attributes="AdditionalAttributes" />
```

**Comment by ArgoZhang** [comment] 2024-01-02 07:25
link or script should be loaded before blazor component. so use blazor component like `Link` or `Script` I don't think it's a good idea. we need find a new way resolve this issue.

**Comment by Markz878** [comment] 2024-01-02 09:42
> link or script should be loaded before blazor component. so use blazor component like `Link` or `Script` I don't think it's a good idea. we need find a new way resolve this issue.

In Blazor SSR mode the entire page is rendered first before sending anything to the client, so the link tag doesn't have to "loaded before blazor". I have used my implementation of the Link component in production for a while and it works well. What are you basing this on @ArgoZhang ?

**Comment by ArgoZhang** [comment] 2024-01-02 10:27
Yes, you are right. My viewpoint is wrong.

**Comment by mkArtakMSFT** [comment] 2024-01-16 18:21
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/52824

**Closed by mkArtakMSFT** 2024-01-16 18:21 UTC
Labels: enhancement, area-blazor, feature-static-web-assets, Pillar: Complete Blazor Web
