### ISSUE TITLE
dotnet core oauth2 is not working

### ISSUE THREAD

**Issue by ashutosh1ibm** [dotnet/aspnetcore#20940] opened 2020-04-17 09:01 UTC
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by javiercn** [comment] 2020-04-17 09:14
closing as a duplicate of https://github.com/dotnet/aspnetcore/issues/20939

**Closed by javiercn** 2020-04-17 09:14 UTC
