### ISSUE TITLE
Add support JsObjectRef for Blazor WebAssembly

### ISSUE THREAD

**Issue by redradist** [dotnet/aspnetcore#24434] opened 2020-07-30 09:02 UTC
What I see right now in Blazor Wrappers happens some mess with custom Js Iterop that provides its own JsObjectRef or whatever ... It is splitting Blazor community

Each library creates analog of JsObjectRef from https://github.com/RemiBou/BrowserInterop/wiki/Utility-methods

### Describe the solution you'd like
Add JsObjectRef like in https://github.com/RemiBou/BrowserInterop/wiki/Utility-methods

In such way community will have standard way for working with JsObjectRef-s in Blazor

@SteveSandersonMS @danroth27 Seems like this is not hard to do and maintain, in https://github.com/RemiBou/BrowserInterop Js Object storage not so big ;)

**Comment by javiercn** [comment] 2020-07-30 12:18
@redradist thanks for contacting us.

I think this is a dupe of https://github.com/dotnet/aspnetcore/issues/21598,
possibly https://github.com/dotnet/aspnetcore/issues/15087
and https://github.com/dotnet/aspnetcore/issues/16078

**Comment by redradist** [comment] 2020-07-30 12:54
> 
> 
> @redradist thanks for contacting us.
> 
> I think this is a dupe of #21598,
> possibly #15087
> and #16078

@javiercn Yes, it seems like ... but still there is no progress even implementation could be pretty simple like in [BrowserInterop](https://github.com/RemiBou/BrowserInterop)

**Comment by javiercn** [comment] 2020-07-30 14:09
@redradist this is not something we've prioritized up to this point.

I've captured the related issues so that we can bring more visibility to the request.

I hope you understand that ultimately we have a big backlog and we need to prioritize the items we work on. We do make this public in our roadmap issue [here](https://github.com/dotnet/aspnetcore/issues/21514).

If you feel that this ask is not receiving enough visibility, feel free to upvote this one and direct folks to it so that we get a clearer picture of the people interested in it.

I'll leave this issue open for tracking purposes so that we can collect feedback.

**Comment by SteveSandersonMS** [comment] 2020-10-07 09:57
This was implemented in .NET 5, so closing as done.

**Closed by SteveSandersonMS** 2020-10-07 09:57 UTC
Labels: area-blazor, blazor-wasm, enhancement

**Comment by redradist** [comment] 2020-10-07 10:04
> 
> 
> This was implemented in .NET 5, so closing as done.

@SteveSandersonMS Do you mean this already implemented in .NET 5 ? If yes, is there any documentation that describes solution ?

**Comment by SteveSandersonMS** [comment] 2020-10-07 10:45
Yes, it's here: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references

**Comment by SteveSandersonMS** [comment] 2020-10-07 10:47
Note that you can use `IJSObjectReference` on any JS call from .NET to JS. It's not limited to being used with ES modules (though the docs seem to suggest they go together).

**Comment by redradist** [comment] 2020-10-07 11:02
> 
> 
> Yes, it's here: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references

It is very cool !! Nice you added this very use-full feature !!

**Comment by redradist** [comment] 2020-10-07 11:04
> 
> 
> Note that you can use `IJSObjectReference` on any JS interop call from .NET to JS. It's not limited to being used with ES modules (though the docs seem to suggest they go together).

@SteveSandersonMS Actually, I did not get your last statement ... Is there some issues with ES modules ?
Or do you mean that it will work for both non-module and module JavaScript ?

**Comment by redradist** [comment] 2020-10-07 11:17
@SteveSandersonMS Also you may be interested, I am working in free time for providing all browser API to .NET WebAssembly and maybe in future it would be possible to integrate this solution to .NET WebAssembly, because I think each developer deserve freedom of choice what to do with Browser API and if other UI frameworks implementation (React Web, Angular) provides this API I think .NET WebAssembly also should provide this functionality to user

For example exposing whole Browser API to user may allow to create framework in framework, for example framework for some animation inside of Blazor WebAssembly and .NET should not restrict developer in use of Browser API that is available on other platforms ;)

**Comment by danroth27** [comment] 2020-10-07 22:19
> I am working in free time for providing [all browser API to .NET WebAssembly](https://github.com/redradist/BlazorTypeScriptGenerator)

@redradist I believe the Mono folks were working on something similar for a while. @kjpou1 is that code still around?

**Comment by redradist** [comment] 2020-10-09 10:05
@SteveSandersonMS @danroth27 What do you think about https://github.com/dotnet/aspnetcore/issues/24801 ?
It is related to this repository https://github.com/redradist/BlazorDependencies

This library simplifies managing Static Web Assets? it would be nice if Blazor WebAssembly supports it directly ...

**Comment by SteveSandersonMS** [comment] 2020-10-09 11:00
@redradist As of .NET 5, we now have some recommended built-in ways to achieve this:

 * For loading CSS automatically, RCL authors can used scoped CSS (`*.razor.css`). These will be imported automatically.
 * For loading JS automatically, RCL authors can use [the `import` mechanism to load JS modules](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references) as needed

These mean that RCL consumers don't need to add `<script>` or `<link>` tags to their page to get the CSS/JS from the RCL.

I'm aware that your library provides a different way to achieve it, and that's great! Anyone who prefers your approach can use your library. Having multiple options, and well-maintained open-source libraries from a wide range of contributors, is an indicator of a healthy ecosystem. We don't currently have plans to add a different loading mechanism into the framework.

**Comment by redradist** [comment] 2020-10-18 09:48
> 
> 
> @redradist As of .NET 5, we now have some recommended built-in ways to achieve this:
> 
>     * For loading CSS automatically, Razor Class Library (RCL) authors can used scoped CSS (`*.razor.css`). These will be imported automatically.
> 
>     * For loading JS automatically, RCL authors can use [the `import` mechanism to load JS modules](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references) as needed
> 
> 
> These mean that RCL consumers don't need to add `<script>` or `<link>` tags to their page to get the CSS/JS from the RCL.
> 
> I'm aware that your library provides a different way to achieve it, and that's great! Anyone who prefers your approach can use your library. Having multiple options, and well-maintained open-source libraries from a wide range of contributors, is an indicator of a healthy ecosystem. We don't currently have plans to add a different loading mechanism into the framework.

@SteveSandersonMS Sometimes CSS is global for all components and cannot be passed to `*.razor.css` and due to this it is also hard to decide where to put loading CSS using import statement because this CSS is not related to some specific components and for this reason https://github.com/redradist/BlazorDependencies proper solution ...

... But due to that this solution is external not all user know about this, also consider if someone else implement the same functionality with different `.json` deps file ... it could also split ecosystem

As for the best way to avoid this is to provide single dependency mechanism for static files with standard `.json` format
