### ISSUE TITLE
How to translate Identity Core 2.1 DefaultUI to german

### ISSUE THREAD

**Issue by mduu** [dotnet/aspnetcore#5838] opened 2018-11-17 07:58 UTC
I'm trying to switch the Identity Core 2.1 Default UI to another language.

In the startup.cs I forced the app to german but the default UI still shows up in englisch:

            services.Configure<RequestLocalizationOptions>(options =>
            {
                options.DefaultRequestCulture = new RequestCulture("de-CH");
                options.SupportedCultures = new List<CultureInfo> { new CultureInfo("de-CH") };
                options.RequestCultureProviders = new List<IRequestCultureProvider>();
                options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(
                    async context => new ProviderCultureResult("de")
                ));
            });

How can I a) switch to german texts for the default UI or b) do my own german translations for the texts in the default UI?

I did research for several hours already without success. I read that one may can influence the texts like error messages with .resx files but I don't know what file with which content to put where. Further more I think there should be german translations already available as they are for the .Net since years.

I'm using Visual Studio for Mac and deploy the app to Azure AppServer on Windows. I welcome any help to get german translations for Identity Core 2.1 into place.

**Comment by HaoK** [comment] 2020-10-06 18:29
Dupe of https://github.com/dotnet/aspnetcore/issues/5778

**Closed by HaoK** 2020-10-06 18:29 UTC
Labels: area-identity, blocked, enhancement
