### ISSUE TITLE
Ending quote not added after typing first quote for the value of a component parameter

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22745] opened 2020-06-09 23:33 UTC
![wiRXRs6kgw](https://user-images.githubusercontent.com/1874516/84210891-c8c99500-aa6e-11ea-92ab-97ee36d6d28a.gif)

Ending quote does get added if the tag has not yet been completed.

![YCgBUM0App](https://user-images.githubusercontent.com/1874516/84210947-f57dac80-aa6e-11ea-8b21-787c6ea876b3.gif)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by NTaylorMullen** [comment] 2020-06-09 23:43
Duplicate of: https://github.com/dotnet/aspnetcore/issues/21857

**Closed by NTaylorMullen** 2020-06-09 23:43 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, bug
