### ISSUE TITLE
Blazor @page directive remove requirement for string double quotes (RZ1016)

### ISSUE THREAD

**Issue by wstaelens** [dotnet/aspnetcore#44352] opened 2022-10-04 09:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Blazor server the @page only accepts a string with double quotes.

We can't use `@page MyRoutes.ModuleA` or `@page $"{MyRoutes.Base}\{MyRoutes.ModuleB}"`

### Expected Behavior

Should be possible to use const string routes defined in a static class:

```
@page MyRoutes.ModuleA`
@page $"{MyRoutes.Base}\{MyRoutes.ModuleB}"
```

### Steps To Reproduce

```
@page RouteHelper.Foo

internal static class RouteHelper {
public const string Foo = "foo/bar";
}
```

### Exceptions (if any)

RZ1016 The 'page' directive expects a string surrounded by double quotes.

### .NET Version

6.0.401

### Anything else?

Blazor Server
Visual Studio 2022

**Comment by campersau** [comment] 2022-10-04 09:48
See also: #35465

**Comment by javiercn** [comment] 2022-10-04 10:07
@wstaelens thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/35465 as per @campersau comment

**Closed by javiercn** 2022-10-04 10:07 UTC
