### ISSUE TITLE
[Blazor] Define blazor.webassembly.Js as a static web asset

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#47640] opened 2023-04-11 10:06 UTC
We currently have this code in the SDK https://github.com/dotnet/sdk/blob/main/src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets#L97-L126 to gather the file and resolve it.

This is completely unnecessary as the file can directly be defined as a static web asset at the time we pack it [here](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/targets/Microsoft.AspNetCore.Components.WebAssembly.props)

**Comment by mkArtakMSFT** [comment] 2024-11-12 19:25
Closing as a dupe of #58783

**Closed by mkArtakMSFT** 2024-11-12 19:25 UTC
Labels: enhancement, area-blazor, Priority:2, Pillar: Technical Debt
