### ISSUE TITLE
Add 127.0.0.1 support to dotnet dev-certs

### ISSUE THREAD

**Issue by jongio** [dotnet/aspnetcore#19399] opened 2020-02-27 13:40 UTC
### Is your feature request related to a problem? Please describe.
I'm trying to use dev-certs with Azurite.

Azurite defaults to 127.0.0.1

dev-certs only supports 'localhost'

### Describe the solution you'd like

dev-certs supports 127.0.0.1

I'm using mkcert instead, but would like dev-certs to be an option.

I could also start Azurite with 'localhost' as the default, but that isn't the default option and I want to make this experience as seamless as possible for the dev

1. `dotnet dev-certs http --trust` - to trust the cert
2. `azurite -s` - to start Azurite in secure mode

### Additional context

More details in this blog post about the hoops we currently have to jump through to get Azurite working with HTTPS: https://blog.jongallant.com/2020/02/azurite-https-defaultazurecredential/

**Comment by blowdart** [comment] 2020-02-27 13:51
Dupe of https://github.com/dotnet/aspnetcore/issues/18959

Basically, no, as that doesn't really match the type of certs you'd get when getting a "real" certificate, and the browser support is, well, patchy, it's not something that's urgent enough to do.

**Closed by blowdart** 2020-02-27 13:51 UTC
