### ISSUE TITLE
Double diagnostics in error list after building

### ISSUE THREAD

**Issue by allisonchou** [dotnet/aspnetcore#27141] opened 2020-10-22 23:15 UTC
![doublediag](https://user-images.githubusercontent.com/16968319/96939285-82a32a00-1481-11eb-8241-c6c6bc24da0d.png)

Double diagnostics for an invalid/undefined variable appeared after trying to build a WebAssembly app.

**Comment by NTaylorMullen** [comment] 2020-11-11 00:38
@allisonchou could you please try seeing if this reproduces on the latest VSMaster builds.

**Comment by allisonchou** [comment] 2020-11-13 01:01
@NTaylorMullen I'm still seeing this in the latest main build (30712.122.main).
Not all errors are duplicated, but some seem to be:
![DoubleBuildErrors](https://user-images.githubusercontent.com/16968319/99014976-b44f6400-2508-11eb-8d33-fe74b9526156.gif)

**Comment by TanayParikh** [comment] 2020-11-16 21:57
![image](https://user-images.githubusercontent.com/14852843/99298287-7a87a180-2817-11eb-88e4-7a2ea7fcbb1d.png)

This is still an issue with pull-diagnostics (verified locally on Main).

The source of the error seems to not be razor, notice the duplicated entries contain a "clickable"/linked error code, a value for the `Project` and a value for `Suppression State`.

**Comment by TanayParikh** [comment] 2020-11-17 00:01
So this is due to a mix of C# push diagnostics on build & razor pull diagnostics. When both C# and razor pull diagnostics flags are enabled, this issue doesn't persist. Closing out with the acknowledgement that until both C# & Razor are using pull diagnostics by default, the issue will remain.

**Closed by TanayParikh** 2020-11-17 00:01 UTC
Labels: area-razor.tooling, bug, feature-razor.vs, investigate

**Comment by NTaylorMullen** [comment] 2020-11-17 04:51
@danroth27 so technically this means our new Razor editor will get duplicate diagnostics from building for a while. How "end of the world" does that sound?

**Comment by danroth27** [comment] 2020-11-17 05:39
It's certainly not great, but not the end of the world.
