### ISSUE TITLE
[Blazor] ::deep does not work in combination with [dir="rtl"]

### ISSUE THREAD

**Issue by vnbaaij** [dotnet/aspnetcore#45138] opened 2022-11-16 23:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you have an isolated CSS file that contains `[dir="rtl"]`-selector in combination with `::deep`-selector the generated CSS does not work correctly because there is no space between the two selectors.

Because of the space not being there, targeting rtl-languages with isolated CSS icw [dir] selector is very hard/impossible.

### Expected Behavior

The generated CSS should contain a space between `[dir="rtl"]`-selector and `::deep`-selector.

What gets generated:
```
[dir="rtl"][b-fl]  fluent-button {
    display: none;
    position: fixed;
    bottom: 45px;
    left: 20px;
    right: unset;
    z-index: 99;
    cursor: pointer;
}
```
What should be generated:
```
[dir="rtl"] [b-fl]  fluent-button {
    display: none;
    position: fixed;
    bottom: 45px;
    left: 20px;
    right: unset;
    z-index: 99;
    cursor: pointer;
}
```
_NOTE:  There are **2** spaces generated between the generated `::deep` selector and the fluent-button selector_

### Steps To Reproduce

Repo: https://github.com/vnbaaij/CssIsolationBug

Standard new Blazor WebAssembly project. 
- I changed `<html>-tag` to `<html lang="en" dir="rtl">`
- I've added a <div> at the bottom of the survey prompt withing the existing div:
 ```
<div class="rtlspecific">
            Some RTL content
    </div>
```
- I've put the `<SurveyPrompt>` in `<Counter>`
- I've added `SurveyPrompt.razor.css` with:
```
[dir="rtl"] ::deep .rtlspecific {
    color: red;
    border: 1px dotted red;
}
```
Running this gives:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/1761079/202312627-b767c617-ded1-4ba1-b5c5-41dadf0d9769.png">

**No red text/border**
Going to Dev Tools you'll find in CssIsolationBug.styles.css:
```
:
/* /Shared/SurveyPrompt.razor.rz.scp.css */
[dir="rtl"][b-e23gho3fj3]  .rtlspecific {
    color: red;
    border: 1px dotted red;
}
```

Adding the space between `[dir="rtl"]` and `[b-e23...]` in Dev Tools gives the desired effect:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1761079/202313024-0dc04e68-32ca-4ef2-920b-89fb09c9a8e4.png">

### .NET Version

.NET 6 and higher

**Comment by Nick-Stanton** [comment] 2022-11-18 23:57
It seems that leading with a square-bracketed attribute selector (i.e. `[dir="rtl"] ::deep .rtlspecific`) is not currently supported for Razor's `::deep` pseudo-element. In a designed use case ([e.g.](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#child-component-support) `::deep h1`), the expected behavior is for the output to have no space.

CC @SteveSandersonMS on whether this scenario is intended behavior.

Repro: https://github.com/Nick-Stanton/CSSMissingSpace

**Comment by SteveSandersonMS** [comment] 2022-11-21 18:02
@Nick-Stanton I'll look into the more general point you've raised. Thanks!

@vnbaaij It's possible I'm misunderstanding your objective, but it looks as if you're just not using `::deep` correctly. Your code looks like this:

```
[dir="rtl"] ::deep .rtlspecific
```

... and what that means is "match anything in this component that has `[dir="rtl"]` and find any descendant (in any component) with `.rtlspecific`".

But that's not really what you want, is it? Don't you want to put `dir="rtl"` on the `html` or `body` element or similar? You're not actually putting `dir=rtl` onto something in the current component, are you?

I think what you really mean is "when an ancestor has [dir=rtl], match any element from this component or any descendant with `.rtlspecific`". So I think the syntax you should use is this:

```
[dir="rtl"] * ::deep .rtlspecific
```

Doesn't that work?

BTW https://github.com/vnbaaij/CssIsolationBug gives a 404. Maybe it's a private repo.

**Comment by vnbaaij** [comment] 2022-11-21 18:16
Oops, repo is private indeed. Will correct that first later (today probably).

>But that's not really what you want, is it? Don't you want to put dir="rtl" on the html or body element or similar? You're not actually putting dir=rtl onto something in the current component, are you?

No, I'm not doing that. What I'm doing is indeed setting dir="rtl" on a higher level (through a user selected switch). I then want to target (part of) my component with some specific rtl styling. 

>I think what you really mean is "when an ancestor has [dir=rtl], match any element from this component or any descendant with .rtlspecific". So I think the syntax you should use is this:

Yes, that is what I want

>`[dir="rtl"] * ::deep .rtlspecific

I'll give this a try and report back. Thanks!

**Comment by SteveSandersonMS** [comment] 2022-11-21 18:24
BTW if `.rtlspecific` is within the current component (not a descendant) then you wouldn't even need `::deep` at all. The syntax would just be:

```css
[dir=rtl] .rtlspecific { ... }
```

That matches things in the current component with `.rtlspecific` as long as some ancestor has `[dir=rtl]`.

**Comment by vnbaaij** [comment] 2022-11-21 20:31
> BTW if `.rtlspecific` is within the current component (not a descendant) then you wouldn't even need `::deep` at all. The syntax would just be:
Yes, understood. Thing is I'm composing a lot of things with components getting nested and therefore need the `::deep`.

I've made the repo public now.

**Comment by SteveSandersonMS** [comment] 2022-11-23 09:52
> Feels strange to have this difference, right?

The difference is only because `::deep .rtlspecific { ... }` is shorthand for `* ::deep .rtlspecific { ... }`. If you wish, you could use the longhand version for the ltr case and then the code would look more symmetrical.

I'll close this as answered now. Hope that's OK.

**Closed by SteveSandersonMS** 2022-11-23 09:52 UTC
Labels: question, area-blazor
