### ISSUE TITLE
When rendering interactive components, ability to pass in passive RenderFragment as parameter

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#46991] opened 2023-03-02 14:33 UTC
The expectation is that during SSR, any `RenderFragment` that is passed as a `SSRRenderModeBoundary` parameter would get pre-evaluated as HTML during the initial SSR and becomes a special `RenderFragment` in the interactive component that outputs this HTML.

### Preserving DOM nodes during subsequent renders

If we want to preserve DOM nodes if the interactive component renders the magic `RenderFragment` multiple times, we can't just render it as a markup frame. We would have to also include some metadata to tell the TypeScript-side code not to simply discard the old markup, but instead to go through the DomSync logic.

### What if it also contains more interactive components?

This should be supported too. Superficially it shouldn't be too hard; if we're introducing the content into the page using DomSync, it should automatically activate or update any interactive components inside it.

However, a complication arises with "auto" rendermode. For example:

 * Some SSR markup
   * Contains interactive component A (`TabSet`, say)
     * Parameter: RenderFragment (which is passed as more SSR markup, i.e., the new feature described by this issue)
       * Contains interactive component B (`Tab`, say)

Perhaps WebAssembly is not initially loaded, so component A resolves as `server`. But then, by the time it injects the `RenderFragment` into the page, WebAssembly becomes loaded. So component B resolves as `webassembly`. But component B (the `Tab`) relies on receiving a cascaded value supplied by an ancestor (the `TabSet`), and ~~hence will fail with a NRE~~. 

~~The failure here happens as a race condition, and is quite possibly not going to surface in development because everything loads so fast. But in prod, it's definitely going to happen sometimes.~~

~~To avoid this, the ideal would be that `auto` always resolves as the same as its closest interactive ancestor, and only does the dynamic switching if there is no interactive ancestor. That's a new feature we'll need to implement.~~

**Update** No, this is nonsense. In this scenario both `TabSet` and `Tab` would be independent **root components**, even though that is unintuitive. So it would make no difference whether they have the same rendering platform or not - you still couldn't pass a cascading value from one to the other.

Right now, I can't think of an extra problem that would necessarily occur due to `auto` changing from resolving with one rendermode to another later. If anyone can think of such a problem, please let us know!

**Comment by ElderJames** [comment] 2023-12-15 02:01
I have a scene just explain in https://github.com/dotnet/aspnetcore/issues/51518.

I want the Layout component to be interactive, but some pages to be static. Currently, passing pages through the Body is not supported.

**Comment by mkArtakMSFT** [comment] 2023-12-20 18:18
Related https://github.com/dotnet/aspnetcore/issues/52768

**Comment by mkArtakMSFT** [comment] 2024-01-17 17:54
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/52768

**Closed by mkArtakMSFT** 2024-01-17 17:54 UTC
Labels: enhancement, area-blazor, feature-full-stack-web-ui, Pillar: Complete Blazor Web
