### ISSUE TITLE
Using filter (IRouteHandlerFilter) in minimal API throws exception

### ISSUE THREAD

**Issue by JohnyL** [dotnet/aspnetcore#41464] opened 2022-05-01 14:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Say, I have this simple API:
```csharp
app.MapPost("/clients", (SearchCriteria search) => Results.Ok())
   .AddFilter<ValidationFilter<SearchCriteria>>();
```
I use empty validation filter:
```csharp
public class ValidationFilter<T> : IRouteHandlerFilter where T : class
{
  public async ValueTask<object> InvokeAsync(
    RouteHandlerInvocationContext context,
    RouteHandlerFilterDelegate next)
  {
    return await next(context);
  }
}
```
SearchCriteria class:
```csharp
public class SearchCriteria
{
  public int Id { get; set; }
  public string Name { get; set; }
}
```
Request to this API throws exception:
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at lambda_method5(Closure, RouteHandlerInvocationContext)
         at ValidationFilter`1.InvokeAsync(RouteHandlerInvocationContext context, RouteHandlerFilterDelegate next) in E:\Projects\TestWebApi\TestWebApi\Program.cs:line 93
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteObjectReturn(Object obj, HttpContext httpContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass64_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### .NET Version

7.0.100-preview.3.22179.4

**Comment by BrennanConroy** [comment] 2022-05-01 15:31
Dupe of https://github.com/dotnet/aspnetcore/issues/41188, fixed in preview4.

Workaround is to move the inline delegate into a function.

**Comment by JohnyL** [comment] 2022-05-01 15:51
@BrennanConroy That works. Thanks! 🙂

**Closed** 2022-05-02 16:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved
