### ISSUE TITLE
Blazor support for root level do while loop in C# code

### ISSUE THREAD

**Issue by anirugu** [dotnet/aspnetcore#43264] opened 2022-08-13 06:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I develop c# based console application (top level statement) for API calls and create the blazor app for doing same. I am using Do While loop because it will be run at-least once to get the count from API call.

The code that is working in console, I pasted in blazor app. Blazor app show it like a invalid code. Can someone please look how I can make a do while loop. 

### Expected Behavior

It should execute as it is proper valid c# code
[testing.txt](https://github.com/dotnet/aspnetcore/files/9330932/testing.txt)

I am attaching the file, rename it to .razor and you must be able to copy paste in your project. The file doesn't require anything except newtonsoft and Restsharp.

### Steps To Reproduce

Copy paste, Run, It will give you compile error.

### Exceptions (if any)

NA

### .NET Version

Dotnet 7 Preview 7

### Anything else?

NA

**Comment by TanayParikh** [comment] 2022-08-13 06:40
Hello, thanks for reaching out. A do while loop is a C# language construct and should just work as is. Are you saying just creating an empty do while loop produces a compiler error in a blazor file? If so, what is the error? Do you get the error in a regular C# console app?

**Comment by anirugu** [comment] 2022-08-13 07:36
@TanayParikh  I have attached the testing.txt (which is actually testing.razor) to reproduce the issue. For screenshot please look 

![image](https://user-images.githubusercontent.com/35772421/184474048-419f85ef-9f70-4ab4-a2d1-02ad728bca0b.png)

**Comment by MariovanZeist** [comment] 2022-08-13 09:01
@anirugu in blazor a .razor file will be compiled into a class.  You are missing a function description.
Your code block should look something like this:

```razor
@code {
   //Your variables
    int SomeValue;
    string SomeOtherValue;
    
    public Task RunSomeAsyncCode()
    {
      // the do while loop should be here somewhere
    }
}
```

If you want your code to execute when the component loads, you could for example override the ``Task OnInitializeAsync()``
function. 
You can find more information on the components lifecycle [Here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0)

**Comment by TanayParikh** [comment] 2022-08-13 16:42
As @MariovanZeist mentions above, the do while loop needs to be in a function or a @{ block (https://docs.microsoft.com/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#razor-code-blocks).

Closing as by design.

**Closed** 2022-08-14 19:01 UTC
Labels: :heavy_check_mark: Resolution: By Design, area-blazor, Status: Resolved

**Comment by anirugu** [comment] 2022-08-15 06:25
Thanks @MariovanZeist @TanayParikh I am able to make it work as you explained. https://github.com/anirugu/Testing.Jobs
