### ISSUE TITLE
[Blazor] .NET6 Preview 4 - Standalone Published Blazor WebAssembly does not work 

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#33265] opened 2021-06-03 22:11 UTC
Early Evaluating .NET 6 - Preview 4

Blazor WebAssembly Published standalone (published all the binaries) to Azure is throwing  error when using EditForm and CascadingParameters

Also throws exception for ChildContent not being public.

Works on local environments but fails when published.

```
Unhandled exception rendering component: The type 'PiFormInputMultiSelect' declares a parameter matching the name 'ChildContent' that is not public. Parameters must be public.
System.InvalidOperationException: The type 'PiFormInputMultiSelect' declares a parameter matching the name 'ChildContent' that is not public. Parameters must be public.
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.WritersForType..ctor(Type targetType)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1[[System.String[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

```
 Unhandled exception rendering component: The type 'PiFormInputNumber`1[[System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' declares a parameter matching the name 'ParsingErrorMessage' that is not public. Parameters must be public.
System.InvalidOperationException: The type 'PiFormInputNumber`1[[System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' declares a parameter matching the name 'ParsingErrorMessage' that is not public. Parameters must be public.
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.WritersForType..ctor(Type targetType)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1[[System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)

```

**Comment by pranavkm** [comment] 2021-06-03 23:07
Thanks for the issue report @ameyasubhedar. 

I suspect this is a dupe of https://github.com/mono/linker/issues/2059 that is being fixed as part of 6.0-preview5. If you'd like you could try grabbing a nightly build of the preview5 or newer SDK from https://github.com/dotnet/installer#installers-and-binaries and see if that addresses the issue. Other users have had success using the nightly to work around this issue so it might help.

**Closed** 2021-06-07 16:51 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor, blazor-wasm, feature-blazor-deployment
