### ISSUE TITLE
No longer have access to HttpCookie objects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37714] opened 2021-10-20 16:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-longer-have-access-to-HttpCookie-obje/1549728)._

---
[severity:It's more difficult to complete my work]
In the past, .NET allowed us to access a collection of `HttpCookie` objects. This allowed me to access cookies that can contain multiple values.

Now, with .NET Core/5.0, this ability is gone! The `Request.Cookies` collection is only a dictionary from string to string.

It's hard to call it progress when useful features are being pulled for no apparent reason.

---
#### Feedback Bot on 10/11/2021, 00:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Tratcher** [comment] 2021-10-20 17:09
Duplicate of https://github.com/dotnet/aspnetcore/issues/37431

**Closed by Tratcher** 2021-10-20 17:09 UTC
Labels: area-runtime, Author: Migration Bot :robot:
