### ISSUE TITLE
Template/MVC tests fail after updating TFM to net7.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#36765] opened 2021-09-20 21:31 UTC
`Templates.Test.BaselineTest.Template_Produces_The_Right_Set_Of_FilesAsync(arguments: "new react", expectedFiles: ["ClientApp/public/favicon.ico", "ClientApp/public/index.html", "ClientApp/public/manifest.json", "ClientApp/src/components/Counter.js", "ClientApp/src/components/FetchData.js", ...])`

> Expected file to exist, but it doesn't: ClientApp/src/reportWebVitals.js

`Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationTest.CacheTagHelper_BubblesExpirationOfNestedTagHelpers`

> Assert.Equal() Failure
↓ (pos 33)
Expected: ···ctronics
Products: Music Systems, Televisions (3)
Actual:   ···ctronics
Products: Book1, Book2 (1)
↑ (pos 33)

`Microsoft.AspNetCore.Mvc.TagHelpers.CacheTagHelperTest.ProcessAsync_FlowsEntryLinkThatAllowsAddingTriggersToAddedEntry`

> Assert.False() Failure
Expected: False
Actual:   True
at Microsoft.AspNetCore.Mvc.TagHelpers.CacheTagHelperTest.ProcessAsync_FlowsEntryLinkThatAllowsAddingTriggersToAddedEntry() in /_/src/Mvc/Mvc.TagHelpers/test/CacheTagHelperTest.cs:line 539

**Comment by BrennanConroy** [comment] 2021-10-30 02:19
This is caused by https://github.com/dotnet/runtime/pull/57648 which made a breaking change to the MemoryCache on purpose.

I'm not sure if the product needs to change or just the two tests affected.

`CacheTagHelper_BubblesExpirationOfNestedTagHelpers` can be fixed by adding
`services.AddMemoryCache(o => o.TrackLinkedCacheEntries = true);` to the Startup of HtmlGenerationWebSite.

`ProcessAsync_FlowsEntryLinkThatAllowsAddingTriggersToAddedEntry` can be fixed by setting `TrackLinkedCacheEntries` to `true` when newing up the `MemoryCacheOptions`.

**Comment by Tratcher** [comment] 2021-11-08 19:49
Offline notes: This is a product regression for cache tag helpers and we should turn TrackLinkedCacheEntries back on in MVC for this scenario.

**Closed** 2021-11-11 17:29 UTC
Labels: bug, test-failure, area-mvc, feature-templates, ss-p3
