### ISSUE TITLE
Html Markdown in .razor file creates warnings after inserting @onclick

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27474] opened 2020-11-02 23:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Html-Markdown-in-razor-file-creates-war/1129868)._

---
When writing html markup in a razor file, adding an @onclick to a <div> element causes the div enclosing all of my elements to stop closing, i.e. the <div> can't find its matching </div> at the end of the file.

This only affects half of the </div> elements on the page.

```
<div> <!--This div will say it doesn't have an end tag-->
  <div>
      more children elements
  </div>
  <div> <!--Only this div and its children divs cause the problem when an @onclick is added to them.-->
      more children elements
  </div>
</div> <!--This div will say it doesn't have a closing tag-->
```

When this problem happens, my entire @code {} block beneath the ending div is highlighted in blue and says end tag is missing matching start tag.

The end div element has its last two characters (v and >) highlighted in yellow (I'm running dark mode). When I add a space so the element is written as `</div >` the last two characters (space and >) continue to be highlighted, but the error dissappears.

Unfortunatelly, this causing all of the highlighting in my @code {} block to dissapear as well, rendering it as a bunch of white text.

On a side note, when I copied the entirety of the offending code from Machine.razor to Test.razor, a System.ArgumentOutOfRangeException occured. The activitiy log is attached.

I am using Telerik's Kendo UI for Blazor, but removing all Telerik elements did not solve the problem.

This only affects <div> elements in the specified area. I can attach the @onclick event to a <img> element.

I was on Visual Studio 2019 v. 16.6.4, and upgrading to v. 16.6.5 did not solve the problem.
Restarting Visual Studio did not solve the problem.
Restarting my PC did not solve the problem.
Deleting the .vs folder did not solve the problem.

---
#### Feedback Bot on 7/29/2020, 08:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/29/2020, 11:08 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 8/19/2020, 06:15 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2021-01-06 20:05
This is a side effect of the Razor compiler not gracefully falling back. Pushing over to razor.compiler area.

**Comment by NTaylorMullen** [comment] 2021-01-13 18:49
> @NTaylorMullen can you please share more details regarding what `Razor compiler not gracefully falling back` is?

If the parser gets to the end of the document and sees an unclosed tag it needs to "recover" by rolling back the parser all the way to the "'unclosed" tag and then stop parsing at the end of the start tag since it knows it's "error prone". Otherwise, if you continue to parse the rest of the document then you can incorrectly parse pieces resulting in unexpected behavior / error scenarios.

**Comment by TanayParikh** [comment] 2021-10-23 00:04
Thanks for reporting, closing as duplicate of https://github.com/dotnet/aspnetcore/issues/30573.

**Closed by TanayParikh** 2021-10-23 00:04 UTC
Labels: bug, Author: Migration Bot :robot:, affected-few, severity-minor, area-razor.compiler, Priority:2
