### ISSUE TITLE
CORS with endpoint routing and RequireCors does not support automatic preflight requests

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#20709] opened 2020-04-09 22:35 UTC
This was first reported in #18665
See [Enable Cors with endpoint routing](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#enable-cors-with-endpoint-routing) which explains it and has deployed code to reproduce the behavior. Given this is documented you may want to close this issue by design and I'll update the docs to say ***By Design**.

cc @pranavkm  @apacurariu

**Comment by Bottswana** [comment] 2020-04-16 11:41
Hello,

I believe there is still a real issue here that should not be closed as By design. Allow me to explain.
Currently, the only way to support Pre-Flight OPTIONS requests using CORS is to enable a application-wide CORS policy using app.UseCors() in Configure.

- As this issue describes, the RequireCors method does not support OPTIONS requests at all.
- In addition, the [EnableCors] attribute does not work when Authorization Middleware is in use, as the Authorization middleware intercepts the Pre-Flight request first and returns a 401. There used to be an option with Mvc using the CorsAuthorizationFilterFactory as a filter, but this appears to have been removed in asp.net core 3.

As such, it seems with my 4 hours of attempting combinations and reading the newly updated documentation in regards to CORS, that the only way to achieve this is to enable application wide CORS support. This probably isn't ideal, as the documentation states, it would be much more secure to be able to target specific controllers with specific CORS policies as needed.

As it stands I have had to go with a global policy, but I would prefer to not have to do this, by having either of the other two options work with Authorization middleware without workarounds.

**Comment by Rick-Anderson** [comment] 2020-04-16 19:06
@Bottswana wrote

> enable a application-wide CORS policy using app.UseCors() in Configure.

As the doc states: 

* `app.UseCors` enables the CORS middleware. Because a default policy hasn't been configured, `app.UseCors()` alone doesn't enable CORS.

So call `app.UseCors`  and ***do not*** define default policy. Then apply the `[EnableCors(MyPolicy)]` attribute on the endpoints you want to.

cc @serpent5

**Comment by Bottswana** [comment] 2020-04-16 19:19
Thanks, but that is not what I meant. The point I was making was that app.UseCors with an appropriate policy works, but using EnableCors decorator on a controller does not work in any configuration, be that with a policy or not.

To summarize:
- Using CORS Middleware, calling app.UseCors() and specifying a default policy works. OPTIONS requests are intercepted and returned without authentication and headers are added, allowing pre-flight requests to succeed.
- Using [EnableCors] either with a default policy, or a named policy, regardless of the addition of app.UseCors() (without a default policy configured) results in the Authorization middleware intercepting the Pre-Flight request and returning a 401.
- Endpoint routing doesn't work and Pre-flight requests return a 405 (Known issue)

Just to double check, I did just now add a named policy, called app.UseCors() with no default policy, and add the [EnableCors] decorator, but this resulted in 401 errors. Disabling the Authorization middleware resulted in the Pre-Flight request succeeding and the headers as specified in the policy being added correctly.

**Comment by Rick-Anderson** [comment] 2020-04-16 19:25
> Using [EnableCors] either with a default policy, or a named policy, regardless of the addition of app.UseCors() (without a default policy configured) results in the Authorization middleware intercepting the Pre-Flight request and returning a 401.

That's not correct.

**Comment by Bottswana** [comment] 2020-04-16 19:28
That's what I am seeing. Removing [Authorize] immediately results in the code working as is and the CORS headers being added as defined in the policy.

**Comment by Bottswana** [comment] 2020-04-16 19:36
As far as I can see, this controller is not attempting to authenticate the user. The issue seems to appear when authentication is in play, as it returns 401.
Performing a OPTIONS request in CURL with a valid Authorization header results in it succeeding, so it seems to be an order issue with the Authentication/Authorization middleware intercepting the request.

Apart from configuring Authorization using JWT my code is the same as your source in the article and I get a 401.

**Comment by Rick-Anderson** [comment] 2020-04-16 19:44
Why not authenticate the user before the CORS call.

**Comment by Bottswana** [comment] 2020-04-16 19:48
The browser is making the pre-flight request because the actual request requires adding the Authorization header. Because this makes the request a 'non simple' request the pre-flight request is made with a Access-Control-Request-Headers: authorize header.
In this case, when using [EnableCors], that pre-flight request is denied with a 401.

If I was to configure CORS using with something like this for example: 
`app.UseCors(options => options.AllowAnyOrigin().WithMethods("GET","POST").WithHeaders("authorization","content-type"));`

Then it would work perfectly.

The issue seems to be compounded by JWT authentication + using [EnableCors].

**Comment by Rick-Anderson** [comment] 2020-04-16 19:52
> If I was to configure CORS using with something like this for example:
> `app.UseCors(options => options.AllowAnyOrigin().WithMethods("GET","POST").WithHeaders("authorization","content-type"));`
> 
> Then it would work perfectly.

Great info, I'll add that to my article.

**Comment by Bottswana** [comment] 2020-04-16 19:56
The problem then is it's on for everything. What I haven't checked is if I can go and put [DisableCors] on all controllers I don't want CORS to work on, such as my Razor pages.
All I'm worried about is having a permissive CORS policy on my API endpoints, and having the local Razor pages not permit cross origin requests.

**Comment by serpent5** [comment] 2020-04-16 20:09
@Bottswana Do you have a repro project for this? I've tried to emulate the problem you describe, but the `OPTIONS` request succeeds in the project I've built. It's using JwtBearer, no default policy, `UseCors()`, and `[EnableCors("MyPolicy")]` on the controller.

**Comment by Bottswana** [comment] 2020-04-16 20:13
The project that has the actual issue is private, but I will make a reproducable project and link it.
That should let me rule out anything untoward that might be causing it in my own project as well.
Did you have the source for your attempt to reproduce it that I can compare out of interest?

**Comment by serpent5** [comment] 2020-04-16 20:17
```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers();

        // Just enough authN to get a 401.
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer();

        services.AddCors(o =>
        {
            o.AddPolicy("Angular", corsPolicyBuilder =>
            {
                corsPolicyBuilder.WithOrigins("http://localhost:4200")
                    .WithMethods("POST")
                    .WithHeaders("Authorization");
            });
        });
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseDeveloperExceptionPage();
        app.UseStaticFiles();

        app.UseRouting();

        app.UseCors();

        app.UseAuthentication();
        app.UseAuthorization();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
    }
}

[ApiController]
[Route("/api/Values")]
[Authorize]
[EnableCors("Angular")]
public class ValuesController : ControllerBase
{
    [HttpPost]
    public IActionResult Post() =>
        Ok(new[] { 1, 2, 3, 4, 5 });
}
```

**Comment by Bottswana** [comment] 2020-04-16 20:41
Okay so this is super interesting.
It looks like the cause of this was the positioning of the app.UseCors(), however, for whatever reason the environment I was building in didn't throw the runtime error indicating that UseCors() was located in the wrong position.

On top of that, the app.UseCors(builder => policy) I posted above worked fine in the wrong order (before app.UseRouting) so it wasn't something I specifically caught.

I'm not sure why the project I am working on did not get the runtime error the same was as a new project did, otherwise that would have been an easy catch. Perhaps in my case it was IdentityServer4 initialising Cors in the background for me.

Position is mentioned in the documentation, but because it worked with the policy I overlooked this, so I'm not sure anything needs to be updated. I am curious as to why the runtime error was not presented on this project however.

**Comment by Rick-Anderson** [comment] 2020-04-16 21:28
@Bottswana can you edit your first post in this thread with something like:

***SOLVED*** I had `UseCors` and `UseAuthorization` in the wrong order.

And then please hide all your posts.

This issue is about endpoint routing.

**Comment by Bottswana** [comment] 2020-04-16 21:38
> It can't do that. There might be cases where you need a different order. See #18791

When I prototyped out a test project copying over just that code, it did just that, throwing a runtime warning indicating UseCors was in the wrong location, that's how I was able to identify the issue.

Specifically, when using IdentityServer4, it also initiates the CORS middleware and was doing so for me, and something odd was happening resulting in CORS partially working. At the end of the day, the specific part was that it was being called before UseRouting() which works when using a blanket policy, but not when using Endpoint Routing (As in the documentation).

**Closed** 2020-11-12 02:03 UTC
Labels: area-mvc
