### ISSUE TITLE
'Do not use top level statements' check does not work for Minimal API template.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#41636] opened 2022-05-11 18:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

First of all, thank you ASP.NET Core Team for adding an option in templates to avoid top-level statements.

However, we have noticed that `do not use top-level statements` check is not working for the **Minimal API template**.

During Project Creation:

![Capture3](https://user-images.githubusercontent.com/14342773/167921673-5b21f8c3-ee7b-41d9-9e00-e7ab0ba83452.PNG)

Generated Code in `Program.cs` file:

```C#
using Microsoft.AspNetCore.OpenApi;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateTime.Now.AddDays(index),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast")
.WithOpenApi();

app.Run();

internal record WeatherForecast(DateTime Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

### Expected Behavior

The code should be wrapped inside explicit `Program.Main`.

### .NET Version

6.0.300 and 7.0.100-preview.4.22252.9

### Anything else?

Visual Studio Version: 2022 17.3 preview 1.

**Comment by DamianEdwards** [comment] 2022-05-11 18:44
Dupe of #41491

**Closed by DamianEdwards** 2022-05-11 18:44 UTC
