### ISSUE TITLE
[SignalR] java.lang.RuntimeException thrown in HubConnection (Java Client)

### ISSUE THREAD

**Issue by petermcc0807nw** [dotnet/aspnetcore#28109] opened 2020-11-24 11:56 UTC
Hi,

I have an ASP.NET Core service, targeting the **.NET 5.0** runtime, running on a **Windows 10 (v10.0.18362)** development machine.

I also have an **Android 9.0** app which connects to the service via **SignalR** (**com.microsoft.signalr:signalr:5.0.0**)

If I repeatedly (and quite randomly) restart the service and app, resulting in continuous SignalR connects / disconnects, I will eventually crash the app with a FATAL EXCEPTION similar to the following logcat dump:

```
2020-11-23 09:10:39.956 6849-6910/com.foo.bar E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.foo.bar, PID: 6849
    java.lang.RuntimeException: The HubConnection failed to transition from the 'CONNECTED' state to the 'DISCONNECTED' state because it was actually in the 'CONNECTING' state.
        at com.microsoft.signalr.HubConnection$ReconnectingConnectionState.changeState(HubConnection.java:1512)
        at com.microsoft.signalr.HubConnection.stopConnection(HubConnection.java:538)
        at com.microsoft.signalr.HubConnection.lambda$start$6$HubConnection(HubConnection.java:279)
        at com.microsoft.signalr.-$$Lambda$HubConnection$plWe2n559m5117SGBt0gopoPs3g.invoke(Unknown Source:2)
        at com.microsoft.signalr.WebSocketTransport.onClose(WebSocketTransport.java:92)
        at com.microsoft.signalr.WebSocketTransport.lambda$start$1$WebSocketTransport(WebSocketTransport.java:55)
        at com.microsoft.signalr.-$$Lambda$WebSocketTransport$vlt_DXG3u2t5OJvAYlxBdjX-Br4.invoke(Unknown Source:2)
        at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:124)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$1.onFailure(RealWebSocket.java:216)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-11-23 09:10:39.975 6849-6910/com.foo.bar I/Process: Sending signal. PID: 6849 SIG: 9
```
In fact, this is all pretty similar to the [java.lang.NullPointerException](https://github.com/dotnet/aspnetcore/issues/24367) issue I reported back in July.

Thanks.

**Comment by BrennanConroy** [comment] 2020-11-30 17:09
Looks like a dupe of https://github.com/dotnet/aspnetcore/issues/27438

**Closed** 2020-12-02 21:07 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
