### ISSUE TITLE
SignalR MessagePack polymorphism.

### ISSUE THREAD

**Issue by olegsavelos** [dotnet/aspnetcore#30096] opened 2021-02-11 13:56 UTC
I am trying to implement an messaging based on polymorphism with SignalR and MessagePack.
It seems that with SignalR when sending messages MessagePack unions are omitted and client side cant deserialize them either by base class or interface as described [here](https://github.com/neuecc/MessagePack-CSharp#union). 
When using the normal messagepack serializer the pattern works as expected and its possible to achieve polymorphism , same does not apply with SignalR.
I have described the probelem in detail [here](https://stackoverflow.com/questions/66139055/signalr-messagepack-polymorphism.)

I am using .NET 5 and latest public releases of MessagePack and  SignalR.Protocols.MessagePack.
Can someone confirm if this is even supported ?

Looked at source code and it looks like the problem can be related to [this](https://github.com/dotnet/aspnetcore/blob/d6a287064b64a98f60a5b1d6560ea0608a817d59/src/SignalR/common/Protocols.MessagePack/src/Protocol/MessagePackHubProtocolWorker.cs#L428)
The messages are always serialized by the actual type of object and not by the type passed into function, this will never generate any union headers required for polymorphism.

**Comment by BrennanConroy** [comment] 2021-02-11 17:35
Dupe of https://github.com/dotnet/aspnetcore/issues/7298

SignalR doesn't support messagepack unions. I'm not sure if the messagepack library could be changed to support unions with `MessagePackSerializer.Deserialize(type, obj);` or if SignalR would need to use the typed `Deserialize` methods.

**Comment by olegsavelos** [comment] 2021-02-11 17:57
As I understand SignalR would need to preserve the passed argument type to hub function and pass it on to `MessagePackSerializer.Deserialize(type, obj)` that way MessagePack would serialize based on function input type and produce the union header. This is shocking for me to see that this is not implemented, based on source I suspect that even with custom protocol this cant be achieved as HubMessage does not carry any information for the objects passed as function arguments ?

**Comment by BrennanConroy** [comment] 2021-02-11 17:59
> preserve the argument passed to hub function

I don't understand what you mean here. SignalR isn't modifying the object you pass, so everything should be preserved.

**Comment by olegsavelos** [comment] 2021-02-11 18:12
I said nothing about object modification what I am saying is that the InvocationMessage class has the `public object?[]? Arguments { get; }`,those are the object that will be serialized by MessagePack with type returned by GetType, GetType will return the exact runtime type which will cause the MessagePack to serialize by that type, instead you would need to have the object instance plus the type you want to use for the serialization.
MessagePack documentation explains this [here](https://github.com/neuecc/MessagePack-CSharp#union).

Say we have three classes

abstract baseClass
class1:baseClass
class2:baseClass

in order to have the union header added (polymorphism) we need to serialize by baseClass and not any of the derived classes, currently with SignalR implementation you will always serialize with inherited classes and not base thus no union header.

**Comment by olegsavelos** [comment] 2021-02-12 10:30
By inspecting the code I think a much easier solution can be used.
Basically the only change that need to be made is in [here](https://github.com/dotnet/aspnetcore/blob/d6a287064b64a98f60a5b1d6560ea0608a817d59/src/SignalR/common/Protocols.MessagePack/src/Protocol/MessagePackHubProtocolWorker.cs#L436)

Instead of calling `argument.GetType()` you should get the **actual variable type** and not exact type,
To get actual variable type some kind of extension like this can be used

` public static class Extensions
    {
        public static Type GetArgumentType<T>(this T instance)
        {
            return typeof(T);
        }
    }`
    
   This can be behavior could enabled by hub option if you would actually want implement it.
   In any case it looks like you wont be giving any attention to this and its really disappointing :(

**Comment by davidfowl** [comment] 2021-02-12 10:51
@olegsavelos you can always send a pull request once we agree on a design. It might be cleaner to add a Type array to the invocation message. Or we can make the invocation have an optional method info (to describe the method being invoked).

**Comment by olegsavelos** [comment] 2021-02-12 11:01
Thanks a lot @davidfowl , I think that just having an option and getting correct object type should be sufficient and easier to implement but sure let me make my own implementation and see if this would be enough.

**Comment by olegsavelos** [comment] 2021-02-12 15:54
After trying to implement this with a custom HubProtocol based on your code it looks like its not possible to use the previously mentioned approach so the only way I can see this working is with extended information in the InvocationMessage, since you pass all the arguments as object the argument type information is lost and cant be obtained.
For now I can use custom HubProtocol that will check if object being serialized implements and interface that provides serialization type and serialize by that type, otherwise use default behavior.
Of course I would want to avoid this as I would need to maintain the HubProtocol code and that can lead to lots of problems with future changes you might do in your implementation.

**Comment by BrennanConroy** [comment] 2021-02-17 21:08
Feel free to continue the discussion on the other issue https://github.com/dotnet/aspnetcore/issues/7298

**Closed by BrennanConroy** 2021-02-17 21:08 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
