### ISSUE TITLE
Global usings break when using AddRazorRuntimeCompilation

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#45806] opened 2022-12-30 16:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Global-usings-break-when-using-AddRazorR/10241577)._

---
[severity:It's more difficult to complete my work]
AddRazorRuntimeCompilation makes it so that Global Using statements in razor pages do not function. This is despite intellesense within Visual Studio expecting it to work properly. This is with .net 6.0 and visual studio 14.3

---
#### Feedback Bot on 12/29/2022, 05:43 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment] 2022-12-30 17:29
Duplicate of https://github.com/dotnet/aspnetcore/issues/42839

**Closed by javiercn** 2022-12-30 17:29 UTC
Labels: area-mvc, Author: Migration Bot :robot:, feature-runtime-compilation
