### ISSUE TITLE
Your documentation horrible and needs a complete restructuring and rewrite

### ISSUE THREAD

**Issue by Prajwal-Jadhav** [dotnet/aspnetcore#33398] opened 2021-06-09 12:38 UTC
_I know this isn't the Docs repository but you need to be aware of the issue._

There are lots of issues with ASP.NET Core documentation so I will highlight few.

**1. The structure:**

**_Why do we need two **tutorials** for every project type?!!_**  
  
Here's one at Tutorials > Razor Pages
    
![razor1](https://user-images.githubusercontent.com/52888509/121351542-853b8c80-c949-11eb-9f4c-49578567e58f.png)

  
  
   _Here's one at Web Apps > Razor Pages > Tutorial_

![razor2](https://user-images.githubusercontent.com/52888509/121351567-8e2c5e00-c949-11eb-896c-5a94d9c4b7dd.png)

  
  
My problem is it forces us to follow the sample app they are building and not give us the quick docs and info we want.
  
<br/>
<br/>
     
You guys seriously need to learn from Django how to build a [well structured documentation](https://docs.djangoproject.com/en/3.2/contents/). Amazing that a non-profit builds a better documentation than a billion dollar company. Is it because you are too focused on adding new features that you forgot how important docs are? Or is it because you don't have enough (and competent) people who can design and write clear documentation?

<br/>
<br/>

**2. Search Engine Optimization**

The docs site sucks at SEO. Even when I type right keywords it never shows me the correct page in the docs. Never. This might be the direct consequence of horrible structure and relying on tutorial style docs. Every time I have to read through pages and pages to get to the real thing. Ditch the tutorial style docs and this will be a lot better.

<br/>

Please take a look at Django docs and learn how to structure documentations. Your current docs may be good enough for people with experience in ASP.NET who work in a enterprise environment where they have seniors advising them, but it is absolutely unacceptable (not to mention, frustrating) for people new to the ASP.NET Core.

<br/>

**Seriously, learn from Django docs**

**Comment by blowdart** [comment] 2021-06-09 13:25
Did you file an issue in the docs repo at all?

**Comment by Prajwal-Jadhav** [comment] 2021-06-09 13:31
@blowdart yes i did.

**Comment by blowdart** [comment] 2021-06-09 13:41
Then this is a dupe of https://github.com/dotnet/AspNetCore.Docs/issues/22521 so closing

**Closed by blowdart** 2021-06-09 13:41 UTC
