### ISSUE TITLE
Different behavior on json parsing errors in mvc and minimal apis

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/aspnetcore#41459] opened 2022-05-01 11:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In minimal Apis when something goes wrong while parsing JSON body it just throws an exception. The request doesn't even come to the handler.

```c#
builder.MapPost("/route/", CreateRequest request => ...);

public record CreateRequest(
        string Title,
        bool Completed,
        DateTime? Deadline);
```

If an invalid JSON is provided in the request body it just throws an exception right away.
```
{
  "title": "string",
  "completed": "string",
  "deadline": "2022-05-01T11:15:31.907Z"
}
```
```
Microsoft.AspNetCore.Http.BadHttpRequestException: Failed to read parameter "CreateRequest request" from the request body as JSON.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to CreateRequest. Path: $.completed
```
So there is nothing i can do to send some information about error because the request doesn't reach the handler

### Expected Behavior

In this case, controllers handle the scenario very well. The controller will run the action with an error message in the ModeStateDictionary.

### .NET Version

6.0.300

**Comment by davidfowl** [comment] 2022-05-02 16:12
@ziaulhasanhamim What logic do you want to write in the handler?

**Comment by ziaulhasanhamim** [comment] 2022-05-03 07:39
Maybe a helpful message to the user

**Comment by captainsafia** [comment] 2022-05-03 23:06
This request is related to https://github.com/dotnet/aspnetcore/issues/35501.

Closing as a dupe of that one.

**Closed by captainsafia** 2022-05-03 23:06 UTC
Labels: area-web-frameworks
