### ISSUE TITLE
Version 16.11.3 broke something.  New warnings appear!

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#36736] opened 2021-09-20 05:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Version-16113-broke-something--New-wa/1530521)._

---
[regression] [worked-in:16.11.2]
Severity	Code	Description	Project	File	Line	Source	Suppression State
Warning	CS8032	An instance of analyzer Microsoft.Extensions.Internal.ComponentInternalUsageDiagnosticAnalyzer cannot be created from C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\Sdks\Microsoft.NET.Sdk.Web\analyzers\cs\Microsoft.AspNetCore.Components.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..	CubiShippingDashboardAPI		1	IntelliSense	Active

! [image.png] (https://aka.ms/dc/image?name=Bbe8c3a02fd6b4110989faeffa9a26b47637673142157779076_20210915-214954-image.png&tid=be8c3a02fd6b4110989faeffa9a26b47637673142157779076)

---
#### Feedback Bot on 9/16/2021, 02:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-09-20 16:19
Thanks for contacting us. This is a dupe of #36552

**Closed by mkArtakMSFT** 2021-09-20 16:19 UTC
Labels: area-blazor, analyzer, Author: Migration Bot :robot:
