### ISSUE TITLE
Razor page not escaping @ in attributes

### ISSUE THREAD

**Issue by Muchiachio** [dotnet/aspnetcore#38595] opened 2021-11-23 15:40 UTC
Trying to escape @ in razor's html attribute results in two @@ being written. Using single @ doesn't work either, because it switches back to C# context. Repro can be found [here](https://github.com/Muchiachio/EtaHandler).

### Example
```Razor
@{
    string domain = "com";
}

<author mail-domain="@@company.@domain">John Freyman</author>
```

### Expected
```HTML
<author mail-domain="@company.com">John Freyman</author>
```

### Actual
```HTML
<author mail-domain="@@company.com">John Freyman</author>
```

### Workaround
```Razor
@{
    string domain = "com";
}

<author mail-domain="@("@")company.@domain">John Freyman</author>
```

**Comment by javiercn** [comment] 2021-11-23 16:52
@Muchiachio thanks for contacting us.

I believe this might be a dupe of https://github.com/dotnet/aspnetcore/issues/15045#issuecomment-966502884 or related.

@NTaylorMullen do you have thoughts here, since I don't remember what the transition was there.

**Comment by NTaylorMullen** [comment] 2021-11-23 20:34
> @NTaylorMullen do you have thoughts here, since I don't remember what the transition was there.

I don't 😢

**Closed** 2021-11-25 17:04 UTC
Labels: bug, area-razor.compiler
