### ISSUE TITLE
Append Hashes To Blazor Published Files

### ISSUE THREAD

**Issue by elepner** [dotnet/aspnetcore#47575] opened 2023-04-05 14:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When one deploys Blazor application to CDN the application sometimes fails to load because integrity check fails. That happens because there's significant delay between deployment and CDN content update. There's little room to control how the updated files propagate.

### Describe the solution you'd like

The ultimate (and maybe only) solution to this problem would be to attach hash to every file name like bundlers in JS Frameworks  do. It can be hash of the file or hash connected to the build itself. Here's example of Angular production build:
![image](https://user-images.githubusercontent.com/3992180/230118977-d2f9d49a-d834-4d59-b50e-7563eeaef86f.png)
I know it's possible to implement DIY solution for that, but it's something that would be nice to have in Blazor by default for everyone.

**Comment by SteveSandersonMS** [comment] 2023-04-05 16:06
Thanks for the suggestion, @elepner.

It could be more complicated than just changing the filenames, though. If the images (etc) had their filenames changed, what would happen to code like `<img src="someimage.png"/>` or `@include url('somefile.css')` in CSS?

Would you need to change all your existing code to work with this?

**Comment by elepner** [comment] 2023-04-06 15:42
As far as I know, modern JS bundlers are capable of tracking all dependencies, including images and replace URLs with the correct hashed ones. However, executables download is the most critical issue since the app just fails to load and there's little room for manoeuvre.

**Comment by SteveSandersonMS** [comment] 2023-04-06 15:45
The issue is that there isn't a JS bundler involved here. These references appear inside `.razor` files, for example, which are processed by the Razor compiler not by a JS bundler.

**Comment by elepner** [comment] 2023-04-06 18:28
I fully understand that, I'm just pointing out how the other frameworks address other types of assets. It'd require from Blazor builder to keep the graph of static asset dependencies, but I suppose this feature is beyond the scope this feature request.

**Comment by SteveSandersonMS** [comment] 2024-01-24 10:43
@javiercn Is this a dupe of https://github.com/dotnet/aspnetcore/issues/52824? If so can we close it?

**Comment by codymullins** [comment] 2024-02-04 04:45
+1 here, we've seen this intermittently and it's not an ideal user experience

**Comment by mkArtakMSFT** [comment] 2024-07-08 18:26
@javiercn should this be cloased already (as done) ?

**Comment by javiercn** [comment] 2024-08-13 09:11
This is now done.

**Closed by javiercn** 2024-08-13 09:11 UTC
Labels: enhancement, area-blazor, feature-static-web-assets, Priority:1, Pillar: Technical Debt

**Comment by thomasbach-dk** [comment] 2024-10-25 08:46
> This is now done.

What exactly is done? Can you refer to the pull request solving this? Will this be backported to .NET 8?

I cannot find any code related to this issue - only doc related stuff:
![Image](https://github.com/user-attachments/assets/06cfb32f-9e33-4160-a142-8dc66238c56c)
