### ISSUE TITLE
`dotnet watch` (hot reload) does not set property `DotNetWatchBuild` or `DOTNET_WATCH`

### ISSUE THREAD

**Issue by zbecknell** [dotnet/aspnetcore#38296] opened 2021-11-11 16:36 UTC
### Describe the bug
When running `dotnet watch` in 6.0, the `DotNetWatchBuild` property is not set, nor is `DOTNET_WATCH` set, and any attempt to pass custom properties or even use `/bl` (like `dotnet watch -- build /bl`) to see what is available reverts `dotnet watch` to its old rebuild behavior, which DOES set `DOTNET_WATCH`.

I just want to be able to disable a target when hot reload is active, as I finally found that a particular target breaks hot reload for me.

### Further technical details
- SDK 6.0.100

**Comment by pranavkm** [comment] 2021-11-11 19:24
Thanks @zbecknell for the issue report. This is a dupe of https://github.com/dotnet/aspnetcore/issues/35838 and there's an ongoing PR for it that we are considering: https://github.com/dotnet/sdk/pull/21722.

**Closed by pranavkm** 2021-11-11 19:24 UTC
Labels: area-commandlinetools, feature-dotnetwatch, feature-hot-reload
