### ISSUE TITLE
.NET 6 - blazor-hotreload.js is missing from _framework folder

### ISSUE THREAD

**Issue by erecord** [dotnet/aspnetcore#35194] opened 2021-08-08 10:54 UTC
SDK: .NET 6 Preview 6 

### Steps to reproduce

1. Create a blazorwasm project
2. Run `dotnet watch` command (hot reload enabled appears in the logs) 
3. Visit the app in a web browser
4. 'An unhandled error has occured'. 

The network tab shows a 404 for the `http://localhost:5000/_framework/blazor-hotreload.js` file.
The file is missing when I look in the bin/Debug/net6/wwwroot/_framework folder.

Occurred in a Linux docker container as well as on a native windows 10 environment without docker.

Is it possible to be given access to `blazor-hotreload.js` and manually place it in _framework myself as a workaround?

Thank you

**Comment by mkArtakMSFT** [comment] 2021-08-10 16:39
Thanks for contacting us. Can you please confirm that this is still the case with the latest .NET 6 preview 7 release (it's being released as I type :) ).

**Comment by erecord** [comment] 2021-08-11 20:22
I updated the SDK to .NET 6 Preview 7 and also updated the .csproj packages (below) to the preview 7 versions:

- Microsoft.AspNetCore.Components.WebAssembly
- Microsoft.AspNetCore.Components.WebAssembly.DevServer

The first time I started the application it did not start successfully. Here is the log output:

```
watch : Polling file watcher is enabled
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + Shift + R" to restart.
watch : Building...
  Determining projects to restore...
  Restored /src/frontend.csproj (in 267 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  frontend -> /src/bin/Debug/net6/frontend.dll
  frontend (Blazor output) -> /src/bin/Debug/net6/wwwroot
watch : Started
Cannot use file stream for [/src/bin/Debug/net6/frontend.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/src/bin/Debug/net6/'.     
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/src/bin/Debug/net6/frontend.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/src/bin/Debug/net6/frontend.runtimeconfig.json' file and specify the appropriate framework.
watch : Exited with error code 131
watch : Waiting for a file to change before restarting dotnet...
```


However, simply restarting the application a second time allowed it to start successfully. 
The log output is reproducible if I delete my obj folder and restart the application.

When I access the app in a browser I no longer get the 'blazor-hotreload.js missing' error, **so this issue is technically resolved**. Although the hotreload feature is not working for me when I update the increment value in the counter example.

Thanks for the response :)

**Comment by sofiageo** [comment] 2021-08-25 14:30
This is also working for me. I've had the issue in the past (I only made a question about it on reddit - [Link](https://www.reddit.com/r/Blazor/comments/nbbdhh/can_i_use_blazor_with_daily_net_build/) because I wasn't sure it was a bug back then. With Preview 7 it works when I start Blazor wasm from the command line. I used to run it through Jetbrains Rider to bypass the issue but still work with preview SDKs which for some reason worked.

However Hot-Reload is not working which I assume it's normal since it's not done yet. I get the following output when changing a file:

`watch : Caught top-level exception from hot reload: System.TimeoutException: The operation has timed out.
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyDeltaApplier.Apply(DotNetWatchContext context, String changedFile, ImmutableArray`1 solutionUpdate, CancellationToken cancellationToken) in dotnet-watch.dll:token 0x600017d+0x14b
   at Microsoft.DotNet.Watcher.Tools.CompilationHandler.TryHandleFileChange(DotNetWatchContext context, FileItem file, CancellationToken cancellationToken) in dotnet-watch.dll:token 0x600018c+0x6a6
   at Microsoft.DotNet.Watcher.Tools.HotReload.TryHandleFileChange(DotNetWatchContext context, FileItem file, CancellationToken cancellationToken) in dotnet-watch.dll:token 0x60001a0+0x1a4
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken) in dotnet-watch.dll:token 0x6000094+0x58f
watch : Killing process 7804
`

**Comment by elylv** [comment] 2021-11-10 17:46
@mkArtakMSFT this might be related to #35555 which has been closed, but I still have the same issue in VS2022 with .NET 6 release (I have changed application base, and it's looking for /_framework/blazor-hotreload.js from the root of the application, instead of the actual base, e.g. /wwwroot/MyBase/_framework/blazor-hotreload.js)

**Comment by Stratster** [comment] 2021-11-15 12:44
We have the same issue as @elylv described above

**Comment by ldsenow** [comment] 2021-11-29 00:34
me too. However, the hot reload feature somehow is working for a custom root base application (Running on ctrl + F5). I am just having a 404 error on the path of /abc/_framework/blazor-hotreload. The hotreload.js is loaded and it is looking to load some resource from the previous path. It sounds magical to me when I see the hotreload applies my changes.

**Comment by jord-w** [comment] 2021-11-30 21:33
Can confirm I am also still having this issue in .NET 6 Blazor WASM project that is using a custom application base url.

**Comment by WilStead** [comment] 2022-01-18 19:27
I believe this is caused by line 11 of `blazor-hotreload.js`:

```js
const response = await fetch('_framework/blazor-hotreload', { headers });
```

Commit 365a9c4 partially fixed this issue by initially loading the module from `"/_framework/blazor-hotreload.js"` (notice the leading "/"). The script itself is missing the leading slash, though, so the internal fetch still incorrectly uses the base path, and gets the 404.

**Comment by Dunge** [comment] 2022-03-04 00:15
Same with everything up to date (VS 17.2.0 Preview and NET SDK 6.0.200). My Blazor WASM is hosted on a extra path base. Can't get hot reload to work, always give 404.

**Closed** 2022-05-03 02:00 UTC
Labels: area-blazor, blazor-wasm
