### ISSUE TITLE
Blazor analyzer for non-existing property

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/aspnetcore#39167] opened 2021-12-23 12:51 UTC
Currently if is pass attribute to component which do not have matching property it is throw exception in runtime. This is annoying because for example during refactoring parameter cannot be safely removed.

Similarly as with `EditorRequired` will be nice to have analyzer which detect this type of error during compile time.

```
 TestComponent.razor
...
[Parameter]
public bool TestA { get; set; }
..

```

```
Page.razor
..
<TestComponent TestB="false" /> ---> should provide some sort of check during development
...
```

**Comment by pranavkm** [comment] 2021-12-27 17:33
Dupe of https://github.com/dotnet/aspnetcore/issues/25813.

**Closed by pranavkm** 2021-12-27 17:33 UTC
Labels: area-blazor
