### ISSUE TITLE
Incorrect nullability warning for razor files

### ISSUE THREAD

**Issue by skyflyer** [dotnet/aspnetcore#38252] opened 2021-11-10 11:05 UTC
### Describe the bug

Compiler (`dontet build`) issues `warning CS8602: Dereference of a possibly null reference.` even though the null checks in a CSHTML file are present. It seems that warning is emitted when tag helper (`<a asp-for...`) is used, but not otherwise.

### To Reproduce

The minimalistic reproduction is available here: https://github.com/skyflyer/net6-nullable-repro

The following CSHTML produces this warning even though the check for `Model != null` is in place:

N.B.: line 11 triggers the error while line 7 does not.

```cshtml
@model HomeViewModel
@{
    ViewData["id"] = Model?.Number;
}

@if(Model != null) {
    <text>@Model.Number</text>
    @foreach (var asset in Model.Assets){}
    <a href="#">foobar</a>
    <a asp-action="CreateAsset" asp-route-id="@Model?.Number" class="btn btn-primary">Create a new asset</a>

    @foreach (var asset in Model.Assets)
    {
            <td>@asset.InventoryNumber</td>
            <td>@asset.Name</td>
            <td>@asset.Description</td>
            <td class="table-action text-end">
                <form method="POST">
                    <input type="hidden" name="RowVersion" value="@asset.RowVersion" />
                    <input type="hidden" name="AgentAvsNumber" value="@Model.Number"/>
                    <a asp-action="EditAsset" asp-route-id="@asset.Id" asp-route-agentAvsNumber="@Model.Number" class="btn btn-icon px-1">
                        <i class="icon icon-pencil"></i>
                    </a>
                    <button asp-action="DeleteAsset" asp-route-id="@asset.Id" class="btn-sm btn btn-link px-1 are-you-sure" type="submit">
                        <i class="icon icon-trash"></i>
                    </button>
                </form>
            </td>
    }
}
```

### Further technical details
- ASP.NET Core version: 6.0.0.
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS Code with omnisharp, but IDE is irrelevant; the problem is visible when running `dotnet clean && dotnet build`
- Include the output of `dotnet --info`:
- The issue was reproduced on Mac OS (x64) and Windows 10 (x64)

<details>
  <summary>dotnet --info Output</summary>

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100-preview5-011568 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.112 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]
  3.1.406 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  3.1.415 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]
  5.0.402 [/usr/local/share/dotnet/sdk]
  5.0.403 [/usr/local/share/dotnet/sdk]
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

</details>

## Additional questions

* Since turning off nullability checks is not an option, is there a way to tell the compiler/framework that view models are not nullable? (is there a `View()` overload that would help here?
* Is there a way to disable nullability checks for CSHTML (views) only?

**Comment by pranavkm** [comment] 2021-11-10 14:08
> Since turning off nullability checks is not an option, is there a way to tell the compiler/framework that view models are not nullable? (is there a View() overload that would help here?

Yup, something we'd like to look at for 7.0. In the meanwhile, the workaround that works best is to use a base type for view that does not have a null model property: https://github.com/dotnet/aspnetcore/issues/37510#issuecomment-943573122

> Is there a way to disable nullability checks for CSHTML (views) only?

Unfortunately not. More frustratingly, because Razor's code-gen generates a bunch of `nullable restore`, it's difficult to even annotate individual files with pragmas on a per-file basis.

**Comment by skyflyer** [comment] 2021-11-10 15:36
Thank you 🙏 for the pointer @pranavkm, appreciate it! The workaround works, even though it is cumbersome. I'm surprised that such a big issue will have to wait until 7.0 (it seems quite problematic IMHO).

I'm assuming that the bug described here will be addressed sooner than 7.0 though...

**Comment by CarbonAtom** [comment] 2021-11-17 16:30
> Yup, something we'd like to look at for 7.0. In the meanwhile, the workaround that works best is to use a base type for view that does not have a null model property: [#37510 (comment)](https://github.com/dotnet/aspnetcore/issues/37510#issuecomment-943573122)

This seems like having Model nullable on every view when it is not is undesirable behavior in general. After switching to 6.0, every view that uses Model now results in warnings. Its strange this survived through RC to full release, I imagine this produces hundreds of warnings for other developers. 

Given that views now have inconsistent and incorrect null warnings requiring suppression or unnecessary null checks and 6 is LTS, shouldn't this behavior be at the very least reversed rather than having a custom RazorPageOfT (I am assuming it is causing the problem) for every view?

**Comment by mkArtakMSFT** [comment] 2021-12-16 17:59
Thanks for contacting us. Closing this as a dupe of #37510

**Closed by mkArtakMSFT** 2021-12-16 17:59 UTC
Labels: area-razor.compiler
