### ISSUE TITLE
Improvement to virtualize component

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#28921] opened 2020-12-30 16:46 UTC
I would like the ability in some cases where one more object can be put in memory somehow which is some type of elementreference.  Which would allow being able to scroll to a certain element even with virtualize.

Currently, unless the item is on the page, then does not work.  If a person did not use virtualize, then would work with no problem but then has the performance problems because so many elements are on the page.

There can be certain use cases where they click a button or even type something and it would scroll to that part of the list.  Would be disappointing if a person was forced to not use virtualize and have the performance penalty for it.

**Comment by mkArtakMSFT** [comment] 2021-01-05 17:43
Thanks for contacting us. This looks like a dupe of #26943

**Closed by mkArtakMSFT** 2021-01-05 17:43 UTC
Labels: area-blazor
