### ISSUE TITLE
Circular dependency error when publishing webdeploy package using .net 5.0.300

### ISSUE THREAD

**Issue by davidsk** [dotnet/aspnetcore#35134] opened 2021-05-30 14:59 UTC
I am getting the following error when I try and generate a webdeploy package using .net 5:
C:\Program
```
Files\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk.Publish\targets\CopyTargets\Microsoft.NET.Sdk.Publish.CopyFiles.targets(80,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "Publish". Since "_CopyAspNetCoreFilesToIntermediateOutputPath" has "DependsOn" dependence on "Publish", the circular is "Publish<-_CopyAspNetCoreFilesToIntermediateOutputPath<-CorePublish<-DotNetPublish<-_PublishBuildAlternative<-Publish"
```
Repro steps:
dotnet new mvc -n mvcApp
cd mvcApp
dotnet restore
dotnet publish /p:WebDeployMethod=package /p:DeployOnBuild=true;

expected result:
Web Deploy Package produced

actual result:
Microsoft (R) Build Engine version 16.10.0+4242f381a for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  mvcApp -> C:\Temp\mvcApp\bin\Debug\net5.0\mvcApp.dll
  mvcApp -> C:\Temp\mvcApp\bin\Debug\net5.0\mvcApp.Views.dll
C:\Program Files\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk.Publish\targets\CopyTargets\Microsoft.NET.Sdk.Publish.CopyFiles.targets(80,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "Publish". Since "_CopyAspNetCoreFilesToIntermediateOutputPath" has "DependsOn" dependence on "Publish", the circular is "Publish<-_CopyAspNetCoreFilesToIntermediateOutputPath<-CorePublish<-DotNetPublish<-_PublishBuildAlternative<-Publish". [C:\Temp\mvcApp\mvcApp.csproj]

This seems to be similar to https://github.com/dotnet/sdk/issues/16474 but I'm not using Visual Studio.  dotnet clean doesn't seem to help.

**Comment by javiercn** [comment] 2021-08-07 10:58
@vijayrkn this seems to be related to some of the targets [here](https://github.com/dotnet/sdk/blame/c53c8ac81e1bcb8118c31bc4f5622396c72e9959/src/WebSdk/Publish/Targets/CopyTargets/Microsoft.NET.Sdk.Publish.CopyFiles.targets#L67-L81)

Can you take a look?

**Comment by vijayrkn** [comment] 2021-08-09 15:16
@davidsk - The `deployOnBuild` property is only applicable for `dotnet build`. When set to true, this means that the bits should be also published as a part of build. This property is not applicable for `dotnet publish` since the primary purpose of this command is to publish. So, if you remove the property during publish, it should work and should provide you the expected output. Hope this helps.

**Comment by Kaelum** [comment] 2021-08-09 16:21
@vijayrkn & @davidsk I just tried it using `publish` w/o the `-p:DeployOnBuild=true` option, and it does build, but that is all that it does, it does not publish at all.  It appears that it is only using `PublishProfile` option for building the solution, and doesn't actually perform any of the publish actions.

When using `build` with both options, it both builds and publishes.  I reported this well over 3 years ago in another issue, that I have since lost track of.  There we talked about how using MSBuild directly works properly, but the coding inside of `dotnet` that uses MSBuild is very broken.

**Comment by Pilchie** [comment] 2021-08-11 20:31
@vijayrkn ?

**Comment by vijayrkn** [comment] 2021-08-11 21:01
@Kaelum - The publish option without the `deployOnBuild` flag should ideally publish. Let me get a sample uploaded to GitHub with the right command to see how your apps behavior is different. I will hopefully get to it in a day. Sorry for the tardiness here.

**Comment by Kaelum** [comment] 2021-08-11 21:18
@vijayrkn here is a scrubbed version of one of our PublishProfile files (the one I referenced previously):

```XML
<?xml version="1.0" encoding="utf-8"?>
<!--
This file is used by the publish/package process of your project. You can customize the behavior of this process
by editing this MSBuild file. In order to learn more about this please visit https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <PublishProvider>FileSystem</PublishProvider>
    <LastUsedBuildConfiguration>Debug-Publish</LastUsedBuildConfiguration>
    <LastUsedPlatform>x64</LastUsedPlatform>
    <PublishSingleFile>False</PublishSingleFile>
    <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <ProjectGuid>[scrubbed]</ProjectGuid>
    <SelfContained>true</SelfContained>
    <_IsPortable>false</_IsPortable>
    <publishUrl>..\.publish\ACME.debug.linux-x64\</publishUrl>
    <DeleteExistingFiles>True</DeleteExistingFiles>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <Content Update="ApplicationSettings.json;appsettings.json;NLog.config">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
```
If I look into the /bin folder of the project that contains this file, I do see a folder that contains the files that should be published, but those files are not published per the settings of this file.  That is the part that is broken, as I believe you are using the wrong parameters when calling MSBuild.

**Comment by vijayrkn** [comment] 2021-08-11 23:29
@Kaelum - Now I see the issue.  `dotnet publish` honors the property PublishDir instead of PublishUrl. 

So, you can just change the above pubxml to have this instead and you should see it publish properly. 
`		<PublishDir>..\.publish\ACME.debug.linux-x64\</PublishDir>`

```
C:\Users\vramak\source\repos\WebDeployTestApp\WebDeployTestApp>dotnet publish /p:PublishProfile=PublishToLinuxFolder
Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  WebDeployTestApp -> C:\Users\vramak\source\repos\WebDeployTestApp\WebDeployTestApp\bin\Debug\net5.0\linux-x64\WebDeployTestApp.dll
  WebDeployTestApp -> C:\Users\vramak\source\repos\WebDeployTestApp\WebDeployTestApp\bin\Debug\net5.0\linux-x64\WebDeployTestApp.Views.dll
  WebDeployTestApp -> C:\Users\vramak\source\repos\WebDeployTestApp\.publish\ACME.debug.linux-x64\
```

Hope this helps.

**Comment by Kaelum** [comment] 2021-08-11 23:50
@vijayrkn that is something that I am not comfortable changing, as that is directly tied to the Visual Studio Tooling.  We are using the Visual Studio Tooling to create and modify these files, and if we change the name of the element, the Visual Studio Tooling will no longer function properly.  Is there a reason why the `dotnet publish` code is not also looking at `<PublishUrl>`, while the `dotnet build` code is?  Seeing as how it is working with `dotnet build` and `MSBuild`, it would seem that the issue is with `dotnet publish`.

@Pilchie this is obviously a much larger discussion, which appears to be a desync between the different teams.  I spent 3 months last year discussing this with the people working on `dotnet build`, `dotnet publish`, and `MSBuild`, in order to get this work-around that we are using today, and I don't really want to go through that all over again.  If you guys could communicate with all of those involved, it would be very much be appreciated.

**Comment by vijayrkn** [comment] 2021-08-11 23:57
@Kaelum - If you feel uncomfortable replacing the property, you can always add this as an additional property 

```
		<publishUrl>..\.publish\ACME.debug.linux-x64\</publishUrl>
		<PublishDir>$(PublishUrl)</PublishDir>
```

With this both CLI & VS will work happily. 

I agree that having the difference in the property name can be confusing. The reason VS still uses publishUrl is because VS has always honored this property even before the dotnet cli tools were ever built.  Web publishing has been a concept in VS before the CLI tool era. 


Having said that, I can see how dotnet publish honoring this additional property can reduce the confusion for existing profiles created from VS or otherwise.

**Comment by Kaelum** [comment] 2021-08-12 00:23
@vijayrkn I'll try that tomorrow.  Thank you very much!

**Comment by Pilchie** [comment] 2021-08-20 15:54
@Kaelum any updates here?

**Comment by Kaelum** [comment] 2021-08-20 18:11
@Pilchie sorry, I've been a little busy.  Adding that line does not work, as it brings back the circular dependency if this issue.

**Comment by vijayrkn** [comment] 2021-08-20 19:06
@Kaelum - Yes. please don't use 'deployOnBuild' with publish. This property is supposed to be used with Build when you also want deploy to happen as a part of build. 

'DeployOnBuild' on publish is not relevant since you are stating your intention by using the publish verb already.

**Comment by Pilchie** [comment] 2021-09-09 18:30
Is there more to do here, or should this be closed?  @vijayrkn - should we doc the above guidance?

**Comment by vijayrkn** [comment] 2021-09-09 19:59
@Pilchie - The only other option outside of documenting would be for sdk to inherently support `PublishUrl` along with `PublishDir`. 

@dsplaisted - do you have concerns if sdk were to support the PublishDir through either of these properties?

**Comment by dsplaisted** [comment] 2021-09-09 20:31
It sounds like maybe we should generate a better error if you try to publish with `DeployOnBuild` set to true, as that's always going to fail (at least with the Web SDK).  Is this correct?

> do you have concerns if sdk were to support the PublishDir through either of these properties?

Defaulting the value of `PublishDir` to `PublishUrl`, basically?  That seems fine, although the devil might be in the details (especially with respect to evaluation order and the pubxml file).

I don't really understand, though.  It sounds like the UI in VS was always setting `PublishUrl`, but that never had an effect?  Wouldn't we have run into this earlier?

**Comment by vijayrkn** [comment] 2021-09-09 20:39
@dsplaisted - The issue is the other way. WebSDK does support both `PublishUrl` (for backward compat) & `PublishDir` but NetSDK only supports `PublishDir`. 

The reason WebSDK supports `PublishUrl` is because this was the recommended way to set the publish path for web applications before the `dotnet cli` was built.

**Comment by dsplaisted** [comment] 2021-09-09 20:44
OK, I've filed #36343 for the PublishDir / PublishUrl issue.

**Comment by Pilchie** [comment] 2021-09-09 20:50
Sounds good - I'm going to close this at this point.

**Closed by Pilchie** 2021-09-09 20:50 UTC
Labels: External
