### ISSUE TITLE
Enable using the Blazor WebAssembly loading progress indicator in a Blazor Web App

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#51510] opened 2023-10-20 01:52 UTC
In Blazor WebAssembly apps we provided a loading progress indicator that acted as placeholder while the app loaded. Once the app loaded, the loading progress indicator would get replaced with the app content. It doesn't appear that we have a way to define placeholder content for root components anymore with the Blazor Web App model. This issue tracks coming up with a way to enable this scenario again.

**Comment by SteveSandersonMS** [comment] 2023-10-20 10:13
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/49056 (closed) but it's reasonable to keep this open to track changing this in the future if we want. Please see that other issue for more thoughts about what would be involved in changing this.

**Comment by danroth27** [comment] 2023-10-20 15:40
> This is a duplicate of #49056 (closed) but it's reasonable to keep this open to track changing this in the future if we want. Please see that other issue for more thoughts about what would be involved in changing this.

There are a lot more details in #49056, so let's reopen it and close this one as the dup.

**Closed** 2023-10-21 16:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved
