### ISSUE TITLE
Adding a format to input=time causes issues

### ISSUE THREAD

**Issue by sbuchok** [dotnet/aspnetcore#13322] opened 2019-08-21 23:25 UTC
<input type="time" @bind="MyTimeSpan" @bind:format="HH:mm tt" />

Throws an error saying that you can't use TimeSpan as the type, it must be DateTime. If you remove @bind:format it works, but you can't specify your format.

**Comment by dougbu** [comment] 2019-08-22 16:58
@sbuchok thank you for your feedback. We're closing this issue as the behaviour discussed is by design.

### Details
A `TimeSpan` would not be appropriate for a specific time. That is, `type='time'` is not for use with durations. See
- https://www.w3.org/TR/html52/sec-forms.html#time-state-typetime (includes links to the bullet just below)
- https://www.w3.org/TR/html52/infrastructure.html#time
- https://www.w3.org/TR/html52/infrastructure.html#durations (completely separate from the above and not supported in `<input/>` elements)

**Comment by sbuchok** [comment] 2019-08-22 17:54
Ok, that's odd. You guys have it working for TimeSpan if there is no @bind:format specified. So I'm confused, does it work with TimeSpan or doesn't it. You are saying that it doesn't yet, without format it does. Is this a mistake that it works partially with TimeSpan?

Does this also mean that you expect us to only use DateTime as the type for type="time"?

**Comment by sbuchok** [comment] 2019-08-22 19:05
Also, DateTime has TimeOfDay, this is a TimeSpan that indicates the time since midnight (I believe). So, if the time portion of DateTime is a TimeSpan, why would we not use TimeSpan for the type to use for the type="time" input? It also doesn't make sense to use DateTime for an input where the type="time" as the date portion is useless. 

For my situation, I store a time in SQL, pull it out into a TimeSpan in C# and use that as the time for the input. It doesn't make sense that I would take the time stored in SQL and bring it back as a DateTime as I don't care about the date. So now, what is the point of having a time type if there is no matching object to put into C#?

**Comment by dougbu** [comment] 2019-08-22 19:15
> So, if the time portion of DateTime is a TimeSpan, why would we not use TimeSpan for the type to use for the type="time" input?

The `TimeOfDay` property is a little odd and, again, is a duration (since midnight as you mention) and not a time. What we support is formatting `DateTime` and `DateTimeOffset` values to mask out what doesn't apply for just dates and times.

> this also mean that you expect us to only use DateTime as the type for type="time"?

`DateTime` or `DateTimeOffset` are the supported datatypes.

**Comment by sbuchok** [comment] 2019-08-22 23:06
Just another note, if you use the Time type in SQL, the data type returned to C# is a TimeSpan. I now need to either use DateTime in SQL (which doesn't make sense for what I'm doing) or I need to convert the TimeSpan that is returned from SQL to a DateTime object. All of this is because TimeSpan isn't supported for either the input type="time" or for proper JSON serialization (this is a separate bug that someone else has already logged).

Also, DateTime doesn't seem to work. I'll log a separate bug for that with a blazorfiddle

Ultimately, I think this is wrong. SQL returns TimeSpan for Time type. To me, that means that input type="time" should as well for consistency. Or, SQL Time type should return DateTime to C#. 

Thanks for the conversation, I hope that this can get more consistent in the future and maybe C# can get a proper Time type.

**Comment by sbuchok** [comment] 2019-08-22 23:15
Last thing, honest. TimeSpan does work with the type="time" and works better than DateTime does. The only thing that doesn't work for TimeSpan is bind:format. DateTime however doesn't really work at all:
https://github.com/aspnet/AspNetCore/issues/13357

This just adds to the confusion as to what is supposed to work and what isn't.

**Comment by sbuchok** [comment] 2019-08-22 23:40
More confusion. This ticket someone says that DateTime isn't supported but that TimeSpan is:

https://github.com/aspnet/AspNetCore/issues/13357

**Comment by mathisloge** [comment] 2019-12-10 19:01
so, with the 3.1 release, it wont bind to a timespan anymore

**Comment by mkArtakMSFT** [comment] 2022-10-19 22:35
We've decided that using `DateOnly` and `TimeOnly` are a better fit for this scenario.

**Closed by mkArtakMSFT** 2022-10-19 22:35 UTC
Labels: enhancement, area-blazor, affected-few, severity-major, feature-blazor-component-model
