### ISSUE TITLE
When building the entire aspnetcore repo (i.e. inside the VMR) desktop msbuild is chosen

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/aspnetcore#58985] opened 2024-11-15 15:35 UTC
When building aspnetcore inside the VMR, desktop msbuild is being used which is required to build installers. The logic which msbuild engine to use lives here: https://github.com/dotnet/aspnetcore/blob/eb68e016a554b4da50d7fb0aeffe897cfabf36c7/eng/build.ps1#L317-L323

It might be ok to build the entire repository with desktop msbuild but ideally only the parts that need the desktop engine should build with it. Runtime does that which works really fine. Arcade already has a script that handles shelling out to desktop msbuild.

cc @wtgodbe

**Comment by wtgodbe** [comment] 2024-11-26 19:11
I think this is a dupe of https://github.com/dotnet/aspnetcore/issues/59151 at this point, closing

**Closed by wtgodbe** 2024-11-26 19:11 UTC
Labels: area-infrastructure
