### ISSUE TITLE
/_framework/aspnetcore-browser-refresh.js not found

### ISSUE THREAD

**Issue by robi26** [dotnet/aspnetcore#39888] opened 2022-01-31 12:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I would like to reopen the issue #35291 
The /_framework/aspnetcore-browser-refresh.js is still (using latest version) not found if the app is running in IISExpress mode and on a virtual directory. Repro steps as described in #35291 (blazor server)
When running the app in dotnet mode, the file is found.
Thanks

### Expected Behavior

File /_framework/aspnetcore-browser-refresh.js should be found when app is running in IISExpress mode and having a virtual directory.

### Steps To Reproduce

See #35291

### .NET Version

6.0.101

**Comment by javiercn** [comment] 2022-01-31 14:31
@robi26 thanks for contacting us.

@pranavkm I imagine this is external and something we should route to the web tools folks?

**Comment by mkArtakMSFT** [comment] 2022-01-31 17:36
Thanks for contacting us, @robi26.
This is a dupe of https://github.com/dotnet/aspnetcore/issues/39762

**Closed by mkArtakMSFT** 2022-01-31 17:36 UTC
Labels: External, area-blazor, blazor-wasm, feature-hot-reload
