### ISSUE TITLE
Make default app discriminator the same as it was in .net 5 so decryption works when upgrade to .net 6

### ISSUE THREAD

**Issue by JohnnyFun** [dotnet/aspnetcore#39070] opened 2021-12-15 22:51 UTC
Consider trimming the end slash in `Microsoft.AspNetCore.DataProtection.Internal.HostingApplicationDiscriminator` usage of `_hostEnvironment.ContentRootPath`. It had no trailing slash in .net 5 in my case, so when I upgraded to .net 6, I couldn't decrypt data that had been encrypted with .net 5.

Or, since that would technically be a breaking change, could just document here: https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio

See https://stackoverflow.com/questions/70355858/upgraded-from-dotnet-5-to-6-getting-error-when-decrypting-the-computed-authent

**Comment by Tratcher** [comment] 2021-12-15 23:06
Duplicate of https://github.com/dotnet/aspnetcore/issues/38274

**Comment by JohnnyFun** [comment] 2021-12-15 23:10
Oh sorry--didn't see that one in my searches. Feel free to close.

**Closed** 2021-12-15 23:11 UTC
Labels: area-dataprotection, api-suggestion
