### ISSUE TITLE
[NativeAOT] - IL trimming warnings. 

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/aspnetcore#40315] opened 2022-02-19 15:24 UTC
While publishing an empty web app (https://github.com/ShreyasJejurkar/NativeAOT-play/tree/main/WebTest) project, I got the below warnings. Interestingly it does work if I visit the HTTP port, but it fails when visiting the HTTPS port, but the following warnings are not related to HTTPS thing. 
```
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync<TValue>(HttpResponse,!!0,JsonSerializerOptions,String,CancellationToken): Using member 'System.Text.Json.JsonSerializer.SerializeAsync<TValue>(Stream,TValue,JsonSerializerOptions,CancellationToken)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Routing.DefaultInlineConstraintResolver.DefaultInlineConstraintResolver(IOptions`1<RouteOptions>,IServiceProvider): Using member 'Microsoft.AspNetCore.Routing.RouteOptions.get_ConstraintMap()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The linker cannot determine what constraints are being added via the ConstraintMap property. Prefer RouteOptions.SetParameterPolicy instead for setting constraints. This warning can be suppressed if this property is being used to read of delete constraints. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext): Using member 'System.Diagnostics.DiagnosticSource.Write(String,Object)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The type of object being written to DiagnosticSource cannot be discovered statically. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider.StaticWebAssetManifest.Parse(Stream): Using member 'System.Text.Json.JsonSerializer.Deserialize<StaticWebAssetManifest>(Stream,JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Routing.DefaultParameterPolicyFactory.Create(RoutePatternParameterPart,String): Using member 'Microsoft.AspNetCore.Routing.RouteOptions.get_ConstraintMap()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The linker cannot determine what constraints are being added via the ConstraintMap property. Prefer RouteOptions.SetParameterPolicy instead for setting constraints. This warning can be suppressed if this property is being used to read of delete constraints. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsyncSlow<TValue>(Stream,!!0,JsonSerializerOptions,CancellationToken): Using member 'System.Text.Json.JsonSerializer.SerializeAsync<TValue>(Stream,TValue,JsonSerializerOptions,CancellationToken)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider.OSBasedCaseConverter.Write(Utf8JsonWriter,Dictionary`2<String,StaticWebAssetNode>,JsonSerializerOptions): Using member 'System.Text.Json.JsonSerializer.Serialize<Dictionary`2<String,StaticWebAssetNode>>(Utf8JsonWriter,Dictionary`2<String,StaticWebAssetNode>,JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.ReadFromJsonAsync(HttpRequest,Type,JsonSerializerOptions,CancellationToken): Using member 'System.Text.Json.JsonSerializer.DeserializeAsync(Stream,Type,JsonSerializerOptions,CancellationToken)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider.OSBasedCaseConverter.Read(Utf8JsonReader&,Type,JsonSerializerOptions): Using member 'System.Text.Json.JsonSerializer.Deserialize<IDictionary`2<String,StaticWebAssetNode>>(Utf8JsonReader&,JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConfigurationReader.ParseSslProcotols(IConfigurationSection): Using member 'Microsoft.Extensions.Configuration.ConfigurationBinder.Get<String[]>(IConfiguration)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. In case the type is non-primitive, the trimmer cannot statically analyze the object's type so its members may be trimmed. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Certificates.Generation.CertificateManager.CertificateManagerEventSource.ListCertificatesStart(StoreLocation,StoreName): Using member 'System.Diagnostics.Tracing.EventSource.WriteEvent(Int32,Object[])' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. EventSource will serialize the whole object graph. Trimmer will not safely handle this case because properties may be trimmed. This can be suppressed if the object is a primitive type. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
```
How to reproduce 
Clone this repo => https://github.com/ShreyasJejurkar/NativeAOT-play. Navigate to WebTest and execute `dotnet publish -c Release -r win-x64` and watch console. 

There are other warnings as well, this above is more specific to the aspnetcore side!

**Comment by ShreyasJejurkar** [comment] 2022-02-19 15:26
The same warning we get while publishing, I guess this is the reason why requests to HTTPS fail but HTTP works flawlessly! 
https://github.com/dotnet/runtime/issues/65613

**Comment by pranavkm** [comment] 2022-02-20 00:49
@JamesNK

**Comment by hez2010** [comment] 2022-02-20 13:20
> The same warning mentioned in below issue, we get while publishing

That's not the same issue. The issue in https://github.com/dotnet/runtime/issues/65613 is because of the lack of abstract SIM support in ilc, while the issue here is about type preservation.

**Comment by ShreyasJejurkar** [comment] 2022-02-20 13:43
@hez2010 does this also does not belong to the aspnetcore side? 
```
ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsyncSlow<TValue>(Stream,!!0,JsonSerializerOptions,CancellationToken): Using member 'System.Text.Json.JsonSerializer.SerializeAsync<TValue>(Stream,TValue,JsonSerializerOptions,CancellationToken)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
```

**Comment by hez2010** [comment] 2022-02-20 13:49
> @hez2010 can these types of warnings belong to the aspnetcore side?
> 
> ```
> ILC : Trim analysis warning IL2026: Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsyncSlow<TValue>(Stream,!!0,JsonSerializerOptions,CancellationToken): Using member 'System.Text.Json.JsonSerializer.SerializeAsync<TValue>(Stream,TValue,JsonSerializerOptions,CancellationToken)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [E:\opensource\NativeAOT-play\WebTest\WebTest.csproj]
> ```

Yes. And for now, you may workaround it via writing rd.xml.

**Comment by ShreyasJejurkar** [comment] 2022-02-20 13:53
Not sure what does that means, quite new to NativeAOT stuff. It tried to address the issue, by using `JsonTypeInfo` overload as that as error messages tell, but I wasn't unable to compiler it properly, as I was new to that type also! 
So I thought let me create an issue regarding this, as the team has more experience with this stuff.

**Comment by hez2010** [comment] 2022-02-20 13:58
> Not sure what does that means, quite new to NativeAOT stuff.

It's documented in https://github.com/dotnet/runtime/tree/main/src/coreclr/nativeaot/docs.

> It tried to address the issue, by using JsonTypeInfo overload as that as error messages tell, but I wasn't unable to compiler it properly, as I was new to that type also!

You may ignore those warning messages during compilation and try to run the compiled binary.

If you're seeing `MissingRuntimeArtifactException` at the runtime, you'll need to create a rd.xml and preserve the type or method mentioned in the exception message.

**Comment by ShreyasJejurkar** [comment] 2022-02-20 14:00
> > It tried to address the issue, by using JsonTypeInfo overload as that as error messages tell, but I wasn't unable to compiler it properly, as I was new to that type also!
> 
> You may ignore those warning messages during compilation and try to run the compiled binary.
> 
> If you're seeing `MissingRuntimeArtifactException` at the runtime, you'll need to create a rd.xml and preserve the type or method mentioned in the exception message.

So there is nothing we can do from the code side, to avoid these warnings in the first place!?

**Comment by hez2010** [comment] 2022-02-20 14:08
> So there is nothing we can do from the code side, to avoid these warnings in the first place!? 

Most of trimming issues can be avoided, but some of them can't because not all dynamic invocations can be statically analyzed during compilation.

**Comment by JamesNK** [comment] 2022-02-23 21:19
Trimming isn't officially supported in .NET 6.

Fixing trimming warnings will happen in .NET 7 - https://github.com/dotnet/aspnetcore/issues/27384

**Comment by JamesNK** [comment] 2022-02-23 21:19
Duplicate of https://github.com/dotnet/aspnetcore/issues/27384

**Closed by JamesNK** 2022-02-23 21:19 UTC
Labels: area-runtime, linker-friendliness
