### ISSUE TITLE
.NET 6 Server has already started

### ISSUE THREAD

**Issue by TropicalThunder** [dotnet/aspnetcore#34209] opened 2021-07-08 18:31 UTC
Perhaps it's not an issue with .NET 6, but I cannot see what's causing the problem in my project. 
```
public class Program
{
  public static async Task Main(string[] args)
  {
	  await CreateHostBuilder(args).Build().RunAsync();
  }

  public static IHostBuilder CreateHostBuilder(string[] args) =>
	  Host.CreateDefaultBuilder(args)
		  .ConfigureWebHostDefaults(webBuilder =>
		  {
			  webBuilder.UseStartup<Startup>()
			  .UseAzureAppServices()
			  .UseSetting(WebHostDefaults.DetailedErrorsKey, "true");
		  }).ConfigureLogging(logging =>
		  {
			  logging.AddFilter("Microsoft.AspNetCore.SignalR", LogLevel.Debug);
			  logging.AddFilter("Microsoft.AspNetCore.Http.Connections", LogLevel.Debug);
		  });
}
```

### Describe the bug
Whenever I start any of my .NET 6 projects the RunAsync() throws an exception stating that the server has already started.

### To Reproduce

Unfortunately, this works fine in a clean .NET 6 project. But upgrading a massive .NET 5 project results in this behavior. Running our Blazor UI throws this exception, running our Hangfire workers throws this exception and the API is also affected. 

### Exceptions (if any)

Server has already started from "Microsoft.AspNetCore.Server.Kestrel.Core"

   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<StartAsync>d__29`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MYPROJECT.UI.Program.<Main>d__0.MoveNext() in C:\DevOps\MY-PROJECT\Program.cs:line 18

### Further technical details
- ASP.NET Core version
 .NET 6 preview 5
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
This issue happens in both Visual Studio 2022 preview 1.1 and 2019 (latest version). Tried running in Release mode, same issue.

**Comment by davidfowl** [comment] 2021-07-08 18:35
Duplicate of https://github.com/dotnet/aspnetcore/issues/33763

**Comment by TropicalThunder** [comment] 2021-07-08 18:36
@davidfowl my searching skills must be so bad since I didn't find that myself. Thank you so much!

**Closed** 2021-07-16 20:21 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-runtime
