### ISSUE TITLE
WithSummary and WithDescription deson't work in minimal api

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/aspnetcore#45082] opened 2022-11-14 17:57 UTC
Hi,
I have a minimal api in .net 7, I used `WithSummary()` and `WithDescription()` bur it doesn't generate anything in swagger ui!

``` csharp
app.MapGet("/api/v{version:apiVersion}/weatherforecast/byid", () => { return new List<string>(); })
    .WithApiVersionSet(weatherforecasts)
    .HasApiVersion(1.0)
    .HasApiVersion(2.0)
    .WithName("weatherforecast-byid")
    .WithTags("WeatherForecast")
    .WithSummary("summary002")
    .WithDescription("description002");
```

**Comment by captainsafia** [comment] 2022-11-14 18:33
@mehdihadeli This is a dupe of https://github.com/dotnet/aspnetcore/issues/40753 and is blocked on https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2414 being merged.

As an alternative, I'd recommend using the `WithOpenApi` extension method which has more flexibility for setting values.

```csharp
app.MapGet("/api/v{version:apiVersion}/weatherforecast/byid", () => { return new List<string>(); }
  .WithOpenApi(operation => new(operation)
  {
    Summary = "Summary",
    Description = "Description"
  });
```

**Comment by mehdihadeli** [comment] 2022-11-14 19:12
@captainsafia Thanks for your response.
When I use `WithOpenApi`, with minimal api versioning with `.WithApiVersionSet(CustomersConfigs.VersionSet).HasApiVersion(1.0)` I get error.

**Comment by captainsafia** [comment] 2022-11-14 19:29
@mehdihadeli What's the error you get?

The `WithApiVersionSet` returns a custom version of the `IEndpointConventionBuilder` type that might not interop with the generic constraint on the builder type that exists in `WithOpenApi` method. Try calling `WithOpenApi` _before_ `WithApiVersionSet`.

**Comment by mehdihadeli** [comment] 2022-11-15 08:41
@captainsafia When I put `WithOpenApi()` after `HasVersion` and `WithApiVesionSet` I get this error

``` csharp
app.MapGet("/api/v{version:apiVersion}/weatherforecast/byid", () => { return new List<string>(); }
 .WithApiVersionSet("weatherforecast")
 .HasApiVersion(1.0)
  .WithOpenApi(operation => new(operation)
  {
    Summary = "Summary",
    Description = "Description"
  });
```

``` cmd
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.AspNetCore.Builder.IEndpointConventionBuilder.Finally(Action`1 finallyConvention)
   at Microsoft.AspNetCore.Builder.OpenApiEndpointConventionBuilderExtensions.WithOpenApi[TBuilder](TBuilder builder, Func`2 configureOperation)
   at Program.<Main>$(String[] args) in C:\Users\MehdiHadeli\Desktop\versoining\Program.cs:line 43
```
but when I move the `WithOpenApi` in the first, it works!

``` csharp
app.MapGet("/api/v{version:apiVersion}/weatherforecast/byid", () => { return new List<string>(); }
  .WithOpenApi(operation => new(operation)
  {
    Summary = "Summary",
    Description = "Description"
  })
 .WithApiVersionSet("weatherforecast")
 .HasApiVersion(1.0);
```

**Comment by captainsafia** [comment] 2022-11-15 16:21
> Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.AspNetCore.Builder.IEndpointConventionBuilder.Finally(Action`1 finallyConvention)
   at Microsoft.AspNetCore.Builder.OpenApiEndpointConventionBuilderExtensions.WithOpenApi[TBuilder](TBuilder builder, Func`2 configureOperation)

Aha! @commonsensesoftware I think you might have to update the builders in Asp.Versioning to implement the new `Finally` method.

**Comment by mehdihadeli** [comment] 2022-11-16 11:50
@commonsensesoftware Hi,
No, it is .Net 7.0.0 stable version.

**Comment by mehdihadeli** [comment] 2022-11-16 17:22
@commonsensesoftware Thanks for your response. I'm waiting for fixing this issue in next minor versions of .net 7 :)

**Comment by mehdihadeli** [comment] 2022-11-17 10:31
@commonsensesoftware `WithOpenApi()` method with [Asp.Versioning.Http/7.0.0-preview.1](https://www.nuget.org/packages/Asp.Versioning.Http/7.0.0-preview.1) and .Net 7 with any orders (before or after other operations) works great.
Thanks :)

**Comment by captainsafia** [comment] 2022-11-17 17:02
Thanks! Closing this issue out now.

There's a PR out on Swashbuckle to support the summary and description methods that's waiting on merge and release.

Other than that, I think everything is resolved here.

**Closed** 2022-11-17 17:02 UTC
Labels: External, feature-openapi, area-web-frameworks

**Comment by mehdihadeli** [comment] 2022-11-17 19:15
@captainsafia Thanks
