### ISSUE TITLE
.NET 6 Blazor IBrowserFile's OpenReadStream().ReadAsync(buffer) not able to read all bytes

### ISSUE THREAD

**Issue by dougliu** [dotnet/aspnetcore#41875] opened 2022-05-26 17:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I upgrade my .NET 5.0 Blazor project to .NET 6 and find the  IBrowserFile's OpenReadStream().ReadAsync(buffer) not able to read all bytes anymore.
I have to use while loop read smaller size to handle it in .NET 6.

### Expected Behavior

I expect  IBrowserFile's OpenReadStream().ReadAsync(buffer) can read all bytes as it doesn't in .NET 5.

### Steps To Reproduce

I made a simple .NET 5 Blazor page using Visual Studio 2022 https://github.com/dougliu/UpdateNet6FileUploadReadAsyncIssue
it will show all bytes can be read for file size larger than 1 MB.
But, by simple upgrade project framework to .NET 6, it can only read less than 96K.

### .NET Version

.NET 5 migrate to .NET 6

**Comment by TanayParikh** [comment] 2022-05-26 18:26
> and find the IBrowserFile's OpenReadStream().ReadAsync(buffer) not able to read all bytes anymore.

`OpenReadStream` has a maximum default file size of 500kb. Please see [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.ibrowserfile.openreadstream?view=aspnetcore-6.0#parameters).

> Calling [OpenReadStream(Int64, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.ibrowserfile.openreadstream?view=aspnetcore-6.0#microsoft-aspnetcore-components-forms-ibrowserfile-openreadstream(system-int64-system-threading-cancellationtoken)) will throw if the file's size, as specified by [Size](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.ibrowserfile.size?view=aspnetcore-6.0#microsoft-aspnetcore-components-forms-ibrowserfile-size) is larger than maxAllowedSize. By default, if the user supplies a file larger than 500 KB, this method will throw an exception.
>
> It is valuable to choose a size limit that corresponds to your use case. If you allow excessively large files, this may result in excessive consumption of memory or disk/database space, depending on what your code does with the supplied [Stream](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream).
>
> For Blazor Server in particular, beware of reading the entire stream into a memory buffer unless you have passed a suitably low size limit, since you will be consuming that memory on the server.

**Comment by dougliu** [comment] 2022-05-26 21:05
No, it doesn't get the point.
The issue is IBrowserFile's ReadAsync method works under .NET 5, but it only read small part of it under .NET 6. I guess that 
OpenReadStream(maxFileSize).ReadAsync(buffer)  ignore the maxFileSize under .NET 6 as it showed in my sample code. I made a simple .NET 5 Blazor page using Visual Studio 2022 https://github.com/dougliu/UpdateNet6FileUploadReadAsyncIssue
it will show all bytes can be read for file size larger than 1 MB as it is NET 5 framework.
But, by simple upgrade project framework to .NET 6 in Visual Studio 2022, it can only read less than 96K, totally ignored the maxFileSize.

**Comment by TanayParikh** [comment] 2022-05-26 21:08
@dougliu do you have a sample file I can try your repo with? Please add it to the github repo if so.

**Comment by dougliu** [comment] 2022-05-26 21:11
or
private long maxFileSize = 1024 * 1024 * 15;
    private string message = String.Empty;

    private async Task FileLoad(InputFileChangeEventArgs e)
    {
        var file = (IBrowserFile)e.File;

        if(file != null)
        {
            var buffer = new byte[file.Size];
            var length = await file.OpenReadStream(maxFileSize).ReadAsync(buffer);

            message = "Read " + length + " bytes; File size = " + file.Size;
        }
        StateHasChanged();
    }

**Comment by dougliu** [comment] 2022-05-26 21:27
I checked in a file named judicialapplication.pdf as a sample file to the repo.

**Comment by MackinnonBuck** [comment] 2022-06-01 21:09
Thanks for the repro, @dougliu.

I'm going to close this since it appears to be a duplicate of #38842. Using the provided repro, if you wait long enough after loading the file, a `System.TimeoutException` is thrown just like the one documented in the other issue.

**Closed by MackinnonBuck** 2022-06-01 21:09 UTC
Labels: investigate, area-blazor, blazor-server
