### ISSUE TITLE
Quarantine LongPollingUsesHttp2ByDefault

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/aspnetcore#49966] opened 2023-08-09 20:18 UTC
## Failing Test(s)

- Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.LongPollingUsesHttp2ByDefault

## Error Message

```text
[0.088s] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: Test threw an exception.
2023-08-09T19:13:12.3353023Z [xUnit.net 00:00:58.58]         | Xunit.Sdk.ContainsException: Assert.Contains() Failure
2023-08-09T19:13:12.3418894Z [xUnit.net 00:00:58.58]         | Not found: (filter expression)
2023-08-09T19:13:12.3419003Z [xUnit.net 00:00:58.58]         | In value:  ConcurrentQueue<WriteContext> 
```

## Stacktrace

<details>

```text
at Xunit.Assert.Contains[T](IEnumerable`1 collection, Predicate`1 filter) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 264
2023-08-09T19:13:12.3419336Z [xUnit.net 00:00:58.58]         |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.LongPollingUsesHttp2ByDefault() in /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubConnectionTests.cs:line 2402
2023-08-09T19:13:12.3419383Z [xUnit.net 00:00:58.58]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-08-09T19:13:12.3419409Z [xUnit.net 00:00:58.58]         | --- End of stack trace from previous location ---
2023-08-09T19:13:12.3419433Z [xUnit.net 00:00:58.58]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-08-09T19:13:12.3419456Z [xUnit.net 00:00:58.58]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
```
</details>

## Logs

<details>

```text
2023-08-09T19:13:12.3317612Z [xUnit.net 00:00:58.58]         | [0.088s] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: Test threw an exception.
2023-08-09T19:13:12.3353023Z [xUnit.net 00:00:58.58]         | Xunit.Sdk.ContainsException: Assert.Contains() Failure
2023-08-09T19:13:12.3418894Z [xUnit.net 00:00:58.58]         | Not found: (filter expression)
2023-08-09T19:13:12.3419003Z [xUnit.net 00:00:58.58]         | In value:  ConcurrentQueue<WriteContext> [Information Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer: Starting test server..., Debug Microsoft.Extensions.Hosting.Internal.Host: Hosting starting, Debug Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver: Repository contains no viable default key. Caller should generate a key with immediate activation., Debug Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: Policy resolution states that a new key should be added to the key ring., Information Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Creating key {148c2e55-1f64-4d76-b0cb-3fa38973c8c1} with creation date 2023-08-09 19:13:11Z, activation date 2023-08-09 19:13:11Z, and expiration date 2023-11-07 19:13:11Z., ...]
2023-08-09T19:13:12.3419298Z [xUnit.net 00:00:58.58]         |    at Xunit.Assert.Contains[T](IEnumerable`1 collection, Predicate`1 filter) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 264
2023-08-09T19:13:12.3419336Z [xUnit.net 00:00:58.58]         |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.LongPollingUsesHttp2ByDefault() in /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubConnectionTests.cs:line 2402
2023-08-09T19:13:12.3419383Z [xUnit.net 00:00:58.58]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-08-09T19:13:12.3419409Z [xUnit.net 00:00:58.58]         | --- End of stack trace from previous location ---
2023-08-09T19:13:12.3419433Z [xUnit.net 00:00:58.58]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-08-09T19:13:12.3419456Z [xUnit.net 00:00:58.58]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-08-09T19:13:12.3494334Z [xUnit.net 00:00:58.58]         | [0.090s] TestLifetime Information: Finished test LongPollingUsesHttp2ByDefault in 0.0894467s
2023-08-09T19:13:12.3543820Z [xUnit.net 00:00:58.59]   Finished:    Microsoft.AspNetCore.SignalR.Client.FunctionalTests
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=368651&view=ms.vss-test-web.build-test-results-tab&runId=7812532&resultId=123373&paneView=debug

**Comment by adityamandaleeka** [comment] 2023-08-09 20:18
@BrennanConroy

**Comment by BrennanConroy** [comment] 2023-08-18 16:31
Dupe of https://github.com/dotnet/aspnetcore/issues/50180, using that one for tracking.

**Closed by BrennanConroy** 2023-08-18 16:31 UTC
Labels: test-failure, area-signalr
