### ISSUE TITLE
Impossible to set a RenderFragment parameter to null from .razor syntax

### ISSUE THREAD

**Issue by JHBonarius** [dotnet/aspnetcore#30663] opened 2021-03-04 19:47 UTC
### Describe the bug
(This is a new attempt to describe one issue in https://github.com/dotnet/aspnetcore/issues/30534)

I have multiple third-party (i.e. I cannot modify) components that take multiple `RenderFragment` parameters. I will use a simplified example with only two RenderFragments:
```c#
@*Foo.razor*@
@if (Block1!=null)
{
    @Block1
} else {
    <...some other stuff...>
}
@if (Block2!=null)
{
    @Block2
} else {
    <...some other stuff...>
}
@code{
    [Parameter]
    public RenderFragment Block1 { get; set; }
    [Parameter]
    public RenderFragment Block2 { get; set; }
}
```
I want to be able to set each `RenderFragement` to have child content conditionally (based on some state) and `null` otherwise.

What I tried.

1)
```c#
<Foo>
    <Block1>
        @if (condition1)
        {
            <..some data..>
        }
    </Block1>
    <Block2>
        @if (condition2)
        {
            <..some data..>
        }
    </Block2>
</Foo>
```
But this doesn't work, as empty `RenderFragment`s are not the same as `null`.

2)
```c#
<Foo>
    @if (condition1)
    {
        <Block1>
            <..some data..>
        </Block1>
    }
    @if (condition2)
    {
        <Block2>
            <..some data..>
        </Block2>
    }
</Foo>
```
doesn't compile: `RZ9996 Unrecognized child content inside component 'Foo'. The component 'Foo' accepts child content through the following top-level items: 'Block'.`

3)
```c#
@if (!condition1 && !condition2)
{
    <Foo />
} else if (condition1 && !condition2)
{
    <Foo>
        <Block1>
            <..some data..>
        </Block1>
    </Foo>
} else if (!condition1 && condition2)
{
    <Foo>
        <Block2>
            <..some data..>
        </Block2>
    </Foo>
} else //if (condition1 && condition2)
    <Foo>
        <Block1>
            <..some data..>
        </Block1>
        <Block2>
            <..some data..>
        </Block2>
    </Foo>
}
```
works, has a lot of code duplication **and doesn't scale well**! It's O(2^N). This is just a simple example with 2 block = 4 possibilities. With 3 blocks its 8, with 4 -> 16 etc.

4)
```c#
<Foo Block1=@(condition1?<..some data...>:null) Block2=@(condition2?<...some data...>:null) />
```
This compiles, but doesn't work then either of the conditions are false: It will throw a `ArgumentException: Delegate to an instance method cannot have null 'this'.`

I consider the last code the best option, however it doesn't work due to a limitation in the razor source generator. Details on that can be found in https://github.com/dotnet/aspnetcore/issues/30534

### To Reproduce
See Code above

### Exceptions (if any)
`ArgumentException: Delegate to an instance method cannot have null 'this'.`

### Further technical details
- ASP.NET Core version: 5
- Include the output of `dotnet --info` : See https://github.com/dotnet/aspnetcore/issues/30534
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019 16

**Comment by SteveSandersonMS** [comment] 2021-03-08 19:07
@JHBonarius Thanks for the details.

In the short term, a quick (though not very pretty) workaround for you would be to render the `Foo` component via `DynamicComponent`. This would let you pass `null` for any of the `RenderFragment` parameters without interfering (or you could even conditionally exclude the parameter completely when you build the dictionary). `DynamicComponent` will ship in .NET 6, but until then, you can just add [its sources](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/DynamicComponent.cs) to your project.

Longer term, we need to figure out how to make the Razor compiler stop wrapping all delegate-typed parameters in `new DelegateType(...)`. The reason the compiler does this is to make intellisense and methodgroup-to-delegate conversion work properly. However I'm not clear on why this is the best way to do it, since it seems like we could use `TypeCheck<DelegateType>(...)` instead, like we do for other parameters. This requires more investigation and perhaps digging through the history about how we got here.

**Comment by mkArtakMSFT** [comment] 2021-04-20 17:46
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/23892

**Closed by mkArtakMSFT** 2021-04-20 17:46 UTC
Labels: area-blazor, area-razor.compiler, bug, feature-razor.language
