### ISSUE TITLE
Hot reload changes not applied for WebAssembly-rendered pages in Blazor Web app

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#50765] opened 2023-09-17 20:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Changes applied in WebAssembly-rendered pages during hot reload not applied.

### Expected Behavior

Hot reload successfully detects and applies changes in WebAssembly rendered pages.

### Steps To Reproduce

1. `dotnet new blazor -int WebAssembly -o BlazorWasmHotReload`
2. `dotnet watch --project BlazorWasmHotReload/BlazorWasmHotReload.csproj`
3. Modify `BlazorWasmHotReload.Client/Pages/Counter.razor`.
4. Observe output in the console.
```
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5260
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/captainsafia/tests/BlazorWasmHotReload/BlazorWasmHotReload
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
dotnet watch ⌚ File changed: ./BlazorWasmHotReload.Client/Pages/Counter.razor.
dotnet watch ⌚ No changes applied to client because they are not supported by the runtime.
dotnet watch 🔥 Hot reload of changes succeeded.
```
5. Observe browser registers successful hot reload event but no changes applied.
6. Refresh page.
7. Observe changes applied then reverted in browser.

### .NET Version

8.0.100-rc.2.23466.1

### Anything else?

Reproed on VS Code + `dotnet watch`.

```bash
dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.0-rc.2.23465.17 [/Users/captainsafia/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.0-rc.2.23464.16 [/Users/captainsafia/.dotnet/shared/Microsoft.NETCore.App]
```

```bash
$ dotnet --info
.NET SDK:
 Version:   8.0.100-rc.2.23466.1
 Commit:    d7b01118f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /Users/captainsafia/.dotnet/sdk/8.0.100-rc.2.23466.1/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23464.16
  Architecture: arm64
  Commit:       9cdbc87dad

.NET SDKs installed:
  8.0.100-rc.2.23466.1 [/Users/captainsafia/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.2.23465.17 [/Users/captainsafia/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23464.16 [/Users/captainsafia/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/Users/captainsafia/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mkArtakMSFT** [comment] 2023-09-19 17:04
@captainsafia isn't this fixed already?

**Comment by Claire-kangkang** [comment] 2023-09-20 07:47
hi @captainsafia @mkArtakMSFT I verified this issue with `8.0.100-rc.2.23469.4`.
1. I noticed the hot reload successfully and applied changes in webpage when modify `BlazorWasmHotReload\Components\Pages\Home.razor`, but the command line still output `No changes applied to client because they are not supported by the runtime`.
![image](https://github.com/dotnet/aspnetcore/assets/70516076/a3698e98-22be-4e61-9861-9a884030d5ab)

2. I tried to modify `BlazorWasmHotReload.Client/Pages/Counter.razor` according to the bug reproduce steps, still no changes applied in webpage when hot reload.

**Comment by mkArtakMSFT** [comment] 2023-09-21 23:02
@tmat , @thaystg this scenario has regressed recently. Can one of you please look into this and see what may have caused it? Thanks!

**Comment by captainsafia** [comment] 2023-09-25 21:26
@tmat I believe you need to be on .NET 8 RC 2 in order to use the new template flag. .NET 8 supports different render modes and `dotnet new blazor -int WebAssembly` allows you to create a template where the default render mode is WebAssembly.

**Comment by tmat** [comment] 2023-09-27 01:10
I'm seeing this exception in WASM:

![image](https://github.com/dotnet/aspnetcore/assets/41759/5ea97472-9fe4-4c3b-8bb8-b8f93aaff0fa)

**Comment by mkArtakMSFT** [comment] 2023-09-27 02:12
@MackinnonBuck what can be causing this?

**Comment by tmat** [comment] 2023-09-27 16:55
@captainsafia has repro with 8.0.100-rc.2.23466.1. There is no global.json for the project.

**Comment by captainsafia** [comment] 2023-09-27 19:50
@tmat Good spot! I can't recall if I saw that warning when I was reproing.

One question, it does appear that we define this API in our global exports:

https://github.com/dotnet/aspnetcore/blob/3dbfa81c7393b18e7ce1b4abb25c0c6f38616a89/src/Components/Web.JS/src/GlobalExports.ts#L94

And that export has changed throughout .NET 8 so I'm not sure why an undefined function would be the issue here...

**Comment by tmat** [comment] 2023-09-27 20:00
>  I can't recall if I saw that warning when I was reproing.

Unlikely since we swallowed that exception in browser-refresh.js. https://github.com/dotnet/sdk/pull/35755 addresses that.

**Comment by tmat** [comment] 2023-10-17 20:01
I'm now seeing this error, I'm guess it's the same issue:

```
dotnet watch ❌ Exception while reading WASM runtime capabilities: TypeError: Cannot read properties of undefined (reading '_internal')
    at getBlazorWasmApplyUpdateCapabilities (http://localhost:5019/_framework/aspnetcore-browser-refresh.js:101:47)
    at Object.BlazorRequestApplyUpdateCapabilities2 (http://localhost:5019/_framework/aspnetcore-browser-refresh.js:51:56)
    at connection.onmessage (http://localhost:5019/_framework/aspnetcore-browser-refresh.js:56:29)
```

**Comment by tmat** [comment] 2023-10-17 20:07
@MackinnonBuck Do we know what version of WASM is going to be loaded before it gets loaded?

**Comment by tmat** [comment] 2023-10-17 20:15
[3] should be possible, but will require changes to Roslyn, VS Web Tools and dotnet watch.

VS Web Tools caches the capabilities and also falls back to defaults if it fails to retrieve them from WASM, so that wouldn't work:
https://devdiv.visualstudio.com/DevDiv/_git/WebTools?path=/src/ProjectSystem/Web/HotReload/WASMDeltaApplier.cs&version=GBmain&line=43&lineEnd=44&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by MackinnonBuck** [comment] 2023-10-17 20:36
> @MackinnonBuck Do we know what version of WASM is going to be loaded before it gets loaded?

I don't think so - it might be theoretically possible to load and parse `blazor.boot.json` and infer the version based on the names of the dotnet JS modules referenced in that file, but that seems extremely fragile.

> VS Web Tools caches the capabilities and also falls back to defaults if it fails to retrieve them from WASM, so that wouldn't work

Just so I make sure I'm understanding, are you saying [4] wouldn't work because the initial set of capabilities returned from the browser gets cached by VS? Does that cache get cleared between hot reload sessions? If so, I think approach [4] would be an improvement in VS the same way it would when using `dotnet watch` in that if a new hot reload session starts and the WebAssembly hot reload capabilities were previously cached in the browser, then we will be able to fetch the correct capabilities before the WebAssembly runtime loads. But I do understand that this would not improve the experience for the first hot reload session, or if the browser cache gets cleared between sessions (I may not have been clear about that being a drawback in my previous comment).

**Comment by tmat** [comment] 2023-10-17 20:44
> Just so I make sure I'm understanding, are you saying [4] wouldn't work because the initial set of capabilities returned from the browser gets cached by VS?

I was thinking about [3], but yes, [4] would also not work every time for the same reason. 

It would be an improvement that would apply if you had the capabilities available from previous session at the start of the new session.

**Comment by MackinnonBuck** [comment] 2023-10-17 20:44
> I'm now seeing this error, I'm guess it's the same issue (project created with wasmbrowser template)

Hm, yeah the `wasmbrowser` template doesn't have any dependency on Blazor, so Blazor-specific hot reload functionality shouldn't even in that case. That looks like another bug we'd need to address.

**Comment by MackinnonBuck** [comment] 2023-10-17 20:50
@tmat Do you know what would happen if we used some set of default capabilities when we couldn't read them from WebAssembly? Would hot reload fail gracefully if an unsupported edit was made? I'm wondering if a potential solution [5] is to just have some hard coded set of capabilities that serves as a "best guess".

**Comment by tmat** [comment] 2023-10-17 20:51
The VS Tools delta applier has default set: https://devdiv.visualstudio.com/DevDiv/_git/WebTools?path=/src/ProjectSystem/Web/HotReload/WASMDeltaApplier.cs&version=GBmain&line=30&lineEnd=31&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

I think at this point we can assume that WASM has all capabilities.

**Comment by tmat** [comment] 2023-10-17 20:54
https://github.com/dotnet/runtime/blob/de098118c730bd2c1ac31a7a54e1bc80b7ad1d8c/src/mono/mono/component/hot_reload.c#L3559

I think that'd be the bast approach here. If we fail to get the capabilities from runtime return all these.

**Comment by MackinnonBuck** [comment] 2023-10-17 20:55
> dotnet watch assumes that when the project has WebAssembly in the ProjectCapability item group then it is either BlazorHosted or BlazorWebAssembly project, depending on whether or not it also has AspNetCore capability.

If that's the case, then I'm not sure why `wasmbrowser` gets picked up as a BlazorWebAssembly project. Maybe it also has the `AspNetCore` capability? That template isn't part of ASP.NET Core.

**Comment by MackinnonBuck** [comment] 2023-10-17 20:56
> https://github.com/dotnet/runtime/blob/de098118c730bd2c1ac31a7a54e1bc80b7ad1d8c/src/mono/mono/component/hot_reload.c#L3559
> 
> I think that'd be the bast approach here. If we fail to get the capabilities from runtime return all these.

I agree, that seems like the safest approach and it'll probably result in the best developer experience.

**Comment by MackinnonBuck** [comment] 2023-10-17 21:10
I'll start working on a fix for this!

**Closed** 2023-10-18 18:49 UTC
Labels: bug, area-blazor, feature-hot-reload
