### ISSUE TITLE
Blazor WebAssembly Application Insights

### ISSUE THREAD

**Issue by idizh** [dotnet/aspnetcore#18715] opened 2020-01-31 17:06 UTC
Can't find any article about connecting Blazor Wab Assembly to Application Insights. Tried default connector but it doesn't send any metrics. Also during creating instance of TelemetryClient application is hanging. Perhaps it's because HttpClient? Do not know(

**Comment by mkArtakMSFT** [comment] 2020-01-31 17:24
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by danroth27** [comment] 2020-01-31 17:25
Duplicate of #5461

**Closed by danroth27** 2020-01-31 17:25 UTC
Labels: External, area-blazor, blazor-wasm, enhancement
