### ISSUE TITLE
Thrown exception gets ignored when function is running with async/await

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#45393] opened 2022-12-01 14:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using advanced data-binding within a blazor app any thrown exception within the ValueChanged EventCallback are being ignored when the function uses the await keyword. 

For example:
```
<InputSelect Value="Input5.MyValue"
                 ValueChanged="async (int value) => await OnValueChanged5(value)"
                 ValueExpression="() => Input5.MyValue"
                 class="form-select">
        <option value="0">None</option>
        <option value="1">1. Option</option>
        <option value="2">2. Option</option>
        <option value="3">3. Option</option>
        <option value="4">4. Option</option>
    </InputSelect>
```
```

private async Task OnValueChanged5(int value)
    {
        throw new Exception();
        await Task.Delay(2000);
        Input5.MyValue = value;
    }
```

Calling the same code without async/await, the exception gets thrown as expected.

Async/Await seem to work though because I can run this code with success, as long as the code does not raise any exception:
```
 private async Task OnValueChanged5(int value)
    {
        await Task.Delay(2000);
        Input4.MyValue = 3;
    }
```

### Expected Behavior

I expect the exceptions beeing thrown just like in case 1 & 3.

### Steps To Reproduce

I've created a small repository which helds 5 different cases.
https://github.com/MarvinKlein1508/AdvancedBindingErrorSample

Case 1 & 3 are throwing the exception as expected. 
Case 2 & 5 are not throwing the exception
Case 4 shows that async funcationaltiy does work in general here.

### .NET Version

7.0.100

**Comment by MarvinKlein1508** [comment] 2022-12-01 14:37
I'Ve tested it on .nET 5 & 6 as well. Doesn't work their either.

**Comment by MarvinKlein1508** [comment] 2022-12-01 14:51
It looks like the result of `InvokeAsync `is never awaited for.
https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Components/Web/src/Forms/InputBase.cs#L78

**Comment by javiercn** [comment] 2022-12-01 16:19
@MarvinKlein1508 thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/44105

**Closed** 2022-12-01 16:19 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor
