### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by jer231** [dotnet/aspnetcore#36052] opened 2021-09-01 20:27 UTC
### Describe the bug
In a docker container using alpine linux, a simple dotnet 3.1 app that just fetches images from remote servers using HttpClient occasionally fails with the exception "The remote certificate is invalid according to the validation procedure".  Here is an image URL that will fail: https://ogden_images.s3.amazonaws.com/www.minotdailynews.com/images/2021/08/29205857/30-Darlene-Perkins-441x500.jpg
The same URL works fine in the same app using windows, and it can also be fetched just fine using curl from the same docker container. Other images that are also hosted at s3.amazonaws.com work fine too, so it is an issue with just that url. The only slightly suspicious thing I can see is that the offending url has a host name as a path segment ("/www.minotdailynews.com/"), but nothing wrong with that I think.

**Comment by jer231** [comment] 2021-09-01 21:10
Just found this https://github.com/dotnet/runtime/issues/35880, probably that pesky underscore in the domain name that is causing an issue I think

**Comment by adityamandaleeka** [comment] 2021-09-03 20:23
@jer231 Yea, it would appear you're hitting that. Closing this issue since it's actually a duplicate of that runtime issue and not an ASP.NET issue.

**Closed** 2021-09-03 20:23 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Status: Resolved
