### ISSUE TITLE
[Big Rock] Razor compiler should generate runtime code that is usable at design time

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#35395] opened 2021-08-16 18:39 UTC
Today Razor generates C# output for a given .cshtml or .razor file that’s understood at runtime; however, at tooling time the Razor parser generates a separate design time variant of it’s C# output. Because of this Razor work done at the C# layer in regards to editing, hot reload, compilation effectively needs to be done twice in VS. Typically you could say lets only do twice the work when “F5 debugging”; however, we want VS to also power the debug while not attached scenario. Because of this we consistently need to maintain multiple worlds of the C# universe in VS, something that’s already complex and heavy.

To accomplish this there are several issues that need to be done, some of which have already been done.

- [x] Generated line pragmas at runtime that directly map to generated code
- [ ] Programmatic source mappings need to be generated at runtime so design time code can provide an adequate editing experience
- [ ] Errored documents need to be more intelligent about what code is generated. Meaning as you type the generated C# should have better output to ensure we don't flood users with bad errors
- [ ] ....

**Comment by ShreyasJejurkar** [comment] 2021-10-31 04:42
This is has to be considered for .NET 7 for sure to further improving EnC or hot reload experience.

Because of this multiple files issues I guess sometimes hot reload does not work/behave as expected and am sure most of the people here have faced similar issues!

**Comment by mkArtakMSFT** [comment] 2021-11-30 19:19
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/30669

**Closed by mkArtakMSFT** 2021-11-30 19:19 UTC
Labels: enhancement, Components Big Rock, triaged, area-razor.compiler, Priority:1
