### ISSUE TITLE
Provide input arguments when calling OnParametersSet(Async) method

### ISSUE THREAD

**Issue by gparissis** [dotnet/aspnetcore#45516] opened 2022-12-09 18:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When we do page navigation, having load logic in the OnInitialized(Async) works as expected.
But when we do parameter navigation, OnOnitialized(Async) is not called anymore, so our next best option is the OnParametersSetAsync().
But this method is being called multiple times depending on changes, causing the code to be executed multiple times.

### Describe the solution you'd like

Is it possible to receive as an input argument the parameter that caused this time the OnParametersSet(Async) to be called?
Or, even better, can we have a flag that indicates if this is the last time that the OnParametersSet(Async) is being executed so that we can execute our code?
The best solution is to call the method only once, but for reasons I can't understand, it can't be done, as I have read multiple posts about this.

### Additional context

The way the method is implemented now is not convenient.
- The name is wrong, indicating that it will be called after all parameters are set.
- There is no reference to the parameter that triggered the execution.
- And since it is being executed multiple times, there is no indication of when it will stop.

Many thanks for considering my request.

**Comment by surayya-MS** [comment] 2023-01-03 17:23
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/13610

**Closed by surayya-MS** 2023-01-03 17:23 UTC
Labels: area-blazor, feature-rendering
