### ISSUE TITLE
error MSB3073 during build from command line

### ISSUE THREAD

**Issue by Omcsesz** [dotnet/aspnetcore#33771] opened 2021-06-22 22:30 UTC
Hello, Team!

When I'm running .\build.cmd, the script crashes.
### To Reproduce

1. Download the repo
2. Download pre-requisites
3. Execute third step to build project (https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md -> run .\build.cmd)

### Exceptions (if any)
`D:\github\aspnetcore\src\Framework\App.Ref\src\Microsoft.AspNetCore.App.Ref.csproj(245,5): error MSB3073: The command "tar -czf "D:\github\aspnetcore\artifacts\installers\Debug\aspnetcore-targeting-pack-6.0.0-dev.tar.gz" ." exited with code 9009.`
[log.txt](https://github.com/dotnet/aspnetcore/files/6697719/log.txt)

### Further technical details

  -  ASP.NET Core version : 5.0.7
  -  Include the output of dotnet --info: [dotnetinfo.txt](https://github.com/dotnet/aspnetcore/files/6697605/dotnetinfo.txt)
  -  The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Microsoft Visual Studio Community 2019, Version 16.10.2

**Comment by BrennanConroy** [comment] 2021-06-22 22:32
>  'tar' is not recognized as an internal or external command,

Looks like you don't have tar on the machine, or it isn't on the path.

**Comment by Omcsesz** [comment] 2021-06-22 22:56
@BrennanConroy I installed tar, and set the PATH variable accordingly.
Now I'm getting a different error:
[log.txt](https://github.com/dotnet/aspnetcore/files/6697823/log.txt)

**Comment by dougbu** [comment] 2021-06-24 22:17
@Omcsesz am I correct e858e3dabbe8 fixes this issue for you❔

**Comment by Omcsesz** [comment] 2021-06-25 09:30
@dougbu No, it does not.

**Comment by Omcsesz** [comment] 2021-06-25 09:31
The error message I get after I add tar to PATH, is this:
Zipping directory "D:\github\aspnetcore\artifacts\obj\TargetingPack.Layout\Debug\" to "D:\github\aspnetcore\artifacts\installers\Debug\aspnetcore-targeting-pack-6.0.0-dev.zip".
  Executing: tar -czf "D:\github\aspnetcore\artifacts\installers\Debug\aspnetcore-targeting-pack-6.0.0-dev.tar.gz" .
  tar (child): Cannot connect to D: resolve failed
  tar: D\:\\github\\aspnetcore\\artifacts\\installers\\Debug\\aspnetcore-targeting-pack-6.0.0-dev.tar.gz: Cannot write: Broken pipe
  tar: Child returned status 128
  tar: Error is not recoverable: exiting now

**Comment by Omcsesz** [comment] 2021-06-25 09:32
The error message I get after I add tar to PATH, is this:
```
Zipping directory "D:\github\aspnetcore\artifacts\obj\TargetingPack.Layout\Debug" to "D:\github\aspnetcore\artifacts\installers\Debug\aspnetcore-targeting-pack-6.0.0-dev.zip".
Executing: tar -czf "D:\github\aspnetcore\artifacts\installers\Debug\aspnetcore-targeting-pack-6.0.0-dev.tar.gz" .
tar (child): Cannot connect to D: resolve failed
tar: D:\github\aspnetcore\artifacts\installers\Debug\aspnetcore-targeting-pack-6.0.0-dev.tar.gz: Cannot write: Broken pipe
tar: Child returned status 128
tar: Error is not recoverable: exiting now
```

**Comment by dougbu** [comment] 2021-06-26 00:52
@Omcsesz which path for `tar` did you add❔ I ask because that error message makes it seem like the `tar` the build found doesn't understand Windows path syntax.

I can reproduce this problem using 'C:\Program Files\Git\usr\bin\tar.exe' and suspect Microsoft.AspNetCore.App.Ref.csproj and Microsoft.AspNetCore.App.Runtime.csproj need a bit of work to detect the `git` copy of `tar`. To confirm I'm on the right track, please

1. Remove the directory containing `tar` from your path
2. Run eng/scripts/InstallTar.ps1
3. Try the build again
4. Let me know how it goes 😃

**Comment by Omcsesz** [comment] 2021-06-26 11:43
> 
> 
> @Omcsesz which path for `tar` did you addgrey_question I ask because that error message makes it seem like the `tar` the build found doesn't understand Windows path syntax.
> 
> I can reproduce this problem using 'C:\Program Files\Git\usr\bin\tar.exe' and suspect Microsoft.AspNetCore.App.Ref.csproj ~and Microsoft.AspNetCore.App.Runtime.csproj~ need a bit of work to detect the `git` copy of `tar`. To confirm I'm on the right track, please
> 
>     1. Remove the directory containing `tar` from your path
> 
>     2. Run eng/scripts/InstallTar.ps1
> 
>     3. Try the build again
> 
1. done
2. when I run the script, I get the following message:

```
out-file : Could not find a part of the path 'D:\github\aspnetcore\eng\scripts\.tools\tar.fro
mGit'.
At D:\github\aspnetcore\eng\scripts\InstallTar.ps1:73 char:5
+     $null >.\.tools\tar.fromGit
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

**Comment by dougbu** [comment] 2021-06-26 18:54
On 2.: The script expects to be run from the repo root, not the eng/scripts/ folder. I guess it could be made easier to use e.g. by determining the repo root itself and using that rather than `.\` but it's usually run only in AzDO pipelines. For now, run it in the repo root.

**Comment by Omcsesz** [comment] 2021-06-26 19:19
> 
> 
> On 2.: The script expects to be run from the repo root, not the eng/scripts/ folder. I guess it could be made easier to use e.g. by determining the repo root itself and using that rather than `.\` but it's usually run only in AzDO pipelines. For now, run it in the repo root.

If I run the InstallTar.ps1 scripts from the repo root, it finishes correctly:

```
VERBOSE: Performing the operation "Copy File" on target "Item: C:\Program Files\Git\usr\bin\tar.exe Destina
tion: D:\github\aspnetcore\.tools\tar.exe".
Tar now available at 'D:\github\aspnetcore\.tools\tar.exe'
```

**Comment by Omcsesz** [comment] 2021-06-29 16:26
@dougbu any ideas?

**Comment by dougbu** [comment] 2021-06-29 19:28
> But after that, the build.cmd fails:&hellip;

I can't tell much from the error code but it at least implies the `git` version of `tar` isn't compatible w/ Windows 7. We may have used it to fill a gap in later Windows releases.

It may help to edit Microsoft.AspNetCore.App.Ref.csproj, adding `--verbose` to the command line and building again. But, I'm not sure how much more effort I can put into supporting a Windows version that has been out of support for about a year and a half.

> the InstallTar.ps1 did not update the PATH variable for me.

This is intentional because we avoid updating the users environment more than necessary and usually only when the user takes an explicit action e.g. `. ./activate.ps1`. The Microsoft.AspNetCore.App.Ref.csproj finds the `tar.exe` file in .tools/ automatically.

**Comment by Omcsesz** [comment] 2021-06-30 00:06
I ran

> 
> 
> > But after that, the build.cmd fails:…
> 
> I can't tell much from the error code but it at least implies the `git` version of `tar` isn't compatible w/ Windows 7. We may have used it to fill a gap in later Windows releases.
> 
> It may help to edit Microsoft.AspNetCore.App.Ref.csproj, adding `--verbose` to the command line and building again. But, I'm not sure how much more effort I can put into supporting a Windows version that has been out of support for about a year and a half.
> 
> > the InstallTar.ps1 did not update the PATH variable for me.
> 
> This is intentional because we avoid updating the users environment more than necessary and usually only when the user takes an explicit action e.g. `. ./activate.ps1`. The Microsoft.AspNetCore.App.Ref.csproj finds the `tar.exe` file in .tools/ automatically.

I ran the .\build.cmd with -v normal switch, and it finished without problems.

**Comment by dougbu** [comment] 2021-06-30 00:26
> I ran the .\build.cmd with -v normal switch, and it finished without problems.

My suggestion was to change https://github.com/dotnet/aspnetcore/blob/main/src/Framework/App.Ref/src/Microsoft.AspNetCore.App.Ref.csproj#L232
to include ` --verbose` at the end. Passing `-v` to `./build.cmd` only affects the PowerShell verbosity.

**Comment by dougbu** [comment] 2021-09-15 19:46
@Omcsesz thank-you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2021-09-15 19:46 UTC
Labels: area-infrastructure, Needs: Attention :wave:
