### ISSUE TITLE
Blazor wasm - Hot reload - EditForm issue

### ISSUE THREAD

**Issue by radderz** [dotnet/aspnetcore#33662] opened 2021-06-19 06:15 UTC
Hi,

I am using the recently released dotnet.6.0.0-preview.5.21301.5 bits

I have a larger blazor site, which debugs and runs normally when published. I am finding dotnet reload crashes at startup all the time. I started a fresh site and slowly migrated parts to find what was wrong and any time I had an EditForm with an InputText that was bound to a model it would crash straight away meaning I can't get the value of the new feature for hot changes show up on the fly.

the below is a simple razor file that triggers this issue on the default template (i.e. dotnet new blazorwasm -o Test). Add this razor page to any working solution, and try to navigate to it i.e. /form. And it'll blow up.

```
@page "/form"

@using System.ComponentModel.DataAnnotations

@if (Loading)
{
	<div>loading...</div>
}
else
{
	<br />
	<h2>Login</h2>
	@if (ShowErrors)
	{
		<div class="alert alert-danger" role="alert">
		 <p>@Error</p>
		</div>
	}

	<EditForm Model="loginModel" OnValidSubmit="HandleLogin">
        <DataAnnotationsValidator />
        <ValidationSummary />
		<div class="form-group">
			<label for="email">Email address</label>
			<InputText Id="email" @bind-Value="@loginModel.Email" />
		</div>
		<div class="form-group">
			<label for="password">Password</label>
			<InputText Id="password" @bind-Value="@loginModel.Password" />
		</div>
		<button type="submit" class="btn btn-whitelabelled">Submit</button>
	</EditForm>

}

@code {

	public class LoginModel
    {
        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        public bool RememberMe { get; set; }
    }

	private LoginModel loginModel = new LoginModel();
	private bool ShowErrors;
	private string Error = "";
	private bool Loading;

	async Task HandleLogin()
	{
		ShowErrors = false;

		Loading = true;

		await Task.Delay(2000);

		Loading = false;
	}
}
```

The only console errors I receive are below. with the default 

```
dotnet.6.0.0-preview.5.21301.5.js:1 * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1374, condition `<disabled>' not met

542256 @ dotnet.6.0.0-preview.5.21301.5.js:1
_emscripten_asm_const_int @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0xde854
(anonymous) @ 008a4f9a:0x190ec8
(anonymous) @ 008a4f9a:0x10693e
(anonymous) @ 008a4f9a:0x8a472
(anonymous) @ 008a4f9a:0xef24
(anonymous) @ 008a4f9a:0x7e88
(anonymous) @ 008a4f9a:0x56ee
(anonymous) @ 008a4f9a:0x682c3
(anonymous) @ 008a4f9a:0x10ebb9
(anonymous) @ 008a4f9a:0xedf7e
(anonymous) @ 008a4f9a:0x192fcc
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x9ab1
(anonymous) @ 008a4f9a:0x31b7b
(anonymous) @ 008a4f9a:0xd33b6
(anonymous) @ 008a4f9a:0x50675
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
mono_wasm_convert_return_value @ dotnet.6.0.0-preview.5.21301.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x193074
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
receiveHotReload @ blazor-hotreload.js:2
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
he._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
call_assembly_entry_point @ dotnet.6.0.0-preview.5.21301.5.js:1
callEntryPoint @ blazor.webassembly.js:1
ct @ blazor.webassembly.js:1
async function (async)
ct @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Show 4 more frames
localhost/:1 Uncaught (in promise) ExitStatus {name: "ExitStatus", message: "Program terminated with exit(0)", status: 0}
```

**Comment by radderz** [comment] 2021-06-19 06:17
dotnet watch run debug works btw, but this doesn't give the benefit of hot reload as it just reloads the whole page every change.

**Comment by weibaohui** [comment] 2021-06-19 08:49
same issue

**Comment by chucker** [comment] 2021-06-19 09:40
Simplified test case:

```html
@page "/form"

@using System.ComponentModel.DataAnnotations

<EditForm Model="loginModel">
    <div class="form-group">
        <label for="email">Email address</label>
        <InputText Id="email" @bind-Value="@loginModel.Email" />
    </div>
</EditForm>

@code {
    public class LoginModel
    {
        [Required]
        public string Email { get; set; }
    }

    private LoginModel loginModel = new LoginModel();
}
```

Something about `EditForm` seems to throw.

(There are no further messages in `dotnet watch --verbose`.)

**Comment by chucker** [comment] 2021-06-19 09:49
Guessing this is a dupe of https://github.com/dotnet/aspnetcore/issues/33319 and will be fixed in preview 6.

See also:

https://github.com/dotnet/aspnetcore/issues/33432#issuecomment-859011212

**Comment by radderz** [comment] 2021-06-20 20:42
> Guessing this is a dupe of #33319 and will be fixed in preview 6.
> 
> See also:
> 
> [#33432 (comment)](https://github.com/dotnet/aspnetcore/issues/33432#issuecomment-859011212)

@chucker I think you are right, I did search for a similar issue but I mustn't have included closed issues. It looks like that one does overlap with this one.

**Closed** 2021-06-20 20:42 UTC
Labels: area-blazor, blazor-wasm, feature-hot-reload
