### ISSUE TITLE
CS0234 : The type or namespace name '...' does not exist in the namespace '__Blazor....'

### ISSUE THREAD

**Issue by kefyru** [dotnet/aspnetcore#37482] opened 2021-10-12 10:04 UTC
```Razor
<Parent ItemsProvider="@_itemsProvider">
   <Child/>
</Parent>
```
where
```C#
[CascadingTypeParameter(nameof(T))]
public class Parent<T>: IComponent 
{
   [Parameter] 
   public IItemsProvider<T> ItemsProvider {get;set;}
}

public class Child<T>: IComponent {}
```

generated razor.g.cs:
```C#
public static void CreateParent_1_CaptureParameters<T>(
   global::MyApp.IItemsProvider<T> __arg0, 
   out global::MyApp.IItemsProvider<T> __arg0_out
) 
{
 __arg0_out = __arg0;
}

public static void CreateChild_2<T>(
   global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, 
   int seq, 
   MyApp.IItemsProvider<T> __syntheticArg0 // problem here: seems like lacks 'global::'
)
{
        __builder.OpenComponent<global::MyApp.Child<T>>(seq);
        __builder.CloseComponent();
}

```
DotNet6.RC1

**Comment by TanayParikh** [comment] 2021-10-20 22:40
Thanks for reporting, closing this out as duplicate of: https://github.com/dotnet/aspnetcore/issues/36326

**Closed** 2021-10-20 22:40 UTC
Labels: bug, :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved, area-razor.compiler
