### ISSUE TITLE
Admin -user registration using blazor server

### ISSUE THREAD

**Issue by shkar-dev** [dotnet/aspnetcore#42201] opened 2022-06-15 07:18 UTC
I want to create. A different login and registration page for admin and user in a different path how to achieve that is it possible

**Comment by javiercn** [comment] 2022-06-15 09:30
@shkar-dev thanks for contacting us.

This is a duplicate of https://github.com/dotnet/aspnetcore/issues/13601. Unfortunately, this is not a direction we plan to take. You might want to create your own or use a solution provided by a third-party.

**Closed** 2022-06-15 09:31 UTC
Labels: area-identity, area-blazor, blazor-server
