### ISSUE TITLE
Blazor InteractiveServer APP:[PackageId].lib.module.js in RCL cannot reflect change

### ISSUE THREAD

**Issue by cyuz** [dotnet/aspnetcore#58050] opened 2024-09-24 03:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In my RCL project, I register custom blazor event in wwwroot/[PACKAGE ID].lib.module.js
After months, I decide to  add another event in the js file.
But browser just use cached file.

After trace the source code, I found blazor import _content/[PACKAGE ID]/[PACKAGE ID].lib.module.js via {_environment.ApplicationName}.modules.json.

If I make a publish, I can modify the file via post-process.
But this is a RCL project, so I must tell every user to add post-process.
It's very inconvenient.

### Expected Behavior

1. _content/[PACKAGE ID]/[PACKAGE ID].lib.module.js update automatically
2. or add some API or mechanism to insert a tag version. e.g. _content/[PACKAGE ID]/[PACKAGE ID].lib.module.js?V=MyCustomVersion

### Steps To Reproduce

1. Create RCL Projects
2. Create wwwroot/[PACKAGE ID].lib.module.js
3. Write any thing in lib.modules.js
4. Create a blazor Project(Server/InteractiveRender) and reference RCL Project
5. Start blazor Project
6. Modify [PACKAGE ID].lib.module.js
7. Start Server agin
8. Check _content/[PACKAGE ID]/[PACKAGE ID].lib.module.js

### .NET Version

8.0.303

**Comment by javiercn** [comment] 2024-09-24 11:25
@cyuz thanks for contacting us.

This is already addressed in 9.0 with our fingerprinting feature, that creates unique URLs for all files based on the content.

**Comment by javiercn** [comment] 2024-09-24 11:25
Dupe of https://github.com/dotnet/aspnetcore/issues/54874

**Closed by javiercn** 2024-09-24 11:25 UTC
Labels: area-blazor
