### ISSUE TITLE
Blazor wasm: Reference Javascript function with IJSObjectReference

### ISSUE THREAD

**Issue by Socolin** [dotnet/aspnetcore#38517] opened 2021-11-19 02:17 UTC
### Describe the bug

When I'm trying to reference a javascript function in JS I'm getting this error.

```
Uncaught (in promise) Error: Cannot create a JSObjectReference from the value 'function () {
        console.log('Hello !');
}'.
```

### To Reproduce

In a `.js` file  put

```js
function funcReference() {
    return function () {
        console.log('Hello !');
    }
}
```

Then 

```cs
@inject IJSRuntime _jsRuntime
...
await _jsRuntime.InvokeVoidAsync("loadScript", "js/launcher-wrapper.js");
```

### Further technical details
- Version: 6.0

### Use case:

What I'm trying to achieve is to call a JS function from .NET and give it a callback to a .NET method.
Something like:

```js
function __simple_callback(name, dotnetReference) {
    return function () {
        console.log('in __simple_callback');
        dotnetReference.invokeMethodAsync(name, ...arguments);
    }
}
```

```cs
await _jsRuntime.InvokeVoidAsync("someJsMethod", DotNetObjectReference.Create(new {
    onError = await _jsRuntime.InvokeAsync<IJSObjectReference>("__simple_callback", "OnError")
});


[JSInvokable]
public void OnError(string message) {
  // Something
}
```

**Comment by javiercn** [comment] 2021-11-22 14:06
@Socolin thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/38517. Consider upvoting that issue instead

**Closed by javiercn** 2021-11-22 14:06 UTC
Labels: area-blazor, feature-blazor-jsinterop

**Comment by Socolin** [comment] 2021-11-22 17:36
@javiercn What is the dupe issue # ? You linked this one in your comment

**Comment by javiercn** [comment] 2021-11-22 17:48
[@Socolin ](https://github.com/dotnet/aspnetcore/issues/31151)
