### ISSUE TITLE
[StringLength] Attribute makes nullable string required in blazor

### ISSUE THREAD

**Issue by flatproject** [dotnet/aspnetcore#53179] opened 2024-01-05 21:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I start a new blazor server project from a VS (latest version) template with Identity (local accounts). I add a nullable property in the InputModel of Register.razor page with a [StringLength] attribute. The property is made required when it shouldn't.

This is my InputModel:
```
[StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
public string? MyNotRequiredProperty { get; set; }
```

This is the UI code:

```
<div class="form-floating mb-3">
    <InputText type="password" @bind-Value="Input.MyNotRequiredProperty" class="form-control" />
    <label for="MyNotRequiredProperty">Confirm Password</label>
    <ValidationMessage For="() => Input.MyNotRequiredProperty" class="text-danger" />
</div>
```

This is the validation when i click Register:
![image](https://github.com/dotnet/aspnetcore/assets/18282373/520fce93-7c23-4557-8d5b-6b709031edd2)

### Expected Behavior

I expect the [StringLength] attribute not to make a nullable string required on validation.

### .NET Version

8.0.100

**Comment by javiercn** [comment] 2024-01-08 09:16
@flatproject thanks for contacting us.

That's because the browser is sending the "". Inputs in HTML don't really have the concept of null.

This is a duplicate of https://github.com/dotnet/aspnetcore/issues/52195

**Closed by javiercn** 2024-01-08 09:16 UTC
Labels: area-blazor
