### ISSUE TITLE
StaticWebAssetBasePath not taken into account with JavaScript module initalizer

### ISSUE THREAD

**Issue by rogihee** [dotnet/aspnetcore#38690] opened 2021-11-29 13:19 UTC
I'm trying out the new experimental package (to circumvent firewalls blocking dlls) to [customize the blazor webassembly loading process](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly-deployment-layout?view=aspnetcore-6.0#customize-the-blazor-webassembly-loading-process-via-a-nuget-package). I have multiple hosted apps and use the `StaticWebAssetBasePath` project property to set a custom root path per app, and use a custom setup as described in the section [Hosted deployment with multiple apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#hosted-deployment-with-multiple-blazor-webassembly-apps). Sample here:  [https://github.com/rogihee/BlazorAppBundle](https://github.com/rogihee/BlazorAppBundle)

Without the MultipartBundle package everything is published to the correct `wwwroot/firstapp` path. After adding the package, the blazor boot.json is copied to _framework and the javascript module initializer to _content/package. These files should be in the `firstapp` directory, though:
![image](https://user-images.githubusercontent.com/4984486/143870662-39e80dba-7ec9-4a52-a3d3-8dddb860a2cb.png)

Note that the sample does not run out of the box. If I publish and merge the files / folders to /firstapp manually, everything works. Apparantly, whenever there is an extension of Javascript module initializer, the `StaticWebAssetBasePath` is not taken into account anymore.

### To Reproduce
Download the source and run the project, it fails:
[https://github.com/rogihee/BlazorAppBundle](https://github.com/rogihee/BlazorAppBundle)

Publish the FolderProfile and merge the folders in wwwroot  into firstapp subdir and dotnet run the project it works. 

### Further technical details
- ASP.NET Core version: 6.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2022

**Comment by javiercn** [comment] 2022-11-10 15:39
The issue is here
```
app.MapWhen(ctx => ctx.Request.Path.StartsWithSegments("/firstapp"), first =>
{
    //needs app.UsePathBase("/firstapp");
    first.UseBlazorFrameworkFiles();
    first.UseStaticFiles();

    first.UseRouting();
    first.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
        endpoints.MapFallbackToFile("firstapp/{*path:nonfile}", "firstapp/index.html");
    });
});


app.MapGet("/firstapp/app.bundle", (HttpContext context) =>
{
    string? contentEncoding = null;
    var contentType = "multipart/form-data; boundary=\"--0a7e8441d64b4bf89086b85e59523b7d\"";
    var fileName = "app.bundle";


    var acceptEncodings = context.Request.Headers.AcceptEncoding;
    if (StringWithQualityHeaderValue.TryParseList(acceptEncodings, out var encodings))
    {
        if (encodings.Any(e => e.Value == "br"))
        {
            contentEncoding = "br";
            fileName += ".br";
        }
        else if (encodings.Any(e => e.Value == "gzip"))
        {
            contentEncoding = "gzip";
            fileName += ".gz";
        }
    }


    if (contentEncoding != null)
    {
        context.Response.Headers.ContentEncoding = contentEncoding;
    }
    return Results.File(
        app.Environment.WebRootFileProvider.GetFileInfo(Path.Combine("firstapp", fileName)).CreateReadStream(),
        contentType);
});
```

**Comment by mkArtakMSFT** [comment] 2023-11-08 02:06
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2023-11-08 02:06 UTC
Labels: bug, area-blazor, feature-static-web-assets
