### ISSUE TITLE
VS 2022 17.4.3 throw a exception at startup: The startup hook simple assembly name 'Watch.BrowserRefresh.dll' is invalid

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#45610] opened 2022-12-15 13:51 UTC
### Description

```
System.ArgumentException: 'The startup hook simple assembly name '\Program Files\dotnet\SDK\7.0.101\DotnetTools\dotnet-watch\7.0.101-servicing.22579.2\tools\net7.0\any\middleware\Microsoft.AspNetCore.Watch.BrowserRefresh.dll' is invalid. It must be a valid assembly name and it may not contain directory separator, space or comma characters and must not end with '.dll'.'
```
![image](https://user-images.githubusercontent.com/7550366/207838586-6ccfa56e-f849-43fb-a6d5-50b70cf49142.png)

### Reproduction Steps

1. Create a webapi project in VS 2022 17.4.3
2. F5 to Debug

### Expected behavior

Normal start

### Actual behavior

Throw an Exception.

### Configuration

launchSettings.json:
```
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:33747",
      "sslPort": 44308
    }
  },
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:5064",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:7210;http://localhost:5064",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by ElderJames** [comment] 2022-12-15 15:28
Thanks for response. It could be a configuration of VS, but  I don't know how/where to fix it.

**Comment by mkArtakMSFT** [comment] 2023-01-27 04:58
Thanks for contacting us, @ElderJames.
Are you still facing this issue or was it resolved?

**Comment by ElderJames** [comment] 2023-01-27 05:09
Thank you @mkArtakMSFT , I still meet this issue after update  the lastest VS.

**Comment by ElderJames** [comment] 2023-03-02 07:57
I workaround the issue by modify the folder name.

C:\Program Files\dotnet\sdk\7.0.201\DotnetTools\dotnet-watch -> C:\Program Files\dotnet\sdk\7.0.201\DotnetTools\dotnet-watch2

**Comment by mkArtakMSFT** [comment] 2023-10-06 21:41
Unfortunately we were unable to reproduce this issue so closing given that it hasn't impacted many customers.

**Closed by mkArtakMSFT** 2023-10-06 21:41 UTC
Labels: area-commandlinetools, feature-dotnetwatch
