### ISSUE TITLE
Multiple users get registered with same email id

### ISSUE THREAD

**Issue by harjit-neo** [dotnet/aspnetcore#17594] opened 2019-12-04 13:07 UTC
I am using entityframework 2.2. to sign up I am using the below code

```c#
[HttpPost("[action]")]
public async Task<ActionResult<ResultViewModel>> Register([FromBody] RegisterViewModel model)
{
    if (ModelState.IsValid)
    {
        IdentityResult result = null;
        var user = await _userManager.FindByNameAsync(model.Email);
        if (user != null)
        {
            return new ResultViewModel
            {
                Status = Status.Error,
                Message = "User already exist.",
            };
        }

        user = new ApplicationUser
        {
            UserName = model.Email,
            Email = model.Email.ToLower(),
            FullName = model.Name,
            Gender = model.Gender,
            CreatedDate = DateTime.UtcNow.Ticks
        };

        try
        {
            result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                var token = Helper.UtilityFunctions.GetSecurityToken(_configuration, user, "App User");
                await _userManager.AddToRoleAsync(user, "App User");

                return Ok(new
                {
                    Status = Status.Success,
                    Message = "User successfully created.",
                    Token = new JwtSecurityTokenHandler().WriteToken(token),
                    Expiration = token.ValidTo,
                });
            }
            else
            {
                if (result.Errors != null)
                {
                    List<string> resultError = new List<string>();

                    foreach (var error in result.Errors)
                    {
                        resultError.Add(error.Description);
                    }

                    return new ResultViewModel
                    {
                        Status = Status.Error,
                        Message = string.Join(",", resultError)
                    };

                }
            }
        }
        catch (Exception ex)
        {
            return new ResultViewModel
            {
                Status = Status.Error,
                Message = string.Join(",", ex.Message)
            };
        }
    }

    return new ResultViewModel
    {
        Status = Status.Error,
        Message = Helper.UtilityFunctions.ModelValidation(ModelState)
    };
}
```

Above post method is working perfectly fine until I used the PostMan tool to hit the post API with same post body with the gap of neno seconds. Above function need to insert first request and for subsequent API requests above function need to return error message
> User already exist.

Because post request frequency is in neno seconds  and before first request reach to ` result = await _userManager.CreateAsync(user, model.Password);` line two or three (some time more) requests pass ` var user = await _userManager.FindByNameAsync(model.Email);` (user find check in database) and all the passed requests get inserted in the database with same email id. 

Is there any solution to at entity framework level to handle this kind case scenario?

Thanks

**Comment by ajcvickers** [comment] 2019-12-04 21:56
@harjit-neo I moved this to ASP.NET Core repo, since that's where the Identity implementation is. However, I expect this this is by-design on the Identity side.

/cc @HaoK @blowdart

**Comment by blowdart** [comment] 2019-12-04 23:19
It's by design, and there's also a property to stop it;

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/Extensions.Core/src/UserOptions.cs#L25

**Comment by blowdart** [comment] 2020-01-08 20:05
We're closing this issue as the behaviour discussed seems to be by design.

**Closed** 2020-03-25 19:04 UTC
Labels: area-identity
