### ISSUE TITLE
<select multiple @bind> in pure .razor page

### ISSUE THREAD

**Issue by niconico49** [dotnet/aspnetcore#15405] opened 2019-10-25 15:07 UTC
<select multiple @bind> in pure .razor page

is possible @bind the selected multiple values with some internal variable?
normally the select @bind an internal string variable, but how do same thing with multiple selected row? there are some solution without the .cshtml, @model implementation and using?

because if I try to use an array like IList<string> the runtime give me an error like:
System.InvalidOperationException: The type 'System.Collections.Generic.IList`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' does not have an associated TypeConverter that supports conversion from a string. Apply 'TypeConverterAttribute' to the type to register a converter.

**Comment by javiercn** [comment] 2019-10-25 15:33
@niconico49 thanks for contacting us.

That is not a currently supported scenario I believe.

@SteveSandersonMS We might be able to support this through `element.selectedOptions`?

**Comment by SteveSandersonMS** [comment] 2019-10-28 09:47
@javiercn Yes, we certainly could implement some support for this. I think it's reasonable for this to be a backlog item currently.

**Comment by SteveSandersonMS** [comment] 2020-10-07 10:50
I think this is a duplicate of #5519

**Closed by SteveSandersonMS** 2020-10-07 10:50 UTC
Labels: area-blazor, enhancement
