### ISSUE TITLE
VSCode Snippet Completions Corrupt Document

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#26832] opened 2020-10-12 23:36 UTC
![Code](https://user-images.githubusercontent.com/14852843/95799396-5e896100-0ca9-11eb-995f-1bbe1d73735d.gif)

Thanks @pranavkm for pointing this out!

**Comment by NTaylorMullen** [comment] 2020-10-13 00:24
Duplicate of: https://github.com/dotnet/aspnetcore/issues/25509

**Closed** 2020-10-13 01:14 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, bug, feature-razor.vscode
