### ISSUE TITLE
blazor-hotreload.js is missing if `UseFrameworkFiles` is set to a subdirectory

### ISSUE THREAD

**Issue by Hawxy** [dotnet/aspnetcore#35967] opened 2021-08-31 10:49 UTC
### Describe the bug
`blazor-hotreload.js` 404's if you set `UseFrameworkFiles` to anything under .NET 6 Preview 7.

Edit: I'm actually not seeing any difference between setting the path in `UseFrameworkFiles` and leaving it as default outside of `blazor-hotreload.js` adding itself in and failing. The file is not present at all if set to the root path, and the other framework files still serve from root. Is this expected behavior? 

### To Reproduce
1. Created a hosted ASP.NET Core + Blazor WebAssembly Project
2. Configure it to operate under a subdirectory (set base href, `StaticWebAssetBasePath` etc) as you would under .NET 5.
3. Run the API project.
4. Observe that blazor-hotreload tries to load under the subdirectory but is not there, breaking the site.

Reproduction project: https://github.com/Hawxy/Blazor-MissingHotReload
### Exceptions (if any)
```
System.AggregateException: One or more errors occurred. (Failed to fetch dynamically imported module: https://localhost:5001/ui/_framework/blazor-hotreload.js
```
### Further technical details
- ASP.NET Core version: 6.0 preview 7
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2022 Preview 3.1

**Comment by pranavkm** [comment] 2021-08-31 17:35
This looks like a dupe of https://github.com/dotnet/aspnetcore/issues/35555 which we're addressing as part of the rc1 release.

**Comment by Hawxy** [comment] 2021-09-01 01:36
That does seem to be the case, thanks!

**Comment by Hawxy** [comment] 2021-09-15 02:44
@pranavkm this still appears to be a problem in RC1:
![image](https://user-images.githubusercontent.com/975824/133361794-ba4648be-fe24-46bd-9bfb-977783d82123.png)
I've updated the repoduction.

**Comment by ThaRaven403** [comment] 2021-09-22 15:43
We're also experimenting this issue on our project that we just migrated from preview 5 to RC1, but we're not in a subdirectory. The thing is though, on my computer everything's fine, but on my colleague's computer he's getting this error.

**Comment by pranavkm** [comment] 2021-09-23 21:29
Thanks @Hawxy for bringing this to our attention. I'd missed porting the original change back to rc1. We have this addressed for the rc2 release.

**Closed** 2021-09-23 21:29 UTC
Labels: area-blazor, blazor-wasm, feature-hot-reload
