### ISSUE TITLE
[Blazor] Blazor Server .NET 6 No Scroll after clicking an anchor link

### ISSUE THREAD

**Issue by Programmer3591** [dotnet/aspnetcore#40800] opened 2022-03-21 15:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking an anchor link to redirect to another app page the page does not scroll up to the top. This requires having the link you click low on the first page to allow room for the scroll to occur. 

Code to reproduce this error can be found here: https://github.com/Programmer3591/BlazorServerNet6_ScrollToTopOnPageLoadIssue

A video example of this error using the code above can be found here: https://youtu.be/3lVr5Kv_TDo

A very similar issues was fixed back in 2019. I have tested this code on a Blazor Server .NET 5 app and it does not occur, therefore I believe the 2019 issues has resurfaced upon moving to .NET 6.

### Expected Behavior

Upon a new app page redirect the web view should be at the top of the page and not get stuck while scrolling up to the top.

### Steps To Reproduce

Code to reproduce this error can be found here: https://github.com/Programmer3591/BlazorServerNet6_ScrollToTopOnPageLoadIssue

Start at the home page, scroll down to the bottom anchor link. Click the link, repeat till the next page gets stuck somewhere at the lower half of the screen.

### Exceptions (if any)

No Exceptions thrown.

### .NET Version

6.0.201

### Anything else?

Code to reproduce this error can be found here: https://github.com/Programmer3591/BlazorServerNet6_ScrollToTopOnPageLoadIssue

A video example of this error using the code above can be found here: https://youtu.be/3lVr5Kv_TDo

**Comment by Programmer3591** [comment] 2022-03-24 03:14
I just tested the code again using .NET 6 Blazor and it seems by adding an ID to the IFrame the issue goes away. I am unsure if this is something Blazor should ignore moving forward or at least throw an error message against it if this is in fact the cause of the no scroll issue.

**Comment by BrayanRZ** [comment] 2022-04-04 13:19
Hello everyone, is there any workaround we can apply to solve this issue? I can reproduce it intermittently and it's so frustrating.

**Comment by Programmer3591** [comment] 2022-04-04 22:39
@BrayanRZ As seen in the previous post, the issue was solved by making sure important <div> or elements have unique identifications. That seemed to completely solve mine. For example, I had two IFrames with no ID set, and by setting <iframe id="frame1"> and <iframe id="frame2"> the issue was never encountered again. Hope this helps!

**Comment by MackinnonBuck** [comment] 2023-12-05 00:28
Closing this out since a workaround was found and it's not evident that there is a framework problem here.

**Closed by MackinnonBuck** 2023-12-05 00:28 UTC
Labels: investigate, area-blazor
