### ISSUE TITLE
When will be implemented injecting to class/viewModel in Blazor? 

### ISSUE THREAD

**Issue by DOWSCZ** [dotnet/aspnetcore#46311] opened 2023-01-29 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

When will be implemented injecting to class/viewModel in Blazor? It s extremely impractical to pass it to every constructor.

**Comment by mkArtakMSFT** [comment] 2023-01-30 17:20
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/18088

**Closed by mkArtakMSFT** 2023-01-30 17:20 UTC
Labels: area-blazor
