### ISSUE TITLE
Resource lookup succeeds locally but fails when deployed to server

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspnetcore#27791] opened 2020-11-12 23:28 UTC
### Describe the bug
When creating a resource file in your project and including the locale as it is the default "UIStrings.en.resx" and having code generation you get a static class to use.  When running locally with Visual Studio or `dotnet run` this all succeeds.  When deploying to Azure, it fails on startup

### To Reproduce
Repo (Blazor Server template with resource and changed Index.razor page): https://github.com/timheuer/blazor-loc-error
1. Clone repo
2. Execute `dotnet run` (or open in VS and F5)
OBSERVE:
Index page shows "Hello" and "Goodbye" as expected
3. Publish to an app service as either self-contained or framework-dependent (for FDD, you need to create the Azure resource in portal first as of 12-Nov)
4. Visit the deployed URL
EXPECT: see the same strings as happened locally
ACTUAL: Exception on load

### Exceptions (if any)
2020-11-12T23:11:23.085269660Z       An unhandled exception has occurred while executing the request.
2020-11-12T23:11:23.085938290Z       System.Resources.MissingManifestResourceException: Could not find the resource "LocTest.Resources.UIStrings.resources" among the resources "" embedded in the assembly "LocTest", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
2020-11-12T23:11:23.085964592Z          at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
2020-11-12T23:11:23.085969292Z          at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
2020-11-12T23:11:23.085972992Z          at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
2020-11-12T23:11:23.085976492Z          at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
2020-11-12T23:11:23.087019340Z          at TacticView.Resources.UIStrings.get_ReportAnIssue() in D:\GitHub\tacticview\Resources\UIStrings.en.Designer.cs:line 122
2020-11-12T23:11:23.087032040Z          at TacticView.Shared.NavMenu.BuildRenderTree(RenderTreeBuilder __builder)
2020-11-12T23:11:23.087035840Z          at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
2020-11-12T23:11:23.087039741Z          at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
2020-11-12T23:11:23.087043241Z          at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
2020-11-12T23:11:23.087046741Z          at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

### Further technical details
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment] 2020-11-12 23:32
Thanks @timheuer.
@pranavkm can you please look into this? I've added the investigation into the 5.0.1 for now. Let's see what you can find out and we can make the call later.

**Comment by pranavkm** [comment] 2020-11-12 23:56
@timheuer I think your repo might be non-public. Could you make it available?

**Comment by timheuer** [comment] 2020-11-13 08:42
Fixed the link but here also https://github.com/timheuer/blazor-loc-error

**Comment by dieterdp** [comment] 2020-11-16 14:31
i have the same problem but only on Safari on my Mac

**Comment by pranavkm** [comment] 2020-11-17 01:44
@SteveSandersonMS are you able to look at this? I was unfortunately unable to get to this today

**Comment by SteveSandersonMS** [comment] 2020-11-18 11:29
@timheuer I looked into this, but wasn't able to reproduce the problem. I deployed your site to Azure app service both in self-contained and framework-dependent modes, and in both cases it immediately worked fine (displaying the two resource strings). My only guess is that there was something temporarily wrong when you tried it before.

If this is something you can still reproduce, can you provide further details about what's needed to reproduce it beyond the steps already listed above?

**Comment by dieterdp** [comment] 2020-11-18 14:34
i don't know if i have the same problem. I have Blazor Web Assembly application written in .NET 5. I uses resx files for the labels, text etc... This works perfect on Windows with Chrome and Edge. I have tested this also on Android with Chrome (browser and PWA). This works fine. When i run this on OSX Big Sure with Chrome, Safari or Edge, the app breaks. The content from the resx files is not shown, the keys from the resx files are shown. If i test this on a iPhone 12 Pro with the latest iOS tis works fine.

**Comment by SteveSandersonMS** [comment] 2020-11-18 14:37
@dieterdp Your probably is definitely different. This issue is about Blazor Server. Could you please post a new separate issue to describe your scenario? Please be sure to include full repro steps or a sample app. Also when figuring out the exact repro steps, please bear in mind that your mac running Big Sur may be set to a different default language than your other devices, which may explain the difference.

**Comment by dieterdp** [comment] 2020-11-18 15:05
> @dieterdp Your issue is definitely different. This issue is about Blazor Server. Could you please post a new separate issue to describe your scenario? Please be sure to include full repro steps or a sample app. Also when figuring out the exact repro steps, please bear in mind that your mac running Big Sur may be set to a different default language than your other devices, which may explain the difference.

thx it's fixed, OSX language was Dutch, in English its's perfect,

**Comment by timheuer** [comment] 2020-11-18 17:06
@SteveSandersonMS I sent you a mail but also here is a temporary setup showing the repro and it not working :-) http://blazorloctestnet5.azurewebsites.net/

**Comment by SteveSandersonMS** [comment] 2020-11-18 17:40
That's odd. I do believe the problem happened :) I just don't know how since no such problem happened for me. My best guess the issue is in some detail to do with exactly how you're creating the app service or publishing to it.

Could you try doing the same with a plain ASP.NET Core 5.0 application? That would help narrow it down to whether there's an issue in Blazor's publishing mechanism or whether it's a general issue in the Web SDK.

If you find you can *only* repro it with Blazor Server apps (and not with, say, an MVC application) then could you provide a more detailed description of exactly how you're going about deploying? (Like, the full set of options chosen at each stage)

**Comment by timheuer** [comment] 2020-11-18 18:01
@SteveSandersonMS this does not happen with ASP.NET Core 5 app using the same flow.  Will get a video showing exactly what I'm doing.

**Comment by timheuer** [comment] 2020-11-18 19:37
@SteveSandersonMS here's a video of specifically what I'm doing: https://www.youtube.com/watch?v=gxX86aLr280

**Comment by SteveSandersonMS** [comment] 2020-11-19 14:46
OK, I see you were deploying to Linux. I was deploying to Windows.

What's happening here is nothing to do with either publishing or Blazor. What's happening is:

 * Your resource file isn't valid. You have `UIStrings.en.resx`, but no `UIStrings.resx`. As far as I can tell, VS won't generate the `*.Designer.cs` file at all unless you have a non-culture-specific `.resx`. Did you do something like rename `UIStrings.resx` to `UIStrings.en.resx`?
 * There's a difference between how .NET on Linux handles this situation from how .NET on Windows does. It seems that on Windows, it falls back on using the values from the designer class, whereas on Linux it throws because it can't load the resources assembly.

This will repro just the same with ASP.NET Core (non-Blazor) as with Blazor. My guess is that when you tried to repro it, you didn't create the same invalid resx file setup.

I'll close this as it's not an issue in this repo. Arguably the Linux/Windows inconsistency would be good to fix, but since it's only happening in a situation with inconsistent resx files, it might be that the runtime team don't consider it an issue.

**Closed by SteveSandersonMS** 2020-11-19 14:46 UTC
Labels: Needs: Attention :wave:, area-blazor, feature-localization

**Comment by timheuer** [comment] 2020-11-19 17:11
@SteveSandersonMS should we transfer to the runtime team to resolve the fallback differences then?  What I'm doing is not 'incorrect' and in other .NET areas you can provide AssemblyInfo metadata to indicate a fallback version.

**Comment by SteveSandersonMS** [comment] 2020-11-19 17:50
Following up with the runtime team does sound like a good idea to clarify this. I'm not clear on how much of a supported scenario this should be (having a mismatching resx and .Designer.cs file) but I definitely agree that a behavioral difference between Windows and Linux is surprising and undesirable.
