### ISSUE TITLE
Browser crash on iOS for client site image resizing with large number of files- Blazor Web Assembly (RequestImageFileAsync)

### ISSUE THREAD

**Issue by warrenkc** [dotnet/aspnetcore#35185] opened 2021-06-03 08:41 UTC
During testing desktop pcs with a large amount of memory work well. However on systems with a low amount of memory the browser will crash. 

On my iPad Air  (4th generation iOS version 14.5) I can resize about 400 pictures but after that point it will crash the browser.
I setup a demo site to demonstrate the issue: https://blazorimageresize.azurewebsites.net

Here is a recording of the browser crash on the iOS device: https://drive.google.com/file/d/1WR7ykyR7Q0tYb0D5umrj2J6odTvRsPCa/view?usp=sharing

```
async Task OnInputFileChange(InputFileChangeEventArgs e)
        {
        var imageFiles = e.GetMultipleFiles(2000);

        var format = "image/jpg";
        foreach (var imageFile in imageFiles)
        {
            var resizedImageFile = await imageFile.RequestImageFileAsync(format, 1920, 1080);          
        }
```

**Comment by javiercn** [comment] 2021-08-09 14:04
Thanks @lewing, we'll take a look.

**Comment by mkArtakMSFT** [comment] 2021-08-09 16:55
Thanks @lewing!

Looks like this is a dupe of https://github.com/dotnet/aspnetcore/issues/35156

**Closed by mkArtakMSFT** 2021-08-09 16:55 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-builtin-components

**Comment by MichelJansson** [comment] 2021-08-10 14:51
> Looks like this is a dupe of #35156

@mkArtakMSFT I have been studying InputFile quite a bit over the last few days, and while these are similar, #35156 is probably not the only reason for this crash.

#35156 is about the ObjectURL of the **source file**, and since that is a JS File object (from the File API) it _should_ only hold a reference to the file in local file system (unless iOS is doing it differently...).

Though what I think is happening here is what @pavelsavara touched on, the result of the resize is stored as a **blob** on the input element to later be accessed via the `IBlazorFile.OpenReadStream`. This will probably quickly consume quite a bit of memory. Chromium docs also warns about [creating large blobs too fast](https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md#creating-large-blobs-too-fast).

A solution to this issue could be to stream the resize results directly into .NET via a [`IJSStreamReference` (6.0 preview 7)](https://github.com/dotnet/aspnetcore/blob/v6.0.0-preview.7.21378.6/src/JSInterop/Microsoft.JSInterop/src/Implementation/JSStreamReference.cs) instead of a "faked" BrowserFile. This way it can be read directly, and when `IJSStreamReference` is disposed, it should also release the blob on the JS side. This of course requires a change of the public API...
