### ISSUE TITLE
Microsoft.AspNetCore.ApiAuthorization.IdentityServer support non Entity Framework data stores

### ISSUE THREAD

**Issue by pwelter34** [dotnet/aspnetcore#21752] opened 2020-05-12 20:31 UTC
### Is your feature request related to a problem? Please describe.

Currently, the use of the Microsoft.AspNetCore.ApiAuthorization.IdentityServer package requires that your data store be accessed by Entity Framework.  I have a MongoDB data store and I've implemented all the interfaces for using MongoDB with Identity framework.  However, I ran into a huge road block when trying to implement web api security in that the Microsoft.AspNetCore.ApiAuthorization.IdentityServer package requires an instance of DbContact. There is no way to implement my own data access layer for Identity Server while using all the configuration setup in the Microsoft.AspNetCore.ApiAuthorization.IdentityServer package.

### Describe the solution you'd like

Microsoft.AspNetCore.ApiAuthorization.IdentityServer package contains many configuration defaults for setting up Identity Server.  The Entity Framework portion seems very small and should be abstracted out into its own package. At a minimum, abstract a way all the useful Identity Server configuration.  Allow the implementation of your own data access layer, same way asp.net core identity does.

**Comment by blowdart** [comment] 2020-05-12 20:46
There are various[ 3rd party identity packages](https://github.com/dotnet/aspnetcore/tree/master/src/Identity) for things like MongoDB.

You should be able to configure identity server for them, just not using our overloads.

**Comment by blowdart** [comment] 2020-05-20 19:21
Closing as by design.

**Closed by blowdart** 2020-05-20 19:21 UTC
Labels: area-identity
