### ISSUE TITLE
SignalR JAVA Client bypass self-signed Certificate

### ISSUE THREAD

**Issue by hieu2010** [dotnet/aspnetcore#19361] opened 2020-02-26 10:01 UTC
Hello,

I am currently building a SignalR client using Java and I can't manage to build a successful connection using a self-signed certificate. It seems like SignalR isnt using cacerts from the jre library. Can anyone tell me how to bypass the validation of the certificate or add my self-signed certificate as an exception?

Thank you.

**Comment by anurse** [comment] 2020-02-28 19:15
Looks like something we are indeed missing options to flow in to `okhttp` here to configure self-signed certificates.

**Comment by hieu2010** [comment] 2020-03-02 14:07
So the issue can't be fixed as of now or is there a way to solve it?

**Comment by anurse** [comment] 2020-03-02 16:52
I don't believe it's possible today, we don't expose the right hooks for it.

**Comment by Steve0212a** [comment] 2020-03-09 21:24
I too need this.  Any idea when a fix would be available so I can let my managers know?

**Comment by anurse** [comment] 2020-03-10 04:43
At this point it is not currently scheduled for 5.0. We can look at moving it up given the higher priority (and if anyone is interested, submitting a PR would certainly help move things along).

At best, we'd release it as part of the .NET 5.0 release, which is targeted for GA in November 2020 (though there will be preview releases much sooner than that).

**Comment by anurse** [comment] 2020-03-17 20:05
Merging this in to https://github.com/dotnet/aspnetcore/issues/15404 which covers adding a custom callback for validating certs in the Java client (which would allow self-signed certs, as well as pinning and other scenarios).

Duplicate of #15404

**Closed by anurse** 2020-03-17 20:05 UTC
Labels: 5.0-candidate, area-signalr, help wanted
