### ISSUE TITLE
The message The value '' is not valid for

### ISSUE THREAD

**Issue by zandiarash** [dotnet/aspnetcore#54577] opened 2024-03-17 08:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a **Blazor** web application which uses **System.ComponentModel.DataAnnotations** attribute for **validation** in a registration form .
I have a property named **NationalCode** which is **nullable long**
I did not added **[Required]** attribute above my **NationalCode** property
But when I want to submit the form if I leave the field **NationalCode** empty this validation message appears :
"The value '' is not valid for 'NationalCode'."

If I change my code and add [Required] attribute like this :

```
[Required(ErrorMessage = "Please Enter your national code", AllowEmptyStrings = true)]
public long? NationalCode { get; set; } = null;
```

Two message appears :
```
- "The value '' is not valid for 'NationalCode'."
- "Please Enter your national code"
```
This is my codes :

```
<div class="form-floating">
    <InputNumber @bind-Value="Input.NationalCode" autocomplete="nationalCode" aria-required="true" />
    <label for="family">NationalCode</label>
    <ValidationMessage For="() => Input.NationalCode" class="text-danger" />
</div>

 private sealed class InputModel
 {
     public long? NationalCode { get; set; }
 }
```

### Expected Behavior

But I want only my message appear.
Where is the first message come from ?
How can I disable it ?

### .NET Version

8.0.3

**Comment by javiercn** [comment] 2024-03-17 13:13
@zandiarash thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/52195

**Closed** 2024-03-17 13:13 UTC
Labels: area-blazor
