### ISSUE TITLE
[Test Failure] Reset_BeforeResponse_Resets

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#29126] opened 2021-01-07 19:20 UTC
https://dev.azure.com/dnceng/internal/_build/results?buildId=940584&view=ms.vss-test-web.build-test-results-tab&runId=29717438&resultId=106254&paneView=debug
```
Error message
System.AggregateException : One or more hosted services failed to stop. (Assert.Equal('1111', 'INTERNAL_ERROR') failed)
---- System.Exception : Assert.Equal('1111', 'INTERNAL_ERROR') failed


Stack trace
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.Http2Tests.Reset_BeforeResponse_Resets() in /_/src/Servers/HttpSys/test/FunctionalTests/Http2Tests.cs:line 631
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Http2Cat.Http2Utilities.Assert.Equal[T](T expected, T actual) in /_/src/Shared/Http2cat/Http2Utilities.cs:line 1060
   at Microsoft.AspNetCore.Http2Cat.Http2Utilities.VerifyResetFrame(Http2Frame frame, Int32 expectedStreamId, Http2ErrorCode expectedErrorCode) in /_/src/Shared/Http2cat/Http2Utilities.cs:line 984
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.Http2Tests.<>c__DisplayClass15_0.<<Reset_BeforeResponse_Resets>b__1>d.MoveNext() in /_/src/Servers/HttpSys/test/FunctionalTests/Http2Tests.cs:line 641
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http2Cat.Http2CatHostedService.RunAsync() in /_/src/Shared/Http2cat/Http2CatHostedService.cs:line 105
   at Microsoft.AspNetCore.Http2Cat.Http2CatHostedService.RunAsync() in /_/src/Shared/Http2cat/Http2CatHostedService.cs:line 119
   at Microsoft.AspNetCore.Http2Cat.Http2CatHostedService.RunAsync() in /_/src/Shared/Http2cat/Http2CatHostedService.cs:line 119
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
```

**Comment by Tratcher** [comment] 2021-01-07 20:04
Theory: An exception is being thrown on the server side and is being reported as INTERNAL_ERROR by HttpSys. The default HttpSys reset code is CANCEL, so we know resets are still working.

**Comment by Tratcher** [comment] 2021-01-08 16:51
From the logs in #29127, #12194 is likely the cause.

**Comment by Tratcher** [comment] 2021-01-14 21:30
We're getting the same error in adjacent tests:
Reset_DurringRequestBody_Resets
https://dev.azure.com/dnceng/internal/_build/results?buildId=947174&view=ms.vss-test-web.build-test-results-tab&runId=29871338&resultId=109246&paneView=debug
Reset_BeforeRequestBody_Resets
https://dev.azure.com/dnceng/internal/_build/results?buildId=944237&view=ms.vss-test-web.build-test-results-tab&runId=29799814&resultId=109857&paneView=debug

**Comment by BrennanConroy** [comment] 2022-01-12 00:02
We believe this is fixed by https://github.com/dotnet/aspnetcore/pull/35401

**Closed** 2022-01-14 17:54 UTC
Labels: test-failure, area-runtime, test-fixed
