### ISSUE TITLE
MemoryPool in SocketConnectionListener leaks after high load

### ISSUE THREAD

**Issue by zackliu** [dotnet/aspnetcore#28560] opened 2020-12-10 03:39 UTC
### Describe the bug
I found lots of memory doesn't get gc after a very high load testing (More than 30000 websocket connections and concurrent sending message every 1 second on a 8 cores VM).
I got a dump after testing and found MemoryPool in SocketConnectionListener consumes a lot of memories.

![Screenshot 2020-12-10 113540](https://user-images.githubusercontent.com/7847428/101718331-edfd9580-3adb-11eb-972f-b6a068be7f8f.png)

### To Reproduce

1. Make a large number of concurrent connections to a SignalR project and send quickly
2. End all connections

### Further technical details
- ASP.NET Core version 3.1.5

**Comment by davidfowl** [comment] 2020-12-10 03:40
Duplicate of https://github.com/dotnet/aspnetcore/issues/24958

I think we need to fix this now 😄

**Closed** 2020-12-11 22:29 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers
