### ISSUE TITLE
[BLAZOR] - [RequiredFragment] attribute for Blazor components [Request]

### ISSUE THREAD

**Issue by taha-ghadirian** [dotnet/aspnetcore#33465] opened 2021-06-11 07:37 UTC
### Is your feature request related to a problem? Please describe.
Add `[RequiredFragment]` For **RenderFragment** Parameters for easily Null Checking.
**Component.Razor:**
```
<div class="Some Amazing Class">
    @if(HeaderContent != null)
    {
         <div class="HeaderClass">@HeaderContent</div>
    }
    <div class="MainContent">@MainContent</div>
    @if(FooterContent != null)
    {
         <div class="FooterClass">@FooterContent </div>
    }
</div>

@code {
[parameter] public RendeFragment HeaderContent {get;set;}
[parameter] public RendeFragment MainContent {get;set;}
[parameter] public RendeFragment FooterContent {get;set;}

    OnParameterSet(){
         if(mainContent == null)
         {
            throw new exception....
         }
    }
}
```

### Describe the solution you'd like
Should remove the in code null checking and add an attribute for that.

**Comment by javiercn** [comment] 2021-06-11 10:08
@taha-ghadirian thanks for contacting us.

This is a duplicate of #11815

**Closed by javiercn** 2021-06-11 10:08 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor, question
