### ISSUE TITLE
Blazor Prerendering for Static Web Apps

### ISSUE THREAD

**Issue by MichaelPeter** [dotnet/aspnetcore#40023] opened 2022-02-06 21:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I want to use Blazor Webassembly with Static Web Apps. For Instant Load and SEO.

Now the recent trend is instant loading/SSR/SEO in Webframeworks, so the user does not have to wait for the side to load initally but gets a instant prerender. (Blazor Server, Angular Universal, Next.js for React and Vue SSR). 
To not lose users because of long inital loading.

Now thankfully since .NET6 and .NET5 Blazor has really good prerendering, but only if you have an Active Server. If you use Blazor Webassembly with for example Azure Static Web Apps or any other fileserver, I logically cannot do this.

This would also be really usefull for static sites (about, contacts etc.)

### Describe the solution you'd like

Now wouldn't it be nice if you could generate on deploy or during runtime static html/javascript into a directory which can be loaded initally and then after the runtime is loaded the side becomes interactive? Like Webassembly preredering but just from a directory?

Of corse the preprender would be static.
But there could be different prerendering directories for differnt users.

During Runtime the generation should also be possible, because the side could look different depending on the runtime configuration.

**Comment by javiercn** [comment] 2022-02-07 10:45
@MichaelPeter thanks for contacting us.

This is a duplicate of https://github.com/dotnet/aspnetcore/issues/38114

**Closed** 2022-02-07 10:47 UTC
Labels: question, :heavy_check_mark: Resolution: Duplicate, area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved
