### ISSUE TITLE
Corrupted Padding Bits Brotli Decode Blazor Azure Static Web App

### ISSUE THREAD

**Issue by SeanLeitzinger** [dotnet/aspnetcore#52735] opened 2023-12-11 18:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting the following error when deploying our Blazor WASM App to an Azure Static Web App resource.
![image](https://github.com/dotnet/aspnetcore/assets/24277209/e6d6d72d-33e3-4315-8c9e-136d89def59d)

I have followed all of the documentation and also tried using both the min version of decode and the non-min version. The app runs fine locally with Brotli and the decode script. The issue appears specific to the Azure Static Web App resource since I have had no issues deploying to other servers in the past. I was unable to find much info on the issue.

Here is what is served when navigating to the app:
![image](https://github.com/dotnet/aspnetcore/assets/24277209/5c6337f0-a5bf-4d22-8d48-2f2ae44512c4)

The script code:
`<script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script type="module">
        import { BrotliDecode } from './decode.js';
        Blazor.start({
            loadBootResource: function (type, name, defaultUri, integrity) {
                if (type !== 'dotnetjs' && location.hostname !== 'localhost' && type !== 'configuration') {
                    return (async function () {
                        const response = await fetch(defaultUri + '.br', { cache: 'no-cache' });
                        if (!response.ok) {
                            throw new Error(response.statusText);
                        }
                        const originalResponseBuffer = await response.arrayBuffer();
                        const originalResponseArray = new Int8Array(originalResponseBuffer);
                        const decompressedResponseArray = BrotliDecode(originalResponseArray);
                        const contentType = type ===
                            'dotnetwasm' ? 'application/wasm' : 'application/octet-stream';
                        return new Response(decompressedResponseArray,
                            { headers: { 'content-type': contentType } });
                    })();
                }
            }
        });
    </script>`

### Expected Behavior

The app should load without error when using Brotli in a Blazor WASM app and deploying to an Azure Static Web App.

### Exceptions (if any)

Uncaught (in promise) Error: Corrupted padding bits
    at jumpToByteBoundary (decode.js:1759:23)
    at decompress (decode.js:1352:13)
    at decode (decode.js:2208:13)
    at (index):38:59
    at async at.initAsync (blazor.webassembly.js:1:36102)
    at async Object.Vt [as start] (blazor.webassembly.js:1:61895)
jumpToByteBoundary @ decode.js:1759
decompress @ decode.js:1352
decode @ decode.js:2208
(anonymous) @ (index):38
await in (anonymous) (async)
(anonymous) @ (index):28

### .NET Version

7.0.4

**Comment by javiercn** [comment] 2023-12-12 09:37
@SeanLeitzinger thanks for contacting us.

This seems to be an interaction with the library used to decode the brotli stream. I would suggest using an alternative library. 

Is it correct to assume it works correctly when served locally without using a script to decode the payload manually?

**Comment by SeanLeitzinger** [comment] 2023-12-12 14:21
Hi Javier. We are using the same set up locally as when deployed. There is no difference except it works locally.

**Comment by javiercn** [comment] 2023-12-12 15:49
@SeanLeitzinger thanks for the additional details.

Are there any errors on the network tab? Does the response look the same in both cases? (Content size, type, and other headers)

At the very least, I suggest you do the following:
* Open Dev tools.
* Break on all the exceptions.
* Navigate the stack to determine what brotli file is causing the issue you are observing.
* Save the file to disk from the Network Tab in the version that is not working
* Save the file to disk from the Network Tab in the version that is working.
* Use `Get-FileHash` to get a hash of both files and see if anyone is different.
* Do the same against your publish output to see if there are any differences.

**Comment by javiercn** [comment] 2023-12-13 18:13
Probably dupe of https://github.com/dotnet/aspnetcore/issues/45191

**Comment by SeanLeitzinger** [comment] 2023-12-13 19:57
I saw that one before posting this. Don't think it's a dupe. I debugged this and it looks like it fails when trying to decode the blazor.boot.json.br. I pulled it down and that is JSON in plain text. When publishing locally that is a brotli file that doesn't load in plain text. It looks to me like this is getting published as a br file but not actually compressed with brotli. Maybe I need something in the devops pipeline? Seems weird that it is creating a brotli extension file but not actually compressing it.

**Comment by javiercn** [comment] 2023-12-14 08:30
@SeanLeitzinger thanks for the additional details.

> "I pulled it down and that is JSON in plain text" 
> How did you pull it down exactly, using curl or similar? Some of these tools might automatically decompress the response.

If the output from the publish process is a brotli file, there's something afterwards in your pipeline that is causing the issue.

**Comment by SeanLeitzinger** [comment] 2023-12-14 14:20
The response in the network tab is plain text, getting it from the address bar is plain text, and in the javascript it's a plain text file. I just tested on another production blazor wasm site and it is not in plain text and it is not hosted on Azure Static Web Apps. This is something specific to Azure Static Web Apps and I'm using the generated devops pipeline it creates when you create the resource. From reading the documentation, it should be creating the brotli files by default.

**Comment by javiercn** [comment] 2023-12-14 15:47
@SeanLeitzinger Can you point out to the docs you are following?

**Comment by SeanLeitzinger** [comment] 2023-12-14 17:30
Compression is enabled by default on build per https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0

The build shows it is compressing:
 Stripping symbols from dotnet.wasm ...
  Compressing Blazor WebAssembly publish artifacts. This may take a while...
  Polaris.Web -> /f20e39d7-d481-4dbb-a66a-448a96dfbafb-swa-oryx/app/

I also attempted to specify the build command in the task in case for some odd reason the Azure Static web App build disables it:

task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: {TOKEN}
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "Polaris/Polaris.Web" # App source code path
      #api_location: "" # Api source code path - optional
      output_location: "wwwroot" # Built app content directory - optional
      app_build_command: dotnet publish -c Release
###### End of Repository/Build Configurations ######

Documentation states also that Azure Static Web Apps automatically serves it:
https://learn.microsoft.com/en-us/azure/static-web-apps/faq#how-do-i-enable-gzip-or-brotli-compression-

**Comment by javiercn** [comment] 2023-12-15 11:36
@SeanLeitzinger that seems to be an issue on how the Azure Static Web app is configured on your end.

When you download the file from the browser, what does the content-encoding on the network tab say?

**Comment by SeanLeitzinger** [comment] 2023-12-15 14:42
@javiercn 
![image](https://github.com/dotnet/aspnetcore/assets/24277209/5167c085-6a30-436f-92d5-5e685498ae72)

Content encoding says br. Correct me if I'm wrong here, but the whole point of brotli is that the files are pre-compressed in brotli and then the decode.min.js is used to decode them client side. If the file is coming across as plain text JSON, that means that it was never actually compressed using Brotli, right? On my other sites this does not come across in plain text.

**Comment by javiercn** [comment] 2023-12-18 16:20
@SeanLeitzinger Yes.

I'm asking questions to see if we can narrow down the issue and track where the problem is. If you download the asset with curl or similar, do you get the correct response? (Trying to determine if the response is not actually compressed, if its compressed but the bytes are somehow corrupted, etc).

**Comment by SeanLeitzinger** [comment] 2023-12-19 15:27
When using curl it comes in as binary. When looking through devtools or the browser it is coming in as plain text. On my other system which is served by YARP, these files come through in dev tools and through the browser as unreadable binary. There seems to be a difference in the way the content is being served after examining the headers.

With that said, we're thinking of abandoning the static web app and moving onto .NET 8 with a hosted solution. .NET 8 now has the auto rendering mode which would require a hosted solution, correct? Which would then mean moving onto an app service instead. If that's the case, it may be best just to abandon this.

**Comment by javiercn** [comment] 2023-12-20 10:48
@SeanLeitzinger thanks for the additional details.

> With that said, we're thinking of abandoning the static web app and moving onto .NET 8 with a hosted solution. .NET 8 now has the auto rendering mode which would require a hosted solution, correct? Which would then mean moving onto an app service instead. 

Yes, if you want prerendering you need a hosted solution.

Given the current time, folks are out, and things will take a bit longer, but I'm definitely interested in us getting to the bottom of this, to know if there's an issue on our docs or somewhere else along the way.

My assumption is that you were following one of our docs (I remember we talk about this in the docs when self-hosting).

**Comment by SeanLeitzinger** [comment] 2023-12-20 15:41
Not sure if this helps, but this is what the headers look like on the YARP served site:
![image](https://github.com/dotnet/aspnetcore/assets/24277209/38e321de-e306-4f29-8514-c3edf6b02356)

Response:
![image](https://github.com/dotnet/aspnetcore/assets/24277209/0da1e9f5-3fe5-4d6d-b83c-28220c5534b2)

Here is what the headers look like on the Azure static web app:
![image](https://github.com/dotnet/aspnetcore/assets/24277209/2fb86f3e-dd1a-4b96-9ec4-94e37dfefdcb)

And the response:
![image](https://github.com/dotnet/aspnetcore/assets/24277209/d239aa67-b441-405b-b0b7-8676f58d530d)

**Comment by SeanLeitzinger** [comment] 2023-12-20 15:58
Here's what the dev tools looks like. The one on the left is the Azure static web app, then one on the right is the site served by YARP. The static azure web app is missing response headers.
![image](https://github.com/dotnet/aspnetcore/assets/24277209/e5fe3be6-f39c-4b19-bfa7-cc323fcd886b)

And here is the response. Left is Azure static web app, right is YARP.
https://github.com/dotnet/aspnetcore/assets/24277209/8e0bdf69-a452-4c9f-abf2-b3a36c3d7d5a)

**Comment by SeanLeitzinger** [comment] 2023-12-21 18:34
@javiercn Is there any specific docs I should be following? Want to make sure I have gone through everything I should have.

**Comment by danroth27** [comment] 2024-01-02 20:28
@SeanLeitzinger Azure Static Web Apps should correctly host your Blazor WebAssembly app by serving the precompressed Brotli files (.br) that get produced when the app is published. You shouldn't need to use the decode.js. Azure Static Web Apps should automatically serve the precompressed .br file and the browser will handle decoding the downloaded content. And you please try with your custom `Blazor.start` logic removed?

**Comment by SeanLeitzinger** [comment] 2024-01-03 15:23
Hi @danroth27 I actually tried this a while back, but I didn't think it was working because it serves the blazor.boot.json instead of the brotli file. It also serves everything as wasm files uncompressed. 

Azure Static Web App:
![image](https://github.com/dotnet/aspnetcore/assets/24277209/86d71138-7d28-4647-a767-18a731678dbc)

vs

![image](https://github.com/dotnet/aspnetcore/assets/24277209/5c0f7b7f-5ba8-475e-9b49-7dcbfb668f63)

Is this the intended behavior?

**Comment by SeanLeitzinger** [comment] 2024-01-03 15:32
Hi @danroth27 I actually tried this a while back but didn't think it was working since the br files weren't being served and the blazor.boot.json wasn't br. I just went through and analyzed the size of the files vs another blazor site and it looks like the wasm files are the same even though the azure static web app doesn't have the br suffix on it. Thanks for clearing this up.

**Comment by danroth27** [comment] 2024-01-03 18:50
@SeanLeitzinger Cool, it sounds like this issue is resolved then. Let us know if you run into any other problems that we can help you out with!

**Closed by danroth27** 2024-01-03 18:50 UTC
Labels: External, area-blazor
