### ISSUE TITLE
Experimental Razor editor does not work with MobileBlazorBindings

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29840] opened 2021-02-01 23:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Experimental-Razor-editor-does-not-work-/1322425)._

---
[severity:It's more difficult to complete my work]
When experimental Razor editor is used with MobileBlazorBindings projects, it cannot resolve components:

RZ10012	Found markup element with unexpected name 'StackLayout'. If this is intended to be a component, add a @using directive for its namespace.

Old editor works just fine.

Example file: https://github.com/xamarin/MobileBlazorBindings/blob/master/samples/ControlGallery/ControlGallery/Views/CommonControls.razor

---
#### Feedback Bot on 1/27/2021, 09:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Dreamescaper** [comment] 2021-03-03 09:50
I cannot reproduce this issue in latest VS preview anymore, so probably it is fixed!

**Comment by NTaylorMullen** [comment] 2021-03-03 21:01
> I cannot reproduce this issue in latest VS preview anymore, so probably it is fixed!

Thanks for following up @Dreamescaper i'll close this out!

**Closed by NTaylorMullen** 2021-03-03 21:01 UTC
Labels: Author: Migration Bot :robot:, area-razor.tooling, bug, feature-razor.vs
