### ISSUE TITLE
Support for registering multiple root components and automatically injecting them into HTML

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#24905] opened 2020-08-14 06:11 UTC
### Is your feature request related to a problem? Please describe.

I'm writing a component library, some components such as messages, modals, and overlay components require a container component to allow them to dynamically generate HTML at the bottom of the page.

As a result, we now have to instruct users to add the container component to the root component before they can use this functionality.

To display the pop-up component dynamically, you need to add the `<AntContainer />` component in `App.razor`. 

  ```
  <Router AppAssembly="@typeof(MainLayout).Assembly">
      <Found Context="routeData">
          <RouteView RouteData="routeData" DefaultLayout="@typeof(MainLayout)" />
      </Found>
      <NotFound>
          <LayoutView Layout="@typeof(MainLayout)">
              <Result Status="404" />
          </LayoutView>
      </NotFound>
  </Router>

  <AntContainer />   <-- add this component ✨
  ```

It's not too much trouble, but it's not elegant.

The hope is to implement a decoupled mechanism by registering multiple root components in the component library and then rendering them all when the render is called.

### Describe the solution you'd like

Hopefully we can use something like the following during the services registration phase:

```
services.AddRootComponent<AntContainer>();
```

Then render these registered components below the location of the render result of `builder.RootComponents.Add<App>("app")` or `<component type="typeof(App)" render-mode="Server"/>` at the moment the blazor application starts.

This feature is very much like the Overlay in Angular CDK. I think this also makes sense for Blazor.

**Comment by javiercn** [comment] 2020-08-14 13:00
@ElderJames thanks for contacting us.

We don't have a feature like the one that you are describing, but we are working on being able to render Blazor webassembly components from within razor pages, and you could use that to render your component below the app component.

Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/24098

**Closed by javiercn** 2020-08-14 13:00 UTC
Labels: area-blazor, blazor-wasm
