### ISSUE TITLE
Content in razor code blocks, @: vs <text> 

### ISSUE THREAD

**Issue by maloo** [dotnet/aspnetcore#26637] opened 2020-10-06 17:08 UTC
I just came across an issue with rendering SVG <text> tags in a @foreach loop in a razor page (in a Blazor Server app).
https://stackoverflow.com/questions/64229877/how-to-add-svg-text-in-blazor-razor-file
Wrapping like `<text><text x="0" /></text>` works, but `@:<text x="0" />` does not work.
Isn't @: also supposed to mark the line as content and not code in razor. Why is it that the render output using @: is plain text and `<text>` is removed? I get the attributes rendered as text, but not the `<text>` tag itself. Is this a bug? If not, it is a very unintuitive feature since the syntax highlighting shows it as valid markup.

@SteveSandersonMS @danroth27

**Comment by mkArtakMSFT** [comment] 2020-10-07 16:26
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/11612

**Closed by mkArtakMSFT** 2020-10-07 16:26 UTC
Labels: area-blazor
