### ISSUE TITLE
'Failed to launch debug adapter' error running new .NET 6 project in IIS Express

### ISSUE THREAD

**Issue by NeoXtreem** [dotnet/aspnetcore#31532] opened 2021-04-04 03:03 UTC
I have created a new Blazor WebAssembly App targeting .NET 6. When I run using the default IIS Express profile, a blank Chrome window is displayed, then the following error message appears after a short while:
![image](https://user-images.githubusercontent.com/16148007/113497185-d40c1680-9501-11eb-9939-bd09072cf74e.png)

This appears to be a [known issue](https://github.com/dotnet/aspnetcore/issues/28113), and I've tried all the relevant suggestions described in [this comment](https://github.com/dotnet/aspnetcore/issues/28113#issuecomment-793258878) (by a Microsoft employee), namely disabling 'Script Debugging' (it was already disabled), and enabling the "new debugger", but to no avail.

I am using VS Community 2019 Preview (16.10.00 Preview 1.0), and .NET 6.0.100-preview.2.21155.3.

I created an identical new project targeting .NET 5, and I don't get this problem.

**Comment by captainsafia** [comment] 2021-04-05 16:11
@NeoXtreem It looks like you're running into a dupe of https://github.com/dotnet/aspnetcore/issues/30917.

We'll be shipping a fix in preview4. In the meantime, you can run your app in Development using Kestrel.

**Comment by NeoXtreem** [comment] 2021-04-05 20:47
> @NeoXtreem It looks like you're running into a dupe of #30917.
> 
> We'll be shipping a fix in preview4. In the meantime, you can run your app in Development using Kestrel.

OK, thanks. Will do.

**Closed** 2021-04-06 21:00 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor, feature-blazor-debugging
