### ISSUE TITLE
Kestrel Web Server returns 404 to all requests while using inherited Startup from another project (application, assembly). Net Core 3.1.

### ISSUE THREAD

**Issue by AnastasiyaPoli** [dotnet/aspnetcore#24291] opened 2020-07-24 18:37 UTC
### Description of the bug:

**Link to repository with solution:** https://github.com/AnastasiyaPoli/MemberService

**Short description of the solution:** there are two projects in solution: web project _MemberService.Api_ and tests project _MemberService.SystemTests_. _MemberService.Api_ starts Kestrel service and has a controller _DiagnosticController_ with endpoint "ping". _MemberService.SystemTests_ has a test to test the first project. It starts Kestrel service, uses a proxy and calls endpoint "ping".

**The problem is:** in _MemberService.SystemTests_ I have to use _TestStartup_ (declared in file _TestStartup.cs_ in project _MemberService.SystemTests_), that inherits _Startup_ from project _MemberService.Api_, because some of settings should be changed for tests (for example, if I am using Application Insights in my project, I will not use them for tests). Configuring Kestrel server, that uses inherited _TestStartup_ was a big problem.

In file _KestrelWebService.cs_ (line 17) there is such code now for service configuration:
```
Server = new WebHostBuilder()
                .UseKestrel()
                .UseStartup<TestStartup>()
                .ConfigureKestrel((context, options) =>
                {
                    options.Listen(IPAddress.Loopback, 5000);
                })
                .UseConfiguration(Configuration)
                .UseSetting("applicationName", "MemberService.Api")
                .Build();
```
In this way the test _Given_ServiceIsRunning_When_PingActionIsCalled_Then_ResponseStatusCodeShouldBeSucceed_  in file _DiagnosticTests.cs_ works fine. But the line `UseSetting("applicationName", "MemberService.Api")` is a hack to change assembly (application) name after building a server. Without it application name "MemberService.SystemTests" is used and the test fails: "ping" call to server is not 200 (OK), but 404 (NotFound).

### Steps to reproduce
1. Run test _Given_ServiceIsRunning_When_PingActionIsCalled_Then_ResponseStatusCodeShouldBeSucceed_  in file _DiagnosticTests.cs_. You will get successful result.
2. Comment line `.UseSetting("applicationName", "MemberService.Api")` (line 28) in file _KestrelWebService.cs_. 
3. Run test _Given_ServiceIsRunning_When_PingActionIsCalled_Then_ResponseStatusCodeShouldBeSucceed_  in file _DiagnosticTests.cs_ again. You will get failure result. "Ping" request to server will return 404 (NotFound). You can see it, setting a breakpoint on line `return Result.ParseFromHttpResponse(response);` (line 12) in file _HttpClientExtensions.cs_ and look at response variable.

**Test is also successful in such case:**
1. Comment line `.UseSetting("applicationName", "MemberService.Api")` (line 28) in file _KestrelWebService.cs_. 
2. In file _KestrelWebService.cs_ in line `.UseStartup<TestStartup>()` (line 22) change type from _TestStartup_ to _TestStartupApi_ (declared in file _Startup.cs_ in project _MemberService.Api_).
3. Run test _Given_ServiceIsRunning_When_PingActionIsCalled_Then_ResponseStatusCodeShouldBeSucceed_  in file _DiagnosticTests.cs_. You will get successful result.

**Resolution:** classes _TestStartupApi_  and _TestStartup_ are completely the same, but located in different projects (applications, assemblies). With _TestStartupApi_ Kestrel service works fine ("ping" call is successful) but with _TestStartup_ - it is not working ("ping" call is failing). Changing assembly (application) name from "MemberService.SystemTests" to "MemberService.Api" after building a server helps, but it does not seem like normal behavior.

**Important note**: the code worked for .NET Core 2.2, but caused problems for .NET Core 3.1. The issue became visible after changing the version.

Could you suggest a correct solution to configure Kestrel service for project _MemberService.SystemTests_ in this case? Or is it a bug that is going to be fixed? Thanks in advance!

### Exceptions:
The problem is not followed by any exceptions.

### Further technical details
- ASP.NET Core version: 3.1
- the output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.514 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.1.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs: https://aka.ms/dotnet-download
```
- The IDE: Visual Studio Professional 2019, version: 16.5.5

**Comment by Tratcher** [comment] 2020-07-24 18:49
`applicationName` is used when doing MVC controller discovery. `UseStartup` sets it to the assembly of the given startup type. You'd have this issue any time you specified controllers and startup classes in separate assemblies.

MVC, is this covered in the MVC test docs?

**Comment by AnastasiyaPoli** [comment] 2020-07-24 18:55
@Tratcher, thanks for answer. Questions:
- it was change for .NET Core 3.1? In .NET Core 2.2 it worked fine;
- what the solution in this case, then? Either move TestStartup to Api project or use the hack, that I described for building a server: .UseSetting("applicationName", "MemberService.Api")?

**Comment by davidfowl** [comment] 2020-07-24 19:01
> or use the hack, that I described for building a server: .UseSetting("applicationName", "MemberService.Api")?

That's not a hack, that's by design 😄

**Comment by AnastasiyaPoli** [comment] 2020-07-24 19:22
@davidfowl changing an application name in server configuration in runtime is by design? 😄

**Comment by davidfowl** [comment] 2020-07-24 19:26
Yes absolutely. The name defaults to the assembly where the startup class or configure delegate is. Honestly though longer term, I'd love to fix this by changing MVC to avoid looking at the application name to find controllers. That's the thing that's broken here...

**Comment by AnastasiyaPoli** [comment] 2020-07-24 19:42
@davidfowl that change is definitely needed. Or at least exception should be thrown. There were no errors during initialization, but server did not start and the root cause was not obvious at all.

**Comment by davidfowl** [comment] 2020-07-24 19:50
That's because there's no reasonable way to know what's wrong. Controllers can be anywhere, in the main app, in the assembly where the startup class is or in another assembly altogether.

That said, what we have now is a pit of failure and we've seen this 404 problem come up lots of times. I think as a minimum bar we can add verbose logging (I though we did that already ...)

cc @pranavkm

**Comment by Tratcher** [comment] 2020-07-24 19:52
MVC could throw on startup if it doesn't discover any controllers. Then at least the issue would be more obvious.

**Comment by AnastasiyaPoli** [comment] 2020-07-24 19:57
@davidfowl yes, that's a pit of failure, hope to be fixed.

@Tratcher good point, that would be great.

**Comment by davidfowl** [comment] 2020-07-24 20:39
I dunno maybe that sounds reasonable but it's a breaking change. MVC could be a part of your application made up of multiple frameworks or libraries in a single app composed at startup or dynamically. It might make a working app start throwing after an upgrade

**Comment by AnastasiyaPoli** [comment] 2020-07-25 10:59
@davidfowl at least a warning message can be thrown then.

**Comment by SashaPshenychniy** [comment] 2020-07-27 12:31
@davidfowl, @Tratcher Would you agree that it's unobvious that while resolving controllers MVC relies on some "_applicationName_" setting and expects that 'string' setting to correspond to some assembly name where controllers are located?
[Documentation ](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.1) suggests to set applicationName to the entry-point assembly which leads to an issue in described scenario. 
If overriding that setting manually as Anastasiya did is not a hack - it's an 'Inappropriate Intimacy' code smell at least. So does MVC, assuming controllers are located in same assembly as Startup file and not even providing easy way of changing that.

Another interesting question to think of: what if someone have 2 assemblies with controllers? Then first assembly must be specified via '_applicationName_' and second - via _AddApplicationParts_ method - completely different approaches for doing the same thing.

I can see at least a few ways how this could be made more easy to understand:

1. Create an extension method for `IWebHostBuilder`: `UseWebAppAssembly(Assembly a)` which may internally set the setting '_applicationName_'. This is non-breaking change and extreemely easy to introduce.
2. Traverse base types of the `TStartup` in `UseStartup<TStartup>()` method and add all those root type assemblies as application parts. May be breaking-change, but really unlikely someone gets some controllers loaded which shouldn't have been loaded anyway.
3. Same as #2, but only find first assembly where at least one controller is present - even less chances to break anything.
4. Totally breaking, but just a dream... Make `AddApplicationParts` call required and do not rely on unverified assumptions (such as controllers are located in the same assembly as Startup class). It's so hard to debug such implicit default behaviors which do not indicate any errors! I faced it myself couple of times with Azure Functions and AppInsights before...

**Comment by AnastasiyaPoli** [comment] 2020-07-27 13:37
@Tratcher @davidfowl 
I created a branch **net-core-version-2.2** for test project: https://github.com/AnastasiyaPoli/MemberService/tree/net-core-version-2.2.

In scope of it I changed target framework for MemberService.Api and MemberService.SystemTests projects from .NET Core 3.1 to .NET Core 2.2. Added needed packages and changed IWebHostEnvironment to IHostingEnvironment. Commented the line .UseSetting("applicationName", "MemberService.Api") in file "KestrelWebService.cs". 

**The issue with Kestrel had gone.** Now ping test works fine, although file _TestStartup.cs_ and files with controllers are in different projects (applications, assemblies) and I do not use any methods to change application name in runtime.

So, such approach works for .NET Core 2.2 and does not work for .NET Core 3.1. If so, it is definitely a breaking and not obvious change in logic.

**Comment by davidfowl** [comment] 2020-07-27 14:38
@AnastasiyaPoli I'll take a look at your repos today.

**Comment by AnastasiyaPoli** [comment] 2020-07-28 18:04
@davidfowl did you have a chance to look at repo?

**Comment by davidfowl** [comment] 2020-07-28 19:01
Yes, the difference between the 2.2 and 3.1 projects is that the controller discovery logic was moved to build time in 3.x. Change the test project's SDK from:

```xml
<Project Sdk="Microsoft.NET.Sdk">
```

to 

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

And it'll work without changing the application name.

**Comment by AnastasiyaPoli** [comment] 2020-07-29 09:38
@davidfowl thanks for the solution and explanations.
It really works if `<EnableDefaultContentItems>false</EnableDefaultContentItems>` added to .csproj file (at least, in my case).

Checked once again the documentation https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1 and did not find information about that change. It would be just great if it could be added, because the behavior is not obvious at all when the error occurs.

**Comment by jjxtra** [comment] 2020-09-21 22:33
This hack is needed as of .net core 3.1 (and .NET 5). It appears the controller discovery tree uses the wrong assembly to start with. Probably it should just use `AppDomain.GetAssemblies`, but maybe it is using `Assembly.GetExecutingAssembly` or something...

```
IWebHostEnvironment env = ...
env.ApplicationName = System.Reflection.Assembly.GetEntryAssembly().GetName().Name;
```

**Closed** 2020-11-21 02:00 UTC
Labels: area-mvc
