### ISSUE TITLE
Hosted service prevents app to start completely without startup class

### ISSUE THREAD

**Issue by EResman** [dotnet/aspnetcore#38698] opened 2021-11-25 07:14 UTC
### Description

We have a hosted service that runs in the background all the time (while(true)) listening on a kafka topic for new events. But using the new way to write the program file without startup prevents for example the swagger to show when the hosted service is running. To prevent this according to the [Microsoft docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio) is to add the hosted service after this line:

`var builder = WebApplication.CreateBuilder(args);`

This is the Program.cs:

```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddHostedService<KafkaService>();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();
```

This is how our service looks:

```
public class KafkaService : IHostedService
{
    public Task StartAsync(CancellationToken cancellationToken)
    {

        while (true)
        {
            string doSomething = "doSomething";
        }

    }
    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

### Configuration

Version: .NET 6
OS: Windows 10

### Regression?

In .NET 5 you needed to do this by adding it after the startup in the program file:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        })
        .ConfigureServices(services =>
        {
            services.AddHostedService<VideosWatcher>();
        });
```

Using the method in .NET 5 also works in .NET 6.

**Comment by halter73** [comment] 2021-12-01 21:27
Before the final release, `WebApplication` had [a bug](https://github.com/dotnet/aspnetcore/issues/35454) where all `IHostedServices` would start after the server started accepting requests, but this was fixed in rc2. There's not really a way to get the old buggy behavior back since generally you want to wait for your hosted services to start before you start handling request.

I think the real issue here is that `IHostedService.StartAsync()` never completes. Why not have `StartAsync()` start its work in the background if you don't want to wait on it? We have some examples of this at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio#backgroundservice-base-class

**Comment by davidfowl** [comment] 2021-12-08 07:52
This is by design, but in general, starting the host will fail if *any* of the IHostedServices fail to start. The ordering is different when using the `WebApplicationBuilder` and services `IHostedService` instances always run before the server starts. This maps to adding the IHostedService inside of ConfigureServices inside off the startup class. There's no explicit way to register an `IHostedService` after the server, if you need that control, reverting to the generic Host APIs are fine.

**Closed** 2021-12-09 10:00 UTC
Labels: :heavy_check_mark: Resolution: By Design, area-runtime, Status: Resolved
