### ISSUE TITLE
RDLC  work on a Linux based environment

### ISSUE THREAD

**Issue by mylysddp** [dotnet/aspnetcore#44466] opened 2022-10-11 06:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

can RDLC  work on a Linux based environment？ it's there  any plans to migrate rdlc to netcore 7?

### Describe the solution you'd like

*

### Additional context

*

**Comment by adityamandaleeka** [comment] 2022-10-12 22:23
Looks like a duplicate of https://github.com/dotnet/aspnetcore/issues/39912

**Closed** 2022-10-12 22:23 UTC
Labels: area-runtime
