### ISSUE TITLE
Support POSTGRESQLCONNSTR_ in EnvironmentVariablesConfigurationProvider.cs

### ISSUE THREAD

**Issue by bookuha** [dotnet/aspnetcore#47704] opened 2023-04-14 12:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to create a Azure App Service with Postgres DB (Web app + Database option on the portal)
The connection string I've been provided with has a prefix POSTGRESQLCONNSTR_ in the environment, which is not recognized by EnvironmentVariablesConfigurationProvider.cs, so I have to either access it as environment variable directly or to add the prefix as a parameter to the .AddEnvironmentVariables(). The MSSQL, SQLAzure, MySQL connection string environment variables are processed properly.

### Describe the solution you'd like

I would like POSTGRESQLCONNSTR_ to be added as recognizable connection string prefix in EnvironmentVariablesConfigurationProvider.cs.

### Additional context

![conn_str](https://user-images.githubusercontent.com/82080872/232046586-00133a0d-fb51-4573-99bb-63275c7778f3.png)
![conn_str as environment variable](https://user-images.githubusercontent.com/82080872/232046787-e4734e1e-5eda-4bb3-9e55-aa956e383762.png)

**Comment by Tratcher** [comment] 2023-04-14 22:56
Duplicate of https://github.com/dotnet/runtime/issues/36123

**Closed** 2023-04-16 01:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, External, area-runtime, Status: Resolved
