### ISSUE TITLE
Race condition with On Type Formatting

### ISSUE THREAD

**Issue by veler** [dotnet/aspnetcore#30447] opened 2021-02-25 01:19 UTC
### Description
In a local Blazor project with the new Razor editor enabled, on type formatting doesn't work consistently.

### To Reproduce
1. Enable the new Razor editor.
2. Create Blazor project
3. Open Counter.razor
4. Type a bunch of `;`, like in this video: https://user-images.githubusercontent.com/3747805/109087645-b3f76500-76c2-11eb-8473-be2d6f6aa48a.mp4

This also reproduce with other formatting scenario, like typing `<p>` and pressing _[Enter]_ very quickly. When doing this, it happens that `</p>` isn't added.

It happens most of the time when typing very fast.

#### Language Server logs

[LSP logs.zip](https://github.com/dotnet/aspnetcore/files/6039891/LSP.logs.zip)

### Further technical details
- VS version: Version 16.10.0 Preview 1.0 [31022.35.main]
- Scenario: Local

### Pre-requisite checklist
- [x] Steps to reproduce the issue
- [x] Razor Language Server client logs included.
- [ ] HTML Language Server client logs included

**Comment by TanayParikh** [comment] 2021-02-25 01:22
Discussed offline;

It's a race condition where between the time we create the formatting edit, and when we respond, another `;` has already been added, making our previous edit invalid.

[Document version check](https://github.com/dotnet/aspnetcore-tooling/blob/5e540dfa1581a6ca3928853d596fcf763bb54142/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs#L352) fails and razor returns null.

This is by design for now, but long term we're looking to get this resolved.

**Comment by NTaylorMullen** [comment] 2021-09-01 00:31
Closing as by design

**Closed by NTaylorMullen** 2021-09-01 00:31 UTC
Labels: area-razor.tooling, feature-razor.vs
