### ISSUE TITLE
NotFound RenderFragment ignore in .Net 8 Blazor Web App?

### ISSUE THREAD

**Issue by cvalerio** [dotnet/aspnetcore#51044] opened 2023-09-30 16:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a .NET 8 Blazor Web App, when using `<NotFound>` in `<Router>`, and navigating to non existing routes (from NavLinks) the expected content is not shown. A fixed "Error: 404" string is shown instead.

### Expected Behavior

The content from `<NotFound>` should be shown.

### Steps To Reproduce

In VS 2022 Preview, create a new .NET 8 Blazor Web App.
Modify Components/Routes.razor as follow:
```
<Router AppAssembly="@typeof(App).Assembly" AdditionalAssemblies="new[] { typeof(Client._Imports).Assembly }">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <h1>Sorry, there's nothing at this address.</h1>
    </NotFound>
</Router>
```
Modify Components/Layout/NavMenu.razor as follows:
```
<div class="top-row ps-3 navbar navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="">MyBlazorWeb</a>
    </div>
</div>

<input type="checkbox" title="Navigation menu" class="navbar-toggler" />

<div class="nav-scrollable" onclick="document.querySelector('.navbar-toggler').click()">
    <nav class="flex-column">
        <div class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="bi bi-house-door-fill" aria-hidden="true"></span> Home
            </NavLink>
        </div>

        <div class="nav-item px-3">
            <NavLink class="nav-link" href="counter">
                <span class="bi bi-plus-square-fill" aria-hidden="true"></span> Counter
            </NavLink>
        </div>

    <div class="nav-item px-3">
      <NavLink class="nav-link" href="weather">
        <span class="bi bi-list-nested" aria-hidden="true"></span> Weather
      </NavLink>
    </div>
    <div class="nav-item px-3">
      <NavLink class="nav-link" href="i-do-not-exists">
        <span class="bi bi-list-nested" aria-hidden="true"></span> Non existent
      </NavLink>
    </div>
  </nav>
</div>
```

Start the application, then click on "Non existent" link.
The app shows "Error: 404", instead of "Sorry, there's nothing at this address."

### .NET Version

8.0.100-rc.1.23455.8

### Anything else?

.NET SDK:
 Version:   8.0.100-rc.1.23455.8
 Commit:    e14caf947f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.1.23455.8\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64
  
Visual Studio 2022 Version 17.8.0 Preview 2.0

**Comment by mkArtakMSFT** [comment] 2023-10-02 16:49
This is a dupe of https://github.com/dotnet/aspnetcore/issues/48983

**Closed by mkArtakMSFT** 2023-10-02 16:49 UTC
Labels: area-blazor
