### ISSUE TITLE
Loggin in with a popup in Blazor WebAssembly

### ISSUE THREAD

**Issue by frankabbruzzese** [dotnet/aspnetcore#32906] opened 2021-05-21 16:55 UTC
### Is your feature request related to a problem? Please describe.
Leaving a Blazor WebAssembly page for logging in with an identity provider causes several problems:

1. The application state is lost, or we need to manage to serialize and save it somehow.
2. Loading a Blazor application takes several seconds, so leaving the application and then reloading it after login is a quite bad user experience.

Logging in with a (non-Blazor) popup would be better.

### Describe the solution you'd like
It would be nice if all authentication supported in Blazor (such as `AddOidcAuthentication`) would have a `options.ProviderOptions.LoginMode="popup`" option. 
Moreover, is there a way to customize the behavior of the `RemoteAuthenticatorView` component, to support custom authentications. It would be nice that LoginMode would be available also in `RemoteAuthenticatorView` like most of all other authentication options. 

### Additional context
At the moment just `AddMsalAuthentication` offers the LoginMode="popup`" option, which is its default. I don't understand why.

**Comment by gingters** [comment] 2021-07-07 06:33
> Leaving a Blazor WebAssembly page for logging in with an identity provider causes several problems:
> 1. The application state is lost, or we need to manage to serialize and save it somehow.
For that there is the `state` parameter in an OIDC request and response.

> 2. Loading a Blazor application takes several seconds, so leaving the application and then reloading it after login is a quite bad user experience.
The issue isn't the login redirect, but the bad performance and/or size of (your) Blazor app.

> Logging in with a (non-Blazor) popup would be better.

No. The OIDC specification is _very_ clear about how the login flows need to work in order to be secure.
When you have a popup, the application still owns the popup and can do whatever it wants within that popup. If you have malicious components or an attacker somehow manages to inject malicious Javascript or IL into your application, that attacking code would be able to capture the users credentials that are entered into the popup.

The OIDC redirect flows are designed specifically to completely leave and unload the authenticating application in order to prevent any kinds of such attacks.

> ### Additional context
> At the moment just `AddMsalAuthentication` offers the LoginMode="popup`" option, which is its default. I don't understand why.

That should be treated as a security-related bug and fixed asap.

**Comment by frankabbruzzese** [comment] 2021-07-08 17:44
@gingters ,
The application can access data in the popup only if the popup is rendering a page from the same domain. When the popup is redirected to the identity provider it is no more accessible to its parent page. It becomes accessible again when the identity provider redirects back to the application domain.

In general, different tabs/pages can share data only iff they are in the same domain. If the browser has some bug on domains isolation, then it is dangerous also opening two different tabs on two different domains..... so I don't see your point.

Redirection does take place but in the popup, as required by OIDC specifications, or if you want in a different tab. The algorithm does work the same if you open a different tab with a link with something like target="aurth", or target = "_blank".

Then, when authentication is successfully completed it can provide a cookie in the application domain, that can be read from the other tab.....

Anyway using a popup doesn't change anything. The only important fact is that the user can verify it actually is in the identity provider domain by checking the URL and by verifying the HTTPS certificate in the browser.....Obviously if the browser is not bugged.....

**Comment by mkArtakMSFT** [comment] 2023-12-03 17:32
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2023-12-03 17:32 UTC
Labels: enhancement, area-blazor, feature-blazor-wasm, feature-blazor-wasm-auth
