### ISSUE TITLE
signalr ts client has a dependency on "node-fetch": "^2.6.1" has Governance Alert 

### ISSUE THREAD

**Issue by musema** [dotnet/aspnetcore#40404] opened 2022-02-24 23:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

signalr ts client has a dependency on "node-fetch": "^2.6.1" has Governance Alert when are we planning to have a new release with "node-fetch": "^2.6.7"

**Comment by BrennanConroy** [comment] 2022-02-24 23:44
Dupe of https://github.com/dotnet/aspnetcore/issues/39672

See https://github.com/dotnet/aspnetcore/issues/39672#issuecomment-1020688172 about why this isn't a major issue in patch releases.

**Closed** 2022-02-26 19:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-signalr, Status: Resolved
