### ISSUE TITLE
[Blazor] Unnecessary Html comments in the script tag

### ISSUE THREAD

**Issue by SavoInfostream** [dotnet/aspnetcore#52435] opened 2023-11-28 23:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using Razor syntax inside script tag will automatically create HTML comments that produce invalid HTML.
```
@{
    var a = 3;
}

<script>
    let a = @a;
</script>
```
This code sample will lead to the following HTML output:

```
<script><!--!-->
    let a = 3<!--!-->;
</script>
```

Which gives: Uncaught SyntaxError: Unexpected end of input.
Is there any reason for this behavior? Are there any other tags that will change the way how the content will be rendered?

### .NET Version

8.0.100

**Comment by javiercn** [comment] 2023-11-29 06:26
@SavoInfostream thanks for contacting us.

Can you give us more details? Are you using Blazor, Razor pages, or MVC?

Do you see any error on the console? Do the comments appear on the actual HTML that comes from the network?

**Comment by SavoInfostream** [comment] 2023-11-29 07:51
@javiercn I am using Blazor. This is a Blazor Server component, and besides the mentioned (HTML parsing) error in the Chrome DevTools (you can copy the html and see that's it's invalid) there are no errors logged by the .NET itself. Comments do appear in the HTML that comes from the network, both in the prerendered HTML, and in the WS message if I used a condition around the script tag, i.e. 
```
@if (!firstRender) {
<script>
    let a = @a;
</script>
}
```

**Comment by javiercn** [comment] 2023-11-30 20:30
> Comments do appear in the HTML that comes from the network, both in the prerendered HTML, and in the WS message if I used a condition around the script tag, i.e.

Yes, it's expected for comments to appear in the HTML, as that's the mechanism Blazor uses for identifying the location components must be rendered.

But **these** comments are not appearing, are they?
```
<script><!--!-->
    let a = 3<!--!-->;
</script>
```

If they are, please provide a minimal repro project that demonstrates the issue.

To be fair, this is likely an artifact of the dev tools, not something that the framework is doing.

**Comment by SavoInfostream** [comment] 2023-11-30 20:53
Here's the example, just open the Counter page.
[BlazorApp1.zip](https://github.com/dotnet/aspnetcore/files/13517601/BlazorApp1.zip)

**Comment by javiercn** [comment] 2023-12-01 08:46
@SavoInfostream thanks for the additional details.

Unfortunately your sample does not seem runnable. Please make sure the sample builds and runs and provide a link to a public github repo for it.

**Comment by SavoInfostream** [comment] 2023-12-01 14:08
@javiercn Here's the repo: https://github.com/SavoInfostream/ScriptSample
I'm afraid I don't know what's causing it not to run for you. It's a solution from a template, and I have only added this in Counter.razor
```
<script>
    let a = @currentCount;
</script>
```

And I added this attribute in Counter.razor `@attribute [RenderModeInteractiveServer]`, and its definition in the `RenderModes.cs`. I did this because default render directive is not supported in Rider for .NET 8.

**Comment by javiercn** [comment] 2023-12-12 15:33
@SavoInfostream thanks for the additional details.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/51010

We don't support adding script tags to interactive components, this is only supported when the component renders statically. See https://github.com/dotnet/aspnetcore/issues/51010#issuecomment-1740916259 for details

**Closed by javiercn** 2023-12-12 15:33 UTC
Labels: area-blazor, Needs: Attention :wave:, Needs: Repro
