### ISSUE TITLE
Error "InvalidOperationException: Sequence contains more than one matching element" in Swagger when using multiple [FromForm] parameters in Minimal API

### ISSUE THREAD

**Issue by marcominerva** [dotnet/aspnetcore#53831] opened 2024-02-06 09:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following Minimal API endpoint:

```csharp
app.MapPost("/api/people-minimalapi", ([FromForm] Person person, [FromForm] Address address)
    => TypedResults.NoContent())
.WithOpenApi();

public record class Person(string FirstName, string LastName);

public record class Address(string Street, string City, string State, string ZipCode);
```

When I launch the application, I get the following Exception related to Swagger:

```
InvalidOperationException: Sequence contains more than one matching element
System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
System.Linq.Enumerable.TryGetSingle<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)
System.Linq.Enumerable.SingleOrDefault<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOpenApiOperationFromMetadata(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

If instead I use a Controller like this:

```csharp
[ApiController]
[Route("api/[controller]")]
public class PeopleController : ControllerBase
{
    [HttpPost]
    public IActionResult Save([FromForm] Person person, [FromForm] Address address) => NoContent();
}
```

Everything works as expected.

### Expected Behavior

Swagger should not throw the exception.

### Steps To Reproduce

Minimal repro here: https://github.com/marcominerva/FromFormBindingIssue

### Exceptions (if any)

InvalidOperationException: Sequence contains more than one matching element
System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
System.Linq.Enumerable.TryGetSingle<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)
System.Linq.Enumerable.SingleOrDefault<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOpenApiOperationFromMetadata(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### .NET Version

8.0.101

**Comment by captainsafia** [comment] 2024-02-06 20:44
@marcominerva Thanks for reporting this issue!

I believe the issue is coming from the Microsoft.AspNetCore.OpenAPI <-> Swashbuckle integration layer. In particular here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L266

I don't have immediate thoughts on the best way to workaround this, at the moment.

**Comment by Havunen** [comment] 2024-02-13 19:25
Have you tested if DotSwashbuckle produces the same error? https://github.com/Havunen/DotSwashbuckle

**Comment by vdevc** [comment] 2024-03-07 15:39
The same behaviour happens, in minimal api endpoints, if using header versioning and so having endpoints like this one

```
app.MapPost("/api/people-minimalapi", ([FromHeader(Name = "x-api-version"] string apiVersion)
    => TypedResults.NoContent())
.WithOpenApi();
```

> Have you tested if DotSwashbuckle produces the same error? https://github.com/Havunen/DotSwashbuckle

Yes. The error is present also with DotSwashbuckle @Havunen :)

**Comment by captainsafia** [comment] 2024-03-07 16:21
@Havunen You should be able to resolve this in DotSwashbuckle by updating the line of code referenced [here](https://github.com/dotnet/aspnetcore/issues/53831#issuecomment-1930720704) to accept either a single parameter from body or multiple parameters from the form.

One thing to note is that I _think_ you'd have to gather the schemas for all the `FromForm` attributes when constructing the form body. 

> The exact same behaviour happens, in minimal api endpoints, if using header (like, e.g. for versioning) and so having endpoints like this one

This is surprising to me because I don't know of any code in minimal APIs/ApiExplorer/Swashbuckle that would be causing this off the top of my head but I can look deeper.

**Comment by vdevc** [comment] 2024-03-08 08:24
> This is surprising to me because I don't know of any code in minimal APIs/ApiExplorer/Swashbuckle that would be causing this off the top of my head but I can look deeper.

Actually the exception seems to be the same

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOpenApiOperationFromMetadata(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at DotSwashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at DotSwashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by Havunen** [comment] 2024-03-08 17:49
> @Havunen You should be able to resolve this in DotSwashbuckle by updating the line of code referenced https://github.com/dotnet/aspnetcore/issues/53831#issuecomment-1930720704 to accept either a single parameter from body or multiple parameters from the form.

that code line does not exist in DotSwashbuckle

> Actually the exception seems to be the same

Is this latest version of DotSwashbuckle 3.0.9 ?  I cannot reproduce the exception, however there seems to be something wrong with the generated schema so I will check that

**Comment by captainsafia** [comment] 2024-03-08 23:54
> that code line does not exist in DotSwashbuckle

You're right. It looks like it was removed in [this commit](https://github.com/Havunen/DotSwashbuckle/commit/fd2825a799e3284ec9816f4be751a60094817a7a).

@marcominerva Given the divergence in the codebases, can you confirm if you repro this issue with DotSwashbuckle? I don't believe what @vdevc reported with `FromHeader` is related to your `FromForm` issue.

**Comment by vdevc** [comment] 2024-03-09 07:10
> Is this latest version of DotSwashbuckle 3.0.9 ? I cannot reproduce the exception, however there seems to be something wrong with the generated schema so I will check that

My check was done on 3.0.8 yesterday. I don't see the 3.0.9 version on nuget yet 🙃

**Comment by Havunen** [comment] 2024-03-09 09:38
> > Is this latest version of DotSwashbuckle 3.0.9 ? I cannot reproduce the exception, however there seems to be something wrong with the generated schema so I will check that
> 
> My check was done on 3.0.8 yesterday. I don't see the 3.0.9 version on nuget yet 🙃
> 
> > I don't believe what @vdevc reported with `FromHeader` is related to your `FromForm` issue.
> 
> @captainsafia same doubts here. I am suspecting about the presence of multiple `Produces` extensions methods. However I haven't been able to reproduce the problem without using the `FromHeader` parameter.

ah yes, I meant 3.0.8. 

Can you edit the Basic examaple project here to make it fail: https://github.com/Havunen/DotSwashbuckle

I have tried different approaches here but I am not able to reproduce the exception

https://github.com/Havunen/DotSwashbuckle/blob/master/test/WebSites/Basic/Startup.cs#L88-L98

**Comment by vdevc** [comment] 2024-03-11 08:09
> Can you edit the Basic examaple project here to make it fail: https://github.com/Havunen/DotSwashbuckle

I edited the `test/Website/MinimalApi8/MinimalApi8.csproj` instead as it is exactly like in my scenario.
You can see the commit in my [fork here](https://github.com/vdevc/DotSwashbuckle) for your reference. 

The error occur on [line 279 of SwaggerGenerator.cs](https://github.com/vdevc/DotSwashbuckle/blob/7fee3b1341a942b3d3306a50e0fd7e979727b21f/src/DotSwashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L279) 

<img width="1002" alt="image" src="https://github.com/dotnet/aspnetcore/assets/143489513/9589b2ad-b0e7-45ac-957a-c9be032fc7b4">

Member `apiDescription.ParameterDescriptions` contains 3 items one of which is duplicated

<img width="501" alt="image" src="https://github.com/dotnet/aspnetcore/assets/143489513/7fa958a6-43a9-43d5-9f1b-bf00167dc575">

The packages 

```
<PackageReference Include="Asp.Versioning.Http" Version="8.0.0" />
<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.0.0" />
``` 

comes from the excellent project from @commonsensesoftware available [here](https://github.com/dotnet/aspnet-api-versioning).

**Comment by captainsafia** [comment] 2024-03-18 18:48
Hi all,

We just posted an announcement regarding our plans for OpenAPI support in ASP.NET Core moving forward in [this post](https://github.com/dotnet/aspnetcore/issues/54599). We're bringing OpenAPI document generation as a first class feature in ASP.NET Core.

@marcominerva  I've included the scenario with multiple `FromForm` parameters into our test bed and verified that the appropriate schema is generated for both Minimal APIs and controllers.

@vdevc It looks like your issues is specifically related to the integration with Asp.Versioning. I'm eager to get this working with the built-in integration. Do you mind filing a separate issue so that we can track this work appropriately?

**Comment by captainsafia** [comment] 2024-04-23 20:48
I've opened https://github.com/dotnet/aspnetcore/pull/55321 to resolve this issue in our built-in OpenAPI support.

The TL;DR is that we are now using `allOf` to properly coalesce multiple parameters that are sources from the form body into the same request. I've also double checked that the correct schema is produced between MVC's model binding semantics and minimal APIs model binding semantics.

**Comment by vdevc** [comment] 2024-04-27 06:06
I see that #54623 is not addressed in the pull request. Are you planning with a different solution?

**Comment by captainsafia** [comment] 2024-04-29 15:55
> I see that #54623 is not addressed in the pull request. Are you planning with a different solution?

Yep, that issue is distinct from this one although the exception is the same. We'll need to look at it separately especially when Asp.Versioning is thrown in the mix since it modifies the way ApiExplorer metadata is generated.

**Comment by captainsafia** [comment] 2024-05-06 21:44
Fixed in preview5 of Microsoft.AspNetCore.OpenApi.

**Closed by captainsafia** 2024-05-06 21:44 UTC
Labels: feature-openapi, area-minimal
