### ISSUE TITLE
Support Declarative Shadow DOM in Razor/Blazor files

### ISSUE THREAD

**Issue by ostomachion** [dotnet/aspnetcore#44986] opened 2022-11-09 22:10 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Adding a `template` element with a `shadowroot` attribute to a Blazor component does not create a shadow DOM, even in browsers that support the feature. This is most likely a result of [this rule](https://web.dev/declarative-shadow-dom/#parser-only). The [polyfill](https://web.dev/declarative-shadow-dom/#polyfill) works for some components, but causes problems if there is any dynamic content inside the `template` element.

### Describe the solution you'd like

I would expect a `template` element with a `shadowroot` attribute to do the same thing in a .razor file as it would in a static .html file, i.e., create a shadow DOM (at least in browsers that support declarative shadow DOMs).

**Comment by javiercn** [comment] 2022-11-10 10:13
@ostomachion thanks for contacting us.

Unfortunately, we do not offer support for Shadow DOM in Blazor least for declarative Shadow DOM, which is not even available across browsers.

If we decide it to support either of them in the future it is very likely that we won't be scanning the markup to replicate the browser logic, but that at best we give you a gesture to mark a component as Shadow DOM enabled and do what is needed both in Blazor (attach the children to a shadow root) or in MVC/Static rendering which is to use declarative shadow dom.

**Comment by javiercn** [comment] 2022-11-10 10:15
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/34641. We suggest you upvote that issue instead.

**Closed** 2022-11-11 13:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved
