### ISSUE TITLE
Blazor wasm ADB2C hosted app is not launching and just spinning forever. 

### ISSUE THREAD

**Issue by spkiran** [dotnet/aspnetcore#24658] opened 2020-08-07 15:18 UTC
Setup:
Blazor WASM AD B2C hosted app created using command line as per instructions here

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1

**Issue**
**After adding a screen and launching, the debugger spins forever and app never launched.** I tried manual configuration as well as per the document but still the same. 

**FIX**
I**f I remove the following from lauchsettings.json** in Server project, then APP launched quickly and everything seems to be working. **However, I cant debug**.

Remove from lauchsettings.json 
 "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",

Anyone has the same issue? Suggestions?

**Comment by spkiran** [comment] 2020-08-07 15:39
labels: Balzor

**Comment by spkiran** [comment] 2020-08-07 17:19
Another work around is, While the server is spinning on blank page, if you open developer tools, site appears quickly.

**Comment by spkiran** [comment] 2020-08-08 17:53
![Annotation 2020-08-08 124920](https://user-images.githubusercontent.com/10189277/89716847-36fadd00-d976-11ea-90a9-690f793a8dbf.png)
![Annotation 2020-08-08 125035](https://user-images.githubusercontent.com/10189277/89716848-36fadd00-d976-11ea-9403-f7a6958e24ed.png)
![Annotation 2020-08-08 125343](https://user-images.githubusercontent.com/10189277/89716849-37937380-d976-11ea-9540-a4f84566959c.png)

**Comment by spkiran** [comment] 2020-08-08 17:54
Second Image is the default. Fix is to open dev tools (first screen).

**Comment by pranavkm** [comment] 2020-08-10 16:33
Can you tell us what version of VS that you're using? Also, are you able to share a repro project on GitHub?

**Comment by spkiran** [comment] 2020-08-11 04:50
Visual Studio prof. 2019 16.7.0

**Comment by pranavkm** [comment] 2020-08-11 16:48
@spkiran could you share a minima; app for us to investigate this? We don't see this issue in our templates.

**Comment by spkiran** [comment] 2020-08-13 18:43
Hello,
I tried to recreate this and even I cant reproduce it. Annoying really. The project I have still creates this issue but, when I went in to change app id's and api id's so that I share the code, its working properly. However, the one I have still is buggy. I cant share my codes with you that is the problem

I went ahead and recreated manually ADB2C with blazor wasm, it works fine on F5. You can close this I guess.

**Comment by captainsafia** [comment] 2020-08-18 17:03
Closing as dupe of https://github.com/dotnet/aspnetcore/issues/24706.

**Closed by captainsafia** 2020-08-18 17:03 UTC
Labels: Needs: Attention :wave:, area-blazor, blazor-wasm
