### ISSUE TITLE
Microsoft.dotnet-openapi issue with whitespace character folder path

### ISSUE THREAD

**Issue by sjoerd222888** [dotnet/aspnetcore#45893] opened 2023-01-05 10:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Microsoft.dotnet-openapi tool fails if username and/or path to project contains a whitespace

### Expected Behavior

Tool can work with whitespace characters

### Steps To Reproduce

Have a username on Windows containing a whitespace character. Such that your .nuget folder is found for example under 

```
C:\Users\Ed Example\.nuget
```

Install the openapi tool:
```
dotnet tool install --global Microsoft.dotnet-openapi --version 6.0.12
```
Create a small test project in a folder that contains a whitespace:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
</Project>
```

Add any arbitrary openapi definition with:
```
dotnet openapi add file .\swagger_simple.json
```

Run `dotnet build`

### Exceptions (if any)

You get an error like this

```
PS C:\Users\Ed Example\Documents\MyTest> dotnet build
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  Restored C:\Users\Ed Example\Documents\MyTest\test.csproj (in 2.81 sec).
  
  GenerateNSwagCSharp:
    dotnet --roll-forward-on-no-candidate-fx 2 C:\Users\Ed Example\.nuget\packages\nswag.msbuild\13.0.5\build\../tools/NetCore21//dotnet-nswag.dll openapi2csclient /className:swagger_simpleClient /namespace:test /input:C:\Users\Alexander Tim
  mermans\Documents\MyTest\swagger_simple.json /output:obj\swagger_simpleClient.cs
C:\Users\Ed Example\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets(28,5): error : Could not execute because the specified command or file was not found. [C:\Users\Ed Example\Documents\U
nblu\issues\ROAD-631\Test_ATI\MyTest\test.csproj]
C:\Users\Ed Example\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets(28,5): error : Possible reasons for this include: [C:\Users\Ed Example\Documents\MyTest 
\test.csproj]
C:\Users\Ed Example\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets(28,5): error :   * You misspelled a built-in dotnet command. [C:\Users\Ed Example\Documents\Unblu\issues\ROAD-631\Test 
_ATI\MyTest\test.csproj]
C:\Users\Ed Example\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets(28,5): error :   * You intended to execute a .NET program, but dotnet---roll-forward-on-no-candidate-fx does not exist. [C:\User 
s\Ed Example\Documents\MyTest\test.csproj]
C:\Users\Ed Example\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets(28,5): error :   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the  
PATH. [C:\Users\Ed Example\Documents\MyTest\test.csproj]
C:\Users\Ed Example\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets(28,5): error MSB3073: The command "dotnet --roll-forward-on-no-candidate-fx 2 C:\Users\Ed Example\.nuget\packages\nswa
g.msbuild\13.0.5\build\../tools/NetCore21//dotnet-nswag.dll openapi2csclient /className:swagger_simpleClient /namespace:test /input:C:\Users\Ed Example\Documents\MyTest\swagger_simple.json /output:obj\swagger_s 
impleClient.cs " exited with code 1. [C:\Users\Ed Example\Documents\MyTest\test.csproj]
```

### .NET Version

6.0.404

### Anything else?

Running the following manually while making sure there is no issue with whitespaces works:

```
dotnet 'C:\Users\Ed Example\\.nuget\packages\nswag.msbuild\13.0.5\build\../tools/NetCore21//dotnet-nswag.dll' openapi2csclient /className:swagger_simpleClient /namespace:test /input:"C:\Users\Ed Example\Documents\MyTest\swagger_simple.json" /output:obj\swagger_simpleClient.cs 
```

So you can easily fix this by just adding some `"` and/or `'` characters.

**Comment by captainsafia** [comment] 2023-01-13 02:12
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/45926.

**Closed by captainsafia** 2023-01-13 02:12 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, area-web-frameworks

**Comment by sjoerd222888** [comment] 2023-01-13 13:06
Your LTS is 6.0 and this still does not work.
