### ISSUE TITLE
Cannot run blazor wasm projects in debug mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26079] opened 2020-09-18 22:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1187459/cannot-run-blazor-wasm-projects-in-debug-mode.html)._

---
[severity:I'm unable to use this version of Visual Studio]
Launching an ASP.NET Core hosting blazor web assembly app in debug mode does hangs. It opens a browser window to about: blank and after about minute or two then shows the attached error. This worked previously. The imported point here is that this kills the underlying asp.net core process as well making visual studio completely unusable for debugging a ASP.NET core host blazor wasm app. Even if the web assembly debugging cannot attach visual studio should not kill the server process. Ideally they would both just work though.

---
#### Feedback Bot on 9/16/2020, 11:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by nikonthethird** [comment] 2020-09-19 20:21
It's not just Visual Studio. After upgrading from .NET 5 Preview 8 to .NET 5 RC 1, the debugging session in a Visual Studio Code Blazor WASM app is very slow and can halt completely. On the other hand, launching the app via `dotnet run` is fine.

Here is the last log entry of a debug session that couldn't even load the favicon:
```text
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/assets/favicon.ico - -
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 GET https://localhost:5001/assets/favicon.ico - -
```
This is the final log entry, nothing more comes after it even after waiting 10 minutes. All subsequent requests timed out after about a minute.

On the other hand, when started with `dotnet run`, the log looks like this:
```text
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/assets/favicon.ico - -
dbug: Microsoft.AspNetCore.ResponseCompression.ResponseCompressionProvider[5]
      Response compression is not enabled for the Content-Type 'image/x-icon'.
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/assets/favicon.ico'. Physical path: '/home/nikon/Documents/Programming/TgrMgmt/Source/Client/wwwroot/assets/favicon.ico'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/assets/favicon.ico - - - 200 254188 image/x-icon 1.3588ms
```

It's not just that debugging breaks completely, when it works, requests to localhost that take a couple of milliseconds when using `dotnet run` can take multiple seconds during debugging, causing Firefox to show a turtle symbol next to the request in the network statistics.

Is there a way I can help to debug this? Somehow this does not seem related to Blazor at all...

**Comment by nikonthethird** [comment] 2020-09-19 20:47
The picture below shows one of the slow debug sessions. I display a list of thumbnails, and you can see that they took over 8s. (I removed the file names.)
![Slow](https://user-images.githubusercontent.com/15893812/93688862-7a924c00-fac9-11ea-864d-447efdc32c23.jpg)

This picture on the other hand shows the same list when started with `dotnet run`. Quite the difference.
![Fast](https://user-images.githubusercontent.com/15893812/93688902-e96fa500-fac9-11ea-93f6-f065af6c930a.jpg)

**Comment by captainsafia** [comment] 2020-09-21 15:39
@nikonthethird Thanks for sharing this info! Do you mind moving your bug report to a new issue? Your particular issue is different from what was originally reported. Some things that would be helpful to include in the report are:

- What server do you use to launch the app when running in VS (Kestrel or IIS)?
- Is your app a PWA? Hosted? Configured with auth? etc.

I'd recommend using the "Feedback" feature in VS so that the relevant logs will be included with your report.

> Launching an ASP.NET Core hosting blazor web assembly app in debug mode does hangs. It opens a browser window to about: blank and after about minute or two then shows the attached error... Even if the web assembly debugging cannot attach visual studio should not kill the server process. Ideally they would both just work though.

This is expected behavior. When starting an app with debugging enabled, VS will attempt to establish a debugging session. If it can't, it will bail out. If you're OK running your app without debugging enabled, I'd recommend using "Start without debugging."

**Closed** 2020-09-28 16:01 UTC
Labels: Author: Migration Bot :robot:, Needs: Author Feedback, Status: No Recent Activity, area-blazor
