### ISSUE TITLE
Deserializing an object with an IJSObjectReference property crash

### ISSUE THREAD

**Issue by Elyhaka** [dotnet/aspnetcore#29981] opened 2021-02-08 11:08 UTC
### Describe the bug

Deserializing a JS object into a .Net object with a property of type `IJSObjectReference` raises an error.

For instance, passing the a type with a IJSObjectReference property as a generic parameter `T` on `InvokeAsync<T>` will trigger a crash even if it exists on the underlying JS object.

### To Reproduce

Minimal reproduction can be achieved with this 3 files.

```html
<script>
  function getObject() { return {a: 'hello'} }
  function consoleLogMe(me) { console.log(me) }
</script>
```

```csharp
public class MyJsObject 
{
  [JsonPropertyName("myValue")]
  public IJSObjectReference MyValue { get; set; }
}
```

```razor
@page "/"
@inject IJSRuntime Js
@using System.Text.Json.Serialization

@code {
    public class At
    {
        [JsonPropertyName("a")]
        public IJSObjectReference A { get; set; }
    }
    
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        var obj = await Js.InvokeAsync<At>("getObject");
        await Js.InvokeVoidAsync("consoleLogMe", obj.A);
    }
}
```

### Exceptions (if any)

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: Required property __jsObjectId not found.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: Required property __jsObjectId not found.. See InnerException for more details.
 ---> System.Text.Json.JsonException: Required property __jsObjectId not found.
   at Microsoft.JSInterop.Infrastructure.JSObjectReferenceJsonConverter`2[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.JSInterop.Implementation.JSObjectReference, Microsoft.JSInterop, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, IJSObjectReference& value)
   at System.Text.Json.JsonPropertyInfo`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
[...]
```

### Further technical details

Reproduced on On Asp Net Core 5.0.2.

**Comment by pranavkm** [comment] 2021-02-08 19:05
Deserializing is only supported if the `IJSObjectReference` is the returned value. Nesting it as a property is not a scenario we had designed for or currently support. I'm resolving this as by design, we'll revisit this if we see feedback that this scenario is important.

**Comment by SteveSandersonMS** [comment] 2021-02-15 15:12
A clarification: you can have an `IJSObjectReference` nested arbitrarily in your object graph, but you need your JS-side code to declare it. Otherwise the JS-side logic has no way to know which part of the object graph to capture as a JSObjectReference.

Example:

```razor
@inject IJSRuntime Js
@using System.Text.Json.Serialization

@code {
    public class At
    {
        [JsonPropertyName("a")]
        public IJSObjectReference A { get; set; }
    }

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        var obj = await Js.InvokeAsync<At>("getObject");
        await Js.InvokeVoidAsync("consoleLogMe", obj.A);
    }
}
```

```html
    <script>
        function getObject() { return { a: DotNet.createJSObjectReference({ text: 'hello' }) } }
        function consoleLogMe(me) { console.log(me.text) }
    </script>
```

Notice that `DotNet.createJSObjectReference` creates the JS object reference that correctly deserializes as an `IJSObjectReference`. The value you supply has to be an object (e.g., `{ text: 'hello' }`) and not just a string literal (e.g., `'hello'`).

Also please bear in mind that whenever you create a JS object reference, you also need to dispose it (either on the .NET side or on the JS side) otherwise it will leak JS memory.

**Closed by SteveSandersonMS** 2021-02-15 15:12 UTC
Labels: :heavy_check_mark: Resolution: By Design, Status: Resolved, area-blazor, investigate
