### ISSUE TITLE
Blazor WebAssembly lazy loading assemblies not working when using @ref attribute in the component

### ISSUE THREAD

**Issue by ajithr** [dotnet/aspnetcore#29342] opened 2021-01-15 10:07 UTC
### Describe the bug
* When using Blazor WebAssembly lazy loading assemblies with component's `@ref` attribute, the corresponding assembly could not load issue throws in the browser console and the application not running.

### To Reproduce
https://github.com/ajithr/blazor-wasm-lazy-ref

* Check out the above repo and open `~/LazyLoadingRef/LazyLoadingRef.csproj` file in the `VS 2019`.
* Run the application it will throw exceptions in the browser console.
* Open `~/LazyLoadingRef/Pages/Counter.razor` file and remove `@ref` attribute and `LazyLoadComponent` reference in the `@code` section.
* Run the sample again and it will work properly with the lazy loading feature.
![image](https://user-images.githubusercontent.com/8641400/104714180-e4a2c100-574a-11eb-9ea8-2f3d0d1f0e92.png)

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/8641400/104710376-03528900-5746-11eb-8afd-aed4fbd4ce6e.png)

### Further technical details
- ASP.NET Core version - `.net5.0`
- Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/8641400/104710494-2b41ec80-5746-11eb-9d16-7492133b4101.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
![image](https://user-images.githubusercontent.com/8641400/104710733-6d6b2e00-5746-11eb-98d8-399e1cb60a9f.png)

**Comment by javiercn** [comment] 2021-01-15 11:01
@ajithr thanks for contacting us.

This seems to be an issue, I can't tell there's anything wrong from looking at the code.

@captainsafia do you have any thoughts?

**Comment by ajithr** [comment] 2021-03-17 04:00
@mkArtakMSFT @javiercn @captainsafia The issue is closed itself by msftbot. Do we really need to create a new issue report for this? It is not yet discussed and it is under investigation.

**Comment by captainsafia** [comment] 2021-03-17 22:38
@ajithr Thanks for the following up. Reopening this issue and moving to backlog.

I had a hunch that this might be caused by some issues that existed in the codepaths used for assembly loading in the WASM runtime. We'll need to (1) validate if this still happens in .NET 6 and (2) investigate why if it does.

**Comment by guardrex** [comment] 2021-07-08 10:27
@captainsafia ... My error from our offline chat is the same accessing a type in a lazily-loaded RCL assembly. Should I add my error details here or open a new issue?

**Comment by captainsafia** [comment] 2021-07-12 20:20
@guardrex You can add the details here. Both issues might have the same root cause.

**Comment by guardrex** [comment] 2021-07-12 20:28
Error:

> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
> Unhandled exception rendering component: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
> Could not load type of field 'LazyLoadTest.Pages.Robot+RobotModel:<AxisSelection>k__BackingField' (0) due to: Could not load file or assembly 'GrantImaharaRobotControls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

The error isn't thrown when the user tries to navigate to the component: It's thrown at app start up.

The lazily-loaded RCL assembly (`GrantImaharaRobotControls.dll`) includes:

```csharp
public enum Axis
{ 
    Left,
    Right,
}
```

The WASM **app** seeks to use the type in a component (`Pages/Robot.razor` in the app) ...

```razor
@page "/robot"
@using GrantImaharaRobotControls

...

@code {
    private RobotModel robotModel = new() { AxisSelection = Axis.Left };
    
    ...

    public class RobotModel
    {
        public Axis AxisSelection { get; set; }
    }
}
```

In `App.razor` ...

```csharp
if (args.Path.EndsWith("/robot"))
{
    var assemblies = await AssemblyLoader.LoadAssembliesAsync(new[] { "GrantImaharaRobotControls.dll" });
    lazyLoadedAssemblies.AddRange(assemblies);
}
```

In the project file ...

```xml
<ItemGroup>
  <BlazorWebAssemblyLazyLoad Include="GrantImaharaRobotControls.dll" />
</ItemGroup>
```

Repro project: https://github.com/guardrex/LazyLoadSolution

To workaround this for the doc, I've simply placed the `Robot` component into the RCL. It's routable from the app, renders fine, and uses `Axis` fine in the RCL. We can go with that for the doc. I cross-link to this engineering issue from a remark in the topic. I'll revert/version and/or update the doc remark later. I plan to shoot that PR in shortly ... tomorrow maybe. https://github.com/dotnet/AspNetCore.Docs/pull/22603

**Comment by Bala-tec** [comment] 2021-11-19 06:15
Hi Guys, 
I'm facing same exceptions. May I know the status of this issue?

**Comment by Sureshv2** [comment] 2021-12-12 11:31
Hi Guys

Because of @ref attribute issue, we cannot use lazy loading assembly feature in our project and it is downloading all referenced assemblies which is not required at initial startup page.  Please do let us know that when it could be fixed.

**Comment by bingxueyinlian** [comment] 2021-12-17 11:10
same problem

**Comment by syncsiva** [comment] 2022-03-07 04:23
Hi Guys, Any update on this issue. This affects using Lazy loading in blazor WASM apps.

**Comment by laurence73** [comment] 2022-04-29 12:46
same problem

**Comment by danroth27** [comment] 2022-11-16 16:35
Both repro projects seem to work fine with .NET 7, so it looks like this issue is now fixed. If you're still hitting this issue, please let us know and provide detailed steps to reproduce the problem and we'll take another look.

**Closed by danroth27** 2022-11-16 16:35 UTC
Labels: bug, area-blazor, triaged, blazor-wasm, feature-blazor-lazy-loading, affected-few, severity-major, feature-blazor-builtin-components
