### ISSUE TITLE
Question: what are the necessary configuration options to add Open API support to a aspnetcore hosted Blazor Wasm Server project with Authentication/Authorization

### ISSUE THREAD

**Issue by wvmstr** [dotnet/aspnetcore#34201] opened 2021-07-08 14:08 UTC
It is really convenient to be able to use Swagger during development of the Server project of the project type referenced in the title.

I have been able to come as far as the Swagger UI showing up when I navigate to the Server project by itself, however then there are exceptions which I think mean Authentication/Authorization is not set up.

Been Binging/Googling for a while and have not found anything useful, and I am blocked.

This developer's velocity = 0

**Comment by mkArtakMSFT** [comment] 2021-07-08 16:35
Thanks for contacting us.
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/34200

**Comment by mkArtakMSFT** [comment] 2021-07-08 16:36
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **blazor** tag.

**Closed by mkArtakMSFT** 2021-07-08 16:36 UTC
Labels: area-blazor, blazor-wasm, feature-openapi
