### ISSUE TITLE
IEndpointRouteBuilder.Map throws an exception for a parameter of a nullable value type with a default value

### ISSUE THREAD

**Issue by AleyCZ** [dotnet/aspnetcore#45867] opened 2023-01-04 12:28 UTC
(Please excuse me if I did something wrongly, this is my very first ticket created here.)

*This seems like a bug:*

`IEndpointRouteBuilder.Map` extension method (and its sister methods) is used to register routing. The problem is that it throws an exception when I have a parameter of a nullable value type with a default value. (Nullable value types without default values work, as well as non-nullable value types in general.)

This can be easily reproduced with an NUnit test:

    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using Microsoft.Extensions.Hosting.Internal;
    using NUnit.Framework;

    namespace Mynt.Connect.Plugins.NewApi.Tests.RequestProcessor;

    public class RouteBuilderTests
    {
        private IServiceProvider serviceProvider;

        [SetUp]
        public void Setup()
        {
            var sc = new ServiceCollection();
            sc
                .AddSingleton<IHostEnvironment, HostingEnvironment>()
                .AddOptions()
                .AddRouting()
                .AddSingleton<FakeHandler>();

            serviceProvider = sc.BuildServiceProvider();
        }

        [Test]
        public void Test()
        {
            var applicationBuilder = new ApplicationBuilder(serviceProvider);

            applicationBuilder.UseRouting();
            applicationBuilder.UseEndpoints(endpointRouteBuilder =>
            {
                FakeHandler handler = new FakeHandler();
                endpointRouteBuilder.Map("anypath", handler.HandlingMethod);
            });
        }
    }

    public class FakeHandler
    {
        public Task<int> HandlingMethod(int? param1, int param2 = 123, int? param3 = null)
        {
            throw new NotImplementedException();
        }
    }

This example code throws the following exception:

    System.ArgumentException : Expression of type 'System.Object' cannot be used for assignment to type 'System.Nullable`1[System.Int32]'
        at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.BindParameterFromValue(ParameterInfo parameter, Expression valueExpression, FactoryContext factoryContext, String source)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArgument(ParameterInfo parameter, FactoryContext factoryContext)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArguments(ParameterInfo[] parameters, FactoryContext factoryContext)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateTargetableRequestDelegate(MethodInfo methodInfo, Expression targetExpression, FactoryContext factoryContext)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.Create(Delegate handler, RequestDelegateFactoryOptions options)
       at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler, Boolean disableInferBodyFromParameters)
       at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(IEndpointRouteBuilder endpoints, String pattern, Delegate handler)

Looking at my `FakeHandler.HandlingMethod`, you can see it has three parameters. The issue is caused only by `param3`, which is a nullable value type with a default value `null`. A similar exception also occurs when I try to use a numeric default value instead of `null`. (If a not-null default is provided, it says it cannot assign `System.Int32` to `System.Nullable`1[System.Int32]`.) Other two parameters are OK.

*Expected behavior:*

It should be able to have a handler with default values, including nullable value types.

*Why I need this:*

The main reason why I need this may help to find some other solution to my task, so let me explain: We use minimal API with a very simple http API. But we also have dynamic plugins in the service and we want to allow them to have something like controllers in them. Dynamic plugins are dynamically loaded .NET assemblies. I tried to use attribute-based routing - I wrote a simple helper method which scans the whole assembly for classic MVC routing attributes (`HttpGet`, `HttpPost`...) and then tries to add those methods to routing by calling `MapMethods` extension method (which then calls more generic Map method). And this seems to work, only these nullable value types with default values throw exceptions.

I think a good solution for my task would be to have something like *IEndpointRouteBuilder.MapMethod(MethodInfo)*, but this does not seem to be supported by ASP.NET Core. And that is especially surprising, because it seems there is no way how we can register a handling method without instantiating the declaring class in the moment of registration. I think it makes more sense to register a handler with a `MethodInfo` instead of a delegate and let ASP.NET Core create the instance of the handling class dynamically with the service provider in the time of need. At the moment, ASP.NET Core forces us to instantiate all these pseudo-controller handing classes during registration of routing. Which I think completely violates the principle of dependency inversion. (Maybe this is a topic for a feature request?)

**Comment by davidfowl** [comment] 2023-01-05 06:17
We should fix the nullable issue, that looks like a bug. 

> I think a good solution for my task would be to have something like IEndpointRouteBuilder.MapMethod(MethodInfo), but this does not seem to be supported by ASP.NET Core. 

Please file an [API proposal](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=) for that, explaining the usage with a *real* example.


> At the moment, ASP.NET Core forces us to instantiate all these pseudo-controller handing classes during registration of routing. Which I think completely violates the principle of dependency inversion. (Maybe this is a topic for a feature request?)

This is absolutely the case by default, but you can extend it. Extending routing means building your own `EndpointDatasource`. That will let you do what you want and give you whatever control you need over how endpoints are built and refreshed.

**Comment by halter73** [comment] 2023-01-27 03:14
This is a dupe of #40774 which was fixed in .NET 7. I verified that your repro fails as described when targeting net6.0 but not net7.0.

**Closed by halter73** 2023-01-27 03:14 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-web-frameworks
