### ISSUE TITLE
SignalR Core for .NET 5 sends malformed messages

### ISSUE THREAD

**Issue by miroslavp** [dotnet/aspnetcore#28065] opened 2020-11-23 02:12 UTC
### Describe the bug
After upgrading to .NET 5, my SignalR project does not work properly anymore. The project is Blazor WASM using C# SignalR Core client. The bug can be easily reproduced when sending messages containing long strings. Basically when sending big messages they appear in the browser console as malformed (only the end of the json is preserved/sent.)
Setting ApplicationMaxBufferSize and TransportMaxBufferSize to 0, does not help.
**The code breaks both with the JSON and MessagePack protocols**

The code was working fine before upgrading from 3.1.8 to .NET 5, both with JSON and MessagePack

### To Reproduce

The issue can be easily reproduced.

This is the code in Startup.cs on the server (BlazorApp123.Server)

```csharp
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllersWithViews();
            services.AddRazorPages();


            services.AddSignalR(opts =>
            {
                opts.EnableDetailedErrors = true;
            })
            .AddJsonProtocol(options =>
            {
                options.PayloadSerializerOptions.PropertyNameCaseInsensitive = true;
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebAssemblyDebugging();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToFile("index.html");
                endpoints.MapHub<MainHub>("/mainHub", opts =>
                {
                    opts.ApplicationMaxBufferSize = 0;
                    opts.TransportMaxBufferSize = 0;
                });
            });
        }
```
The hub is very simple
```csharp
    public class MainHub : Hub
    {
        public async Task TestMethod(TestMessage msg)
        {
            //some logic here
        }
    }
```

Here we have a simple dto class in the shared project (BlazorApp123.Shared)
```csharp
    public class TestMessage
    {
        public string TestProperty { get; set; }
    }

```

This is the code in the blazor component Index.razor.cs (simplified for brevity)
```csharp
    public partial class Index : ComponentBase
    {
        protected async override Task OnInitializedAsync()
        {
            await MyMethod();
        }

        public async Task MyMethod()
        {
            var connectionBuilder = new HubConnectionBuilder();

            var connection = connectionBuilder.WithUrl(($"https://localhost:44328/mainHub"),
                    opt =>
                    {
                            opt.Transports = HttpTransportType.WebSockets;
                        })
                .AddJsonProtocol()
                .Build();
            await connection.StartAsync();

            var msg = new TestMessage();

            string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            Random random = new Random();
            int length = 1334;

            msg.TestProperty = new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());


            await connection.InvokeAsync("TestMethod", msg);
        }
    }
```
The code above just creates random string of 1334 characters. If I change it to 1335 and exception occurs.
### Exceptions (if any)

This is the malformed message
"H66YBF8GC26ALKSI42W4YR583MKEV69MZ67C9AW1H9F5VXCJD5FJHTX0A74Z53UF3TKONPI4G5XZL9MGJBB00ZFGIHCBF66NO9CCMX6XWLDL58OAUYQ324PENDGFNHYJ8KKM7K3VEODPV4LJ2BRRQCUTU8YIR0JPW4NUYBDK44ZO09ST26MMZH35Z129VVDOEY20Q0V17GXVNG2UPEQVN7ZPBR57JDYI0KKCH1DBKVOTTHRT8IURERAH9NZ85YS4SO4D60MXBOL1SG54AL8ATHEJKCD4CEFVDUAFMOWH57P0GIY2R58TZRKKKV33XSV7IZY7FZRVZ1EW2OCBNKMGFW5WJ050V3TNMRRRU1X1ON48MYS6T1PMGO1W3BXP4096H1KK6VQWXU2217JVH9H3NHH704XSDH7XN80UOI98L3ZVV9562CI4TFTAUMUC87TPXFO3GYH9AJSTRVL0910A9CDHP0ABX79NKJ8QVBZD5I4KX9S9B3CGHSQUBGNQYFLCJFJIX4F7CWF0I3UPHAA453F23OPOYIOZ71BS0KMGYEEUMZLIW7JXFRHQ9ROIP1J3HP3Q2BZ6Y4F0YUPECG1080UQTVSJ6D074LN665QUIM9KLR1OBKGI9T4Q5M7HSQAVDI5NHSIH0HSV1JEC3EHV6R7LQ6BT8JB1MNHDVOHSC9S1AJZVH4NOIOYVKU7LRYJRF0JOCBQO7ZT79GKHHPLD5WT7YV2BR5ANZBWK9KTGO8RT51WEJZDBNGVTHLZQIP7BYGI7UAH66FZ6F9C78Y21199TPDDXUC78BP4YTYUJSHEIQZNHJ2SUWFJYGYSR7UL4I05ZENOJESJU41C0Z5O2TML5GFS4GDM85KA03XC6OIQD6Z4PV11BGTK5O9T95TDBGLZT1M6C3ROL6H8QLCJOLK2MAEL4DDB4FP7VAKXI4ZIYE98GADX2JYZ5TMTWBC8ZQTFRKNQAOAUWCDHBGE3APIURZBCX1BH20SHV3R5XWWNJEC3PFSQ6J8JH8Y1JL3JN315U6WHYIGO35LNXHXSIULT2I9WFZWM2M9QMGISTL1XCTQMXKEBXLB2RIDM69C9W4VQ55AQ9E973YQI1X94UUYRLH8DD6WTI2AI8AQ1JYCTMD9314UJAHOBFEEY66NDSPYAXIK1GHU6SFFHHFMILNSBN8C4615ML9B6P8FTU3C3WRTA86Q1UE1F6XWYFQ5OLHVTDI2J92XSKZO5PB59KE2GI591LQNE8XRP6970EH12RI4HJ0IEV5EHPOLHJA7SOTUXI89QEF5DN9Z9B2SUIJTCTJ9RYZQDKIN7YG9K129PAA4PZLGRRMKE"}]}

This is the response from the server
{"type":7,"error":"Connection closed with an error. InvalidDataException: Unexpected JSON Token Type 'String'. Expected a JSON Object.","allowReconnect":true}

And this is the message when it is sent successfully (when number of chars is 1334 or less)
{"type":6}{"type":1,"invocationId":"1","target":"TestMethod","arguments":[{"testProperty":"97PM59VOG8IVK7QNM19NKKKM9YQ51N3ZJ5OBYU5HC5BJA5QJCYLYZARZWDNGT0W2FTLOSPZ261KPIBLDHG2DBFAJOZOUHYYMJIDRUC1X9T27ZCQV2J8M7S1ATC92AFVHC8F973TFPEESMCTMI3170MO0RD8SC8X48U516RX80273OIXQSXTHNXQ0TPR35BCRQKT2H2P1F2H7PVLJQR9POQQKDEHRA4DYZQMEZ5JZH2BUQTL8DINOBXCA3JYCU81LZSH8IHTVHJHWO64U3JO1QYWCNLKPGHEJB047MMZ5Y2G1QQW7PEILU94A5FV66EOAE8UXB6IRTSDYR4V7ZNAB83YB53BG028UNGXS585S602B6GTBUYHTDNBLJT2H4B00TTKLHDB0RRFIAWFYKAWCVPQ9FLILGXY49BSN5H3QWQBVI2KWOD73PYFDCKF64ZU43KI9E13CHFQEO51MAV7C05PL6OLUB6V66H27ULSWK4VJHAZHS35J2RD846D0QIAKTTIHC41ZDK26JGE5YEBIBMEOD3DXI2GB3KZX2SEYBGFSZHZX2HBMG2JHP4DJ1EQLD0C8RQDG9NH4GWZ6EP5A045BBSI8O577Z4O8E0GLE5M3VPA3EHELIQUJ5B79IE1EPJEMH11OIT65RCQVRO3G0VYJJEDD3HD9DHNLKYVNQ0DYTZ12VLR3LVO4U4CDYYUAP71KYEK32Q0AS90TMKSR0KXS3T0PWSZ2FCJW8RDQAYA54NMVES0NGDKFJJQFO5GK074P0DV5GBQBJ2XPHFKE2LWC2DNZB8BFR0E6S64B65HEWJ5QVA8JUCSOL2XW063IALTTX06KKJH6ESQSI7DA92VPH0V0JHLAB8EKZL24EX8K5VJ3MEN333IH0EM7FGBC8H5GNF37EI6M3KUWQ1OF3RGH06UU94Z7W5MX0DPGKQYU76NPUZRN16IQAXPRVI7JS8Z8866MMI4M3WK3SEAJNMF0W5WCX7VCTPB8HPRX3EATB6XOMW8QHX5G28LCJ3YOW13OULWDXMPILVY0IIZB9E45T4GIDOOAPW7JCJ3B9534HX5GJV4ADXPR774ZFN9I8P3YYOY9PYBDL9X6998SUN72HPMEOD6W6U624GS465VOVLF8K80GOQYVRARJCTUL2PG1D5C2REVY1SG5JN4PNZHQ5KK3ZI2NKKWGFO5O68ZK4A484WAYYE8CI062UICILIOQ6A05SPTOA6V5QL9CIDYFMT8ORC3X5Q8WWNC36EGIVTCLFAMJJ99ITIENBLNPW5TT79JCJFGD7PU3RWJQ0UO5R0CNJZ1U10WZASOF1J9D35LDXK5PC6"}]}
### Further technical details
- .NET 5
- Visual Studio Community 2019 16.8.1

**Comment by BrennanConroy** [comment] 2020-11-23 02:27
Dupe of https://github.com/dotnet/aspnetcore/issues/27774

Runtime issue tracking this has been fixed https://github.com/dotnet/runtime/issues/44551 and will be in 5.0.1

**Closed** 2020-11-23 22:13 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
