### ISSUE TITLE
The config for identity isn't sync with client-side validation for password

### ISSUE THREAD

**Issue by mamdos** [dotnet/aspnetcore#40793] opened 2022-03-21 09:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I recently faced this bug that is , when I change the password minimum length in identity configure it doesn't make any change to client-side validation and client-side validation is always fixed with 6 password lengths.

### Expected Behavior

for example, I want the minimum length of the password to be 8 chars and I change it in identity configuration when the user enters 4 chars password the app says to the user that your password must be more than 6 chars which is incorrect, it must be more than 8 chars.

### .NET Version

6

**Comment by HaoK** [comment] 2022-03-21 21:02
Dupe of https://github.com/dotnet/aspnetcore/issues/25788

**Closed by HaoK** 2022-03-21 21:02 UTC
Labels: area-identity
