### ISSUE TITLE
TopLevelParameterNameAnalyzer threw an exception of type System.NullReferenceException.

### ISSUE THREAD

**Issue by twitchax** [dotnet/aspnetcore#14723] opened 2019-10-04 06:31 UTC
### Describe the bug
The warning below is emitted when [building my project](https://github.com/twitchax/AspNetCore.Proxy/commit/ab68b5dc7e231d8180994f2aedcda097f6f0190e/checks?check_suite_id=250379972#step:5:25).

```
CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

### To Reproduce
1. Install [.NET Core SDK 3.0.100](https://dotnet.microsoft.com/download/dotnet-core/3.0).
1. `git clone git@github.com:twitchax/AspNetCore.Proxy.git`
1. `dotnet test`

### Expected behavior
No warnings.

### Screenshots
N/A.

### Additional context

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005051 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005077 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005098 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0-preview1-005977 [C:\Program Files\dotnet\sdk]
  2.0.0-preview2-006497 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2-vspre-006949 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.1-preview-007094 [C:\Program Files\dotnet\sdk]
  2.1.1-preview-007165 [C:\Program Files\dotnet\sdk]
  2.1.1 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007326 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007363 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007474 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007597 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009171 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0-preview1-002111-00 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0-preview2-25407-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by twitchax** [comment] 2019-10-04 06:41
Well, frustratingly, I opened up the latest VS 2019 Preview, and now the warnings have disappeared.

However, the warnings continue to appear:
* In WSL. with 3.0.100.
* In an ubuntu docker container with 3.0.100.
* In my GitHub Action build, which is an ubuntu docker container with 3.0.100.

Is there a delta in the toolchains between the .NET Core 3.0 SDK and the VS 2019 16.3.0 toolchain that would cause this to only appear on a bare machine with .NET Core 3.0, while not appearing on a machine with VS 2019 16.3.0?

**Comment by pranavkm** [comment] 2019-10-04 13:49
@twitchax the test app is using a 3.0.0 of `Microsoft.AspNetCore.TestHost` which is effectively lifting the tests to compile the app against 3.0.0 versions of ASP.NET Core. Your app is still targeting .NET Core 2.2. Given there were many breaking changes in 3.0, I don't think you want to mix the two versions when testing. 

Consider changing the test app to target `2.2.x` version of TestHost or [migrating your application](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio) to .NET Core 3.0. Alternatively, you should be able to [suppress the analyzer](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019) in the test project.

----------------------------------

More details:
The null refs is a result of one of the breaking changes in 3.0 - some types that were formerly pub-internal were moved to a public interface while also changing their namespace. The app's package reference to `Microsoft.AspNetCore.Mvc` to 2.2.0 gets lifted to the 3.0.0 framework reference in the test app, but the analyzer package remains 2.2.0. You effectively get this:

![image](https://user-images.githubusercontent.com/174281/66211883-86032200-e682-11e9-928f-105fbead7608.png)

This might fall in to the category of the SDK lifting the 2.2 analyzer package reference to a 3.0 version if it sees a `FrameworkReference` to `Microsoft.AspNetCore.App`, but I'm not sure how trivial that is.

**Comment by mkArtakMSFT** [comment] 2019-10-04 16:37
While this seems to be a non-supported scenario, let's try to polish up the analyzer to account for this scenarios too.

**Comment by Shiko1st** [comment] 2019-10-31 21:18
Have the same problem after migration to core 3, visual studio is 16.3.7

**Comment by yuchen-w** [comment] 2019-11-20 20:49
Without disabling the Code Analysis (Project Settings > Code Analysis > Run On Build) this error prevents my project from building in Visual Studio.

**Comment by sm-g** [comment] 2019-11-26 18:18
@yuchen-w You probably have nuget package which have 2.2.0 as dependency, like:

![devenv_2019-11-26_21-16-53](https://user-images.githubusercontent.com/7280273/69660828-347b8000-1092-11ea-884d-da5a2891a41a.png)

**Comment by PeterPann23** [comment] 2020-02-04 17:12
I have a similar issue that get's introduced by a dll that uses entity framework where EF is abstracted from the consuming assembly. It then load analyzers from 
![image](https://user-images.githubusercontent.com/44400822/73768750-dd70e600-4779-11ea-8033-48121a4d18c4.png)

**Comment by ChrisProlls** [comment] 2020-02-13 10:04
Same warning for me, is there any solution ?

**Comment by OwenPattison** [comment] 2020-02-19 16:57
I am also seeing the same issue, @PeterPann23 were you able to resolve your issue?

**Comment by PeterPann23** [comment] 2020-02-19 17:48
Yes, I have noted that the issue is that code analysis by default does generate the issue by the way it is configured. 
2 options:
![image](https://user-images.githubusercontent.com/44400822/74859920-24e59d80-5348-11ea-8682-14fa52618b76.png)
remove the checkboxes, the default is checked and what it installs does not work

![image](https://user-images.githubusercontent.com/44400822/74860066-53fc0f00-5348-11ea-904b-753e1051bfff.png)
and then 
![image](https://user-images.githubusercontent.com/44400822/74860102-60806780-5348-11ea-989b-acf3bcbcb5fd.png)
update to the new version, no clue why it isn't installing a updated version to start with

**Comment by pranavkm** [comment] 2020-02-19 19:00
From the reports we've seen for this issue, this seems to only occur if you have an app that mixes 3.x shared framework and 2.x packages. 

* If you haven't already looked at our migration guide,  https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio, I'd recommend starting there. 
* If you've followed the steps in the migration guide but continue to see this error, please file a separate issue. A resolution for the issue reported here might not your help in your case since it's specific to using 2.x and 3.x binaries in the same application, something which we generally do not support.  
* If this is blocking you from building your applications, you can turn off the analyzers that the WebSDK adds by setting this property in your project file:

```xml
<PropertyGroup>
   <DisableImplicitAspNetCoreAnalyzers>true</DisableImplicitAspNetCoreAnalyzers>
</PropertyGroup>
```

We generally wouldn't recommend doing this since the analyzers will recommend against using problematic code patterns, but getting an application building is much more important.

**Comment by PeterPann23** [comment] 2020-02-20 05:06
this is definitely not the case with my projects, they are not migrated to start with and I do not have 2.2 on my station. the issue I have is the default analyzers are wrong on a "file new project"

**Comment by OwenPattison** [comment] 2020-02-20 10:44
@PeterPann23 thanks for the feedback, I can confirm i was up to date with analyzers and had those options checked.

I've delved deeper into external dependencies as per @pranavkm comments and can confirm I found a nested package that had a 2.x dependency which seems to have solved the problem for me, thanks for the suggestions.

**Comment by TahirAhmadov** [comment] 2020-05-06 15:12
I'm still getting this message. Under dependencies, I see analyzers for 2.2 and 3.1 which I think is the problem, but I can't figure out how to get rid of the 2.2 analyzers. (The project is targeting .NET Core 3.1)

**Comment by PeterPann23** [comment] 2020-05-06 18:51
perhaps have a look at each nuget package and have a look if you have the right ones, sometimes this happens when you have a nuget package added that was suggested by intellisense when actually it's mend as a dependent project, 

after that you have a version 2.2 package in a 3.1 solution that actually you do not need as it's coming in the right version from another nuget package. 

In my case I had .net core entity framework packages added wher actually I needed to remove all and have only the SQL  server nuget and the right dependent core EF loaded and the FXCop issues where okey and the conflict was solved.

**Comment by mkArtakMSFT** [comment] 2020-05-21 20:36
Closing this as there are no follow-up items left here. If you hit this issue, read @pranavkm 's comment above: https://github.com/dotnet/aspnetcore/issues/14723#issuecomment-588389938

**Closed by mkArtakMSFT** 2020-05-21 20:36 UTC
Labels: analyzer, area-mvc, bug

**Comment by Vaccano** [comment] 2020-06-02 18:19
This page is the top of google for this error.

It would be nice to post here a way to check if you have any pre 3.x .Net Core dependencies.  

Or do I just have to expand all my dependency trees in all my projects and try to visually catch any that are referencing the wrong version.

**Comment by pranavkm** [comment] 2020-06-02 18:38
@Vaccano unfortunately there isn't a very good way to do this. The two approaches that I have followed were:

* to use the search option in Solution Explorer

![image](https://user-images.githubusercontent.com/174281/83556701-39980c80-a4c5-11ea-8fb5-a9fc023c938d.png)

* or opening up the `obj\project.assets.json` and looking for packages or projects that reference MVC.
