### ISSUE TITLE
Visual Studio warning about razor component closing tag

### ISSUE THREAD

**Issue by stsrki** [dotnet/aspnetcore#18685] opened 2020-01-30 15:54 UTC
I have a razor component named `Link`. When I try to use it Visual Studio keeps warning me that it cannot have closing tag. I guess the IntelliSense is thinking it is a regular html tag named `link` which is a lower-cased. I know the Blazor team has allowed us to have razor components that are named with upper-case a few month ago, so it's strange for me why this is not working.

**Example:**

![image](https://user-images.githubusercontent.com/900302/73465465-baf95a00-4380-11ea-8e1b-b3ccec2e1ccd.png)

*EDIT: The component works just fine, it's just that the VS is raising the warning.

**Comment by mkArtakMSFT** [comment] 2020-01-30 17:46
Thanks for contacting us.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment] 2020-01-30 21:14
@ToddGrun You guys look to be ignoring the componentization of `</Link>` here. Would this be an easy, trivial fix to perform? If not, this work will be solved by LSPification.

**Comment by ToddGrun** [comment] 2020-01-31 16:42
I wouldn't say it's a trivial change. There appear to be both classification and error issues that need to be changed to understand razor components. Adding @jodavis to help determine whether this is high enough priority to fix before the LSPification.

**Comment by jodavis** [comment] 2020-02-04 05:49
If there was a simple short-term fix, I would say go for it. But since we already have the right long-term fix on the roadmap, and the impact of the issue, while annoying, isn't blocking anything, I think we should wait for the right fix. Let me know if there's something that makes this more severe than my current read on it.

**Comment by stsrki** [comment] 2020-02-04 08:46
I would like to mention that while the warning for the `<Link>` was not blocking me from using it in the client-side app, it was giving me a compile error when trying to use it in another class-library project.

![image](https://user-images.githubusercontent.com/900302/73728143-146fd900-4733-11ea-9b81-513b43e7d22d.png)

![image](https://user-images.githubusercontent.com/900302/73728155-19cd2380-4733-11ea-9d2d-44b1837462db.png)

So to workaround the error I had to define full path to the component, including the namespace. eg 

![image](https://user-images.githubusercontent.com/900302/73728186-2b163000-4733-11ea-9a6c-3104afe11cf4.png)

I agree that the issue is not a blocker, but I also think this should be addressed as soon as possible as it would allow something that in other client-side libraries already works.

**Comment by jodavis** [comment] 2020-02-04 13:11
I don't think those errors are coming from the editor. The editor creates a warning with the text "Closing tag supplied for self-closing element. Remove closing tag." But it would only be noise when the file is open in the VS editor. It would never cause build-time errors.

@NTaylorMullen Does the Blazor parser have any special logic around "link" tags? It looks like it's failing to match up the start and end tags, since there are errors for both "missing end tag" and "unexpected end tag."

**Comment by NTaylorMullen** [comment] 2020-02-04 19:41
Does not have any special logic around `Link` tags surprisingly. @strski that's definitely worrisome and I agree with @jodavis. If you're getting compile time errors that would be a separate issue. If you could provide a repro app I'd be happy to take a look.

**Comment by stsrki** [comment] 2020-02-04 21:28
@NTaylorMullen I have created a repro project: https://github.com/stsrki/BlazorClosingTagIssue

Also I found out what triggers the error. It is happening every time that `<Link>` is placed inside of `@if( ) { }` statement. Example in the screen-shot:

![image](https://user-images.githubusercontent.com/900302/73788470-5df50e00-479d-11ea-9fda-c5ac3f8b01ca.png)

Without the `if` statement only the warning is raised. Very weird. Anyways, If you need anything else please let me know. tnx

**Comment by NTaylorMullen** [comment] 2020-02-05 01:18
Thanks for the repro @stsrki. 

@mkArtakMSFT I can reproduce this in VS and in VSCode. It's definitely a parser issue. Seems like our parser is treating the `Link` tag as the void element `link` instead of the Component `Link`. I'll leave this in the next spring planning (and unassigning myself) for you to decide if it's worth fixing (given this is the first report we've had of this) since the issue has existed since v1.0 of Blazor/components.

To workaround your issue for now if you are to change your component to something other than `Link` all should work fine.

**Comment by stsrki** [comment] 2020-02-05 11:31
@NTaylorMullen Thank you for committing to this issue. I will leave it as a `Link` but I will advise it to the users of my library to always write it as `Blazorise.Link`. So once the issue is fixed I will just remove the note from my documentation.

**Comment by fastlink30** [comment] 2021-01-06 16:47
reading this solved my problem! good is to insert this information on the documentation

**Comment by CaiusJard** [comment] 2021-09-08 09:12
@NTaylorMullen just wanted to flag up (and it might have been raised elsewhere) that Blazorise's `<Text>` possibly also suffers some similar affliction/confusion with `<text>`. When used in markup-that-was-already-markup it's fine, but when used as the first element in a markup-inside-code it becomes a compiler and syntax highlighting error:

![image](https://user-images.githubusercontent.com/68939130/132481375-31fb9367-c268-4b50-9e63-096237e8daa0.png)

**Comment by allisonchou** [comment] 2021-10-05 05:24
Per Taylor's earlier comment, this should be fixed in the new Razor editor (VS 2022). Closing out this issue for now, please feel free to file another issue if the problem persists. Thanks!

**Closed by allisonchou** 2021-10-05 05:24 UTC
Labels: bug, area-blazor, area-razor.tooling, feature-razor.language, affected-few, severity-minor
