### ISSUE TITLE
Blazor Net 8 interactive auto <NotFound> not triggerd

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#52660] opened 2023-12-08 14:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using the default template of Blazor with interactive mode set to auto (server and webassembly) we are getting the Routes.razor in the server project.

I've added also the <NotFound> component to display some pretty 404 page, but it seems it is not working, the browser's default 404 page is getting displayed:

```
<Router AppAssembly="@typeof(Program).Assembly" AdditionalAssemblies="new[] { typeof(Client._Imports).Assembly }">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(Layout.MainLayout)">
            <h1>Not Found</h1>
        </LayoutView>
    </NotFound>
</Router>
```

![image](https://github.com/dotnet/aspnetcore/assets/549272/7e618592-0134-496f-94b3-996d41dbaea3)

**Comment by MariovanZeist** [comment] 2023-12-09 08:38
Hi @mihaimyh 
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/52251 
potentially more info also here https://github.com/dotnet/aspnetcore/issues/48983

**Comment by javiercn** [comment] 2023-12-12 15:21
@MariovanZeist is correct.

**Closed by javiercn** 2023-12-12 15:21 UTC
Labels: area-blazor

**Comment by mandeep-sps** [comment] 2023-12-14 11:16
@javiercn @MariovanZeist Not Found is not working in Blazor Dotnet 8.
I have added these line of Code:-
<NotFound>
    <LayoutView Layout="@typeof(Layout.MainLayout)">
        <h1>Not Found</h1>
    </LayoutView>
</NotFound>

Please help me on this part.

**Comment by mandeep-sps** [comment] 2023-12-14 12:14
Hi team I got the Solution:-
```
app.UseStatusCodePagesWithRedirects("/404");

app.Run();
Add a _404.razor page to your Pages folder.


@page "/404"
<h3>Show me 404</h3>
@code {
    
}
```

Dotnet 8 Web app Template
