### ISSUE TITLE
Issue while converting .net 6 to .net 8 for IHttpContextAccessor.

### ISSUE THREAD

**Issue by NitinDevang** [dotnet/aspnetcore#54958] opened 2024-04-05 06:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While upgrading dot net 6 to dot net 8 for azure function it is giving issue as IHttpContextAccessor is null.[](url)

### Expected Behavior

It should create object of HttpContextAccessor and should smoothly run.

### Steps To Reproduce

Upgrade project from dot net 6 to dot net 8

### .NET Version

8.0

**Comment by martincostello** [comment] 2024-04-05 07:35
Looks like a duplicate of https://github.com/dotnet/aspnetcore/issues/53143, which is an issue with Azure Functions: https://github.com/Azure/azure-functions-dotnet-worker/issues/2372

**Comment by amcasey** [comment] 2024-04-05 19:46
The details here are sparse, but I agree that it looks like a dup.  Please let us know if you have reason to believe you're seeing a different issue.

**Closed by amcasey** 2024-04-05 19:46 UTC
Labels: area-networking
