### ISSUE TITLE
SignalR in Electron not working

### ISSUE THREAD

**Issue by hillin** [dotnet/aspnetcore#58545] opened 2024-10-21 14:02 UTC
We have a SignalR hub in our web app, consumed in the frontend with `"@microsoft/signalr": "^8.0.0"`. It worked fine in browsers, but once they are packed into an Electron app (with [Electron.NET](https://github.com/ElectronNET/Electron.NET)), an error occurs when trying to connect to the hub:

> Error: Failed to start the transport 'WebSockets': Error: ws does not work in the browser. Browser clients must use the native WebSocket object

I can pinpoint the issue down to the following code:

https://github.com/dotnet/aspnetcore/blob/4b8269fca79f95dc28c0c03546f941e86f663c15/src/SignalR/clients/ts/signalr/src/Utils.ts#L56C1-L58C6

Apparently in Electron's renderer process (frontend), the [`window.process`](https://www.electronjs.org/docs/latest/api/process) object exists just like in node. In this case SignalR thought it was in a node environment and seek to `ws` for web socket transportation, which does not work because it's actually a browser environment.

**Comment by BrennanConroy** [comment] 2024-10-21 17:26
Basically a duplicate of https://github.com/dotnet/aspnetcore/issues/49065
We'll use the other issue for tracking.

**Closed** 2024-10-22 19:22 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-signalr, Status: Resolved
