### ISSUE TITLE
When razor page uses InputDate, the use of the time format is invalid.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#49873] opened 2023-08-04 17:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-razor-page-uses-InputDate-the-use-/10427173)._

<img width="729" alt="image" src="https://github.com/dotnet/aspnetcore/assets/34246760/8f296c02-e555-4b1f-ad84-44913e128232">Repeated tests, using <input type=“datetime-local” > display, not the same format on the browser, should be changed to the only style after being colored.

---
#### Feedback Bot on 7/31/2023, 07:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2023-12-29 18:10
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/38603

**Closed by mkArtakMSFT** 2023-12-29 18:10 UTC
Labels: investigate, area-blazor, feature-blazor-builtin-components, Pillar: Technical Debt
