### ISSUE TITLE
[Blazor] Ability to manually "compile" a component and retrieve generated HTML

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#26692] opened 2020-10-08 09:54 UTC
Hello guys, in my blazor app i have to export some of my views (or part of views) in PDF.

I was wondering if there is something in the engine who allow me to manually call a component with the parameters but not for rendering but just retrieve the html ? after that it will be easy for me to transform it into pdf (with adding necessary stylesheet).

We can imagine this functionnality can be also useful to make engine view for mailing for example.

thanks for your your help and your suggestions !

**Comment by mkArtakMSFT** [comment] 2020-10-08 16:41
Thanks for contacting us. This is a dupe of #23258.

**Closed by mkArtakMSFT** 2020-10-08 16:41 UTC
Labels: area-blazor
