### ISSUE TITLE
``UserManager`` should include a ``BulkCreateAsync`` method

### ISSUE THREAD

**Issue by AmSmart** [dotnet/aspnetcore#34066] opened 2021-07-03 15:24 UTC
### Is your feature request related to a problem? Please describe.
We have to manually implement bulk user insertion for ASP.NET's ``UserManager``. This requires knowing and recreating the implementation details of how users are created like password hashing and others so that the behaviour is consistent with other users created by the UserManager's ``CreateAsync`` method.

While the initial implementation effort is fairly trivial, it could lead to problems in the long run if some implementation details change and this may cause errors like valid users not able to log in or other similar issues.

### Describe the solution you'd like
I think an out of the box method for bulk creation of users would make ``UserManager`` more complete. If perhaps, I am wrong, I would like to know why this is a bad idea and the best way for the developer to go about this.

Thanks.

**Comment by blowdart** [comment] 2021-07-03 19:15
It's out of scope for what we consider asp.net identity apis' use case to be honest, it falls under much the same category as apis for writing management pages, and the idea of setting user passwords to a known value is a bit worrisome. 

While I could backlog this it would languish as it's not what we're aiming for wrt to the product direction, so closing this as "by design" is more honest.

**Closed by blowdart** 2021-07-03 19:15 UTC
Labels: area-identity
