### ISSUE TITLE
Data and Models folders are no longer created for new ASP.NET Core applications

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25642] opened 2020-09-05 03:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1170138/data-folder-is-no-longer-created-on-new-aspnet-cor.html)._

---
<p>[severity:Other]<br>
I’ve just created a new <a href="https://ASP.NET">ASP.NET</a> Core web application with the latest version of Visual Studio (16.7.2).</p><p>However, Visual Studio no longer creates the Data and Models folders like it did the last time I created a web application.</p><p>I know I can create a folder easy enough. But I’m trying to find out why it didn’t set up this structure for me. Has something changed? Is adding the folders enough to support code first? Where do I get templates for the context classes?</p><p>Last time this worked for me was months ago. I do not recall the version I was using at the time.</p>

---
#### Jonathan Wood on 9/1/2020, 09:50 AM: 

<p>I don't know why this changed. But looking at the documentation at <a target='_blank' href="https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio">https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio</a>, it says to manually create the Models folder.</p><p>However, it then says to go ahead and use the `Add-Migration InitialCreate` command, which isn't available in my new project.</p>

#### Feedback Bot on 9/1/2020, 07:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/1/2020, 08:11 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### Ajay Bhargav Baaskaran [MSFT] solved on 9/4/2020, 04:01 PM, 0 votes: 

<p>Thanks for contacting us. We have changed our default template to not include identity. You will need to select the required auth option when creating a new project.</p>

#### Jonathan Wood on 9/4/2020, 05:00 PM: 

<p>Whoever wrote this did not read my post.</p><p>My issue was not that Identity is not included by default. My issue is that when I don't select the Identity option, I don't get other data scaffolding.</p><p>Someone who doesn't need identity might still want a *Data* folder and an `ApplicationDbContext` class, along with installing the components needed for the `Add-Migrations` and `Update-Database` commands.</p><p>Leaving identity unselected should not change whether or not data scaffolding is added.</p>

#### Jonathan Wood solved on 9/1/2020, 09:05 AM, 0 votes: 

<p>-----[DELETE]-----</p>

**Comment by mkArtakMSFT** [comment] 2020-09-05 03:52
Thanks for contacting us.
If I understand the ask correctly, you would like to have the `Data` and `Models` folders being part of the default project template. Can you please confirm this? If not, please be more specific about the ask.

**Comment by SoftCircuits** [comment] 2020-09-05 04:01
@mkArtakMSFT I would like the same scaffolding added that gets added when I check the option to implement identity for individual accounts (except for identity itself). Even if I don't need user accounts, I may still want a database.

This scaffolding includes:

1. Create the Data folder.
2. Create the Models folder (less important).
3. Create the ApplicationDbContext class.
4. Install components so that the Add-Migration and Update-Database commands are available.
5. Any other scaffolding added when I select the identity option (with the exception of identity code).

Thanks.

**Comment by javiercn** [comment] 2020-09-07 15:24
@SoftCircuits thanks for the additional details.

From what we understand, you want a template that contains the setup code for a database that is not tied to identity?

**Comment by SoftCircuits** [comment] 2020-09-07 15:52
@javiercn Correct. Not wanting identity does not necessarily mean I don't want a database.

**Comment by KalleNil** [comment] 2022-05-23 23:27
This is still an issue.

**Comment by kironiitdu** [comment] 2022-10-13 06:12
This issue can be resolved by selecting authentication type as `Individual Account` which will add data folder as before. Please refer to below screenshot. <img height="100" src="https://github.com/kironiitdu/Dotnet6App/blob/master/DataModel.png" alt="csharp">

**Comment by SebastianPascual** [comment] 2023-07-07 22:47
> This issue can be resolved by selecting authentication type as `Individual Account` which will add data folder as before. Please refer to below screenshot ![Data Model](https://github.com/kironiitdu/Dotnet6App/blob/master/DataModel.png?raw=true)

This worked for me as long as I selected .NET 6.0 instead of 7.0.

**Comment by mitchdenny** [comment] 2023-07-10 03:57
I'm not sure if this is actionable at this point. We don't want to assume that if someone is building a Razor Pages and/or MVC application that they will want to be using Entity Framework - plenty of apps don't directly access databases - so we shouldn't opt folks into a dependency that isn't strictly requried for the code in the template to work (note this is not true when you use Invidual Accounts because we do need EF in that case).

I'm going to mark this as by design since the OP doesn't seem to have followed this issue over from vsfeedback anyway.

**Closed** 2023-07-11 04:00 UTC
Labels: enhancement, :heavy_check_mark: Resolution: By Design, area-mvc, triaged, Author: Migration Bot :robot:, Status: Resolved, severity-minor, affected-very-few, feature-templates

**Comment by rrymer2** [comment] 2023-07-25 00:10
This is about the ability to choose between code first vs database first.  The option should not be taken away let the programmer decide on what approach they want instead of forcing them down a path they would rather not go.
