### ISSUE TITLE
Provide the ability to build static sites like Svelte, Hugo, or Gatsby

### ISSUE THREAD

**Issue by wonsil** [dotnet/aspnetcore#53365] opened 2024-01-14 15:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

For the DOTNET 8 Server-Side Rendering (SSR) mode only, enable dotnet publish to create a static site suitable for GitHub Pages, Azure Static Sites, Azure Blob sites, etc.

Blazor WASM can be used for these workloads but with a larger disc/network load and less-friendly SEO.

### Additional context

Blazor is _almost_ the full web UI stack. It is missing the static site, which is popular with SMBs and developers who host these workloads on IIS, Azure Static Websites, and GitHub Pages. It would be useful to teach new web developers Razor syntax and the component model which would prepare them for more advanced rendering models in Blazor. Until then, we are ceding this portion of the market to markdown and JavaScript frameworks which may lure developers away from Blazor technology.

**Comment by gregorygandy** [comment] 2024-01-15 01:33
I was thinking along similar lines the other day. Adding support for Static Site Generation (SSG) would round out the Blazor stack. I would like to see static site generation added as a fifth render mode.

**Comment by javiercn** [comment] 2024-01-15 11:46
Dupe of https://github.com/dotnet/aspnetcore/issues/48810

**Closed** 2024-01-15 11:46 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor
