### ISSUE TITLE
FromQueryAttribute fails to deserialize complex object if object is the same name as a containing property

### ISSUE THREAD

**Issue by HunterAhlquist** [dotnet/aspnetcore#59527] opened 2024-12-17 18:16 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Query parameters of complex object will not deserialize if the parameter name is the same name as one of the enclosing property names.

Let's say we have the following class:
```csharp
public class SearchQuery {
  public string Query { get; set; } = "";
  public int Limit { get; set; } = 10;
  public int Page { get; set; }
}
```
and the following API endpoint utilizing `[FromQuery]`:
```csharp
public Task<IActionResult> Search([FromQuery] query) {
  if (string.IsNullOrWhiteSpace(query.Query))
    return BadRequest();
  return Ok();
}
```

If I send this request: 
`Search?QueryT=Brian&Limit=5&Page=0`
No properties will get deserialized into the parameter object (including the overridden `Limit` part,) and will trigger the bad request response.

### Expected Behavior

The deserialization process will first attempt to map the query's properties to the defined parameter.
An alternative would be to have a warning that the parameter name is the same name of a property in the containing type and may not deserialize as expected.

### Steps To Reproduce

Should be easily reproducible using the example in the first section.

### Exceptions (if any)

N/A

### .NET Version

9.0.101

### Anything else?

I realize the fact that the name of the parameter and the containing property are the same could cause deserialization confusion, but my exception was that it would still attempt to place the properties into it. I do think the best outcome would probably be to create a warning about this, but I'm unsure of the process of that as I've never defined my own custom compiler warnings.

**Comment by captainsafia** [comment] 2024-12-17 21:11
@HunterAhlquist Thanks for filing this issue! I believe this is a duplicate of https://github.com/dotnet/aspnetcore/issues/57637. An attempt to fix this bug has been opened in https://github.com/dotnet/aspnetcore/issues/57637.

**Comment by HunterAhlquist** [comment] 2024-12-17 21:12
Looks like I gotta work on my Google-fu, glad it's being worked on.

**Closed** 2024-12-18 22:41 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-mvc, Status: Resolved
