### ISSUE TITLE
StatusCodePages middleware returns both JSON Problem Details & plaintext content for responses to requests from browsers

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspnetcore#45678] opened 2022-12-19 18:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `StatusCodePagesMiddleware` is returning both JSON Problem Details **and** plain text content (concatenated together) when the request's `Accept` header contains certain combinations of media types. This can be easily seen by making a request from a browser (reproduced using Edge latest on Windows).

### Expected Behavior

The response should only contain either plain text or JSON Problem Details content, depending on the value of the `Accept` header.

### Steps To Reproduce

1. Create a new ASP.NET Core Web API application (minimal)
2. In `Program.cs` add a call to `builder.Services.AddProblemDetails()` to enable the `IProblemDetailsService`
3. In `Program.cs` add a call to `app.UseStatusCodePages()` to add the `StatusCodePagesMiddleware` to the pipeline
4. Run the application
5. Make a request from a browser to "/test" to force a 404 response

Example `Program.cs`:

```csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddProblemDetails();

var app = builder.Build();

app.UseStatusCodePages();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.MapGet("/", () => new { hello = "World" });

app.Run();
```

Result:
<img width="684" alt="image" src="https://user-images.githubusercontent.com/249088/208498737-8826ffc8-a07c-42d9-bd9b-0ead0206258c.png">

`Accet` header content for request from browser:

```
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
```

### .NET Version

7.0.200-preview.22605.5

**Comment by Tratcher** [comment] 2022-12-19 20:52
This check should have prevented that:
https://github.com/dotnet/aspnetcore/blob/2b63a5fc7fee6944af03723767be2335f1d9bf9c/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesOptions.cs#L37

The response must be buffered?

The easy fix is to make that line an `else if`.

**Comment by DamianEdwards** [comment] 2022-12-19 23:31
Ah interesting, I only tried reproducing by launching from VS which would inject the BrowserLink/Refresh middleware so almost certainly buffered.

**Comment by DamianEdwards** [comment] 2022-12-19 23:33
Confirmed it doesn't repro when launching from the cmd line with `dotnet run`

**Comment by captainsafia** [comment] 2023-01-04 00:02
Triage: We think it might be related to the change in behavior in the `BrowserLink` middleware that is documented here (https://github.com/dotnet/aspnetcore/issues/45037).

@MackinnonBuck Do you know if the PR to fix this in .NET 7 has been approved?

We can also do what Chris mentioned here (https://github.com/dotnet/aspnetcore/issues/45678#issuecomment-1358329975).

cc: @brunolins16

**Comment by MackinnonBuck** [comment] 2023-01-04 00:05
@captainsafia The PR has been approved. I just left a comment asking if we're clear to merge it (I'm not sure what the rules are regarding when merging into servicing release branches is allowed).

**Comment by Tratcher** [comment] 2023-01-04 00:22
@MackinnonBuck link?

Wait for the build team to merge servicing PRs.

**Comment by MackinnonBuck** [comment] 2023-01-04 00:23
@Tratcher https://github.com/dotnet/sdk/pull/29152

**Comment by Tratcher** [comment] 2023-01-04 00:25
Oh, I thought you were referring to a fix for this issue. This issue should still be fixed regardless.

**Comment by brunolins16** [comment] 2023-02-10 23:46
> The response must be buffered?
> 
> The easy fix is to make that line an `else`.

@Tratcher  I wasn't able to reproduce (buffered or not) and a quick look seems move to an else might not be possible since this can skip all `Writers` and complete without writing anything.

https://github.com/dotnet/aspnetcore/blob/2cd5873673d6c9858625baf80730507e428a6bad/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesOptions.cs#L29

I am planning to change the check to something like this, that might be good enough:

https://github.com/dotnet/aspnetcore/blob/2cd5873673d6c9858625baf80730507e428a6bad/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesMiddleware.cs#L67-L72

Thoughts?

**Comment by brunolins16** [comment] 2023-02-14 18:31
## Background and Motivation

I have been talking with @Tratcher and we believe that we are trying to work around a wrong decision about the `IProblemDetailsService` design (I can blame myself 😅) where the `WriteAsync` might or might not write the `ProblemDetails`, however, it doesn't report this to the caller. 

Just for context, a ProblemDetails will not be written when all of the registered `IProblemDetailsWriter`, including the `DefaultProblemDetailsWriter`, returns `false` for a call to `CanWrite`. 

As an example, the `DefaultProblemDetailsWriter` will not be able to write when the request contains a `Accept` header without `application/json` or `application/problem+json`.

https://github.com/dotnet/aspnetcore/blob/c42902459618afe114f189e23708fa1a35b6be74/src/Http/Http.Extensions/src/DefaultProblemDetailsWriter.cs#L42-L43
 

## Proposed API

``` diff
namespace Microsoft.AspNetCore.Http;

public interface IProblemDetailsService
{
    ValueTask WriteAsync(ProblemDetailsContext context);

+    async ValueTask<bool> TryWriteAsync(ProblemDetailsContext context)
+   {
+        await WriteAsync(context);
+        return true;
+    }
}
```
## Usage Examples

``` c#
var problemDetailsService = httpContext.RequestServices.GetService<IProblemDetailsService>();
if (problemDetailsService == null ||
    !await problemDetailsService.TryWriteAsync(new() { HttpContext = httpContext }))
{
    // Your fallback behavior, since problem details was not able to be written.
}
```

## Alternative Designs

``` diff
public interface IProblemDetailsService
{
    ValueTask WriteAsync(ProblemDetailsContext context);

+   ValueTask TryWriteAsync(ProblemDetailsContext context, out bool result)
+   {
+        result = true;
+        return WriteAsync(context);
+    }
}
```

## Risks

To be consistent with the Parse/TryParse behavior, as part of this proposal we should change our `DefaultProblemDetailsWriter` to throw in `WriteAsync` when not able to write. If this behavior change is too bad, maybe we could introduce some flag to the `ProblemDetailsOptions` where users can tweak the behavior.

**Comment by Tratcher** [comment] 2023-02-14 19:04
> +   ValueTask TryWriteAsync(ProblemDetailsContext context, out bool result)

Async APIs can't have out parameters.

One other alternative: IProblemDetailsService.CanWrite(ProblemDetailsContext ) that mirrors IProblemDetailsWriter

**Comment by brunolins16** [comment] 2023-02-14 19:43
> Async APIs can't have out parameters.

I proposed it while writing the API suggestion and I completed missed this. Thanks

**Comment by halter73** [comment] 2023-02-16 23:36
API Review Notes:

1. We should `return context.HttpContext.Response.HasStarted;` by default.
2. Do we prefer `CanWrite()` or `TryWrite()`? There's no good default implementation `CanWrite()`. However, we don't think there are many third-party implementations yet, but @DamianEdwards wrote one and filed the bug 😆 

The TryWrite API looks good!

``` diff
namespace Microsoft.AspNetCore.Http;

public interface IProblemDetailsService
{
    ValueTask WriteAsync(ProblemDetailsContext context);

+    async ValueTask<bool> TryWriteAsync(ProblemDetailsContext context)
+   {
+        await WriteAsync(context);
+        return context.HttpContext.Response.HasStarted;
+    }
}
```

**Closed** 2023-02-17 19:05 UTC
Labels: bug, feature-middleware, api-approved, area-web-frameworks

**Comment by dstarosta** [comment] 2023-03-16 05:00
Is there a way to fix this behavior in .NET 7?

**Comment by captainsafia** [comment] 2023-03-17 22:41
> Is there a way to fix this behavior in .NET 7?

We don't typically backport bug fixes that include a new API. @DamianEdwards was there a workaround for this other than running the app from the CLI when you ran into it?

**Comment by DamianEdwards** [comment] 2023-03-17 23:26
The behavior in the browser refresh middleware injected by Visual Studio was fixed in 7.0.2xx back in November 2022 so I'd ensure you're running the latest version of Visual Studio and confirm you have the 7.0.202 SDK installed. If the behavior is still observed it could be due to another middleware in the pipeline doing "bad things".

**Comment by halter73** [comment] 2023-03-17 23:28
We're definitely not backporting new API, but it should be possible to work around this issue

The issue happens when `HttpResponse.Body` is buffered and not flushed before UseStatusCodePages tries to look at it. That's what was happening with the hot reload script injection logic which originally triggered this issue before it was reverted. E.g.:

```csharp
// StatusCodePages would work here because CopyToAsync runs before it checks context.Resposne.HasStarted.
//app.UseStatusCodePages();

// Example buffering middleware. Thanks Bing Chat!
app.Use(async (context, next) =>
{
    var bodyStream = context.Response.Body;

    try
    {
        using (var bufferStream = new MemoryStream())
        {
            context.Response.Body = bufferStream;

            await next();

            bufferStream.Seek(0, SeekOrigin.Begin);
            await bufferStream.CopyToAsync(bodyStream);
        }
    }
    finally
    {
        context.Response.Body = bodyStream;
    }
});

// StatusCodePages breaks here because it exits before CopyToAsync runs.
app.UseStatusCodePages();
```

The fix is to call `app.UseStatusCodePages()` before adding the buffering middleware if you don't need the status code page to be buffered as well.

If you just need to log the status code pages, but not delay the response, you can pass through the writes like our HttpLogging [ResponseBufferingStream](https://github.com/dotnet/aspnetcore/blob/e7603bc5bb8a79183b8d743531eeea7e2d23d209/src/Middleware/HttpLogging/src/ResponseBufferingStream.cs) does rather than waiting for middleware to call `CopyToAsync()`. Or maybe just use that middleware since it's available in .NET 7. https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-7.0

Worst case scenario, you could override `IHttpResponseFeature.HasStarted`, but that would be a lot more involved.

**Comment by dstarosta** [comment] 2023-03-18 04:44
Moving `UseStatusCodePages()` and `UseExceptionHandler()` to the top was the first thing I have tried. But it did not work until I updated Visual Studio (I was on the latest minor but not the patch version) and the SDK. Now everything works correctly.

Thanks. Both answers were very helpful.
