### ISSUE TITLE
[Blazor] Nested Components with inner partial classes (not child components)

### ISSUE THREAD

**Issue by vertonghenb** [dotnet/aspnetcore#20765] opened 2020-04-12 03:13 UTC
### The Idea
In C# we can use inner or nested classes for example:
```cs
partial class ClassWithNestedClass
{
    partial class NestedClass { }
}

partial class ClassWithNestedClass
{
    partial class NestedClass { }
}
```
More information about nested classes can be found [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods).

However it would be nice to see the same approach in Blazor for components, which can make the usage much cleaner and clearer, an example component (mind the `.` between `Menu` and `Item` or `Menu` and `SubMenu`)

```razor
<Menu>
   <Menu.Item Label="Text" Icon="myicon"/>
   <Menu.SubMenu>
      <Menu.Item Label="Text" Icon="myicon"/>
      <Menu.Item Label="Text" Icon="myicon"/>
   </Menu.Submenu>
</Menu>
```

The current workaround is to have the components fully named and there is no way (or at least that I'm aware of) to nest components like this(like nested classes), Which makes the code a bit less clear especially if you have multiple components with the `SubMenu` or `Item` name. 
```razor
<Menu>
   <MenuItem Label="Text" Icon="myicon"/>
   <MenuSubMenu>
      <MenuItem Label="Text" Icon="myicon"/>
      <MenuItem Label="Text" Icon="myicon"/>
   </MenuSubmenu>
</Menu>
```

### Describe the solution you'd like
Make it possible to create inner (nested) components just like we can do with normal nested classes.

**Comment by mkArtakMSFT** [comment] 2020-04-13 16:22
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by StevenTCramer** [comment] 2020-08-09 03:10
This would be a nice feature to support encapsulation.  Would reduce name conflicts and make code overall cleaner.

**Comment by montyclt** [comment] 2020-11-02 15:07
That not only improve clearer markup, that allow too to access a private member of Menu class from Menu.Item class.

When creating a component file named "Menu.Item.razor", the generated class is named Menu_Item. Creating nested classes with this file name will be a good enhacement.

**Comment by mkArtakMSFT** [comment] 2023-12-21 17:05
This is a dupe of https://github.com/dotnet/aspnetcore/issues/12302

**Closed by mkArtakMSFT** 2023-12-21 17:05 UTC
Labels: enhancement, area-blazor, feature-razor.language, severity-minor, affected-medium, Priority:2, feature-blazor-component-model, Pillar: Dev Experience

**Comment by montyclt** [comment] 2023-12-24 19:40
> This is a dupe of #12302

Not really due the other issue is about restricting component to be placed as child of other component in markup and this issue is about define component as inner class of another class.

As I said:
> That not only improve clearer markup, that allow too to access a private member of Menu class from Menu.Item class because a nested class can access to private members of the class that holds it.
