### ISSUE TITLE
Allow customization of Gson in java SignalR client

### ISSUE THREAD

**Issue by xtremeyolo** [dotnet/aspnetcore#24023] opened 2020-07-16 17:20 UTC
Hi. I am currently working on a java app with using SignalR, and i have some custom Gson serialization/deserialization logic using some custom type adapters. The problem is there is no way to specify those in SignalR client.

The possible way to implement that is to allow passing `GsonBuilder` to `JsonHubProtocol` and make a method for that in `HubConnectionBuilder`, e.g `withHubProtocol(HubProtocol protocol)`.

It would look something like this
`GsonBuilder gsonBuilder = new GsonBuilder().registerTypeAdapter(...);`
`HubConnectionBuilder.create(url).withHubProtocol(new JsonHubProtocol(gsonBuilder))`

**Comment by BrennanConroy** [comment] 2020-07-16 17:27
Dupe of https://github.com/dotnet/aspnetcore/issues/17519

**Closed** 2020-07-17 21:02 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
