### ISSUE TITLE
VS stops responding with Blazor projects

### ISSUE THREAD

**Issue by MrYossu** [dotnet/aspnetcore#28765] opened 2020-12-20 15:43 UTC
This is a follow-up to [a previous bug report](https://github.com/dotnet/aspnetcore/issues/28644) that was closed without waiting for me to reply.

As suggested in that thread, I tried the preview features, and it did NOT make any difference. VS still stops responding very regularly. This makes it extremely difficult to develop.

This is a serious bug, and I'm pretty annoyed that the response was "_It might be fixed in the next version, which is almost a year away, and by the way we're closing this so you can't respond_." Please can I have a proper response, **without** this being closed immediately.

**Comment by mkArtakMSFT** [comment] 2020-12-20 22:20
Thanks for following-up, @MrYossu.

I understand that it may be hard sometimes to get a response indicating that a specific fix is not going to happen quite soon.
Here is some background which may help you better understand us and see where we're coming from when posted such a response:
- Before the Razor Experimental Editor work, which has started about a year ago, all support for Razor was and still is handled by the current Razor Editor. That editor, unfortunately, has gone through so many underlying design changes, that it made it quite hard for us to innovate and even catch up with the incoming bugs users have with it.
- Last year, we've finally decided that we should pause for a moment, and, rather than trying to catch up with the incoming bug reports, see whether what we were doing is a good long-term strategy. Very soon it was obvious, that it wasn't and as much as we try, there will still be too many frustrated customers because of Razor.
- That's when we've decided that it would be much beneficial for everyone (and firstly, for our customers) to come up with a new design for the Razor Editor. One, which is flexible enough to power VS on all platforms as well as enable us to continue innovation in that space.
- It's been now exactly a year, that we've stopped investing in current (we now call it `old`) editor. We would only fix issues, which would have widespread impact on high number of customers and prevent them from doing their day -to-day work. This particular issue, while seems high-impact, doesn't fall into that category, as not many others are facing it.
- As for the new editor (which we still call `experimental` because some important features are still missing from that experience), it's been in works for a year now and it is in a state where we already have many customers who happily use it as their default one. Yes, it will require a preview VS installed, so that's something you'll have to opt-in to use it.

I hope you can now understand us better.
As for whether this specific bug will be fixed in the new editor or not, most probably yes. The reason we can't state if for sure, is that the new editor is a complete rewrite and there will be some bugs still which will be much easier to address after we release the new editor.

**Comment by MrYossu** [comment] 2020-12-20 22:56
@mkArtakMSFT Thanks for the response, it's certainly a better way to do it than simply closing the issue without giving me chance to respond!

Can you clarify what implications there are in me installing a preview version of VS? Would this install side-by-side with the release version, or would it install on top of it? I'm nervous about installing preview software on my PC, as I am sure you can understand.

Thanks again.

**Comment by mkArtakMSFT** [comment] 2020-12-21 00:40
No problem, @MrYossu. It's that during triage meetings that we have time is very limited and we usually can't respond in such details to every issue.

You can install VS 2019 Preview side-by-side with your non-preview version of VS. The experience is pretty good from that point of view. I use that setup on both my work and personal laptops and it's great. From VS perspective I can't think about any issues. The only thing to be aware of is that as part of VS preview installation you may get a preview SDK installation too. In case that results in any impact on your project, which you work using your non-preview VS, you can always ping your SDK to an RTM version following the guidance here: https://docs.microsoft.com/en-us/dotnet/core/versions/selection

Hope this helps.

**Comment by MrYossu** [comment] 2020-12-21 15:25
@mkArtakMSFT Thanks for the reply.

I installed VS 2019 preview, enabled the preview Razor editor and tried it out, and it took about 5-10 minutes before it stopped responding.

So, where do we go from here? Seems that the problem isn't fixed. I could be wrong, but the chances of the previous problem being fixed and the new editor having a separate bug that causes the same issue seems a little unlikely.

Thanks again.

**Comment by mkArtakMSFT** [comment] 2020-12-21 16:26
Glad that you did, thanks @MrYossu.

That is something interesting now. I will leave **@NTaylorMullen to follow up with you regarding what's going on with this in the new editor** now. It may very well be something the team will be able to address earlier.

**Comment by mkArtakMSFT** [comment] 2020-12-21 16:27
Ah, also, to set expectations, most of the team is already out for the rest of the year so please expect delays in responses. Things will go back to normal early next year.

Hope you will have memorable holidays too 👍

**Comment by MrYossu** [comment] 2020-12-21 16:32
@mkArtakMSFT Thanks for the reply. Don't worry, I wasn't expecting too much at this time of year 🎈

**Comment by MrYossu** [comment] 2020-12-23 16:24
@mkArtakMSFT Over the last few days I haven't been working on any Blazor components, but have been working on Razor pages within the same project. However, the number of times VS stops responding hasn't changed, making me think that this is nothing to do with the Blazor editor at all.

If so, this bug won't be fixed with the next release.

Any comments? Thanks

**Comment by aryehsilver** [comment] 2020-12-27 17:49
Hey I've also had this issue... Sometimes VS just stops responding. I haven't noticed it to be particularly in the razor editor.

It is EXTEREMLY annoying!

Please help us get our sanity back!

**Comment by NTaylorMullen** [comment] 2020-12-31 18:43
@MrYossu / @aryehsilver  when Visual Studio stops responding would you mind capturing and providing a dump of the process? It'll help us figure out what's going on.

**Comment by MrYossu** [comment] 2020-12-31 20:32
How do I do that? Bear in mind I have no idea when it's going to do it. Can I capture a dump afterwards? If so, how?

**Comment by NTaylorMullen** [comment] 2020-12-31 21:31
Probably the easiest way would be to open Task Manager -> Details -> Find the devenv.exe that's hanging and click "Create Dump":
![image](https://user-images.githubusercontent.com/2008729/103426164-56381800-4b6c-11eb-9891-4196b6cd2ea3.png)

This of course is assuming that it's a "hang" to give you enough time to do it 😄

**Comment by MrYossu** [comment] 2020-12-31 23:09
> This of course is assuming that it's a "hang" to give you enough time to do it 😄

Enough time! Ha, far too much! It hangs for nearly a minute, so plenty of time to grab the dump.

I zipped it up so it's a "mere" 768Mb, and you can [download it from here](https://www.pixata.co.uk/MyBits/devenv.dmp.zip).

Thanks for the help.

**Comment by NTaylorMullen** [comment] 2021-01-04 19:25
@MrYossu Thanks for the dump! I've opened it up and it actually looks like a separate team may be responsible in tearing down the web server. Now the unfortunate side effect to this find is that the other team operates in VS' issue reporting system. Sooooo would you mind going through the VS feedback filing flow? Aka top-right corner of VS -> Report a Problem: 
![image](https://user-images.githubusercontent.com/2008729/103571247-6824fe00-4e7f-11eb-817d-5ba4a9977125.png)

If you link the created issue here I'll help facilitate getting it to the right folks.

**Comment by NTaylorMullen** [comment] 2021-01-04 19:29
For future onlookers. The responsible code hanging:
```
Microsoft.VisualStudio.Web.Application.dll!Microsoft.VisualStudio.Web.Application.VsDeveloperWebServer.StopExistingServer()    Unknown
     Microsoft.VisualStudio.Web.Application.dll!Microsoft.VisualStudio.Web.Application.VsDeveloperWebServer.Start(Microsoft.VisualStudio.Web.Application.WebServerStartOption startOption, string pszEnv)    Unknown
     Microsoft.VisualStudio.Web.Application.dll!Microsoft.VisualStudio.Web.Application.VsDeveloperWebServer.EnsureRunning(uint startOption, string environment)    Unknown
     Microsoft.WebTools.ProjectSystem.dll!Microsoft.WebTools.ProjectSystem.WebServer.IISExpressWebServer.EnsureRunningAsync(Microsoft.WebTools.ProjectSystem.WebServer.ServerStartOption startOption, string currentConfiguration, string curFramework, Microsoft.WebTools.ProjectSystem.WebServer.ServerBitness bitness, Microsoft.VisualStudio.ProjectSystem.Debug.ILaunchProfile resolvedProfile)    Unknown
     [Resuming Async Method]    
     mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)    Unknown
     mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)    Unknown
     mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)    Unknown
     mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()    Unknown
     mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state)    Unknown
     mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)    Unknown
     mscorlib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(System.Threading.Tasks.Task task, bool canInlineContinuationTask)    Unknown
     mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()    Unknown
     mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()    Unknown
     mscorlib.dll!System.Threading.Tasks.Task<bool>.TrySetResult(bool result)    Unknown
     mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.SetResult(bool result)    Unknown
     [Completed] Microsoft.WebTools.ProjectSystem.dll!Microsoft.WebTools.ProjectSystem.WebServer.ANCMHostingSupport.ConfigureANCMHosting(string processExe, string processArgs, bool windowsAuthEnabled, Microsoft.WebTools.ProjectSystem.WebServer.ANCMHostingModel hostingModel, string ancmModuleName, System.Collections.Generic.Dictionary<string, string> envVars)    Unknown
     mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)    Unknown
     mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)    Unknown
     mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)    Unknown
     mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()    Unknown
     mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state)    Unknown
     mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)    Unknown
     mscorlib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(System.Threading.Tasks.Task task, bool canInlineContinuationTask)    Unknown
     mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()    Unknown
     mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()    Unknown
     mscorlib.dll!System.Threading.Tasks.Task<bool>.TrySetResult(bool result)    Unknown
     mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.SetResult(bool result)    Unknown
```

**Comment by MrYossu** [comment] 2021-01-04 20:23
@NTaylorMullen Thanks for the reply.

This all started from the VS feedback. I posted a feedback issue (either [this one](https://developercommunity2.visualstudio.com/t/VS-stops-responding-with-Blazor-projects/1279902) or [this one](https://developercommunity2.visualstudio.com/t/VS-stops-responding-with-Blazor-projects/1278920), not sure which had the files), and that resulted in this github issue being opened.

Are either of those tickets good enough, or do you need a new one? If so, do I do the feedback as soon as it starts responding? For obvious reasons, I can't do it while VS isn't responding.

Thanks again

**Comment by MrYossu** [comment] 2021-01-04 21:37
Just used the VS feedback tool to create [yet another ticket for this issue](https://developercommunity2.visualstudio.com/t/VS-stops-responding-with-Blazor-projects/1300899).

Thanks

**Comment by NTaylorMullen** [comment] 2021-01-11 23:10
Thank you @MrYossu! Closing as duplicate of your other issue now. https://developercommunity2.visualstudio.com/t/VS-stops-responding-with-Blazor-projects/1300899

**Closed by NTaylorMullen** 2021-01-11 23:10 UTC
Labels: area-razor.tooling
