### ISSUE TITLE
ObjectGraphDataAnnotationsValidator

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#33247] opened 2021-06-03 14:01 UTC
Hello,

Is there an update for the Blazor integration of ```ObjectGraphDataAnnotationsValidator``` in .NET 6.0 ?
I am currently using .NET 6.0 Preview 4 and it is not present  😄 (unless I am mistaken)
I know this is planned : [Roadmap ASP.NET Core 6 - Missing issues](https://github.com/dotnet/aspnetcore/issues/28975)
I don't see it in the [ASP.NET Core Roadmap for .NET 6](https://github.com/dotnet/aspnetcore/issues/27883)
Would it be possible to get an ETA please?

**Comment by javiercn** [comment] 2021-06-03 14:48
@boukenka thanks for contacting us.

I believe @pranavkm was working towards getting this on the runtime itself, I'm not sure if that'll happen, though.

**Comment by boukenka** [comment] 2021-06-03 17:01
@javiercn Thank you for the answer. I hope it will be part of the .NET 6.0 release.

**Comment by boukenka** [comment] 2021-07-20 19:06
@mkArtakMSFT Hello. The current package is still in 3.2.-rc1. ASP.NET Core 3.2 RC was released on April 30, 2020. I assume it will not be part of .NET 6. What is the hope that one day this issue will be resolved? Should I open in a few months the same issue?

**Comment by pranavkm** [comment] 2021-07-20 21:28
@boukenka some of the same issues that we're trying to tackle as part of this package also need to be solved for minimal actions. Unfortunately we haven't found the time to figure out ways to productize a solution that works for either and hope to look at it in 7.0. In the meanwhile, the current package should continue to function.

**Comment by boukenka** [comment] 2021-07-21 08:33
@pranavkm Thanks for the reply. I am keeping my fingers crossed that this problem will be solved in version 7.0, even if it will take more than a year to wait.

**Comment by boukenka** [comment] 2021-10-05 07:02
@mkArtakMSFT Hello. Could this issue be added in the [.NET 7 Planning](https://github.com/dotnet/aspnetcore/milestone/174) ? Also, do you plan to ask people what issues/improvements they would like for .NET 7, as was done for .NET 6.0?

**Comment by boukenka** [comment] 2021-11-11 22:26
@mkArtakMSFT Hello. Why is it back to the Backlog milestone?

**Comment by boukenka** [comment] 2021-11-24 07:06
Glad it is back via [Consider shipping ObjectGraphDataAnnotationsValidator / ValidateComplexTypeAttribute](https://github.com/dotnet/aspnetcore/issues/28640).

**Comment by ZacBoyet** [comment] 2022-01-28 19:08
I very much need this functionality and hope that this does not get left in the dust.

**Comment by LukasKubicek** [comment] 2022-03-20 22:05
This should really be given some priority. Validating only top level object in real business applications is pretty much useless.

**Comment by danroth27** [comment] 2022-06-07 19:48
Closing as duplicate of https://github.com/dotnet/aspnetcore/issues/28640

**Closed by danroth27** 2022-06-07 19:48 UTC
Labels: enhancement, area-blazor, feature-blazor-builtin-components, ss-p2
