### ISSUE TITLE
Blazor Server-Side does not always refresh when StateHasChanged within an async method

### ISSUE THREAD

**Issue by panesofglass** [dotnet/aspnetcore#22286] opened 2020-05-27 20:09 UTC
### Describe the bug
I want to update the UI from an async method while calling an expensive database query. If I have the following code:

``` csharp
async Task RunSearchAsync()
{
    Searching = true;
    StateHasChanged();
    SearchResults = await GetSearchResults();
    Searching = false;
    StateHasChanged();
}
```

I only see my UI update after the second `StateHasChanged`. If I don't have a long-running database query but instead an in-memory cache of values from which I'm doing a simple LINQ query, both calls refresh the UI.

### To Reproduce
See above. I unfortunately cannot share the code I'm working with, and as noted above, using an in-memory collection, even with an `await Task.Delay(50000);` fails to reproduce the issue.

### Further technical details
- ASP.NET Core version **3.1**
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version **Visual Studio 2019**

I'm using the `AppState` model, so the calls to `StateHasChanged` are triggered through an event I've hooked up when the application loads. All other calls to refresh the state appear to work just fine and refresh the UI as expected.

**Comment by panesofglass** [comment] 2020-05-28 02:26
I've found a work-around:

``` csharp
async Task RunSearchAsync()
{
    Searching = true;
    StateHasChanged();
    await Task.Delay(1); // <-- why is this needed to refresh the UI?
    SearchResults = await GetSearchResults();
    Searching = false;
    StateHasChanged();
}
```

**Comment by mrpmorris** [comment] 2020-05-28 07:42
Your experiment suggests GetSearchResults has no asynchronous code in and is therefore executing synchronously.

**Comment by panesofglass** [comment] 2020-05-28 18:07
@mrpmorris, it's opening a database connection and calling `ExecuteNonQueryAsync` on several `OdbcCommand` instances, so it's definitely making async calls. My in-memory test store did not have an async call until I added an `await Task.Delay(3000)` to simulate loading data, and it worked both ways.

**Comment by mkArtakMSFT** [comment] 2020-06-01 16:42
We've not been able to reproduce this. please provide a small repro project to help repro this, so we can move forward here.

**Comment by panesofglass** [comment] 2020-06-02 03:07
As I noted previously, I don't know how to reproduce it. This only happened to me after loading a lot of data into a DB2 for iSeries database table that caused the query to take longer to return. I've not been able to re-create a similar incident. It's seems like it is an edge case.

**Comment by mrpmorris** [comment] 2020-06-02 08:37
I downloaded your sample and was able to reproduce your problem. The problem is caused because Blazor will re-render the component as soon as you `await` in code called from `EventCallback` (i.e. your `Add` method).

```
public async Task Add()
{
	await UserManager.CreateAsync(new IdentityUser { UserName = $"test_{Guid.NewGuid().ToString()}" });
}
```

If you add a `System.Diagnostics.WriteLine` to the start of `Add` and to the end of `Add`, and then also add one at the top of your Razor page and one at the bottom, you will see the following output when you click your button.

//First render
Start: BuildRenderTree
End: BuildRenderTree

//Button clicked
Start: Add
(This is where the `await` occurs`)
Start: BuildRenderTree
Exception thrown

You can prevent this mid-method rerender like so....

```
protected override bool ShouldRender() => MayRender;

public async Task Add()
{
	MayRender = false;
	try
	{
		await UserManager.CreateAsync(new IdentityUser { UserName = $"test_{Guid.NewGuid().ToString()}" });
	}
	finally
	{
		MayRender = true;
	}
}
```

This will prevent re-rendering whilst your method is running. Note that if you define `Users` as `IdentityUser[] Users` you will not see this problem because the array is not set until after the `await` has completed, so you don't get this reentrancy problem.

I believe you want to use `IQueryable<T>` because you need to pass it to 3rd party components. The problem is, different components can be rendered on different threads, so if you pass IQueryable to other components then

1: They might render on different threads and cause the same problem.
2: They most likely will have an `await` in the code that consumes the `IQueryable<T>` and you'll have the same problem again.

Ideally, what you need is for the 3rd party component to have an event that asks you for data, giving you some kind of query definition (page number etc).

That way you can do the following

1: Acquire a lock
2: Apply the filter to IQueryable
3: Run the query
4: Release the lock
5: Pass the results to the component

You cannot use `lock()` in async code, so you'd need to use something like `SpinLock` to lock a resource.

```
private SpinLock Lock = new SpinLock();

private async Task<WhatTelerikNeeds> ReadData(SomeFilterFromTelerik filter)
{
  bool gotLock = false;
  while (!gotLock) Lock.Enter(ref gotLock);
  try
  {
    IUserIdentity result = await ApplyFilter(MyDbContext.Users, filter).ToArrayAsync().ConfigureAwait(false);
    return new WhatTelerikNeeds(result);
  }
  finally
  {
    Lock.Exit();
  }
}
```

**Comment by mkArtakMSFT** [comment] 2020-06-02 16:53
Thanks @panesofglass.
If you happen to come up with a repro we will be interested in looking into that. Otherwise, there is not much we can do.

**Closed by mkArtakMSFT** 2020-06-02 16:53 UTC
Labels: Needs: Attention :wave:, area-blazor
