### ISSUE TITLE
Blazor: PreRender WASM: PageTitle/HeadContent not updated on publish

### ISSUE THREAD

**Issue by srpeirce** [dotnet/aspnetcore#35363] opened 2021-08-15 21:31 UTC
### Describe the bug
.Net 6 Preview 7
PageTitle and Head content does not update when navigating between pages after Publish.

> Note: It works as expected when developing (e.g. `dotnet run --project .\Server\`).

This is running WebAssembly PreRendering.

### To Reproduce
Repo to recreate
https://github.com/srpeirce/blazor-pagetitle-bug-net6-7

```
dotnet publish -c Release
Server\bin\Release\net6.0\publish\HeadFail.Server.exe
```

Open 
![image](https://user-images.githubusercontent.com/12847647/129493363-ff111f17-c774-4e28-a8a3-856bfd854355.png)

❌ Click Counter - Doesn't Update Page title
![image](https://user-images.githubusercontent.com/12847647/129493396-4e54d00e-f67e-42b0-9b5a-f80366d8e3e5.png)

Additional:
Refreshing page, the title is updated.
![image](https://user-images.githubusercontent.com/12847647/129493416-15c50a9f-9d8e-4a80-aa02-a3fa42f59c39.png)

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d
  
```

**Comment by pranavkm** [comment] 2021-08-16 00:45
@MackinnonBuck is this a dupe of https://github.com/dotnet/aspnetcore/issues/35343?

**Comment by MackinnonBuck** [comment] 2021-08-16 01:06
@pranavkm this looks different - the fact that it's only breaking after publish suggests to me that something trickier is happening (plus, the updated templates aren't coming until RC1). I think I have an idea why is is happening from looking at the provided repro, but I will investigate it more thoroughly tomorrow.

**Closed** 2021-08-23 23:41 UTC
Labels: Working, area-blazor
