### ISSUE TITLE
Support certificate pinning for java SignalR client

### ISSUE THREAD

**Issue by AsamK** [dotnet/aspnetcore#15404] opened 2019-10-25 14:25 UTC
### Is your feature request related to a problem? Please describe.
For an android application I need to pin the server TLS certificate of the SignalR connection.

The [old SignalR library](https://github.com/SignalR/java-client) had the possibility to provide a custom HttpConnection implementation (via ServerSentEventsTransport). We used that to provide our OkHttpClient instance, that did the certificate pinning.

As far as I could see, the new java library for the .net core SignalR doesn't provide a way to pin the certificate.
There is a `withHttpClient` method in the [Builder](https://github.com/aspnet/AspNetCore/blob/3d3ad96206fc504dba954c0c6403139e3438263e/src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/HttpHubConnectionBuilder.java), that could probably be used to provide an http client with the pinning, but that method and the corresponding `HttpClient` class are package private, so we can't use them.

### Describe the solution you'd like
The most flexible solution would probably be to expose the `withHttpClient` method an `HttpClient` abstract class, so that the library users can provide custom implementations.

If there is some other way to implement certificate pinning or if I overlooked something, I look forward for feedback.

**Comment by jkotalik** [comment] 2019-10-31 18:14
@blowdart thoughts on allowing the client to pin certs? From what I heard, this is very fragile in Auth.

**Comment by blowdart** [comment] 2019-10-31 18:16
We've avoided it, because yes, cert pinning is horrible fragile, and is being deprecated, but we could just expose a custom validator and let people do it if they want, as well as supporting self signed certs that way.

**Comment by anurse** [comment] 2019-11-07 23:22
The work items here:

* [ ] Add a cert validation callback to Java client
* [ ] Investigate adding a callback to NodeJS client?
* [ ] Add a first-class cert validation callback to .NET client

**Comment by anurse** [comment] 2019-11-07 23:26
> The Java client should have an HttpClient extensibility point that would allow you to hook in here.

I actually don't think this is a feasible thing right now. We could look at it later. The problem is that WebSockets uses a completely different API.

**Comment by anurse** [comment] 2020-03-18 16:38
Pre-planning notes: I'm going to propose scoping this to making `HttpClient` and friends public in order to provide some options. I don't know that we have the resources to build out a full config API here, so let's focus on what would unblock people first.

**Comment by BrennanConroy** [comment] 2020-07-20 22:54
Closed via https://github.com/dotnet/aspnetcore/pull/23822

**Closed by BrennanConroy** 2020-07-20 22:54 UTC
Labels: area-signalr, cost: M
