### ISSUE TITLE
StateHasChanged doesn't update input value

### ISSUE THREAD

**Issue by omuleanu** [dotnet/aspnetcore#41274] opened 2022-04-20 06:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've reproduced it here: https://blazorfiddle.com/s/fuienanj

having this code:
```
<input type="text" value="@str1" @onchange="onChange" />
@code {
    private string str1 = "ab";

    private void onChange(ChangeEventArgs args)
    {
        var val = args.Value.ToString();

        if(val.Length > 2)
        {
            val = val.Substring(0, 2);
            str1 = val;
            StateHasChanged();
        }
    }
}
```
if you type after the first 2 letters "ab" (or you don't change the first 2 letters)
 the input value won't reflect the value of @str1 variable even though StateHasChanged was called.

### Expected Behavior

value="@str1" should show value of `str1` after `StateHasChanged()`

seems like an optimization because str1 hasn't changed, maybe a `force` render flag is needed

### .NET Version

6

### Anything else?

VS2022

**Comment by javiercn** [comment] 2022-04-20 09:45
@omuleanu thanks for contacting us.

This is expected, that's why you need to use `@bind` in these scenarios, as it does some magic behind the scenes to reconciliate the state between the input and the C# side.

We do have plans to improve this in .NET 7.0 to make this scenario easier. See https://github.com/dotnet/aspnetcore/issues/39837

Other than that, the behavior here is by design, since we can't update the input value because that would create problems with events fired during oninput (you'll be typing and your changes will be destroyed)

Going to close this issue as dupe.

**Closed by javiercn** 2022-04-20 09:45 UTC
Labels: area-blazor

**Comment by omuleanu** [comment] 2022-04-20 09:59
> we can't update the input value because that would create problems

@javiercn you are updating the input value, if the `str1` var would get a different value, the input value would update.

**Comment by javiercn** [comment] 2022-04-20 11:20
@omuleanu there are two values. The value in the `C#` field and the one in the actual input within JavaScript. The one that is not being updated is the one in the actual input element in JS. That's the magic that bind does that I was talking about.

**Comment by omuleanu** [comment] 2022-04-20 11:39
@javiercn I get that, however,
in the demo above if I type `1234` the server and client value of the input will be `12`, 
after if you type `abcd` the server and client value will be `ab`,  
and only after if you type `abwhatever` the client value stays `abwhatever` because the server value didn't change

**Comment by javiercn** [comment] 2022-04-20 11:44
@omuleanu and that again goes to my comment about `@bind`. 

That's the special magic that makes this work. The behavior you are observing is by design and that's why there is special logic in `@bind` to reconciliate the values and have the value on the input field updated to `ab` when you use bind.

**Comment by omuleanu** [comment] 2022-04-20 12:02
@javiercn is there some flag that can be set to achieve the same result as `@bind` , but without using `@bind`

**Comment by javiercn** [comment] 2022-04-20 12:13
@omuleanu no.

That's why we are implementing something in .NET 7.0 so that you can do the same thing you do with `attribute + handler` but with `@bind` semantics.

The only way to achieve the same today is using C# and the rendertreebuilder apis.
