### ISSUE TITLE
Microsoft.AspNetCore.Components.QuickGrid fails with "BLAZOR106: The JS module file wwwroot/_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js' was defined but no associated razor component or view was found for it."

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/aspnetcore#54644] opened 2024-03-20 13:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Adding the quick grid to a Net8.0 project breaks the build / publish process from the console with the following error:

```log
/builds/MyServer/publish/wwwroot/_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js :
error BLAZOR106: The JS module file '/builds/MyServer/publish/wwwroot/_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js'
was defined but no associated razor component or view was found for it. [/builds/MyServer/MyServer.csproj]
```

Publish: `dotnet publish --configuration Release -r win-x64 --no-self-contained --no-restore --output publish.win-x64/`

### Expected Behavior

Build works without errors.

### Steps To Reproduce

Create a dummy Net8 project and add the `Microsoft.AspNetCore.Components.QuickGrid` package from NuGet, add it to a dummy page.

### Exceptions (if any)

```log
/builds/MyServer/publish/wwwroot/_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js :
error BLAZOR106: The JS module file '/builds/MyServer/publish/wwwroot/_content/Microsoft.AspNetCore.Components.QuickGrid/QuickGrid.razor.js'
was defined but no associated razor component or view was found for it. [/builds/MyServer/MyServer.csproj]
```

### .NET Version

8.0.202

### Anything else?

* ASP.NET Core version: 8.0.3
* No IDE, Gitlab CI build with latest Docker image as base (`mcr.microsoft.com/dotnet/sdk:8.0`)
* Dotnet --info:

```log
$ dotnet --info
.NET SDK:
 Version:           8.0.202
 Commit:            25674bb2f4
 Workload version:  8.0.200-manifests.4e94be9c
Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.202/
.NET workloads installed:
There are no installed workloads to display.
Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66
.NET SDKs installed:
  8.0.202 [/usr/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Other architectures found:
  None
Environment variables:
  Not set
global.json file:
  Not found
Learn more:
  https://aka.ms/dotnet/info
Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by SeppPenner** [comment] 2024-03-22 09:34
Minimal repro project is under https://github.com/SeppPenner/QuickGridTest. I added the build image we use in our Gitlab CI pipeline as well under https://github.com/SeppPenner/QuickGridTest/tree/master/src/docker-buildimage (And pushed it fresh to dockerhub with my username as well).

The thing is that this now works with the minimal repro... Do you have any ideas where this issue might come from?

**Comment by mkArtakMSFT** [comment] 2024-03-25 17:02
> The thing is that this now works with the minimal repro... 

Thanks for contacting us. It's not clear if the issue still relevant then. Are you still facing this issue, or not?

**Comment by SeppPenner** [comment] 2024-03-26 07:37
> > The thing is that this now works with the minimal repro...
> 
> Thanks for contacting us. It's not clear if the issue still relevant then. Are you still facing this issue, or not?

I'm still facing the issue within our build pipeline, but I sadly couldn't reproduce it within the minimal working example...

**Comment by mkArtakMSFT** [comment] 2024-03-26 16:38
Unfortunately, we won't be able to investigate this without a repro. I'm going to close this issue and hopefully you will be able to reproduce the issue and give us a repro later. Ideally, of course, you will find the culprit in your pipeline / code and fix it yourself.
Once you have a repro, please file a new issue.

**Closed by mkArtakMSFT** 2024-03-26 16:38 UTC
Labels: area-blazor, Needs: Attention :wave:, feature-blazor-quickgrid

**Comment by SeppPenner** [comment] 2024-03-27 10:31
> Unfortunately, we won't be able to investigate this without a repro. I'm going to close this issue and hopefully you will be able to reproduce the issue and give us a repro later. Ideally, of course, you will find the culprit in your pipeline / code and fix it yourself. Once you have a repro, please file a new issue.

Do you by any chance have some ideas where I should look at? E.g. some logs or whatever?

**Comment by mdmontesinos** [comment] 2024-04-04 10:23
I'm also getting the same error when trying to extract the staticwebassets from the NuGet package and manually adding them to my project (as is required because I'm using [Oqtane](https://github.com/oqtane/oqtane.framework)).

**Comment by AndreiShenets** [comment] 2024-06-06 11:02
The issue still happens for me as well. After some successful builds it starts to fail.

As a work around it helps to delete `bin` and `obj` folders, then restore nuget packages and build again.

**Comment by gt-dbechtold** [comment] 2025-06-03 19:02
I ran into this issue since I had a `NuGet.Config` file which restored to a local `.\packages` subdirectory in the same directory as the .csproj.  This was easy to reproduce using one of the samples from https://github.com/dotnet/blazor-samples.  I moved the `packages` directory up a level, above the project directory and then everything worked.  It appears that the build is scanning for `.js` files in the project subdirectories and probably excludes known subdirectories like `bin`, `obj`, and `wwwroot`, but that's just my speculation.  I could see why this might make a pipeline fail if the pipeline was designed to restore packages to a local directory and not to the user's home directory.

**Comment by manusoft** [comment] 2025-06-21 21:42
### ✅ **Solution (Visual Studio 2022)**

To fix this, clear the NuGet package caches to ensure all required resources are refreshed correctly:

1. Open **Visual Studio 2022**
2. Go to **`Tools` → `NuGet Package Manager` → `Package Manager Settings`**
3. In the **Settings** window, navigate to:
   **`NuGet Package Manager` → `General`**
4. Click **`Clear All NuGet Cache(s)`**

This will:

* Remove cached `.nupkg` files
* Ensure Blazor static assets like `QuickGrid.razor.js` are properly restored and served
