### ISSUE TITLE
PublishSingleFile excluding appsettings not working as expected

### ISSUE THREAD

**Issue by tarekgh** [dotnet/aspnetcore#12621] opened 2019-07-26 18:09 UTC
_From @matthew-mcginty on Friday, July 26, 2019 8:15:23 AM_

I'm trying to publish an app so that the publish output creates 2 files only:
App.exe
appsettings.config

App.exe should read/use the config

I have attempted this by placing this in my .proj file:
```
<ItemGroup>        
    <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>            
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
</ItemGroup>
```
and publishing with the following:
`dotnet publish -c Release --self-contained -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true`

The expected 2 files are created (exe/config) but the exe does not read the config file, rendering the exe non-functional

Is this possible to achieve?

```
dotnet --version
3.0.100-preview7-012821
```

_Copied from original issue: dotnet/corefx#39801_

**Comment by tarekgh** [comment] 2019-07-26 18:09
_From @ViktorHofer on Friday, July 26, 2019 8:34:53 AM_

You can use the `runtimeconfig.json` file to set runtime switches / settings. Would that work for your use-case?

**Comment by tarekgh** [comment] 2019-07-26 18:09
_From @matthew-mcginty on Friday, July 26, 2019 10:48:00 AM_

If it can work then I wouldn't know how. Currently the app uses ConfigurationBuilder/ServiceProvider approach in my `Startup.cs` to load appsettings.json via `GetSection()`. I would not know how to read the `runtimeconfig.json` in a similar way if it's indeed possible. I don't see anything [here](https://github.com/dotnet/cli/blob/v2.0.0/Documentation/specs/runtime-configuration-file.md) which suggests how to to do this.
My `appsettings.json` mainly contains system paths that would vary form user to user

**Comment by tarekgh** [comment] 2019-07-26 18:09
_From @ViktorHofer on Friday, July 26, 2019 11:01:36 AM_

this sounds like aspnetcore specific logic. You might want to move that issue over to https://github.com/aspnet/aspnetcore

**Comment by dasMulli** [comment] 2019-08-07 15:37
I'm working around this with Program.cs customizations using `Process.GetCurrentProcess().MainModule.FileName` as suggested in https://github.com/dotnet/core-setup/issues/7491#issuecomment-517835272 - checking if the file is in a different location than `AppContext.BaseDirectory` and the executable name (without extension) is not `dotnet`.

The weird thing about it is that the design document for single file publishing states that `AppContext.BaseDirectory` should point to the host location but actually points to the bundle location - opened https://github.com/dotnet/core-setup/issues/7491 for that, but it has an effect on what to do now vs. how to "future proof" such logic.

**Comment by Pilchie** [comment] 2020-01-28 00:53
Sorry this fell through the cracks.  Is this still an issue?

**Comment by dasMulli** [comment] 2020-01-28 08:52
Similar issues are waiting for this to be solved via https://github.com/dotnet/core-setup/issues/7491

**Comment by Pilchie** [comment] 2020-01-28 17:40
Closing this as a dupe of dotnet/core-setup#7491.

**Closed by Pilchie** 2020-01-28 17:40 UTC
Labels: Needs: Author Feedback, area-platform
