### ISSUE TITLE
Update .net 5 to 6: 'The path must be absolute'

### ISSUE THREAD

**Issue by clintsinger** [dotnet/aspnetcore#38226] opened 2021-11-09 19:27 UTC
I am updating my project from .net 5 to .net 6 and have run into an issue.  The project is running VS 2022 using docker-compose and container tools on linux containers.   
![image](https://user-images.githubusercontent.com/1449736/140990662-574719f0-6ab6-4243-b2a7-a3912155c685.png)

The problem comes from the `.ConfigureAppConfiguration()` where I am trying to pass in configuration to be shared across containers.
![image](https://user-images.githubusercontent.com/1449736/140990828-61fddfa1-067e-49e8-8c03-7145be5cee1c.png)
![image](https://user-images.githubusercontent.com/1449736/140990867-2e96abd2-9e21-40bb-a4c2-9c8f7eb0bc84.png)

If I comment out the `.ConfigureAppConfiguration()` the error goes away (other than I don't have my configuration anymore).

This worked fine previously and the only change is the upgrade to .net 6 (and corresponding nuget files) so it certainly appears to be some kind of regression.  I see that a number of other issues were raised for a similar problem but appears to be different from this.

I have confirmed that "User Docker Compose V2" was not enabled.

**Comment by javiercn** [comment] 2021-11-09 19:30
@clintsinger thanks for contacting us.

This is a known issue within the docker tooling in Visual Studio that we are working to address. The original report is [here](https://github.com/dotnet/aspnetcore/issues/37876)

**Comment by NCarlsonMSFT** [comment] 2021-11-09 19:43
@clintsinger I see you added the .json file to your compose project, but did you add volume mounts to a docker-compose file or COPY commands to your Dockerfile to copy the file into your container?
FYI You can use the [Containers window](https://docs.microsoft.com/en-us/visualstudio/containers/view-and-diagnose-containers?view=vs-2022) in VS to explore the filesystem of your running container and confirm whether the file is present.

**Comment by clintsinger** [comment] 2021-11-09 20:23
@javiercn , I saw issue https://github.com/dotnet/aspnetcore/issues/37876 originally but what I am seeing feels like it is different.  As I mentioned already I don't have "Use Docker Compose V2" enabled.  

@NCarlsonMSFT, it appears that all of the volume mounts are correct.   As also mentioned, the only change was moving to .net 6 so none of the configuration or other volume mounts changed.

**Comment by NCarlsonMSFT** [comment] 2021-11-09 20:33
@clintsinger I agree this seems like a different issue; but I don't have enough info to create a repro. Can you provide a minimized repro repo, or more details about how the file gets into the container?

**Comment by NCarlsonMSFT** [comment] 2021-11-09 20:40
@clintsinger another obvious question I should have asked. Can you copy the full exception details? I would be particularly interested in the call-stack.

**Comment by clintsinger** [comment] 2021-11-09 21:52
```
System.ArgumentException
  HResult=0x80070057
  Message=The path must be absolute.
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Frontend.Auth.Program.Main(String[] args) in C:\Projects\DSG\Software\Thompson\Garrison\src\Frontend\Frontend.Auth\Program.cs:line 23
```

The file does appear in the container under `/src` when I check the files browser in container tools. 
![image](https://user-images.githubusercontent.com/1449736/141010425-5c1ffd03-fbf1-48e6-bb6a-57396d1e9c46.png)

I also tried giving it a "full path" buy changing the path to `/src/config/appsettings...` but I get the same error.

**Comment by NCarlsonMSFT** [comment] 2021-11-09 22:31
The stack trace is for static assets! If you look in your project output, is there a static assets file? If so, can you try:
1) Deleting all static assets files
2) Double checking that Compose V2 is still disabled (It sometimes gets enabled on update)
3) Rebuild and try debugging again?

**Comment by javiercn** [comment] 2021-11-09 22:37
@NCarlsonMSFT I think this can then likely be the same issue we've talked about. Thanks for taking a look.

**Comment by clintsinger** [comment] 2021-11-09 22:59
Yes, it does appear to not be related to the `appsettings...` as I tried commenting out the code again and still ran into the issue.   Something else must have happened before.   I have more than one project so that could have been it and sent me down the wrong rabbit hole.

That being said, I don't have and have never had Compose V2 enabled, so I shouldn't be encountering anything related to that.  I have done multiple clean and rebuilds as well.  I also deleted the bin folders directly because I noticed that the `*.statiwebassets.runtime.DT.json` isn't deleted after a `Clean`.

Still after all that I still run into the issue.   https://github.com/dotnet/aspnetcore/issues/37876 is closed but probably shouldn't be.

**Comment by clintsinger** [comment] 2021-11-09 23:21
I have now done the following:

1) Deleted all bin folders
2) Rebooted the computer
3) Factory reset Docker
4) Confirmed "Use Docker Compose V2" is still disabled.
5) Rebuilt and ran the solution.

And I am still running into the same issue.

**Comment by clintsinger** [comment] 2021-11-10 00:00
@NCarlsonMSFT , I guess my question is:   Is https://github.com/dotnet/aspnetcore/issues/37876 being treated as the solution to this or am I waiting for some other fix to come out?   If it is the later then I'll switch back to .net 5 until there is a fix because the former didn't resolve my issue.

**Comment by NCarlsonMSFT** [comment] 2021-11-10 01:38
@clintsinger There is a new version of Docker-Compose release today with fixes that may help.

As of now, outside of #37876, I can't reproduce this issue. I did try creating a .NET 5 web app and updating it to .NET 6, but that worked with the basic project from the template.

The only other thing that comes to mind would be to look at the contents of the static assets file and see which paths weren't updated to container paths, and whether there are volume mounts for those paths. Also if they are volume mounts you've customized that would be good to know for crafting a repro.

**Comment by clintsinger** [comment] 2021-11-10 16:49
Is the docker-compose update coming from Docker directly?  (Just wondering where I should look for it)

I compared the volume mounts of my project in .net 5 and .net 6 (I have different branches so it is easy to swap them) and the volume mounts are identical between the two.   I did notice that `*.staticwebassets.*` are new to .net 6 as I didn't see them in my .net 5 debug bin folder.

It's not obvious for me which paths aren't being mounted because I am not too sure what I am looking for.

I'd be happy to schedule a teams meeting if you wanted to do some digging around.

**Comment by NCarlsonMSFT** [comment] 2021-11-10 19:05
@clintsinger the docker-compose update is from Docker: Docker Desktop version 4.2.

What should be interesting is the contents of <projectname>.staticwebassets.runtime.DT.json. The top node is ContentRoots which is a list of absolute paths. The bug you are seeing is usually caused by failing to find a path in the container for one of the windows paths, so you will see a windows path in this version of the file (which should all be linux paths).

If you want to try and schedule a call you can reach out to me via e-mail, just replace the 'MSFT' in my username with '@microsoft.com'

**Comment by clintsinger** [comment] 2021-11-10 23:26
@NCarlsonMSFT, I was hoping that the update to 4.2 would be the magic fix, but alas, it was not.

I'll reach out to you directly.

**Comment by Pilchie** [comment] 2021-11-12 21:24
Closing as external.

**Closed by Pilchie** 2021-11-12 21:24 UTC
Labels: External, docker

**Comment by cdavernas** [comment] 2021-11-26 13:07
@Pilchie I'm facing the exact same issue. As this one has been closed for `Closing as external`, is there a fix or a link to the appropriate issue?

I crawled google for hours for a solution, with no luck. All suggested fixes fail to work. I tried with both Docker-Compose V1 and V2, deleted all bin/vs/obj directories, rebuilt images, reset docker, manually setting contentroot, etc. to no avail. I've no fancy static file assets, the only external package dependency I have is to Swashbuckle's SwaggerUI.

```c#
Exception thrown: 'System.ArgumentException' in Microsoft.Extensions.FileProviders.Physical.dll
An unhandled exception of type 'System.ArgumentException' occurred in Microsoft.Extensions.FileProviders.Physical.dll: 'The path must be absolute.'
Stack trace:
 >   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
 >   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
 >   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
 >   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
 >   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
 >   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
 >   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
 >   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
 >   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
 >   at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

**Comment by javiercn** [comment] 2021-11-26 13:32
@clintsinger the fix will ve available in a future VS 2022 update.

**Comment by cdavernas** [comment] 2021-11-26 13:34
@javiercn Allright, thanks for your prompt answer! Any workaround you know of, in the meanwhile?

**Comment by jkasperbl** [comment] 2021-12-06 22:37
Agreed, is there any workaround for this or information about when a fix will be available? I am experiencing the exact same issue after upgrading from .NET 5 to 6.

**Comment by clintsinger** [comment] 2021-12-06 23:09
On my machine I have to manually modify the `bin\Debug\net6.0\*.staticwebassets.runtime.DT.json` file.   

There is a `ContentRoots` that has my Windows absolute path but it should be the containers relative path.   So in my case I change `ContentRoots` to look like the following (your relative path may be something else):

```
"ContentRoots": [
    "/app/wwwroot/"
],
```

As long as I don't rebuild it stays like that.

**Comment by cdavernas** [comment] 2021-12-07 07:35
@clintsinger Many thanks, I'll try that straight away!!!

**Comment by NCarlsonMSFT** [comment] 2021-12-07 17:21
@jkasperbl unfortunately I think @javiercn is mistaken. The fix for the main scenario has been shipped. But some users such as @clintsinger are still seeing an issue. We have been unable to reproduce the issue, but if you are open to a call, I would love to be able to do some remote debugging with you to see if we can find out why you are still seeing this. You can reach out to me directly for scheduling a call by swapping the MSFT from my username with @microsoft.com

**Comment by psiservices-dbrink** [comment] 2021-12-10 16:29
@NCarlsonMSFT , I shot you an email in case you still need remote debug assistance.  We've hit this with an angular webapp hosted in asp.net core.

I can't say whether this situation is true for anyone else, but I think our variety of this issue results from having a custom build configuration.  When using a separate build config {Project}.staticwebassets.runtime.DT.json isn't produced in the /bin/{Config} which results in a Windows path for content root.  These paths aren't "riooted" on linux and thus the exception.

Our angular webapp supports localization.  Within angular that means producing multiple builds for each locale (/en, /es, etc).  Due to how containerfastmode works on VS we added a separate DockerDebug build config and tweaked our startup to support some semblance of debugging multiple locales while running node within the container.  

I've pushed a simple reproduction to https://github.com/psiservices-dbrink/RootExRepro2/tree/master/RootExRepro2.  

- asp.net "weather" app (no angular needed for repro) created in VS 2019 on .NET 5
- Added Docker and Docker Compose orchestration support
- I've added a "DockerDebug" build config to the solution and webapp.  
- *This works on .NET 5
- Made a quick migration to .NET 6 by changing &lt;TargetFramework&gt; to net6.0 and updating DockerFile to aspnet:6.0 and sdk:6.0
- Debugged via DockerDebug on VS 2022 and exception occurs

**Comment by cdavernas** [comment] 2021-12-10 20:37
@NCarlsonMSFT quickly spotted that my faulty project's docker-compose file was off and, after some investigation, a misconfiguration was in my case the source of the issue. 

My original docker-compose file:

```
...

myproject:
   build:
     context: .
     dockerfile: ../../src/MyProject/Dockerfile
     
...
```

The fixed docker-compose file:

```
...

myproject:
   build:
     context: ../../
     dockerfile: ./src/MyProject/Dockerfile
     
...
```

You see, I do not like having my docker-compose project at the root of my solution, so I move it to '/deployment/docker-compose/', that's why you see the '../../'. However, this was the wrong place to set it, and trying to build in release mode in visual studio failed because the path to the DockerFile could not be resolved.

Voila!

Thanks again for your time and your precious help @NCarlsonMSFT !

## Additional notes:

Strangely enough, the same misconfiguration was present in another project, and was running just fine. In addition, the faulty project had been successfully published/deployed in my Github CI/CD pipeline a good dozen of times over the months and was perfectly, too.

**Comment by psiservices-dbrink** [comment] 2021-12-14 17:11
@NCarlsonMSFT any updates?

**Comment by NCarlsonMSFT** [comment] 2021-12-14 17:20
@psiservices-dbrink you've found an additional bug on top of the [known issue](https://github.com/microsoft/DockerTools/issues/320) 😔
I have a fix queued up targeting the next release. in the mean-time you can use the general work-around documented [here](https://github.com/microsoft/DockerTools/issues/320) and then for the second bug you can add the section:
```
  <PropertyGroup Condition=" '$(Configuration)' == 'DockerDebug' ">
    <DockerDevelopmentMode>Fast</DockerDevelopmentMode>
  </PropertyGroup>
```
To your service projects

**Comment by psiservices-dbrink** [comment] 2021-12-14 17:27
@NCarlsonMSFT, thanks for the update.

Does &lt;DockerDevelopmentMode&gt; work in csproj files?  I've only observed an effect in dcproj files.  Unfortunately adding it to the dcproj affects all defined services and not just the single angular app where I need a full dockerfile build.

**Comment by NCarlsonMSFT** [comment] 2021-12-14 22:48
@psiservices-dbrink there is currently no support for setting DockerDevelopmentMode on a per-service basis. The closest option available would be to move the dockerfile to be in a different folder than the project (be sure to update the reference in the compose file). This will cause the tooling to leave managing the service to compose. The service will no longer launch under the debugger, but if/when desired you can [attach](https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-process-running-in-docker-container?view=vs-2022#attach-to-a-process-running-on-a-linux-docker-container)

**Comment by Sen-Gupta** [comment] 2021-12-17 08:46
It is still broken with latest docker 4.3.1. Unable to debug the projects!

**Comment by NCarlsonMSFT** [comment] 2021-12-17 21:02
@Sen-Gupta: please use https://github.com/microsoft/DockerTools/issues/320 to watch for updates and discuss this issue. If the workarounds are not unblocking you, please let us know in the https://github.com/microsoft/DockerTools repo.
