### ISSUE TITLE
Blazor JavaScript tag

### ISSUE THREAD

**Issue by vd3d** [dotnet/aspnetcore#24231] opened 2020-07-23 08:16 UTC
Currently, blazor support the <style> tag, it is really helpful, this way we can add CSS style only in their respective components.
Otherwise, it is a pain to manage and clean very large CSS files.

So, I think we also need a <JavaScript> tag that we can use into each component, with specific component JavaScript.
Currently, I have my own library loading some JavaScript on the fly, but it is done from the code.
My library do the following:
- Evaluate("....")
- LoadFromURL("HTTP://....")
- LoadFromScript("var t = ....")

Why JavaScript, because today, there exist so much JS libraries ... they are useful too, having a 100% C# platform is not realist today.

And it works perfectly since months (I can share my code) :-)

### Describe the solution you'd like

So, my proposition is

1) to have a <Script> tag with theses features, but also:
- is able to optimize and minify this JavaScript code
- Version 2, can even support TypeScript etc...

(I have try to create it myself, but the Fragments seems to only support HTML like for now)

2) improve the <style> tag to minify the css (and version 2) can even support SCSS etc...
(I know that it is an existing feature request already)

**Comment by mkArtakMSFT** [comment] 2020-07-23 16:45
Thanks for contacting us.
This is a dupe of #23560

**Closed by mkArtakMSFT** 2020-07-23 16:45 UTC
Labels: area-blazor
