### ISSUE TITLE
Blazor WASM 3.2.0-preview3 Auto-rebuild not working

### ISSUE THREAD

**Issue by dominiclapointe** [dotnet/aspnetcore#20220] opened 2020-03-27 01:51 UTC
### Describe the bug
When running a new Balzor WASM core hosted the auto-rebuild function doesnt work.
Basically when changing the content of the H1 in for ex: Counter.razor then saving, absolutely nothing happen. Refreshing the browser doesn't bring the changes. I have to stop VS and restart it to see the change, like in previous version

### To Reproduce
- Create a new Blazor WebAssembly App project from VSTS choosing 'ASP.NET Core Hosted' and 'Configure HTTPS'
- Press F5
- Once your browser is showing the app, do a change in any .razor file, in the HTML
- Nothing happen...

### Further technical details
VS 2019 pro PREVIEW 16.6.0 Preview 2.0

Windows 10 Pro build  18362

MS Edge Version 80.0.361.69 (Official build) (64-bit)

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\
Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8
.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mihaimyh** [comment] 2020-03-27 11:57
I've also noticed this issue.

**Comment by vulcanlee** [comment] 2020-03-28 04:15
I have same problem.

**Comment by csillagd** [comment] 2020-03-31 05:10
As Daniel said in the blog, you need run your code with ctrl-F5, not just F5.

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/#comment-1748

**Comment by vulcanlee** [comment] 2020-03-31 06:10
@csillagd 

I have followed Daniel suggestion, but the Auto Rebuild is also not work.

**Comment by mkArtakMSFT** [comment] 2020-03-31 16:49
@BillHiebert can you please look into this?

**Comment by danroth27** [comment] 2020-03-31 16:54
Hi @vulcanlee. What auto-rebuild enables is not having to rebuild and restart the app, but you still need to refresh the browser. Are you refreshing the browser after making the code change? The browser won't refresh automatically - you still need to refresh it manually.

**Comment by vulcanlee** [comment] 2020-03-31 16:58
@danroth27 

Yes, when I make the code change and refresh manually, but it not work

**Comment by IvanJosipovic** [comment] 2020-03-31 18:46
I am also having trouble getting this to work. 

VS Ent Version 16.6.0 Preview 2.0
Windows 10 Build 2004

1. New Blazor Wasm Project
2. IIS Express
3. Ctrl + F5
4. Make changes to Index.razor, Save
5. Wait a few seconds
6. Refresh browser, no changes

**Comment by danroth27** [comment] 2020-03-31 18:57
@ivanbasov Did you create a standalone or ASP.NET Core hosted project?

**Comment by IvanJosipovic** [comment] 2020-03-31 19:04
> @ivanbasov Did you create a standalone or ASP.NET Core hosted project?

Standalone

**Comment by danroth27** [comment] 2020-03-31 19:07
@ivanbasov Got it, thx! I've confirmed that auto-rebuild isn't working with standalone projects, but it should work with ASP.NET Core hosted projects. Can you try that out and see if it works for you?

**Comment by IvanJosipovic** [comment] 2020-03-31 19:32
I can confirm that it works in ASP.NET Core hosted project.

Is this expected to work in Standalone projects by RTM?

**Comment by danroth27** [comment] 2020-03-31 22:58
After digging into this a bit, the reason auto-rebuild doesn't work for standalone projects is because Blazor explicitly turns it off by setting `<NoRestartServerOnBuild>True</ NoRestartServerOnBuild>`. And there's a good reason for this: it doesn't make sense to restart the server for a standalone project because all it's doing is hosting static files. You should be able to rebuild the project and refresh the browser without the overhead of restarting the server. Unfortunately, this also disables the auto-rebuild part of the system as files change, but we'll look at addressing that in the .NET 5 time frame. 

So, for now, the dev workflow in a Blazor WebAssembly  standalone app is edit, *build*, refresh (instead of edit, save, refresh).

**Comment by mihaimyh** [comment] 2020-04-01 05:58
> @ivanbasov Got it, thx! I've confirmed that auto-rebuild isn't working with standalone projects, but it should work with ASP.NET Core hosted projects. Can you try that out and see if it works for you?

Including PWAs?

**Comment by danroth27** [comment] 2020-04-22 18:21
There's a limitation in the auto-rebuild support in VS that couples auto-rebuild to restarting the web server. For a standalone Blazor WebAssembly app, restarting the web server is unnecessary and actually slows down the development experience. Instead, we want to just rebuild the files as they are changed. Enabling auto-rebuild support without restarting the server in VS isn't going to land in time for the Blazor WebAssembly 3.2 release, so I'm moving this out to .NET 5. In the meantime, an optimal dev workflow for standalone Blazor WebAssembly apps is to 1. Start the app without debugging, 2. Make your edits, 3. Build, 4. Refresh the browser to see your changes.

**Comment by danroth27** [comment] 2020-04-22 18:23
Putting in the same milestone as #5456

**Comment by mkArtakMSFT** [comment] 2020-04-28 20:46
Duping this with the above referenced issue: #5456

**Closed by mkArtakMSFT** 2020-04-28 20:46 UTC
Labels: External, area-blazor, blazor-wasm, investigate
