### ISSUE TITLE
Changing Environment Variables causes error in Blazor WASM .NET Core hosted .NET 6.0

### ISSUE THREAD

**Issue by Programmer04515** [dotnet/aspnetcore#43843] opened 2022-09-08 17:54 UTC
Cannot change the Launch Profiles ASPNETCORE_ENVIRONMENT variable to anything except Development.  Anything except Development causes your initial web view to open about:blank.  

You can reproduce the issue by first creating a 

- new Blazor WASM .Net 6.0
- With options: No https, .NET Core Hosted

Then in the new app right click Properties of the projects.Server (Solution Explorer) >> Debug >> General >> Open debug launch profiles UI >> Change the ASPNETCORE_ENVIRONMENT variable from Development to Staging.

Start debugging using Visual Studios 2022 and it will fail to setup correctly, followed by closing itself after a couple of minutes.

**Comment by TanayParikh** [comment] 2022-09-08 20:24
Hey @Programmer04515 thanks for reaching out. Which specific version of the .NET SDK are you using (`dotnet --version`).

This should've been fixed in 6.0.6 via https://github.com/dotnet/aspnetcore/pull/41182. This appears to be a duplicate of https://github.com/dotnet/aspnetcore/issues/38654.

**Comment by Programmer04515** [comment] 2022-09-08 20:26
6.0.400

I will have to update and try again. Thanks.

**Comment by TanayParikh** [comment] 2022-09-08 20:31
6.0.400 should be fine, it's more so the runtime that may need to be updated. 6.0.8 is latest https://dotnet.microsoft.com/download/dotnet/6.0

**Comment by Programmer04515** [comment] 2022-09-09 09:36
Upgraded to 6.0.400 and still running into the the same issue. However, when starting both the server and the client using the terminal's dotnet run command everything starts up and is using the ASPNETCORE_ENVIRONMENT = Staging  just without a Visual Studio's debugger attached. I am using Visual Studios 2022 Professional.

**Comment by TanayParikh** [comment] 2022-09-09 20:53
Can you please provide the output of `dotnet --info`? Are you using the latest runtime. Also, please provide the exact version of Visual Studio you're using (ex. 17.3.1).

**Comment by Programmer04515** [comment] 2022-09-12 09:23
P:\>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]


VISUAL STUDIO 2022 - ABOUT
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.3.1
Microsoft Visual Studio Professional 2022
Version 17.3.1
VisualStudio.17.Release/17.3.1+32811.315
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ASP.NET and Web Tools   17.3.375.53775
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.375.53775
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.375.53775
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-3.22401.3+41ae77386c335929113f61d6f51f2663d2780443
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

Syncfusion ASP.NET Core Project Templates   20.1.0.47
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion ASP.NET Core components.

Syncfusion ASP.NET Core Project Templates   16.1.0.32
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion ASP.NET Core components.

Syncfusion EJ2 Web Conversion and Migration   13.4.0.53
Converts and migrates a web project into a Syncfusion web project.

SyncfusionCodeGeneratorMenuCommand Extension   16.1.0.32
SyncfusionCodeGeneratorMenuCommand Visual Studio Extension Detailed Info

SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22401.3+41ae77386c335929113f61d6f51f2663d2780443
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by TanayParikh** [comment] 2022-09-12 23:51
Got it, looks like you have the latest runtime & VS.

> However, when starting both the server and the client using the terminal's dotnet run command everything starts up and is using the ASPNETCORE_ENVIRONMENT = Staging just without a Visual Studio's debugger attached. I am using Visual Studios 2022 Professional.

So it's working on command line but not through VS 17.3.1?

**Comment by Programmer04515** [comment] 2022-09-13 12:41
That seems to be the case. I have always used that configuration variable in ASP.NET Core projects for the last 3 years never had and issue , until I started working with Blazor .NET 6.0. Now when you change either the client or server project's ASPNETCORE_ENVIRONMENT variable Visual Studio hangs up when trying to debug anything.  The project builds however Visual Studio 2022 debugger does not attach and the initial redirection to the root startup page never occurs. Either I am missing something or it is broken. The project I'm currently working with is a Blazor WASM as .NET Core Hosted (.NET 6.0).

**Comment by Programmer04515** [comment] 2022-09-13 17:53
Apparently I did not read how to correctly set the Blazor environmental variable. Blazor does not use ASPNETCORE_ENVIRONMENT it uses the following to set its environment variable.

    <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        if (window.location.hostname.includes("localhost")) {
            Blazor.start({
                environment: "Staging"
            });
        } else {
            Blazor.start({
                environment: "Production"
            });
        }
    </script>


With this being the case, I believe this issues is resolved. Sorry for wasting your time.

**Closed** 2022-09-14 12:37 UTC
Labels: bug, area-blazor
