### ISSUE TITLE
Blazor WebAssembly: changing culture at runtime does not work

### ISSUE THREAD

**Issue by Fredolx** [dotnet/aspnetcore#31998] opened 2021-04-20 22:26 UTC
### Describe the bug
Blazor WebAssembly only loads the specified language in Program.cs (or browser default language if none speficied) and default fallback resx despite this
```
<PropertyGroup>
  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
</PropertyGroup>
```
being in the csproj.

Blazor WebAssembly should load ALL resx, but only loads a single one + the default fallback. 

### To Reproduce

Create a new blazor project. Add this line in program.cs (library Microsoft.Extensions.Localization 5.0.5 was used):
```
builder.Services.AddLocalization(x => x.ResourcePath = "Resources");
```
Create a folder "Resources" in root project folder, add multiple resx, ex: Pages.Index.resx, Pages.Index.fr.resx, Pages.Index.es.resx...)

Specify a default language in program.cs with the following lines:

```
            var culture = CultureInfo.GetCultureInfo("en-CA");
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;
```
Try to switch the language in Index.resx, example code:

```
@page "/"
@inject Microsoft.Extensions.Localization.IStringLocalizer<Index> r

<h1>@r["Greeting"]</h1>
<button class="btn btn-primary" @onclick='e => ChangeLang("en-CA")'>English</button>
<button class="btn btn-primary" @onclick='e => ChangeLang("fr-CA")'>French</button>
<button class="btn btn-primary" @onclick='e => ChangeLang("es-CA")'>Espagnol</button>

@code {
    void ChangeLang(string lang)
    {
        var culture = System.Globalization.CultureInfo.GetCultureInfo(lang);
        System.Globalization.CultureInfo.DefaultThreadCurrentCulture = culture;
        System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = culture;
        System.Globalization.CultureInfo.CurrentCulture = culture;
        System.Globalization.CultureInfo.CurrentUICulture = culture;

        StateHasChanged();
    }
} 
```
Only en-ca will load, other cultures will use the default fallback (Pages.Index.resx)

The bug was reproduced using Dotnet 5.

**Comment by mkArtakMSFT** [comment] 2021-04-21 16:42
Thank you for your feedback.
We're closing this issue as this behavior is by design. For culture changes to take effect the app has to be restarted.

**Closed by mkArtakMSFT** 2021-04-21 16:42 UTC
Labels: area-blazor, blazor-wasm, feature-localization

**Comment by Fredolx** [comment] 2021-04-21 16:54
Hello @mkArtakMSFT, thank you for your quick reply. Would it be possible for this to become a feature request? Other frameworks such as Angular allow instant switching without reload. I think the community may appreciate such feature! Thank you
