### ISSUE TITLE
[Blazor] [WASM-3.2 Preview 4] Authorize Attribute Roles Ignored, Identity.IsInRole() Broken

### ISSUE THREAD

**Issue by rdadkins** [dotnet/aspnetcore#21032] opened 2020-04-20 21:11 UTC
### Describe the bug
I upgraded from WASM 3.2 Preview 3 to 3.2 Preview 4 today and found that the 
```
@attribute [Authorize(Roles = "Role1,Role2,etc.")]
``` 
is ignored or broken along with `AuthenticationState.User.Claims.IsInRole("Role1")`

This did work in the previous preview.

### To Reproduce
- Have a hosted WASM with a server that is backed with Identity Server.
- Have an Authorize attribute as above with desired roles and navigate to it.
- Notice that authentication will go through fine but authorization acts as if the user does not have the roles specified. (An empty Authorize attribute works fine)

I am supplying roles from a custom `IProfileService` which I can confirm do get loaded and are visible through `AuthenticationState.User.Claims`

### Further technical details
- ASP.NET Core version: 3.1.201
- Include the output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:
  - JetBrains Rider (2020.1)
  - Visual Studio Professional 2019 (16.5.4)
  - Visual Studio Professional 2019 Preview (16.6.0 preview 3)

**Comment by javiercn** [comment] 2020-04-21 06:41
@rdadkins thanks for contacting us.

Can you provide a minimal repro that demonstrates your issue? We have specific E2E automation for this scenario, so I believe you might be missing some configuration.

**Comment by rdadkins** [comment] 2020-04-21 14:03
@javiercn sure, https://github.com/rdadkins/BlazorBrokenAuthorization

Both working and broken solutions should be identical aside from preview 3 / 4 usage.

Both utilize `[Authorize(Roles = "Admin")]` in the client Index.razor pages. Both clients also handle redirecting to the login / register page (`RedirectToLogin.razor`, `Authentication.razor`) when a user is determined to not be authenticated. For brevity, every user is an admin as defined by `ApplicationProfileService`. 

The problem that I originally reported holds true in this sample: if you run the WorkingAuthorization.Server project, you will be redirected to login / register and brought back to the main page. If authorization passes via the Authorize attribute, you will be able to see the page content. If you run BrokenAuthorization.Server project, you will be redirected to login and brought back. However, something changed when determining if a user has the specified roles or not.

Here are the tokens that `IAccessTokenProvider` returns:

Broken:
```
{
  "nbf": 1587477549,
  "exp": 1587481149,
  "iss": "https://localhost:5001",
  "aud": "BrokenAuthorization.ServerAPI",
  "client_id": "BrokenAuthorization.Client",
  "sub": "d1e39798-5b30-482d-a34f-49967012c2be",
  "auth_time": 1587476621,
  "idp": "local",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": "Admin",
  "scope": [
    "openid",
    "profile",
    "BrokenAuthorization.ServerAPI"
  ],
  "amr": [
    "pwd"
  ]
}
```
Working:
```
{
  "nbf": 1587477664,
  "exp": 1587481264,
  "iss": "https://localhost:5001",
  "aud": "WorkingAuthorization.ServerAPI",
  "client_id": "WorkingAuthorization.Client",
  "sub": "c90ce7f4-65e7-4419-92c3-9df6e1c1fe18",
  "auth_time": 1587477662,
  "idp": "local",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": "Admin",
  "scope": [
    "openid",
    "profile",
    "WorkingAuthorization.ServerAPI"
  ],
  "amr": [
    "pwd"
  ]
}
```

**Comment by aguacongas** [comment] 2020-04-23 06:54
On Blazor wasm `User.IsInRole` is not working any more too in preview 4 if the user has more than mode role. I thought it's a token deserialization issue : 

I set the role claim type to `role`.  
It works if the token contains :
```json
{
     ...
     "role": "Is4-Reader",
     ...
}
```

It's broken if the token contains:

```json
{
     ...
     "role": [
          "Is4-Reader",
         ""Is4-Writer"
    ],
    ...
}
```

At the moment I workaround with this ugly code :

```cs
public static void AddIdentityServerPolicies(this AuthorizationOptions options)
{
    options.AddPolicy(SharedConstants.WRITER, policy =>
            policy.RequireAssertion(context => context.User.Identity.IsAuthenticated &&
            context.User.Claims
                .Any(c => c.Type == "role" && c.Value.Contains(SharedConstants.WRITER))
            ));
    options.AddPolicy(SharedConstants.READER, policy =>
            policy.RequireAssertion(context => context.User.Identity.IsAuthenticated &&
            context.User.Claims
                .Any(c => c.Type == "role" && c.Value.Contains(SharedConstants.READER))
            ));
}
```

**Comment by rdadkins** [comment] 2020-04-24 14:55
I checked preview 5 and it is still broken.

I did some more research and there may be two things at play here.

1. The role claim type name is not read from the token properly or this is an undocumented change. This sort of relates to what @aguacongas mentioned with setting the role claim type to `role`.

I can do this but it still won't help:
```
builder.Services.AddApiAuthorization(options =>
{
    options.UserOptions.RoleClaim = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
});
```

2. I then stumbled upon the role claims being condensed into 1 value. Preview 3 has the claims separated:
  - http://schemas.microsoft.com/ws/2008/06/identity/claims/role - Admin 
  - http://schemas.microsoft.com/ws/2008/06/identity/claims/role - User
and preview 4 condenses the roles into one line:
  - http://schemas.microsoft.com/ws/2008/06/identity/claims/role - ["Admin","User"]

I don't know where the condensing is occurring but if I check 
```User.IsInRole(@"[""Admin"",""User""]")``` 
in preview 4+, that will return true.

**Comment by rdadkins** [comment] 2020-04-24 15:12
I think I found the issue. Before the auth rewrite in preview 4+, [`RemoteAuthenticationService` handled converting tokens to claims](https://github.com/dotnet/aspnetcore/commit/fd9c7861655f368848ede4661b183098690aabad#diff-11fb2b7199301f1ad68bf9deed0a5726L211-L228) (link is hard to view, here is the snippet);
```
if (value is JsonElement element && element.ValueKind == JsonValueKind.Array)
{
  foreach (var item in element.EnumerateArray())
  {
    identity.AddClaim(new Claim(name, JsonSerializer.Deserialize<object>(item.GetRawText()).ToString()));
  }
}
else
{
  identity.AddClaim(new Claim(name, value.ToString()));
}
```

The responsibility went to [`AccountClaimsPrincipalFactory`](https://github.com/dotnet/aspnetcore/blob/80bc4c437631ed0318f4d659ec5addba68195e3c/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccountClaimsPrincipalFactory.cs#L44-L53) and it looks like `AccountClaimsPrincipalFactory` doesn't treat arrays as it previously did. That may explain the condensing of arrays into a single line.

**Comment by javiercn** [comment] 2020-04-24 15:17
> @javiercn sure, https://github.com/rdadkins/BlazorBrokenAuthorization
> 
> Both working and broken solutions should be identical aside from preview 3 / 4 usage.
> 
> Both utilize `[Authorize(Roles = "Admin")]` in the client Index.razor pages. Both clients also handle redirecting to the login / register page (`RedirectToLogin.razor`, `Authentication.razor`) when a user is determined to not be authenticated. For brevity, every user is an admin as defined by `ApplicationProfileService`.
> 
> The problem that I originally reported holds true in this sample: if you run the WorkingAuthorization.Server project, you will be redirected to login / register and brought back to the main page. If authorization passes via the Authorize attribute, you will be able to see the page content. If you run BrokenAuthorization.Server project, you will be redirected to login and brought back. However, something changed when determining if a user has the specified roles or not.

Looked at your code, seems like you are implementing your own IProfileService. This is not how we recommend implementing roles. See [here[(https://github.com/dotnet/AspNetCore.Docs/issues/17649) for details.

The difference you are observing is due to a deliberate change we introduced in preview4 to avoid mapping arrays into claims list for you, but there is additional extensibility that should allow you to achieve this if that's how you want to do it. See [here](https://github.com/dotnet/AspNetCore.Docs/pull/17926/files?short_path=3ab406f#diff-3ab406f91c1a2e844168afcf3e458855) which gives you full control of the final ClaimsPrincipal

**Comment by javiercn** [comment] 2020-04-24 15:19
> The responsibility went to [`AccountClaimsPrincipalFactory`](https://github.com/dotnet/aspnetcore/blob/80bc4c437631ed0318f4d659ec5addba68195e3c/src/Components/WebAssembly/WebAssembly.Authentication/src/Services/AccountClaimsPrincipalFactory.cs#L44-L53) and it looks like `AccountClaimsPrincipalFactory` doesn't treat arrays as it previously did. That may explain the condensing of arrays into a single line.

Yep, this is exactly it. We don't want to have any opinion on how to remap the data from the account, but you can build it your own using the technique described [here](https://github.com/dotnet/AspNetCore.Docs/pull/17926)

**Comment by javiercn** [comment] 2020-04-24 15:20
I'm going to close this as the current behavior is by design, I suggest you follow the guidance described in the comment to make it work.

**Closed by javiercn** 2020-04-24 15:20 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor, question
