### ISSUE TITLE
[BUG] Asp.net 5 not posting form to controller when 

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/aspnetcore#29372] opened 2021-01-16 03:14 UTC
For some reason my form is refusing to post I have a controller with the method. I am using a base controller but its not overidden any of those methods just a few properties. I simply get a 404 not found even though the index is found within the same controller. I am usng .net 5
   
My Model has 
    
    public class FileManagerViewModel
    {
        public int Id { get; set; }
        
         public IFormFile? File { get; set; }
     }

My Controller method

    [HttpPost]
    [ValidateAntiForgeryToken] 
    public IActionResult UploadFiles(FileManagerViewModel fileManager) {
        FileClient client = new FileClient();
        FileInfo info = new FileInfo(fileManager.File.FileName);
        var remoteIpAddress = _httpContextAccessor.HttpContext.Connection.RemoteIpAddress;
         var t = Task.Run(() =>
            client.UploadFileAsync(_context, "username", "password", fileManager.File.FileName, info.Extension.ToLower(), UserId.ToString(), remoteIpAddress.ToString()
          ));

            return View(fileManager);
    }

Here is the form

 
    @model MSFSAddons.Models.ViewModels.FileManagerViewModel

    @{
       ViewData["Title"] = "Upload";
       Layout = "~/Themes/FrontEnd/_MyProfile.cshtml";
     }

      <form method="post" enctype="multipart/form-data" asp-controller="FileManager" asp-action="UploadFiles">
     <dl>
        <dt>
            <label asp-for="File"></label>
        </dt>
        <dd>
            <input asp-for="File" type="file">
            <span asp-validation-for="File"></span>
        </dd>
    </dl>
     <input asp-page-handler="Upload" class="btn" type="submit" value="Upload" />
    </form>

Here is my startup class 

     public void ConfigureServices(IServiceCollection services)
        {
            AppConfig.WebRootPath = _hostingEnvironment.WebRootPath;
            AppConfig.ContentRootPath = _hostingEnvironment.ContentRootPath;

            services.AddControllersWithViews();
            services.AddMvc().AddNToastNotifyToastr(new ToastrOptions()
            {
                ProgressBar = false,
                PositionClass = ToastPositions.TopRight,
                ToastClass = "alert",

            });
           
    services.AddIdentity<ApplicationUser, IdentityRole>(config =>
    {
        config.SignIn.RequireConfirmedEmail = true;
        config.Tokens.AuthenticatorTokenProvider = TokenOptions.DefaultAuthenticatorProvider;
        config.User.RequireUniqueEmail = true;

    })
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<MSFSAddonDBContext>()
        .AddDefaultTokenProviders()      
        .AddRoles<IdentityRole>();

  services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>,
AdditionalUserClaimsPrincipalFactory>();
    services.AddSession(opts =>
    {
        opts.Cookie.IsEssential = false; // make the session cookie Essential
        opts.IdleTimeout = TimeSpan.FromMinutes(30);

    });
            services.Configure<FileTransferConfig>(Configuration.GetSection("FileTransferConfig"));

            services.AddDbContext<MSFSAddonDBContext>(options =>
               options.UseSqlServer(
                   Configuration.GetConnectionString("DefaultConnection")));
                    services.AddHttpContextAccessor();
            services.Configure<FormOptions>(options =>
            {
                options.MultipartBodyLengthLimit = 6000000000;
            });

            services.AddAuthorization(options =>
        options.AddPolicy("TwoFactorEnabled",
        x => x.RequireClaim("amr", "mfa")));
            services.AddAntiforgery(o => o.HeaderName = "XSRF-TOKEN");
            services.Configure<IdentityOptions>(options =>
            {

                // Default Lockout settings.
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                options.Lockout.MaxFailedAccessAttempts = 5;
                options.Lockout.AllowedForNewUsers = true;
                

            });
    services.ConfigureApplicationCookie(config =>
    {
        config.Cookie.Name = "Identity.Cookie";
        config.LoginPath = "/Identity/Account/Login";
    
    });

            services.AddMvc().AddNToastNotifyToastr(new ToastrOptions()
            {
                ProgressBar = false,
                PositionClass = ToastPositions.TopRight,
                ToastClass = "alert",

            });
            services.AddTransient<IEmailSender, EmailSender>(i =>
                new EmailSender(
                    Configuration["EmailSender:Host"],
                    Configuration.GetValue<int>("EmailSender:Port"),
                    Configuration.GetValue<bool>("EmailSender:EnableSSL"),
                    Configuration["EmailSender:UserName"],
                    Configuration["EmailSender:Password"]
                )
            );
       
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
                options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
                options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
                
            });

   

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseDeveloperExceptionPage();

                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
    app.UseHttpsRedirection();
    app.UseStaticFiles();
            
    app.UseRouting();

    app.UseAuthorization();
    app.UseAuthentication();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
        name: "areas",
        pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");

        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
        endpoints.MapRazorPages();
    });
        }
    }

Version Info 

Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA994
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by javiercn** [comment] 2021-01-18 14:20
@davidbuckleyni thanks for contacting us.

This seems like a dupe of https://github.com/dotnet/aspnetcore/issues/29372 so closing this one in favor of the other existing issue. If they are different please let us know.

**Closed by javiercn** 2021-01-18 14:20 UTC
Labels: area-mvc

**Comment by davidbuckleyni** [comment] 2021-01-18 14:35
@javiercn  I found my solution anyway it was the type of submit button I had once i changed that it worked
