### ISSUE TITLE
Enhancements to JSInterop for when consuming from TypeScript

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/aspnetcore#18625] opened 2020-01-22 14:49 UTC
As a developer, I would like to consume JSInterop from TypeScript.

* **Export the DotNetObject class** so that it can be used when writing interop code.
* Generate a declaration file and publish it with the package.

**Comment by mkArtakMSFT** [comment] 2020-01-28 17:58
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by TanayParikh** [comment] 2021-10-19 05:39
Duplicate of https://github.com/dotnet/aspnetcore/issues/5508.

**Closed by TanayParikh** 2021-10-19 05:39 UTC
Labels: enhancement, area-blazor, affected-few, severity-major, feature-blazor-jsinterop
