### ISSUE TITLE
Hot Reload: Adding a CSS file at runtime "Index.razor.css" doesn't get picked up as a result any changes made do not get hot reloaded into the running app

### ISSUE THREAD

**Issue by MacdonaldRobinson** [dotnet/aspnetcore#34464] opened 2021-07-18 01:14 UTC
### Describe the bug
Hot Reload: Adding a CSS file at runtime "Index.razor.css" doesn't get picked up as a result any changes made do not get hot reloaded into the running app.

![image](https://user-images.githubusercontent.com/18366446/126052519-1035cdd7-9814-4c37-a719-d3e53511e563.png)

### To Reproduce
- In WSL - Ubuntu 20.04 LTS
- Create a new web app using "dotnet new blazorwasm"
- Use "code ." to open it in VS Code
- In the Terminal type "dotnet watch"
- Open the link in the browser
- Open Pages/Index.razor
- Make a change and you will see hotreload working correctly.
- Now create a new file Index.razor.css
- Notice that the file addition was not detected by dotnet watch
- Now add a css rule and save the file, nothing happens
- Refreshing the browser doesn't work as well
- CTRL + SHIFT + R does not work for some reason so you will need to stop and restart the app
- Now you can see your changes

### Expectation
Adding a Index.razor.css file should have been detected and any changes made in the file should have been hot reloaded into the running app

### Output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/mac/dotnet/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  6.0.100-preview.6.21355.2 [/home/mac/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/home/mac/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/home/mac/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment] 2021-07-19 16:46
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/33569

**Closed by mkArtakMSFT** 2021-07-19 16:46 UTC
Labels: area-blazor, feature-hot-reload
