### ISSUE TITLE
Blazor WASM Euro Currency

### ISSUE THREAD

**Issue by JulienM28** [dotnet/aspnetcore#33616] opened 2021-06-17 17:58 UTC
SDK .Net 5.0.301 Blazor WASM 5.07

in my Blazor app this:

```
@order.Price.ToString("c2")
```
is display like that: Euro currency charater is replaced by a tiny circle
![image](https://user-images.githubusercontent.com/23618436/122449596-51deaa80-cfa6-11eb-90d0-52e8a2b88831.png)

```
@order.Price.ToString("### ###.00 €")
```
is producing expected result

Thanks.

**Comment by javiercn** [comment] 2021-06-21 09:17
@JulienM28 thanks for contacting us.

Do you have enabled globalization data in your project settings as described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization)?

**Comment by JulienM28** [comment] 2021-06-21 09:59
I didn't, but it doesn't change anything.

I Added
```xml
<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
```
to my project file

and updated index.html file to:

```html
 <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        Blazor.start({
            applicationCulture: 'fr-FR'
        });
    </script>
```

But it doesn't change anything.

**Comment by JulienM28** [comment] 2021-06-21 10:02
I just noticed an interesting point:
It doesn't work on Edge 91.0.864.54 64 bits but it does on Chrome 91.0.4472.106 64 bits

**Comment by mkArtakMSFT** [comment] 2021-07-27 18:00
Thanks for the additional details, @JulienM28.
This confirms that the issue is not in Blazor and we're going to close this issue. Feel free to report this to the Edge team via the option in the browser.

**Closed by mkArtakMSFT** 2021-07-27 18:00 UTC
Labels: Needs: Attention :wave:, area-blazor, blazor-wasm, feature-localization, investigate
