### ISSUE TITLE
Navigate to incorrect URL when launch the .NET 9.0 Web API project with IIS Express.

### ISSUE THREAD

**Issue by Claire-kangkang** [dotnet/aspnetcore#56740] opened 2024-07-11 07:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

According to the change `Move generating IIS profiles in launchSettings.json from template to VS` https://github.com/dotnet/aspnetcore/issues/46501, it will generate IIS profiles automatically when launch with IIS Express, but it missing `"launchUrl": "weatherforecast"`, so it will navigate to incorrect URl when run the Web API project.

### Expected Behavior

Navigate to correct URL and load the web page correctly.
![image](https://github.com/dotnet/aspnetcore/assets/70516076/2b4d73b0-7643-4307-a792-5e100c380053)

### Steps To Reproduce

1. Create a .NET 9.0 `ASP .NET Core Web API` project.
2. Launch the project with `IIS Express`    
![image](https://github.com/dotnet/aspnetcore/assets/70516076/8e687b78-fa19-4ca4-acd5-d197305499c9)

### Exceptions (if any)

Launch the incorrectly URL
![image](https://github.com/dotnet/aspnetcore/assets/70516076/fdd7f39a-e835-4fd0-a568-b27a8168867c)

### .NET Version

Latest 9.0.100-preview.7

### Anything else?

Workaround:
 1. Ctrl + F5 run the project to generate IIS Express profiles in launchSettings.json
 2. Add `"launchUrl": "weatherforecast"` in IIS Express profiles, then run the project, the web page load correctly.
![image](https://github.com/dotnet/aspnetcore/assets/70516076/2f73f5af-5c8e-49f8-9b64-f42461178a06)

**Comment by mkArtakMSFT** [comment] 2024-07-11 15:11
@DamianEdwards would you like to take this? Looks like a regression from the previous change.

**Comment by balachir** [comment] 2024-07-15 17:23
@v-qushi can you take a look at this one? Perhaps the issue needs to move to AzDO as a tooling issue for VS 17.12.

**Comment by Claire-kangkang** [comment] 2024-07-16 07:01
@balachir I reactivated the AzDO bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2135460

**Comment by balachir** [comment] 2024-07-16 07:11
@Claire-kangkang thanks. I'll go ahead and close this issue now as it's now tracked in AzDO.

**Closed by balachir** 2024-07-16 07:11 UTC
Labels: bug, area-networking
