### ISSUE TITLE
.NET 6 Blazor typeparam constraints causing compilation error

### ISSUE THREAD

**Issue by CAPCHIK** [dotnet/aspnetcore#38041] opened 2021-11-02 21:37 UTC
### Describe the bug
I want to create reusable component for async loaded data
That component can receive nullable data and render placeholder while data is loading

I have created a component `SomeLoaderComponent`
```razor
@typeparam TData where TData : notnull // notnull to desribe that the "main" type must be not null

@if(Data is null)
{
    <p>Some loading stuff</p>
} else
{
    @if(ChildContent is not null)
    {
        @ChildContent(Data)
    }
}

@code {
    [Parameter]
    public TData? Data { get; set; } // I can take nullable data
    [Parameter]
    public RenderFragment<TData>? ChildContent { get; set; } // And render ChildContent only with loaded data
}
```

When I use that component with explicit `TData` it works correctly
```razor
@page "/"
<PageTitle>Index</PageTitle>

<SomeLoaderComponent TData="SomeDataFromServer" Data="dataFromServer" Context="loadedData">
    <h2>@loadedData.Value</h2>
</SomeLoaderComponent>

@code {
    private SomeDataFromServer? dataFromServer;
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await Task.Delay(TimeSpan.FromSeconds(5));
        dataFromServer = new SomeDataFromServer("Mock data");
    }
    public record SomeDataFromServer(string Value);
}

```

But if I try to use `SomeLoaderComponent` with `Data` only compilation will fail
```razor
@page "/"

<PageTitle>Index</PageTitle>

<SomeLoaderComponent Data="dataFromServer" Context="loadedData">
    <h2>@loadedData.Value</h2>
</SomeLoaderComponent>

@code {
    private SomeDataFromServer? dataFromServer;

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await Task.Delay(TimeSpan.FromSeconds(5));
        dataFromServer = new SomeDataFromServer("Mock data");
    }

    public record SomeDataFromServer(string Value);
}

```
```bash
﻿Microsoft (R) Build Engine version 17.0.0-preview-21501-01+bbcce1dff for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
C:\projects\ConstraintsErrorExampleSolution\ConstraintsErrorExample\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Index_razor.g.cs(142,29): error CS0449: The 'class', 'struct', 'unmanaged', 'notnull', and 'default' constraints cannot be combined or duplicated, and must be specified first in the constraints list. [C:\projects\ConstraintsErrorExampleSolution\ConstraintsErrorExample\ConstraintsErrorExample.csproj]

Build FAILED.

C:\projects\ConstraintsErrorExampleSolution\ConstraintsErrorExample\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Index_razor.g.cs(142,29): error CS0449: The 'class', 'struct', 'unmanaged', 'notnull', and 'default' constraints cannot be combined or duplicated, and must be specified first in the constraints list. [C:\projects\ConstraintsErrorExampleSolution\ConstraintsErrorExample\ConstraintsErrorExample.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.94
```

But Visual Studio UI shows correct type for `context`
![image](https://user-images.githubusercontent.com/12235437/139954372-d50173ca-f4fb-4838-853c-0874be45e6c8.png)

Compile error can be found in `Pages_Index_razor.g.cs(142,29`

```csharp
internal static class TypeInference
    {
        public static void CreateSomeLoaderComponent_0<TData>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, TData __arg0, int __seq1, global::Microsoft.AspNetCore.Components.RenderFragment<TData> __arg1)
            where TData : , notnull
        {
        __builder.OpenComponent<global::ConstraintsErrorExample.Shared.SomeLoaderComponent<TData>>(seq);
        __builder.AddAttribute(__seq0, "Data", __arg0);
        __builder.AddAttribute(__seq1, "ChildContent", __arg1);
        __builder.CloseComponent();
        }
    }
```

This looks like incorrect code generation when working with constraints not on specific types, but on keywords, according to `notnull` or `class`.

### To Reproduce
All code can be found on published repo with minimal modifications from Blazor WASM template
https://github.com/CAPCHIK/ConstraintsErrorExampleSolution

### Further technical details
- ASP.NET Core version: .NET 6 Release Candidate 2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio Enterprise 2022 Preview 17.0.0 Preview 7.0
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
﻿.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22489
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

</details>

**Comment by pranavkm** [comment] 2021-11-02 21:53
Thanks @CAPCHIK for the issue report. We'll look at addressing this issue soon. In the meanwhile, I wanted to appreciate the quality of your bug report, it's very detailed. Thanks!

**Comment by mkArtakMSFT** [comment] 2021-11-08 17:53
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/25588

**Closed by mkArtakMSFT** 2021-11-08 17:53 UTC
Labels: feature-razor.language, area-razor.compiler
