### ISSUE TITLE
Automatic type inference won't work when an EventCallBack<T> is added

### ISSUE THREAD

**Issue by MariovanZeist** [dotnet/aspnetcore#39734] opened 2022-01-24 19:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Repo to demonstrate the Issue: https://github.com/MariovanZeist/BlazorInferenceCallback

Although my use case is for Table and Grid like components I will demonstrate the feature using a simpler component:

Assume this component: (A generic list component with a click event that has the clicked item as a parameter)

``InferAndCallback.razor``
```razor
@typeparam T
  //Hide non-important code to make this brief. full code in attached Repo
@code {
    [Parameter] public IEnumerable<T> Items { get; set; } = default!;
    [Parameter] public EventCallback<T> SelectEvent { get; set; } = default!;
}
```

We will supply the component with a List of ``Ingredient``, and  (optionally) supply a click event to handle selecting the ingredient.

``index.razor``
```razor
<InferAndCallBack Items=Ingredient.Ingredients />  //This will Compile without a callback

<InferAndCallBack Items=Ingredient.Ingredients SelectEvent=SelectedIngredient /> //Adding the Callback will not compile

<InferAndCallBack Items=Ingredient.Ingredients SelectEvent=SelectedIngredient T=Ingredient /> //Removing typeinference and specifying the type directly will make it compile again.

Last ingredient:@_ingredient

@code {
    private Ingredient? _ingredient;

    private Task SelectedIngredient(Ingredient selectedIngredient)
    {
        _ingredient = selectedIngredient;
        return Task.CompletedTask;
    }
}
```

### Describe the solution you'd like

I would prefer to not have to specify the ``T`` type parameter directly, and instead, let it be inferred by the generated code.

so
```razor
<InferAndCallBack Items=Ingredient.Ingredients SelectEvent=SelectedIngredient />
``` 

Would compile without specifying the TypeParam

### Additional context

This is probably due to how the source is generated:
I cleaned the generated source up a bit to show the difference, and the problem:

this is the relevant part of the generated source file: with comments to show the problem:
```cs
{
    [Microsoft.AspNetCore.Components.RouteAttribute("/")]
    public partial class Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
		protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
		{
			//<InferAndCallBack Items=Ingredient.Ingredients />
			__Blazor.BlazorInferenceCallback.Pages.Index.TypeInference.CreateInferAndCallBack_0(__builder, 0, 1, Ingredient.Ingredients);
			//^ This compiles to and works correctly


			//<InferAndCallBack Items=Ingredient.Ingredients SelectEvent=SelectedIngredient />
			__Blazor.BlazorInferenceCallback.Pages.Index.TypeInference.CreateInferAndCallBack_1(__builder, 3, 4, Ingredient.Ingredients, 5, Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, SelectedIngredient));
			//^This fails because it generates an EventCallback instead of an EventCallback<T>
			// and the CreateInferAndCallBack_1 function expects an EventCallback<T>
			//It should be:
			//__Blazor.BlazorInferenceCallback.Pages.Index.TypeInference.CreateInferAndCallBack_1(__builder, 3, 4, Ingredient.Ingredients, 5, Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Ingredient>(this, SelectedIngredient));


			//<InferAndCallBack T=Ingredient Items=Ingredient.Ingredients SelectEvent=SelectedIngredient/>
			__builder.OpenComponent<BlazorInferenceCallback.Components.InferAndCallBack<Ingredient>>(7);
			__builder.AddAttribute(8, "Items", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Collections.Generic.IEnumerable<Ingredient>>(Ingredient.Ingredients));
			__builder.AddAttribute(9, "SelectEvent", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<Ingredient>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Ingredient>(this, SelectedIngredient)));
			__builder.CloseComponent();
			//^As we specified the type, no type inference is needed so we can generate the code as any other non generic component
		}
	}
}
namespace __Blazor.BlazorInferenceCallback.Pages.Index
{
	#line hidden
	internal static class TypeInference
	{
		public static void CreateInferAndCallBack_0<T>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.Collections.Generic.IEnumerable<T> __arg0)
		{
			__builder.OpenComponent<global::BlazorInferenceCallback.Components.InferAndCallBack<T>>(seq);
			__builder.AddAttribute(__seq0, "Items", __arg0);
			__builder.CloseComponent();
		}
		public static void CreateInferAndCallBack_1<T>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.Collections.Generic.IEnumerable<T> __arg0, int __seq1, global::Microsoft.AspNetCore.Components.EventCallback<T> __arg1)
		{
			__builder.OpenComponent<global::BlazorInferenceCallback.Components.InferAndCallBack<T>>(seq);
			__builder.AddAttribute(__seq0, "Items", __arg0);
			__builder.AddAttribute(__seq1, "SelectEvent", __arg1);
			__builder.CloseComponent();
		}
	}
}
```

**Comment by MariovanZeist** [comment] 2022-01-24 19:48
@javiercn I had another issue with Type inference, but as it was not related to constraints I created a separate Issue.

**Comment by MariovanZeist** [comment] 2022-01-24 20:16
Oops I have been sloppy, I found a duplicate issue, https://github.com/dotnet/aspnetcore/issues/37569
Although this issue might have more information. Sorry for the inconvenience.

**Comment by MariovanZeist** [comment] 2022-01-25 08:21
Updated Repo, to clarify the feature request

So I would like to be able to use the following callbacks
`` EventCallback<T>``  and  ``EventCallback<RowArgs<T>>`` without specifying the ``T=Type``

```razor
@typeparam T

@code {
    [Parameter] public IEnumerable<T> Items { get; set; } = default!;
    [Parameter] public EventCallback SimpleEvent { get; set; } = default!;
    [Parameter] public EventCallback<MouseEventArgs> MouseEvent { get; set; } = default!;
    //The below added Callbacks won't compile with TypeInference
    [Parameter] public EventCallback<T> SelectEvent { get; set; } = default!;
    [Parameter] public EventCallback<RowArgs<T>> RowEvent { get; set; } = default!;
}
```

**Comment by mkArtakMSFT** [comment] 2022-01-25 17:36
Thanks for contacting us and  providing all the details, @MariovanZeist.
This is indeed a dupe of the abovementioned issue, so closing this one.
Also, will bump-up the priority of the original issue.

**Closed by mkArtakMSFT** 2022-01-25 17:36 UTC
Labels: area-blazor
