### ISSUE TITLE
Blazor @typeparam with constraints

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/aspnetcore#27306] opened 2020-10-28 19:44 UTC
I'm trying to create a Blazor Component with typeparam, but the Razor syntax doesn't seem to allow constraints; or if it does, the syntax is not documented at all.

I was able to achieve the result by using a code-behind file and specifying the constraints there, but it would be good to be able to do it from the Razor markup.

**Comment by mkArtakMSFT** [comment] 2020-10-29 16:55
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/8433

**Closed** 2021-01-15 11:52 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
