### ISSUE TITLE
`dotnet watch` WebSockets port configuration for HotReload

### ISSUE THREAD

**Issue by sdykae** [dotnet/aspnetcore#39608] opened 2022-01-06 00:02 UTC
From https://github.com/dotnet/sdk/blob/1cbb60f4ad1a34415a8f360c90e92a70587bdb1b/src/BuiltInTools/BrowserRefresh/BrowserScriptMiddleware.cs#L49

We should configure static ports like this.
![image](https://user-images.githubusercontent.com/50224521/148306890-0d6cd9cb-2b94-49de-8543-c9f0cea6af26.png)

```json
{
    "SuperHeroAPI": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "hotReloadEnabled": true,
      "hotReloadProfile": "aspnetcore",
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:7078;http://localhost:5055",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_AUTO_RELOAD_WS_ENDPOINT": "wss://localhost:35871,ws://localhost:33863"
      }
    }
```

Then If you are a vscode remote developer you could just open those ports
![image](https://user-images.githubusercontent.com/50224521/148307028-71b873bd-493d-4819-b5e9-6c8612227162.png)

**Comment by jrmoreno1** [comment] 2022-01-25 15:59
What determines whether Hot Rloads uses  ws or wss?

**Comment by lonix1** [comment] 2022-05-01 04:15
Did you find a workaround? Hot reload is unusable as it chooses a random port each time.

**Comment by asm-flairstech** [comment] 2022-07-08 07:58
It would be impossible to configure this with CspOptions ConnectSources custom sources for trusted domains if ports are always generated randomly!

**Comment by Trystan-SA** [comment] 2023-10-26 17:29
The year is 2023 and Microsoft still didn't add an environment variable to prevent its random websocket port allocation... 🤦‍♂️

**Comment by mkArtakMSFT** [comment] 2023-12-15 22:34
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/39765

**Closed by mkArtakMSFT** 2023-12-15 22:34 UTC
Labels: enhancement, area-commandlinetools, feature-dotnetwatch

**Comment by sdykae** [comment] 2023-12-16 03:00
@mkArtakMSFT you are closing in favor of a resent issue? why? that is the dupe not this one
