### ISSUE TITLE
Can't set my own traceparent header in HttpClient

### ISSUE THREAD

**Issue by nosalan** [dotnet/aspnetcore#27846] opened 2020-11-14 13:53 UTC
# Describe the bug
.NET core is prepending something unwanted to the traceparent header. 
I'm sending HTTP request with traceparent header from .NET core app to another .NET core app. This is how I prepare request:

![image](https://user-images.githubusercontent.com/2273250/99148530-6a8d8780-2688-11eb-9767-3e275dace001.png)

In the receiving app, the Activity.Current looks like this:

![image](https://user-images.githubusercontent.com/2273250/99148393-b0961b80-2687-11eb-86c4-c7327f6c5c76.png)

My problem is that something got prepended to the the `Activity.Current.ParentID`. I expected the ParentId to be exactly equal `what_ever_1` and not `00-41ef1aa0b0bed74eb5675bed53f68b07-607cc5475c05974c-00,what_ever_1`. **This behaves correctly i.e. nothing gets prepended, when I make a request from app that is not written in .net, e.g. Postman**

### Further technical details
- ASP.NET Core version
netcoreapp3.1
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
- The IDE (VS / VS Code/ VS4Mac) Rider 2020.2.4

**Comment by Trolldemorted** [comment] 2020-11-16 22:18
Can we disable this header completely somehow?

**Comment by BrennanConroy** [comment] 2020-11-18 21:30
This looks like a dupe of https://github.com/dotnet/runtime/issues/41072. Please follow up on that issue.

**Closed** 2020-11-20 22:19 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-middleware, diagnostics
