### ISSUE TITLE
[Blazor .NET 8]  The same component instance rendered in different pages when using interactive mode

### ISSUE THREAD

**Issue by gaplin** [dotnet/aspnetcore#52102] opened 2023-11-15 22:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When on a static page I include interactive component in **the same place** then when moving from one page to the other, the same instance is rendered.
I've included simple repro including timer component.
Here is a video showing current behaviour (counter value should be reset between pages):

https://github.com/dotnet/aspnetcore/assets/50521366/edd6cda7-af26-4760-9f54-0a54ceac1dbb

Problem is solved either by:
- Using @key attribute directly on components
- Adding empty component **before** interactive one on either counter or home page.
- Using InteractiveMode directly on page

I think it might be related to this open issue #51073

### Expected Behavior

Rendered instances are different

### Steps To Reproduce

1. Clone https://github.com/gaplin/TimerRepro
2. Run the app
3. Move between pages using nav menu

### .NET Version

8.0.100

**Comment by javiercn** [comment] 2023-11-16 15:04
@gaplin thanks for contacting us.

That behavior is expected and by design. We will preserve existing interactive components when they are present on the new page, otherwise the components will lose their state, which we don't think its desirable.

**Comment by gaplin** [comment] 2023-11-16 16:47
For above use case (showing how much time user spent on given page) it is desirable to have different instances.

It's pretty hard to run into this issue since both components need to have the same parameters and be placed in the same place on different pages.

For me it seems kind of odd since such behaviour adds hidden dependency on other pages.

**Comment by mkArtakMSFT** [comment] 2023-11-16 17:57
We're going to close this for now, given this was an intentional design choice we've made during development, as well as there are ways to work around this behavior. We will, however, keep an eye to see if others will run into this issue too in the future, and if we find that too many customers find this behavior unexpected, we will revisit the design decision.

**Closed** 2023-11-16 18:00 UTC
Labels: enhancement, area-blazor
