### ISSUE TITLE
upgrade 2.1 to 3.1 - Could not load type 'Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.NumericClientModelValidatorProvider' from assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=3.1.32.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by harinath2github** [dotnet/aspnetcore#46559] opened 2023-02-09 21:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Team,

We recently started migrating our web app from core  2.1 to 3.1, but running into below.

We know the last and latest version of  Microsoft.AspNetCore.Mvc.DataAnnotations is 2.2.0

but after migrating our app from 2.1 to 3.1, we resolved all the issues, but below issue is coming all the time...

i tried all the options... nothing working out... pls help us here and resolve this

Could not load type 'Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.NumericClientModelValidatorProvider' from assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=3.1.32.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### Expected Behavior

Hi Team,

We recently started migrating our web app from core  2.1 to 3.1, but running into below.

We know the last and latest version of  Microsoft.AspNetCore.Mvc.DataAnnotations is 2.2.0

but after migrating our app from 2.1 to 3.1, we resolved all the issues, but below issue is coming all the time...

i tried all the options... nothing working out... pls help us here and resolve this

Could not load type 'Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.NumericClientModelValidatorProvider' from assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=3.1.32.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### Steps To Reproduce

Hi Team,

We recently started migrating our web app from core  2.1 to 3.1, but running into below.

We know the last and latest version of  Microsoft.AspNetCore.Mvc.DataAnnotations is 2.2.0

but after migrating our app from 2.1 to 3.1, we resolved all the issues, but below issue is coming all the time...

i tried all the options... nothing working out... pls help us here and resolve this

Could not load type 'Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.NumericClientModelValidatorProvider' from assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=3.1.32.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### Exceptions (if any)

Hi Team,

We recently started migrating our web app from core  2.1 to 3.1, but running into below.

We know the last and latest version of  Microsoft.AspNetCore.Mvc.DataAnnotations is 2.2.0

but after migrating our app from 2.1 to 3.1, we resolved all the issues, but below issue is coming all the time...

i tried all the options... nothing working out... pls help us here and resolve this

Could not load type 'Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.NumericClientModelValidatorProvider' from assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=3.1.32.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### .NET Version

2.1 to 3.1

### Anything else?

Hi Team,

We recently started migrating our web app from core  2.1 to 3.1, but running into below.

We know the last and latest version of  Microsoft.AspNetCore.Mvc.DataAnnotations is 2.2.0

but after migrating our app from 2.1 to 3.1, we resolved all the issues, but below issue is coming all the time...

i tried all the options... nothing working out... pls help us here and resolve this

Could not load type 'Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.NumericClientModelValidatorProvider' from assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=3.1.32.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by Tratcher** [comment] 2023-02-10 00:38
Is there a callstack for that exception?

Components from the `Internal` namespaces were moved to be actually internal.
https://github.com/dotnet/aspnetcore/commit/195a22d92c95445fabef3b17e67bee4aa75eff81

It sounds like you have a mixed set of dependencies. Remove any AspNetCore 2.2 packages from your project, many of those packages were discontinued and merged into a shared framework that does not require a direct reference.

https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-7.0&tabs=visual-studio#remove-obsolete-package-references

**Comment by harinath2github** [comment] 2023-02-10 17:55
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.DataAnnotations.Internal.NumericClientModelValidatorProvider' from assembly 'Microsoft.AspNetCore.Mvc.DataAnnotations, Version=3.1.32.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Moon.AspNetCore.Validation.MoonValidationMvcViewOptionsSetup.Configure(MvcViewOptions options, IServiceProvider serviceProvider)
   at Moon.AspNetCore.Validation.MoonValidationMvcViewOptionsSetup.<>c__DisplayClass0_0.<.ctor>b__0(MvcViewOptions options)
   at Microsoft.Extensions.Options.ConfigureOptions<T>.Configure(TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory<T>.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager<T>.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy<T>.CreateValue()
   at System.Lazy<T>.get_Value()
   at Microsoft.Extensions.Options.OptionsCache<T>.GetOrAdd(String name, Func<T> createOptions)
   at Microsoft.Extensions.Options.OptionsManager<T>.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager<T>.get_Value()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvokerProvider..ctor(PageLoader loader, IPageFactoryProvider pageFactoryProvider, IPageModelFactoryProvider modelFactoryProvider, IRazorPageFactoryProvider razorPageFactoryProvider, IActionDescriptorCollectionProvider collectionProvider, IEnumerable<T> filterProviders, ParameterBinder parameterBinder, IModelMetadataProvider modelMetadataProvider, IModelBinderFactory modelBinderFactory, ITempDataDictionaryFactory tempDataFactory, IOptions<T> mvcOptions, IOptions<T> mvcViewOptions, IPageHandlerMethodSelector selector, DiagnosticListener diagnosticListener, ILoggerFactory loggerFactory, IActionResultTypeMapper mapper, IActionContextAccessor actionContextAccessor)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<T1,T2>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<T1,T2>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<T1,T2>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<T1,T2>.VisitNoCache(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<T1,T2>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<T1,T2>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<T1,T2>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at async Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 105
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)

Full Trace:

   at StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(TStateMachine& stateMachine)
   at StackExchange.Exceptional.ExceptionalMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Versioning.ApiVersioningMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT<T>.ProcessRequestAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT<T>.ProcessRequestAsync()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by harinath2github** [comment] 2023-02-10 18:01
after reviewing ur response... i looked my packages, i see below two packages, which are referencing  Microsoft.AspNetCore.Mvc.DataAnnotations (2.0.0)

<PackageReference Include="BSolutions.Bocons" Version="1.0.0" />
<PackageReference Include="Moon.AspNetCore.Validation" Version="8.0.0" />

i dont latest packages for these two packages supporting core 3.1 

kindly suggest me how should i handle this for 3.1 ?

These two packages are mandatory to use

Bsolutions are needed for custom tags creation
Moon is needed for validations 



![data_annotations](https://user-images.githubusercontent.com/11857093/218163009-305e2fca-3574-4854-b0b8-b25eb81b13ac.png)

**Comment by Tratcher** [comment] 2023-02-10 21:59
MoonValidationMvcViewOptionsSetup is referencing a type NumericClientModelValidatorProvider that has been moved and made internal. There's no way work around that without updating Moon.AspNetCore.Validation.
https://github.com/djanosik/Moon.Validation/blob/7fe351827208d73eb28bb76b013c66ed86b1c2f8/src/Moon.AspNetCore.Validation/MoonValidationMvcViewOptionsSetup.cs#L31

**Comment by harinath2github** [comment] 2023-02-10 22:16
As per nuget gallery, am using latest version of Moon.AspNetCore.Validation 8.0.0
https://www.nuget.org/packages/Moon.AspNetCore.Validation#versions-body-tab

do i need to downgrade the version?

**Comment by Tratcher** [comment] 2023-02-10 23:06
I mean that you'll have to ask the developer of Moon.AspNetCore.Validation for an updated version. https://github.com/djanosik/Moon.Validation

**Closed** 2023-02-14 19:00 UTC
Labels: area-mvc, :heavy_check_mark: Resolution: Answered, Status: Resolved

**Comment by harinath2github** [comment] 2023-02-14 20:15
none of the responses are useful...Issue is not resolved....

**Comment by Tratcher** [comment] 2023-02-14 20:17
The issue is in Moon.AspNetCore.Validation, it cannot be resolved anywhere else. Please contact them for assistance.
