### ISSUE TITLE
Multiple AuthenticationHandlers still not working as expected in .net core 3.1

### ISSUE THREAD

**Issue by admir86** [dotnet/aspnetcore#18241] opened 2020-01-09 19:12 UTC
### Describe the bug
Not sure if it's a duplicate of https://github.com/dotnet/aspnetcore/issues/17485
If I return `Forbid()` in my ApiController which is using specific AuthenticationSchemes it redirects to the account/AccessDenied. The default AuthenticationScheme seems to be used. Instead of the AuthenticationSchemes defined via Authorize attribute.

I tried to set `options.ForwardDefault` oder `options.ForwardDefaultSelector` but it changes nothing.

### To Reproduce
I started with the IdentityServer and asp.net identity template `dotnet new is4aspid -n IdentityServerAspNetIdentity`.

And I added more API Endpoints like described in the [docs](http://docs.identityserver.io/en/latest/topics/add_apis.html#advanced).

Startup.cs:
```C#
...
// add asp net identity
services.AddIdentity<UserEntity, IdentityRole>(options =>
{
	options.Password.RequiredUniqueChars = 2;
})
	.AddEntityFrameworkStores<AuthDbContext>()
	.AddDefaultTokenProviders();

// add and configure identityServer
var builder = services.AddIdentityServer(options =>
{
	options.Events.RaiseErrorEvents = true;
	options.Events.RaiseInformationEvents = true;
	options.Events.RaiseFailureEvents = true;
	options.Events.RaiseSuccessEvents = true;
})
	.AddInMemoryIdentityResources(Config.Ids)
	.AddInMemoryApiResources(Config.Apis)
	.AddInMemoryClients(Config.Clients)
	.AddAspNetIdentity<UserEntity>();
...

// add "custom" scheme
builder.AddLocalApi(JwtBearerDefaults.AuthenticationScheme, options =>
{
	options.ForwardDefault = JwtBearerDefaults.AuthenticationScheme;
	options.ExpectedScope = UserConstantes.Api.ScopeName;
});

services.AddAuthorization(options =>
{
	options.AddPolicy(UserConstantes.Api.PolicyName, policy =>
	{
		policy.AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme);
		policy.RequireScope(UserConstantes.Api.ScopeName);
		policy.RequireAuthenticatedUser();
	});
});
```
Controller:
```C#
[Route("api/[controller]")]
[Authorize(Policy = UserConstantes.Api.PolicyName, AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
[ApiController]
public class UserController : ApiControllerBase
{
}
```

If I use `return Forbid(new string[1] { JwtBearerDefaults.AuthenticationScheme });` instead of `return Forbid()` it works. But that should not be necessary if the policy with that scheme is already specified on the Authorize attribute.

Another way to receive an 403 instead of a redirect to account/AccessDenied is when I move `builder.AddLocalApi` and `services.AddAuthorization` with the custom policy before `services.AddIdentity`.

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

**Comment by anurse** [comment] 2020-01-09 22:18
Which auth scheme is used by `Forbid()` is defined exclusively by [`AuthenticationOptions.DefaultForbidScheme`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationoptions.defaultforbidscheme?view=aspnetcore-3.1), so the auth scheme used on your `AuthorizeAttribute` isn't factored in.

It might be reasonable for MVC's `Forbid()` helper to look at the active endpoint metadata and use the scheme from that as the default. Though it would mean it was different behavior from `HttpContext.Forbid()` which may not be ideal.

That's up to the MVC team to decide though. Moving this to `area-mvc` since the behavior is By Design as far as `HttpContext.Forbid()` is concerned (which is what `ForbidResult` uses).

**Comment by admir86** [comment] 2020-01-11 16:06
> Which auth scheme is used by `Forbid()` is defined exclusively by [`AuthenticationOptions.DefaultForbidScheme`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationoptions.defaultforbidscheme?view=aspnetcore-3.1), so the auth scheme used on your `AuthorizeAttribute` isn't factored in.

But why its working when I change the service order? If I add the custom scheme before `AddIdentity` it works.

what do you suggest as workaround for this? to change the service order or to pass the AuthenticationScheme to the Forbid method?

**Comment by mkArtakMSFT** [comment] 2020-06-16 20:10
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

@admir86 the reason this works when you change the order is because `AddIdentity` modifies the default authentication scheme. The recommendation is to pass the scheme to the `Forbid` explicitly.

**Closed by mkArtakMSFT** 2020-06-16 20:10 UTC
Labels: area-mvc, investigate
