### ISSUE TITLE
Change behaviour for custom protocol links in blazor apps

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#29259] opened 2021-01-13 09:17 UTC
### Is your feature request related to a problem? Please describe.
I want to link a custom protocol to a hyperlink. Whenever the user clicks on it, the SignalR connection will be closed and established again automatically. A workaround for this is to set `target="_blank"` for the hyperlink but this leaves the user with an open blank tab.

### Describe the solution you'd like
It already works fine for the `mailto:` protocol, so why do other protocols behave differently? However, the `mailto:` protocol results in the same if you call it with `navigationManager.NavigateTo()`

Sometimes it is necessary to load data first which you want to forward with the protocol. So I think the `NavigateTo()` should be able to do the same thing just without closing the SignalR connection. 

### Additional context
I created a small [repo ](https://github.com/MarvinKlein1508/ProtocolExample)to show exactly what I mean

**Comment by mkArtakMSFT** [comment] 2021-07-20 17:52
@captainsafia isn't this fixed already?

**Comment by captainsafia** [comment] 2021-07-21 23:02
Yes, this was already fixed. We have tests to cover the mailto protocol scenario. It looks like this issue is related to a different custom protocol so that might have something to do with it.

- Can you try setting the forceReload property in your NavigateTo call?
- What is the custom protocol you are trying to use? Do you repro the same issue with mailto?

**Comment by MarvinKlein1508** [comment] 2021-07-22 06:46
@captainsafia 

I tested it yesterday with the latest public .NET 6 and it still has the same behaviour as mentioned above.

We created our own protocol which should open an installed C# console application with a parameter and do a simple task which is not possible otherwise.

Also we need to call the mailto within the navigation manager because there are multiple possible email addresses in our case which we need to get first from the database before we can navigate with mailto (as well as some attachments needs to be created first).

Sire I can try to set force reload to true but we don‘t want the page to reload while calling a custom protocol.

**Comment by captainsafia** [comment] 2021-07-26 23:01
So we validate the `mailto` link scenario in our own tests here:

https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Components/test/E2ETest/ServerExecutionTests/CircuitGracefulTerminationTests.cs#L95

Are you able to provide a repro for this? Otherwise it's hard how to see our validations pass for custom protocols (or at least `mailto` links).

**Comment by MarvinKlein1508** [comment] 2021-07-27 07:50
@captainsafia I updated my example repro from above for you. You can find it here:
https://github.com/MarvinKlein1508/ProtocolExample

I put six scenarios for you in it.
1.) mailto as href
2.) mailto with navigationManager
3.) mailto with new tab
4.) Custom protocol with href
5.) Custom protocol with navigationManager
6.) Custom protocol with new tab

To test the custom protocol you'll need to register it within your registry first.

**Comment by MarvinKlein1508** [comment] 2021-08-05 16:58
@captainsafia did you find some time to check the repro out?

**Comment by captainsafia** [comment] 2021-08-06 20:05
@MarvinKlein1508 Yes -- admittedly, I had trouble setting the custom protocol registration up so I ended up replacing `myprotocoll` with a protocol that was already registered on my machine (notion).

For that scenario, I wasn't able to reproduce the SignalR connection closing. Is there any chance it might be an issue with the protocol you registered?

**Comment by MarvinKlein1508** [comment] 2021-08-06 20:12
@captainsafia you should be able to test this scenario with this registry script:

Windows Registry Editor Version 5.00

```
[HKEY_CURRENT_USER\Software\Classes\CustomProtocoll]
"URL Protocol"="\"\""
@="\"URL:Custom Protocol\""

[HKEY_CURRENT_USER\Software\Classes\CustomProtocoll\DefaultIcon]
@="\"CustomProtocoll.exe,1\""

[HKEY_CURRENT_USER\Software\Classes\CustomProtocoll\shell]

[HKEY_CURRENT_USER\Software\Classes\CustomProtocoll\shell\open]

[HKEY_CURRENT_USER\Software\Classes\CustomProtocoll\shell\open\command]
@="\"C:\\CustomProtocoll\\CustomProtocoll.exe" \"%1\""
```

All you'll need know is a exe called `CustomProtocoll.exe` which is located in `C:\CustomProtocoll` Just create a basic C# console app for this. 

I don't know in which version you've tested this. In my repro the SignalR connection will be closed in case 2, 4 & 5.

3 & 6 are my workaround to prevent the closing.

**Comment by MarvinKlein1508** [comment] 2022-08-02 13:14
@captainsafia any update on this? :)

**Comment by mkArtakMSFT** [comment] 2023-11-05 23:37
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2023-11-05 23:37 UTC
Labels: bug, investigate, area-blazor, affected-few, severity-blocking, feature-blazor-builtin-components
