### ISSUE TITLE
Blazor - support variable height container in Virtualize component

### ISSUE THREAD

**Issue by GioviQ** [dotnet/aspnetcore#36969] opened 2021-09-25 12:53 UTC
I know only at runtime the height of Virtualize container with the following style.

                        <div style="flex-grow: 1; flex-basis: 0; min-height: 0; overflow-y: auto; overflow-x: hidden; margin: 0 -15px ">                                      
                                      <Virtualize @ref="asyncVirtualize" Context="item" ItemsProvider="LoadToDos" ItemSize="50">
                                          <ItemContent>
                                              <div class="row row-todo" @key="item.Id">
                                                  <div class="col-2"><MatIconButton Icon="delete" OnClick="@(() => OpenDeleteDialog(item))"></MatIconButton></div>
                                                  <div class="col-2">@item.Title</div>
                                                  <div class="col-2"><MatCheckbox class="filled-in chk-col-blue" TValue="bool" Value="@item.IsCompleted" ValueChanged="@(() => Update(item))"></MatCheckbox></div>
                                                  <div class="col-2">@item.CreatedOn</div>
                                                  <div class="col-2">@item.CreatedBy?.UserName</div>
                                                  <div class="col-2">@item.ModifiedBy?.UserName</div>
                                              </div>
                                          </ItemContent>
                                          <Placeholder>
                                              <div class="loading-items" />
                                          </Placeholder>
                                      </Virtualize>
                                  </div>
                                  

Without a fixed height I have

https://user-images.githubusercontent.com/7103057/134772254-b55017c5-56e7-4d71-9ebd-b1e8e01ee20b.mp4

**Comment by GioviQ** [comment] 2021-09-25 19:21
In fact it would be better if it can scroll like Twitter

**Comment by mkArtakMSFT** [comment] 2021-09-27 16:57
Thanks for contacting us. This is a dupe of #25058

**Closed by mkArtakMSFT** 2021-09-27 16:57 UTC
Labels: area-blazor

**Comment by GioviQ** [comment] 2021-09-27 19:03
It is not a duplicate of #25058 where it regards variable item height, this regard height of container not fixed.

**Comment by GioviQ** [comment] 2021-09-29 19:09
https://www.youtube.com/watch?v=CxK5qNhhZmo
