### ISSUE TITLE
Setting custom StartIndex in Blazor Virtualize

### ISSUE THREAD

**Issue by qin-guan** [dotnet/aspnetcore#29381] opened 2021-01-16 16:54 UTC
I am trying to manually set the StartIndex in Blazor Virtualize. 

Currently Virtualize would always query from index 0, which makes it hard to implement things like a chat, where the user would expect to start from a certain index/the most recent message and not the first message. 

Being able to manually define a StartIndex would most likely solve the issue, unless there is already a solution for this.

I have opened a [discussion](https://github.com/dotnet/aspnetcore/discussions/29188),  but there has been no progress, so I've resorted to opening an issue.

**Comment by javiercn** [comment] 2021-01-18 15:18
@qin-guan thanks for contacting us.

We believe this issue will be covered by #26943 so we are marking this issue as a duplicate of that one and using it to track it.

**Closed** 2021-01-18 15:27 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
