### ISSUE TITLE
dotnet watch run does not reload application in a Blazor wasm app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37708] opened 2021-10-20 15:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/dotnet-watch-run-does-not-reload-applica/1557007)._

---
[regression] [worked-in:16.11.5]
I have a Blazor WebAssembly app in Visual Studio 2022 RC with .NET 6.

I'm running the application with dotnet watch run. However, the application does not reload when I change the contents of a page. The Console says

```
watch : File changed: C:\[path]\MyPage.razor.
watch : No hot reload changes to apply.
```

I need to press Ctrl+R in the console window to reload manually.

---
#### Feedback Bot on 10/18/2021, 07:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/18/2021, 07:46 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-11-02 19:42
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/36723

**Closed by mkArtakMSFT** 2021-11-02 19:42 UTC
Labels: bug, area-commandlinetools, Author: Migration Bot :robot:, feature-dotnetwatch, feature-hot-reload
