### ISSUE TITLE
IdentityUserClaim<> and IdentityRoleClaim<> primary key

### ISSUE THREAD

**Issue by Vake93** [dotnet/aspnetcore#18046] opened 2019-12-27 13:22 UTC
Currently I can set the key(Id) type in most of the identity related tables, but in IdentityUserClaim<> and IdentityRoleClaim<> TKey corresponds to the key of the UserId and not the Id itself. I understand that this is might be a breaking change, but would it be possible consider changing this in 5.0 just that it is more consistent?

**Comment by blowdart** [comment] 2020-01-07 15:52
What benefit do you see in changing this?

**Comment by Vake93** [comment] 2020-01-08 03:26
Maybe this isn’t a general scenario but in my project I have modeled the domain models to inherit from a base class called “Entity” which contains the Id (of type Guid) and some other columns like created date, last modified date and row deleted state.
Then I create repositories and queries for these models, and because of all my domain models inherit from “Entity” class I can have a Repository<TEntity> and Query<TEntity> (where TEnitity: Entity) and have a generic base implementation for Repositories and Queries. Also in the DB Context I have overloaded the SaveChanges and SaveChangesAsync methods and have a change tracking log implemented based on the fact that all domain models inherit from the base class “Entity”.
But as you see I have the model Id as a Guid and IdentityUserClaim<> and IdentityRoleClaim<> doesn’t fit in to this model of mine.
That being said it’s being sometime since I got this issue initially, and I have excluded Identity models from custom domain class hierarchy and I have yet to run into a need to directly access IdentityUserClaim or IdentityRoleClaim directly as all most all interactions with identity is handled by UserManager<User>.
The only minor issue I have currently is the change tracking but even that is not that bad.
So if you all don’t see the huge gain by this change please disregard this issue.

**Comment by blowdart** [comment] 2020-01-08 20:24
OK, we don't want to disregard the issue, but this is simply the way it is. You could head down the route of writing all your own POCOs and then you can test using our tests, but that's probably a huge burden on you, as you'd have to implement stores too. 

The benefit here is too narrow for changes that would be needed for us,

**Comment by Vake93** [comment] 2020-01-09 03:09
Yeah that is something I could do and would be an interesting exercise as well, but for my current project I don't really want to do it as i want to keep this project upto date with future versions of .NET / ASP.NET core. If I implemented identity models and stores again in my code, I would have to upgrade them as well. 😅

**Comment by blowdart** [comment] 2020-02-05 20:20
We're closing this issue as the behaviour discussed seems to be by design.

**Comment by blowdart** [comment] 2020-02-19 18:26
We're closing this issue as the behaviour discussed seems to be by design.

**Closed by blowdart** 2020-02-19 18:26 UTC
Labels: area-identity
