### ISSUE TITLE
Can't find the {project}.styles.css file, when using the Blazor Web App template create a .Net 8.0 application

### ISSUE THREAD

**Issue by SebastianKruseWago** [dotnet/aspnetcore#56262] opened 2024-06-17 08:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1:1 the same issue as in this issue: https://github.com/dotnet/aspnetcore/issues/50473 

<img width="1919" alt="chrome_eDiEWXuZmi" src="https://github.com/dotnet/aspnetcore/assets/43960542/87cbf67b-034e-45dc-81c4-9172538006bf">

[EMC-MET Web.zip](https://github.com/user-attachments/files/15864395/EMC-MET.Web.zip)

### Expected Behavior

That at least the templates work as expected...

### Steps To Reproduce

Create a new Blazor App with .NET 8. 

### Exceptions (if any)

That the templates work...

### .NET Version

8.0.300

**Comment by javiercn** [comment] 2024-06-17 09:10
@SebastianKruseWago thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/52196 

the problem is the space in your project name. You need to substitute it with `EMC-MET_Web.styles.css`

**Closed** 2024-06-17 09:10 UTC
Labels: area-blazor
