### ISSUE TITLE
In VS cloud scenarios doing find all references on a C# type results in a broken FAR dialog

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21070] opened 2020-04-21 20:33 UTC
![image](https://user-images.githubusercontent.com/2008729/79910994-7eb02580-83d4-11ea-9d33-d7f7c0f9adeb.png)

We probably need to fill out our LSP span mapping service: https://github.com/dotnet/aspnetcore-tooling/blob/7fa56fb1071c014bad8e471916a0143acb33fd6a/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentPublisher.cs#L95-L98

**Comment by ryanbrandenburg** [comment] 2020-05-04 20:39
I'm not seeing this, it seems like FAR isn't even enabled in these scenarios? Has that changed recently or is there some way to make this happen other than the dropdown menu or hitting Shift+F12?

**Comment by NTaylorMullen** [comment] 2020-05-04 22:47
> I'm not seeing this, it seems like FAR isn't even enabled in these scenarios? Has that changed recently or is there some way to make this happen other than the dropdown menu or hitting Shift+F12?

Those are both the ways I know of to invoke FAR. But you're right it looks like that error doesn't come up anymore. Instead it looks like it just does nothing if you do FAR on something that exists in a Razor file. Makes me think things are just exploding int he background.

**Comment by TanayParikh** [comment] 2020-05-15 23:05
This appears to be a C# issue. Created: https://github.com/dotnet/roslyn/issues/44308

**Comment by TanayParikh** [comment] 2020-05-19 22:44
Removing external flag as a TEMP fix to this has been merged and inserted into VS (https://github.com/dotnet/roslyn/pull/44283), however the issue is still repro'ing. 

 A more permanent fix requires updates to VS LSP (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1094786/).

**Comment by ajaybhargavb** [comment] 2020-06-19 21:16
@TanayParikh is this now unblocked?

**Comment by TanayParikh** [comment] 2020-06-19 21:53
> @TanayParikh is this now unblocked?

This should've been unblocked with the C# Span Mapping & Excerpt services. However, after trying it out, the requests weren't being received in the LiveShare environment. 

I was going to wait on https://github.com/dotnet/roslyn/issues/45063 to see whether the issue is FAR specific, or an underlying bug with Liveshare where the appropriate calls may be lost.

**Comment by TanayParikh** [comment] 2020-07-16 05:19
Linking with: https://github.com/dotnet/roslyn/pull/45956

**Closed** 2020-07-29 22:39 UTC
Labels: Done, area-razor.tooling, bug, cost: S
