### ISSUE TITLE
Cannot build on Ubuntu 18.04 in WSL (1 or 2)

### ISSUE THREAD

**Issue by sharpninja** [dotnet/aspnetcore#12963] opened 2019-08-08 01:16 UTC
### Describe the bug
I cannot build aspnetcore from source.  When the `./restore.sh` script runs it attempts to add `internal.aspnetcore.buildtasks/3.0.0-build-20190530.3` to `~/.nuget/packages` twice, failing on the second attempt.

### To Reproduce

I am using this script to initialize a fresh pull from GitHub, update it from aspnet/aspnetcore MASTER and then do the build.

```bash
#!/usr/bin/env bash

cd /mnt/e/GitHub/sharpninja

rm -r -f aspnetcore

git clone --recursive git@github.com:sharpninja/AspNetCore.git

cd aspnetcore

git remote add upstream https://github.com/aspnet/aspnetcore
git fetch upstream
git reset --hard upstream/master

git submodule update --init --recursive

./restore.sh
./build.sh --all -c Debug -v d
```

### Expected behavior

Build should complete.

### Additional context
I'm attaching a log file of a run.  This problem is repeatable.
[aspnet-build.log](https://github.com/aspnet/AspNetCore/files/3479421/aspnet-build.log)

**Comment by jkotalik** [comment] 2019-08-08 06:07
I don't think we have tried running our builds on WSL. Seems like we probably make some invalid assumptions.

**Comment by sharpninja** [comment] 2019-08-09 15:00
This is an important dev cycle as I believe that developing for Linux is actually easier on Windows/WSL than on a standalone Linux as Windows is such a better GUI experience.

**Comment by dougbu** [comment] 2020-07-09 05:07
@sharpninja this issue seemed to fall through the cracks. I cannot reproduce the problem today and suggest you retry.

That said, WSL does introduce odd problems not seen in regular Linux environment. The build can get confused and attempt to run Windows executables if they are found in your path (then fail). I for example had to install the Linux versions of `nodejs`, `npm` and `yarn` to build cleanly.

**Comment by sharpninja** [comment] 2020-07-17 14:53
@dougbu I haven't worked with this in quite a while but may get around to trying again soon.

**Comment by dougbu** [comment] 2020-10-21 22:28
Thank you for your feedback. We're closing this issue as the questions asked here have been answered. If you're still having issues, please reopen this issue.

@javiercn that is _not_ to say everything is perfect w/ WSL and our repo. I suggest the Department of Infrastructure cover an issue to improve our documentation to help users ensure they aren't using (say) the Windows version of `javac` in their WSL environments. See
> The build can get confused and attempt to run Windows executables if they are found in your path (then fail). I for example had to install the Linux versions of nodejs, npm and yarn to build cleanly.

**Closed** 2020-10-21 22:28 UTC
Labels: area-infrastructure
