### ISSUE TITLE
New Blazor application (any type) hangs in browser with "Loading..." message

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27522] opened 2020-11-04 16:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/New-Blazor-application-any-type-hangs-/1228763?preview=true)._

---
[severity:I'm unable to use this version of Visual Studio]
1. Start-up Visual Studio 2019 Preview 4 (with .NET 5). This was the latest (.NET 5) preview release when I installed it on 16 October 2020.
2. Create new Blazor (Client-side, without .NET Core hosting) project. Don't click any of the checkboxes. Leave all defaults unchanged. (I also at some point tried the Server-side Blazor project. That then also resulted in the same hanging problem.)
3. Choose the file location and give names to the solution and project. Create the project.
4. Wait for the solution and project to get created. Don't delete, change or create anything in the project or solution.
5. Click on run, and see the browser (Edge) open (after the build seems to complete inside Visual Studio).
6. Inside the Edge browser the browser page says "Loading...". The text stays there, seemingly forever. Nothing else happens inside the browser.

Of course this is wrong. It should complete loading the application and show the application contents, but it hangs there for at least 10 minutes that I left it there. My conclusion is the the application hangs.

---
#### Feedback Bot on 10/21/2020, 07:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Aubrey Herman solved on 10/26/2020, 03:19 AM, 0 votes: 

<p>In short: The issue seems to go away after 'opening' the firewall. Initially there was no hint (and I did not think) about checking if the firewall is allowing access.</p><p>Explanation:</p><p>I downloaded version 16.8 preview 5, and it seemed to have the same problem. But then at some point when I was trying to run the application (PWA) from within Visual Studio, I (surprisingly for the very first time) got a message from my Windows Firewall that an application (Nodejs) was blocked and that I had to give permission for it to communicate over the network. After giving it this firewall permission, the problem went away.</p><p>Suggestion: when in development mode, after a timeout showing 'Loading...' in the browser, show a message to the developer (or some hint) to check the firewall!</p>

**Comment by mkArtakMSFT** [comment] 2020-11-04 16:37
Thanks for contacting us.
@captainsafia do we know whether this port-opening is expected? If I remember correctly, Firewall will pop up for any app asking to open any ports. Given that the Debugger does indeed try to open up a port, I think this is expected.

**Comment by captainsafia** [comment] 2020-11-04 16:46
@mkArtakMSFT Yes, this is expected. The NodeJS process that is asking for the debugger is the vscode-js-debug adapter.

@guardrex Let's add a note about this in the docs.

**Comment by guardrex** [comment] 2020-11-04 16:50
@captainsafia ... This is such a fundamental problem it seems like it should be covered in the Get Started topic. Is that correct, or where do you want it covered?

**Comment by captainsafia** [comment] 2020-11-04 16:55
@guardrex Yeah, I would propose adding a bullet under the debugging prerequisites section (e.g. "Ensure that no firewalls or proxies will block communication with the debug proxy") then a few sentences in the troubleshooting section about configuring the Windows Firewall.

**Comment by guardrex** [comment] 2020-11-04 17:00
That list is about browser versions, so that text won't compose well there. It will need to be it's own separate instruction. We can look at it on the PR shortly.

**Comment by captainsafia** [comment] 2020-11-04 17:05
Sounds good! I'll close this issue in favor of the docs issue referenced above.

**Closed by captainsafia** 2020-11-04 17:05 UTC
Labels: Author: Migration Bot :robot:, area-blazor, blazor-wasm, feature-blazor-debugging

**Comment by mrpmorris** [comment] 2020-11-05 08:41
I think the problem is that you need the latest Edge Beta for Blazor .NET5 to work. It should work in Chrome/Firefox, which should prove it's not a firewall issue.

This is why I cannot upgrade my work project. I can't instruct customers to download beta apps.

I hope the compatible version of Edge will be released soon!

**Comment by captainsafia** [comment] 2020-11-05 22:50
@mrpmorris Assuming I understood your report correctly, this seems unrelated to debugging. This issue only affects development instances of the app and shouldn't affect customers. If you've noticed something weird with Edge Beta and Blazor in production, please file a new issue so we can track it.

**Comment by mrpmorris** [comment] 2020-11-06 08:33
@captainsafia There isn't a problem with the latest beta. My problem is that if I want to use Net5 wasm I have to tell my clients to install Beta software, and as they are all large companies there is zero chance of that happening.

We really need a compatible version of Edge to be released to support Net5
