### ISSUE TITLE
hubconnection.stop() throws Object expected error in Angular 9 and IE11.

### ISSUE THREAD

**Issue by Vikki123** [dotnet/aspnetcore#20959] opened 2020-04-17 16:58 UTC
### Describe the bug
Hi all. I am using angular 9 application with "@microsoft/signalr": "~3.1.2", My application runs as an iframe of another application.

My Requirement

When the parent application unloads the angular application, on window unload event we call hubconnection.stop() method to stop the connection . But when i do this i see an error in the IE console as shown below

![image](https://user-images.githubusercontent.com/8450434/79593931-cba4ab00-80f9-11ea-893a-9705ee66ead8.png)

The issue does not happen in chrome or any other browser. So my question is does the library require any specific core-js polyfills to make it run in the old browsers? Also i have not seen this error in old versions of angular.

### To Reproduce

What steps can we follow to reproduce the issue?

1) Create a new angular 9 application.
2) Change the target in tsconfig to es5.
3) Delete browserslist file.
4) App.component.ts

```
import { Component, OnDestroy, OnInit } from '@angular/core';
import { HubConnection, HubConnectionBuilder } from '@microsoft/signalr';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'lkasjsd';

  hubConnection: HubConnection;
  subject = new Subject();
  subjectObs = this.subject.asObservable();

  ngOnInit() {
    this.hubConnection =
      new HubConnectionBuilder().withUrl('/url').build();
    window.addEventListener('unload', this.handleWindowUnload.bind(this));

    this.hubConnection.start().then(() => {
      console.log('Connnected Success');
    });

    this.subjectObs.subscribe(() => {
      console.log('Stopping');
      this.hubConnection.stop();
    })
  }

  handleWindowUnload() {
      this.subject.next();
  }
}
```

Replace url with any signalR server address.
5) Run the application as an iframe of some other application. I use the following script to reproduce the error

```
< !DOCTYPE html>
    <html>

    <body>

        <button id="add" onclick="add()">Add</button>
        <button id="remove" onclick="remove()">Remove</button>
        <div id="iframe">

        </div>

    </body>
    <script>
        function add() {
            var ifrm = document.createElement("iframe");
            ifrm.setAttribute("src", "http://localhost:4200");
            ifrm.style.width = "640px";
            ifrm.style.height = "480px";
            document.getElementById('iframe').appendChild(ifrm);
        }

        function remove() {
            let element = document.getElementsByTagName('iframe')[0];
            document.getElementById('iframe').removeChild(element);
        }
    </script>

    </html>
```

6) Click on add, and then remove in IE. You will see the exception logged in the console.
 

### Further technical details
Angular CLI: 9.0.4
Node: 10.19.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.4
@angular-devkit/core         9.0.4
@angular-devkit/schematics   9.0.4
@schematics/angular          9.0.4
@schematics/update           0.900.4
rxjs                         6.5.3

Let me know if any further informations are required.

**Comment by anurse** [comment] 2020-04-17 19:58
That call stack doesn't have SignalR in it at all, as far as I can tell. The error appears to be from a slice operation happening in `Subject.next`. Does the issue reproduce if you don't use a subject and instead capture the `hubConnection` and call `.stop` on it directly from your on unload handler with code like this?

```javascript
    window.addEventListener('unload', () => this.hubConnection.stop());
```

**Comment by Vikki123** [comment] 2020-04-17 20:27
I had tried commented out the hubconnection.stop() line and everything works fine. So i assume it doesn't have to do anything with subject.next. And this occures only during frame unload. Normal scenario seems to be working fine. Does the library need any polyfills to make it work during this scenario. Anything we r missing ?

**Comment by BrennanConroy** [comment] 2020-04-17 22:32
I don't see how this is related to SignalR at all.

I grabbed your html page and loaded an empty angular component. When I remove the iframe I still get the "Object doesn't support this action" error.

**Comment by Vikki123** [comment] 2020-04-18 03:29
Yes thats because angular dev server uses websocket internally for live reloading. If you do a ng build, it will work fine and you can see only signalR error. Also the error is different in the above case. Reffer the screenshot attached in the original question.

**Comment by Vikki123** [comment] 2020-04-19 14:15
Just to add on the issue, i followed the tutorial given in the official docs [Here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio) and ran the application as an iframe as shown above. I started the chat, and in the middle i unloaded the frame and following error is shown.
![image](https://user-images.githubusercontent.com/8450434/79690095-53afbf80-8276-11ea-8f75-8b48a8cb755b.png).

**Comment by Vikki123** [comment] 2020-04-19 14:16
Please have a look at the issue and let us know if anything we are missing. This is blocking our release. Thanks in advance :)

**Comment by anurse** [comment] 2020-04-19 14:31
> This is blocking our release.

@Vikki123 please be aware that if you want SLA-bound support (i.e. a commitment to a specific timeline for help debugging an issue), then you’ll need to go through [Microsoft Support](http://support.microsoft.com/supportforbusiness/productselection?sapId=bec2bc54-b200-6962-301f-f098532f27b2). We’ll do our best to assist and try to investigate if there might be a SignalR bug here but can’t commit to diagnosing a problem in specific apps unless we can identify a clear product bug.

**Comment by anurse** [comment] 2020-04-20 19:59
@Vikki123 can you collect Debug-level logs from the SignalR JavaScript client (guidance here: https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#javascript-client-logging) and share them (feel free to check them for secrets, but the client-side logs will only have things that a user browsing your site would already be able to see). My hunch is that a different error is occurring and being masked by (or possibly causing) the you're seeing.

Angular (well, actually zone.js) does some weird stuff to hijack WebSockets and it can cause problems. It's possible this issue lies in their logic.

**Comment by Vikki123** [comment] 2020-04-22 12:58
Attaching the debug logs. I have removed the hub url and replaced it with the string url. Hope thats okay


```
[2020-04-22T12:53:38.753Z] Information: Normalizing 'url' to 'url'
[2020-04-22T12:53:38.754Z] Debug: Starting connection with transfer format 'Text'.
[2020-04-22T12:53:38.754Z] Debug: Sending negotiation request: url.
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[2020-04-22T12:53:38.777Z] Debug: Selecting transport 'WebSockets'.
[2020-04-22T12:53:38.800Z] Information: WebSocket connected to url.
[2020-04-22T12:53:38.801Z] Debug: The HttpConnection connected successfully.
[2020-04-22T12:53:38.802Z] Debug: Sending handshake request.
[2020-04-22T12:53:38.802Z] Information: Using HubProtocol 'json'.
[2020-04-22T12:53:38.805Z] Debug: Server handshake complete.
[2020-04-22T12:53:38.805Z] Debug: HubConnection connected successfully.
Connnected Success
[WDS] Live Reloading enabled.
[2020-04-22T12:53:45.327Z] Debug: Stopping HubConnection.
[2020-04-22T12:53:45.328Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnecting.
[2020-04-22T12:53:45.329Z] Information: Connection disconnected.
[2020-04-22T12:53:45.329Z] Debug: HubConnection.connectionClosed(undefined) called while in state Disconnecting.
SCRIPT445: Object doesn't support this action
zone.js (192,1)
SCRIPT5007: Object expected
to-integer.js (7,1)

```

**Comment by Vikki123** [comment] 2020-04-22 12:59
Yes i agree something is happening when it is run under zone. Running it outside the angular zone seems to be working fine.

**Comment by anurse** [comment] 2020-04-22 21:55
Doing some debugging, this appears to be an issue in core-js (the ECMAScript polyfill Angular is using). The reason removing the `hubConnection.stop` call fixes the issue is simply because we're hitting a code path that causes this bug (which seems to be in handing async code, and `hubConnection.stop` is async).

Zone.js is calling `array.slice()` with no arguments, which is not listed as allowed by the [definition of `slice`](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.10) but the implementation is supposed to eventually call [`ToNumber(start)`](http://www.ecma-international.org/ecma-262/5.1/#sec-9.3) which is supposed to return `NaN` when given an undefined argument instead of throwing.

I noticed you seem to have come to a similar conclusion and filed https://github.com/zloirock/core-js/issues/812 . It's up to core-js to fix this from here, unless we can identify a problem in SignalR's usage. I'm going to close this issue for now and post a similar bit of my analysis in the other thread on core-js's tracker.

**Closed by anurse** 2020-04-22 21:55 UTC
Labels: Needs: Attention :wave:, area-signalr
