### ISSUE TITLE
Add support for CSS isolation in MVC tag helpers

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#38265] opened 2021-11-10 18:26 UTC
### Describe the solution you'd like
I'd like to be able to use CSS isolation with tag helpers e.g. the `<input>` tag.

**Comment by javiercn** [comment] 2021-11-11 11:10
@BrunoBlanes thanks for contacting us.

I'm going to mark this as a dupe of https://github.com/dotnet/aspnetcore/issues/30213 since this is the approach that we would take. Please feel free to upvote that issue instead.

**Closed by javiercn** 2021-11-11 11:10 UTC
Labels: area-mvc

**Comment by BrunoBlanes** [comment] 2021-11-11 11:20
But that's for Blazor, what about MVC?

**Comment by javiercn** [comment] 2021-11-11 11:22
@BrunoBlanes we'll do it for both, we didn't have CSS isolation support for MVC when we filed the issue.

**Comment by BrunoBlanes** [comment] 2021-11-11 11:23
Lovely, thanks!
