### ISSUE TITLE
Are there plans to imlement adding user to group by name identifier(not connectionId)?

### ISSUE THREAD

**Issue by AwanesowArtem** [dotnet/aspnetcore#18490] opened 2020-01-21 21:54 UTC

**Comment by javiercn** [comment] 2020-01-22 12:40
@AwanesowArtem thanks for contacting us.

Can you clarify what you mean?

**Comment by AwanesowArtem** [comment] 2020-01-22 13:03
@javiercn there is method "Groups.AddToGroupAsync", the first parameter of this method is connectionId. 
I would be happy if there is method overload which will accept userId instead of connectionId.

Thanks in advance.

**Comment by AwanesowArtem** [comment] 2020-01-22 13:59
@javiercn did I describe clearly?

**Comment by javiercn** [comment] 2020-01-22 14:55
@AwanesowArtem thanks.

I couldn't tell which part of the product you were talking about. I'm assuming this is signalr

**Comment by AwanesowArtem** [comment] 2020-01-22 22:05
@javiercn sorry for not specifying which product I'm talking about. Yes, it's SignalR Core(ASP.NET Core 2.2)

**Comment by anurse** [comment] 2020-01-22 22:35
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/8367 .

Adding to a group by name identifier is quite costly and the value hasn't outweighed the cost in our experience. The Azure SignalR service would need to be updated, as would the Redis scale-out provider. That can change as we hear more, but for now I'm closing as this isn't something we plan to take action on now, or in the current plans for the future.

**Closed by anurse** 2020-01-22 22:35 UTC
Labels: area-signalr
