### ISSUE TITLE
Unwanted reload of Blazor wasm

### ISSUE THREAD

**Issue by istvanloth** [dotnet/aspnetcore#18986] opened 2020-02-12 18:56 UTC
(First I'd like to say sorry, my english isn't very good).

My Environment:
- Blazor 3.2.0-preview1.20073.1 (this problem was exists in the previous versions also)
- VS 2019 Community (fresh)
- Blazor WebAssemblyApp(s) with "ASP.NET Core Hosted option)

Wasm reloads many time in my complex solution. I can't identify the cause in every case but I can reproduce it in a special one: load a page from another assembly than the Client.

Steps to reproduce:
- Create a new Blazor Web Assembly with hosting (In my example called: TestBlazorApp)
- Add a Razor Class library (TestPortal) to store portal pages (simple solution, the real is more complex)
- Add new Razor Component (PortalTestPage1) to portal project and modify it to page with route: @page "/portal/page1"
- Add reference in TestBlazorApp.Client to Portal
- Modify App.razor to find route in TestPortal assembly: 
      <Router AppAssembly="@typeof(Program).Assembly" AdditionalAssemblies="@(new[] {typeof(PortalTestPage1).Assembly })">
- Start the TestBlazorApp.Server as usual
- After it's loaded than modify the address in the browser:  http://localhost:5001/portal/page1
- You can see "Loading...." on blank window than the page is appears correctly. 
(btw wasm reloads in case if you try to navigate to non exists page also)

Do you have any idea how can I avoid this reload?
[TestBlazorApp.zip](https://github.com/dotnet/aspnetcore/files/4194406/TestBlazorApp.zip)

**Comment by javiercn** [comment] 2020-02-13 09:45
@istvanloth thanks for contacting us.

I believe that's by design. Changing the URL in the browser will always cause a full page refresh, that's the browser behavior. There's nothing Blazor can do to prevent that.

**Comment by istvanloth** [comment] 2020-02-13 10:49
Ouch. Thanks to answered it!
(To test the new functionality i just wrote the address to the address bar. With link or navigatto it's working without reload)

**Comment by javiercn** [comment] 2020-02-13 10:52
I'm closing the issue as there's nothing else for us to do here.

**Closed by javiercn** 2020-02-13 10:52 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor, blazor-wasm, question
