### ISSUE TITLE
GenerateStaticWebAssetEndpointsManifest - An Item with the same key has already been added

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#57992] opened 2024-09-20 17:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/GenerateStaticWebAssetEndpointsManifest-/10745916)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.11.3]
Updated to the Latest Visual Studio Version 17.12.0 Preview 2.0, Blazor WASM App that is still building as .net 8 no longer builds... 
Nothing changed other than updating to get .net 9 installed. 

I then performed a Full Repair using Visual Studio Installer for both installed versions
Version 17.12.0 Preview 2.0
Version 17.11.3

Application Builds and Runs on Version 17.11.3, but doesn't build on Preview 2 version.

Error:

```
ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAssetEndpointsManifest.Execute()
```

When I click to Show the error source. the following is shown
 
```
<GenerateStaticWebAssetEndpointsManifest
   Source="$(PackageId)"
   ManifestType="Build"
   Assets="@(StaticWebAsset)"
   Endpoints="@(StaticWebAssetEndpoint)"
   ManifestPath="$(StaticWebAssetEndpointsBuildManifestPath)">
 </GenerateStaticWebAssetEndpointsManifest>
```

I did double check and the Assets.targets file doesn't have a second header called GenerateStaticWebAssetEndpointsManifest
and I've never changed this file... 

---
#### Feedback Bot on 9/17/2024, 06:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by martincostello** [comment] 2024-09-20 18:06
Might be a duplicate of https://github.com/dotnet/aspnetcore/issues/57512.

**Closed** 2024-10-25 00:15 UTC
Labels: bug, Needs: Author Feedback, area-blazor, Status: No Recent Activity, Author: Migration Bot :robot:, feature-static-web-assets, Needs: Repro
