### ISSUE TITLE
Hotreload doesn't work on Blazor wasm (.NET6)

### ISSUE THREAD

**Issue by Alikhll** [dotnet/aspnetcore#38576] opened 2021-11-22 20:38 UTC
### Hotreload doesn't work on blazor wasm (.NET6 LTS)
I've created a brand new blazor wasm project using Visual Studio 2022 (Version 17.1.0 Preview 1.1) and couldn't get hotreload to work, HOWEVER it works perfectly fine on blazor server!

### To Reproduce
Windows 11
Brand new .NET6 blazor wasm project
and then run "dotnet watch"
as soon as something is changed it's gonna end up with this particular message and should be restarted manually!

```
watch : File changed: C:\Users\alikh\source\repos\BlazorApp1\BlazorApp1\Pages\Index.razor.
watch : No hot reload changes to apply.
```

**Comment by SteveSandersonMS** [comment] 2021-11-25 15:47
@pranavkm Can you suggest any diagnostic steps here? There's not much information to indicate what might be wrong.

**Comment by Alikhll** [comment] 2021-11-25 21:29
@SteveSandersonMS Please provide what exactly I'm meant to do, let me know and I'll be doing that ASAP :)
meanwhile I'll be looking for a way to find out potential logs and so on

**Comment by Alikhll** [comment] 2021-11-25 21:37
It's so bizarre actually, I just realized it works using this command "Dotnet watch --project ."
is it something particularly different in that way? I couldn't find it in official documentation, I just bumped into that one in some forums..

**Comment by Alikhll** [comment] 2021-11-25 22:09
However it won't be working using that certain trick for blazorwasm hosted with asp.net core :(

**Comment by Aquaritek** [comment] 2021-12-04 04:58
> Thanks for contacting us.
> 
> We're moving this issue to the `.NET 7 Planning` milestone for future evaluation / consideration. We would like to keep this around to collect more feedback, which can help us with prioritizing this work. We will re-evaluate this issue, during our next planning meeting(s). If we later determine, that the issue has no community involvement, or it's very rare and low-impact issue, we will close it - so that the team can focus on more important and high impact issues. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md).

Umm I'm going to raise a flag here because for me it extends to the hosting environment also (meaning no clients receive updates after changes are published) and I think it's related. Please see my comment on this same topic in another issue thread https://github.com/dotnet/aspnetcore/issues/38809#issuecomment-985967854

**Comment by szalapski** [comment] 2022-02-24 19:15
This seems not to be fixed in SDK 6.0.200--when I do `dotnet watch --project .` from the Server directory, wait for it to spin up and load the page, then change the text on the page, I still get:

```
watch : File changed: C:\...\MyComponent.razor.
watch : No hot reload changes to apply.
```

With --verbose, I get:

```
watch : File changed: C:\...\MyComponent.razor.
watch : No deltas modified. Applying changes to clear diagnostics.
watch : Received 1 from browser in [Count: 1, MessageType: Binary, EndOfMessage: True].
watch : No hot reload changes to apply.
watch : Hot reload change handled in 5902.7638ms.
```

Can anyone help?

**Comment by mkArtakMSFT** [comment] 2022-08-10 17:07
@tmat can you please look into this? This may already be fixed but wanted you to confirm.

**Comment by ChristopherHaws** [comment] 2022-09-07 06:12
This is happening to me also. Creating a new ASP.NET Core Hosted Web Assembly app and running `dotnet watch` from the `Server` directory.

**Comment by szalapski** [comment] 2022-09-16 03:23
After trying and re-trying this and reconsidering it each time, I found that when I first start `dotnet watch` it works for me for several iterations, rebuilding automatically and reloading my page, before eventually (5 or 20 minutes later) it stops working and I get the bogus "No hot reload changes to apply", when it won't rebuild even though it should.

What more is needed to troubleshoot this?

**Comment by MarcoMedrano** [comment] 2022-11-26 15:41
Does anyone find a solution?
I moved to .NET 7 November release , still happening. `dotnet watch` or `dotnet watch run` they work well when first editing a file, after that:
```shell
dotnet watch ⌚ File changed: ./Pages/Index.razor.
dotnet watch ⌚ No hot reload changes to apply.
```

**Comment by szalapski** [comment] 2023-02-08 22:55
See also https://github.com/dotnet/aspnetcore/issues/45519

**Comment by pedrinCjm** [comment] 2023-02-21 12:39
This worked for me (.net 6 and .net 7):

Install NuGet package: 
- Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
Add line in Startup.cs:
- services.AddControllersWithViews().AddRazorRuntimeCompilation();
Or in Program.cs:
- builder.Services.AddControllersWithViews().AddRazorRuntimeCompilation();

**Comment by pedrinCjm** [comment] 2023-02-21 12:39
This worked for me (.net 6 and .net 7):

- Install NuGet package: 
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
- Add line in Startup.cs:
services.AddControllersWithViews().AddRazorRuntimeCompilation();
- Or in Program.cs:
builder.Services.AddControllersWithViews().AddRazorRuntimeCompilation();

**Comment by szalapski** [comment] 2023-02-21 16:19
It didn't help me. I still get.
```
dotnet watch ⌚ File changed: .\Client\Pages\Index.razor.
dotnet watch ⌚ No deltas modified. Applying changes to clear diagnostics.
dotnet watch ⌚ Received 1 from browser in [Count: 1, MessageType: Binary, EndOfMessage: True].
dotnet watch ⌚ No hot reload changes to apply.
```

**Comment by tmat** [comment] 2023-09-25 23:37
We have made multiple changes to address `dotnet watch` reliability. If the issue still reproduces with the latest .NET 8 SDK preview, please reopen the issue with `--verbose` output, the project it reproes with and what changes are made to the files.

**Closed by tmat** 2023-09-25 23:37 UTC
Labels: area-blazor, feature-blazor-wasm, feature-hot-reload
