### ISSUE TITLE
Issue with Bootstrap Icon and DateTime Picker functionality in Blazor Server Application

### ISSUE THREAD

**Issue by sambhavyadav90** [dotnet/aspnetcore#55337] opened 2024-04-24 11:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In my Blazor Server Application, I've implemented a Bootstrap theme. However, there seems to be an issue with the functionality of the Icon and DateTime Picker on the website [url](http://debug.erp9i.com)

After 1-2 seconds of loading the page, the Icon and DateTime Picker functionality stops working. This behavior is consistent and needs investigation to identify the root cause.

### Expected Behavior

The Icon and DateTime Picker functionality should remain operational without interruption after loading the page.

### Steps To Reproduce

Navigate to http://debug.erp9i.com
Observe the behavior of the Icon and DateTime Picker functionality.
Notice that after 1-2 seconds, the functionality stops working.

### Exceptions (if any)

It appears that after loading the DOM in my Blazor application with a Bootstrap theme implemented, the functionality of the Feather icon is being removed.

Upon inspecting the behavior, it seems that after 1-2 seconds of loading the page at [application](http://debug.erp9i.com), the Feather icon functionality ceases to work. This behavior persists across different browsers, and no error messages are displayed in the console.

### .NET Version

8.0

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/11171479/8641f398-d78d-4d54-8495-c091de106789)

After 1-2 Seconds

![image](https://github.com/dotnet/aspnetcore/assets/11171479/5942a79f-c64c-4272-83a3-3dfe78f1135f)

**Comment by halter73** [comment] 2024-04-24 16:45
Closing as a duplicate of #55336.

**Closed by halter73** 2024-04-24 16:45 UTC
Labels: area-blazor
