### ISSUE TITLE
Output cache middleware throws when changing AllowCacheStorage on a later stage AND when AllowLocking = true. 

### ISSUE THREAD

**Issue by Gebov** [dotnet/aspnetcore#47253] opened 2023-03-16 14:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The OutputCacheMiddleware throws an error when there are multiple concurrent requests for the same resource that has not yet been cached. I have a scenario where I decide whether or not to cache a page based on a runtime condition. If the check fails I do not need to cache this resource. For this I am using a custom caching policy (inherits from IOutputCachePolicy) and in the CacheRequestAsync method I am setting AllowCacheStorage=true

and in the ServeResponseAsync method I am setting AllowCacheStorage=false.

The real world example is based on a more complex condition, but this way it reproduces as well.

**The current error I am receiving is when AllowLocking = true: in my CustomCachePolicy class**

``` c#
 System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.TryServeCachedResponseAsync(OutputCacheContext context, OutputCacheEntry cacheEntry, IReadOnlyList`1 policies)
         at Microsoft.AspNetCore.OutputCaching.OutputCacheMiddleware.InvokeAwaited(HttpContext httpContext, IReadOnlyList`1 policies)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
**When AllowLocking is set to false, the error does not reproduce**

### Expected Behavior

I would expect no errors to be thrown when AllowLocking is set to true. 

### Steps To Reproduce

Open [this repository](https://github.com/Gebov/aspnetcore-7-cache-issue/tree/gebov/concurrent-locking-issue) 
and switch to the branch **gebov/concurrent-locking-issue**
and run the test inside it (Test1). The test fails when AllowLocking is set to **true** and passes when AllowLocking is set to **false**.

### .NET Version

7.0.202

**Comment by BrennanConroy** [comment] 2023-03-17 15:33
Dupe of https://github.com/dotnet/aspnetcore/issues/46333?

**Comment by Gebov** [comment] 2023-03-19 05:09
@BrennanConroy I think yes. Will this be in the next release ? With 7.0.202 it was not working

**Comment by BrennanConroy** [comment] 2023-03-20 15:33
It will be in 7.0.5 next month.

P.S. the SDK version 7.0.202 has nothing to do with the runtime version.

**Comment by Gebov** [comment] 2023-04-12 06:22
Can confirm that 7.0.5 fixes the issue

**Comment by Gebov** [comment] 2023-04-12 13:20
For some reason my original problem was fixed, but now I keep hitting the other issue that was referenced. #46333

**Comment by mitchdenny** [comment] 2023-04-14 02:29
Hrm. I'm not confused ... I had a PR in for 8.0 that fixed an NRE here as well, but we ended up not backporting it to 7.0 - @sebastienros did your fix for another issue get backported which included a similar fix to what I made?

My fix for reference: https://github.com/dotnet/aspnetcore/pull/47392

Or is this a different NRE?

**Comment by Gebov** [comment] 2023-04-25 11:57
@mitchdenny I saw the msfbot close this. Shouldn't it reman open ?

**Comment by mitchdenny** [comment] 2023-04-27 05:02
I think this was closed because it was a duplicate by @BrennanConroy

**Closed** 2023-04-27 05:01 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Status: Resolved, feature-output-caching
