### ISSUE TITLE
Blazor exception thrown when visiting a non-existent url and then trying to interact with page when RenderMode="Server"

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#40056] opened 2022-02-08 07:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Exception is thrown after navigating to a non-existent page and then clicking on a nav link that's part of the main layout when the `RenderMode` is set to `Server`. Doesn't occur when the `RenderMode` is set to `ServerPreferred`.

Brower output:

blazor.server.js:1 [2022-02-08T06:59:11.892Z] Error: There was an error applying batch 6.
log @ blazor.server.js:1
processBatch @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
_invokeClientMethod @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
Tt.connection.onreceive @ blazor.server.js:1
o.onmessage @ blazor.server.js:1
blazor.server.js:1 [2022-02-08T06:59:11.931Z] Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---

### Expected Behavior

Should navigate without throwing any exceptions.

### Steps To Reproduce

1) Create a new Blazor Server App (VS 2022 Preview)
2) Change _Host.cshtml render mode to `<component type="typeof(App)" render-mode="Server" />`
3) Goto a non-existent link and see "Sorry, there's nothing at this address." message.
4) Click on a nav link in the menu on the left
5) Exception thrown

### Exceptions (if any)

Error: System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'insertBefore'))
 ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'insertBefore')
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

### .NET Version

6.0.101

### Anything else?

![image](https://user-images.githubusercontent.com/12207061/152939426-55ec4be6-b9dd-4a3b-a608-510921e204a7.png)

![image](https://user-images.githubusercontent.com/12207061/152939438-abc423fc-dead-400d-999e-9c7c8f054275.png)

**Comment by surayya-MS** [comment] 2022-12-22 17:01
Thanks for contacting us.
I followed the steps and couldn't reproduce the bug. Therefore closing this issue.

**Closed by surayya-MS** 2022-12-22 17:01 UTC
Labels: bug, area-blazor, triaged, Priority:2, blazor-server

**Comment by vflame** [comment] 2022-12-31 18:35
@surayya-MS can you please re-open?

**Comment by vflame** [comment] 2023-01-05 03:16
Turns out it was an extension I had for Chrome specifically that was mutating page title. Once I removed it, the issue stopped occurring.
