### ISSUE TITLE
Helix OSX - Playwright ERR_CERT_DATABASE_CHANGED failures Individual Auth

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#30825] opened 2021-03-11 00:13 UTC
IndividualAuth_Works tests are failing with the following on OSX, this seems like its generally an issue when the trust store is modified which causes Chrome to flush all the connections, we should investigate to see if we can avoid these exceptions

```
PlaywrightSharp.PlaywrightSharpException : net::ERR_CERT_DATABASE_CHANGED at http://localhost:63342/
=========================== logs ===========================
navigating to "http://localhost:63342/", waiting until "load"

  at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args, Boolean ignoreNullValues, JsonSerializerOptions serializerOptions, Boolean treatErrorPropertyAsError) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 186
   at PlaywrightSharp.Frame.GoToAsync(Boolean isPage, String url, Nullable`1 waitUntil, String referer, Nullable`1 timeout) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Frame.cs:line 761
   at Templates.Test.Helpers.AspNetProcess.VisitInBrowserAsync(IPage page) in /_/src/ProjectTemplates/Shared/AspNetProcess.cs:line 108
   at Templates.Test.BlazorServerTemplateTest.BlazorServerTemplateWorks_IndividualAuth(BrowserKind browserKind, Boolean useLocalDB) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorServerTemplateTest.cs:line 164
--- End of stack trace from previous location ---
```

**Comment by javiercn** [comment] 2021-03-11 16:58
I think I ran into this in my prototype, but there's an easy solution for it.

We create a cert every time we spin up a .NET project, we can switch to create a single https certificate and use that for all of our tests instead.

**Comment by TanayParikh** [comment] 2021-11-16 23:48
Re-opening this issue as it's still used to mark tests as quarantined.

- BlazorServerTemplateWorks_IndividualAuth
- BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB
- BlazorServerTemplateWorks_IndividualAuth

**Comment by SteveSandersonMS** [comment] 2021-11-18 13:11
@TanayParikh I see this has the `test-fixed` label but could you clarify which PR contained the fix? I'm unclear on how to know if it's been 30 days since this was fixed.

**Comment by TanayParikh** [comment] 2021-11-18 16:59
> which PR contained the fix

https://github.com/dotnet/aspnetcore/pull/31012

> I'm unclear on how to know if it's been 30 days since this was fixed.

This issue was closed out when the above PR was merged, but the underlying issues were never un-quarantined. Given it was merged in March, assuming all the tests have a consistent pass rate, we should be fine to un-quarantine now.

**Comment by TanayParikh** [comment] 2022-12-21 23:26
Closing out as dup of https://github.com/dotnet/aspnetcore/issues/38818

**Comment by TanayParikh** [comment] 2022-12-21 23:30
We need Helix enabled for the Playwright tests first before we resolve this issue (if this is still an issue): 

Depends on: https://github.com/dotnet/aspnetcore/issues/38818

**Comment by TanayParikh** [comment] 2023-02-01 00:40
> We need Helix enabled for the Playwright tests first before we resolve this issue (if this is still an issue):

We're running the tests specifically on the build agents for now due to issues with Helix compatibility. Backlogging this until we decide we'd like these tests running on helix.

**Comment by javiercn** [comment] 2023-02-06 12:30
For reference here: I believe the issue is that we generate a new HTTPS cert for each test and that causes issues on chrome. We can generate a single HTTPS cert at the beginning of the test run and that should get rid of these problems.

**Comment by mkArtakMSFT** [comment] 2024-02-20 17:27
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/46430

**Closed by mkArtakMSFT** 2024-02-20 17:27 UTC
Labels: test-failure, area-blazor, Priority:0, feature-playwright 🎭, Pillar: Technical Debt
