### ISSUE TITLE
Razor editor "Comment Selection" uses markup not C# comments in code section

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25357] opened 2020-08-28 17:04 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1165588/razor-editor-comment-selection-uses-markup-not-c-c.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
VS2019 version 16.8.0 Preview 2 with Razor Editor Preview enabled

Selecting a code section of a .razor file and selecting Ctrl-K-Ctrl-C (Edit / Advanced / Comment Selection) comments the Razor C# code using @* *@ comment syntax, not C# /* .. */ or // prefix syntax

---
#### Feedback Bot on 8/28/2020, 00:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2020-11-03 21:13
Duplicate of: https://github.com/dotnet/aspnetcore/issues/14320

**Closed by NTaylorMullen** 2020-11-03 21:13 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved, area-razor.tooling, cost: M, enhancement, feature-razor.vs
