### ISSUE TITLE
wasm/dotnet Integrity attribute invalid for my Blazor app on Github pages

### ISSUE THREAD

**Issue by chrisevans9629** [dotnet/aspnetcore#21560] opened 2020-05-07 02:00 UTC
### Describe the bug
[See the error on my website here](https://chrisevans9629.github.io/blazor/xt/)

I have embedded a blazor app in my jekyll site.  It runs perfectly locally, but when I publish it on github pages, I am getting this error:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://chrisevans9629.github.io/blazor/xt/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js' with computed SHA-256 integrity 'yVt8FYsTQDifOGsifIkmEXwe+7ML0jZ1dMi2xluiDXQ='. The resource has been blocked.
```
This is something that I think blazor generates when the page is ran.  this is what my page looks like that starts blazor:
```html
<script src="js/index.js"></script>
<app>Loading...</app>
Built with <3 using Blazor
<script src="_framework/blazor.webassembly.js"></script>
```

This is what the page looks like on github pages:
```html

<script src="js/index.js"></script>

<app>Loading...</app>
<p>Built with &lt;3 using Blazor
<script src="_framework/blazor.webassembly.js"></script></p>		
	
<script type="text/javascript">var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;</script><script src="_framework/wasm/dotnet.3.2.0-rc1.20222.2.js" defer="" integrity="sha256-iZCHkFXJWYNxCUFwhj+4oqR4fkEJc5YGjfTTvdIuX84=" crossorigin="anonymous"></script></body>
```

Why is this error happening and how can I fix this?  I have not been able to find any solution.  I have tried rebuilding and removing the integrity attribute, but it still did not work.

### To Reproduce

1. create a blazor app
2. host it on github pages
3. open the blazor page on **Chrome** or **Chromium edge**.  Edge works for some reason.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

This is my project setup

```
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0-rc1.20223.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0-rc1.20223.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0-rc1.20223.4" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.0-rc1.20217.1" />
  </ItemGroup>

```

**Comment by javiercn** [comment] 2020-05-07 10:23
@chrisevans9629 thanks for contacting us.

This is likely because publishing to gh is changing the end line of your files. You need to add a `.gitattributes` file to you project so that the line endings don't change when published.

Something like 
```
* binary
```
within your publish folder

**Comment by javiercn** [comment] 2020-05-07 11:38
See https://github.com/dotnet/aspnetcore/issues/19796 for a more complete discussion.

I'm closing this issue as a dupe of https://github.com/dotnet/aspnetcore/issues/19796

**Closed by javiercn** 2020-05-07 11:38 UTC
Labels: area-blazor, blazor-wasm
