### ISSUE TITLE
Use ValueTuple element names in minimal route handlers

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#40510] opened 2022-03-02 23:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Take the following minimal route handler:

```C#
app.MapPut("/todos/{id}", async ((int Id, string Title, bool IsComplete) inputTodo, TodoDb db) =>
```

Today, to upload an inputTodoo to this endpoint, you would need a JSON request body like the following because we don't look for any [TupleElementNameAttributes](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.tupleelementnamesattribute?view=net-6.0) on the parameter:

```json
{
    "Item1": 1,
    "Item2": "Support named items in ValueTuples",
    "Item3": false
}
```

### Describe the solution you'd like

If we took the names of the ValueTuple elements into account, the request body could look like you'd expect:

```json
{
    "Id": 1,
    "Title": "Support named items in ValueTuples",
    "IsComplete": false
}
```

### Additional context

We have the same problem with ValueTuples returned from minimal route handlers. Today, the following would be serialized using `Item1`, `Item2` and `Item3` as the property values instead of the specified names.

```C#
app.MapGet("/todos/{id}", async (int Id, string Title, bool IsComplete)  (int id, TodoDb db) =>
```

**Comment by DamianEdwards** [comment] 2022-03-03 01:35
We'd also need to consider what the generated `ApiExplorer` schema looks like, i.e. it should match what we'd deserialize from/serialize to.

This is an enticing idea when one considers it as a way to enable inline definition of DTOs. This is useful when wanting to explicitly control the shape of an API body argument to prevent mass-assignment/over-binding to the concrete type, e.g.

``` c#
app.MapPost("/todos", async ((string Title, bool IsComplete) newTodo, TodoDb db) =>
{
    // We don't want to bind to Id or CreatedOn when creating new todos
    var todo = new Todo { Title = newTodo.Title, IsComplete = newTodo.IsComplete, CreatedOn = DateTimeOffset.Now };

    db.Todos.Add(todo);
    await db.SaveChangesAsync();

    return Results.Created($"/todos/{todo.Id}", todo);
});

public class Todo
{
    public int Id { get; set; }
    public string? Title { get; set; }
    public bool IsComplete { get; set; }
    public DateTimeOffset CreatedOn? { get; set; }
}
```

**Comment by davidfowl** [comment] 2022-03-03 02:55
This is a very cool idea but I have concerns about implementing a custom serializer for tuples. There are also lots of challenges around nested tuples and how that would interact with the serializer. 

This to me feels like it should work everywhere, not just minimal APIs (like `IAsyncEnumerable<T>`). The problem is that the schema for the lives with the methods and not with the type. This means that we need to somehow feed gather this information into a single unit the JSON serializer can understand. This gets more complex with nested tuples see [this](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpHqHECWAdgC7oBiA9vQBROU0C2ANOq9ehd140ADtzboAjgEp09GQC8ZADymkieYiSSbNANwCGAJx4AzbgH0ZAXnRKA3Gp1QA7OhN2tmgL7JkPpEA=)  and [this](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEDMACdAmbAYWwG8BYAKG2tx3QBZsBZACgEpTKbvsA3CAE7YANhDDAEEbAF5sLFrAAu2CHDlLswNRoDGbDorUKYysNpPYAXhwAeHaQD4uPaiW7OX3Y8svnT9uQBGODw2AG53Kk9udAB2OV85M2wwfTCPHgBfdKjqTMpMoA=) for an example. Assuming we could figure out which names are paired with with which nested tuples, the only reasonable way to do this would be a custom `JsonConverter`. That would allow us to not lose the benefits of the serializer (recursion depth checks, nested serialization etc etc). This would mean that we'd need to allocate a `JsonSerializationOptions` per callsite that captured the required information to handle tuples.

JsonConverters don't give you access to the member being deserialized, just the type. This makes that more challenging.

Or we could say it only works for top level properties and nested isn't supported...(no `VT<T0, VT<T1>>`)


I'd like to hear some thoughts from @layomia and @eiriktsarpalis.

**Comment by eiriktsarpalis** [comment] 2022-03-03 12:47
I don't see how this might be possible to solve in the general case, for the reasons @davidfowl already mentioned. I'm also not sure how a custom `JsonConverter` might be able to work with ambiguity such as `((int foo, int bar), (int baz, int qux))`. As far as the STJ converter infrastructure is concerned, both nested values are of type `ValueTuple<int, int>` and as such they will be dispatched to the same converter instance for serialization without any contextual information.

**Comment by davidfowl** [comment] 2022-03-04 01:46
@eiriktsarpalis yep I came to the same conclusion.

**Comment by zyofeng** [comment] 2022-12-17 21:09
This would work quite nicely with CQRS pattern by splitting up the request DTOs instead of having to pollute them with Parameter Binding attributes or creating new ones

`
var group = app.MapGroup("/accounts")
            .WithTags("Accounts")
            .RequireAuthorization();

        group.MapPost("{accountNumber}/transactions",
                (ISender sender, string accountNumber,
                    (DateOnly From, DateOnly To, int CurrentPage, int PageSize) body) => sender.Send(
                    new GetTransactionsQuery
                    {
                        AccountNumber = accountNumber,
                        PageSize = body.PageSize,
                        From = body.From,
                        To = body.To,
                        CurrentPage = body.CurrentPage
                    }))
            .WithName("Transactions");`

**Comment by davidfowl** [comment] 2022-12-18 04:59
I'm not sure why this issue is still open. We should close this out. Tuples are unsuitable for this.

@zyofeng you can use [AsParameters](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0#parameter-binding-for-argument-lists-with-asparameters) for this usecase:

```C#
group.MapPost("{accountNumber}/transactions",
    ([AsParameters]RequestDto dto) => dto.Sender.Send(
        new GetTransactionsQuery
        {
            AccountNumber = dto.AccountNumber,
            PageSize = dto.Body.PageSize,
            From = dto.Body.From,
            To = dto.Body.To,
            CurrentPage = dto.Body.CurrentPage
        }))
    .WithName("Transactions");

record struct RequestBody(DateOnly From, DateOnly To, int CurrentPage, int PageSize); 
record struct RequestDto(ISender Sender, string AccountNumber, RequestBody Body);
```

**Closed by davidfowl** 2022-12-18 04:59 UTC
Labels: Needs: Design, Priority:3, feature-minimal-actions, area-web-frameworks

**Comment by zyofeng** [comment] 2022-12-18 06:57
Thanks @davidfowl.
That's what I am doing atm, 

```csharp
        group.MapPost("{accountNumber}/transactions",
                (ISender sender, string accountNumber, GetTransactionsRequest body) => sender.Send(
                    new GetTransactionsQuery
                    {
                        AccountNumber = accountNumber,
                        PageSize = body.PageSize,
                        From = body.From,
                        To = body.To,
                        CurrentPage = body.CurrentPage
                    }))
            .WithName("Transactions");

        return app;
    }
    public record GetTransactionsRequest(DateOnly From, DateOnly To, int CurrentPage, int PageSize = 20);

```

Although I am kinda hoping I don't have to create another request dto. Cheers
