### ISSUE TITLE
Blazor Server-side and Named Anchors

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#23476] opened 2020-06-29 17:10 UTC
I created a test project with the following in Index.razor. Clicking the link does not honor the named anchor and scroll to the `<div>`. Adding the same code to a Razor Pages app works as expected. Are named anchors supported at this time?

in Index.razor
```razor
<a href="#anchor-link">Named Anchor Link</a>

@* a lot of content *@

<div id="anchor-link">Named Anchor Div</div>
```

**Comment by mkArtakMSFT** [comment] 2020-06-30 16:45
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by mkArtakMSFT** [comment] 2020-06-30 16:46
Thanks for contacting us. This is a dupe of #8393

**Closed by mkArtakMSFT** 2020-06-30 16:46 UTC
Labels: area-blazor, investigate
