### ISSUE TITLE
Quarantined test: InteropTests.InteropTests.InteropTestCase(name: "ping_pong")

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#22101] opened 2020-05-21 21:34 UTC
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=655956&view=ms.vss-test-web.build-test-results-tab&runId=20358470&resultId=100809&paneView=debug

Error message
System.TimeoutException : The operation at /_/src/Grpc/test/InteropTests/InteropTests.cs:40 timed out after reaching the limit of 30000ms.

Stack trace
```
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Testing/src/TaskExtensions.cs:line 59
   at InteropTests.InteropTests.InteropTestCase(String name) in /_/src/Grpc/test/InteropTests/InteropTests.cs:line 45
--- End of stack trace from previous location ---
```

**Comment by BrennanConroy** [comment] 2020-06-15 21:49
Current hypothesis is there was an HttpClient change that is causing failures.

**Comment by JunTaoLuo** [comment] 2020-06-17 00:29
@JamesNK it seems like you are onto something here. Specifically, we ingested the change https://github.com/dotnet/runtime/commit/5b112c310f9ea28ca7a06941787f2bea7eb315eb#diff-441a1252f436e5e5b3ad0cc10b2256ef in our commit https://github.com/dotnet/aspnetcore/commit/b37ebf51e339bb6f24c94385e3e126447f7661e3#diff-8b8f08ffbf7b863fb3700c1718eeb4cb on May 21. If most of the failures are seen after that change, then it could be possible that underlying changes in System.Net.Http could be the cause.

**Comment by JamesNK** [comment] 2020-06-17 00:50
@stephentoub I think changes [to SocketsHttpHandler for HTTP/2 performance](https://github.com/dotnet/runtime/pull/36246) has caused some of our gRPC interop tests to become flaky.

May 16 - PR is merged in runtime
May 21 - aspnetcore updated to a new runtime with changes from the PR
May 22 - Flaky gRPC interop tests are noticed and quarantined.

The tests that are failing can be found here - https://github.com/dotnet/aspnetcore/blob/master/src/Grpc/test/InteropTests/InteropTests.cs

Only some of them became flaky:
* LargeUnary
* ClientStreaming
* PingPong
* CustomMetadata
* ClientCompressedUnary
* ServerCompressedUnary

The common attribute shared between the flaky tests is they send a large request body.

Analytics about one of the flaky tests - https://dev.azure.com/dnceng/internal/_test/analytics?definitionId=787&contextType=build

Error from the test. The logs in the error message indicate the server starting to read the message from the client, and then timing out waiting on the message data from the client.

```
[xUnit.net 00:00:31.62]     InteropTests.InteropTests.LargeUnary [FAIL]
[xUnit.net 00:00:31.62]       System.InvalidOperationException : Error while running client process.
[xUnit.net 00:00:31.62]       
[xUnit.net 00:00:31.62]       Server ready: True
[xUnit.net 00:00:31.62]       Client ready: True
[xUnit.net 00:00:31.62]       
[xUnit.net 00:00:31.62]       Server process output:
[xUnit.net 00:00:31.62]       ======================================
[xUnit.net 00:00:31.62]       dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
[xUnit.net 00:00:31.62]             Hosting starting
[xUnit.net 00:00:31.62]       Enabling connection encryption: False
[xUnit.net 00:00:31.62]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
[xUnit.net 00:00:31.62]             Discovering gRPC methods for Grpc.Testing.TestServiceImpl.
[xUnit.net 00:00:31.62]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.62]             Added gRPC method 'EmptyCall' to service 'grpc.testing.TestService'. Method type: 'Unary', route pattern: '/grpc.testing.TestService/EmptyCall'.
[xUnit.net 00:00:31.62]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.62]             Added gRPC method 'UnaryCall' to service 'grpc.testing.TestService'. Method type: 'Unary', route pattern: '/grpc.testing.TestService/UnaryCall'.
[xUnit.net 00:00:31.62]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.62]             Added gRPC method 'CacheableUnaryCall' to service 'grpc.testing.TestService'. Method type: 'Unary', route pattern: '/grpc.testing.TestService/CacheableUnaryCall'.
[xUnit.net 00:00:31.63]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.63]             Added gRPC method 'StreamingOutputCall' to service 'grpc.testing.TestService'. Method type: 'ServerStreaming', route pattern: '/grpc.testing.TestService/StreamingOutputCall'.
[xUnit.net 00:00:31.63]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.63]             Added gRPC method 'StreamingInputCall' to service 'grpc.testing.TestService'. Method type: 'ClientStreaming', route pattern: '/grpc.testing.TestService/StreamingInputCall'.
[xUnit.net 00:00:31.63]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.63]             Added gRPC method 'FullDuplexCall' to service 'grpc.testing.TestService'. Method type: 'DuplexStreaming', route pattern: '/grpc.testing.TestService/FullDuplexCall'.
[xUnit.net 00:00:31.63]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.63]             Added gRPC method 'HalfDuplexCall' to service 'grpc.testing.TestService'. Method type: 'DuplexStreaming', route pattern: '/grpc.testing.TestService/HalfDuplexCall'.
[xUnit.net 00:00:31.63]       dbug: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
[xUnit.net 00:00:31.63]             Added gRPC method 'UnimplementedCall' to service 'grpc.testing.TestService'. Method type: 'Unary', route pattern: '/grpc.testing.TestService/UnimplementedCall'.
[xUnit.net 00:00:31.63]       [40m[32minfo: Microsoft.Hosting.Lifetime[0]
[xUnit.net 00:00:31.63]             Now listening on: http://[::]:65011
[xUnit.net 00:00:31.63]       Application started.
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
[xUnit.net 00:00:31.63]             Loaded hosting startup assembly InteropWebsite
[xUnit.net 00:00:31.63]       [40m[32minfo: Microsoft.Hosting.Lifetime[0]
[xUnit.net 00:00:31.63]             Application started. Press Ctrl+C to shut down.
[xUnit.net 00:00:31.63]       [40m[32minfo: Microsoft.Hosting.Lifetime[0]
[xUnit.net 00:00:31.63]             Hosting environment: Production
[xUnit.net 00:00:31.63]       [40m[32minfo: Microsoft.Hosting.Lifetime[0]
[xUnit.net 00:00:31.63]             Content root path: /private/tmp/helix/working/ABBF091E/w/C0630A3A/e
[xUnit.net 00:00:31.63]       dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
[xUnit.net 00:00:31.63]             Hosting started
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Server.Kestrel[39]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" accepted.
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Server.Kestrel[1]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" started.
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received HEADERS frame for stream ID 1 with length 189 and flags END_HEADERS
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received DATA frame for stream ID 1 with length 5 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received DATA frame for stream ID 1 with length 16384 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received DATA frame for stream ID 1 with length 16384 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received DATA frame for stream ID 1 with length 16384 and flags NONE
[xUnit.net 00:00:31.63]       [40m[32minfo: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[xUnit.net 00:00:31.63]             Request starting HTTP/2 POST http://localhost:65011/grpc.testing.TestService/UnaryCall application/grpc -
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[0]
[xUnit.net 00:00:31.63]             Wildcard detected, all requests with hosts will be allowed.
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware[2]
[xUnit.net 00:00:31.63]             All hosts are allowed.
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
[xUnit.net 00:00:31.63]             3 candidate(s) found for the request path '/grpc.testing.TestService/UnaryCall'
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
[xUnit.net 00:00:31.63]             Endpoint 'gRPC - /grpc.testing.TestService/UnaryCall' with route pattern '/grpc.testing.TestService/UnaryCall' is valid for the request path '/grpc.testing.TestService/UnaryCall'
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
[xUnit.net 00:00:31.63]             Endpoint 'gRPC - Unimplemented method for grpc.testing.TestService' with route pattern 'grpc.testing.TestService/{unimplementedMethod}' is valid for the request path '/grpc.testing.TestService/UnaryCall'
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
[xUnit.net 00:00:31.63]             Endpoint 'gRPC - Unimplemented service' with route pattern '{unimplementedService}/{unimplementedMethod}' is valid for the request path '/grpc.testing.TestService/UnaryCall'
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
[xUnit.net 00:00:31.63]             Request matched endpoint 'gRPC - /grpc.testing.TestService/UnaryCall'
[xUnit.net 00:00:31.63]       [40m[32minfo: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
[xUnit.net 00:00:31.63]             Executing endpoint 'gRPC - /grpc.testing.TestService/UnaryCall'
[xUnit.net 00:00:31.63]       dbug: Grpc.AspNetCore.Server.ServerCallHandler[10]
[xUnit.net 00:00:31.63]             Reading message.
[xUnit.net 00:00:31.63]       dbug: Microsoft.AspNetCore.Server.Kestrel[25]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH", Request id "0HM0I771TDHUH:00000001": started reading request body.
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" sending WINDOW_UPDATE frame for stream ID 1 with length 4 and flags 0x0
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received DATA frame for stream ID 1 with length 16378 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received DATA frame for stream ID 1 with length 16384 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" received DATA frame for stream ID 1 with length 16384 and flags NONE
[xUnit.net 00:00:31.63]       trce: Microsoft.AspNetCore.Server.Kestrel[37]
[xUnit.net 00:00:31.63]             Connection id "0HM0I771TDHUH" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
[xUnit.net 00:00:31.63]       
[xUnit.net 00:00:31.63]       ======================================
[xUnit.net 00:00:31.63]       
[xUnit.net 00:00:31.63]       Client process output:
[xUnit.net 00:00:31.63]       ======================================
[xUnit.net 00:00:31.63]       Application started.
[xUnit.net 00:00:31.63]       Use TLS: False
[xUnit.net 00:00:31.63]       Use Test CA: False
[xUnit.net 00:00:31.63]       Client type: httpclient
[xUnit.net 00:00:31.63]       Server host: localhost
[xUnit.net 00:00:31.63]       Server port: 65011
[xUnit.net 00:00:31.63]       running large_unary
[xUnit.net 00:00:31.63]       dbug: Grpc.Net.Client.Internal.GrpcCall[1]
[xUnit.net 00:00:31.63]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:31.63]             Starting gRPC call. Method type: 'Unary', URI: 'http://localhost:65011/grpc.testing.TestService/UnaryCall'.
[xUnit.net 00:00:31.63]       dbug: Grpc.Net.Client.Internal.GrpcCall[18]
[xUnit.net 00:00:31.63]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:31.63]             Sending message.
[xUnit.net 00:00:31.63]       trce: Grpc.Net.Client.Internal.GrpcCall[21]
[xUnit.net 00:00:31.63]             => GrpcMethodType:Unary GrpcUri:/grpc.testing.TestService/UnaryCall
[xUnit.net 00:00:31.63]             Serialized 'Grpc.Testing.SimpleRequest' to 271840 byte message.
```

**Closed** 2020-06-18 13:13 UTC
Labels: area-grpc, test-investigation
