### ISSUE TITLE
IHttpContextAccessor is null

### ISSUE THREAD

**Issue by IglooGary** [dotnet/aspnetcore#53143] opened 2024-01-03 14:27 UTC
When creating a brand new ASP.NET Core Web App project in Visual Studio 2022 with .NET 8.0 (Long Term Support) and adding the following code, the result of httpContextAccessor is HttpContext = null:

**Program.cs**

```
using Test.Extensions;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddServices();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();
```

**ServiceExtentions.cs**

```
namespace Test.Extensions;

public static class ServiceExtentions
{
    public static void AddServices(this IServiceCollection serviceCollection)
    {
        serviceCollection.AddControllersWithViews();
        serviceCollection.AddHttpContextAccessor();
        //serviceCollection.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        
        var serviceProvider = serviceCollection.BuildServiceProvider();

        var httpContextAccessor = serviceProvider.GetService<IHttpContextAccessor>();
        
        StringExtensions.Initialize(httpContextAccessor);
    }
}
```

**StringExtensions.cs**

```
namespace Test.Extensions;

public static class StringExtensions
{
    private static IHttpContextAccessor? _httpContextAccessor;

    public static void Initialize(IHttpContextAccessor? httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    private static string GetAbsoluteUri()
    {
        var request = _httpContextAccessor?.HttpContext?.Request;

        var uriBuilder = new UriBuilder
        {
            Scheme = request?.Scheme,
            Host = request?.Host.Host,
            Path = request?.Path.ToString(),
            Query = request?.QueryString.ToString()
        };

        return uriBuilder.Uri.ToString();
    }
}
```

**Comment by martincostello** [comment] 2024-01-04 18:20
How is the `GetAbsoluteUri()` method called? It doesn't appear to be used anywhere in the code you've provided.

`HttpContextAccessor.HttpContext` will always be null unless it's accessed on a thread that's processing an incoming HTTP request.

**Comment by IglooGary** [comment] 2024-01-04 18:51
If that is by design then that is fair enough, however the same code works in a .NET 6 project.

I have noticed some other issues re the IHttpContextAccessor and Primary Constructors, in some cases, the IHttpContextAccessor in some cases is available and others null.

The work around is just to create a typical public Constructor and then instantiate typical private readonly properties.

In all instances where IHttpContextAccessor is consumed, and all related Interfaces are registered post registration of IHttpContextAccessor and some Primary Constructors work, some result in null instances irrespective of Lifecycle, whether Transient, Scoped, etc

**Comment by martincostello** [comment] 2024-01-04 19:25
Maybe I misunderstood your issue. I thought you were saying that the `HttpContext` on the property was null, but the `HttpContextAccessor` itself. But also for it to work properly, it needs to be the same one ASP.NET Core itself uses when it processes requests. If you're building the service provider twice then the one you get might not be the same one so then it would still not work properly.

I think the problem with your design here is you're trying to stash a service into a static class field and use it indefinitely, rather than access it as part of another non-static service also retrieved from IoC during request processing. Instead you want to be passing it in in some way from where you're using them from:

```csharp
string url = "/slug?foo=bar".AbsoluteUrl(HttpContext);
```

I'm just guessing here based on the code provided as there's no example of how your StringExtensions are being used.

**Comment by IglooGary** [comment] 2024-01-04 19:58
The design was not of my doing, it was merely an observation, that code which worked in .NET 6, no longer works in .NET 8.

I provided the bare minimum of code to reproduce, as I said earlier, if this is by design, I have no issues with this matter being closed.

The .NET 8 solution I am working on has been refactored accordingly, there are still issues with IHttpContextAccessor.

I have tried various approaches based on Microsoft literature and certain approaches do not work in certain conditions where Primary Constructors are concerned.

**Comment by amcasey** [comment] 2024-01-18 00:16
@IglooGary Thanks for the detailed repro!  A few questions:

1. I think you're saying that `httpContextAccessor` is null when the `StringExtensions.Initialize(httpContextAccessor)` call is made, is that correct? If not, can you please be more specific about what you expect to happen or not happen when that code is run?
2. What do you mean when you say "primary constructor"?  It doesn't seem to be the new C# [language feature](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors).
3. You mentioned that the problem was present in 8.0, but not in 6.0.  Did you have a chance to test 7.0?

**Comment by MarkMilfordMe** [comment] 2024-03-31 05:37
We are experiencing exactly the same issue moving from .NET 6 to .NET 8 that IHttpContextAccessor is null when on a Azure Function HTTP call, previously we used this in .NET 6 without issue.

Do we have any eta on fix given Microsoft terminating support for .NET 6 in November?

**Comment by davidfowl** [comment] 2024-03-31 07:29
This is a usually a symptom. It's null because there's code using the IHttpContextAccessor when it's out of scope (request has ended or maybe some code ran outside of the request scope and it now fails).

@MarkMilfordMe if the IHttpContextAccessor if null in an isolated function, I'd recommend letting the team know here https://github.com/Azure/azure-functions-dotnet-worker.

**Comment by MarkMilfordMe** [comment] 2024-03-31 08:22
> This is a usually a symptom. It's null because there's code using the IHttpContextAccessor when it's out of scope (request has ended or maybe some code ran outside of the request scope and it now fails).
> 
> @MarkMilfordMe if the IHttpContextAccessor if null in an isolated function, I'd recommend letting the team know here https://github.com/Azure/azure-functions-dotnet-worker.

Thanks @davidfowl I've created a demonstration of it working in .NET6 and failing in .NET 8
https://github.com/MarkMilfordMe/AzureFunctionsHttpContextorIssue

Will raise on Azure Functions repo referencing here

**Comment by amcasey** [comment] 2024-04-02 21:05
Thanks for the repro!  After setting `"FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"` in launchSettings.json, I was able to repro the NRE.  Since the 6.0 and 8.0 projects weren't quite the same, I downgraded the 8.0 project to 6.0 and the saw the same NRE with that configuration.  This (and David's comment above) make me think it's not a regression in aspnetcore.  Since you're tracking your issue on the Azure Functions repo and there was no response from the OP, I'm going to close this for now.  Please feel free to file a new issue if the Azure Functions investigation reveals something aspnetcore needs to look at.  Thanks!

**Closed by amcasey** 2024-04-02 21:05 UTC
Labels: Needs: Attention :wave:, area-networking
