### ISSUE TITLE
Missing completions when defining field member in @code block

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#22747] opened 2020-06-09 23:40 UTC
I'm not getting completions when adding a field member in my `@code` block.

![3EMIU4AGNO](https://user-images.githubusercontent.com/1874516/84211234-b8fe8080-aa6f-11ea-92a0-98f13933a983.gif)

Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.7.0 Preview 3.0 [30208.133.master]
VisualStudio.16.IntPreview/16.7.0-pre.3.0+30208.133.master
Microsoft .NET Framework
Version 4.8.03752
**Experimental Razor tooling enabled**

**Comment by danroth27** [comment] 2020-06-09 23:46
For comparison, here the experience with VS 16.6:

![akJvmjIZK0](https://user-images.githubusercontent.com/1874516/84211661-b18ba700-aa70-11ea-8e2f-4873c0f36dd1.gif)

**Comment by NTaylorMullen** [comment] 2020-06-11 23:23
Found that this was a duplicate of: https://github.com/dotnet/aspnetcore/issues/22837

After working around the above bug:
![SVRhA40v15](https://user-images.githubusercontent.com/2008729/84448509-baf74980-abff-11ea-9dcc-058b90ddc6d4.gif)

**Closed by NTaylorMullen** 2020-06-11 23:23 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, bug
