### ISSUE TITLE
Identitybuilder Improve

### ISSUE THREAD

**Issue by HossienMehdikhah** [dotnet/aspnetcore#23705] opened 2020-07-06 16:52 UTC
Hi. i use aspcore.identity to create identity system
i think is good to improve identitybuilder.

`public class UserManagement<TUser> : UserManager<TUser> where TUser : IdentityUser`

i create UserManagment that add some feature to UserManager.
also i have variety user role that each of them have  business logic.

`public class AdminManagement : UserManagement<AdminSet>`

AdminManagment driven from my UserManagment<Admin>.

my problem is when i configure my class in startup that way
i get error

System.InvalidOperationException: 'Type AdminManagement must derive from UserManager<MyIdentityUser>.'

`services.AddIdentity<MyIdentityUser, IdentityRole>(options =>
{
options.SignIn.RequireConfirmedEmail = true;
}).AddEntityFrameworkStores<Context>()
.AddDefaultTokenProviders()
.AddUserManager<AdminManagement>()
.AddUserStore<AdminStore>();
`
MyidentityUser driven from IdentityUser.

that problem is confilect myIdentity and Admin becuse i define User type in services.AddIdentity<MyIdentityUser, IdentityRole>(); to Myidentity But AdminManagment's Usertype is Admin.

**Comment by blowdart** [comment] 2020-07-15 22:07
We really unsure what you're trying to do here, so we don't know what we need to improve. Could you expand on it please?

**Comment by HossienMehdikhah** [comment] 2020-07-18 05:39
@blowdart  my system have three  type user admin, owner, athlete and each one have own create or some other process. for example create of admin is deference with owner so i have to create admin management and owner management and ..
problem is begin when i want register this. identity not support multi user management  class. 
i solve this problem with extension method but i think it better to commet to aspcore

**Comment by blowdart** [comment] 2020-07-19 13:19
This is really outside of how we expect identity to be used, we don't do inheritance of users like this. User classes are generally POCOs, nothing more, with user types being distinguished by claims, not an entire class, so this isn't something we would make any changes for I'm afraid.

Closing as by design.

**Closed by blowdart** 2020-07-19 13:19 UTC
Labels: area-identity

**Comment by HossienMehdikhah** [comment] 2020-07-20 09:09
@blowdart  thanks for response. 
claims is for authorization. i want that if when a owner signin send confirme email but if admin signin dont send email .
i think its better to put this process in own usermanger like ownermanager but identity dont support it. i make it with some change in identitybuilder. 
so if you say you cant  provide it accordengly by its design so what do you advice me? how way is better to impliment it?
