### ISSUE TITLE
[.NET 6] Backport the GenerateMvcTestManifestTask fix

### ISSUE THREAD

**Issue by Hammer-NL** [dotnet/aspnetcore#48189] opened 2023-05-11 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since bug #42966 was only fixed in it's NET7 version, it is preventing us from updating `Microsoft.AspNetCore.Mvc.Testing` to it's NET6 version.

We don't want to upgrade to NET7 yet, since we need to stay on an LTS version.

Can this fix be backported to NET6 please?

The bug is described here: https://github.com/dotnet/aspnetcore/issues/42966
and it's NET7 fix is here: https://github.com/dotnet/aspnetcore/pull/43329

### Expected Behavior

GenerateMvcTestManifestTask should not be run if IsPublishable == false

### .NET Version

net6.0

**Comment by Tratcher** [comment] 2023-05-11 15:25
@Hammer-NL does the workaround provided in the linked issue work for you? We only backport fixes that are high impact and hard to work around.

**Comment by Hammer-NL** [comment] 2023-05-12 09:42
No, we have tried the workaround extensively, and we did not manage to get it to work.

**Comment by Tratcher** [comment] 2023-05-12 15:29
@captainsafia ?

**Comment by captainsafia** [comment] 2023-05-12 15:53
I'm comfortable backporting this to net6.0. It's a fairly low-risk and localized change.

But first, I'm interested as to why the workaround didn't work for you. The workaround works by creating a publish directory to appease the requirements of the `GenerateMvcTestManifestTask` to address the specific exception in the issue you referenced. Were you getting a _different_ exception than what was described in the issue you linked after applying the workaround?

**Comment by Hammer-NL** [comment] 2023-05-20 14:05
@captainsafia Unfortunately I can't answer that question properly, but let me tell you what I do know.

In our Visual Studio solution, with 20+ projects, we have 3 test projects that were affected by this issue, so I applied the workaround to all 3 of them. This indeed fixed the issue in our local builds, however, our DevOps server builds continued to fail due to what seemed to be related to the order in which those three projects were build. If I remember correctly, it kept complaining about some directory not existing. We played around with making those projects depend on each other, or on certain other projects, in order to force a certain build order, but we couldn't make the DevOps server build work.

As a result, we're now using the NET5 version of this library, but we'd like to use the NET6 version. Our company policy does not allow us to use the NET7 version since that is not an LTS version.

**Comment by captainsafia** [comment] 2023-05-22 15:17
@Hammer-NL I see. There's a chance that if the target for publishing is built in to the testing targets that the issue might not reproduce in your CI environment. You've confirmed that the workaround does address the issue in the local environment, which is a good indicator.

Anyways, as mentioned previously, I'm OK backporting this to 6.0 given the nature of the bug fix. Due to keep me up-to-date on whether or not the issue is resolved in your CI environment once the backport goes through.

**Comment by Hammer-NL** [comment] 2023-05-23 19:47
@captainsafia Thanks a lot! I will let you know if the fix works on our DevOps build servers as soon as the v6 version comes available.

**Comment by captainsafia** [comment] 2023-06-27 01:56
@Hammer-NL Have you had the chance to test this in 6.0.19?

**Comment by Hammer-NL** [comment] 2023-06-28 13:21
Hi @captainsafia, thanks for the trigger. I checked last week, but 6.0.19 was not yet released.
I've just tested with Microsoft.AspNetCore.Mvc.Testing 6.0.19 and it seems our DevOps server build works fine now!
Thank you very much for your efforts, much appreciated.

**Closed** 2023-06-29 15:21 UTC
Labels: area-mvc, Needs: Attention :wave:, feature-mvc-testing
