### ISSUE TITLE
SignalR Hub OnDisconnectedAsync method is invoked  [proposed Label] area-signalr

### ISSUE THREAD

**Issue by PankajkJhaRepo** [dotnet/aspnetcore#28458] opened 2020-12-06 12:08 UTC
There seems to be some dependency issue with System.Text.Json version 5.0.0 and SignalR (Microsoft.AspNetCore.SignalR.Core, Version=3.1.0.0,) .
I created a SignalR application (https://github.com/PankajkJhaRepo/SignalR.git) which works fine when nuget package System.Text.Json version 5.0.0 is uninstalled from the project but as soon as we add this package to the project , SignalR client connection is disconnected. 
I have uploaded sample project here https://github.com/PankajkJhaRepo/SignalR.git where System.Text.Json is added to the project and hence when Send button is clicked from client, OnDisconnectedAsync  method of Hub is called and client connection is disconnected. 
In order to to fix the issue we just need to remove System.Text.Json package from the project, but it would cause problem for a project which would require SignalR and System.Text.Json.

**Comment by BrennanConroy** [comment] 2020-12-06 17:09
Dupe of https://github.com/dotnet/aspnetcore/issues/27519

**Comment by PankajkJhaRepo** [comment] 2020-12-08 06:53
I tried updating to latest released sdk i.e. dotnet-sdk-3.1.404-win-x64  but still the issue is reproducible on my sample project. Does it means that the fix is not yet released ?

**Closed** 2020-12-09 21:05 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
