### ISSUE TITLE
[Blazor WASM] Registering a typed HttpClient does not work when using `dotnet watch`

### ISSUE THREAD

**Issue by johanndev** [dotnet/aspnetcore#33839] opened 2021-06-25 08:51 UTC
### Describe the bug

I tried using a typed HttpClient in a Blazor WebAssembly app as described here: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-6.0&pivots=webassembly#typed-httpclient.

When I try to run the app with `dotnet watch`, the app prints an error message to the console and does not start. 
When I use `dotnet run`, everything works as expected.

### To Reproduce
Repo: https://github.com/johanndev/BlazorTypedHttpClientTest

1. Run the app with `dotnet run`, observe the output of a JSON object in the browser console.
2. Start the app again with `dotnet watch`, the following error will be printed to the browser console:
```
Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1374, condition `' not met
```
<details>
<summary>Full console output with dotnet watch:</summary>

* Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1374, condition `<disabled>' not met

542256 @ dotnet.6.0.0-preview.5.21301.5.js:1
_emscripten_asm_const_int @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0xde854
(anonymous) @ 008a4f9a:0x190ec8
(anonymous) @ 008a4f9a:0x10693e
(anonymous) @ 008a4f9a:0x8a472
(anonymous) @ 008a4f9a:0xef24
(anonymous) @ 008a4f9a:0x7e88
(anonymous) @ 008a4f9a:0x56ee
(anonymous) @ 008a4f9a:0x682c3
(anonymous) @ 008a4f9a:0x10ebb9
(anonymous) @ 008a4f9a:0xedf7e
(anonymous) @ 008a4f9a:0x192fcc
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x9ab1
(anonymous) @ 008a4f9a:0x31b7b
(anonymous) @ 008a4f9a:0xd33b6
(anonymous) @ 008a4f9a:0x50675
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
receiveHotReload @ blazor-hotreload.js:2
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
he._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
call_assembly_entry_point @ dotnet.6.0.0-preview.5.21301.5.js:1
callEntryPoint @ blazor.webassembly.js:1
ct @ blazor.webassembly.js:1
async function (async)
ct @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Show 4 more frames
localhost/:1 Uncaught (in promise) ExitStatus {name: "ExitStatus", message: "Program terminated with exit(0)", status: 0}
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
receiveHotReload @ blazor-hotreload.js:2
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
set_task_result @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.6.0.0-preview.5.21301.5.js:1
he._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
lt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ 008a4f9a:0x1930bb
(anonymous) @ 008a4f9a:0x5972b
(anonymous) @ 008a4f9a:0x4541e
(anonymous) @ 008a4f9a:0x12d0c6
(anonymous) @ 008a4f9a:0x116d09
(anonymous) @ 008a4f9a:0x79023
(anonymous) @ 008a4f9a:0x1415b
(anonymous) @ 008a4f9a:0x10ce9e
gb @ 008a4f9a:0x10787a
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.5.21301.5.js:1
_call_method_with_converted_args @ dotnet.6.0.0-preview.5.21301.5.js:1
call_method @ dotnet.6.0.0-preview.5.21301.5.js:1
(anonymous) @ dotnet.6.0.0-preview.5.21301.5.js:1
call_assembly_entry_point @ dotnet.6.0.0-preview.5.21301.5.js:1
callEntryPoint @ blazor.webassembly.js:1
ct @ blazor.webassembly.js:1
async function (async)
ct @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1

</details>

### Further info
If I use `builder.Services.AddScoped<TypedClient>();` instead of `builder.Services.AddHttpClient<TypedClient>();` to register the typed client with DI, `dotnet watch` works as expected.

### Further technical details
ASP.NET Core 6 Preview 5
<details>
<summary>dotnet --info:</summary>
  dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

</details>

**Comment by pranavkm** [comment] 2021-06-25 14:40
Thanks for the issue report. This is a dupe of https://github.com/dotnet/aspnetcore/issues/33319 and is fixed in preview6.

**Closed by pranavkm** 2021-06-25 14:40 UTC
Labels: area-blazor, blazor-wasm
