### ISSUE TITLE
InputBase<TValue> derived types not working if TValue has an implicit operator string

### ISSUE THREAD

**Issue by AndreasHeisel** [dotnet/aspnetcore#24554] opened 2020-08-04 07:06 UTC
I have a type like this:

```CSharp
public class ReferenceTypeWithOperator
{
	public static implicit operator String(ReferenceTypeWithOperator value)
		=> "Foo";
}
```
and build an input-component for it like this:

```
@inherits InputBase<ReferenceTypeWithOperator>
@code {
	protected override bool TryParseValueFromString(string value, out ReferenceTypeWithOperator result, out string validationErrorMessage)
	{
		result = new ReferenceTypeWithOperator();
		validationErrorMessage = default;
		return true;
	}
}

```

If I use it, I get the following exception

```
InvalidCastException: Unable to cast object of type 'System.String' to type 'BlazorInput.Components.ReferenceTypeWithOperator'.
Microsoft.AspNetCore.Components.Reflection.MemberAssignment+PropertySetter<TTarget, TValue>.SetValue(object target, object value)

InvalidOperationException: Unable to set property 'Value' on object of type 'BlazorInput.Components.InputReferenceTypeWithOperator'. The error was: Unable to cast object of type 'System.String' to type 'BlazorInput.Components.ReferenceTypeWithOperator'.
Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(object target, IPropertySetter writer, string parameterName, object value)
```

If I remove the operator, everything works.

The Microsoft.AspNetCore.App package version is 3.1.3

dotnet --info:
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.302
 Commit:    41faccf259

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

I am using VisualStudio 16.6.4 on Windows 10 1909

**Comment by mkArtakMSFT** [comment] 2020-08-04 16:37
Thanks for contacting us. This is a dupe of #18042

**Closed by mkArtakMSFT** 2020-08-04 16:37 UTC
Labels: area-blazor
