### ISSUE TITLE
Blazor Text Page: Issue with Displaying Russian Text in Source Code

### ISSUE THREAD

**Issue by UserDinDF** [dotnet/aspnetcore#53056] opened 2023-12-29 10:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello Blazor Team,

I am experiencing an issue with the text in Source Code in a C# Blazor project. Example with Meta-Tags, when I set meta tag content using a variable, like so:

`<meta name="description" content="@fileModel.Seo_Description">`
The Russian text is not displayed correctly in the source code. Instead, it appears as decoded text, as shown below:
`<meta name="keywords" content="&#x442;&#x435;&#x441;&#x442; &#x442;&#x435;&#x43A;&#x441;&#x442;&#x442;&#x442" /> `

However, if I manually write the meta tag in the code like this:

`<meta name="description" content="Тест текст">`

It displays correctly. This issue seems specific to dynamically generated content in meta tags, as static content displays as expected.

The problem is not only in the meta tags but in the total source code

### Expected Behavior

The expected behavior is that when setting the content of meta tags dynamically using a variable in a C# Blazor application, the Russian text should display correctly in the source code, similar to how it appears when written directly in HTML. For instance, using the following line:

`<meta name="description" content="@fileModel.Seo_Description">`
should result in the Russian text appearing in the source code as it is, rather than being converted into decoded text. The goal is to ensure that dynamic content in meta tags, especially non-English characters like Russian, is rendered accurately in the source code.

### Steps To Reproduce

![Screenshot_4 (2)](https://github.com/dotnet/aspnetcore/assets/146924936/772f9139-a8e4-4179-abbd-c3cccd084aa7)
![Screenshot_3 (1)](https://github.com/dotnet/aspnetcore/assets/146924936/3ca2461c-51b6-4578-98e8-630d00e3b134)
![Screenshot_5](https://github.com/dotnet/aspnetcore/assets/146924936/00bb3b01-61c9-4122-b8a3-d5413abccc78)

### .NET Version

8.0.100

**Comment by guardrex** [comment] 2023-12-29 12:06
Thanks @UserDinDF ... I'll keep an 👁️ on this issue, and I'll cover this scenario in the documentation after the product unit assists here, unless it's a bug that will be updated in a patch release.

**Comment by javiercn** [comment] 2024-01-11 15:36
Fixed by https://github.com/dotnet/aspnetcore/pull/53213, will be available in a future patch release.

A custom encoder can be configured with
```
builder.Services.AddWebEncoders(encoders =>
{
    ...
});
```

**Comment by javiercn** [comment] 2024-01-11 15:37
Dupe of https://github.com/dotnet/aspnetcore/pull/53140

**Closed by javiercn** 2024-01-11 15:37 UTC
Labels: area-blazor

**Comment by UserDinDF** [comment] 2024-01-28 15:03
> Dupe of #53140

Hallo Javier Calvarro Nelson. Is this feature available for use in my application?

I added:

builder.Services.AddWebEncoders(encoders =>
{
    encoders.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All);
});

but I didn't notice any changes
