### ISSUE TITLE
Analyer issue .

### ISSUE THREAD

**Issue by Raja-Ashutosh** [dotnet/aspnetcore#20677] opened 2020-04-09 11:56 UTC
we are building one new application in aspnetcore3.1.
We are facing .net Analyer . object reference not set the instance of object along with some other warning message.  Which causes the pipeline failed . And i have verified the code where showing the warning. 
Anyway for work around we suppress the Analyzer .

 <DisableImplicitAspNetCoreAnalyzers>true</DisableImplicitAspNetCoreAnalyzers>
    <CodeAnalysisRuleSet>../../Analyzer.ruleset</CodeAnalysisRuleSet>

Can someone shared some thought here

**Comment by javiercn** [comment] 2020-04-09 12:23
@Raja-Ashutosh Thanks for contacting us.

can you share the stack trace of the analyzer in question? Is this an asp.net core specific analyzer?

**Comment by Raja-Ashutosh** [comment] 2020-04-09 13:28
1>------ Build started: Project: Web, Configuration: Debug Any CPU ------
1>Features\Components\ProductStacks\ProductStacks.cs(14,7,14,29): warning CS0105: The using directive for 'System.Threading.Tasks' appeared previously in this namespace
1>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
1>Web -> C:\Git\deals\src\Applications\Web\bin\Debug\netcoreapp3.1\Dell.Deals.Web.dll
1>Web -> C:\Git\deals\src\Applications\Web\bin\Debug\netcoreapp3.1\Dell.Deals.Web.Views.dll

**Comment by Raja-Ashutosh** [comment] 2020-04-09 13:30
1>------ Build started: Project: Web, Configuration: Debug Any CPU ------
1>CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
1>Web -> C:\Git\deals\src\Applications\Web\bin\Debug\netcoreapp3.1\Dell.Deals.Web.dll
1>Web -> C:\Git\deals\src\Applications\Web\bin\Debug\netcoreapp3.1\Dell.Deals.Web.Views.dll
1>Building assets for Debug configuration

**Comment by javiercn** [comment] 2020-04-09 13:45
@pranavkm can you take a look?

**Comment by pranavkm** [comment] 2020-04-09 16:17
@Raja-Ashutosh can you share your project file? This could very well be a dup of https://github.com/dotnet/aspnetcore/issues/14723 which appears when you reference 2.x MVC in a 3.1 application.

**Comment by Raja-Ashutosh** [comment] 2020-04-09 17:28
I am going through  the issue link you shared with me.looks like our infrastructure project still in 2.2 and the new project is 3.1. This might be the rca

**Comment by pranavkm** [comment] 2020-04-09 18:00
Upgrading the project would be the way to go. If you unable to upgrade it, skipping the analyzer would be appropriate. We'll use the linked issue to track resolving this.

**Comment by RobinHSanner** [comment] 2020-04-14 20:20
Which issue is this a duplicate of?

**Comment by pranavkm** [comment] 2020-04-14 20:23
@RobinHSanner  - https://github.com/dotnet/aspnetcore/issues/14723

**Comment by Pilchie** [comment] 2020-05-11 18:27
Closing resolved issue.

**Closed by Pilchie** 2020-05-11 18:27 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-platform
