### ISSUE TITLE
Class renames do not work

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#30889] opened 2021-03-12 20:55 UTC
### Describe the bug
Suppose ComponentA has a dependency on a service class ServiceC; introduced via @inject directive in the razor file. If you rename ServiceC to ServiceRenamed, the build fails. This is because the class references are not updated in the razor file and the g.razor file continues to refer to the old name ServiceC. One has to manually change every ServiceC reference to ServiceRenamed. 

### To Reproduce
Inject a service on the razor page. Rename the class.

**Comment by NTaylorMullen** [comment] 2021-03-15 22:02
Duplicate of: https://github.com/dotnet/aspnetcore/issues/30949

**Closed** 2021-03-15 22:05 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, feature-razor.vs
