### ISSUE TITLE
ConfigureKestrel() for certificate authentication must be placed before UseKestrel()!

### ISSUE THREAD

**Issue by replaysMike** [dotnet/aspnetcore#15351] opened 2019-10-02 21:16 UTC
The docs don't mention it but to configure Kestrel for certificate authentication, you must place the following _before_ UseKestrel() is defined.

```
.ConfigureKestrel(options => {
    options.ConfigureHttpsDefaults(opt => {
        opt.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
    });
})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment] 2019-10-23 21:48
It's required because we need to turn the normal cert authentication off so we can handle it later on as middleware. It was in my [original docs](https://github.com/blowdart/idunno.Authentication/tree/master/src/idunno.Authentication.Certificate) it just appears not to have made it over.

**Comment by Tratcher** [comment] 2019-10-23 22:02
But ConfigureKestrel and UseKestrel shouldn't be order dependent.

**Comment by anurse** [comment] 2019-11-05 21:12
@replaysMike can you provide a runnable sample that reproduces the problem so we can investigate? We don't believe these should be order-dependent.

**Comment by replaysMike** [comment] 2019-11-14 19:25
I’ll try to mark a few minutes to do this today

**Comment by anurse** [comment] 2019-11-14 21:17
@Tratcher was also going to take a look and double check.

**Comment by Tratcher** [comment] 2019-11-14 22:19
I can reproduce this issue with the following code:
```
            var host = new WebHostBuilder()
                .UseKestrel(options =>
                {
                    options.ListenLocalhost(5001, options =>
                    {
                        options.UseHttps();
                    });
                })
                .ConfigureKestrel(options => {
                    options.ConfigureHttpsDefaults(opt => {
                        opt.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                    });
                })
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .Build();

            await host.RunAsync();
```
The problem is that ListenLocalhost and UseHttps run inline so ConfigureHttpsDefaults must be called before any endpoints are registered.

The workaround described above of calling ConfigureKestrel before UseKestrel is valid, but not viable when using CreateDefaultBuilder.

The scenario where setting ConfigureHttpsDefaults in ConfigureKestrel works is when the endpoints are defined in config such as how CreateDefaultBuilder already does. This works because the config doesn't actually create endpoints until the server starts.

(More notes to follow)

**Comment by Tratcher** [comment] 2019-11-14 22:59
Note UseKestrel and ConfigureKestrel do mostly the same thing except that ConfigureKestrel doesn't register an IServer so it avoid conflicts with other lazily activated servers like IIS in-proc.

In most applications UseKestrel is called by CreateDefaultBuilder or ConfigureWebHostDefaults so you won't be calling Listen in there. ConfigureKestrel  was added so you could call it after CreateDefaultBuilder without doing redundant work. In this scenario all Kestrel config should happen inside ConfigureKestrel, you shouldn't have direct calls to UseKestrel.

If you're not using CreateDefaultBuilder or ConfigureWebHostDefaults then you call UseKestrel and do all of the config there, there's no need to call ConfigureKestrel.

When I combine the UseKestrel and ConfigureKestrel code from my sample above the ordering issue still exists within the call:
```
                .Use/ConfigureKestrel(options =>
                {
                    options.ListenLocalhost(5001, options =>
                    {
                        options.UseHttps();
                    });
                    options.ConfigureHttpsDefaults(opt => {
                        opt.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                    });
                })
```
The above doesn't work because ConfigureHttpsDefaults needs to be called before ListenLocalhost in order to affect that endpoint:
```
                .Use/ConfigureKestrel(options =>
                {
                    options.ConfigureHttpsDefaults(opt => {
                        opt.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                    });
                    options.ListenLocalhost(5001, options =>
                    {
                        options.UseHttps();
                    });
                })
```
@replaysMike does this match what you're seeing?

I don't anticipate making any code fixes here, there's not much that can be changed without some dramatic redesigns. There are likely some clarifications we can make to the docs though.

**Comment by jkotalik** [comment] 2020-01-24 21:05
I believe https://github.com/aspnet/AspNetCore.Docs/pull/15697 documented this issue. Closing.

**Closed by jkotalik** 2020-01-24 21:05 UTC
Labels: Docs, area-servers
