### ISSUE TITLE
ConfigureKestrel Called During WebApplicationBuilder.Build in 6.0.9

### ISSUE THREAD

**Issue by JonathanHopeDMRC** [dotnet/aspnetcore#43993] opened 2022-09-14 21:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In runtime 6.0.8 the call to ConfigureKestrel occurred during WebApplication.Run. In 6.0.9 the call to ConfigureKestrel  occurs during WebApplication.Build. This means that we can no longer access anything in the ServiceProvider in ConfigureKestrel. If there is a more idiomatic way to access things in the SeviceProvider in ConfigureKestrel we are open to it, however this change surprised us for a point release.

### Expected Behavior

The call to ConfigureKestrel occurring during WebApplication.Run.

### Steps To Reproduce

1. Clone this project: https://github.com/JonathanHopeDMRC/callorder
2. docker build . -t callorder --no-cache
3. docker run -t callorder

Changing the runtime to 6.0.8 in the Dockerfile will make this work.

### .NET Version

6.0.9

**Comment by Tratcher** [comment] 2022-09-14 22:21
Hmm, there shouldn't be any hosting related changes in 6.0.9.. We'll have to investigate.
https://github.com/dotnet/aspnetcore/commits/v6.0.9
https://github.com/dotnet/runtime/commits/v6.0.9

@halter73

**Comment by davidfowl** [comment] 2022-09-15 05:07
I see the issue, it was [this change](https://github.com/dotnet/aspnetcore/commit/ce292b36cfcbf2d8488b1ea235eae1949fb0c8bc)

**Comment by JonathanHopeDMRC** [comment] 2022-09-15 15:57
That workaround works great! Thanks for the quick response.

**Comment by davidfowl** [comment] 2022-09-16 21:30
@HaoK this is still a regression in a patch. We should probably discuss if we think it should be fixed.

**Comment by Tratcher** [comment] 2022-09-16 22:40
The example given here was suspect (timing capturing statics). We shouldn't change it again unless we find a more compelling break.

**Comment by HaoK** [comment] 2022-09-16 22:54
Ok clearing the labels so next triage can look at this again

**Comment by adityamandaleeka** [comment] 2022-09-23 20:33
Triage: this was an unintentional side effect, but we're going to keep the behavior as-is since the original issue this addressed was more severe than this consequence.

**Closed** 2022-09-25 19:01 UTC
Labels: :heavy_check_mark: Resolution: Won't Fix, area-runtime, Status: Resolved
