### ISSUE TITLE
[dotnet-watch] Hot Reload - Provide a way to suppress rude edit dialog

### ISSUE THREAD

**Issue by eknkc** [dotnet/aspnetcore#37023] opened 2021-09-25 11:06 UTC
I've been testing the new hot reload feature and currently, if there is a rude edit detected, the watcher prompts for action:

```
watch : Files changed: /...../Program.cs~
watch : Unable to apply hot reload because of a rude edit. Rebuilding the app...
watch : Unable to handle changes using hot reload.
watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
```

My problem is, I do not run this watch directly attached to my terminal. It is buried under a task runner, redirecting stdin to somewhere else and so I can not send the a keypress.

I tried `yes a | dotnet watch...` but that also does not seem to work.

Can we have an environment variable or a cli flag to set up a default action? Or is there any alternative to `yes` that I can try?

**Comment by mkArtakMSFT** [comment] 2021-11-02 19:30
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/37190

**Closed by mkArtakMSFT** 2021-11-02 19:30 UTC
Labels: area-commandlinetools, feature-dotnetwatch, feature-hot-reload
