### ISSUE TITLE
ConfigureTestContainer not being invoked

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/aspnetcore#51381] opened 2023-10-14 18:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a `ConfigureTestContainer` action is register through `WebHostBuilder.ConfigureTestContainer`, the action is not invoked.

### Expected Behavior

The action should be invoked.

### Steps To Reproduce

I've adapted the test [ServicesCanBeOverridenForTestingAsync](https://github.com/dotnet/aspnetcore/blob/16f8b03c2f5b4d3bc82a92ddafc642182e39c1b7/src/Hosting/TestHost/test/TestServerTests.cs#L122) to:

```csharp
var builder = new WebHostBuilder()
    .UseStartup<ThirdPartyContainerStartup>()
    .ConfigureTestServices(services =>
    {
        Console.WriteLine("WebHostBuilder.ConfigureTestServices");
    })
    .ConfigureTestContainer<ThirdPartyContainer>(container =>
    {
        Console.WriteLine("WebHostBuilder.ConfigureTestContainer");
    })
    ;

var host = new TestServer(builder);

public class ThirdPartyContainerStartup
{
    public void ConfigureServices(IServiceCollection services)
    {
        Console.WriteLine("ThirdPartyContainerStartup.ConfigureServices");
    }
    public void ConfigureContainer(IServiceCollection services)
    {
        Console.WriteLine("ThirdPartyContainerStartup.ConfigureContainer");
    }
    public void Configure(IApplicationBuilder app)
    {
        Console.WriteLine("ThirdPartyContainerStartup.Configure");
    }
}
public class ThirdPartyContainer
{
    public IServiceCollection Services { get; set; }
}
public class ThirdPartyContainerServiceProviderFactory : IServiceProviderFactory<ThirdPartyContainer>
{
    public ThirdPartyContainer CreateBuilder(IServiceCollection services) => new ThirdPartyContainer { Services = services };
    public IServiceProvider CreateServiceProvider(ThirdPartyContainer containerBuilder) => containerBuilder.Services.BuildServiceProvider();
}
```

And the output is:

```
ThirdPartyContainerStartup.ConfigureServices
WebHostBuilder.ConfigureTestServices
ThirdPartyContainerStartup.ConfigureContainer
ThirdPartyContainerStartup.Configure
```

### .NET Version

.NET SDK 8.0.100-rc.2.23502.2

**Comment by halter73** [comment] 2023-11-01 16:38
Given that `WebApplicationBuilder` uses the generic host internally, I think this is a dupe of #14907.

**Closed by halter73** 2023-11-01 16:38 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-hosting
