### ISSUE TITLE
Transient local build failures: error MSB3491: Could not write lines to file

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspnetcore#45596] opened 2022-12-15 01:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When building locally on Windows I am occasionally seeing build failures when running ```src\Framework\build.cmd```, the error is:

```
C:\Code\dotnet\aspnetcore\.dotnet\sdk\8.0.100-alpha.1.22531.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAsse
mblyInfo.targets(165,5): error MSB3491: Could not write lines to file "C:\Code\dotnet\aspnetcore\artifacts\obj\Microsof
t.AspNetCore.App.CodeFixes\Debug\netstandard2.0\Microsoft.AspNetCore.App.CodeFixes.AssemblyInfoInputs.cache". The proce
ss cannot access the file 'C:\Code\dotnet\aspnetcore\artifacts\obj\Microsoft.AspNetCore.App.CodeFixes\Debug\netstandard
2.0\Microsoft.AspNetCore.App.CodeFixes.AssemblyInfoInputs.cache' because it is being used by another process. [C:\Code\
dotnet\aspnetcore\src\Framework\AspNetCoreAnalyzers\src\CodeFixes\Microsoft.AspNetCore.App.CodeFixes.csproj]
```

It can happen at multiple different places from my experience, and sometimes multiple times. The error is coming from this MSBuild task invocation:

https://github.com/dotnet/sdk/blob/5811125cd07d6beb0a6f3e0ec7db2ce191b8887a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L165

If I run the build again it usually works, but can fail multiple times in a row.

### Expected Behavior

Build should complete successfully from latest on main.

### Steps To Reproduce

1. Clone https://github.com/dotnet/aspnetcore (or your updated fork)
2. ```git submodule update --recursive``` to make sure everything is up to date.
3.  ```. .\activate.ps1``` from root of repo.
4. ```.\restore.cmd``` from root of repo.
5. ```.\src\Framework\build.cmd``` (may need to do this multiple times before a failure occurs).

### Exceptions (if any)

C:\Code\dotnet\aspnetcore\.dotnet\sdk\8.0.100-alpha.1.22531.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAsse
mblyInfo.targets(165,5): error MSB3491: Could not write lines to file "C:\Code\dotnet\aspnetcore\artifacts\obj\Microsof
t.AspNetCore.App.CodeFixes\Debug\netstandard2.0\Microsoft.AspNetCore.App.CodeFixes.AssemblyInfoInputs.cache". The proce
ss cannot access the file 'C:\Code\dotnet\aspnetcore\artifacts\obj\Microsoft.AspNetCore.App.CodeFixes\Debug\netstandard
2.0\Microsoft.AspNetCore.App.CodeFixes.AssemblyInfoInputs.cache' because it is being used by another process. [C:\Code\
dotnet\aspnetcore\src\Framework\AspNetCoreAnalyzers\src\CodeFixes\Microsoft.AspNetCore.App.CodeFixes.csproj]

### .NET Version

8.0.100-alpha.1.22531.1

**Comment by TanayParikh** [comment] 2022-12-15 02:52
Probably not related, but you're missing the environment activation (step 3.5) `. ./activate.ps1`

**Comment by mitchdenny** [comment] 2022-12-15 03:16
> Probably not related, but you're missing the environment activation (step 3.5) `. .\activate.ps1`

I had assumed that the DOTNET_ROOT was setup automatically when I ran build.cmd, but apparently not :)

**Comment by mkArtakMSFT** [comment] 2023-01-03 19:16
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/32219

**Closed by mkArtakMSFT** 2023-01-03 19:16 UTC
Labels: area-infrastructure
