### ISSUE TITLE
New blazor wasm hosted project add container orchestrator support debugging doesn't work.

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#51038] opened 2023-09-30 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. On windows, create a new blazor wasm hosted project using standard template for dotnet 6.
  - Chose to add docker support, and select linux.
2. In VS2022 right click on server project and "Add Container Orchestrator" support.
3. Launch the compose project in debug mode.

Everything builds and deploys, debugger is attached, all containers are running via compose as expected.

1. Put a breakpoint in the blazor project "Counter" component button click.
2. Click the button in the browser.

(pushed here:  https://github.com/dazinator/TestDockerBlazorDebug/tree/master)

### Expected Behavior

Expect the breakpoint to be hit.
The breakpoint is not hit.

Inside of the running container, there are the "static asset" files. As I understand it, the docker tooling should be "transforming" windows absolute paths that work on the windows host, to linux paths that work within the container.

As per this screenshot - it does appear to do this for the server project (see the additional file ending "DT.json")
However it doesn't do this for the client wasm project. If I look at the static assets file for the client project it uses full windows paths still which only work on the host.

<img width="575" alt="image" src="https://github.com/dotnet/aspnetcore/assets/3176632/3ae9d123-97f3-45b4-8e20-0d6a0b42cfd2">

### Steps To Reproduce

As described above or repro pushed here:  https://github.com/dazinator/TestDockerBlazorDebug/tree/master

### .NET Version

dotnet --version

**Comment by mkArtakMSFT** [comment] 2023-10-02 17:01
This is a dupe of https://github.com/dotnet/aspnetcore/issues/37565

**Closed by mkArtakMSFT** 2023-10-02 17:01 UTC
Labels: investigate, area-blazor
