### ISSUE TITLE
How to persist data on Blazor SSR + WASM Client in .NET 8 preview 6

### ISSUE THREAD

**Issue by Markz878** [dotnet/aspnetcore#49448] opened 2023-07-16 17:17 UTC
Trying to reproduce .NET 7 WASM hosted + prerendering template on .NET 8 preview 6.
Is there a possibility yet to persist the data fetched from the server side in Blazor WASM components?

**Comment by danroth27** [comment] 2023-07-17 16:28
We have a tag helper for this when using a .cshtml file. We'll need a component for when using a .razor file. We also need to think about how this will work with streaming rendering.

**Comment by Markz878** [comment] 2023-07-18 16:09
@danroth27 Thanks Dan, this is crucial for us to be able to move to the new SSR style in our apps.

Would it possible to also somehow make it easier to do the data persisting part?
Currently the PersistentComponentState with PersistingComponentStateSubscription and disposing is a bit much.
Javier showed some [Persist] attribute in one of the stand-ups, hopefully something like that would also be possible.

**Comment by danroth27** [comment] 2023-07-18 20:16
> @danroth27 Thanks Dan, this is crucial for us to be able to move to the new SSR style in our apps.

Agreed! We're going to try to get this addressed for .NET 8.

> Could it be possible to also somehow make it easier to do the data persisting part? Currently the PersistentComponentState with PersistingComponentStateSubscription with disposing is a bit much. Javier showed some [Persist] attribute in one of the stand-ups, hopefully something like that would also be possible.

Yup, we're tracking having a declarative model with https://github.com/dotnet/aspnetcore/issues/26794

**Comment by mkArtakMSFT** [comment] 2023-07-31 18:46
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/49733

**Closed** 2023-09-02 21:51 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, enhancement, area-blazor, Status: Resolved
