### ISSUE TITLE
JS Isolation in Blazor Components

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#23560] opened 2020-07-01 08:11 UTC
JS isolation has been discussed in many separate issues ([example](https://github.com/dotnet/aspnetcore/issues/10170#issuecomment-532652760)). I'm sure the team intends to tackle this at some point, but it hasn't been tracked as an independent issue, until now.

JS Isolation per Blazor component would be appreciated because:
- much easier
- much cleaner
- reduces lots of boilerplate
- those used to SPAs are expecting to work that way

**Comment by mkArtakMSFT** [comment] 2020-07-01 16:23
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Closed** 2020-08-26 16:03 UTC
Labels: Done, area-blazor, enhancement

**Comment by egil** [comment] 2020-09-06 08:54
Hey folks,

Does this addition mean a custom attribute will be added to generated HTML markup like with scoped CSS?

**Comment by SteveSandersonMS** [comment] 2020-09-06 17:22
No. The form of JS isolation we have added is the ability to load and invoke ES6 modules. They are not tied to specific components.

**Comment by Amine-Smahi** [comment] 2020-09-15 10:53
Hello,
First i want to thank the team for adding js module support to blazor.
But everyone was expecting to be able to use a component js isolation "component.razor.js"

This is the most suitable way for a angular devs

**Comment by SteveSandersonMS** [comment] 2020-09-15 11:03
@Amine-Smahi You can have any naming convention you want. If you want to have one JS file per component, you can certainly do that.

The one limitation is that the `.js` file needs to go in `wwwroot` rather than side-by-side with the component. Perhaps that's something we could enhance in the future but I hope for now it doesn't inconvenience you too much to put the `.js` file into some directory structure within `wwwroot`.

**Comment by Amine-Smahi** [comment] 2020-09-15 11:11
The problem is not in the naming convention specifically, but rather in the location of the js file.
It would be perfect if we had the ability to create a folder for each component that contain the css, js and razor tougher just like angular.

I would like to thank the team again for the amazing work but i think it’s a bit missy to have to switch between wwwroot and component location just saying

**Comment by egil** [comment] 2020-09-15 11:31
@Amine-Smahi my first thought is that this should be doable by a build script/msbuild step, that finds all .js/.ts files in a Blazor class lib/app and copies them to wwwroot at build time.

**Comment by lonix1** [comment] 2020-09-16 06:36
@egil That is a very good workaround, for now. But long-term I think most of us with previous SPA experience would agree with @Amine-Smahi.

Also agree with him that this is still v1, and awesome as is. Since @SteveSandersonMS is receptive to the idea, I'm sure we'll see something better in vNext.

**Comment by lonix1** [comment] 2020-09-17 06:32
@Amine-Smahi I suppose you could copy your comment into a new backlog issue so no one forgets about it?

**Comment by lonix1** [comment] 2020-09-24 06:45
Folks if you agree with @Amine-Smahi that we need colocated cs/css/js files per component, please upvote the new [issue here](https://github.com/dotnet/aspnetcore/issues/26145).
