### ISSUE TITLE
Restore reliability

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#21185] opened 2020-04-24 17:20 UTC
We sometimes run into issues with our NuGet stores wherein they temporarily throw errors, such as https://dev.azure.com/dnceng/public/_build/results?buildId=615558&view=logs&j=1f58c02c-a2e7-59c3-5915-ab7de64e5b92&t=fdbd47cf-8ee9-5156-ca10-83b314ab5884&l=258. Generally these clear up quickly but as a whole they add up to decrease our reliability. We should consider ways that we can reduce or eliminate failures of this nature.

Off the top of my head some ideas:
1. Cache some (ideally all) packages on the image used by the build in such a way that the build can't even start if they're not available, then use that local store as a NuGet store. (This would likely require us to maintain the store by hand, and would probably require either a feature in AZDO or constant modification of the images used for our builds. both expensive prospects)
1. Maintain multiple NuGet stores with full package lists and ensure that failover between the two (or more) is silent. Even if each service only has a 99% uptime, the combined uptime should be really solid. (This means a bit of work around maintaining multiple stores, but most of that work is automated anyway. Possibly this would also require some work from NuGet related to resiliency on for this kind of scenario, but they might have already done that).

**Comment by dougbu** [comment] 2020-04-24 19:23
This may actually be an issue with the particular blob feed. Note the `restore` operation retried the package download three times.

@MattGal @mmitche is anything wrong with https://dotnetfeed.blob.core.windows.net/ ATM? The specific download that failed was for https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.extensions.fileproviders.embedded/2.1.1/microsoft.extensions.fileproviders.embedded.2.1.1.nupkg

**Comment by ryanbrandenburg** [comment] 2020-04-24 19:51
I've been able to successfully download that file like 6 times at this point, so it's likely that it was a transient issue, plus the error given each time was a 500 rather than a 40X. Regardless, a single NuGet feed represents a single point of failure, even if we're able to increase the reliability of that feed significantly.

**Comment by MattGal** [comment] 2020-04-27 15:57
> This may actually be an issue with the particular blob feed. Note the `restore` operation retried the package download three times.
> 
> @MattGal @mmitche is anything wrong with https://dotnetfeed.blob.core.windows.net/ ATM? The specific download that failed was for https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.extensions.fileproviders.embedded/2.1.1/microsoft.extensions.fileproviders.embedded.2.1.1.nupkg

When you see an error like "500 (Operation could not be completed within the specified time.)" while it's confusing this is a 500, from reading around I suspect this is actually just a way of surfacing internal throttling limits of a storage account that is handling 40+M transactions a week... i.e. I think this is just the symptom of a peak load moment.

**Comment by ryanbrandenburg** [comment] 2020-04-27 16:36
@MattGal, while I'm sure that's true, the Department of Infrastructure and @rynowak have been talking about our need for reliability here in terms of needing something like "6 nines". I think that's likely to be difficult to hit with a single point of failure, even for high reliability stores like the dotnetfeed and GitHub because momentary downtime will always be a possibility.

**Comment by ryanbrandenburg** [comment] 2020-04-27 20:49
* https://dev.azure.com/dnceng/public/_build/results?buildId=617667&view=logs&j=efda9e5f-cf98-536e-4181-9b6c13ac35b3&t=dca754b7-8b76-5f52-60ef-6b0e8f7eb325&l=1349

**Comment by dougbu** [comment] 2020-04-27 21:46
@ryanbrandenburg I very much doubt this issue is actionable. Even if we could cache things without blowing up our disk space usage, it's a lot of infrastructure for a rare and transient issue. Suggest we close this.

**Comment by dougbu** [comment] 2020-11-05 22:53
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2020-11-05 22:53 UTC
Labels: area-infrastructure
