### ISSUE TITLE
Blazor: Inconsistent binding behaviour

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#18239] opened 2020-01-09 17:20 UTC
When passing a value to a component's parameter, Blazor passes the value of the variable when the parameter is not a string, and the name of the variable when it is a string.

Component that receives the values
```
<ul>
    <li>BooleanParam = @BooleanParam</li>
    <li>IntegerParam = @IntegerParam</li>
    <li>StringParam = @StringParam</li>
</ul>

@code {
  [Parameter]
  public bool BooleanParam { get; set; }

  [Parameter]
  public int IntegerParam { get; set; }

  [Parameter]
  public string StringParam { get; set; }
}
```

Index.razor
```
@page "/"

<MyComponent BooleanParam=BooleanParamVariable IntegerParam=IntegerParamVariable StringParam=StringParamVariable />

@code
{
	private bool BooleanParamVariable = true;
	private int IntegerParamVariable = 42;
	private string StringParamVariable = "We should see this value";
}
```

**Expected output**
BooleanParam = True
IntegerParam = 42
StringParam = We should see this value

**Actual output**
BooleanParam = True
IntegerParam = 42
StringParam = StringParamVariable

Blazor shouldn't try to evaluate the variable value unless it is prefixed with `@`, the above consuming mark-up should really result in a compiler error that says the string BooleanParam cannot be assigned to a boolean - otherwise the behaviour is inconsistent, and the result of passing a string will be unanticipated.

**Comment by mkArtakMSFT** [comment] 2020-01-09 17:37
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design. Strings are being treated differently and this is true not only for Blazor but also in Razor generally. This is not something we can change as that would be a breaking change with a huge impact.

**Closed by mkArtakMSFT** 2020-01-09 17:37 UTC
Labels: area-blazor

**Comment by mrpmorris** [comment] 2020-01-09 17:46
> This is not something we can change as that would be a breaking change with a huge impact.

Shame it wasn't changed in 3.0
