### ISSUE TITLE
Stopping Blazor debugging presents an error notification

### ISSUE THREAD

**Issue by connor4312** [dotnet/aspnetcore#26413] opened 2020-09-29 01:34 UTC
### Describe the bug

On windows with PS5, I get this notification each time I stop debugging:

![](https://memes.peet.io/img/20-09-aee63242-6770-47ca-852e-372173f01503.png)

### To Reproduce

1. Start debugging
1. Stop debugging by hitting the ⏹️  button

### Exceptions (if any)

none

### Further technical details
- ASP.NET Core: 3.1.402
- C# extension 1.23.2
- VS Code 1.50.0-insiders
- dotnet --info:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by captainsafia** [comment] 2020-09-29 02:51
It looks like you might be running into a dupe of https://github.com/OmniSharp/omnisharp-vscode/issues/4056.

I put a fix in for this in https://github.com/dotnet/aspnetcore-tooling/pull/2537.

**Closed by captainsafia** 2020-09-29 02:51 UTC
