### ISSUE TITLE
Ignore Authentication  via AllowAnonymous in blazor  issue 

### ISSUE THREAD

**Issue by zanyar3** [dotnet/aspnetcore#23914] opened 2020-07-13 19:01 UTC
I want show first page `Welcome.razor`, it is route `@page "/"` without **Authentication** but blazor execute some process after that show `Weclome.razor`.

I was used `AuthenticationStateProvider`, and implement `CascadingAuthenticationState` in `App.razor` 

Blazor work like this steps 

App.razor

```
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeView>
                <Authorized>
                    <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
                </Authorized>
                <NotAuthorized>
                    <RedirectToLogin />
                </NotAuthorized>
            </AuthorizeView>
        </Found>
        <NotFound>
            <CascadingAuthenticationState>
                <LayoutView Layout="@typeof(EmptyLayout)">
                    <p>No Found</p>
                </LayoutView>
            </CascadingAuthenticationState>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

1. Run `App.razor` for check user Authorize or not 
2. Already user **No Authorize** for first time That's why page redirect to `LoginPage`
3. after page from `LoginPage.razor` redirect to `Welcome.razor`
4. after all steps WebPage show Welcome.razor`

> That is a big problem because some page execute No need to execute run and show

[For more information about details problem see stackoverflow](https://stackoverflow.com/q/62882049/12777835)

**Comment by javiercn** [comment] 2020-07-14 09:39
@zanyar3 thanks for contacting us.

This is a dupe of #23157. I'm closing this issue as we are using the other issue to track the enhancement. I suggest you comment or upvote the other issue instead so that we can better assess the feedback for future planning prioritization.

**Closed by javiercn** 2020-07-14 09:39 UTC
Labels: area-blazor
