### ISSUE TITLE
.net 5.0 SSL certificate failed to run in Linux system

### ISSUE THREAD

**Issue by sukney** [dotnet/aspnetcore#28584] opened 2020-12-11 02:16 UTC
The configuration file is as follows
```
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://0.0.0.0:1116"
      },
      "HttpsInlineCertFile": {
        "Url": "https://localhost:5001",
        "Certificate": {
          "Path": "4896942_vx.jjbbl.com.pfx",
          "Password": "B0rEh8gi"
        }
      }
      
    }
  },
```
The certificate file is as follows
[certificate file](http://yunticket.com/4896942_vx.jjbbl.com_iis.zip)

The following error is reported in CentOS 7
```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
         at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at ScottBrady.Pem.Kestrel.Program.Main(String[] args) in C:\Users\leus\Downloads\Blog-Example-Classes-master\Blog-Example-Classes-master\Pem Loading in .NET Core and .NET 5\ScottBrady.Pem.Kestrel\Program.cs:line 11
```

**Comment by shirhatti** [comment] 2020-12-11 22:14
@sukney Is it possible to share a test certificate that produces this issue? Please do not share your certificate that you're currently using.

**Comment by sukney** [comment] 2020-12-12 01:51
[test certificate file](http://yunticket.com/4908561_test.jjbbl.com_iis.zip)  
This certificate is not used, can download the test, there are certificates and passwords。

**Comment by hvidgaard-ims** [comment] 2020-12-14 13:44
Any progress on this? It's blocking our upgrade from core3.1 to net5.0 with the exact same error.

**Comment by BrennanConroy** [comment] 2020-12-14 22:16
@wfurt Does this stacktrace/issue look familiar?

**Comment by hvidgaard-ims** [comment] 2020-12-15 07:52
If any workaround is known that is not downgrading to 3.1, I would love to know. So far I have not been able to figure any out.

**Comment by sukney** [comment] 2020-12-19 14:33
Are there any alternatives? I need to upgrade to 5.0

**Comment by wfurt** [comment] 2020-12-21 18:38
I will take a look. There is probably workaround manipulating the certificates.

**Comment by wfurt** [comment] 2020-12-21 19:30
I was not able to reproduce it with 5.0.1 and simple Kestrel app. I did verify that the app is using certificate from the pfx (tested on Ubuntu 18.04) Can you provide full unable app @sukney? 
Is there some special option to force Kestrel to the SslStreamCertificateContext or is that default now @BrennanConroy ?

**Comment by sukney** [comment] 2020-12-26 06:02
# @wfurt #[Click here to download my source code](http://yunticket.com/ScottBrady.Pem.Kestrel.rar)

**Comment by BrennanConroy** [comment] 2020-12-28 18:58
> Is there some special option to force Kestrel to the SslStreamCertificateContext or is that default now

Should be the default, assuming you don't provide your own cert selector
https://github.com/dotnet/aspnetcore/blob/cd5303d6d82b067ec5365970229fe34588f924d0/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs#L109

**Comment by wfurt** [comment] 2020-12-28 20:09
I still cannot reproduce it on Centos7 with the linked code @sukne. I used default 1.0.2 OpenSSL but I think it does not really matter. (It is interesting as that uses HttpsFromPem while the pfx file is not really pem)

So I was thinking about what the difference may be. 

The linked code will never pass additional certificates from the pfx file. 
I'm not sure if that is intentional @BrennanConroy but that will force the code to depend on online resolution and internal certificate cache. 
That would be written to `~/.dotnet/corefx/cryptography/x509stores/ca` and you can verify that the location is writable for user running the kestrel server @sukney

I made that fail by manipulating DNS can cleaning the cache but constructing `SslStreamCertificateContext` still works for me. 

The other difference may be access to CA certificates. You can run `openssl version -d` and verify that the returned location and files under "certs" are readable by the user running Kestrel. 

Lastly, can you run following code fragment @sukney, prefferably as user running Kestrel

```c#
using System;
using System.Net.Security;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace repro
{
    class Program
    {
        static void Main(string[] args)
        {
            X509Certificate2  cert = new X509Certificate2("/tmp/repro/4908561_test.jjbbl.com.pfx", "5JyA38Hw");

            X509Chain ch = new X509Chain();
            ch.Build(cert);

            Console.WriteLine ("Chain status length: {0}", ch.ChainStatus.Length);
            Console.WriteLine ("Chain application policy count: {0}", ch.ChainPolicy.ApplicationPolicy.Count);
            Console.WriteLine ("Chain certificate policy count: {0} {1}", ch.ChainPolicy.CertificatePolicy.Count, Environment.NewLine);

            //Output chain element information.
            Console.WriteLine ("Chain Element Information");
            Console.WriteLine ("Number of chain elements: {0}", ch.ChainElements.Count);
            Console.WriteLine ("Chain elements synchronized? {0} {1}", ch.ChainElements.IsSynchronized, Environment.NewLine);

            foreach (X509ChainElement element in ch.ChainElements)
            {
                Console.WriteLine ("Element issuer name: {0}", element.Certificate.Issuer);
                Console.WriteLine ("Element subject name: {0}", element.Certificate.Subject);
                Console.WriteLine ("Element certificate valid until: {0}", element.Certificate.NotAfter);
                Console.WriteLine ("Element certificate is valid: {0}", element.Certificate.Verify ());
                Console.WriteLine ("Element error status length: {0}", element.ChainElementStatus.Length);
                Console.WriteLine ("Element information: {0}", element.Information);
                Console.WriteLine ("Number of element extensions: {0}{1}", element.Certificate.Extensions.Count, Environment.NewLine);

                if (ch.ChainStatus.Length > 1)
                {
                    for (int index = 0; index < element.ChainElementStatus.Length; index++)
                    {
                        Console.WriteLine (element.ChainElementStatus[index].Status);
                        Console.WriteLine (element.ChainElementStatus[index].StatusInformation);
                    }
                }
            }

            var ctx = SslStreamCertificateContext.Create(cert, additionalCertificates: null);
            Console.WriteLine("All done");
        }
    }
}
```

On my system, the chain either returns one element or three, depending on internet reachability.

**Comment by sukney** [comment] 2020-12-29 11:57
@wfurt I run the following error
CChain status length: 1
Chain application policy count: 0
Chain certificate policy count: 0

Chain Element Information
Number of chain elements: 2
Chain elements synchronized? False

Element issuer name: CN=Encryption Everywhere DV TLS CA - G1, OU=www.digicert.com, O=DigiCert Inc, C=US
Element subject name: CN=test.jjbbl.com
Element certificate valid until: 12/13/2021 7:59:59 AM
Element certificate is valid: False
Element error status length: 0
Element information:
Number of element extensions: 9

Element issuer name: CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Element subject name: CN=Encryption Everywhere DV TLS CA - G1, OU=www.digicert.com, O=DigiCert Inc, C=US
Element certificate valid until: 11/27/2027 8:46:10 PM
Element certificate is valid: False
Element error status length: 1
Element information:
Number of element extensions: 8

Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\leus\Downloads\Blog-Example-Classes-master\Blog-Example-Classes-master\Pem Loading in .NET Core and .NET 5\ConsoleApp1\Program.cs:line 45
Aborted (core dumped)

**Comment by wfurt** [comment] 2020-12-30 04:45
that is interesting @sukney as you miss the root and not the intermediate cert as I suspected. That would normally be part of your system. On Centos7, that should be under `/etc/pki/tls` (unless you set OPENSSLDIR) Can you check your app has access there? The root certificate should be in `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` (search for `DigiCert Global Root CA')

**Comment by hvidgaard** [comment] 2021-01-04 07:29
I'm loading the certificate in a mcr.microsoft.com/dotnet/runtime-deps:5.0-alpine docker image, but I would expect that to not matter. It is loading with 

```
var clientHandler = new HttpClientHandler();
clientHandler.ClientCertificates.Add(new X509Certificate2("path to certificate", "cert password"));
clientHandler.ClientCertificateOptions = ClientCertificateOption.Manual;

using (var client = new HttpClient(clientHandler))
{
  ...
}
```

If it will help you I can see to that a minimal repo example of project and docker file is created.

**Comment by wfurt** [comment] 2021-01-04 18:57
minimal repro would be nice @hvidgaard since I was not able to reproduce it and running only on speculations at the moment. It seems like your setup is different so it would be nice if you can also run the test code I posted to see if you get similar results as @sukney

**Comment by hvidgaard** [comment] 2021-01-06 14:15
I have a minimal repro, but I cannot send it to you with a certificate just yet. In the meantime, I have the output from the testcode

```
Chain status length: 1
Chain application policy count: 0
Chain certificate policy count: 0 

Chain Element Information
Number of chain elements: 2
Chain elements synchronized? False 

Element issuer name: CN=TRUST2408 OCES CA III, O=TRUST2408, C=DK
Element subject name: SERIALNUMBER=CVR:25862015-FID:39648716 + CN=IMSoft (funktionscertifikat), O=IMS A/S // CVR:25862015, C=DK
Element certificate valid until: 5/5/2023 2:33:50 PM
Element certificate is valid: False
Element error status length: 0
Element information: 
Number of element extensions: 7

Element issuer name: CN=TRUST2408 OCES Primary CA, O=TRUST2408, C=DK
Element subject name: CN=TRUST2408 OCES CA III, O=TRUST2408, C=DK
Element certificate valid until: 10/26/2032 2:07:43 PM
Element certificate is valid: False
Element error status length: 1
Element information: 
Number of element extensions: 6
```

I am in the process to see if we can get a burner certificate I can use for reproducing the error.

**Comment by wfurt** [comment] 2021-01-06 20:44
Thanks @hvidgaard . It seems like in both cases the chain is missing root CA. That is some hint. I'll try to mimic that in my test setup.

Did you install the root CA to the system and run `update-ca-trust` ?  What OpenSSL do you use `openssl` or `openssl11`

**Comment by wfurt** [comment] 2021-01-06 21:01
I was able to reproduce the exception by forcing the root CA to vanish and I'll proceed on fix. Making the root CA available should be workaround in the mean time.

**Comment by hvidgaard** [comment] 2021-01-07 09:01
@wfurt In production we use the dotnet alpine docker image. No specific root CA installed, so I assume that is the reason. As you've identified, I believe this is not a aspnetcore issue, as I can reproduce it without any reference to aspnetcore.

**Comment by BrennanConroy** [comment] 2021-01-07 16:56
Closing as there is an issue in Runtime for this.

**Closed by BrennanConroy** 2021-01-07 16:56 UTC
Labels: area-servers, investigate, servers-kestrel

**Comment by sukney** [comment] 2021-01-14 13:51
5.02 The console example is good, but the web example still reports the following error

Unable to start Kestrel.
      System.IO.IOException: Failed to bind to address https://localhost:5001.
       ---> System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')) (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
       ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
         at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
         --- End of inner exception stack trace ---
       ---> (Inner Exception #1) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
         at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)<---

         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.IO.IOException: Failed to bind to address https://localhost:50071.
 ---> System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')) (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware..ctor(ConnectionDelegate next, HttpsConnectionAdapterOptions options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.<>c__DisplayClass12_0.<UseHttps>b__0(ConnectionDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.Build()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)<---

   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at ScottBrady.Pem.Kestrel.Program.Main(String[] args) in C:\Users\leus\Downloads\Blog-Example-Classes-master\Blog-Example-Classes-master\Pem Loading in .NET Core and .NET 5\ScottBrady.Pem.Kestrel\Program.cs:line 11
Aborted (core dumped)

**Comment by hvidgaard** [comment] 2021-01-14 14:00
@sukney It's not released yet. You can follow it [here](https://github.com/dotnet/runtime/pull/46904).

**Comment by hvidgaard** [comment] 2021-01-15 13:55
I can confirm that installing the root CA fixes the problem at our end, and I expect the next bugfix release (5.0.3) works without the workaround. Thanks for the help @wfurt, it is much appreciated.
