### ISSUE TITLE
VSCode TextMate Grammar edge case

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#20592] opened 2020-04-06 23:26 UTC
While doing my verification I ran into a case where textmate seems to have gone off the rails:
![textmate](https://user-images.githubusercontent.com/14987221/78614270-f9007780-7822-11ea-8231-3da459420e47.PNG)

Repo steps:
1. dotnet new blazorserver
1. Open NavMenu.razor
1. Edit until it looks like:
```razor
<div class="top-row pl-4 navbar navbar-dark">
    <a class="navbar-brand" href="">mvc</a>
    <button class="navbar-toggler" @onclick="ToggleNavMenu">
        <span class="navbar-toggler-icon"></span>
    </button>
</div>

<div class="@NavMenuCssClass" @onclick="ToggleNavMenu">
    <ul class="nav flex-column">
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="" Match="NavLinkMatch.All">
                <span class="oi oi-home" aria-hidden="true"></span> Home
            </NavLink>
        </li>
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="counter">
                <span class="oi oi-plus" aria-hidden="true"></span> Counter
            </NavLink>
        </li>
        <li class="nav-item px-3">
            <NavLink class="nav-link" href="fetchdata">
                <span class="oi oi-list-rich" aria-hidden="true"></span> Fetch data
            </NavLink>
        </li>
    </ul>
</div>

@functions{
    public void SomeOtherMethod()
    {
        var i = 1;
    }

    interface Foo{}

    class Bar: Foo{}
}

@code {
    private bool collapseNavMenu = true;

    private string NavMenuCssClass => collapseNavMenu ? "collapse" : null;

    private void ToggleNavMenu()
    {
        <text></text>
        collapseNavMenu = !collapseNavMenu;
    }
}
```
Note that `class Bar: Foo{}` is miscolored.

**Comment by ryanbrandenburg** [comment] 2020-04-06 23:28
@NTaylorMullen FYI for textmate.

**Comment by NTaylorMullen** [comment] 2020-04-06 23:40
Duplicate of https://github.com/dotnet/aspnetcore/issues/18864

**Closed by NTaylorMullen** 2020-04-06 23:40 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-mvc, feature-razor.tooling
