### ISSUE TITLE
Blazor WebAssembly HttpContext is always null

### ISSUE THREAD

**Issue by roysurles** [dotnet/aspnetcore#22820] opened 2020-06-11 13:36 UTC
### Describe the bug
Create new Blazor WebAssembly app.  Try to access HttpContext from HttpContextAccessor and HttpContext is always null.

### To Reproduce
1) Create new Blazor WebAssembly app
2) In Main method of Program.cs of Client project, add:
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<HttpContextAccessor>();
3) Inject HttpContextAccessor into any page
@inject Microsoft.AspNetCore.Http.HttpContextAccessor HttpContextAccessor
4) Try to access HttpContextAccessor.HttpContext and HttpContext is always null

Is there another way to get to TraceIdentifier, Session.Id, etc.?

### Exceptions (if any)
None

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`
PS C:\Users\Roy> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.400-preview-015151
 Commit:    0755a9e324

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.400-preview-015151\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\Users\Roy>

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
VS2019 16.6.2 on Windows 10

**Comment by roysurles** [comment] 2020-06-11 13:37
ammending #2:
In Main method of Program.cs of Client project, add:
```
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped<HttpContextAccessor>();
```

**Comment by pranavkm** [comment] 2020-06-11 14:12
A Blazor WebAssembly application runs inside the user's browser sandbox, not in an ASP.NET Core server process. This would explain why it's unavailable. What is it that you're trying to do with the `HttpContext`?

**Comment by roysurles** [comment] 2020-06-11 14:20
I would like to get the SessionId or TraceIdentifier to trace a complete transaction from UI thru WebApi.

**Comment by pranavkm** [comment] 2020-06-11 16:39
Our recommendation would be to set up an API on the server that exposes the trace-identifier.

**Comment by DamianEdwards** [comment] 2020-06-11 18:05
@pranavkm isn't the trace identifier different per request? If the goal is to trace something from the UI through to the web API on the server (and even beyond) I think the trace identifier has to originate from the UI itself, be passed into the API call (a header would be good) and then have the server side code use that as the seed for the trace identifier from there on.

@shirhatti @davidfowl can this be achieved with standard header names and value formats and our support for W3C Trace Context and Open Telemetry?

**Comment by pranavkm** [comment] 2020-06-11 18:28
The way I understood it was that they needed an identifier to uniquely track a session, not necessarily ASP.NET Core's request identifier which is why we recommended having an API to do this. WASM currently does not have a way to send down additional parameters as part of the initial rendering. However, you could get an equivalent behavior by fetching it during the first render.

**Comment by DamianEdwards** [comment] 2020-06-11 18:31
I guess it all depends on the desired scope of the transaction tracking. In reality one might want both, e.g. a session identifier that correlates to the user session, a transaction identifier that correlates to the logical transaction from the user's point of view.

**Comment by davidfowl** [comment] 2020-06-11 18:36
Feels very related to the activity and w3c trace context.

**Comment by roysurles** [comment] 2020-06-11 18:42
Thank you for helping.  In a "micro-services" environment or and an environment where there are multiple WebApi calls for a single action invoked by the user, it would be very helpful to have a consistent TraceIdentifier thru-out the transaction for debugging and/or performance, etc.

**Comment by davidfowl** [comment] 2020-06-11 19:53
@roysurles that happens today by default in ASP.NET Core. But nothing is created from the webassembly client today AFAIK.

**Comment by DamianEdwards** [comment] 2020-06-11 20:01
@davidfowl so just setting the outgoing header from the WASM client would make this light-up yeah? Can you point to some pseudo-code as an example?

**Comment by pranavkm** [comment] 2020-06-12 21:02
Parking this in discussion in case @davidfowl wants to respond.

**Comment by DamianEdwards** [comment] 2020-06-23 21:16
We should provide a sample on how to do this today.

**Comment by Otto404** [comment] 2020-10-07 09:29
@DamianEdwards  where do I find the example?

**Comment by steamonimo** [comment] 2020-11-12 12:31
I have the same problem with Blazor on NET5. Our own implementation of an identity provider for mongodb needs to have access to the HttpContext via the injected IHttpContextAccessor. This way we can access HttpContext.User.Claims to retrieve the user id.

**Comment by davidfowl** [comment] 2020-11-12 13:05
This issue should be renamed, accessing the HttpContext in Blazor WASM doesn't make any sense, it's like trying to access the HttpContext in the react or angular. It runs on the client without access to this information. 

It sounds like the original ask was about correlation, as for the auth information @javiercn do we have anything for this on the client?

**Comment by javiercn** [comment] 2020-11-12 13:12
You don't access HttpContext directly on Blazor, you pass the data you need from the context as parameters to the root component on the initial render. I wrote a sample for this [here](https://github.com/javiercn/blazor-server-aad-sample) and there are docs available.

As for accessing the user, the right way to do this is through either `AuthenticationStateProvider` or if you are using CascadingAuthenticationState, then a `Task<AuthenticationState>` cascading parameter.

**Comment by steamonimo** [comment] 2020-11-12 13:14
@javiercn Is your remark true for server sided Blazor as well?

**Comment by javiercn** [comment] 2020-11-12 13:19
Yes. See the guidance [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-5.0#blazor-and-shared-state)

**Comment by javiercn** [comment] 2020-11-12 14:43
I'm closing this issue since we've answered the question, there are docs available and the current behavior is by design.

**Closed by javiercn** 2020-11-12 14:43 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor, question

**Comment by qfyra** [comment] 2020-11-17 17:09
@javiercn Your sample code (blazor-server-aad-sample) doesn't work if a service that needs an injected TokenProvider is added as singleton. For singleton services you will get an AggregateException because you can't consume scoped services from singletons. What do I need to do to be able to inject e.g. a TokenProvider (or similar, in my case I just want to access the current host url, which I've previously accessed through an injected HttpContextAccessor) into a singleton service?

**Comment by javiercn** [comment] 2020-11-17 17:27
@qfyra If you use a singleton service in that context you'll be in trouble, since you will be sharing tokens between users, so such service shouldn't be a singleton on the first place.

**Comment by qfyra** [comment] 2020-11-18 15:17
@javiercn Very true, one would be in trouble in the case of a TokenProvider, but in my case I'm not using the HttpContextAccessor for anything related to users or even a specific session. I'm using it to get the current host URL string, which is already a disclosed and unencrypted piece of data and will be the same for the lifetime of the application. The services that depend on the current host URL string are singleton for a reason, mostly related to performance and syncronization, which is why non-singleton is not an option. 

So, in case anyone comes across this at a later point in time I'll answer my own question. After following the example code provided by @javiercn and also following [these similar instructions, specifically the ones related to the file App.razor](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0#pass-tokens-to-a-blazor-server-app), I was able to construct a "HostProvider", similar to the TokenProvider but with a simple HostUrl string property. I was also able to add the HostProvider as a singleton service instead of a transient/scoped service, which means I can now inject it in my other singleton services. Problem solved for me at least :)
