### ISSUE TITLE
BasePath is not honoured when requesting/serving hot-reload scripts

### ISSUE THREAD

**Issue by schmellow** [dotnet/aspnetcore#53497] opened 2024-01-19 20:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to test and debug a blazor sever application that is served from behind reverse proxy (nginx specifically) with sub-path, hot reload related scripts are not being served/loaded correctly

### Steps To Reproduce

https://github.com/schmellow/BlazorSubfolderIssueRepro

Configuration and steps are described in readme

### .NET Version

8.0.101

### Anything else?

I'm not entirely sure if this an actual bug, a misconfiguration on my part, or an intended behaviour (or rather unsupported use case)

[Existing documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy) talks about using MapBlazorHub (which seems to be doing nothing for SSR apps), and then about changing ```<base>``` tag value in WebAssembly section. It appears you actually need to adjust the latter regardless of the application type, and then also use AddPathBase. After that you will also need to manually add all the required middlewares manually, since default Blazor template relies on implicit middleware registration, and explicit AddPathBase apparently disables/breaks these

**Comment by javiercn** [comment] 2024-01-29 13:07
Dupe of https://github.com/dotnet/aspnetcore/issues/53454

**Closed by javiercn** 2024-01-29 13:07 UTC
Labels: area-blazor
