### ISSUE TITLE
Blazor WebAssembly hot reload failure with `dotnet watch` and .NET 6 Preview 6

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#33741] opened 2021-06-22 06:15 UTC
Repro steps:

- Install .NET 6 Preview 6 (6.0.100-preview.6.21321.10)
- `dotnet new blazorwasm -o BlazorWasmApp`
- `cd BlazorWasmApp`
- `dotnet watch`
- Edit markup in *Pages/Index.razor*

Expected result: Markup change hot reloaded into running app

Actual result:

```
watch : File changed: C:\Users\daroth\desktop\BlazorWasmApp\Pages\Index.razor.
watch : Received 0 from browser in [Count: 1, MessageType: Binary, EndOfMessage: True].
watch : Received failed apply from delta applier.
watch : Unable to handle changes to C:\Users\daroth\desktop\BlazorWasmApp\Pages\Index.razor.
watch : Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
```

```
Unhandled Exception:
blazor.webassembly.js:1 System.Text.Json.JsonException: ByteArraysToBeRevived is empty.
blazor.webassembly.js:1    at Microsoft.JSInterop.Infrastructure.ByteArrayJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in Microsoft.JSInterop.dll:token 0x6000050+0x12
blazor.webassembly.js:1    at System.Text.Json.Serialization.JsonConverter`1[[System.Byte[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Byte[]& value) in System.Text.Json.dll:token 0x6000790+0xd6
blazor.webassembly.js:1    at System.Text.Json.Serialization.JsonConverter`1[[System.Byte[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x600077c+0x1a7
blazor.webassembly.js:1    at System.Text.Json.Serialization.JsonConverter`1[[System.Byte[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x600077b+0x0
blazor.webassembly.js:1    at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000391+0x14
blazor.webassembly.js:1    at System.Text.Json.JsonSerializer.ReadUsingMetadata[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo) in System.Text.Json.dll:token 0x60003b2+0x2e4
blazor.webassembly.js:1    at System.Text.Json.JsonSerializer.ReadUsingOptions[Object](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options) in System.Text.Json.dll:token 0x60003b1+0x8
blazor.webassembly.js:1    at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options) in System.Text.Json.dll:token 0x60003ae+0x14
blazor.webassembly.js:1    at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes) in Microsoft.JSInterop.dll:token 0x6000057+0xd7
blazor.webassembly.js:1    at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson) in Microsoft.JSInterop.dll:token 0x6000056+0x6f
blazor.webassembly.js:1    at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson) in Microsoft.JSInterop.dll:token 0x6000053+0x17
blazor.webassembly.js:1    at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x60000a6+0x1c
```

**Comment by danroth27** [comment] 2021-06-22 06:29
Also repros with 6.0.100-preview.7.21321.6

**Comment by danroth27** [comment] 2021-06-22 06:29
@pranavkm @lambdageek

**Comment by pranavkm** [comment] 2021-06-22 16:34
Dupe of https://github.com/dotnet/aspnetcore/issues/33756.

**Closed by pranavkm** 2021-06-22 16:34 UTC
Labels: area-blazor, blazor-wasm, feature-dotnetwatch
