### ISSUE TITLE
Blazor -  Cannot implicitly convert type 'Microsoft.AspNetCore.Components.ElementReference' when upgraded to VS 17.6.0

### ISSUE THREAD

**Issue by vladop** [dotnet/aspnetcore#48327] opened 2023-05-19 10:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading my VS from 17.5.5 to 17.6.0 my Blazor application how has lot of errors. Most of them are :  Cannot implicitly convert
type 'Microsoft.AspNetCore.Components.ElementReference' to MyComponent.
MyComponent inherits some other component.

This are relevant SO issues from today and yesterday, people have problem with something breaking going on:
 - https://stackoverflow.com/questions/76286911/error-cs0029-cannot-implicitly-convert-type-microsoft-aspnetcore-components-el
 - https://stackoverflow.com/questions/76274539/maui-blazor-cs0029-when-passing-component-ref

### Steps To Reproduce

Create .net7 blazor project
Create component which inherits from some other
Now, use this component somewhere <MyComponent @ref="myRef" /> and use @andrefboliveira 

This used to work in 17.5.5

It is not problem for me to downgrade Visual Studio but on our CI/CD build inside docker fails since it pulls
dotnet build tooling from mcr.microsoft

### .NET Version

7.0.302

**Comment by ScarletKuro** [comment] 2023-05-19 10:35
Duplicate of https://github.com/dotnet/razor/issues/8727

**Closed** 2023-05-19 12:50 UTC
Labels: area-blazor
