### ISSUE TITLE
Server Side Blazor: CSS Animations Elements Run Twice

### ISSUE THREAD

**Issue by codemonkeh-dave** [dotnet/aspnetcore#11975] opened 2019-07-08 18:56 UTC
### Describe the bug
When you add css animations (such as animation.css) that start on display, they appear to run twice. This issue does not appear locally but does when hosted on a web server.

### To Reproduce
1. Create a new `server side Blazor Website`
2. Add a reference to `animat.css` in the `_Host.cshtml` file
```
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" rel="stylesheet"/>
```
3. Add an animation to a div
``` html
<div class="animated fadeIn">
    <h1>Hello, world!</h1>
    Welcome to your new app.
</div>
```
4. Upload website to a web server

### Expected behavior
Animations should run once (one fade in)

### Screenshots
![Issue](https://user-images.githubusercontent.com/6661533/60835112-45e2ef00-a1ba-11e9-93fd-9e223deb4e33.gif)

**Comment by mkArtakMSFT** [comment] 2019-07-09 16:37
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by enetstudio** [comment] 2019-07-09 17:45
This is perhaps because the home page is rerendered. I think you should try to find out the reason to this rerendering (I think it is by design), and prevent a second use of class="animated fadeIn" by assigning an empty string to the class attribute (class="")

Hope this helps...

**Comment by Programmer-david** [comment] 2019-07-10 12:09
> This is perhaps because the home page is rerendered. I think you should try to find out the reason to this rerendering (I think it is by design), and prevent a second use of class="animated fadeIn" by assigning an empty string to the class attribute (class="")
> 
> Hope this helps...

Thanks for the suggestion @enetstudio I assumed I would have to remove the class as soon as the page rendered. Do you have any suggestion on how to achieve this? I assume I can't do this server side with blazor as web server latency will mean it will take too long to complete.

**Comment by peterMaclean** [comment] 2020-04-08 18:39
I know this is a pretty old issue, but since it's still open and as someone who's just come across this problem myself, I just thought I'd point out that this likely due to the fact that you're using `RenderMode.ServerPrerendered` to render your component.

```csharp
@(await Html.RenderComponentAsync<App>(RenderMode.ServerPrerendered))
```

If my understanding is correct, due to the way `ServerPrerendered` works, you're effectively rendering the component twice, which would explain the issue with the animation.

Unless you really need to use `ServerPrerendered` for some reason, one way to solve this issue would be to use `Server` instead.

```csharp
@(await Html.RenderComponentAsync<App>(RenderMode.Server))
```

You should find that your animation will work just fine after that.

**Comment by SteveSandersonMS** [comment] 2020-10-14 14:07
@peterMaclean is correct.

I'll close this as answered.

**Closed by SteveSandersonMS** 2020-10-14 14:07 UTC
Labels: area-blazor, investigate
