### ISSUE TITLE
Is it possible to invoke components to the project by including the library in the blazor runtime

### ISSUE THREAD

**Issue by burakakca** [dotnet/aspnetcore#22399] opened 2020-05-31 12:08 UTC

**Comment by javiercn** [comment] 2020-05-31 13:07
@burakakca thanks for contacting us.

Can you please clarify what you are trying to achieve?

**Comment by burakakca** [comment] 2020-06-09 16:19
I have the idea of downloading and using a widget while the project is live

**Comment by burakakca** [comment] 2020-06-09 16:20
Like wordpress

**Comment by javiercn** [comment] 2020-06-09 16:27
@burakakca I think you might be looking at something like [this](https://github.com/dotnet/aspnetcore/issues/5465) which is in our roadmap.

I'm closing this issue as a dupe of #5465.

For the time being we don't have a built-in solution, but you can look at some available third-party solutions.

**Closed by javiercn** 2020-06-09 16:27 UTC
Labels: Needs: Author Feedback, area-blazor
