### ISSUE TITLE
Authentication fails with new ASP.NET Core hosted Blazor WebAssembly app and Microsoft Identity Platform

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#44288] opened 2022-09-30 17:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Authentication-fails-with-new-ASPNET-Co/10154320)._

---
Repro steps:
- Install VS 17.4 P2.1 with web workload
- Create new ASP.NET Core hosted Blazor WebAssembly app with Microsoft Identity Platform auth
- Follow the wizard to configure authentication for the app
- Run the app
- Try to login

Expected result: Login succeeds.
Actual result: A dialog briefly displays and then disappears and the app browses to /authentication/login and then gets stuck on a page that says "Checking login state..."

---
#### Daniel Roth [MSFT] on 9/21/2022, 00:18 PM: 

(private comment, text removed)
#### Feedback Bot on 9/21/2022, 08:05 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MackinnonBuck** [comment] 2022-09-30 17:50
From @danroth27's comment on the original issue:

In the browser dev tools I see the following error:
Failed to load resource: the server responded with a status of 400 (Bad Request)

Request URL: https://login.microsoftonline.com/22222222-2222-2222-2222-222222222222/v2.0/.well-known/openid-configuration
Request Method: GET
Status Code: 400 Bad Request

```
{“error”:“invalid_tenant”,“error_description”:“AADSTS90002: Tenant ‘22222222-2222-2222-2222-222222222222’ not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\r\nTrace ID: 25ba7afe-2daf-4f28-aa9b-23b0501b2f01\r\nCorrelation ID: b6c292b3-5537-4b4a-bb92-6d80cf54f325\r\nTimestamp: 2022-09-21 19:15:40Z”,“error_codes”:[90002],“timestamp”:“2022-09-21 19:15:40Z”,“trace_id”:“25ba7afe-2daf-4f28-aa9b-23b0501b2f01”,“correlation_id”:“b6c292b3-5537-4b4a-bb92-6d80cf54f325”,“error_uri”:“https://login.microsoftonline.com/error?code=90002”}
```

So it looks like the tenant ID didn’t get configured correctly by the tooling.

**Comment by blowdart** [comment] 2022-09-30 17:55
That would fall under tooling then.

**Comment by adityamandaleeka** [comment] 2022-09-30 20:05
@vijayrkn Does your team own this tooling?

**Comment by vijayrkn** [comment] 2022-09-30 20:07
yes, you can move this to the https://github.com/dotnet/scaffolding repo

**Comment by zahalzel** [comment] 2022-09-30 20:35
Closing as not reproducible

**Closed by zahalzel** 2022-09-30 20:35 UTC
Labels: area-identity, Tooling, Author: Migration Bot :robot:

**Comment by adityamandaleeka** [comment] 2022-09-30 21:00
FYI @danroth27 do you have a repro for this?
