### ISSUE TITLE
MaxLength and StringLengh attribute is adding maxlength html attribute to the input field.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#19439] opened 2020-02-28 15:22 UTC
For the following property:

    [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter your first name")]
    [MaxLength(30, ErrorMessage = "{0} can not more than {1} characters.")]
    [Display(Name = "First Name")]
    public string FirstName { get; set; }

**ASP.NET Core 3.1** is generating the following input field:

`<input class="form-control is-invalid" type="text" data-val="true" data-val-maxlength="First Name can not more than 30 characters." data-val-maxlength-max="30" data-val-required="Please enter your first name" id="FirstName" maxlength="30" name="FirstName" aria-required="true" aria-invalid="true" aria-describedby="FirstName-error">`

Surprisingly its adding `maxlength="30"` html attribute to the input field and hence user is not being allowed to type more than 30 characters and therefore `First Name can not more than 30 characters.` error is never showing.

Even if user paste more than 30 characters it silently truncating the string to 30 characters without showing the validation error message `First Name can not more than 30 characters.`.

Please look into this issue. This will cause major problem to the applications those have been updated to ASP.MET Core 3.1.

Thank you.

**Comment by pranavkm** [comment] 2020-02-28 16:32
@TanvirArjel this looks like a duplicate of https://github.com/dotnet/aspnetcore/issues/18607. Unfortunately we don't have a very good way to turn off this behavior from the runtime at this point. We'll look in to addressing this in the next major release. In the meanwhile, you might be able to write some JavaScript to remove these attributes:

```JS
   document.addEventListener("DOMContentLoaded", function(){
        for (const item of document.querySelectorAll('input[maxlength][data-val-maxlength]')) {
         item.removeAttribute("maxlength");
       }
    });
```

**Comment by TanvirArjel** [comment] 2020-02-29 06:22
@pranavkm 

> We'll look in to addressing this in the next major release.

May be it should not take so much time. So you can add this to **Milestone 5.0**.

**Closed** 2020-03-24 05:03 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-mvc
