### ISSUE TITLE
System.NullReferenceException at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_HasFormContentType()

### ISSUE THREAD

**Issue by rexpan** [dotnet/aspnetcore#41574] opened 2022-05-08 10:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Sometime** I got the error `System.NullReferenceException` at `Microsoft.AspNetCore.Http.DefaultHttpRequest.get_HasFormContentType()` for several GET API.

### Exceptions (if any)

```
Error: Object reference not set to an instance of an object.System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_HasFormContentType()
at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.CreateValueProviderAsync(ValueProviderFactoryContext context)
at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.TryCreateAsync(ActionContext actionContext, IList`1 factories)
at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
```

### .NET Version

6.0.202

**Comment by davidfowl** [comment] 2022-05-08 16:15
That's really strange. Are you running on IIS or Kestrel? Do you have a repro? Is that the entire call stack?

**Comment by arisewanggithub** [comment] 2022-06-03 21:04
Our service has the same issue. This happens for a very small portion of the requests.

**Comment by davidfowl** [comment] 2022-06-03 22:11
Are you using application insights?

**Comment by arisewanggithub** [comment] 2022-06-03 22:12
yes.

**Comment by arisewanggithub** [comment] 2022-06-03 22:22
We use Kestrel. No idea how to repro it. This is just observed from the logs from app insights from our production traffic. 
The exception is thrown inside the await _next(context) in the last middleware we have. So, it shouldn't be caused by our own code.
public async Task Invoke(HttpContext context)
        {
            ...
            await _next(context);
        }

**Comment by arisewanggithub** [comment] 2022-06-03 22:27
This is our stack trace. To remove project related code, I renamed our last middleware to MyCustomMiddleware and removed the stacks before it. But it should be enough to show where the issue is:
System.NullReferenceException:
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_HasFormContentType (Microsoft.AspNetCore.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.CreateValueProviderAsync (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider+<CreateAsync>d__3.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider+<TryCreateAsync>d__4.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider+<>c__DisplayClass0_0+<<CreateBinderDelegate>g__Bind|0>d.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker+<<InvokeInnerFilterAsync>g__Awaited|13_0>d.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeFilterPipelineAsync>g__Awaited|20_0>d.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeAsync>g__Logged|17_1>d.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker+<<InvokeAsync>g__Logged|17_1>d.MoveNext (Microsoft.AspNetCore.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware+<<Invoke>g__AwaitRequestTask|6_0>d.MoveNext (Microsoft.AspNetCore.Routing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at MyCustomMiddleware

**Comment by davidfowl** [comment] 2022-06-08 02:39
Are you using SQL server anywhere?

**Comment by arisewanggithub** [comment] 2022-06-08 02:40
> 

Nope

**Comment by davidfowl** [comment] 2022-06-08 03:05
Here's an example of an issue we just fixed in SqlClient that appeared as a null reference exception in ASP.NET Core when used with app insights https://github.com/dotnet/aspnetcore/issues/41924.

@okolvik-avento did a really helpful investigation by getting us a crash dump we could use to quickly identify the problem. He's written a helpful guide that could assist you in collecting a dump here https://okolvik-avento.github.io/pages/2022-06-05-creating-iis-userdumps

**Comment by arisewanggithub** [comment] 2022-06-08 03:19
Unfortunately, we don't use IIS. And I can't repro it. So, it's really hard to get a crash dump. For logging, we use ILogger. Only in some special cases where we can't get an instance of ILogger, we use TelemetryClient directly.

**Comment by davidfowl** [comment] 2022-06-08 04:03
OK here's the deal:
- I won't be able to help you diagnose the problem unless I have access to the source *and* or dumps.
- If you're running on windows, you might be able to use debug diag to get a crash dump when this happens
- If you're on Linux there are other ways but they are harder.

Read the other issue and see what the issue was and what the fix was. That will help you narrow your code down to what parts of your code might be a problem. It could be logger, direct usage of the telemetry client or indirect usage.

**Comment by ip-dsosunov** [comment] 2022-06-09 10:04
In my project, we've got the same issue.

I have found a similar issue discussed in the 2020 year.
https://github.com/dotnet/aspnetcore/pull/25892

Probably the reason is concurrent access to FeaturesCollection.

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Http/Http/src/Internal/DefaultHttpRequest.cs

```
    public override bool HasFormContentType
    {
        get { return FormFeature.HasFormContentType; }
    }

    private IFormFeature FormFeature =>
        _features.Fetch(ref _features.Cache.Form, this, _newFormFeature)!;
```

In our case, I suppose ```_features.Cache``` is null, but I don't know why.

We are using Kestrel not IIS and running inside Azure with out-of-process model

**Comment by davidfowl** [comment] 2022-06-09 14:36
Oh I know why it's null, you can read more about it here https://github.com/dotnet/aspnetcore/issues/42040.

But the comment I wrote right above this will help you debug.

**Closed** 2022-06-16 16:01 UTC
Labels: Needs: Author Feedback, feature-Model-Binding, Status: No Recent Activity, area-web-frameworks
