### ISSUE TITLE
Xamarin iOS: SignalR nuget package throws MissingMethodException

### ISSUE THREAD

**Issue by petro2050** [dotnet/aspnetcore#36763] opened 2021-09-20 21:20 UTC
I'm on version 6.0.0-rc.1.21452.15 for Microsoft.AspNetCore.SignalR.Client, and I'm getting a runtime exception when I use SignalR in a Xamarin.iOS project.

> **System.MissingMethodException:** 'Loading...'
> 
> 2021-09-20 16:09:26.091 MyClient.iOS[3951:872602] [AppCenterCrashes] ERROR: +[MSACWrapperLogger MSACWrapperLog:tag:level:]/10 Unhandled Exception:
> System.MissingMethodException: Method not found: Microsoft.AspNetCore.Http.Connections.NegotiationResponse Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(System.ReadOnlySpan`1<byte>)
>   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471 
>   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync (System.Uri url, System.Net.Http.HttpClient httpClient, Microsoft.Extensions.Logging.ILogger logger, System.Threading.CancellationToken cancellationToken) [0x0003d] in <f94565406ea347168482bf5ef345fe39>:0 
>   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotia
> tionResponseAsync (System.Uri uri, System.Threading.CancellationToken cancellationToken) [0x00011] in <f94565406ea347168482bf5ef345fe39>:0 
>   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x0017b] in <f94565406ea347168482bf5ef345fe39>:0 
>   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00127] in <f94565406ea347168482bf5ef345fe39>:0 
>   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <f94565406ea347168482bf5ef345fe39>:0 
>   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00091] in <f94565406ea347168482bf5ef345fe39>:0 
>   at Microsoft.AspN
> etCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x00114] in <f94565406ea347168482bf5ef345fe39>:0 
>   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x001bf] in <f94565406ea347168482bf5ef345fe39>:0 
>   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore (System.Threading.CancellationToken cancellationToken) [0x000a5] in <51877fb55d294afdad19ca4c17a29fe8>:0 
>   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner (System.Threading.CancellationToken cancellationToken) [0x001a3] in <51877fb55d294afdad19ca4c17a29fe8>:0 
>   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <51877fb55d294afdad19ca4c17a29fe8>:0 
>   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync (System.Threading.CancellationToken cancellationToken) [0x00091] in <518

**Comment by halter73** [comment] 2021-09-21 21:35
This looks like this is a dupe of https://github.com/mono/mono/issues/20805. Does [this workaround](https://github.com/mono/mono/issues/20805#issuecomment-791440473) solve your issue?

**Closed** 2021-09-22 21:21 UTC
Labels: Needs: Author Feedback, area-signalr
