### ISSUE TITLE
Default Blazor Wasm template does not run

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#38195] opened 2021-11-09 06:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Default-Blazor-Wasm-template-does-not-ru/1574511)._

---
Steps to recreate
Create a new Blazor WASM project
Try to run it
Witness error stating could not load file or assembly system.io.pipelines version 6.0.0
[Snag_2f5222.png] (https://aka.ms/dc/file?name=Ba3b61b749f384856a20de61249130035637720031527980900_Snag_2f5222.png&tid=a3b61b749f384856a20de61249130035637720031527980900)

---
#### Feedback Bot on 11/8/2021, 01:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Artak Mkrtchyan on 11/8/2021, 02:18 PM: 

<p>Thanks for contacting us. Can you please share the content of the .csproj file ? Thanks.</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Kevon Houghton on 11/8/2021, 03:39 PM: 

<p>FYI: It works on a brand new install of Windows 11, but not my current install of Windows 10.<br>
I have previously had several versions of Visual Studio installed on this machine.<br>
I may try to format and upgrade to Windows 11 and try again.</p>
<p>One thing though, even on the Windows 11, with server hosted blazor wasm, debugger attached to the server project, hot reload is not working.  I make some simple HTML changes and they are never reflected in the browser.</p>

#### Kevon Houghton on 11/8/2021, 02:28 PM: 

<p>Literally, create a new blazor wasm project</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=Bcdceb8472985477ba586e31f1a47c11b637720072561524977_Test.zip&amp;tid=cdceb8472985477ba586e31f1a47c11b637720072561524977">Test.zip</a></p>

#### Artak Mkrtchyan on 11/8/2021, 04:21 PM: 

<p>Thanks for sharing this. The project looks correct. You may be hitting this issue: <a target='_blank' href="https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows">https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#2-upgrade-of-visual-studio-or-net-sdk-from-earlier-builds-can-result-in-a-bad-path-configuration-on-windows</a></p>
<p>Can you try to fix your path to dotnet and see whether that resolved it?</p>

#### Kevon Houghton on 11/8/2021, 04:32 PM: 

<p>It does not look like that’s the issue<br>
<a target='_blank' href="https://aka.ms/dc/file?name=B3135205918ba435cad7f8002ef29b0f0637720147663597719_Snag_8e0423.png&amp;tid=3135205918ba435cad7f8002ef29b0f0637720147663597719">Snag_8e0423.png</a></p>

#### Artak Mkrtchyan on 11/8/2021, 05:00 PM: 

<p>Let’s keep the debugging issue aside for now, as the app should first run before debugging.<br>
If you try to run this using the CLI (dotnet run) - does it work?</p>

#### Kevon Houghton on 11/8/2021, 06:36 PM: 

<p>Negative:</p>
<p>S C:\Users\khoughton\source\repos\Test\test\server&gt; dotnet run<br>
Building…<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. System.BadImageFormatException: Assembly file ‘C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\ref\net6.0\System.Net.WebProxy.dll’ could not be opened – PE image doesn’t contain managed metadata. [C:\Users\khoughton\source\repos\Test\test\Shared\Test.Shared.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Shared.AssemblyNameExtension.GetAssemblyNameEx(String path) [C:\Users\khoughton\source\repos\Test\test\Shared\Test.Shared.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Tasks.SystemState.GetAssemblyName(String path) [C:\Users\khoughton\source\repos\Test\test\Shared\Test.Shared.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName) [C:\Users\khoughton\source\repos\Test\test\Shared\Test.Shared.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. System.BadImageFormatException: Assembly file ‘C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\ref\net6.0\System.Net.WebProxy.dll’ could not be opened – PE image doesn’t contain managed metadata. [C:\Users\khoughton\source\repos\Test\test\Client\Test.Client.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Shared.AssemblyNameExtension.GetAssemblyNameEx(String path) [C:\Users\khoughton\source\repos\Test\test\Client\Test.Client.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Tasks.SystemState.GetAssemblyName(String path) [C:\Users\khoughton\source\repos\Test\test\Client\Test.Client.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName) [C:\Users\khoughton\source\repos\Test\test\Client\Test.Client.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. System.BadImageFormatException: Assembly file ‘C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\ref\net6.0\System.Net.WebProxy.dll’ could not be opened – PE image doesn’t contain managed metadata. [C:\Users\khoughton\source\repos\Test\test\server\Test.Server.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Shared.AssemblyNameExtension.GetAssemblyNameEx(String path) [C:\Users\khoughton\source\repos\Test\test\server\Test.Server.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Tasks.SystemState.GetAssemblyName(String path) [C:\Users\khoughton\source\repos\Test\test\server\Test.Server.csproj]<br>
C:\Program Files\dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3246:    at Microsoft.Build.Tasks.ReferenceTable.SetPrimaryAssemblyReferenceItem(ITaskItem referenceAssemblyName) [C:\Users\khoughton\source\repos\Test\test\server\Test.Server.csproj]<br>
Unhandled exception. System.BadImageFormatException: Could not load file or assembly ‘System.IO.Pipelines, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51’. Format of the executable (.exe) or library (.dll) is invalid.<br>
File name: ‘System.IO.Pipelines, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51’<br>
at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions<code>1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource) at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions</code>1 options, IEnumerable<code>1 transportFactories, IEnumerable</code>1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)<br>
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span<code>1&amp; arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor</code>2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)<br>
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)<br>
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<code>2.VisitCallSite(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType) at System.Collections.Concurrent.ConcurrentDictionary</code>2.GetOrAdd(TKey key, Func`2 valueFactory)<br>
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)<br>
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)<br>
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)<br>
at Microsoft.AspNetCore.Builder.WebApplication.get_ServerFeatures()<br>
at Microsoft.AspNetCore.Builder.WebApplication.Microsoft.AspNetCore.Builder.IApplicationBuilder.get_ServerFeatures()<br>
at Microsoft.AspNetCore.Builder.HttpsPolicyBuilderExtensions.UseHttpsRedirection(IApplicationBuilder app)<br>
at Program.&lt;Main&gt;$(String[] args) in C:\Users\khoughton\source\repos\Test\test\server\Program.cs:line 24</p>

#### Artak Mkrtchyan on 11/8/2021, 10:07 PM: 

<p>Thanks for additional information. I’ll move this issue over to GitHub to try to find the right owners for this. That said, it feels like you may indeed run into some problem with mixed installations, and reinstalling the latest .NET SDK may help.</p>

---
### Original Solutions
(no solutions)

**Comment by adityamandaleeka** [comment] 2021-11-10 21:53
> FYI: It works on a brand new install of Windows 11, but not my current install of Windows 10.
I have previously had several versions of Visual Studio installed on this machine.
I may try to format and upgrade to Windows 11 and try again.

This could be related to the PATH environment issue that was mentioned above. Since we don't have a repro of this issue there's unfortunately not much we can do here.

**Comment by halter73** [comment] 2021-11-10 21:59
This seems to be environmental. This does work on my Win 10 machine with the 6.0.100 SDK. Maybe the SDK installation got corrupted somehow?

Thanks for the report though @kevonh. Please file a new issue if you can reproduce this in a clean environment with the 6.0.100 SDK.

```
~\Downloads\Test❯ dotnet new globaljson --sdk-version 6.0.100
The template "global.json file" was created successfully.                                               687ms 13:55:47
~\Downloads\Test❯ cd .\Test\Server\                                                                           13:55:51
~\Downloads\Test\Test\Server❯ dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7093
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5093
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\halter73\Downloads\Test\Test\Server\
```

**Comment by khoughton-Landmark** [comment] 2021-11-10 22:02
Are there any other troubleshooting steps you could suggest?  Un-install / Re-Install the SDK?  Might that help?

**Comment by halter73** [comment] 2021-11-10 22:45
Reinstalling the SDK might help. It'd be interesting to check if ‘C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\ref\net6.0\System.Net.WebProxy.dll’ is accessible and valid by opening it in ilspy or something. This is a ref assembly, so there shouldn't be any implementation, but you should be able to read it.

![image](https://user-images.githubusercontent.com/54385/141205856-3931546e-edd8-4e03-8286-922a5bde3412.png)

You can also up the verbosity of the msbuild warnings. https://www.hanselman.com/blog/interesting-bugs-msb3246-resolved-file-has-a-bad-image-no-metadata-or-is-otherwise-inaccessible-image-is-too-small

**Comment by khoughton-Landmark** [comment] 2021-11-10 23:23
Interestingly, the file does not exist.  It seems it might be a corrupt install of the SDK.  I'll re-install and see if that help
![Snag_a9b41d5](https://user-images.githubusercontent.com/22649000/141209529-df2c9e63-19a8-4561-8d0d-f0be89137f09.png)
s.

**Comment by khoughton-Landmark** [comment] 2021-11-10 23:35
Did not work... Still hitting the same exception.  Oddly, the file you indicate should be there is still not there after re-installing .Net 6 and SDK

**Comment by halter73** [comment] 2021-11-11 01:37
`System.Net.WebProxy.dll` is supposed to be in `Microsoft.NETCore.App.Ref` instead of `Microsoft.AspNetCore.App.Ref`. Sadly, it does seem like there's something corrupted about your dotnet installation that isn't being fixed by a simple re-install.

> I may try to format and upgrade to Windows 11 and try again.

If you cannot quickly figure out exactly what is corrupted using verbose build logs and formatting is an option, I'd consider it.

**Comment by kevonh** [comment] 2021-11-12 18:36
Upgraded to Win 11, issue is resolved.  Please close.

**Closed** 2021-11-12 21:24 UTC
Labels: area-runtime, Author: Migration Bot :robot:
