### ISSUE TITLE
Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005

### ISSUE THREAD

**Issue by Marius-du-Toit** [dotnet/aspnetcore#58902] opened 2024-11-12 23:17 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have just upgrade VS to 17.12.0, and the build error "Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005" is showing. Prio version did not fail the build on this.

### Expected Behavior

Should build the same project and be backwards compatible.

### .NET Version

9.0.100

**Comment by BrennanConroy** [comment] 2024-11-12 23:23
Dupe of https://github.com/dotnet/aspnetcore/issues/47912

**Closed** 2024-11-14 12:27 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-infrastructure, Status: Resolved
