### ISSUE TITLE
Failure to launch debug adapter - unable to launch browser

### ISSUE THREAD

**Issue by markiemarkus** [dotnet/aspnetcore#22871] opened 2020-06-12 11:31 UTC
This is caused with a Blazor WebAssembly app. All latest stable versions.
Then changing

  "windowsAuthentication": true,
  "anonymousAuthentication": false,

The app runs correctly with following section settings.
  "windowsAuthentication": false
    "anonymousAuthentication": true,

full file error and full file 
![error](https://user-images.githubusercontent.com/8809743/84498427-8ee3d300-aca8-11ea-904a-65b5d9528de8.PNG)

{
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": false,
    "iisExpress": {
      "applicationUrl": "http://localhost:9698",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
    },
    "BlazorWA": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
    }
  }
}

**Comment by javiercn** [comment] 2020-06-12 14:15
@markiemarkus thanks for contacting us.

This is due to the debugger proxy running on the same process as the hosting application. We have plans to move the proxy to a separate process and that should solve this issue.

Dupe of #21466 

/cc: @captainsafia

**Closed by javiercn** 2020-06-12 14:15 UTC
Labels: area-blazor, blazor-wasm
