### ISSUE TITLE
Blazor Stream Rendering not working on Azure Web Apps

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet/aspnetcore#54390] opened 2024-03-06 00:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello - I have a blazor application that has stream rendering activated on multiple pages. It works without any issues locally. I have deployed it to Azure Web app. The page behaves as there is no stream rendering. Is there a particular configuration that we need to use (or not use) to enable stream rendering on Azure web app

**Comment by javiercn** [comment] 2024-03-06 11:57
@darena-pjindal thanks for contacting us.

* Are you able to make it work with a project created straight out of the template?
* Are you using the default publish settings to Azure Web Apps?
* Is there a public URL where we can see this not working?
* Are you using any middleware that might be buffering the response?

**Comment by darena-pjindal** [comment] 2024-03-06 12:25
Hello @javiercn 

I created a new blazor web app from scratch and published it to Azure Web app. The only change I made was to increase the delay on the weather page so the steaming is more visible. You can check the deployed site here - https://blazortestds.azurewebsites.net/weather

There were no other changes made to the default template. Here are the settings from visual studio to deploy 
![image](https://github.com/dotnet/aspnetcore/assets/45796558/c8671081-9514-4462-a54f-939108713544)

Thanks, 
Pawan

**Comment by darena-pjindal** [comment] 2024-03-06 14:19
Hi @javiercn  - I just noticed that if I go directly to the weather page, it does seem to work. However, if I go from the home page to that page, it doesn't seem to work. Our app requires a user to be logged in. Therefore, all our pages (with stream rendering) are viewed from one component to another. Thanks for your help.

**Comment by javiercn** [comment] 2024-03-06 16:12
It's scheduled to go into a servicing release https://github.com/dotnet/aspnetcore/pull/53930

**Comment by javiercn** [comment] 2024-03-06 16:14
@darena-pjindal we are closing this issue as a dupe of https://github.com/dotnet/aspnetcore/issues/52323

You can apply a similar workaround by setting `context.Response.Headers.ContentEncoding = "identity";` on the responses. That should prevent IIS from applying compression

**Comment by darena-pjindal** [comment] 2024-03-06 16:40
Hi @javiercn - thanks for your help. Can you please share more details on how and where I should set this?

**Comment by darena-pjindal** [comment] 2024-03-06 17:12
> You can apply a similar workaround by setting `context.Response.Headers.ContentEncoding = "identity";` on the responses. That should prevent IIS from applying compression

I figured it out. Just added a middleware to handle that. Copying here if someone else also needs it. Thanks again . 

public class PreventCompressionMiddleware
{
    private readonly RequestDelegate _next;

    public PreventCompressionMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        context.Response.OnStarting(() =>
        {
            context.Response.Headers["Content-Encoding"] = "identity";
            return Task.CompletedTask;
        });

        await _next(context);
    }
}

**Closed** 2024-03-06 17:27 UTC
Labels: area-blazor, Needs: Attention :wave:
