### ISSUE TITLE
I got a bug where I can't read custom classes in Razor Page.

### ISSUE THREAD

**Issue by cyberprophet** [dotnet/aspnetcore#48576] opened 2023-06-01 16:24 UTC
### Description

Found markup element with unexpected name 'CoreNavMenu'.

If this is intended to be a component, add a @using directive for its namespace.

### Reproduction Steps

![20230602_011848](https://github.com/dotnet/runtime/assets/48705422/6c4f8c64-5408-4481-bf1e-9e6fb649a642)

### Expected behavior

It was a problem that often occurred when I wrote custom tags on the laser page, but it disappeared.

However, it is found again in this patch.

### Actual behavior

It shows a non-display error (suppression), but it could not be captured.

**Comment by mkArtakMSFT** [comment] 2023-06-01 21:42
Thanks for contacting us. This is due to a recent regression in Razor Compiler, which is being tracked at https://github.com/dotnet/razor/issues/8718.
Please use the provided workaround to unblock while the fix is in progress.

**Closed by mkArtakMSFT** 2023-06-01 21:42 UTC
Labels: area-blazor
