### ISSUE TITLE
Blazor WebAssembly AOT publiish output contains files that should not be published

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#32744] opened 2021-05-16 00:36 UTC
Repro steps:

- Install .NET 6 Preview 4 (6.0.100-preview.4.21255.9)
- AOT compile a Blazor WebAssembly app by publishing it
- Inspect the published output

Expected result:

- Only files that should be published with the app are present in the published wwwroot folder

Actual result:

- Published output contains C code, header files, and other implementation files like:
    - corebindings.c
    - driver.c
    - pinvoke.c
    - pinvoke.h
    - emcc-flags.txt
    - emcc-version.txt
    - etc.

@lewing @pranavkm

**Comment by mkArtakMSFT** [comment] 2021-05-17 16:28
This is most probably caused by the runtime. Will talk to them and update this issue accordingly.

**Comment by mkArtakMSFT** [comment] 2021-05-17 16:28
@eerhardt do you have a tracking issue for this that we can dupe this against?

**Comment by eerhardt** [comment] 2021-05-17 16:32
Seems to be a dupe of https://github.com/dotnet/runtime/issues/48016 (mostly). I guess I wrote it as `.c` and `.h` files, but this also lists `.txt` files.

**Closed** 2021-08-20 21:25 UTC
Labels: bug, area-blazor, blazor-wasm, feature-blazor-aot-compilation
