### ISSUE TITLE
Kestrel TLS certificate inside kubernetes cluster

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#19274] opened 2020-02-24 08:22 UTC
I know Kestrel can be configured for https using PKCS#12 (pfx) certificates, but is there a way for it to be integrated with something like [cert-manager](https://cert-manager.io/) for a simpler and faster way of generating and managing certificates inside a kubernetes cluster?

If not, can Kestrel read pem or der certificates, or pfx is the only supported way of doing this?

**Comment by javiercn** [comment] 2020-02-24 09:31
@mihaimyh thanks for contacting us.

Currently the only file format supported by kestrel through configuration is PFX, but I believe it is possible since .NET Core 3.0 to read the PEM key file + the .cer file and assemble it on to a certificate that you can use with Kestrel.

I believe we have a workitem tracking support for this.

See https://github.com/dotnet/aspnetcore/issues/4706

See https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#cryptographic-key-importexport for the relevant .NET Core APIs to support this.

**Comment by javiercn** [comment] 2020-02-24 09:31
Closing this issue as a dupe of #4706

**Closed by javiercn** 2020-02-24 09:31 UTC
Labels: area-servers, servers-kestrel
