### ISSUE TITLE
Blazor Client environment seems fixed on 'development'

### ISSUE THREAD

**Issue by NibblyPig** [dotnet/aspnetcore#28176] opened 2020-11-26 10:41 UTC
I created a Blazor Client app and what I wanted to do was have a different app config for my dev environment and my server release environment.

The first line of the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-5.0) states:

>When running an app locally, the environment defaults to Development. When the app is published, the environment defaults to Production.

This does not appear to be the case. It comes up as Development for me both times.

In a normal .NET Core app I can do this:

```
return Host.CreateDefaultBuilder(args)
    .UseEnvironment(environmentName)
```

to set the environment.  However the Enivornment of the Blazor Client app is readonly.  It picks up `appsettings.development.json` regardless of if it's built/published in DEBUG or RELEASE configuration.

I can define it in Index.html using the meta tag, however this is static and I can't easily change this. The goal is simply to be able to publish with a different config because my client has the URL of a service it uses and on my development machine, I want it to use the test service and when published live, the live service.

I'm publishing via web deploy to IIS, it mentions putting the environment into a web config but there isn't a web config, plus it's blazor client so it doesn't really have a web config even if IIS does.

Either I'm missing something fundamental or the first line of the documentation above is wrong.

### To Reproduce
Create a blazor client application, create an appsettings.development.json and appsettings.production.json and put something in each. Consume it in the index.razor. Notice that it always uses appsettings.development.json contrary to what the documentation states about when it's published.

### Further technical details

VS 2019 / server 2019

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment] 2021-07-20 17:49
This is a dupe of #28573

**Closed by mkArtakMSFT** 2021-07-20 17:49 UTC
Labels: affected-medium, area-blazor, blazor-wasm, bug, feature-blazor-boot-up, investigate, severity-major
