### ISSUE TITLE
F5 doesn't compile child Razor Component Projects

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#53334] opened 2024-01-12 19:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F5-doesnt-compile-child-Razor-Component/10554328)._

---

[Issue 17.9 P2 Child project not compiling.gif](https://aka.ms/dc/file?name=B5a18011002354c729a0813f64ded070c638400971773342600_Issue_17.9_P2_Child_project_not_compiling.gif&tid=5a18011002354c729a0813f64ded070c638400971773342600)

[BlazorApp.zip](https://aka.ms/dc/file?name=Bfa41431e2f504ca39ec98579e42c5713638400971994447909_BlazorApp.zip&tid=fa41431e2f504ca39ec98579e42c5713638400971994447909)
\[severity:It’s more difficult to complete my work\]  
When creating a Blazor WASM (could be others just what I’ve tried) project and referencing a Razor Component Library making changes in the referenced library are not compiled when pressing F5. However, if a rebuild either at the solution or project (component) level will compile the code and F5 will now act as expected. This is a significant issue if you’re unaware or simply forget (I keep doing it) you’ll be debugging old code wondering why it doesn’t work.

I’ve attached a repro project as well as a screencast demoing the issue.

---
#### Feedback Bot on 1/7/2024, 05:37 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment] 2024-01-15 12:10
Dupe of https://github.com/dotnet/aspnetcore/issues/52148

Disable accelerated builds in Visual Studio. It will be automatically disabled in a future patch of the SDK for wasm projects.
```
<Project>
  <PropertyGroup>
    <AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
</Project>
```

**Comment by garrm** [comment] 2024-01-15 21:06
This seems to have resolved my issue, thanks!

**Closed** 2024-01-16 22:00 UTC
Labels: question, area-blazor, :heavy_check_mark: Resolution: Answered, Author: Migration Bot :robot:, Status: Resolved
