### ISSUE TITLE
How Redirect To Not Found Without Change Url In Blazor .Net 8

### ISSUE THREAD

**Issue by MahdiElahi** [dotnet/aspnetcore#53337] opened 2024-01-12 20:19 UTC
Hi, 
How to redirect user to not found when page is not exists **without change url** in blazor ?

Like this link :  [git not found](https://github.com/asdadasdasdadxc32423sdf)

**Comment by mkArtakMSFT** [comment] 2024-01-23 17:32
Closing as a dupe of https://teams.microsoft.com/l/message/19:meeting_NWZiNGZjM2EtY2E2YS00MWQwLWFiZmUtODI3OTg2Yzg4N2Nj@thread.v2/1706031131747?context=%7B%22contextType%22%3A%22chat%22%7D

**Closed** 2024-01-23 17:33 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor
