### ISSUE TITLE
Browser Data Storage

### ISSUE THREAD

**Issue by boukenka** [dotnet/aspnetcore#18691] opened 2020-01-30 17:18 UTC
### Feature request

Today, there are different packages for managing local and session storage in the browser. Here are some examples: 

- [cloudcrate/BlazorStorage](https://github.com/cloudcrate/BlazorStorage) 
- [BlazorExtensions/Storage](https://github.com/BlazorExtensions/Storage)
- [Blazored/SessionStorage](https://github.com/Blazored/SessionStorage)
- [Blazored/LocalStorage](https://github.com/Blazored/LocalStorage)

Is there a plan to have an '_official_' package provided by default in ASP.NET Core in a Blazor toolkit?

### Further technical details

ASP.NET Core version 3.1.1
Microsoft Edge 81.0.403.1
Blazor Web Assembly with ASP.NET core hosted
Visual Studio 16.5.0 Preview 2.0.

**Comment by mkArtakMSFT** [comment] 2020-01-30 17:38
Thanks for contacting us.
Yes, we are considering such an option. At the moment we have an experimental package https://www.nuget.org/packages/Microsoft.AspNetCore.ProtectedBrowserStorage/0.1.0-alpha.19521.1

**Comment by boukenka** [comment] 2020-01-31 15:03
Thank you @mkArtakMSFT for the quick answer. 😄

**Comment by boukenka** [comment] 2020-02-13 13:23
Thank you @danroth27 for the [#18755](https://github.com/dotnet/aspnetcore/issues/18755) official request. I'll look forward to testing this version of the data storage.

**Comment by mkArtakMSFT** [comment] 2020-05-05 20:35
Closing this as a dupe of the #18755

**Closed by mkArtakMSFT** 2020-05-05 20:35 UTC
Labels: area-blazor, blazor-wasm, enhancement
