### ISSUE TITLE
QuickGrid does not support 'record'-based objects

### ISSUE THREAD

**Issue by danieldegtyarev** [dotnet/aspnetcore#50534] opened 2023-09-05 19:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In case we have 

record Foo(string text);

and 

Foo[] Foos = new [] { new Foo("A"), new Foo("A") };

<QuickGrid TGridItem="Foo" ....

Exception thrown

```
Unhandled exception rendering component: More than one sibling of element 'tr' has the same key value, 'Foo{ text = A }'. Key values must be unique.
```

### Exceptions (if any)

Unhandled exception rendering component: More than one sibling of element 'tr' has the same key value, 'Foo{ text = A }'. Key values must be unique.

### .NET Version

8.0.100-preview.7.23376.3

**Comment by marinasundstrom** [comment] 2023-09-05 22:38
Not strange since records that have the same values are considered equal. 

And if you pass the record objects as `@key` they risk having the same hash code. That is not allowed.

The reason for using `@key` is for Blazor to identify a component based on that key, which will aid in re-rendering.

The question is whether this intentionally

**Comment by marinasundstrom** [comment] 2023-09-06 16:09
@danieldegtyarev Sorry for accidentally closing this.

I'm not sure. If the QuickGrid is supposed to show unique items, then it is not.

In what scenario do you use records to display data like this - that has the same fields? Are you consuming objects, or are you just using records for the simplified syntax?

QuickGrid, to me, is about showing unique items. 

If you want a record to unique then you need to add like an Id field with a unique value.

**Comment by mkArtakMSFT** [comment] 2023-09-06 17:01
Thanks for contacting us, @danieldegtyarev.
Unique items in a QuickGrid should have unique keys. As @marinasundstrom has mentioned, this is not a bug. You should provide unique keys for your objects yourself in this scenario. You can also use `ItemKey` property of the `QuickGrid` component to provide the expression to use for determining the `key` for each item.

**Closed by mkArtakMSFT** 2023-09-06 17:01 UTC
Labels: area-blazor, feature-blazor-quickgrid

**Comment by mkArtakMSFT** [comment] 2023-09-06 17:02
@guardrex can you please make sure that QuickGrid documentation have been moved to the ASP.NET Core Docs and the `ItemKey` is also documented? Thanks!

**Comment by marinasundstrom** [comment] 2023-09-06 17:06
@mkArtakMSFT I was wondering whether there was such a property like ``ItemKey``. Then that would solve the problem.

**Comment by guardrex** [comment] 2023-09-06 17:10
AFAIK, it's covered, including the keying aspects ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-8.0
