### ISSUE TITLE
Sending a request with empty body to an endpoint with a filter, returns the `Task` result on the response bdy when running with the Production environment

### ISSUE THREAD

**Issue by wilsonrivera** [dotnet/aspnetcore#45432] opened 2022-12-03 04:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've been trying the Minimal API and wanted to run the application in the Production environment to see what the empty body error would look like, however, when I ran the application and sent the request using `Insomnia`, what I saw was completely unexpected, the reponse body is as a `Task` or `ValueTask` object was being converted to `JSON`.

This only occurs when running the application with the `ASPNETCORE_ENVIRONMENT` set to `Production` on the `launchSettings.json` file. The only difference between the two images below is changing the environment.

![image](https://user-images.githubusercontent.com/225781/205421941-aaa15628-ecb2-403a-97a4-96d222b06fa0.png)
![image](https://user-images.githubusercontent.com/225781/205421963-4f8e717e-c075-4727-bc03-b6e27f5ef295.png)

By simply removing the filter from the endpoint, I get the following respnse using the `Prduction` environment:
![image](https://user-images.githubusercontent.com/225781/205421990-8b69874c-4e7f-4e61-9f68-52c289158cfa.png)

### Expected Behavior

Either produce an exception or an error response

### Steps To Reproduce

Clone https://github.com/wilsonrivera/minimal-api-prod-issue
Run the `http` or `https` profile (have not tested it with the `IIS Express` one)

### .NET Version

7.0.100

### Anything else?

ASP.NET Core version: 7
The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Rider, executing `dotnet run` produces same outcome
Include the output of dotnet --info:

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by davidfowl** [comment] 2022-12-03 04:33
This is a duplicate of https://github.com/dotnet/aspnetcore/issues/45040

**Comment by captainsafia** [comment] 2022-12-06 22:40
Closing as a duplicate.

**Closed by captainsafia** 2022-12-06 22:40 UTC
Labels: area-web-frameworks
