### ISSUE TITLE
Adding and using SignalR NPM package breaks Angular (9-11) app build

### ISSUE THREAD

**Issue by stasberkov** [dotnet/aspnetcore#28853] opened 2020-12-25 15:12 UTC
Adding and *using* `@microsoft/signalr` v.5.0.1 package in angular application breaks the build.
Build failes with error:
````
> angular.io-example@0.0.0 build C:\Users\stasb\source\ng11
> ng build
√ Browser application bundle generation complete.
Error: src/app/app.component.ts:16:11 - error TS2322: Type 'Timeout' is not assignable to type 'number'.
16       let intval: number = setTimeout(()=>{ console.log("ok"); }, 0);
             ~~~~~~
````
This happens due to `node` type reference

````typescript
/// <reference types="node" />
import { ILogger } from "./ILogger";
import { TransferFormat } from "./ITransport";
/** Defines the type of a Hub Message. */
export declare enum MessageType {
````
in `node_modules\@microsoft\signalr\dist\esm\IHubProtocol.d.ts` file.
As a result browser types are overriden by node types. 
This is very inconvenient.

If you remove this `node` refrence and `Buffer` type usage from the file then app will compile ok.

### To Reproduce
Sample application
[signalr-breaks-ng11-build.zip](https://github.com/dotnet/aspnetcore/files/5742123/signalr-breakes-ng11-build.zip)
Download and run
````
npm install
npm run build
````

Min changes in code to reporduce the issue: install `@microsoft/signalr` package and try using signalr
````typescript
import { Component } from '@angular/core';
import { HubConnection, HubConnectionBuilder } from "@microsoft/signalr";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Tour of Heroes';
  constructor() {
      const connection = new HubConnectionBuilder()
          .withUrl("some-url")
          .withAutomaticReconnect()
          .build();
      let intval: number = setTimeout(()=>{ console.log("ok"); }, 0);
  }
}
````
If you just add `@microsoft/signalr` to package.json it will not break the build.
Build is broken when try using signalr module.

**Comment by stasberkov** [comment] 2020-12-27 06:56
While this is not fixed you can use the following https://www.npmjs.com/package/patch-package package to patch `@microsoft/signalr` package during `npm install`. 
Here is how to:
1. Install `@microsoft/signalr`.
2. Patch `node_modules\@microsoft\signalr\dist\esm\IHubProtocol.d.ts` file by removing `/// <reference types="node" />` line and `Buffer` type usage from line `parseMessages(input: string | ArrayBuffer | Buffer, logger: ILogger): HubMessage[];`.
3. Run `npx patch-package @microsoft/signalr` command. It will create `patches` folder with instructions how to patch original packages after npm install procedure.
4. Add file from `patches` folder to your git repository.
5. Add ` "postinstall": "patch-package" ` into `scripts` section in `package.json`.
6. Run `npm i patch-package --save`. This will add `patch-package` to you npm dependencies.

**Comment by BrennanConroy** [comment] 2020-12-28 17:59
Dupe of https://github.com/dotnet/aspnetcore/issues/13805

**Closed** 2020-12-29 06:26 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
