### ISSUE TITLE
Microsoft.AspNetCore.Identity.EntityFramework EF >= 6.3

### ISSUE THREAD

**Issue by 1Jesper1** [dotnet/aspnetcore#21357] opened 2020-04-30 10:55 UTC
Please provide a package for Microsoft.AspNetCore.Identity.EntityFramework with Entity Framework version >= 6.3 Entity Framework 6.3 supports .NET Core. We don't want to use Entity Framework Core in our .NET Core application.

**Comment by blowdart** [comment] 2020-04-30 12:27
Why don't you want to use EF Core?

**Comment by blowdart** [comment] 2020-04-30 12:29
Possible dupe of https://github.com/dotnet/aspnetcore/issues/18102

**Comment by 1Jesper1** [comment] 2020-04-30 12:30
We are migrating an ASP .NET 4.6 MVC application to .NET Core, we thought about moving to Entity Framework Core, but EF 6.3 was released and added compatibility for .NET Core. It was suggested to not move to Entity Framework Core if there is no need.

**Comment by blowdart** [comment] 2020-04-30 12:54
Definitely a dupe then. From #18102,

> The path for aspnet applications still remains update to aspnetcore, which in turn means moving to efcore. EF6 on core is there to simplify migrations,

It doesn't applies to aspnet core migrations as, you still have to port your aspnet application to asp.net core, and at that point, as you're migrating you should migrate to EF Core as well.

Closing as By Design.

**Closed by blowdart** 2020-04-30 12:54 UTC
Labels: area-identity

**Comment by 1Jesper1** [comment] 2020-04-30 13:08
@blowdart Thanks for the fast reply. So the only option here is to migrate to EF Core?
So EF6 for Core was introduced to first migrate the aspnet application to core and at last migrate EF6 to EF Core?

**Comment by blowdart** [comment] 2020-04-30 13:12
Yes, that's your only option. Whilst I can't speak for EF (@ajcvickers can) my understanding was EF6 for Core was targeted at non-ASP.NET applications (WPF, WinForms etc.) so they can do a staged migration. 

As moving to ASP.NET Core involves updating many moving parts, we don't target it for identity as you're already migrating anyway, so at that point the EF Core migration should happen, EF6 on Core is a stepping stone for older non-ASP.NET apps.
