### ISSUE TITLE
Quarantined test: BundlesScopedCssFiles_UpdatesBundleWhenContentsChange

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#25623] opened 2020-09-04 17:29 UTC
It's failing on Helix even though it passes locally and in other CI environments:

https://dev.azure.com/dnceng/public/_build/results?buildId=802210&view=ms.vss-test-web.build-test-results-tab&runId=25400452&resultId=107994&paneView=debug

**Comment by BrennanConroy** [comment] 2020-09-06 06:20
Why isn't it marked quarantined then?

**Comment by SteveSandersonMS** [comment] 2020-09-06 16:54
The PR that quarantines it isn’t yet merged.

**Comment by javiercn** [comment] 2020-09-07 15:25
@BrennanConroy Is there anything wrong here?

**Comment by captainsafia** [comment] 2020-09-09 20:28
@javiercn I think we can improve the way the test is written here. The issue happens when we check to see that the last-modified timestamp of the compiled CSS does not change if the file contents haven't ([ref](https://github.com/dotnet/aspnetcore/blob/a190fd34854542266956b1af980c19afacb95feb/src/Razor/Microsoft.NET.Sdk.Razor/test/ConcatenateFilesTest.cs#L391)). The way we determine the timestamps results in a millisecond variance in the test environment which causes the check to fail. We should either (1) read the timestamp from the file directly or (2) update the test to account for millisecond variance in last modified datetime.

**Comment by Tratcher** [comment] 2020-10-23 22:17
This test is currently our flakiest, with 118 failures out of 373 runs. Glad to see you've got a PR out for it!

**Comment by captainsafia** [comment] 2020-11-09 17:12
We shipped a code change to improve the test here. Hopefully, we'll be able to unquarantine this test in 30 days.

**Comment by dougbu** [comment] 2022-01-07 21:10
@captainsafia or @dotnet/aspnet-blazor-eng in general, any idea why `BundlesScopedCssFiles_UpdatesBundleWhenContentsChange()` is still executing in the main aspnetcore-ci pipeline❔ See #39303

I'd also appreciate your thoughts on simply skipping this test in release/5.0. It's only about 30% successful and therefore isn't providing any value.

**Comment by dougbu** [comment] 2022-01-08 01:05
Reopening because I'm about to `Skip` this test in release/5.0. It's providing no value at the moment.

**Comment by javiercn** [comment] 2022-01-10 11:34
@mkArtakMSFT not sure what action you expect me to take here.

**Comment by mkArtakMSFT** [comment] 2022-01-20 19:32
@javiercn need to address the stability issue with this test. Let's target to do this in 7.0

**Comment by javiercn** [comment] 2022-01-23 11:03
@mkArtakMSFT this test is not flaky, the issue is from 2 years ago. I'm closing this as there's no action to be taken here

**Closed by javiercn** 2022-01-23 11:03 UTC
Labels: test-failure, area-mvc
