### ISSUE TITLE
VS Code: Type "@DateTime" in the _layout.cshtml , the color of this symbol is incorrect. 

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspnetcore#36495] opened 2021-09-14 09:32 UTC
**REPRO CONFIGURATION**:Win11 x64 + SDK 6.0.rc2
**Latest SDK Version:** 6.0.100-rc.2.21463.12
**Latest Runtime Version:** 6.0.0-rc.2.21460.8

**INSTALL STEPS​:**
1. Clean machine: Win11 x64
2. Install the sdk 6.0.rc2 from: https://aka.ms/dotnet/6.0.1xx/daily/dotnet-sdk-win-x64.exe
3. Install VS Code from: [https://code.visualstudio.com/Download](url)
4. Install C# Extensions version: v1.23.15.vsix from: https://github.com/OmniSharp/omnisharp-vscode/releases

**Testcases Affected**
[SimpleWebAppRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppRazorEditingWithVSCode.md)
[SimpleWebAppRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppRazorEditingWithVSCode.md)
[SimpleBlazorRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.9/E2EWalkthroughs/VS/AspNetCore30/30_SimpleBlazorRazorEditingWithVSCode.md)

**Platform**
- [x] Windows
- [ ] macOS
- [x] Linux

**Repro Steps**
1. Open a normal Terminal Emulator
2. Create mvc project and open it using VS code
```
  md mvc
  cd mvc
  dotnet new mvc
  code .
```
3. Go to [https://github.com/OmniSharp/omnisharp-vscode/releases](url) > Download the csharp-1.23.15.vsix.
4. In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
5.Select mvc.csproj on the top of the tool bar, then click yes.
6.Open Views/Shared/_Layout.cshtml and type " **@da** " in the `<head>` tag, then press enter to complete "@Datetime", the color of "**Datetime**" is different from "**@**".

**Note:**
1. This issue repro on the SDK 6.0 rc1 +  v1.23.15.
2. This issue repro on C# Extensions is v1.23.14.
3. This issue also repro when type **@foo** / **@Program** / **@ThisDoesNoExist**.

**Actual Result**:

![image](https://user-images.githubusercontent.com/82028229/133230318-4fd14de1-2080-4a9d-80b3-78395f555535.png)

![image](https://user-images.githubusercontent.com/82028229/133230341-990e0f59-def9-4aec-90e8-ebd46c2530e6.png)

![image](https://user-images.githubusercontent.com/82028229/133230358-8d136946-3260-48bf-b7d2-6c474eeb8320.png)

![image](https://user-images.githubusercontent.com/82028229/133230374-afc9e654-8d53-4e1a-889a-eb15c432b0b9.png)

**Expected Result**:

![image](https://user-images.githubusercontent.com/82028229/133229873-3541e73c-bbd4-4270-b0b6-32d22be859d3.png)

![image](https://user-images.githubusercontent.com/82028229/133229947-6df4d4fd-74a0-4659-a1f3-4a3a2541f47e.png)

![image](https://user-images.githubusercontent.com/82028229/133231726-62674fda-a565-434f-b8df-9d5b95ff916a.png)

![image](https://user-images.githubusercontent.com/82028229/133231522-d0a38072-2668-484d-94e6-8fffdd5e149e.png)

**Comment by ryanbrandenburg** [comment] 2021-09-17 22:25
This appears to be a duplicate of https://github.com/dotnet/aspnetcore/issues/26479. These scenarios will light up once that feature is added.

**Closed by ryanbrandenburg** 2021-09-17 22:25 UTC
Labels: area-razor.tooling, feature-razor.vs
