### ISSUE TITLE
Unable to publish views of a Microsoft.NET.Sdk.Web project 

### ISSUE THREAD

**Issue by geetmenon** [dotnet/aspnetcore#36716] opened 2021-09-18 21:23 UTC
Opening a ticket again for the same issue ( #36583) since this issue has been incorrectly marked as Resolved and Closed.  At least this time please provide a proper resolution. 

I am unable to publish views if I disable EnableDefaultItems in my project and explicitly specify all the compile includes, content includes and the None includes. 

```
<PropertyGroup>
        <EnableDefaultItems>false</EnableDefaultItems>
	<RazorCompileOnBuild>false</RazorCompileOnBuild>
	<RazorCompileOnPublish>false</RazorCompileOnPublish>
	<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>  
</PropertyGroup>
```

Just to reiterate that I have explicitly included each of my Compile includes, Content includes and None (static file) includes. So please don't tell me that I need to  manually include cshtml files as Content items and close this issue.  Please refer to issue #36583 for the details. Please also don't close this issue saying it is as duplicate of #36583. Yes it is a duplicate of #36583 but that ticket was closed prematurely without providing a solution to the issue I am facing.

**Comment by geetmenon** [comment] 2021-09-18 21:26
As mentioned in ticket #36583, I am able to replicate this issue with the sample project that @pranavkm had uploaded if set EnableDefaultItems  to false and explictly add the includes in my project file.

**Comment by javiercn** [comment] 2021-09-20 10:23
@geetmenon apologies if the bot closed the original issue early, will reopen that one and close this one as duplicate, since it has all the context.

Dupe of https://github.com/dotnet/aspnetcore/issues/36583

**Closed by javiercn** 2021-09-20 10:23 UTC
