### ISSUE TITLE
[Blazor] Auto Render not working properly in .NET 8 and page locks until WebAssembly start

### ISSUE THREAD

**Issue by AmBplus** [dotnet/aspnetcore#52154] opened 2023-11-17 14:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I updated Visual Studio to the latest version 17.8.0 and created a Blazor app using Auto render mode With Dotnet 8. When I run the application and navigate to the Counter tab, the whole page locks up until the WebAssembly Start. I can't do anything or switch to another tab until the download Finished And WebAssembly Start, even though it happens quickly locally. This could cause problems in production where the download may take longer. It also goes against the purpose of Auto render mode.

### Expected Behavior

With auto render mode, the page should initially use server-side rendering. Once WebAssembly finishes downloading And Start, it can switch over seamlessly without locking up the page.

### .NET Version

NET 8 , Windows 10-64

### Anything else?

As you can see, the page is locked and prevents navigating to another tab.
<img width="960" alt="lockPage" src="https://github.com/dotnet/aspnetcore/assets/96792239/791d2d0d-a756-4ed9-ae28-2004374330d7">

**Comment by danroth27** [comment] 2023-11-17 19:40
The delay is most likely due to starting up the .NET WebAssembly runtime, not the download. I believe the issue is we don't currently have a way to download the .NET WebAssembly runtime without also starting it, so this delay happens even on the first visit when using interactive server rendering. But even if we could avoid that delay on the first visit, on subsequent visits you'd still see the delay as the runtime starts up even though the runtime has been cached.

@lewing @MackinnonBuck

**Comment by carlfranklin** [comment] 2023-11-17 19:55
I’m seeing the same thing

**Comment by ray440** [comment] 2023-11-17 20:13
If you change the Counter title to:
```
<h1>Counter @(OperatingSystem.IsBrowser() ? "Wasm" : "Server")</h1>
```
It's kinda neat to watch the change as it happens.

The delay is expected but much longer than expected leading to a stalled UX for antsy users.

Is there a way to tell what @rendermode is?

**Comment by danroth27** [comment] 2023-11-17 20:24
> Is there a way to tell what `@rendermode` is?

Not currently: https://github.com/dotnet/aspnetcore/issues/49401

**Comment by carlfranklin** [comment] 2023-11-17 22:03
Can we hook afterWebAssemblyStarted in JavaScript to determine when WASM is
loaded ?

**Comment by mkalinski93** [comment] 2023-11-18 13:52
I found out that OnAfterRender actually can be an indicator that the framework and dependencies has been loaded. I think I'm going to have a root level component that will display a waiting indicator or something. My problem is that my clients will have a fast initial response from the server, but the overall hydration is taking a long time (especially on mobile end with slow connectivity) 

In the end, my clients would be more confused when there's no interactivity yet established. My observation is that OnAfterRender gets executed when the framework has been loaded fully. Maybe we can get used to it.

**Comment by SteveSandersonMS** [comment] 2023-11-20 10:49
> @carlfranklin I’m seeing the same thing

Can you clarify what same thing you are seeing? The original report suggested that the UI is locked while downloading WebAssembly resources, but as far as we understand that is not the case.

If you mean that the UI is locked while the WebAssembly runtime *starts* (not while downloading, but *after* downloading), this is true and always has been since the beginning of Blazor WebAssembly. Over the years we've made it faster - it took about 1 second to start on the first version, and is down to about 350ms on recent hardware.

**Comment by AmBplus** [comment] 2023-11-20 16:26
@SteveSandersonMS (usually< 500ms, but depends on CPU speed)
It seems this problem only happens in debug mode. What I mean is that it's more noticeable, not that there is no locking at all in other modes.
In debug mode with Visual Studio it takes around 6 seconds , with dotnet run it takes less than 1 sec or half sec, and in release you almost don't feel your page is locked.
It seems like we don't have any issues in production mode.

**Comment by carlfranklin** [comment] 2023-11-20 16:28
Thanks!

**Comment by ziaulhasanhamim** [comment] 2023-11-22 08:32
I am facing the same issue

**Comment by SteveSandersonMS** [comment] 2023-11-22 09:18
> In my case the browser first loads webassembly files and then it connects to the server with signalr

@ziaulhasanhamim When you use the word "loads" here, do you mean "downloads" (as in the WebAssembly files are not already cached, and you are waiting for them to be transferred over the network), or do you mean it in the sense of "starts" (as in, the WebAssembly files are already downloaded, but it takes some nonzero time to start the .NET runtime under WebAssembly, most likely ~0.5s assuming you are not debugging).

**Comment by ziaulhasanhamim** [comment] 2023-11-22 09:49
@SteveSandersonMS I meant that it is not cached. When wasm runtime is not cached it first downloads the wasm files then connects to server through websockets. But if it has to download the wasm runtime first then what is the benefit of auto interactivity.

**Comment by AmBplus** [comment] 2023-11-22 10:05
@ziaulhasanhamim , Try Publish File And See Still Have Delay

**Comment by ziaulhasanhamim** [comment] 2023-11-22 10:08
Yeah in publish delay is less. But fundamentally it's a problem because what is benefit of auto interactivity if wasm runtime needs to downloaded first(runtime is not cached already) before websocket connection

**Comment by SteveSandersonMS** [comment] 2023-11-22 10:18
> I meant that it is not cached. When wasm runtime is not cached it first downloads the wasm files then connects to server through websockets. But if it has to download the wasm runtime first then what is the benefit of auto interactivity.

If that's true it would be very surprising and a definite major bug we'd hurry to patch. However I don't think we've ever observed this happening, so it's also possible that something else is going on.

Can you clarify how you know this is what's happening? Are you talking about when running on `localhost`? How do you know which part of the delay comes from downloading the WebAssembly files, compared with after the files are downloaded and the WebAssembly runtime is booting up?

**Comment by ziaulhasanhamim** [comment] 2023-11-22 10:41
Yes, I'm facing it on localhost. The network tab shows that first, it is downloading the whole wasm runtime and then connecting the websocket. Moreover, in the console tab Blazor websocket connection message and runtime loaded message are emitted together, and after it the page becomes interactive. Also In auto interactive mode, first load time is as bad as webassembly load time whereas in server mode it loads instantly. 
My observation on the network tab in slow 3G throttle. 

![image](https://github.com/dotnet/aspnetcore/assets/65945752/c337f36f-6b06-4e75-be8d-8daa2a4ae8ab)

I can be totally wrong here. But in general, the Auto mode load time is not appraisable.

**Comment by SteveSandersonMS** [comment] 2023-11-22 12:06
Thanks @ziaulhasanhamim for the clarification. This is helpful. It's possible that this problem only surfaces in the artificial localhost+throttling case rather than in real deployments. We're investigating to confirm, and will certainly look to improve this quickly either way.

**Comment by baktay** [comment] 2023-11-24 11:36
I used the sample counter-weather code as is. I switched to counter page and clicked Click Me button immediately. Nothing happened for couple of clicks until it worked (I am not using a super fast computer). 

Then, I changed counter page rendermode to InteractiveServer and refreshed the page. It worked immediately. My first immediate click worked. InteractiveAuto does not seem to render from server first time (at least not as good as InteractiveServer  rendermode) when compared.

**Comment by achmstein** [comment] 2023-11-26 07:32
Facing the same issue.

**Comment by carlfranklin** [comment] 2023-11-27 23:30
@SteveSandersonMS I published a test app to Azure at https://blazorautotest.azurewebsites.net/

It does load fast, but try to click the button before it reads "Platform: Wasm"

**Comment by SteveSandersonMS** [comment] 2023-11-28 12:52
Thanks @carlfranklin. Yes that is helpful and probably does confirm the issue.

One minor remaining detail though: I see your deployment is not configured to enable WebSockets, so it's falling back on long polling. Could you update it so it does enable WebSockets? Then assuming the same issue still repros, that would be a complete smoking gun.

**Comment by carlfranklin** [comment] 2023-11-28 13:15
@SteveSandersonMS Done.

**Comment by SteveSandersonMS** [comment] 2023-11-28 14:08
Thanks. That does seem pretty convincing. @mkArtakMSFT I think this should be at the top of our priority list.

**Comment by codeputer** [comment] 2023-12-01 22:32
I'd this not an issue with the blazor server side unable to to a pre render, and hence, the ux locks up until the client side is ready to address the ux request?

I recently watch a demo of this on the web, and thought I would raise it here (tried to find a reference,  but cant find it).  This switch on what service is satisfying the request is a tricky spot in this new paradigm of web development

**Comment by carlfranklin** [comment] 2023-12-01 22:34
My demo turns off pre-rendering.

**Comment by danielgreen** [comment] 2023-12-01 22:41
> My demo turns off pre-rendering.

So the UI being locked in your demo isn't due to static content having been rendered?

It's locked even though it should be interactive via SignalR in the interim while wasm starts?

**Comment by codeputer** [comment] 2023-12-01 22:56
> > My demo turns off pre-rendering.
> 
> So the UI being locked in your demo isn't due to static content having been rendered?
> 
> It's locked even though it should be interactive via SignalR in the interim while wasm starts.

Not sure I understand your question - so I'll explain my understanding (happy to be corrected)

I know that one issue with a client I had in Blazor was the behaviour of InitializationAsync being called twice.  As I understand it in Blazor 8 - the first time it's called is when it's on the server, and the second time it's called, it's on the client.  What he explained was that the first time through the InitializeAsync -  you definitely want to be sure that it's not blocked (like waiting for data) because after it exits that method does the server release the pre-rendered HTML data down to the client.  At this point the client works to present the HTML on the screen (typically this is showing the "Loading..." eye candy stuff).  Once it's done that (this is without a socket) the WASM prep and download starts to happen.  Interaction with the server with Blazor Socket, can only start after the JS file is downloaded, as its an outbound connection with the server that starts the websocket connection.  Delay the pre-render, and you delay the socket being established as well, and the whole thing locks up until WASM is fully established (something that should be avoided in my thinking).  My preference is to leave everything on the server, unless the application requires off-line capabilities, or even heavy in terms of graphics (like casino application for example).

**Comment by MackinnonBuck** [comment] 2023-12-06 19:12
Hi all - we really appreciate all the community engagement on this issue. It's clear to us that there are improvements we can make to the Auto render mode to better support certain scenarios, and we're working quickly to ensure that we make the right improvements.

The nature of this feature makes it behave differently on different types of devices, connections, and apps. That's why it's valuable for us to get feedback about whether the improvements we make are going to address the concerns being expressed here.

To provide some insight, the primary issues people seem to be experiencing are:
1. Downloading WebAssembly resources in parallel means that the leftover bandwidth for other network activity (like initializing a websocket connection or fetching a new page) may be too small to be effective. This results in cases like:
    * The Blazor Server circuit appearing to "wait" for WebAssembly resource downloads to complete
    * Page navigations or link clicks "waiting" until WebAssembly resources are downloaded
2. Especially when debugging locally, the page may momentarily "lock up" _after_ WebAssembly resources have been downloaded. For a brief period, animations stop playing, text boxes stop receiving input, etc. This happens because when WebAssembly resources are already cached or get downloaded quickly, then the Auto render mode may decide to use WebAssembly for interactivity. Blazor's WebAssembly interactivity startup is largely synchronous, and since debug builds are slower and have more work to do (e.g., initialize hot reload functionality), then this blocking period when debugging can appear significant (up to a second or so, from my experience). This issue shouldn't affect published apps, but it's still a continuous effort of ours to make improvements to Blazor WebAssembly startup time.

### Call to action

I've locally made some small adjustments to the Auto render mode and seen significant improvement, particularly as it relates to issue [1] described above. We would really appreciate it if you could try out these changes to see if they improve your own apps. The most notable changes is a fix that allows the downloading of WebAssembly resources to be throttled to reduce their impact on other network activity.

To test these changes, download the files from [this gist](https://gist.github.com/MackinnonBuck/460b0493eb8dda3f570900cfb3bb1c62), and place them in your `wwwroot` folder. This following example assumes these files are placed in the `wwwroot/js` folder, so you'll have to adjust the following code accordingly if you make a different choice.

In your `App.razor` file, replace the script element referencing `blazor.web.js` with the following:

```html
<script src="js/blazor.web.patched.js" autostart="false"></script>
<script>
    Blazor.start({
        webAssembly: {
            loadBootResource: function (type, name, defaultUri, integrity) {
                if (type === 'dotnetjs' && name === 'dotnet.js') {
                    return 'js/dotnet.patched.js';
                }
                return `_framework/${name}`;
            },
            configureRuntime: (builder) => {
                builder.withConfig({
                    maxParallelDownloads: 1, // Adjust this to change the WebAssembly resource throttling amount
                });
            },
        },
    });
</script>
```

We may also experiment with other changes, like delaying the start of WebAssembly resource downloads until the circuit connects. This might improve the initial time to interactivity, even if the websocket connection quality continues to be slightly affected by the downloading of WebAssembly resources in the background. Until then, we'd love to hear your feedback!

**Comment by carlfranklin** [comment] 2023-12-06 19:55
I will check it out, thanks!

Is it possible to make the WASM download happen on a lower-priority thread?
If we have a circuit, what's the rush to get to WASM?

In my DevIntersection talk today someone asked what happens to the state?
Do my variables re-initialize once WASM is loaded? If that's the case,
would it work to have a new virtual lifecycle method? Do we just look at
OperatingSystem.IsBrowser() in OnAfterRender, assuming that OnAfterRender
is called when WASM is ready?

Thanks again for tackling this.

Carl

**Comment by SteveSandersonMS** [comment] 2023-12-06 20:19
> The result is that it still doesn't let me click before WASM files are downloaded.

That's strange. I just tried your new site on a throttled connection and it did work this time - I was able to use the counter immediately, even though I could see the webassembly resources were still downloading for a long time in the background.

**Comment by carlfranklin** [comment] 2023-12-06 20:37
Maybe I don't understand what OperatingSystem.IsBrowser() means when it
returns true. If I press F5 to refresh, it only returns false for a second,
and then switches to WASM. During that one second, the button is not
responsive.

[image: image.png]

**Comment by carlfranklin** [comment] 2023-12-06 20:40
I throttled the connection. It took longer to switch to WASM, but the
button was still unresponsive in Server mode.. What's more, I see no
websockets.

[image: image.png]

**Comment by MackinnonBuck** [comment] 2023-12-06 21:10
> In my DevIntersection talk today someone asked what happens to the state?
Do my variables re-initialize once WASM is loaded? If that's the case,
would it work to have a new virtual lifecycle method? Do we just look at
OperatingSystem.IsBrowser() in OnAfterRender, assuming that OnAfterRender
is called when WASM is ready?

The Auto render mode doesn't dynamically change the render mode of components that have already become interactive. It makes an initial decision based on whether WebAssembly resources are cached. If they are, then WebAssembly interactivity gets used. If they aren't, then Server interactivity is used, but the download of WebAssembly resources starts so that on the next visit to the site (or the next refresh), WebAssembly gets used.

Allowing components to dynamically switch from Server interactivity to WebAssembly interactivity poses some interesting challenges, but it's something worth considering for investigation in .NET 9.

Side note: when testing the Auto mode feature, it might help to distinguish between the "statically rendered but not yet interactive" case from the "server interactive" case. Here's the counter component I've been using:

```razor
<p role="status">Current count: @currentCount</p>

<p>Render mode: @renderMode</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;
    private string renderMode = "SSR";

    private void IncrementCount()
    {
        currentCount++;
    }

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            renderMode = OperatingSystem.IsBrowser() ? "WebAssembly" : "Server";
            StateHasChanged();
        }
    }
}
```

**Comment by arthastheking113** [comment] 2023-12-07 03:11
@MackinnonBuck I tested it out. I see we can control how many maxParallelDownloads as we want. Navigation is using Server Side Prerendering which is very good for SEO. The only thing I don't see is the Signal R connection, there is no Signal R to start connecting to activate Interactive Server mode.

It would be great if we can start first by connecting Signal R and have to wait for Signal R connected Successfully then start downloading .wasm files.

**Comment by david-at-solve** [comment] 2023-12-07 07:30
Hello @MackinnonBuck, I tried out your changes and it works as expected :) 

For the following video I disabled SSR for the `Counter` component and used `maxParallelDownloads: 3`.

https://github.com/dotnet/aspnetcore/assets/139991064/4ee082e8-41bb-40e3-89a5-b911d0c3d83e

As you can see the `Counter` component is usable and it's also possible to navigate to other pages. The WASM runtime then needs some time for the first startup, but the second startup is a lot faster. Auto mode as expected :) 

The Idea with "waiting for Blazor Server connection" is good but probably not the only thing required. Because users also navigate to other pages those HTTP calls (including images, further styles, ...) also need to have the chance to get executed early, so I think a combination of "late wasm download + maxParallelDownloads" would be great :)

And I want to thank you all for your great work in inventing and developing Blazor 🎉 👏 👏 👏

**Comment by ihorlazarenko** [comment] 2023-12-10 09:34
For me, interactive Server side rendering is never used in Auto mode. I disabled prerendering, switched to "slow 3G" mode in networking in browser and  had been observing 22 sec empty counter page before wasm libs were downloaded. Auto mode behaves like webassembly mode, there are no differences for me.

**Comment by mandeep-sps** [comment] 2023-12-15 12:43
Hi Team,

I am facing a Page title Issue in the Blazor Dotnet 8 with Auto Mode and Prerender:False
I am using these lines of codes:-

`@page "/sfgrid-Grid"
@attribute [StreamRendering]
@rendermode @(new InteractiveAutoRenderMode(prerender:false))
@* @rendermode InteractiveAuto *@

<PageTitle>Employee Listing</PageTitle>`

Please help me on this part
Thanks

**Comment by CreamyMiracle** [comment] 2023-12-16 08:49
I was banging my head against the wall and almost gave up trying InteractiveAuto rendering since it didn't make any sense to wait all WASM files to be downloaded before the websocket circuit was healthy and the InteractiveServer rendering kicked in. 

Many thanks to @MackinnonBuck to provide a workaround for this problem!

Hope this fix will be included in Blazor Web App templates soon!

**Comment by zenopm** [comment] 2023-12-16 16:27
> I was banging my head against the wall and almost gave up trying InteractiveAuto rendering since it didn't make any sense to wait all WASM files to be downloaded before the websocket circuit was healthy and the InteractiveServer rendering kicked in.
> 
> Many thanks to @MackinnonBuck to provide a workaround for this problem!
> 
> Hope this fix will be included in Blazor Web App templates soon!

agreed, i was banging my head as well, didn't see a point to using InteractiveAuto until I realized (mainly from this post) that it was not working correctly... I'm sure there are many many others banging their heads too wondering why it is not working as you'd expect...

any guess on a timeline as to when this will be released? or will it not be?

**Comment by MackinnonBuck** [comment] 2023-12-18 20:18
> any guess on a timeline as to when this will be released? or will it not be?

We're working on addressing the issue with the hope that the fix will be low risk enough to patch it in an upcoming servicing release.

**Comment by fdonnet** [comment] 2023-12-20 16:31
same here... I was questioning myself about the purpose because it always switchs to wasm at the first load and it take sometimes to load. In InteractiveServer it's quick.
But ok, it's not the expected behavior... we need to have the speed of the InteractiveServer first load and the WASM loading in background for the next uses of the component or for sure, automode is not useful.

**Comment by bxjg1987** [comment] 2023-12-21 13:38
> > I was banging my head against the wall and almost gave up trying InteractiveAuto rendering since it didn't make any sense to wait all WASM files to be downloaded before the websocket circuit was healthy and the InteractiveServer rendering kicked in.
> > Many thanks to @MackinnonBuck to provide a workaround for this problem!
> > Hope this fix will be included in Blazor Web App templates soon!
> 
> agreed, i was banging my head as well, didn't see a point to using InteractiveAuto until I realized (mainly from this post) that it was not working correctly... I'm sure there are many many others banging their heads too wondering why it is not working as you'd expect...
> 
> any guess on a timeline as to when this will be released? or will it not be?

Yes, this is completely different from the auto mode in the advertisement. I have already wasted a week on this matter, and fortunately, the blazer team is actively addressing this issue.

**Comment by mikes-gh** [comment] 2024-01-05 15:51
My experience is the same.

Open private window to simulate first visit.
Open Browser tools to monitor responses.
Click on Counter.
Not interactive for about 5-7 seconds in my environment.
The Web socket is only connected after all wasm resources have been downloaded.

![image](https://github.com/dotnet/aspnetcore/assets/16208742/398b3c66-261b-4256-93c2-105cda79c97d)

**Comment by mikes-gh** [comment] 2024-01-05 15:58
@MackinnonBuck When is the BSS websocket meant to cleanup once the page is using wasm?  I am thinking of server resources here.

**Comment by mikes-gh** [comment] 2024-01-05 17:10
I tested @MackinnonBuck fix here https://github.com/dotnet/aspnetcore/issues/52154#issuecomment-1843535849 and it is a significant improvement.  Thanks for looking into it.  Ultimately rescheduling/delaying the wasm startup procedure would be preferable than turning off parallel downloads but it does work.

**Closed** 2024-01-10 22:52 UTC
Labels: bug, area-blazor, feature-full-stack-web-ui

**Comment by mikes-gh** [comment] 2024-01-31 13:23
Ok So I'm confused when this fix will be released.  This issue is milestone `8.0.2` but the corresponding PR is `9.0-preview1`.
Surely Render mode auto won't be broken until `net9.0`?

**Comment by danroth27** [comment] 2024-01-31 18:25
> Ok So I'm confused when this fix will be released. This issue is milestone `8.0.2` but the corresponding PR is `9.0-preview1`. Surely Render mode auto won't be broken until `net9.0`?

@mikes-gh This issue will be fixed in _both_ 8.02 and 9.0 Preview 1. Expected release timeframe is mid-Feb.

**Comment by bcookew** [comment] 2024-02-14 03:53
Hiya,

Did this go live in 8.0.2 as expected? 
I am running:
- VS 2022 CE 17.9
- SDK 8.0.2

Behavior seems similar / the same at least in development. But perhaps I have misunderstood the fix...
Does the fix correct the behavior without developer intervention or do we still need to modify the Blazor startup in some way?

Thanks for you efforts!

**Comment by ashishsinha24** [comment] 2024-02-14 04:13
Same here.

**Comment by mikes-gh** [comment] 2024-02-14 10:14
Looks like it only got merged 10 hours ago and is labelled `8.0.3`
https://github.com/dotnet/aspnetcore/pull/54011
Can someone confirm it missed `8.0.2`?

**Comment by wtgodbe** [comment] 2024-02-14 17:59
> Looks like it only got merged 10 hours ago and is labelled 8.0.3
https://github.com/dotnet/aspnetcore/pull/54011
Can someone confirm it missed 8.0.2?


That label is misleading, that PR is a mechanical one that brings in any internal fixes from the previous month. All of the commits in that PR, except for the last 2, were internal commits that were included with 8.0.2. If you browse the commit history from the v8.0.2 tag (below), you can see that the render mode fix was included in 8.0.2.

https://github.com/dotnet/aspnetcore/releases/tag/v8.0.2

@MackinnonBuck any thoughts on why customers might not be seeing the new behavior with the change?

**Comment by MackinnonBuck** [comment] 2024-02-14 18:37
The fix was included in 8.0.2. I confirmed this by installing the SDK on a fresh machine and testing a Blazor Web App with "Auto" interactivity by creating a new project from the project template. All that should be required for existing projects is updating `Microsoft.AspNetCore.Components.*` packages to use version 8.0.2.

My verification steps were the following:
1. Create the project using `dotnet new blazor -int Auto`
2. Start the project using `dotnet run`
3. Navigate to the app's URL
4. Open the browser dev tools window (Edge)
5. In the network tab, select Fast 3G (or Slow 3G) throttling
6. Navigate to the counter page
7. Observe that WebAssembly resource downloads are throttled, allowing server interactivity to start before WebAssembly resources finish downloading

A few notes/caveats:
* Especially when a debugger is attached, the time it takes to start the WebAssembly runtime may noticeably contribute to the startup delay seen during development.
* When using the `Auto` render mode, `blazor.boot.json` has to be fetched over the network before the circuit starts. This is because `blazor.boot.json` contains the WebAssembly resource hash that's used to determine whether WebAssembly resources are cached. This is a step that's not required when using the InteractiveServer render mode, so it might contribute to a startup time difference between the InteractiveAuto and InteractiveServer render modes when Auto resolves to using Server interactivity.

For those that see issues not described by the above, could you describe what problem you're seeing? Thanks!

**Comment by MackinnonBuck** [comment] 2024-02-14 18:43
> For those that see issues not described by the above, could you describe what problem you're seeing? Thanks!

To expand on this, if someone can point out to a difference in behavior between 8.0.2 and the fix that I linked in [a previous comment](https://github.com/dotnet/aspnetcore/issues/52154#issuecomment-1843535849), that would potentially point to a bug. Thanks!

**Comment by mikes-gh** [comment] 2024-02-14 19:58
@MackinnonBuck I was one of the users that tested your hotfix before and it worked well for me.
I just installed 8.0.2 and it seems that the symptoms are the same as 8.0.1 i.e. no server side interactivity until wasm app has downloaded.

**Comment by mikes-gh** [comment] 2024-02-14 20:06
@MackinnonBuck For me I made sure all my references were `8.0.2`
I had previously tested your hotfix successfully.
As a preliminary test using `8.0.2` the problem of delayed server interactivity returns the same as before.

**Comment by bcookew** [comment] 2024-02-15 01:03
A small update. My experience of that delay and switchover to wasm rather than staying in interactive server has been resolved.
I think I caused my own problem by trying to implement an undocumented (unsupported) project configuration. I was experimenting with adding a second client project with the same setup as the original and then when I couldn't determine how to resolve an issue around Static Assets paths to the two projects I deleted one... You can probably see where this is going.

I thoughtlessly deleted the original client project instead of the one I added and didn't observe that there was an extra package reference.
```xml
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.2" PrivateAssets="all" />

```
As soon as I realized that this was the only difference I could find between a fresh template and my project I removed it, cleaned, rebuilt, ran without debugging, and there it was. The behavior was working correctly as you had described.

Apologies for reopening this can of worms over an error on my part.

**Comment by david-at-solve** [comment] 2024-02-15 07:52
Auto-mode now works as expected, thank you!

**Comment by danroth27** [comment] 2024-02-15 18:09
> Same here.

@ashishsinha24 Can you share more details about the issue you're still seeing?

**Comment by ashishsinha24** [comment] 2024-02-15 18:14
> > Same here.
> 
> @ashishsinha24 Can you share more details about the issue you're still seeing?

I am still seeing that the app locks until the wasm is downloaded. I am seeing it in debug and release versions. I am using Radzen controls. Maybe the problem is specific to this. I haven't had the time to fully test it.

**Comment by MackinnonBuck** [comment] 2024-02-15 18:31
@ashishsinha24,

> I am still seeing that the app locks until the wasm is downloaded.

If the app is locking up, it's probably the WebAssembly runtime _starting_, not being downloaded. The WebAssembly runtime starts synchronously, which is why the webpage becomes temporarily non-interactive. Does the same thing happen when using an `InteractiveWebAssembly` render mode? If so, that would indicate that this is not a problem with the `InteractiveAuto` mode, but rather a performance characteristic of WebAssembly runtime startup.

**Comment by mikes-gh** [comment] 2024-02-15 18:37
@MackinnonBuck 

1. Is it expected that wasm dotnet runtime downloads and starts up before the websocket for InteractiveServer becomes available?
2. Which exact libraries does your fix alter.

TIA

**Comment by MackinnonBuck** [comment] 2024-02-15 19:53
> Is it expected that wasm dotnet runtime downloads and starts up before the websocket for InteractiveServer becomes available?

It's not expected, but I don't think this is what's happening in the screenshot you shared. If you're pointing out that `dotnet.native.wasm` gets downloaded before the websocket connects, that's somewhat of a timing coincidence, and the download of `dotnet.native.wasm` doesn't block the circuit starting up. If you test using "Slow 3G" performance, you might find that the websocket can connect before `dotnet.native.wasm` fully downloads. But the WebAssembly runtime doesn't actually start until all `.wasm` downloads have completed.

In a future release, we could also make changes in the runtime to enable the starting of Blazor Server before `dotnet.runtime.*.js` and `dotnet.native.*.js` are loaded, but those changes are likely going to be too large to include in a servicing release.

> Which exact libraries does your fix alter.

The fix only alters `blazor.web.js`, which is an embedded resource in `Microsoft.AspNetCore.Components.Endpoints.dll`, which is part of the ASP.NET Core shared framework.

**Comment by Andrzej-W** [comment] 2024-02-15 20:06
I tested a new application created as Global InteractiveAuto and everything works as expected. I can switch between pages and Counter page is interactive while wasm files are loaded.

@ashishsinha24 I have no experience with Radzen components, but I have some with DevExpress. Simple application with one DxGrid downloads A LOT of files and it is huge. Here is an interesting blog post:
https://community.devexpress.com/blogs/aspnet/archive/2023/03/16/blazor-webassembly-aot-compilation-and-link-trimming.aspx

Maybe you see the problem described by @MackinnonBuck (WebAssembly startup.) On a fast computer I have to wait 1 s. before WebAssembly app with DevExpress components will be interactive. On iPhone 6s and laptop with Intel Core i7-6500U processor I have to wait about 4 s. It is possible that app with Radzen component also needs a few seconds to start on your hardware.

**Comment by mikes-gh** [comment] 2024-02-15 20:29
@MackinnonBuck 
>But the WebAssembly runtime doesn't actually start until all .wasm downloads have completed.

>If the app is locking up, it's probably the WebAssembly runtime starting, not being downloaded. The WebAssembly runtime starts synchronously, which is why the webpage becomes temporarily non-interactive. Does the same thing happen when using an InteractiveWebAssembly render mode? If so, that would indicate that this is not a problem with the InteractiveAuto mode, but rather a performance characteristic of WebAssembly runtime startup.

I'm a bit lost on the order of things.  I hadn't considered that the WebAssembly runtime starting could block the Blazor Server interactivity.

So if the app downloads quite quickly then the WebAssembly runtime starting can still block the Blazor Server interactivity giving the same feel that the app is not responding even though the websocket is open?

**Comment by MackinnonBuck** [comment] 2024-02-15 21:25
> So if the app downloads quite quickly then the WebAssembly runtime starting can still block the Blazor Server interactivity giving the same feel that the app is not responding even though the websocket is open?

I should have been clearer - the WebAssembly runtime (as in the code from the `.Client` project) won't actually start until all `.wasm` downloads have completed _and_ a component requires WebAssembly interactivity. So, if you had an `InteractiveServer` component and `InteractiveWebAssembly` component on the same page, the starting of the WebAssembly runtime could momentarily block interactivity for the `InteractiveServer` component. But this shouldn't happen when only using the `InteractiveAuto` render mode. If you do see a delay like that, it's probably because the `InteractiveAuto` component is using WebAssembly interactivity.

**Comment by saintarian** [comment] 2024-02-16 22:26
Thanks for the fix, @MackinnonBuck. I updated my SDK to 8.0.2 and tried on a new project and the issue looks fixed. However, I see that all the wasm files are downloaded serially (see image below). Is there a way to make this parallel (or, say 10 degrees of parallelism), while still having the websocket connection be established before the wasm is downloaded?

<img width="551" alt="Screenshot 2024-02-16 at 5 25 46 PM" src="https://github.com/dotnet/aspnetcore/assets/2073737/9a5dd64d-a3ff-433f-9bb7-d869878a0a90">

**Comment by Andrzej-W** [comment] 2024-02-17 04:06
@saintarian you cannot download 10 files concurrently because your application will be unusable. Maybe it is not a problem on high speed fiber Internet connection but try to download a few files concurrently using cellular network and check latency with ping command.

**Comment by bxjg1987** [comment] 2024-02-18 02:10
Regarding the content here, the official document does not seem to provide a detailed explanation. Would you like to supplement this document

**Comment by bcookew** [comment] 2024-02-20 05:56
It may be unrelated and specific to something I have done in my app but... Is anyone having difficulty with InteractiveAuto since the last update when using:
```@rendermode @(new InteractiveAutoRenderMode(prerender: false))```
The page I am trying to render is injecting services from the WASM service collection which is why I am not pre-rendering. 
Page loads no issues with
```@rendermode @(new InteractiveWebAssemblyRenderMode(prerender: false))```
But when using auto I get nothing loading and if I navigate to another page I get a circuit exception.
![image](https://github.com/dotnet/aspnetcore/assets/83699317/d25491d6-7809-40e2-af39-a05cfcbf42e1)

The component loads normally if I refresh the page once or twice. Maybe a BrowserLink / Debugging issue?
I did notice that after navigating to the page the DevTools Debugger does briefly hold on an unhandled exception but even with "Pause on uncaught exceptions" ticked it jumps over it so quickly I can't catch it.

**Comment by danielgreen** [comment] 2024-02-20 06:27
@bcookew If the page initially loads in server mode then it will be trying to resolve the injected dependencies from the server side service provider. The dependencies will need to be present there, if they're not that could explain the problems.

**Comment by bcookew** [comment] 2024-02-20 06:49
> @bcookew If the page initially loads in server mode then it will be trying to resolve the injected dependencies from the server side service provider. The dependencies will need to be present there, if they're not that could explain the problems.

Good offer. That was, in truth, where I started my day. I had a look at the MS Docs related to render modes [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#client-side-services-fail-to-resolve-during-prerendering). And followed their advice to set prerender to false. This did indeed clear the DI issue but left me with this odd behavior where the page never loads unless I refresh a couple of times. 

Open to further thoughts / discussion on this for sure!

**Comment by danielgreen** [comment] 2024-02-20 06:52
It still sounds like a DI issue. Setting prerender to false will still mean it tries to load in server (SignalR) mode initially. Then when you refresh, if the wasm resources have been downloaded by that point then after refreshing it will switch to wasm mode.
So you still need to ensure the dependencies can be resolved server side, or change the render mode from Auto to WebAssembly.

**Comment by bcookew** [comment] 2024-02-20 06:55
@danielgreen 
Thanks, I will dig deeper around that.

**Comment by Evengard** [comment] 2024-02-26 01:14
I stumbled upon a similar problem. A browser which doesn't have WASM or WASM is disabled alltogether. I tested with Firefox setting javascript.options.wasm to false. I'd expect it to still work using server-side rendering. Instead, it seems like it crashes and no interactivity works.
