### ISSUE TITLE
Access to CSS scope in RenderTreeBuilder (Blazor CSS isolation)

### ISSUE THREAD

**Issue by kefyru** [dotnet/aspnetcore#32614] opened 2021-05-12 12:40 UTC
MyComponent:

```c#
public class MyComponent: ComponentBase
{
   [Parameter]
   public string Class { get; set; }

   protected override void BuildRenderTree(RenderTreeBuilder builder)
   {
      builder.OpenElement(0, "div");
      builder.AddAttribute(1, "class", Class);
      builder.AddContent(2, "Hello world");
      builder.CloseElement();
   }
}
```

MyPage.razor:
```c#
@page "./MyPage"
<MyComponent Class="bg-red"/>
```

MyPage.razor.css:
```css
.bg-red { background-color: red }
```

This not works. To make it work, we have to wrap MyComponent with ```<div>```, than use ::deep selector...

It would be great to have possibility to access parent CSS scope identifier to do something like:

```c#
...
   builder.OpenElement(0, "div");
   builder.AddAttribute(1, builder.GetParentCssScope()); // <----
   builder.AddAttribute(2, "class", Class);
   builder.AddContent(3, "Hello world");
   builder.CloseElement();
...
```

**Comment by TanayParikh** [comment] 2021-10-21 22:13
Thanks for reporting this issue, I'm closing this as a duplicate of https://github.com/dotnet/aspnetcore/issues/30213.

**Closed by TanayParikh** 2021-10-21 22:13 UTC
Labels: enhancement, area-blazor, feature-css-isolation
