### ISSUE TITLE
(Blazor) Navigating to a non-existing page does not call Dispose() on IDisposable component

### ISSUE THREAD

**Issue by RobinLanderloos** [dotnet/aspnetcore#44539] opened 2022-10-14 09:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

(This is one for the backburner as you probably shouldn't have routes to non-existing pages)

I have a component implementing a System.Timers.Timer for some polling behaviour.
On this component I implemented the IDisposable interface and call the Timer.Dispose() method in it.

This works fine when another component is loaded onto the view or when I navigate to a working page.

However, when I navigate to a non-existing page, the component.Dispose() method doesn't get called.

### Expected Behavior

When navigating away from a page with IDisposable components to a page that doesn't exist, the components should be properly disposed.

### Steps To Reproduce

A default Blazor Server project where the Index.razor implements IDisposable and sets up and starts a System.Timers.Timer object.
On every TimerElapsed it will log to console, and when the dispose method is called, it will log this as well.

Steps to replicate bug:

1. Start solution
2. Check in the output window that the TimerElapsed log is occurring
3. Navigate to the "I Do Exist" page with the sidebar
4. Check in the output window that the disposed log event occurred
5. Navigate back to the "Index" page
6. Check in the output window that the TimerElapsed log is occurring
7. Navigate to the "I Do Not Exist" page with the sidebar
8. The disposed log will not occur and the timer will continue

https://github.com/RobinLanderloos/NoDisposeNonExistingPage

### .NET Version

6.0.401

### dotnet --info output

> .NET SDK (reflecting any global.json):
>  Version:   6.0.401
>  Commit:    0906eae6f8
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19044
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.401\
> 
> global.json file:
>   Not found
> 
> Host:
>   Version:      6.0.9
>   Architecture: x64
>   Commit:       163a63591c
> .NET SDKs installed:
>   5.0.412 [C:\Program Files\dotnet\sdk]
>   6.0.401 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>

**Comment by MariovanZeist** [comment] 2022-10-17 08:15
It also happens in net 7 rc2.

**Comment by MackinnonBuck** [comment] 2022-10-18 19:01
I think I know what is happening here. When you navigate to a "not found" route, the browser refreshes the page. In doing so, we make an attempt to disconnect the circuit, which in theory should dispose everything correctly. Under the hood, we attempt to send the disconnect message to the server by registering a handler on [`window.unload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event). However, as pointed out in the MDN docs, this event is not reliably fired. And if it doesn't get fired, the circuit doesn't terminate gracefully (so it will eventually timeout instead). In the meantime, the components that were last rendered don't get disposed, and in your repro, you will continue to see the timer fire.

Your repro project actually worked correctly on my machine, and I was unable to reproduce the bug. This is probably a symptom of the unreliable nature of the `unload` event. We've seen this unreliability [in our automated testing](https://github.com/dotnet/aspnetcore/issues/44185) as well, and plan to investigate ways to make Blazor Server circuit disconnection more reliable.

**Comment by MackinnonBuck** [comment] 2022-10-25 21:51
Going to close this as a dupe of https://github.com/dotnet/aspnetcore/issues/39409, since achieving that would resolve this issue as well.

**Closed by MackinnonBuck** 2022-10-25 21:51 UTC
Labels: area-blazor, blazor-server, feature-rendering
