### ISSUE TITLE
.NET 9: `dotnet user-jwts` not working

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [dotnet/aspnetcore#58996] opened 2024-11-16 01:45 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I followed the [MSDN](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-9.0&tabs=windows) and upon sending the HTTP Request with the Bearer token, the server returns 401. The `WWW-Authenticate` response header shows `Bearer error="invalid_token", error_description="The signature key was not found"`.

### Expected Behavior

Server returns 200.

### Steps To Reproduce

Followed the exact steps in the [MSDN](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-9.0&tabs=windows)

### .NET Version

9.0.100

### Anything else?

RID: win-arm64
It used to work on .NET 8.

**Comment by oussamatecnique** [comment] 2024-11-16 20:52
can you add more details please... like how the jwt token used in this call look like, and the appsettings.developement authentication details 
such validissuer.
this could be the issue the validIssuer used by the command line dotnet user-jwts, is not what your app expect.

**Comment by Zhiyuan-Amos** [comment] 2024-11-17 00:35
I'm aware of these possible concerns as I understand these security concepts and I had it working on .NET 8. I have attached the code from following the instructions in the above documentation [https://github.com/Zhiyuan-Amos/MyJWT](https://github.com/Zhiyuan-Amos/MyJWT) for ease of repro: Just create the JWT using `dotnet user-jwts` and try sending it to the `/secret` endpoint.

**Comment by oussamatecnique** [comment] 2024-11-17 23:31
you are right it's not working on dotnet9 I debugged deeply I found 2 issues:
1st issue:
in JwtBearerConfigureOptions

in dotnet9 the IssuersigningKeys  is not loaded from secrets.json, because of a parameter called ValidIssuers.

the difference reside in this commit:
https://github.com/dotnet/aspnetcore/commit/cc5bc6b56dc0a6e6f1ca103acff5afd9c71973ba

this can be fixed by adding this to your asppsettings: 
 "ValidIssuers": [
            "dotnet-user-jwts"
        ]
2nd issue:
if you apply this solution the token validation throws a different error.
Authentication failed: IDX10517: Signature validation failed. The token's kid is missing. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey,

I am not sure now jsonwebTokenValidator is checking also kid which is empty when you assign IssuerSigninKey by byte[]

**Comment by ig33kmor3** [comment] 2024-11-20 06:11
+1 I also had to rollback to the latest version of 8.x.x to resolve this problem. Works fine on 8.x.x

**Comment by gepa21** [comment] 2024-11-20 06:35
the problem is that with [this change](https://github.com/dotnet/aspnetcore/commit/cc5bc6b56dc0a6e6f1ca103acff5afd9c71973ba#diff-9bab7c649b4a8f9a0af36a4ae662acfc87b621b471a6774df2aca2821c7530c6L45) the `issuer` is not added to the `issuers` list and the `GetIssuerSigningKeys()` method only cares about the `issuers` list to search for signing keys

**Comment by Estyn** [comment] 2024-12-08 03:39
If anyone else is looking for a quick and dirty work around, the following worked for me.

```c#
builder.Services.AddAuthentication("Bearer").AddJwtBearer(o =>
{
    o.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
         ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuers = [builder.Configuration.GetSection("Authentication:Schemes:Bearer:ValidIssuer").Get<string>()],
        ValidAudiences = builder.Configuration.GetSection("Authentication:Schemes:Bearer:ValidAudiences").Get<string[]>(),
         IssuerSigningKey = new SymmetricSecurityKey(Convert.FromBase64String(builder.Configuration.GetSection("Authentication:Schemes:Bearer:SigningKeys:0").GetValue<string>("Value")))
    };
});
```

**Comment by michielpost** [comment] 2024-12-08 14:09
> If anyone else is looking for a quick and dirty work around, the following worked for me.
> 
> builder.Services.AddAuthentication("Bearer").AddJwtBearer(o =>
> {
>     o.TokenValidationParameters = new TokenValidationParameters
>     {
>         ValidateIssuer = true,
>          ValidateAudience = true,
>         ValidateLifetime = true,
>         ValidateIssuerSigningKey = true,
>         ValidIssuers = [builder.Configuration.GetSection("Authentication:Schemes:Bearer:ValidIssuer").Get<string>()],
>         ValidAudiences = builder.Configuration.GetSection("Authentication:Schemes:Bearer:ValidAudiences").Get<string[]>(),
>          IssuerSigningKey = new SymmetricSecurityKey(Convert.FromBase64String(builder.Configuration.GetSection("Authentication:Schemes:Bearer:SigningKeys:0").GetValue<string>("Value")))
>     };
> });

Thanks. I've also ran into this issue and this workaround solved it for me.

**Comment by rblackmore** [comment] 2024-12-11 02:22
> you are right it's not working on dotnet9 I debugged deeply I found 2 issues: 1st issue: in JwtBearerConfigureOptions
> 
> in dotnet9 the IssuersigningKeys is not loaded from secrets.json, because of a parameter called ValidIssuers.
> 
> the difference reside in this commit: [cc5bc6b](https://github.com/dotnet/aspnetcore/commit/cc5bc6b56dc0a6e6f1ca103acff5afd9c71973ba)
> 
> this can be fixed by adding this to your asppsettings: "ValidIssuers": [ "dotnet-user-jwts" ] 2nd issue: if you apply solution above the token validation throws a different error. Authentication failed: IDX10517: Signature validation failed. The token's kid is missing. Keys tried: 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey,
> 
> I am not sure now jsonwebTokenValidator is checking also kid which is empty when you assign IssuerSigninKey by byte[]

Replacing the ValidIssuer with ValidIssuers array instead, in the appsettings.Development.json file fixed this for me, Thank you.

**Comment by coderabsolute** [comment] 2024-12-11 20:11
Tokens are generated through the Firebase Authentication. This is the configuration on my side, but I got

`Authentication failed: IDX10500: Signature validation failed. No security keys were provided to validate the signature.`

```
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.Authority = "https://securetoken.google.com/your-domain-com"; // Matches the issuer
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidIssuer = "https://securetoken.google.com/your-domain-com",
            ValidateAudience = true,
            ValidAudience = "your-domain-com",
            ValidateLifetime = true
        };

        options.Events = new JwtBearerEvents
        {
            OnAuthenticationFailed = context =>
            {
                Console.WriteLine($"Authentication failed: {context.Exception.Message}");
                return Task.CompletedTask;
            },
            OnTokenValidated = context =>
            {
                Console.WriteLine("Token validated successfully");
                return Task.CompletedTask;
            }
        };
    });


 builder.Services.AddAuthorization();
```


I'm using these packages and I read somewhere that there could be an issue with the versioning - but I'm not sure.

```
<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />

```
Is anyone facing a similar issue with Firebase? If it works for you, please send me the version of your packages so that I can also use them.

**Closed** 2024-12-13 19:04 UTC
Labels: bug, area-commandlinetools, feature-userjwts
