### ISSUE TITLE
Visual Studio 16.8.0 Preview 2.1 generates erroneous TypeScript errors

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#25812] opened 2020-09-11 13:23 UTC
### Describe the bug
I have a solution that generates 3 dll's:

The first dll, GC.dll has some TypeScript files, has a tsconfig.json, and properly creates an output js file in the desired location. The content is a set of Blazor components.

The second dll, O20.dll, has no typescript, refers to GC.dll, and builder some more complex Blazor components using a mix of components from GC.dll. It has the app.razor element and is basically my Blazor app which is used in either server or wasm deployments.

The third dll, B20.dll is the wasm based dll that refers to the O20.dll and has all of the wasm required startup in its programs.cs. It has no Typescript files.

All of this builds and runs as expected until it doesn't build.

The B20.dll build fails with the following error message (repeated twice):
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS6053	Build:File 'C:/Solutions/OHI/Optimiser/Optimiser.2020.Blazor/bin/Debug_Server/net5.0/browser-wasm/Scripts/MTGrid.ts' not found.	Optimiser.2020.Blazor	C:\Solutions\OHI\Optimiser\Optimiser.2020.Blazor\tsc	1	
```

The 'Scripts/MTGrid.ts' reference is the typescript location in the GC.dll project.

The only two ways to correct this error are
1) Exit VS & reopen the project
2) Delete the bin & obj directories of the solution

A build after doing this succeeds, At some number of builds later the error re-occurs.

### To Reproduce

I can't get the broken behavior in a minimal repo at this time.

### Further technical details
```
C:\Users\ms>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

VS 16,8,0 Preview 2.1
[edit] The version of Microsoft.TypeScript.MSBuild that is installed in the GC.csproj is 4.0.2
```

**Comment by Pilchie** [comment] 2020-09-11 15:55
Hi - can you report this using the Visual Studio Feedback tool.  The code and team for this are not part of this project, and that is a better way of routing it to them.

**Comment by MarkStega** [comment] 2020-09-12 11:49
I'll do so; But my experience is that the VS Feedback mechanism is a 'black hole'; Lots of stuff goes in, nothing comes out, I was hoping that someone in the asp.net team experience the same issue.

**Comment by MarkStega** [comment] 2020-09-12 11:53
It's even worse than usual - When doing a 'report a problem' from Visual Studio it brings me to a window that says 'Disconnected from Visual Studio - Please reopen this window and reopen from a running instance of VS.

I guess this is better - It is an upfront acknowledgement that the VS team doesn't want pesky feedback.

**Comment by nikolami** [comment] 2020-09-13 08:23
@MarkStega Sorry about the feedback bug and I appreciate you letting us know. I'm on the feedback team working on the new feedback tool. Do you mind trying the workarounds for the feedback error and commenting on the following developer community issue if the workaround worked for you? https://developercommunity.visualstudio.com/content/problem/1174914/visual-studio-1672-could-not-report-a-problem-repo.html

**Comment by MarkStega** [comment] 2020-09-13 12:42
@nikolami I added the lines to the feedback.exe.config, restarted VS and got exactly the same behavior when issuing the 'report a problem. Could you please enter the details of my issue in the appropriate location while the feedback took is broken?

Thanks ,
-m-

**Comment by nikolami** [comment] 2020-09-15 00:54
Just did, https://developercommunity.visualstudio.com/content/problem/1184547/visual-studio-1680-preview-21-generates-erroneous-typescript-errors.html

hmm, interesting. For feedback: I'll finish investigating the connection issues that other customers reported, then will ping you if you don't mind sharing more information. Thanks for reporting these issues, I appreciate it!

**Comment by MarkStega** [comment] 2020-09-16 16:12
@nikolami Thanks for adding a feedback item. Since we started this dialog, VS was updated to 16.8.0 Preview 3.0; Unfortunately, the error persists when trying to report...

**Comment by nikolami** [comment] 2020-09-18 01:43
Thanks for the info @MarkStega! Would it be Ok for you if I setup a Teams call with you directly through your developercommunity email contact info to investigate the feedback issue? Several people reported a similar issue to yours recently and I'd like to understand the root cause and fix it for everyone - thanks!

**Comment by MarkStega** [comment] 2020-09-18 18:45
Certainly

**Comment by Pilchie** [comment] 2020-09-18 18:48
I'm going to close this issue, since it's not being tracked above.

**Closed by Pilchie** 2020-09-18 18:48 UTC
Labels: External
