### ISSUE TITLE
C++ client needs to support pings

### ISSUE THREAD

**Issue by BhavanaMSFT** [dotnet/aspnetcore#35516] opened 2021-08-19 18:02 UTC
The C# client supports pings. Without pings client disconnect detection takes longer (got to rely on TCP timeouts).

**Comment by BrennanConroy** [comment] 2021-08-19 18:37
Dupe of https://github.com/dotnet/aspnetcore/issues/8721

**Closed by BrennanConroy** 2021-08-19 18:37 UTC
