### ISSUE TITLE
Microsoft.AspNetCore.AzureAppServices.HostingStartup Assembly not found

### ISSUE THREAD

**Issue by DanielStout5** [dotnet/aspnetcore#37255] opened 2021-10-04 13:21 UTC
We randomly started getting a 500.31 error from our app service - enabling the stdout logs in web.config gave this error:

```
Error:
  An assembly specified in the application dependencies manifest (Microsoft.AspNetCore.AzureAppServices.HostingStartup.deps.json) was not found:
    package: 'Microsoft.AspNetCore.AzureAppServices.HostingStartup', version: '5.0.9'
    path: 'lib/net5.0/Microsoft.AspNetCore.AzureAppServices.HostingStartup.dll'
```

Running `dotnet --info` does show the 5.0.9 SDK and runtimes installed on the app service plan:

```
Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  [...]
  5.0.400 [D:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  [...]
  Microsoft.NETCore.App 5.0.9 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```

I also tried updating the ASP.NET Core Logging Integration to the latest version to see if that was related, but it didn't change anything.

**Comment by adityamandaleeka** [comment] 2021-10-04 20:15
@DanielStout5 Thanks for reporting this. Have you by any chance tried to reproduce this on another App Service instance? That would help us determine if this is something we can fix or whether this is an App Service issue to investigate further.

**Comment by DanielStout5** [comment] 2021-10-04 20:17
The issue does seem to have gone away on a different app service plan.

**Comment by adityamandaleeka** [comment] 2021-10-04 20:54
Great, thanks @DanielStout5. I'll pass this along to the app service team to see if they're aware of it. Closing this issue since there's no aspnetcore bug here.

**Closed by adityamandaleeka** 2021-10-04 20:54 UTC
Labels: area-runtime, Needs: Attention :wave:
