### ISSUE TITLE
Asp.net core .cs file encoding is not uft-8 encoded

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#37201] opened 2021-10-01 20:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Aspnet-core-cshtmls-file-encoding-for/1424016)._

---
[severity:It's more difficult to complete my work]
When creating a new razor file, the cshtml file gets UTF-8 encoded but the .cs file is ANSI encoded.
This happens if you are using a swedish windows operations system with latest VS2019.

It is very easy to reproduce.
1) Install Windows 10 Swedish version
2) Install Visual Studio 2019
3) Create a new Web Project (.net Core)
4) Add a razor page
5) Check the encoding for the newly created .cs file by doing "Save as" and select "Save with different encoding" in VS.

It might sound like a small issue but it's not.
When developing code to run on AKS, the file encoding is extreamly important.

Lets say you have a file with a comment containing. UTF-8 charaters. It will compile fine on you local machine, all tests will pass, but when you check in your code and compile it on a Linux machine, it will fail.

For every file you add you need to manually change it's encoding to UTF-8. Please fix this asap.
Please don't ask me for more information. This is 100% reproducable.

---
#### Feedback Bot on 5/16/2021, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jiahui Zhang (Beyondsoft Corporation) [MSFT] on 5/25/2021, 00:12 AM: 

<p>Thank you for your feedback! We tried to reproduce this issue with following steps:</p>
<ol>
<li>Create a C# <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core Web App project.</li>
<li>Open Pages &gt; _ViewImports.cshtml and edit it.</li>
<li>Go to File &gt; Save _ViewImports.cshtml As…</li>
<li>Click “Save with Encoding…”<br>
The Encoding shows “Western European (Windows)” instead of “Unicode(UTF-8 with signature)”.<br>
<img src="https://aka.ms/dc/image?name=Bc37fb06cdd534ff99087885cf32d4dd5637575239304462080_Actual.png&amp;tid=c37fb06cdd534ff99087885cf32d4dd5637575239304462080" alt="Actual.png"></li>
</ol>
<p>Is it the behavior of this issue? If yes, we will go through a further investigation. If not, could you help to correct us?<br>
We are looking forward to your reply!</p>

#### per.bornsjo on 5/25/2021, 00:27 AM: 

<p>Yes, that’s the problem!<br>
Both the .cs and the .cshtml should be UTF-8.</p>

#### Feedback Bot on 6/2/2021, 02:38 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment] 2021-10-06 17:07
I just re-read the issue, and it's specifically talking about .cs files in the project template that we haven't done any work on. While I agree this is a gap, this isn't a regression and I'm going to punt this to 7.0. Fixing it for ASP.NET Core's projects might not be sufficient here since this affects other non-ASP.NET Core templates and scaffolding.

**Comment by TanayParikh** [comment] 2021-10-22 00:17
Docs & infra candidate? We'll need to update our pipelines / git configs to enforce UTF8 encoding for committed files.

**Comment by mkArtakMSFT** [comment] 2021-11-17 17:22
The plan here is to follow up with @DamianEdwards and make sure that all files (including `.cs` files, which is the main problem here) are saved as UTF-8

**Comment by DamianEdwards** [comment] 2021-11-17 17:55
What's my involvement here?

**Comment by mkArtakMSFT** [comment] 2022-09-14 16:45
We need to validate this to confirm this is still the case and if not, close this. Otherwise, this will indeed be a good infra candidate.

**Comment by mkArtakMSFT** [comment] 2022-10-26 17:21
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2022-10-26 17:21 UTC
Labels: bug, area-mvc, triaged, Author: Migration Bot :robot:, Priority:2

**Comment by andreassandin** [comment] 2022-11-08 08:43
Hi. I just found this after struggling for days with a docker container that just was impossible to have a Razor page show correct characters!
I use Visual Studio 2022, so the same problem exists there to.
This is a real problem as the original comment from vsfeedback writes, and if i would not have seen this page would have been a impossible to solve without manual re-saving every cshtml.cs file for every project that this bug will happen in.
You at Microsoft should really open this again and make a fix as soon as possible.
Best Regards Andreas
