### ISSUE TITLE
Targeting pack PlatformManifest.txt built by source-build has differences vs. official build

### ISSUE THREAD

**Issue by dagood** [dotnet/aspnetcore#37651] opened 2021-10-18 19:06 UTC
After applying a source-build patch to enable targeting pack build (https://github.com/dotnet/aspnetcore/pull/37646) and building with this command:
```
eng/build.sh --no-build-repo-tasks --restore --build --pack --configuration Release /p:ArcadeBuildFromSource=true /bl /p:OfficialBuildId=20211018.7
```

Then the platform manifest in the source-build output `Microsoft.AspNetCore.App.Ref.6.0.0-dev.21518.7.nupkg` has a few lines missing vs. the official `Microsoft.AspNetCore.App.Ref.6.0.0-rtm.21518.7.nupkg` targeting pack from ~https://dev.azure.com/dnceng/public/_build/results?buildId=1427727&view=results (same base commit)~ https://dev.azure.com/dnceng/internal/_build/results?buildId=1428949&view=results:

```diff
-aspnetcorev2_inprocess.dll|Microsoft.AspNetCore.App.Ref||16.0.21291.0
 Microsoft.AspNetCore.Antiforgery.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51807
 Microsoft.AspNetCore.Authentication.Abstractions.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51807
 Microsoft.AspNetCore.Authentication.Cookies.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51807
@@ -125,6 +126,7 @@ Microsoft.Extensions.WebEncoders.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21
 Microsoft.JSInterop.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51807
 Microsoft.Net.Http.Headers.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51807
 System.Diagnostics.EventLog.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51702
-System.Diagnostics.EventLog.Messages.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|0.0.0.0
 System.IO.Pipelines.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51702
 System.Security.Cryptography.Pkcs.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51702
 System.Security.Cryptography.Xml.dll|Microsoft.AspNetCore.App.Ref|6.0.0.0|6.0.21.51702
```

* `aspnetcorev2_inprocess.dll` seems like a native DLL that only builds for Windows (IIS). I *think* the risk this causes is that if you were to use a source-built targeting pack to build and publish an app for Windows, the set of DLLs included in the output might be wrong.
* `System.Diagnostics.EventLog.Messages.dll` is missing, but the Microsoft-built version has a suspicious `0.0.0.0` vs. the others having `6.0.21.51702`. I'm not sure what this means.

@wtgodbe @dougbu can you help look into these differences and help with fixing for 6.0.0+?

/cc @dotnet/source-build-internal 

---

For now I'm going to continue with enabling the targeting pack build because it's critical for source-building 6.0.0 without prebuilts. But, it's also important to understand the impact of these diffs (and fix if nonzero) because they could have end-user impact.

Other than these diffs in the platform manifest, the source-built vs. Microsoft-built targeting packs appear the same (same set of files, other text files the same), so we're off to a pretty reasonable start. 😄 

---

This work is to make sure the source-build targeting pack behaves the same as the official targeting pack so we can resolve the targeting pack prebuilt by building it during source-build. We can't use SBRP anymore because the targeting pack contains analyzers in 6.0+. More info:
* https://github.com/dotnet/source-build/issues/2506

**Comment by wtgodbe** [comment] 2021-10-19 21:19
You're right about `aspnetcorev2_inprocess.dll`. As for `System.Diagnostics.EventLog.Messages.dll`, I believe that's related to https://github.com/dotnet/aspnetcore/pull/36248- I'm surprised to see differences on a commit from the past few days, though.  @dougbu or @ericstj may know more there.

Regardless, we use a hard-coded `platformManifest.txt` file in servicing - after 6.0.0 RTM's, we'll update https://github.com/dotnet/aspnetcore/blob/release/6.0/eng/PlatformManifest.txt, which will cause all built targeting packs to have consistent content in `platformManifest.txt`, so this inconsistency will go away:

https://github.com/dotnet/aspnetcore/blob/4c194c587503c46d9ea1dba33f90e0c77c7a20fc/src/Framework/App.Ref/src/Microsoft.AspNetCore.App.Ref.csproj#L59-L60

**Comment by ericstj** [comment] 2021-10-20 20:28
What @ViktorHofer says is correct.  It's a win32 resource assembly needed for our Windows implementation of EventLog.  EventLog is a PNSE on non-windows, so we don't need it there.

I do see that it used to be in the transport package (checked an old Preview7 one) but I don't think ASP.NET ever picked it up from there.  IIRC aspnetcore only gets reference assemblies from the transport package and gets implementation assemblies from the library packages.  @ViktorHofer I think this stopped being part of the transport package in https://github.com/dotnet/runtime/commit/21e340dcaff114d7a4f063abcf2b900d6b450751.

**Comment by dagood** [comment] 2021-10-20 21:59
Thanks for the details. It sounds like the worst this can do is cause `dotnet publish --runtime win-*` to potentially include a DLL that won't actually be used. So, it seems not worth solving for 6.0.0. Leaving the diff in the product unresolved (closing the issue) would make me uneasy though--it seems like the issue could potentially expand in future versions.

I seem to remember that dotnet/runtime has a solution for generating platform manifests that makes sure it's the same on any platform that builds the targeting pack. (There are a lot more platform-specific runtime pack DLLs there, so it's more obvious and I suppose impactful if it's not working there.) Could that infra be borrowed by aspnetcore?

**Comment by dougbu** [comment] 2021-10-20 23:14
> Could that infra be borrowed by aspnetcore?

Like @ericstj, I'm not sure where or why the difference in the Linux-only source-built targeting pack would make a difference @dagood. Shouldn't `dotnet publish` use the files in the platform-specific shared Fx when `--runtime` is passed❔

Yes, we have up this point always shipped Microsoft.AspNetCore.App.Ref as it's built on Windows. The targeting packs for other platforms also built that project and automatically leave the Windows-specific assemblies out of the PlatformManifest.txt file (and our shared framework runtimes). That _should_ mean the targeting packs correctly reflect the shared Fx content for their platforms.

Again, I'm not understanding the concern here.

**Comment by dagood** [comment] 2021-10-21 00:00
> Like ericstj, I'm not sure where or why the difference in the Linux-only source-built targeting pack would make a difference dagood.

When I read this, it seems to me to say that host would *account* for a difference, but it may happen:

> > Even if this happens the host does a check to make the decision about which to use, app or runtime. We had to do this for rollforward. Imagine someone builds a 2.1 app using a 3.0 GA package, but then rolls forward to run the app on 3.1. The runtime needs to load its 3.1 copy and avoid letting the app downgrade the shared framework.

> Shouldn't `dotnet publish` use the files in the platform-specific shared Fx when `--runtime` is passed❔

I'm not sure--seems reasonable to me that it would. I think I might have just picked the wrong scenario. A framework dependent runtime-agnostic app with Windows-specific native dependencies could run into the diff, right? (I'm forgetting if all `runtimes/win-x64/...`/`runtimes/linux-x64/...` dependencies are candidates to be copied to the publish output.)

> That _should_ mean the targeting packs correctly reflect the shared Fx content for their platforms.

Isn't the intent of a targeting pack to reflect the sharedfx content for *any* platform?

---

The reason it's hard for me to dismiss this is because the only thing I know is totally safe and will remain safe in the future is to reduce the diff to zero. The principles behind the platform manifest as I understand them (from way back when I worked on Microsoft.NetCore.App.Ref--so potentially very outdated!) seem not to be considered important here, and I'm not sure what the line is.

**Comment by wtgodbe** [comment] 2022-06-06 23:34
> The "right" fix here may be to remove aspnetcorev2_inprocess.dll and System.Diagnostics.EventLog.Messages.dll from the listing in all targeting packs.

Thoughts on this @dagood @ericstj @ViktorHofer? This would mean that the windows targeting pack would contain these 2 assemblies but not have them listed in the manifest.

**Comment by wtgodbe** [comment] 2022-08-04 23:19
@dagood @ericstj @ViktorHofer any thoughts on removing aspnetcorev2_inprocess.dll and System.Diagnostics.EventLog.Messages.dll from the platform manifest in all targeting packs?

**Comment by ericstj** [comment] 2022-08-05 16:34
> I would appreciate more information about why we'd want the PlatformManifest.txt file to list assemblies user code doesn't reference directly on any platform

The platformmanifest.txt file is not about manifesting the files referenced by user code.  It's about manifesting the files that are used at runtime.  It's what allowed us to eliminate the package graph from the 1.0 days without forcing folks to reference new empty packages or remove package references from the ecosystem.  It tells the build what files make up the product at runtime so that the application won't bring its own copy of those unless they are newer.   It contains the superset of the files that are in the framework for all runtimes.

>  This would mean that the windows targeting pack would contain these 2 assemblies but not have them listed in the manifest.

I don't think they are in the targeting pack.  They're in the runtime-packs.  If you remove them from the platfrommanifest.txt it would mean that a framework dependent application referencing packages that contain these would get a copy of the files in the application even if it didn't need them.

Probably they are missing during source build because you're looking at source build on linux and the single runtime built doesn't contain them.  That's OK for building framework dependent on that machine.  You'd get the wrong behavior if someone built framework dependent on that linux machine then wanted to run on a windows client.

**Comment by mitchdenny** [comment] 2022-11-29 02:53
We've just noticed some unit test failures related to framework/packaging in the aspnetcore:

![image](https://user-images.githubusercontent.com/513398/204426956-007679c5-3705-44ca-acaf-4cbcc805792e.png)

We are wondering if it related to this. Here is an example of a test failure:

```
  Message: 
Assert.Empty() Failure
Expected: <empty>
Actual:   ["Microsoft.Bcl.AsyncInterfaces"]

  Stack Trace: 
SharedFxTests.RuntimeListContainsCorrectEntries() line 297
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

  Standard Output: 
==== file contents ====
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Antiforgery.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Authentication.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Authentication.Cookies.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Authentication.Core.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Authentication.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Authentication.OAuth.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Authorization.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Authorization.Policy.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Components.Authorization.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Components.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Components.Forms.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Components.Server.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Components.Web.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Connections.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.CookiePolicy.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Cors.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Cryptography.Internal.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Cryptography.KeyDerivation.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.DataProtection.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.DataProtection.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.DataProtection.Extensions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Diagnostics.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Diagnostics.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Diagnostics.HealthChecks.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.HostFiltering.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Hosting.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Hosting.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Html.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Http.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Http.Connections.Common.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Http.Connections.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Http.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Http.Extensions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Http.Features.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Http.Results.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.HttpLogging.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.HttpOverrides.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.HttpsPolicy.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Identity.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Localization.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Localization.Routing.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Metadata.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.Abstractions.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.ApiExplorer.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.Core.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.Cors.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.DataAnnotations.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.Formatters.Json.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.Localization.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.Razor.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.RazorPages.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.TagHelpers.dll
runtimes/win-x64/lib/net7.0/Microsoft.AspNetCore.Mvc.ViewFeature
... truncated
```

There are more with a similar kind of flavor.

**Comment by wtgodbe** [comment] 2022-11-29 17:13
@mitchdenny where are you seeing these failures?

**Comment by mitchdenny** [comment] 2022-11-29 22:11
When you run the test cases in ```src\Framework\test\Microsoft.AspNetCore.App.UnitTests.csproj```.

**Comment by dougbu** [comment] 2022-11-30 02:18
@mitchdenny try `git clean -dfx` before your build. Something seems confused at the moment in your local repo

**Comment by mitchdenny** [comment] 2022-12-08 22:34
They were showing up in test explorer, so I was running them to make sure that my change hadn't broken anything (locally). Now that I know that they are only meant to be run during official builds I'm less concerned :)

**Comment by mkArtakMSFT** [comment] 2022-12-13 19:21
Closing this as there is no any pending action here and the initial concerns have been addressed (as by design) per @ericstj 's comment.

**Closed by mkArtakMSFT** 2022-12-13 19:21 UTC
Labels: area-infrastructure
