### ISSUE TITLE
Blazor auto-format inserts empty comment lines and messes up indentation

### ISSUE THREAD

**Issue by bprime** [dotnet/aspnetcore#19381] opened 2020-02-26 19:11 UTC
### Describe the bug
When auto-formatting code in a .razor file (CTRL+K, CTRL+D), the indentation will disappear and an empty comment line will be inserted below the closing brace of an if statement or a foreach loop. Repeated formats will add a new empty comment line.

![blazor-formatting](https://user-images.githubusercontent.com/5882025/75377822-d24c3a00-588f-11ea-8ee0-0e1df8a40aad.PNG)

### To Reproduce

1. Create a new server side Blazor project
2. Put this markup in one of the .razor files

```
<TableTemplate>
  <TableHeader>
  </TableHeader>
  <RowTemplate>
    @if (1 == 1)
    {
    }
    else
    {
    <span></span>
    }
  </RowTemplate>
</TableTemplate>
```
3. Add a TableTemplate.razor component file

```
@typeparam TItem

@code {
  [Parameter]
  public RenderFragment TableHeader { get; set; }

  [Parameter]
  public RenderFragment<TItem> RowTemplate { get; set; }

  [Parameter]
  public IReadOnlyList<TItem> Items { get; set; }
}

<table class="table table-striped table-sm">
  <thead class="thead-light">
    @TableHeader
  </thead>
  <tbody>
    @foreach (var item in Items)
    {
      @RowTemplate(item)
    }
  </tbody>
</table>
```
3. Auto format the document

Note that if you remove the `<TableHeader>` or `<span>` tag the issue doesn't happen anymore. 

### Further technical details
- ASP.NET Core v3.1
- VS2019 Enterprise v16.4.3

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by javiercn** [comment] 2020-02-26 21:52
@bprime thanks for contacting us.

@NTaylorMullen is this you?

**Comment by iamgmd** [comment] 2020-03-04 12:07
Same applies to Visual Studio for Mac.

**Comment by NTaylorMullen** [comment] 2020-03-04 17:22
> @NTaylorMullen is this you?

Nope.

@ToddGrun it looks like some of the formatting comments are making there way to the top-level buffer? This looks pretty bad.

**Comment by ToddGrun** [comment] 2020-03-05 22:40
We had a feedback issue that was related that we have fixed in the 16.6 VS release. I've verified that I'm not able to reproduce the formatting issue on that release. Thanks!

**Comment by NTaylorMullen** [comment] 2020-03-06 03:42
Awesome, thanks Todd!

**Closed by NTaylorMullen** 2020-03-06 03:42 UTC
Labels: area-blazor, feature-razor.tooling

**Comment by iamgmd** [comment] 2020-03-06 03:50
Hi Todd, Currently, 16.5 preview 5.0 is in use, when will 16.6 be available?

**Comment by ToddGrun** [comment] 2020-03-06 18:00
My (limited) understanding is that the first preview should be available in a couple weeks.
