### ISSUE TITLE
TryUpdateModelAsync validates deep objects in excluded properties

### ISSUE THREAD

**Issue by grammophone** [dotnet/aspnetcore#25516] opened 2020-09-01 22:33 UTC
### Describe the bug
Calling `TryUpdateModelAsync` method inside a controller makes recursive deep validation on an object graph following properties which where explicitly excluded from `includeExpressions`. Only properties in `includeExpressions` should have been navigated. This also departs from what ASP.NET MVC 5 does.

### To Reproduce
Just try something like:
``` CSharp
await TryUpdateModelAsync(
  userModel.User,
  nameof(userModel.User),
  u => u.FirstName,
  u => u.LastName);
```

If the `User` in the above model has a property like `Group`, and the `Group` has a collection of `Users`, then the group and all users of the group will be validated as well, despite that the `Group` property was excluded from `TryUpdateModelAsync`. If this is an Entity Framework object with lazy loading enabled, this will load up the whole database. 

### Further technical details
- ASP.NET Core 3.1
- .NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005
- Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\
Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b
- Visual Studio 2019 16.7.2

**Comment by brunolins16** [comment] 2021-12-01 00:10
I did some investigation and @grammophone analysis is correct, basically, during the `TryUpdateModelAsync` execution the `propertyfilter` is used during the **_binding_** operation but not during the **_validation_**.

https://github.com/dotnet/aspnetcore/blob/f444e01827c12766a5d3dd3dca0781783d332b10/src/Mvc/Mvc.Core/src/ModelBinding/ModelBindingHelper.cs#L314

I don't see any indication of workaround or even a code that use the specified filter for the validation during the ModelUpdate, however, @pranavkm, will be great, if you could confirm if that is the expected design or not? If not, I can start working on add the needed support.

**Comment by pranavkm** [comment] 2021-12-01 16:58
You can use [SuppressChildValidationMetadataProvider](https://docs.microsoft.com/aspnet/core/mvc/models/model-binding?#exclude-specified-types-from-model-binding) or [`ValidateNeverAttribute`](https://docs.microsoft.com/aspnet/core/mvc/models/validation#built-in-attributes) to suppress validation for certain types or properties. Given these exist, I don't think it's necessary to introduce new ways to suppress validation.

**Comment by grammophone** [comment] 2021-12-01 17:12
Dear @pranavkm,

Is it the same to use `SuppressChildValidationMetadataProvider` to statically and always suppress validation of all child properties of an object instead of excluding some properties on a use-case basis when calling `TryUpdateModelAsync`?

Is it the same to bake a `ValidateNeverAttribute` into a property to statically and always suppress validation of the property instead of excluding it on a use-case basis when calling `TryUpdateModelAsync`?

Is what you propose a solution?

Thank you.

**Comment by pranavkm** [comment] 2021-12-01 18:53
@grammophone I admit it's not great, but given how little feedback we have received on this, it seems like a reasonable solution. A more obtuse workaround which does not involve adding a new API would be to bind to a view model (and I usually encourage this since it very clearly delineates what gets bound and validated) and map that to your data model.

**Comment by grammophone** [comment] 2021-12-01 21:01
Dear @pranavkm,

Thank you for your answer. I was expecting that you would mention view models and to change my architecture.

The choice of my architecture is very conscious, and I was hoping that the new version of ASP.NET would not hinder my decision. I chose ASP.NET MVC classic and now Core as a server-side technology for the following reasons:

- Drastically limit the real-life explosion of manual and auto mappings back and forth. Otherwise, I could have gone with a client-side architecture. This is noise code that adds no logic, exposes surface for bugs and code update concerns, distracts lines of code from intent to focus on technicalities, all costing time and money.
- Avoid copying the same metadata on properties on exploded view models. Another costly repetition.
- Avoid repeating the same validation attributes or `IValidatableObject` implementations on exploded view models. Another distraction and costly repetition. If there is an exceptional need, first, I have built on-the-fly validation or metadata injection for Classic and Core; secondly, view models are always welcome in this minority of cases. 
- Avoid the friction, repetition and effort of synchronizing relations and collections of complex objects and their view models. My enhanced complex model binders for both Classic and Core help things even further.
- As for model injection and security threats, my framework impersonates and automatically checks every access to models in a cross-cutting way, declaring the access rules in a single place. No unauthorized, reads, writes, creations, deletions, model injections can take place.
- For adding UI state, we can employ a MVVM pattern to enclose models instead of rewriting view models from scratch, greatly benefiting from generics, for example having a `IPagedResults<TResult, TRequest> where TRequest : IPagedRequest`  instead of, well, exploding view models.
- Code which focuses on intent rather technical noise reduces bugs, reduces footprint, increases performance, improves maintainability and really shortens time and resources to bring about a project. 

I am aware of the trends, but I have also many years of experience in frameworks and full-stack building and I had to bring these skills to create robust and secure projects in record time and resources. So, instead of changing my architecture, I derived a class from `Controller`, albeit dirtily, to behave like ASP.MVC 5 did.

Thank you for reading these thoughts.

**Comment by brunolins16** [comment] 2021-12-14 00:40
@grammophone we appreciate your time sharing your thoughts and they make sense in general, however, as stated by @pranavkm, we have a reasonable solution right now and a little feedback related to the current behavior. With that, I am closing this issue as By Design. Thanks.

**Closed** 2021-12-15 01:00 UTC
Labels: bug, :heavy_check_mark: Resolution: By Design, feature-Model-Binding, Status: Resolved, affected-few, severity-major, area-web-frameworks
