### ISSUE TITLE
Updating a `workload` during the "patch Tuesday" release window corrupts most dotnet commands on Linux and macOS

### ISSUE THREAD

**Issue by StudioLE** [dotnet/aspnetcore#55032] opened 2024-04-09 17:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When `dotnet workload install wasm-tools` (or any other workload) is run on a linux or macOS machine during the "patch Tuesday" release window it corrupts most of the `dotnet` commands.

This issue was first noted on a GitHub Actions build but subsequently experienced by multiple users on their local machines.

Command and output:

```
$ dotnet workload install wasm-tools

Skipping NuGet package signature verification.
Skipping NuGet package signature verification.
Installing workload manifest microsoft.net.sdk.android version 34.0.95...
Installing workload manifest microsoft.net.sdk.ios version 17.2.8043...
Installing workload manifest microsoft.net.sdk.maccatalyst version 17.2.8043...
Installing workload manifest microsoft.net.sdk.macos version 14.2.8043...
Installing workload manifest microsoft.net.sdk.maui version 8.0.7...
Installing workload manifest microsoft.net.sdk.tvos version 17.2.8043...
Installing workload manifest microsoft.net.workload.mono.toolchain.current version 8.0.4...
Installing workload manifest microsoft.net.sdk.aspire version 8.0.0-preview.5.24201.12...
Workload installation failed. Rolling back installed packs...
Installation rollback failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '8.0.3' is lower than version '8.0.4' required by manifest 'microsoft.net.workload.mono.toolchain.current' [/usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.4/WorkloadManifest.json]
Workload installation failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '8.0.3' is lower than version '8.0.4' required by manifest 'microsoft.net.workload.mono.toolchain.current' [/usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.4/WorkloadManifest.json]
Error: Process completed with exit code 1.
```

### Expected Behavior

Expected to be able to update a workload at any time without it corrupting the local system.

### Steps To Reproduce

Execute the following during a "patch Tuesday" release window when some but apparently not all dependencies have been released.

```
dotnet workload install wasm-tools
```

### .NET Version

8.0.202

### Anything else?

Developers should not have to have knowledge of the .NET release process. The tooling should have checks built in to ensure that any dependencies it's installing are actually available.

The tools should either:

- Fail with a warning that not all dependencies of the next version are available, or
- Install the existing working version - ie as `8.0.4` was only partially released the tool should have fallen back to `8.0.3`

**Comment by martincostello** [comment] 2024-04-09 18:01
The 8.0.4 release is in the process of being published as we speak as part of Patch Tuesday, but it's not an atomic process and takes some time to complete, culminating with it being available from the .NET website for download.

Does your CI pin all of your dependencies to specific versions, or do you have some floating versions somewhere? If the latter, then if the CI runs while a new monthly release is being published, then there will be a window of time where the versions aren't coherent and may be incompatible with each other, like you've experienced.

**Comment by martincostello** [comment] 2024-04-09 18:23
When I said "CI", what I meant "build and source control" rather than specifically _just_ your Continuous Integration environment.

I'm not aware of a way to get `dotnet workload install` to use a specific version. [According to the documentation](https://learn.microsoft.com/dotnet/core/tools/dotnet-workload-install#results-vary-by-sdk-version) it's appears to be tied to the .NET SDK version used.

The .NET 8.0.4 release changes were merged a few minutes ago (https://github.com/dotnet/core/pull/9262), my own personal automation has even kicked in updating my repositories (https://github.com/martincostello/alexa-london-travel/pull/1150?notification_referrer_id=NT_kwDOABX2bbMxMDE5MjY4MTQyNDoxNDM5MzQx), so if you re-run now or in a few minutes, you'll probably find the problem will have resolved itself.

As I originally noted though, unless there's a way for your code to pin all the versions (e.g. with a `global.json` file, etc.), then there will be a period during a new release when the versions won't all be aligned/available until the rollout is completed.

**Comment by MaximG1234** [comment] 2024-04-10 09:50
Thanks heaps @StudioLE, I ran into this issue with MAUI and following your suggested steps worked for me. I don't think the SDK version matters as I already had 8.0.203 installed.

**Comment by MaximG1234** [comment] 2024-04-10 10:08
@StudioLE I suppose it must have been, I initially attempted to install MAUI workloads at around maybe 12am-1AM Melbourne, Australia time yesterday.

**Comment by MaximG1234** [comment] 2024-04-10 10:09
The exact command was: `dotnet workload install maui`

**Comment by martincostello** [comment] 2024-04-10 10:53
This issue isn't ASP.NET Core specific from what I can tell as it looks like it would affect any workload.

It looks like https://github.com/dotnet/aspnetcore/issues/55032#issuecomment-2045930325 mentions issues that will either improve or fix this in a future SDK feature release.

I'm not sure if we should transfer the issue to dotnet/sdk, or close this as an effective duplicate of the issues those fix PRs relate to.

**Comment by martincostello** [comment] 2024-04-10 11:10
I'd say this was a dupe of https://github.com/dotnet/sdk/issues/23820 then.

**Comment by MUJaCHe66** [comment] 2024-04-10 13:54
Same issue on Windows machine with Winui 3 project not being able to load after Windows and Visual Studio updates.

**Closed** 2024-04-11 16:34 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-infrastructure, Status: Resolved
