### ISSUE TITLE
Introduction of a new ASP.NET Core application project template - ASP.NET Core App with TailwindCSS framework

### ISSUE THREAD

**Issue by SirCypkowskyy** [dotnet/aspnetcore#46745] opened 2023-02-19 13:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I believe that the implementation of Bootstrap as the default CSS formatting solution for a sample project is somewhat outdated - it is an increasingly unpopular solution that (in my humble opinion) could be replaced by a new solution, in the form of TailwindCSS.

TailwindCSS has a number of advantages over Bootstrap, and I've listed a couple of them below, due to which I believe that it would be of value to create an ASP.NET Core application template with this framework.

## 1. Control over stylization

Tailwind is a fairly unique CSS platform when it comes to styling web applications, meaning that Tailwind doesn't have a default theme that you have to use like other CSS frameworks.

For example, you can give each project a different look, even if you use the same elements (colour palette, size, etc.). Therefore, it is one of the few CSS frameworks that does not dictate how you should style your design (unlike Bootstrap, which is currently used).

## 2. Versatility of operation

TailwindCSS works with almost all libraries and frameworks for creating dynamic UI (e.g. React, Vue, Angular). Therefore, further expansion of the project with further libraries and frameworks should not be problematic.

## 3. Faster CSS styling process

There is no faster framework than Tailwind when it comes to HTML styling. As a result, you can effortlessly create good-looking layouts by directly styling elements. This is possible because Tailwind offers thousands of embedded classes that do not require you to create projects from scratch.

Thus, you do not need to write CSS rules yourself. These CSS classes are the main reason why creating and styling with Tailwind is so fast.

## 4. Responsiveness and security 

With Tailwind's ready-made classes, you can design the layout directly in the HTML file. This makes it a highly responsive, mobile-friendly CSS framework. In addition, Tailwind has proven to be a stable framework since its first version.

The framework has been developed by top-notch engineers, so bugs and prolonged interruptions in subsequent updates are rare. 

## 5. Additional features 

Tailwind's CSS runs in the website interface. For this reason, developers should demand maximum responsiveness. As a matter of fact, Tailwind provides the ability to create responsive themes for web applications and to remove all unused CSS classes. With PurgeCSS, Tailwind helps to keep the final CSS layer as small as possible.

# Conclusion

Of course, this is only part of Tailwind's advantages. On their own, however, they significantly incentivise the creation of an official ASP.NET Core application template utilising this framework as the baseline web styling solution.

### Describe the solution you'd like

- Implementation of an ASP.NET Core project template utilising TailwindCSS.
- (Optional) Implementation of code completion hints, when using TailwindCSS in your project, in `.razor` and `.cshtml` files, along the lines of the related solution in [Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)

**Comment by javiercn** [comment] 2023-03-01 15:21
@SirCypkowskyy thanks for contacting us.

This issue is a duplicate of https://github.com/dotnet/aspnetcore/issues/40935

**Closed by javiercn** 2023-03-01 15:21 UTC
Labels: area-mvc
