### ISSUE TITLE
Suggestion for mixing Blazor Webassembly and Server

### ISSUE THREAD

**Issue by jtheisen** [dotnet/aspnetcore#43508] opened 2022-08-24 06:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

In Blazor Webassembly components are rendered on the client, in Blazor Server they are rendered on the server.

In NextJS, React components can be rendered on the server and but then also re-rendered on the client.

I'm relatively new to Blazor and wondering why Blazor has such a strict separation between client and server rendering compared to NextJS. Really, I want both.

### Describe the solution you'd like

While I can see that rendering a component in an entirely different environment is hair-raisingly complicated and error-prone in the context of Blazor (it's already icky in React), there is some much more simple middle ground: Have some components always render on the server and some always on the client.

The components I want rendering on a client are those with lots of UI state and DOM event handlers. The components I want rendered on the server are those visible after initial page navigation. While there is an overlap, I think with some care and perhaps some minor duplication of components in that overlap this approach should work fine.

Still, the server side must be able to trigger a client-side component update by setting parameters:

```
<MyServerSideComponent>
    <MyClientSideComponent SomeParam="@Foo" />
</MyServerSideComponent>

@code {
    // ...
}
```

This would be a Blazor Server component that, when updated, doesn't itself re-render `MyClientSideComponent` but merely sends the parameter values to the client and has the client Blazor WebAssembly do the updating.

There's less of a need for the other way round.

The way I anticipate using this would less or even do away with the need for server-side state in Blazor Server, which is mostly to allow for maintaining state for UI components.

### Additional context

This is a suggestion mostly, but if there's something good to say to the following questions I'd be happy about some pointers.

- Is there an approach that already gives me much of this with the current state of Blazor?
- Is there a discussion around issues like this I haven't found yet?

**Comment by javiercn** [comment] 2022-08-24 11:39
This is a dupe of https://github.com/dotnet/aspnetcore/issues/38128 please upvote that issue instead.

**Closed by javiercn** 2022-08-24 11:39 UTC
