### ISSUE TITLE
Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated fails

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#36472] opened 2021-09-13 16:32 UTC
## Failing Test(s)

Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated

-

## Error Message

```
Assert.NotEqual() Failure
Expected: Not Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
```

## Stacktrace

```
   at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated() in /_/src/Hosting/Hosting/test/HostingApplicationTests.cs:line 122

```
## Logs

```
[xUnit.net 00:00:01.98]     Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated [FAIL]
[xUnit.net 00:00:01.98]       Assert.NotEqual() Failure
[xUnit.net 00:00:01.98]       Expected: Not Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
[xUnit.net 00:00:01.98]       Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
[xUnit.net 00:00:01.99]       Stack Trace:
[xUnit.net 00:00:01.99]         /_/src/Hosting/Hosting/test/HostingApplicationTests.cs(122,0): at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated()
Application startup exception: System.Exception: Exception from ConfigureServices
   at Microsoft.AspNetCore.Hosting.Fakes.StartupConfigureServicesThrows.ConfigureServices(IServiceCollection services) in /_/src/Hosting/Hosting/test/Fakes/StartupConfigureServicesThrows.cs:line 14
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters) in /_/src/Hosting/Hosting/src/Internal/MethodInfoExtensions.cs:line 17
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services) in /_/src/Hosting/Hosting/src/Internal/ConfigureServicesBuilder.cs:line 53
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection) in /_/src/Hosting/Hosting/src/Internal/ConfigureServicesBuilder.cs:line 28
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services) in /_/src/Hosting/Hosting/src/Internal/ConfigureServicesBuilder.cs:line 26
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services) in /_/src/Hosting/Hosting/src/Internal/ConfigureServicesBuilder.cs:line 22
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services) in /_/src/Hosting/Hosting/src/Internal/StartupLoader.cs:line 128
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services) in /_/src/Hosting/Hosting/src/Startup/ConventionBasedStartup.cs:line 42
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices() in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 194
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize() in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 118
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication() in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 223
```
## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1358128&view=results

**Comment by Tratcher** [comment] 2021-09-13 16:38
Duplicate of https://github.com/dotnet/aspnetcore/issues/35142

**Closed** 2021-09-13 16:39 UTC
Labels: test-failure, area-runtime, feature-hosting
