### ISSUE TITLE
Add JS isolation

### ISSUE THREAD

**Issue by talley** [dotnet/aspnetcore#30902] opened 2021-03-13 04:23 UTC
Add  JS isolation like this

Index.cshtml
Index.cshtml.css
Index.cshtml.js
![js isolation](https://user-images.githubusercontent.com/6354720/111018923-0191f400-838a-11eb-83c8-b12b768b7eb0.png)

**Comment by javiercn** [comment] 2021-03-15 13:09
@talley thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/30850

**Closed** 2021-03-15 13:10 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-mvc
