### ISSUE TITLE
Hot reload not working on .cshtml (converted project) - Workound found but unsure why it's needed

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/aspnetcore#39111] opened 2021-12-19 06:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I recently updated my asp.net core project from .net 5 to .net 6

Everything in hot reload seems to work fine except for `.cshtml` files. 
I've gone through all the issues associated such as response caching etc

**Workaround**
I was finally able to get hot reloading working for .cshtml by enabling the following in my `.csproj`
```xml
<ItemGroup>
	  <!-- extends watching group to include *.cshtml files -->
	  <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
  </ItemGroup>
```

I wonder why the above is necessary? 

Interestingly enough if I create a new project I don't need to do the above, so I'm just wondering what I can do about it?

**Edit**
I just tested on a new project and added runtimecompilation package and indeed .cshtml files stopped working
So it seems there is an issue here?
`xml
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.1" />
`

### Expected Behavior

Hot reload should work on .cshtml files

### Steps To Reproduce

I would provide a repo if there is a need to

### .NET Version

6.0.101

### Anything else?

asp.net core 6.0.1
Visual Studio 22
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

**Comment by TanayParikh** [comment] 2021-12-19 16:42
Duplicate of https://github.com/dotnet/aspnetcore/issues/38809

**Closed** 2022-01-14 03:39 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, feature-hot-reload
