### ISSUE TITLE
Enum route binding are case sensitive

### ISSUE THREAD

**Issue by PureKrome** [dotnet/aspnetcore#56952] opened 2024-07-23 16:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a route/querystring parameter is model binded, it only works if the value is the exact casing (aka. case sensitive).

Enums model binding should be case -insensitive-

### Expected Behavior

Case insensitive model binding for enum's.

e.g

GET/optiona resolves the endpoint and returns the string OptionA

### Steps To Reproduce

```
dotnet new webapi -minimal
```

```
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);
builder.Services.Configure<Microsoft.AspNetCore.Http.Json.JsonOptions>(o =>
{
    o.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    o.SerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
    o.SerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
});

var app = builder.Build();

app.MapGet("/", () => "Hello World!");
app.MapGet("/{myenum}", ([FromRoute] MyEnum myenum) =>
{
    return Results.Ok(myenum.ToString());
});

app.Run();

public enum MyEnum
{
    OptionA,
    OptionB
}
```

Navigate to /optiona and be shown an error
> BadHttpRequestException: Failed to bind parameter "MyEnum myenum" from "optiona".

Navigate to /OptionA and see "OptionA" in the response body of the browser.

### Exceptions (if any)

N.A.

### .NET Version

8.0.303

### Anything else?

This is a duplicate of #45590 which is now closed 😢 It was requiring human feedback from the author but never got it so it's auto closed.

I think it should be reopened and the suggested _workaround_ not a fair suggestion at all. I feel like this should be default to case _insensitive_ with a possible "setting" to make it either sensitive-or-insensitive

Visual Studio (latest community edition)

```
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.34944930
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.35027.167
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.424 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Projects\<snipped>\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by martincostello** [comment] 2024-07-23 17:12
Duplicate of #52497

**Closed by martincostello** 2024-07-23 17:12 UTC
Labels: area-web-frameworks

**Comment by PureKrome** [comment] 2024-07-24 01:38
Thanks @martincostello - i'll now subscribe to #52497 and 🙏🏻 it slips into a vnext not too long in the future. Cheers and keep fighting the good fight!
