### ISSUE TITLE
JavaScript InterOp Error : Can't find JavaScript function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#58071] opened 2024-09-25 14:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/JavaScript-InterOp-Error-:-Cant-find-Ja/10749435)._

---
[severity:It bothers me. A fix would be nice]
Blazor/Wasm .Net8 VS 20

![C#callJsEer.png](https://aka.ms/dc/image?name=B87af6ffa94dd4b42b2bf8a047aac470e638623531719791822_C#callJsEer.png&tid=87af6ffa94dd4b42b2bf8a047aac470e638623531719791822)
22 community 17.11.4

"showAlert" JavaScript functon can't not be found in wwwroot/JScripts/SiteScript.js  
 by the standard coding scheme

1. Index.html
```html
<body>
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="JScripts/SiteScript.js"></script>
</body>
```
3. In wwwroot/JScripts/SiteScript.js  file
```js
function showAlert(name) {
    alert('Hello ' + name);
}
```

5. In Register.razor
```csharp
    protected override async Task OnInitializedAsync()
    {
        await JSRuntime.InvokeVoidAsync("showAlert", "Unkown user");
        //await JSRuntime.InvokeVoidAsync("EnableAllSubDivs", "EditUser");
    }
```
---
#### Feedback Bot on 9/19/2024, 06:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by ShingYehGit** [comment] 2024-09-29 22:24
It will work as following coding scheme
1. in IIndex.html
<body>
........
    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="SiteScript.js"></script>
---------------------------BEWARE don't put in a www.... directory--------------- 
</body>
2. in SiteScript.js
function helloFunction() {
    alert("Hello Blazor Web Assembly");
}

function showAlert(name) {
    alert('Hello ' + name);
}

3.In Page Razor

@inject IJSRuntime JS

<h1>Hello, world!</h1>
<button @onclick="CallJavaScript">Click Me</button>
@code
{

    protected override async Task OnInitializedAsync()
    {
        var jsInProcess = (IJSInProcessRuntime)JS;
        await jsInProcess.InvokeVoidAsync("showAlert", "Samuel Wang");//Work
    }

    private async Task CallJavaScript()
    {
        //WORK await JS.InvokeVoidAsync("helloFunction");
        // NOT WORK await JS.InvokeVoidAsync("showAler", "Samuel Wang");

        var jsInProcess = (IJSInProcessRuntime)JS;
        //jsInProcess.InvokeVoid("showAlert", "Unkown user");//Work
        await jsInProcess.InvokeVoidAsync("showAlert", "Unkown user");//Work
        //jsInProcess.InvokeVoidAsync("helloFunction");//WORK
    }

Well ! good luck! and be happy in coding

**Comment by mkArtakMSFT** [comment] 2024-09-30 16:29
Thank you for filing this issue. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.

**Comment by MackinnonBuck** [comment] 2024-10-01 16:35
Closing as a duplicate of https://github.com/dotnet/aspnetcore/issues/58174

**Closed by MackinnonBuck** 2024-10-01 16:35 UTC
Labels: Needs: Author Feedback, area-blazor, Author: Migration Bot :robot:, feature-blazor-jsinterop, Needs: Repro

**Comment by ShingYehGit** [comment] 2024-10-01 23:30
Whatever tough SOS!
Check 
https://github.com/ShingYehGit/WasmSkiaApp/tree/master/WasmSkiaApp

![InterOpErr1](https://github.com/user-attachments/assets/fd77f9d0-75bc-43ee-87a7-93b691402008)
![InterOpErr](https://github.com/user-attachments/assets/bf5230e4-5990-4735-9c0a-2bf2574539a2)

1. All input component in EditForm should be actively enabled ready for inputing
2. Interop won't work to solve above 1.

**Comment by ShingYehGit** [comment] 2024-10-01 23:32
Help SOS things tough

Mackinnon Buck ***@***.***> 於 2024年10月1日 週二 上午11:35寫道：

**Comment by mkArtakMSFT** [comment] 2024-10-04 17:54
Looks like you're missing a closing curly bracket `}` in the SiteScript.js file (the last function isn't closed). And that's causing the function not to be found later.
