### ISSUE TITLE
JSInterop : allow capture of JS variable reference

### ISSUE THREAD

**Issue by RemiBou** [dotnet/aspnetcore#21598] opened 2020-02-11 14:53 UTC
### Is your feature request related to a problem? Please describe.

Right now it's difficult to keep a reference of a js variable from your .net code : you need to write some interop code where you identify instance with an ID, then return this ID to .net etc ... 

The feature request would be to be able to get reference of a JS object in JS interop then call method on those instance. 

### Describe the solution you'd like

I started working on a solution that looks like how you manage elementref or dotnetobjectref here : https://github.com/RemiBou/BrowserInterop/blob/master/src/BrowserInterop/scripts.js

By implementing a "reviver" with a WeakMap (so the instance are not kept around forever) :

```js
    var weakMap = new WeakMap();
    var weakMapKeys = {};
    var jsObjectRefId = 0;

    const jsRefKey = '__jsObjectRefId'; // Keep in sync with ElementRef.cs
 //reviver will help me store js object ref on .net like the .net do with elementreference or dotnetobjectreference
    DotNet.attachReviver((key, value) => {
        if (value &&
            typeof value === 'object' &&
            value.hasOwnProperty(jsRefKey) &&
            typeof value[jsRefKey] === 'number') {

            var id = value[jsRefKey];
            if (!(id in weakMapKeys) && !weakMap.has(weakMapKeys[id])) {
                throw new Error("This JS object reference does not exists : " + id);
            }
            const instance = weakMap.get(weakMapKeys[id]);
            return instance;
        } else {
            return value;
        }
    });
```
And I get a member reference like this

```js
this.getInstancePropertyRef = function (instance, propertyPath) {
        var res = me.getInstanceProperty(instance, propertyPath);
        var id = jsObjectRefId++;
        weakMapKeys[id] = { id: id };
        weakMap.set(weakMapKeys[id], res);
        var jsRef = {};
        jsRef[jsRefKey] = id;

        return jsRef;
    };
```
And in C# I have this struct (I am too lazy to create a custom serializer for now) :
```cs
 public struct JsRuntimeObjectRef
    {
        [JsonPropertyName("__jsObjectRefId")]
        public int JsObjectRefId { get; set; }
}
```

So the user can keep around reference to JsRuntimeObjectRef and call method on it with this js function

```js
this.callInstanceMethod = function (instance, methodPath, ...args) {
        var method = me.getInstanceProperty(instance, methodPath);
        return method.apply(instance, args);
    }
```

For now it works well. The last evolution I need to do is to be able to get the reference AND the content of the object so I don't need interop call everytime I need to access a property (I hesitate between a generic class that hold the value and the ref  OR a base class that hold the ref).

What do you think ? Should this be part of Microsoft.JSInterop or is it better to keep it in a 3rd party lib ? 

I copied only the code that seems relevant for me, if you need more code, I'll be happy to send more.

**Comment by mrpmorris** [comment] 2020-05-12 15:08
Why a weakmap?

**Comment by RemiBou** [comment] 2020-05-12 15:17
I changed my code for a classic map. At first I used a WeakMap so we wouldn't keep object in memory for ever. But WeakMap doesn't fit my needs (the oject is the key of the map...). So I did the same as jsinterop : implement IAsyncDisposable and remove ref on Dispose

**Comment by mrpmorris** [comment] 2020-05-12 20:06
Yeah, you want to keep the reference, because dotnet potentially holds a reference.

**Comment by mkArtakMSFT** [comment] 2020-07-30 16:33
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/24434

**Closed by mkArtakMSFT** 2020-07-30 16:33 UTC
Labels: area-blazor, enhancement
