### ISSUE TITLE
Blazor Wasm issue with Nullable Ref Types enabled and Component Generic base class

### ISSUE THREAD

**Issue by WayneHiller** [dotnet/aspnetcore#26971] opened 2020-10-16 16:28 UTC
### Describe the bug
Blazor Wasm issue with Nullable Ref Types enabled and a Component Generic base class

Created a basic Blazor Wasm Hosted Pwa project in VS. 

Added a CmpBase<T> class:
```
public class CmpBase<T> : ComponentBase
{
}
```

Created a Counter.razor.cs code behind class:
```
public partial class Counter : CmpBase<string>
    {
        private int currentCount = 0;

        private void IncrementCount()
        {
            currentCount++;
        }
    }
```

Changed counter.razor to:
```
@page "/counter"
@inherits CmpBase<string>

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
```

In the Client project add:
```
  <PropertyGroup>
    ....
    <Nullable>enable</Nullable>
  </PropertyGroup>
```

Compile and get errors:

![image](https://user-images.githubusercontent.com/1186731/96283493-22981980-0f91-11eb-9897-84c2cf31b011.png)

Set Nullable disabled in project file, compile and no errors.
```
<Nullable>disable</Nullable>
```

### To Reproduce

https://github.com/WayneHiller/BlazorWasmPwa

### Further technical details
- ASP.NET Core version 5.0.100-rc.2.20479.15
- VS Version 16.8.0 Preview 4.0

**Comment by SteveSandersonMS** [comment] 2020-11-06 19:27
Seems like this may be a duplicate of https://github.com/dotnet/aspnetcore/issues/27218

**Comment by SteveSandersonMS** [comment] 2021-08-03 17:58
Closing as duplicate of #27218

**Closed by SteveSandersonMS** 2021-08-03 17:58 UTC
Labels: affected-medium, area-blazor, area-razor.compiler, bug, feature-razor.language, nullable, reevaluate, severity-major
