### ISSUE TITLE
Blazor PWA Not Able to Install After Publishing on Azure Web Service

### ISSUE THREAD

**Issue by theumairtahir** [dotnet/aspnetcore#39195] opened 2021-12-27 08:37 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have created an application using Blazor WebAssembly (.Net 5) named as Altanzil.org. The main feature of this application was to be offline as PWA. In the development environment it was working fine and the PWA install button was appearing accurately. But as soon as I published the application on the production using Azure, the install button is not showing and the service worker throws some integrity errors. I have explored the some other related issues on this aspect but does not find any thing to counter my issue.
I have used the default service worker and method provided by the Microsoft with the template. My application link is https://altanzil.org and it is deployed on azure webapp service (windows).

Browser Console errors:
Failed to find a valid digest in the 'integrity' attribute for resource 'https://altanzil.org/manifest.json' with computed SHA-256 integrity 'yVFLqAnHMupUocO8sJG2St43rtWBklEEIv8dV6DgpzI='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:22 Uncaught (in promise) TypeError: Failed to fetch
    at service-worker.js:22
    at async onInstall (service-worker.js:22)

One more thing I need to mention here is that the domain "altanzil.org" is forwarded to "altanzil.azurewebsites.net".
Please help me in solving this issue on priority biases as I have to deliver the project to my client. Thank You. 

### Expected Behavior

I need a standard install button which appears on the top bar to install the PWA. 

### .NET Version

.net 5

**Comment by pranavkm** [comment] 2021-12-27 19:16
@ut786 I'm able to install the app using the website you listed. Were you able to resolve the integrity error you encountered? We also provide a script to help resolving integrity errors as part of our docs: https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#resolve-integrity-check-failures

**Comment by ut786** [comment] 2021-12-28 08:43
> @ut786 I'm able to install the app using the website you listed. Were you able to resolve the integrity error you encountered? We also provide a script to help resolving integrity errors as part of our docs: https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#resolve-integrity-check-failures

@pranavkm The issue is not resolved on my side yet nor on my client's side. Can you please share me how do you accessed the URL?
I am attaching my screenshot below
![image](https://user-images.githubusercontent.com/38358557/147547078-afafa09a-f5e4-4966-8595-abfb3a0156ff.png)

Plus I am going to check the docs you've shared with me.

**Comment by pranavkm** [comment] 2021-12-28 15:33
Here you go: 
![Screencap](https://user-images.githubusercontent.com/174281/147581323-567b26b1-f32b-4276-b877-116149cd25b7.gif)

I wonder if it's HTTP (over)caching that is causing this. Perhaps try deleting your application's cache from the browser, turn off network caching and retry. If that's the case you might want to consider tweaking your host to return different headers. ASP.NET Core will return `Cache-Control: no-cache` for the service-worker.js and service-worker-assets.js to ensure that these files are always checked for updated content. 

Unrelated, I noticed that your app is returning uncompressed binaries rather than the brotli compressed ones which would mean increased app size and startup time. Have a look at https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#compression,

**Comment by ut786** [comment] 2021-12-28 18:48
@pranavkm Thanks for the guidance. Let me check that if it works.

**Comment by ut786** [comment] 2021-12-29 07:32
> Here you go: ![Screencap](https://user-images.githubusercontent.com/174281/147581323-567b26b1-f32b-4276-b877-116149cd25b7.gif)
> 
> I wonder if it's HTTP (over)caching that is causing this. Perhaps try deleting your application's cache from the browser, turn off network caching and retry. If that's the case you might want to consider tweaking your host to return different headers. ASP.NET Core will return `Cache-Control: no-cache` for the service-worker.js and service-worker-assets.js to ensure that these files are always checked for updated content.
> 
> Unrelated, I noticed that your app is returning uncompressed binaries rather than the brotli compressed ones which would mean increased app size and startup time. Have a look at https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#compression,

@pranavkm I have tried your solution but I is just working on Microsoft Edge browser and only on the latest desktop version of it not the mobile version as well. It is not working on Google Chrome (either desktop or mobile) which is the standard browser for PWAs and has a vast number of users. If the application doesn't behave accurately on Chrome then we can loose interest of most of the users.
I think there maybe some tags which are missing but I couldn't found them. I have also tried to add cache tags but they also not worked.

**Comment by mkArtakMSFT** [comment] 2022-01-03 17:44
Thanks @ut786.
We'll take a closer look at this as part of the work of updating the integrity check failures investigation docs.

**Comment by ut786** [comment] 2022-01-04 07:33
@mkArtakMSFT Thanks for adding it to the milestone. I am looking forward to it.
But currently what solution should I propose to my client?

**Comment by mkArtakMSFT** [comment] 2022-10-11 17:17
@ut786 is this still an issue for you or did you get to some resolution here?

**Comment by ut786** [comment] 2022-10-11 18:28
@mkArtakMSFT I somehow fixed the issue last time and it didn't reproduced on my other application. So I cannot say anything confidently here.

**Comment by MackinnonBuck** [comment] 2023-12-05 00:36
Closing this out since it's not clear that there's a framework problem here. A new issue can be opened if the problem arises again.

**Closed by MackinnonBuck** 2023-12-05 00:36 UTC
Labels: investigate, area-blazor, Needs: Attention :wave:, feature-integrity-check
