### ISSUE TITLE
[Blazor] No Razor editor support

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#19262] opened 2020-02-22 13:29 UTC
I updated to the newest VS preview 16.5 preview 3.

When I create a new Blazor WASM app I do not get any editor support for Razor. The editor shows razor code as if it were plain text - although it compiles and runs just fine.

**Comment by AceTheWiz** [comment] 2020-02-23 12:37
I was experiencing the same issue, so I repaired the VS installation but even then there was no razor syntax highlighting. I then closed the all razor files and re-opened them. then it was working again ???.

**Comment by mrpmorris** [comment] 2020-02-23 12:40
Open/close didn't work for me. Uninstall / reinstall didn't work either.

**Comment by AceTheWiz** [comment] 2020-02-23 17:57
> Open/close didn't work for me. Uninstall / reinstall didn't work either.
I can't say I'm an expert here but have you installed the latest Blazor templates. ?
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1

**Comment by javiercn** [comment] 2020-02-24 09:56
@mrpmorris thanks for contacting us.

@NTaylorMullen can you look into this?

**Comment by mkArtakMSFT** [comment] 2020-02-24 17:29
@NTaylorMullen did our "preview LSP" kicked in here?

**Comment by NTaylorMullen** [comment] 2020-02-24 18:21
> @NTaylorMullen did our "preview LSP" kicked in here?

Nope, impossible. Haven't inserted that into Visual Studio yet.

@mrpmorris & @AceTheWiz if you repair Visual Studio do you still see the issue? Also, do you happen to have the `ASP.NET and web development workload checked?`
![image](https://user-images.githubusercontent.com/2008729/75179672-721e9200-56ef-11ea-80a6-5e12054e3518.png)

**Comment by AceTheWiz** [comment] 2020-03-01 19:13
No to the first question and yes to the second.
I am running Microsoft Visual Studio Community 2019 Preview

I had the issue just after I installed Version 16.5.0 Preview 3.0. Re-installing didn't fix the issue.  I then closed the all razor files and re-opened them. Then it was working again ???.

**Now it's back** after installing Version 16.5.0 Preview 4.0 and my previous fix is not helping.

I get this error when starting VS.
![image](https://user-images.githubusercontent.com/11596641/75632060-05305e00-5c01-11ea-9475-0d8d2daf27a3.png)

The ActivityLog has the foll errors:

270 | ERROR | Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.Windows.Simulator.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.          c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\commonextensions\platform\diagnosticshub\Microsoft.DiagnosticsHub.VisualStudio.Package.dll |   |   | Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost | 2020/03/01 19:00:34.032
-- | -- | -- | -- | -- | -- | --
502 | ERROR | SetSite failed for package [Microsoft.VisualStudio.Editor.Implementation.EditorPackage]Source: 'mscorlib' Description: Value was either too large or too small for an Int32. System.OverflowException: Value was either too large or too small for an Int32.   at System.Convert.ToInt32(UInt32 value)   at System.UInt32.System.IConvertible.ToInt32(IFormatProvider provider)   at System.Convert.ToInt32(Object value, IFormatProvider provider)   at Microsoft.VisualStudio.Editor.Implementation.EditorPackage.SetGlobalOptions(SettingsScope scope)   at Microsoft.VisualStudio.Editor.Implementation.EditorPackage.<InitializeAsync>d__32.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass100_1.<InternalGetResult>b__1()   at Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass100_0.<InternalGetResult>b__0()   at Microsoft.VisualStudio.Services.VsTask.<>c__DisplayClass108_0.<InvokeWithWaitDialog>b__0()   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog(Action action)   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)   at Microsoft.VisualStudio.Services.VsTask.GetResult() | {E269B994-EF71-4CE0-8BCD-581C217372E8} | 80131516 | VisualStudio | 2020/03/01 19:00:36.664
503 | ERROR | End package load [Microsoft.VisualStudio.Editor.Implementation.EditorPackage] | {E269B994-EF71-4CE0-8BCD-581C217372E8} | 80131516 | VisualStudio | 2020/03/01 19:00:36.695

**Comment by NTaylorMullen** [comment] 2020-03-01 21:05
Hmm, super odd @AmadeusW would you be the right person to reach out to here or someone else on the CoreEditor team? I ask because this package load failure looks very suspicious and I'm not quite sure where to go from here.

**Comment by AceTheWiz** [comment] 2020-03-02 19:53
Update: Did a Repair and then things were working again. The only other change, was to disable a 3rd party extension (not sure if it had any effect). 
Hold thumbs, I'm going to update to Preview 5.

**Comment by NTaylorMullen** [comment] 2020-03-02 23:44
Awesome, thanks for the follow up @AceTheWiz. Closing this out for now.

**Closed by NTaylorMullen** 2020-03-02 23:44 UTC
Labels: Needs: Author Feedback, area-blazor, investigate

**Comment by mrpmorris** [comment] 2020-03-03 11:09
This is working in 16.5.0 @javiercn

**Comment by AceTheWiz** [comment] 2020-03-03 18:21
Yes. also working in 16.5.0 Preview 5.0
Thanks for you time guys.

**Comment by AmadeusW** [comment] 2020-03-03 19:35
Editor team has introduced this regression. It is resolved by repairing VS, which is what @AceTheWiz did. The fix is available in 16.5 Preview 5
