### ISSUE TITLE
Excessive memory usage using endpoint.MapControllerRoute (up to 4GB) for Routes Candidates

### ISSUE THREAD

**Issue by Sbaia** [dotnet/aspnetcore#30092] opened 2021-02-11 12:17 UTC
### Describe the bug

Using the MapControllerRoute function with various route templates the server memory explodes in the order of GB.
A project with about 1K of Controllers and each with 30/40 Actions, with a dozen MapControllerRoute endpoints can weight up to 3GB.

We are not using the RouteAttribute decorations, but attributing the routes with MapControllerRoute, for a precise choice and for compatibility with NET.

```
app.UseEndpoint(endpoint => {
	endpoint.MapControllerRoute({
		name: "RouteName",
		pattern: "api/{controller}/{action}",
	});
	...
	endpoint.MapControllerRoute({
		name: "RouteName",
		pattern: "api/{controller}/{id}/{action}",
	})
	..
});
```

The memory is almost completely occupied by the Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata class and the internal routing dictionaries.

If, instead of with the UseEndpoint, the same identical routes are linked with UseMvc, there is not problems, and the application has a normal use of RAM (<500MB in Debug, 150MB in Release)

```
// this works without leak
app.UseMvc(route => {
	route.MapRoute(
                name: name,
                template: routeTemplate,
                defaults: defaults,
                constraints: constraints);
});
```

### To Reproduce

To replicate the problem I created a test project, with 1k controller with 30 actions, and I defined a series of Route patterns, and the RAM usage is also excessive, reaching 3GB.

[https://github.com/Sbaia/WebApp.Core.MemoryUsage](https://github.com/Sbaia/WebApp.Core.MemoryUsage)

### Exceptions (if any)

No Exceptions was thrown

### Further technical details
- ASP.NET Core 5 (tested also on 3.1, with same results)
- Visual Studio 2019
- Include the output of `dotnet --info`

```

dotnet --info
.NET SDK (che rispecchia un qualsiasi file global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by NinjaCross** [comment] 2021-02-12 11:46
I have this problem too, and the performances are terrible due to the absurd memory pressure / allocation :(

**Comment by davidfowl** [comment] 2021-03-08 07:35
@NinjaCross how many controllers do you have?

**Comment by NinjaCross** [comment] 2021-03-09 23:48
> @NinjaCross how many controllers do you have?

I have between 200 and 800 statically/dinamically compiled controllers.
The more controllers I have, the heaviest the memory consumption is.

**Comment by NinjaCross** [comment] 2021-03-11 07:32
First of all, thankyou for your answer :)

> In short, routing uses a DFA that avoids backtracking by trading off memory for compute time (it "precomputes" all possible destinations ahead of time).

That's indeed a great feature, but IMHO the developer should be able to decide **if** and **when** to apply or _modulate_ this "precomputation".
There are many factors to consider when balancing the resources (CPU and RAM) allocation in an application, and the fact that a single component of the system decide how to _balance_ itself in an _opaque/untunable_ way is a bit offsetting.

> There are strategies to reduce the amount of nodes in the tree, but we believe in general this is not a problem for the majority of apps. Apps with these many routes are not common, and even in these cases the advantage of running matching in linear time is normally worth the memory trade-off.

I appreciate your technical analysis, and I see your general point... but I also think there is a flaw in this last sentence.
Maybe it's just a misunderstanding from my side.
If it is so, please accept my apologies in advance :)

I agree that big applications are not as common as small/average ones, but with this statement you are implicitly saying that it's **ok** to build small applications using ASP.NET CORE MVC, and it's **not ok** to use it for big applications.
It's an invitation to (average/big) companies (usually creating big products) to move away from ASP.NET CORE MVC and transition to other technologies (... and that's exactly what my customers are asking me to do right now due to this unsolvable problem).
I feel this is a very dangerous statement, and accepting it could cause an unwanted precedence.

**Comment by davidfowl** [comment] 2021-03-11 08:01
There's big and there's big. This is huge. When we say things like "we believe in general this is not a problem for the majority of apps", it's because we haven't seen this complaint before. It doesn't mean that we don't care but it certainly lowers the priority of the issue for us.

**Comment by sstraus** [comment] 2021-03-11 08:15
@davidfowl Probably many others had the same problem, especially when porting big old Net Framework applications, and decide to quit instead of discussing it here. So Net Core is just for simple and small applications? I dont think so, but your answer is pointing to a different direction...

**Comment by davidfowl** [comment] 2021-03-11 08:19
If many people are having this issue they should absolutely file bugs. That's how we know the issue is affecting customers... We can't guess as to which issues people give up on, we make a judgement call based on how loud people are and how bad we think the issue is. 

I just ran the project and its a really bad experience so I'm hoping we can at least look into it more to understand how feasible it is to shrink some of the data structures. That said, we don't have a good sense (at least I don't) of the types of applications that have thousands of controllers loaded at the same time. I'd love to understand how common this is in enterprise applications, we don't have any data on this other than what people share.

**Comment by NinjaCross** [comment] 2021-03-11 08:51
> but it certainly lowers the priority of the issue for us.

I only _partially_ see your point.

I would like to stress on a (IMHO) 2 very significant aspects:

1. As a professional developer, my priorities are money-driven.
I don't develop software only for pleasure: I do it because **I'm payed to do it**.
If the technology doesn't support the needs of my customer's projects, I'll simply use another technology that doesn't do assumptions on what is important based on the fact that it's rare.
Even a rare problem can be show-stopper.
This is exactly the case.

2. Of course big/huge project are rare, that's how statistics works :)
Nonetheless, they exists, and since they are big, they tipically involve tens or hundreds of people (developers, analysts, testers, and so on).
Just because it's rare, doesn't mean it's not statistically relevant.
In a money-driven world, the **number of the projects** impacted by the problem is meaningless on itself.
To know if a problem has priority, you should count the **total number of people involved into the project**, not the **number of the projects** impacted by the problem.
I know it's not possible from your POV, but I think you get the meaning of what I'm saying.

Please, don't see this as just a "rambling"... here we are debating the future usage of this technology of many (even huge, as you defined them) projects.

> That said, we don't have a good sense (at least I don't) of the types of applications that have thousands of controllers loaded at the same time. I'd love to understand how common this is in enterprise applications, we don't have any data on this other than what people share.

Applications in the following categories contains *hundreds or thousands* of different database entities, which are exposed through APIs.
- ERP
- CRM
- Engineering calculation apps and 3D modeling (CADs and so on) apps
- Medical treatment
- Banking management
- ... and so on

In my experience, an average CRM contains at least 200-400 tables.
An average ERP contains at least 300-600 tables
Banking management applications contains **many thousands** tables (I've seen systems with **tens of thousands** of tables).

Dynamic-generation of  data models and APIs is also a very real, very frequent scenario in bug systems that needs for flexibility and extensibility.
As you can imagine, the situation goes haywire if your system allows to "extend" native entities structures through plugins, and those "extended models" are exposed too using dynamically generated APIs.

I strongly hope the situation will be patched ASAP.

**Comment by javiercn** [comment] 2021-03-11 15:13
> That's indeed a great feature, but IMHO the developer should be able to decide **if** and **when** to apply or _modulate_ this "precomputation".
> There are many factors to consider when balancing the resources (CPU and RAM) allocation in an application, and the fact that a single component of the system decide how to _balance_ itself in an _opaque/untunable_ way is a bit offsetting.

We take these things into account, and there are ways to "modulate" it. It just isn't a problem until you enter the realm of "very large" applications. To give you an idea of the sheer size of the sample app provided, it's about 10x bigger than the routing space for all Azure APIs combined (which are distributed across many services). We've validated this approach with many large applications including CMSs like Orchard and many products at Microsoft without this being a problem.

> I agree that big applications are not as common as small/average ones, but with this statement you are implicitly saying that it's **ok** to build small applications using ASP.NET CORE MVC, and it's **not ok** to use it for big applications.
> It's an invitation to (average/big) companies (usually creating big products) to move away from ASP.NET CORE MVC and transition to other technologies (... and that's exactly what my customers are asking me to do right now due to this unsolvable problem).
> I feel this is a very dangerous statement, and accepting it could cause an unwanted precedence.

The problem here is "expectations", you can totally use ASP.NET Core to build internet facing hyper-scale applications, but when you reach a certain scale, you should expect that the default patterns the system use might not work for you and that you might need to reach for other tools on the toolbelt or get a deeper understanding of how the system works to ensure you optimize for it.

For an application hosting 40K endpoints we believe it's perfectly valid to allocate a couple hundred megabytes upfront to handle routing to all those endpoints.
If you want more control, you can use things like `MapDynamicControllerRoute` which allows you define how a given route matches to a controller/action without creating individual endpoints for each action.

**Comment by NinjaCross** [comment] 2021-03-11 16:21
> We take these things into account, and there are ways to "modulate" it.

Very interesting !
Could you please provide some hints about how to "modulate" this behaviour ?

> It just isn't a problem until you enter the realm of "very large" applications. To give you an idea of the sheer size of the sample app provided, it's about 10x bigger than the routing space for all Azure APIs combined (which are distributed across many services). We've validated this approach with many large applications including CMSs like Orchard and many products at Microsoft without this being a problem.

I'm absolutely sure you did everything you could to satisfy the majority of common scenarios :)
Anyway, I'm also not sure this is a valid comparison.

The size of an API surface is strongly related to the specific functionalities implemented by the application.
In our specific case, the routes are thousands because we allow our customers to dynamically define strongly-typed data entities, and expose them with strongly-typed, dynamically generated WebApi controllers.

This is just one case, anyway.
As I said, there are other scenarios having thousands of statically-typed entities, having their own controllers.

> The problem here is "expectations"

You are right, expectations are everything :)
I need to be able to decide on my own which is the correct trade-off for my application.
So, my expectation for this specific problem is just to be able to "tune" (or, worst case scenario, disable) the "precomputation" mechanisms mentioned by @davidfowl 
I would be totally satisfited if I could trade memory for speed, and slightly reduce the performances in order to significantly decrease the memory allocation.
User's time is important (indeed !), but is also free (from my POV, of course). 
RAM, on the other hand, is not (especially in cloud-based environments) :)
 
> For an application hosting 40K endpoints we believe it's perfectly valid to allocate a couple hundred megabytes upfront to handle routing to all those endpoints.

Maybe you misread.
@Sbaia is talking about (3) gigabytes, not a couple hundred megabytes.
My scenario is very similar to his.

> If you want more control, you can use things like `MapDynamicControllerRoute` which allows you define how a given route matches to a controller/action without creating individual endpoints for each action.

I will give that a spin, thanks for the suggestion !

**Comment by javiercn** [comment] 2021-03-11 16:23
> 1. As a professional developer, my priorities are money-driven.
>    I don't develop software only for pleasure: I do it because **I'm payed to do it**.
>    If the technology doesn't support the needs of my customer's projects, I'll simply use another technology that doesn't do assumptions on what is important based on the fact that it's rare.
>    Even a rare problem can be show-stopper.
>    This is exactly the case.

I agree, however I don't think the sample you are providing is using the right routing configuration/options for an app this size.
* It's incredibly hard to evaluate how representative of a real application a synthetic example like the one provided is.
* There are other options/configuration that offer different trade-offs and that you can leverage.

At a given point in app size you need to have some understanding of the inner workings of the primitives you use and their performance characteristics. The same way you know what sorting algorithms you can use based on the set size or the collection you should use based on the operations you need to perform, you need to understand how routing works and what options are available to you.

> 2\. Of course big/huge project are rare, that's how statistics works :)
>     Nonetheless, they exists, and since they are big, they typically involve tens or hundreds of people (developers, analysts, testers, and so on).
>     Just because it's rare, doesn't mean it's not statistically relevant.
>     In a money-driven world, the **number of the projects** impacted by the problem is meaningless on itself.
>     To know if a problem has priority, you should count the **total number of people involved into the project**, not the **number of the projects** impacted by the problem.
>     I know it's not possible from your POV, but I think you get the meaning of what I'm saying.

We do care about these types of projects and we offer options and flexibility on how you configure routing to scale as much as you need to, however, there are different tools for different app sizes and different approaches you can take within routing that have different trade-offs.

Our default approach is a static route table which in our opinion offers the best trade-off for the majority of applications between consumed memory and CPU time, but we provide multiple options and extensibility points that allow you to control how the routing process works.

> Applications in the following categories contains _hundreds or thousands_ of different database entities, which are exposed through APIs.
> 
> * ERP
> * CRM
> * Engineering calculation apps and 3D modeling (CADs and so on) apps
> * Medical treatment
> * Banking management
> * ... and so on
> 
> In my experience, an average CRM contains at least 200-400 tables.
> An average ERP contains at least 300-600 tables
> Banking management applications contains **many thousands** tables (I've seen systems with **tens of thousands** of tables).

Sure, however I believe the common practice is to break such large applications into multiple services and perform multiple levels of routing instead of hosting everything in the same process. You can't expect the same approach you follow for an app with 40 endpoints to work for an app with 40000; the scale matters. That said, it doesn't mean there are no alternative approaches for those situations.

I also believe that with the correct routing configuration, it's not problematic to handle 300-600 tables. After all, with the sample you provided with attribute routing enabled, the 40K endpoints take less than 1GB memory which is one order of magnitude above what 300-600 tables would represent in terms of number of endpoints.

**Comment by NinjaCross** [comment] 2021-03-11 16:29
> I also believe that with the correct routing configuration, it's not problematic to handle 300-600 tables.

I will try with MapDynamicControllerRoute as you suggested, thankyou.

**Comment by javiercn** [comment] 2021-03-11 16:35
@NinjaCross I totally got people mixed up on the thread, sorry about the confusion.

The original sample that @Sbaia provided offers different configurations it can run on.

> > We take these things into account, and there are ways to "modulate" it.
> 
> Very interesting !
> Could you please provide some hints about how to "modulate" this behaviour ?

MapDynamicControllerRoute is the approach in these cases
 
> > It just isn't a problem until you enter the realm of "very large" applications. To give you an idea of the sheer size of the sample app provided, it's about 10x bigger than the routing space for all Azure APIs combined (which are distributed across many services). We've validated this approach with many large applications including CMSs like Orchard and many products at Microsoft without this being a problem.
> 
> I'm absolutely sure you did everything you could to satisfy the majority of common scenarios :)
> Anyway, I'm also not sure this is a valid comparison.

It was meant to point out that we've researched this space and that our defaults are optimized for the majority of apps out there, but that we do offer other options for when the common approach is not enough.

> The size of an API surface is strongly related to the specific functionalities implemented by the application.
> In our specific case, the routes are thousands because we allow our customers to dynamically define strongly-typed data entities, and expose them with strongly-typed, dynamically generated WebApi controllers.
> 
> This is just one case, anyway.
> As I said, there are other scenarios having thousands of statically-typed entities, having their own controllers.

This is exactly the type of scenario dynamic endpoints are for.

> > The problem here is "expectations"
> 
> You are right, expectations are everything :)
> I need to be able to decide on my own which is the correct trade-off for my application.
> So, my expectation for this specific problem is just to be able to "tune" (or, worst case scenario, disable) the "precomputation" mechanisms mentioned by @davidfowl
> I would be totally satisfited if I could trade memory for speed, and slightly reduce the performances in order to significantly decrease the memory allocation.
> User's time is important (indeed !), but is also free (from my POV, of course).
> RAM, on the other hand, is not (especially in cloud-based environments) :)

I agree, and if you run into trouble with the suggestion we provided, let us know and we can help, it's important for us that these types of scenarios are possible within our routing system.

> > For an application hosting 40K endpoints we believe it's perfectly valid to allocate a couple hundred megabytes upfront to handle routing to all those endpoints.
> 
> Maybe you misread.
> @Sbaia is talking about (3) gigabytes, not a couple hundred megabytes.

Yeah I got things a bit mixed up, however the sample had different configurations and the one using 3GB is not something we recommend in this situation.

> My scenario is very similar to his.
> 
> > If you want more control, you can use things like `MapDynamicControllerRoute` which allows you define how a given route matches to a controller/action without creating individual endpoints for each action.
> 
> I will give that a spin, thanks for the suggestion !

I hope this suggestion help you, and if not, please file a separate issue and we can help. 

When in doubt, file a separate issue and additionally mention an existing/similar issue. That way it helps us avoid confusions.

**Comment by davidfowl** [comment] 2021-03-11 16:43
We're here to help. We should also improve the docs and warn about this API for an *extra* large number of routes.

**Comment by droyad** [comment] 2021-06-18 00:02
We have just run into this as well. Some info from our internal investigation:

We are about 25% through our conversion to ASP.NET Core (from NancyFX) and we found a ratio of 240:1 "anti-match" route to defined route. Memory usage is currently at 350MB for the routing, so end result would be 1.4GB.

A rough test we've done shows that removing all the Regex constraints drops the size of this DFA tree by ~72%.

**Comment by mkArtakMSFT** [comment] 2021-08-12 18:13
This is now fixed and will be released as part of the upcoming .NET 6 RC1 release.

**Closed by mkArtakMSFT** 2021-08-12 18:13 UTC
Labels: investigate, Docs, area-mvc, feature-routing
