### ISSUE TITLE
Blazor WASM project - incorrect rendering of currency symbol in en-gb

### ISSUE THREAD

**Issue by MattE-S** [dotnet/aspnetcore#35651] opened 2021-08-24 11:10 UTC
In Blazor WASM, when rendering decimal value with [ToString](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.tostring?view=net-5.0#System_Decimal_ToString_System_String_System_IFormatProvider_) the returned string uses "GBP" as the [NumberFormat.CurrencySymbol](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.currencysymbol?view=net-5.0).  The .Net 5 server uses "£".  When the Culture Info uses "en-us", "$" is used on both client and server.

WASM project, DI:
```
public static async Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    builder.Services.AddSingleton(_=> System.Globalization.CultureInfo.GetCultureInfo("en-gb"));
}

```
Server .Net 5 API DI:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(_ => System.Globalization.CultureInfo.GetCultureInfo("en-gb"));
}
```
Shared assembly consumer:
```
public class Consumer
{
    private readonly CultureInfo MyCultureInfo;
    public Consumer(CultureInfo cultureInfo) => MyCultureInfo = cultureInfo;

    public string ConsumingMethod(decimal value) => value.ToString("C", MyCultureInfo); // en-gb returns "GBP{value}" here in WASM.
}
```
When `Consumer.ConsumingMethod(0m)` is called on the client with, the result is "GBP0.00", when called on the server the result is "£0.00".  In the WASM project, `MyCultureInfo.NumberFormat.CurrencySymbol` is "$" in en-us,  "€" in fr-fr and "GBP" in en-gb.

**Comment by pranavkm** [comment] 2021-08-24 16:37
Thanks for your issue report @MattE-S. This sounds like a dupe of https://github.com/dotnet/runtime/issues/45262. We'll use the other issue to track addressing this.

**Closed by pranavkm** 2021-08-24 16:37 UTC
Labels: area-blazor, blazor-wasm
