### ISSUE TITLE
Visual Studio very slow and crashes frequently for large blazor project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22586] opened 2020-06-05 17:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1063967/visual-studio-very-slow-and-crashes-frequently-for.html)._

---
<p>Visual Studio very slow and crashes frequently for large blazor project. This crash happened during debugging with multiple projects. I have crashes frequently when just working in razor files</p>

---
#### Visual Studio Feedback System on 6/3/2020, 07:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2020-06-08 22:06
Duplicate of: https://github.com/dotnet/aspnetcore/issues/22276

**Closed by NTaylorMullen** 2020-06-08 22:06 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, area-razor.tooling
