### ISSUE TITLE
Support for .NET Standard 2.0 IN  Microsoft.AspNetCore.Identity.EntityFrameworkCore

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [dotnet/aspnetcore#18339] opened 2020-01-14 18:37 UTC
The only dependencies are NET Standard 2.0 compatible libraries:
Microsoft.Extensions.Identity.Stores 
Microsoft.EntityFrameworkCore.Relational

--

Also, from an interoperability standpoint, Microsoft.EntityFrameworkCore added support back for .NET Standard 2.0 in 3.1.

**Comment by blowdart** [comment] 2020-01-14 18:40
Closing as dupe of https://github.com/dotnet/aspnetcore/issues/17932

**Closed by blowdart** 2020-01-14 18:40 UTC
