### ISSUE TITLE
Add Forwarded header to known headers

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/aspnetcore#24788] opened 2020-08-11 12:18 UTC
[RFC 7239 - Forwarded HTTP Extension](https://tools.ietf.org/html/rfc7239)

> The "Forwarded" HTTP header field is an OPTIONAL header field that,
   when used, contains a list of parameter-identifier pairs that
   disclose information that is altered or lost when a proxy is involved
   in the path of the request.

**Comment by Tratcher** [comment] 2020-08-11 12:25
Probably not until we have an implementation in the repo that uses it.

**Comment by BrennanConroy** [comment] 2020-08-12 20:08
Dupe of https://github.com/dotnet/aspnetcore/issues/5978

**Closed** 2020-08-14 15:48 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers
