### ISSUE TITLE
CSS Isolation not works for Img elements

### ISSUE THREAD

**Issue by miladahmadi33** [dotnet/aspnetcore#38376] opened 2021-11-14 17:07 UTC
### Describe the bug
When I use CSS Isolation and I set id for img element, then I write css style for img element in index.cshtml.css,  the css styles not works for the img element and styles not effect on the img element

### Further technical details
- ASP.NET Core version: 6.0.100
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual studio 2022 17.0.0

**Comment by javiercn** [comment] 2021-11-15 11:45
@miladahmadi33 thanks for contacting us.

We believe this is a dupe of https://github.com/dotnet/aspnetcore/issues/38377

**Closed by javiercn** 2021-11-15 11:45 UTC
Labels: area-blazor, feature-css-isolation
