### ISSUE TITLE
asp-route-page does not generate the url as I want

### ISSUE THREAD

**Issue by daping123** [dotnet/aspnetcore#25529] opened 2020-09-02 08:24 UTC
### Describe the bug
I have a HttpGet route template.It has route parameter and query string parameter.I create a link by using `asp-route-data` tag helper.It could generate as what i want before.But when I add `endponits.MapRazorPages`.All the parameter will generate to query string.

What I want:`symbols/aaa/sss/news?page=4&perpage=10`

It generates:`symbols/news?symbol=aaa&slug=sss&page=4&perpage=10`

After a long time researching,I find that I could use any tag helper like `asp-route-xxpage` but can't use `asp-route-page`.It seems to be a bug in razor pages.

### To Reproduce
View:

```
<a class="page-link"  asp-action="News"  asp-controller="Symbols"
        asp-route-symbol="aaa"  asp-route-slug="sss"  asp-route-page="4" asp-route-perPage="10">Test</a>
```
Controller:
```
 [HttpGet("symbols/{symbol}/{slug}/news")]
    public async Task<IActionResult> News(
        [FromRoute] string symbol,
        [FromRoute] string slug,
        [FromQuery] int perPage,
        [FromQuery] int page)
    {
        ...
    }
```
Startup.cs:
```
app.UseEndpoints(endpoints =>
{               
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
    endpoints.MapRazorPages();
});
```
### SO thread

https://stackoverflow.com/questions/63606603/asp-net-core-asp-route-helpers-not-rendering-link-correctly

**Comment by mkArtakMSFT** [comment] 2020-09-02 16:56
Thanks for contacting us. This is a dupe of #25299

**Closed by mkArtakMSFT** 2020-09-02 16:56 UTC
Labels: area-mvc, feature-routing
