### ISSUE TITLE
Eventlog error when hosting on iis with httpsys: The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID

### ISSUE THREAD

**Issue by guylando** [dotnet/aspnetcore#6648] opened 2019-01-13 16:08 UTC
Seeing in server event log "System" catalog errors originating from "DistributedCOM" source saying:
`
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user IIS APPPOOL\user SID (S-1-5-82-2959028982-2059026064-4278656777-697959589-1111111111) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
`
Windows Server 2016, Microsoft net core 2.1.5 hosting and runtime installed on server.
The app is hosted on HttpSys behind IIS 10, target net472. (runtime identifier win7-x64 if that makes a difference?)

Is there some additional step required to host on IIS to prevent this error? I am not aware of the consequences of this error. Seems that everything works. Still wondering how to clean the error.
I saw some people with similar problems modifying dcom permissions but I wonder if you know why this error happens and if that's what you recommend (modifying dcom permissions).
https://stackoverflow.com/questions/42233336/is-allowing-the-apppool-local-activation-permission-system-wide-in-dcomcnfg-a-bi
https://social.technet.microsoft.com/Forums/en-US/dfc465bc-7bbd-483e-b98b-2ba56fa98313/the-applicationspecific-permission-settings-do-not-grant-local-launch-permission-for-the-com-server?forum=configmgrgeneral
https://stackoverflow.com/questions/49208958/is-it-possible-to-resolve-a-dcom-interactive-user-permission-error-when-using-d

**Comment by anurse** [comment] 2019-04-11 00:20
Are you trying to call a COM object? This error seems unrelated to ASP.NET. Can you provide a sample that reproduces the issue?

**Comment by guylando** [comment] 2019-04-11 16:13
@anurse that COM CLSID belongs to C:\Windows\System32\RuntimeBroker.exe if that helps. I am not aware of using any COM object related to RuntimeBroker. I don't currently have a sample that reproduces the issue

**Comment by anurse** [comment] 2019-04-11 21:02
Is your application failing or is it just logging this to the event log without failing? Also, can you verify the process ID associated with the Event (it's in the Details tab of the Event Viewer view for the event item itself) is your `dotnet.exe` application?

I'm not aware of anything in ASP.NET Core that would trigger this kind of error, so I'm trying to track down what could be originating the COM call.

> that COM CLSID belongs to C:\Windows\System32\RuntimeBroker.exe if that helps

Apparently `RuntimeBroker` is used by Microsoft Store apps, which makes this even more strange.

**Comment by asp-entwickler** [comment] 2019-05-19 19:37
I have the same issue

![image](https://user-images.githubusercontent.com/19171449/57987173-3b3f8f80-7a7e-11e9-8a7b-74796b3f927d.png)

![image](https://user-images.githubusercontent.com/19171449/57987179-4c889c00-7a7e-11e9-8ae2-270fe5856664.png)

**Comment by anurse** [comment] 2019-06-11 00:11
It seems like these errors are completely unrelated to ASP.NET Core. The reference to the `IIS APPPOOL` identity indicates to me that something running under that user is trying to do something with DCOM but nothing in ASP.NET Core would be triggering it, so I'm moving this to our Discussions milestone for now.

Having said that, it looks like one option for getting more data is to search the registry for the CLSID and APPID guids you are getting in the error to see what component is being activated.

**Comment by guylando** [comment] 2019-06-11 14:47
@asp-entwickler check if your component is the same as I reported here: https://github.com/aspnet/AspNetCore/issues/6648#issuecomment-482180371 (RuntimeBroker)

**Closed** 2020-11-12 08:05 UTC
Labels: area-servers
