### ISSUE TITLE
Add Binary Logging to HttpLogging middleware

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31884] opened 2021-04-16 20:06 UTC
We want to extend the HttpLogging middleware to work with binary logging, using the same format that Kestrel does for connection logs.

**Comment by BrennanConroy** [comment] 2021-04-20 21:10
Dupe of https://github.com/dotnet/aspnetcore/issues/31849

**Closed by BrennanConroy** 2021-04-20 21:10 UTC
Labels: area-runtime
