### ISSUE TITLE
HttpLogger does not log RequestBody

### ISSUE THREAD

**Issue by johnkors** [dotnet/aspnetcore#49063] opened 2023-06-27 22:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

HttpLogging does not log the RequestBody when configured to do so.

### Expected Behavior

A log statement from HttpLogger with the actual body sent

### Steps To Reproduce

```csharp
using Microsoft.AspNetCore.HttpLogging;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddHttpLogging(c =>
{
  c.LoggingFields = HttpLoggingFields.RequestBody |
                    HttpLoggingFields.RequestPath |
                    HttpLoggingFields.ResponseBody;
});

var app = builder.Build();

app.UseHttpLogging();
app.MapPost("/", () => "Hello POST!");

app.Run();
```

### Exceptions (if any)

Any request having a body towards the POST endpoint at root results in a log statement that says the body is empty when it's not:

```
POST http://localhost:5145/ HTTP/1.1
User-Agent: vscode-restclient
Content-Type: text/plain
accept-encoding: gzip, deflate
content-length: 3

some text


HTTP/1.1 200 OK
Connection: close
Content-Type: text/plain; charset=utf-8
Date: Tue, 27 Jun 2023 22:13:05 GMT
Server: Kestrel
Transfer-Encoding: chunked

Hello POST!
```

```log
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5145/ text/plain 3
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:
      PathBase: 
      Path: /
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody:    👈 👈 
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[4]
      ResponseBody: Hello POST!
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5145/ text/plain 3 - 200 - text/plain;+charset=utf-8 0.4329ms
```

### .NET Version

7.0.203

### Anything else?

Microsoft.AspNetCore.App 7.0.5
VSCode / Rider

**Comment by johnkors** [comment] 2023-06-27 22:34
Swapping `app.UseHttpLogging()` for a simple middleware, the body is logged as expected:

```csharp
app.Use(async (context, next) =>
{
    var logger = context.RequestServices.GetService<ILogger<Program>>();
    context.Request.EnableBuffering();
    using var reader = new StreamReader(context.Request.Body, Encoding.UTF8);
    var body = await reader.ReadToEndAsync();
    context.Request.Body.Position = 0;
    logger?.LogWarning("body is {ReqBody}",body);
    await next();
});
```

```log
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5145/ text/plain 9
warn: Program[0]
      body is some text    👈  👈 
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5145/ text/plain 9 - 200 - text/plain;+charset=utf-8 2.8885ms
```

**Comment by adityamandaleeka** [comment] 2023-06-27 22:59
@johnkors This is by design. The logging middleware doesn't read the body on its own; rather, it logs when another component consumes the body. If you were to modify your `"Hello POST!"` to instead do `"Hello <something from the body>"`, you should see the request body appear in the logging.

The reason we do this is that consuming the request body on behalf of the application is not safe; the application code might be choosing intentionally to not read the body.

**Comment by adityamandaleeka** [comment] 2023-06-27 23:02
I think we should update our documentation to mention this.

**Comment by johnkors** [comment] 2023-06-27 23:05
Yeah, that's not clear at all :/  

I'm using this along with YARP to read proxied bodies, so then YARP needs to add something so it's possible to read proxied bodies?

**Comment by Tratcher** [comment] 2023-06-27 23:32
YARP is the component that will consume the body in this case. You shouldn't need a separate middleware.

**Comment by adityamandaleeka** [comment] 2023-06-28 00:01
Ah, I didn't know this discussion started over in the YARP repo, and GitHub didn't show the backlink since I wasn't authenticated to that repo (sigh...). But yes, @Tratcher is right.

**Comment by johnkors** [comment] 2023-06-28 05:00
Ok, so then it's a bug. I don't see the body when using the combo of HttpLogging+YARP without any extra effort (adding a middleware that reads the body).

**Comment by davidfowl** [comment] 2023-06-28 05:42
@johnkors can you show the full repro including yarp?

**Comment by johnkors** [comment] 2023-06-28 08:56
> @johnkors can you show the full repro including yarp?

https://github.com/johnkors/bodylogging

**Comment by Tratcher** [comment] 2023-06-28 20:57
I think this is a duplicate of https://github.com/dotnet/aspnetcore/issues/47216 which was fixed in 7.0.7 by https://github.com/dotnet/aspnetcore/pull/47811. Can you try updating?

**Comment by johnkors** [comment] 2023-06-29 08:42
I updated to 7.0.8, and then the HttpLogger logged proxied requests 🎉 .

 It's still unable to log the body for non-proxied requests though. :

```csharp
app.MapPost("/", () => "Hello Post!");
```

```
POST http://localhost:5145
Content-Type: text/plain

some text
```


```log
Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5145/ text/plain 9
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:
      
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: POST /'
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[3]
      RequestBody: 
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5145/ text/plain 9 - 200 - text/plain;+charset=utf-8 0.3127ms
```

But as I now understand:

> This is by design

**Comment by Tratcher** [comment] 2023-06-29 17:29
I recomend DrainAsync instead of StreamReader, it doesn't need to store or decode the data.
https://github.com/dotnet/aspnetcore/blob/1e86b6cd87163153337cbb5555fa727264eceb2e/src/Http/WebUtilities/src/StreamHelperExtensions.cs#L24

**Comment by adityamandaleeka** [comment] 2023-06-29 20:38
Glad this is solved for you @johnkors. Keeping the issue open to update docs to reflect the fact that something needs to consume the request body for it to be logged.

**Comment by Tratcher** [comment] 2023-06-29 20:42
We should change the log to indicate the full request body wasn't consumed. Self-documenting :->

**Comment by davidfowl** [comment] 2023-06-29 22:12
@johnkors IMO, you shouldn't worry about logging request bodies for requests that don't consume them. I could DOS your site by sending requests to random endpoints that don't exist forcing you to buffer the body (even with our buffering helpers that go to disk over a certain threshold).

**Comment by johnkors** [comment] 2023-06-30 17:14
Understood. This is acceptable for my scenario, though:

We moved an API to a different domain, and just want to log any old/dated usage as part of the migration, and return backwards compatible 400 responses to clients.

The stuff we proxy is not critical either, but done to ease the transition. All a temporary. 🤞

**Comment by johnkors** [comment] 2023-07-03 12:59
> I think this is a duplicate of #47216 which was fixed in 7.0.7 by #47811. Can you try updating?

I know this isn't your table - but Azure (on Linux at least) is still on 7.0.5, while there's a 7.0.7 security patch out since 2 weeks. Ah well. 

![snip xRsvtZPM](https://github.com/dotnet/aspnetcore/assets/206726/2a57a164-8133-4e63-bc03-c68cec191977)

**Comment by bradygaster** [comment] 2023-07-07 17:23
cc @btardif - Any potential you could look at this; if this logging is specific to the update, I presume it'll resolve when that update is pushed? @johnkors - have you tried (or could you? no pressure, if you can't do this no worries.) to do a self-contained publish using the latest bits?

**Comment by johnkors** [comment] 2023-07-07 17:26
Confirmed working on my machine ™️ on 7.0.8, and in a container (non-azure) using 7.0.8 image.

**Comment by danmoseley** [comment] 2023-07-07 18:11
cool -- we just wanted to check with @btardif whether there was an unexpected latency of some sort. Because we collaborate closely together around servicing points.

**Closed** 2023-09-01 15:55 UTC
Labels: Docs, area-middleware, net8_docathon
