### ISSUE TITLE
HeadContent with prerender=false doesn't work

### ISSUE THREAD

**Issue by ray440** [dotnet/aspnetcore#52368] opened 2023-11-25 21:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`<HeadContent>` is not included in `<HeadOutlet>` when prerender=false.

### Expected Behavior

`<HeadOutlet>` does not contain the proper content.

### Steps To Reproduce

Given a basic non-global, Auto rendered project, where Home.razor holds 

```
IComponentRenderMode rmode = new InteractiveServerRenderMode(prerender:false);

 :
<Counter @rendermode=@rmode />
```

and Counter.razor contains some HeadContent like:

```
<HeadContent>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Round" rel="stylesheet">
</HeadContent>
```

When, rendered, the HeadOutlet doesn't contain anything. 
Note this works if `prerender:true`.

### .NET Version

8.0.100

**Comment by mkArtakMSFT** [comment] 2023-11-27 17:33
While we wait for a repro, it may be because you haven't specified a `rendermode` for the `HeadContent` component. It should match the same rendermode, as the `HeadOutlet`.

**Comment by javiercn** [comment] 2023-12-15 13:11
@ray440 thanks for the additional details.

@mkArtakMSFT we might be able to detect when there is no head outlet for a given head content and potentially throw an exception at that point.

In this case, we can't do anything during prerendering because HeadContent doesn't even get rendered, and the only thing that gets rendered in interactive mode is HeadContent and not HeadOutlet. In that case, we might be able to detect the lack of a HeadContent and throw at that point.

**Comment by ray440** [comment] 2023-12-16 19:11
@javiercn Thanks for looking into this.
 
Yeah, this seems like a tricky issue.  In the meantime,  I'm using JS interop to achieve the same effect.

**Comment by mkArtakMSFT** [comment] 2024-01-17 18:29
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/51132

**Closed by mkArtakMSFT** 2024-01-17 18:29 UTC
Labels: enhancement, area-blazor, feature-blazor-sections, Pillar: Dev Experience
