### ISSUE TITLE
MissingMethodException IsComponentDisposed() after update to .NET 7.0.17

### ISSUE THREAD

**Issue by MichaelL79** [dotnet/aspnetcore#54614] opened 2024-03-19 08:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After the update to .NET 7.0.17 we are constantly having the unhandled exception **System.MissingMethodException: Method not found: 'Boolean Microsoft.AspNetCore.Components.ComponentBase.IsComponentDisposed()'** in our Blazor Serverside solution.

It is hard to tell when it occurs as it only happens on the production server which is Windows Server 2019. It seems to happen when a property of the model of an EditForm is changed but this is just a guess as we cannot reproduce it with all such scenarios.

A downgrade to .NET 7.0.16 did not resolve the issue so we went straigt back to .NET 7 which fixed it. Unfortunately we could not spend a lot of time to investigate the issue as the application is business crititcal an we had to resolve the issue as fast as possible.

### Exceptions (if any)

2024-03-19 08:50:59.1216 WARN 10.2.222.64 Unhandled exception rendering component: Method not found: 'Boolean Microsoft.AspNetCore.Components.ComponentBase.IsComponentDisposed()'. System.MissingMethodException: Method not found: 'Boolean Microsoft.AspNetCore.Components.ComponentBase.IsComponentDisposed()'.
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-19 08:50:59.1216 ERROR 10.2.222.64 Unhandled exception in circuit 'P2dziy8Hm18dvsCKuDguPDRV1QJphHMJZC3fnuXJxk4'. System.MissingMethodException: Method not found: 'Boolean Microsoft.AspNetCore.Components.ComponentBase.IsComponentDisposed()'.
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-03-19 08:50:59.1216 ERROR 10.2.222.64 Unhandled exception in circuit 'P2dziy8Hm18dvsCKuDguPDRV1QJphHMJZC3fnuXJxk4'. Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
   at BlazorInputFileExtended.InputFileExtended.UnLoadDropScriptsAsync()
   at BlazorInputFileExtended.InputFileExtended.Dispose()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

### .NET Version

7.0.17

**Comment by javiercn** [comment] 2024-03-19 10:51
@MichaelL79 thanks for contacting us.

This very likely points to an issue in one of your dependencies that hasn't been updated to 8.0 correctly. The method you are talking about is [internal](https://github.com/dotnet/aspnetcore/blob/release/7.0/src/Components/Components/src/ComponentBase.cs#L331)

**Comment by MichaelL79** [comment] 2024-03-22 16:53
Hi @javiercn, this could indeed be the case as we updated a paket a few weeks ago that already uses .NET8

**Comment by mkArtakMSFT** [comment] 2024-03-25 16:49
Closing as this seems to be a dependency mixup problem. Hopefully you will be able to find the cause and address it quickly.

**Closed by mkArtakMSFT** 2024-03-25 16:49 UTC
Labels: area-blazor, Needs: Attention :wave:
