### ISSUE TITLE
How are hub options configured in a Blazor Web App?

### ISSUE THREAD

**Issue by guardrex** [dotnet/aspnetcore#49710] opened 2023-07-28 15:43 UTC
In prior releases, hub options were configured for Blazor Server's hub as ...

```csharp
builder.Services.AddServerSideBlazor().AddHubOptions(options =>
{
    options.ClientTimeoutInterval = ...;
    options.EnableDetailedErrors = ...;
    options.HandshakeTimeout = ...;
    options.KeepAliveInterval = ...;
    options.MaximumParallelInvocationsPerClient = ...;
    options.MaximumReceiveMessageSize = ...;
    options.StreamBufferCapacity = ...;
});
```

How are hub options configured for a BWA with SSR/server interactivity?

```csharp
builder.Services.AddRazorComponents().AddServerComponents()

... ??? ...

.AddHubOptions(...);
```

**Comment by javiercn** [comment] 2023-07-28 18:28
https://github.com/dotnet/aspnetcore/pull/49712

**Comment by javiercn** [comment] 2023-07-28 18:30
Dupe of https://github.com/dotnet/aspnetcore/issues/49300

**Closed by javiercn** 2023-07-28 18:30 UTC
Labels: area-blazor, design-proposal
