### ISSUE TITLE
Blazor WASM Hot Reload cli not working

### ISSUE THREAD

**Issue by chhinsras** [dotnet/aspnetcore#38561] opened 2021-11-22 01:40 UTC
I have blazor hosted. I run dotnet watch inside server project. Only hot reload works for sever project not the client project.

I try to run dotnet watch inside project. It has hot reload on client project when I change file, and of course there is no server running. 

@chhinsras Can you file a new issue specifically about your Blazor WASM + hot reload problem?

_Originally posted by @captainsafia in https://github.com/dotnet/aspnetcore/issues/38103#issuecomment-974920846_

**Comment by mkArtakMSFT** [comment] 2021-11-22 17:59
Thanks for contacting us. Can you please share more context about the scenario in this issue so that everyone who will be reading this won't need to go to the linked issue and get  the details from there?

**Comment by chhinsras** [comment] 2021-11-24 09:22
I have blazor hosted. I run dotnet watch inside server project. Only hot reload works for sever project not the client project.

I try to run dotnet watch inside project. It has hot reload on client project when I change file, and of course there is no server running.

**Comment by SteveSandersonMS** [comment] 2021-11-25 15:49
@pranavkm Does `watch` handle ASP.NET Core-hosted WebAssembly projects?

**Comment by pranavkm** [comment] 2021-11-25 18:42
It does. There is a (concurrency) issue with watch where it'll [sometimes timeout and get incorrect hot reload capabilities for a Blazor WASM app](https://github.com/dotnet/aspnetcore/issues/36723), but in general, it should work.

**Comment by ziaulhasanhamim** [comment] 2021-11-26 02:47
@pranavkm generally it doesn't work. once in a while it works.

**Comment by mkArtakMSFT** [comment] 2021-11-29 17:53
@pranavkm is this a dupe then of the linked issue?

**Comment by chhinsras** [comment] 2021-12-01 05:07
hahah. .NET 7. Why not addressing in upcoming patch

**Comment by ziaulhasanhamim** [comment] 2021-12-01 12:03
1 year of waiting for these kinda bugs is hilarious

**Comment by Aquaritek** [comment] 2021-12-04 05:00
> Thanks for contacting us.
> 
> We're moving this issue to the `.NET 7 Planning` milestone for future evaluation / consideration. We would like to keep this around to collect more feedback, which can help us with prioritizing this work. We will re-evaluate this issue, during our next planning meeting(s). If we later determine, that the issue has no community involvement, or it's very rare and low-impact issue, we will close it - so that the team can focus on more important and high impact issues. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md).

And I'll raise another flag here too referring to the first thread I posted in about this same issue. I'm fairly certain there are 3 threads on this now. https://github.com/dotnet/aspnetcore/issues/38809#issuecomment-985967854

**Comment by chhinsras** [comment] 2021-12-04 12:29
@Aquaritek I have been working with C# since 2015 and with Asp.Net since 2019. I really love them.

I started to adapt Blazor in 2020. I most of the time use VS code for development which I am on Mac. I started the company project with Asp.Net and Blazor early this year. Really struggling with development experienece and no reason bugs. Been almost a year, finally, It is hard but I have to move away from Blazor right now with the current development expereience. 

Hope to be back in upcoming .NET7 with ready and user-friendly development expereience. 


What I like using now is Asp.Net and Angular stacks. MAUI is interesting but I hesitate to compare with Flutter.

My suggestion, VS code should be priorized as well since it is Microsoft open source project, yet, the Flutter development on VS code is far-far better than MAUI or Blazor.

**Comment by ziaulhasanhamim** [comment] 2021-12-04 14:05
@chhinsras I agree. CLI and vs code should be the absolute first choice for .net development. the .net platform should be CLI first for ultimate cross-platform development solution like any other platform such as js, node, go, flutter, python, etc. these all have great ide support. But they prioritize CLI most

**Comment by chhinsras** [comment] 2021-12-04 16:00
> @chhinsras I agree. CLI and vs code should be the absolute first choice for .net development. the .net platform should be CLI first for ultimate cross-platform development solution like any other platform such as js, node, go, flutter, python, etc. these all have great ide support. But they prioritize CLI most

I love .net but yeah, I am really struggling. it's shameful that VS Code support Flutter much much better than Blazor , MAUI

**Comment by ziaulhasanhamim** [comment] 2021-12-04 16:07
> I love .net but yeah, I am really struggling. it's shameful that VS Code support Flutter much much better than Blazor , MAUI

yeah even go, rust support in vs code is increasing day by day. But I can't see much improvements in vs code omnisharp for c# extension.

**Comment by chhinsras** [comment] 2021-12-04 16:39
> > I love .net but yeah, I am really struggling. it's shameful that VS Code support Flutter much much better than Blazor , MAUI
> 
> yeah even go, rust support in vs code is increasing day by day. But I can't see much improvements in vs code omnisharp for c# extension.

I do not understand either. VS IDE is good, but I love VS Code than. Now Hot Reload CLI is planned for .NET7 which is another year to go.

I just found another bug inside VS code for C# 10 with .NET6.

Using implicit namespace. you will see differnt color of property inside Class.

**Comment by ziaulhasanhamim** [comment] 2021-12-05 05:16
Yeah, there are quite some bugs. C# doesn't provide the ultimate coding experience with vs code like most other modern languages

**Comment by chhinsras** [comment] 2021-12-07 15:55
> Yeah, there are quite some bugs. C# doesn't provide the ultimate coding experience with vs code like most other modern languages

It's so frustrating sometime! I like flutter more on its dev experience

**Comment by pranavkm** [comment] 2022-01-07 17:57
@chhinsras do you happen to have a minimal app that reproduces the issue? I'm unable to reproduce the reported issue on a project created from the template.

**Comment by chhinsras** [comment] 2022-01-10 01:14
> @chhinsras do you happen to have a minimal app that reproduces the issue? I'm unable to reproduce the reported issue on a project created from the template.

Yes. Blazor WSAM hosted project.

**Comment by pranavkm** [comment] 2022-01-11 19:09
@chhinsras can you run watch with the `--verbose` switch, make a file change once the app is running and include the output?

**Comment by ziaulhasanhamim** [comment] 2022-01-12 02:37
@pranavkm i was facing the same issue.
```
watch : Project supports hot reload and was configured to run with the default run-command. Watching with hot-reload
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
watch : Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 11308
  Determining projects to restore...
  All projects are up-to-date for restore.
  BlazorWasm -> C:\Users\ziaul\BlazorWasm\bin\Debug\net6.0\BlazorWasm.dll
  BlazorWasm (Blazor output) -> C:\Users\ziaul\BlazorWasm\bin\Debug\net6.0\wwwroot
watch : Process id 11308 ran for 10074ms
watch : Running MSBuild target 'GenerateWatchList' on 'C:\Users\ziaul\BlazorWasm\BlazorWasm.csproj'
watch : Started 'C:\Program Files\dotnet\dotnet.exe' '' with process id 8312
watch : Process id 8312 ran for 1342ms
watch : Watching 28 file(s) for changes
watch : dotnet-watch is configured to launch a browser on ASP.NET Core application startup.
watch : Configuring the app to use browser-refresh middleware.
watch : Refresh server running at wss://localhost:60157,ws://localhost:60158.
watch : HotReloadProfile: BlazorWebAssembly.
watch : Waiting for a browser to connect
watch : Started 'dotnet' '"C:\Users\ziaul\.nuget\packages\microsoft.aspnetcore.components.webassembly.devserver\6.0.1\build\../tools/blazor-devserver.dll" --applicationpath "C:\Users\ziaul\BlazorWasm\bin\Debug\net6.0\BlazorWasm.dll"' with process id 12684
watch : Running dotnet with the following arguments: run
watch : Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7179
watch : Launching browser.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5013
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\ziaul\BlazorWasm
watch : Hot reload capabilities: .
watch : File changed: C:\Users\ziaul\BlazorWasm\Pages\Index.razor.
watch : No deltas modified. Applying changes to clear diagnostics.
watch : Received 1 from browser in [Count: 1, MessageType: Binary, EndOfMessage: True].
watch : No hot reload changes to apply.
watch : Hot reload change handled in 2993.5768ms.
```

**Comment by pranavkm** [comment] 2022-01-12 04:43
@ziaulhasanhamim thanks for the logs. The log indicates a dupe of https://github.com/dotnet/aspnetcore/issues/36723 which is being addressed in the the upcoming .NET 6.0 SDK / VS 17.1 release. You could try a nightly build of the SDK from: https://github.com/dotnet/installer#installers-and-binaries (use an installer from the Release/6.0.2XX column).

**Comment by ziaulhasanhamim** [comment] 2022-01-12 04:48
thanks for letting me know

**Closed** 2022-01-20 01:00 UTC
Labels: Needs: Author Feedback, area-commandlinetools, area-blazor, Status: No Recent Activity, feature-hot-reload

**Comment by szalapski** [comment] 2022-02-24 19:08
This seems not to be fixed in SDK 6.0.200.  I still get:

```
watch : File changed: C:\...\MyComponent.razor.
watch : No hot reload changes to apply.
```

Can anyone help?

**Comment by ziaulhasanhamim** [comment] 2022-02-25 03:22
Having the same problem with SDK 6.0.200
```
watch : Hot reload capabilities: .
```

**Comment by ziaulhasanhamim** [comment] 2022-02-27 10:00
@pranavkm
