### ISSUE TITLE
Route parameter with urlencoded slash. Inconsistency beetween TestServer and Kestrel behavior.

### ISSUE THREAD

**Issue by mcrio** [dotnet/aspnetcore#28965] opened 2021-01-01 10:45 UTC
### Describe the bug
Having a route parameter that includes a urlencoded `/` character produces inconsistent results between TestServer and Kestrel behavior.

Route: `/api/{itemId}`
Client requests: `/api/foo%2Fbar`

**Kestrel:** As expected matches the controller action.
**TestServer:** Produces a HTTP 404 Not Found.

### To Reproduce
https://github.com/mcrio/AspNet5TestServerSlashTest

### Further technical details

`net5.0`

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

**Comment by Tratcher** [comment] 2021-01-01 17:51
How did you test this with Kestrel? I think this is a case where the difference is caused by the client, not the server. E.g. System.Uri (used by HttpRequestMessage/HttpClient) has it's own escaping behaviors before the request is even submitted. If you used HttpClient to send the same request to Kestrel I think you'd get the same result.

**Comment by Tratcher** [comment] 2021-01-01 17:57
Actually, this logic may give different results from Kestrel:
https://github.com/dotnet/aspnetcore/blob/8a8b94a7be28cd861e50ae5fbbab5586e1df5cd7/src/Hosting/TestHost/src/ClientHandler.cs#L172
https://github.com/dotnet/aspnetcore/blob/8a8b94a7be28cd861e50ae5fbbab5586e1df5cd7/src/Http/Http.Abstractions/src/PathString.cs#L192

**Comment by mcrio** [comment] 2021-01-02 21:16
Hi @Tratcher  

I compared the behavior using a web browser in one instance and TestHost + HttpClient in another (provided sample project above).

You are right. The problem is with the client. The TestHost ClientHandler at 
https://github.com/dotnet/aspnetcore/blob/8a8b94a7be28cd861e50ae5fbbab5586e1df5cd7/src/Hosting/TestHost/src/ClientHandler.cs#L172
transforms the request path `/api/foo%2Fbar` to `api/foo/bar`.

Is this behavior expected? I wouldn't expect the client to alter the escaped request path.

**Comment by mcrio** [comment] 2021-01-02 23:14
The code @Tratcher pointed above

https://github.com/dotnet/aspnetcore/blob/8a8b94a7be28cd861e50ae5fbbab5586e1df5cd7/src/Http/Http.Abstractions/src/PathString.cs#L173
https://github.com/dotnet/aspnetcore/blob/8a8b94a7be28cd861e50ae5fbbab5586e1df5cd7/src/Http/Http.Abstractions/src/PathString.cs#L184

both will convert a `/api/foo%2Fbar` path to `/api/foo/bar`.

**Comment by Tratcher** [comment] 2021-01-04 17:20
Decoding `%2F` is a common problem across servers, it's the only path character that can't be decoded because it changes the meaning. Kestrel had to write its own decoder to avoid it. We can try applying similar logic to FromUriComponent.

**Comment by ckuetbach** [comment] 2021-01-04 18:48
Will the fix be ported back to the supported LTS versions if needed?

**Comment by Tratcher** [comment] 2021-01-04 18:54
Not by default. You'd need to demonstrate that this is a significant blocker without a workaround.

You could work around this by bypassing the HttpClient layer and working directly with the HttpContext as shown here:
https://github.com/dotnet/aspnetcore/blob/5467bd53447d386da473ca4eb9ce1b857a7af714/src/Hosting/TestHost/test/HttpContextBuilderTests.cs#L28-L33

**Comment by mcrio** [comment] 2021-01-04 22:37
@Tratcher thanks for the workaround.

**Comment by johnyk87** [comment] 2021-03-18 11:04
Hi folks,

My team came across this same issue today in some of our tests. We are dealing with endpoints that receive an URL as a path parameter (yes, we know now that is not a very good idea 😁).

Anyway, in our setup we are heavily dependent on the `HttpClient` instances, so we came up with an alternative workaround for this issue and just thought it might help someone else that comes across this.

Our solution was to implement a delegating handler to wrap the test host's client handler, and in this wrapper we double encode any `%2F` in the request's URI (which results in `%252F`). That way, when the client handler tries to decode the `%252F` in the URI it will end up with the expected `%2F`.

A possible implementation for this handler is this:

```c#
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

public class SlashDoubleEncodingHandler : DelegatingHandler
{
	public SlashDoubleEncodingHandler(HttpMessageHandler innerHandler)
		: base(innerHandler)
	{
	}

	protected override Task<HttpResponseMessage> SendAsync(
		HttpRequestMessage request, CancellationToken cancellationToken)
	{
		request.RequestUri = new Uri(request.RequestUri.AbsoluteUri.Replace("%2F", "%252F"));
		return base.SendAsync(request, cancellationToken);
	}
}
```

Then, in order to plug this handler into an `HttpClient` to use with `TestServer`, we have created the following custom extension:

```c#
using System.Net.Http;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Hosting;

public static class TestServerExtensions
{
	/*
	 * The TestHost used by test server has a different behavior from Kestrel in how it handles encoded characters
	 * in the URL path. See https://github.com/dotnet/aspnetcore/issues/28965 for the report.
	 *
	 * In short, the `%2F` combination is decoded to a `/` by the test host client handler, and affects the
	 * destination route computed by ASP.NET routing.
	 *
	 * The custom HttpClient created here will applies a workaround to this issue by double encoding the `%2F` using
	 * a wrapper handler (`SlashDoubleEncodingHandler`). By double encoding that combination we ensure a similar
	 * behavior between the test host flow and Kestrel.
	 */
	public static HttpClient GetCustomTestClient(this IHost host)
	{
		var testServer = host.GetTestServer();
		return new HttpClient(new SlashDoubleEncodingHandler(testServer.CreateHandler()))
		{
			BaseAddress = testServer.BaseAddress,
		};
	}
}
```

This extension mimics the behavior of the current `GetTestClient` extension on `IHost`, and can be used in its place.

I hope this helps others facing this issue.

**Comment by ladeak** [comment] 2021-05-23 12:58
Looking at this `PathString.FromUriComponent` method using with *UriFormat.SafeUnescaped* solves the problem.
I am not so sure if PathString.FromUriComponent can be changed. It is being referenced by 6 places, some of them seems to benefit from the change, not sure on all of them, for example [UriHelper.Encode()] (https://github.com/dotnet/aspnetcore/blob/8a8b94a7be28cd861e50ae5fbbab5586e1df5cd7/src/Http/Http.Extensions/src/UriHelper.cs#L159) seems dangerous.

The other references seem OK-ish:
TestServer, ClientHandler, WebSockertClient to be changed, (however this is on Public API, so this would be then breaking change).

`PathString` itself is a bit unsure on this implementation too, it says:
> // REVIEW: what is the exactly correct thing to do?

For a proposed fix in a PR, would you suggest changing the PathString implementation, or to handle to handle this differently?

**Comment by Tratcher** [comment] 2021-05-24 19:31
> `PathString` itself is a bit unsure on this implementation too, it says:
> 
> > // REVIEW: what is the exactly correct thing to do?

Resolving that ambiguity is probably the best path forward.

Can you do a thorough comparison please? E.g. for a fully escaped input sequence of ascii bytes %00-%7F, what's the current behavior of PathString.FromUriComponent (TestServer) and Kestrel. Include the test setup code if possible.

**Comment by Tratcher** [comment] 2021-05-27 17:38
This overlaps with https://github.com/dotnet/aspnetcore/issues/2686.

**Comment by ladeak** [comment] 2021-05-27 17:49
Not forgotten, just busy in the last few days.

**Comment by ladeak** [comment] 2021-06-01 21:04
I don't see [FastPathTokenizer](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Routing/src/Matching/FastPathTokenizer.cs) would deal with escaping. My test input path still includes %2F or %20 during tokenization. DfaMatcher uses that to find segments of the path and to match the [route](https://github.com/dotnet/aspnetcore/blob/df47cc793afb6bbc28d4f555bbf8d486cff5ad73/src/Http/Routing/src/Matching/DfaMatcher.cs#L49).

I will attach the comparison for PathString.FromUriComponent with SafeUnescaped and Unescaped, but now I wonder if either of behavior is reasonable.

**Comment by ladeak** [comment] 2021-06-07 09:39
Hi @Tratcher 

Here is a sample code to do the test. I compared the 3 ways of unescaping the uri.
```uri.GetComponents(UriComponents.Path, UriFormat.Unescaped);```
```uri.GetComponents(UriComponents.Path, UriFormat.SafeUnescaped);```
and Kestrel's way: 
```UrlDecoder.DecodeInPlace(address, false);``` (Ref: [PathNormalizer](https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Servers/Kestrel/Core/src/Internal/Http/PathNormalizer.cs#L23))

The sample code used for the test:

```c#
private readonly ITestOutputHelper _outputWriter;
public ClientHandlerTests(ITestOutputHelper outputWriter)
{
    _outputWriter = outputWriter;
}
[Fact]
public void TestAllHex()
{
    _outputWriter.WriteLine("|Hex|Unescaped|SafeUnescaped|UrlDecoder|");
    _outputWriter.WriteLine("|---|---------|-------------|----------|");
    foreach (var currentHex in Enumerable.Range(1, 127).Select(x => "%" + x.ToString("x2", CultureInfo.InvariantCulture)))
    {
        var uri = new Uri($"https://localhost:5000/{currentHex}");
        var unescape = uri.GetComponents(UriComponents.Path, UriFormat.Unescaped);
        var safeUnescape = uri.GetComponents(UriComponents.Path, UriFormat.SafeUnescaped);
        
        var address = Encoding.UTF8.GetBytes($"/{currentHex}");
        int length = Microsoft.AspNetCore.Internal.UrlDecoder.DecodeInPlace(address, false);
        _outputWriter.WriteLine($"|/{currentHex,-10}|/{unescape,-10}|/{safeUnescape,-10}|{Encoding.UTF8.GetString(address.AsSpan(0, length)),-10}|");
    }
}
```

Here are the results (the ones to easily visualize):

|Hex|Unescaped|SafeUnescaped|UrlDecoder|
|---|---------|-------------|----------|
|/%01       |/\x01         |/%01       |/\x01        |
|/%02       |/\x02         |/%02       |/\x02        |
|/%03       |/\x03         |/%03       |/\x03        |
|/%04       |/\x04         |/%04       |/\x04        |
|/%05       |/\x05         |/%05       |/\x05        |
|/%06       |/\x06         |/%06       |/\x06        |
|/%07       |/\x07         |/%07       |/\x07        |
|/%08       |/\x08         |/%08       |/\x08        |
|/%0e       |/\x0e         |/%0e       |/\x0e        |
|/%0f       |/\x0f         |/%0f       |/\x0f        |
|/%10       |/\x10         |/%10       |/\x10        |
|/%11       |/\x11         |/%11       |/\x11        |
|/%12       |/\x12         |/%12       |/\x12        |
|/%13       |/\x13         |/%13       |/\x13        |
|/%14       |/\x14         |/%14       |/\x14        |
|/%15       |/\x15         |/%15       |/\x15        |
|/%16       |/\x16         |/%16       |/\x16        |
|/%17       |/\x17         |/%17       |/\x17        |
|/%18       |/\x18         |/%18       |/\x18        |
|/%19       |/\x19         |/%19       |/\x19        |
|/%1a       |/\x1a         |/%1a       |/\x1a        |
|/%1b       |/\x1b         |/%1b       |/\x1b        |
|/%1c       |/\x1c         |/%1c       |/\x1c        |
|/%1d       |/\x1d         |/%1d       |/\x1d        |
|/%1e       |/\x1e         |/%1e       |/\x1e        |
|/%1f       |/\x1f         |/%1f       |/\x1f        |
|/%20       |/          |/          |/         |
|/%21       |/!         |/%21       |/!        |
|/%22       |/"         |/"         |/"        |
|/%23       |/#         |/%23       |/#        |
|/%24       |/$         |/%24       |/$        |
|/%25       |/%         |/%25       |/%        |
|/%26       |/&         |/%26       |/&        |
|/%27       |/'         |/%27       |/'        |
|/%28       |/(         |/%28       |/(        |
|/%29       |/)         |/%29       |/)        |
|/%2a       |/*         |/%2a       |/*        |
|/%2b       |/+         |/%2b       |/+        |
|/%2c       |/,         |/%2c       |/,        |
|/%2d       |/-         |/-         |/-        |
|/%2e       |/          |/          |/.        |
|/%2f       |//         |/%2f       |/%2f      |
|/%30       |/0         |/0         |/0        |
|/%31       |/1         |/1         |/1        |
|/%32       |/2         |/2         |/2        |
|/%33       |/3         |/3         |/3        |
|/%34       |/4         |/4         |/4        |
|/%35       |/5         |/5         |/5        |
|/%36       |/6         |/6         |/6        |
|/%37       |/7         |/7         |/7        |
|/%38       |/8         |/8         |/8        |
|/%39       |/9         |/9         |/9        |
|/%3a       |/:         |/%3a       |/:        |
|/%3b       |/;         |/%3b       |/;        |
|/%3c       |/<         |/<         |/<        |
|/%3d       |/=         |/%3d       |/=        |
|/%3e       |/>         |/>         |/>        |
|/%3f       |/?         |/%3f       |/?        |
|/%40       |/@         |/%40       |/@        |
|/%41       |/A         |/A         |/A        |
|/%42       |/B         |/B         |/B        |
|/%43       |/C         |/C         |/C        |
|/%44       |/D         |/D         |/D        |
|/%45       |/E         |/E         |/E        |
|/%46       |/F         |/F         |/F        |
|/%47       |/G         |/G         |/G        |
|/%48       |/H         |/H         |/H        |
|/%49       |/I         |/I         |/I        |
|/%4a       |/J         |/J         |/J        |
|/%4b       |/K         |/K         |/K        |
|/%4c       |/L         |/L         |/L        |
|/%4d       |/M         |/M         |/M        |
|/%4e       |/N         |/N         |/N        |
|/%4f       |/O         |/O         |/O        |
|/%50       |/P         |/P         |/P        |
|/%51       |/Q         |/Q         |/Q        |
|/%52       |/R         |/R         |/R        |
|/%53       |/S         |/S         |/S        |
|/%54       |/T         |/T         |/T        |
|/%55       |/U         |/U         |/U        |
|/%56       |/V         |/V         |/V        |
|/%57       |/W         |/W         |/W        |
|/%58       |/X         |/X         |/X        |
|/%59       |/Y         |/Y         |/Y        |
|/%5a       |/Z         |/Z         |/Z        |
|/%5b       |/[         |/%5b       |/[        |
|/%5c       |/\         |/%5c       |/\        |
|/%5d       |/]         |/%5d       |/]        |
|/%5e       |/^         |/^         |/^        |
|/%5f       |/_         |/_         |/_        |
|/%60       |/`         |/`         |/`        |
|/%61       |/a         |/a         |/a        |
|/%62       |/b         |/b         |/b        |
|/%63       |/c         |/c         |/c        |
|/%64       |/d         |/d         |/d        |
|/%65       |/e         |/e         |/e        |
|/%66       |/f         |/f         |/f        |
|/%67       |/g         |/g         |/g        |
|/%68       |/h         |/h         |/h        |
|/%69       |/i         |/i         |/i        |
|/%6a       |/j         |/j         |/j        |
|/%6b       |/k         |/k         |/k        |
|/%6c       |/l         |/l         |/l        |
|/%6d       |/m         |/m         |/m        |
|/%6e       |/n         |/n         |/n        |
|/%6f       |/o         |/o         |/o        |
|/%70       |/p         |/p         |/p        |
|/%71       |/q         |/q         |/q        |
|/%72       |/r         |/r         |/r        |
|/%73       |/s         |/s         |/s        |
|/%74       |/t         |/t         |/t        |
|/%75       |/u         |/u         |/u        |
|/%76       |/v         |/v         |/v        |
|/%77       |/w         |/w         |/w        |
|/%78       |/x         |/x         |/x        |
|/%79       |/y         |/y         |/y        |
|/%7a       |/z         |/z         |/z        |
|/%7b       |/{         |/{         |/{        |
|/%7d       |/}         |/}         |/}        |
|/%7e       |/~         |/~         |/~        |

The ones left out:
%00 (Kestrel throws InvalidOperationException: *The path contains null characters.*
%09 Renders horizontal tab for Unescaped and UrlDecoder, %09 for SafeUnescaped
%0a Renders LF (newline) for Unescaped and UrlDecoder, %0a for SafeUnescaped 
%0b Renders VT (vertical tab) for Unescaped and UrlDecoder, %0b for SafeUnescaped 
%0c Renders FF (page break) for Unescaped and UrlDecoder, %0c for SafeUnescaped 
%0d Renders CR (carriage return) for Unescaped and UrlDecoder, %0d for SafeUnescaped 
%7c Renders | for all (I did not want to temper the table above by manually escaping it)
%7f Renders DEL for Unescaped and UrlDecoder, %7f for SafeUnescaped

**Comment by Tratcher** [comment] 2021-06-07 18:54
Ok, so SafeUnescaped is not what we need. Unescaped is pretty close except for `%2f` and `%2e`.

The `%2e` difference might actually be an issue in UrlDecoder rather than URI. In https://datatracker.ietf.org/doc/html/rfc3986/#section-5.2.4 it calls out `/.` and `/./` as a special case where the segment should be removed. UrlDecoder handles the other special navigation case for `/..` and `/../` but not the single dot case. I'll file a separate issue for that.

Yes, try using UrlDecoder in PathString. When working with the Uri overload of FromUriComponent you'll want to start with SafeUnescaped and then apply the UrlDecoder.

**Closed** 2021-07-09 16:37 UTC
Labels: area-runtime, bug, feature-HttpAbstractions, help wanted
