### ISSUE TITLE
Process crash in gRPC interop tests

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#20336] opened 2020-03-30 22:53 UTC
https://dev.azure.com/dnceng/internal/_build/results?buildId=580057&view=ms.vss-test-web.build-test-results-tab&runId=18238376&resultId=120468&paneView=attachments

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 66
   at Microsoft.AspNetCore.Internal.ProcessEx.OnOutputData(Object sender, DataReceivedEventArgs e) in /_/src/Shared/Process/ProcessEx.cs:line 159
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

@JunTaoLuo previously tried to fix this with https://github.com/dotnet/aspnetcore/pull/20254 but it's still happeing in main.

This seems like a race between disposing the process and receiving data from it. Microsoft.AspNetCore.Internal.ProcessEx.OnOutputData should suppress output if disposed.

**Comment by rynowak** [comment] 2020-04-02 17:45
Failed again here: https://dev.azure.com/dnceng/internal/_build/results?buildId=584860&view=ms.vss-test-web.build-test-results-tab&runId=18431950&resultId=120522&paneView=debug

**Comment by JunTaoLuo** [comment] 2020-04-16 20:41
The failures listed here seem to have been before my changes in https://github.com/dotnet/aspnetcore/pull/20341 were merged into master. I'm closing this since that PR seems to have resolve the issues.

**Comment by JunTaoLuo** [comment] 2020-04-16 20:50
Double checked the test history and it seems like there hasn't been a crash in our internal builds since April 1 so that seems to confirm the issue is resolved.

**Comment by Tratcher** [comment] 2020-04-17 16:35
Fresh failure:
https://dev.azure.com/dnceng/internal/_build/results?buildId=605459&view=ms.vss-test-web.build-test-results-tab&runId=19035330&resultId=120552&paneView=attachments

**Comment by BrennanConroy** [comment] 2020-06-15 21:49
Dupe of https://github.com/dotnet/aspnetcore/issues/22101

**Closed by BrennanConroy** 2020-06-15 21:49 UTC
Labels: area-grpc
