### ISSUE TITLE
How to use pregzipped js files in angular

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/aspnetcore#2444] opened 2018-01-01 21:33 UTC
_From @akashshelke22 on Thursday, October 5, 2017 5:35:17 AM_

I have an angular application. I am using webpack and commonjs. i have minified all js files. Now i have **vendor.js**(angular lib file) of size 888 kb and **vendor.js.gz** 195 kb. 
But i don't know how to use this **vendor.js.gz** file. 

I also tried to enable compression from iis but no luck. It shows me 'transferred- encoding': chunked in response header instead of 'content-encoding': gzip.

So, please help me if anyone knows gzip implementation

_Copied from original issue: aspnet/StaticFiles#216_

**Comment by aspnet-hello** [comment] 2018-01-01 21:33
_From @Tratcher on Thursday, October 5, 2017 6:26:53 AM_

This isn't supported. We've done some research on it recently but it looks like it will take some invasive changes in the stack to make it work. We're stuck with dynamic compression for now.

Are you primarily trying to do this to reduce:
A) Deployment size?
B) CPU utilization?
C) Download size?

**Comment by aspnet-hello** [comment] 2018-01-01 21:33
_From @akashshelke22 on Thursday, October 5, 2017 6:56:47 AM_

Download size

**Comment by JunTaoLuo** [comment] 2020-11-11 21:26
This seems like a duplicate of https://github.com/dotnet/aspnetcore/issues/2458

**Closed by JunTaoLuo** 2020-11-11 21:26 UTC
Labels: area-middleware, feature-StaticFiles
