### ISSUE TITLE
Blazor Client side-cache busting

### ISSUE THREAD

**Issue by joseftw** [dotnet/aspnetcore#10198] opened 2019-05-13 07:24 UTC
Im hosting a Blazor application (client-side) in Azure Storage (Static website). I then have Cloudflare CDN in front of it. I cache everything in the _framework folder for 24 hours.

Whenever I deploy I manually need to clear the Cloudflare cache since the filenames of all the DLLs and static files are the same.

It would be really great if we were able (maybe we are already?) to append a querystring or something similar with the current assembly version (or something else that we can change per release) to all the static files like this that would force the browser (and bypass cdn caches) to fetch the new file.

Example:
Current:  GET https://myexamplesite.org/_framework/_bin/System.Net.Http.dll
Wanted: GET https://myexamplesite.org/_framework/_bin/System.Net.Http.dll?version=1.0.1

**Comment by sbuchok** [comment] 2019-10-02 00:51
Just a thought, but what about something like this:

app.UseClientSideBlazorFiles<Client.Startup>(options => {
    options.version = "SomeString";
or
    options.cacheVersion = "SomeString";
});

Then all Blazor files end with ?v=SomeString, this might include mono as well. I believe there was talk about reducing the mono.wasm file when you compile by removing code that isn't used/referenced (I could be wrong). 

This is absolutely needed though. Every time I upload my site, I need to ctrl + F5 otherwise I'm getting the cached files. Not good for my clients to need to do this (when I get clients that is).

**Comment by muneebakhter** [comment] 2019-11-06 00:01
I'm having an issue with this also. Is there a quick way to enable caching client-side for the mono.wasm, blazor.webassembly.js and other framework files. It's taking almost 5 seconds to get interactive on a mobile browser hosting on firebase (tried Azure Blob storage but it doesnt give SSL certificate and CDN deploy like firebase).

**Comment by sbuchok** [comment] 2019-11-06 00:09
I found this a little while ago and figured I could probably use this to do my cache busting. 
https://remibou.github.io/Change-Blazor-DLL-extension-with-ASPNET-Core/

It looks like it's just renaming what is coming over, if that's the case, you could rename with 
?v=SomeVersionNumberingThingy and then everytime you release, just have SomeVersionNumberingThingy point to something in a config file or something ... for now.

Just a thought, I haven't tried it yet and this is where I was going to start until there was an actual fix in Blazor.

Hope this helps. Not sure if it will.

**Comment by mkArtakMSFT** [comment] 2020-01-10 19:12
Thanks for contacting us. This seems to be a dupe of https://github.com/dotnet/aspnetcore/issues/17036

**Closed by mkArtakMSFT** 2020-01-10 19:12 UTC
Labels: PRI: 2 - Preferred, area-blazor, enhancement, help wanted
