### ISSUE TITLE
How to Base64UrlEncode in Blazor WebAssembly client now that Microsoft.AspNetCore.WebUtilities has been deprecated?

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/aspnetcore#48068] opened 2023-05-04 13:44 UTC
I just spotted that NuGet in Visual Studio is saying that package `Microsoft.AspNetCore.WebUtilities` at 2.2.0 is deprecated.

I have this package installed into my Blazor WebAssembly `Client` project because I need to call method `WebEncoders.Base64UrlEncode`.

If I should remove `Microsoft.AspNetCore.WebUtilities`, how should my `Client` project perform base64 URL encoding?

(I note that my Server project is still able to call `WebEncoders` methods, and doesn't have the deprecated package installed anyway.)

[This resource](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.webencoders.base64urlencode?view=aspnetcore-7.0) says that `WebEncoders.Base64UrlEncode` lives in package `Microsoft.AspNetCore.App.Ref` but NuGet tells me that I shouldn't install that package as it's an internal thing.

**Comment by mkArtakMSFT** [comment] 2023-05-04 16:40
@wtgodbe what would it take to publish this as a package? It's part of our API set in main, so we do still have the API, it has just moved to Shared Framework some time ago, and we stopped publishing a package.

**Comment by mkArtakMSFT** [comment] 2023-05-04 16:56
@wtgodbe this is Blazor WebAssembly scenario, so they don't have access to Shared Framework.

**Comment by wtgodbe** [comment] 2023-05-04 16:59
I see - are we not going have this need for other such packages needed in the Blazor Wasm scenario? Do we think lots of people were still using those 2.2 era packages for this purpose?

If we do need to ship this package again, we just need to flip this bit, but I want to make sure we understand the scenario fully first: https://github.com/dotnet/aspnetcore/blob/28602638d11f01a0e20a3d0a0aa1f3a9a84406d6/src/Http/WebUtilities/src/Microsoft.AspNetCore.WebUtilities.csproj#L11

**Comment by Bellarmine-Head** [comment] 2023-05-05 07:03
@wtgodbe 

> then you just need to have asp.net installed on your machine & you'll get Microsoft.AspNetCore.WebUtilities for free without needing the PackageReference

Sure.  This is the deal with my `Server` project in my Blazor WebAssembly solution, but as @mkArtakMSFT has pointed out, the `Client` project doesn't access the shared framework.

@mkArtakMSFT 

> It's part of our API set in main, so we do still have the API, it has just moved to Shared Framework some time ago, and we stopped publishing a package.

This suggests that this and other packages were deprecated without sufficient consideration being given to the needs of Blazor WebAssembly client projects.

Thanks for getting the ball rolling on a possible remedy.

**Comment by Bellarmine-Head** [comment] 2023-05-05 07:06
@wtgodbe 

> what TargetFramework is your project using?

`net7.0`

**Comment by Bellarmine-Head** [comment] 2023-05-05 07:21
@wtgodbe 

Maybe an explicit `Blazor WebAssembly Client Utilities` package could be put together - culled from the original `Microsoft.AspNetCore.WebUtilities` (and maybe a few other likely, deprecated packages that have useful utility functions)...?

This would encourage devs to add the package to the `Client` project, and discourage them from adding it to the `Server` project.

**Comment by Bellarmine-Head** [comment] 2023-05-05 12:58
... or, include the utility methods in a near-term future version of https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebAssembly (for .NET 6 and .NET 7 and later).  This package gets included in every Blazor WebAssembly `Client` project.

**Comment by Peymanpn** [comment] 2023-05-07 13:20
In my opinion, keeping this package separate would help, at least in my case.

I just wanted a few methods, in this case, `Base64UrlEncode`, and I really don't want to install all of it just because of these few ones.

Thanks

**Comment by javiercn** [comment] 2023-05-08 14:22
I don't think we'll put this inside Blazor. We should not be owning this type of "common" case functionality, or else we will end up with 15 version of this across libraries (as is the case today). I would suggest making the case on the runtime repo to see if this can be added to the BCL.

You can implement this yourself in your app as follows if you need to: `Convert.ToBase64(...).Replace("+","-").Replace("+/,"_").TrimEnd("=")`

**Comment by javiercn** [comment] 2023-05-08 15:10
Closing in favor of https://github.com/dotnet/runtime/issues/1658

**Comment by Bellarmine-Head** [comment] 2023-05-09 12:50
@javiercn - ooh!  I remove the deprecated package from my Blazor client project just now, and discovered that it's **also** using https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.queryhelpers?view=aspnetcore-7.0

So this ticket shouldn't be closed in favour of https://github.com/dotnet/runtime/issues/1658 since that only deals with base64 URL encoding.

Can you re-open?

**Comment by Bellarmine-Head** [comment] 2023-05-09 13:04
@javiercn for the BCL to fully take the place of this deprecated package, it would need to include all this lot:-

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities?view=aspnetcore-7.0

**Comment by javiercn** [comment] 2023-05-09 13:11
@Bellarmine-Head sorry, I am a bit lost.

The issue is about base 64 encoding, not replacing a server package. Many of the clases in that package don't make sense in the context of Blazor, and is not something that we would create a Blazor specific package for.

**Comment by Bellarmine-Head** [comment] 2023-05-09 13:17
@javiercn

> sorry, I am a bit lost

Yes the ticket does say "How to Base64UrlEncode in Blazor WebAssembly client [...]", I grant you. 

> Many of the clases in that package don't make sense in the context of Blazor

That is true, and I was just about to add a comment to that effect.

Nevertheless, my client code also calls `QueryHelpers` in the deprecated package. That makes sense in the context of Blazor.

1. Do you have a BCL replacement for `QueryHelpers`, given that I shouldn't call into that class in the deprecated package?
2. Do you see any other types [in the list](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities?view=aspnetcore-7.0) that might still be applicable to Blazor client projects?

**Comment by javiercn** [comment] 2023-05-09 13:19
`new UriBuilder(<<your-uri>>).QueryString`

**Comment by javiercn** [comment] 2023-05-09 13:23
@Bellarmine-Head It'll help if you are concrete about what you are missing, we don't provide blazor compatible versions of every API available in the .NET ecosystem. There are some APIs that won't make sense or that will be so specialized that it is not worth for us to build a replacement around.

Like base64 url encoding, query helpers, etc. There are in most cases either simple implementations you can write or alternatives on the BCL. The abstractions that you are using are optimized for a server context, where the requirements are more stringent, but its not our goal to port those or make them available as a separate package for blazor, because most of the people won't need them. And those who do, can use acceptable alternatives or create their own implementation.

**Comment by wtgodbe** [comment] 2023-05-16 20:17
Thanks for the report - we agree that we should start shipping this package again. I'll open a PR to take care of that, and you should start seeing it in the upcoming .Net 8 previews.

**Comment by wtgodbe** [comment] 2023-05-17 16:03
Done by https://github.com/dotnet/aspnetcore/pull/48265

**Closed** 2023-05-17 16:03 UTC
Labels: enhancement, area-blazor
