### ISSUE TITLE
Browser Link Errors after Disconnect

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#43571] opened 2022-08-26 17:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Browser-Link-Errors-after-Disconnect/10132431)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Not sure]
1.  Start a Blazor Web Assembly Project with most recent template.
2.  Hit Start Debugging.
3.  Copy the URL into another browser and start the page.
4.  Stop Debugging
5.  Change something in the client project that forces it to recompile.
6.  Go to the separate browser window you had open and click to go to another page on the browser that was already started up.
7.  You will get an error "An Unhandled Error has occurred"  Console error: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'insertBefore')

If you start debugging without browser link / hot reload there is not an issue.  This also works just fine, if just execute "dotnet watch"  There is something going on with Visual Studio integration specifically.

The reason I was doing this was to test our application when network disconnect events occurred.  I thought this was an issue with my code and burned a bunch of time chasing it down.

I am confident this did not raise an error in previous versions.  I am running VS17.3.2.

Server reference versions:

Client reference versions:

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment] 2022-08-26 17:39
Note this is VS specific, however moved to GitHub given the error message in aspnetcore code:

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer

**Comment by javiercn** [comment] 2022-08-27 10:44
@TanayParikh the exception is likely caused by something manipulating the DOM.

This is likely something for @BillHiebert to look at.

**Comment by TanayParikh** [comment] 2022-08-29 16:40
Re-opened VSTS issue, closing this out.

**Closed by TanayParikh** 2022-08-29 16:40 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-debugging
