### ISSUE TITLE
Need ProblemDetails  returned for 404NotFound and 500Exception in asp.net core

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28426] opened 2020-12-04 18:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/505667/need-problemdetails-returned-for-404notfound-and-5.html)._

---
<p>Asp.net core 2.2 supports <a href="https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2?view=aspnetcore-2.2#problem-details-support" target=_blank>ProblemDetails</a> now, an IActionResult returning a client error status code (4xx) now returns a problemDetails body.</p><p>Given a new ASPNET Core 2.2 &quot;API&quot; Website,`ProblemDetails are not returned when:</p><ul>
<li>the route doesn't exist (404 Not found) </li><li>an exception is thrown from inside an ActionMethod. </li></ul><p>I understand that currently ProblemDetails are provided when a Controller is decorated with ApiController. So the first scenario (route doesn't exist/match) can't currently be handled. </p><p>The second scenario (exeception thrown) is inside an Controller/ActionMethod that has been decorated.</p><p>
ProblemDetails should apply globally, not just on a half-specific set of scenario's. This breaks application-consistency. </p><p>Currently, the only workaround is to use @khellang 's ProblemDetails nuget library (part of his 'Middleware' <a href="https://github.com/khellang/Middleware" target=_blank>repo</a>).</p><pre>Install-Package Hellang.Middleware.ProblemDetails -Version 3.0.1
</pre><p>How could we configure Web API project to also use ProblemDetails for unhandled exceptions (&quot;500 Internal Server Error&quot; responses)? By default such unhandled exceptions either return a HTML body or no body (if neither method was called).</p><p>See the github <a href="https://github.com/aspnet/AspNetCore/issues/4953" target=_blank>issue</a>.</p>

---
#### Jane Wu [MSFT] on 3/27/2019, 00:37 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by khellang** [comment] 2020-12-04 18:30
Duplicate of https://github.com/dotnet/aspnetcore/issues/4953 😅

**Closed** 2021-04-18 11:25 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved, area-mvc
