### ISSUE TITLE
Wrongly assigned number in for statement with Blazor

### ISSUE THREAD

**Issue by jjindrich** [dotnet/aspnetcore#52184] opened 2023-11-18 19:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have following code:
`@for(int i = 1; i < 3 ; i++)
{
    int n = i;
    <button @onclick="@(() => SetNum(n))">Click me @i</button>
    <button @onclick="@(() => SetNum(i))">Click me(wrong) @i</button>
}

<br/>

Clicked: @num.ToString();

@code {
    int num = 0;

    private void SetNum(int i)
    {
        num = i;
    }
}`

This code is assigning number by clicking on button. Buttons are generated by for statement.
When I click on "click me", there is assigned right number.
When I click on "click me (wrong)", there is assigned wrong number - still same.

### Expected Behavior

I expect to number will be assigned same on both buttons.

### Steps To Reproduce

`@for(int i = 1; i < 3 ; i++)
{
    int n = i;
    <button @onclick="@(() => SetNum(n))">Click me @i</button>
    <button @onclick="@(() => SetNum(i))">Click me(wrong) @i</button>
}

<br/>

Clicked: @num.ToString();

@code {
    int num = 0;

    private void SetNum(int i)
    {
        num = i;
    }
}
`

### .NET Version

6.0.320

**Comment by Andrzej-W** [comment] 2023-11-19 01:30
Hello @jjindrich 
It is not a bug. If you are ready to read in depth explanation please look here:
https://github.com/dotnet/AspNetCore.Docs/issues/10768

**Comment by Andrzej-W** [comment] 2023-11-19 02:23
@jjindrich Unrelated to your programming problem, but useful: https://github.com/dotnet/aspnetcore/issues/15915

If you think your problem has been solved, remember to close it.

**Comment by jjindrich** [comment] 2023-11-19 16:22
@Andrzej-W thanks for sharing related item. But still I don't understand why is not bug. As described lot of people are using it and are confused as me. Can you give me some explanation why it is designed in this way ?
If I will create local variable, it will start to work.

**Comment by Andrzej-W** [comment] 2023-11-19 19:52
First I have to say that this design is not related to Blazor at all. It is a language feature and is documented here:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions#capture-of-outer-variables-and-variable-scope-in-lambda-expressions

When lambda expression is assigned to OnClick event it is not executed. It will be executed in the future after user clicks the button. At this time your variable `i` and `n` is out of scope. To correctly execute your code compiler has to capture references to these variables. You have only one instance of variable `i` - it is declared in `for` loop. You have 3 instances of variable `n` - new variable is created at the beginning of each loop.

Here is a simple example of console application to show you how it works
```c#
List<Func<int>> fi_list = new List<Func<int>>(); 
List<Func<int>> fn_list = new List<Func<int>>();

// variable i is declared before for loop because I want to have
// access to it near the end of this function
int i;
for (i = 2; i < 5; i++)
{
    int n = i;
    
    // create lambda expression to calculate square of i and add it to the list
    Func<int> fi = () => i * i;
    fi_list.Add(fi);
 
    // create lambda expression to calculate square of n and add it to the list
    Func<int> fx = () => n * n;
    fn_list.Add(fx);
}

// call each lambda to see the result
foreach (var f in fi_list)
    Console.WriteLine($"i * i = {f()}");

foreach (var f in fn_list)
    Console.WriteLine($"n * n = {f()}");

// change the value of i and call any lambda from fi_list
i = 10;
Console.WriteLine($"i * i = {fi_list[0]()}");

Console.ReadLine();
```

And here is the result:
```
i * i = 25
i * i = 25
i * i = 25
n * n = 4
n * n = 9
n * n = 16
i * i = 100
```

**Closed** 2023-11-20 09:56 UTC
Labels: area-blazor
