### ISSUE TITLE
svg not rendering properly.

### ISSUE THREAD

**Issue by musictopia2** [dotnet/aspnetcore#22933] opened 2020-06-14 08:14 UTC
When this code is used
<svg viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
        
        <rect x="0" y="0" width="100%" height="100%" />

        
        <circle cx="50%" cy="50%" r="4" fill="white" />
    </svg>

nothing gets rendered.  However, when i use the exact same code in a normal html page, is fine.

**Comment by blowdart** [comment] 2020-06-14 16:07
Is this in an MVC app, a Razor page or Blazor?

**Comment by musictopia2** [comment] 2020-06-14 19:16
This is blazor.

**Comment by javiercn** [comment] 2020-06-15 18:25
@musictopia2 thanks for contacting us.

We have an issue tracking adding proper support for SVG.

Closing this issue as a dupe of https://github.com/dotnet/aspnetcore/issues/18271

**Closed by javiercn** 2020-06-15 18:25 UTC
Labels: Needs: Attention :wave:, area-blazor
