### ISSUE TITLE
RenderFragment with an event handler throws an error

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#26729] opened 2020-10-09 05:53 UTC
### Describe the bug
Attaching an event handler in a `RenderFragment` throws a compilation error. Using the idea from https://github.com/dotnet/AspNetCore.Docs/blob/1e199f340780f407a685695e6c4d953f173fa891/aspnetcore/blazor/webassembly-performance-best-practices.md#defining-reusable-renderfragments-in-code

### To Reproduce
Use the code snippet and compile (tested with 5.0 RC1):
```razor
@code {
    RenderFragment<Input> InputRenderer = input => __builder =>
    {
        <input @oninput="@(input.OnInput)" />
    };
}
```

### Exceptions (if any)
 Argument : cannot convert from 'method group' to 'bool'

### Additional context
This is handy in cases where you don't want to create a separate component, but reuse a simple fragment like the above. In addition, such fragments are useful in the internal implementation of a component, when rendering is based on some type of a configuration parameter, e.g:
```razor
if (AutoSize) 
{
    <div class="some-sizing-wrapper">
             @InputRenderer(this);
    </div>
}
else
{
    <div class="wrapper">
             @InputRenderer(this);
    </div>
}
```

### Further technical details
- ASP.NET Core version 5.0 RC1
- Include the output of `dotnet --info`
- VS 2019 16.8 Preview

**Comment by javiercn** [comment] 2020-10-09 08:07
@Stamo-Gochev thanks for contacting us. 

Have you tried using the lambda syntax within the handler attribute? `@oninput="(e) => input.OnInput(e)" />

**Comment by Stamo-Gochev** [comment] 2020-10-09 08:38
I've tried various syntaxes, but not of them are working. The `@oninput="(e) => input.OnInput(e)"` throws with `CS1660: Cannot convert lambda expression to type 'bool' because it is not a delegate type`. The compiler can probably be tricked to allow the syntax, but I haven't found a workaround.

**Comment by mkArtakMSFT** [comment] 2020-10-09 16:11
Thanks for contacting us.
This is a dupe of #20538 and answered at https://github.com/dotnet/aspnetcore/issues/20538#issuecomment-706156819

**Closed by mkArtakMSFT** 2020-10-09 16:11 UTC
Labels: area-blazor

**Comment by Stamo-Gochev** [comment] 2020-10-12 07:12
None of the suggested syntax versions seem to work though (including the one posted by @SteveSandersonMS in https://github.com/dotnet/aspnetcore/issues/20538#issuecomment-706156819

```razor
@InputRenderer(InputInstance)

@InputRenderer2(InputInstance)

@code {
    public class Input
    {
        public void OnInput(ChangeEventArgs args)
        {
            Console.WriteLine("change: " + DateTime.Now.ToString());
        }
    }

    public Input InputInstance { get; set; } = new Input();

    RenderFragment<Input> InputRenderer = input => __builder =>
    {
        <input @oninput="@(input.OnInput)" />
    };


    RenderFragment InputRenderer2(Input input) => __builder =>
    {
        <input @oninput="@(input.OnInput)" />
    };
}
```
Am I missing something?

**Comment by SteveSandersonMS** [comment] 2020-10-13 12:53
@Stamo-Gochev I've checked, and the following works (at least on .NET 5 RC2, probably earlier too):

```razor
@page "/counter"

@InputRenderer2(InputInstance)

@code{
    public class Input
    {
        public void OnInput(ChangeEventArgs args)
        {
            Console.WriteLine("change: " + DateTime.Now.ToString());
        }
    }

    public Input InputInstance { get; set; } = new Input();

    RenderFragment InputRenderer2(Input input) => __builder =>
    {
        <input @oninput="input.OnInput" />
    };
}
```

There is a weird problem that occurs if you replace `@oninput="input.OnInput"` with `@oninput="@input.OnInput"` (notice the extra `@`). This gives a compiler error. I don't know why and am reporting that as a separate bug. Until that's fixed, you'll have to be careful not to add that extra `@` in this specific case.
