### ISSUE TITLE
[SignalR] Stateful reconnect

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#46691] opened 2023-02-15 21:46 UTC
Allows the server to retain the send buffer while the client is reconnecting and preserve connection state (`Context.Items`, connection ID, etc.).

Thoughts:
* Would need to be opt-in and supported by both client and server. Because client needs to change to try to reconnect with the same connection ID as its previous connection.
* Need an option to configure how long to keep the connection state on the server
* Skip negotiate doesn't play well in a multi-server environment when sticky-sessions aren't enabled
* How does it work with Azure SignalR Service
* Does the client need a new event to say "doing stateful reconnect"? What's the interaction with the current automatic reconnect feature?
* If client connects with different auth credentials, do we replace the `User`?

Needs work:
- [ ] Configurable buffer limit(s), total bytes count and maybe total message count too
- [x] Versioning, probably increment HubProtocol and add "ack protocol"
- [ ] ~~Try to push feature fully into SignalR layer, i.e. get new ConnectionContext from lower layer and map onto existing connection~~
  - [ ] Replace IReconnectFeature with IExistingConnectionFeature or something, that contains the previous ID on the new ConnectionContext (because client will send old id via query string)
  - [ ] Need timeout logic in SignalR layer then
  - [ ] And pause the read loop waiting for a new connection
  - [ ] Figure out what happens when a seamless reconnect takes too long, do we just kill the connection attempt, or keep it as a new connection (since the ConnectionContext is completely new) and send the new ID back to the client somehow?
  - [ ] Potentially send a CloseMessage from clients to have a guaranteed way of knowing the connection close is graceful
- [ ] If not, finalize IReconnectFeature API
- [ ] Fix StopAsync race in WebSocketsTransport (Running task being overwritten), it might be delaying reconnect fallback logic
- [x] Pool buffers in MessageBuffer
- [x] Finalize options for enabling the feature, both client and server side
  - [x] And disallowing the feature from server side
- [ ] Retry policy for seamless reconnect attempts, separate from current reconnect policies
- [ ] Fix many TODOs in current code

**Comment by johnkattenhorn** [comment] 2023-05-21 01:56
Hey @BrennanConroy, we've seen the pull request and the proposal, we think this will be a great feature for our use-case of mobile gaming which we've been working with @kevinguo305 on. We are working on a plan to put a reference architecture to illustrate how to use signalR in gaming. 

@kevinguo305 - do you know if the team who built the UnityClient are aware of this work going on this feature ?

**Comment by BrennanConroy** [comment] 2023-05-25 03:44
Glad to hear it! Are you in a position to be able to try out .NET previews? We're planning on getting the initial implementation into 8.0-preview5 and would love to find folks to try it out and make sure it works well.

**Comment by johnkattenhorn** [comment] 2023-05-25 04:08
Yep - we would be happy to try it out.

**Comment by TimChen44** [comment] 2023-06-14 11:54
This capability is too important for Blazor Server, and I hope that in the future, Blazor Server will not cause the entire program to crash due to network reasons.

**Comment by Webreaper** [comment] 2023-06-14 11:58
> Glad to hear it! Are you in a position to be able to try out .NET previews?

I'd love to try/test this, but for some reason .Net 8 previews still aren't supported by VS for Mac. Maybe in preview 6?

**Comment by m33p** [comment] 2023-06-24 23:15
I wanted to give my feedback and this feature.
This feature is amazing and a must have. I've been engaging with our VPN team with connection issues to our Blazor application. One of our VPN or firewall is dropping the websocket connection. After testing with this feature turned on the issue isn't even noticeable. Please ship this with .NET 8.

**Comment by adityamandaleeka** [comment] 2023-06-28 17:51
That's great to hear @m33p. @johnkattenhorn Have you had a chance to try it as well?

As you've seen, we got the initial implementation out in preview 5 and plan to make some improvements in preview 7. I'm moving the milestone on this issue to reflect that.

**Comment by agrubbszenzio** [comment] 2023-06-29 21:25
> @johnkattenhorn [preview 5 is out](https://dotnet.microsoft.com/download/dotnet/8.0). To try this out you have to use the .NET client with WebSockets and enable the feature option:
> 
> ```
> var hubConnection = new HubConnectionBuilder()
>     .WithUrl("<hub url>",
>              options =>
>              {
>                 options.UseAcks = true;
>              })
>     .Build();
> ```

Looking for documentation on where to implement this. Can this be placed in the program.cs?

We have a dashboard business app that loses connectivity and are planning to give this a go. We are hoping to keep the project in Blazor server side.

Thanks

**Comment by BrennanConroy** [comment] 2023-07-11 16:13
> connection issues to our Blazor application.

@m33p I assume you're using Blazor WASM and have a component using `HubConnection`? Glad that it's working better for you!

> We are hoping to keep the project in Blazor server side.

@agrubbszenzio This isn't possible yet since Blazor server side uses the Javascript SignalR client which doesn't implement this feature yet. We're nailing down the details with the .NET client first before getting other clients updated. Javascript client will be next though.

8.0-preview6 is out today and does require the server to opt-in to this feature now to use it.

Example code:
**Server:**
```csharp
app.MapHub<AppHub>("/default", o => o.AllowAcks = true);
```
**Client:**
```csharp
var hubConnection = new HubConnectionBuilder()
    .WithUrl("<hub url>",
             options =>
             {
                options.UseAcks = true;
             })
    .Build();
```

**Comment by Webreaper** [comment] 2023-07-11 16:19
> 8.0-preview6 is out today and does require the server to opt-in to this feature now to use it.

This is exciting - I'd like to try it. Do we know if preview 6 will finally add VS for Mac support?

**Comment by BrennanConroy** [comment] 2023-07-11 16:28
> Do we know if preview 6 will finally add VS for Mac support?

No idea. I think the relationship is the other way around though: "Does VS for Mac support 8.0-preview6?"

**Comment by Webreaper** [comment] 2023-07-11 22:48
Turns out the answer is Yes!

**Comment by Webreaper** [comment] 2023-07-12 07:41
I'm trying this in my app, but I'm getting an error for `options.UseAcks = true;` - compiler is saying there's no UseAcks property. This is with .Net 8 preview 6. Did it definitely get into the release?

**Comment by BrennanConroy** [comment] 2023-07-24 21:56
> I'm trying this in my app, but I'm getting an error for `options.UseAcks = true;` - compiler is saying there's no UseAcks property. This is with .Net 8 preview 6. Did it definitely get into the release?

Yes, it's definitely been present since preview5. This likely means you aren't actually using the preview builds.

**Comment by Webreaper** [comment] 2023-07-25 08:29
> Yes, it's definitely been present since preview5. This likely means you aren't actually using the preview builds.

I was definitely using the preview builds, because I had other code using features from preview 6. However, I just uncommented that line, and it's not generating a compiler error (I haven't installed any updated SDKs since I last tried). Very very weird. But looks better now!

**Comment by WhitWaldo** [comment] 2023-07-31 03:25
> This isn't possible yet since Blazor server side uses the Javascript SignalR client which doesn't implement this feature yet. We're nailing down the details with the .NET client first before getting other clients updated. Javascript client will be next though.

I, too, am really looking forward to seeing this functionality in Blazor Server once it's been fleshed out in this context.

**Comment by juanyacovino77** [comment] 2023-08-03 19:32
Hey, 

is there a guaranteed way of sharing state between SignalR client and the hub?  I mean guaranteed because we know HttpContext it is not.

For example, I would like to receive data from the client at the OnConnected() Hub event... How could I make this? (out of using headers and cookies)

Let say I have the list of connectionId s mapped with user id at in-memory dictionary or using Context.Items.. at the moment the conection get disconnected I need to map that (disconnected) connectionid  to the corresponding connected new one ...(in order to identify the same device) The only way of mapping the last disconnect connectionId with the new one it to define a new hub method and call it from the client with the parameters.

I am using ASP.NET Core 6. 

it would be useful to have more info about the SignalR conection context (not http)

thanks

**Comment by benguenter** [comment] 2023-09-05 22:39
Very excited about this feature, at what point after the .net 8 release will this be available when using the Azure SignalR Service?

**Comment by Sebazzz** [comment] 2023-09-12 19:28
> This isn't possible yet since Blazor server side uses the Javascript SignalR client which doesn't implement this feature yet. 

Is this expected before RTM, or do we need to wait on .NET 9 for that?

**Comment by BrennanConroy** [comment] 2023-09-12 19:37
> > This isn't possible yet since Blazor server side uses the Javascript SignalR client which doesn't implement this feature yet.
> 
> Is this expected before RTM, or do we need to wait on .NET 9 for that?

This will work in 8.0-rc2

**Comment by adityamandaleeka** [comment] 2023-10-03 23:45
@BrennanConroy can we call this issue done now?

**Comment by pigwing** [comment] 2023-10-11 01:56
> > > This isn't possible yet since Blazor server side uses the Javascript SignalR client which doesn't implement this feature yet.
> > 
> > 
> > Is this expected before RTM, or do we need to wait on .NET 9 for that?
> 
> This will work in 8.0-rc2

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-2/
![image](https://github.com/dotnet/aspnetcore/assets/8393545/190a6214-ea57-4271-8c83-bab8ca29c27d)


blazor haven't updated it yet?^_^

**Comment by BrennanConroy** [comment] 2023-10-11 02:00
Blazor can be configured for the client side via https://learn.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-7.0#configure-signalr-timeouts-and-keep-alive-on-the-client, you still need server side settings as well.

**Comment by pigwing** [comment] 2023-10-11 02:02
thx

**Comment by kescherCode** [comment] 2023-10-12 16:05
Would this work with Azure SignalR as-is or will it require explicit support on their end?

**Comment by BrennanConroy** [comment] 2023-10-12 19:07
Azure SignalR Service requires explicit support.

**Comment by hrytskivr** [comment] 2023-10-12 20:56
Can this work with Redis backplane and when web-api i scaled out behind load balancer?

**Comment by BrennanConroy** [comment] 2023-10-12 21:27
> With sticky sessions not configured and skipNegotiation: true on the client side.

No, you need sticky sessions.

**Comment by XorZy** [comment] 2023-10-13 22:13
How does one configure the server to enable stateful reconnect with InteractiveServerRenderMode?
I don't see where in the new template one could set that option.

**Comment by pigwing** [comment] 2023-10-16 07:27
`app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode().Add(convention =>
    {
        var meta = convention.Metadata.FirstOrDefault(e => e is HttpConnectionDispatcherOptions);
        if (meta != null)
        {
            HttpConnectionDispatcherOptions options = (HttpConnectionDispatcherOptions)meta;
            options.AllowStatefulReconnects = true;
        }
    });`
I found this method at present.

**Comment by mkArtakMSFT** [comment] 2023-12-12 03:42
Removing the milestone for the team to retriage

**Comment by Benedicht** [comment] 2024-01-02 16:44
Is there an up-to-date documentation for implementors about this feature?

- Main branch's [TransportProtocols](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md) spec looks very out of date.
- [This version](https://github.com/dotnet/aspnetcore/blob/58c06cf5813746835d2dd34355ff10ce15c3c38a/src/SignalR/docs/specs/TransportProtocols.md) has some detail about the framing too, but i don't know how trustworthy the information.

**Comment by adityamandaleeka** [comment] 2024-01-03 02:02
@Benedicht I've opened #53103 to track your question about the doc. I'm going to close this issue now since it was originally meant to track getting stateful reconnect done, which has now shipped in .NET 8. Further work/issues can be tracked separately.

**Closed by adityamandaleeka** 2024-01-03 02:02 UTC
Labels: area-signalr
