### ISSUE TITLE
Build fails for Blazor App with overridden BaseIntermediatePath 

### ISSUE THREAD

**Issue by ravenpride** [dotnet/aspnetcore#29893] opened 2021-02-04 12:26 UTC
### Describe the bug

The issue occurs with SDK 5.0.2.

I've created a fresh project based on the "Blazor App" project template. The resulting project builds and runs as expected. Then I've overridden the `BaseIntermediatePath` property with a `Directory.Build.props` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<BaseIntermediateOutputPath>..\..\_build\.obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
	</PropertyGroup>
</Project>
```

After this the build fails with the following output:
```
2>------ Rebuild All started: Project: BlazorApp1.Client, Configuration: Debug Any CPU ------
2>BlazorApp1.Client -> C:\Users\fals\source\repos\BlazorApp1\BlazorApp1\Client\bin\Debug\net5.0\BlazorApp1.Client.dll
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018: The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fals\source\repos\BlazorApp1\BlazorApp1\Client\obj\Debug\net5.0\service-worker-assets.js'.
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018:    at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateServiceWorkerAssetsManifest.Execute()
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Done building project "BlazorApp1.Client.csproj" -- FAILED.
```

### To Reproduce

Create a new project based on the "Blazor App" project template and put the `Directory.Build.props` file (see above) beside the solution file (topmost directory). Then trigger the build to see the error.

### Own investigations

Although the `BaseIntermediatePath` is not rooted in the `Directory.Build.props` file, it is in this [targets file](https://github.com/dotnet/aspnetcore/blame/v5.0.2/src/Components/WebAssembly/Sdk/src/targets/Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets#L19-L21). Therefore a wrong path is constructed at the top of the file. There seems to be something that mangles the path on the way from the `Directory.Build.props` to the targets file, I cannot see, yet.

Any help is appreciated.

**Comment by javiercn** [comment] 2021-02-04 13:26
@ravenpride thanks for contacting us.

We'll look at this and update the issue accordingly.

**Comment by nvmkpk** [comment] 2021-05-09 05:40
I ran into the same issue. I had to remove the items that `_ComputeServiceWorkerAssets` target adds and duplicate it with corrected value for `` property to fix this issue. Fix is very simple, remove the condition from line 20 and completely remove line 19 (always use $(IntermediateOutputPath) and do not assume obj folder to be inside the project folder). Sad this isn't fixed yet.

**Comment by SimonCropp** [comment] 2021-05-14 01:57
i think this is the same problem as https://github.com/dotnet/aspnetcore/issues/29939  ?

**Comment by ravenpride** [comment] 2021-05-14 06:14
Maybe it is a related issue, but I don't think it is the same.

#29939 is about a problem that occurs when setting *AppendTargetFrameworkToOutputPath* to *false* to omit the target framework when generating the output path.

This issue is about overriding the *BaseIntermediatePath* property.

**Comment by SimonCropp** [comment] 2021-05-14 06:50
@ravenpride agreed. although i suspect it might be the same root cause https://github.com/dotnet/aspnetcore/issues/29939#issuecomment-840942679

**Comment by SteveSandersonMS** [comment] 2021-08-03 18:10
We think this is resolved in .NET 6. Could you please try the latest .NET 6 preview release and let us know if the issue still affects your application? Thanks!

**Comment by McNerdius** [comment] 2021-08-11 05:34
After upgrading to Preview 7 i am having a similar issue.

Up until now, i've set `<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>` and `<IntermediateOutputPath>obj</IntermediateOutputPath>`  so as to have a consistent output path for the intermediate `scopedcss` between debug & deploy.

As of preview 7, the build fails with `Could not find a part of the path '...\obj\Debug\net6.0\StaticWebAssets.build.json'`

Not sure if making this its own issue is warranted / if there's a better way to get feedback on how to work around this, specifying a path for the intermediate scoped-css bundle one way or another.

**Closed** 2021-08-11 07:09 UTC
Labels: bug, area-blazor, blazor-wasm, affected-few, severity-major, feature-razor-sdk

**Comment by pbiggar** [comment] 2021-08-17 18:31
This was also broken for me on preview 7, and fixed in RC1.
