### ISSUE TITLE
Improve TLS mismatch error messages/experience

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27472] opened 2020-11-02 22:56 UTC
* Grpc hits this a lot
* HTTP -> HTTPS
* HTTPS -> HTTP
* H2C -> HTTP(S)

**Comment by Tratcher** [comment] 2020-12-07 20:20
Nginx has a special status code for that:
497 HTTP Request Sent to HTTPS Port
http://nginx.org/en/docs/http/ngx_http_ssl_module.html

**Comment by Tratcher** [comment] 2020-12-07 20:23
Note H2C -> HTTPS endpoint would trigger the same checks and message as HTTP -> HTTPS because of the connection preface unless we special cased the HTTP/2 prefface `PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n`.

**Comment by Tratcher** [comment] 2022-09-13 17:11
@JamesNK this looks like a duplicate of another issue you were working on?

**Comment by JamesNK** [comment] 2022-09-13 22:28
I improved the mismatch between HTTP/1.1 and HTTP/2. I haven't done anything for TLS.

**Comment by Tratcher** [comment] 2022-09-13 22:53
What was the issue number?

**Comment by JamesNK** [comment] 2022-09-13 22:57
https://github.com/dotnet/aspnetcore/issues/14884

Yes, this can be closed as a dupe.

**Closed** 2022-09-13 22:57 UTC
Labels: enhancement, area-runtime, severity-nice-to-have, affected-medium
