### ISSUE TITLE
Handle dotnet/extensions scenarios in ASP.NET http logging middleware

### ISSUE THREAD

**Issue by noahfalk** [dotnet/aspnetcore#48667] opened 2023-06-08 03:43 UTC
Dotnet/extensions recently introduced alternative middleware for ASP.NET logging. Right now the behavior feels duplicative with a variety of differences between the two implementations. Neither one has a superset of the features and they don't agree on API naming or defaults. We'd like an experience that feels more like composition or an upgrade, not picking between alternatives.

This issue tracks:
- [ ] - Planning any necessary changes to the dotnet/extensions API to better align the experience
- [ ] - Implementing any needed extensibility hooks or disable mechanisms in the built-in middleware

**Comment by NilayParikh33** [comment] 2023-06-13 09:00
Hello @noahfalk I am solving my First Opensource Problem Statement so can you elaborate why to change the current functionality and what is issue coming up.

**Comment by noahfalk** [comment] 2023-06-13 12:27
Hi @NilayParikh33, its always great to have folks coming in, thanks! This issue is probably not a good issue to start with but there are suggestions here on how to find good ones: https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md#finding-an-issue-to-work-on.

**Comment by joperezr** [comment] 2023-08-22 16:10
This is a dupe of https://github.com/dotnet/extensions/issues/4210 as this is basically tracking the piece on dotnet/extensions side. We already have a bug for covering the aspnetcore pieces.

**Closed** 2023-08-22 16:11 UTC
Labels: area-runtime
