### ISSUE TITLE
Blazor TaskCanceledException when using <Virtualize>

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#30535] opened 2021-02-27 09:06 UTC
Using `<Virtualize>` tags is causing my error logs to be filled with the following:

```c#
021-02-27 04:02:24.5061|100|WARN|Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer|Unhandled exception rendering component: A task was canceled. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
2021-02-27 04:02:24.5268|100|WARN|Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer|Unhandled exception rendering component: A task was canceled. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
2021-02-27 04:02:24.5268|111|ERROR|Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost|Unhandled exception in circuit 'LXO0dO3nLRRxNIOYunyJaRLWp2YgyqsL5smNuYdWznA'. System.AggregateException: Exceptions were encountered while disposing components. (A task was canceled.) (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
```

The above exceptions seem to be logged about 30 seconds or so after I load a blazor component with `<Virtualize></Virtualize>` tags. If I refresh the page with the blazor component X times, the exception will be logged X times, about 30 seconds after the refresh is finished.

Can these be suppressed/ignored? It doesn't seem to have any affect on the app's functionality.

**Comment by mkArtakMSFT** [comment] 2021-03-01 17:24
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/30086

**Closed by mkArtakMSFT** 2021-03-01 17:24 UTC
Labels: area-blazor, feature-blazor-virtualization

**Comment by mkArtakMSFT** [comment] 2021-03-01 17:25
Also, feel free to ignore those exceptions.
We will make sure these don't show up in the future as these cancellations are intentional.
