### ISSUE TITLE
System.Runtime.InteropServices.COMException: The client has disconnected An operation was attempted on a nonexistent network connection.

### ISSUE THREAD

**Issue by mayankmaheshwari18** [dotnet/aspnetcore#36375] opened 2021-09-10 15:12 UTC
### Describe the bug

We have a service on .Net Core 3.1 hosted on Azure App service. AFD and APIM stands in front of this service. Flow is VS Code calls AFD, AFD calls APIM and APIM calls the service. 

### Exceptions (if any)
**EXCEPTION**
System.Runtime.InteropServices.COMException
**Exception Properties**
**Event time**	9/9/2021, 11:18:08.350 AM (Local time)	
**Message**	The client has disconnected An operation was attempted on a nonexistent network connection. (0x800704CD)	
**Exception type**	System.Runtime.InteropServices.COMException	
**Failed method**	Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult	
**Problem Id**	System.Runtime.InteropServices.COMException at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult	
Assembly	Microsoft.AspNetCore.Server.IIS, Version=3.1.16.0, Culture=neutral, PublicKeyToken=adb9793829ddae60	
**Severity level**	Error	
**Telemetry type**	exception	
**Operation name**	POST ExtensionQuery/QueryExtensions	
**Application version**	1.0.0.0	
Device type	PC	
SDK version	il:2.16.0-18277	
Sample rate	1	
Custom Properties
**FormattedMessage**	Connection ID "15348267531689295453", Request ID "80007ed7-0000-d500-b63f-84710c7967bb": An unhandled exception was thrown by the application.	
OriginalFormat	Connection ID "{ConnectionId}", Request ID "{TraceIdentifier}": **An unhandled exception was thrown by the application.**	
AspNetCoreEnvironment	Production	
CategoryName	**Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer**	
EventName	ApplicationError	

1. Why do these exception occurs?
2. Is there a way to handle them gracefully?
3. This is happening periodically (if this helps)
![ComsException](https://user-images.githubusercontent.com/16611785/132876180-f4de674c-1ab0-4554-ba23-6d2b736b8f2e.png)

Attaching Call Stack: 
[ComException Call Stack.txt](https://github.com/dotnet/aspnetcore/files/7144746/ComException.Call.Stack.txt)

**Comment by davidfowl** [comment] 2021-09-10 16:07
Where's the full callstack? This is a normal error that happens when a client disconnects and the server is trying to read data.

**Comment by mayankmaheshwari18** [comment] 2021-09-10 17:13
I have attached the call stack. Application Insights have provided the same. 
Regarding the exception, wondering why is there a continuous pattern there? We are also getting **Client Disconnect** exception but they are larger in number compared to these exceptions.

**Comment by adityamandaleeka** [comment] 2021-09-10 20:22
Triage: the COM Exception is caught and a ConnectionResetException is thrown. Whoever is reading the body should be catching the IOException that ConnectionResetException derives from.

@pranavkm Should model binding be catching this? Is there an existing issue we can duplicate this on?

**Comment by pranavkm** [comment] 2021-09-10 20:34
We've been addressing IOExceptions that are encountered as part of model binding over releases: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/ModelBinding/FormValueProviderFactory.cs#L43-L58. My guess is this is a 3.1 app, updating it to 5.0 or later is likely to address this issue. Here's an issue you can dupe this against: https://github.com/dotnet/aspnetcore/issues/13333

**Comment by adityamandaleeka** [comment] 2021-09-11 01:53
Per above, closing this as a duplicate of https://github.com/dotnet/aspnetcore/issues/13333

**Closed by adityamandaleeka** 2021-09-11 01:53 UTC
Labels: area-runtime
