### ISSUE TITLE
IHostedService StopAsync is not getting Stopped without exception in Azure App Service Linux

### ISSUE THREAD

**Issue by mars-boy** [dotnet/aspnetcore#24569] opened 2020-08-04 20:14 UTC
### IHostedService StopAsync is not getting Stopped without exception in Azure App Service Linux
I have implemented background service which works fine in IIS. When deployed in azure background service is getting stopped in between. Implemented the same as is from this blob 

https://www.stevejgordon.co.uk/asp-net-core-2-ihostedservice

Logs...

```
2020-08-04T19:55:56.341402416Z INFO  04-08-2020 19:55:56 Engine.Worker [52] - Running in loop :
2020-08-04T19:55:56.436460623Z INFO  04-08-2020 19:55:56 Engine.Worker [27] - Running in loop for UniqueId : 9cadda6c-61dc-4daf-98ea-217cc021be2e
2020-08-04T19:56:06.437710082Z INFO  04-08-2020 19:56:06 Engine.Worker [52] - Running in loop :
2020-08-04T19:56:06.554352084Z INFO  04-08-2020 19:56:06 Engine.Worker [27] - Running in loop for UniqueId : 9cadda6c-61dc-4daf-98ea-217cc021be2e
2020-08-04T19:56:16.560875556Z INFO  04-08-2020 19:56:16 Engine.Worker [27] - Running in loop :
2020-08-04T19:56:16.671622282Z INFO  04-08-2020 19:56:16 Engine.Worker [27] - Running in loop for UniqueId : 9cadda6c-61dc-4daf-98ea-217cc021be2e
2020-08-04T19:56:26.677579018Z INFO  04-08-2020 19:56:26 Engine.Worker [39] - Running in loop :
2020-08-04T19:56:26.777754060Z INFO  04-08-2020 19:56:26 Engine.Worker [39] - Running in loop for UniqueId : 9cadda6c-61dc-4daf-98ea-217cc021be2e
2020-08-04T19:56:36.777162084Z INFO  04-08-2020 19:56:36 Engine.Worker [39] - Running in loop :
2020-08-04T19:56:36.877469666Z INFO  04-08-2020 19:56:36 Engine.Worker [27] - Running in loop for UniqueId : 9cadda6c-61dc-4daf-98ea-217cc021be2e
2020-08-04T19:56:43.250136102Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
2020-08-04T19:56:43.250182501Z       Received hub invocation: InvocationMessage { InvocationId: "4", Target: "MasterBucketConfigGetAll", Arguments: [ SiteID: 4
2020-08-04T19:56:43.250189801Z       UserID: 4
2020-08-04T19:56:43.256896460Z        ], StreamIds: [  ] }.
2020-08-04T19:56:43.258300251Z INFO  04-08-2020 19:56:43 Engine.SignalR.AdminHub [39] - MasterBucketConfigGetAll : SiteID: 4
2020-08-04T19:56:43.258314851Z UserID: 4
```

There's no further info about worker after that.

### Further technical details
- ASP.NET Core version 3.1
- Running on Azure App Service Linux

**Comment by BrennanConroy** [comment] 2020-08-05 20:08
@bradygaster Can you close as dupe if this isn't different from the other similar issues.

**Comment by mars-boy** [comment] 2020-08-07 08:45
@bradygaster  any update.

**Comment by mars-boy** [comment] 2020-08-13 07:24
@BrennanConroy  Thanks

**Comment by bradygaster** [comment] 2020-08-17 17:43
referencing #22272 as these are probably same root cause

**Comment by BrennanConroy** [comment] 2020-11-06 22:41
Closing in favor of #22272

**Closed by BrennanConroy** 2020-11-06 22:41 UTC
Labels: area-servers
