### ISSUE TITLE
File Input in Blazor SSR not validating

### ISSUE THREAD

**Issue by darena-pjindal** [dotnet/aspnetcore#54607] opened 2024-03-18 21:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a blazor web app with only SSR (no WASM or Server). I added the following component to upload a file. I understand from other issues posted that the bind parameter is not available, and I have to use the name. This works fine if I add a file and click upload. However, I need to make sure that the user doesn't click the upload button without selecting a file. I assumed that the Required annotation on FIleUpload will prevent the form being submitted. It should give me an error. However, the application crashes if I try to run this code without selecting a file. It doesn't even hit the submit function. So, there is no way to handle this error. Is there any known issue with the inputfile for validation. I would appreciate any help resolving this. 

```html

    <EditForm Model="@vm" OnValidSubmit="@Submit" FormName="FileUpload" method="post" enctype="multipart/form-data" Enhance>
        <DataAnnotationsValidator/>

        <div class="container-fluid mt-4">
            <div class="card shadow-sm">
                <div class="card-body">

                    <h5 class="card-title">Upload </h5>
                    <p class="card-text">Select file from your device.</p>

                    <div class="mb-3">
                        <InputFile name="vm.FileUpload" class="form-control" placeholder/>
                        <ValidationMessage For="() => vm.FileUpload" class="text-danger"/>
                    </div>

                    <div class="text-center mb-3">
                        <button type="submit" class="btn btn-primary">Upload </button>
                    </div>
                  
                </div>
            </div>
        </div>
    </EditForm>

```
```cs
[SupplyParameterFromForm(FormName = "FileUpload")]
    private FileUploadVm vm { get; set; } = new();

    public async Task Submit(EditContext editContext)
    {
        try
        {
            string fileContent;
            if (vm.FileUpload != null && vm.FileUpload.Length > 0)
            {
                using var reader = new StreamReader(vm.FileUpload.OpenReadStream());
                fileContent = await reader.ReadToEndAsync();
                //do something with the file
            }
        }
        catch (Exception e)
        {
        }
    }

    public class FileUploadVm
    {
        [Required] public IFormFile? FileUpload { get; set; }
    }
```

### Expected Behavior

I was expecting to get a validation error on clicking submit as the file is required.

**Comment by MackinnonBuck** [comment] 2024-03-21 16:48
Without looking into it deeply, here are two possible causes of the issue:
* The `FileUpload` property is being assigned a non-null value to represent an "empty" file
* Data annotations validation does not happen for `InputFile`

See https://github.com/dotnet/aspnetcore/blob/main/src/Components/Endpoints/src/FormMapping/Converters/FileConverter.cs

Marking this as `investigate` so a member of the team can look into it further.

**Comment by SteveSandersonMS** [comment] 2024-03-21 17:06
@darena-pjindal Sorry for the inconvenience! We tracked this down. The issue is that when the form is submitted, if it contains no information at all, then `[SupplyParameterFromForm]` overwrites your `vm` value with `null`. And then there's an exception because you're trying to use `null` as the `Model` on your `EditForm`, which is not allowed.

Fortunately it's quite easy to fix this in your code. Just replace this:

```cs
[SupplyParameterFromForm(FormName = "FileUpload")]
private FileUploadVm vm { get; set; } = new();
```

... with this:

```cs
[SupplyParameterFromForm(FormName = "FileUpload")]
private FileUploadVm vm { get; set; } = default!;

protected override void OnInitialized()
{
    vm ??= new();
}
```

... and now everything should work as you want.

**Comment by darena-pjindal** [comment] 2024-03-21 17:23
@SteveSandersonMS & @MackinnonBuck  - thank you so much for your response! That worked.

**Closed** 2024-03-22 20:07 UTC
Labels: area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved
