### ISSUE TITLE
When can we have a great hotreload experience like flutter

### ISSUE THREAD

**Issue by ioer2008** [dotnet/aspnetcore#25436] opened 2020-08-31 08:13 UTC
In my current project, for any small modification, I need to click build, wait and refresh the web page to see the modification results.I think such development efficiency is too low.
If you have tried to develop with flutter, you will imagine what a great experience if blazor also has a similar hotreload.I believe that if this step can be achieved, it will be a major milestone.

我在目前进行的项目中,任何一个小的修改,都需要点击生成,等待并刷新网页,才能看到修改结果,我认为这样的开发效率太低了.
如果你试过使用flutter开发,你就会想象如果blazor也有类似的hotreload,将会是多么棒的一个体验,我相信如果可以做到这一步,将会是一个重大的里程碑.

**Comment by mkArtakMSFT** [comment] 2020-08-31 16:27
Thanks for contacting us. This is a dupe of #5456

**Closed by mkArtakMSFT** 2020-08-31 16:27 UTC
Labels: area-blazor, enhancement
