### ISSUE TITLE
File nesting: include rules in NuGet packages or as project items

### ISSUE THREAD

**Issue by gfraiteur** [dotnet/aspnetcore#40652] opened 2022-02-25 13:15 UTC
## Summary

A package author could include VS file nesting rules in the package so that all project that reference this package will have these rules enabled without further user intervention.

## User Impact

* Users of third-party packages do not need to configure file nesting manually.

## Example use case

In [Metalama testing framework](https://doc.metalama.net/aspects/testing/compile-time-testing), every test is a series of files. The main file has the `Foo.cs` extension, and dependent files have different extensions, e.g. `Foo.t.cs`, `Foo.t.txt`, `Foo.Aspects.cs` and so on.

**Comment by tmeschter** [comment] 2022-03-11 00:29
@AngelosP Moving to ASP.NET Core as you are working on the design of the File Nesting feature.

**Comment by javiercn** [comment] 2022-03-11 11:16
@AngelosP feel free to move this where it belongs, I don't think this is a runtime issue, so we shouldn't track it here.

**Comment by Pilchie** [comment] 2022-03-17 21:44
@vijayrkn @AngelosP @sayedihashimi ?

**Comment by sayedihashimi** [comment] 2022-03-17 21:57
I think file nesting is owned by the core project system. @vijayrkn knows.

**Comment by AngelosP** [comment] 2022-03-17 22:40
Interesting! Cool request :)

So my understanding is that the feature is now owned by CPS, even though it was designed and implemented originally by the Web Tools team. I'd happily move it over to our Web Tools backlog, but I'm not sure it would get picked up if I do that. 

On the other hand, file nesting is the most useful for web scenarios and most of the customers who find this useful will probably be ASP.NET devs and NuGet pckg authors. So maybe from that point of view who owns the feature doesn't really make that much of a difference.

@vijayrkn what do you think is the best way forward here? Should I create a Feedback ticket for this and let it take its natural flow through that process?

**Comment by vijayrkn** [comment] 2022-03-17 23:34
Yes, Feedback Suggestion request would be best since it can be assigned to the right team.

**Comment by Pilchie** [comment] 2022-03-23 19:53
@AngelosP - are you going to enter the feedback ticket?

**Comment by AngelosP** [comment] 2022-03-24 19:54
https://developercommunity.visualstudio.com/t/File-nesting:-include-rules-in-NuGet-pac/1702508?space=8&q=%5Bweb-tools-roadmap%5D&ftype=idea&stateGroup=active&entry=myfeedback

**Closed by AngelosP** 2022-03-24 19:54 UTC
Labels: External

**Comment by gfraiteur** [comment] 2022-03-24 20:49
I confirm I could include nesting rules in the NuGet package using the DependentUpon trick, so the case is closed for me too.
