### ISSUE TITLE
Microsoft.AspNetCore.Components.WebAssembly @ 6.0.0 offered by NuGet for .NET 5 project

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/aspnetcore#38256] opened 2021-11-10 14:01 UTC
Visual Studio 2019 @ 16.11.6 is offering the following v6.0.0 updates for my .NET 5.0-based Blazor WebAssembly solution:-

* Microsoft.AspNetCore.Components.WebAssembly
* Microsoft.AspNetCore.Components.WebAssembly.DevServer
* Microsoft.AspNetCore.Components.WebAssembly.Server

despite the fact that NuGet is telling me that they have (and especially the first in my list has) dependency on `net6.0`.

Surely that can't be right...?

![net60](https://user-images.githubusercontent.com/3470891/141126815-bbed10cc-c8aa-404b-be8f-6972e66f88b3.png)

**Comment by Bellarmine-Head** [comment] 2021-11-10 14:36
> Surely that can't be right...?

If it is right - or at least okayish - what will happen if I go ahead with the update?

**Comment by javiercn** [comment] 2021-11-10 14:44
@Bellarmine-Head thanks for contacting us.

I suspect either the installation will fail or the TFM will get updated, but I doubt the result will be what you expect. It's not clear to me why the Nuget UI is suggesting the update.

**Comment by Bellarmine-Head** [comment] 2021-11-11 15:15
We don't want v6.0.0 offerings blocking genuine 5.*.* updates to the listed 5.0.11 packages in the future.

**Comment by javiercn** [comment] 2021-11-12 14:18
@Bellarmine-Head I'm not super familiar with the nuget UI, but I believe you can pick the version.

AFAIK the UI offers the latest package. I would suggest you open an issue in the nuget repo as they will be able to offer more help.

**Comment by javiercn** [comment] 2021-11-12 14:28
/cc: @pranavkm in case you have any thoughts.

closing as there's nothing for us to do here.

**Comment by javiercn** [comment] 2021-11-12 15:33
@dotnet/aspnet-build do you have any thoughts here?

**Comment by Bellarmine-Head** [comment] 2021-11-12 15:36
@javiercn You were right, it's a NugGet issue: https://github.com/NuGet/Home/issues/11372

I'm dumbfounded that this problem even exists in 2021.

**Comment by Bellarmine-Head** [comment] 2021-11-12 15:38
How has the NuGet deficiency not brought the .NET world to its knees by now?

**Comment by javiercn** [comment] 2021-11-12 15:38
@Bellarmine-Head thanks for the additional details.

Closing as the problem is external.

**Closed by javiercn** 2021-11-12 15:38 UTC
Labels: External

**Comment by joemey** [comment] 2021-11-12 16:01
@javiercn
> Closing as the problem is external.

I disagree that this is a NuGet problem, because NuGet never supported filtering by Version AND TFM for package updates. Maybe this was planed, but it never happend.

This problem here is how the ASP.NET team is using NuGet in a not supported way, which (again) breaks package updates for old projects. 

(as you can see from the refrenced nuget issue, the problem is rather old (4 years) and has been ignored by the nuget team)

**Comment by Bellarmine-Head** [comment] 2021-11-12 16:27
> This problem here is how the ASP.NET team is using NuGet in a not supported way, which (again) breaks package updates for old projects.

If you're right, this could be wider than just the ASP.NET team.

From my screenshot:-

* System.Net.Http.Json

And from here https://github.com/NuGet/Home/issues/11372#issue-1049427850 

* Microsoft.EntityFrameworkCore*

i.e. at least three packages that (I believe) fall outside the purview of the ASP.NET team also suffer from this update problem.
