### ISSUE TITLE
Support enumarable of RenderFragment and RenderFragment<T> in components

### ISSUE THREAD

**Issue by montyclt** [dotnet/aspnetcore#29495] opened 2021-01-21 14:34 UTC
### Is your feature request related to a problem? Please describe.
Support enumarable of `RenderFragment` and `RenderFragment<T>` in components.

### Describe the solution you'd like
List.razor:
```razor
<ul>
    @foreach (var item in Items)
    {
        <li>@item</li>
    }
</ul>

@code {
    [Parameter(Tag = "Item")]
    public IEnumerable<RenderFragment> Items { get; set; }
}
```

Page.razor:
```razor
<List>
    <Item>Item 1</Item>
    <Item>Item 2</Item>
    <Item>Item 3</Item>
</List>
```

### Additional context
Enumerables members usually are written in plural form, but in the usage, the singular form is more accurate. I propose add a parameter in `[Parameter]` attribute to specify the tag. This proposal should be available to any parameter like this:

Person.razor
```csharp
[Parameter(Tag = "Name")]
public string FullName { get; set; }
```

Page.razor
```razor
<Person Name="Ivan" />
```

**Comment by SteveSandersonMS** [comment] 2021-01-26 17:17
I think this is a subset of the request in #29379 where we've done more design and analysis, so I'll close as a duplicate of that.

**Closed by SteveSandersonMS** 2021-01-26 17:17 UTC
Labels: area-blazor, enhancement
