### ISSUE TITLE
Dynamic EditForm composition

### ISSUE THREAD

**Issue by yopez83** [dotnet/aspnetcore#19550] opened 2020-03-04 02:53 UTC
### Goal
To compose an EditForm base of a dynamic Model, which properties at given at runtime.

### Customer.razor
``` C#
@page "/customer"
@using System.Dynamic
@using Newtonsoft.Json

    <EditForm Model="Customer" OnValidSubmit="Submit">
        @foreach (var key in ((IDictionary<string, object>)Customer).Keys)
        {
            <div class="form-group">
                <label for="@key.ToLower()">@key:</label>
                <InputText id="@key.ToLower()" @bind-Value="(how-do-I-bind-here)" />
            </div>
        }

        <button type="submit" class="btn btn-primary">Process</button>
    </EditForm>

@code {
    protected override Task OnInitializedAsync()
    {
        var modelDictionary = (IDictionary<string, object>)Customer;
        modelDictionary.Add("Name", "");
        modelDictionary.Add("Street", "");
        modelDictionary.Add("City", "");
        
        return base.OnInitializedAsync();
    }

    public void Submit(dynamic customer)
    {
        Console.WriteLine(JsonConvert.SerializeObject(customer));
    }

    private dynamic Customer = new ExpandoObject();

}
```

### Key point
- How to properly bind to the dynamic property?

**Comment by javiercn** [comment] 2020-03-04 12:11
@yopez83 thanks for contacting us.

I don't think this is a feature that we have. @SteveSandersonMS am I wrong?

**Comment by GeraudFabien** [comment] 2020-03-04 12:56
Maybe you could use an ObservableCollection<string, string>(). This way you can add you're field and raise stateHasChanged.
I personally won't use ObservableCollection<string, string>() but somethinks like ObservableCollection<IEditField>(). IEditField would allow you to add custom type and so custom design for futur type you may need. So for instance you would have a class ShortTextEditField. You can also have a NumberEditField who may inherit from ShortTextEditField. So it would work. And with thinks like [this](https://blog.stevensanderson.com/2019/09/04/blazor-fluentvalidation/) it would handle the case where the user didn't fill with a number.

Is there any case where dynamic is useful here ?

**Comment by SteveSandersonMS** [comment] 2020-03-04 15:21
If I understand the question correctly, it's a duplicate of #14006, which also contains a code sample showing how it can be done.

**Comment by yopez83** [comment] 2020-03-04 16:28
Thank you all for your input. @SteveSandersonMS in #14006 says it will be supported in the near future. Is there a time frame?

**Comment by SteveSandersonMS** [comment] 2020-03-04 16:59
> says it will be supported in the near future. Is there a time frame?

Where does it say something will be supported?

**Comment by yopez83** [comment] 2020-03-04 17:17
@SteveSandersonMS my bad. It says the “will not”.

**Closed** 2020-03-04 17:31 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
