### ISSUE TITLE
dotnet-sdk-3.1.406-win-x64 failed to install, always

### ISSUE THREAD

**Issue by EricOuellet2** [dotnet/aspnetcore#30484] opened 2021-02-25 19:17 UTC
### Description

Always getting error :

[4E6C:35F0][2021-02-25T14:08:15]e000: Error 0x80070002: Failed to find payload: AspNetCoreSharedFramework_x64 in working path: C:\LOCAL\TEMP\{C8B06F83-D0BD-4A3C-86FF-E0115FE762B4}\AspNetCoreSharedFramework_x64 and unverified path: C:\ProgramData\Package Cache\.unverified\AspNetCoreSharedFramework_x64
[4E6C:35F0][2021-02-25T14:08:15]e000: Error 0x80070002: Failed to cache payload: AspNetCoreSharedFramework_x64

I expect to install without any fuss.

### Configuration

Windows 10 1803. Visual Studio 2019 latest. 
I do have Asp.Net development selected in VS2019 installation.

### Regression?

???

### Other information

Log included
[Microsoft_.NET_Core_SDK_3.1.406_(x64)_20210225140807.log](https://github.com/dotnet/runtime/files/6045245/Microsoft_.NET_Core_SDK_3.1.406_.x64._20210225140807.log)

**Comment by danmoseley** [comment] 2021-02-26 05:52
Thanks @wli3. transferring there.

**Comment by danmoseley** [comment] 2021-02-26 05:55
sounds like https://github.com/dotnet/aspnetcore/issues/28029 which looks like it has a fix https://github.com/dotnet/aspnetcore/pull/30439 schedule for 3.1.14. (April)
perhaps they can help with a workaround meantime.

**Comment by javiercn** [comment] 2021-02-26 10:19
@EricOuellet2 thanks for reporting this.

@dotnet/aspnet-build folks, can you check this out?

/cc: @Pilchie

**Comment by Pilchie** [comment] 2021-02-26 17:00
@wtgodbe checked in the fix, and @joeloff was looking for workaround.

**Comment by dougbu** [comment] 2021-02-26 18:54
> help with a workaround meantime

@wtgodbe @joeloff is there a way to work around this issue prior to the April 3.1.14 release❔

**Comment by joeloff** [comment] 2021-02-26 20:05
@EricOuellet2 can you provide this log file: C:\LOCAL\TEMP\Microsoft_.NET_Core_SDK_3.1.406_(x64)_20210225140807_014_AspNetCoreSharedFramework_x64.log

**Comment by EricOuellet2** [comment] 2021-02-26 20:11
[Microsoft_.NET_Core_SDK_3.1.406_(x64)_20210225140807_014_AspNetCoreSharedFramework_x64.log](https://github.com/dotnet/aspnetcore/files/6052222/Microsoft_.NET_Core_SDK_3.1.406_.x64._20210225140807_014_AspNetCoreSharedFramework_x64.log)

This is it

**Comment by joeloff** [comment] 2021-02-26 20:15
This looks like the SEC REPAIR issue we're fixing for the next release where it's conflicting with the original source location of the install from VS.

@EricOuellet2 You can try the following from a commandline: <SDK.EXE> /install OPT_NO_SHAREDFX=1

**Comment by EricOuellet2** [comment] 2021-02-26 20:26
Still failed.

[Microsoft_.NET_Core_SDK_3.1.406_(x64)_20210226152123.log](https://github.com/dotnet/aspnetcore/files/6052309/Microsoft_.NET_Core_SDK_3.1.406_.x64._20210226152123.log)
[Microsoft_.NET_Core_SDK_3.1.406_(x64)_20210226152123_014_AspNetCoreSharedFramework_x64.log](https://github.com/dotnet/aspnetcore/files/6052310/Microsoft_.NET_Core_SDK_3.1.406_.x64._20210226152123_014_AspNetCoreSharedFramework_x64.log)

**Comment by EricOuellet2** [comment] 2021-02-26 20:27
Just want to mention. It is an update, not a new installation.

**Comment by joeloff** [comment] 2021-02-26 23:19
Thanks @EricOuellet2 Let me see if there's another option. The problem is with a file that was renamed, and even though it's the binary equivalent to the copy that VS might have, the installer service has a hard check against the original source.

Let me see if I can find you a workaround

**Comment by dougbu** [comment] 2021-06-22 22:22
@joeloff @wtgodbe didn't we _just_ fix the repair issue w/ the runtime MSI❔ I think that would mean the fix is coming on Patch Tuesday in July&hellip;

If that's the case, this bug be marked as a duplicate of #33572 Please do the needful

**Comment by dougbu** [comment] 2022-01-19 23:13
Dupe of #33572

**Closed by dougbu** 2022-01-19 23:13 UTC
Labels: area-infrastructure, feature-installers
