### ISSUE TITLE
CORS validate does not work when visiting from Private Browse model 

### ISSUE THREAD

**Issue by xboxeer** [dotnet/aspnetcore#23004] opened 2020-06-16 15:52 UTC
### Describe the bug
We have a user who is building an SPA application, he is using cors middleware and everything works fine, however if the request comes from a Private Browsing mode session, Access-Control-Allow-Origin header is not set, which result to the CORS validate always fails, for this kind of senario, can we add support or this is an impossible requirement? 

### Exceptions (if any)

Access to XMLHttpRequest at 'x' from origin 'y' has been blocked by CORS policy:
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
- Source link: https://stackoverflow.com/questions/62351108/signalr-throws-no-access-control-allow-origin-header-error-when-using-a-brow

**Comment by BrennanConroy** [comment] 2020-06-17 20:11
Could you share your network trace please?
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#collect-a-network-trace-in-the-browser

Also, is this a browser specific issue?

**Comment by halter73** [comment] 2020-06-17 20:26
@pranavkm Could it be that Edge/Chrome isn't setting an 'Origin' header when in private browsing mode?

I think CorsMiddleware won't respond with an 'Access-Control-Allow-Origin' if there's no 'Origin' request header, but there should be an option to to send `Access-Control-Allow-Origin: <configured origins>` regardless of the presence of the 'Origin' if browsers are starting to not send the 'Origin' header for cross-origin requests when in private browsing mode.

**Comment by pranavkm** [comment] 2020-06-17 20:55
> if browsers are starting to not send the 'Origin' header for cross-origin requests when in private browsing mode.

That's the first I've heard of browsers doing this. I just tried it with Chrome v83, Edgium v83. and Firefox v77, and they appear to be sending the Origin header just fine in private browsing. Perhaps the app has CORS appear after auth which explain why going to private browsing results in a cors error.

**Comment by halter73** [comment] 2020-06-18 00:01
> That's the first I've heard of browsers doing this.

Browsers very well might **not** be doing this. I'm just making a wild guess. We should wait for a network trace so we know for sure what's going on.

> Perhaps the app has CORS appear after auth which explain why going to private browsing results in a cors error.

So if I understand this right, calling UseCors() after UseAuthn()/UseAuthz() could also cause this issue in private browsing mode if UseAuthorization() rejects the request before the CorsMiddleware has a chance to add the Access-Control-Allow-Origin header.

This *does* seem way more likely. Could this be what's going on @xboxeer? Can you share a copy of your Startup class?

**Comment by xboxeer** [comment] 2020-06-21 16:31
@halter73 very appreciate for your inputs, I'll confirm with customer, meanwhile the sequence of UseCors and UseAuthn seems not mentioned in docs and never though this would cause such an issue, is it by design?

**Comment by halter73** [comment] 2020-06-22 20:33
It is by design.

> Calls the UseCors extension method and specifies the _myAllowSpecificOrigins CORS policy. UseCors adds the CORS middleware. The call to UseCors must be placed after UseRouting, but before UseAuthorization. For more information, see Middleware order.

https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#cors-with-named-policy-and-middleware

> Not every middleware needs to go in this exact order, but many do. For example, UseCors, UseAuthentication, and UseAuthorization must go in the order shown.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order

If you were looking for this in another section of the docs, maybe we should call it out there too. There's an "edit" link on our docs that point to the corresponding markdown file in https://github.com/dotnet/AspNetCore.Docs/ so anyone can submit PRs to improve docs.

**Comment by javiercn** [comment] 2020-06-23 11:53
@halter73 thanks for digging into this.

I'm closing this issue since the behavior is by design.

**Closed by javiercn** 2020-06-23 11:53 UTC
Labels: Needs: Author Feedback, area-mvc, area-signalr
