### ISSUE TITLE
.Net 8 Blazor Web hot reload not working

### ISSUE THREAD

**Issue by Edemilorhea** [dotnet/aspnetcore#52596] opened 2023-12-06 04:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the .Net 8 Blazor Web app project. In the past, when I was using the .Net 7 blazor Webassembly Hosted project, I wrote a script to start dotnet watch in Vscode for debugging, and hot reload could be performed smoothly. However, currently Web app uses the same method but cannot re-render smoothly

As shown in the picture below, I have copied two H1tags. When saving the file, the hot reload successful icon will appear in the upper left corner of the web page, but in fact the page is not re-rendered, and the log record also shows updates that do not require hot reload.

But when using Visual Studio, hot reload can indeed be run smoothly.

![image](https://github.com/dotnet/aspnetcore/assets/92776711/b15c70af-ba1a-412e-af8d-c1d698ea31ea)
![image](https://github.com/dotnet/aspnetcore/assets/92776711/00e13754-3927-4a67-9450-a463a59c125c)

![image](https://github.com/dotnet/aspnetcore/assets/92776711/2671687e-3a40-4962-bb00-e5f88fb78459)

### Expected Behavior

Using Vscode hopes to provide a better debugging method that can hot reload and break points. It doesn't matter even if you have to write your own script, but now it has no effect.

### .NET Version

8.0.100

**Comment by tmat** [comment] 2023-12-06 20:00
Could you please set environment variable `Microsoft_CodeAnalysis_EditAndContinue_LogDir` to `%tmp%\HotReload`, run dotnet-watch, reproduce the issue and then share the log directory?

**Comment by Edemilorhea** [comment] 2023-12-07 08:55
> Could you please set environment variable `Microsoft_CodeAnalysis_EditAndContinue_LogDir` to `%temp%\HotReload`, run dotnet-watch, reproduce the issue and then share the log directory?

I did what you said. I set the environment variables on the launched launch.json, but I changed it to the C disk.


This is the content of the vscode debug startup file
![image](https://github.com/dotnet/aspnetcore/assets/92776711/9ebd94f8-e423-4c40-866c-4d06cfaf4efd)



This is the changed content. I just copied two more ht tags.
![image](https://github.com/dotnet/aspnetcore/assets/92776711/20e4df7f-0421-47cc-aa46-aeaa1adeb7d5)

![image](https://github.com/dotnet/aspnetcore/assets/92776711/f55e6655-3ddc-4366-a143-7d0736d05609)

This is the output Console and file.
![image](https://github.com/dotnet/aspnetcore/assets/92776711/394b64a4-d702-49b3-8443-40d2ea394afc)

![image](https://github.com/dotnet/aspnetcore/assets/92776711/f6444008-0890-435e-88d9-5232d55ca41c)

**Comment by tmat** [comment] 2023-12-07 17:35
Based on the message "Checksum differs for source file ... AssemblyInfo.cs" I think you might be hitting https://github.com/dotnet/sdk/issues/36666. This is fixed in 8.0.1.

Could you please share the content of the log directory? If you don't want to do so publicly feel free to file VS Feedback ticket: https://developercommunity.visualstudio.com/home

**Comment by Edemilorhea** [comment] 2023-12-08 02:15
> Based on the message "Checksum differs for source file ... AssemblyInfo.cs" I think you might be hitting [dotnet/sdk#36666](https://github.com/dotnet/sdk/issues/36666). This is fixed in 8.0.1.
> 
> Could you please share the content of the log directory? If you don't want to do so publicly feel free to file VS Feedback ticket: https://developercommunity.visualstudio.com/home

![image](https://github.com/dotnet/aspnetcore/assets/92776711/af10721e-8795-405d-9135-b0af2a313e36)

You just need this? 
Cause I already changed the log path.

**Comment by Edemilorhea** [comment] 2023-12-08 06:52
> Based on the message "Checksum differs for source file ... AssemblyInfo.cs" I think you might be hitting [dotnet/sdk#36666](https://github.com/dotnet/sdk/issues/36666). This is fixed in 8.0.1.
> 
> Could you please share the content of the log directory? If you don't want to do so publicly feel free to file VS Feedback ticket: https://developercommunity.visualstudio.com/home

Sorry, I re-read the new hot reloading of Vscode today. It says that C# dev kit currently only supports hot reloading of *.Cs, but in the past, if the startup item started coreclr dotnet watch through a command, it should be I am able to hot reload the Blazor screen. I would like to ask if these things are correct.

**Comment by mkArtakMSFT** [comment] 2024-01-02 17:10
@tmat where should this issue move to? dotnet/razor ?

**Comment by tmat** [comment] 2024-02-03 01:52
[Edemilorhea](https://github.com/Edemilorhea) 
I tried the following project with .NET SDK 8.0.101 and it works fine:
[BlazorWebApp.zip](https://github.com/dotnet/aspnetcore/files/14149051/BlazorWebApp.zip)

Based on this screenshot, it seems that the issue is indeed https://github.com/dotnet/sdk/issues/36666, which was intermittent and might not repro every time.
![image](https://github.com/dotnet/aspnetcore/assets/41759/147a443c-242a-4c56-a7e0-ddbefcf7685b)

Please, try 8.0.200-preview.23604.9 and if you still run into a problem open a new issue.

**Closed by tmat** 2024-02-03 01:52 UTC
Labels: investigate, area-blazor, feature-dotnetwatch, triaged
