### ISSUE TITLE
.Net9 Dev Bug adout MapStaticAssets :  "System.InvalidOperationException: The file '_framework/blazor.boot.json.gz' could not be found."

### ISSUE THREAD

**Issue by QingYuMuYu** [dotnet/aspnetcore#57725] opened 2024-09-06 08:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using vs2022's. net9 to build the default template project for the blazor app, I only added two lines of code to the "Counter. razor" file under the "BlazorApp1. Client" project, and then ran it. When I clicked on the "Counter" tab of the sample project, it prompted"System.InvalidOperationException: The file '_framework/blazor.boot.json.gz' could not be found."

[modify]
<img width="917" alt="1" src="https://github.com/user-attachments/assets/089bd817-0da1-4933-8df8-eb14866e8c63">

[error]
<img width="721" alt="2" src="https://github.com/user-attachments/assets/15ba5a49-981c-499b-b87d-b2506ef9d894">

English is not my native language, I don't know if it expresses clearing, but this is easy to reproduce, and the problem will automatically disappear when regenerated

### .NET Version

9.0.100-preview.7.24407.12

**Comment by javiercn** [comment] 2024-09-06 11:11
@QingYuMuYu thanks for contacting us.

This is a problem with Accelerated builds in Visual Studio. You can use `<AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>` to work around the issue.

**Comment by javiercn** [comment] 2024-09-06 11:12
Dupe of https://github.com/dotnet/AspNetCore-ManualTests/issues/2972

**Closed by javiercn** 2024-09-06 11:12 UTC
Labels: area-blazor

**Comment by javiercn** [comment] 2024-09-06 11:14
Fix for 9.0 is [here](https://github.com/dotnet/sdk/pull/43156)
