### ISSUE TITLE
Identity database scaffolding

### ISSUE THREAD

**Issue by Maraud3r** [dotnet/aspnetcore#46970] opened 2023-03-02 01:42 UTC
I have spent a fair number of hours today trying to scaffold the identity database without having a bunch of UI code generated that I don’t need.

Does anybody have examples of generating the database without UI code?

Ideally if I could generate it into a WebAPI project that would be great.

**Comment by captainsafia** [comment] 2023-03-02 19:37
> Does anybody have examples of generating the database without UI code?

What are you currently doing to generate the scaffold? Are you generating the scaffolding then removing the UI or are you starting from scratch by invoking `AddIdentityCore` in your application?

**Comment by Maraud3r** [comment] 2023-03-02 21:37
> > Does anybody have examples of generating the database without UI code?
> 
> What are you currently doing to generate the scaffold? Are you generating the scaffolding then removing the UI or are you starting from scratch by invoking `AddIdentityCore` in your application?

All the documentation I have read says to do it via the VS2022 interface.

Is AddIdentityCore a dotnet command or something I run at the package manager console ?

If you could point me at some documentation for it they would be great.

Thanks

**Comment by captainsafia** [comment] 2023-03-09 05:21
> Is AddIdentityCore a dotnet command or something I run at the package manager console ?

`AddIdentityCore` is an extension method that registers Identity-related services into your application. You can view the API docs [here[(https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.identityservicecollectionextensions.addidentitycore?view=aspnetcore-7.0). We were assuming that you were calling the individual APIs directly in your app.

Unfortunately, we don't have docs on the identity layer yet. This is being tracked [here](https://github.com/dotnet/AspNetCore.Docs/issues/15374)).

**Comment by halter73** [comment] 2023-03-30 17:13
This MVC sample shows how to use `AddIdentityCore`. The sample also winds up including all the default UI code in the Account and Manage views, but that isn't necessary.

https://github.com/dotnet/aspnetcore/blob/83728cac8c2feb5b81f2402c3d83c32f9239c22c/src/Identity/samples/IdentitySample.Mvc/Startup.cs#L28-L52

And then you should be able to apply migrations like you normally would https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=netcore-cli#apply-migrations using something like `dotnet ef database update`.

I think we should probably close this issue as a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/15374.

**Closed** 2023-04-05 19:00 UTC
Labels: area-identity, :heavy_check_mark: Resolution: Answered, Status: Resolved
