### ISSUE TITLE
Error while adding WSDL service Asp.net Core 3.1 web api

### ISSUE THREAD

**Issue by kuntalbose** [dotnet/aspnetcore#21395] opened 2020-05-01 10:41 UTC
I am trying to add a service in a .net core 3.1 application with **Microsoft Visual Studio Community 2019 Version 16.4.6** .I share my steps with screen shots.

The following is from **.csproj**

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>


</Project>
```

**Step 1**
![image](https://user-images.githubusercontent.com/7402233/80788699-75c70d00-8ba7-11ea-97cb-f10cad472d9a.png)

**Step 2**
![image](https://user-images.githubusercontent.com/7402233/80788812-cd657880-8ba7-11ea-8479-6f6b57557ec2.png)

**Step 3**

![image](https://user-images.githubusercontent.com/7402233/80788880-fede4400-8ba7-11ea-8a27-1661a038b8ad.png)

**Step 4**

![image](https://user-images.githubusercontent.com/7402233/80788946-36e58700-8ba8-11ea-9dce-0ba1d7d56d71.png)

**Step 5**

![image](https://user-images.githubusercontent.com/7402233/80789031-74e2ab00-8ba8-11ea-9f6d-afa2f5e5920b.png)

**Comment by Pilchie** [comment] 2020-05-01 15:39
@vijayrkn - where should this go?

**Comment by vijayrkn** [comment] 2020-05-01 15:42
@kuntalbose - This is a Visual Studio issue. Can you please report the issue as mentioned here - https://developercommunity.visualstudio.com/content/problem/post.html?space=8. 

This will help us route to the right team and provide the required diagnostic information to investigate this further.

**Comment by Pilchie** [comment] 2020-05-01 15:45
Closing as external.

**Closed by Pilchie** 2020-05-01 15:45 UTC
Labels: External

**Comment by KamranShahid** [comment] 2020-05-02 18:16
Try same wsdl https://ws.jobdiva.com/axis2/services/BIData?wsdl from WCF test client. 
Some time there are things in wsdl due to which they can't be referenced.
Also then try same wsdl from soapui

**Comment by KamranShahid** [comment] 2020-05-02 18:18
Following is the error when tried same wsdl from wcf test client

Error: Cannot obtain Metadata from https://ws.jobdiva.com/axis2/services/BIData?wsdl 
If this is a Windows (R) Communication Foundation service to which you have access, 
please check that you have enabled metadata publishing at the specified address.  
For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.WS-Metadata Exchange Error 
   URI: https://ws.jobdiva.com/axis2/services/BIData?wsdl  
   Metadata contains a reference that cannot be resolved: 'https://ws.jobdiva.com/axis2/services/BIData?wsdl'.   
   An error occurred while making the HTTP request to https://ws.jobdiva.com/axis2/services/BIData?wsdl. T
   his could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. 
   This could also be caused by a mismatch of the security binding between the client and the server.   
   The underlying connection was closed: An unexpected error occurred on a send.   
   Received an unexpected EOF or 0 bytes from the transport stream.HTTP GET Error 
   URI: https://ws.jobdiva.com/axis2/services/BIData?wsdl  
   There was an error downloading 'https://ws.jobdiva.com/axis2/services/BIData?wsdl'. 
   The underlying connection was closed: An unexpected error occurred on a send.    Received an unexpected EOF or 0 bytes from the transport stream.
