### ISSUE TITLE
Adding an openapi  service reference to a rest client doesn't work, if you have a space in your project path

### ISSUE THREAD

**Issue by Agakhan** [dotnet/aspnetcore#27198] opened 2020-10-24 18:30 UTC
Using: Visual Studio Community Edition  Preview 16.8.0, ASP.Net.Core RC2

To reproduce the bug, your directory for all projects must include a space, e.g. <b>"C:\SEG\Ediline 3.0"</b>

1) Create a Webapi procect und generate the swagger.json file.
2) Add a console application and add a service reference to your app, based on the generated swagger.json
3) If you check the automated generated code for the referenced service, the code will be missing but you haven't got any error messages during adding the reference.

**Comment by captainsafia** [comment] 2021-10-05 17:08
@Agakhan It looks like your issue might be a dupe of https://github.com/dotnet/aspnetcore/issues/33463 which has been resolved. Can you try updating your NSwag dependency and see if that resolves the issue?

**Closed** 2021-11-03 01:02 UTC
Labels: bug, Needs: Author Feedback, feature-code-generation, Status: No Recent Activity, affected-few, severity-major, area-web-frameworks
