### ISSUE TITLE
Blazor layout file issue

### ISSUE THREAD

**Issue by aktxyz** [dotnet/aspnetcore#19892] opened 2020-03-16 17:31 UTC
First off ... blazor is a amazing and literally life changing :)

### Describe the bug

https://github.com/aktxyz/BlazorLayoutIssue

**Background**
Simple repo to show a blazor layout issue (or at least an annoyance).

Basically a Layout.razor file in the same directory as the _Imports.razor file ... gets the Layout attribute applied in the generated source ... and I think that is creating a infinite loop of some sort causing blazor to lock up and cpu to spike. I was hoping for a folder structure like ...

```
Pages/Section1/_Imports.razor - has @layout attr pointing to _Layout below
Pages/Section1/_Layout.razor
Pages/Section1/This/.... bunch of pages - all getting the _Layout above
Pages/Section1/That/.... bunch of pages - all getting the _Layout above
```

This fails ... and after digging a bit I think because the generated _Layout.razor.g.cs file actually has the [LayoutAttribute] applied, so a layout with layout, which seems wrong (a layout specifying a layout?).

I can always move the _Layout.razor up ... but that gets rid of the structure/nesting that keeps things clean.

There may be another reason for this all not working, but I played around quite a bit and ended up bailing on code and doing this sample.

**What would be nice ...**
treat _Layout.razor as a special name, like _Imports.razor ... and automatically apply to all child pages
do not apply [LayoutAttribute] to a component unless it has a @page directive ... right now even a non-page directive will the [LayoutAttribute] applied if a parent path _Imports.razor has a @layout directive (yes only pages should be under /Pages, but we don't always do that) ... this would keep non-page components from getting the attr and also prevent layouts from getting the attr

### To Reproduce
https://github.com/aktxyz/BlazorLayoutIssue

**Comment by javiercn** [comment] 2020-03-17 15:07
@aktxyz thanks for contacting us.

I think the behavior you are seeing is by design. The compilation process for the "_Imports.razor" might not be able to determine that a given razor file is a Layout and as a result it will blindly apply the directive (similarly to how it does to other files). 

A simple solution to this would be to separate your layouts into a different folder structure as that would allow you to apply them without issue.

**Comment by aktxyz** [comment] 2020-03-17 15:41
The separate folder structure certainly works ... just seems a shame to have to create another similar tree structure just for this.

Is there a reason that applying the Layout attribute to a component that does not have a Route attribute makes sense and is useful?  Maybe individual components can have layouts and I never realized that?

Or why not just exclude the magic filename _Imports.razor from the list of components that can get a layout attribute.

**Comment by aktxyz** [comment] 2020-03-17 15:43
Or perhaps consider another magic file _Layout.razor ... that automatigically applies to all components in the folder on down ... similar to how _Imports.razor is applied.

I have worked around it ... so not a big deal ... but tidying up the edges is always nice.

**Comment by mkArtakMSFT** [comment] 2020-03-17 16:40
Thanks @aktxyz.
Closing as there is no pending action for us here.

**Closed by mkArtakMSFT** 2020-03-17 16:40 UTC
Labels: area-blazor
