### ISSUE TITLE
Persistent issue with razor namespaces in Blazor Project

### ISSUE THREAD

**Issue by pochtaliot** [dotnet/aspnetcore#31792] opened 2021-04-14 08:01 UTC
Hi, what is about error when razor component (page) does not see reference to the own components (dialogs, tabs) that located in different folders. I can run project, but errors still showing. The only thing I need to do is to open particular dialog or tab component in VS and the error is gone. Same relates to losing App file namespace in Program.cs. I need to open files that contained in parent pages as own components and the errors are gone.

My pages located in ./Solution/BlazorProject/Pages/[CategorizedPageFolder]
My components located in ./Solution/BlazorProject/Components/[CategorizedComponentFolder]

VS 2019 version 4.8.04084
Projects target framework is .NET5

![2021-04-14_09h55_18](https://user-images.githubusercontent.com/8088197/114676048-2ff84b80-9d09-11eb-88d1-63f3439d28ed.png)

**Comment by NTaylorMullen** [comment] 2021-04-19 22:25
Thank you for your reported issue. We believe this issue will be fixed by our Razor tooling efforts in the .NET 6 time frame. If you'd like to try this tooling out you can download the latest VS preview release and check the following preview feature checkbox (Tools -> Options -> Environment -> Preview Features):

![image](https://user-images.githubusercontent.com/2008729/87990285-8b5a1d80-ca98-11ea-914f-949fa326d9e3.png)

If this issue has been closed and you're still encountering issues feel free to respond to still communicate via the issue and we'll re-open if needed.

Also, duplicate of: https://github.com/dotnet/aspnetcore/issues/17660

**Closed by NTaylorMullen** 2021-04-19 22:25 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, feature-razor.vs
