### ISSUE TITLE
System.ArgumentException: 'The path must be absolute.'

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35347] opened 2021-08-14 03:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemArgumentException:-The-path-must/1501186)._

---
[regression] [worked-in:Version 17.0.0 Preview 3.0]
The path must be absolute. (Parameter 'root')

at Microsoft.Extensions.FileProviders.PhysicalFileProvider.. ctor(String root, ExclusionFilters filters) in Microsoft.Extensions.FileProviders.Physical.dll:token 0x600001b+0x28
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.. ctor(String root) in Microsoft.Extensions.FileProviders.Physical.dll:token 0x600001a+0x0
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__2_1(String contentRoot) in Microsoft.AspNetCore.Hosting.dll:token 0x6000304+0x0
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.ManifestStaticWebAssetFileProvider.. ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory) in Microsoft.AspNetCore.Hosting.dll:token 0x60001bc+0x1d
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest, Boolean isJson) in Microsoft.AspNetCore.Hosting.dll:token 0x60001c5+0x22
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration) in Microsoft.AspNetCore.Hosting.dll:token 0x60001c4+0x19
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunConfigurationCallbacks() in Microsoft.AspNetCore.dll:token 0x6000075+0x39
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.. ctor(Assembly callingAssembly, String[] args) in Microsoft.AspNetCore.dll:token 0x600004a+0x98
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args) in Microsoft.AspNetCore.dll:token 0x600003d+0x0
   at <Program>$.<Main> $(String[] args) in C:\Demos\CatetIn\CatetIn\Server\Program.cs:line 3

---
#### Feedback Bot on 8/12/2021, 02:36 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-08-14 03:17
@javiercn is this Static Web Assets related?

**Comment by leo-costa** [comment] 2021-08-14 16:34
@mkArtakMSFT  I'm having the same problem as the person above. Using the default template `blazorserver`, from .net preview 7, doesn't work under visual studio 2019 16.11.0. Using `dotnet watch` everything works fine. So I assume it must be visual studio.  Inside the container it says `The path must be absolute` and when using kestrel it can't find `_Host`.

**Comment by javiercn** [comment] 2021-08-16 12:31
This is a dupe of https://github.com/dotnet/aspnetcore/issues/35285, we are already working with the docker team to update the tooling support.

**Closed** 2021-08-16 12:31 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-mvc, Author: Migration Bot :robot:, Status: Resolved
