### ISSUE TITLE
Webpack Live Reloading broke when I moved from VS 2019 version 16.7 / .NET 3.1 / Angular 10 to VS 2019 v.16.8 / .NET 5 / Angular 11

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28038] opened 2020-11-20 23:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Webpack-Live-Reloading-is-broken-in-VS-2/1256591?preview=true)._

---
<p>After I moved from VS 2019 version 16.7 / .NET Core 3.1 / Angular 10 to VS 2019 v.16.8 / .NET 5 / Angular 11 (which I will admit is a LOT of change), when starting my spa app from within Visual Studio using View in Browser from Solution Explorer, as the Angular application is starting up, the browser dev tools debug window does not report &quot;[WDS] Live Reloading enabled.&quot; and if a .ts or other file is modified in the Angular project, the browser doesn't hot reload the app.</p><p>Using the .NET 5 framework dotnet command line app to create a default .NET 5 Angular application -- it creates, currently, an Angular 8 application (the package.json file contains Angular 8.2.12 dependencies (side-note: Angular 8 was some time ago, the current version is Angular 11 -- perhaps the template should be updated).)</p><ul><li>with the default template .NET 5.0 / Angular application when run (browsed-to) from Visual Studio 16.8.0 / 1, the browser debug window does not report &quot;[WDS] Live Reloading enabled.&quot; and it is not enabled.</li><li>with the default template .NET 5.0 / Angular application when run (browsed-to) from Visual Studio 2019 prior to 16.8.0, or, it turns out, it can be run (browsed-to) from Visual 2017 as well, the browser debug window DOES report &quot;[WDS] Live Reloading enabled.&quot; and hot reload when a file is changed works as expected.</li></ul><p>[EDIT] After I created this problem report and kept trying different ideas it started to seem less like a Visual Studio specific issue and maybe more about the fact there are now websockets errors occurring as the app is starting up (see my comment below).</p>

---
#### Feedback Bot on 11/16/2020, 02:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Eric Nielsen on 11/17/2020, 04:39 PM: 

<p>At first, after moving to Angular 11, I was (and apparently plenty of others were) getting a host of ERR_SSL_PROTOCOL_ERROR's and that was, I guess, killing Live Reload.  https://github.com/angular/angular-cli/issues/19403 provides details.  That issue is resolved now with Angular 11.1 with Angular CLI 11.2.</p><p>Live Reload is still not working for me, however, and it appears to be tied to a different websockets error that happens as the browser is starting the spa app after a recycle: "WebSocket connection to 'wss://localhost:44300/sockjs-node/..../..../websocket' failed: WebSocket is closed before the connection is established."</p><p>If that error occurs, Live Reload won't work.  On occasions when the error does not occur, Live Reload does work.</p><p>There's something about sockjs-client, or calls into it that are outside my codebase, that is causing the error.</p><p>I'm now feeling that my issue report here is probably not very relevant for Visual Studio and if I knew how to delete it, I would.</p>

#### Feedback Bot on 11/19/2020, 01:08 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2020-11-20 23:40
Thanks for contacting us. This is a dupe of #27790

**Closed by mkArtakMSFT** 2020-11-20 23:40 UTC
Labels: Author: Migration Bot :robot:, area-websockets

**Comment by erictor** [comment] 2020-11-21 04:53
Thank you for your attention.  I already knew about #27790 and there's a comment from me on that one from four days ago.  There's also related and linked-to issue #19403 where I have a comment from 4 days ago with the following verbiage:

The ERR_SSL issue described here gets resolved now with Angular 11.1 / Angular CLI 11.2. However for me it did not resolve the other issue I've been experiencing which is that Live Reload is still getting killed because the error:

sockjs.js:2999 WebSocket connection to 'wss://localhost:44300/sockjs-node/.../websocket' failed: WebSocket is closed before the connection is established

This occurs for me nearly every time the browser reloads.

![WebsocketClosedBeforeTheConnectionEstablished](https://user-images.githubusercontent.com/13494060/99867840-1a279580-2b72-11eb-9535-82c86c8b8f6f.jpg)

I have updated to the latest Angular and Angular CLI, 11.0.2, and this error is occurring.  And the impact of the error is Live Reload does not work.

What is the proper procedure if I feel my concern wasn't resolved but the associated issue has been marked Resolved?
Thank you.
