### ISSUE TITLE
Trim unused code when publish will delete route controllers

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#56898] opened 2024-07-19 17:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Trim-unused-code-when-publish-will-delet/10702095)._

---
I notice that if i use (Trim unused code) when making publish, will cut all my created routes. Is possible to access swagger page to see that. Any request to route will cause 404 error.
Publish specs:
dotnet 8
self-contained
linux-arm64

---
#### Feedback Bot on 7/14/2024, 11:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2024-07-19 17:41
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/41767

**Closed by mkArtakMSFT** 2024-07-19 17:41 UTC
Labels: area-mvc, Author: Migration Bot :robot:
