### ISSUE TITLE
Blazor: Ability to set the JsonSerializerOptions.IgnoreNullValues property for JS Interop.

### ISSUE THREAD

**Issue by user72356** [dotnet/aspnetcore#27015] opened 2020-10-18 01:02 UTC
Blazor appears to have no mechanism to configure the global serialization/deserialization process when making JS Interop function calls. For instance I would like the ability to ignore null values, a facility provided by `System.Text.Json` via the [JsonSerializerOptions.IgnoreNullValues](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.ignorenullvalues?view=netcore-3.1#System_Text_Json_JsonSerializerOptions_IgnoreNullValues) property.

The only way today is to manually serialize my parameters before feeding them into `InvokeVoid`:

    var options = new JsonSerializerOptions
    {
        IgnoreNullValues = true
    };

    var arg = JsonSerializer.ToString<WeatherForecast>(value, options);

**Comment by mkArtakMSFT** [comment] 2020-10-19 16:29
Thanks for contacting us. This is a dupe of #12685
If you want, you can serialize the value as a string and send that (as a JSON object).

**Closed by mkArtakMSFT** 2020-10-19 16:29 UTC
Labels: area-blazor
