### ISSUE TITLE
Can you reopen my issue 44088 ?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [dotnet/aspnetcore#45107] opened 2022-11-15 15:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I provided a repro, edited the old post, wrote (new activity) a new message mentioning MSFT employee and @msftbot was still adamant on closing it!
 
https://github.com/dotnet/aspnetcore/issues/44088

### Expected Behavior

@msftbot does not close my issue due to lack of activity

### Steps To Reproduce

Find a runtime breaking bug that precludes C# WASM from use in production environments as a library invoked by JS/TS and watch your issue get closed by a bot

### .NET Version

irrelevant

**Comment by javiercn** [comment] 2022-11-15 16:09
@devshgraphicsprogramming Thanks for contacting us.

Our general interop mechanism is not designed to pass around large amounts of data, so it is not surprising that passing a 1MB array is slow compared to other approaches.

We do have an alternative (webassembly only) interop mechanism available in .NET 7.0 that we suggest you try. That should give you performance closer to what you expect.

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0

**Comment by mkArtakMSFT** [comment] 2022-11-15 17:33
Closed as a dupe of the linked issue.

**Closed by mkArtakMSFT** 2022-11-15 17:33 UTC
Labels: area-blazor
