### ISSUE TITLE
Visual Studio hangs for long periods and frequesntly crashes while typing in a razor file in a large Blazor project

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22968] opened 2020-06-15 20:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1076037/visual-studio-hangs-for-long-periods-and-frequesnt.html)._

---
Long pauses while typging in a razor file in a BlazoVisual Studio hangs for long periods and frequesntly crashes while typing in a razor file in a large Blazor project project

---
#### Visual Studio Feedback System on 6/15/2020, 00:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2020-06-15 20:15
Duplicate of https://github.com/dotnet/aspnetcore/issues/22276

**Closed by NTaylorMullen** 2020-06-15 20:15 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved
