### ISSUE TITLE
Run Blazor Server app using dotnet watch, the second counter loses its state(resets count to 0) when IncrementAmount attribute is added to the first counter.

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#36299] opened 2021-09-08 21:00 UTC
* Open up a normal Command Prompt, create a 6.0 Blazor Server app, run it using dotnet watch    

         dotnet new blazorserver -o MyBlazorServerApp 
         cd MyBlazorServerApp 
         dotnet watch

* Open the project with VS, add two <Counter /> to Index.razor and save file. The two Counter show up in the browser and they all work (click the button a few times for each one to change the count).

         <Counter />
         <Counter />

* Open Counter.razor, update theCounter component to add an IncrementAmount parameter and then save file.
```razor
@code {
    private int currentCount = 0;
    [Parameter]
    public int IncrementAmount { get; set; } = 1;
    private void IncrementCount()
    {
        currentCount+=IncrementAmount;
    }
}    
```

* In the Index.razor file set the IncrementAmount parameter on the first Counter component to 10, save file and then go to browser.
```razor
   <Counter IncrementAmount="10"/>
```

ACTUAL: 
The second counter loses its state sometimes (resets count to 0) when IncrementAmount attribute is added to the first counter.

**Comment by pranavkm** [comment] 2021-09-08 21:08
@SteveSandersonMS I haven't dug in to this a whole lot, but from what I can tell, adding the attribute causes the renderer to treat this as adding / removing a component which results in it being reinitialized. 

```
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[1]
      Initializing component 75 (b1.Pages.Counter) as child of 53 (b1.Pages.Index)
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[4]
      Disposing component 72 of type b1.Pages.Counter
....
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 56 of type b1.Pages.Counter
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 75 of type b1.Pages.Counter
```

I'd like to say yeah, state preservation in components is best effort, but not guaranteed and so you might see 👻 behavior like this, but I don't know if you differently and this is something we must tackle for 6.0.

**Comment by SteveSandersonMS** [comment] 2021-09-08 22:18
Yes, it would result in the sequence number changing, so it will be treated as a new child. The same would happen if you just added some new content (like another element) before the component. 

In the long term we could do an entirely different - and far more expensive - least-edit-distance type diffing immediately after hot reload updates, but it’s massively out of scope for 6.0.

**Comment by SteveSandersonMS** [comment] 2021-09-09 13:47
BTW if anyone is super keen on preserving instances in this specific case, they can always put on a `@key`, even just with a fixed literal value, e.g.:

```
   <Counter @key="first" />
   <Counter @key="second" />
```

Now the diffing system will preserve instances based on those `@key` values rather than the compiler-generated sequence numbers.

**Comment by SteveSandersonMS** [comment] 2021-09-09 13:47
Closing as by design.

**Closed by SteveSandersonMS** 2021-09-09 13:47 UTC
Labels: area-blazor
