### ISSUE TITLE
Nested CSS is not colorized properly

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#21522] opened 2020-05-05 22:16 UTC
![image](https://user-images.githubusercontent.com/2008729/81121303-43891880-8ee3-11ea-9426-e76dde29c469.png)

Chances are this is due to a TextMate colorization issue but we should double check  nevertheless.

**Comment by TanayParikh** [comment] 2020-05-07 21:04
No repro in `.razor`.
![image](https://user-images.githubusercontent.com/14852843/81344418-91c92380-906b-11ea-9d99-da25b8682ee1.png)


No `var` colorization in `HTML / CSS`.

![image](https://user-images.githubusercontent.com/14852843/81342009-5debff00-9067-11ea-84f8-a16d7df43774.png)

Would a `.html` document be using the same TextMate CSS grammar as a `.razor` document?

**Comment by NTaylorMullen** [comment] 2020-05-07 22:44
> Would a `.html` document be using the same TextMate CSS grammar as a `.razor` document?
No.

Keep in mind I don't think `var` wouldn't be colorized in a CSS section. In an html file try:
```CSS
hello {
    foo: "bar"
}
```

**Comment by TanayParikh** [comment] 2020-05-07 23:02
<img width="409" alt="Screen Shot 2020-05-07 at 4 00 53 PM" src="https://user-images.githubusercontent.com/14852843/81352655-ef656c00-907b-11ea-9d26-4255e1a76b21.png">

<img width="409" alt="Screen Shot 2020-05-07 at 4 00 30 PM" src="https://user-images.githubusercontent.com/14852843/81352636-e2e11380-907b-11ea-9d8e-53fe4157cc4b.png">

Ah I see the missing colorization now. 🎨

**Comment by NTaylorMullen** [comment] 2020-06-25 21:31
Bhavya helped us out big time and here are her findings on how to fix this:
1.	More mappings in aspnetcorerazor.tmLanguage.tmTheme:  
```
            <!-- Begin CSS specific colorization -->

            <dict>
                <key>scope</key>
                <string>
                    meta.selector.custom.css,
                    meta.selector.asterisk.css
                </string>
                <key>settings</key>
                <dict>
                    <key>vsclassificationtype</key>
                    <string>CSS Selector</string>
                </dict>
            </dict>

            <dict>
                <key>scope</key>
                <string>
                    source.css meta.property-name,
                    support.type.property-name.css,
                    support.type.vendored.property-name.css
                </string>
                <key>settings</key>
                <dict>
                    <key>vsclassificationtype</key>
                    <string>CSS Property Name</string>
                </dict>
            </dict>

            <dict>
                <key>scope</key>
                <string>meta.property-value.css</string>
                <key>settings</key>
                <dict>
                    <key>vsclassificationtype</key>
                    <string>CSS Property Value</string>
                </dict>
            </dict>

            <dict>
                <key>scope</key>
                <string>comment.block.css</string>
                <key>settings</key>
                <dict>
                    <key>vsclassificationtype</key>
                    <string>CSS Comment</string>
                </dict>
            </dict>

            <dict>
                <key>scope</key>
                <string>
                    meta.at-rule.charset.css,
                    meta.at-rule.import.css,
                    meta.at-rule.font-face.css,
                    meta.at-rule.page.css,
                    meta.at-rule.media.header.css,
                    meta.at-rule.counter-style.header.css,
                    meta.at-rule.document.header.css,
                    meta.at-rule.keyframes.header.css,
                    meta.at-rule.supports.header.css,
                    meta.at-rule.viewport.css,
                    meta.at-rule.font-features.css,
                    meta.at-rule.namespace.css,
                    meta.at-rule.header.css
                </string>
                <key>settings</key>
                <dict>
                    <key>vsclassificationtype</key>
                    <string>CSS Keyword</string>
                </dict>
            </dict>

            <!-- End CSS specific colorization -->
```

2.	Also, for some reason entity.name.tag.css <-> CSS Selector mapping doesn’t seem to work. I inspected in VS Code(using Inspect TM Scopes option) and entity.name.tag.css seems to be the correct scope. But for some reason it doesn’t work. In my case I added injections in htmly tmlanguage file. For the purpose of testing, I added the below in aspnetrazor.tmLanguage.json and the selector colorization works(at least covers some cases)

```
    "L:source.css": {
      "patterns": [
        {
          "match": "\\*",
          "name": "meta.selector.asterisk.css"
        },
        {
          "match": "[^\\s]([@]*.+?(?=[\\s]*{))",
          "name": "meta.selector.custom.css"
        }
      ]
    }
```

**Comment by ryanbrandenburg** [comment] 2020-10-09 19:58
I've reported the "CSS Selector" thing to @gundermanc who is investigating it from their end since as best I can tell it's an issue on the VS side of things.

**Comment by gundermanc** [comment] 2020-10-09 20:58
Generated a baseline against TextMate editor for Mac and VS Code and VS is inconsistent here, so probably a VS bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1228720

**Comment by gundermanc** [comment] 2020-10-09 23:22
```
(?x)
(?=
  (?:\|)?                    # Possible anonymous namespace prefix
  (?:
    [-\[:.*\#a-zA-Z_]       # Valid selector character
    |
    [^\x00-\x7F]            # Which can include non-ASCII symbols
    |
    \\                      # Or an escape sequence
    (?:[0-9a-fA-F]{1,6}|.)
  )
)
```

This regex in the CSS grammar fails to match `hello`. It looks one of the following:

- Bug in our fork of Oniguruma regex engine. There are several in circulation.
- An encoding specific bug in all forks: we're parsing UTF-16LE strings vs. UTF-8, like in VS Code. We do this to avoid an expensive conversion at parse time.

**Comment by gundermanc** [comment] 2020-10-10 01:23
Alrighty, update: there is indeed something different about the version of Oniguruma we're using. Running the same regex in UTF-16LE and UTF8 encodings yielded two different regex compilation errors:

- UTF-16_LE: ONIGERR_TOO_SHORT_MULTI_BYTE_STRING
- UTF8: ONIGERR_PREMATURE_END_OF_CHAR_CLASS

It's not clear if the regex bug is in VS's fork or the one being used by VS Code. I'm looking into it a bit more to see if we should take a patch.

In the meantime, an effective work-around is to delete the character-class that references Unicode codepoints, `[^\x00-\x7F]` from the meta.selector.css rule in the CSS grammar

```
		<dict>
			<key>begin</key>
			<string>(?x)
(?=
  (?:\|)?                    # Possible anonymous namespace prefix
  (?:
    [-\[:.*\#a-zA-Z_]       # Valid selector character
    |
    [^\x00-\x7F]            # Which can include non-ASCII symbols
    |
    \\                      # Or an escape sequence
    (?:[0-9a-fA-F]{1,6}|.)
  )
)</string>
```

I then modified the ASP.NET theme to theme `meta.selector.css`:

```
      <dict>
          <key>scope</key>
          <string>
              meta.selector.css,
              meta.selector.custom.css,
              meta.selector.asterisk.css
          </string>
          <key>settings</key>
          <dict>
              <key>vsclassificationtype</key>
              <string>CSS Selector</string>
          </dict>
      </dict>
```

![image](https://user-images.githubusercontent.com/5387680/95642286-6bfddb80-0a5c-11eb-9884-69a103472861.png)

**Comment by gundermanc** [comment] 2020-10-10 03:14
Looks like this is indeed a behavior change in the regex engine that is encoding specific. In v6.9.5_rev1, this expression compiles correctly with UTF8, but in UTF-16 it gives an invalid code point error. I'm reaching out to the regex engine owner for clarification.

**Comment by gundermanc** [comment] 2020-10-10 19:56
Spoke with K. Kosako and it sounds like this might be by-design behavior since the \xAA regex expression matches characters by their byte representation, and VS is using the UTF-16LE API, which has 2 bytes per character.

Fix here: https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/280584

Once this is in, simple adding TMTheme for `meta.selector.css` should be adequate to fix the bug.

**Comment by ryanbrandenburg** [comment] 2020-10-12 21:38
@gundermanc's fix is in, so this should be fixed in versions of VS available on the main channel soon.

**Comment by ryanbrandenburg** [comment] 2020-10-16 16:22
Fix confirmed, thanks @gundermanc!

**Closed by ryanbrandenburg** 2020-10-16 16:22 UTC
Labels: External, area-razor.tooling, blocked, bug, cost: S, feature-razor.textmate, feature-razor.vs
