### ISSUE TITLE
Blazor Server Access IP Address

### ISSUE THREAD

**Issue by ctigrisht** [dotnet/aspnetcore#39517] opened 2022-01-14 15:10 UTC
In Blazor Server, it would be immensely useful to be able to access IP and other information about a connecting client directly from blazor
We could inject something like a `SessionContext` and access IP address via `SessionContext.Client.Host`

**Comment by TanayParikh** [comment] 2022-01-14 16:18
@ctigrisht you should be able to use this in your Blazor Server app: 

```C#
var remoteIpAddress = request.HttpContext.Connection.RemoteIpAddress;
```

You should be able to capture this as part of your `_Host.cshtml` and pass it to your root component.

Duplicate of https://github.com/dotnet/aspnetcore/issues/37728.

**Comment by ctigrisht** [comment] 2022-01-15 08:38
@TanayParikh I meant to be able to access if directly from a component and not having to pass it through from the Host file

**Closed** 2022-01-16 10:00 UTC
Labels: area-blazor, :heavy_check_mark: Resolution: Answered, Status: Resolved, blazor-server
