### ISSUE TITLE
IHost Memory leak with CreateDefaultBuilder

### ISSUE THREAD

**Issue by CurtisFulton** [dotnet/aspnetcore#31219] opened 2021-03-25 02:29 UTC
### Describe the bug
Stopping and disposing an instance of IHost leaves FileSystemWatchers, causing a small memory leak. 
Seems to be related to the default configuration files it tries to watch.

### To Reproduce
Using the Standard .Net 5 Console App template in Visual studio.

```
private static async Task Main(string[] args)
{
    var loopCount = 0;
    while (true)
    {
        loopCount++;
        using var host = Host.CreateDefaultBuilder()
                             .Build();

        await host.StartAsync();
        await host.StopAsync();

        GC.Collect();
        GC.WaitForPendingFinalizers();

        Console.WriteLine($"Completed loop {loopCount}");
    }
}
```

Running the above code, note the memory usage of the console app consistently goes up.
After ~15000 loops it was using ~200mb of memory.

Looking at the memory snapshot I can see there seems to be 1 FileSystemWatcher (And related things) stuck for every loop that occurs. 

![image](https://user-images.githubusercontent.com/28940132/112409353-12b50a80-8d65-11eb-9f01-c843fb094404.png)

I found that clearing the config sources by running 

```
ConfigureAppConfiguration(config =>
{
    config.Sources.Clear();
})
```

seemingly removes the issue. So I assume that the leak is coming from the setup of the default configuration.

**Comment by BrennanConroy** [comment] 2021-03-25 02:35
Looks like a dupe of https://github.com/dotnet/aspnetcore/issues/31125

**Comment by CurtisFulton** [comment] 2021-03-25 02:43
Didn't seem like it at first, but based on the pull request fixes it looks like it's the same issue.

Do I close this one or do they both stay open until it's fixed?

**Comment by BrennanConroy** [comment] 2021-03-25 02:47
Let's close this, if you think it's different we can reopen :)

**Closed by BrennanConroy** 2021-03-25 02:47 UTC
