### ISSUE TITLE
16.7-Preview2 / 5.0.0-Preview6 - Validate Razor tooling on Linux

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#22111] opened 2020-05-21 22:17 UTC
## Instructions
It's up to you to validate all features, if applicable, done in the [16.7-preview2 / 5.0.0-preview6 milestone](https://github.com/dotnet/aspnetcore/milestone/103?closed=1) (not just your own). Given that this is tooling validation, features and bug fixes should be relatively easy to validate given they don't require complex setups to ensure something works.

As part of this process don't be afraid to experiment outside the context of the issues within the milestone.

## Debug Adapter Test scenarios

- [ ] Blazor WASM Hosted
- [ ] Blazor WASM Standalone

## Filing issues
All issues found should be filed under the **Razor.Tooling** milestone and assigned to the **Razor Tooling vNext** project. Lastly give those issues the appropriate labels and mention them under this issue before closing.

## Completing validation

Once you're done with your validation, link to any issues found and then close this issue and move it to the "Done" column in the Razor Tooling vNext project.

## Validation Build
**O# release:** https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.22.0

You can install this VSIX by downloading the VSIX from above and then installing it by going to your extensions pane in VSCode -> Clicking the ... -> Install from VSIX
![image](https://user-images.githubusercontent.com/2008729/72949076-0df95e80-3d3c-11ea-8d25-aa9a82a29d2b.png)

**Comment by TanayParikh** [comment] 2020-05-22 17:53
Issues found:
- [] https://github.com/dotnet/aspnetcore/issues/22150
- [ ] https://github.com/dotnet/aspnetcore/issues/22149

**Comment by TanayParikh** [comment] 2020-05-22 20:49
Linux validations are done with the above issues noted. 

@captainsafia is there anything else needed for Blazor WASM debug adapter validation before closing this out?

**Comment by captainsafia** [comment] 2020-05-22 22:07
This can be closed out.

The pre-existing issue with hosted Blazor apps exists in Linux.

But it looks like dev server processes are cleaned up correctly so 👍 .

**Comment by TanayParikh** [comment] 2020-05-27 04:38
Re-tried https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.22.0 based on the latest insertion.

The issues look good, but noticed the following issue (**Note:** Not a regression caused by the current build, it can be reproduced in the old published extension): https://github.com/dotnet/aspnetcore/issues/22261

**Comment by captainsafia** [comment] 2020-05-27 05:13
Validated attach on Linux.

**Comment by TanayParikh** [comment] 2020-05-27 16:25
Closing out again. @captainsafia feel free to re-open if there's anything left.

**Closed by TanayParikh** 2020-05-27 16:25 UTC
Labels: Validation, area-razor.tooling, task
