### ISSUE TITLE
Virtualize ItemsProvider work incorrectly and causes blink

### ISSUE THREAD

**Issue by ElderJames** [dotnet/aspnetcore#48254] opened 2023-05-16 06:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes the ItemsProvider will request data twice at the same time, and the first time the StartIndex is incorrect and causes the list to blink.

Maybe this issue is related https://github.com/dotnet/aspnetcore/issues/28653 , but this always happen on the second load.

![virsualize-load](https://github.com/dotnet/aspnetcore/assets/7550366/2d5b9d5f-aaf2-402f-b62d-733e9183e027)

As you can see from the screenshot, two simultaneous requests were made for the second load, one of which appears to be useless.

### Expected Behavior

I think it should avoid the second request and just call the third.

### Steps To Reproduce

This is a problem I encountered while making improvements to my component library, here's what I changed:

https://github.com/ant-design-blazor/ant-design-blazor/pull/3262

### .NET Version

.NET 7

**Comment by simeyla** [comment] 2023-06-26 02:25
I'm assuming this is the same issue I'm seeing. It is really noticeable if you have an image in one of the grid columns. 
Select 'Disable Cache' under browser tools in the 'Network' control panel and when the grid scrolled you can see all the images flicker indicating a redraw.

Another way to observe that each row is recreated is to set `outline: 2px solid red` on a grid cell and then scroll.

I would have expected it to just add and remove rows above existing ones. Also it would be really nice if QuickGrid would support [overscan](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0#overscan-count). I want to load 50 rows at a time, not 3 or 4. It's much too slow without it.

**Comment by mkArtakMSFT** [comment] 2023-12-13 17:30
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/28653

**Closed by mkArtakMSFT** 2023-12-13 17:30 UTC
Labels: bug, area-blazor, feature-blazor-quickgrid, Pillar: Technical Debt
