### ISSUE TITLE
Validate source link info for 2.1 servicing

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#22469] opened 2020-06-02 16:37 UTC
Per [this issue](https://github.com/dotnet/runtime/issues/13257#issuecomment-637659872) in `dotnet/runtime`, it looks like when consolidating aspnet/* repos for 2.1 servicing, we may not have correctly configured sourcelink for all packages.  Can we take a look and see if we can fix it for the next servicing release?

**Comment by Pilchie** [comment] 2020-06-02 16:38
Tagging @dotnet/aspnet-build

**Comment by wtgodbe** [comment] 2020-06-04 17:38
> Based on the files that do exist, presumably it should have been:
https://raw.githubusercontent.com/aspnet/AspnetCore/28cf04843f3456a72f1816e83a1f4aa59f49a049/src/MetaPackages/src/Microsoft.AspNetCore/WebHost.cs
i.e. the original link was missing the "src/MetaPackages" part of the path? Regardless, the above resolves even with "aspnet/AspnetCore", so as @ViktorHofer cited, this doesn't appear to be related to the repo migration (but maybe there's a separate issue with PDB generation).

I'm confused - I don't see a folder named `src/MetaPackages` in release/2.1 (or 3.1) - @dotnet/aspnet-build does anyone know where that might be coming from?

**Comment by wtgodbe** [comment] 2020-06-04 17:40
I guess that folder _used_ to exist: https://github.com/dotnet/aspnetcore/tree/28cf04843f3456a72f1816e83a1f4aa59f49a049/src/MetaPackages. The user is talking about a 2.1.7 PDB, so likely the issue is just that the file existed at the time we shipped 2.1.7, but doesn't exist any more. I'll respond to the other thread.

**Comment by dougbu** [comment] 2020-06-05 22:27
From https://github.com/dotnet/runtime/issues/13257#issuecomment-639157447:
> Any later code movement and the directory consolidation are red herrings for this part of the discussion.

> https://raw.githubusercontent.com/aspnet/AspnetCore/28cf04843f3456a72f1816e83a1f4aa59f49a049/src/MetaPackages/src/Microsoft.AspNetCore/WebHost.cs is a completely valid URI that matches what https://github.com/dotnet/aspnetcore/blob/v2.1.7/src/MetaPackages/src/Microsoft.AspNetCore/WebHost.cs shows. The PDB is messed up.

> Questions:
> 1. Is this a general issue w/ our 2.1.x releases all up?
>    - Is it still a problem when we build the 'release/2.1' branch?
>    - If not, when did we fix it?
> 2. If this is a current issue, should we release everything next time?
> 3. Otherwise, how much needs to be released next time?

**Comment by wtgodbe** [comment] 2020-06-12 17:14
I've been combing through old .pdb's, and so far the only broken one I've found is `Microsoft.AspNetCore` in 2.1.7. In 2.1.0, that package carried correct SourceLink info: https://raw.githubusercontent.com/aspnet/MetaPackages/9a5f4958e20c8cf3698d03bb262b1fd06b60be15/src/Microsoft.AspNetCore/WebHost.cs. I'll check other 2.1.7 packages now

**Comment by wtgodbe** [comment] 2020-06-12 17:28
Other 2.1.7 packages are busted - `Microsoft.AspNetCore.Server.IISIntegration.2.1.7` carries links to local paths on a build machine (`C:\b\w\da744fbcc13abce\src\Shared\HttpSys\NativeInterop\HttpApiTypes.cs`), as well as busted github links: https://raw.githubusercontent.com/aspnet/AspNetCore/28cf04843f3456a72f1816e83a1f4aa59f49a049/src/Microsoft.AspNetCore.Server.IISIntegration/AuthenticationHandler.cs

However, another 2.1.7 package (`Microsoft.VisualStudioWeb.CodeGeneration.Utils`) has correct SourceLink info: https://raw.githubusercontent.com/aspnet/scaffolding/2f81b98c133c24ec699f370bf07b557dd484c646/src/VS.Web.CG.Utils/Resource.Designer.cs, though this points to the scaffolding repo.

There's also `Microsoft.AspNetCore.WebSockets.2.1.7`, which has correct sourcelink info and points to the aspnetcore repo: https://raw.githubusercontent.com/aspnet/AspNetCore/28cf04843f3456a72f1816e83a1f4aa59f49a049/src/Middleware/WebSockets/src/ExtendedWebSocketAcceptContext.cs. Very confusing stuff. I'm still digging

**Comment by wtgodbe** [comment] 2020-06-12 17:50
`Microsoft.AspNetCore.2.1.6` has correct SourceLink data: https://raw.githubusercontent.com/aspnet/MetaPackages/96be626c87c3ca325b18aa6653602f5e7087497f/src/Microsoft.AspNetCore/WebHost.cs. The 2.1.7 version of this package was the one that was originally reported

**Comment by wtgodbe** [comment] 2020-06-12 20:24
The only 2 busted .pdb's I've found have been `Microsoft.AspNetCore.Server.IISIntegration.2.1.7` and `Microsoft.AspNetCore.2.1.7`. I'm seeing what happens if we rebuild them, here: https://github.com/dotnet/aspnetcore/pull/22894

**Comment by Pilchie** [comment] 2020-06-12 20:26
I wonder if it would be possible to just re-write the PDBs and republish them without actually shipping new versions of the packages too.

**Comment by wtgodbe** [comment] 2020-06-12 20:31
> I wonder if it would be possible to just re-write the PDBs and republish them without actually shipping new versions of the packages too.

Seems likely, though I'm not sure where in the .pdb the SourceLink info is written (I've only been able to view it w/ nuget package explorer, I haven't been successful in finding it by dumping the content). @tmat is this something we could do?

**Comment by wtgodbe** [comment] 2020-06-12 20:36
If we decide to re-ship the packages, looks like the issue was fixed some time between 2.1.7 and now - https://github.com/dotnet/aspnetcore/pull/22894 produced symbol packages for `Microsoft.AspNetCore.Server.IISIntegration` and `Microsoft.AspNetCore` with accurate SourceLink info

**Comment by wtgodbe** [comment] 2020-06-22 17:07
Update on this: The underlying issue is already fixed, so the next time we ship the 2 broken packages, they will have correct sourcelink info - but, we won't re-ship the packages _just_ for the purpose of correcting sourcelink. Closing as won't-fix.

**Closed by wtgodbe** 2020-06-22 17:07 UTC
Labels: :heavy_check_mark: Resolution: Won't Fix, area-infrastructure

**Comment by ulrichb** [comment] 2020-06-25 09:53
Okay, thx for info.
