### ISSUE TITLE
Identity: Scaffolded Login page includes bad link to ./ResendEmailConfirmation

### ISSUE THREAD

**Issue by mwhouser** [dotnet/aspnetcore#22013] opened 2020-05-20 01:09 UTC
### Describe the bug

If you scaffold "all" identity pages, then the Login page that is scaffolded includes an extra link to ./ResendEmailConfirmation. Clicking that link shows an exception:

> InvalidOperationException: Can't compile a NewExpression with a constructor declared on an abstract class

### To Reproduce

1. Create a new ASP.NET Core Web Application
    * Web Application (Model-View-Controller)
    * Authentication: Individual User Accounts

Once created, run your application and go to the "Login page". Notice that at the bottom there are 2 links:
* Forgot your password
* Register as a new user

Stop your app, in the Solution Explorer, right click, select "Add" then "New Scaffolded Item..."

2. Choose "Identity"
3. Choose "Override all files".

Run your new application again. Go to the "Login" page. This time, you'll see a new "Resend email confirmation" link.

Click that link and you'll see the exception:

> InvalidOperationException: Can't compile a NewExpression with a constructor declared on an abstract class

### Further technical details
- ASP.NET Core version: 3.1.4
- IDE: Visual Studio 2019 version 16.6.0

**Comment by dahln** [comment] 2020-05-20 04:23
I am having this exact issue. 

The ResendEmailConfirmationModel class is marked as abstract. When I remove abstract from the class, the page loads and functions as expected.

I considered creating a PR to remove the abstract keyword from the class, but I don't want to do so without understanding why it was marked abstract in the first place.

**Comment by codingyourlife** [comment] 2020-05-22 01:17
I can confirm this issue and what @dahln fixed it for me. Not sure about all the implications of the fix...

**Comment by HaoK** [comment] 2020-05-22 01:38
Dupe of https://github.com/dotnet/aspnetcore/issues/21827

Fixed by https://github.com/dotnet/Scaffolding/pull/1339

**Closed by HaoK** 2020-05-22 01:38 UTC
Labels: area-identity
