### ISSUE TITLE
MetadataTypeAttribute (still) does NOT work for Blazor WASM (.NET 6)

### ISSUE THREAD

**Issue by CDEngineer** [dotnet/aspnetcore#41142] opened 2022-04-12 02:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The MetadataTypeAttribute class is (still) not working for Blazor WASM.

I am following the instructions found in the official documentation.
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.metadatatypeattribute?view=net-6.0

This was supposed to be fixed for .NET 6.
https://github.com/dotnet/runtime/pull/51772

But it is still not working.

### Expected Behavior

Data annotations added using the MetadataTypeAttribute class should validate the same as data annotations made directly. Both fields in the Blazor WASM bug-demo (below) should validate correctly.

### Steps To Reproduce

I created a bug-demo at GitHub.
https://github.com/CDEngineer/MetadataTypeBug

The most relevant part of the bug-demo code follows.

**Collaborator.cs**

Here I add the "Required" attribute directly to the "FirstName" property.

```
    // In a real application, this class was auto-generated
    // (scaffolded using Entity Framework database-first).
    public partial class Collaborator
    {
        public Collaborator()
        {
        }

        // This "Required" attribute was added manually
        // and will be deleted when we need to scaffold it again.
        [Required(ErrorMessage = "First name is required.")] 
        public string FirstName { get; set; } = null!;

        public string LastName { get; set; } = null!;
    }
```

**Collaborator.Partial.cs**

Here I add the "Required" attribute to the "LastName" property.

```
    [MetadataType(typeof(CollaboratorMetadata))]
    public partial class Collaborator
    {
    }

    public class CollaboratorMetadata
    {
        [Required(ErrorMessage = "Last name is required.")]
        public string LastName { get; set; } = null!;       
    }
```

If I leave both text-boxes empty, only the first one validates.

![image](https://user-images.githubusercontent.com/38195661/162869169-205ce5a8-a827-4ab9-b808-0fe75c28f1a2.png)

If I only leave the second text-box empty, the form (incorrectly) passes validation.

![image](https://user-images.githubusercontent.com/38195661/162869213-b85e46d4-6c39-42c9-852e-b23c2e5161d0.png)

### .NET Version

6.0.201

### Anything else?

PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.212 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by TanayParikh** [comment] 2022-04-12 03:31
Hello @CDEngineer, thanks for reaching out. This appears to be a duplicate of https://github.com/dotnet/aspnetcore/issues/39938, so I'm closing out this issue. Have you tried out https://github.com/dotnet/aspnetcore/issues/39938#issuecomment-1006945517?

**Closed** 2022-04-13 04:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, Status: Resolved
