### ISSUE TITLE
Razor C# colorization inconsistency

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#27134] opened 2020-10-22 22:43 UTC
With the new Razor editor in 16.9 P2 [30621.305.main]:

In C#
![image](https://user-images.githubusercontent.com/1874516/96937521-2e964680-147d-11eb-9dfa-e4e458fa730a.png)

In Razor:
![image](https://user-images.githubusercontent.com/1874516/96937547-38b84500-147d-11eb-8a35-65d49d6fbece.png)

**Comment by NTaylorMullen** [comment] 2020-11-11 00:17
Duplicate of https://github.com/dotnet/aspnetcore/issues/26753

**Closed by NTaylorMullen** 2020-11-11 00:17 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling
