### ISSUE TITLE
Problem with body parameters when using `WithOpenApi()` from `Microsoft.AspNetCore.OpenApi`

### ISSUE THREAD

**Issue by andrewlock** [dotnet/aspnetcore#43938] opened 2022-09-13 07:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Body parameters are incorrectly emitted as "parameters" by Swagger (in addition to `requestBody`) when using the `WithOpenApi()` extension method from `Microsoft.AspNetCore.OpenApi`. The parameter has no schema (just a name) in the swagger document. For example, the following endpoint: 

```csharp
app.MapPost("/fruit/{id}", (string id, Fruit fruit) => fruit)
    .WithOpenApi();
```

Produces a swagger.json similar to:

```json
"paths": {
    "/fruit/{id}": {
      "post": {
        "tags": [
          "fruit"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {                     // Should not exist
            "name": "fruit",    //
            "required": true    //
          }                     //
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Fruit"
              }
            }
          },
          "required": true
        },
    }
}
```

This leads to incorrect handling in Swagger UI (for example)
![image](https://user-images.githubusercontent.com/18755388/189841987-4aa0ead2-01b0-4a9a-88ee-7ec42f561fa3.png)

### Expected Behavior

The body endpoint parameter should not appear as a parameter in the swagger schema. This is the behaviour if you _don't_ call `WithOpenApi()`: 

```json
"paths": {
    "/fruit/{id}": {
      "post": {
        "tags": [
          "fruit"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Fruit"
              }
            }
          },
          "required": true
        },
    }
}
```

### Steps To Reproduce

A new minimal API project, using .NET 7 preview 7, and the following packages:

```xml
  <ItemGroup>	
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.0-preview.7.22376.6" />
    <PackageReference Include="swashbuckle.aspnetcore" Version="6.4.0" />
  </ItemGroup>
```

Program.cs:

```csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

WebApplication app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();

app.MapPost("/fruit/{id}",(string id, Fruit fruit) => fruit)
    .WithOpenApi();

app.Run();

record Fruit(string Name, int Stock);
```

### Exceptions (if any)

N/A

### .NET Version

7.0.100-preview.7.22377.5

### Anything else?

ASP.NET Core version: 7
The IDE: VS/VS Code/ Rider (Not applicable)
<details>
<summary>dotnet --info</summary>
<pre><code>
.NET SDK:
 Version:   7.0.100-preview.7.22377.5
 Commit:    ba310d9309

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.7.22377.5\

Host:
  Version:      7.0.0-preview.7.22375.6
  Architecture: x64
  Commit:       eecb028078

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  6.0.108 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.7.22377.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.7.22376.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.7.22377.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
</code></pre></details>

**Comment by captainsafia** [comment] 2022-09-13 21:42
@andrewlock It looks like this bug is a dupe of https://github.com/dotnet/aspnetcore/issues/42483 which is fixed in rc1.

**Closed** 2022-09-14 00:45 UTC
Labels: bug, :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-web-frameworks
