### ISSUE TITLE
Crippled Visual Studio 2022 debugging performance on Blazor Web (WASM components) after updating to .NET 9

### ISSUE THREAD

**Issue by mip1983** [dotnet/aspnetcore#58577] opened 2024-10-18 14:54 UTC
I'm in the process of trying out the latest RC2 .NET 9 update on a couple of my Blazor Web projects (which have mixed server/wasm client pages/components), and am having some severe issue's with debugging in Visual Studio 2022 Professional (Version 17.12.0 Preview 3.0, have run dotnet workload update). I used the upgrade tool in visual studio to target .NET 9 on my blazor projects (web and client). I'm on a reasonable machine, intel core ultra 7, 32gb memory.

On a basic 'Starter template' kind of project, all seems mostly ok, though it sometimes gets stuck in the process of ending debugging with an error message that I have to close/re-open visual studio to be able to debug again.

On a more substantial project with .NET 8, the debug experience is fine, The time from the initial server pre-render to the web page fully rendering is **~7 seconds** when debugging. In terms of what the page is doing, it's an 'InteractiveWebAssembly' page, it's making a number of HttpClient calls to the back end API to populate a dashboard of charts (less than 400kb transferred, charts are third party Blazor components from Syncfusion).

On the same project with no other changes than running the .NET 9 upgrade tool, when starting debugging, the time from initial server pre-render to the page fully loaded is **106 seconds**. The console output is a slow trickle and the CPU is working harder. It sometimes causes time outs on the http client calls to web api's so the app errors. It's basically unusable.

If I run the .NET 9 version without debugging, it works fine running at a normal speeds, so it looks to be specific to debugging (and probably debugging wasm).

Is this just the nature of the preview version or are there some things that need fixing? Happy to provide any further info/profiling if you let me know what you need.

Visual studio: 17.12.0 Preview 3
SDK: 9.0.100-rc.2.24474.11 
wasm-tools (workload): 9.0.0-rc.2.24473.5/9.0.100-rc.2 
Browser for debugging: Edge Version 129.0.2792.89

**Comment by Pvxtotal** [comment] 2024-10-22 23:51
I opened an issue on this subject too: 

https://github.com/dotnet/aspnetcore/issues/58507

Apparently is a Visual Studio problem, I'm worried because it makes almost impossible to debug in .NET 9

**Comment by mip1983** [comment] 2024-10-23 08:15
Thanks @Pvxtotal, useful to know it's not just a local installation issue.

**Comment by javiercn** [comment] 2024-10-23 08:34
@mip1983 thanks for contacting us.

We are following up on https://github.com/dotnet/aspnetcore/issues/58507 and have loop in the right folks so that we can get to the bottom of it.

Can you confirm that the issue only happens when you launch with the debugger attached?

**Comment by javiercn** [comment] 2024-10-23 10:44
@mip1983 thanks for the confirmation.

I'm going to close this issue as we are going to be using another issue to track the investigation and any fix needed.

Dupe of https://github.com/dotnet/aspnetcore/issues/58507

**Closed by javiercn** 2024-10-23 10:44 UTC
Labels: area-blazor, Needs: Attention :wave:, untriaged
