### ISSUE TITLE
Signalr : Allow controlling maximum buffer size on client . 

### ISSUE THREAD

**Issue by vinaykapoor** [dotnet/aspnetcore#34895] opened 2021-07-31 01:31 UTC
This is the same request as issue [17797](http://github.com/dotnet/aspnetcore/issues/17797) , as more and more people adopt to .net core and signalr the requirement for ability to avoid back pressure on client becomes a need. 
can you please allow maximum buffer size on .NET client.

**Comment by BrennanConroy** [comment] 2021-07-31 02:27
Like you linked, dupe of https://github.com/dotnet/aspnetcore/issues/17797

**Comment by davidfowl** [comment] 2021-07-31 02:33
@vinaykapoor  do you have a real scenario?

**Comment by vinaykapoor** [comment] 2021-07-31 04:07
I have a WPF UI which gets stock orders amd updates on orders with market data updates throughout the day , however at the end of the day I get a burst of messages and all the clients get slowed down by 20-30 seconds. It looks like a back pressure scenario on the client side which is why I was going to try to  increasing the transport buffer on server side and increase the max receive buffer on client. 

Vinay

**Comment by davidfowl** [comment] 2021-07-31 04:32
If you could create an application. That helps us test the scenario or if you can build your own copy of the client and use that setting to see if it solves your problem, that would help us prioritize the issue

**Comment by davidfowl** [comment] 2021-07-31 09:44
This was the original fix we put in https://github.com/dotnet/aspnetcore/issues/20654

**Comment by vinaykapoor** [comment] 2021-07-31 13:13
The application has been in works for a year so it will be difficult to send. I will have to create a sample, however I could not recreate how the traffic evolves at the end of day. I have noticed this on multiple users that everything works to the millisecond until 3:59 and then everyone slows down. If you could tell me which setting I can set and make my own build and see if that fixes the issue I can try that out. Or if you could give me a build with that setting active I could try it and let you know if it worked. I will highly appreciate your time. 

Vinay

**Comment by vinaykapoor** [comment] 2021-07-31 13:43
David 

I didn’t find the signalr setting you mentioned but if you could guide me as to where I should make the change mentioned in #20654 I could try it out. 
The UI acts as monitoring tool which tracks orders / child order / children of child orders along with updates on each such as executions/market data/ processing updates. Do you think moving some of messages e.g. market data to another signalr hub could help?  I have been working on this since last year. I don’t know if you remember but You and Brennan and helped me on the authentication issue with websockets on .net client. The messages are received within milliseconds throughout the day however at that last minute there’s a large burst that gets sent and slows down all UIs.. This application is a rewrite of a silverlight UI With the same number of messages being sent to it and the messaging framework used was Socketsasynceventargs on server and client. I had large buffer sizes there and the application is still in use and there is no issue on that during closing hours. 

If you could point me where I could add the code for on the signalr .net client, I can try it out on my end and let you know of the results. 

Thank you for your help.

Vinay

**Comment by BrennanConroy** [comment] 2021-07-31 22:07
A simple test would be to use the 3.1 client as it didn't have backpressure on the client until 5.0.

**Comment by vinaykapoor** [comment] 2021-07-31 22:30
I could try that but 3.1 had the authentication issue with websockets on negotiate ntlm  . I will try that locally but all if the server has the option to control send and receive buffer size it seems logical that the client also have similar usage . Even in the past other protocols such as nettcp over WCF had maxbuffersize capabilities . 

Thank you for the suggestion. I appreciate the help.

Vinay

**Comment by BrennanConroy** [comment] 2021-07-31 22:44
> 3.1 had the authentication issue with websockets on negotiate ntlm

Idk what issue that is, but if it was a problem with client websockets specifically then you could try manually referencing a newer websocket package with the 3.1 client.

**Comment by davidfowl** [comment] 2021-08-01 01:18
If you can try this branch out https://github.com/dotnet/aspnetcore/pull/34913. You need to build [this dll](https://github.com/dotnet/aspnetcore/tree/5075b1e1431a8454586e735ca57247c7057df0f8/src/SignalR/clients/csharp/Http.Connections.Client/src). Let us know if it resolves the issue or if you have trouble building it.

**Comment by davidfowl** [comment] 2021-08-01 06:27
Actually you should be able to use [this URL](https://dev.azure.com/dnceng/_apis/resources/Containers/7755947/Windows_Packages?itemPath=Windows_Packages%2FRelease%2FShipping%2FMicrosoft.AspNetCore.Http.Connections.Client.6.0.0-ci.nupkg)

**Comment by vinaykapoor** [comment] 2021-08-01 21:38
I seem to be unable to access the link you sent.
Do i need to use an outlook.com address?

**Comment by vinaykapoor** [comment] 2021-08-01 21:41
{"$id":"1","innerException":null,"message":"TF400813: The user
'Windows Live ***@***.***' is not authorized to access
this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException,
Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}

**Comment by davidfowl** [comment] 2021-08-01 23:44
I've uploaded the built package here https://wormhole.app/086WM#ztu3JhvZiAzYkonJ7MOfmA. It'll last for 24 hours or 5 downloads.

**Comment by vinaykapoor** [comment] 2021-08-02 16:19
David,
I was not able to add the nuget package because it detected a package
downgrade from 6.0.0.0-preview.6.21355.* to 6.0.0-ci. Do i need to
downgrade any packages? I also tried to just replace the dll after building
my project and tried to run it, but it doesnt connect to the hub after that.

**Comment by vinaykapoor** [comment] 2021-08-02 18:48
Would it be possible to make the version of the fall higher than latest one?

Vinay

**Comment by davidfowl** [comment] 2021-08-03 04:45
What target framework are you using? I'll send a dll compiled against preview6

**Comment by davidfowl** [comment] 2021-08-03 04:48
Here's another link https://wormhole.app/yEnxv#ozrEXYeQbvr_CZhMRmkwgA

**Comment by vinaykapoor** [comment] 2021-08-03 14:59
David

I am using .NET 6 preview 6. I noticed that your dll requires logging.abstractions and extensions.options >= 6.0.0-rc1. But the lates ones for these that I see on nugget are 6.0.0-preview6.2*

Vinay

**Comment by davidfowl** [comment] 2021-08-03 15:04
The latest URL in the last comment uses the preview6 branch and *should* work against preview 6 dependencies.

**Comment by vinaykapoor** [comment] 2021-08-03 15:27
I was able to replace the dlls with what you sent and i was able to run the exe. I did not build against the dll since it wasn’t a nuget pkg and I am referencing signalr client from nuget.

Vinay

**Comment by vinaykapoor** [comment] 2021-08-03 20:07
David 
The dlls you gave me today worked extremely well. There was a significant improvement . Unfortunately I had turned off logging so I didnt log any metrics but just by looking it was obvious that it was faster. I will continue to try this for next few days. 

Alternatively I also created an additional hub So that I could also split my messages between 2 hubs in the same server one for orders and another for market data updates, and I was able to notice some improvements there as well. I did it use your changes for that version. In your opinion is it a good idea to have multiple hubs (essentially multiple TCP stacks) in a scenario like mine. 

Thank you very much. 
Vinay

**Comment by vinaykapoor** [comment] 2021-08-04 00:52
Can I get a build with .NET 5? So I can ask other users to observe ?

Vinay

**Comment by vinaykapoor** [comment] 2021-08-04 02:34
Could this be something that can be included on the next update. If I branch out a build I will not be able to update update the packages. 

Vinay

**Comment by davidfowl** [comment] 2021-08-04 02:40
It'll be part of .net 6 rc1

**Comment by davidfowl** [comment] 2021-08-05 06:18
Closing this in favor of the duped issue.

**Closed by davidfowl** 2021-08-05 06:18 UTC
Labels: area-signalr
