### ISSUE TITLE
Flaky CanSendAndReceiveBytes

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#23366] opened 2020-06-25 22:46 UTC
There were four blazor test failures in https://dev.azure.com/dnceng/public/_build/results?buildId=704666&view=ms.vss-test-web.build-test-results-tab&runId=21834978&resultId=100374&paneView=debug. All of them look fairly similar, seems more likely to be a general issue.

Failure:
```
  | OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.TrueException: Assert.True() Failure\r\nExpected: True\r\nActual: False\r\n at Xunit.Assert.True(Nullable1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 95\r\n at Xunit.Assert.True(Boolean condition) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 62\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass5_0.<True>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 103\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\802524f612c74cb3b73db104eeb550a3.png'\r\nEncountered browser errors\r\n[2020-06-25T18:18:26Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:28Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:32Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:37Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:42Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:47Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705927218"\r\n[2020-06-25T18:18:48Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705928121"\r\n[2020-06-25T18:18:50Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705929998"\r\n[2020-06-25T18:19:01Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705941484.01"\r\n[2020-06-25T18:19:04Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705944285.01"\r\n[2020-06-25T18:19:08Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705948035.99"Page content:\r\n<head>\r\n <meta charset="utf-8">\r\n <title>E2EPerformance</title>\r\n <link href="benchmarks/lib/bootstrap.min.css" rel="stylesheet">\r\n <link href="benchmarks/lib/minibench/style.css" rel="stylesheet">\r\n</head>\r\n<body style="overflow: scroll;">\r\n <div class="container" id="display"><div class="d-flex align-items-center"><h2 class="mx-3 flex-grow-1">E2E Performance<label class="ml-auto mr-5"><input type="checkbox" class="mr-2">Verify only</label><button class="btn btn-success ml-auto px-4 run-button" id="runAll" style="display: block;">Run all</button><button class="btn btn-danger ml-auto px-4 stop-button" style="display: none;">Stop</button><div class="my-3 py-2 bg-white rounded shadow-sm"><div class="d-flex align-items-baseline px-4"><h5 class="py-2">App Startup<a class="ml-auto run-button" href="" style="display: block;">Run all<table class="table mb-0 benchmarks">
-- | --
Executions: 1 | Duration: 17300ms

 at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 123
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.True(IWebDriver driver, Func`1 actual, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30
   at Microsoft.AspNetCore.Components.E2ETest.Tests.PerformanceTest.BenchmarksRunWithoutError() in /_/src/Components/test/E2ETest/Tests/PerformanceTest.cs:line 51
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass5_0.<True>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 103
```

@pranavkm mentioned:

> I wonder if the issue is that we're not waiting for the component to be ready before doing work. We should quarantine these until we've had a chance to investigate.

**Comment by pranavkm** [comment] 2020-10-14 22:25
As part of https://github.com/dotnet/aspnetcore/pull/26519, we addressed the shorter timeouts that was the likely cause for the initial timeout. Closing the issue. The tests will become eligible to be unquarantined after Nov 2 2020.

**Comment by HaoK** [comment] 2021-03-23 21:22
Will use this as one of the tests for pw baseline

**Comment by HaoK** [comment] 2021-04-20 20:09
Unassigning since I'm not planning on looking into why the test is flaky, just copying it for one of the initial seeded tests on playwright

**Comment by TanayParikh** [comment] 2021-04-29 21:25
The original build link is no longer available, so basing this investigation off of the copied error message. It mentions the [`Microsoft.AspNetCore.Components.E2ETest.Tests.PerformanceTest.BenchmarksRunWithoutError`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/PerformanceTest.cs#L38-L58) test which has already been unquarantined. 

This leaves [`CanSendAndReceiveBytes`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/BinaryHttpClientTest.cs#L45-L53)  which should be safe to unquarantine now based on the 30 day pass history and infra improvements which addressed the root cause.

Formatted error message from above:
```
  | OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual: False
 at Xunit.Assert.True(Nullable1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 95
 at Xunit.Assert.True(Boolean condition) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 62
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass5_0.<True>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 103
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\802524f612c74cb3b73db104eeb550a3.png'
Encountered browser errors
[2020-06-25T18:18:26Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2020-06-25T18:18:28Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2020-06-25T18:18:32Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2020-06-25T18:18:37Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2020-06-25T18:18:42Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2020-06-25T18:18:47Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705927218"
[2020-06-25T18:18:48Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705928121"
[2020-06-25T18:18:50Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705929998"
[2020-06-25T18:19:01Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705941484.01"
[2020-06-25T18:19:04Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705944285.01"
[2020-06-25T18:19:08Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705948035.99"Page content:
<head>
 <meta charset="utf-8">
 <title>E2EPerformance</title>
 <link href="benchmarks/lib/bootstrap.min.css" rel="stylesheet">
 <link href="benchmarks/lib/minibench/style.css" rel="stylesheet">
</head>
<body style="overflow: scroll;">
 <div class="container" id="display"><div class="d-flex align-items-center"><h2 class="mx-3 flex-grow-1">E2E Performance<label class="ml-auto mr-5"><input type="checkbox" class="mr-2">Verify only</label><button class="btn btn-success ml-auto px-4 run-button" id="runAll" style="display: block;">Run all</button><button class="btn btn-danger ml-auto px-4 stop-button" style="display: none;">Stop</button><div class="my-3 py-2 bg-white rounded shadow-sm"><div class="d-flex align-items-baseline px-4"><h5 class="py-2">App Startup<a class="ml-auto run-button" href="" style="display: block;">Run all<table class="table mb-0 benchmarks">
-- | --
Executions: 1 | Duration: 17300ms

 at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 123
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.True(IWebDriver driver, Func`1 actual, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30
   at Microsoft.AspNetCore.Components.E2ETest.Tests.PerformanceTest.BenchmarksRunWithoutError() in /_/src/Components/test/E2ETest/Tests/PerformanceTest.cs:line 51
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass5_0.<True>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 103
```

**Closed** 2021-05-12 22:00 UTC
Labels: Working, area-blazor, feature-infrastructure-improvements, task, test-failure
