### ISSUE TITLE
[Blazor] Is ObjectGraphDataAnnotationsValidator production-ready?

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#31208] opened 2021-03-24 21:30 UTC
Hi,

Is there a reason why ``ObjectGraphDataAnnotationsValidator`` is still "experimental"? Can I use it in production? When will it be part of the official .NET?

Thanks.

**Comment by mkArtakMSFT** [comment] 2021-03-25 16:36
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/28640

**Closed by mkArtakMSFT** 2021-03-25 16:36 UTC
Labels: area-blazor
