### ISSUE TITLE
Debugging Blazor WASM in VS Code leaves process behind when finished

### ISSUE THREAD

**Issue by ar0311** [dotnet/aspnetcore#20223] opened 2020-03-27 03:31 UTC
### Describe the bug
When debugging Blazor WASM 3.2 preview 3 in VS Code and Chrome there is a process left behind after you stop debugging that prevents a subsequent debugging run as it still has ports 5000 and 5001 reserved.

### To Reproduce

Create a new Blazor WASM project. Debug it following the instructions on the blog here:

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available

Stop debugging.

Attempt to start a new debugging session.

Error in debug window:

```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address https://127.0.0.1:5001: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (48): Address already in use
```

A ps -ax | grep blazor reveals:

`59023 ??         0:05.00 dotnet /Users/adam/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/3.2.0-preview3.20168.3/build/../tools/blazor-devserver.dll serve --applicationpath /Users/adam/Repos/blazordebug/bin/Debug/netstandard2.1/blazordebug.dll`

Killing this process allows you to start a new debugging session as normal.

### Further technical details

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment] 2020-03-27 10:58
@ar0311 thanks for contacting us.

@SteveSandersonMS any ideas?

**Comment by SteveSandersonMS** [comment] 2020-03-27 11:02
Let's check with @NTaylorMullen whether the VS Code "stop debugging" gesture is meant to terminate the application process.

**Comment by NTaylorMullen** [comment] 2020-03-27 16:31
> Let's check with @NTaylorMullen whether the VS Code "stop debugging" gesture is meant to terminate the application process.

Yup it should. @ar0311 could you provide your `launch.json` contents?

**Comment by ar0311** [comment] 2020-03-27 22:12
Sure, it's just what was auto-generated by VS Code when opening the folder.

```
launch.json

{
   // Use IntelliSense to find out which attributes exist for C# debugging
   // Use hover for the description of the existing attributes
   // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (Blazor Standalone)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": ["run"],
            "cwd": "${workspaceFolder}",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        },
        {
            "name": ".NET Core Debug Blazor Web Assembly in Chrome",
            "type": "pwa-chrome",
            "request": "launch",
            "timeout": 30000,
            // If you have changed the default port / launch URL make sure to update the expectation below
            "url": "https://localhost:5001",
            "webRoot": "${workspaceFolder}",
            "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
        }
    ]
}
```

**Comment by ar0311** [comment] 2020-03-30 06:50
Doesn't seem to happen on Windows. Happens every time on MacOS though.

**Comment by sergiolindolfoferreira** [comment] 2020-03-31 16:22
I have the same problem.

**Comment by NTaylorMullen** [comment] 2020-04-15 21:22
So I'm able to reproduce the issue but I'm not quite sure where the problem lies (debugger, Blazor dev server, VSCode). 

@gregg-miskelly does the coreclr debug adapter control shutting down a launched program?

Background: Stopping an active debug session doesn't tear down the `dotnet run` Blazor WASM application on MacOS (works on Windows). This is the `launch.json`:
```JSON
{
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (Blazor Standalone)",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": ["run"],
            "cwd": "${workspaceFolder}",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        }
    ]
}
```

**Comment by gregg-miskelly** [comment] 2020-04-15 21:37
@NTaylorMullen `dotnet run` is not going to work if you actually want to debug anything -- you will wind up debugging a random `dotnet` process that doesn't load any use code. Stop debugging will wind up tearing down this `dotnet` process. Unless the child processes do something to detect when their parent dies then stop debugging would do nothing.

**Comment by NTaylorMullen** [comment] 2020-04-15 21:58
> @NTaylorMullen `dotnet run` is not going to work if you actually want to debug anything -- you will wind up debugging a random `dotnet` process that doesn't load any user code.

Ya in this case that's ok. Blazor WASM runs all of its .NET code in the browser in the Mono web assembly runtime. 

> Stop debugging will wind up tearing down this `dotnet` process.

Interesting, good to know that code lives onthat end.

> Unless the child processes do something to detect when their parent dies then stop debugging would do nothing.

Would you mind elaborating? Are you referring to the child processes re-booting the parent process when it detects it "stopping"?

**Comment by gregg-miskelly** [comment] 2020-04-16 00:13
`dotnet run` will cause a parent process to spin up that doesn't do much, it will then kick off a bunch of child processes where the real stuff happens (ex: processes to host msbuild during the build part, and then the app process to actually run). Stop debugging will issue a terminate on whatever process is being debugged. But you aren't debugging the useful processes. So unless they happen to do something to detect the death of their parent and treat that as a reason to exit, they will just keep on running.

**Comment by NTaylorMullen** [comment] 2020-04-16 18:14
@gregg-miskelly wouldn't dotnet run take care of tearing down its child processes though when it detects that it's shutting down?

**Comment by gregg-miskelly** [comment] 2020-04-17 01:59
No. It couldn't. When you press 'stop debugging' the debugger will just terminate it.

**Comment by NTaylorMullen** [comment] 2020-04-17 04:11
@gregg-miskelly sorry for all the questions, last one hopefully! Why on Windows do things "work"? Does windows `dotnet run` not create a child process?

**Comment by gregg-miskelly** [comment] 2020-04-17 04:26
My **guess** is that VS Code terminates debug adapters on Windows in a way that results in all their child processes getting killed (ex: they might be using a job object).

In case it isn't obvious, here are few ways to make this work:
1. For Blazor projects that have a web server side: just debug them like normal (point `program` at the dll that they build)
2. For Blazor projects that do NOT have a web server side, so you are just using a simple dev server that servers some static files, you have two options:
    A. Assuming there is a simple command to start this server, you give that command line (ex: `"program":"dotnet"`, `"args":"start-web-server-command-here"`).
    B. Don't use the debugger pipeline to start the web server at all. Instead, just automatically open a terminal window and run it. You might do this as part of project load, or make you could make a fake debug adapter type that gets redirected under the covers, but allows you to use a DebugAdapterDescriptorFactory that would spawn the server first.

**Comment by NTaylorMullen** [comment] 2020-04-17 04:46
> My **guess** is that VS Code terminates debug adapters on Windows in a way that results in all their child processes getting killed (ex: they might be using a job object).

Ah super interesting. That would make sense!



> In case it isn't obvious, here are few ways to make this work:

Appreciate the clarity! For Blazor projects that have a server side today we generate a launch.json that boots the server directly. For Blazor WASM (no debuggable server side) I was debating option A but didn't think of option B.

Thanks Gregg for your help, i'll have to play around with solutions 😄 !

**Comment by NTaylorMullen** [comment] 2020-04-21 20:55
After a few email threads we landed on two viable ways forward:
1.	Create a custom, simple debug adapter in O# to enable running the Blazor dev server and then tear down it and all of its child processes on “stop”.
2.	Expand the CoreCLR debug adapter to kill child processes and keep using `dotnet run`


We’re going to attempt doing 1 because changing something that hasn’t changed in 20 years or so is concerning. If 1 proves to be overly troublesome we’ll re-evaluate and potentially do 2.

**Comment by mkArtakMSFT** [comment] 2020-04-28 20:42
This is going to be handled as part of https://github.com/dotnet/aspnetcore/issues/19246

**Closed by mkArtakMSFT** 2020-04-28 20:42 UTC
Labels: area-blazor, blazor-wasm, enhancement
