### ISSUE TITLE
Please consider adding multipart-form-data

### ISSUE THREAD

**Issue by ak-hasanuzzaman** [dotnet/aspnetcore#46103] opened 2023-01-14 13:21 UTC
https://stackoverflow.com/questions/71047077/net-6-minimal-api-and-multipart-form-data

**Comment by davidfowl** [comment] 2023-01-14 17:20
This is coming in .NET 8 https://github.com/dotnet/aspnetcore/pull/44653.

Closing as dupe of https://github.com/dotnet/aspnetcore/issues/39430

**Closed by davidfowl** 2023-01-14 17:20 UTC
Labels: area-web-frameworks
