### ISSUE TITLE
Incorrect Razor error `The 'functions' directive must appear at the start of the line.`

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#32154] opened 2021-04-25 14:50 UTC
### Describe the bug
Switched from `.NET 5.0` to `.NET 6.0 preview 5` and Razor started erroring `RZ2005`

**Note:** The error probably thinks its being triggered correctly as look at the source Column it is reporting for (even though its in first column)

In VS

![image](https://user-images.githubusercontent.com/1142958/115998063-6bcec300-a5dd-11eb-8e19-5b3c109b6023.png)

At CLI
```
...\Attributes.cshtml(205,9530): error RZ2005: The 'functions` directive must appear at the start of the line. 
...\Recipe.cshtml(274,13502): error RZ2005: The 'functions` directive must appear at the start of the line. 
...\Menu.cshtml(101,3953): error RZ2005: The 'functions` directive must appear at the start of the line. 
```

### To Reproduce

Haven't yet been able to isolate; new web project and current web project are both using `CRLF` so not that.

### Further technical details
- ASP.NET Core version: `Microsoft.AspNetCore.App 6.0.0-preview.5.21224.3`
```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21225.4
 Commit:    474224c41a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21225.4\

Host (useful for support):
  Version: 6.0.0-preview.5.21224.1
  Commit:  e5dd7150e6

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21225.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21224.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21224.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21224.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- VS: Version `16.10.0 Preview 2.1`

**Comment by mkArtakMSFT** [comment] 2021-04-26 16:32
Thanks for reporting this. This is a dupe of #31783.

**Comment by mkArtakMSFT** [comment] 2021-04-26 16:34
@benaadams can you share a small sample app for us to take a closer look? Thanks!

**Comment by benaadams** [comment] 2021-04-26 16:41
>  can you share a small sample app for us to take a closer look? Thanks!

I can't generate it in an isolated repo yet 😥

Also it doesn't look like its the column number of the generated source (from https://github.com/dotnet/aspnetcore/issues/31783) as that looks fine; it looks like its more the character index from the start (ignoring line endings) rather than than the column on that line being used.

Also the generated source doesn't have a `@function` directive so isn't from that :)

**Comment by captainsafia** [comment] 2021-04-26 20:01
@benaadams Yep -- also just realized that the issue you are describing repros in the CLI so it is likely not related to the VS issue referenced above.

I've been trying to get a repro with the different variations of `@functions` syntax but haven't had any luck. :/

> Also the generated source doesn't have a @function directive so isn't from that :)

Are you able to share an upload of the `obj` directory and the binlog from a build that repros? There might be some helpful clues in there.

```
$ dotnet build /bl /p:EmitCompilerGeneratedFiles=true
```

**Comment by benaadams** [comment] 2021-04-26 20:21
Should this line [SourceTextSourceLineCollection.cs#L30-L34](https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/RazorSdk/SourceGenerators/SourceTextSourceLineCollection.cs#L30-L34) be changed to something like
```diff
internal override SourceLocation GetLocation(int position)
{
    var line = _textLines.GetLineFromPosition(position);
-   return new SourceLocation(_filePath, position, line.LineNumber, position);
+   return new SourceLocation(_filePath, position, line.LineNumber, position - line.Start);
}
```

Since the params are `SourceLocation(string filePath, int absoluteIndex, int lineIndex, int characterIndex)`; so its putting the absoluteIndex in as the characterIndex?

**Comment by benaadams** [comment] 2021-04-26 21:14
That looks to fix it

**Comment by benaadams** [comment] 2021-04-26 21:25
Added PR https://github.com/dotnet/sdk/pull/17204

**Closed** 2021-04-27 03:28 UTC
Labels: area-razor.compiler, feature-razor.language
