### ISSUE TITLE
Unable to debug/launch Blazor WASM application after changing Environment variables

### ISSUE THREAD

**Issue by BiggT76** [dotnet/aspnetcore#23536] opened 2020-06-30 20:52 UTC
I'm currently using VS 2019 Preview (16.7.0 Preview 3.1) and when I run my hosted Blazor WASM application normally, it launches and will debug as expected.  However, we created secondary launch profiles to aid in publishing to our test server which contained a custom environment variable: `"ASPNETCORE_ENVIRONMENT": "Test"`.  While we could build and publish, we could not debug.  I also tried changing the default variables from "Development" and the application will not launch.

### To Reproduce
Here you can find a quick repro of the issue using the standard Wasm 3.2.0 hosted template (updated launchSettings.json files and Server.Startup.cs to check for variables and enable WASM debugging): [https://github.com/BiggT76/BlazorWasmEnvironmentVariables/tree/master](url).

### Exceptions (if any)
The browser window gives a 404 

### Further technical details
VS 2019 Preview (16.7.0 Preview 3.1)

`dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.4.20258.7
 Commit:    65f0fc2cad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.4.20258.7\

Host (useful for support):
  Version: 5.0.0-preview.4.20251.6
  Commit:  47ec733ba7

.NET SDKs installed:
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.515 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.4.20258.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.4.20257.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.4.20251.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`

**Comment by javiercn** [comment] 2020-07-01 08:04
@BiggT76 thanks for contacting us.

* Can you clarify what you mean by "The application will not launch"?
* Does the application not start at all?
* Do you get a 404 in the browser?

It is likely that you need to plug-in static web assets explicitly if you are using other environments (Call webHost.UseStaticWebAssets()) as we only plug it in for development scenarios.

**Comment by rahuldj** [comment] 2020-07-01 08:23
@javiercn: Seems to be the same issue as https://github.com/dotnet/aspnetcore/issues/21992.

When you change environment variable (ASPNETCORE_ENVIRONMENT) to anything except "Development", the application stops working. All blazor URLs return 404 and you get error like this in console.

Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'Fallback {*p'sath:nonfile}'

The easiest way to reproduce this issue is to create a new blazor wasm project and then in launchsettings.json, modify ASPNETCORE_ENVIRONMENT to anything except Development. The project will stop working.

I should mention that I had reproduced this issue with  Host: 3.1.4 and SDK: 3.1.300. (The RTM 3.1 build.)
It appears that reporter above mentions it's also reproducible with net5 preview builds.

**Comment by BiggT76** [comment] 2020-07-01 14:13
@rahuldj: Thanks for helping me clarify.

I just created a new project from the .NET 5.0.100-preview.6 build for WASM and can confirm that changing the environment variable breaks debugging.  I also received this error which I've seen with prior versions of .NET:


![image](https://user-images.githubusercontent.com/6043075/86254102-5dfa0e00-bb83-11ea-962b-1fc3b0a96244.png)

**Comment by mkArtakMSFT** [comment] 2020-07-01 16:26
Thanks for contacting us.
This is a dupe of #21466.

**Closed by mkArtakMSFT** 2020-07-01 16:26 UTC
Labels: Needs: Attention :wave:, area-blazor

**Comment by captainsafia** [comment] 2020-07-01 16:34
@BiggT76 The issue referenced above is the ideal long-term solution for this.

For your scenario, since you're running on a hosted template, you can manually change the environment check which prevents the debugging proxy from being launched in non-dev environments.

To do this, you can remove the if-statement in the following lines in your Startup.cs.

```csharp
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBlazorDebugging();
            }
```

**Comment by BiggT76** [comment] 2020-07-01 18:01
@captainsafia: Thanks for the info.  

We had already updated the conditional you referenced to correctly enable/disable debugging based on the necessary variable.  Thankfully they work in our hosting environment we just can't debug them.

**Comment by captainsafia** [comment] 2020-07-06 19:38
> Thankfully they work in our hosting environment we just can't debug them.

Hmm. Can you clarify what you mean here?

**Comment by BiggT76** [comment] 2020-07-06 20:05
We cannot launch the application from Visual Studio once the environment variables have been changed (in order to debug the app).  If we build and publish the solution with the desired environment variable, all conditionals/functions that hinge on this variable work as expected.
