### ISSUE TITLE
OpenApi inline enum for query parameters

### ISSUE THREAD

**Issue by dnv-kimbell** [dotnet/aspnetcore#57979] opened 2024-09-20 07:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an operation with that takes in an enum as query string parameter, and returns it back in the response.

In the parameter section, the enum is just defined as string with no information about what valid values are
```json
"parameters": [
	{
		"name": "e",
		"in": "query",
		"schema": {
			"type": "string"
		}
	}
],
```
In the response the enum is referenced and it's possible to figure out valid values

```json
"responses": {
	"200": {
		"description": "OK",
		"content": {
			"application/json": {
				"schema": {
					"$ref": "#/components/schemas/EnumWithNoFlags"
				}
			}
		}
	}
}

```

### Expected Behavior

The query parameter should use a reference to the enum schema.

### Steps To Reproduce

https://github.com/dnv-kimbell/openapi-inlineschema

### .NET Version

9.0 RC1

**Comment by martincostello** [comment] 2024-09-21 08:07
Just spotted this one myself with version `9.0.100-rc.2.24468.2` of the SDK and `9.0.0-rc.2.24470.14` of the M.A.OpenApi library.

With https://github.com/martincostello/openapi-extensions/pull/103/commits/5742a21726f9e1ff99688989e72ffbc0a8fa05ad I get an empty enum for [`CarType`](https://github.com/martincostello/openapi-extensions/blob/5742a21726f9e1ff99688989e72ffbc0a8fa05ad/tests/Models.B/CarType.cs#L9):

```json
"CarType": {
  "type": "integer",
  "description": "The type of the car."
}
```

**Comment by captainsafia** [comment] 2024-09-22 22:35
> The query parameter should use a reference to the enum schema.

The behavior that I find surprising here is that the schemas generated for the response and the query parameter are different. The schema generated by the query parameter uses a `type: string` with no enum list configured, whereas the schema configured for the response contains the correct enum listing. The difference in behavior between the two is the actual source of the issue.

Upon further debugging, the issue seemed to only manifest for endpoints that used controller actions (as opposed to minimal APIs) which is particularly strange given that the schema generation logic is shared between the two.

Some further debugging reveals that this might be an issue with the ApiExplorer layer for MVC because the `ApiParameterDescription` generates a default type of `string` for this argument:

<img width="197" alt="image" src="https://github.com/user-attachments/assets/ec990dbb-471a-454b-9952-8297595f2a80">

Based on the logic [here](https://github.com/dotnet/aspnetcore/blob/e9160bede6d2dd80e6a46428647270b82837bbcc/src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs#L669-L678). My suspicion gravitated towards the recent changes we made to ModelMetadata to support native AoT since the referenced method interacts with the `IsParsable` and `IsConvertibleType` properties that we recently modified as a result of this work although that doesn't appear to be the case.

It seems like the actual root cause is some code that we added in https://github.com/dotnet/aspnetcore/commit/46b5580e8a7ba2375820d95e3af80637be69f9de that set the parameter type of simple types (including those that can be parsed from an enum) to `string` to support the introduction of `TryParse` binding support in MVC. Ultimately, that appears to be the issue.

Anyhow, I've figured out a bug fix for this that I hope to include in .NET 9 but figured I'd monologue a bit about the root case here for posterities sake.

**Comment by captainsafia** [comment] 2024-09-26 19:50
@dnv-kimbell  The fix for this has landed in nightly package version `9.0.0-rtm.24476.2`.

You'll need to use the following `PackageReference`:

```
<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0-rtm.24476.2" />
```

And make sure that you have a reference to the nightly dotnet9 feed in your `nuget.config` file:

```
<add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
```

Can you let me know if that works for you?

**Comment by dnv-kimbell** [comment] 2024-09-27 05:24
When I try that package, I get a reference to the enum from the query section, both with and without flags, so it seems to be working as expected.

```json
"parameters": [
	{
		"name": "e",
		"in": "query",
		"schema": {
			"$ref": "#/components/schemas/EnumWithFlags"
		}
	}
],

"parameters": [
	{
		"name": "e",
		"in": "query",
		"schema": {
			"$ref": "#/components/schemas/EnumWithNoFlags"
		}
	}
],
```

**Comment by captainsafia** [comment] 2024-09-27 05:58
@dnv-kimbell Great! Thanks for verifying. Closing this bug as fixed.

**Closed by captainsafia** 2024-09-27 05:58 UTC
Labels: area-mvc, Needs: Attention :wave:, feature-openapi, area-minimal
