### ISSUE TITLE
Template UX refresh

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#40935] opened 2022-03-29 15:12 UTC
This issue tracks the changes to the templates in the .NET 7.0 timeframe. This includes things like updating Bootstrap and any refresh to the look and feel in the templates we want to do.

**Comment by lonix1** [comment] 2022-06-01 03:33
Actually the latest version of Bootstrap doesn't use jQuery. So the only reason to use jQuery is for "jQuery Validation" and "jQuery Validation Unobtrusive", both of which work but are old and gnarly (especially the latter, which [needs work](https://github.com/aspnet/jquery-validation-unobtrusive/issues/104)). Maybe there's a modern/better validation library that doesn't need jQuery.

**Comment by TanayParikh** [comment] 2022-11-09 01:06
Related:
https://github.com/dotnet/aspnetcore/issues/44606
https://github.com/dotnet/aspnetcore/issues/25631

**Comment by Alerinos** [comment] 2023-02-02 15:30
It is also worth adding in the template ``data-nosnippet`` for all elements that are not to be displayed in search engines such as Bing, Google.

https://developers.google.com/search/docs/advanced/robots/robots_meta_tag#data-nosnippet-attr

https://github.com/dotnet/blazor-samples/pull/68

**Comment by Alerinos** [comment] 2023-02-05 09:40
When updating the templates, you can think about a new solution for connecting to the server.

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md#automatically-refresh-the-page-when-reconnection-fails-blazor-server

@javiercn I can help. Which repository is the template in?

**Comment by codemonkey85** [comment] 2023-02-15 05:03
One thing I'd like to see is a change from packaging a specific version of bootstrap / open iconic to relying on libman and specifying the version number there. That would make it easier to change or update the version being used from the template, after creating a new project.

**Comment by mrlife** [comment] 2023-02-23 13:59
Are there any plans to consider using https://github.com/microsoft/fast or https://github.com/microsoft/fast-blazor?

**Comment by Lumethys** [comment] 2023-03-14 01:13
an idea is to look at other frameworks are doing: A option in the scaffolding would be the best option, let the dev decide whether they like jquery, alpine or some sort of blazor WASM solution

**Comment by FabianAronsson** [comment] 2023-05-04 16:49
> an idea is to look at other frameworks are doing: A option in the scaffolding would be the best option, let the dev decide whether they like jquery, alpine or some sort of blazor WASM solution

I agree. Different projects require different implementations and it should be easy to choose what your specific project needs.
Keep Bootstrap, but perhaps refresh it a little and also add some other new popular framework.

**Comment by mkArtakMSFT** [comment] 2023-05-25 16:55
Moving this as we didn't get to updating the templates in .NET 8. Moving to .NET 9.

**Comment by Alerinos** [comment] 2023-05-25 23:32
@lonix1 You can do the implementation of the libraries yourself. Besides, you don't use jquery anymore. In addition, we now have WebAssembly Blazor which is being heavily developed. The change was only supposed to be about cosmetics of the finished template.

**Comment by main-laurensoft** [comment] 2023-06-11 16:04
We have CSS Grid / Flexbox / CSS Variables and a lot of things else; I don't understand why people prefer to install things with more complexities to use ... Bootstrap and jQuery...  Why? jQuery, we have Alpine.JS / HTMX (also good for simple things) for people that do not like the weird JavaScript like me. But TS makes JS more pleasurable not like the beauty of CSharp but more pleasure with types... "Blazor United we are waiting for you XDD \o/". So, jQuery we understand, because a lot of people do not like JS, but like I said Alpine and HTMX resolve what is needed. Bootstrap I don't understand. When I'm going to buy a course and I see bootstrap I go next... I learned Bootstrap once, before modern CSS layouts to be introduced. Even so, I didn't like it. Because I must use a class created for others, install packages, following rules that change version to version ... But today... `display: grid` only with these things already get better lol .... we do use frameworks outside; the company I work for, we use Vanilla HTML / Vanilla CSS / Alpine - Vanilla JS (for quite simple tasks), we work with Sveltekit (with Typescript) for a good part of company work (for things that need to be dynamics; interactivity). and for large things the company I work rely on .NET Razor Pages, and now that with Minimal API with svelte became a wonderful thing that we got the authorization to use, and understand (but Blazor United can be the new kid on the ground for us) in this area ... In the company I work for, we follow a rule that is: less inside template, do you want to use Bootstrap makes easy installation, do not make the developer swallow it out of the box, want jQuery (or better saying Alpine) make easy installation. Like Sveltekit that makes simple, want TS ? say Y (yes), want prettier? say Y (yes) etc. ...  

ps.: I know that some people work a long date with bootstrap each version things get better, seems like today flexbox is inside, but; to give option before to create template is the way to go ...

**Comment by mkArtakMSFT** [comment] 2024-10-29 21:29
Closing as a dupe of #53142

**Closed by mkArtakMSFT** 2024-10-29 21:29 UTC
Labels: enhancement, Priority:1, feature-templates, area-ui-rendering
