### ISSUE TITLE
<select> binding not working properly on Firefox

### ISSUE THREAD

**Issue by baartho** [dotnet/aspnetcore#18129] opened 2020-01-04 19:16 UTC
### Describe the bug
_select_ binding not working properly on Firefox if I mix clicking with typing. 

https://vimeo.com/382797982

As you can see on the video binding for 5 and 6 does not work. Please notice that this is an intermittent issue. It happened for 5 and 6 on this video, but it could happen to any number (and work for 5 and 6). 

### To Reproduce

1- Click on the _select_
2 - Type the number of an option (0 to 9)
3 - Click again on the _select_ (and not on one of its _options_)

### Further technical details
- Blazor 3.1.1 
- Firefox 71.0 (64-bits)
- VS Community 2019 16.4.2

``` 
@page "/counter"

@prop

<select class="select" style="text-align: center;width: 75px;padding: 6px 8px;padding-right: 0px;"
        @bind="prop">
    @for (int i = 0; i <= 10; i++)
    {
        <option value="@i">@i</option>
    }
</select>

@code {
    decimal prop;
}
```

**Comment by baartho** [comment] 2020-01-09 15:14
FYI this might actually be a firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1607038

**Comment by enetstudio** [comment] 2020-01-11 12:33
@baartho, I ran your code but could not reproduce the 'bug'. It works perfectly well. 

Why do you use decimal data type ?
I watched your video. It starts with the digit 4 displayed in the text portion of the select element, while the prop variable contains 2. Is this another bug you forgot to relate to ?

**Comment by baartho** [comment] 2020-01-14 17:09
@enetstudio I believe this is a firefox bug as stated above. 

This is not very easy to reproduce. As you will see I've to try several times to make it happen. It took more than 1 minute on my end. The steps are:

1- Click on the arrow icon pointing down (on the box that holds the icon actually) I'm not sure if you really have to click on it, but this is where I've been clicking.
2 - TYPE a random number from 1 to 9 on your keyboard
3 - Click again on the arrow icon.

-------- 

Those are the notes from another person on how to reproduce the issue: 

 I was able to reproduce the issue on Win10x64 with Firefox versions 72.0.1, 73.0b2 and 74.0a1, following the below steps, after running the html file through a local host:

Click on the drop-down arrow icon.
- Quickly, type "1" several times and click again on the drop-down arrow icon.
- Click on the drop-down arrow icon.
- Quickly, type a number and click again on the drop-down arrow icon.
- Repeat steps 3 and 4 until the number from the drop-down doesn't coincide with the number outside of it.

The issue couldn't be reproduced on Mac 10.14 and Ubuntu 18.04 with Firefox versions 72.0.1, 73.0b2 and 74.0a1.

**Comment by mkArtakMSFT** [comment] 2020-03-02 18:37
Closing as external. Thanks!

**Closed by mkArtakMSFT** 2020-03-02 18:37 UTC
Labels: External, area-blazor, investigate
