### ISSUE TITLE
Startup class in a library is not working

### ISSUE THREAD

**Issue by iiibbbmmm** [dotnet/aspnetcore#28722] opened 2020-12-18 09:44 UTC
### Describe the bug
Startup class in a library is not working

### To Reproduce

1. Create a new WebApplication with ASP.NET Core Web API presets (no HTTPS/Docker/OpenAPI).
2. Create a new ClassLibrary(.NET Core) in the same solution.
3. Reference ClassLibrary by WebApplication.
4. Shift+Drag the Startup.cs from WebApplication to ClassLibrary.
5. Put these in ClassLibrary.csproj.
```xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

6. Press F5.

### Exceptions (if any)
HTTP ERROR 404

### Further technical details
- ASP.NET Core version
5.0
- Include the output of `dotnet --info`
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\dev\projects\aspnetcore-test\WebApplication1
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
VS 2019 16.8.3

**Comment by Tratcher** [comment] 2020-12-18 20:33
Duplicate of https://github.com/dotnet/aspnetcore/issues/7315.

**Comment by shirhatti** [comment] 2020-12-18 22:17
Closing as dupe

**Closed by shirhatti** 2020-12-18 22:17 UTC
Labels: area-hosting
