### ISSUE TITLE
Asp.net Blazor RC1 Virtualize Component breaks with different height items

### ISSUE THREAD

**Issue by chrdlx** [dotnet/aspnetcore#26099] opened 2020-09-19 15:58 UTC
I'm having problems with the Virtualize component....  it only seems to work if all the items are exactly the same height.
In the provided example (https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1),  if a row has a text that wraps to the next line (different items heights),  the whole virtualization breaks.  It doesn't throw an exception but it starts rendering unrelated items, and the scroll goes anywhere.

This could be a limitation by design, but I couldn't find more information about it, so I'm filling a bug,  sorry if it's not.

Regards

**Comment by chrdlx** [comment] 2020-09-19 16:32
[VirtualizeTest.zip](https://github.com/dotnet/aspnetcore/files/5250160/VirtualizeTest.zip)

I attach the VS project to reproduce this...  just go to the Counter component page....  start decreasing the browser size until the text starts wrapping to the next line, and you will see that the scroll starts failing and also the rendering of items.

Also, I tried this in Chrome,  in Edge (Microsoft Edge 44.19041.423.0) it doesn't even display the items.

**Comment by SteveSandersonMS** [comment] 2020-09-21 09:56
Yes, this is by design.

It's not meaningful to support scrolling to arbitrary points if the items aren't a known height. How can the system know the total scroll range within rendering all the items in this case?

There are two ways we *could* try to enhance to support this in the future:

 * Offering some callback that developers could use to return the height of the Nth item
 * Or, like some 3rd-party virtualization mechanisms, just assume the heights are fixed even when they aren't, and then each time an item is rendered, update the information and try to adjust the scroll range to match. This results in some pretty strange scrolling behavior, so is not an ideal solution.

**Comment by SteveSandersonMS** [comment] 2020-10-07 10:38
Just realised this is a duplicate of #25058

**Closed by SteveSandersonMS** 2020-10-07 10:38 UTC
Labels: area-blazor
