### ISSUE TITLE
Error "View Index.cshtml not found" and also .html caused by missing Packages which were not needed before .net 6.0.2

### ISSUE THREAD

**Issue by schamal2205** [dotnet/aspnetcore#40454] opened 2022-02-22 14:56 UTC
### Description
Since few Days ago, after updating our application to .net 6.0.2 all views where missing in the DLLs under AspNetCoreGeneratedDocument. 
After bit of researching we figured out that the following error could cause the error. 
```
2022-02-17T21:10:20.2925355Z    102>CSC : warning CS8032: An instance of analyzer Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator cannot be created from C:\hostedtoolcache\windows\dotnet\sdk\6.0.200\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. 
```
So after that we have added the following to all projects containing .cshtml and .html files and everything worked as expected again: 
```yaml
<PackageReference Include="Microsoft.CodeAnalysis.Compilers" Version="4.1.0" />
<PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.1.0">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

Was there any major change in 6.0.2 that these packages are not delivered by default anymore? 
I would assume that this problem will raise to everyone with .cs/html files updating to .net 6.0.2 in the next days. 

### Configuration

* Which version of .NET is the code running on? .NET 6.0.2

**Comment by mkArtakMSFT** [comment] 2022-04-12 16:46
Thanks for contacting us. This is a dupe of https://github.com/dotnet/sdk/issues/23972

**Closed by mkArtakMSFT** 2022-04-12 16:46 UTC
Labels: area-mvc
