### ISSUE TITLE
Blazor WebAssembly Standalone does not launch with .NET 6 Preview3

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#31791] opened 2021-04-14 05:44 UTC
### Describe the bug
Blazor WebAssembly Fails to launch with default hosting model (InProcess) after migrating to .NET6 Preview 3. This is working with .NET5.0.

### To Reproduce
No custom code is needed to reproduce. Just create a new Blazor WebAssembly Standalone project from Visual Studio 2019. 
![image](https://user-images.githubusercontent.com/13166236/114659602-c8aaaf00-9ca8-11eb-9276-1a195f6c9ff2.png)

### Build it and run
You will getting the InProcess error, 
![image](https://user-images.githubusercontent.com/13166236/114659458-83867d00-9ca8-11eb-8249-a08f1cc5370f.png)

###  Switch Project back to .NET5.0, everything works
![image](https://user-images.githubusercontent.com/13166236/114659777-0dcee100-9ca9-11eb-952b-da1e7a397caa.png)

### Further technical details
- NET SDK 6.0.100-preview.3
- Visual Studio 16.10 Preview

**Comment by javiercn** [comment] 2021-04-14 08:45
@ameyasubhedar thanks for contacting us.

Does a new application also fail to run for you? 

If you updated from 5.0 to 6.0 preview 3, can you compare that with a brand new application to see if you spot any difference?

**Comment by pranavkm** [comment] 2021-04-14 13:26
Dupe of https://github.com/dotnet/aspnetcore/issues/30917. We fixed this in 6.0-preview4. In the meanwhile, running it without IIS should work.

**Comment by ameyasubhedar** [comment] 2021-04-14 16:28
@javiercn, yes a new application and old application both fails to run.

**Closed** 2021-04-21 20:04 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Needs: Attention :wave:, Status: Resolved, area-runtime, servers-iis
