### ISSUE TITLE
Blazor WASM hosted on IIS 10 log in exception for some users.

### ISSUE THREAD

**Issue by Kazbek** [dotnet/aspnetcore#23215] opened 2020-06-22 12:34 UTC
### Describe the bug
I`m using blazor webassembly with authorization on IdentityServer (as from the box). Now app published on IIS 10. And 4 user of 200+ registered when login has this error:
![image](https://user-images.githubusercontent.com/15718432/85285793-2fe93f80-b49a-11ea-96f6-62cf63861960.png)

Some of them use Google Chrome, some Mozilla Firefox

### To Reproduce
I can't reproduce that. For them reauthorize doesn`t help (also cache clearing) but they can log in from other devices.

### Exceptions
When I login myself (withoit error). Browser console log: All Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1] have index '[1]'.

```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[100]
      Start processing HTTP request POST https://ismc.academy/Course.Course/GetCourseIndex
blazor.webassembly.js:1 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[100]
      Start processing HTTP request POST https://ismc.academy/UserInfo.UserInfo/GetCurrentUserShortName
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[100]
      Sending HTTP request POST https://ismc.academy/Course.Course/GetCourseIndex
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[100]
      Sending HTTP request POST https://ismc.academy/UserInfo.UserInfo/GetCurrentUserShortName
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[101]
      Received HTTP response after 243.53ms - OK
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[101]
      End processing HTTP request after 489.965ms - OK
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[101]
      Received HTTP response after 379.355ms - OK
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[101]
      End processing HTTP request after 784.4049ms - OK
blazor.webassembly.js:1 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
```

When I log in as user who has error (I don`t have error but anyway) some of Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2] (have number 2 and failed).
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[100]
      Start processing HTTP request POST https://ismc.academy/Course.Course/GetCourseIndex
blazor.webassembly.js:1 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
blazor.webassembly.js:1 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[100]
      Start processing HTTP request POST https://ismc.academy/UserInfo.UserInfo/GetCurrentUserShortName
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[100]
      Sending HTTP request POST https://ismc.academy/Course.Course/GetCourseIndex
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[100]
      Sending HTTP request POST https://ismc.academy/UserInfo.UserInfo/GetCurrentUserShortName
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[101]
      Received HTTP response after 203.9549ms - OK
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[101]
      End processing HTTP request after 511.6849ms - OK
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.ClientHandler[101]
      Received HTTP response after 233.73ms - OK
blazor.webassembly.js:1 info: System.Net.Http.HttpClient.AuthCenter.gRPC.LogicalHandler[101]
      End processing HTTP request after 437.115ms - OK
blazor.webassembly.js:1 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
```

But on screenshot from the user I see only failed with number 2 and none of DefaultAuthorizationService[1] (I apologize for the quality of the screenshot, it was sent by the user):
![image](https://user-images.githubusercontent.com/15718432/85286405-417f1700-b49b-11ea-8faa-8fd8fbbfd17b.png)

### A bit of code

Program.cs
```
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("app");

builder.Services.AddHttpClient("AuthCenter.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
    .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

builder.Services.AddHttpClient("AuthCenter.gRPC", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
    .ConfigurePrimaryHttpMessageHandler(() => new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler()))
    .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("AuthCenter.ServerAPI"));

builder.Services.AddOptions();
builder.Services.AddAuthorizationCore();
builder.Services.AddApiAuthorization(options =>
{
    options.UserOptions.RoleClaim = "role";
}).AddAccountClaimsPrincipalFactory<RolesClaimsPrincipalFactory>(); ;

builder.Services.AddScoped<ICurrentUserService, CurrentUserService>();

builder.Services.AddScoped(services =>
{
    var httpClient = services.GetRequiredService<IHttpClientFactory>().CreateClient("AuthCenter.gRPC");
    var channel = GrpcChannel.ForAddress(httpClient.BaseAddress, new GrpcChannelOptions { HttpClient = httpClient });
    return new UserInfo.UserInfoClient(channel);
});

builder.Services.AddScoped(services =>
{
    var httpClient = services.GetRequiredService<IHttpClientFactory>().CreateClient("AuthCenter.gRPC");
    var channel = GrpcChannel.ForAddress(httpClient.BaseAddress, new GrpcChannelOptions { HttpClient = httpClient });
    return new Course.CourseClient(channel);
});

builder.Services.AddScoped(services =>
{
    var httpClient = services.GetRequiredService<IHttpClientFactory>().CreateClient("AuthCenter.gRPC");
    var channel = GrpcChannel.ForAddress(httpClient.BaseAddress, new GrpcChannelOptions { HttpClient = httpClient });
    return new StudyGroups.StudyGroupsClient(channel);
});

builder.Services.AddBlazoredModal();
builder.Services.AddBlazoredToast();
builder.Services.AddScoped<IToastService, ToastService>();

await builder.Build().RunAsync();
```

RolesClaimsPrincipalFactory.cs
```
public class RolesClaimsPrincipalFactory : AccountClaimsPrincipalFactory<RemoteUserAccount>
{
    public RolesClaimsPrincipalFactory(IAccessTokenProviderAccessor accessor) : base(accessor)
    {
    }

    public override async ValueTask<ClaimsPrincipal> CreateUserAsync(RemoteUserAccount account, RemoteAuthenticationUserOptions options)
    {
        var user = await base.CreateUserAsync(account, options);
        if (user.Identity.IsAuthenticated)
        {
            var identity = (ClaimsIdentity)user.Identity;
            var roleClaims = identity.FindAll(identity.RoleClaimType);
            if (roleClaims != null && roleClaims.Any())
            {
                foreach (var existingClaim in roleClaims)
                {
                    identity.RemoveClaim(existingClaim);
                }

                var rolesElem = account.AdditionalProperties[identity.RoleClaimType];
                if (rolesElem is JsonElement roles)
                {
                    if (roles.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var role in roles.EnumerateArray())
                        {
                            identity.AddClaim(new Claim(options.RoleClaim, role.GetString()));
                        }
                    }
                    else
                    {
                        identity.AddClaim(new Claim(options.RoleClaim, roles.GetString()));
                    }
                }
            }
        }

        return user;
    }
}
```

### Further technical details

![image](https://user-images.githubusercontent.com/15718432/85287118-7b045200-b49c-11ea-8e91-0493b4107a40.png)

> dotnet --info
> Џ ЄҐв SDK ¤«п .NET Core (®ва ¦ ойЁ© «оЎ®© global.json):
>  Version:   3.1.301
>  Commit:    7feb845744
> 
> ‘аҐ¤  ўлЇ®«­Ґ­Ёп:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.301\
> 
> Host (useful for support):
>   Version: 3.1.5
>   Commit:  65cd789777
> 
> .NET Core SDKs installed:
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
>   2.1.403 [C:\Program Files\dotnet\sdk]
>   2.1.502 [C:\Program Files\dotnet\sdk]
>   2.1.505 [C:\Program Files\dotnet\sdk]
>   2.2.101 [C:\Program Files\dotnet\sdk]
>   3.1.101 [C:\Program Files\dotnet\sdk]
>   3.1.301 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

> VisualStudio.16.Release/16.6.2+30204.135
> 
> ASP.NET and Web Tools 2019   16.6.948.25768
> ASP.NET and Web Tools 2019
> 
> ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
> Provides languages services for ASP.NET Core Razor.

I’m sorry if I did something wrong, for a week now we can’t find the cause of this problem.

**Comment by javiercn** [comment] 2020-06-22 13:36
@Kazbek thanks for contacting us.

Are you saying that clearing the local/session storage doesn't fix the issue?

Are they able to login if they use InPrivate browsing?
Does this error happen right away or after they've had a tab open for some time?

The code you have looks right to me, but at the same time I'm not sure what is going wrong.

**Comment by Kazbek** [comment] 2020-06-22 13:48
> Are you saying that clearing the local/session storage doesn't fix the issue?
> Are they able to login if they use InPrivate browsing?

Doesn`t fix. Neither login use InPrivate browsing.

> Does this error happen right away or after they've had a tab open for some time?

This happen right after tab open and loaded. All pages of app have [Authorize] attribute.
Also app serving method have [Authorize] attribute. So they are successful log in on login page. (Scaffolded Identity pages)

```
[Authorize(AuthenticationSchemes = "Identity.Application")]
public class GatewayModel : PageModel
{
    public IActionResult OnGet([FromServices] IWebHostEnvironment webHost)
    {
        var file = webHost.WebRootFileProvider.GetFileInfo("index.html");
        return PhysicalFile(file.PhysicalPath, "text/html");
    }
}
```

And this is Authentication component which is a bit modified.
```
@page "/authentication/{action}"
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication

@inject NavigationManager Navigation
@inject IJSRuntime JSRuntime
<div class="col-12">
    <div class="rounded-block">
        <div class="row">
            <div class="col-12">
                <RemoteAuthenticatorView Action="@Action" OnLogOutSucceeded="OnLogOutSucceededHandler" OnLogInSucceeded="OnLoginSucceededHandler">
                    <LoggingIn>
                        <h4>Авторизация...</h4>
                    </LoggingIn>
                    <CompletingLoggingIn>
                        <h4>Авторизация...</h4>
                    </CompletingLoggingIn>
                    <LogOut>
                        <h4>Завершение сессии...</h4>
                    </LogOut>
                    <CompletingLogOut>
                        <h4>Завершение сессии...</h4>
                    </CompletingLogOut>
                </RemoteAuthenticatorView>
                <div class="progress">
                    <div class="indeterminate"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@code{
    [Parameter] public string Action { get; set; }

    private async Task OnLogOutSucceededHandler()
    {
        await JSRuntime.InvokeVoidAsync("GoToLink", System.IO.Path.Combine(Navigation.BaseUri, "Identity/Account/Login"));
    }

    private async Task OnLoginSucceededHandler()
    {
        Console.WriteLine("OnLoginSucceededHandler");
    }
}

```

**Comment by javiercn** [comment] 2020-06-22 14:00
```csharp
[Authorize(AuthenticationSchemes = "Identity.Application")]
public class GatewayModel : PageModel
{
    public IActionResult OnGet([FromServices] IWebHostEnvironment webHost)
    {
        var file = webHost.WebRootFileProvider.GetFileInfo("index.html");
        return PhysicalFile(file.PhysicalPath, "text/html");
    }
}
```

That looks wrong, why are you passing a scheme to [Authorize]?

Can you produce a minimal repro project on a public location so that we can take a look at it and try to help you?

**Comment by javiercn** [comment] 2020-06-22 14:02
>     private async Task OnLogOutSucceededHandler()
>     {
>         await JSRuntime.InvokeVoidAsync("GoToLink", System.IO.Path.Combine(Navigation.BaseUri, "Identity/Account/Login"));
>     }

This also doesn't seem right, you shouldn't send  users to identity directly to be authenticated. `authentication/login` is responsible for starting the authentication flow.

**Comment by Kazbek** [comment] 2020-06-22 14:30
> ```cs
> [Authorize(AuthenticationSchemes = "Identity.Application")]
> public class GatewayModel : PageModel
> {
>     public IActionResult OnGet([FromServices] IWebHostEnvironment webHost)
>     {
>         var file = webHost.WebRootFileProvider.GetFileInfo("index.html");
>         return PhysicalFile(file.PhysicalPath, "text/html");
>     }
> }
> ```
> 
> That looks wrong, why are you passing a scheme to [Authorize]?
> 
> Can you produce a minimal repro project on a public location so that we can take a look at it and try to help you?

This just help me to avoid scenario when new user loads app, then redirected to login page and again load app. He just start with login page.

I can clear my project of business logic and publish it, will it be useful?

> This also doesn't seem right, you shouldn't send users to identity directly to be authenticated. authentication/login is responsible for starting the authentication flow.

Here the problem is precisely in the redirection, or precisely in its address? I do not want the user to remain on the application page after exiting.

**Comment by javiercn** [comment] 2020-06-22 15:59
> This just help me to avoid scenario when new user loads app, then redirected to login page and again load app. He just start with login page.

It's not the same because it doesn't go through the authorize endpoint, so it does not perform an OAuth flow.

> I can clear my project of business logic and publish it, will it be useful?

It would help us understand what's going on, at least make sure we are not missing anything that is not trivial.

> Here the problem is precisely in the redirection, or precisely in its address? I do not want the user to remain on the application page after exiting.

The redirection is fine, but why send them to the login place, specially directly to the identity page? It shouldn't matter, but I'm worried that it can cause issues if the session is not established through IdentityServer.

**Comment by Kazbek** [comment] 2020-06-23 16:57
I`m collected as more information as I can at this moment. Also prepared repo.

**Additonal error information**
One more user get this error. He use latest Google Chrome browser.
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

He send me few screenshots of console. Here only one error of loading jivo js (its chat which we use to get feedback, you can see it on screenshot, its blocked by uBlock). Second screenshot hava additional jivo errors (some time passed between screenshot was made).  I`m hide some user personal information.
![image](https://user-images.githubusercontent.com/15718432/85430625-0bb85c00-b589-11ea-9ba3-af100922d2b5.png)

![image](https://user-images.githubusercontent.com/15718432/85430572-f6433200-b588-11ea-945b-3ee580a8026a.png)

I`m also tried to install uBlock to check if it cause the error. But for me its all fine (I have same jivo js error). Correct site open screenshot: 
![image](https://user-images.githubusercontent.com/15718432/85431337-13c4cb80-b58a-11ea-984a-31b61c282d84.png)

> It's not the same because it doesn't go through the authorize endpoint, so it does not perform an OAuth flow.

We also ask users try to go diretly to site address/index.html (to avoid going through action mentioned before) and login after redirection but they said it doesn`t help too.

**Repository**

I cleaned the project. I tried to save all the settings. Changed the database from Postgres to ms sql file to simplify debugging. If something else is required, please let me know, I will try to do my best.
Repository: https://github.com/Kazbek/Test-BlazorAuthProblemDemo

**Comment by mkArtakMSFT** [comment] 2020-06-23 16:58
Thanks for contacting us.
We're moving this issue to the `Next sprint planning` milestone for future evaluation / consideration. We will evaluate the request when we will planning the work for the next milestone. To learn more about what to expect next and how this issue will be handled you can read more about our triage process [here](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md).

**Comment by Kazbek** [comment] 2020-06-24 17:00
@javiercn ,excuse me for writing so much in my first issue in this repository.

I'm searched in this respository for the message "There was an error signing in." which shown in browser address bar and found only this file related to wasm. May be I can add some more log outputs to result js in my project and get some more information about this error? Is it  good idea or I`m totally wrong? And I would like to hear advice on what exactly it would be necessary to get in log.

https://github.com/dotnet/aspnetcore/blob/648c15dbe90fb8c113f7c6b4adeb40d9e10494f6/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts#L172-L189

**Comment by nullfield** [comment] 2020-07-06 18:58
I'm having this issue as well with iPads on iOS 13. Application works on every supported browser but the iPads I've tried where it happens every time. Returns the same message to the user: 

> There was an error trying to log you in: ''

In the console of Safari: 

> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2] Authorization failed.

There are no other error messages anywhere.

To reproduce just create a Blazor WebAssembly project with individual user accounts and ASP.NET Core hosted checked. (Progressive Web Application doesn't matter. Same issue either way.) Compile and publish to a server. Visit with iPad and try to sign in.
As an aside, after you try to signin if you then click the register link it will redirect you to the Identity register page which shows you as already signed in. The link in the username takes you to the manage account page. All of that works. It just doesn't successfully pass the authentication state to the WebAssembly part. I've attached the console output from the server side below.

[test_log.log](https://github.com/dotnet/aspnetcore/files/4880568/test_log.log)

**Comment by Kazbek** [comment] 2020-07-09 22:04
Additional Information. One of the users registered on June 23 and until today has been using the site normally. Today on the same device and browser this error occurred.

**Comment by SCEV** [comment] 2020-07-22 01:35
I am encountering this same issue.  I feel like it's some configuration I am missing.  When I run my application locally (localhost) in IISExpress I can authenticate, and navigate the Blazor application fine.  If I publish the site to IIS (10), and access the site via the URL it seems to log me in correctly on the server-side, I can manually navigate to {URL}/Identity/Account/Manage, and see my account settings. But then I navigate back to the client blazer application I get the error "There was an error trying to log you in: ''"

In Chome (for the localhost site) looking in the development tools, Application / Session Storage I see a Key called **oidc.user:https://localhost:44375:Test.Client.BlazorUI** with the values of my access token.

When I look at the same session storage for the published site there is NO **oidc.user:* ** Key / Value at all.

Is there a setting that I need to provide for IdentityServer that indicates that the published URL should be for this session key?

**Comment by SCEV** [comment] 2020-07-24 22:49
I've spent a good bit of time going over my settings/configuration.  I have learned quite a bit about IdentityServer.  From what I can tell all of my configurations are correct.  

I created a basic Blazor WASM app straight from the template, published it to my IIS server and I get the same issue when trying to log in: **There was an error trying to log you in: ''** looking through the asp .net core code the error is coming from **WebAssembly.Authentication.RemoteAuthenticatorViewCore.cs on line 397**.  it looks like there should be some additional error message, but I guess either IdentityServer is not sending one, or it is lost.

Is ANYONE able to login with a deployed Blazor WASM app in Blazor?  This is a production application that was deployed, and now not usable because users can't log in.

Any help would be greatly appreciated!

**Comment by Kazbek** [comment] 2020-08-06 10:51
Today my host provider reboot my server. And I and 2 more (I'm only asked 2) users have the same issue. Private mode/re log in doesn`t help. But restart site via IIS resolved problem for us. Before it I made some screenshots from js part of code. I hope it will helpful for investigation.
![js-auth-problem](https://user-images.githubusercontent.com/15718432/89523574-bf994200-d7eb-11ea-9654-8749159cbad8.png)

**Comment by Kazbek** [comment] 2020-11-26 00:14
Migrate to .NET 5 wasn't help.

**Comment by rayder2007** [comment] 2020-11-29 17:03
Try to check if the time and time zone are set correctly on the client.

**Comment by Kazbek** [comment] 2020-11-30 15:09
@rayder2007 tried to set incorrect (+1 month)  time on my phone and then got the same error. I'll try to clarify the time with users when there will be another such problem.
In any case, even I had such a problem, if I set the wrong time, can I somehow solve this problem? It is a bit difficult to get all users to set the correct time. For some, even sending a screenshot is an impossible task.

**Comment by rayder2007** [comment] 2020-12-01 01:29
@Kazbek We ran a test.  A difference of 10 minutes is enough.  How to configure this is not clear.

**Comment by rayder2007** [comment] 2021-01-31 03:34
@Kazbek Did you manage to solve this problem?

**Comment by Kazbek** [comment] 2021-01-31 09:39
@rayder2007 Unfortunately no. For some users help to set correct time but not all users contact support. We have to use a classic website in parallel for such users.

**Comment by mkArtakMSFT** [comment] 2021-11-11 18:57
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2021-11-11 18:57 UTC
Labels: bug, investigate, area-blazor, blazor-wasm, severity-major, affected-very-few, feature-blazor-deployment

**Comment by Kazbek** [comment] 2021-11-11 19:10
Just to know. Migrated project to net6 and issue still gere.
