### ISSUE TITLE
SignalR GET with body

### ISSUE THREAD

**Issue by marcstern** [dotnet/aspnetcore#55749] opened 2024-05-16 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In recent versions, SignalR sometimes send GET requests with a header "Transfer-Encoding: chunked".
Some reverse proxies crash with this in certain conditions and most WAF block this.

### Expected Behavior

GET requests should have no Transfer-Encoding header, nor body.

**Comment by BrennanConroy** [comment] 2024-05-16 17:09
What client are you using? What transport? "In recent versions", what version did it start happening?

**Comment by marcstern** [comment] 2024-05-21 07:00
Hello.

We have the problem with version 8.0.0. We tried Chrome & Edge.
Actually, the problem may have been present in older versions, not sure.
We detected this because we were behind a WAF.

It seems that the problem happens during SignalR negotiation.
If the web socket cannot be established, a GET requests with a header "Transfer-Encoding: chunked" is sent.
Because it's inside the negotiation, we don't see it in the developers tools but we saw it on the WAF.

**Comment by BrennanConroy** [comment] 2024-05-21 18:13
> Because it's inside the negotiation, we don't see it in the developers tools

That doesn't make any sense. If the request is coming from the browser it will be in the developer tools.

SignalR in the browser never sets `Transfer-Encoding: chunked`. So either the browser is setting it for some reason (out of our control), you're setting it in your configuration, or you're omitting some information about your setup.

**Comment by marcstern** [comment] 2024-05-27 06:56
I will try to get more detailed info from the developer

**Comment by sebas-ambrero** [comment] 2024-07-04 09:42
> Hello.
> 
> We have the problem with version 8.0.0. We tried Chrome & Edge. Actually, the problem may have been present in older versions, not sure. We detected this because we were behind a WAF.
> 
> It seems that the problem happens during SignalR negotiation. If the web socket cannot be established, a GET requests with a header "Transfer-Encoding: chunked" is sent. Because it's inside the negotiation, we don't see it in the developers tools but we saw it on the WAF.

The issue has become stale, but to just add my 2 cents if anyone finds this in the future. 

Recentely I've run into a similar) issue, which probably is the same as yours, but I have some additional information.

It's not a bug in SignalR, but if you install (in my case) ModSecurity (v3) in kubernetes (WAF), then by default a rule, 920420 is applied.
This rule specifies that the "Content-Type" header can not be "plain/text" for a POST call.

SignalR sends a negotiate call to the endpoint "/hub/negotiate?negotiateVersion=1". 
This is a POST call with the following headers:

accept: "*/*"
accept-encoding: "gzip, deflate, br, zstd"
accept-language: "nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7"
content-length: "0"
content-type: "text/plain;charset=UTF-8"
user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
x-requested-with: "XMLHttpRequest"

Default this is not allowed, the idea being that you could still send json data for example, and the application then still parsing it, bypassing whatever security rule is applied to json data in the filter. (I'm no security researcher so the explanation might be not be the best one ).

The fix for me was to allow text/plain in a POST (for the specific hub endpoints).

Hope this helps.

**Comment by marcstern** [comment] 2024-07-04 11:01
Thanks for the info @sebas-ambrero.
Having a C-T or a C-L for a GET is definitely a bad practice, even if not explicitely forbidden by the standard.
This kind of unusual things can really crash a server (read next).
On top of this, `Transfer-Encoding: chunked` is sometimes used. Again, this is not explicitely forbidden by the standard.
However, it's sometimes added when using HTTP/2 as well, and this is strictly forbidden.
This last problem leads to crash several well known application servers (some of them were notified).
So, I see no reason to have a C-T, nor a C-L, nor a T-E; it only can add problems and doesn't have any benefit.

**Comment by BrennanConroy** [comment] 2024-07-06 04:08
Like I said above, I'm not aware of any case where SignalR sets `Transfer-Encoding: chunked` in the browser. Please provide repro steps or debug further to let us know where the header is coming from.

**Closed** 2024-07-15 00:36 UTC
Labels: Needs: Author Feedback, area-signalr, Status: No Recent Activity
