### ISSUE TITLE
 ResendEmailConfirmationModel is abstract after scaffolding the code

### ISSUE THREAD

**Issue by H-Ashrafi** [dotnet/aspnetcore#22626] opened 2020-06-06 18:18 UTC
### Describe the bug
In Identity _Resend Email Confirmation_ causes error below

> InvalidOperationException: Can't compile a NewExpression with a constructor declared on an 
> abstract class

### To Reproduce
- Create an ASP.Net core web app v3.1.
- In visual studio right-click on project name and choose Add>New Scaffolded item>Identity.
- check Override all files and create a new Data Context Class then click Add. This adds the latest nuget packages. At the time of writing this thread they are Identity.EntityFramworkCore v3.1.3, Identity.UI v3.1.3
- Go to login page.
- Press Resend Email Confirmation
### To Fix
Remove **abstract** from  **ResendEmailConfirmationModel** class.

**Comment by blowdart** [comment] 2020-06-06 23:17
@HaoK

**Comment by blowdart** [comment] 2020-06-06 23:17
Closing as dupe of https://github.com/dotnet/aspnetcore/issues/21827

**Closed by blowdart** 2020-06-06 23:17 UTC
Labels: area-identity
