### ISSUE TITLE
SupplyParameterFromForm Issues biding Nullable enumerations within collections in complex objects in Blazor SSR

### ISSUE THREAD

**Issue by xxnickles** [dotnet/aspnetcore#59364] opened 2024-12-07 06:53 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have come accross with a werid behavior when trying to bing a collection that includes a nullable enum value from a form in Blazor SSR. When I am trying to bind a form to the following object

```csharp
public enum Test
{
    A,
    B
}

public class BadComplexProperty
{
    public string? StringValue { get; set; }
    public Test? EnumValue { get; set; }
}

public class BadBiding
{
    public Test? EnumValueParent { get; set; }
    public BadComplexProperty[] Items { get; set; } = [new(), new() { EnumValue = Test.A, StringValue = "Nothing" }];
}
```

The property Items ends being null. Note how I am trying to bind the nullable enumeration as a property in as a simple property in the object, but also will as part of the object in the collection. In the contrary, when I use a nullable string instead the enumeration in the object that will be part of the collection works and I get the expected colelction

```csharp
public class GoodComplexProperty
{
    public string? StringValue { get; set; }
    public string? EnumValue { get; set; }
}

public class GoodBiding
{
    public Test? EnumValueParent { get; set; }
    public GoodComplexProperty[] Items { get; set; } = [new(), new() { EnumValue = Test.A.ToString(), StringValue = "Nothing" }];
}
```

### Expected Behavior

It seems the binding to nullable enumeration works just fine when the property as "standalone" is in the parent class. However, when is part of a collection, the binding is just not working. For my test it seems in this case empty values are bound as empty strings instead of  null in suchs cases. 

### Steps To Reproduce

I have prepared the following [repository](https://github.com/xxnickles/enum-issues/tree/main/EnumInCollections). You can check both bindings in the pages [WorkingBinding ](https://github.com/xxnickles/enum-issues/blob/main/EnumInCollections/Components/Pages/WorkingBiding.razor) and [NotWorkingBinding](https://github.com/xxnickles/enum-issues/blob/main/EnumInCollections/Components/Pages/NotWorkingBinding.razor). not working binding will produce runtime expections submitting the form as the Items array will be null after submition

### Exceptions (if any)

Unfortunatelly I am not getting any meaninful exception from the binding process, I just can see the end result (null array)

### .NET Version

9.0.101

### Anything else?

.NET SDK:
 Version:           9.0.101
 Commit:            eedb237549
 Workload version:  9.0.100-manifests.4a280210
 MSBuild version:   17.12.12+1cce77968

**Comment by javiercn** [comment] 2024-12-12 14:58
@xxnickles thanks for contacting us.

We think this is a dupe of https://github.com/dotnet/aspnetcore/issues/54565

**Closed by javiercn** 2024-12-12 14:58 UTC
Labels: area-blazor

**Comment by xxnickles** [comment] 2024-12-12 17:21
@javiercn I could be in this specific scenario.  But I would like to point out this issue with nullable bindings from forms is not limited to the select component. For my verifications, complex properties bindings from form data have short comings in both blazor and minimal APIs, especially on cases when the complex object has nullable/numeric properties. That is only pointing to the binding part because I also understand the validation of those cases also doesn't work out of the box. In my opinion, the documentation for SSR forms should discourage the usage of complex properties until there is a proper support for it
