### ISSUE TITLE
Blazor: Separate Validate/StateChange concerns in EditContext

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#13595] opened 2019-08-31 20:13 UTC
### Is your feature request related to a problem? Please describe.
It is currently not possible to validate an individual field of an EditForm without also marking the field as modified.

Currently we can call EditContext.NotifyFieldChanged to invoke validation, but that also sets the FieldState.IsModified to true for that item in the form.

### Describe the solution you'd like
Please separate change notification and validation requests for properties, so we can validate without marking the state as modified. 

Add a `ValidateProperty(FieldIdentifier)` method to EditContext which invokes an `OnFieldValidationRequested` event that validation strategies can use to trigger validation.

`NotifyFieldChanged` and `OnFieldChanged` should remain as it might be useful to know when an individual property is changed.

**Comment by mkArtakMSFT** [comment] 2019-09-03 17:17
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mrpmorris** [comment] 2019-09-04 13:35
I'll happily provide the resources, it's only a few lines of code :)

**Comment by mrpmorris** [comment] 2020-02-06 15:51
Could this be considered please? It allows the validation of a sub-set of object properties without having to mark them as modified.

**Comment by mkArtakMSFT** [comment] 2020-02-10 06:19
@SteveSandersonMS thoughts?

**Comment by mkArtakMSFT** [comment] 2022-10-19 22:13
Closing as this is a dupe of https://github.com/dotnet/aspnetcore/issues/31252

**Closed by mkArtakMSFT** 2022-10-19 22:13 UTC
Labels: enhancement, area-blazor, affected-few, severity-minor, feature-blazor-form-validation, feature-blazor-builtin-components
