### ISSUE TITLE
Nullable issue with RazorPage model

### ISSUE THREAD

**Issue by nfplee** [dotnet/aspnetcore#38762] opened 2021-12-01 15:38 UTC
I'm looking to upgrade to ASP.NET Core 6 after embracing nullable reference types in ASP.NET Core 5. However now on build i'm getting lots of warnings saying:

> Dereference of a possibly null reference.

Where I say `@Model.Foo` within my views. This is because the `Model` property on the `Microsoft.AspNetCore.Mvc.Razor.RazorPage<TModel>` class has been marked as nullable. To fix this I have to now either check for null within every view or say `@Model!.Foo` neither of which are that great.

Surely it should respect the type of model I specify in my view. e.g. `@model string` or `@model string?` if it can be null.

**Comment by pranavkm** [comment] 2021-12-01 16:52
Dupe of https://github.com/dotnet/aspnetcore/issues/37510. https://github.com/dotnet/aspnetcore/issues/37510#issuecomment-943573122 has a possible workaround until we try and address this.

**Closed** 2021-12-02 10:13 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-mvc, Status: Resolved
