### ISSUE TITLE
[Blazor] Generate razor.cs file when adding razor component

### ISSUE THREAD

**Issue by Lupusa87** [dotnet/aspnetcore#23180] opened 2020-06-19 23:39 UTC
It will be great if tooling will add component with partial class.
Current template is generating one file with code block, some people even do not know they can have partial class, separated UI and logic.
If using partial classes is prefered approach then tooling should follow it by default.

**Comment by mkArtakMSFT** [comment] 2020-06-20 04:30
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/21445

**Closed by mkArtakMSFT** 2020-06-20 04:30 UTC
Labels: area-blazor, enhancement
