### ISSUE TITLE
Inconsistent StateHasChanged Behavior

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#27961] opened 2020-11-18 21:05 UTC
I am running into a situation where StateHasChanged is not consistently re-rendering a component in a Blazor Wasm app (not yet upgraded to 5.0).  I have created a small  demo of the problem, but don't know how best to upload it in github (it is a bit too big to just insert the code). Please point me to some instructions so I can upload it.

The problem occurs when I attempt to render a specific component (that contains a child component) in a panel of the layout more than once in succession, with different underlying data in each rendering.  In the demo, the component contains a single child that consists of a single checkbox whose checkstate is changed from one StateHasChanged-triggered rendering to the next.   The first time I step through the renderings, the checkstate changes as expected.  But after causing a different component to render in the same panel and then returning to the "checkbox" one, the checkstate does not change.  

I have seen similar behavior with a combobox in my full app.  For a better understanding of the app's architecture, see closed issue [#25154](https://github.com/dotnet/aspnetcore/issues/25154).  I'm hoping that the "diffing" explanation provided by @SteveSandersonMS doesn't mean the situation I am describing here can't be made to work.

**Comment by javiercn** [comment] 2020-11-19 12:34
@CincySteve thanks for contacting us.

It's impossible for us to give you an answer without a minimal repro project. I would suggest you create a new application from scratch and copy the minimal code necessary to reproduce the situation.

Then either create a GH repo and put the code there (with detailed instructions on how to reproduce the problem) or upload the project as a zip file here and again, include instructions to reproduce the behavior you think it's wrong.

**Comment by CincySteve** [comment] 2020-11-19 21:39
@javiercn I wasn't sure how you might want my repro project.   To create it, simply create a Blazor Wasm project called "Refresh" using the enclosed zipped files.  I hope this is what you were expecting.  GitHub said a zip of the full project folder was too big.  Excuse some of the layout stuff.  I cribbed it from my full app rather than totally starting from scratch. 

To see the problem:

1. Click the "Comp1 True" and then "Comp1 False" buttons and notice how the label and check state of the checkbox changes.  Toggle back and forth between those buttons to see that the checkbox toggles too.  That's what I expect to happen.

2. Next click the "Start" button and then repeat step 1.  This time the checkbox does not toggle as it did in the beginning.  It will remain in the state of the first "Comp1..." button that you click after clicking "Start".  

I have included console messages so you can see what is happening and the data that's being used by Comp1 depending on which button you hit.  



[RefreshFiles.zip](https://github.com/dotnet/aspnetcore/files/5569821/RefreshFiles.zip)

**Comment by CincySteve** [comment] 2020-11-21 20:44
I just updated the repro app to 5.0 and still see the same behavior.

**Comment by mkArtakMSFT** [comment] 2020-11-23 17:33
Thanks for contacting us, @CincySteve.
We don't look into complex user applications. Please provide a project with minimum changes from the default project template required to reproduce the behavior.

**Comment by CincySteve** [comment] 2020-11-23 22:22
@mkArtakMSFT I must admit to being in deep water.  I have created what appears to me to be a GitHub repository containing a full VS project that reproduces the problem using as few changes to the Blazor template as I can envision.   I am hoping this meets your needs.  Before I describe the specific sequence of actions to take with this repro, please confirm that it meets your requirement for "minimum changes to the default project template."  Thanks.  Steve  Here's the [repro](https://github.com/CincySteve/RefreshRepro1/tree/7c2956595c519808dae4eea2d04a52f6937b2333/RefreshRepro).

**Comment by SteveSandersonMS** [comment] 2020-11-24 10:15
> Next click the "Start" button and then repeat step 1

@CincySteve I looked at [your repro app](https://github.com/CincySteve/RefreshRepro1) and it doesn't seem to contain any button labelled "Start" so I can't be 100% sure I'm doing what you want to repro the issue. However I did observe that the following behaves weirdly:

 * Start at `/`
 * Click "My comp" to go to `/mycomp` and observe that the "Comp1 True" and "Comp1 False" buttons cause the checkbox state to change
 * Click "Home" to navigate to `/` then "My comp" to navigate back to `/mycomp`
 * Now observe that the "Comp1 True" and "Comp1 False" buttons no longer cause the checkbox state to change

If this is the bug you're talking about, it appears to be entirely due to a logic error in the application. On [this line of code](https://github.com/CincySteve/RefreshRepro1/blob/b4fbc7c191070d5258ade8b99aab27b032478989/RefreshRepro/Static_.cs#L37), you're only allowing an event subscription to the *first* caller that supplies a given `subscriberName`. When you navigate away and then back again, the new instance of `IBCheckbox` tries to subscribe, but since it's not the first subscriber, your logic doesn't add any new event subscription. Hence it does not receive notification of events.

More generally, to understand and diagnose issues like this, I'd recommend getting familiar with the debugger to step through the execution in detail. In the example above, it's possible to observe with the debugger that the 2nd-and-later attempts to subscribe are rejected.

**Comment by CincySteve** [comment] 2020-11-24 14:03
@SteveSandersonMS Thanks so much for your reply.  You correctly discovered the repro steps after I removed the "Start" button in reaction to being asked to redo the repro with as few changes to the template project as possible.

I'm hoping to get one more bit of clarification on your observation.  When I simply remove the line of code you point out, the IBCheckbox Refresh method is invoked twice as observed using the debugger (which I use extensively) and the console messages.  Both invocations execute StateHasChanged.  One changes what's displayed (ie triggers a new render I presume), while the other does not.  Is the one that does not simply being ignored (_with no indication_), perhaps because the initial rendering (instance?) of IBCheckbox when MYComp was initially clicked is simply gone?  Or are there 2 "instances" of IBCheckbox (and hence MyComp)?  This seems to be an important thing to know.

I solved the duplicate invocations of Refresh by removing the line of code you reference and calling the following new Static_ method in the MyComp OnInitlaized method.  

public static void Refresh_Clear()
            {
            Refresh_Subscribers.Clear();
            Refresh_Event = null;
            }``

**Comment by SteveSandersonMS** [comment] 2020-11-24 14:58
> When I simply remove the line of code you point out, the IBCheckbox Refresh method is invoked twice

Yes, unless you remove the event registrations on component disposal, you'll keep accumulating more of them each time a new component is added. This is leaking memory, so you should make sure to clear these up.

See: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#component-disposal-with-idisposable

Closing as it's clear now that this is answered.

**Closed by SteveSandersonMS** 2020-11-24 14:58 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor
