### ISSUE TITLE
SignalR library throws error when it application run without debug points and work fine while debugging 

### ISSUE THREAD

**Issue by JanithaKalshan** [dotnet/aspnetcore#20777] opened 2020-04-12 20:15 UTC
I have created a .net core chat application using SignalR and I need move to next user by clicking next button. When I click the next button it will trigger the method "getRemoteClientNext" inside the Hub class

public async Task getRemoteClientNext(string RemoteUserId)
        {
           
          var name = Context.User.Identity.Name;
            var CurrentAppUser = _userManager.FindByNameAsync(name);

            if(RemoteUserId != null) {
                using (var db = _dBContext)
                {
                    var remotename = db.Users.Find(RemoteUserId);

                    var RemoteUser = db.Connections.Where(c => c.UsersId != CurrentAppUser.Result.Id && c.UsersId != RemoteUserId && c.RemoteConnected == false).AsEnumerable().GroupBy(c => c.UsersId);

                    //var remoteConnection = db.Connections.Where(u => u.UsersId == CurrentAppUser.Result.Id || u.UsersId == RemoteUserId).ToList();
                    //remoteConnection.ForEach(i => i.RemoteConnected = false);
                    var currntUserConnection = db.Connections.Where(u => u.UsersId == CurrentAppUser.Result.Id).AsEnumerable().FirstOrDefault();
                    currntUserConnection.RemoteConnected = false;
                    db.SaveChanges();

                    var RemoteUserConnection = db.Connections.Where(u => u.UsersId == RemoteUserId).AsEnumerable().FirstOrDefault();
                    if (RemoteUserConnection != null)
                    {
                        RemoteUserConnection.RemoteConnected = false;
                    }
                    db.SaveChanges();

                    var connec = db.Connections.Where(c => c.UsersId == RemoteUserId);

                    if (connec.Count() == 0)
                    {
                        await Clients.Caller.SendAsync("ClienErrors", "The user is no longer connected");
                    }
                    else
                    {
                        foreach (var connection in connec)
                        {
                            await Clients.Client(connection.ConnectionID).SendAsync("maintainConnectionStatus", "Connecting a remote user......");
                        }

                    }
                    await Clients.Caller.SendAsync("maintainConnectionStatus", "Connecting a remote user......");

                    if (RemoteUser.Count() == 0)
                    {
                        await Clients.Caller.SendAsync("maintainConnectionStatus", "Connecting a remote user......");
                    }
                    else
                    {
                        var selectedRemoteUser = RemoteUser.First().ToList();
                        var currentUserConnection = db.Connections.Where(u => u.UsersId == CurrentAppUser.Result.Id).AsEnumerable().FirstOrDefault();
                       // selectedRemoteUser.ForEach(c => c.RemoteConnected = true) ;
                        foreach(Connections con in selectedRemoteUser)
                        {
                            con.RemoteConnected = true;
                            con.RemoteConnectionID = currentUserConnection.ConnectionID;
                            currentUserConnection.RemoteConnectionID = con.ConnectionID;
                        }
                        // var currentUserConnection = db.Connections.Where(u => u.UsersId == CurrentAppUser.Result.Id).AsEnumerable().FirstOrDefault();
                        var RemoteId = selectedRemoteUser.Select(u => u.UsersId).FirstOrDefault();
                        var RemoteName = db.Users.Find(RemoteId);
                        currentUserConnection.RemoteConnected = true;
                       
                        db.SaveChanges();

                        //var RemoteId = selectedRemoteUser.Select(u => u.UsersId).FirstOrDefault();
                        //var RemoteName = db.Users.Find(RemoteId);

                        var connec2 = db.Connections.Where(c => c.UsersId == RemoteId);

                        if (connec2.Count() ==0)
                        {
                            await Clients.Caller.SendAsync("ClienErrors", "The user is no longer connected");
                        }
                        else
                        {
                            foreach (var connection in connec2)
                            {
                                await Clients.Client(connection.ConnectionID).SendAsync("SendRemoteUserId", CurrentAppUser.Result.Id, CurrentAppUser.Result.FirstName);
                            }

                        }
                        await Clients.Caller.SendAsync("SendRemoteUserId", RemoteId, RemoteName.FirstName);
                    }
                }
            }
        }

in java script the event is like 

document.getElementById("next").addEventListener("click", function (event) {
    connection.invoke("getRemoteClientNext", RemoteUserId);
});

The issue I got is when I click the next button "getRemoteClientNext" will be triggered and work fine when it is  debugging. If I disable all the debug points and run the application this will not work. But other functions like sending the chat messages using hub are working finely. Then I check the console and I saw the error message 

Uncaught (in promise) Error: An unexpected error occurred invoking 'getRemoteClientNext' on the server.
    at _this.callbacks.<computed> (signalr.js:2088)
    at HubConnection.processIncomingData (signalr.js:2182)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1905)
    at WebSocket.webSocket.onmessage (signalr.js:3949)

I removed the SignalR and try to install it again but it is not working and in add client side library also only  showing Jquery.SignalR.js and  Jquery.SignalR.min.js files. So I added Signalr.js file manually from another project.

Can any one tell me why this is happening is it error in SignalR library

**Comment by JanithaKalshan** [comment] 2020-04-12 20:39
Again I commented the foreach loop inside the method "getRemoteClientNext" and delete the comment on "selectedRemoteUser.ForEach(c => c.RemoteConnected = true)"

this work one time fine and now it is giving the error 

signalr.js:2088 Uncaught (in promise) Error: An unexpected error occurred invoking 'getRemoteClientNext' on the server.
    at _this.callbacks.<computed> (signalr.js:2088)
    at HubConnection.processIncomingData (signalr.js:2182)
    at WebSocketTransport.HubConnection.connection.onreceive (signalr.js:1905)
    at WebSocket.webSocket.onmessage (signalr.js:3949)

Why is this happening

**Comment by BrennanConroy** [comment] 2020-04-12 21:58
You're not observing the return value on the client from `connection.invoke(...)` so you're getting an uncaught error.

Take a look at the [docs](https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1#call-hub-methods-from-client) for details about calling invoke vs. send and also what you should be doing about the return value.

The actual issue is most likely that your hub method is throwing an error, you can take a look at the server logs to see if there is an exception being thrown.

**Comment by JanithaKalshan** [comment] 2020-04-16 20:07
@BrennanConroy  thanks for you help. I think I miss the await in "_userManager.FindByNameAsync(name)" . before I get the reply for this I sleep the thread for 2 seconds then this error didn't pop up. when I use await in this place also this error didnt pop up and thanks again for the reply

**Comment by BrennanConroy** [comment] 2020-04-16 20:11
Glad you fixed the issue. Is this good to close then?

**Comment by anurse** [comment] 2020-04-17 20:03
Closing since it sounds like the issue is resolved. Feel free to comment if I'm misinterpreting things.

**Closed by anurse** 2020-04-17 20:03 UTC
Labels: Needs: Attention :wave:, area-signalr

**Comment by JanithaKalshan** [comment] 2020-04-19 06:16
Thanks for closing this
