### ISSUE TITLE
dotnet dev-certs (again)

### ISSUE THREAD

**Issue by thales-man** [dotnet/aspnetcore#21592] opened 2020-05-07 20:22 UTC
I need to raise this again.

I've read extensively on the problem, taken all the steps. completely removed all runtimes and SDK's and reinstalled. repeatedly dumped the certs from the key chain, re-run the cert generator, to no avail; run under sudo. added property group items to project files, removed 'use https redirect'... none of these 'solutions' works.

Application Insights Telemetry: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware: Error: The ASP.NET Core developer certificate is in an invalid state. To fix this issue, run the following commands 'dotnet dev-certs https --clean' and 'dotnet dev-certs https' to remove all existing ASP.NET Core development certificates and create a new untrusted developer certificate. On macOS or Windows, use 'dotnet dev-certs https --trust' to trust the new certificate.

=====================================
dotnet --info
.NET Core SDK (reflecting any global.json):
Version: 3.1.200
Commit: c5123d973b

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.15
OS Platform: Darwin
RID: osx.10.15-x64
Base Path: /usr/local/share/dotnet/sdk/3.1.200/

Host (useful for support):
Version: 3.1.2
Commit: 916b5cba26

.NET Core SDKs installed:
3.1.200 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

clearing doesn't work as the cert is stated as still present once a the clear down has completed.
the app when loading repeatedly asks for the cert and tries to create one.

it just doesn't work...
it's an absolute PINTA and I've spent days on it...

**Comment by javiercn** [comment] 2020-05-07 20:48
@thales-man thanks for contacting us.

I believe you are running into an existing issue on Mac OS. See https://github.com/dotnet/aspnetcore/issues/19590#issuecomment-597784639 for steps on how to workaround it while we are working on a fix.

Let us know if this fixes your issue.

**Comment by javiercn** [comment] 2020-05-08 12:07
Closing this issue as it is a duplicate of #19590.

**Closed by javiercn** 2020-05-08 12:07 UTC
Labels: area-commandlinetools, feature-devcerts, investigate
