### ISSUE TITLE
http body writeasync size limit

### ISSUE THREAD

**Issue by joslb** [dotnet/aspnetcore#45154] opened 2022-11-17 16:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,

I'm trying to stream 'png' files to a browser. To do this, i use this code :

                            if (imageBytes != null)
                            {
                                var header = $"--{_boundary}\r\nContent-Type: image/png\r\nContent-Length: {imageBytes.Length}\r\n\r\n";
                                var headerData = Encoding.UTF8.GetBytes(header);

                                await pipeWriter.WriteAsync(headerData);
                                await pipeWriter.WriteAsync(imageBytes);
                                await pipeWriter.WriteAsync(_newLine);

                                await pipeWriter.FlushAsync();

                            }
"
When the size of the image is greater than 65536 bytes, the writeasync operation does not succeed. 

I played with the available options without success. I may have missed something. Can you tell me if this behavior is normal?

Thanks

### .NET Version

6.0.42

**Comment by Tratcher** [comment] 2022-11-17 17:43
Can you give a more complete code sample and the original error message and stack trace?

**Comment by joslb** [comment] 2022-11-18 09:14
Hi,
Thank you for your quick reply

1. code snippet of the startup.cs
-----------------------------------

 public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<KestrelServerOptions>(serverOptions =>
            {
                serverOptions.AllowSynchronousIO = true;
                serverOptions.Limits.MaxResponseBufferSize = 2147483647;
            });

            services.AddControllers().AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                options.SerializerSettings.Formatting = Formatting.Indented;
                options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            });
            services.AddSwaggerGen();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UsePathBase("/aop/api");
            app.UseRouting();
            app.UseAuthorization();

            app.UseHttpsRedirection();
            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseSwagger();
            app.UseSwaggerUI();
        }

3. Code snippet from the controller
-----------------------------------------

 public  IActionResult GetCollectionPlotAnim(...)
 {
            //await AnimateAsync((atStep) => this.GetCollectionPlot(...);
            return new PngStreamContent((atStep)
                => this.GetCollectionPlot(...);
}

-> the 'GetCollectionPlot' method produces 'FileContentResult' type results.

4. 'PngStreamContent' code:

public class PngStreamContent : IActionResult
    {
        private static readonly string _boundary = "ImageBoundary";
        private static readonly string _contentType = "multipart/x-mixed-replace;boundary=" + _boundary;
        private static readonly byte[] _newLine = Encoding.UTF8.GetBytes("\r\n");

        private readonly Func<DateTime?, IActionResult> _onNextPng;
        private DateTime? _at;
        private readonly int _speed;
        private readonly int _step;


        //Func<DateTime?, IActionResult> provider, DateTime? at, int speed, int step

        public PngStreamContent(Func<DateTime?, IActionResult> onNextPng, DateTime? at, int speed, int step)
        {
            _onNextPng = onNextPng;
            _at = at;
            _speed = speed;
            _step = step;
        }

        public async Task ExecuteResultAsync(ActionContext context)
        {
            var pipeWriter = context.HttpContext.Response.BodyWriter;

           
            context.HttpContext.Response.ContentType = _contentType;
            context.HttpContext.Response.Headers.Remove("Cache-Control");
            context.HttpContext.Response.Headers.Add("Cache-Control", "no-store, no-cache, no-transform, must-revalidate, max-age=0");

            var outputStream = context.HttpContext.Response.Body;
            var cancellationToken = context.HttpContext.RequestAborted;



            var frameTime = TimeSpan.FromMilliseconds(1000.0 / Math.Max(_speed, 1)); // nb: speed is in minutes per second
            var frameClock = new TimeSpan();
            var st = Stopwatch.StartNew();

            if (_at == null)
                _at = DateTime.Now.Date.ToUniversalTime();

            try
            {
                while (true)
                {
                    //Appel de la route 'GetplotCollection
                    var response = _onNextPng(_at);

                    var status = HttpStatusCode.BadRequest;
                    try
                    {
                        if (response.GetType().Equals(typeof(FileContentResult)))
                            status = HttpStatusCode.OK;
                    }
                    catch (Exception)
                    {
                        status = HttpStatusCode.BadRequest;
                    }

                    if (status == HttpStatusCode.OK)
                    {
                        var returnContent = response as FileContentResult;
                        if (returnContent != null)
                        {
                            while (st.Elapsed < frameClock)
                                Thread.Sleep(Math.Max(1, (int)Math.Ceiling((frameClock - st.Elapsed).TotalMilliseconds)));

                            Trace.WriteLine("at=" + _at.Value.ToShortTimeString() + " length=" + returnContent.FileContents.Length + " delay=" + (st.Elapsed - frameClock).TotalMilliseconds.ToString("0.0") + "ms");

                            frameClock += frameTime;

                            if (returnContent.FileContents != null)
                            {
                                var header = $"--{_boundary}\r\nContent-Type: image/png\r\nContent-Length: {returnContent.FileContents.Length}\r\n\r\n";
                                var headerData = Encoding.UTF8.GetBytes(header);

                                await pipeWriter.WriteAsync(headerData);
                                await pipeWriter.WriteAsync(returnContent.FileContents);
                                await pipeWriter.WriteAsync(_newLine);
                                await pipeWriter.FlushAsync();
  
                            }

                        }
                    }

                    var oldAt = _at.Value;

                    _at = _at.Value.AddMinutes(_step);

                    if (_at > DateTime.UtcNow || oldAt.ToLocalTime().Date != _at.Value.ToLocalTime().Date)
                        break;

                }
            }
            catch (TaskCanceledException)
            {
                //Todo
            }
            finally
            {
                //todo
            }

-> When the 'png' to be processed is larger than 65536 bytes, the process gets stuck on the line 'await pipeWriter.WriteAsync(returnContent.FileContents);' . No exception is thrown. 

4. Parallel stack :

![image](https://user-images.githubusercontent.com/33684878/202665311-4d058b00-bdbb-4be9-8909-de17daa475b8.png)

Thanks a lot,
Jo

**Comment by Tratcher** [comment] 2022-11-18 17:43
It looks like this is using HTTP/2. Do you know if the client is actively consuming the data? HTTP/2 flow control could prevent the server from sending any more data. Can you try it with HTTP/1.1 to see if it behaves differently?

**Comment by joslb** [comment] 2022-11-21 13:44
Hello, the change of protocol unfortunately did not solve the problem. On the client side, it remains pending. No data reaches it. 

Jo

**Comment by adityamandaleeka** [comment] 2022-11-21 23:07
Thanks @joslb, can you share the stack you see now when using HTTP/1.1?

Can you also share more info about the client? You mentioned that it's a browser.

And if you could share a minimal reproducer app as a public GitHub repo, that would be great!

**Comment by adityamandaleeka** [comment] 2022-11-21 23:09
BTW, can you share the other stacks when it's stuck too?

**Comment by joslb** [comment] 2022-11-23 10:02
Hello,
Thank you for your help. I think that the problem comes from my solution. I have not yet identified the cause but I do not lose hope :-)

**Comment by adityamandaleeka** [comment] 2022-11-28 23:58
Thanks @joslb. Good luck finding the issue 😄 

Closing this for now, please feel to reopen (or make a new issue) if you run into anything else.

**Closed by adityamandaleeka** 2022-11-28 23:58 UTC
Labels: area-runtime, Needs: Attention :wave:
