### ISSUE TITLE
Blazor Server Localization Middleware works but local time is always UTC.

### ISSUE THREAD

**Issue by micgreen** [dotnet/aspnetcore#23662] opened 2020-07-03 20:11 UTC
### Describe the bug

Blazor Server Localization Middleware doesn't appear to work, ie it doesn't appear to convert UTC dates to local time.

I have followed the [official guide](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1#blazor-server) to setup the Blazor Server Localization Middleware.  As a test, I have deployed my app to South Korea (Azure) & I am printing out the UTC & Local Time.

I am located in Texas & when I browse the app, the UTC is displayed, even if I use ```ToLocalTime()```

### To Reproduce

Public repo can be found [here](https://dev.azure.com/csedevcrewmedia/CSE%20EventGridViewer%20Blazor/_git/eventgrid-viewer-blazor?path=%2F&version=GBmgreen%2Ffeature%2Fblazor-localization-middleware&_a=contents)

1.  Navigate to <https://as-cse-egvb-kor.azurewebsites.net/> or <https://as-cse-egvb-westus2.azurewebsites.net/>
1. Observe that Local Time is UTC for the client-browser

The relevant files are:
[Startup.cs](https://dev.azure.com/csedevcrewmedia/CSE%20EventGridViewer%20Blazor/_git/eventgrid-viewer-blazor?path=%2Fsrc%2FBlazor.EventGridViewer.ServerApp%2FStartup.cs&version=GBmgreen%2Ffeature%2Fblazor-localization-middleware&_a=contents)

```csharp method
// ConfigureServices
services.AddLocalization();

// Configure method
            var supportedCultures = new[] { "en-US", "fr-FR", "ko-KR" };
            var localizationOptions = new RequestLocalizationOptions().SetDefaultCulture(supportedCultures[0])
                .AddSupportedCultures(supportedCultures)
                .AddSupportedUICultures(supportedCultures);

```

[_Host.cshtml](https://dev.azure.com/csedevcrewmedia/CSE%20EventGridViewer%20Blazor/_git/eventgrid-viewer-blazor?path=%2Fsrc%2FBlazor.EventGridViewer.ServerApp%2FPages%2F_Host.cshtml&version=GBmgreen%2Ffeature%2Fblazor-localization-middleware&_a=contents)

```csharp
    @{
        this.HttpContext.Response.Cookies.Append(
        CookieRequestCultureProvider.DefaultCookieName,
        CookieRequestCultureProvider.MakeCookieValue(
            new RequestCulture(
                CultureInfo.CurrentCulture,
                CultureInfo.CurrentUICulture)));
    }
```

[Index.razor](https://dev.azure.com/csedevcrewmedia/CSE%20EventGridViewer%20Blazor/_git/eventgrid-viewer-blazor?path=%2Fsrc%2FBlazor.EventGridViewer.ServerApp%2FPages%2FIndex.razor&version=GBmgreen%2Ffeature%2Fblazor-localization-middleware&_a=contents)

```csharp
<div>
    Culture Name: @CultureInfo.CurrentCulture.Name <br />
    Current Time (UTC): @DateTime.UtcNow <br />
    Current Time (Local): @DateTime.UtcNow.ToLocalTime().ToString()<br />
</div>
```

### Exceptions (if any)

None (I am a Blazor newb, so could be user error 👍 )

### Further technical details
- ASP.NET Core 3.1
- Blazor Server
- VS
- Azure App Server Plan - Windows
- Azure Web App
- dotnet --info
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by micgreen** [comment] 2020-07-04 00:26
Actually, I think this may be a dupe of [this](https://github.com/mono/mono/issues/15260) issue.

**Comment by micgreen** [comment] 2020-07-04 14:30
Interesting.

When I debug locally, it works:
![image](https://user-images.githubusercontent.com/65030708/86514587-df96a980-bdd8-11ea-9114-b1bd340c8065.png)

When deployed:
![image](https://user-images.githubusercontent.com/65030708/86514633-f3421000-bdd8-11ea-83b7-a3a4e2322e32.png)

**Comment by pranavkm** [comment] 2020-07-06 16:29
The problem isn't specific to Blazor, but to .NET Core in general. The runtime has a mechanism to set the `CultureInfo` on a per-thread basis (`CultureInfo.CurrentCulture`) and have it flow with the async context. Supporting this feature would require having an equivalent feature for timezones which does not exist today.

@DamianEdwards did we evaluate this scenario when designing the localization middleware?

**Comment by micgreen** [comment] 2020-07-06 16:46
@pranavkm , thanks for the info!  Not a show stopper.

I attempted to implement the solution with JS (momenjs) but unfortunately, the returned JS localized date doesn't appear on the screen unless a user does something on the screen  or a new item is added to the list (I display a list in a for loop) & the screen is updated.

I may open up another ticket for that but more than likely, will just wait until the feature is added as I would like to stay away from JS if I can.

Thanks

**Comment by mkArtakMSFT** [comment] 2021-11-05 23:32
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2021-11-05 23:32 UTC
Labels: External, enhancement, area-blazor, severity-minor, affected-very-few, blazor-server

**Comment by svenbaus** [comment] 2021-11-18 16:01
> Hi. Thanks for contacting us. We're closing this issue as there was not much community interest in this ask for quite a while now. 

I would like to mention that there is a community interest, because we would like to use Blazor Server in a enterprise environment with multiple locations. For know it seems like there is just the workaround with Javascript, which is (in my opinion) really bad.
