### ISSUE TITLE
NavigationException raised when using NavigationManager.NavigateTo upon form post in SSR

### ISSUE THREAD

**Issue by blissvalley** [dotnet/aspnetcore#50478] opened 2023-09-01 13:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

NavigationException raised when using NavigationManager.NavigateTo upon form post in server-side rendering

### Expected Behavior

redirect page to destination

### Steps To Reproduce

```
@page "/admin_login"
@attribute [StreamRendering(true)]

@using Models
@inject NavigationManager Navigation

<h3>AdminLogin</h3>

<EditForm Model="loginRequest" OnValidSubmit="ProcessLogin" FormName="AdminLoginForm">
    <div class="form-group">
        <label for="password" class="form-label">Password:</label>
        <InputText id="password" class="form-control" @bind-Value="@loginRequest.Password" type="password" />
    </div>
    <div class="mb-2">
        <button type="submit" class="btn btn-primary">Login</button>
    </div>

</EditForm>

@if (errorMessage != null)
{
    <div class="alert alert-danger" role="alert">
        @errorMessage
    </div>
}

@code {

    [SupplyParameterFromForm]
    private LoginRequest loginRequest { get; set; } = new();

    private string? errorMessage { get; set; } = null;

    private void ProcessLogin()
    {

        if (loginRequest.Password == "123")
        {
            Navigation.NavigateTo("/admin"); //Exception Raised
        }
        else
        {
            errorMessage = "Invalid password";
        }
    }

}

```

### .NET Version

8.0.100-preview.7.23376.3

**Comment by marinasundstrom** [comment] 2023-09-01 14:54
This seems like an issue that I have encountered.

The NavigationManager not being for SSR.

From what I heard it should be fixed. Perhaps not released yet.

**Comment by marinasundstrom** [comment] 2023-09-01 15:29
Duplicate: https://github.com/dotnet/aspnetcore/issues/49670

**Comment by marinasundstrom** [comment] 2023-09-01 15:55
This one seems more likely: https://github.com/dotnet/aspnetcore/issues/50260

**Comment by mkArtakMSFT** [comment] 2023-09-11 17:01
Thanks for contacting us. Does this exception result in an error in application or does it simply go away after you Continue debugging (F5) ?

**Comment by danroth27** [comment] 2023-09-11 17:12
I'm unable to reproduce this exception with .NET 8 RC1.

**Comment by blissvalley** [comment] 2023-09-12 05:41
> Thanks for contacting us. Does this exception result in an error in application or does it simply go away after you Continue debugging (F5) ?

When continue using F5, the program continue and go to destination page successfully.

**Comment by javiercn** [comment] 2023-09-12 16:45
@blissvalley thanks for the additional details.

That exception is launched and caught internally by the framework, the behavior is by design. You can avoid pausing on it if you turn off first chance exceptions

**Closed by javiercn** 2023-09-12 16:45 UTC
Labels: area-blazor, Needs: Attention :wave:, Needs: Repro
