### ISSUE TITLE
Add a weather API call to the Blazor Web App template when global interactivity is enabled with WebAssembly/Auto

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#51204] opened 2023-10-07 22:05 UTC
The earlier Blazor WebAssembly template demonstrated in the weather page how to make an API call from the client to the server. The new Blazor Web App template no longer demonstrates this scenario - instead the weather page manufactures the weather forecast data in the weather component implementation. It would be instructive if the weather page instead made an API call to the server to get the weather forecast data. This would also provide an opportunity to show how to handle component state persistence when prerendering.

**Comment by aleksanderwercis** [comment] 2024-03-01 05:45
Could at least describe how to add API to Blazor template in .NET 8????

**Comment by danroth27** [comment] 2024-03-01 16:59
> Could at least describe how to add API to Blazor template in .NET 8????

@aleksanderwercis You can find docs on calling web APIs from Blazor here: https://learn.microsoft.com/aspnet/core/blazor/call-web-api. If that doesn't answer all your questions, please let us know!

**Comment by mkArtakMSFT** [comment] 2024-11-01 17:27
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/55307

**Closed** 2024-11-01 17:27 UTC
Labels: enhancement, area-blazor, Priority:2, feature-templates, Pillar: Dev Experience
