### ISSUE TITLE
Go to definition on a component type results in exception

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#24875] opened 2020-08-13 14:20 UTC
### Describe the bug

Exception when hitting F12 on a component type.

### To Reproduce

Version 16.8.0 Preview 2.0 [30412.17.master]

- Create a new Blazor WebAssembly app
- In *Program.cs*, add the code `Counter c;` and resolve the namespace for `Counter`.
- Put the cursor on `Counter` and hit F12

Actual result: Yellow bar saying that an exception has occurred.

[ActivityLog.zip](https://github.com/dotnet/aspnetcore/files/5069561/ActivityLog.zip)

**Comment by NTaylorMullen** [comment] 2020-08-13 23:39
Duplicate of: https://github.com/dotnet/aspnetcore/issues/24351

**Closed by NTaylorMullen** 2020-08-13 23:39 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, feature-razor.vs
