### ISSUE TITLE
Progressive enhancement of form submission & navigation

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46399] opened 2023-02-01 21:53 UTC
Normally page navigations and form submissions require a full page load. With progressive enhancement, page navigations and form submissions can be handled more efficiently by intercepting the navigation and patching the DOM. This makes the user experience much smoother and faster while preserving more of the user's context on the page. If JS functionality is not available for whatever reason the app degrades gracefully to normal page loads.

**Comment by Xyncgas** [comment] 2023-05-27 07:53
Is it essentially baking in PWA mechanisms into blazor, does it work only with Blazor's mechanism for example NavigationManager.NavigateTo() or it works for a ref linking too

**Comment by SteveSandersonMS** [comment] 2023-06-05 08:25
@Xyncgas It should work for all the things that already work with traditional Blazor interactive client-side routing (e.g., on WebAssembly). Any case where we've intercepted navigation in the past to wire it up to the client-side router, we'll also intercept to wire up to this new system.

**Comment by Xyncgas** [comment] 2023-06-05 10:13
> Any case where we've intercepted navigation in the past to wire it up to the client-side router, we'll also intercept to wire up to this new system.

Thanks

**Comment by SteveSandersonMS** [comment] 2023-06-21 08:23
Duplicate of https://github.com/dotnet/aspnetcore/issues/48761 and https://github.com/dotnet/aspnetcore/issues/48762

**Closed by SteveSandersonMS** 2023-06-21 08:23 UTC
Labels: enhancement, area-blazor, Priority:1, feature-full-stack-web-ui
