### ISSUE TITLE
Revive Para Code Snippet

### ISSUE THREAD

**Issue by vertonghenb** [dotnet/aspnetcore#8904] opened 2019-03-29 01:15 UTC
### Is your feature request related to a problem? Please describe.
We used to have the code snippet `para > tab > tab` to generate:
```cs
[Parameter] protected TYPE Name {get;set;}
```
This got lost in some way, can we revive this snippet or extend on the idea?

### Describe the solution you'd like
Basically the PR was already present in Blazor : https://github.com/aspnet/Blazor/pull/974
I know @SteveSandersonMS  had some thoughts about the visibility therefore we could create 2 snippets
`para`
```cs
[Parameter] protected TYPE Name {get;set;}
```

`param` (about the same as propg)
```cs
[Parameter] TYPE Name
```

**Comment by vertonghenb** [comment] 2019-04-23 22:33
Is this up for grabs?

**Comment by danroth27** [comment] 2019-04-24 02:53
Yup.

**Comment by danroth27** [comment] 2019-05-21 06:07
@rynowak I think the experience we have with the `para` snippet in the Blazor VSIX is fine. There are plenty of other snippets that show up that are project type specific already (like all the WPF related ones: propa, propdp, etc.), so I don't see any issue with adding another one more.

@mkArtakMSFT Please assign

**Comment by danroth27** [comment] 2020-07-15 17:13
> Integrating these directly would be better because there is an issue with Visual Studio that causes the VSIX installer to fail when updating.

@madskristensen Is this a known issue with VSIX installation?

**Comment by EdCharbeneau** [comment] 2020-07-15 17:29
@danroth27  Reported here. https://developercommunity.visualstudio.com/content/problem/745995/cannot-update-or-reinstalling-vsix-installed-snipp.html

**Comment by SQL-MisterMagoo** [comment] 2020-07-16 09:07
Also note - code snippets don't appear to be working in the experimental razor editor...

**Comment by mkArtakMSFT** [comment] 2020-09-09 19:09
Thanks for contacting us. Closing as a dupe of the above referenced issue.

**Closed by mkArtakMSFT** 2020-09-09 19:09 UTC
Labels: area-blazor, enhancement, help wanted
