### ISSUE TITLE
Build-time Razor HTML generation 

### ISSUE THREAD

**Issue by Atulin** [dotnet/aspnetcore#41923] opened 2022-05-30 10:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Sometimes it doesn't make much sense to call some code every time a page is rendered. Being able to run it once on build time would bring a whole new amount of performance.

For example, let's say I have a list of contributors to my project stored somewhere as a JSON file and want to display it in the footer of my project.

Currently, the best solution is to create a `ViewComponent`, a helper tag, or a Razor component that will fetch the data from the file and display all of the contributors. That, however, means either

a) New I/O operation on every render of every page
b) Caching something that's just static data and won't change between versions

and both of those seem wasteful in their own way.

### Describe the solution you'd like

*Some* way to hook into the way Razor engine compiles `.cshtml` files to their final form. Ideally, a short, sweet and simple way, like a `StaticViewComponent` or `RenderMode.Build` for Razor components.

The way I envision it working would be, for example

```cs
<h1>@GetTime()</h1>

@code {
    private string GetTime()
    {
        var now = DateTime.Now;
        Log.Info("Rendering time data: {now}", now);
        return now.ToString();
    }
}
```

the above component being used anywhere in the project would always display the time of **build**, not the current server time. The information would either be logged to the console during build time or perhaps startup time, but just **once**.

**Comment by javiercn** [comment] 2022-05-30 11:54
@Atulin thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/38114. We are going to use that issue to track this request and we would suggest you upvote that issue instead.

**Closed by javiercn** 2022-05-30 11:54 UTC
Labels: area-blazor, blazor-wasm

**Comment by Atulin** [comment] 2022-05-30 12:04
Okay, seems similar enough. I'll leave a thumbs up there, then
