### ISSUE TITLE
Сreate a way to disable Request-Id header distribution in HostingApplicationDiagnostics

### ISSUE THREAD

**Issue by eduard-bystrov** [dotnet/aspnetcore#23217] opened 2020-06-22 12:45 UTC
here from https://github.com/aspnet/Hosting/issues/1385#issuecomment-388092179

Now we have OnActivityImport/OnActivityExport, but can't create a new root Id as desired, because it is already installed previously here https://github.com/dotnet/aspnetcore/blob/adbedd2cfb8dea7b5af3fe9e1c0d49684596e6d5/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L261

Is there an easy way to ignore Request-Id header distribution ?

**Comment by BrennanConroy** [comment] 2020-06-22 21:19
Dupe of https://github.com/dotnet/aspnetcore/issues/21012

**Closed** 2020-06-22 21:19 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-servers
