### ISSUE TITLE
Use IConfiguration from Program.cs in Blazor WebAssembly

### ISSUE THREAD

**Issue by yudielcurbelo** [dotnet/aspnetcore#20483] opened 2020-04-03 01:56 UTC
I'm trying to access wwwroot/appsettings.json from Program.cs in Blazor WebAssembly 3.2.0 Preview 3.

Content of Program.cs
` var configuration = builder.Services.BuildServiceProvider().GetRequiredService<IConfiguration>();
            var ApiBaseAddress = configuration["ApiBaseAddress"];`

Content of appsettings.json
`{
  "ApiBaseAddress": "https://localhost:5001/api/"
}`

Error
No service for type 'Microsoft.Extensions.Configuration.IConfiguration' has been registered.

**Comment by benhysell** [comment] 2020-04-06 01:39
I was able to get access to the configuration while setting up https://github.com/sounj142/HLSoft.BlazorWebAssembly.Authentication.OpenIdConnect

in Program.cs

```
builder.Services.AddAuthorizationCore(options => { })
               .AddBlazoredOpenIdConnect(async (provider) =>
               {
                   var options = new OpenIdConnectOptions();                  
                   var configuration = provider.GetRequiredService<IConfiguration>();
                   options.Authority = configuration["SpaOptions:Authority"].ToString(); 
                   options.ClientId = configuration["SpaOptions:SpaClientId"].ToString();
                   options.ResponseType = "token id_token";
                   options.Scopes.Add("openid");
                   options.Scopes.Add("profile");
                   options.Scopes.Add("email");
                   options.Scopes.Add(configuration["SpaOptions:Scope"].ToString());
                   return options;
               })
            ;
```

**Comment by benhysell** [comment] 2020-04-06 11:20
Looks like this is also being tracked over here: https://github.com/dotnet/aspnetcore/issues/20231

**Comment by mkArtakMSFT** [comment] 2020-04-06 16:53
Thanks @benhysell, this is indeed a dupe of the referenced issue.

**Closed by mkArtakMSFT** 2020-04-06 16:53 UTC
Labels: area-blazor, blazor-wasm
