### ISSUE TITLE
Embedded JavaScript doesn't get TextMate colorization in dark theme

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#36673] opened 2021-09-17 19:40 UTC
### Blue & Blue (Extra Contrast) & Light theme (Expected)
![image](https://user-images.githubusercontent.com/2008729/133844466-3caa7b2f-30d6-46e7-980f-f9596dcc3212.png)

### Dark theme
![image](https://user-images.githubusercontent.com/2008729/133844568-b793c242-dee5-4629-9f52-0a2ee72b79b4.png)

**Comment by ryanbrandenburg** [comment] 2021-09-29 23:38
Seems like a dupe of https://github.com/dotnet/aspnetcore/issues/32823.

**Closed by ryanbrandenburg** 2021-09-29 23:38 UTC
Labels: bug, area-razor.tooling, feature-razor.vs
