### ISSUE TITLE
Blazor: EditContextFieldClassExtensions unmodified field

### ISSUE THREAD

**Issue by Condra963** [dotnet/aspnetcore#16649] opened 2019-10-29 21:33 UTC
When we create a form, the default class of the input fields are already 'valid', even when the default value is 'invalid' the default class will already be 'valid'.

So the solution should be that you have 'valid' and 'invalid' class when submitted or modified, but when the form is just loaded the default class should not be 'valid' or 'invalid' yet.

This is the code part where it goes wrong:
```
public static string FieldCssClass(this EditContext editContext, in FieldIdentifier fieldIdentifier)
{
    var isValid = !editContext.GetValidationMessages(fieldIdentifier).Any();
    if (editContext.IsModified(fieldIdentifier))
    {
        return isValid ? "modified valid" : "modified invalid";
    }
    else
    {
        return isValid ? "valid" : "invalid";
    }
}
```

this is an example of the result, a form, not submitted, not modified, just loaded and ready to be filled in. But all fields are valid by default. (FYI: I overwritten the 'valid' class with the bootstrap 'is-valid' class if you where wondering why it has a different name.)

![image](https://user-images.githubusercontent.com/2640455/67810762-7917f980-fa9b-11e9-8f78-29a9340cfdf2.png)

**Comment by javiercn** [comment] 2019-10-30 08:54
@Condra963 thanks for contacting us.

I believe at this point this would be a breaking change. I do believe MVC has a similar concept of "not validated yet" but I'm not sure if there's an alternative way to look that up.

@SteveSandersonMS knows more about this area.

**Comment by SteveSandersonMS** [comment] 2020-10-09 12:46
Note that in 5.0 you can customize this behavior by implementing your own `FieldClassCssProvider`. Since we don't plan to change the default, I'll close this.

Note that the default behavior is useful as designed. You can use the "modified" class to know whether or not to highlight a field as "valid" if you want to do that only after edits.

**Closed by SteveSandersonMS** 2020-10-09 12:46 UTC
Labels: affected-most, area-blazor, enhancement, investigate, severity-blocking
