### ISSUE TITLE
Unable to read appsettings using appcmd.exe

### ISSUE THREAD

**Issue by geetmenon** [dotnet/aspnetcore#41596] opened 2022-05-09 20:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The below command used to work fine when we were on asp.net (with an appsetting  named MyFlag1 in web.config). It doesn't work any more now that we have migrated our app to asp.net core where we have our all our appsettings in appsettings.json (instead of in web.config). How do we get this to work in asp.net core? We are able to read the appsettings from within our asp.net core solution, but appcmd is not able to read it. We get the error 
"ERROR ( message:Cannot find requested collection element. )" 
What are we doing wrong?

appcmd.exe set config "MyWebSite" -section:appSettings /[key='MyFlag1'].value:"true"

We use IIS 7.5.

### Expected Behavior

Expect this command to change the MyFlag1 appsetting value to true in my appsettings.json

### Steps To Reproduce

1) Create a asp.net core app with appsettings.json

2) Let there be the following json entry in your appsettings.json
"MyFlag1": false

3) Add a website named "MyWebSite" pointing to this app.

4) Run the following command
%windir%\system32\inetsrv\appcmd.exe set config "MyWebSite" -section:appSettings /[key='MyFlag1'].value:"true"

### Exceptions (if any)

ERROR ( message:Cannot find requested collection element. )

### .NET Version

AspNetCore.App 5.0.10   NetCore.app.5.0.10

**Comment by adityamandaleeka** [comment] 2022-05-09 22:12
This is expected behavior. appcmd wouldn't know about appsettings.json or be able to modify it.

If you want to flow configuration to your ASP.NET Core app this way, you can use appcmd to define environment variables in web.config that will then be read by the ASP.NET Core app.

These links might be useful:
- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-6.0#set-environment-variables
- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0

**Comment by geetmenon** [comment] 2022-05-10 01:19
Could you please explain why this is the expected behavior.  Microsoft recommends that we move appsettings from web.config to appsettings.json when we migrate to aspnet.core. That is the reason why we moved all our settings from web.config to appsettings.json in the first place when we migrated to asp.net core.

See this link [https://docs.microsoft.com/en-us/aspnet/core/migration/configuration?view=aspnetcore-6.0](url)

**Comment by adityamandaleeka** [comment] 2022-05-11 06:10
@geetmenon Yes, you're right that appsettings.json is where configuration goes. The comment about "expected behavior" was for the fact that appcmd.exe doesn't know about appsettings.json.

**Comment by geetmenon** [comment] 2022-05-13 07:34
What kind of expected behavior is this?  If appcmd was earlier aware of appsettings when it was defined in web.config prior to migration, shouldn't appcmd be enhanced to be aware of appsettings in appsettings.json when it is Microsoft that recommended that we move appsettings from web.config to appsettings.json when we migrate to asp.net core? This explanation is not acceptable.

**Comment by geetmenon** [comment] 2022-05-16 20:51
We use appcmd.exe to start and stop our website as well as to change appsettings (which was earlier in web.config but is now migrated to appsettings.json). We do not use it to mutate applicationHostConfig.

**Comment by davidfowl** [comment] 2022-05-16 22:38
The only solution here that comes to mind would be to support an app settings based config provider that you can use to manage config in app settins. appcmd won't be updated to support `appsettings.json`, that doesn't make much sense to do since it's purpose is to modify iis configuration. ASP.NET Core runs outside of IIS and "appSettings.json is a decoupled from IIS" replacement for configuration. That said, configuration sources can be anything that can provide name value pairs so it would be possible to add one that could read appsettings from a site and could layer that into the current configuration system.  That way, you could in an IIS based workflow, keep using appcmd to manage your site, config, start and stop and then use this new config providers to read the settings.

Thoughts on that approach?

**Comment by geetmenon** [comment] 2022-05-18 02:11
An appsettings based config provider would be helpful.  Would greatly appreciate it if you can provide us that.

**Comment by adityamandaleeka** [comment] 2022-06-01 21:29
We're looking into options for solving this in https://github.com/dotnet/systemweb-adapters/issues/23

**Comment by adityamandaleeka** [comment] 2022-06-01 21:30
Let's use that issue for follow-up discussion. I'll close this one now.

**Closed by adityamandaleeka** 2022-06-01 21:30 UTC
Labels: area-runtime
