### ISSUE TITLE
Blazor WASM. Can not change BaseIntermediateOutputPath to another directory with preview4

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#20994] opened 2020-04-19 05:37 UTC
### Describe the bug
I have created an blank Blazor WASM app from scratch and tried to set a custom BaseIntermediateOutputPath in Directory.Build.props. Unfortunately this will throw a bunch of errors.

### To Reproduce
Follow the official guidelines to create a new project: https://docs.microsoft.com/de-de/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code

1. Create a new Blazor Webassembly project.
2. Create a Directory.Build.props file with this content:
```xml
<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)\build\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)\build\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```
3. The error occurres on dotnet build:
```pwsh
dotnet build
Microsoft (R)-Build-Engine, Version 16.5.0+d4cbfca49 für .NET Core
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Wiederherstellung in "621,93 ms" für "C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj" abgeschlossen.
  WebApplication2 -> C:\Users\Admin\Test\WebApplication2\build\bin\Debug\netstandard2.1\WebApplication2.dll
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error : Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'C:\Users\Admin\Test\WebApplication2\C:\Users\Admin\Test\WebApplication2\build\obj\Debug\netstandard2.1\blazor\service-worker-assets.js' [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: Unerwarteter Fehler bei der GzipCompressBlazorApplicationFiles-Aufgabe. [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: System.AggregateException: One or more errors occurred. (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'C:\Users\Admin\Test\WebApplication2\C:\Users\Admin\Test\WebApplication2\build\obj\Debug\netstandard2.1\blazor\service-worker-assets.js') [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]      
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:  ---> System.IO.IOException: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'C:\Users\Admin\Test\WebApplication2\C:\Users\Admin\Test\WebApplication2\build\obj\Debug\netstandard2.1\blazor\service-worker-assets.js' [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions 
options) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.File.OpenRead(String path) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]      
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.AspNetCore.Components.WebAssembly.Build.GzipCompressBlazorApplicationFiles.<Execute>b__4_0(CompressedFile file) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.TaskReplicator.Replica.Execute() [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    --- End of inner exception stack trace --- [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]   
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 
body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.AspNetCore.Components.WebAssembly.Build.GzipCompressBlazorApplicationFiles.Execute() [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]

Fehler beim Buildvorgang.

C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error : Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'C:\Users\Admin\Test\WebApplication2\C:\Users\Admin\Test\WebApplication2\build\obj\Debug\netstandard2.1\blazor\service-worker-assets.js' [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: Unerwarteter Fehler bei der GzipCompressBlazorApplicationFiles-Aufgabe. [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: System.AggregateException: One or more errors occurred. (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'C:\Users\Admin\Test\WebApplication2\C:\Users\Admin\Test\WebApplication2\build\obj\Debug\netstandard2.1\blazor\service-worker-assets.js') [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:  ---> System.IO.IOException: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. : 'C:\Users\Admin\Test\WebApplication2\C:\Users\Admin\Test\WebApplication2\build\obj\Debug\netstandard2.1\blazor\service-worker-assets.js' [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions 
options) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.IO.File.OpenRead(String path) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]      
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.AspNetCore.Components.WebAssembly.Build.GzipCompressBlazorApplicationFiles.<Execute>b__4_0(CompressedFile file) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.TaskReplicator.Replica.Execute() [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    --- End of inner exception stack trace --- [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]   
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 
body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.AspNetCore.Components.WebAssembly.Build.GzipCompressBlazorApplicationFiles.Execute() [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
C:\Users\Admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(72,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\Admin\Test\WebApplication2\WebApplication2.csproj]
    0 Warnung(en)
    2 Fehler

Verstrichene Zeit 00:00:05.86
```

### Further technical details
ASP.NET Core version: 3.1.201
The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Code
Include the output of dotnet --info:
```pwsh
dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.201
 Commit:    b1768b4ae7

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Additional info
I did already filed a similar bug with BaseIntermediateOutputPath: #18288
In that bug I tried to set it to a parent directory that didn't work. This doesn't work in this bug too. I had no time to verify if BaseIntermediateOutputPath could be set to the parent directory with preview3. So maybe you can verify that in that bug solution too.
Building without changing BaseIntermediateOutputPath works as expected and I think it is a problem within the addition of the new Compression.

**Comment by javiercn** [comment] 2020-04-20 09:58
@MarkusRodler thanks for contacting us. 

We'll take a look and get back to you.

**Comment by captainsafia** [comment] 2020-04-22 15:37
Thanks for reporting this detailed issue, @MarkusRodler.

I took a stab at reproing this with some slightly different dependencies:
* MSBuild 16.6.0-preview-20105-01+5d872c945
* Blazor WebAssembly 3.2.0-rc1 (from an internal feed to verify if this is an issue moving forward)

I wasn't able to reproduce the issue on these bits, which might indicate that it is msbuild-related or has been fixed in the delta between preview4 and rc.

The build targets currently derive the location to store compressed targets from the IntermediateOutputPath ([link](https://github.com/dotnet/aspnetcore/blob/98bbb3ba3e9409f24e27f80fb04a6427f385305e/src/Components/WebAssembly/Build/src/targets/Compression.targets#L15)). I can verify that it is consumed correctly by inspecting the build logs from my local build.

![image](https://user-images.githubusercontent.com/1857993/80002375-67287980-8474-11ea-8188-19c7583b61e1.png)

Can you share your build log?

**Comment by MarkusRodler** [comment] 2020-04-22 16:10
@captainsafia which command should I execute? I don't know about any other build log output except that from dotnet build.
I do not have Visual Studio. I use the command line client within VS Code

**Comment by captainsafia** [comment] 2020-04-22 16:18
You can execute the following in your commandline.

```
$ dotnet build /bl
```

This will generate a `msbuild.binlog` file that you can upload.

**Comment by MarkusRodler** [comment] 2020-04-22 16:21
Thanks. Here it is: [msbuild.zip](https://github.com/dotnet/aspnetcore/files/4517446/msbuild.zip)

**Comment by captainsafia** [comment] 2020-04-22 17:55
From what I can see in the build log, the intermediate path is set correctly. However, it looks like there are two forward slashes in the path name, caused by the extra slash in the build config. Remove it like so and let me know if that works.

```
<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)build\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)build\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```

**Comment by MarkusRodler** [comment] 2020-04-22 18:00
Nope. That does not fix the issue.
[msbuild.zip](https://github.com/dotnet/aspnetcore/files/4518130/msbuild.zip)

**Comment by captainsafia** [comment] 2020-04-22 18:10
Thanks for verifying this really quickly. Took another look and have just noticed that the project you are using is a PWA. Creating a new project using `dotnet new blazorwasm --pwa -o buildbug` reproduces the issue that you are seeing.

I'll take another look now that there is a repro and get back to you.

**Comment by captainsafia** [comment] 2020-04-23 19:07
I've got a fix out for this but it hasn't made the cut for RC.

As a temporary stopgap, you can use the following build props (not the relative paths, as opposed to full paths).

```
<Project>
  <PropertyGroup>
    <BaseOutputPath>build\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>build\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```

**Comment by MarkusRodler** [comment] 2020-04-24 05:42
Thanks @captainsafia 
Are there any plans when it will be fixed?

**Comment by captainsafia** [comment] 2020-04-27 19:52
It's likely that the fix will land as part of the .NET 5 releases with Blazor WASM. Unless more people report running into the issue at which point it'll be patched into Blazor WASm.

**Closed** 2020-05-13 17:10 UTC
Labels: Done, area-blazor, blazor-wasm, bug
