### ISSUE TITLE
Blazor wasm any event + @onfocusout event produces System.ArgumentException error only in Chrome

### ISSUE THREAD

**Issue by Grizor1911** [dotnet/aspnetcore#21366] opened 2020-04-30 15:22 UTC
<input id="EditBox" type="text" @onkeydown="KeyWasPressed" @onfocusout="() => anymethod()" value="@anyValue" />

    @code{
        int RowId;  

        private void KeyWasPressed(KeyboardEventArgs e)
        {
           RowId = 0; // needed to set some variable or anything for the error to appear
        }

        private void anymethod()
        {
           RowId = 0;
        }
    }

When any key is pressed in the input element, this error appears:
_**System.ArgumentException: There is no event handler associated with this event. EventId: '416'.
Parameter name: eventHandlerId**_

The error only appears using Chrome and including onfocusout event or maybe with others events too.

Can you help me with this please ?
Thanks.

**Comment by mkArtakMSFT** [comment] 2020-04-30 16:33
Thanks for contacting us. This is a dupe of #21240 1

**Closed by mkArtakMSFT** 2020-04-30 16:33 UTC
Labels: area-blazor
