### ISSUE TITLE
Code generation for setting Blazor component parameters

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#36071] opened 2021-09-02 00:09 UTC
Currently, we use reflection to find and set component parameter properties given a parameter name. A more performant alternative could be to code-gen parameter setting logic and avoid reflection altogether.

**Comment by mkArtakMSFT** [comment] 2021-11-16 19:28
Closing this as a dupe of #29550

**Closed by mkArtakMSFT** 2021-11-16 19:28 UTC
Labels: enhancement, Perf, area-blazor, triaged, area-razor.compiler, Priority:1
