### ISSUE TITLE
Request: `dotnet watch` with specific build Configuration (and Hot Reload)

### ISSUE THREAD

**Issue by Strepto** [dotnet/aspnetcore#38133] opened 2021-11-05 16:57 UTC
I am trying to run multiple `dotnet watch` on the same project, to run multiple instances of the program at the same time. But I am not able to do so because they conflict as the builds go to the same output folder.

This error comes in the second dotnet watch process:

```text
error MSB3021: Unable to copy file "C:\unimportant\bin\Debug\net6.0\App.dll" to "bin\Debug\net6.0\App.dll". The process cannot access the file 'C:\unimportant\bin\Debug\net6.0\App.dll' because it is being used by another process. 
```

I have been doing this using `dotnet watch run --configuration Debug`, and `dotnet watch run --configuration Debug2`. (Using two separate debug build configurations to have separate build outputs)
But this does not support the great hot-reload feature for dotnet 6. 

### Describe the solution you'd like

A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

I would like to be able to specify the configuration of the dotnet project by adding it as a parameter to dotnet watch

If it already exists, I would like for it to be documented somewhere how to do it. As I was not able to find any docs at all on dotnet watch :)

I have tried `dotnet watch --configuration Debug` but it does not work. 

Thank you for a great tool :)

**Comment by pranavkm** [comment] 2022-01-21 21:13
This is a dupe of https://github.com/dotnet/aspnetcore/issues/31365. We'll use the other issue to track further work.

**Closed by pranavkm** 2022-01-21 21:13 UTC
Labels: area-commandlinetools, feature-dotnetwatch, feature-hot-reload
