### ISSUE TITLE
Blazor Constructor Dependency Injection Stopped Working

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#41209] opened 2022-04-15 17:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Constructor-Dependency-Injection-/10013082)._

---
I had a working project which was using Blazor and dependency injection. At some point the dependency injection stopped working and I am unable to get it to work in any project. The main page just fails and shows that there was an unhandled exception. When I remove the Dependency, The page loads fine.

It seems that even the Injection of the HttpClient into TestService is not being injected properly. 

If I Change the injection on the Index page to an "@inject" or an "[Inject]" and manually pass in the HttpClient for the TestService, the injection of TestService Into Index Page seems to work. But its not possible to use those injection methods to inject into a service like TestService.

Essentially, Dependency Injection into a Constructor has stopped working, suddenly (4/12/22). It's worth noting that I tried to make a Blazor Project in VS2019 on .Net5 and encountered the same issue as in VS2022 on .Net 6.

    public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add("#app");

            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            builder.Services.AddTransient();

            builder.Services.AddTransient();

            await builder.Build().RunAsync();
        }
    }

    public class TestService
    {
        private HttpClient Http { get; set; }
        public TestService(HttpClient Http)
        {
            this.Http = Http;
        }
    }
Index:
{

    @page "/"

    <h1>Hello, world! </h1>

    Welcome to your new app.

    @code
    {
        public Index(TestService test)
        {

        }
    }
}

---
#### Feedback Bot on 4/14/2022, 03:32 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment] 2022-04-15 18:09
This a dupe of https://github.com/dotnet/aspnetcore/issues/18088#issuecomment-1058373609

**Closed** 2022-04-15 18:10 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, Author: Migration Bot :robot:, Status: Resolved
