### ISSUE TITLE
Add ability to generate PIN instead of long tokens when trying to generate confirm email token or change password token.

### ISSUE THREAD

**Issue by skillmaker-dev** [dotnet/aspnetcore#49607] opened 2023-07-24 17:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to generate confirmation pins (confirm email change, confirm password change...) that are 6-8 digits or letters long and that can be easily input by a user as a way to confirm email change, but there is only the ability to generate tokens that are very long and can't be input manually by user instead they are used in confirmation links to confirm the email in the existing methods like  ```UserManager<TUser>.GenerateEmailConfirmationTokenAsync(TUser)```.

### Describe the solution you'd like

It would be nice if there was a method to generate confirmation pins instead, for example ```GenerateEmailConfirmationPinAsync(TUser)``` or ```GeneratePasswordResetPinAsync(TUser)```

**Comment by mkArtakMSFT** [comment] 2023-07-25 16:56
Thanks for contacting us. This seems to be a dupe of https://github.com/dotnet/aspnetcore/issues/49549

**Closed by mkArtakMSFT** 2023-07-25 16:56 UTC
Labels: area-identity
