### ISSUE TITLE
Blazor Wasm: Antivirus rejects files written to cache, despite DLL bundling

### ISSUE THREAD

**Issue by paulguz-datapa** [dotnet/aspnetcore#40139] opened 2022-02-11 12:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

One of our customers uses [GData Internet Security.](https://www.gdatasoftware.com/internet-security) .

For our Blazor Wasm application, GData thinks that files written to the browser's cache storage are Trojans.  We have implemented DLL bundling as per the docs.  

This does not seem to be the case for other Blazor Wasm applications.  For instance, [Asteroids.Blazor](https://aesalazar.github.io/AsteroidsWasm/), a .Net 6 Wasm application, produces no such warnings.  I have tried other recent Blazor Wasm sites out there, and can't find another one that produces these warnings.

You can try our application at https://demo.test-inmydata.com/demo

If you wish, I can supply one of the cache files that GData doesn't like.  I'm not going to attach it here, considering that it's a file that antivirus considers a Trojan.

We are in communication with GData regarding this being a false positive.  However, there's an indication here that Multipart Bundling may not be enough to solve the Blazor Antivirus problem.

### Expected Behavior

Application should run with no Antivirus warnings

### Steps To Reproduce

1. Install GData Internet Security
2. In Chrome or Edge, navigate to  https://demo.test-inmydata.com/demo

### .NET Version

6.0.102

**Comment by javiercn** [comment] 2022-02-11 12:29
@paulguz-datapa thanks for contacting us.

This is a duplicate of https://github.com/dotnet/aspnetcore/issues/36978

I would suggest you take a look at this comment where someone has created an alternative solution https://github.com/dotnet/aspnetcore/issues/36978#issuecomment-1028877849

**Comment by paulguz-datapa** [comment] 2022-02-14 10:59
No, that alternative solution does not work.  GData must be finding something within the cached files that it objects to - the MIME type, possibly?

I don't know specifically which caching options you refer to; please supply a link to documentation.

**Comment by paulguz-datapa** [comment] 2022-02-14 11:29
@javiercn thanks for the link

**Comment by paulguz-datapa** [comment] 2022-02-14 13:54
@javiercn Turning off caching using <BlazorCacheBootResources>false</BlazorCacheBootResources> worked - GData no longer throws warnings.  Thanks for your help.

Is there any way at all <BlazorCacheBootResources> could be set at runtime?  So we could set it on or off per tenant?

**Comment by javiercn** [comment] 2022-02-14 14:24
https://github.com/dotnet/aspnetcore/blob/6ac8ebc38cd43027efb4b2cbb32599befe9a6f60/src/Components/Web.JS/src/Platform/WebAssemblyStartOptions.ts#L14

**Comment by paulguz-datapa** [comment] 2022-02-15 08:28
This issue is affecting live, revenue-generating, enteprise applications right now.  It completely blocks customers from using the product.  .Net 7 is 9 months away.  I sincerely hope any fixes are drip-fed in new preview packages, or .Net 6.1 if such a thing will exist.

**Comment by paulguz-datapa** [comment] 2022-02-15 12:32
Another consideration is PWAs.  The DLLs need to be removed from offlineAssetsInclude in service-worker.js or they will be in the offline cache and will be flagged by AV.  But this surely means the PWA will not run offline.

**Comment by danroth27** [comment] 2022-11-11 01:18
Closing as a duplicate of https://github.com/dotnet/aspnetcore/issues/36978

**Closed by danroth27** 2022-11-11 01:18 UTC
Labels: enhancement, area-blazor, triaged, blazor-wasm, webui-P1-JC, webui-P3-MB, webui-P3-TP, webui-P1-SS
