### ISSUE TITLE
Razor pages page route not selected based on route values; always uses the last one registered for the page

### ISSUE THREAD

**Issue by marius-bughiu** [dotnet/aspnetcore#24090] opened 2020-07-18 20:19 UTC
I have a `JobPosts/Index` page with multiple GET parameter bindings to allow filtering: let's take `CityId` and `IsRemote` for example. I don't want these to be passed as query string parameters, instead I want to use friendly routes for them. So I have defined these:

```
options.Conventions.AddPageRoute("/JobPosts/Index", "cities/{cityId}/jobs");
options.Conventions.AddPageRoute("/JobPosts/Index", "remote-jobs");
options.Conventions.AddPageRoute("/JobPosts/Index", "jobs");
```

The routes work just fine when I type them in the browser and the `CityId` one is bound properly, but two things are missing.

First, there is no way to specify a default value for my `IsRemote` param, which I want to set to `true` *ONLY* when using the `remote-jobs` URL. 

And second, when trying to generate a URL like this: 

```
<a asp-area="" asp-page="/JobPosts/Index" asp-route-cityId="@Model.CityId"></a>
``` 

I get the following URL: 

```
https://localhost:44391/jobs?cityId=2265885
```

When what I actually expect is:

```
https://localhost:44391/cities/2265885/jobs
````

So it looks like the tag helper or the part responsible for constructing the URL doesn't look at all at the different routes to try and get a best match based on the list of parameters. Actually, it will always use the last page route defined for that page. 

Nor do I have the option anywhere to specify a route name for the page route and then use `asp-route` to explicitly say which route I want. 

Any ideas how to achieve that? Or if it's something that's on the roadmap for Razor Pages?

Hardcoding the `href` is not an option. I want this to go through the proper routing pipeline as there are other things to be done as well, like generating culture-specific URL for non-english users (eg. `{cultureId}/cities/{cityId}/jobs` - this is done through route conventions. Hardcoding the `href` would obviously bypass that.

**Comment by captainsafia** [comment] 2020-07-21 16:54
Thank you for your feedback. We're closing this issue as the behavior discussed is by design.

@pranavkm Can you point to a code sample for how this can be implemented in the app?

**Comment by pranavkm** [comment] 2020-07-21 17:05
It would look something like this:

```C#
conventions.AddPageRouteModelConvention("/JobPosts/Index", convention =>
{
     // Use the route specified in MapPageRoute for outbound routing.
    foreach (var selector in model.Selectors)
    {
        selector.AttributeRouteModel.SuppressLinkGeneration = true;
    }

    
    foreach (var route in new[] { "cities/{cityId}/jobs", "remote-jobs", ... })
    {
        model.Selectors.Add(new SelectorModel
        {
            AttributeRouteModel = new AttributeRouteModel
            {
                Template = route,
            }
        });
    }
});
```

**Comment by javiercn** [comment] 2020-07-21 17:08
To add to what @pranavkm said, note that the set of routes you have there, are ambiguous for link generation. Routing will be incapable of deciding between unless you provide an explicit preference through order (meaning one of them will never be used for link generation)
```csharp
options.Conventions.AddPageRoute("/JobPosts/Index", "remote-jobs");
options.Conventions.AddPageRoute("/JobPosts/Index", "jobs");
```

**Comment by marius-bughiu** [comment] 2020-07-21 20:37
Thank everyone for taking the time to answer 💯 

@pranavkm thanks a lot for the code snippet, it seems to do the trick just fine though it's a bit weird why it's even needed. I would expect the `AddPageRoute` method to do the same, to simply add an additional `SelectorModel` without disabling all the existing ones, but from what I could notice while debugging (haven't looked at the source code yet), it actually sets the `SuppressLinkGeneration` to `true` on all previously registered routes, which is why they are not used in link generation. For someone used to classic MVC/WebAPI routing this is not something you would expect. But it's a start, I can work with this.

Is there a similar workaround for specifying a default value for an optional parameter? Something equivalent to this, where `IsRemote` is a bound property on my page model:

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(name: "remote-jobs",
                pattern: "remote-jobs",
                defaults: new { controller = "JobPosts", action = "Index", isRemote = true });
});
```

I tried to use a route template like this `remote-jobs/{isRemote=true?}`, but this will just result in a runtime error saying `RoutePatternException: An optional parameter cannot have default value.`. It's interesting that it recognizes the syntax and what I was trying to do, so is there a way to force this somehow?

@javiercn, you are right, in this case the order is important to determine which route to use by default, but more so - in order to enable one to use the similar routes, it would be important to allow people to specify a name for the route. Using Pranav's suggestion I was actually able to set a name (`AttributeRouteModel.Name`) for my `remote-jobs` route and then use `asp-route="my-route-name"` to explicitly state my preference on which of the two routes to be used for generating the link.

**Comment by pranavkm** [comment] 2020-07-21 20:44
@marius-bughiu the intent was for `AddPageRoute` to override the implicit route template created from the path (explicit vs implicit). Clearly there's a bug where calling `AddPageRoute` stomps over each other.

**Comment by marius-bughiu** [comment] 2020-07-22 07:18
@pranavkm, clear, then we should probably leave the issue open for someone to pick it up, right? 

I can also try and have a look at it over the weekend to see if I can fix it without having deep knowledge of what is happening under the hood, but I can't promise anything.

As for my optional parameter remark above, is there any way to achieve it with Razor Pages routing? & if not, should I open a new issue for it?

Thanks!

**Closed** 2020-11-12 02:01 UTC
Labels: area-mvc, feature-routing
