### ISSUE TITLE
Hot Reload doesn't work when passing -p flag

### ISSUE THREAD

**Issue by srpeirce** [dotnet/aspnetcore#31654] opened 2021-04-09 21:21 UTC
### Describe the bug
Dotnet 6 Preview 3.

Hot reload with `dotnet watch only seems to work when navigating to directory, but not passing project.

### To Reproduce
Hot reload does not work when passing in project with `-p` flag:
```
C:\code\P4\P4.Web [feature/net-6-preview3 +0 ~4 -0 !]> dotnet watch -p .\P4.Web.Public.Server\
watch : Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\code\P4\P4.Web\P4.Web.Public.Server
```

But does work when navigating to directory and `dotnet watch`:
```
C:\code\P4\P4.Web\P4.Web.Public.Server [feature/net-6-preview3 +0 ~4 -0 !]> dotnet watch
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  P4.ITOps.AspNetCore.Blazor.Core -> C:\code\P4\P4.Web\P4.ITOps.AspNetCore.Blazor.Core\bin\Debug\net6.0\P4.ITOps.AspNetCore.Blazor.Core.dll
  P4.ITOps.ApplicationInsights -> C:\code\P4\P4.Web\P4.ITOps.ApplicationInsights\bin\Debug\net6.0\P4.ITOps.ApplicationInsights.dll
  P4.Web.Shared.Components -> C:\code\P4\P4.Web\P4.Web.Shared.Components\bin\Debug\net6.0\P4.Web.Shared.Components.dll
  P4.Web.Public.Client -> C:\code\P4\P4.Web\P4.Web.Public.Client\bin\Debug\net6.0\P4.Web.Public.Client.dll
  P4.Web.Public.Client (Blazor output) -> C:\code\P4\P4.Web\P4.Web.Public.Client\bin\Debug\net6.0\wwwroot
  P4.Web.Public.Server -> C:\code\P4\P4.Web\P4.Web.Public.Server\bin\Debug\net6.0\P4.Web.Public.Server.dll
watch : Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\code\P4\P4.Web\P4.Web.Public.Server
```

### Additional Notes
This is a Blazor server that is prerendering a blazor client app.

Launchsettings:
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "P4.Web.Public.Server": {
      "hotReloadProfile": "blazorwasm",
      "commandName": "Project",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "launchUrl": "https://localhost:5001/"
    }
  }
}
```

**Comment by chneau** [comment] 2021-04-10 01:44
Hello,

This limitation is coming from here https://github.com/dotnet/sdk/blob/3ed075dff7d4b3025ebeeedcb0d9ab4d1644240a/src/BuiltInTools/dotnet-watch/Program.cs#L265 
There is a `isDefaultRunCommand` that forces the command to be only `dotnet watch` or `dotnet watch run`.

If this is of any help, here is some context that goes for enabling command line options:

Following https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/ , updating our blazor server project to use net6.0 is working just fine, no breaking change and hot reloading is just the best.

We were thinking to use multiple frameworks target `<TargetFrameworks>net5.0;net6.0</TargetFrameworks>` with nuggets conditions `<ItemGroup Condition = "'$(TargetFramework)' == 'net5.0'">` and the same for `'net6.0'` with their `6.0.0-preview.3.*` version, to enjoy developing with the awesome hot reloading, while building for production to net5.0.

But this approach needs extra parameters to the dotnet command that `isDefaultRunCommand` is not allowing for the moment.

```bash
# expecting this command to work when in project folder
dotnet watch run --framework net6.0

# expecting this command to work when in solution folder
dotnet watch --project Example.Web run --framework net6.0
```

**Comment by srpeirce** [comment] 2021-04-12 12:02
Thank you for the explanation @chneau.

**Comment by mkArtakMSFT** [comment] 2021-04-12 16:30
Thanks for contacting us. This is a dupe of #31365

**Closed by mkArtakMSFT** 2021-04-12 16:30 UTC
Labels: area-blazor, feature-hot-reload
