### ISSUE TITLE
StaticFileMiddleware serve pre-compressed file when found by file provider

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#38295] opened 2021-11-11 16:10 UTC
### Is your feature request related to a problem? Please describe.

Today, most sites have a build system in place to build, uglify, compress, remove unused code from static web assets such as css, js, or other assets. One such a build system could be webpack as an example. Furthermore, some sites might use such build systems to pre-compress some static assets to reduce the runtime load. The `StaticFileMiddleware` added by `UseStaticFiles` has currently no ability to serve a pre-compressed file if present or fallback to the uncompressed file.

### Describe the solution you'd like
It would be nice to add an opt-in option to the `StaticFileOptions` to enable serving pre-compressed files if present or otherwise falling back to the original uncompressed file.

The implementation would be straight forward I think. In the [StaticFileContext.cs#L115](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/StaticFiles/src/StaticFileContext.cs#L115) the file provider could be additionally queried for a compressed version of the requested file according to the `accept-encoding` request header. If a version of a pre-compressed file exists the `StaticFileContext` would serve the pre-compressed file and the `content-encoding` would be set accordingly. The `content-type` would be unaffected as it is retrieved by `IContentTypeProvider` from the originally requested path.
If there is no pre-compressed file available (i.e. the `IFileInfo.Exists` property returned by the file provider is `false`), the `StaticFileContext` would fallback and serve the normal uncompressed file.

**Comment by davidfowl** [comment] 2021-11-11 16:15
cc @DamianEdwards @javiercn

**Comment by Tratcher** [comment] 2021-11-11 16:24
Duplicate of #2458

**Closed** 2021-11-12 21:52 UTC
Labels: feature-StaticFiles, area-runtime
