### ISSUE TITLE
Blazor app crashes when debugging after updates

### ISSUE THREAD

**Issue by carlblanchard** [dotnet/aspnetcore#47238] opened 2023-03-15 21:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Everything was working perfectly over the weekend, I updated Visual Studio to 17.5.1 - On Monday I could no longer debug my Blazor application. It looks like it errors when redirecting to auth server. I have managed to obtain the following error from Console.

I've tried rolling back and uninstalling, working on different branches. Visual Studio. everything!!!

I am still running on .net 6 with most Nuget packages @ 6.0.15 I don't really want to upgrade to .net 7 as it's not LTS.

fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') at System.Collections.Generic.List1.get_Item(Int32 index) at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index) at Newtonsoft.Json.Linq.JArray.get_Item(Object key) at Microsoft.WebAssembly.Diagnostics.MonoProxy.AcceptEvent(SessionId sessionId, String method, JObject args, CancellationToken token) at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.OnEvent(SessionId sessionId, String method, JObject args, CancellationToken token) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)

I have since tried updating my project to .net 7 and all the Nuget packages to 7.0.4 and the problem still persists. 
Also, it looks like I am not the one with this problem, there are lots of people reporting the same here. https://learn.microsoft.com/en-us/answers/questions/1189857/blazor-app-crashes-when-debugging-after-windows-se?comment=question#comment-1230302

### Expected Behavior

To be able to run my Blazor WASM application

### Steps To Reproduce

Build a Blazor WASM project with authentication in .net 6 and run it on a system which has been recently updated to VS > 17.5.1 

### Exceptions (if any)

Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') at System.Collections.Generic.List1.get_Item(Int32 index) at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index) at Newtonsoft.Json.Linq.JArray.get_Item(Object key) at Microsoft.WebAssembly.Diagnostics.MonoProxy.AcceptEvent(SessionId sessionId, String method, JObject args, CancellationToken token) at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.OnEvent(SessionId sessionId, String method, JObject args, CancellationToken token) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)

### .NET Version

7.0.202

### Anything else?

![image](https://user-images.githubusercontent.com/18427214/225447478-0a5b9ec4-50b6-44ea-9b7d-58648dd6049c.png)

**Comment by carlblanchard** [comment] 2023-03-16 08:35
Removing breakpoints before starting the application does resolve the problem.
It seems you can apply them after it has started and they work as expected.

If any breakpoint remains when restarting the application it will fail again.

**Comment by liamfl** [comment] 2023-03-16 09:23
I have the same issue (.net 6 Blazor Wasm project, VS 17.5.1 and 17.5.2 with Edge 111.0.1661.41 and Chrome (whatever the latest version is). I can confirm that starting the project without breakpoints works.

**Comment by liamfl** [comment] 2023-03-16 09:26
I have just upgraded to Edge 111.0.1661.43 and can now run with breakpoints already set in my project

**Comment by ledluks** [comment] 2023-03-16 10:10
Same here. I updated to Visual Studio version 17.5.2 and the Blazor app won't start with brakepoints while using Chrome version 111.0.5563.65 (64-bit) meanwhile it seems to work for Edge version 111.0.1661.43 (64-bit).

**Comment by TimAndreJacobsen** [comment] 2023-03-17 13:13
Struggled with this issue as well. A good workaround atm is using a newer version of chrome.
e.g. the dev channel https://www.chromium.org/getting-involved/dev-channel/

then you can select the beta browser in VS. You might have to restart VS or even reboot for it to show up.
![image](https://user-images.githubusercontent.com/35067641/225914614-a0c50bd5-60db-4a3d-8427-b3b3dc9a03e9.png)

**Comment by rafael-f** [comment] 2023-03-17 14:46
Yeah on my Blazor Server app the app gets stuck on app.Run and does nothing when a project has breakpoints when I press play, no error message, nothing.

I guess it's worse on Blazor server because even breakpoints set after running it are not hit, it's seriously impacting my work, wasted hours to understand this yesterday.

**Comment by robalexclark** [comment] 2023-03-19 10:59
I am also having this issue with 17.5.2. Blazor server app using 7.0.4 packages runs fine until I set one breakpoint, then the app never starts (or completes rendering). Basically it looks like it locks up the browser, whether it is edge or chrome.

Removing all breakpoints resolves the issue but this is obviously not a viable workaround!

**Comment by MackinnonBuck** [comment] 2023-03-20 16:32
Thanks for reaching out. We currently are tracking this issue via https://github.com/dotnet/runtime/issues/83452. Closing this as a duplicate.

**Closed by MackinnonBuck** 2023-03-20 16:32 UTC
Labels: area-blazor
