### ISSUE TITLE
Password Reset Flow not working correctly on Blazor WASM Applications

### ISSUE THREAD

**Issue by efonsecab** [dotnet/aspnetcore#30923] opened 2021-03-14 13:51 UTC
### Describe the bug
Some of our customers are using Blazor WASM with Azure AD B2C, Flows, SignInSignUp policies work just fine, 
however, when we try to execute the Password Reset flow in the app we see this behavior
1. After clicking on the forgot password link, we see two subsequent login screens.
2. After clicking the second screen forgot password link, the flow redirects to the "/authentication/login-failed" page, which as we have read is by design, problem is, we tried to override all of the methods for both the login component and in a Custom Class inheriting from RemoteAuthenticationView and we have not been able to capture the action to continue the flow manually.
We need a feasible way to solve this issue.

### To Reproduce
1. Follow the steps in here: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C (https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
2. Configure a Password Reset flow in the portal and app
3. Click the Forgot Password link. The page redirects.
4. Click the Forgot Password link once again. The flow redirects to the applications with the login-failed action.

We also tried this but did not work:
https://iheartms.azurewebsites.net/2020/04/10/blazor-aad-b2c-additional-user-flows/?fbclid=IwAR0LQn1zeXPY5JIpezJkMtdzmQSkP38PkFzGeFeUM72-pSD1-rvTsR0BWOE
### Further technical details
- ASP.NET Core version: Blazor on .NET Core 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment] 2021-03-15 13:06
@efonsecab thanks for contacting us.

We only support sign-in/sign-up policies in our Azure AD and Azure AD B2C support. At release time msal.js didn't support any other flow (and I'm not sure if it currently does)

**Comment by javiercn** [comment] 2021-03-15 13:38
Closing this issue as a dupe of https://github.com/dotnet/aspnetcore/issues/27549

**Closed by javiercn** 2021-03-15 13:38 UTC
Labels: area-blazor, blazor-wasm
