### ISSUE TITLE
Blazor WebAssembly - very aggressive caching

### ISSUE THREAD

**Issue by Andrew-Webb** [dotnet/aspnetcore#29095] opened 2021-01-06 18:01 UTC
On ASP.NET Core 5.0, in a Blazor WebAssembly Client + Server + Shared website solution, the caching of assets can be very aggressive.

Today we republished a new version of our website (on `azurewebsites`).  For many people, including me, it would simply NOT get data from newly-introduced server-side "API" controllers that return JSON.  Instead the client got a standard HTML error page rather than the JSON.  (Of course everything had worked fine when I was running locally in Visual Studio.)

In the end, a `Hard Reload` (Ctrl+Shift+R) in Chrome got the client-side page to load its data from the server correctly.  But not even a Hard Reload / Hard Refresh worked in FireFox or Edge... I had to explicitly clear all cached data via those browser's options menus before the page worked correctly.

Over the last few months, from time to time, I have also had to do Hard Reloads in the browser when running locally in VS (Visual Studio Pro at latest) just to get some new asset to be downloaded from my Client website by the browser.

Hard to give you a repro because it's so inconsistent, but caching (like client-side debugging) is certainly a bit wonky in Blazor.

Apart from that, Blazor WebAssembly is fantastic and I love it!

BTW... all my "API" controllers that supply JSON to the client side SPA derive from this:-

```
    [ApiController]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public abstract class BaseApiController : ControllerBase
```

**Comment by chrissainty** [comment] 2021-01-06 18:24
I have been meaning to open a similar issue myself. The caching can really be a nightmare, I’ve lost several hours in total trying to fix errors which turned out to be aggressive caching, which only resolved by clearing the browser cache.

**Comment by Andrew-Webb** [comment] 2021-01-07 09:26
To clarify what has gone wrong:-

_On our published website_

Newly-introduced API controllers whose actions return JSON were not contactable until a `Hard Reload` or clear-browser-cache was performed in the browser (FF, Chrome, Edge).  When not contactable, standard error HTML saying "a problem happened; reload" was returned instead, but my app was expecting JSON not HTML, so the HTML was not displayed.  I think that the my client side code that made the request got an exception.

_On localhost + VS Pro_

New API controllers are always contactable.  However, adding JS functions to my `app.js` file (a small collection of JS functions in the Client project that I invoke from Blazor C#) is sometimes a problem.  *Sometimes* the new version of `app.js` won't be re-loaded until I do a `Hard Reload` in the browser... and sometimes this isn't the case.

**Comment by Andrew-Webb** [comment] 2021-01-07 09:29
Currently my web app is an internal-facing tool.  Telling our team to clear browser cache is ok.  But this problem tells us that we can't yet use Blazor WebAssembly for public-facing websites.  Telling your public to "clear browser cache if the website doesn't work properly" seems like something from 15 years ago.

Hopefully there is an easy workaround that you can tell us about...

**Comment by mkArtakMSFT** [comment] 2021-01-07 17:43
Thanks for contacting us. Are you facing this behavior with a PWA application? If that's the case, have you seen as it may be useful here: https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#caveats-for-offline-pwas

If that doesn't help, we would need a small repro project to be able to investigate this. Please share one as a GitHub repo.

**Comment by Andrew-Webb** [comment] 2021-01-07 18:11
> Are you facing this behavior with a PWA application?

No.

> If that doesn't help, we would need a small repro project to be able to investigate this. Please share one as a GitHub repo.

Groan.  If only it were that simple.  As I've indicated, this is one of those "sometimes" situations.  Plus it also depends on your own browser's history of interacting with a published app as it evolves.  I have built you repros before where such a thing was possible and relatively easy; this isn't one of those times.  As I've indicated, our published website suffered from newly-introduced API controllers not being contactable until browser cache was cleared, and this hasn't happened on localhost.  Therefore knocking something up in VS and running on localhost is little to the purpose... we'd need to have a published app and you'd need to have some history of interacting with it as it evolved over time.  Unfortunately I cannot give you access to our published website, because it's an internal-facing tool of some sensitivity.

If I was made redundant or furloughed tomorrow and was out of a job, I'd happily spend my time building a Blazor WebAssembly website, publishing it, browsing to it, evolving it, and hopefully being able to able to get a repro of the issue eventually.... (even if you couldn't get a repro because you hadn't interacted with it before).  I'd do that for sure, especially as some covid-furloughed guy has already turned "The Mandalorian" into a '90s sitcom, beating me to it.  But as it is, I'm under work deadlines.

Since this issue, to my mind, obviously does not fall into that happy category where you can just build a simple repro, send it over, you see the problem and fix it, I would urge you instead to dog food Blazor WebAssembly more.  As you've seen, even Blazor luminary @chrissainty suffers from this.

@chrissainty - any ideas for a repro?

**Comment by chrissainty** [comment] 2021-01-08 06:05
@Andrew-Webb The inability to create a reliable repro has been the reason I haven't opened an issue so far. Interestingly, reading about your experience, I'm seeing the issue more during local dev, I don't recall having experienced it yet on a published app.

**Comment by Andrew-Webb** [comment] 2021-01-08 10:19
I remember some details of how our published website came to require a browser-cache-clear / hard reload...

My boss published the new version of our website... I think from VS directly on his machine, since we haven't set up a publishing pipeline for it yet.  

We all hit it from various browsers, and it was obvious that something was wrong.  It soon became clear to me that the new `Client` website had been published, but that the `Server` website (with the new API controllers) had not.  So there was a mismatch between the `Client` and the `Server` aspects of the same web app that our browsers were talking to.  The two were not in sync.

He then deleted the whole thing from his machine, re-cloned from the repo, and re-published.  This time both `Client` and `Server` were the new versions, and in sync.

But now we encountered the needs-hard-reload-or-clear-browser-cache situation before new controllers in the `Server` were reachable.

Do you think the initial publishing failure and the fact that our browsers were hitting (and potentially caching resources from) the out-of-sync versions could have caused the caching problem?

If so, I would be less worried about the problem than I have been, since - for a public facing website - we would ensure that both client and server were correctly published and in sync before releasing the new version.  The public would not (hopefully) be spending any browser time hitting an out-of-sync version.

**Comment by javiercn** [comment] 2021-01-11 16:44
@Andrew-Webb It's really hard for us to tell what might be going wrong since it's very deployment specific. AFAIK we are doing the right thing. I would suggest you try to use a script like [this](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#troubleshoot-integrity-powershell-script) as a starting point to troubleshoot it yourself.

It will compare the output of a publish directory with the files being served to spot any differences. 

These types of errors can be caused by intermediate proxies serving obsolete versions of some files, something we don't have control of or by the app not being correctly configured to serve the cache-control headers (which it does by default).

**Comment by Andrew-Webb** [comment] 2021-01-11 16:47
Thanks @javiercn I'll keep that script in mind should it happen again.

**Closed** 2021-01-12 18:02 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor
