### ISSUE TITLE
Shouldn't the .NET 8 Blazor Web App template show client-server communication for WebAssembly SPAs?

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/aspnetcore#52285] opened 2023-11-22 09:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Prior to converting my .NET 7 ASP.NET-hosted Blazor WebAssembly apps (three of them) to .NET 8, I created some new apps using the new Blazor Web App template.

In no variation of creating an app did I end up with the client project _actually communicating with the server project over HTTP_ (if there can be said to be a server project... the `Server` designation seems to have gone away).

Instead, the Weather page in the client fakes it:-

```
        // Simulate asynchronous loading to demonstrate a loading indicator
        await Task.Delay(500);

        var startDate = DateOnly.FromDateTime(DateTime.Now);
        var summaries = new[] { "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching" };
```

Did I miss something?  What is the magic combination of choices that shows me genuine client-server communication?

Now, I can probably work out what to do... rename the first project to say "Server", add a "Shared" project, add controllers to the Server, set up the calls from the Client etc.

But really: shouldn't the template have these features?

If I'm right and the template simply doesn't include this stuff, then all I can say is that I'm glad I started with Blazor WebAssembly for creating SPAs in May 2020 and aren't starting now.  It seems to me that if you're starting now, using the new template won't help you any.

You're a new adopter.. you create a new Blazor WebAssembly solution with the new template... you get what is probably a Server project and you definitely get a Client project... _and the two don't even communicate with each other_!  It's bizarre and totally unhelpful.

### Describe the solution you'd like

The new .NET 8 Blazor Web App project template shows a clear "Blazor WebAssembly SPA with Client and Server" option, and includes code that demonstrates the client getting data from the server thru a shared model... instead of not doing so and "faking" a load of some data after a delay, purely in the client.

### Additional context

The changes need to be communicated better for users migrating solutions from .NET 5, 6, 7 - and more especially the new project template needs to show genuine client-server communication for people new to Blazor.

E.g when I migrate, should I keep the `Shared` project?  Or should I add shared DTOs to the `Client` project?  Is the `Shared` project deprecated now?  Or what?  The new project template is causing confusion, and not providing clear answers.

I was hoping (even expecting!) the template to take a major step forwards, and include a gRPC-instead-over-Http-communication-between-client-and-server option... instead it's taken a regrettable major step backwards by not showing any communication.

**Comment by mkArtakMSFT** [comment] 2024-01-03 01:28
Looks like this is a dupe of https://github.com/dotnet/aspnetcore/issues/52474

**Closed by mkArtakMSFT** 2024-01-03 01:28 UTC
Labels: area-blazor
