### ISSUE TITLE
 Support Blazor .Net 8 Microsoft.Identity.Web client for Azure clients

### ISSUE THREAD

**Issue by damienbod** [dotnet/aspnetcore#51374] opened 2023-10-14 06:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to implement a secure client Microsoft.Identity.Web (no ASP.NET Core Identity) using the new Blazor features.

In RC2, this does not work due to Blazor 8 State Management, required duplicate components and persisting the user state which is stored in a cookie on the client.

Would it be possible to support this for the different rendering modes

### Describe the solution you'd like

The application authenticates against Microsoft Entra ID using the Web flow and requires a secret or a certificate. (Single Azure App registration)

OIDC Code flow with PKCE is used, not implicit flow which is the default using Microsoft.Identity.Web

The authentication session is stored in a HTTP only secure cookie.

All Blazor components in the different rendering modes have access to the authentication claims and the user session.

The Anti-forgery cookie is used to access APIs or any post, delete, put requests to the same site server. This can be added to the request using a html component in the form or a HTTP request header using a HttpClient.

No unsecure inline scripts are used in the client.

ASP.NET Core Identity is not used.

UI components can be displayed checking the authorized state

Logout form request uses the Anti-forgery cookie

**Comment by JeremyLikness** [comment] 2023-12-19 17:28
We just added the sample for [OIDC with Microsoft Entra (Azure AD)](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebOidc) ... does this get you what you are looking for/need?

**Comment by joseph-hungerman** [comment] 2023-12-19 19:29
Is the Aspire portion required?

Joseph Hungerman
Founder/CEO
SEE/EYE, LLC
ph: (615) 559-9495
em: ***@***.***

https://see-eye.io<https://see-eye.io/>

Let's meet! https://savvycal.com/joseph-hungerman
________________________________

**Comment by joseph-hungerman** [comment] 2023-12-19 21:06
What package is this extension in? AddHttpForwarderWithServiceDiscovery

I'm still getting the same error (I have tried on Chrome & Firefox):

An unhandled exception occurred while processing the request.
AuthenticationFailureException: Correlation failed.

Unknown location

AuthenticationFailureException: An error was encountered while handling the remote login.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

  *   Stack
  *   Query
  *   Cookies
  *   Headers
  *   Routing
  *
AuthenticationFailureException: Correlation failed.
  *
Show raw exception details
  *
AuthenticationFailureException: An error was encountered while handling the remote login.
     *
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
     *
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
     *
SeeEye.Toolbox.Infrastructure.Extensions.PipelineExtensions+<>c__DisplayClass0_0+<<UseSecurityHeaders>b__0>d.MoveNext()
     *
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

________________________________

**Comment by joseph-hungerman** [comment] 2023-12-20 08:23
OK, so I figured out the cookie issue. The problem was in my effort to make my app secure. I set the Referrer-Policy to "strict-origin-when-cross-origin" which apparently messed everything up. I will re-test your new OIDC example with this change in mind.

**Comment by joseph-hungerman** [comment] 2023-12-20 13:33
> We just added the sample for [OIDC with Microsoft Entra (Azure AD)](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebOidc) ... does this get you what you are looking for/need?

I tested the new sample implementation, and it worked well. I think it is a big step forward, but the documentation still needs to be updated. A couple things I noticed:

1. The sample wraps the router in a CascadingAuthenticationState component, which I thought was out of fashion with .NET8. Should AddCascadingAuthenticationState be added to the server and client projects?
2. The documentation warns against adding an HTTP context accessor in the Program file, which the template has.

**Comment by damienbod** [comment] 2024-01-04 07:49
Hi @JeremyLikness @halter73 

Thanks for the example. I tried this and it does not work for me. After the authentication is complete, the client **AuthenticationStateProvider** gets updated with no state (after a small delay)

Greetings Damien

**Comment by halter73** [comment] 2024-01-08 23:43
> Thanks for the example. I tried this and it does not work for me. After the authentication is complete, the client **AuthenticationStateProvider** gets updated with no state (after a small delay) and the authenticated session is reset.

Is this something you see while running the [BlazorWebOidc sample](https://github.com/dotnet/blazor-samples/tree/bf071e1fbc9bedd15e3366e822942c512ffbec23/8.0/BlazorWebOidc) without modification? Do you have a stack trace for whatever is constructing the client's `PersistentAuthenticationStateProvider` constructor the second time? This shouldn't hapen since it's registered as a singleton.

**Comment by damienbod** [comment] 2024-01-09 12:02
Hi @halter73 Thanks for your reply. Almost. I just switched out the OpenID Connect client to use a local STS and remove the aspire stuff. 

I create the trace later.

**Comment by damienbod** [comment] 2024-04-05 06:47
@halter73 Got around to looking at this. I did not disable the Microsoft claims mappings. When the claims renaming is disabled, everything works. I will create a PR to update the docs

**Comment by danroth27** [comment] 2024-12-11 17:52
@halter73 @mikekistler Is this basically a duplicate of #51202?

**Comment by halter73** [comment] 2024-12-11 19:57
Yes. I'll close it. @damienbod let us know if you disagree.

**Closed by halter73** 2024-12-11 19:57 UTC
Labels: Docs, area-blazor
