### ISSUE TITLE
ImageDisplay component sample

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#37016] opened 2021-09-27 16:53 UTC
Create an ImageDisplay component sample that efficiently displays a byte[]/stream as an image via streaming it to the browser.

**Comment by TanayParikh** [comment] 2021-09-27 16:57
Part of: https://github.com/dotnet/aspnetcore/issues/36991

**Comment by javiercn** [comment] 2021-09-29 09:38
I think this is a dupe of another issue I filed a while ago.

**Closed** 2021-11-04 18:05 UTC
Labels: Working, Docs, area-blazor, feature-blazor-jsinterop
