### ISSUE TITLE
Fix warning: "CS0618: 'RelationalIndexBuilderExtensions.HasName(IndexBuilder, string)' is obsolete"

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#22630] opened 2020-06-06 20:45 UTC
Introduced in #22558 due (apparently) to a breaking change in efcore e.g. aspnetcore-ci build [20200605.41](https://dev.azure.com/dnceng/public/_build/results?buildId=674408&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=a59c73d3-09b1-5a7e-4e53-9d83598ad56e&l=3109). The warning did not occur in the previous build of master ([20200605.38](https://dev.azure.com/dnceng/public/_build/results?buildId=674408)) but did in the CI validation of #22558 ([20200605.33](https://dev.azure.com/dnceng/public/_build/results?buildId=674271)).

Part of #22240

**Comment by smitpatel** [comment] 2020-06-06 20:47
Duplicate of #22610

**Comment by smitpatel** [comment] 2020-06-06 20:49
Something missing, checking

**Comment by dougbu** [comment] 2020-06-06 20:55
@smitpatel yeah, the rolling build of your fix for #22610 (#22612) already hit this warning [here](https://dev.azure.com/dnceng/public/_build/results?buildId=674929&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=a59c73d3-09b1-5a7e-4e53-9d83598ad56e&l=2563).

Not sure I understand though. Why not rebuild the migrations❔

**Comment by smitpatel** [comment] 2020-06-06 21:12
3 files were missed that for migration file. Added pragma disable in those in #22631 

>Not sure I understand though. Why not rebuild the migrations❔

@ajcvickers @AndriySvyryd @bricelam

**Comment by ajcvickers** [comment] 2020-06-06 21:18
@smitpatel Lots of customers will have Identity migrations already in their project. Regenerating migrations here won't help them. I don't think we want them all to be getting warnings that they then have to suppress/fix. That's why we need to discuss this breaking change at a higher-level--i.e. should we just revert it.

**Comment by smitpatel** [comment] 2020-06-06 21:38
>  I don't think we want them all to be getting warnings that they then have to suppress/fix.

Only migrations generated in 1.x releases and API breaks to the API which was available back then will have to react. Post 1.x everything works fine. Let's discuss in team meeting.

**Comment by ajcvickers** [comment] 2020-06-06 21:52
@smitpatel Got it. So this is only because this sample hasn't been updated since the 1.0 rc3 release. We should double check that migrations shipped for 2.x and 3.x don't have these issues. (It is a manual step to update these migrations, so just because we put the code to ignore obsoletes in a 2.x release doesn't mean the Identity migrations necessarily picked up that change.)

**Comment by smitpatel** [comment] 2020-06-06 22:04
I was testing out upgrade path since this repo had warnings coming out of migrations.
- Created a migration which uses HasName on index using 5.0-preview4 packages. It used `HasName`
- Upgraded to nightly build.
- Fixed build warning in OnModelCreating code to use `HasDatabaseName`, build passed without warning.
- Generated a new migration, ModelSnapshot got updated to use new API. New migration is using new API. Old migration still uses old API but does not warn due to pragma.

We can do more thorough testing with older snapshot. @bricelam would know if we have testing in our repo for such scenarios. I think important learning from this would be, if we are going to support all old migrations then we can obsolete model building APIs but cannot remove them ever.

**Comment by ajcvickers** [comment] 2020-06-06 23:02
@smitpatel Specifically, I am concerned about the pre-generated migrations that are added to your project from the template when you create a new ASP.NET Core app and choose Individual Auth. The 3.1 templates must include migrations that don't have this issue for this break to be acceptable. (I'm pretty sure this is true.) I would be even more comfortable if the 2.1 templates also work.

**Closed** 2020-06-07 18:17 UTC
