### ISSUE TITLE
Blazor Deprecated Error in Lighthouse - UnloadHandler

### ISSUE THREAD

**Issue by Beblia** [dotnet/aspnetcore#57882] opened 2024-09-16 05:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Lighthouse produces a deprecated code error. Blazor.web.js is using deprecated function = UnloadHandler
It would be great to update the code in web.js to not use this code for .NET 10.

Thank you for the great work on Blazor!

### .NET Version

.net 8, .net 9

**Comment by javiercn** [comment] 2024-09-16 10:10
@Beblia thanks for contacting us.

This issue is a dupe of https://github.com/dotnet/aspnetcore/issues/56081#issuecomment-2149631058

**Closed by javiercn** 2024-09-16 10:10 UTC
Labels: area-blazor
