### ISSUE TITLE
Razor compiler produces incorrect markup content for single-quoted attributes

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#20950] opened 2020-04-17 15:05 UTC
Repro: Create a `.razor` file containing:

```razor
<button onclick='alert("hello")'>Click me</button>
```

Compiled result:

```
__builder.AddMarkupContent(0, "<button onclick=\"alert(\"hello\")\">Click me</button>");
```

This is incorrect because the double-quotes inside the attribute haven't been encoded in any way. At runtime, clicking on the button will produce an error (`SyntaxError: Unexpected end of input`).

Expected result: Something like

```
__builder.AddMarkupContent(0, "<button onclick=\"alert(&quot;hello&quot;)\">Click me</button>");
```

Or even:

```
__builder.AddMarkupContent(0, "<button onclick='alert(\"hello\")'>Click me</button>");
```

Do we claim to support single-quoted attributes fully in Razor?

cc @ajaybhargavb @NTaylorMullen

**Comment by NTaylorMullen** [comment] 2020-04-17 18:05
> Do we claim to support single-quoted attributes fully in Razor?

Yes

**Comment by phlexpay** [comment] 2020-05-03 06:16
Does this mean this will be part of the next preview.  This issue has been lingering and prevents the user of blazor in scenarios where json content is used in attributes.  So js-carousel and other controls like that basically dont work on the client or server side blazor.

**Comment by SteveSandersonMS** [comment] 2020-05-04 09:52
> Does this mean this will be part of the next preview

There isn't a specific ETA that I can see listed on this issue but @NTaylorMullen would know best whether this is expected to be fixed as part of some 5.0 preview.

> So js-carousel and other controls like that basically dont work on the client or server side blazor.

If you can supply an example of some markup that you're struggling with, I'm sure we can suggest a supported way to represent it in a `.razor` file.

**Comment by phlexpay** [comment] 2020-06-12 08:55
See the sample below.  Within the data-options tag json is used to configure the control.  This is a very common practice for html5 controls.  In many cases folks simply buy precreated templates and use them as a starting point for their sites.  We cannot be expected to delve though 100s of thousands of html code escaping double quotes.  One of the tenets of HTML rendering is to render **exactly** what the developer created.  This is what got you in trouble with ASP.NET in the first place !  No other framework does this.  If I use angular my HTML just works as is.  The moment I try to incorporate controls stop rendering and HTML errors start piling up.  Please fix this as this is an amazing technology but folks has been mentioning this for a long time now. 

<section class="dzsparallaxer auto-init height-is-based-on-content use-loading" **data-options="{direction: reverse, settings_mode_oneelement_max_offset: 150}"**>
    
    <div class="divimage dzsparallaxer--target w-100 u-bg-overlay g-bg-black-opacity-0_5--after" style="height: 140%; background-image: url(/assets/img-temp/1920x1080/img35.jpg)"></div>
    

    <div class="container text-center g-color-white g-py-200--md g-py-80">
        <div class="row">
            <div class="col-md-8 ml-md-auto mr-md-auto">
                <div class="u-heading-v7-2 g-mb-30">
                    <h2 class="display-4 u-heading-v7__title g-mb-20">

                        The <span class="g-color-primary">PHLEX</span> Story
                    </h2>
                </div>

                <hr />
                <p class="lead g-mb-60 pull-left">
                    Phlex is a fully featured retail management platform built from the ground up with flexibility, security, and collaboration in mind.
                    With Phlex you have all the power of large scale retail management systems without any of the headaches of maintaining them.  Phlex
                    is cloud native, distributed, and highly scalable, allowing it to scale from taking payments on your phone or tablet to running a multi-store, multi-regional
                    fleet of stores.  Whether it be inventory management, customer relationship management, event management, invoicing, or retail point-of-sale, Phlex is the
                    place for you.
                </p>

                @*<a class="js-fancybox-media btn btn-xl u-btn-primary g-rounded-15" href="javascript:;" data-src="//vimeo.com/14220611" data-animate-in="flipInY" data-animate-out="flipOutY" data-speed="1000">
                        <i class="fa fa-video-camera g-mr-15"></i>
                        Watch Our Presentation
                    </a>*@
            </div>
        </div>
    </div>
</section>

**Comment by SteveSandersonMS** [comment] 2020-06-12 13:50
@phlexpay Could you clarify? Are you saying that adding the attribute `data-options="{direction: reverse, settings_mode_oneelement_max_offset: 150}"` to an element doesn't work in some way? In what way doesn't it work?

I just tried adding that attribute and it appeared to work correctly, so it would be great if you could clarify what's wrong in this specific case. Thanks!

**Comment by phlexpay** [comment] 2020-06-12 18:30
I've created a simple example to show the problem.  The snippet to prompt the user with the name john, however because the single quotes of the attribute data-one are converted into double quotes the resulting value of the attribute (when requested via the dom) is **data-one="{"name":"john"}"**

so the getAttribute returns **{**  instead of the whole contents of the attribute.

**//html page script section**
 <script defer>
        function DoSomething() {
            var btn_one = document.getElementById("one");
            alert(btn_one);
            var attr = btn_one.getAttribute("data-one");
            alert(attr);

            var result = eval("(" + attr + ")");
            alert(result.name);
        }
    </script>

**//razor page**
<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<p id="one" data-one='{"name":"john"}'>Pet: dsfsfds</p>

<button @onclick="test">Hellooooo</button>

@code
{

    async protected override Task OnAfterRenderAsync(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        await JS.InvokeVoidAsync("DoSomething");
    }

    async void test()
    {
        await JS.InvokeVoidAsync("DoSomething");
    }

}

**Comment by phlexpay** [comment] 2020-06-12 18:37
Again this kind of use of json within attributes if fairly common with HTML controls that need advanced configuration to render.  And when you buy a template and want to use it it will be there.  I am converting a template I have used perfectly fine with normal asp.net core and angular.  Why cant we get the html we created when the blazor page renders.  Changing single quotes to double quotes can cause a lot of problems as previously shown by other folks.  We shouldnt have to go back through our code escaping quotes just so we can use blazor.  As I understand it this is the future of asp.net - it should just work.

**Comment by SteveSandersonMS** [comment] 2020-06-12 19:35
It seems that you’re using a single-quoted attribute, which is exactly what this issue already tracks the need for us to fix. 

Apologies that I misunderstood your intent before. I thought you were reporting a different issue when in fact you were providing another illustration of this existing issue.

**Comment by NTaylorMullen** [comment] 2020-06-12 22:33
> There isn't a specific ETA that I can see listed on this issue but @NTaylorMullen would know best whether this is expected to be fixed as part of some 5.0 preview.

Sadly this issue isn't currently planned for the .NET 5.0 milestone

**Comment by LockTar** [comment] 2021-04-11 20:04
I see the labels connected to this issue that states this isn't happening a lot. I think it does. @phlexpay explains it very well. Third party html controls can't be used now because of this. Whole bought templates are running against this problem. 
I'm running now again against this problem with implementing a template. I never had these problems with asp .net  mvc or pages. 

@phlexpay did you find a solution for the problem? I'm having the same problem with the same plugin.

**Comment by LockTar** [comment] 2021-04-12 15:27
Changing the following:

```
data-options='{direction: "fromtop", animation_duration: 25, direction: "reverse"}'
```
to
```
data-options='{direction: &quot;fromtop&quot;, animation_duration: 25, direction: &quot;reverse&quot;}'
```
seems to work for me! Not really a workaround that you want but it works for **this** problem. Hopefully as well for all others...

@SteveSandersonMS do you have another suggestion?

**Comment by phlexpay** [comment] 2021-04-12 15:33
That's not a viable solution.  First off many third party html controls also inject html attributes and elements *via javascript*. Secondly it is unrealistic to expect each developer to wade through 10000 lines of code from an external vendor searching for every instance of quotes so they can use escape characters.  Again, any rendering technology needs to *honor the markup it encounters* or it wont be viable.  As I stated originally, it's this kind of bizarre modification of the markup that frustrated everyone away from asp.net and the asp.net designers.  Why are we going back to this.

**Comment by SteveSandersonMS** [comment] 2021-04-12 15:42
I’m not saying this isn’t a problem (clearly it is) but want to clarify that it doesn’t affect anything injected via JS. It only has an effect at compile time.

**Comment by LockTar** [comment] 2021-04-12 15:52
@phlexpay I'm not saying that this is a nice solution. It is a temporarily workaround until hopefully Microsoft fixes this issue. Hopefully this issue will get higher priority. 



>but want to clarify that it doesn’t affect anything injected via JS. It only has an effect at compile time.
@SteveSandersonMS just to confirm: 
You mean that if in example json is injected in the html the problem is not there?

**Comment by SteveSandersonMS** [comment] 2021-04-23 14:36
> You mean that if in example json is injected in the html the problem is not there?

Not sure what you mean by that. I was specifically addressing the concern raised above ("many third party html controls also inject html attributes and elements via javascript.") and saying that's not relevant to the issue here since JavaScript happens at runtime, so the Razor compiler couldn't see anything it's doing anyway. The Razor compiler only runs at compile-time.

**Closed** 2021-06-15 18:29 UTC
Labels: affected-very-few, area-blazor, area-razor.compiler, area-razor.tooling, bug, feature-razor.language, severity-nice-to-have
