### ISSUE TITLE
[6.0.100-preview.4.21178.2] Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.0 error on .net 6.0.100-preview.4.21178.2

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/aspnetcore#31387] opened 2021-03-30 08:22 UTC
**Application Name:**  Blogifier, WalletWasabi,YoyoCmsFreeTemplate,OqtaneFramework,Moonglade
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** main branch - 6.0.100-preview.4.21178.2
App 3.1 Blazor Server app, running .net6, has dependecy to  System.Drawing.Common 4.7.0: 
**Source code check at:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1302985](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1302985)
**Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build  6.0.100-preview.4.21178.2: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-preview.2.21158.2: Pass
3). Windows 10 RS5 X64 + .NET Core SDK build 5.0.104 : Pass
4). Windows 10 RS5 X64 + .NET Core SDK build 3.1.300 Pass

**Repro steps to run**
Repro source at: [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1302985](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1302985)
1) Copy LoadDllErrorApp link provided in above devdiv bug.
2) Run WebApplication2.exe
3) Go to http://localhost:5000/counter
4) Click Click me button

**Expected Result:**
It should display image size,

**Code for click me button :**
```
Image img = Image.FromFile("test.jpg");
testWidth= img.Width.ToString();
```

**Actual Result:**
```
  Unhandled exception rendering component: Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

      System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
      File name: 'System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
         at WebApplication2.Pages.Counter.IncrementCount()
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```

**Findings:**
In Asp.net apps, when we have dependency to System.Drawing.Common(4.7.0), after we publish, it doesn't create "runtimes" folder, when we run it against  6.0.0-preview.4.21178.2, we get the above error, if we update System.Drawing.Common package to latest(5.0.2), when we publish, it creates "runtimes" folder,  and  app works fine.  We have seen this issue on 2 Asp .NET apps : Blogifier and WalletWasabi.

WalletWasabi  app, we have a similar error :

 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.SystemEvents, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Win32.SystemEvents, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at WalletWasabi.Services.Terminate.TerminateService..ctor(Func`1 terminateApplicationAsync)
   at WalletWasabi.Gui.Program..cctor()
   --- End of inner exception stack trace ---
   at WalletWasabi.Gui.Program.TerminateAppAndHandleException(Exception ex, Boolean runGui)
   at WalletWasabi.Gui.Program.Main(String[] args)

We think these issues are related,  System.Drawing.Common has dependency to Microsoft.Win32.SystemEvents

@dotnet-actwx-bot  @dotnet/compat

**Comment by ericstj** [comment] 2021-03-30 16:15
This is by-design.  Roll-forward across major versions is not guaranteed to work.  When running an app on a newer framework than it was built on you may face problems when a breaking change is made.  To work-around you can either a) reference a newer version of System.Drawing.Common package so that it will be carried app-local or b) retarget to net6.0.

This breaking change was announced here: https://github.com/dotnet/aspnetcore/issues/31007

cc @pranavkm

**Comment by Pilchie** [comment] 2021-03-30 17:17
Duplicate of #31007

**Comment by jiangzeng01** [comment] 2021-03-31 05:27
Thanks @Pilchie & @ericstj !
Link announcement here [https://github.com/aspnet/Announcements/issues/456](https://github.com/aspnet/Announcements/issues/456)

**Closed** 2021-04-01 01:31 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-infrastructure
