### ISSUE TITLE
[Minimal API] Validation errors are absent in response

### ISSUE THREAD

**Issue by JohnyL** [dotnet/aspnetcore#41686] opened 2022-05-14 16:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using FluentValidation and `IRouteHandlerFilter` in minimal API (using `AddFilter`):
```csharp
// Fluent validation
builder.Services.AddFluentValidation(config =>
  config.RegisterValidatorsFromAssembly(typeof(Program).Assembly));

// API
app
  .MapPost("/clients-m", async (ClientsContext db, ClientM client) =>
  {
    var newClient = db.Add(client);
    await db.SaveChangesAsync();
    var entity = newClient.Entity;
    return CreatedAtRoute("GetClientByIdAsync", new { id = entity.Id }, entity);
  })
  .AddFilter<ValidationFilter<ClientM>>();

// Validator class
public class ClientValidator : AbstractValidator<ClientM>
{
  public ClientValidator()
  {
    RuleFor(c => c.Id)
      .GreaterThan(0)
      .WithMessage("Oops! Incorrect ID. Value must be greater than 0!");
  }
}

// Validation filter
public class ValidationFilter<T> : IRouteHandlerFilter where T : class
{
  private readonly IValidator<T> validator;

  public ValidationFilter(IValidator<T> validator) => this.validator = validator;

  public async ValueTask<object> InvokeAsync(
    RouteHandlerInvocationContext context,
    RouteHandlerFilterDelegate next)
  {
    var validatable = context.Parameters.SingleOrDefault(x => x.GetType() == typeof(T)) as T;
    if (validatable is null)
    {
      return BadRequest(new { Error = "Could not find any validator." });
    }

    var validationResult = await validator.ValidateAsync(validatable);

    if (!validationResult.IsValid)
    {
      var errors = validationResult.ToDictionary();
      return ValidationProblem(errors);
    }

    return await next(context);
  }
}

// Extension method for generating IDictionary for ValidationProblem
public static class ValidationExtensions
{
  public static IDictionary<string, string[]> ToDictionary(this ValidationResult validationResult)
    => validationResult.Errors
         .GroupBy(x => x.PropertyName)
         .ToDictionary(
           g => g.Key,
           g => g.Select(x => x.ErrorMessage).ToArray());
}
```
I passed incorrect `id` (less than 0), but didn't get validation errors in response:

![image](https://user-images.githubusercontent.com/7391680/168439604-2b57d3d7-d0db-4972-a035-6cbefc3619fe.png)

However, if I use controllers, everything works:
```csharp
// Adding controllers
builder.Services.AddControllers().AddFluentValidation();
// ...
app.MapControllers();

// Controller
[ApiController]
[Route("[controller]")]
public class ClientsController : ControllerBase
{
  private readonly ClientsContext db;

  public ClientsController(ClientsContext db) => this.db = db;

  [HttpPost]
  public async Task<IActionResult> Post(ClientM client)
{
    var newClient = db.Add(client);
    await db.SaveChangesAsync();
    var entity = newClient.Entity;
    return Created($"/clients-m/{entity.Id}", entity);
  }
}
```
Response:

![image](https://user-images.githubusercontent.com/7391680/168439728-e165f1c5-0078-494c-ab5a-773526c8c854.png)

P.S. As a note: it worked in .NET 7 Preview 3.

### .NET Version

7.0.100-preview.4.22252.9

### Anything else?

• Visual Studio 2022 Version 17.3.0 Preview 1.0
• It worked in .NET 7 Preview 3

**Comment by martincostello** [comment] 2022-05-14 16:59
Dupe of #41634?

**Comment by JohnyL** [comment] 2022-05-14 17:05
@martincostello Yes. Seems the problem is fixed. 🙂

**Closed** 2022-05-17 23:00 UTC
Labels: feature-minimal-actions, area-web-frameworks
