### ISSUE TITLE
ASP.Net Hosting Bundle Installer Has Issues In Some Situations

### ISSUE THREAD

**Issue by Ni2Be** [dotnet/aspnetcore#42764] opened 2022-07-17 09:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The ASP.Net Hosting Bundle installer fails if a ASP.Net Runtime (the x64 installer) already exists on the system in a higher version.

Reproduce:
1. Install ASP.Net x64 installer v6.0.7 (https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
2. Install ASP.Net Hosting Bundle installer v6.0.3

We are shipping the Hosting Bundle with our own installer. That installer must be installable on devices not connected to the web.
The only option we have at the moment is to first uninstall the higher version of ASP.Net and then install the lower version of Hosting Bundle - that is of course not optimal. 

I already tried executing the Hosting Bundle installer with some options of: https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md
but it just leads to making the installation work but then the installed ASP version is broken.

(Issue may be related to: https://github.com/dotnet/aspnetcore/issues/33819)

Another issue is already documented in https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md
"If the Hosting Bundle is installed before IIS, the bundle installation must be repaired. Run the Hosting Bundle installer again after installing IIS."

That is also a problem because we offer Addons that will install IIS but use .Net Framework themself. So it would be very confusing to just ship the Hosting Bundle with them just to run the repair setup if needed.

Why exactly is this repair needed? We did some testing and it seems to work for our use-cases, is this still an issue?

### Expected Behavior

Hosting Bundle should install normally even if a higher version of ASP.Net Runtime is already installed.
Hosting Bundle should not need to be repaired if it was installed before IIS.

### Steps To Reproduce

1. Install ASP.Net x64 installer v6.0.7 (https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
2. Install ASP.Net Hosting Bundle installer v6.0.3

**Comment by adityamandaleeka** [comment] 2022-07-18 22:18
@wtgodbe PTAL

**Comment by Ni2Be** [comment] 2022-07-19 05:35
> Why do you need to install the standalone asp.net runtime before you install the hosting bundle? The hosting bundle includes the asp.net runtime, it should be all you need

We don't have influence on what a customer has already installed on his system. Maybe he first installed some other program that was shipped with just standalone asp.net runtime. 
Then we have a problem when he wants to install our product after that.

**Comment by wtgodbe** [comment] 2022-07-20 16:25
What error does the customer see when using the OPT_NO_SHAREDFX switch from https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md? 

I think you're right that this is related to https://github.com/dotnet/aspnetcore/issues/33819 - @joeloff as I recall it was an issue w/ the WiX documentation where it seemed like the success blocker would do what we wanted, but it actually couldn't. Is the only solution here for the us to tell customers to manually uninstall older runtimes before installing the newer hosting bundle within the same feature band?

**Comment by joeloff** [comment] 2022-07-20 17:06
Kind of. The success blockers were intended for a different situation around redistributable bundles, which almost feels like it fits our situation, but we'd need to implement it end-to-end to verify.

**Comment by joeloff** [comment] 2022-07-20 18:52
Tested a fix for this, I'll ping you offline. This scenario is one we can address, but it will have to be over multiple releases since we can retroactively update previously published bundles. We probably want to fix this in the runtime installs as well.

**Comment by Ni2Be** [comment] 2022-07-21 06:05
> What error does the customer see when using the OPT_NO_SHAREDFX switch from https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md?
> 

I don't have an error log of the program that fails to start, only from the install log something like "Failed to start the service".
It's some work to recreate that issue, @wtgodbe, @joeloff would that information help or are you good?

**Comment by wtgodbe** [comment] 2022-07-21 16:03
@Ni2Be for now, you should tell the customer to manually uninstall the asp.net shared framework before installing the hosting bundle (they can re-install the newer asp.net shared framework afterwards if they want). Long term, we'll fix this scenario with https://github.com/dotnet/aspnetcore/pull/42857 (and will backport it to various servicing branches).

@NikolaMilosavljevic can dotnet/runtime make a similar change to https://github.com/dotnet/aspnetcore/pull/42857 so we can support this scenario (installing a hosting bundle on a machine that has a newer runtime SharedFx already installed)?

**Comment by Ni2Be** [comment] 2022-07-21 16:12
@wtgodbe will do. Thanks!

**Closed** 2022-07-22 11:20 UTC
Labels: feature-installers, area-runtime

**Comment by NikolaMilosavljevic** [comment] 2022-07-26 16:43
> @Ni2Be for now, you should tell the customer to manually uninstall the asp.net shared framework before installing the hosting bundle (they can re-install the newer asp.net shared framework afterwards if they want). Long term, we'll fix this scenario with #42857 (and will backport it to various servicing branches).
> 
> @NikolaMilosavljevic can dotnet/runtime make a similar change to #42857 so we can support this scenario (installing a hosting bundle on a machine that has a newer runtime SharedFx already installed)?

I'd prefer if Hosting bundle could ignore runtime installer's failure to downgrade. @joeloff does Wix stdba supports something similar?

**Comment by joeloff** [comment] 2022-07-26 17:01
Yes, that's the change that Will made for ASP.NET. The bundles inside the hosting bundle need to implement the success blocker.

Let's say you have two runtime bundles, 5.0.6 and 5.0.8

- You install runtime 5.0.8
- You install hosting bundle 5.0.6
- The hosting bundle will report a downgrade failure when it tries to run the 5.0.6 runtime

Once you add the success blocker, the downgrade error is ignored by the 5.0.6 runtime bundle and reported as a success result to the hosting bundle. 

I created 3 bundles: NestedV1.exe, NestedV2.exe (think of these as the runtime installers) and SuccessBlocker.Exe (the hosting bundle). I first install NestedV2, then SuccessBlocker.Exe (which carries an older copy, NestedV1). When the outer bundle executes the older v1 bundle, the log will show the following:

```
[14D8:0B58][2022-07-26T09:57:22]i000: A newer version of this product is installed but downgrade failure has been suppressed; continuing..
```

This is an implementation detail in WiX that cannot be changed. The success blockers must be included in the inner bundles.

**Comment by NikolaMilosavljevic** [comment] 2022-07-26 18:02
Thanks @joeloff - by success blocker I presume you are referring to this attribute, that would be added to runtime bundle:

`bal:WixStandardBootstrapperApplication@SuppressDowngradeFailure="yes"`

**Comment by NikolaMilosavljevic** [comment] 2022-08-01 16:43
> @Ni2Be for now, you should tell the customer to manually uninstall the asp.net shared framework before installing the hosting bundle (they can re-install the newer asp.net shared framework afterwards if they want). Long term, we'll fix this scenario with #42857 (and will backport it to various servicing branches).
> 
> @NikolaMilosavljevic can dotnet/runtime make a similar change to #42857 so we can support this scenario (installing a hosting bundle on a machine that has a newer runtime SharedFx already installed)?

@wtgodbe was ASP.Net change made for 7.0 only, or did you backport to earlier releases?

**Comment by wtgodbe** [comment] 2022-08-01 16:44
I'm backporting it to all active servicing branches

**Comment by NikolaMilosavljevic** [comment] 2022-08-09 17:53
@wtgodbe @joeloff just so we are super clear. Adding this attribute to Runtime installers will let the older Runtime bundle install an older version to user's machine. It will not simply ignore the warning. At least that's what I'm seeing in my tests.

**Comment by joeloff** [comment] 2022-08-10 00:20
Yes, except for the host because the MSI upgrades so should be detected by the runtime bundle as a superseded install. The complete fix for this would be to ensure all the MSIs are upgradable, but that breaks current behavior and opens up other issues. Users can easily remove the older runtime, so it's slightly better than not being able to install the hosting bundle.

**Comment by NikolaMilosavljevic** [comment] 2022-08-10 16:58
> Yes, except for the host because the MSI upgrades so should be detected by the runtime bundle as a superseded install. The complete fix for this would be to ensure all the MSIs are upgradable, but that breaks current behavior and opens up other issues. Users can easily remove the older runtime, so it's slightly better than not being able to install the hosting bundle.

Yeah, host is upgradable, so everything seems to be working fine. I've also confirmed that installing a newer version of runtime, would uninstall all previous versions, as well, so that is also working fine.

Thanks for confirming!
