### ISSUE TITLE
I set the BlazorWebAssemblyLoadAllGlobalizationData property to true but not working after publish in .net 6 preview 7

### ISSUE THREAD

**Issue by zarinportal** [dotnet/aspnetcore#35338] opened 2021-08-13 19:27 UTC
### Describe the bug
I set the BlazorWebAssemblyLoadAllGlobalizationData property to true but not working after publish in .net 6 preview 7.

### To Reproduce

\<BlazorWebAssemblyLoadAllGlobalizationData\>true\<\/BlazorWebAssemblyLoadAllGlobalizationData\>

### Exceptions 
System.AggregateException: AggregateException_ctor_DefaultMessage (Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.)
 ---> System.InvalidOperationException: Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyCultureProvider.ThrowIfCultureChangeIsUnsupported() in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x60000b5+0x55
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken , WebAssemblyCultureProvider ) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x60000be+0x60
   at <Program>$.<<Main>$>d__0.MoveNext() in Presentation.Client.dll:token 0x600011a+0x2cb
   Exception_EndOfInnerExceptionStack

### Further technical details
- Blazor WebAssembly
- .Net 6 Preview 7
- Visual Studio 2022 Version 17.0.0 Preview 3.0

**Comment by 3x0dv5** [comment] 2021-08-16 13:15
I am seeing the same behaviour, also when publishing from command prompt

```
dotnet publish --force -o C:\temp\Deployments\MyApp\ -f net6.0 --runtime linux-x64 --configuration Release --self-contained -p:BlazorEnableCompression=true -p:BlazorWebAssemblyLoadAllGlobalizationData=true 
```

I even tried to see if passing -p:BlazorWebAssemblyLoadAllGlobalizationData=true would make any difference, but no joy.
```
dotnet publish --force -o C:\temp\Deployments\MyApp\ -f net6.0 --runtime linux-x64 --configuration Release --self-contained -p:BlazorEnableCompression=true -p:PublishTrimmed=True -p:BlazorWebAssemblyLoadAllGlobalizationData=true 
```

**Comment by 3x0dv5** [comment] 2021-08-16 22:08
As a side effect I found what seems an issue with the VS2022 installer. Because I had to rollback the whole migrating to preview7 I also decided to uninstall VS2022, and it seems that VS2022 took the awesome Cascadia font with it, had to install it again :)

**Comment by zarinportal** [comment] 2021-08-17 08:36
I think we will have to wait for the next version :) . I hope the problem is solved in the next version

**Comment by ThomasKuijper** [comment] 2021-08-18 12:20
I have the same problem. Only occurs after publishing

**Comment by ThomasKuijper** [comment] 2021-08-25 12:23
Any updates? Maybe a workaround? I would like to continue testing

**Comment by zarinportal** [comment] 2021-08-25 16:52
Im still waiting and praying for the problem to be solved :)

**Comment by zarinportal** [comment] 2021-08-31 09:20
Thank you @pranavkm
I tried to solve my problem according to what you said.
I made these changes in the NuGet.Config file but it did not make a difference.
I definitely made a mistake. Please help me 

![image](https://user-images.githubusercontent.com/44922871/131475903-e4b20e0f-fe59-4b28-b959-27af4cad28a4.png)

**Comment by pranavkm** [comment] 2021-08-31 15:14
@zarinportal the fix is specifically in the SDK / installer. For e.g. one of these if you're on x64 Windows: https://aka.ms/dotnet/6.0.1XX-rc1/daily/dotnet-sdk-win-x64.exe

**Comment by ThomasKuijper** [comment] 2021-09-01 08:55
@pranavkm I tried it, so did a publish with that installer, and then run it on IIS with the same SDK installed on the server.
Still get the following error:

`blazor.webassembly.js:1 System.AggregateException: One or more errors occurred. (Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.)
 ---> System.InvalidOperationException: Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyCultureProvider.ThrowIfCultureChangeIsUnsupported()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken cancellationToken, WebAssemblyCultureProvider cultureProvider)
   at Admedis.Blazor.Client.Program.Main(String[] args)
   --- End of inner exception stack trace ---`

**Comment by mkArtakMSFT** [comment] 2021-09-02 16:16
This seems to be the same as #35459. Leaving this hear for whoever is going to investigate this later to look at both together as they may be dupes

**Comment by zarinportal** [comment] 2021-09-06 11:34
I think a new version will come in a day or two. I hope it will be solved soon

**Comment by SteveSandersonMS** [comment] 2021-09-08 13:25
On investigation this is **not** related to #35459. That issue is about `IStringLocalizer` and a problem in the generated `.resx` resource names, whereas this issue is about `BlazorWebAssemblyLoadAllGlobalizationData` and how we load native ICU data which is a completely different part of the product.

However I was not able to reproduce this using the latest nightly SDK (RC2):

 * I created a webassembly app that triggers the *Blazor detected a change in the application's culture that is not supported with the current project configuration* error, and then verified that adding `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>` did fix it.
 * Then I published the application, since people above have said this only occurs after publishing. But when running the published app, it behaved correctly with no errors.

So it seems likely that this was fixed in RC1. If anyone can still repro it with the [latest nightly SDK (RC2)](https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries), then please supply a repro project and details repro steps.

**Comment by ThomasKuijper** [comment] 2021-09-08 14:09
@st

> On investigation this is **not** related to #35459. That issue is about `IStringLocalizer` and a problem in the generated `.resx` resource names, whereas this issue is about `BlazorWebAssemblyLoadAllGlobalizationData` and how we load native ICU data which is a completely different part of the product.
> 
> However I was not able to reproduce this using the latest nightly SDK (RC2):
> 
> * I created a webassembly app that triggers the _Blazor detected a change in the application's culture that is not supported with the current project configuration_ error, and then verified that adding `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>` did fix it.
> * Then I published the application, since people above have said this only occurs after publishing. But when running the published app, it behaved correctly with no errors.
> 
> So it seems likely that this was fixed in RC1. If anyone can still repro it with the [latest nightly SDK (RC2)](https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries), then please supply a repro project and details repro steps.

I tried it with my app 7 days ago.
For now I tried creating a brand new app and inserting my localized code. But it seems that the new 'blazor wasm' project template is broken. If I publish I get errors 'Warning MSB3026: Could not copy "C:\Users\thoma\.nuget\packages\microsoft.aspnetcore.components.webassembly.authentication\6.0.0-rc.2.21455.6\staticwebassets\AuthenticationService.js.LICENSE.txt'

So the steps I did 7 days ago:

- Used the nightly SDK installer from that day
- Updated all packages to latest nightly 
- Added <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> to csproj
- Added the following code to program.cs
 `  var culture = new CultureInfo('nl-NL);
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;
            CultureInfo.CurrentUICulture = culture;`
- Used a resx file in the project and the 'Microsoft.Extensions.Localization.IStringLocalizer' to load in a resource
- Published this and used it in an IIS site

**Comment by SteveSandersonMS** [comment] 2021-09-08 14:41
@ThomasKuijper Thanks for replying. Since I posted before, I actually did manage to repro the issue :) The difference is that this only happens in the "ASP.NET Core Hosted" case and not in the "Standalone" WebAssembly case.

So, it **is still an active issue and is not fixed in RC1**.

The good news is that we think we know what's wrong and how to fix it.

**Comment by SteveSandersonMS** [comment] 2021-09-08 14:44
@javiercn This is the publishing issue we were discussing. To observe the issue more directly, create a hosted project, and in the client csproj, add `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>`.

* On a normal build, `blazor.boot.json` will contain `"icuDataMode": 1`
* But in the publish output, `blazor.boot.json` will contain `"icuDataMode": 0`

As we discussed, it seems that `GetCurrentProjectPublishStaticWebAssetItems` fails to call `_ResolveBlazorWasmOutputs`, which means that `_BlazorWebAssemblyLoadAllGlobalizationData` remains undefined, and then when we call `GenerateBlazorWebAssemblyBootJson`, the `LoadAllICUData` parameter is unset, which is why the resulting `icuDataMode` shows up as the default value `0` instead of `1` which means `BlazorWebAssemblyLoadAllGlobalizationData`.

**Comment by ThomasKuijper** [comment] 2021-09-08 16:56
> @ThomasKuijper Thanks for replying. Since I posted before, I actually did manage to repro the issue :) The difference is that this only happens in the "ASP.NET Core Hosted" case and not in the "Standalone" WebAssembly case.
> 
> So, it **is still an active issue and is not fixed in RC1**.
> 
> The good news is that we think we know what's wrong and how to fix it.

Superb, thank you for your continued investigations. Sadly it wont be RC1 then, but it would be for final release right?

**Comment by SteveSandersonMS** [comment] 2021-09-08 17:00
Correct. We're aiming to fix it in RC2, as RC1 is already pretty much locked.

Editing `blazor.boot.json` manually is inconvenient but you could do it. Remember to also delete or edit the compressed versions of that file as well.

**Comment by javiercn** [comment] 2021-09-08 17:06
@SteveSandersonMS if this is the MSBuild thing we discussed, it can probably be achieved by setting the property in the csproj file as a workaround. It might be a bit more convenient.

**Comment by zarinportal** [comment] 2021-09-08 19:10
> 
> 
> Correct. We're aiming to fix it in RC2, as RC1 is already pretty much locked.
> 
> Editing `blazor.boot.json` manually is inconvenient but you could do it. Remember to also delete or edit the compressed versions of that file as well.

@SteveSandersonMS Thanks for replying. Since I'm using brotli formats, I will first try to extract the blazor.boot.json.br file by paezip, then edit it and compress it again and using it in published project.Will this problem be solved in .Net 6 Preview 8 version?

**Comment by javiercn** [comment] 2021-09-08 19:15
@zarinportal as a workaround is much easier if you unconditionally set this `_BlazorWebAssemblyLoadAllGlobalizationData` to the right value in your csproj file

**Closed** 2021-09-08 22:03 UTC
Labels: bug, area-blazor, blazor-wasm, Needs: Attention :wave:

**Comment by zarinportal** [comment] 2021-09-09 03:22
@javiercn I set BlazorWebAssemblyLoadAllGlobalizationData property to true in .csproj but not be solved

**Comment by zarinportal** [comment] 2021-09-09 08:52
@SteveSandersonMS are you program manager for Microsoft? If this is true, I have a suggestion for Blazor development. You can save Brotli files in the browser cache after extraction to be loaded in a much shorter time in the next page refresh and no need to extract again brotli files

**Comment by javiercn** [comment] 2021-09-09 08:55
@zarinportal note the leading underscore `_BlazorWebAssemblyLoadAllGlobalizationData`

**Comment by javiercn** [comment] 2021-09-09 08:55
> @SteveSandersonMS are you program manager for Microsoft? If this is true, I have a suggestion for Blazor development. You can save Brotli files in the browser cache after extraction to be loaded in a much shorter time in the next page refresh and no need to extract again brotli files

We already do this when possible.

**Comment by zarinportal** [comment] 2021-09-09 10:41
> 
> 
> > @SteveSandersonMS are you program manager for Microsoft? If this is true, I have a suggestion for Blazor development. You can save Brotli files in the browser cache after extraction to be loaded in a much shorter time in the next page refresh and no need to extract again brotli files
> 
> We already do this when possible.

Ok its good.thanks
