### ISSUE TITLE
CascadingValue ignoring element's razor definition

### ISSUE THREAD

**Issue by MihaMarkic** [dotnet/aspnetcore#43750] opened 2022-09-05 07:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Not sure whether this is a bug or not, but it seems to me like one. Imagine razor code like this:
```razor
@if (SomeValue is not null) {
  <CascadingValue Name="xxx" Value="cascading_value">
    <MyComponent Input="SomeValue" />
  </CascadingValue>
}
```

I'd assume MyComponent won't ever get a null SomeValue, right?
However, sometimes it does and I pinpointed to probably caused by CascadingValue.
I have a feeling that if an action happens, SomeValue is set to null and cascading_value changes*, MyComponent life cycle would start **regardless of that explicit if** at root and it's Input parameter will be null.
Another pointer that it is related to CascadingValue is that if I set it to `IsFixed="true"` the issue disappears.
* cascading_value might even not actually change but see ^^

Though my project is fairly complex and I couldn't reproduce it with a repro project so far.
If someone thinks it's worth and perhaps give me some helping info, I'd try to repro it for good.

### Expected Behavior

Lifecycle of the page should be honored and null SomeValue shouldn't be passed to MyComponent regardless of CascadingValue change.

### Steps To Reproduce

So far I couldn't reproduce, but probably some nested CascadingValues in components.

### .NET Version

6.0.400

**Comment by javiercn** [comment] 2022-09-05 17:04
@MihaMarkic thanks for contacting us.

There seems to be a problem going on in your app. It is very unlikely that CascadingValue is responsible for it. If you are able to reproduce it, we might be able to take a look, but we currently do not have enough information to think that there is an issue in this area.

**Comment by MihaMarkic** [comment] 2022-09-06 07:35
@javiercn Fair enough. I'll try to reproduce it. But in the meantime, how is it even possible for getting to OnParametersSet with SomeValue being null? Any idea?

**Comment by javiercn** [comment] 2022-09-06 09:32
@MihaMarkic Unfortunately, we don't have enough context to make an educated guess.

**Comment by MihaMarkic** [comment] 2022-09-12 09:18
Hey @javiercn, after quite a lot of sweat I've managed to strip down the project to a simple as possible sample.
[BlazorCascadeIssue.zip](https://github.com/dotnet/aspnetcore/files/9546532/BlazorCascadeIssue.zip)
Though code is not beautiful, it should demonstrate the issue at hand.

When you start the app you should see text Form Root, below is a Refresh button and bellow Subform / FormX / /Subform.

Click Refresh and you'll get the exception in FormX.razor because Meta parameter is null. Now check SubForm.razor where FormX is configured - it is within `if (FormMeta is not null)` statement which means it shouldn't be null at all.

The components hierarchy is:
MasterPage -> FormRoot -> ItemContainer -> SubForm -> FormX.

Refresh button on FormRoot triggers refresh at MasterPage which results in the exception (I think triggering from within MasterPage would result in same behavior).
You'll also see quite a loot of senseless CascadingValues, those are real in my project, but I changed them to dummies. Interestingly, if I remove any of them (or some of them) the exception isn't triggered. This goes also to some seemingly unrelated code such as Task.Delays and whatnot. It was really an exercise in patience to strip the project down to this small sample.
Anyway, perhaps I'm doing something wrong, but the outcome is really odd, or there is a nasty hidden bug in Blazor somewhere.

**Comment by MackinnonBuck** [comment] 2022-10-26 23:49
@MihaMarkic I took a look at your repro. The behavior you're experiencing doesn't appear to be specific to `CascadingValue` - you can create a dummy component and replace all occurrences of `CascadingValue` with it, and you will experience the same issue.

Note that `OnParametersSetAsync()` isn't guaranteed to complete before the component starts rendering. My guess as to what's happening is that you have just the perfect combination of `Task.Delay()`, nested components, and `StateHasChanged()` calls such that the `await InitFormAsync()` line in `SubForm.razor.cs` happens to yield execution to a previously queued render of the `FormX` component. This causes `FormX`'s `OnParametersSet()` method to run in between the time that `FormMeta` is reset to `null` and re-initialized in `InitFormAsync()`.

I noticed that there are a couple unnecessary `StateHasChanged()` calls that are causing the component to render 4 times per button click. Removing those extra calls and restructuring the logic so the case I described above can't happen should resolve your issue.

**Comment by MackinnonBuck** [comment] 2022-11-01 17:58
@MihaMarkic Another thing that could resolve your issue is to modify the code you pasted to the following:

```razor

<CascadingValue Name="xxx" Value="cascading_value">
  @if (SomeValue is not null) {
    <MyComponent Input="SomeValue" />
  }
</CascadingValue>
```

That way, there isn't an opportunity for there to be a "gap" between when the `if` statement is evaluated and when `SomeValue` is read and passed as a parameter to `<MyComponent />`.

Closing this issue out as by-design.

**Closed by MackinnonBuck** 2022-11-01 17:58 UTC
Labels: area-blazor
