### ISSUE TITLE
Random View Compilation Error

### ISSUE THREAD

**Issue by joetherod** [dotnet/aspnetcore#22808] opened 2020-06-11 02:28 UTC
App: aspnet MVC core 3.1
This is a tenant based web application. Views are stored in database and compiled on runtime.
The app hosts over 500 different sites. Sites are split up into specific hosted linux containers.
I get the below error randomly when it compiles a view:

```
Exception: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
/app/Views/_ViewImports.cshtml(3,19): Error RZ1036: Invalid tag helper directive look up text '*, Microsoft.AspNetCore.Mvc.Razor'. The correct look up text format is: "name, assemblyName".
/app/Views/DbShared/_ViewImports.cshtml(3,19): Error RZ1036: Invalid tag helper directive look up text '*, Microsoft.AspNetCore.Mvc.Razor'. The correct look up text format is: "name, assemblyName".
(14,15): Error RZ1036: Invalid tag helper directive look up text 'Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper, Microsoft.AspNetCore.Mvc.Razor'. The correct look up text format is: "name, assemblyName".
(15,15): Error RZ1036: Invalid tag helper directive look up text 'Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper, Microsoft.AspNetCore.Mvc.Razor'. The correct look up text format is: "name, assemblyName".
(16,15): Error RZ1036: Invalid tag helper directive look up text 'Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper, Microsoft.AspNetCore.Mvc.Razor'. The correct look up text format is: "name, assemblyName".
```
I made sure the casing was correct. The files are set as content. It is random. It doenst happen to all sites. When I redeploy the app, the error goes away.

My ViewImports is physically part of the project and saved in multiple folders with same content:

```
@inherits MyCompany.Configurations.DynamicLayoutWebViewPage<TModel>
@removeTagHelper "*, Microsoft.AspNetCore.Mvc.Razor"
@using Microsoft.AspNetCore.Html
@using Microsoft.AspNetCore.Mvc.Razor
@using System.Net
@using System.IO
@using System.Web
@using MyCompany.Core
@using MyCompany.Core.ViewModels
@using MyCompany.Core.ViewModels.Modules
@using MyCompany.Core.HtmlHelpers
@using MyCompany.Core.Utilities
@using MyCompany.Core.Extensions`
```

At startup, I define my FileProvider for runtime compilation:

`}).SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
            .AddSessionStateTempDataProvider()
            .AddRazorRuntimeCompilation(options =>
            {
                var fileProvider = options.FileProviders[0];
                options.FileProviders.Clear();
                options.FileProviders.Add(new DbVirtualPathProvider(fileProvider));
            });`

I have a custom IViewLocationExpander.
I have this set in projects file:

```
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>
```

Here is the code to render views to string:

```
public async Task<string> RenderRazorViewToString(ControllerContext controllerContext, ViewDataDictionary viewData, ITempDataDictionary tempData, string viewName, object model, bool isMainPage = false)
        {
            if (!string.IsNullOrWhiteSpace(viewName))
            {
                viewData.Model = model;
                var viewResult = _viewEngine.GetView("/", viewName, isMainPage);

                using (var sw = new StringWriter())
                {
                    var viewContext = new ViewContext(controllerContext, viewResult.View, viewData, tempData, sw, new HtmlHelperOptions());
                    await viewResult.View.RenderAsync(viewContext);

                    return sw.GetStringBuilder().ToString();
                }
            }

            return string.Empty;
        }
```

I have been chasing this issue for months.
Any help would be greatly appreciated.

**Comment by pranavkm** [comment] 2020-06-11 14:15
@ajaybhargavb \ @NTaylorMullen does this error message ring a bell:

> (14,15): Error RZ1036: Invalid tag helper directive look up text 'Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper, Microsoft.AspNetCore.Mvc.Razor'. The correct look up text format is: "name, assemblyName".

**Comment by joetherod** [comment] 2020-06-12 14:04
Another note is this seems to happen randomly when a viewcomponent is called within a viewcomponent call.

**Comment by joetherod** [comment] 2020-06-12 19:55
View compilation now has it's own memory allocation. Use to be able to see the allocations in MemoryCache. Is there anyway to manage the memory cache for view compilation, define what percentage it uses of memory allocated for app and actually see what is in it?
This was removed: IViewCompilationMemoryCacheProvider

**Comment by NTaylorMullen** [comment] 2020-06-13 18:40
> (14,15): Error RZ1036: Invalid tag helper directive look up text 'Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper, Microsoft.AspNetCore.Mvc.Razor'. The correct look up text format is: "name, assemblyName".

It's somehow thinking that the add/removeTagHelper syntax is wrong? @joetherod would you mind providing a simple repro app for us to investigate further?

**Comment by joetherod** [comment] 2020-06-13 22:46
Its random. I think it's related to memory pressure and a lot of requests coming in. It happens to only certain sites, and it looks like its related to high requests rates, many compilations, and limited memory resources. I added more memory and containers and the error happens less frequent. I think the error message isnt telling of what is the real issue.

**Comment by joetherod** [comment] 2020-06-17 13:08
Any ideas what can be done to resolve this?

**Comment by pranavkm** [comment] 2020-06-17 13:15
@joetherod we're unable to investigate this without a minimal application and consistent steps to reproduce the error. Plenty of apps compile views at runtime but this is the first we've seen where compilation fails at random. In particular because this involves application specific code, it seems more likely that this is an issue with how the app uses the framework.

**Comment by joetherod** [comment] 2020-06-17 13:22
I cant reproduce this error locally. I can try to create a minimal application, but it will take time.

**Comment by joetherod** [comment] 2020-06-19 15:32
This application is very big. Dont think I can create a minimal application that will fully recreate the issue. What I can tell you, is that this happens when there are many requests and many compilations happening for the same view that calls a view component. With over 500 different sites, this happens to one site that has a unique dynamic setup that causes many compilations of the same view. My ViewImports files is a physical file. The error that is happening doesnt make sense as the format of the removeTagHelper is correct. The odd thing is the line numbers after words in the stack trace. It's like if the compilation is picking up a default viewimports file and not the one in the physical location. It seems to happen on cache miss. Meaning memory is getting overwhelmed causing compilation of the view since there are many compilations happening.
I use to be able to see the compiled views in memory using  IViewCompilationMemoryCacheProvider. But, that has been removed and there is no way that I know of to see them in memory cache anymore. 

Any insight would help.

**Comment by mkArtakMSFT** [comment] 2020-06-22 22:19
Without a repro app we can't help you much. If you can produce an app with minimal changes required to reproduce this issue (even with 500 dummy pages) we will try to look into this.
Please note that we do not look for a project with external dependencies.
Having said that,  we're closing this issue. If you are able to come up with such a project, please file a new issue and reference this one - so we can take it from there.

**Closed by mkArtakMSFT** 2020-06-22 22:19 UTC
Labels: Needs: Attention :wave:, area-razor.tooling
