### ISSUE TITLE
Multiple AddHostedService Registration Issues

### ISSUE THREAD

**Issue by ahnjehoon** [dotnet/aspnetcore#33987] opened 2021-07-01 03:08 UTC
A problem occurred during the migration operation from .NET CORE 3.1 to 6.

While I was checking by configuring a new project, I noticed that there was an error in registering the Background Service.

- FirstBackgroundService
```csharp
// similer with second, third, forth class
public class FirstBackgroundService : BackgroundService
{
	private int counter = 0;

	protected async override Task ExecuteAsync(CancellationToken stoppingToken)
	{
		while (!stoppingToken.IsCancellationRequested)
		{
			await Task.Run(Run, stoppingToken);
			await Task.Delay(1000, stoppingToken);
		}
	}

	void Run()
	{
		counter++;
		Console.WriteLine($"FirstBackgroundService counter: {counter}");
	}
}
```

- Startup.class
```csharp
public void ConfigureServices(IServiceCollection services)
{

	services.AddControllers();
	services.AddSwaggerGen(c =>
	{
		c.SwaggerDoc("v1", new OpenApiInfo { Title = "SampleApp", Version = "v1" });
	});

	services.AddHostedService<FirstBackgroundService>();
	services.AddHostedService<SecondBackgroundService>();
	services.AddHostedService<ThirdBackgroundService>(); // FINE
	// services.AddHostedService<FourthBackgroundService>(); ERROR!
}
```

There was no problem registering the third Background Service with startup.cs, but there was a problem registering the fourth Background Service.
There was no problem when testing in .NET3.1, .NET5 by changing the framework.
Is there any change in registering Background Service as .NET 6 has been updated?

-------
EDIT: Add an error message.
ERROR MESSAGE: System.InvalidOperationException: 'Server has already started.'
![image](https://user-images.githubusercontent.com/11817356/124060810-c3b7f900-da68-11eb-9b1e-9969fbe9ce5e.png)

**Comment by Tratcher** [comment] 2021-07-01 06:36
Duplicate of https://github.com/dotnet/aspnetcore/issues/33763

**Closed** 2021-07-07 20:36 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-runtime

**Comment by springy76** [comment] 2021-07-19 10:12
I have exact same problem on net 5.0.7 - no preview technology involved, neither .net nor VS.
