### ISSUE TITLE
Cannot render component from RazorClassLibrary with RenderMode.InteractiveWebAssembly or Auto in Blazor 8

### ISSUE THREAD

**Issue by EldinHb** [dotnet/aspnetcore#52037] opened 2023-11-14 10:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With a Blazor web app, a webassembly standalone app and a shared razor class library I get an error in the browser console while trying to use a component with RenderMode.InteractiveWebAssembly or Auto. It does render on the server and the HTML gets sent to the browser, but it is not interactive and shows an error. RenderMode.InteractiveServer does not have this issue.

<img width="1679" alt="image" src="https://github.com/dotnet/aspnetcore/assets/8807015/6c603b1d-114d-4bce-8723-aa99b2f6bea0">

I found [this](https://github.com/dotnet/aspnetcore/issues/50609) issue of Dan Roth having the same issue but Javier couldnt reproduce it in rc2. I am having this issue with rc 2 

https://github.com/EldinHb/Blazor8AutoIssue repo

Edit: updating to the full .net 8 that just released doesn't change anything about the above. In fact, now I get a json error in the browser console if I use a component that's placed inside the client project. 

### Expected Behavior

To be able to use RenderMode.InteractiveWebAssembly

### Steps To Reproduce

- .net 8.0.100-rc.2.23502.2
- clone repo https://github.com/EldinHb/Blazor8AutoIssue
- cd to BlazorWebApp
- dotnet run
- navigate to BlazorPage from the left menu
- See error in console and counter button does not work

### Exceptions (if any)

blazor.web.js:1 Error: One or more errors occurred. (Root component type 'RazorClassLibrary.Counter' could not be found in the assembly 'RazorClassLibrary'.)
    at Jn (marshal-to-js.ts:349:18)
    at Ul (marshal-to-js.ts:306:28)
    at 00b1e352:0x1faca
    at 00b1e352:0x1bf8b
    at 00b1e352:0xf172
    at 00b1e352:0x1e7e4
    at 00b1e352:0x1efda
    at 00b1e352:0xcfec
    at 00b1e352:0x440ad
    at e.<computed> (cwraps.ts:338:24)

### .NET Version

8.0.100-rc.2.23502.2

**Comment by javiercn** [comment] 2023-11-16 12:52
@EldinHb thanks for contacting us.

As a first step, upgrade to RTM bits.

**Comment by sWozzAres** [comment] 2023-11-16 22:56
I had the same problem when moving components from the .Client app to a Razor class library. Renders in server mode, then fails with the above error.

I've moved the components back into the .Client app for the time being.

**Comment by mkalinski93** [comment] 2023-11-17 14:45
I have the exact same problem with the latest .NET version.

**Comment by EldinHb** [comment] 2023-11-17 14:48
@javiercn 

Im not sure what RTM bits is 😄

**Comment by Kumima** [comment] 2023-11-17 18:33
Same problem.

**Comment by Kumima** [comment] 2023-11-17 18:48
Try to clean the solution and rebuild. I'm not sure, but I remember I met this once, but after I make a clean rebuild, it seems disappear.

**Comment by javiercn** [comment] 2023-11-29 15:20
@EldinHb RTM stands for "Release to manufacturing". Essentially the final/shipped version.

That said, I think this is the same bug that got fixed by 8bf4d2de209577d15306635402a594de02fa4d53

**Comment by javiercn** [comment] 2023-11-29 15:20
So dupe of https://github.com/dotnet/aspnetcore/issues/52129

**Comment by javiercn** [comment] 2023-11-29 15:20
A fix for this should be available in the next release.

**Closed by javiercn** 2023-11-29 15:20 UTC
Labels: area-blazor

**Comment by zbarrier** [comment] 2024-01-08 09:58
This error still happens when using .NET Aspire.
