### ISSUE TITLE
New DateOnly and TimeOnly Not handled in Blazor components in .Net 6 preview 4

### ISSUE THREAD

**Issue by frankabbruzzese** [dotnet/aspnetcore#33192] opened 2021-06-01 18:41 UTC
Probably this is not a bug but just an implementation that has not been completed yet. Anyway, the issues are as follows:

1. In Razor Views model properties of type `DateOnly `and `TymeOnly `do not render automatically as input type date and time respectively but as input type text. They do render properly only if properties are decorated with `DataType `attributes that specify respectively  `Date `and `Time `types.
2.  In Razor Views and Pages, properties of type `DateOnly` and `TymeOnly` do not conform to the `ViewContext.Html5DateRenderingMode` setting but always render according to the current Culture.
3. In Blazor components `<input @bind-value = "MyTime"`> and <input @bind-value = "MyDate"> complaint `MyTyme `and `MyDate` must be `DateTime `if they are respectively `TimeOnly` and `DateOnly `types.

Reproducing the error is trivial and can be done immediately in the Asp.net Core and Blazor default project templates.

- ASP.NET Core version: 6 preview 4
- Include the output of `dotnet --info`: Microsoft.NETCore.App 6.0.0-preview.4.21253.7
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS

**Comment by javiercn** [comment] 2021-06-02 09:44
@frankabbruzzese thanks for filing this issue.

Yes, we need to add support for these new types across the board.

**Comment by kinosang** [comment] 2021-06-17 11:00
Also, `DateOnly` and `TimeOnly` are not handled properly in Asp.Net Controllers (such as data binding)

**Comment by mkArtakMSFT** [comment] 2021-07-27 17:44
Closing this as a dupe of the above linked issue.

**Closed by mkArtakMSFT** 2021-07-27 17:44 UTC
Labels: area-blazor, area-mvc, enhancement
