### ISSUE TITLE
Create a provider to pass parameters in blazor components

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#48282] opened 2023-05-17 15:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

For example, I have a button component:
```razor
@inherits Base

<button type="@Type.ToString().ToLower()">@ChildContent</button>
```
```cs
public partial class Button : Base
{
    [Parameter]
    public RenderFragment ChildContent { get; set; } = null!;

    [Parameter]
    public Types Type { get; set; } = Types.Button;

    public enum Types
    {
        Button,
        Submit
    }
}
```
Needs to perform an onclick, unfortunately I don't have this handled:
```razor
 <Button Type=Button.Types.Submit Class="w-full" @onclick=GetCode>Resend the code</Button>
```
For this to work I need to add an ``EventCallback`` support.

In this scenario it is not a problem, the problem starts e.g. in input when we have many binds etc. We have to handle everything separately.

### Describe the solution you'd like

A great way to solve this problem would be to inherit additional bind attributes. We can't do something similar as it is already here for example:
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/splat-attributes-and-arbitrary-parameters?view=aspnetcore-7.0

Just that for the parameters of razor?

Example:
```razor
@attribute [AllowInheritance]

<button @Inheritance>@ChildContent</button>
```

This allows us to have our own intermediary and not handle multiple events. In the case of input, this is very necessary.

**Comment by javiercn** [comment] 2023-05-17 15:48
@Alerinos thanks for contacting us.

It's not clear from your description what you are trying to achieve. Could you clarify what you are trying to do?

**Comment by Alerinos** [comment] 2023-05-17 16:02
@javiercn 
I am already explaining what this is all about.

When creating a service, we need our own components. Suppose I want to make my own rich input component. It contains everything it needs, label, warning etc. Then I want to give it a bind, I will have to create my own parameter that will mediate the data exchange. What I mean is to allow all additional bind parameters to be passed to the component so that I don't have to create them again.

Example MyInput.razor:
```razor
<input @onkeydown="@OnKeyDown"/>
@code{
    [Parameter]
    public EventCallback<KeyboardEventArgs> OnKeyDown { get; set; }
}
```
Use:
``<MyInput OnKeyDown=Test/>``

When creating our own component we need to handle ``onkeydown``, instead of doing this again we can use the attribute. If it is and razor detects that we don't handle it in our component it will try to pass it on. As with @attributes which passes html tags.

Example:
Example MyInput.razor:
```razor
<input @OtherAttributes />

```
Use:
``<MyInput @onkeydown=Test/>``

**Comment by mkArtakMSFT** [comment] 2023-05-17 16:24
Thanks for contacting us. Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/20560

**Closed by mkArtakMSFT** 2023-05-17 16:24 UTC
Labels: area-blazor
