### ISSUE TITLE
[browser][MT] Blazor E2E test with MT runtime

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/aspnetcore#48925] opened 2023-06-20 22:30 UTC
Build the test app with experimental MT workload

To unit test that
- the app could start (with cop headers)

Later scenarios are (we are not ready yet)
- the HTTP client is still working https://github.com/dotnet/runtime/pull/87567
- The JS interop could be dispatched to main thread via `InvokeAsync`  https://github.com/dotnet/aspnetcore/pull/48991

cc @javiercn

**Comment by mkArtakMSFT** [comment] 2024-01-30 17:41
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/53435 as we're including it into .NET 9 plans.

**Closed by mkArtakMSFT** 2024-01-30 17:41 UTC
Labels: area-blazor, Priority:1, arch-wasm, Pillar: Dev Experience
