### ISSUE TITLE
WPF - Blazor hybrid - staticwebassets.runtime.json content root path problem 

### ISSUE THREAD

**Issue by gdar91** [dotnet/aspnetcore#52771] opened 2023-12-11 19:50 UTC
### Description

When publishing a WPF Blazor Hybrid app (that uses BlazorWebView) to a ClickOnce server, a `staticwebassets.runtime.json` file is added to the output. The problem is it contains content root paths from a developer machine, which then causes the application to crash, complaining about the path.

### Configuration

.NET 7.0.14, on Windows 10 x64.

### Regression?

It seems that it is a regression, because in previous versions of .NET 7 and Visual Studio, it didn't use to output the `staticwebassets.runtime.json` file at all.

If I make the app delete this file during launch, then it solves the problem, but I still consider it a workaround.

**Comment by javiercn** [comment] 2023-12-12 18:33
@gdar91 thanks for contacting us.

Can you provide details on the Visual Studio version you are using as well as the exact SDK versions?

Both, the ones where it worked and the ones where it stopped working.

If you pin the SDK to an older version where it worked using a global.json, does it work with the current Visual Studio version you are using?

**Comment by gdar91** [comment] 2023-12-12 21:02
> @gdar91 thanks for contacting us.
> 
> Can you provide details on the Visual Studio version you are using as well as the exact SDK versions?
> 
> Both, the ones where it worked and the ones where it stopped working.
> 
> If you pin the SDK to an older version where it worked using a global.json, does it work with the current Visual Studio version you are using?

I'm currently using .NET 8.0.100 and Visual Studio 17.8.3, and it doesn't work on them.
I have also tried to downgrade the .NET version to 7.0.103 (using a global.json), as it was the version that used to work fine, but it didn't help. I wanted to downgrade Visual Studio to 17.7, as it was the version where it used to work, but it didn't let me go that far back, so I downgraded it to 17.8, which also didn't help.

**Comment by javiercn** [comment] 2023-12-13 06:24
@gdar91 thanks for the additional details.

**Comment by javiercn** [comment] 2023-12-15 13:15
@mkArtak parking this in 8.0.x so that we can keep track of it, but I do not think this is something we've regressed, since from what the issue indicates, something else have cause this issue as apparently this was working before. There was a similar issue reported in AzDo recently I believe.

**Comment by Mr-MooMoo** [comment] 2023-12-19 07:23
I can confirm - I face the same error with net8  / VS 17.8.3. and publish via ClickOnce. Solution was working before moving to net8 & VS 17.8.3

**Comment by SoulsideJourney** [comment] 2024-01-30 11:25
It's working on VS 17.7.6 and broken since 17.8.0
.NET 7.0
#53027

**Comment by mkArtakMSFT** [comment] 2024-02-10 06:05
@merriemcgaw you seem to be listed as the owner of ClickOnce. Is that the case? It looks like there is some regression in ClickOnce that is impacting WPF + Blazor users.

**Comment by veler** [comment] 2024-02-11 00:04
Hello,
I just faced this exact same issue using .NET 8 with VS Code on Ubuntu, by doing a `dotnet publish` command. Unless I'm missing something, it might not be related to ClickOnce then.

**Comment by merriemcgaw** [comment] 2024-02-15 00:04
@mkArtakMSFT that would be more of an issue with the VS ClickOnce publish experience (based on the problem being with the output of a file). The best way to report these issues is through the VS Feedback mechanisms, rather than GitHub. The team that works on the publish actions will reach back out and see if they can help resolve the issue.

**Comment by mkArtakMSFT** [comment] 2024-02-22 00:27
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Closed by mkArtakMSFT** 2024-02-22 00:27 UTC
Labels: External, area-blazor, Needs: Attention :wave:

**Comment by SoulsideJourney** [comment] 2024-02-25 19:20
@mkArtakMSFT so can you reopen my ticket (closed by you I guess) https://developercommunity.visualstudio.com/t/ClickOnce-generates-unnessesary-and-brea/10520709
