### ISSUE TITLE
.net8 preview 4: Hosting environment not detected via Blazor-Environment header

### ISSUE THREAD

**Issue by tn-5** [dotnet/aspnetcore#48271] opened 2023-05-17 06:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have an existing webassembly app that works 100% on preview 3. We select different runtime configurations by setting the `Blazor-Environment` header on the webserver to select the correct `appsettings.{environment}.json` file.

After upgrading to preview 4 the environment is not detected and reverts to the default `Production`

We have verified that the server still returns the correct header as previously. 

Downgrading same to preview 3 still works in same environment.

### .NET Version

8.0.100-preview.4.23260.5

**Comment by JeepNL** [comment] 2023-05-17 11:13
This is also happening with a static Blazor WASM deployment. When running locally the `wwwroot/appsettings.Development.json` is being ignored instead `wwwroot/appsettings.json` is being used. In preview 3 this still worked.

**Comment by JeepNL** [comment] 2023-05-17 22:18
I'm  sorry, I mixed up `wwwroot/appsettings.Development.json` and `wwwroot/appsettings.json` in my previous comment, I've corrected it now.

**Comment by Smalls1652** [comment] 2023-05-18 01:17
I'm seeing the same thing @JeepNL is seeing as well. The strange thing about it though is that it's not happening all of the time. It's very hard to pinpoint down where it's failing, but this is where I'm seeing it start to throw the error: 

https://github.com/dotnet/aspnetcore/blob/c5a9c5973bf735f1bb9d611cd50c796f6c32557e/src/Components/Web.JS/src/Platform/WebAssemblyConfigLoader.ts#L40

**Comment by JeepNL** [comment] 2023-05-18 11:33
#### I've more information + a GitHub Repo & a Live Preview

👇 I've created a Static Blazor WASM GitHub Test Repo
https://github.com/JeepNL/Static-Blazor-Wasm-dotNET8-Preview4

If you deploy this (_Blazor WASM default template created with .NET 8 Preview 4_) to Cloudflare Pages (_or GitHub Pages, I think it will show the errors there too, because it's a static site_) you'll see the following errors:

1) The error `blazor.webassembly.js:1  Error: Assert failed: Blazor._internal.getConfig must be a Function but was undefined` doesn't show if you clear the local storage (_clear site data_) and disable the cache and do a reload. Reloading the page after that again results in the error.

   **Live preview:** you can test this here (Cloudflare Pages) 👉 https://preview4.tusk.pages.dev/

2) The error `blazor.webassembly.js:1  Uncaught (in promise) Corrupted reserved bit` shows when you enable Brotli compression, Always, that's why I've commented out this code. see [index.html](https://github.com/JeepNL/Static-Blazor-Wasm-dotNET8-Preview4/blob/d4fe1e0fc5f8499e7eda11e80dbcb9d804b00bca/StaticBlazorWasm8preview4/wwwroot/index.html#L29)

The good news: `webcil` works! (_If the page loads ..._), but IMHO these were easy to catch errors. With preview 3 I couldn't build the static Blazor WASM app on Windows 11  (_it worked on WSL Ubuntu_), that was an easy to catch error too. We're all human, we all make mistakes, but I think you should update your test environment.

**Comment by JeepNL** [comment] 2023-05-18 11:35
I don't know if I need to create a separate issue with the `Brotli error`, please advise .

**Comment by surayya-MS** [comment] 2023-05-19 14:09
Thanks for contacting us, @tn-5!

I've investigated the issue and found that this is a bug introduced in preview 4. This is no longer an issue in preview 5.

**Comment by surayya-MS** [comment] 2023-05-19 14:11
> I don't know if I need to create a separate issue with the `Brotli error`, please advise .

@JeepNL, thank you for the repro!


@MackinnonBuck , could you please confirm if this the Brotli error is related to your changes?

**Comment by JeepNL** [comment] 2023-05-19 14:21
@surayya-MS Extra FYI: What I've noticed with the error `blazor.webassembly.js:1  Error: Assert failed: Blazor._internal.getConfig must be a Function but was undefined` is that on **slower** PCs / Mobiles the Blazor WASM page most of the times **works**. But on my (**fast**) development desktop PC it always gives the **error** if you've loaded the pages once and try do do a **reload**.

This is just extra 'for your information', maybe you've (or the team) noticed this too already.

**Comment by JeepNL** [comment] 2023-05-19 14:25
FYI: oh, and you can test this 'slow/fast' device behavior with the .NET 8 Preview 4 live static Blazor WASM preview I put online: https://preview4.tusk.pages.dev/

**Comment by JeepNL** [comment] 2023-05-19 14:33
I'm sorry, but to be clear: my last two comments have nothing to do with the Brotli error. That's a separate issue.

**Comment by MackinnonBuck** [comment] 2023-05-19 22:54
@JeepNL, using the latest .NET 8 nightly build, I wasn't able to reproduce the Brotli issue. If you can still reproduce the Brotli problem using the nightly builds (see https://github.com/dotnet/installer#table), would you please file an issue with detailed repro steps and a repro project, hosted as a public GitHub repository? Thanks!

**Comment by JeepNL** [comment] 2023-05-21 18:29
@MackinnonBuck I've spent the whole weekend (and last Friday) investigating this, and today, Sunday 8 PM, I finally got it working. The error is very easy to reproduce. I've made a public GitHub Repo for you to try:  https://github.com/JeepNL/StaticBlazorWasm

### To Reproduce:
(_my repo has everything that is needed_)

1. You need to have a `appsettings.json` file in the `wwwroot` directory of the Static Standalone Blazor WASM app
2. You need to access a value from `appsettings.json` in a `.razor` page. See: [index.razor](https://github.com/JeepNL/StaticBlazorWasm/blob/7faef69deeb7f1b26829ec160f2b58c7e871eed3/StaticBlazorWasm/Pages/Index.razor#L1)
3. You have to enable Brotli compression in `index.html`
4. You have to publish (release) the project to GitHub Pages. Only then the error show ups. Always. 

[appsettings.json](https://github.com/JeepNL/StaticBlazorWasm/blob/7faef69deeb7f1b26829ec160f2b58c7e871eed3/StaticBlazorWasm/wwwroot/appsettings.json#L1)
[index.html](https://github.com/JeepNL/StaticBlazorWasm/blob/7faef69deeb7f1b26829ec160f2b58c7e871eed3/StaticBlazorWasm/wwwroot/index.html#L1) (with Brotli compression enabled for static sites)

### The Error

.NET 8 Preview 5 (daily build) expects a `appsettings.json.br`, but it isn't there. Only files in `_framework` are Brotli compressed. The `appsettings.json` is not.

### Without manually adding a Brotli compressed `appsettings.json.br` the site won't run.

I've also a live **.NET 8 preview 5** (static) Stand Alone Blazor WASM GitHub Pages working demo site running here: https://jeepnl.github.io/StaticBlazorWasmPrebuilt/

If you use developer tools, you'll see the site needs a `appsettings.json.br`

This demo site doesn't use GitHub Workflow Actions, I've built the site locally on my Windows 11 Desktop PC, and deployed, using GitHub Desktop, the contents of the `wwwroot` folder to GitHub, and enabled GitHub Pages. 

I've used .NET 8 Preview 5 daily build because you said you weren't able to reproduce it with that version. With .NET 8 Preview 4 I'm also not able to get a static Stand Alone Blazor WASM site up and running.

**Comment by MackinnonBuck** [comment] 2023-05-24 17:33
@JeepNL Sorry for the delayed reply. Thank you very much for the detailed repro steps. I was able to reproduce the issue. We made a lot of changes in this area, and it looks like `appsettings.json` and `appsettings.Development.json` are no longer compressed by default.

I was able to make things work by adding the following to the `.csproj` file. Could you please try the same, and confirm if it resolves the issue on your end?

```csproj
<PropertyGroup>
  <CompressionIncludePatterns>$(CompressionIncludePatterns);appsettings*.json</CompressionIncludePatterns>
</PropertyGroup>
```

@javiercn Do you think we should change things so `appsettings.json` files are explicitly compressed by default? This would be consistent with how compression worked in the past.

**Comment by JeepNL** [comment] 2023-05-24 18:29
@MackinnonBuck  No problem for the delayed reply, MS Build is happening too, so you all are probably very busy!

And yes, your solution works! Perfectly!

When I 'dotnet publish -c Release' the project, the compressed appsettings*.json files (.br and .gz) are automatically generated.

**Comment by Smalls1652** [comment] 2023-05-24 18:42
That makes sense why it kept failing at reading config settings from `appsettings.json` when it's initializing.

I'll add the `CompressionIncludePattern` property to my website's project file and see if that fixes it under Preview 4.

**Comment by MackinnonBuck** [comment] 2023-05-25 18:34
Glad to hear that the fix worked for you!

I'm going to close this issue out, since the original bug reported in this issue has been fixed.

**Closed by MackinnonBuck** 2023-05-25 18:34 UTC
Labels: bug, area-blazor, blazor-wasm
