### ISSUE TITLE
Remove/replace virtual method in UserManager.cs constructor

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#45358] opened 2022-11-30 00:41 UTC
## Background and Motivation

Developer found that mocking ```UserManager``` using their mocking framework was problematic because a virtual method (```RegisterTokenProvider(...)```) is called in the constructor. This results in token providers not being registered due to how mocking proxies work. Generally speaking its a bad idea to call virtual methods in constructors ([CA2214](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2214)).

## Proposed API

Proposal is to introduce a non-virtual ```RegisterTokenProviderCore(...) method which is called from the constructor and from the existing ```RegisterTokenProvider(...)``` method. This is done so as to not break the API.

```diff
namespace Microsoft.AspNetCore.Identity;

public class UserManager<TUser> : IDisposable where TUser : class
{
+    protected void RegisterTokenProviderCore(string providerName, IUserTwoFactorTokenProvider<TUser> provider)
}
```

## Usage Examples

Usage within the constructor changes:

```diff
        _services = services;
        if (services != null)
        {
            foreach (var providerName in Options.Tokens.ProviderMap.Keys)
            {
                var description = Options.Tokens.ProviderMap[providerName];

                var provider = (description.ProviderInstance ?? services.GetRequiredService(description.ProviderType))
                    as IUserTwoFactorTokenProvider<TUser>;
                if (provider != null)
                {
-                    RegisterTokenProvide(providerName, provider);
+                    RegisterTokenProviderCore(providerName, provider);
                }
            }
        }
```

## Alternative Designs

Considered deferring registration of token providers until first use but this introduces the possibility of failures after startup.

## Risks

Should be low risk.

**Below is the issue detail as raised by developer reporting this issue.**

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Mocking UserManager and found that the virtual method in the constructor was causing the mock to be in an unexpected state where the TokenProviders are not being registered due to how mocking proxies work.

### Describe the solution you'd like

Removal/replacement of the virtual method in UserManager's constructor:

https://github.com/dotnet/aspnetcore/blob/bc4fd75e5ff4d51fbc5f7cf1452164a03573adab/src/Identity/Extensions.Core/src/UserManager.cs#L115

**Comment by mitchdenny** [comment] 2022-12-02 04:37
Did up a PR for the ```RegisterTokenProviderCore``` approach which I think is probably safer.

**Comment by vflame** [comment] 2022-12-03 05:02
> Triage: @vflame Can you share the mocking setup that you are using?
> 
> Triage notes: we can consider providing an interface here for users who want to use mocking.
> 
> @mitchdenny will take a look.

Mocking setup below:

```c#       
        var mockUserManager = new Mock<UserManager<TUser>>(
                _scope.ServiceProvider.GetRequiredService<IUserStore<ApplicationUser>>(),
                _scope.ServiceProvider.GetRequiredService<IOptions<IdentityOptions>>(),
                _scope.ServiceProvider.GetRequiredService<IPasswordHasher<ApplicationUser>>(),
                _scope.ServiceProvider.GetRequiredService<IEnumerable<IUserValidator<ApplicationUser>>>(),
                _scope.ServiceProvider.GetRequiredService<IEnumerable<IPasswordValidator<ApplicationUser>>>(),
                _scope.ServiceProvider.GetRequiredService<ILookupNormalizer>(),
                _scope.ServiceProvider.GetRequiredService<IdentityErrorDescriber>(),
                _scope.ServiceProvider.GetRequiredService<IServiceProvider>(),
                _scope.ServiceProvider.GetRequiredService<ILogger<UserManager<ApplicationUser>>>()
            );
```

Was surprised by the tokens not being registered despite providing all concrete implementations to UserManager. Was able to work around this by setting `mockUserManager.CallBase` to `true` (Moq) before any usage of the mock. Thanks for making the change.

**Comment by mitchdenny** [comment] 2023-01-04 06:32
@vflame I'm actually having trouble reproducing the problem you are seeing. In the setup of your service provider are you registering any token providers?

**Comment by mitchdenny** [comment] 2023-01-04 06:37
... in your mocking set up is TUser a type parameter or the actual concrete class?

**Comment by vflame** [comment] 2023-01-04 16:59
> @vflame I'm actually having trouble reproducing the problem you are seeing. In the setup of your service provider are you registering any token providers? We are also using **Moq** in the ASP.NET Core code base and I was able to observe `RegisterTokenProvider` being called and the token providers being populated from the providermap.
> 
> Basically, are you calling `AddDefaultTokenProviders(this IdentityBuilder builder)` or equivalent so that `IOptions<IdentityOptions>` has the provider map correctly populated?


Yes, we are using the following:
```c#
sc.AddDefaultIdentity<ApplicationUser>(options =>
        {
            options.SignIn.RequireConfirmedAccount = true;
            options.Password.RequiredLength = 4;
            options.Password.RequireDigit = false;
            options.Password.RequireLowercase = false;
            options.Password.RequiredUniqueChars = 0;
            options.Password.RequireUppercase = false;
            options.Password.RequireNonAlphanumeric = false;

        }).AddRoles<IdentityRole>().AddEntityFrameworkStores<ApplicationDbContext>();
```

With `mockUserManager.CallBase = true;`:

![image](https://user-images.githubusercontent.com/12207061/210608472-b4f621ff-e507-4db3-82ef-f7f7344ebea5.png)
 
 
 

Without `mockUserManager.CallBase` set:

![image](https://user-images.githubusercontent.com/12207061/210608535-6d20342b-52bc-44c5-bd34-a75f4d02c640.png)

**Comment by mitchdenny** [comment] 2023-01-04 22:28
You are mocking the `UserManager<TUser>` but you actually want to use the real implementation. Why not just instantiate the real `UserManager<TUser>` given that you are providing all its dependencies?

**Comment by vflame** [comment] 2023-01-04 23:07
We want to be able to override certain UserManager<TUser> method's returns since we have a service that takes UserManager<TUser> as a dependency. E.g.,:

```
 _mockUserManager.Setup(p => p.FindByIdAsync(It.IsAny<string>())).Returns(Task.FromResult(user));
 _mockUserManager.Setup(p => p.RedeemTwoFactorRecoveryCodeAsync(It.IsAny<ApplicationUser>(), It.IsAny<string>())).Returns(Task.FromResult(IdentityResult.Success));
```

**Comment by mitchdenny** [comment] 2023-01-05 00:24
That mocking setup should work though because the mock is just going to return the result you tell it to, you don't need the internal token provider list to be populated. Do you think you can put together a minimal working example of your test in a project and post it on GitHub to help us understand the issue better?

**Comment by vflame** [comment] 2023-01-05 04:05
Reflecting on your comments, I think in our case, setting the mock with `CallBase = true;` is actually what we want--the ability to largely run the UserManager code, except for a few places so that we can change return. 

Maybe in a roundabout way, we were trying to test a few pathways in the UserManager<TUser> code that we were depending on a specific result and wanted to mock as "late" as possible in the call stack. We could alternatively have just mocked the return on of the first UserManager method called, as you indicated. 

E.g., instead of mocking ` public virtual async Task<IdentityResult> ChangePhoneNumberAsync(TUser user, string phoneNumber, string token)` we mocked `public virtual Task<bool> VerifyChangePhoneNumberTokenAsync(TUser user, string token, string phoneNumber)` which `ChangePhoneNumberAsync(TUser user, string phoneNumber, string token)` calls.

Thanks for the clarifying feedback, though I think that if all concrete implementations are provided to the constructor of a mock, then the mocked object should be created in an expected/valid state.

**Comment by mitchdenny** [comment] 2023-01-05 04:28
Yep. Sounds like CallBase is the right solution here. Was an interesting interlude into the mockability or lack thereof of `UserManager<TUser>` and did cause us to have a bit of a discussion on how we might do things differently in the future. I'll go ahead and close this issue for now.

**Closed by mitchdenny** 2023-01-05 04:28 UTC
Labels: api-suggestion, area-web-frameworks
