### ISSUE TITLE
With .NET 7.0 SDK, I cannot create .NET 6.0 web project, the target net6.0 can't be found.

### ISSUE THREAD

**Issue by Andy-Win** [dotnet/aspnetcore#39731] opened 2022-01-24 03:49 UTC
Repro steps:
1. Install latest main build VS from [main-32123.28](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5660393&view=ms.vss-build-web.run-extensions-tab) (Run preinstall command first)
2. Download .NET 7 SDK(7.0.100-alpha.1.22071.3) from main branch of https://github.com/dotnet/installer
3. Open VS, apply feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json
4. Open Command Prompt and run"dotnet new mvc -f net6.0 -o Mvc60" to create ASP.NET Core 6.0 MVC project.

Expected Result
The project should be created successfully.

Actual Result:
![image](https://user-images.githubusercontent.com/35762055/150718835-b06badcf-d6e8-42ef-8b2e-7b31c7f128d6.png)
![image](https://user-images.githubusercontent.com/35762055/150719180-86ef00a3-a732-4e0e-8122-d93fb17d1e98.png)

dotnet --info
![image](https://user-images.githubusercontent.com/35762055/150719033-d6d0c9c6-1911-4806-804f-f2a050612668.png)

**Comment by marcpopMSFT** [comment] 2022-01-24 18:11
From Nicole, this is only a web template issue so routing to aspnet
_For Andy’s [New]#13105, it only occurs on web projects, and creating a .NET 6.0 console/classlib/wpf/winforms project can succeed_

**Comment by mkArtakMSFT** [comment] 2022-01-24 18:50
Also tagging @joeloff in case you have thoughts too

**Comment by dougbu** [comment] 2022-01-24 19:07
@wtgodbe wasn't there an issue in earlier 7.0 SDKs relating to `net6.0` templates❔

**Comment by wtgodbe** [comment] 2022-01-24 19:18
There was an issue a couple weeks ago with `net7.0` templates in 7.0 SDKs, before the templates were added, but I don't remember 7.0 SDKs having problems with `net6.0`, that surprises me. I can try to repro after lunch

**Comment by mkArtakMSFT** [comment] 2022-01-24 22:57
@wtgodbe do you have any updates here?

**Comment by wtgodbe** [comment] 2022-01-24 23:13
I've confirmed that it repros on the SDK mentioned, but not on an older SDK from October, so something changed recently to introduce this. I'm still investigating

**Comment by wtgodbe** [comment] 2022-01-24 23:37
I believe this is related to https://github.com/dotnet/installer/pull/12946, the error doesn't repro on SDKs before we added the `net7.0` templates. @dsplaisted do you know where in dotnet/sdk the error described is getting triggered?

**Comment by wtgodbe** [comment] 2022-01-24 23:40
Also adding @vlada-shubina for the above question

**Comment by dsplaisted** [comment] 2022-01-25 14:13
I think this would be the expected behavior if you just installed the .NET 7 SDK standalone.  For the `mvc` template (and most or all of the ASP.NET ones), you only get the templates for the version of the SDK you have installed.  So if you wanted the .NET 6 templates you would also have to install the .NET 6 SDK.

With Visual Studio it works a bit different, so it's possible there's a bug in the setup authoring.  But I think the way it's supposed to work in Visual Studio is that you wouldn't get the templates for .NET 6 unless you installed the .NET 6 runtime (as you wouldn't by default be able to run a project targeting 6.0 without the 6.0 runtime).

What versions of the .NET SDK and runtimes are installed?  Can you paste the output of `dotnet --info` from a repro machine?

Also adding @joeloff as he is more familiar with the VS setup authoring.

**Comment by MichalPavlik** [comment] 2022-01-25 15:28
I was debugging the templating engine and there is the `ApplyFilters` method, where the engine is trying to find a match for parameters. I see it loads templates for all installed versions, but for some reason, in case of the mvc (and maybe other web templates) I can't see loaded templates for version 6. Need more time to investigate.

**Comment by joeloff** [comment] 2022-01-25 17:11
For VS we insert multiple installers for the templates, e.g. for the 6.0 SDK there would be the 6.0 copies of the 5.0, 3.1 templates. These typically only ship with VS.

**Comment by joeloff** [comment] 2022-01-25 17:45
@dsplaisted are these values correct? https://github.com/dotnet/installer/blob/1a828392f79d5d7a391b2a387e962e204fb245cd/eng/Versions.props#L109

**Comment by dsplaisted** [comment] 2022-01-25 18:14
@joeloff No, they should ideally be updated to 6.0.100 or whatever the latest version available for the 6.0 band is.  For example: https://github.com/dotnet/installer/blob/release/6.0.1xx/eng/Versions.props#L34

**Comment by joeloff** [comment] 2022-01-25 18:23
Right, but the ASP.NET ones are tracking runtime versions so those should be 6.0.1 or 6.0.2 I think

**Comment by wtgodbe** [comment] 2022-01-25 18:27
It sounds like we should update https://github.com/dotnet/installer/blob/1a828392f79d5d7a391b2a387e962e204fb245cd/eng/Versions.props#L109-L111, but if that was the issue, wouldn't 5.0 Asp.Net templates be broken too because of line 110?

**Comment by joeloff** [comment] 2022-01-25 18:30
> It sounds like we should update https://github.com/dotnet/installer/blob/1a828392f79d5d7a391b2a387e962e204fb245cd/eng/Versions.props#L109-L111, but if that was the issue, wouldn't 5.0 Asp.Net templates be broken too because of line 110?

I'm not sure

**Comment by wtgodbe** [comment] 2022-01-25 18:34
Opened https://github.com/dotnet/installer/pull/13113 to see if it helps

**Comment by wtgodbe** [comment] 2022-01-25 23:29
https://github.com/dotnet/installer/pull/13113 didn't do the trick - @MichalPavlik were you able to get anywhere in your investigation?

**Comment by MichalPavlik** [comment] 2022-01-26 08:41
The package for net6 is loaded and scanned for templates, so it seems they are filtered out later in the process. I'm narrowing down the issue slowly and I hope I will get the answer today.

**Comment by MichalPavlik** [comment] 2022-01-26 09:51
I believe I found the root cause. There is a deduplication step which basically adds discovered templates to dictionary with template's identity as a key. Templates for net7.0 have still same identity name, so they replaces net6.0 templates.

https://github.com/dotnet/aspnetcore/blob/fca7c73155408620ca9ee41e90313994b0a62ca1/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/.template.config/template.json#L13

Changing identity to reflect new version should help. I can create PR for you, but I'm not sure this is only thing you want to modify. I see there is also `thirdPartyNotices` field with probably old link.

**Comment by wtgodbe** [comment] 2022-01-26 17:08
Thanks! Looks like we should have updated that at the same time we updated branding - I'll push a PR for it & update our documentation.

**Comment by mkArtakMSFT** [comment] 2022-01-31 23:09
@wtgodbe as I understand this is pending [this PR](https://github.com/dotnet/installer/pull/13125) to merge?

**Comment by wtgodbe** [comment] 2022-01-31 23:47
> @wtgodbe is this blocked on dotnet/installer#13125?

Yes, and that's blocked on https://github.com/dotnet/sdk/pull/23597, which should get in once CI passes

**Comment by dsplaisted** [comment] 2022-02-01 14:02
The PRs have all merged, so hopefully this is now fixed.

**Comment by wtgodbe** [comment] 2022-02-01 17:41
Confirmed that this is now fixed
<img width="614" alt="Screenshot 2022-02-01 094040" src="https://user-images.githubusercontent.com/14283640/152021317-73e438b1-36fd-4b5a-87f6-9f65f60cf199.png">
:

**Closed by wtgodbe** 2022-02-01 17:41 UTC
Labels: bug, External, area-mvc, feature-templates
