### ISSUE TITLE
GoToImplementation takes you to the correct line, but not the identifier

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#18862] opened 2020-02-06 18:47 UTC
```
@functions{
    interface Foo{}

    class Bar: Foo{}
}
```
So if you did Ctrl+F12 on the interface Foo, it takes you to the line for class Bar, but puts you at the start of the line instead of over the Bar identifier like with GoToDefinition.

**Comment by NTaylorMullen** [comment] 2020-02-08 17:30
Is this our problem or Roslyn's?

**Comment by TanayParikh** [comment] 2020-03-24 20:58
### Update:

Code snippet used for testing:
```
    public static void Main()
    {
        Apple();
    }

    public static void Apple()
    {
        var foo = "bar";
    }

    interface Foo{}

    class Bar: Foo{}
```

**For `@functions`:**
Both `Apple()` and `Foo` go the the start of the subsequent implementation lines, instead of right before `Apple()` & `Bar` on the lines, respectively.

**For `Program.cs`:**
Correct behavior is observed.

Additionally, for Go to Declaration, both `@functions` and `Program.cs` exhibit the correct behavior. 

 Focussing on the `@functions` case, the `document` (URI) and `position` (line / char of virtual .cs file) are the same for both go to declaration and find implementation. These params are used to create a request and sent to the OmniSharp C# LSP. The server proceeds to respond with the correct line number for the declaration / implementation. However, the returned column number of find implementation is always `1` while the returned column number for declaration is correct (starting point of declaration).

Also note, the server returns the line/column number relative to the .cshtml document and *not* the inputted virtual .cs file which was indicated in the original server request. Consequently, the server is doing some sort of projection from virtual .cs to .cshtml.

This would make me suspect the error is somewhere in the projection completed in the `omnisharp-roslyn` server/repo. However, `omnisharp-roslyn` seems to just leverage the existing CodeAnalysis libraries. 

https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindImplementationsService.cs#L43

https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionService.cs#L45

There also isn't any explicit projection handling. Which makes it unlikely that the problem is here. 

Investigating...

**Comment by TanayParikh** [comment] 2020-03-24 23:27
After discussing with @ajaybhargavb, it seems we have a [dotnet/roslyn](https://github.com/dotnet/roslyn) bug on our hands.

I've filed an issue with a repro-repo as well as demo videos:
https://github.com/dotnet/roslyn/issues/42743

https://github.com/TanayParikh/line-pragma-implementation-repro

Expected Behavior:
Demo without Line Pragma: https://github.com/TanayParikh/line-pragma-implementation-repro/raw/master/Demo_Without_Line_Pragma.mov

Actual Behavior:
Demo with Line Pragma: https://github.com/TanayParikh/line-pragma-implementation-repro/raw/master/Demo_With_Line_Pragma.mov

**Comment by TanayParikh** [comment] 2020-03-24 23:33
Updated cost due to account for time required to investigate the issue thoroughly (razor tooling -> omnisharp-vscode -> omnisharp server -> roslyn) (per discussion). Closing.

**Closed by TanayParikh** 2020-03-24 23:33 UTC
Labels: External, area-mvc, bug, cost: S, feature-razor.tooling
