### ISSUE TITLE
Flaky test: Microsoft.AspNetCore.Components.RevalidatingServerAuthenticationStateProviderTest.IfValidateAuthenticationStateAsyncReturnsUnrelatedCancelledTask_TreatAsFailure

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#20826] opened 2020-04-14 21:42 UTC
This test has been failing recently and needs to be stabilized.

**Comment by captainsafia** [comment] 2020-04-14 21:44
Closing this a dupe of https://github.com/dotnet/aspnetcore/issues/19940.

**Closed by captainsafia** 2020-04-14 21:44 UTC
Labels: area-blazor, task
