### ISSUE TITLE
NullReferenceException when unit testing ProblemDetails

### ISSUE THREAD

**Issue by niesmo** [dotnet/aspnetcore#23882] opened 2020-07-12 18:22 UTC
### High Level Problem
have a web api using ASP.NET Core 3.1
I have a controller that when an exception is thrown, it returns a [Problem](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ControllerBase.cs#L1882) which is working very well 😄.
```c#
[HttpGet]
public ActionResult<IEnumerable<WeatherForecast>> GetWeatherForecast(int numberOfDays=5)
{
    try
    {
        return Ok(_weatherForecastService.Forecast(numberOfDays));
    }
    catch(Exception ex)
    {
        return Problem(ex.Message);
    }
}
```

The issue comes in when trying to Unit Test such functionality.
```c#
[Fact]
public void WeatherForecastHandlesExceptions()
{
    // Arrange
    const string exception_message = "let's focus on the future";
    var mockWeatherForecastService = new Mock<IWeatherForecastService>();
    mockWeatherForecastService
        .Setup(s => s.Forecast(It.Is<int>(d => d < 1)))
        .Throws(new ArgumentOutOfRangeException(exception_message));
    var controller = new WeatherForecastController(mockLogger.Object, mockWeatherForecastService.Object);

    // Act
    var response = controller.GetWeatherForecast(-1);

    // Assert
    var result = Assert.IsAssignableFrom<ProblemDetails>(response.Result);
    Assert.Equal(exception_message, result.Detail);
}
```
A `NullReferenceException` is thrown when `GetWeatherForecast` is called. More specifically when `Problem(ex.Message)` is executed.

Any thoughts?
<img src="https://user-images.githubusercontent.com/5835438/87253507-cda4ae80-c449-11ea-8fe8-ed9277f2d5d7.png" data-canonical-src="https://user-images.githubusercontent.com/5835438/87253507-cda4ae80-c449-11ea-8fe8-ed9277f2d5d7.png" width="100" height="100" />

### To Reproduce
I generated a simple project using visual studio's templates, and added a test to demonstrates this issue.  
[Project Link](https://github.com/niesmo/ProblemDetailsUnitTestingIssue)

### Exceptions (if any)
```
Message:
  System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
  ControllerBase.Problem(String detail, String instance, Nullable`1 statusCode, String title, String type)
  WeatherForecastController.GetWeatherForecast(Int32 numberOfDays) line 35
  WeatherForecastUnitTests.WeatherForecastHandlesExceptions() line 35
```

### Further technical details
- ASP.NET Core version => `netcoreapp3.1`
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  3.1.105 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version => `Microsoft Visual Studio Enterprise 2019 Version 16.5.4`

**Comment by Kahbazi** [comment] 2020-07-13 12:17
Duplicate of https://github.com/dotnet/aspnetcore/issues/15166

**Closed** 2020-08-19 00:02 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-mvc
