### ISSUE TITLE
Create documentation of http3 and proxy usage

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#46853] opened 2023-02-23 23:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I just wanted to use in .net8 http3, unfortunately it requires me a certificate by such error:
```
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate cou       ld not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
```
I use ubuntu 20 LTS, nginx and cloudflare
The only documentation I found is:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-7.0

I added it:
```cs
webBuilder.ConfigureKestrel((context, options) =>
                {
                    options.ListenAnyIP(5001, listenOptions =>
                    {
                        listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                        listenOptions.UseHttps();
                    });
                });
```

But I have no information on how to add a certificate, what it must be. Can it be generated by CF Origin or lets encrypt. I think it should be in the documentation.

In addition, it would be nice to supplement the documentation with the settings recommended under http3 for nginx.

The nginx documentation I found:
https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/

---
Edit:
I see more information about the certificate. I see one problem, certificates change often. Is there no other way than asking the proxy for a certificate? For example, nginx queries "hey nginx, send me the certificate you are currently using". It would make the job and many problems easier. Many services may stop working one day because of this.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0

---
Edit2:
I found the nginx and quic installation instructions. Requires Ubuntu 22, may come in handy:
https://quic.nginx.org/packages.html

**Comment by Tratcher** [comment] 2023-02-24 17:49
Those nginx docs are for incoming QUICK & HTTP/3. There's no mention that they support forwarding traffic as HTTP/3, they barely even do that for HTTP/2. They likely downgrade traffic to HTTP/1.x when forwarding it to you.

Also, Kestrel and NGinx don't need to use the same certificate, nor does kestrel even need to use HTTPS when behind a proxy like this.

For more general proxy docs see:
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0

**Comment by Alerinos** [comment] 2023-02-24 18:27
@Tratcher 
> Also, why use NGinx at all? Why not directly expose Kestrel?

I've always seen recommendations to use nginx like spreading traffic everywhere. Kestrel used to not do well with face-to-face service, has anything changed? Will there be no problems if I expose Kerstel to the world in heavy traffic?

> Also, Kestrel and NGinx don't need to use the same certificate, nor does kestrel even need to use HTTPS when behind a proxy like this.

Kestrel does not require a certificate for HTTP3? It seemed to me that it was needed.

**Comment by Tratcher** [comment] 2023-02-24 18:36
Kestrel is an good web server on its own, but if you want to run multiple instances for redundancy and higher scale then you do need a load balancer like NGinx. Try Kestrel directly and see if it meets your needs.

Kestrel does require a certificate for HTTP/3, but it doesn't have to be the same certificate used by the reverse proxy. Kestrel does not require a certificate for HTTP/1.x, which is what is commonly used between NGinx and Kestrel.

I don't think NGinx can forward traffic using HTTP/3 to any backend, including kestrel. It would accept HTTP/3 at the front end and then convert it to HTTP/1.x when forwarding.

**Comment by Alerinos** [comment] 2023-02-24 21:04
@Tratcher 
I used the RSA 2048 certificate generated by Cloudflare on *domain.com and domain.com

My appsettings:
```
  "Kestrel": {
    "Endpoints": {
      "HttpsInlineCertAndKeyFile": {
        "Url": "https://domain:443",
        "Certificate": {
          "Path": "Certificate/cert.perm",
          "KeyPath": "Certificate/cert.key",
        }
      }
    }
  }
```
My code:
```cs
        Website = Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.ConfigureKestrel((context, options) =>
                {
                    options.ListenAnyIP(443, listenOptions =>  <--- 150 line
                    {
                        listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                        listenOptions.UseHttps();
                    });
                });

                webBuilder.UseStartup<Startup>();
            })
```
I've tried many things, each time I get the same error:
```
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at .Program.<>c.<Main>b__2_14(ListenOptions listenOptions) in C:\Git\Stand\Source\Projects\\Program.cs:line 153
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.ListenAnyIP(Int32 port, Action`1 configure)
   at .Program.<>c.<Main>b__2_13(WebHostBuilderContext context, KestrelServerOptions options) in C:\Git\Stand\Source\Projects\\Program.cs:line 150
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
   at InvokeStub_KestrelServerImpl..ctor(Object, Object, IntPtr*)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.Main(String[] args) in C:\Git\Stand\Source\Projects\\Program.cs:line 189
Aborted
```

The certificates are correct, what am I doing wrong?


> I don't think NGinx can forward traffic using HTTP/3 to any backend, including kestrel. It would accept HTTP/3 at the front end and then convert it to HTTP/1.x when forwarding.

It's worth mentioning in the documentation, I've often wondered how it works and whether it actually works.

**Comment by Tratcher** [comment] 2023-02-24 21:14
Remove this, it's redundant with your appsettings.json:
```C#
                webBuilder.ConfigureKestrel((context, options) =>
                {
                    options.ListenAnyIP(443, listenOptions =>  <--- 150 line
                    {
                        listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                        listenOptions.UseHttps();
                    });
                });
```

**Comment by Alerinos** [comment] 2023-02-24 22:09
@Tratcher 
I have a clean install of ubuntu 22 as LXD in proxmox zfs. I don't have any www service on the container. When I enter the domain itself, I get this error:
```
Unhandled exception. System.IO.IOException: Failed to bind to address https://[::]:443: address already in use.
```
``sudo netstat -tuln | grep 443`` clear
```
nmap -p 443 localhost
Starting Nmap 7.80 ( https://nmap.org ) at 2023-02-24 22:02 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000043s latency).
Other addresses for localhost (not scanned): ::1

PORT    STATE  SERVICE
443/tcp closed https

Nmap done: 1 IP address (1 host up) scanned in 0.11 seconds
```
When I add the port, the application gets up, unfortunately then it receives ``ERR_CONNECTION_TIMED_OUT``
``"Url": "https://h3.***.***:5001",``

libmsquic version:
```
libmsquic:
  Installed: 2.1.7
  Candidate: 2.1.7
```
I have .net 8 so according to the documentation I don't need 1.9

**Comment by Tratcher** [comment] 2023-02-24 22:21
How did you measure it? The performance difference is primarily for lossy connections like phones.

**Comment by Alerinos** [comment] 2023-02-24 22:58
I disabled http3 in cloudflare:
![image](https://user-images.githubusercontent.com/42449535/221312433-667592b2-bada-4d14-a3ac-9520a0b97836.png)

Kestrel config http3 domain:
```
https://h3.graj.se/
```
![image](https://user-images.githubusercontent.com/42449535/221314971-76a3f5cf-3aa0-40bf-b827-c2af0755fadf.png)

Kestrel + nginx http2 + cloudflare:
```
https://graj.se/
```
![image](https://user-images.githubusercontent.com/42449535/221315188-34adc272-c726-48a9-b4f6-c04f5259bc3c.png)

@Tratcher It seems that HTTP3 is not enabled by default. Any idea how to force the use of http3?

**Comment by Tratcher** [comment] 2023-02-24 23:20
Ah, the defaults vary by version.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0#set-the-http-protocol-from-configuration

```json
  "Kestrel": {
    "Endpoints": {
      "HttpsInlineCertAndKeyFile": {
        "Url": "https://domain:443",
        "Protocols": "Http1AndHttp2AndHttp3"
        "Certificate": {
          "Path": "Certificate/cert.perm",
          "KeyPath": "Certificate/cert.key",
        }
      }
    }
  }
```

**Comment by Alerinos** [comment] 2023-02-24 23:26
My config:
```json
  "Kestrel": {
    "Endpoints": {
      "HttpsInlineCertAndKeyFile": {
        "Url": "https://h3.graj.se:443",
	"Protocols": "Http1AndHttp2AndHttp3",
        "Certificate": {
          "Path": "/home/stand/release/Certificate/cert.perm",
          "KeyPath": "/home/stand/release/Certificate/cert.key",
        }
      }
    }
  }
```
@Tratcher When I did only ``"Protocols": "Http3"`` I got this message:
```
Unhandled exception. System.InvalidOperationException: This platform doesn't support QUIC or HTTP/3.
```

**Comment by Alerinos** [comment] 2023-02-27 20:26
@Tratcher 
```
apt-cache policy libmsquic
libmsquic:
  Installed: 1.9.1
  Candidate: 2.1.7
```
I even downgraded to 1.9
Could it be a problem that it is ubuntu 22?

**Comment by adityamandaleeka** [comment] 2023-02-27 23:05
cc @CarnaViire @karelz

**Comment by CarnaViire** [comment] 2023-02-28 11:56
> Could it be a problem that it is ubuntu 22?

Yes, the problem is that Ubuntu 22 has OpenSSL 3.0 by default. Tracking issue for that is https://github.com/dotnet/runtime/issues/81801

The workaround could be to build msquic from [sources](https://github.com/microsoft/msquic), though, be aware that the support for OpenSSL 3.x is early progress in msquic/main.
Example on manual build script is in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/808/files.
Also, some docs: https://github.com/dotnet/runtime/tree/main/src/libraries/System.Net.Quic#build-msquic.

**Comment by wfurt** [comment] 2023-02-28 16:00
There are also other ways like https://blog.technitium.com/2023/02/configuring-dns-over-quic-and-https3.html 
This is interim as Ubuntu 22 is only OS that does not offer compat openssl. Ubuntu 20 should work just fine.

**Comment by Alerinos** [comment] 2023-03-01 11:30
I think it's worth adding a note to the documentation that there are problems on ubuntu 22

**Comment by wfurt** [comment] 2023-03-01 16:06
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-7.0 still talks MsQuic about 1.9 @Tratcher - that should probably be updated. 

As far as the requirements, there is https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-http3 
While it does not talk about Ubuntu 22 it states the requirements. It is somewhat difficult for .NET to track every single Linux distributions.

There is also cross-link but it seems to be broken and it may not be obvious that what is applicable to HttpClient and Quic  is also applicable to Kestrel

**Comment by Alerinos** [comment] 2023-03-01 16:37
@wfurt Yes I'll do it. Thanks
Before that, I will test on ubuntu 20 to see if everything works.

**Comment by wfurt** [comment] 2023-03-01 18:03
BTW there are performance issues with OpenSSL 3: https://github.com/openssl/openssl/issues/20286 & https://github.com/microsoft/msquic/issues/3410
If you care about perf, Ubuntu 20 may be better choice in general. 

The annoying part about Ubuntu 22 is that it fails silently. Next maintenance version of MsQuic (e.g. 2.1.8) should have that fixed) and the package should fail to install because of missing dependencies. Unfortunately Ubuntu does not provide compat package like other distributions.

**Comment by adityamandaleeka** [comment] 2023-03-01 23:06
Thanks @CarnaViire and @wfurt. Sounds like this is being tracked in https://github.com/dotnet/runtime/issues/81801 so we can probably close this issue.

**Closed** 2023-03-04 00:37 UTC
Labels: area-runtime

**Comment by Alerinos** [comment] 2023-03-15 01:58
@adityamandaleeka 
I just started testing, unfortunately there is also a problem in Ubuntu 20.
```
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.15.74-1-pve x86_64)
```
```
apt-cache policy libmsquic
libmsquic:
  Installed: 2.1.7
  Candidate: 2.1.7
```

The problem is that when we run "Http3" the string still remains until Connection timed out 522.

for ``Http1AndHttp2AndHttp3`` uses H2

If I downgrade the version to 1.9.1 I have this message:
```
Unhandled exception. System.InvalidOperationException: This platform doesn't support QUIC or HTTP/3.
```

**Comment by wfurt** [comment] 2023-03-15 02:03
Does your test work on _any_ Linux @Alerinos? Ubuntu 20 should be just fine and combination of 7.0 and 2.1.7 is correct. 
It may be worth of trying packet capture to see what is going on. (and check packet filer rules if any)

**Comment by Alerinos** [comment] 2023-03-15 02:19
@wfurt Yes, I use the same code on ubuntu 20, ``https://graj.se``
Also if I don't force http3 it works fine.
How do you capture the packets? Wireshark or dump?

**Comment by wfurt** [comment] 2023-03-15 04:06
yes, Wireshark would be good IMHO. Maybe traces from Kestrel. When H/3 is active you should also see UDP port in LISTENING state.
