### ISSUE TITLE
Implement QuickGrid.OverscanCount 

### ISSUE THREAD

**Issue by jfowl** [dotnet/aspnetcore#53108] opened 2024-01-03 09:07 UTC
## Summary

Implement https://github.com/dotnet/aspnetcore/issues/49263, by adding a `OverscanCount` parameter to QuickGrid and passing it down as-is to [`Virtualize`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid/src/QuickGrid.razor#L22-L27)

## Motivation and goals

Being able to avoid loading-state rows upon small scroll changes

## In scope

- Using the same parameter, you would also use on Virtualize

## Out of scope

~~Scenarios you explicitly want to exclude.~~

## Risks / unknowns

None known

## Examples

```razor
<QuickGrid Items="@MyDbContext.People" Virtualize="true" OverscanCount="12">
  @* ... *@
</QuickGrid>
```

**Comment by mkArtakMSFT** [comment] 2024-01-23 17:10
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/49263

**Closed by mkArtakMSFT** 2024-01-23 17:10 UTC
Labels: enhancement, area-blazor, design-proposal, feature-blazor-quickgrid, Pillar: Dev Experience
