### ISSUE TITLE
Problem with nginx config in an app with SignalR and MVC apis

### ISSUE THREAD

**Issue by mrahhal** [dotnet/aspnetcore#25402] opened 2020-08-29 17:56 UTC
I'm opening this issue here as suggested by @guardrex, I first opened this in the docs repo here: https://github.com/dotnet/AspNetCore.Docs/issues/19708.

I have a single application that runs both an MVC api and a signalr hub. I deploy this on linux ubuntu with nginx. Following the docs, it's suggested to use `proxy_set_header   Connection "Upgrade";` in the nginx config. This does allow web sockets to work properly, but I saw a side effect on any api that isn't GET or OPTIONS. An exception was being thrown that re-surfaced as a CORS exception talking about allow origin not being set (a false positive). Inspecting the logs, this appeared:

```
DBG: Microsoft.AspNetCore.Server.Kestrel
  [2020-08-29T14:29:08.3359520+00:00] Connection id ""0HM2C4V9JMP66"" bad request data: ""Requests with 'Connection: Upgrade' cannot have content in the request body."" (86f1a409)
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Requests with 'Connection: Upgrade' cannot have content in the request body.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.For(HttpVersion httpVersion, HttpRequestHeaders headers, Http1Connection context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.CreateMessageBody()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

This is what alluded to the problematic "Upgrade" for the POST api that was ongoing here. I had to research for a long time until I found several places mentioning `$http-connection` . So what I did is the following:

```diff
server {
   ...
    location / {
        ...
-       proxy_set_header   Connection Upgrade;
+       proxy_set_header   Connection $http-connection;
        ...
    }
}
```

This completely fixed apis, and web sockets continued to work. So it seemed that this did the trick. I'm wondering if setting this option is safe and makes sense for the scenario I described.

For completeness, I also found a couple resources talking about separating another location in nginx config specifically for the web socket url so that `proxy_set_header   Connection "Upgrade";` can be set safely there. But I haven't tried this approach.

### Further technical details
- ASP.NET Core version: 3.1

cc: @guardrex

**Comment by Tratcher** [comment] 2020-08-29 18:04
Duplicate of https://github.com/dotnet/aspnetcore/issues/17081

**Closed** 2020-08-31 21:03 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
