### ISSUE TITLE
Initial Styles don't load correctly On new project when there's a spacing between project name on visual studio  

### ISSUE THREAD

**Issue by Oluwapelumi11** [dotnet/aspnetcore#57375] opened 2024-08-16 21:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

So i'm new to blazor, and i tried creating a project, named it Learning Blazor, everythin works fine but the page looks weirdly different from the one on the tutorial i was trying to follow,  i thought it was a version issue, but then i looked at the App.razor file and found the error. It parsed a css file link with spacing in the name, so i created another project without spacing in the name to test and everything works just fine
![Learning Blazor - Microsoft Visual Studio 16_08_2024 22_19_03](https://github.com/user-attachments/assets/bce5a234-bc3b-4c4a-a4db-60552ee55ace)

![Untitled - Personal - Microsoft​ Edge 16_08_2024 22_21_43](https://github.com/user-attachments/assets/e889de61-99b3-4241-b760-afdb89e7d396)

### Expected Behavior

if there are spaces in project names, it should put an underscore to replace spaces just as namespaces do ... i guess
![Untitled - Personal - Microsoft​ Edge 16_08_2024 22_23_05](https://github.com/user-attachments/assets/1fb912e3-d8d8-4c48-a9e6-107d1d260461)
when i crerated BlazorApp1

### .NET Version

8

**Comment by javiercn** [comment] 2024-08-17 16:14
@Oluwapelumi11 thanks for contacting us.

Dupe of https://github.com/dotnet/aspnetcore/issues/52196

**Closed by javiercn** 2024-08-17 16:14 UTC
Labels: area-blazor
