### ISSUE TITLE
Blazor WASM Hot Reload not working; "General Exception This error was not expected, your process might be corrupted..."

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42634] opened 2022-07-08 17:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WASM-Hot-Reload-not-working;-Gen/10060909)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.3.0 Preview 1.0]
Since VS2022 Preview 17.3.0 Preview 1.1, Blazor WASM Hot Reload stopped working with the following message:
Title: "Hot Reload"
"General Exception This error was not expected, your process might be corrupted and restart the app is recommended."

Whatever small change I'm making, this happens. It happens with and without debugging, but the message without debugging is different: "The following error occured when trying to apply your edits to the running application. The connection to the web browser was lost. This error was not expected, your process might be corrupted and restart the app is recommended."

It _DOES NOT_ happen in a newly created Blazor WASM Hosted project.

---
#### Feedback Bot on 6/3/2022, 05:26 PM: 

(private comment, text removed)
#### Bill Hiebert [MSFT] on 6/21/2022, 11:33 AM: 

(private comment, text removed)
#### Gábor Szabó on 6/23/2022, 01:56 AM: 

(private comment, text removed)
#### Bill Hiebert [MSFT] on 6/23/2022, 02:45 PM: 

(private comment, text removed)
#### Feedback Bot on 7/6/2022, 11:56 PM: 

(private comment, text removed)

---
#### Gábor Szabó solved on 6/23/2022, 01:58 AM, 0 votes: 

<p>The problem seems to have stemmed from adding repsonse compression to the server’s middleware pipeline. Removing the <code>app.UseResponseCompression();</code> call solved the issue. Also worth mentioning that Hot Reload might interfere with CSP security header configuration, as the tools might try to establish the initial connection via unsecure HTTP.</p>

**Comment by mkArtakMSFT** [comment] 2022-07-11 16:28
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/41772

**Closed by mkArtakMSFT** 2022-07-11 16:28 UTC
Labels: area-blazor, Author: Migration Bot :robot:, feature-hot-reload
