### ISSUE TITLE
Blazor: Two assets found targeting the same path with incompatible asset kinds

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/aspnetcore#38784] opened 2021-12-02 14:23 UTC
Built and packaged my RCL as nuget.  When adding it to a host project I get this error:

Looks like a conflict in the css folders between the nuget and the host but IDK why.  These are default folders/files provided by the Blazor template.  

> Error		Two assets found targeting the same path with incompatible asset kinds: 
> 'C:\Users\sam\.nuget\packages\my-control\1.0.18-beta.2\contentFiles\any\net6.0\wwwroot\css\open-iconic\FONT-LICENSE' with kind 'All'
> 'C:\Git\my-project\my-project\wwwroot\css\open-iconic\FONT-LICENSE' with kind 'All'
> for path 'css/open-iconic/FONT-LICENSE'	my-project	C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets	442	

Versions:
net6
Visual Studio 17.0.2

Update: Renaming the css folder to myproject-css in my RCL fixed this.  This is likely to be a common error since it involves folders that are created and named by the template.  Would appreciate guidance on how to avoid this in the future.

[See also this ticket](https://github.com/dotnet/aspnetcore/issues/38294).

**Comment by mkArtakMSFT** [comment] 2021-12-02 17:37
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design. There should be no static within the solution that can end up in the same publish location. And the solution you came up with is valid.

**Closed by mkArtakMSFT** 2021-12-02 17:37 UTC
Labels: area-blazor

**Comment by leaderanalytics** [comment] 2021-12-02 17:51
I think you should at least mention in the [documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-6.0&tabs=visual-studio) that this error will be encountered on the RCL happy path.  

1.) Create a new project.
2.) In the Create a new project dialog, select Razor Class Library from the list of ASP.NET Core project templates. Select Next.
3.) In the Configure your new project dialog, provide a project name in the Project name field or accept the default project name. Examples in this topic use the project name ComponentLibrary. Select Create.
4.) In the Create a new Razor class library dialog, select Create.
5.) Add the RCL to a solution:
Open the solution.
Right-click the solution in Solution Explorer. Select Add > Existing Project.
Navigate to the RCL's project file.
Select the RCL's project file (.csproj).
6.) Add a reference to the RCL from the app:
Right-click the app project. Select Add > Project Reference.
Select the RCL project. Select OK.

_**7.) Get a build error - Two assets found targeting the same path with incompatible asset kinds**_
