### ISSUE TITLE
TypeScript type definitions (d.ts) not available for the "Blazor" object

### ISSUE THREAD

**Issue by yugabe** [dotnet/aspnetcore#44942] opened 2022-11-08 12:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When initializing Blazor manually via JavaScript, the user is expected to understand the API surface of the global `Blazor` API based on the following article [https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0](ASP.NET Core Blazor startup | Microsoft Learn)

The API itself is not very well documented in this case. First, it can be deduced the object is probably a bit different between the hosting models.

### Describe the solution you'd like

A straightforward way to document would be to publish a DefinitelyTyped package for the API. This also could be referenced by the docs page mentioned above.

I think it's not a stretch to add this type to the existing `@types/blazor__javascript-interop` package.

### Additional context

I am currently using my own type definition that I tried to figure out from the documentation page:

```ts
declare global {
    const Blazor: {
        start: (options?: {
            loadBootResource?: (
                type: 'assembly' | 'pdb' | 'dotnetjs' | 'dotnetwasm' | 'timezonedata',
                name: string,
                defaultUri: string,
                integrity: string) => string | Promise<Response> | null | undefined,
            applicationCulture?: string
        }) => Promise<void>;
    }
}
```

The definitions help users to find features and solutions to problems in itself, so it shouldn't be overlooked. It can also be considered to be generated (if the source is in TypeScript; I wasn't able to find it in the limited time I spent on this issue).

Possibly related: #18902

**Comment by javiercn** [comment] 2022-11-08 14:08
@yugabe thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/44942

**Closed by javiercn** 2022-11-08 14:08 UTC

**Comment by yugabe** [comment] 2022-11-08 14:13
Thanks @javiercn, but you accidentally linked this issue as its own duplicate :) I already saw #18902 and it doesn't contain the definitions for the `Blazor` object, only for the `DotNet` one.

**Comment by javiercn** [comment] 2022-11-08 14:17
https://github.com/dotnet/aspnetcore/issues/10124

**Comment by javiercn** [comment] 2022-11-08 14:17
I meant to link this one

**Comment by yugabe** [comment] 2022-11-08 14:19
Thanks @javiercn, I saw that one, but didn't realize it was the same as this one.
