### ISSUE TITLE
Blazor WebAssemby Breakpoints on protected override async Task OnInitializedAsync() not working 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#32501] opened 2021-05-07 19:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WebAssemby-Breakpoints-on-protect/1412341)._

---
[severity:It's more difficult to complete my work]
The razor Page has an override for OnInitializedAsync.
The breakpoints in that method are not working.

I have some exception in the OnInitializedAsync and the browser shows a bunch of complex framework/mono errors but no real information about what is happening.
If I put a breakpoint in the OnInitializedAsync, the breakpoint is never hit and VS never stops. The method is being executed because I added code to validate the execution.

Debugging Blazor is not working well in general, with lots of issues with breakpoints not being hit and unreadable errors in JS referring to the framework.

---
#### Feedback Bot on 5/3/2021, 01:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-05-10 16:36
Thanks for contacting us. This might be  a dupe of https://github.com/dotnet/aspnetcore/issues/32505
Also, can you please clarify what are the `unreadable errors in JS` that you'
re seeing? Can you share the error or at least a screenshot?

**Closed** 2021-05-17 17:00 UTC
Labels: Author: Migration Bot :robot:, Needs: Author Feedback, Status: No Recent Activity, area-blazor, blazor-wasm, feature-blazor-debugging
