### ISSUE TITLE
 [9.0-preview.4] Remove default tag with the assembly name from OpenAPI document (#55884 )

### ISSUE THREAD

**Issue by fksalviano** [dotnet/aspnetcore#55906] opened 2024-05-27 17:27 UTC
## Summary

When there is no tags configured, the assembly name is used as a tag for each operation by default (related with #55884).

## Motivation and goals

- The principal motivation is do not show the assembly name to the user.

## In scope

The major scenario is when API has no tags definition to be used on documentation.

## Risks / unknowns

Something be wrong with the open api json being generated without the operation tags.

## Examples

In issue #55884 is showed the json being generated with the assemly name used as tag for the operations when thre is no tag configured:

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "OrderApi | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/": {
      "get": {
        "tags": [
          "OrderApi"
        ],
```
In this case OrderApi is the assembly name.

In my tests was necessary to change two points:

- GetOperationTags() method on OpenApiGenerator class to result an empty list instead a list with one tag containig the application name when not found any tag: 

```
        if (methodInfo.DeclaringType is not null && !TypeHelper.IsCompilerGeneratedType(methodInfo.DeclaringType))
        {
            return new List<OpenApiTag>() { new OpenApiTag() { Name = methodInfo.DeclaringType.Name } };            
        }
        else
        {
            // If the declaring type is null or compiler-generated (e.g. lambdas),
            // returns an empty list of tagas
            return new List<OpenApiTag>();
        }
```

- GetTags() method on OpenApiDocumentService class checking if the route values controller is diferent from assembly and reteurn an empty list:

```
    private List<OpenApiTag>? GetTags(ApiDescription description)
    {
        var actionDescriptor = description.ActionDescriptor;
        if (actionDescriptor.EndpointMetadata?.OfType<ITagsMetadata>().LastOrDefault() is { } tagsMetadata)
        {
            return tagsMetadata.Tags.Select(tag => new OpenApiTag { Name = tag }).ToList();
        }
        // If no tags are specified, use the controller name as the tag. This effectively
        // allows us to group endpoints by the "resource" concept (e.g. users, todos, etc.)
        var controllerName = description.ActionDescriptor.RouteValues["controller"];
        if (controllerName != hostEnvironment.ApplicationName)
            return [new OpenApiTag { Name =  controllerName}];
        else
            return new List<OpenApiTag>();
    }
```

And the generated json without the tags:

```
  "openapi": "3.0.1",
  "info": {
    "title": "API-Clean-VS",
    "description": ".Net Core API sample using Clean Architecture and Vertical Slice",
    "version": "v1"
  },
  "paths": {
    "/api/weatherforecast": {
      "get": {
        "description": "Get weather forecasts sample endpoint",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
```

**Comment by captainsafia** [comment] 2024-05-28 21:52
@fksalviano I believe this issue is an exact duplicate of the one that you referenced? I'll mark it as a dupe for now but if there are differences that I missed, let me know.

**Closed** 2024-05-29 22:59 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, design-proposal, area-web-frameworks
