### ISSUE TITLE
Blazor WebAssembly: Javascript getElementById fails. Blazor rendering bug?

### ISSUE THREAD

**Issue by SweetJV** [dotnet/aspnetcore#20198] opened 2020-03-26 18:43 UTC
### Describe the bug

There is one element in my component where, using Javascript interop, calling getElementById fails, even though the element exists and the id is correct. Calling getElementById on any other element, including children of that element, works fine. This makes me suspect something weird is going on with Blazor's manipulation of the DOM.

### To Reproduce

Here is a simplified project that shows this bug:

[https://github.com/SweetJV/BlazorGetElementByIdBug](https://github.com/SweetJV/BlazorGetElementByIdBug)

### Further technical details

* Visual Studio 16.5.1
* Blazor WebAssembly
* ASP.NET Core 3.1

dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment] 2020-03-31 14:06
@SweetJV thanks for contacting us.

I took a look at your repro project. It is likely that the cause of the issue is that you are trying to do JS interop with an element reference as part of an event handler. 

That makes the event handler async and that will trigger a re-render that might invalidate your element reference.

I would suggest that you change your code to update your component state and then use OnAfterRenderAsync to perform the JS interop calls to update the underlying JavaScript.

**Comment by SweetJV** [comment] 2020-04-01 04:02
@javiercn thanks for the reply.

That's an interesting theory, but I'm not sure how I could refactor my code to use OnAfterRenderAsync. My event handler is what triggers my DOM changes and I want to unregister my JS event before the component goes away, not after.

I would like to understand better what triggers a re-render. Are you saying that the JS event handler document.body.addEventListener("click"...) in RegisterListener() triggers a re-render? If not, the state of the Blazor UI is not changed until that JS event finishes and fires the C# callback. Until that point everything is happening in JS without any interop.

I was able to come up with a workaround that I can live with, but I don't think it's ideal. Here's what I did:

### ColorSwatchBase.razor.cs
1. Moved the call to register the click event from TogglePickerVisibility to OnAfterRenderAsync, when the panel is first shown.

### interop.js
1. Record the ids of the popup, and all children, when the click event is registered
NOTE: getElementById works fine here.

2. Use those ids in OnBodyClick, instead of element contains.

I've updated my repo, if you'd like to see it in action. I've also left the old method that uses element contains to test the click. You can easily toggle between these by changing UseElementIds in OnBodyClick.

### Thoughts
If work arounds like this are required to use Blazor properly and avoid it's rendering quirks, I guess I can live with that. But from a user experience standpoint, not being able to interact with the components during an event feels awkward. I'm sure all the plumbing to render the DOM is tricky. But if there's any way to refactor it so you can interact with components in events, that would be great!

**Comment by javiercn** [comment] 2020-04-01 12:44
@SweetJV any time an event is handled, one or more re-renders can happen.
* When an event handler is asynchronous, a re-render is triggered after the sync code finishes executing and another re-render is triggered after all async code has finished executing.

To update your code, I would change
```
        protected async Task ColorPickerChange(ChangeEventArgs e)
        {
            string sr = await JS.InvokeAsync<string>("GetElementValue", RedId);
            string sg = await JS.InvokeAsync<string>("GetElementValue", GreenId);
            string sb = await JS.InvokeAsync<string>("GetElementValue", BlueId);
            string sa = await JS.InvokeAsync<string>("GetElementValue", AlphaId);

            byte r, g, b, a;
            byte.TryParse(sr, out r);
            byte.TryParse(sg, out g);
            byte.TryParse(sb, out b);
            byte.TryParse(sa, out a);

            Color c = new Color(r, g, b, a);
            this.Color = c;

            await UpdateColorSwatch();
        }
```

To avoid calling `UpdateColorSwatch()` as part of the event handler and instead, simply register in a field that it needs to be called the next time OnAfterRender happens.

**Comment by javiercn** [comment] 2020-04-01 12:46
> ### Thoughts
> If work arounds like this are required to use Blazor properly and avoid it's rendering quirks, I guess I can live with that. But from a user experience standpoint, not being able to interact with the components during an event feels awkward. I'm sure all the plumbing to render the DOM is tricky. But if there's any way to refactor it so you can interact with components in events, that would be great!

In the Blazor programming model the right time to interact with elements is during `OnAfterRenderAsync` I can't talk about the details of your specific use case, but in general renders happen once when the handler/work is synchronous and twice when the handler is asynchronous.

**Comment by SweetJV** [comment] 2020-04-02 03:41
@javiercn Thanks for the advice. I'll try to develop a more deferred mentality in dealing with changes.

That said, after a little more exploration I don't think that's the problem here. I think there's a bug here where the DOM becomes corrupt. I added some more debug logging, including adding an override for ShouldRender, and I reverted to the code that calls getElementById. Here's what happens:

### Click the pop-up panel or any of it's child controls
JS: document.body click event handler
JS: OnBodyClick -> getElementById fails.

 No C# methods are run, before or after this, so I would expect a stable DOM.

### Click/hold a spinner arrow for one of the number inputs 
C#: ColorPickerChange - start
C#: ShouldRender x 2
C#: OnAfterRenderAsync x 2
C#: UpdateColorSwatch
C#: ColorPickerChange - finish
C#: ShouldRender x 2
C#: OnAfterRenderAsync x 2
JS: document.body click event handler
JS: OnBodyClick -> getElementById fails.

Because OnAfterRenderAsync is finished, I would expect a stable DOM.

### Click outside of the pop-up panel
JS: document.body click event handler
JS: OnBodyClick -> getElementById fails.
JS: UnregisterListener
C#: OnOutsideClick
C#: TogglePickerVisibility - start
C#: ShouldRender
C#: TogglePickerVisibility - finish
C#: ShouldRender
C#: OnAfterRenderAsync x 2

I realize that console log is async, so it's hard to trust the order of things. But it looks sensible. I don't know what kind of debugging tools you guys have, but if you're able to inspect the state of the DOM, I think this is worth looking into further. In the first case, no C# calls are involved at all, so clearly something has gone wrong.

I've updated my repo, so it should be easy to see this in action.
.

**Comment by javiercn** [comment] 2020-04-02 09:18
@SweetJV we'll take another more in depth look and get back to you.

**Comment by SweetJV** [comment] 2020-04-02 09:43
@javiercn Sounds good, thanks!

**Comment by captainsafia** [comment] 2020-05-08 22:14
Thanks for taking the time to produce this repro and to follow up with your own investigation, @SweetJV!

I took a look at your project and it looks like there is a typo [here](https://github.com/SweetJV/BlazorGetElementByIdBug/blob/34014af2b7bd15e0627e38c942a7c4f3169f510c/wwwroot/scripts/interop.js#L94). Making the following change resolved the issue on my clone of your project.

```
let el_this_id = document.getElementById(this.id); // Before
let el_this_id = document.getElementById(this.Id); // After, note the "i" is capitalized
```

I'll go ahead and close this as resolved but please reopen if there are other issues.

**Closed by captainsafia** 2020-05-08 22:14 UTC
Labels: area-blazor, blazor-wasm, investigate
