### ISSUE TITLE
NPM @microsoft/signalr instanceof Buffer issue

### ISSUE THREAD

**Issue by saidseven-7** [dotnet/aspnetcore#27290] opened 2020-10-28 14:16 UTC
There is an issue in the file @microsoft/signalr/dist/esm/HandshakeProtocol line 17
`if (isArrayBuffer(data) || (typeof Buffer !== "undefined" && data instanceof Buffer)) {`
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

**Comment by BrennanConroy** [comment] 2020-10-28 16:05
Dupe of https://github.com/dotnet/aspnetcore/issues/14030
Do you have `var Buffer = Buffer || [];` somewhere in your project?

We are looking at removing `Buffer` in the future https://github.com/dotnet/aspnetcore/issues/13805

**Closed** 2020-11-06 22:17 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
