### ISSUE TITLE
Code edit features like quick actions are missing in Blazor components.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#26616] opened 2020-10-05 18:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1208302/code-edit-features-like-quick-actions-are-missing.html)._

---
[severity:It bothers me. A fix would be nice]
Hi, 

Code edit features like quick actions are missing in Blazor components. When you edit a .cs file you see the quick actions and also the dropdowns on top, but they will not show up in .blazor files.

Best regards

---
#### Feedback Bot on 10/3/2020, 06:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by TanayParikh** [comment] 2020-10-05 18:46
Marking as duplicate of: https://github.com/dotnet/aspnetcore/issues/24779

**Closed by TanayParikh** 2020-10-05 18:46 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved
