### ISSUE TITLE
Route template at controller level causes "The request matched multiple endpoints" if AnAction and AnActionAsync is in the given controller

### ISSUE THREAD

**Issue by IshamMohamed** [dotnet/aspnetcore#23209] opened 2020-06-22 01:38 UTC
### Describe the bug
If a route template `[Route("[controller]/[action]")]` or `[Route("api/[controller]/[action]")]` is defined in a controller, which has two actions, with this naming convention `{AnytNameOfAction}` and `{AnytNameOfAction}Async` (ie: `Get `and `GetAsync`) - the framework throws "The request matched multiple endpoints" error.

### To Reproduce
1) Create new API project using the default template.
2) Change the route template at the controller from `[Route("[controller")]` to `[Route("[controller]/[action]")]`.
3) Run the application.
3.a) `curl localhost:[port]/weatherforecast/get` gives HTTP 200.
3.b)  `curl localhost:[port]/weatherforecast/getasync` gives HTTP 404 (correct - as we don't have the `getasync` action yet.
4) Add the new action `[HttpGet] public IActionResult GetAsync()` while `[HttpGet] public IEnumerable<WeatherForecast> Get()` is already in place.
5) Re-run the application.
6) `curl localhost:[port]/weatherforecast/get` and notice "Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints" error.

Workaround:
Remove the `action` in route template at the controller and define route template for each actions.
Eg:
```
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
	[HttpGet]
	[Route("get")]
	public IEnumerable<WeatherForecast> Get()
	{}
	
	[HttpGet]
	[Route("getasync/{id?}")]
	public IActionResult GetAsync(Guid? id)
	{}
}
```

### Further technical details
- ASP.NET Core version - 3.1
- Include the output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version - Visual Studio 16.6.2

**Comment by javiercn** [comment] 2020-06-22 11:38
@IshamMohamed thanks for contacting us.

This is expected since MVC treams the "async" suffix automatically from your action names, so if you have two actions `get` and `getasync` and apply `[Route("[controller]/[action]")] at the controller level, then you end up with two endpoints that match the route `weatherforecast/get`

We're closing this issue as the behavior discussed seems to be by design.

**Closed by javiercn** 2020-06-22 11:38 UTC
Labels: area-mvc, feature-routing

**Comment by IshamMohamed** [comment] 2020-06-22 13:11
For the future visitors (including me) : What happens here is that "Async suffix for controller action names will be trimmed by default" (there is a typo in the comment of @javiercn (read "trims" instead of "treams" - to avoid confusions). Related announcement - https://github.com/aspnet/Announcements/issues/351
