### ISSUE TITLE
Visual Studio version 16.6.0 Editor is Very Slow

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#22439] opened 2020-06-01 23:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1049548/visual-studio-version-1660-editor-is-very-slow.html)._

---
I'm developing Blazor project, and Editor is very slow to respond ... especially when working with razor files.

---
#### Marty Pomeroy on 5/26/2020, 03:35 PM: 

<p>It's not just the Editor.  Startup takes longer, compiling takes longer.</p>

#### Visual Studio Feedback System on 5/27/2020, 02:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment] 2020-06-01 23:01
Duplicate of: https://github.com/dotnet/aspnetcore/issues/22276

**Closed by NTaylorMullen** 2020-06-01 23:01 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Author: Migration Bot :robot:, Status: Resolved
