### ISSUE TITLE
Cannot use a RCL named Shared

### ISSUE THREAD

**Issue by c0g1t8** [dotnet/aspnetcore#20514] opened 2020-02-09 17:52 UTC
Created a RCL project named Shared and added to my solution.  When I attempted to use a component within it, I received compilation errors.

I created a Github repository that reproduces this problem.  https://github.com/c0g1t8/BlazorNamespaceIssue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b02665-c8ab-bd91-8057-3b07b4e238d3
* Version Independent ID: e4f176f5-0b94-d532-53d5-cffce437961a
* Content: [ASP.NET Core Razor components class libraries](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/class-libraries.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/class-libraries.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by javiercn** [comment] 2020-04-06 15:03
This is just the names clashing. The generated code should refer to types using `global::` to be more precise.

**Comment by mkArtakMSFT** [comment] 2020-04-24 17:02
This is a dupe of #18757

**Closed by mkArtakMSFT** 2020-04-24 17:02 UTC
Labels: area-blazor, task
