### ISSUE TITLE
Blazor WASM: Javascript/css not compressing when using Brotli web.config

### ISSUE THREAD

**Issue by Schoof-T** [dotnet/aspnetcore#51166] opened 2023-10-05 13:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When hosting a Blazor WASM application, I want to use brotli compression for the best compression possible. However when using the Microsoft suggested web.config (https://raw.githubusercontent.com/dotnet/AspNetCore.Docs/main/aspnetcore/blazor/host-and-deploy/webassembly/_samples/web.config) mine/external libraries their javascript/css files are not longer compressed.

![image](https://github.com/dotnet/aspnetcore/assets/2319986/f57dc0f6-f3f3-45de-bb4c-3cfe76aa2027)

When using the default generated web.config, the .js and .css files are compressed.

![image](https://github.com/dotnet/aspnetcore/assets/2319986/3e5e08d2-8523-4ca4-99b5-fb141ad9f962)

My IIS has the following installed and enabled:
- https://learn.microsoft.com/en-us/iis/extensions/iis-compression/iis-compression-overview#installation
- https://iis-umbraco.azurewebsites.net/downloads/microsoft/url-rewrite
- ![image](https://github.com/dotnet/aspnetcore/assets/2319986/4a0b5a9a-2ef3-421c-91b8-3cc32d1aad5d)
- ![image](https://github.com/dotnet/aspnetcore/assets/2319986/9794d181-89da-4666-9345-1a17b59858ad)

### Expected Behavior

I would expect the .js and .css files to also be compressed, preferebly in brotli or otherwise in gzip.

### Steps To Reproduce

- create a new Blazor WASM (not hosted) application
- run dotnet publish -c release
- host the application in IIS
- **Note that all content is now GZIP compressed**
- Update the pre-generated web.config to the Microsoft provided one  (https://raw.githubusercontent.com/dotnet/AspNetCore.Docs/main/aspnetcore/blazor/host-and-deploy/webassembly/_samples/web.config)
- **Note now that only the files in the _framework folder are compressed.** (But as brotli)

### .NET Version

.NET 7

### Anything else?

A secondary question, is it possible to generate the brotli web.config when running `dotnet publish`? Is this the correct way to do this? https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0

**Comment by Schoof-T** [comment] 2023-10-05 18:48
> @Schoof-T thanks for contacting us.
> 
> I don't think the web.config applies to files that are not part of the blazor payload. That is, during publish we will compress the Blazor runtime and related files, but we won't be compressing any other static file that you add/bring.
> 
> The configuration in the web.config requires the file to have been statically compressed to serve a compressed version. You can tweak the web.config to compress all the files or to enable dynamic compression on the ones that are not statically compressed, but that's something that we can't offer guidance on.

Thank you for the reply, that makes sense. Is there a reason why you are not compressing other files that I'm adding? I feel like that's a great way to optimize the size of a Blazor App. Might also be a good idea to add this information to the docs, because now just enabling the Brotli web.config has actually increased the file size of my Blazor App.

I'm having a difficult time finding guidance on how to optimize my the files I added.

**Comment by mkArtakMSFT** [comment] 2023-12-18 17:22
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/52824

**Closed by mkArtakMSFT** 2023-12-18 17:22 UTC
Labels: enhancement, area-blazor, Pillar: Technical Debt
