### ISSUE TITLE
Blazor 8 PersistentComponentState and Enhanced Navigation

### ISSUE THREAD

**Issue by oliverw** [dotnet/aspnetcore#51610] opened 2023-10-24 18:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have noticed that when navigating inside a Blazor 8 Web App, components using `@rendermode InteractiveAuto` are rendered once on the server during pre-rendering at which point I store the state in `PersistentComponentState`. When the component is rendered the second time on the client, the state is not available forcing the client to load the data a second time using a http request. Is this working as intended? Sounds like a waste of computation resources.

### .NET Version

8.0.100-rc.2.23502.2

**Comment by MackinnonBuck** [comment] 2023-10-24 18:52
Thanks for filing the issue, @oliverw!

The current mechanism for persistent component state only allows reading persisted state after the initial page load. This currently excludes enhanced navigations, but we have https://github.com/dotnet/aspnetcore/issues/51584 to track having better support for the enhanced navigation scenario.

I'm going to close this out as a duplicate of the existing issue. Thanks again 🙂

**Closed by MackinnonBuck** 2023-10-24 18:52 UTC
Labels: area-blazor

**Comment by Markz878** [comment] 2023-10-26 06:03
@MackinnonBuck @danroth27:  .NET is really performance focused! 
Also .NET: You don't mind double database reads per page navigation do you?
