### ISSUE TITLE
after upgrading to blazor preview 4 ... ResolveStaticWebAssetsInputs does not exist

### ISSUE THREAD

**Issue by aktxyz** [dotnet/aspnetcore#20992] opened 2020-04-19 04:31 UTC
After upgrading from preview2 to preview4 ... I am now getting this error with my blazor/wasm project

...\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview4.20210.8\targets\Compression.targets(67,5): error MSB4057: The target "ResolveStaticWebAssetsInputs" does not exist in the project.

I got this right after upgrading ... funny thing is it went away after a reboot for 2 days ... and then came back.

**Comment by javiercn** [comment] 2020-04-20 09:56
@aktxyz thanks for contacting us.

That sounds very strange, I would suggest you clear up your nuget cache and that should make it go away. It might mean that somehow your nuget package cache got corrupted. You can clear all your packages with `dotnet nuget locals --clear all` **(This will wipe out all the nuget packages from your machine)**

**Comment by aktxyz** [comment] 2020-04-20 13:09
I should have mentioned that I did clear the cache with that exact command you listed (several times) 
 ... and am still getting the error.

**Comment by javiercn** [comment] 2020-04-21 06:56
@aktxyz thanks for the details.

Can you share a minimal repro project that demonstrates the issue?

**Comment by aktxyz** [comment] 2020-04-22 15:47
I spent a good amount of time yesterday trying to get a small repo ... and failed ... and also never honed in what piece I chopped away that caused the error to go away.

One odd thing is if I F5 to debug the project, it attempts to build, shows that error, and does not run ... then when I F5 again ... it runs fine without showing any error ... so I am not stuck but just have an annoying oddness.

If there is any poking about anyone wants to recommend let me know.

**Comment by javiercn** [comment] 2020-04-22 20:48
@aktxyz I would suggest try to build from the command line with `dotnet build /bl:output.binlog;ProjectImports=ZipFile` and capture the binary log and project imports if you are able to reproduce it that way.

It is likely that there is an issue in the set of files you are using. I would also check that all the versions are up to date and that you are using the latest SDK version.

**Comment by Kim-SSi** [comment] 2020-04-24 13:32
I have the same issue with preview 5.
I have attached a small reproducer using BlazorExtensions.Logging updated to preview 5
I am using VS 2019 Preview `16.6.0 Preview 4.0` and my `dotnet --version` is `3.1.300-preview-015115`

I get a build failure that allways causes the target issue with ResolveStaticWebAssetsInputs.
`C:\Users\ssi\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview5.20216.8\targets\Compression.targets(67,5): error MSB4057: The target "ResolveStaticWebAssetsInputs" does not exist in the project. [R:\Issue20992\Reproducer-BlazorExtensions.Logging\src\Blazor.Extensions.Logging.JS\Blazor.Extensions.Logging.JS.csproj]
`

Attached is the output using `dotnet build /bl:output.binlog;ProjectImports=ZipFile`

[cmd ouput.txt](https://github.com/dotnet/aspnetcore/files/4529103/cmd.ouput.txt)
[output.binlog.zip](https://github.com/dotnet/aspnetcore/files/4529110/output.binlog.zip)
[output.ProjectImports.zip](https://github.com/dotnet/aspnetcore/files/4529111/output.ProjectImports.zip)
[Reproducer-BlazorExtensions.Logging.zip](https://github.com/dotnet/aspnetcore/files/4529112/Reproducer-BlazorExtensions.Logging.zip)

**Comment by Timka654** [comment] 2020-04-25 07:18
1. dotnet nuget locals --clear all
2. Update all packages in all projects in solution to latest preview versions 
- Microsoft.AspNetCore.Components
- Microsoft.AspNetCore.Components.*
3. Install package Microsoft.AspNetCore.Components.WebAssembly to project(.Models.dll) have error "ResolveStaticWebAssetsInputs"
4. dotnet restore

resolved problem for me

**Comment by javiercn** [comment] 2020-04-27 14:52
@pranavkm I took a look at @Kim-SSi output and this feels like a potential bug on the MSBuild evaluation? I looked at the binlog, (saw the error) and then looked at the targets in the project imports, and the target was there?

**Comment by pranavkm** [comment] 2020-04-29 13:58
@Kim-SSi Blazor.Extensions.Logging.Js is missing `<RazorLangVersion>3.0</RazorLangVersion>`. You'll need this to be present in your project file for the component model and static web assets support to be enabled. 

Note that we only expect `Microsoft.AspNetCore.Components.WebAssembly.Build` to be referenced by the blazor app that is meant to run, not by libraries or associated projects. 
Blazor.Extensions.Logging.JS does not reference the dev-server, which makes me suspect it's not the app being run.

**Comment by Kim-SSi** [comment] 2020-04-29 14:54
@pranavkm You are correct about the project not being a blazor app. It is a web project that is used to webpack the js files. 
I swapped the `Microsoft.AspNetCore.Components.WebAssembly.Build` to
`<PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.2" />` and 
`<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="3.1.2" />`
Adding the missing `<RazorLangVersion>3.0</RazorLangVersion` did fix the problem. 
And updating BlazorLinkOnBuild to BlazorWebAssemblyEnableLinking as per the build message.
Thank you for your assistance.

**Comment by javiercn** [comment] 2020-04-29 15:03
Closing since the underlying problem has been solved.

**Closed by javiercn** 2020-04-29 15:03 UTC
Labels: :heavy_check_mark: Resolution: Answered, Status: Resolved, area-blazor, blazor-wasm
