### ISSUE TITLE
Support running dotnet.wasm debug builds

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#19407] opened 2020-02-27 16:11 UTC
Currently there are two reasons why Blazor WebAssembly applications can't use the debug build of `dotnet.wasm`:

1. We don't provide any way to say you want to use anything other than the single fixed release binary
2. Even if you manually replace `dotnet.wasm` on disk with the debug binary, it fails at runtime because we're calling some Emscripten bound functions too early and they assert in debug builds.

**This issue is intended to cover item 2 on that list only.** For item 1, we want to deal with that separately, providing control over the `dotnet.wasm` flavor in more detail (debug/release, dynamic linking on/off, threading on/off, etc.).

**Comment by SteveSandersonMS** [comment] 2020-02-27 16:12
The reason why this is valuable is that it makes it easier to investigate things in the underlying runtime, as suggested by @lewing.

**Comment by mkArtakMSFT** [comment] 2020-03-02 17:41
This is a dupe of #13915

**Closed by mkArtakMSFT** 2020-03-02 17:41 UTC
Labels: area-blazor, blazor-wasm
