### ISSUE TITLE
System.Text.Json failure to deserialize strongly typed models from string

### ISSUE THREAD

**Issue by optimizasean** [dotnet/aspnetcore#42545] opened 2022-07-01 19:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

System.Text.Json doesn't seem to be functioning completely.

Used a simple webapi as well as console app.
System.Text.Json fails to deserialize all properties under all circumstances for all models.
It cannot deserialize anything into an object from string, stream, or otherwise.

### Expected Behavior

Newtonsoft works as expected -> reads json string and produces a list of objects set by the json properties.

System does not work, it always returns null/default/0/Empty values.
This is true for all identity framework roles (UserClaims, UserRoles, RoleClaims, UserLogins, UserTokens, ...) and also for all of my custom models (which don't inherit from anything).
No property, no matter the type, access modifier, virtual/not, decorators, nullable, or any collection loads in System.
Everything works in Newtonsoft.

### Steps To Reproduce

Here is a sample controller comparing Newtonsoft and System:
```csharp
using System;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Globalization;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Security.Claims;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

[ApiController]
[Route("[controller]")]
public class TestController: ControllerBase {
    [HttpGet]
    [Route("data/system")]
    public async Task<ActionResult<List<Role>>> DataSystem() => await LoadSystemTextJson<Role>();

    [HttpGet]
    [Route("data/newtonsoft")]
    public async Task<ActionResult<List<Role>>> DataNewtonsoft() => await LoadNewtonsoftJson<Role>();

    //Load Json Data Files using System.Text.Json
    public async Task<List<T>> LoadSystemTextJson<T>() {
        var stream = new FileStream(@$"Data/{typeof(T).ToString().Split('.').Last()}s.json", FileMode.Open, FileAccess.Read);
        return await JsonSerializer.DeserializeAsync<List<T>>(stream);
    }

    //Load Json Data Files using Newtonsoft.Json
    public async Task<List<T>> LoadNewtonsoftJson<T>() {
        using (var reader = new StreamReader(@$"Data/{typeof(T).ToString().Split('.').Last()}s.json")) {
            var json = await reader.ReadToEndAsync();
            return Newtonsoft.Json.JsonConvert.DeserializeObject<List<T>>(json);
        }
    }
}
```

Here is the EF Identity model -> Role:
```csharp
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.AspNetCore.Identity;

public class Role: IdentityRole<Guid> {
    //Key
    //public override Guid Id { get; set; }

    //public override string Name { get; set; }

    //Navigational Properties
    [NotMapped]
    public virtual List<UserRole> UserRoles { get; set; }
    [NotMapped]
    public virtual List<RoleClaim> RoleClaims { get; set; }
}
```

Json I load from file:
```json
[
    {
        "userRoles": null,
        "roleClaims": null,
        "id": "f8fcef98-bd88-4763-a5bb-6133b26d50e5",
        "name": "User",
        "normalizedName": null,
        "concurrencyStamp": "0fa0cec3-353d-4e3e-910d-cda3ce20e7a8"
    },
    {
        "userRoles": null,
        "roleClaims": null,
        "id": "e3a576cb-b3c1-44ee-a741-e949a0b23906",
        "name": "Moderator",
        "normalizedName": null,
        "concurrencyStamp": "ffe459ab-cb45-47e5-903b-3b2af955349d"
    },
    {
        "userRoles": null,
        "roleClaims": null,
        "id": "fb8f294d-6a88-4289-86be-ee89fc18af6e",
        "name": "Admin",
        "normalizedName": null,
        "concurrencyStamp": "5adac65d-81d8-4cf5-8275-21c805f2564b"
    }
]
```

Json loaded by System.Text.Json looks like this:
```json
[
  {
    "userRoles": null,
    "roleClaims": null,
    "id": "00000000-0000-0000-0000-000000000000",
    "name": null,
    "normalizedName": null,
    "concurrencyStamp": "d0b37daf-f34b-4988-8de2-4282d28f07a2"
  },
  {
    "userRoles": null,
    "roleClaims": null,
    "id": "00000000-0000-0000-0000-000000000000",
    "name": null,
    "normalizedName": null,
    "concurrencyStamp": "87a54c22-3e2a-4f09-91c5-52716d3cde56"
  },
  {
    "userRoles": null,
    "roleClaims": null,
    "id": "00000000-0000-0000-0000-000000000000",
    "name": null,
    "normalizedName": null,
    "concurrencyStamp": "9d8ed15b-60e8-427b-ac39-2390cb416876"
  }
]
```

System.Text.Json settings:
```csharp
builder.Services.AddControllers().AddJsonOptions(options => {
    //Only if there are real problems
    options.JsonSerializerOptions.AllowTrailingCommas = false;
    //Should not ignore, design should use [JsonIgnore] to prevent
    options.JsonSerializerOptions.IgnoreReadOnlyFields = false;
    options.JsonSerializerOptions.IgnoreReadOnlyProperties = false;
    //Allow "Json Numbers" - i.e. quoted strings
    options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.AllowReadingFromString;
    //Ignore case because odd serial problems...
    options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
    //Set naming policy - can camel case and other stuff - JsonNamingPolicy
    options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    //Necessary for many entity framework queries in case of self reference or certain other instances
    options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
    //Make pretty for me
    options.JsonSerializerOptions.WriteIndented = true;
});
```

### Exceptions (if any)

None

### .NET Version

.NET 6

### Anything else?

I tried multiple variants like deserializing from read string instead of stream as well as used most of the other methods and always got the same.
The docs were not very helpful in diagnosing the problem so I can't offer any fixes or insight, but @SQL-MisterMagoo did inform me in the gitter that there may be issues regarding inherited properties, although this seems to expand beyond just that since all of my other models fail as well.

**Comment by MariovanZeist** [comment] 2022-07-01 20:48
@optimizasean 
The problem is that you are not using the correct ``JsonSerializeSettings``.
when you call a Deserialize or Serialize function without specifying the options you want to use, STJ will use default options.

For the serialize to use the settings you provided in the ``.AddJsonOptions`` you will have to supply them to the deserialize function.

Change your code to:
```cs
     public async Task<ActionResult<List<Role>>> DataSystem([FromServices] JsonOptions opt ) //get the JsonOptions that are configured
        => await LoadSystemTextJson<Role>(opt);

     public async Task<List<T>> LoadSystemTextJson<T>(JsonOptions opt)
     {
         var stream = new FileStream(@$"Data/{typeof(T).ToString().Split('.').Last()}s.json", FileMode.Open, FileAccess.Read);
         return await JsonSerializer.DeserializeAsync<List<T>>(stream, opt.JsonSerializerOptions);    //Supply those options here
     }
```

**Comment by optimizasean** [comment] 2022-07-01 21:22
Not exactly the problem - although if I do specify it as:
```csharp
public async Task<List<T>> LoadSystemTextJson<T>() {
    var stream = new FileStream(@$"Data/{typeof(T).ToString().Split('.').Last()}s.json", FileMode.Open, FileAccess.Read);
    JsonSerializerOptions options = new (JsonSerializerDefaults.Web);
    return await JsonSerializer.DeserializeAsync<List<T>>(stream, options);
}
```

It works in this case.
I think it is unclear why the defaults are not language independent (permissive case).

Also, when configured through the builder, it was also unclear that it doesn't apply to the instances used in the controller.
I assumed they were inherited and their configurations at base would be identical similar to how the ApiControllerBase provides certain decorators and methods as well as other variables such as the HttpContext (configured based on services defaults + decorators to select in the case of authorization).

Should the options be inherited from the ApiController / builder if they have been configured?
It seems a little against builder configuration to not have them inherited.
Is there a doc referencing how this should be done?

Also, I would like to ask we add something in the docs about this as well as the fact that it successfully fails to deserialize objects (I have a list with the right number of objects) but does not set the properties as I could not find any articles explaining why.

**Comment by optimizasean** [comment] 2022-07-01 21:33
This could be a weird configuration bug if builder is supposed to, but not configuring the default or exposing the options.
It does configure the ApiControllerBase when it serializes the data out (client bound) but it does not appear to be inherited on the serializer "in" the controller, just the one used by it on the middleware.
It also does not appear to be accessible from the services or otherwise to copy or load.

Is there a way to configure the default settings for the JsonSerializer in the builder, and followup, to configure them without needing to previously call `.AddControllers()`?

This would make the serializer less tied to the web stack and usable in more scenarios following the builder configuration conventions.
Potentially there could be `.AddControllers.AddJsonOptions(x)` and `services.ConfigureJsonDefaults(x)` where the configure defaults sets all serializers created to use those options, and the add json options only sets for the controllers (overriding configure defaults if used also)?
This could set up defaults for serialization to and from files to use faster or more permissive settings v.s. api endpoints which would possibly be more secure or strict.

**Comment by MariovanZeist** [comment] 2022-07-01 21:40
You can get the options you configured in ``.AddJsonOptions`` 
By changing your code to:

```cs
 [HttpGet]
 [Route("data/system")]
 public async Task<ActionResult<List<Role>>> DataSystem([FromServices] IOptions<JsonOptions> options )
    => await LoadSystemTextJson<Role>(options.Value);

    //Load Json Data Files using System.Text.Json
 public async Task<List<T>> LoadSystemTextJson<T>(JsonOptions options) {
     var stream = new FileStream(@$"Data/{typeof(T).ToString().Split('.').Last()}s.json", FileMode.Open, FileAccess.Read);
     return await JsonSerializer.DeserializeAsync<List<T>>(stream, options.JsonSerializerOptions);
 }
 ```

**Comment by optimizasean** [comment] 2022-07-01 21:58
That does work, but I wouldn't mark it as a perfect solution.
Since many things need to be passed into methods sometimes, this could quickly get out of hand.

I am imagining passing the options for JsonSerializer, passing the database context, the query parameters, certain service injections for claims building services, jwt defaults, other service options, ...

Could quickly have a method that becomes unreadable with parameters (or at least really ugly at a minimum).

To add in some conversation happening in the gitter:
```text
Is there no way to configure the defaults for all serializers? I guess I would ideally like to configure the json defaults for everywhere it is used, and maybe AddJsonOptions would override that specifically for controllers. If I created custom instances elsewhere like in your scenario, I would still need to specify the options if they need to be different. However, currently, no matter if they should all be identical, I always have to specify the options.

Also, If I configure the defaults the controller uses, I would assume the serializer in the controller would follow those defaults unless otherwise configured at a bare minimum. I can understand not setting everywhere since that .AddJsonOptions is for configuring the controllers settings, but not inheriting inside the controller seems counterintuitive.

A good example would be the dbcontext - when I configure that in the context + builder, all instances of it inherit those defaults unless changed directly.

Same for authentication setup -> the way to construct the identity is setup in the builder and shared to everything that reads the identity to break it down into the claims sets and principles

I tried looking but couldn't find a JsonSettings.ConfigureBaseline or something like that to set the defaults for the scope of the application

NewtonSoft has the ability to set default options. STJ doesn't. And I think it's a dangerous option to have (convenient maybe, but dangerous nontheless)
Suppose I have a reader in some library that uses the default settings for reading some file. And then some developer comes along and changes some defaults. And now suddenly that code tucked away in a library doesn't read your files anymore.

But STJ already has defaults (JsonOptions.Web or something and plenty others) and a way to configure it for all controllers (AddJsonOptions). I would say that it should have a way to set it in the builder to configure for what we want it to be. The point of a configuration class or a builder is to set the defaults for the whole application.

I could even make the argument that not being able to set the default is a security hazard or a potential for failure since I need to review the code everywhere they used a serializer and ensure it was done properly so it does not fail on users or expose the server to risks. And if the way it is supposed to be set (fast and secure) is not good for your usage, it should be changed in the builder like how we configure everything else instead of configured hundreds of times everywhere else.
```

Potentially there may be a feature request to set default configuration v.s. default controller configuration, and/or to have the configuration used in controllers inherited from the controller configuration.


Relevant help docs:
- [Configure Json Serialization/Deserialization options for STJ](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-configure-options?pivots=dotnet-6-0#web-defaults-for-jsonserializeroptions)
- [Json configuration properties](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions?view=net-6.0#properties)
- [Json defaults](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializerdefaults?view=net-6.0)

**Comment by davidfowl** [comment] 2022-07-02 01:56
So we can close this issue?

**Comment by javiercn** [comment] 2022-07-02 09:58
> Potentially there may be a feature request to set default configuration v.s. default controller configuration, and/or to have the configuration used in controllers inherited from the controller configuration.

You can already control this in MVC on a per-controller by setting your own json formatter with whatever options you want in the ObjectResult returned by actions. You can do this at the action, controller or global levels with a filter.

**Closed** 2022-07-02 09:58 UTC
Labels: question, :heavy_check_mark: Resolution: Answered, Status: Resolved, area-web-frameworks

**Comment by optimizasean** [comment] 2022-07-26 23:22
Yes, we can definitely close it. Just wanted to make sure I didn't miss anything documentation wise to add here.

Thanks.
