### ISSUE TITLE
Blazor capturing unmatched values: cannot use `preventDefault`

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/aspnetcore#25647] opened 2020-09-05 16:53 UTC
Consider a component Foo that's implemented as
```
<button @attributes="Attributes">Click me</button>
@code {
   [Parameter(CaptureUnmatchedValues = true)] public Dictionary<string, object> Params { get; set; }
}
```

That can be used as follows:
```
<Foo @onclick="(_) => { Value = !Value; }" />
@Value
@code {
   private bool Value { get; set; }
}
```

If I wanted to `preventDefault` on `onclick`, I could write the following:
```
<button @onclick="(_) => { Value = !Value; }"  @onclick:preventDefault>Click me</button>
```
but the following results in a compile time error:
```
<Foo @onclick="(_) => { Value = !Value; }"  @onclick:preventDefault />
```

The error is 
> RZ10010
>	The component parameter 'onclick' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'onclick' is generated by the `@onclick:preventDefault` directive attribute.	TestProject_Components	

I would expect this to not raise an error, and instead pass on the `preventDefault` to the button in the component too.

Note that this occurs with any event, not just `onclick`.

**Comment by SteveSandersonMS** [comment] 2020-10-07 10:23
Just realised this is a dupe of the more general issue https://github.com/dotnet/aspnetcore/issues/20560

**Closed by SteveSandersonMS** 2020-10-07 10:23 UTC
Labels: area-blazor
