### ISSUE TITLE
Build errors with multi-targetted project referencing ASP.NET Core 6 packages after upgrading to .NET 6 preview 6 

### ISSUE THREAD

**Issue by JeremySkinner** [dotnet/aspnetcore#34349] opened 2021-07-14 19:45 UTC
### Describe the bug
When a project targets `net6.0` as well as `.net5.0`/`netcoreapp3.1` and references `Microsoft.AspNetCore.Mvc.Testing`, a build error occurs:

```
CSC : error CS0006: Metadata file '/home/jskinner/.nuget/packages/microsoft.extensions.logging.abstractions/5.0.0/analyzers/dotnet/cs/Microsoft.Extensions.Logging.Generators.dll' could not be found [/home/jskinner/Desktop/test1/test1.csproj]
CSC : error CS0006: Metadata file '/home/jskinner/.nuget/packages/microsoft.extensions.logging.abstractions/3.1.0/analyzers/dotnet/cs/Microsoft.Extensions.Logging.Generators.dll' could not be found [/home/jskinner/Desktop/test1/test1.csproj]
CSC : error CS0006: Metadata file '/home/jskinner/.nuget/packages/system.text.json/4.7.0/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll' could not be found [/home/jskinner/Desktop/test1/test1.csproj]
```

It appears to be trying to find `Microsoft.Extensions.Logging.Generators.dll` inside the microsoft.extensions.logging.abstractions package, but this doesn't exist in older (pre-net6) versions of the package.

### To Reproduce
Run `dotnet build` against the following csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
    <RootNamespace>Demo</RootNamespace>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='netcoreapp3.1'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="3.1.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net5.0'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net6.0'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.0-preview.6.21355.2" />
  </ItemGroup>
</Project>
```
The same behaviour can be seen [in the .net 6 CI for the FluentValidation project](https://github.com/FluentValidation/FluentValidation/runs/3069817411?check_suite_focus=true). 

The error doesn't occur if I remove the netcoreapp3.1 and net5 targets - the net6 target then builds fine. Similarily, if I remove the net6 target, the net5/netcoreapp3.1 targets build fine. 

I'm not sure if this is the right repo to open this as it's build-related, but as it seems to happen when specifically referencing `Microsoft.AspNetCore.Mvc.Testing` I thought I'd start here. Please feel free to point me to a different repo if it would be better reported elsewhere.

### Exceptions (if any)

n/a

### Further technical details
- .NET 6 preview 6 
- Output of dotnet info:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/jskinner/.dotnet/sdk/6.0.100-preview.6.21355.2/

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  2.1.505 [/home/jskinner/.dotnet/sdk]
  3.1.408 [/home/jskinner/.dotnet/sdk]
  5.0.202 [/home/jskinner/.dotnet/sdk]
  6.0.100-preview.6.21355.2 [/home/jskinner/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/home/jskinner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [/home/jskinner/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by pranavkm** [comment] 2021-07-14 19:58
@JeremySkinner guessing this is a dupe of https://github.com/dotnet/sdk/issues/18148. There's some funny XML here - https://github.com/dotnet/sdk/issues/18148#issuecomment-860957180 - that might temporarily unblock the issue.

**Comment by JeremySkinner** [comment] 2021-07-14 20:10
@pranavkm thanks, yes that does seem to be the same issue and the workaround helps in my case. Thanks for pointing me in the right direction!

**Closed** 2021-07-15 17:00 UTC
Labels: area-mvc
