### ISSUE TITLE
Inject CMS Content to Razor Components at compile time

### ISSUE THREAD

**Issue by mouldt** [dotnet/aspnetcore#50817] opened 2023-09-19 14:35 UTC
Hi,
if you use a CMS with your site but the content is mainly static e.g. home, contact, about us etc - how does this fit with Blazor?
With other SPA frameworks e.g. Nuxt.js there are CMS systems that process and inject their content to the pages at build time.
So, for example, you could have a markdown file or a liquid template (index.liquid)  NOTE: this could even contain frontmatter to enable add meta tags to the head to improve SEO.
At build time a 'processor' would examine the razor component and replace a tag with the processed content of the CMS file. From then on its just the normal razor compilation.
The benefit, as i see it, is twofold:
1. The content is extracted into something a less tech savvy person can deal with e.g. Markdown
2. The razor page is then able to also be pre-rendered to a static html page, with the content embedded, so its not an API call cost every time the page is rendered but a one-time cost at build time. This yield SEO and page performance benefits.

Could we have this functionality/experience with Blazor?

**Comment by mkArtakMSFT** [comment] 2023-09-19 16:44
Thanks for contacting us.
it's not very clear what exactly you're asking for. Are you asking for static-site generation support at compile time?

**Comment by marinasundstrom** [comment] 2023-09-19 18:47
@mouldt Are you talking about using Blazor as a static site generator that produces static files? Like having markdown file and compile it like some other JS framework do?

There is no such thing in Blazor. But I guess that someone could create build tasks that could do that. It is not just included in Blazor.

If you are looking for prerendering of Blazor WASM pages, then I recommend this: https://github.com/jsakamoto/BlazorWasmPreRendering.Build

**Comment by mouldt** [comment] 2023-09-20 07:33
@marinasundstrom - yes exactly that, a static site generator but producing the files from markdown and razor components. These pages are then used as the direct landing page that a user can navigate to, so they render the page quickly, then they hydrate the blazor app in the background and then switch, so you get the best of both worlds.

I did look at [https://github.com/jsakamoto/BlazorWasmPreRendering.Build](https://github.com/jsakamoto/BlazorWasmPreRendering.Build)
but this would need to be enhanced to deal with the markdown injection aspect. I will take a look and see what I can come up with.

**Comment by marinasundstrom** [comment] 2023-09-20 09:21
@mouldt I know that Astro has [MDX](https://docs.astro.build/en/guides/markdown-content/) which is a mix of Markdown and JSX. 

Blazor does not have that. But it's giving me ideas for enhancing my blog. 

Feel free to experiment if you want to.

Some resources:

* [Markdig](https://github.com/xoofx/markdig)
* [Render Razor components outside of ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?view=aspnetcore-8.0)

You could simply combine these resources - then create a MSBuild task. Of course, there is more to do, like editor experience etc.

**Comment by javiercn** [comment] 2023-09-20 10:32
@mouldt thanks for the additional details.

We do have support for rendering components outside of the HTTP context, which is the basis for you to build something like that, by rendering from a console app or similar, but we do not offer an out of the box solution for it.

**Comment by mkArtakMSFT** [comment] 2023-12-20 17:47
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/51046

**Closed by mkArtakMSFT** 2023-12-20 17:47 UTC
Labels: area-blazor, Needs: Attention :wave:, Pillar: Complete Blazor Web
