### ISSUE TITLE
dotnet process stays running after stopping debug.

### ISSUE THREAD

**Issue by cyberyaga** [dotnet/aspnetcore#39090] opened 2021-12-17 07:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm running a brand new blazorwasm project (Hosted). Project Code: [https://github.com/cyberyaga/TerritoryWeb](url)
I'm running on Ubuntu 21.10. VS Code 1.63.2
Dotnet info:
` OS Name:     ubuntu
 OS Version:  21.10
 OS Platform: Linux
 RID:         ubuntu.21.10-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
`

I managed to get Server and Client side debugging (after a lot of work).

Issue: Every time I stop debugging. It seems that kestrel stays running. So, the next time I debug run the project, it errors out with "Address is already in use".

I have to go manually and run:
`lsof -i:[portnumber]`
`kill -9 [PID]`

After doing this a couple of times, it gets old really quick :)

### Expected Behavior

Killing the process manually is not a solution.

The expected behavior is that if the debugger is stopped, the process should end. And when starting the debugger again, it should not error out forcing the user to manually kill the process.

### Steps To Reproduce

OS: Ubuntu 21.10
VS Code: 1.63.2

- Create a new blazorwasm (hosted) project:
`dotnet new blazorwasm -ho`

- Open project in VS Code
- Debug project (F5) and wait for the page loads in your browser.
- Stop the debugger in VS Code (both sessions Server and Client).
- Try to debug again (F5).
- The debugger should throw an exception as shown below.

### Exceptions (if any)

System.IO.IOException: Failed to bind to address https://127.0.0.1:7230: address already in use.

### .NET Version

6.0.101

**Comment by TanayParikh** [comment] 2021-12-17 15:11
Duplicate of https://github.com/dotnet/aspnetcore/issues/38382

**Closed** 2021-12-18 16:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-blazor, blazor-wasm, Status: Resolved, feature-blazor-debugging
