### ISSUE TITLE
Exception Thrown by OnInput Event in a Table

### ISSUE THREAD

**Issue by CincySteve** [dotnet/aspnetcore#25400] opened 2020-08-29 13:44 UTC
An exception is thrown whenever content is changed in a table cell with an oninput event handler.  I have also tried onchange and onkeydown.  onchange did nothing.  onkeydown did fire successfully.  [This](https://stackoverflow.com/questions/63637928/how-to-handle-blazor-wasm-table-input-and-changes) StackOverflow post says that oninput is not supported as a direct table data element event, but that an input element of some type needs to be put inside the table data element.  Seems to make some sense.  But [this](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1) MS documentation indicates otherwise, and certainly not flagging a compile-time error and throwing this obscure event wouldn't be right if it isn't allowed.

The code and exception message is shown below [I can't get the code to post properly, but what's shown does include the table data elements that include the oninput reference].

Exception Message:

blazor.webassembly.js:1 Uncaught (in promise) Error: System.InvalidOperationException: There was an error parsing the event arguments. EventId: '1467'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
  at Microsoft.AspNetCore.Components.Web.WebEventData.DeserializeChangeEventArgs (System.String eventArgsJson) <0x35ea650 + 0x0001e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson (System.UInt64 eventHandlerId, System.String eventArgsType, System.String eventArgsJson) <0x33bd908 + 0x00206> in <filename unknown>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x28694c8 + 0x000ce> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo& callInfo, Microsoft.JSInterop.Infrastructure.IDotNetObjectReference objectReference, System.String argsJson) <0x3c6a970 + 0x0017a> in <filename unknown>:0 
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo invocationInfo, System.String argsJson) <0x3c6a318 + 0x0009e> in <filename unknown>:0 
    at Object.endInvokeDotNetFromJS (https://localhost:44307/_framework/blazor.webassembly.js:1:10049)
    at Object.invokeJSFromDotNet (https://localhost:44307/_framework/blazor.webassembly.js:1:9669)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44307/_framework/wasm/dotnet.3.2.0.js:1:171433)
    at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
    at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[5109]:0xddb3d)
    at do_runtime_invoke (<anonymous>:wasm-function[1410]:0x3ba85)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[418]:0xcfdb)

Code
```razor
    @code 
    {
    private void BBDetail_OnChange(ChangeEventArgs e)
        {
        Console.WriteLine("IBBBDetailTable: OnChange");
        }

    private void BBDetail_OnInput(ChangeEventArgs e)
        {
        Console.WriteLine("IBBBDetailTable: OnInput");
        }

    private void BBDetail_OnKeyDown(EventArgs e)
        {
        Console.WriteLine("IBBBDetailTable: OnKeyDown");
        }
    }

        <table>
            <thead>
                <tr>
                    @foreach (BBDColSpec colSpec in ColSpecList)
                        {
                        <td class="bbdTableHeader">
                            @colSpec.ColName
                        </td>
                        }
                </tr>
            </thead>

            <tbody>

                @for (int year =FirstYear; year <= LastYear; year++)
                    {
                    <tr>
                        <td contenteditable="false">
                            @year
                        </td>

                        @for (var colIndex = 1; colIndex <= ColSpecList.Count() - 1; colIndex++)
                            {
                             <td contenteditable="true"
                                   @oninput="BBDetail_OnInput">
                                   @TableValueList[@year - @FirstYear][@colIndex].Value_Decimal
                               </td>
                            } @*end colIndex*@
                    </tr>
                    } @*end year*@
                </tbody>
            </table>
```

**Comment by praeclarum** [comment] 2020-09-17 01:19
I'm running into this too when trying to get input from a content editable div:

```razor
<div contenteditable="true" @oninput="HandleInput"> EDIT ME </div>
```

Are there any ways to override the default handler?

**Comment by AlexPaskhin** [comment] 2020-09-29 10:25
I have got this issue for "5.0.100-rc.1.20452.10"
I have create Angular Web Component. Everything work fine except "global" events. In my case it is "change", it doesn't work.
```

 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.Web.WebEventData.DeserializeChangeEventArgs(String eventArgsJson)
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(UInt64 eventHandlerId, String eventArgsType, String eventArgsJson)
   --- End of inner exception stack trace ---
```
Here 
https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web.JS/src/Rendering/EventForDotNet.ts

I found the  event "fromDOMEvent" convertor from Dom event to Blazor event.

It causes Json convertor to crash in absence  or compatible  parameters  {value :"text"} for ChangeEventArgs.cs like  
```
class ChangeEventArgs 
{
  public object? Value { get; set; }
}
 
```
In 
https://github.com/dotnet/aspnetcore/blob/master/src/Components/Shared/src/WebEventData.cs

the method fails:
```
var changeArgs = Deserialize<ChangeEventArgs>(eventArgsJson);
```
Also:
The mapping  "DOM Event" ==> "Baloz Event" should be explained in docs.
Now you can find conversion rules  only here.

**Comment by damianog** [comment] 2020-10-04 21:02
Similar issues to me on a checkbox during "onchange" event during check uncheck then after 
 checking again I get the exception

**Comment by SteveSandersonMS** [comment] 2020-10-07 14:57
I think this is a duplicate of #9974

**Closed by SteveSandersonMS** 2020-10-07 14:57 UTC
Labels: area-blazor, investigate
