### ISSUE TITLE
Resolve breaking change with SSL exception

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#18585] opened 2020-01-26 05:20 UTC
We updated runtime dependencies which resulted in a couple SSL tests failing due to an unexpected exception type being thrown. This is occurring on Fedora, Debian, and Ubuntu 18 test runs only.

The temporary change to make the tests pass is https://github.com/dotnet/aspnetcore/commit/c180668c3565a60492a50f669bfbcef355af02ca.

> Throwing a different (and inconsistent) exception is a regression.

We should figure out what changed, why, and how we want to resolve it.

I'm guessing the change is from https://github.com/dotnet/runtime/pull/453

@Tratcher @jkotalik @halter73 @anurse @wfurt

**Comment by wfurt** [comment] 2020-01-27 17:55
Do you have more details @BrennanConroy? Do you know if the systems listed  have OpenSSL 1.1.1? (depends on patch level)

**Comment by BrennanConroy** [comment] 2020-01-27 20:37
I have no idea. I just happened to be around when the change came through and "fixed" it and filed the issue. Please follow up with one of the folks I mentioned above.

**Comment by anurse** [comment] 2020-01-27 22:18
@wfurt It does seem to be OS-specific behavior because it only failed on Fedora, Debian and Ubuntu 18 runs in Helix.

@BrennanConroy can you include the Helix Queue names that failed (the full names).

**Comment by wfurt** [comment] 2020-01-27 22:52
If dotnet/runtime#914 is the root cause for this OS-specific behavior would be expected. We would now properly send/receive TLS alerts. The general expectation is that if peer sends alert we would throw AuthenticationException. If peer closes the connection or if there is an incomplete frame we would throw IOException.
But older OpenSSL versions did not send alerts in all cases where new versions do. 

Is there some way how to reproduce it locally so I can investigate? I'm not that familiar with aspnetcore repo so I would need some guidance.

**Comment by BrennanConroy** [comment] 2020-01-27 23:59
Helix Queues
* `(Fedora.28.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-28-helix-09ca40b-20190508143249`
* `(Debian.9.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-a12566d-20190807161036`
* `(Debian.9.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm64v8-a12566d-20190807161036`

You can follow the [docs to build the repo](https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md), or at least the Kestrel part of it. And then run the test at https://github.com/dotnet/aspnetcore/blob/2cc333ac3013218a3985ecd0809b0c541cbe1f91/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs#L358

**Comment by anurse** [comment] 2020-02-03 22:03
@wfurt Can we get some clarity on whether this break (to throw a different exception in some circumstances) was intentional and will be documented as a breaking change? If so, we can just leave our reaction in place and there's no action here from our side, but if not we'd like to revert it.

**Comment by anurse** [comment] 2020-02-10 22:47
I presume this was intentional then. No further action from our side now, closing this.

**Closed by anurse** 2020-02-10 22:47 UTC
Labels: External, area-servers

**Comment by wfurt** [comment] 2020-02-10 22:58
Sorry for the delay. It may not matter of purpose if the tests but we should only throw IOException _or_ Authentication exception in case of mismatch - depending on the underlying implementation. However, updated tests look ok to me so no further action is needed IMHO.
