### ISSUE TITLE
Updated: Connection could not be started due to: Detected a connection attempt to an ASP.NET SignalR Server. This client only supports connecting to an ASP.NET Core SignalR Server.

### ISSUE THREAD

**Issue by rahul233343** [dotnet/aspnetcore#35059] opened 2021-08-05 05:45 UTC
**i am using these commands:**

$ git submodule update --init
$ ./submodules/vcpkg/bootstrap-vcpkg.sh
$ ./submodules/vcpkg/vcpkg install cpprestsdk boost-system boost-chrono boost-thread
$ mkdir build.release
$ cd build.release
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=../submodules/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CPPRESTSDK=true
$ cmake --build . --config Release

But Issue is coming in cmake command.

    

**$ ./submodules/vcpkg/vcpkg install cpprestsdk boost-system boost-chrono boost-thread**

    find_package(cpprestsdk CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE cpprestsdk::cpprest cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_boost_internal cpprestsdk::cpprestsdk_openssl_internal)

**$ cmake .. -DCMAKE_TOOLCHAIN_FILE=../submodules/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CPPRESTSDK=true**

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /home/user10/libraries/SignalR-Client-Cpp/submodules/vcpkg/installed/x64-linux/lib/libz.a (found version "1.2.11") 
-- Found OpenSSL: /home/user10/libraries/SignalR-Client-Cpp/submodules/vcpkg/installed/x64-linux/lib/libssl.a (found version "1.1.1d") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at submodules/vcpkg/installed/x64-linux/share/openssl/vcpkg-cmake-wrapper.cmake:14 (target_link_libraries):
  Cannot specify link libraries for target "OpenSSL::Crypto" which is not
  built by this project.
Call Stack (most recent call first):
  submodules/vcpkg/scripts/buildsystems/vcpkg.cmake:240 (include)
  /home/user10/cmake-3.8.0/Modules/CMakeFindDependencyMacro.cmake:55 (find_package)
  submodules/vcpkg/installed/x64-linux/share/cpprestsdk/cpprestsdk-config.cmake:11 (find_dependency)
  submodules/vcpkg/scripts/buildsystems/vcpkg.cmake:285 (_find_package)
  CMakeLists.txt:35 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/user10/libraries/SignalR-Client-Cpp/build.release/CMakeFiles/CMakeOutput.log".
See also "/home/user10/libraries/SignalR-Client-Cpp/build.release/CMakeFiles/CMakeError.log".

**Comment by BrennanConroy** [comment] 2021-08-05 05:48
Dupe of https://github.com/dotnet/aspnetcore/issues/33999

What cmake version do you have

**Comment by rahul233343** [comment] 2021-08-05 06:03
3.8.0

**Comment by rahul233343** [comment] 2021-08-05 06:11
But in ~/libraries/SignalR-Client-Cpp/ CMakeList.txt min required version is 3.5

**Comment by rahul233343** [comment] 2021-08-05 06:58
> Dupe of #33999
> 
> What cmake version do you have
now i am using cmake 3.21 and it worked.

**Comment by BrennanConroy** [comment] 2021-08-05 16:10
> Does this library support ASP.NET SignalR Server?

No, like the error log says "This client only supports connecting to an ASP.NET Core SignalR Server."

> But in ~/libraries/SignalR-Client-Cpp/ CMakeLists.txt min required version is 3.5

Yeah, we might want to bump that up, but it isn't the SignalR library that needs a higher cmake version, it's one of the dependencies so it's a little annoying.

**Comment by oscarchang** [comment] 2021-08-06 02:57
good

**Comment by BrennanConroy** [comment] 2021-08-09 18:20
Updated the cmake version required.

**Closed by BrennanConroy** 2021-08-09 18:20 UTC
Labels: area-infrastructure

**Comment by rahul233343** [comment] 2021-08-09 18:34
> Updated the cmake version required.

Does it also solve the connection problem?

> connection could not be started due to: Detected a connection attempt to an ASP.NET SignalR Server. This client only supports connecting to an ASP.NET Core SignalR Server.

**Comment by BrennanConroy** [comment] 2021-08-09 18:38
> Does it also solve the connection problem?

That's not a problem, the client only works for ASP.NET Core SignalR and will only ever work for ASP.NET Core SignalR.

ASP.NET SignalR and ASP.NET Core SignalR are separate projects and do not work together.
https://docs.microsoft.com/aspnet/core/signalr/version-differences?view=aspnetcore-5.0
