### ISSUE TITLE
Parameters from Static Server component to WebAssembly component fail when parameter type defined in separate project 

### ISSUE THREAD

**Issue by sentai77** [dotnet/aspnetcore#53013] opened 2023-12-26 13:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using a Blazor application structured into three projects (WebApp, WebApp.Client, and SharedLibrary), I encounter an unexpected behavior. The application consists of a static server-side rendered page (`/person-page`) in WebApp, which embeds an interactive WebAssembly component (`PersonDetails`) from WebApp.Client. This component is designed to receive a "Person" model (name and age) as a parameter, which is defined in a SharedLibrary project.

Upon navigating to `/person-page`, the interactive component fails to render and the following JavaScript exception is thrown:
`Error: One or more errors occurred. (The parameter 'Person' with type 'SharedLibrary.Person' in assembly 'SharedLibrary' could not be found.)`

Note that:
1. The render mode of the interactive component should be set to `@rendermode @(new InteractiveWebAssemblyRenderMode(prerender: false))`. If the component is prerendered or set to Interactive Auto, then it will initially render successfully, then fail when switching to Web Assembly.
2. In launch settings, `launchBrowser` should be set to false. The auto-launched browser does not raise the error for reasons I do not understand.

### Expected Behavior

The person object is serialized, passed to the web assembly component, deserialized correctly, then rendered.

### Steps To Reproduce

https://github.com/sentai77/BlazorParameterBug/tree/main

### Exceptions (if any)

blazor.web.js:1  Error: One or more errors occurred. (The parameter 'Person' with type 'SharedLibrary.Person' in assembly 'SharedLibrary' could not be found.)
    at Jn (marshal-to-js.ts:349:18)
    at Ul (marshal-to-js.ts:306:28)
    at dotnet.native.wasm:0x1faca
    at dotnet.native.wasm:0x1bf8b
    at dotnet.native.wasm:0xf172
    at dotnet.native.wasm:0x1e7e4
    at dotnet.native.wasm:0x1efda
    at dotnet.native.wasm:0xcfec
    at dotnet.native.wasm:0x440ad
    at e.<computed> (cwraps.ts:338:24)
callEntryPoint @ blazor.web.js:1
await in callEntryPoint (async)
ei @ blazor.web.js:1
await in ei (async)
Zr @ blazor.web.js:1
startWebAssemblyIfNotStarted @ blazor.web.js:1
resolveRendererIdForDescriptor @ blazor.web.js:1
determinePendingOperation @ blazor.web.js:1
refreshRootComponents @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
setTimeout (async)
rootComponentsMayRequireRefresh @ blazor.web.js:1
onDocumentUpdated @ blazor.web.js:1
Ji @ blazor.web.js:1

### .NET Version

8.0.100

**Comment by javiercn** [comment] 2023-12-26 13:53
@sentai77 thanks for contacting us.

This is a known issue that was fixed recently. A fix will be available in 8.0.1 in a future release. As a workaround you can use `GC.KeepAlive(typeof(Person))` in the webassembly project to make sure that the assembly is loaded into memory by the time we try to deserialize it.

Dupe of https://github.com/dotnet/aspnetcore/issues/52129

**Closed by javiercn** 2023-12-26 13:53 UTC
Labels: area-blazor
