### ISSUE TITLE
IIS does not recover from a broken web.config in v6 hosting bundle where it used to in v3 and v5

### ISSUE THREAD

**Issue by RichardHynes** [dotnet/aspnetcore#40194] opened 2022-02-14 09:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In v6 hosting bundle, IIS does not automatically restart the website when it detects the change to the web.config, **_if a previous change caused an exception_**. However, in v3 and v5 IIS would restart the site if a change to the web.config was made regardless of previous changes. 

### Expected Behavior

I update some IIS servers running .Net Core websites without remote access to the IIS server (RDP or PS). However, I do have remote access to the file system. 

In .Net Core 3 & 5 I would take a website offline by editing the web.config and renaming the ‘processPath’ to ‘filename..OFF’ , IIS would shut down the site, I copy in the updated files, edit the web.config, rename the ‘processPath’ back to the correct filename, IIS detects the change and starts up the site. 
 
In v6 this no longer works, and I don’t know if that’s intentional or not (see below).

Alternatively, if I rename the web.config to web.config.off, IIS shuts down the site as normal, I update the files, rename the web.config back, IIS detects the change and starts up the site as normal.

The main difference between the two approaches can be seen in the event viewer. In the first where I ‘break’ the web.config IIS adds an info line to the event viewer to say the site has shutdown (detecting the config change) followed by two exceptions to say the renamed processPath could not be found. In the second method where I rename the web.config I still get an info message to say the site has shut down but no error messages. 

### Steps To Reproduce

'Break' the IIS Site by editing the web.config and changing the processPath to an invalid value.  Allow IIS to shutdown, fix the web.config by renaming the processPath back to a valid path. In v3 and v5 the site would come back up automatically, in v6 it does not come back up. 

### .NET Version

6.0.2

**Comment by HaoK** [comment] 2022-03-16 19:44
I tried this just now and I see the same behavior in 6.0 as 5.0:

After web.config is modified, you get an in-process error 500 page, with an event log saying something like

```
An ISAPI reported an unhealthy condition to its worker process. Therefore, the worker process with process id of '30668' serving application pool 'WebApplication' has requested a recycle.
```

After editing the web.config to be fixed, the error is just a generic 503 like so:

![image](https://user-images.githubusercontent.com/6537861/158676708-ff057c6a-b32d-4b4b-b200-e49d10535ef5.png)

An explicit iisreset at this point will make things work again.

Since this isn't a regression from 5.0, this seems like reasonable behavior to me and recommend we close this as won't fix

**Comment by RichardHynes** [comment] 2022-03-16 20:07
Thank you Hao for looking into this, I tried this repeatedly and could not get it to break in 5.0, but would consistently break in 6.0 I’m not sure why you are getting different results. 

All that aside I would request that you please consider this issue more before you close this as a won’t fix. 
In an enterprise environment, we must use a ‘break glass’ process to request a one-time login to an IIS server to restart IIS because the site won’t come back up on its own even when the site is no longer in a fault state. IIS is fundamentally more _fragile_ now with this issue than it was previously and this behavior feels like a big step backward. 

Thanks,
Richard

**Comment by RichardHynes** [comment] 2022-03-16 20:38
Hi Hao, to be honest, I have not tried app_offline, I got used to a way that worked and never looked for a better alternative. I will give that a try!.
Thanks again, 
Richard

**Comment by HaoK** [comment] 2022-03-16 20:39
Sounds good

**Closed** 2022-03-16 20:38 UTC
Labels: area-runtime
