### ISSUE TITLE
Blazor WASM PWA integrity errors after upgrading from .NET Core 3.1 to .NET 6.

### ISSUE THREAD

**Issue by acamlibe** [dotnet/aspnetcore#39252] opened 2021-12-31 15:11 UTC
Hi, I have a PWA application that I have developed internally for my company. I recently upgraded it to .NET 6 by creating a new project and moving everything over.

When I went to deploy this last week, everything went wrong. I was getting integrity errors everywhere, and some of the users I had testing for me also had the same issues. The app was able to update its service worker assets when you reloaded with a clear cache, but doing a reload right after would bring the version back to the old one, and eventually just broke the application. I had to revert back to the .NET Core 3.1 version temporarily.

The way I have my PWA setup, it should show an "Update Now" button when I do publish a new version. Normally it's instant, and has worked really well on .NET Core 3.1, but for some reason, it did not show up that time.

I haven't tried since, but what I did was run a PowerShell script to check the hashes found in the service-worker-assets.js file with the calculated hashes, and everything matched for all the files in that failed deployment. I also looked at the blazor.boot.json and the hashes seemed to match there as well.

I can't really tell what happened. I heard that one way to fix this was to delete the obj and bin folders before publishing, but I haven't tried that yet. I don't want to publish until I know for sure what went wrong that day.

And just for more information, here's my deployment process:
1. Publish to folder output
2. Move files over to our two web servers (load balanced), and restart the app pool on IIS.
3. The expected outcome here would be that the next time the user reloads or opens the app, they would get an "Update Now" button at the bottom of their page. This did not happen though.

And just FYI, I use the default web.config that comes with the publish step. I haven't messed around with configuring it.

Any ideas how I can better assess what went wrong here? I believe the browser was holding onto old cache somehow?

Here's the service.worker.published.js file:
```
self.importScripts('./service-worker-assets.js');
self.addEventListener('install', event => event.waitUntil(onInstall(event)));
self.addEventListener('activate', event => event.waitUntil(onActivate(event)));
self.addEventListener('fetch', event => event.respondWith(onFetch(event)));

const cacheNamePrefix = 'offline-cache-';
const cacheName = `${cacheNamePrefix}${self.assetsManifest.version}`;
const offlineAssetsInclude = [/\.dll$/, /\.pdb$/, /\.wasm/, /\.html/, /\.js$/, /\.json$/, /\.css$/, /\.woff$/, /\.png$/, /\.jpe?g$/, /\.gif$/, /\.ico$/];
const offlineAssetsExclude = [/^service-worker\.js$/];

const notifyNewVersion = () => {
    const bc = new BroadcastChannel('blazor-channel');

    bc.postMessage('new-version-found');

    bc.onmessage = function (message) {
        if (message && message.data == "skip-waiting") {
            self.skipWaiting();
            bc.postMessage("reload-page");
        }
    }
}

async function onInstall(event) {
    console.info('Service worker: Install');

    // Fetch and cache all matching items from the assets manifest
    const assetsRequests = self.assetsManifest.assets
        .filter(asset => offlineAssetsInclude.some(pattern => pattern.test(asset.url)))
        .filter(asset => !offlineAssetsExclude.some(pattern => pattern.test(asset.url)))
        .map(asset => new Request(asset.url, { integrity: asset.hash }));
    await caches.open(cacheName).then(cache => cache.addAll(assetsRequests));

    notifyNewVersion();
}

async function onActivate(event) {
    console.info('Service worker: Activate');

    // Delete unused caches
    const cacheKeys = await caches.keys();
    await Promise.all(cacheKeys
        .filter(key => key.startsWith(cacheNamePrefix) && key !== cacheName)
        .map(key => caches.delete(key)));
}

async function onFetch(event) {
    let cachedResponse = null;
    if (event.request.method === 'GET') {
        // For all navigation requests, try to serve index.html from cache
        // If you need some URLs to be server-rendered, edit the following check to exclude those URLs
        const shouldServeIndexHtml = event.request.mode === 'navigate';

        const request = shouldServeIndexHtml ? 'index.html' : event.request;
        const cache = await caches.open(cacheName);
        cachedResponse = await cache.match(request);
    }

    return cachedResponse || fetch(event.request);
}
```

**Comment by acamlibe** [comment] 2021-12-31 15:45
Also left out one detail. I did change one thing going from 3.1 to 6. I had added this to my csproj:
```
<PropertyGroup>
  <InvariantGlobalization>true</InvariantGlobalization>
</PropertyGroup>
```

Not sure if that has anything to do with it, but I've removed that line since.

**Comment by mkArtakMSFT** [comment] 2022-01-03 17:16
Thanks for contacting us.
We see many people run into integrity failures with their PWA applications. We've documented some ways to troubleshoot those but it seems those were not good enough. We will reevaluate the [current doc article](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#resolve-integrity-check-failures) and see how we can improve it.

If you haven't yet, can you please review the docs and see whether the current writeup will help you?

In the meantime, your issue is most probably caused by incorrect cache headers configuration. ASP.NET Core configures `cache-control:no-cache` header. Make sure that configuration is in place.

**Comment by acamlibe** [comment] 2022-01-04 14:25
How can I verify that? When I look at the network tab, I see almost all the assets coming from memory cache and disk cache.

**Comment by acamlibe** [comment] 2022-01-04 16:29
I think I just figured it out.

The service-worker.js is getting the latest version from the deployment, but the service-worker-assets.js file is served from disk cache. It contains hashes of old files.

How can I ensure that the service-worker-assets.js file is served fresh on IIS?

**Comment by devgitprojects** [comment] 2022-02-07 12:56
@acamlibe Looks like this is solution [.](https://github.com/dotnet/aspnetcore/issues/39016#issuecomment-998604247) I've just tested and do not see disc caching for service-worker-assets.js file

**Comment by mkArtakMSFT** [comment] 2022-10-11 17:22
@guardrex can you please include a note about the solution pointed out in the above comment in the docs? Thanks!

>@acamlibe Looks like this is solution https://github.com/dotnet/aspnetcore/issues/39016#issuecomment-998604247 I've just tested and do not see disc caching for service-worker-assets.js file

**Comment by guardrex** [comment] 2022-10-11 17:57
@mkArtakMSFT ... It looks like @SteveSandersonMS already took a 🔪 at fixing this problem in ...

https://github.com/dotnet/aspnetcore/pull/20098 (coming off of the issue discussion at https://github.com/dotnet/aspnetcore/issues/19882).

I don't have enough understanding of what's not working (the need for the workaround) in order to document anything. I'll leave the docs issue on standby until I hear back. 👂

**Comment by guardrex** [comment] 2022-10-11 18:09
It's also possible that the **Other issue** part of the issue at ...

https://github.com/dotnet/aspnetcore/issues/19882#issue-582382357

> We should also change the service worker registration logic ...

... was just missed on the PR ... not implemented ... lost in the process.

Thus far the doc addition states ...

> If you must prevent the browser from fetching \`service-worker-assets.js\` from its HTTP cache, for example to resolve temporary integrity check failures when deploying a new version of the service worker, update the service worker registration in \`wwwroot/index.html\` with \[\`updateViaCache\`](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/updateViaCache) set to 'none':
>
> \`\`\`html
> \<script>
>   navigator.serviceWorker.register('/service-worker.js', {updateViaCache: 'none'});
> \</script>
> \`\`\`

**Comment by guardrex** [comment] 2022-10-17 12:22
@mkArtakMSFT ... I'm still stuck on wrapping up the docs coverage for this because ...

* I can't tell if Steve already fixed (or sought to fix) the underlying problem. I guess **not**, given that you're pitching it for coverage now and his PR was back in 2020. I cross-link what I found here in the last two comments.
* Is the use of `updateViaCache: 'none'` meant to be a permanent change to apps, or only temporary (e.g., during a period where a new version of the service worker is being rolled out by a dev)?

Thus far, the doc draft updates are on https://github.com/dotnet/AspNetCore.Docs/pull/27248.

**Comment by javiercn** [comment] 2022-10-19 10:30
I think we should change our templates to do `serviceWorker.register('...', { updateViaCache: 'none' })`

**Comment by javiercn** [comment] 2022-10-19 10:32
Closing this as we have filed a separate issue to track the work we want to do to address this situation.

**Closed by javiercn** 2022-10-19 10:32 UTC
Labels: Docs, area-blazor, Priority:2, feature-pwa, feature-integrity-check
