### ISSUE TITLE
[SignalR] retryContext in withAutomaticReconnect to expose more http context

### ISSUE THREAD

**Issue by vicancy** [dotnet/aspnetcore#37439] opened 2021-10-11 07:50 UTC
### Is your feature request related to a problem? Please describe.
When using Azure SignalR customer uses JWT token to connect, there is a chance when the reconnect happens when the token is expired. In such case, reconnect always returns 401. When withAutomaticReconnect is enabled, the client still retries for the defined time although such 401 is a non-retryable error.
![image](https://user-images.githubusercontent.com/668244/136752374-6a19eb82-707d-4c7b-870d-5df5c4e0af46.png)

### Describe the solution you'd like
Is it possible to provide a way to define some non-retryable errors? If retryContext can expose more HTTP-context related error detail, for example, error code 401, the customer can stop "reconnect" and restart the negotiation with his app server **immediately**.

**Comment by rafikiassumani-msft** [comment] 2022-01-25 21:56
dupe of https://github.com/dotnet/aspnetcore/issues/39079

**Closed** 2022-01-25 21:57 UTC
Labels: area-signalr
