### ISSUE TITLE
Controller QueryParameters not getting UrlDecoded

### ISSUE THREAD

**Issue by tsproesser** [dotnet/aspnetcore#22328] opened 2020-05-28 18:56 UTC
I'm not pretty sure if the behavior just changed with the latest release - almost can't believe it. But right now queryparameters aren't automatically url decoded anymore:

```
[HttpGet("{testparam}")]
public IEnumerable<WeatherForecast> Get(string testparam)
{
	//testparam not url decoded!
	return null;
}
```

Can be tested with any DotNet Core 3.1.3 version

**Comment by mkArtakMSFT** [comment] 2020-06-01 17:01
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/11544

**Closed by mkArtakMSFT** 2020-06-01 17:01 UTC
Labels: area-mvc, investigate
