### ISSUE TITLE
Hotreload not working with .cshtml files

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/aspnetcore#38809] opened 2021-12-03 14:52 UTC
In a .NET 6 Core Web app mixed with Blazor components, Hotreload is not working fully. If I update anything on a Blazor component (.razor file), the browser updates in real time. If I update a .cshtml file, Hotreload happens, but changes are not updated in the browser. I have to refresh.

Is this behavior known?  Any solution?

**Comment by pranavkm** [comment] 2021-12-03 17:06
Does your app reference the RuntimeCompilation package? With dotnet-watch, we let runtime compilation take over since they're both designed to solve the same problem.

**Comment by HybridSolutions** [comment] 2021-12-03 17:16
> 

What is the full name of the package?

**Comment by pranavkm** [comment] 2021-12-03 17:26
Yup, that's the one.

**Comment by HybridSolutions** [comment] 2021-12-03 19:01
> Yup, that's the one. You could remove the package reference if you are currently only using it during development.

Installed the package, re-compiled and ran the project. Changing some text in my .cshtml file did nothing after save. 
Any ideas?

**Comment by Aquaritek** [comment] 2021-12-04 04:53
Not much help here, but I have the same issue. Running on latest VS 2022 Preview with a brand new Blazor WASM app using the built-in templates. Selected all the fixins except docker support.

If I edit server-side code such as API controllers. Hot reload works wonders. If I edit Identity Pages they hot reload as well and automatically refresh from browser-link. If I edit literally anything on the Client side. It'll recompile, hot-reload, I get the checkbox in the browser, but the application does not change. 

I have to stop, rebuild and start the application again running from the server project in this case for client-side changes to take effect.

Secondarily If I publish changes to the hosting server. None of the active clients get updated apps without doing a full browser history clean yes that's right a full browser history clean. On mobile devices that's a real PITA definitely cannot take this application I'm working on to a production environment.

I love Blazor so much though it's hard to be mad at the end of the day ;).

**Comment by SteveSandersonMS** [comment] 2021-12-06 17:51
@pranavkm Since they aren't using runtime compilation, do you have any other suggestions on what might be wrong here, or do we need to investigate?

**Comment by Aquaritek** [comment] 2021-12-06 22:33
@SteveSandersonMS I think this has something to do with the browser instance reloading a cached version of the application. 

I have been working on this for several days and cannot get browsers (Edge, Chrome, Chromium, or Safari) to refresh the application on publish to my development server. 

When you build and run from VS a completely cleaned instance of Edge or Chrome get's started that has no cached version of the application. I think this is where the issue actually lies. I do not understand the core architecture in that area though.

**Comment by mkArtakMSFT** [comment] 2021-12-07 17:42
> @SteveSandersonMS I think this has something to do with the browser instance reloading a cached version of the application.
> 
> I have been working on this for several days and cannot get browsers (Edge, Chrome, Chromium, or Safari) to refresh the application on publish to my development server.
> 
> When you build and run from VS a completely cleaned instance of Edge or Chrome get's started that has no cached version of the application. I think this is where the issue actually lies. I do not understand the core architecture in that area though.
> 
> I do wonder though, if this has something to do with the application being setup as a PWA and the default behavior of a browser is to active any site changes after all iterations of that site have been terminated. Thoughts on this would be nice.

Hi @Aquaritek. The issue you report seems different. Please file a separate issue so that we track it separately.

**Comment by mkArtakMSFT** [comment] 2021-12-07 17:44
@HybridSolutions can you see any errors in the browser console?
Also, please share any activity from the network tab that is initiated by `aspnetcore-browser-refresh.js`.

**Comment by mkArtakMSFT** [comment] 2021-12-07 17:45
Also, a repro project (hosted as a public GitHub repo) would help.

**Comment by HybridSolutions** [comment] 2021-12-07 19:10
> @HybridSolutions can you see any errors in the browser console? Also, please share any activity from the network tab that is initiated by `aspnetcore-browser-refresh.js`.

This issue is easy to find in stackoverflow site. A lot of people having the same issue. Here's a topic where I'm trying to help out: [Link](https://stackoverflow.com/questions/69778272/unable-to-hot-reload-on-visual-studio-2022/70174681?noredirect=1#comment124126941_70174681)

I can't make my project available for you to test because is proprietary but the issue is easily replicated.
1. Make a new .NET 6 "ASP.NET Core Web App" with Razor pages. 
2. Configure it to also support Blazor.
3. Run it and try to change .chtml files. I have to refresh the browser to see changes although I can see the checkmark in the top left corner.
4. Change a Blazor component. I can see changes immediately. 

In Console I only get [this ](https://pasteboard.co/bmnBrDrP9oxo.png)during my above tests. No errors.

Debugging aspnetcore-browser-refresh.js, as soon as I save changes to a .cshtml file, the function aspnetCoreHotReloadApplied() gets hit but although I don't have any Blazor component in the page, the line window.Blazor is true, so **location.reload();** is skipped and instead it always calls **notifyHotReloadApplied();**. That's the function that shows the checkmark svg. The browser reload function never gets called and for razor pages content, I guess **location.reload();** must be called to see any changes.  

[Image of script debug](https://pasteboard.co/7EaKPwgvGohI.png)

May this be the reason for not seeing changes in razor pages? Razor pages are considered blazor content so it does not update as would normally would using **location.reload();**.

**Comment by pranavkm** [comment] 2021-12-08 17:05
@HybridSolutions thanks for the detailed writeup. Our current heuristic chooses to not refresh the browser for code changes if Blazor is running in the app. We had previously tried relying on the file that changed to make a determination but it gets tricky and inconsistent if there's more than one being updated as part of a hot reload update. 

We're working on producing a write up for all these gotchas in our documentation, hopefully that helps here.

**Comment by HybridSolutions** [comment] 2021-12-08 17:12
But will there be a solution in these cases?

**Comment by pranavkm** [comment] 2021-12-08 17:26
@HybridSolutions for the immediate future we're going to rely on users having to manually refresh the browser in this particular case. For a longer term, we were looking at building more generalized rules about how to process changes to individual file types that can be shared by VS and dotnet-watch rather than baking in details about .cshtml, Blazor etc.

**Comment by HybridSolutions** [comment] 2021-12-08 20:11
> @HybridSolutions for the immediate future we're going to rely on users having to manually refresh the browser in this particular case. For a longer term, we were looking at building more generalized rules about how to process changes to individual file types that can be shared by VS and dotnet-watch rather than baking in details about .cshtml, Blazor etc.

That's ok for me. being able to see changes even by pressing F5 is great! .NET 6 and VS 2022 is turning into a wonderful development environment!

**Comment by dotnetshadow** [comment] 2021-12-19 06:00
I had a similar issue, I did the following and hot reload worked on my .cshtml files again
```xml
<ItemGroup>
	  <!-- extends watching group to include *.cshtml files -->
	  <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
  </ItemGroup>
```

**Comment by HybridSolutions** [comment] 2021-12-21 00:32
> I had a similar issue and my .cshtml worked once I did the following:
> 
> ```
> <ItemGroup>
> 	  
> 	  <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
>   </ItemGroup>
> ```
> 
> I needed to do this from a converted project, when I create a new project it seems to work without the need to do the above. I wonder why the above is necessary?

This does not work with the issue presented here since as I explained, the problem is on the script that does not invoke the refresh function location.reload(); when using Razor pages + Blazor in a project.

**Comment by sbsw** [comment] 2022-01-14 04:20
Not sure if this is off-topic. I submitted #39508 about this same issue with a vanilla ASP.Net Core MVC app. **No Blazor involved.**

**Steps To Reproduce**

- Using Visual Studio Professional 2022 (64-bit) Version 17.0.5 
- Create new ASP.NET Core Web App targeting net5.0
- F5
- Open index.cshtml, change the welcome text, and save the changes.

**Expected Behavior**
Welcome text changes

**Actual Behavior**
Welcome text does not change

**Other things I've tried**

- Set Hot Reload on File Save (under the Hot Reload button on the VS toolbar)
- Click the Hot Reload button on the VS toolbar
- Reload the web page in the browser

**Comment by SteveSandersonMS** [comment] 2022-01-14 16:42
@sbsw I'm afraid hot reload requires .NET 6 (so, target `net6.0`).

**Comment by programad** [comment] 2022-01-17 03:17
I have the same issue on my **asp.net mvc core 5** app being _migrated_ to **asp.net core 6.0**. (no blazor involved).

It just doesn't work.

I make the change to a cshtml file, nothing happens (no matter what hot reload button setting o do). When trying to refresh the page on the browser, get the following error: 
![image](https://user-images.githubusercontent.com/1039567/149702834-ba9462c9-5476-403f-b924-3d0db160af55.png)

**Comment by szalapski** [comment] 2022-02-24 19:11
This seems not to be fixed in SDK 6.0.200--when I change the plain HTML markup in a .razor file, I still get:

```
watch : File changed: C:\...\MyComponent.razor.
watch : No hot reload changes to apply.
```

With --verbose, I get:

```
watch : File changed: C:\...\MyComponent.razor.
watch : No deltas modified. Applying changes to clear diagnostics.
watch : Received 1 from browser in [Count: 1, MessageType: Binary, EndOfMessage: True].
watch : No hot reload changes to apply.
watch : Hot reload change handled in 5902.7638ms.
```

Can anyone help?

**Comment by alex-jitbit** [comment] 2022-03-28 19:43
I also have a .NET 5 app migrated to .NET 6 and hot reload is not working not for me, not for any of my coworkers **even after refreshing the page in browser"*. I filed an issue in "Visual Studio Feedback" but no help from Microsoft.

**Comment by Jbechler2** [comment] 2022-06-03 15:35
> I also have a .NET 5 app migrated to .NET 6 and `.cshtml` hot reload is not working neither for me, not for any of my coworkers **even after refreshing the page in browser**. I filed an issue in "Visual Studio Feedback" but no help from Microsoft.
> 
> UPD: The "visual studio feedback" website just closed my issue without providing any workaround.

I'm experiencing this as well. Just upgraded my project to from .NET 5 to .NET 6 and now any changes made to a '.cshtml' are not visible on the page until I stop and restart debugging.

**Comment by ellinge** [comment] 2022-06-16 09:48
> I had a similar issue and my .cshtml worked once I did the following:
> 
> ```
> <ItemGroup>
> 	  
> 	  <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
>   </ItemGroup>
> ```
> 
> I needed to do this from a converted project, when I create a new project it seems to work without the need to do the above. I wonder why the above is necessary?

Thank you! Worked for me having a .NET 6 project, no blazor though. Hot reload would work once but then "No code changes found" after just removing the samt text that just was added. A restart of session was required to get it working again.

**Comment by alex-jitbit** [comment] 2022-07-04 07:13
> I had a similar issue and my .cshtml worked once I did the following:
> 
> ```
> <ItemGroup>
> 	  
> 	  <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" />
>   </ItemGroup>
> ```

Didn't work for at all. As long as all the other workaround. Hot reload is still not functioning in VS 2022 in my .NET 6 project converted from .NET 5.

**Comment by dotnetshadow** [comment] 2022-07-13 08:46
Just a warning an unintended consequence of using this snippet is when you you add a new .chtml file to your solution the build action defaults to None. Not sure why it's doing that.
````
 <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" /> 
 ``` 
 
 Someone else had the exact same problem:
 https://stackoverflow.com/questions/72909569/in-net-6-mvc-view-is-404-not-found-unless-i-manually-change-the-file-type-to

**Comment by lwpinion** [comment] 2022-10-12 21:12
Are there any updates on this? We're encountering this issue on a project that we're migrating to .NET 6. I've double-checked and our dependencies are on .NET 6 as well.


> Just a warning about an unintended consequence of using this snippet. When you you add a new .chtml file to your solution the build action defaults to None. Not sure why it's doing that.
> 
> ```
>  <Watch Include="**\*.cshtml" Exclude="node_modules\**\*;**\*.js.map;obj\**\*;bin\**\*" /> 
> ```
> 
> Someone else had the exact same problem: https://stackoverflow.com/questions/72909569/in-net-6-mvc-view-is-404-not-found-unless-i-manually-change-the-file-type-to

@dotnetshadow Aside from the unintended consequence, is this still a viable workaround?

**Comment by alex-jitbit** [comment] 2022-10-12 22:17
This is what helped resolve the issue: https://github.com/dotnet/aspnetcore/issues/43910

**Comment by mkArtakMSFT** [comment] 2022-10-19 17:40
> @HybridSolutions for the immediate future we're going to rely on users having to manually refresh the browser in this particular case. For a longer term, we were looking at building more generalized rules about how to process changes to individual file types that can be shared by VS and dotnet-watch rather than baking in details about .cshtml, Blazor etc.

@BillHiebert , @tmat do you guys know who would be the owner of this action? Where does this logic lie in today?

**Comment by tmat** [comment] 2022-10-19 18:00
@mkArtakMSFT I think we have 3 kinds of files:
1) .cs/.vb files
2) files that Razor SDK uses as inputs to the source generator (.razor, .cshtml)
3) .css and other content

[1] and [2] are handled the same way - it all goes through Roslyn. [3] are handled separately.

**Comment by tmat** [comment] 2023-02-24 19:36
I validated that repro https://github.com/dotnet/aspnetcore/issues/38809#issuecomment-988195666 works without issues when using .NET 6.0.406 and 7.0.200.

Re https://github.com/dotnet/aspnetcore/issues/38809#issuecomment-1012738824:
.NET 5 does not support Hot Reload. 

I also tried creating .NET 5 Web App and changing TFM to net6.0. Hot Reload works.

If there is any scenario I missed that still does not work with the latest .NET 7 SDK, please file an issue with detailed repro steps.

**Closed by tmat** 2023-02-24 19:36 UTC
Labels: bug, area-blazor, triaged, feature-hot-reload

**Comment by LongBrandon** [comment] 2023-03-04 20:55
I know this issue is closed.  But I'm leaving this here in case it helps someone out.  In my case I had the following in my Blazor Server project file.  I don't remember making this change but perhaps I did when migrating from dotnet 5 to dotnet 6. 

  <PropertyGroup>
    <UseRazorSourceGenerator>false</UseRazorSourceGenerator>
  </PropertyGroup>

If I remove this property from the .proj file my hot reload now works.
