### ISSUE TITLE
chunkingcookiemanager leaks unused chunks

### ISSUE THREAD

**Issue by patrick-hampton-avalara** [dotnet/aspnetcore#4639] opened 2018-11-12 17:47 UTC
There seems to be a bug in Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager when used in conjunction with CookieAuthentication.  What I've seen is that as the size of the Authentication cookie changes the number of chunks needed to the accommodate the cookie data will change as well.  If the number of cookies needed decreases, then chunks that are no longer needed are not being cleaned up.  

Normally this isn't a big deal, but I'm currently running in a system that has a hard limit on the header size of 10240 bytes.  The specify scenario I'm running into has the Authentication cookies going from 2 chunks (3 total cookies) to 1 chunk (1 cookie).  This has the added bonus of replacing the value in the cookie that previously stored the chunk count (really small), to now storing the entire Authentication Ticket (relatively large), in turn nearly doubling the amount of header space consumed by the Authentication cookie.

It seems like it could be beneficial to have ChunkingCookieManager  expire these "vestigial" as it's setting the new chunks on the response.

**Comment by MoonStorm** [comment] 2020-02-28 15:59
It's more serious than simply leaking cookies. I easily triggered this bug when attempting an SSO with Azure via OpenId Connect. All you need is to add a couple more claims in the token configuration in the Azure Portal for the registered app. The external claims are then passed to the cookie auth provider which refreshes the auth cookie but unfortunately isn't removing the extra unused chunks. What will happen next is getting BAD REQUEST errors due to the size of the header. 

The issue is exacerbated by the fact that the ChunkingCookieManager uses the first cookie to just store the number of chunks, as it pushes the actual content of the cookie further down starting with the C1 chunk. So when the cookie gets replaced and the new content isn't more than 4k but close, you end up with two big 2x4k cookies.

**Comment by gurumurthyjv** [comment] 2023-11-21 05:32
Hi @MoonStorm and @patrick-hampton-avalara ,

Even I have the same issue, with Azure B2C authentication,  getting 400 Bad Request, and later on no pages from website loads, if we clear cache and cookies, site starts loading. we have an HA proxy and Akamai cache redirects configured to our website,.

What's the solution for this ? will increasing the header size from Akamai side would fix the issue ? or do we need to implement the custom cookie manager as per @patrick-hampton-avalara comment.

please suggest your inputs, which can help me to get out of the 400 Bad request issue after B2C auth.

Thanks and appreciate your response.

Thanks,
Gurumurthy JV

**Comment by Tratcher** [comment] 2023-11-21 23:40
@gurumurthyjv take a look a this: https://github.com/dotnet/aspnetcore/pull/52272

That class can be copied into your project and used on older versions, though the older you go the more you'd have to adapt the APIs called.

**Comment by gurumurthyjv** [comment] 2023-11-22 04:22
Hi @Tratcher ,

Thanks for your response, as per #52272 , I have copied the file src/Shared/ChunkingCookieManager/ChunkingCookieManager.cs and renamed it with CleanChunkingCookieManager.cs into my project and used this in my startup.cs, all works in my local, but after deploying to Azure App, which has Akamai and HA proxy, its not working. getting the same 400 Bad Request.

my startup.cs config as per below.

` services.AddAuthentication(options =>
 {
     options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
     options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
     options.DefaultAuthenticateScheme = OpenIdConnectMemberExternalLoginProviderOptions.SchemeName;
     options.DefaultSignInScheme = "Cookies";
 })
  .AddCookie(options =>
  {
      // add an instance of the patched manager to the options:
      options.CookieManager = new CleanChunkingCookieManager();

      options.Cookie.HttpOnly = true;
      //options.Cookie.SameSite = SameSiteMode.Lax;
      options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
      options.Cookie.Path = "/";
  });`

Let me know if anything wrong here.

Thanks,
Gurumurthy JV

**Comment by Tratcher** [comment] 2023-11-22 19:02
Did you clear your old cookies first? This won't fix existing cookie problems, it should only prevent new ones.

**Comment by gurumurthyjv** [comment] 2023-11-23 03:26
Hi @Tratcher ,

Yes, Always I used to test with new incognito tab, but no luck.

Even the breakpoint in my local for below config from startup.cs in not triggering, is this correct way of configuring the cookie and authentication ? I see there is method 'DeleteChunks' is being called from AppenCookie(), this not at all triggering with local breakpoint.

`.AddCookie(options =>
{
options.CookieManager = new CleanChunkingCookieManager();
options.Cookie.HttpOnly = true;
options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
options.Cookie.Path = "/";
});`

Thanks,
Gurumurthy JV

**Closed** 2023-11-29 18:45 UTC
Labels: bug, area-auth, affected-few, severity-minor, help candidate

**Comment by MoonStorm** [comment] 2023-11-29 19:25
@Tratcher took you only 6 years 👍
