### ISSUE TITLE
'Failed to instantiate module ui.router' in dotnet core 3.1

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/aspnetcore#28974] opened 2021-01-02 10:14 UTC
I updated app from 2.2 to 3.1, but facing issue in docker, but it is working fine without docker, before migration it was working fine in both docker and with docker environments. The error is given below. Please help me to solve this issue

` [$injector:modulerr] Failed to instantiate module thingtrax due to:
Error: [$injector:modulerr] Failed to instantiate module ui.router due to:
Error: [$injector:nomod] Module 'ui.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
`
![image](https://user-images.githubusercontent.com/23011613/103455215-2bbc9b00-4ce3-11eb-810b-11d564b7a88b.png)

**Comment by pranavkm** [comment] 2021-01-03 21:12
I just tried this using a vanilla 3.1 template and I'm unable to reproduce the problem inside a docker container. It's fairly likely that one of your migration steps wasn't correct. I'd suggest creating a new 3.1 project and using it as a way to compare your migrated project to verify you're not missing any steps. 

I'm closing this as this issue is not specific to ASP.NET Core. If you think otherwise, please feel free to reopen if you think otherwise. A minimal app that reproduces the problem would help.

**Closed by pranavkm** 2021-01-03 21:12 UTC
Labels: area-mvc, feature-spa
