### ISSUE TITLE
PlatformNotSupportedException when navigating from Counter to Home page with multithreading enabled

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#54317] opened 2024-03-02 17:07 UTC
Repro steps:

- Install .NET 9 Preview 2 with the wasm-tools workload
- Create a Blazor Web App with WebAssembly interactivity enabled per component
- Set WasmEnableThreads to true in the client project
- Set up cross-origin isolation in the server project: `ServeMultithreadingHeaders = true`
- Run the app
- Navigate from the home page to the counter page (which loads WebAssembly)
- Verify that the counter works
- Navigate back to the home page
- Check the browser dev console

Expected result: Navigation without exception
Actual result:
![image](https://github.com/dotnet/aspnetcore/assets/1874516/0f998643-a8c8-4b2e-b132-526602b9dae3)
And WebAssembly interactivity is now broken for the app.

@pavelsavara

**Comment by SteveSandersonMS** [comment] 2024-03-05 17:40
There are going to be lots of things broken with multithreading right now so it's not necessary to file issues for them individually, at least until we get to the point where we largely think things should work. But thanks for filing it :)

**Comment by pavelsavara** [comment] 2024-03-05 17:55
It would be good to improve the stack trace. 
Because we don't know what was calling the blocking `.Wait`.

**Comment by mkArtakMSFT** [comment] 2024-03-08 21:20
Closing as a dupe of https://github.com/dotnet/aspnetcore/issues/54365

**Closed by mkArtakMSFT** 2024-03-08 21:20 UTC
Labels: area-blazor
