### ISSUE TITLE
JsonStringEnumConverter missing in Blazor WASM release build

### ISSUE THREAD

**Issue by chA0s-Chris** [dotnet/aspnetcore#20720] opened 2020-04-10 11:12 UTC
### Describe the bug
When using the `JsonConverterAttribute` with `JsonStringEnumConverter` on an enum property to serialize the enum value to string, everything works fine in **debug builds**. When I switch to **release** for deployment this exception will appear when using `HttpClient.GetJsonAsync<T>`:

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute (System.Text.Json.Serialization.JsonConverterAttribute converterAttribute, System.Type typeToConvert, System.Type classTypeAttributeIsOn, System.Reflection.PropertyInfo propertyInfo) <0x29a3170 + 0x0007c> in <filename unknown>:0
  at System.Text.Json.JsonSerializerOptions.DetermineConverterForProperty (System.Type parentClassType, System.Type runtimePropertyType, System.Reflection.PropertyInfo propertyInfo) <0x22657c0 + 0x00048> in <filename unknown>:0
  at System.Text.Json.JsonClassInfo.CreateProperty (System.Type declaredPropertyType, System.Type runtimePropertyType, System.Type implementedPropertyType, System.Reflection.PropertyInfo propertyInfo, System.Type parentClassType, System.Text.Json.Serialization.JsonConverter converter, System.Text.Json.JsonSerializerOptions options) <0x22647d0 + 0x00048> in <filename unknown>:0
  at System.Text.Json.JsonClassInfo.AddProperty (System.Type propertyType, System.Reflection.PropertyInfo propertyInfo, System.Type classType, System.Text.Json.JsonSerializerOptions options) <0x22642e0 + 0x00072> in <filename unknown>:0
  at System.Text.Json.JsonClassInfo..ctor (System.Type type, System.Text.Json.JsonSerializerOptions options) <0x224f7d0 + 0x00168> in <filename unknown>:0
  at System.Text.Json.JsonSerializerOptions.GetOrAddClass (System.Type classType) <0x22448a8 + 0x00036> in <filename unknown>:0
  at System.Text.Json.ReadStackFrame.Initialize (System.Type type, System.Text.Json.JsonSerializerOptions options) <0x22e36b0 + 0x0000c> in <filename unknown>:0
  at System.Text.Json.JsonSerializer.HandleStartObject (System.Text.Json.JsonSerializerOptions options, System.Text.Json.ReadStack& state) <0x298e858 + 0x000b6> in <filename unknown>:0
  at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x22ea2f0 + 0x00168> in <filename unknown>:0
  at System.Text.Json.JsonSerializer.ReadCore (System.Type returnType, System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader) <0x22e35a8 + 0x0002e> in <filename unknown>:0
  at System.Text.Json.JsonSerializer.Deserialize (System.String json, System.Type returnType, System.Text.Json.JsonSerializerOptions options) <0x22e2540 + 0x0017a> in <filename unknown>:0
  at System.Text.Json.JsonSerializer.Deserialize[TValue] (System.String json, System.Text.Json.JsonSerializerOptions options) <0x29f0870 + 0x0000c> in <filename unknown>:0
  at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T] (System.Net.Http.HttpClient httpClient, System.String requestUri) <0x28da5f0 + 0x000d4> in <filename unknown>:0
  at MyApp.TestView.OnInitializedAsync () <0x28cfea0 + 0x000ee> in <filename unknown>:0
```

### To Reproduce

Create an enum and a test model like this:

```csharp
// ...
using System.Text.Json.Serialization;

public enum Status
{
    New,
    Old
}

public class TestModel
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public Status Status { get; set; }
}
```

Use any extension from `HttpClientJsonExtensions` like this in a Blazor component:

```csharp
protected override async Task OnInitializedAsync()
{
    var model = await HttpClient.GetJsonAsync<TestModel>("/my/api/...");
}
```

The server returns a JSON like this:

```json
{
  "status": "New"
}
```

### Workaround
A workaround for the problem is to reference `JsonStringEnumConverter` explicitly somewhere in the code.

I put this code in `Program.cs`:

```csharp
 public static async Task Main(String[] args)
 {
    var builder = WebAssemblyHostBuilder.CreateDefault(args);

    // ...

    // "workaround"
    var converter = new JsonStringEnumConverter();

    builder.RootComponents.Add<App>("app");
    await builder.Build()
                 .RunAsync();
}
```

It looks like the presence of "workaround" code is enough. If `Program.cs` contains something like this

```csharp
private static Dummy()
{
    var converter = new JsonStringEnumConverter();
}
```
it will still work even if `Dummy` is never called.

So it seems to me that `JsonStringEnumConverter` is getting removed from the **release build** by some kind of optimization.

### Further technical details
* `dotnet 3.1.201` 
* Blazor `3.2.0-preview3.20168.3`
* `System.Text.Json 4.7.1`
* Visual Studio 2019 `16.5.2`

**Comment by javiercn** [comment] 2020-04-10 11:20
@chA0s-Chris thanks for contacting us.

This is a known issue and I believe we've fixed it recently. I'm closing this as a dupe of #20446

**Closed by javiercn** 2020-04-10 11:20 UTC
