### ISSUE TITLE
Can't get AuthorizationMessageHandler in Blazor WebAssembly to work due to service lifetime issues

### ISSUE THREAD

**Issue by NArnott** [dotnet/aspnetcore#33806] opened 2021-06-24 14:56 UTC
I cannot get an HttpClient with AuthorizationMessageHandler working.

I have a project set up using the Microsoft.AspNetCore.Components.WebAssembly.Authentication package, and wired up for OIDC. That's working fine. Now, I want to make an http call to an API in another domain, using the access token provided during the OIDC authentication.

Based on https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#typed-httpclient, this should be a simple task, but I'm having all sorts of problems with the service collection. Here's what I have to set up a typed HttpClient:

```
builder.Services.AddScoped<AuthorizationMessageHandler>();

builder.Services.AddHttpClient<IAuthorizationClient, AuthorizationClient>(client => client.BaseAddress = new Uri(authUrl))
   .AddHttpMessageHandler(sp => sp.GetRequiredService<AuthorizationMessageHandler>().ConfigureHandler(new[] { authUrl }));
```

The issue here, for example, is that AuthorizationMessageHandler requires an IAccessTokenProvider in the constructor, which Blazor provides as a Scoped service. However, the HttpClientFactory is registered as a singleton service. When the HttpClientFactory tries to activate an instance of AuthorizationMessageHandler, it fails with the following error:

> Cannot resolve scoped service 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler' from root provider.

Registering AuthorizationMessageHandler as a Singleton, I get:

>  Cannot consume scoped service 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider' from singleton 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler'.

Registering AuthorizationMessageHandler as a Transient, I get:

> Cannot resolve 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler' from root provider because it requires scoped service 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider'.

I'm out of ideas on how to get this to work. All the examples in the referenced link above don't appear to work.

I've tried this with both net5.0 and net6.0, with the same result.

**Comment by pranavkm** [comment] 2021-06-24 16:34
Looks like this is a dupe of https://github.com/dotnet/aspnetcore/issues/23847. We'll use the other issue to track addressing this.

**Comment by NArnott** [comment] 2021-06-24 18:03
That other issue was closed over a year ago as answered. It doesn't seem like it's going anywhere...

**Closed** 2021-09-07 16:42 UTC
Labels: area-blazor, blazor-wasm, feature-blazor-wasm-auth
