### ISSUE TITLE
Cannot integrate into other SPA because of <base /> mismatch

### ISSUE THREAD

**Issue by Bouke** [dotnet/aspnetcore#40114] opened 2022-02-10 10:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

[With .NET 6 it has become possible to use Blazor Components as Web Components from within other SPAs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#render-blazor-components-from-javascript):

> Blazor is great for building client-side web UI using just .NET, but what if you already have existing JavaScript apps that you need to maintain and evolve? How can you avoid having to build common components twice, in .NET and JavaScript?
> 
> In .NET 6, you can now dynamically render Blazor components from JavaScript. This capability enables you to integrate Blazor components with existing JavaScript apps.

However as Blazor requires the use of `<base href="SomeBlazorPath" />` it breaks the routing of the containing SPA. As a result Blazor cannot be used in such scenarios.

The strict reliance on `<base href="" />` is blocking my attempts to use Blazor Components inside our existing ember.js application.

### Describe the solution you'd like

There has been an attempt before to have other means of configuring Blazor, see #24631. It was rejected on the premise of Blazor *being* the SPA and *handling* the routing. However when using Blazor merely as a means to inject Components, this doesn't hold anymore.

Additionally I'd like to propose another design alternative. Similar to configuring `autostart`, there could be a property on the script tag to configure the base path. This would take precedence over `<base href="" />` (if set).

```js
<script src="/_framework/blazor.server.js" autostart="true" base-href="/SomeBlazorPath"></script>
```

**Comment by javiercn** [comment] 2022-02-10 11:41
@Bouke thanks for contacting us.

Can you clarify this bit?

> [With .NET 6 it has become possible to use Blazor Components as Web Components from within other SPAs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#render-blazor-components-from-javascript). However as Blazor requires the use of <base href="SomeBlazorPath" /> it breaks the routing of the containing SPA. As a result Blazor cannot be used in such scenarios.

Can you provide a concrete example of the error you are seeing? Is the issue loading files or is the issue elsewhere, like NavigationManager or the Router.

**Comment by Bouke** [comment] 2022-02-22 12:36
@javiercn is the issue I'm raising here clear(er) to you now? The feature " integrate Blazor components with existing JavaScript apps" appears to be broken because of this very issue.

**Comment by javiercn** [comment] 2022-02-22 13:41
@Bouke I think so.

Do you have routing setup on your Blazor component? if that's the case, the issue seems to be that Blazor is intercepting the clicks to those links. Is that the case?

**Comment by Bouke** [comment] 2022-02-22 14:25
@javiercn The problem is connecting to Blazor Server from the client-side. My Blazor is hosted at `/SomeBlazorPath`, so to connect there I need to specify `<base href="SomeBlazorPath" />`. But that breaks the routing of the existing JavaScript app. In order to integrate with my existing JavaScript app, Blazor shouldn't depend on `<base href="SomeBlazorPath" />`. Also refer to the following table:

|Scenario|Existing JavaScript app works?|Blazor works?|
|--|--|--|
|Do not include `<base href="SomeBlazorPath" />`|✅|❌, wrong path to blazor|
|Include `<base href="SomeBlazorPath" />`|❌, routing is broken|✅|

**Comment by javiercn** [comment] 2022-02-22 14:42
@Bouke thanks for the additional details. I think it helps clarify the issue.

Correct me if I don't understand this correctly. 

The issue seems to be that you are integrating Blazor Server with other frameworks, and in that context you might be rendering things from a Razor Page or MVC view, or some route different than `/`. And the issue is that Blazor Server doesn't allow the connection because the server rejects the connection.

Did I get this correctly?

**Comment by Bouke** [comment] 2022-02-22 16:31
Yes I think that might have the same result. So I'm hosting the Blazor Hub at `SomeBlazorPath`, like this:
```c#
app.UseEndpoints(endpoints => endpoints.MapBlazorHub("SomeBlazorPath/_blazor"));
```

I have an SPA with client-side routing. It is rendered at `/` and an example route might be `about`. Now if I add `<base href="SomeBlazorPath" />` to the HTML the resulting routes href becomes `/SomeBlazorPath/about`. This is incorrect as the expected URL is `/about`.

**Comment by javiercn** [comment] 2022-02-22 16:54
@Bouke I would have to remember how this works, but is there a reason `app.UseEndpoints(endpoints => endpoints.MapBlazorHub());` doesn't work for you?

**Comment by Bouke** [comment] 2022-02-25 10:37
@javiercn Yes I do not want to run the BlazorHub at its default path.

**Comment by mkArtakMSFT** [comment] 2023-12-14 17:06
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Closed by mkArtakMSFT** 2023-12-14 17:06 UTC
Labels: investigate, area-blazor, feature-js-root-components, Pillar: Technical Debt
