### ISSUE TITLE
[linux-arm64] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets crashes

### ISSUE THREAD

**Issue by tommaybe** [dotnet/aspnetcore#50623] opened 2023-08-31 07:08 UTC
*Edit by @antonfirsov: this can be fixed by #50624, see the latest conversation.*

------------------

### Describe the bug
We have been running on Gravitron2 instances for years without any runtime errors. Since upgrading to Gravitron3, quite frequently (at least several times per day) our application runtime crashes with:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'state')
   at System.Threading.ThreadPool.<>c.<.cctor>b__78_0(Object state)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

This seems similar to issues previously raised here, affecting also ARM:
https://github.com/dotnet/runtime/issues/70486
https://github.com/dotnet/runtime/issues/84407

However it is stated as fixed, which does not seem to be the case.

### To Reproduce
We were unable to produce sample code reproducing the error, but are facing the error in a mission-critical service every day.

### Exceptions (if any)
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'state')
   at System.Threading.ThreadPool.<>c.<.cctor>b__78_0(Object state)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Further technical details
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-arm64
 Base Path:   /usr/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Hosting: Docker via Hashicorp Nomad on EC2, specifically c7g.2xlarge
IDE: Rider 2023.1.4

**Comment by antonfirsov** [comment] 2023-09-11 11:37
Thanks @tommaybe, great news! Since we have a proof that this is a bug in Kestrel socket transport, I transferred the issue to aspnetcore.

**Closed** 2023-09-13 17:58 UTC
Labels: area-networking

**Comment by antonfirsov** [comment] 2023-09-13 19:25
@amcasey given this is a crash and a blocker for some ARM64 users like @tommaybe, wouldn't it make sense to backport this? https://github.com/dotnet/runtime/pull/84432 has been pushed to both 6.0 and 7.0, and an equivalent fix has been implemented in 8.0+

**Comment by amcasey** [comment] 2023-09-13 19:56
@antonfirsov That's my intuition, but I'm inquiring because we're so late in the cycle.

**Comment by karelz** [comment] 2023-09-14 10:24
Given that this is hard to root cause crash with straightforward fix, I would suggest fixing it at minimum in 8.0.
@danmoseley what do you think?

@tommaybe would an 8.0 fix be sufficient for you? If you need the fix on 7.0/6.0, we would need business impact from you - how much does the problem affect your production, number of impacted customers, etc.

**Comment by amcasey** [comment] 2023-09-14 16:59
@karelz The 8.0 fix has been merged: https://github.com/dotnet/aspnetcore/pull/50690 

+1 on needing more info for further backports.

**Comment by tommaybe** [comment] 2023-09-15 14:22
@karelz A 8.0 fix is fully sufficient for us. 

Thanks for everyones help on getting this resolved.
