### ISSUE TITLE
Error after update to 17.12.3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#59550] opened 2024-12-18 17:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-after-update-to-17123/10811621)._

---
[severity:Other] [regression]
The "DiscoverPrecompressedAssets" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.DiscoverPrecompressedAssets.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder. &lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()

It worked before the .net 9 Visual Studio upgrade, an older solution I have not worked on for a while.
I tried . Nett 9 and .Net 8 frame work and it still give the same error.

---
#### Lisa Gao (CSI Interfusion Inc) [MSFT] on 12/12/2024, 05:31 PM: 

<p>Thanks for your feedback! In order for us to investigate this further, I need to confirm some questions with you:</p>
<ol>
<li>What type of projects do you create?(C#/C++ console, Web or others/Is this issue related to Visual Studio?)</li>
<li>Could you please provide some screenshots that has this problem.<br>
Thanks for your help and looking forward to your reply!</li>
</ol>

#### Andre van Huyssteen on 12/13/2024, 08:00 AM: 

<p>The screen shot is as posted in the comment and below. It is for a C# Web Assembly project</p>

#### Антон Нестеренко on 12/13/2024, 07:13 AM: 

<p>i’m experiencing same problems with this VS version.<br>
<img src="https://aka.ms/dc/image?name=B1ad51d62a4324cdebfc8e515ae1ae990638696996221257112_Screenshot_2024-12-13_at_18.13.22.png&amp;tid=1ad51d62a4324cdebfc8e515ae1ae990638696996221257112" alt="Screenshot 2024-12-13 at 18.13.22.png"></p>

#### Feedback Bot on 12/17/2024, 09:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by MackinnonBuck** [comment] 2024-12-18 17:44
Possible dupe of https://github.com/dotnet/aspnetcore/issues/59476

**Comment by andrevanhuyssteen** [comment] 2024-12-18 18:01
The "DiscoverPrecompressedAssets" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.

Instead of failing, can you just not check for a duplicate key and ignore if its already there. Would like to test with that implemented
else I would have to rollback a few versions.

**Comment by andrevanhuyssteen** [comment] 2024-12-19 06:05
The error above happens while building the application not running it.

**Comment by javiercn** [comment] 2024-12-20 17:19
@MackinnonBuck you are right, this is a dupe.

**Closed** 2024-12-20 17:19 UTC
Labels: area-blazor, Needs: Attention :wave:, Author: Migration Bot :robot:, feature-static-web-assets, Needs: Repro
