### ISSUE TITLE
LinkGenerator generate wrong links accross areas

### ISSUE THREAD

**Issue by valeriob** [dotnet/aspnetcore#20489] opened 2020-04-03 07:10 UTC
Hi,
i've been using this route rules for years (Mvc, AspNetcore <=2.2) now i'm porting a webapp to aspnetcore3.1.
"Area1/{tenant}/{controller=Home}/{action=Index}/{id?}"
"Area2/{tenant}/{controller=Home}/{action=Index}/{id?}"

Generating links for those routes 3.1 it's not working in some scenario :

1) if i'm on a page not contained in any area /Home/Index, the link generation works ok

Url.Action("Index", "Home", new { Area = "Area1", tenant = "t1" }) = "/Area1/t1" Ok
Url.Action("Index", "Home", new { Area = "Area2", tenant = "t1" }) = "/Area2/t2" Ok

2) if i follow the first link /Area1/t1/Home/Index
Url.Action("Index", "Home", new { Area = "Area1", }) = "/Area1/t1" Ok
Url.Action("Index", "Home", new { Area = "Area2", }) = "/?Area=Area2" Wrong

3) viceversa if i follow the second link to /Area2/t1/Home/Index
Url.Action("Index", "Home", new { Area = "Area1", }) = "/?Area=Area1" Wrong
Url.Action("Index", "Home", new { Area = "Area2", }) = "/Area2/t1" Ok

This feature is required because to build efficiently a multi-tenant application, you just need to select the tenant once, and it will be passed to the whole application automatically (and have been for many many years).

It looks like that the  method GetValues in src\Http\Routing\src\Template\TemplateBinder.cs disables copying AmbientValues if the area is different :( That's very unfortunate.

Attached is the repro, Navigate to link Area1 and Area2 to see the generation failing.

![image](https://user-images.githubusercontent.com/1522516/78333557-529a4500-758a-11ea-9c3d-e0ed0904cc73.png)

[AspNetCore3RoutingBug.zip](https://github.com/dotnet/aspnetcore/files/4425523/AspNetCore3RoutingBug.zip)

**Comment by javiercn** [comment] 2020-04-03 08:49
@valeriob thanks for contacting us.

I believe this is caused by a difference in how endpoint routing treats ambient values. Check https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#differences-from-earlier-versions-of-routing for details.

@rynowak to confirm, but I think this is expected.

**Comment by valeriob** [comment] 2020-04-03 09:20
Ouch, if this is by design it's a very bad news :(
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#problems-with-route-value-invalidation

So the only way to use netcore3 is to disable EndpointRouting, but what is the path forward ? If you will remove the old behavior before implementing this new feature it will case a lot of pain to a lot of people.
Do you have this feature in the roadmap ? I think that it's very important to be able to have this kind of AmbientValues, for many scenarios !
- localization
- multitenant
- whatever ppl need to have as ambient value

See also
https://github.com/dotnet/aspnetcore/issues/19395

Thanks

**Comment by rynowak** [comment] 2020-04-04 23:22
The answer from @javiercn is correct. The best thing for now is to revert to the old routing system. We'll be adding a feature in 5 that allows you to have more control over how ambient values behave.

**Comment by valeriob** [comment] 2020-04-05 06:37
Hi @rynowak ,
by "more control" can we imply that we'll be able to specify a global ambient parameter in routing with this pattern like before "/CustomValue/{globalAmbientValue}/{controller}/{action}" ?
Thanks for sharing the roadmap, i'll keep a close eye to net5 :D

**Comment by rynowak** [comment] 2020-04-07 17:16
Yes. That's the plan

**Comment by Pilchie** [comment] 2020-05-11 18:26
Closing resolved issue.

**Closed by Pilchie** 2020-05-11 18:26 UTC
Labels: Status: Resolved, area-mvc
