### ISSUE TITLE
Support for Microsoft Identity Platform

### ISSUE THREAD

**Issue by akozhikkot** [dotnet/aspnetcore#52118] opened 2023-11-13 21:55 UTC
This may be only me, but in .NET 7 we used to have a hosted template for Blazor Web Assembly which can be protected using Microsoft Identity Platform. However, in .NET 8 I am a bit lost with VS 2022 which option should I select to get a similar experience with .NRT 8 

![image](https://github.com/dotnet/core/assets/80353239/4c25f33d-bf1a-42db-ae90-d1160b4fb64a)

I do see the option of securing the app using Individual Accounts, but organization I work uses Azure Entra

**Comment by danroth27** [comment] 2023-11-17 20:40
Duplicate of https://github.com/dotnet/aspnetcore/issues/51202.

**Closed by danroth27** 2023-11-17 20:40 UTC
Labels: area-blazor
