### ISSUE TITLE
Debugging WebAssembly client project, unable to launch browser

### ISSUE THREAD

**Issue by maurice-freitag** [dotnet/aspnetcore#29261] opened 2021-01-13 12:37 UTC
# Summary 

We're currently building a web client for an already existing, somewhat large code base using Blazor WebAssembly. Debugging using the browser dev tools has proven very time consuming so far, I would like to start the client project directly. I know this is possible when creating a new project using the official Blazor project template. Some change we made to our project however prevents the browser from launching and thus establishing a browser link for debugging. Navigating to the application URL works on its own but no breakpoints are hit of course.

# Reproduction

Reproduction is not really an option as there are far too many changes made to be sure what caused the issue. Could some package or project reference cause this? The project was created using the default project template for WebAssembly apps without authentication and with the following options: 
- [ ] Configure for HTTPS
- [ ] Enable Docker Support
- [x] ASP.NET Core hosted
- [x] Progressive Web Application

Creating a new project with this configuration allows you to set the client project as startup project. Debugging will launch a browser, breakpoints will be hit. This leads me to believe that there must be some change I made that causes this to not work in my project. What's confusing to me is the fact that the app is running just fine, the issue comes up before the Main method is even hit. The only hint I have at the moment is in `visualstudio-js-debugger.txt`, where it says that js-debug (?) makes an attempt to launch something on port 58762, followed by some connection refused errors ([...]`Error looking up /json/version`[...]).

# Files & Information

## vs

> Microsoft Visual Studio Enterprise 2019
> Version 16.8.4

## dotnet

> .NET SDK (reflecting any global.json):
>  Version:   5.0.102
>  Commit:    71365b4d42
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.102\
> 
> Host (useful for support):
>   Version: 5.0.2
>   Commit:  cb5f173b96
> 
> .NET SDKs installed:
>   2.1.811 [C:\Program Files\dotnet\sdk]
>   3.1.404 [C:\Program Files\dotnet\sdk]
>   5.0.100 [C:\Program Files\dotnet\sdk]
>   5.0.101 [C:\Program Files\dotnet\sdk]
>   5.0.102 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

## launchsettings.json:
```json 
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:49713",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "ClientApp": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
** neither profile works

## `visualstudio-js-debugger.txt`

```
{"timestamp":1610538328862,"tag":"runtime.welcome","level":1,"message":"js-debug v1.50.0 started","metadata":{"os":"win32 x64","nodeVersion":"v12.16.3","adapterVersion":"1.50.0"}}
{"tag":"dap.receive","timestamp":1610538328810,"metadata":{"connectionId":0,"message":{"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":"pwa-msedge","locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"SupportsMessageBox":true,"supportsHandshakeRequest":true,"supportsVsAdditionalBreakpointBinds":true,"supportsHitCountsChange":true,"supportsVsCustomMessages":true,"supportsMapURLToFilePathRequest":true,"supportsLaunchUnelevatedProcessRequest":true},"seq":1}},"level":0}
{"tag":"dap.send","timestamp":1610538328812,"metadata":{"connectionId":0,"message":{"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":false,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"caught","label":"Caught Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":false}],"supportsStepBack":false,"supportsSetVariable":true,"supportsRestartFrame":true,"supportsGotoTargetsRequest":false,"supportsStepInTargetsRequest":false,"supportsCompletionsRequest":true,"supportsModulesRequest":false,"additionalModuleColumns":[],"supportedChecksumAlgorithms":[],"supportsRestartRequest":true,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":true,"supportsLoadedSourcesRequest":true,"supportsLogPoints":true,"supportsTerminateThreadsRequest":false,"supportsSetExpression":false,"supportsTerminateRequest":false,"completionTriggerCharacters":[".","[","\"","'"],"supportsBreakpointLocationsRequest":true,"supportsClipboardContext":true}}},"level":0}
{"tag":"dap.send","timestamp":1610538328815,"metadata":{"connectionId":0,"message":{"seq":2,"type":"event","event":"initialized","body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1610538328846,"metadata":{"connectionId":0,"message":{"type":"request","command":"launch","arguments":{"WebRoot":"C:\\[...]\\wwwroot","rootPath":"C:\\[...]\\wwwroot","__workspaceFolder":"C:\\[...]\\wwwroot","runtimeExecutable":"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe","runtimeArgs":[],"sourceMaps":true,"url":"http://localhost:49713/","trace":{"logFile":"C:\\Users\\freitag\\AppData\\Local\\Temp\\visualstudio-js-debugger.txt"},"port":58762,"launchUnelevated":false,"projectGuid":"85ead8d3-e158-455d-b1f2-4f5138966486","userDataDir":"C:\\Users\\freitag\\AppData\\Local\\Microsoft\\VisualStudio\\16.0_d12de34e\\WebTools\\F17440DA_BE37C492","breakOnLoad":true,"smartStep":true,"skipFiles":[],"showAsyncStacks":true,"timeout":60000,"inspectUri":"{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}","cleanUp":"onlyTab","name":"Visual Studio launch configuration override","type":"pwa-msedge","request":"launch","continueOnDisconnect":true},"seq":2}},"level":0}
{"tag":"dap.send","timestamp":1610538328848,"metadata":{"connectionId":0,"message":{"seq":3,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/launch","data":{"type":"pwa-msedge","request":"launch","os":"win32 x64","nodeVersion":"v12.16.3","adapterVersion":"1.50.0","parameters":"{\"type\":\"pwa-msedge\",\"name\":\"<string>\",\"request\":\"launch\",\"trace\":{\"logFile\":\"<string>\"},\"outputCapture\":\"console\",\"timeout\":60000,\"timeouts\":{},\"showAsyncStacks\":true,\"skipFiles\":[],\"smartStep\":true,\"sourceMaps\":true,\"pauseForSourceMap\":true,\"resolveSourceMapLocations\":null,\"rootPath\":\"<string>\",\"outFiles\":[\"<string>\",\"<string>\"],\"sourceMapPathOverrides\":{\"webpack://?:*/*\":\"<string>\",\"webpack:///./~/*\":\"<string>\",\"meteor://💻app/*\":\"<string>\"},\"enableContentValidation\":true,\"cascadeTerminateToConfigurations\":[],\"__workspaceFolder\":\"<string>\",\"__autoExpandGetters\":false,\"__breakOnConditionalError\":false,\"address\":\"localhost\",\"port\":58762,\"disableNetworkCache\":true,\"pathMapping\":{},\"url\":\"<string>\",\"restart\":false,\"urlFilter\":\"*\",\"webRoot\":\"<string>\",\"server\":null,\"browserAttachLocation\":\"workspace\",\"targetSelection\":\"automatic\",\"vueComponentPaths\":[\"<string>\",\"<string>\"],\"cwd\":null,\"file\":null,\"env\":{},\"includeDefaultArgs\":true,\"runtimeArgs\":[],\"runtimeExecutable\":\"<string>\",\"userDataDir\":\"<string>\",\"browserLaunchLocation\":\"workspace\",\"profileStartup\":false,\"cleanUp\":\"<string>\",\"useWebView\":false,\"WebRoot\":\"<string>\",\"launchUnelevated\":false,\"projectGuid\":\"<string>\",\"breakOnLoad\":true,\"inspectUri\":\"<string>\",\"continueOnDisconnect\":true}"}}}},"level":0}
{"tag":"dap.send","timestamp":1610538328851,"metadata":{"connectionId":0,"message":{"seq":4,"type":"event","event":"output","body":{"category":"console","output":"Verbose logs are written to:\nC:\\Users\\freitag\\AppData\\Local\\Temp\\visualstudio-js-debugger.txt\n"}}},"level":0}
{"tag":"dap.receive","timestamp":1610538329033,"metadata":{"connectionId":0,"message":{"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\FASTEC\\development\\Mvvm\\src\\Fastec.Mvvm.Core\\Events\\PubSubEvent.cs","sources":[],"checksums":[]},"breakpoints":[{"line":71,"column":9}],"lines":[71]},"seq":3}},"level":0}
{"tag":"dap.send","timestamp":1610538329034,"metadata":{"connectionId":0,"message":{"seq":5,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":1,"verified":false,"message":"Unbound breakpoint"}]}}},"level":0}
{"tag":"dap.receive","timestamp":1610538329034,"metadata":{"connectionId":0,"message":{"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\[...]\\App.razor","sources":[],"checksums":[]},"breakpoints":[{"line":17,"column":9}],"lines":[17]},"seq":4}},"level":0}
{"tag":"dap.receive","timestamp":1610538329034,"metadata":{"connectionId":0,"message":{"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\[...]\\Services\\NavigationController.cs","sources":[],"checksums":[]},"breakpoints":[{"line":74,"column":9}],"lines":[74]},"seq":5}},"level":0}
{"tag":"dap.receive","timestamp":1610538329034,"metadata":{"connectionId":0,"message":{"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\[...]\\Pages\\Maintenance\\MaintenanceRequestsView.razor","sources":[],"checksums":[]},"breakpoints":[{"line":24,"column":5}],"lines":[24]},"seq":6}},"level":0}
{"tag":"dap.send","timestamp":1610538329034,"metadata":{"connectionId":0,"message":{"seq":6,"type":"response","request_seq":4,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":2,"verified":false,"message":"Unbound breakpoint"}]}}},"level":0}
{"tag":"dap.send","timestamp":1610538329035,"metadata":{"connectionId":0,"message":{"seq":7,"type":"response","request_seq":5,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":3,"verified":false,"message":"Unbound breakpoint"}]}}},"level":0}
{"tag":"dap.send","timestamp":1610538329035,"metadata":{"connectionId":0,"message":{"seq":8,"type":"response","request_seq":6,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"id":4,"verified":false,"message":"Unbound breakpoint"}]}}},"level":0}
{"tag":"dap.receive","timestamp":1610538329048,"metadata":{"connectionId":0,"message":{"type":"request","command":"setExceptionBreakpoints","arguments":{"filters":[]},"seq":7}},"level":0}
{"tag":"dap.send","timestamp":1610538329048,"metadata":{"connectionId":0,"message":{"seq":9,"type":"response","request_seq":7,"command":"setExceptionBreakpoints","success":true,"body":{}}},"level":0}
{"tag":"dap.receive","timestamp":1610538329051,"metadata":{"connectionId":0,"message":{"type":"request","command":"configurationDone","arguments":{},"seq":8}},"level":0}
{"tag":"dap.send","timestamp":1610538329051,"metadata":{"connectionId":0,"message":{"seq":10,"type":"response","request_seq":8,"command":"configurationDone","success":true,"body":{}}},"level":0}
{"tag":"dap.send","timestamp":1610538333825,"metadata":{"connectionId":0,"message":{"seq":11,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"errors":[],"initialize":{"operation":"initialize","totalTime":4.9,"max":4.9,"avg":4.9,"stddev":null,"count":1,"failed":0},"!initialize.errors":[],"initialize.errors":[],"setBreakpoints":{"operation":"setBreakpoints","totalTime":3.3,"max":1,"avg":0.8,"stddev":0.1,"count":4,"failed":0},"!setBreakpoints.errors":[],"setBreakpoints.errors":[],"setExceptionBreakpoints":{"operation":"setExceptionBreakpoints","totalTime":0.6,"max":0.6,"avg":0.6,"stddev":null,"count":1,"failed":0},"!setExceptionBreakpoints.errors":[],"setExceptionBreakpoints.errors":[],"configurationDone":{"operation":"configurationDone","totalTime":0.5,"max":0.5,"avg":0.5,"stddev":null,"count":1,"failed":0},"!configurationDone.errors":[],"configurationDone.errors":[]}}}},"level":0}
{"tag":"runtime.launch","timestamp":1610538339844,"message":"Error looking up /json/version","metadata":{"ok":false,"body":"connect ECONNREFUSED 127.0.0.1:58762","statusCode":503,"error":{"message":"Unexpected 503 response from http://localhost:58762/json/version","stack":"Error: Unexpected 503 response from http://localhost:58762/json/version\n    at g.fetchHttp (c:\\program files (x86)\\microsoft visual studio\\2019\\enterprise\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\adapter\\resourceProvider\\basicResourceProvider.js:103:24)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}},"level":0}
{"tag":"runtime.launch","timestamp":1610538349109,"message":"Error looking up /json/list","metadata":{"ok":false,"body":"connect ECONNREFUSED 127.0.0.1:58762","statusCode":503,"error":{"message":"Unexpected 503 response from http://localhost:58762/json/list","stack":"Error: Unexpected 503 response from http://localhost:58762/json/list\n    at g.fetchHttp (c:\\program files (x86)\\microsoft visual studio\\2019\\enterprise\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\adapter\\resourceProvider\\basicResourceProvider.js:103:24)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}},"level":0}
{"tag":"runtime.launch","timestamp":1610538358591,"message":"Error looking up /json/version","metadata":{"ok":false,"body":"connect ECONNREFUSED 127.0.0.1:58762","statusCode":503,"error":{"message":"Unexpected 503 response from http://localhost:58762/json/version","stack":"Error: Unexpected 503 response from http://localhost:58762/json/version\n    at g.fetchHttp (c:\\program files (x86)\\microsoft visual studio\\2019\\enterprise\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\adapter\\resourceProvider\\basicResourceProvider.js:103:24)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}},"level":0}
{"tag":"runtime.launch","timestamp":1610538367808,"message":"Error looking up /json/list","metadata":{"ok":false,"body":"connect ECONNREFUSED 127.0.0.1:58762","statusCode":503,"error":{"message":"Unexpected 503 response from http://localhost:58762/json/list","stack":"Error: Unexpected 503 response from http://localhost:58762/json/list\n    at g.fetchHttp (c:\\program files (x86)\\microsoft visual studio\\2019\\enterprise\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\adapter\\resourceProvider\\basicResourceProvider.js:103:24)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}},"level":0}
{"tag":"runtime.launch","timestamp":1610538377267,"message":"Error looking up /json/version","metadata":{"ok":false,"body":"connect ECONNREFUSED 127.0.0.1:58762","statusCode":503,"error":{"message":"Unexpected 503 response from http://localhost:58762/json/version","stack":"Error: Unexpected 503 response from http://localhost:58762/json/version\n    at g.fetchHttp (c:\\program files (x86)\\microsoft visual studio\\2019\\enterprise\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\adapter\\resourceProvider\\basicResourceProvider.js:103:24)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}},"level":0}
{"tag":"runtime.launch","timestamp":1610538386484,"message":"Error looking up /json/list","metadata":{"ok":false,"body":"connect ECONNREFUSED 127.0.0.1:58762","statusCode":503,"error":{"message":"Unexpected 503 response from http://localhost:58762/json/list","stack":"Error: Unexpected 503 response from http://localhost:58762/json/list\n    at g.fetchHttp (c:\\program files (x86)\\microsoft visual studio\\2019\\enterprise\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\adapter\\resourceProvider\\basicResourceProvider.js:103:24)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}},"level":0}
{"tag":"runtime.launch","timestamp":1610538388867,"message":"Launch returned error","metadata":{"error":{"message":"Unable to launch browser: \"Could not connect to debug target at http://localhost:58762: Promise was canceled\"","stack":"Error: Unable to launch browser: \"Could not connect to debug target at http://localhost:58762: Promise was canceled\"\n    at k.prepareLaunch (c:\\program files (x86)\\microsoft visual studio\\2019\\enterprise\\common7\\ide\\commonextensions\\microsoft\\jsdiagnostics\\debugger\\debugAdapter\\out\\src\\targets\\browser\\browserLauncher.js:102:19)"},"wasCancelled":true,"name":"k"},"level":2}
{"tag":"dap.send","timestamp":1610538388867,"metadata":{"connectionId":0,"message":{"seq":12,"type":"response","request_seq":2,"command":"launch","success":false,"body":{"error":{"id":9240,"format":"Unable to launch browser: \"Could not connect to debug target at http://localhost:58762: Promise was canceled\"","showUser":false}}}},"level":0}
{"tag":"dap.send","timestamp":1610538390888,"metadata":{"connectionId":0,"message":{"seq":13,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/error","data":{"!error":{"error":{"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"}},"error":{"error":{"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"}},"exceptionType":"uncaughtException"}}}},"level":0}
{"tag":"dap.send","timestamp":1610538390888,"message":"Message not sent. Connection was closed.","level":2}
{"tag":"runtime.exception","timestamp":1610538390888,"message":"Unhandled error in debug adapter","metadata":{"message":"read ECONNRESET","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"},"level":3}
```

**Comment by captainsafia** [comment] 2021-01-13 15:57
Thanks for opening this issue, @maurice-freitag! It's very complete and helpful.

Indeed, it looks like the JS debugger is having trouble communicating with the debugging proxy. Can you confirm the following:

- What is the standard output displayed for your application? You should see the text printed for the running application server (on port 5001) as well as the proxy server (on port 58762 above but typically some other random port).
- Can you reproduce the error when debugging in the browser? Users have reported that VS can sometimes cache some stale data and cause debugging sessions to fail where it was previously working. If debugging in the browser works, it indicates that this might be the issue.

**Comment by maurice-freitag** [comment] 2021-01-14 06:41
Thanks for the quick reply @captainsafia 

> * What is the standard output displayed for your application? You should see the text printed for the running application server (on port 5001) as well as the proxy server (on port 58762 above but typically some other random port).
This is the output: 
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\[...]
Hosting environment: Development
Content root path: C:\[...]
```
The next line should be `Now listening on: http://127.0.0.1:12345` but it stops there.

> * Can you reproduce the error when debugging in the browser? Users have reported that VS can sometimes cache some stale data and cause debugging sessions to fail where it was previously working. If debugging in the browser works, it indicates that this might be the issue.

I think you're right. Debugging in the browser never stopped working and I just downloaded another browser and the issue is not present with that. Before I delete the cached data on my regular browser, is there any data that might be of interest?

**Comment by mkArtakMSFT** [comment] 2021-01-14 17:35
@captainsafia please let us know if there is any actions pending for us here.

**Comment by mkArtakMSFT** [comment] 2021-01-19 17:06
The JS Debugger team will be looking into this. They track their work internally. No further action is pending here, so closing this issue.

**Closed by mkArtakMSFT** 2021-01-19 17:06 UTC
Labels: External, area-blazor, blazor-wasm, feature-blazor-debugging
