### ISSUE TITLE
StreamRendering(true) isn't working correctly with default blazor web app template on rc2

### ISSUE THREAD

**Issue by sharp18** [dotnet/aspnetcore#51502] opened 2023-10-19 17:16 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Created projet from blazor web app template, with server interactivity type and per page / component interactivity
StreamRendering(true) does not show the "Loading..." text. Instead, displays directly the weather table after a second

### Expected Behavior

The page should display the "Loading..." text first.

### Steps To Reproduce

https://github.com/sharp18/BlazorApp1.git

Run Ctrl+F5

Click on "Weather". It takes 1 second to load the data but does not show the loading text

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

IDE: Microsoft Visual Studio Community 2022 (64 bits) - Preview Version 17.8.0 Preview 4.0

dotnet info output

SDK .NET :
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

Charges de travail .NET installées :
Il n'y a aucune charge de travail installée à afficher.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  7.0.401 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by DM-98** [comment] 2023-10-20 06:50
Try "dotnet run" or "dotnet watch" in the project commandline instead of running it through Visual Studio. Does that fix it?

**Comment by sharp18** [comment] 2023-10-20 11:50
@DM-98 , Thanks for the suggestion. I tried "dotnet run" and "dotnet watch" but it does not work either. I did the tests with MS Edge and Chrome, same result

**Comment by DM-98** [comment] 2023-10-20 12:21
I downloaded your repo, and ran the project, navigated to Weather and it shows Loading... for me then shows the result. I can't reproduce your issue.

**Comment by sharp18** [comment] 2023-10-20 12:43
I share my result with you. What am I missing? 😞 

![Animation](https://github.com/dotnet/aspnetcore/assets/20304081/0f15dc25-3157-47bf-a134-5744ff77e0ad)

**Comment by DM-98** [comment] 2023-10-20 12:49
I'll give a list of things you could try, and what I would do:
* Remove obj/bin as well as .vs (hidden) folders
* Try enabling SSL and launch it using https://
* Update VS Preview to the newest version
If you have time:
* Repair VS Preview
* Reinstall VS Preview

I had similar issue and my fix was to use dotnet run until VS tooling team fixed an issue. They did a fix and it worked for me, idk why it doesnt work for you, sry.

**Comment by sharp18** [comment] 2023-10-20 15:24
Hi @DM-98 ,
I just did the following:

- Reinstall VS preview to latest version (17.8.0 Preview 4.0) & restarted computer
- Removed obj/bin and .vs folders
- launched project with ssl enabled 

Still not working for me. Something must be wrong but I can't figure it out.

**Comment by m33p** [comment] 2023-11-01 01:27
Having the exact same issue. When I navigate directly to the page or refresh the page StreamRendering works. When I use the navigation links on the left hand side streaming rendering does not work.

**Comment by xxnickles** [comment] 2023-11-13 17:17
I am also experiencing the same problem. It is not working in any scenario for me (vs preview, rider EAP, dotnet run, release mode) on any browser. As the others this is using the default template with no changes

**Comment by parashgoswami** [comment] 2023-11-17 12:38
I am also facing the same issue with Blazor dotnet 8.0
The loading.... is not shown.
But when I curl, its coming. 
Loading ... is also seen un the generated html.
Many of my colleagues reported the same issue
What could be the issue...

**Comment by cmaslowski7006** [comment] 2023-11-17 20:26
I'm experiencing the same issue. Even reinstalled VS and .NET.

**Comment by m33p** [comment] 2023-11-17 20:51
I'm still experiencing this issue even after upgrading .NET 8.0.0 from RC2. This worked fine in earlier previews.

**Comment by Ccry11** [comment] 2023-11-26 20:50
Unfortunately, I'm experiencing the same issue on .NET 8.0

**Comment by OskarKlintrot** [comment] 2023-11-27 11:49
Glad I'm not alone in this, I thought I was doing something wrong! If I set a breakpoint in `OnInitializedAsync()` I can see that nothing gets rendered until that method is exited. I didn't notice it in the template since the delay is only 500ms, but when I tried using it in a real world use case where my task takes 3 sec I noticed that the browser won't render anything at start.

**Comment by mattanja** [comment] 2023-11-29 07:31
I had the same issue not in the Weather example but in a similar simple use-case and found that the problem occurs whenever Blazor is forced to run server-side in OnInitializedAsync() code (with some serverside I/O operations). In this case the rendering process is blocked until the serverside I/O is done.

However, I have found a simple workaround: Enforcing a thread switch before the actual I/O operation enables the rendering process to finish before continuing the background operation.

Workaround:

    protected override async Task OnInitializedAsync()
    {
        await Task.Delay(1);
        await DoTheBlockingWork();
    }

**Comment by OskarKlintrot** [comment] 2023-11-29 08:09
Unfortunately your workaround didn't work for me.

**Comment by mkArtakMSFT** [comment] 2023-12-13 18:20
We believe this has already been fixed in the 8.0 RTM release. I'm going to close this at this point. If someone experiences similar issues with the 8.0 RTM version, please file a new issue.

**Closed by mkArtakMSFT** 2023-12-13 18:20 UTC
Labels: investigate, area-blazor, Pillar: Complete Blazor Web
