### ISSUE TITLE
Consider adding description to Produces for OpenAPI

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/aspnetcore#55573] opened 2024-05-07 09:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When describing the values produced by an API, it is not possible to add a description to the produced value, forcing the response to be fully defined using the `WithOpenApi` method.

### Describe the solution you'd like

Allow something like:

```csharp
/// <summary>
/// Adds an <see cref="IProducesResponseTypeMetadata"/> to <see cref="EndpointBuilder.Metadata"/> for all endpoints
/// produced by <paramref name="builder"/>.
/// </summary>
/// <typeparam name="TResponse">The type of the response.</typeparam>
/// <param name="builder">The <see cref="RouteHandlerBuilder"/>.</param>
/// <param name="statusCode">The response status code. Defaults to <see cref="StatusCodes.Status200OK"/>.</param>
/// <param name="contentType">The response content type. Defaults to "application/json".</param>
/// <param name="description">The response description.</param>
/// <returns>A <see cref="RouteHandlerBuilder"/> that can be used to further customize the endpoint.</returns>
public static RouteHandlerBuilder Produces<TResponse>(
    this RouteHandlerBuilder builder,
    int statusCode = StatusCodes.Status200OK,
    string? contentType = null,
    string? description);

/// <summary>
/// Adds an <see cref="IProducesResponseTypeMetadata"/> to <see cref="EndpointBuilder.Metadata"/> for all endpoints
/// produced by <paramref name="builder"/>.
/// </summary>
/// <param name="builder">The <see cref="RouteHandlerBuilder"/>.</param>
/// <param name="statusCode">The response status code.</param>
/// <param name="responseType">The type of the response. Defaults to null.</param>
/// <param name="contentType">The response content type. Defaults to "application/json" if responseType is not null, otherwise defaults to null.</param>
/// <param name="description">The response description.</param>
/// <returns>A <see cref="RouteHandlerBuilder"/> that can be used to further customize the endpoint.</returns>
public static RouteHandlerBuilder Produces(
    this RouteHandlerBuilder builder,
    int statusCode,
    Type? responseType = null,
    string? contentType = null,
    string? description);
```

**Comment by captainsafia** [comment] 2024-05-07 23:36
@paulomorgado Thanks for filing this issue!

I'm going to close this as a duplicate of https://github.com/dotnet/aspnetcore/issues/54064.

This issue was a good nudge that I owe a response to an existing comment on there. Let's continue the conversation in the issue mentioned above.

**Closed by captainsafia** 2024-05-07 23:36 UTC
Labels: area-web-frameworks
