### ISSUE TITLE
Potential Tooling Issue (RZ code on whitespace after self closing tab)

### ISSUE THREAD

**Issue by optimizasean** [dotnet/aspnetcore#31081] opened 2021-03-19 21:58 UTC
Check linked issue at bottom of message for original writeup (in dotnet/sdk, could be mistake to place it there).

### Describe the bug

I initially discovered this on my .NET6p2 upgrade from .NET5 for Blazor WebAssembly. I got help from @SQL-MisterMagoo and @IvanJosipovic found the shortened version that also triggers the error (principal issue).

The solution is to either remove empty lines after `<hr>` elements or rewrite them to have a closing slash `<hr />`.

I am not sure if other self closing tags also trigger this or not, didn't test them but my project also didn't have errors from the other ones so it is possible but I am not sure.

### To Reproduce

Shortened version by Ivan below (`@code {}` not required to trigger but will throw an additional error):
```C#
@page "/"

@if (true) {
    <div>
        <hr class="problem here with this element and its placement or not self closing" >

    </div>
}
```

The solution is to either remove empty lines after `<hr>` elements or rewrite them to have a closing slash `<hr />`.

### Exceptions (if any)

- RZ2005 (once per offending file)
- CS0116 (sometimes multiple times per file) very consistently.

### Further technical details

- ASP.NET Core version: 6p2
- IDE: Not IDE related.  Tested using CLI in terminal.

#### Information

`dotnet --info`:
```bash
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     X
 OS Version:  X
 OS Platform: X
 RID:         X
 Base Path:   /dotnet/sdk/6.0.100-preview.2.21155.3/

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  6.0.100-preview.2.21155.3 [dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Linked Issue with full writeup: [dotnet/sdk 16406](https://github.com/dotnet/sdk/issues/16406)

**Comment by TanayParikh** [comment] 2021-10-23 00:08
Thanks for reporting, closing this as a duplicate of https://github.com/dotnet/aspnetcore/issues/31814.

**Closed by TanayParikh** 2021-10-23 00:08 UTC
Labels: bug, area-razor.compiler
