### ISSUE TITLE
SignalR client disconnects

### ISSUE THREAD

**Issue by Serg046** [dotnet/aspnetcore#20816] opened 2020-04-14 17:41 UTC
I guess I experience similar to https://github.com/dotnet/aspnetcore/issues/5324 issue. The client disconnects from time to time due to `server timeout (30000.00ms) elapsed without receiving a message from the server`. However the server itself is up as well as my SignalR hub as it works fine with typescript client at the same time. Also I see that the server responds to the ping requests. This is a log part where you can see the issue (the last line).
```
2020-04-13 20:36:14.6686|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 150, EndOfMessage: True. 
2020-04-13 20:36:14.6686|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 299, EndOfMessage: True. 
2020-04-13 20:36:14.6686|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 150, EndOfMessage: True. 
2020-04-13 20:36:14.6686|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 150 byte message from server. 
2020-04-13 20:36:14.6686|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 449 byte message from server. 
2020-04-13 20:36:14.6980|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 144, EndOfMessage: True. 
2020-04-13 20:36:14.6980|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 144 byte message from server. 
2020-04-13 20:36:14.6980|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 145, EndOfMessage: True. 
2020-04-13 20:36:14.6980|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 145 byte message from server. 
2020-04-13 20:36:14.7921|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message. 
2020-04-13 20:36:14.7921|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message completed. 
2020-04-13 20:36:14.7921|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Received message from application. Payload size: 11. 
2020-04-13 20:36:30.7910|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message. 
2020-04-13 20:36:30.7910|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message completed. 
2020-04-13 20:36:30.7910|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Received message from application. Payload size: 11. 
2020-04-13 20:36:44.7958|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.HttpConnection|Disposing HttpConnection. 
2020-04-13 20:36:44.7958|INFO||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Transport is stopping. 
2020-04-13 20:36:44.7958|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Send loop stopped. 
2020-04-13 20:36:44.7958|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Transport stopped. 
2020-04-13 20:36:44.7958|INFO||Microsoft.AspNetCore.Http.Connections.Client.HttpConnection|HttpConnection Disposed. 
2020-04-13 20:36:44.8067|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Receive loop canceled. 
2020-04-13 20:36:44.8067|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Receive loop stopped. 
2020-04-13 20:36:44.8067|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Canceling all outstanding invocations. 
2020-04-13 20:36:44.8067|ERROR||Microsoft.AspNetCore.SignalR.Client.HubConnection|HubConnection reconnecting due to an error. Server timeout (30000.00ms) elapsed without receiving a message from the server.
```
As you can see there are a few successful Ping requests. This is a full log example with a few timeout errors https://dropmefiles.com/5cqKA

Client side configuration:
```csharp
var hub = new HubConnectionBuilder()
                .WithAutomaticReconnect(new[]
                {
                    TimeSpan.FromSeconds(1),
                    TimeSpan.FromSeconds(5),
                    TimeSpan.FromSeconds(10),
                    TimeSpan.FromSeconds(20),
                    TimeSpan.FromSeconds(40),
                    TimeSpan.FromMinutes(1),
                    TimeSpan.FromMinutes(3),
                    TimeSpan.FromMinutes(5)
                })
                .ConfigureLogging(builder =>
                {
                    builder.SetMinimumLevel(LogLevel.Debug);
                    builder.AddNLog();
                })
                .WithUrl("https://test.com/hubs")
                .Build();
```

**Comment by davidfowl** [comment] 2020-04-15 08:09
Are you using the HubConnection itself anywhere in your On callback? I wonder if you're blocking the message loop on the client side in your callbacks and that's whats causing the client to miss messages. You cannot block in those handlers.

**Comment by Serg046** [comment] 2020-04-15 11:25
Yes, I have there buffered StreamWriter operation. But anyway, I put Thread.Sleep(40000) there for testing and it doesn't get timeouts. However, the issue could be on IIS side. I re-host the app using self-host approach and it seems working - no timeouts during 10 hours. My IIS configuration was with AlwaysRunning, preload enabled, zero idle timeout and out of process hosting.

**Comment by halter73** [comment] 2020-04-15 20:07
Could this be caused by an actual network issue? How would we reproduce this?

**Comment by Serg046** [comment] 2020-04-15 21:13
No, it is not a network issue. I've just switched back to IIS application and started getting timeouts, although it was okay outside of IIS during ~20 hours. I have two SignalR servers on the same AWS EC2 which are hosted inside IIS server and Windows service. The client is hosted on the same instance as well. Another difference is that I'm connected to Windows service using localhost but I use DNS with the IIS app because of TLS validation.

**Comment by halter73** [comment] 2020-04-15 21:49
Can you enable trace-level logging on the client? I looked at the logs again, and it is weird that the client is claiming that 30 seconds elapsed without a message from the server when the WebSocketsTransport reported receiving a message 15 seconds prior.

There should be logs indicating "Resetting keep-alive timer, received a message from the server." at the Trace LogLevel.

**Comment by halter73** [comment] 2020-04-15 21:56
Also, can you provide a repro project and server-side logs? The repro project should tell us what your dependency versions are, and whether or not you're running with IIS in-proc or out-of-proc, but putting that info directly in the issue could also help.

**Comment by Serg046** [comment] 2020-04-17 22:36
Client logs 1:
```
2020-04-16 11:03:43.9537|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 1355 byte message from server. 
2020-04-16 11:03:43.9537|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 453, EndOfMessage: True. 
2020-04-16 11:03:43.9537|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 449 byte message from server. 
2020-04-16 11:03:43.9537|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 453 byte message from server. 
2020-04-16 11:03:43.9718|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 147, EndOfMessage: True. 
2020-04-16 11:03:43.9718|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 147 byte message from server. 
2020-04-16 11:03:43.9718|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 581, EndOfMessage: True. 
2020-04-16 11:03:43.9718|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 581 byte message from server. 
2020-04-16 11:03:43.9979|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 279, EndOfMessage: True. 
2020-04-16 11:03:43.9979|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 280, EndOfMessage: True. 
2020-04-16 11:03:43.9979|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 279 byte message from server. 
2020-04-16 11:03:44.0003|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 280 byte message from server. 
2020-04-16 11:03:48.9993|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message. 
2020-04-16 11:03:48.9993|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message completed. 
2020-04-16 11:03:48.9993|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Received message from application. Payload size: 11. 
2020-04-16 11:04:04.0066|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message. 
2020-04-16 11:04:04.0066|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message completed. 
2020-04-16 11:04:04.0066|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Received message from application. Payload size: 11. 
2020-04-16 11:04:14.0017|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.HttpConnection|Disposing HttpConnection. 
2020-04-16 11:04:14.0017|INFO||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Transport is stopping. 
2020-04-16 11:04:14.0017|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Send loop stopped. 
2020-04-16 11:04:14.0017|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Receive loop canceled. 
2020-04-16 11:04:14.0017|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Receive loop stopped. 
2020-04-16 11:04:14.0017|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Transport stopped. 
2020-04-16 11:04:14.0017|INFO||Microsoft.AspNetCore.Http.Connections.Client.HttpConnection|HttpConnection Disposed. 
2020-04-16 11:04:14.0017|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Canceling all outstanding invocations. 
2020-04-16 11:04:14.0152|ERROR||Microsoft.AspNetCore.SignalR.Client.HubConnection|HubConnection reconnecting due to an error. Server timeout (30000.00ms) elapsed without receiving a message from the server.
```
Server logs 1:
```
2020-04-16 11:03:57.5006|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Error writing frame. The operation was canceled.
2020-04-16 11:03:57.5006|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Waiting for the client to close the socket. 
2020-04-16 11:03:57.5378|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Socket closed. 
2020-04-16 11:03:57.5378|DEBUG||Microsoft.AspNetCore.SignalR.HubConnectionHandler|OnConnectedAsync ending. 
2020-04-16 11:03:57.5378|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager|Removing connection O0W_wUP0OT1E2E-7k9jr5Q from the list of connections. 
2020-04-16 11:04:15.0364|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager|New connection xP7JPNXVKhMDYpTrqwehgQ created. 
2020-04-16 11:04:15.0364|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher|Sending negotiation response. 
2020-04-16 11:04:15.0503|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher|Establishing new connection. 
2020-04-16 11:04:15.0503|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Socket opened using Sub-Protocol: '(null)'. 
2020-04-16 11:04:15.0503|DEBUG||Microsoft.AspNetCore.SignalR.HubConnectionHandler|OnConnectedAsync started. 
2020-04-16 11:04:15.0503|DEBUG||Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver|Found protocol implementation for requested protocol: json. 
2020-04-16 11:04:15.0503|DEBUG||Microsoft.AspNetCore.SignalR.HubConnectionContext|Completed connection handshake. Using HubProtocol 'json'. 
```
Client logs 2:
```
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 1182, EndOfMessage: True. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 542, EndOfMessage: False. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 1182 byte message from server. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 175, EndOfMessage: True. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 542 byte message from server. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 286 byte message from server. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 144, EndOfMessage: True. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 288, EndOfMessage: True. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 144 byte message from server. 
2020-04-16 11:40:16.1139|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 288 byte message from server. 
2020-04-16 11:40:16.1562|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 288, EndOfMessage: True. 
2020-04-16 11:40:16.1562|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Message received. Type: Text, size: 1331, EndOfMessage: True. 
2020-04-16 11:40:16.1562|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 288 byte message from server. 
2020-04-16 11:40:16.1562|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Processing 1331 byte message from server. 
2020-04-16 11:40:22.1801|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message. 
2020-04-16 11:40:22.1801|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message completed. 
2020-04-16 11:40:22.1801|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Received message from application. Payload size: 11. 
2020-04-16 11:40:38.1745|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message. 
2020-04-16 11:40:38.1745|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Sending PingMessage message completed. 
2020-04-16 11:40:38.1745|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Received message from application. Payload size: 11. 
2020-04-16 11:40:46.1747|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.HttpConnection|Disposing HttpConnection. 
2020-04-16 11:40:46.1747|INFO||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Transport is stopping. 
2020-04-16 11:40:46.1747|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Send loop stopped. 
2020-04-16 11:40:46.1747|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Transport stopped. 
2020-04-16 11:40:46.1747|INFO||Microsoft.AspNetCore.Http.Connections.Client.HttpConnection|HttpConnection Disposed. 
2020-04-16 11:40:46.1747|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Receive loop canceled. 
2020-04-16 11:40:46.1747|DEBUG||Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport|Receive loop stopped. 
2020-04-16 11:40:46.1747|DEBUG||Microsoft.AspNetCore.SignalR.Client.HubConnection|Canceling all outstanding invocations. 
2020-04-16 11:40:46.1747|ERROR||Microsoft.AspNetCore.SignalR.Client.HubConnection|HubConnection reconnecting due to an error. Server timeout (30000.00ms) elapsed without receiving a message from the server.
```
Server logs 2:
```
2020-04-16 11:37:36.5086|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Socket opened using Sub-Protocol: '(null)'. 
2020-04-16 11:37:36.5533|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Waiting for the application to finish sending data. 
2020-04-16 11:37:36.5533|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Socket closed. 
2020-04-16 11:37:36.5533|DEBUG||Microsoft.AspNetCore.SignalR.HubConnectionContext|Failed connection handshake. 
2020-04-16 11:37:36.5533|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager|Removing connection ik1KUM8EZvUH8bTehu34XQ from the list of connections. 
2020-04-16 11:37:46.5851|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager|New connection EU-hGN9LsRKw6ZBlboILJg created. 
2020-04-16 11:37:46.5851|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher|Sending negotiation response. 
2020-04-16 11:37:46.7407|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher|Establishing new connection. 
2020-04-16 11:37:46.7407|DEBUG||Microsoft.AspNetCore.SignalR.HubConnectionHandler|OnConnectedAsync started. 
2020-04-16 11:37:46.7407|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Socket opened using Sub-Protocol: '(null)'. 
2020-04-16 11:37:46.8158|DEBUG||Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver|Found protocol implementation for requested protocol: json. 
2020-04-16 11:37:46.8158|DEBUG||Microsoft.AspNetCore.SignalR.HubConnectionContext|Completed connection handshake. Using HubProtocol 'json'. 
2020-04-16 11:40:29.5292|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Error writing frame. The operation was canceled.
2020-04-16 11:40:29.5292|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Waiting for the client to close the socket. 
2020-04-16 11:40:29.5292|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport|Socket closed. 
2020-04-16 11:40:29.7082|DEBUG||Microsoft.AspNetCore.SignalR.HubConnectionHandler|OnConnectedAsync ending. 
2020-04-16 11:40:29.7082|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager|Removing connection rB7Y-qjmHpFwSoJ3mN_t5w from the list of connections. 
2020-04-16 11:40:47.2103|DEBUG||Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager|New connection wpmpHspnEuCMW6fEhw5GvQ created. 
```

**Comment by Serg046** [comment] 2020-04-17 22:39
IIS - out of process
Microsoft.AspNetCore.SignalR Version="1.1.0"
Microsoft.AspNetCore.SignalR.Client Version="3.1.3"

Exatly the same code works fine when hosted inside Kestrel/Windows service

**Comment by BrennanConroy** [comment] 2020-04-20 17:13
> Microsoft.AspNetCore.SignalR Version="1.1.0"

Just FYI, this version is out of support. It aligns with the 2.2.0 version of ASP.NET Core which ended life on December 23, 2019. https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle

While that is likely unrelated to the issue, I do recommend moving to a supported version. Either 2.1 (1.0.x of Microsoft.AspNetCore.SignalR) or 3.1.

Are you able to try using IIS in-process and seeing if the issue also reproduces there?

Is it possible for you to provide an app that repros the issue?

**Closed** 2020-04-27 21:00 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, area-signalr
