### ISSUE TITLE
[Blazor] OnParametersSetAsync being invoked multiple times with guid route argument

### ISSUE THREAD

**Issue by nullpainter** [dotnet/aspnetcore#21348] opened 2020-04-30 02:19 UTC
The following Blazor component results in `OnParametersSetAsync()` being called three times:

```razor
@page "/broken/{id:guid}"

Count is: @Count

@code{

    [Parameter]
    public Guid? Id { get; set; }

    private int Count { get; set; }

    protected override async Task OnParametersSetAsync() => Count++;
}
```

If the `guid` parameter is changed to a string, `OnParametersSetAsync()` is called a single time, as expected:

```razor
@page "/notbroken/{id}"

Count is: @Count

@code{

    [Parameter]
    public string? Id { get; set; }

    private int Count { get; set; }

    protected override async Task OnParametersSetAsync() => Count++;
}
```

I am using ASP.NET Core 3.1.2.

**Comment by mkArtakMSFT** [comment] 2020-04-30 16:41
Thanks for contacting us. This is a dupe of #13610

**Closed by mkArtakMSFT** 2020-04-30 16:41 UTC
Labels: area-blazor, investigate
