### ISSUE TITLE
Blazor WebAssembly loading indicator shows more than 100% in .NET 8 Preview 1

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/aspnetcore#46822] opened 2023-02-22 21:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor WebAssembly loading indicator shows more than 100% in .NET 8 Preview 1

### Expected Behavior

The loading indicator should max at 100%.

### Steps To Reproduce

1. Create a new Blazor WebAssembly project targeting .NET 8 Preview 1
2. Build and run the project

### Exceptions (if any)

None

### .NET Version

8.0.100-preview.1.23115.2

### Anything else?

![WasmApp-Loading](https://user-images.githubusercontent.com/81947404/220763277-c0bf3991-2467-487e-88f5-b7fe00b1c43a.png)

**Comment by egvijayanand** [comment] 2023-02-22 21:30
It shows 104% in a project upgraded from .NET 7 to .NET 8 Preview 1.

![WasmApp-Loading-Net7](https://user-images.githubusercontent.com/81947404/220763582-09244c06-92ce-4ee3-b989-17db14c18a43.png)

**Comment by mkArtak** [comment] 2023-02-23 06:02
This is a dupe of https://github.com/dotnet/aspnetcore/issues/46770, which has been fixed in 8.0-preview2.

**Closed** 2023-02-23 17:43 UTC
Labels: area-blazor
