### ISSUE TITLE
New Razor Editor - Error activating HtmlyLanguageClient

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/aspnetcore#29669] opened 2021-01-27 10:54 UTC
Hi, 

I switched on the new Razor editor in VS 16.9 Preview 3 and I get an error message at the top of the editor: "There was an error activating the remote language server, HtmlyLanguageClient. It's a .Net 5.0 Blazor project.

I switched on the logging, and it may or may not be related, but I noticed this error:

Log: OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter: Finished: Routing Request (5) razor/monitorProjectConfigurationFilePath in 15ms | Id='5' Method='razor/monitorProjectConfigurationFilePath' ElapsedMilliseconds='15'
Error: OmniSharp.Extensions.JsonRpc.InputHandler: Failed to handle request razor/monitorProjectConfigurationFilePath 5 - System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\WINDOWS\system32\obj\Debug\net5.0'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.GetExistingConfigurationFiles(String workspaceDirectory)
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.<StartAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.LanguageServer.MonitorProjectConfigurationFilePathEndpoint.<Handle>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.<Handle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<<RouteRequest>g__InnerRoute|5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext() | Method='razor/monitorProjectConfigurationFilePath' RequestId='5'
Log: OmniSharp.Extensions.JsonRpc.InputHandler: Finished: Processing request razor/monitorProjectConfigurationFilePath 5 in 40ms | Method='razor/monitorProjectConfigurationFilePath' ResponseId='5' ElapsedMilliseconds='40'

Thanks, no rush, I've just turned it off again! :)

LJ

**Comment by javiercn** [comment] 2021-01-27 11:02
@LaughingJohn thanks for contacting us.

@NTaylorMullen @TanayParikh can you take a look?

**Comment by NTaylorMullen** [comment] 2021-01-27 15:16
The error included is expected when the project is in the midst of being initialized and wont fail any part of the project creation. That being said the fact taht the HTMLY language client fails to boot is concerning:

@ToddGrun is there something else @LaughingJohn can provide for you to investigate?

**Comment by NTaylorMullen** [comment] 2021-02-17 00:55
@ToddGrun ping

**Comment by ToddGrun** [comment] 2021-02-17 20:02
I would have thought the LSP logging infrastructure would give us some information about any failures encountered during language server initialization. @LaughingJohn -- can you still repro and see if there is any more information available in the logs? Tagging @jimmylewis too.

**Comment by Nelson9991** [comment] 2021-03-04 14:28
Hello, there are any updates on this bug ?, I'm having the same problem.
VS 2019 16.10 Preview 1.
VS 2019 16.9

**Comment by ToddGrun** [comment] 2021-03-04 17:27
We haven't made any changes that knowingly address this issue, as we aren't sure where the actual error is here. Would it be possible for someone experiencing the html language client activation to capture language server logging information to help us track down where the failure is?

**Comment by Nelson9991** [comment] 2021-03-11 05:28
Hello after some search I found this Logs about the html language client activation error :
--------------
HtmlyLanguageClient: Sending initialize request: StreamJsonRpc.RemoteInvocationException: Internal Error - System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,Newtonsoft.Json.Linq.JToken> OmniSharp.Extensions.LanguageServer.Protocol.Server.Capabilities.ServerCapabilities.get_Experimental()'.
   at Microsoft.WebTools.Languages.LanguageServer.Server.Shared.Capabilities.ExtendableServerCapabilities..ctor(ServerCapabilities inner, IEnumerable`1 registrationExtensions)
   at Microsoft.WebTools.Languages.LanguageServer.Server.Html.HtmlLanguageServer.<>c.<CreateAsync>b__4_2(ILanguageServer server, InitializeParams request, InitializeResult response, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<>c__DisplayClass76_0.<MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InternalInitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle>b__4(OnLanguageServerInitializedDelegate handler, CancellationToken ct)
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolEventingHelper.<>c__DisplayClass0_1`2.<Run>b__2(CancellationToken ct)
   at System.Reactive.Linq.QueryLanguage.StartAsyncImpl(Func`2 actionAsync, IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Async.cs:line 806
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<MediatR-IRequestHandler<OmniSharp-Extensions-LanguageServer-Protocol-Models-InternalInitializeParams\,OmniSharp-Extensions-LanguageServer-Protocol-Models-InitializeResult>-Handle>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.<Handle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<<RouteRequest>g__InnerRoute|5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.JsonRpcExtensionMethods.<SendMethodRequestAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()

--------------

HtmlyLanguageClient: StreamJsonRpc.RemoteInvocationException: Internal Error - System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,Newtonsoft.Json.Linq.JToken> OmniSharp.Extensions.LanguageServer.Protocol.Server.Capabilities.ServerCapabilities.get_Experimental()'.
   at Microsoft.WebTools.Languages.LanguageServer.Server.Shared.Capabilities.ExtendableServerCapabilities..ctor(ServerCapabilities inner, IEnumerable`1 registrationExtensions)
   at Microsoft.WebTools.Languages.LanguageServer.Server.Html.HtmlLanguageServer.<>c.<CreateAsync>b__4_2(ILanguageServer server, InitializeParams request, InitializeResult response, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<>c__DisplayClass76_0.<MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InternalInitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle>b__4(OnLanguageServerInitializedDelegate handler, CancellationToken ct)
   at OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolEventingHelper.<>c__DisplayClass0_1`2.<Run>b__2(CancellationToken ct)
   at System.Reactive.Linq.QueryLanguage.StartAsyncImpl(Func`2 actionAsync, IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Async.cs:line 806
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<MediatR-IRequestHandler<OmniSharp-Extensions-LanguageServer-Protocol-Models-InternalInitializeParams\,OmniSharp-Extensions-LanguageServer-Protocol-Models-InitializeResult>-Handle>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.<Handle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<<RouteRequest>g__InnerRoute|5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.JsonRpcExtensionMethods.<SendMethodRequestAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<InitializeAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Nelson9991** [comment] 2021-04-02 16:14
Hello is there any advance on what may be causing the error with the Htmly client ?

**Comment by ToddGrun** [comment] 2021-04-02 16:33
We've added logging that might help track down issues like this in 16.10 Preview2. As for this particular issue, the trace above is a bit confusing. It looks like it's reporting an exception to the html language server asking omnisharp for the ServerCapabilities.Experimental value and being told that property doesn't exist. I don't have any good ideas on what would cause this. I guess one thing to verify is that the proper omnisharp is being loaded in the process. If you run "dir /s OmniSharp.Extensions.LanguageProtocol.dll" under your install folder, what do you get back? If that returns the expected value, it would be good to actually know what version/location of that assembly is being loaded in the Microsoft.WebTools.Languages.LanguageServer.Host.exe process.

**Comment by Nelson9991** [comment] 2021-04-03 22:44
Hi, @ToddGrun in the install folder of VS 2019, inside RazorLanguageServer folder the OmniSharp.Extensions.LanguageProtocol.dll is on version 0.18.1.0

**Comment by ToddGrun** [comment] 2021-04-03 22:56
That's the one that the razor language server uses, the html/css language servers use the one under "Common7\IDE\Extensions\Microsoft\Web Tools\Languages\LanguageServers". Is that present?

**Comment by Nelson9991** [comment] 2021-04-03 23:48
Yes it's present also in the same version. Here is the list of all the file present in that folder:
cssServerMain.js
htmlServerMain.js
jsonServerMain.js
MediatR.dll
Microsoft.Extensions.Configuration.Abstractions.dll
Microsoft.Extensions.Configuration.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.DependencyInjection.dll
Microsoft.Extensions.Logging.Abstractions.dll
Microsoft.Extensions.Logging.dll
Microsoft.Extensions.Options.dll
Microsoft.Extensions.Primitives.dll
Microsoft.VisualStudio.Threading.dll
Microsoft.WebTools.Languages.LanguageServer.Host.exe
Newtonsoft.Json.dll
OmniSharp.Extensions.JsonRpc.dll
OmniSharp.Extensions.LanguageProtocol.dll
OmniSharp.Extensions.LanguageServer.dll
OmniSharp.Extensions.LanguageServer.Shared.dll
System.Composition.AttributedModel.dll
System.Reactive.dll
yamlServerMain.js

**Comment by LaughingJohn** [comment] 2021-04-08 09:56
Thanks for running with this Nelson, I haven't had much time. I can also confirm using Process Explorer that the version of OmniSharp.Extensions.LanguageProtocol.dll is 0.18.1.0 and is being loaded from the native image cache.

I'm not sure if it's relevant, but I thought it might be worth mentioning that I use both Visual Studio IntelliCode & Roslynator extensions. Just in case something might be clashing.

**Comment by Nelson9991** [comment] 2021-04-21 21:25
Hello, I searched again in the logs of vs 2019 while open an ASP.NET Core MVC project  and it displays the same log about the HTML Language Server activation.

HtmlLanguageClient: Sending initialize request: StreamJsonRpc.RemoteInvocationException: Internal Error - System.MissingMethodException: Método no encontrado: 'System.Collections.Generic.IDictionary`2<System.String,Newtonsoft.Json.Linq.JToken> OmniSharp.Extensions.LanguageServer.Protocol.Server.Capabilities.ServerCapabilities.get_Experimental()'.
   en Microsoft.WebTools.Languages.LanguageServer.Server.Shared.Capabilities.ExtendableServerCapabilities..ctor(ServerCapabilities inner, IEnumerable`1 registrationExtensions)
   en Microsoft.WebTools.Languages.LanguageServer.Server.Html.HtmlLanguageServer.<>c.<CreateAsync>b__4_2(ILanguageServer server, InitializeParams request, InitializeResult response, CancellationToken cancellationToken)
   en OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<>c__DisplayClass76_0.<MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InternalInitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle>b__4(OnLanguageServerInitializedDelegate handler, CancellationToken ct)
   en OmniSharp.Extensions.LanguageServer.Protocol.LanguageProtocolEventingHelper.<>c__DisplayClass0_1`2.<Run>b__2(CancellationToken ct)
   en System.Reactive.Linq.QueryLanguage.StartAsyncImpl(Func`2 actionAsync, IScheduler scheduler) en /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Async.cs:línea 806.
---------------------------------------------------------------------------------------------
I Have found other composition errors, there are 19 in total about other parts of the Html language client, here is some examples :
1.
Microsoft.WebTools.Languages.Html.Editor.Formatting.ContainedLanguage.FormatterProviders.TypeScriptContainedLanguageFormatterProvider.ctor (threadSwitcher) - Exactly 1 export expected to match restrictions:
    Contract name: Microsoft.WebTools.Shared.IThreadSwitcher
    TypeIdentityName: Microsoft.WebTools.Shared.IThreadSwitcher
 but 0 was found.

2.
Microsoft.WebTools.Languages.Html.Editor.Razor.RazorHtmlScriptOrStyleTagNamesServiceProviderProxy.RazorVersionDetector: se esperaba exactamente 1 exportación que coincidiera con las restricciones:
    Contract name: Microsoft.WebTools.Languages.Html.Editor.ContainedLanguage.Razor.Def.IRazorVersionDetector
    TypeIdentityName: Microsoft.WebTools.Languages.Html.Editor.ContainedLanguage.Razor.Def.IRazorVersionDetector
 pero se encontró 0.

**Comment by NTaylorMullen** [comment] 2021-06-02 04:49
I haven't seen this in quite a long time. Would you all mind trying in 16.10 VS and validating if this has been fixed for you?

**Comment by Nelson9991** [comment] 2021-06-03 13:44
Hello @NTaylorMullen. I can confirm that the issue is still present on VS 16.10 and 16.11 Preview 1. I've been trying different things to ge it work but don't know whats causing the error :(

**Comment by Nelson9991** [comment] 2021-06-18 15:58
Hi folks, I managed to solve the issue, but for that had to uninstall vs 2019, and also delete all file related to vs under the AppData folders and start from the ground with a clean installation. Never found what was causing the issue though.

**Comment by LaughingJohn** [comment] 2021-07-01 16:48
Hi,
I just tried it again in 16.11 preview 2 and it seems to have gone away for me too! There's some other issues, but happy to close this if you are! Thanks for the assistance and thanks to @Nelson9991 for joining in!

LJ,

**Comment by NTaylorMullen** [comment] 2021-07-01 17:26
Closing as this seems to have been resolved in latest release. Thank you everyone!

**Closed by NTaylorMullen** 2021-07-01 17:26 UTC
Labels: External, area-razor.tooling, bug
