### ISSUE TITLE
Razor editor feature performance "speed" evaluation

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#30247] opened 2021-02-17 17:38 UTC
Lets dig into a few common requests to better understand where our performance bottlenecks lie in regards to "time spent" so we can make better decisions on where to improve our stack. Some key components of a feature request would be, StreamJsonRpc calls, serialization/deserialization, LSP platform handling, Razor handling, C# handling etc. Basically understanding how much each of those entry points contribute to the total cost of "evaluating" a feature.

- Completion
- CodeActions
- OnAutoInsert
- Semantic colorization

**Also:** One key aspect of this investigation will also be to understand how we operate in "large file" scenarios.

**Comment by NTaylorMullen** [comment] 2021-02-18 18:05
Goal here is to break down each feature into its logical parts and measure its overall average "speed" and what % each logical part represents. A few examples of a logical part would be "C#'s Language Server", "Stream JsonRPC for communication", "VS LSP Platform"

@ryanbrandenburg / @TanayParikh leaving up to you to disperse the 4 items as you two feel fit.

**Comment by ryanbrandenburg** [comment] 2021-03-03 23:15
Semantic tokens scenario:
1. Open a default Razor project, wait for it to colorize.
2. Start PerfView.
3. Copy the contents of a large HTML page (I use https://github.com/dotnet/roslyn/blob/master/docs/wiki/Recording-performance-traces-with-PerfView.md) onto the existing Index page.
4. Add a Razor component at the end and wait for it to be colorized. Once it is colored correctly stop collection.

Semantic Tokens Data:
|Section|CPU Stacks (Inclusive)|Percentage|
|--------|------------|------------|
|Total|73,407|100%|
|RazorSemanticTokensEndpoint.Handle|5|>1%|
|DocumentState.GetGeneratedOutputAndVersionAsync|4,757|6.5%|
|DefaultRazorProjectEngine.ProcessDesignTime|4,583|6.2%|
|DefaultRazorDocumentMappingService.GetLanguageKind|1,981|2.7%|
|FileSystemWatcher.CompletionStatusChanged|4,083|5.6%|
|wks gc_heap|3,446|4.7%|
|BackgroundDocumentGenerator.Timer_Tick|2,193|3%|

**Comment by ryanbrandenburg** [comment] 2021-03-10 00:26
### Thoughts:
#### CPU:
Everything in this category could be significantly higher because PerfView "spagetii"'s async code. But it's still useful to see where some hot-paths are.

1. The innards for GetGeneratedOutputAndVersionAsync could use some optimizing, taking 6% of CPU stacks (not thread time) to get the document version and contents seems high.
2. We're spending surprisingly little (exclusive) time in Newtonsoft, Nerdbank and O# handling requests and streams. This could just be because PerfView turns async calls into "spagetti". In order to learn more we would need to add start/stop ETW events around our serialization and deserialization calls.
3. There seems to be significant delays in calls to `razor/provideSemanticTokens`, which mostly spends its time getting C# semantic tokens for our virtual documents. It may be useful to compare notes with Roslyn's perf analysis in this area.
4. hover, completion, razor/updateHtmlBuffer and razor/updateCSharpBuffer seem to have slowdown problems as well, but none of their relevant stacks show up in PerfView CPU views at all. Does anyone know why that might be?

#### Memory:
1. TextMate seems to be generating a ton of int[]'s. While that's not directly related to this scenario maybe we could ask them to looking into reducing those allocations.
2. TagHelperBinder.GetBinding DID have a ton of allocations from LINQ, but I've already merged a PR for that and it shouldn't show once we've inserted Razor into VS again.
3. ClassifiedSpanVisitor.WriteSpan is caused by the backing array of the list expanding too many times, if we used `SegmentedList` we could reduce these allocations significantly, but ClassifiedSpanVisitor is currently in a project with no dependencies, so we'd have to make sure we didn't cause any problems when we added the reference.
4. I doubt the Newtonsoft string allocations account for every allocation Newtonsoft makes, so once we handle the top 2-4 its allocations will probably become more apparent (as a percentage).

**Comment by NTaylorMullen** [comment] 2021-03-10 18:50
> 4\. hover, completion, razor/updateHtmlBuffer and razor/updateCSharpBuffer seem to have slowdown problems as well, but none of their relevant stacks show up in PerfView CPU views at all. Does anyone know why that might be?

Could you elaborate? What type of slowdowns are you seeing with them?

**Comment by NTaylorMullen** [comment] 2021-03-10 18:51
Ahh this: 
![image](https://user-images.githubusercontent.com/2008729/110681260-7ef11500-818e-11eb-9fac-ff4cd70d5be2.png)

Ya that's super odd. I would not have expected that to take any time at all actually...... Super concerning I'd love to know more

**Comment by ryanbrandenburg** [comment] 2021-03-10 19:06
> Also, for the outbound call captures for hover/semantictokens/completion do we know what's taking so long (in ms) in that path?

No, and it's super weird because those stacks (hover, completions, updateCSharp) don't show up in the PerfView AT ALL. Not like they're small, like they don't exist. Which, I tried not to take any actions that would proc hover or completions, so that wouldn't have surprised me if those hadn't shown up in the event view, but they did.

> We could probably avoid ToStringing and lazily write all content:
Yeah I was less interesting as I went down the list of worst offenders because the top like 3 were so much larger than the rest, but if you know quick fixes a little extra savings never hurt anyone.

**Comment by ryanbrandenburg** [comment] 2021-03-11 00:19
After talking it over with some Perf experts we're pretty sure that the extra time for those slow events was caused (in part or in whole) by `SwitchToMainThreadAsync`, which in a single test caused delays of at least 1.1 seconds (and given that updateHtmlBuffer uses it too could have been double that. Here's the delays I saw in `razor/updateCSharpBuffer` running the same scenario as above:
|Wait for main thread sync (in MS)|
|-|
|1132|
|0|
|41|
|0|
|165|
|77|
|0|
|0|
|2|
|260|
|176|
|56|
|85|
|348|
|9|
|3|
|84|
|31|
|0|
|0|
|36|
|46|
|397|
|13|
|189|
|90|

7/26 (>25%) of waiting more than 100ms just to switch to the main thread. That's obviously going to be a problem for responsiveness as people type. @NTaylorMullen says this will be fixed by his refactor to avoid syncing, but that's a ways off. Another solution was to stop updating the buffers in this case and just send a didChange request to the  language server, but that's a relatively big change in its own right that  we might not want to make  just to throw it away after Taylors refactor.

**Comment by ryanbrandenburg** [comment] 2021-03-11 23:16
### Completion scenario
1. Open a razor project and a razor file
2. Paste in a Github page.
3. Start collection.
3. "<Sur", wait for completion options, select one.
4. "Ti", wait for completion options, select it.
5. Finish,Survey element.
6. "<di", wait for completion, select "div".
7. "cl", wait for completion, select "class".
8. Close div.
9. Stop collection.

#### CPU Thread time
|Stack|CPU Stacks|Percentage|
|------|------------|------------|
|Total|3,127,912|100%|
|DefaultForegroundDispatcher.ThreadStart|62,050|2.0%|
|---BlockingCollection.Take (has other sources too)|107,086|3.4%|
|ThreadPoolWatcher.WatcherThread|63,256|2.0%|
|---Thread.Sleep|63,256|2.0%|
|ComputedStateTracker.GetGeneratedOutputAndVersion|52,256|1.7%|
|---DefaultDocumentSnapshot.GetGeneratedOutputAsync|52,027|1.7%|
|CodeActions.CodeActionEndpoint|2,152|0.1%|
|RazorCompletionEndpoint.Handle|5,940|0.2%|
|RazorLanguageEndpoint.Handle|13,136|0.4%|

#### CPU Stacks
|Location|Stacks|Percentage|
|---------|-------|------------|
|Total|67,031|100%|
|GetGeneratedOutputAsync|36,089|53.8%|
|RazorLanguageEndpoint.Handle|9,912|14.8%|
|RazorDiagnosticEndpoint.Handle|8,072|12%|
|DefaultRazorSemanticTokensInfoService.GetSemanticTOkensEditsAsync|6,467|9.6%|
|---DefaultRazorSemanticTokensInfoService.TryGetDocumentInfoAsync|6,052|9.0%|
|-----spent in GetGeneratedOutputAsync|||
|TagHelperBinder.GetBinding|3,413|5.1%|
|---TaghelperMatchingConventions.SatisfiesRule|2,874|4.3%|
|------IReadOnlyExtensions.All|2,130|3.2%|
|DefaultRazorDocumentMappingService.GetLanguageKind|2,636|3.9%|
|---RazorSyntaxTreeExtensions.GetClassifiedSpans|2,343|3.5%|
|------SyntaxWalker.Visit|2,343|3.5%|

- This seems to reflect that we're spending the majority of our computation time in GetGeneratedOutputAsync and GetLanguageKind. While that's kind of expected because of the large IO opertations involved we should examine existing usages of these call-paths to identify opportunities to:
    - Remove calls (if the call is only incidentally needed)
    - Cache results
    - Improve performance.

#### RPC calls
|Method|Duration MS|
|---------|--------------|
|textDocument/documentHighlight|3041|
|textDocument/_ms_onAutoInsert|3037|
|razor/updateCSharpBuffer|3034|
|razor/updateHtmlBuffer|2985|
|textDocument/_ms_onAutoInsert|2984|
|razor/translateDiagnostics|2849|
|textDocument/_ms_diagnostic|2020|
|textDocument/completion|1792|
|textDocument/signatureHelp|1507|
|textDocument/Completion|1205|
|razor/languageQuery|1000|
|textdocument/_ms_diagnostic|504|

- The slowness here likely reflects the same Main-thread contention we observed in the Semantic scenario.

#### Memory
##### Large Object Heap Allocations
|Location|Type|Size|Iterations|Suggestion|
|-|-|-|-|-|
|devenv|Total|4,831,178,000|41,644|Let's have fewer!|
|ClassifiedSpanVisitor.WriteSpan|ClassifiedSpanInternal[]|107,037,100|268|SegmentedList|
|TextDiffer.ComputeDiff|int[]|94,139,440|60|Looks like an Explicite allocation?|
|MarkupTextLiteralSyntax.SetAnnotations<ConditionalWeakTable.Resize>|Entry[SyntaxAnnotation[]][]|58,401,240|15|SegmentedConditionalWeakTable would be nice but probably doesn't exist|
|RazorHtmlWriter.Ctor(StringBuilderCtor)|char[]|38,575,520|154|Not yet investigated|
|RazorHtmlWriter.GetHtmlDocument|string|38,488,800|154|Taylor says lazy ToString|
|RazorCodeDocumentExtensions.GetSourceText.<StringCTorCharArray>|string|28,241,990|113|Not yet investigated|
|RazorCodeDocumentExtensions.GetSourceText|char[]|28,241,750|113|not yet investigated|
|ConvertSemanticRangesToSemanticTokens.InsertRange<EnsureCapacity>|int[]|27,528,000|90|SegmentedList|
|ResolvableSemanticTOkens.ResolveTokensInternal<Array.Resize>|ResolvedSemanticToken[]|13,617,220|30|Segmented|
|TagSpanCache.AddOrUpdateTags|Span[]|7,388,336|24|Platform issue|
|SerializeTags<EnsureCapacity>|int[]|5,505,600|18|SegmentedList|
|THSRV.AddSemanticRange<set_Capacity>|SemanticRange[]|4,701,672|30|Segmented|
|CombineSemanticRanges<set_Capacity>|SemanticRange[]|4,701,672|30|Segmented|

##### Non-LOH Allocations
|Location|Type|Size|Iterations|Suggestion|
|-|-|-|-|-|
|devenv|Total|4,831,178,000|41,644|Let's have fewer!|
|Razor.Language.Syntax.SyntaxToken.CreateRed|SyntaxToken|305,018,000|2,854|Not yet investigated|
|MarkupTextLiteralSyntax.CreateRed|MarkupTextLiteralSyntax|226,370,200|2,119|Not yet investigated|
|Syntaxnode.DescendantNodesImpl|DescendantNodesImpl,d_76|199,024,900|1,861|Not yet investigated|
|SyntaxFactory.Token|InternalSyntax.SyntaxToken|149,391,800|1397|Not yet investigated|
|MarkupTextLiteralSyntax.SetAnnotations|MarkupTextLiteralSyntax|147,201,600|1,377|Not yet investigated|
|SyntaxNodeExtensions.GetContent<Select>|WhereSelectEnumerableIterator<string>|118,442,200|1,106|avoid linq where possible|
|SpanContextBuilder.Reset()|SpanEditHandler|112,616,800|1,054|Not yet investigated|
|SyntaxNodeExtensions.GetContent|WhereEnumerableIterator<SyntaxNode>|111,211,200|1,040|avoid linq where possible|
|DefaultmarkupSpanContext|IEnumerable<SyntaxToken>|109,786,300|1,027|Not yet investigated|
|SyntaxNodeExtensions.GetContent|Linq.Enumerable.CastIterator|103,286,400|966|avoid linq where possible|
|SyntaxWalker.DefaultVisit|Action<MarkupTextLiteralSyntax>|102,082,400|956|Not yet investigated|
|SyntaxNodeExtensions.GetContent<string.Concat>|string|96,389,580|902|Concat less|
|HtmlMarkupParser.ParseConditionalAttributeValue<set_Capacity>|SyntaxToken[]|88,055,390|824|Not yet investigated|
|HtmlTokenizer.GetTokenContent<StringBuilder.ToString>|string|76,242,780|713|StringBuilder less|

**Comment by NTaylorMullen** [comment] 2021-03-12 00:50
Awesome analysis @ryanbrandenburg !!!

**Comment by ryanbrandenburg** [comment] 2021-03-12 01:08
### Top action items for Completion:
1. SyntaxToken objects are way too big. If I had to guess without looking at it I'd say most of that space was spent on strings which were Parsed in and which could probably be run through our StringCache. That only reduces how long they persist, but when parsing strings we're gonna allocate and we might get them collected in an earlier (cheaper) Gen. Should do actual analysis before acting though.
2. MarkupTextLiteralSyntax , DescendantNodesImpl, InternalSyntax.SyntaxToken, MarkupTextLiteralSyntax, SpanEdithandler are all in the same state as 1.
3. We've got  some LINQ allocations that should go away insideSyntaxNodeExtensions.GetContent. That LIKELY means changing some upstream code to use a list instead of a "yield return" (so that we can index on it cheaply), but if THAT causes us problems with Array resize we can move it to a SegmentedList internally.
4. We've got a lot of allocations happening on the LOH, which is not great news, but a lot of them can be fixed by replacing List with SegmentedList (though we'll have to either copy it or pipe it into more places).
5. TextDiffer.ComputeDiff seems to manually allocate some large arrays, we should examine if we can make that more performant (but be careful since the expert isn't available).
6. We commit some string/StringBuilder crimes which may be largely unavoidable, but we can at least evaluate the situation, get some minor savings where  possible and maybe avoid doing anything where it's not strictly required.

**Comment by TanayParikh** [comment] 2021-03-12 02:53
> 5. TextDiffer.ComputeDiff seems to manually allocate some large arrays, we should examine if we can make that more performant (but be careful since the expert isn't available).

Potentially related to https://github.com/dotnet/aspnetcore/issues/24127. I remember there being some mostly unavoidable large allocations in the runtime layer.

**Comment by ryanbrandenburg** [comment] 2021-03-24 18:38
After talking with Sam he said that most of the memory-suggestions we have here are only worth fixing if they're very easy and/or make the code more clear.

He also suggested that we log ETL events to track the serialization, deserialization and size (on the highest logging level) of our messages as he suspects that's a significant source of slowness. Given that there were 3 messages of size 1.8MB (unfortunately the logs don't tell us which messages those were but I imagine it was either the `textDocument/didChange` or `textDocument/semanticTokens` requests containing the large pasted HTML) in one of my traces that seems plausible. I created https://github.com/dotnet/aspnetcore/issues/31204 to track that.

**Comment by TanayParikh** [comment] 2021-04-03 03:00
### Code Actions Scenario:
1. Open a default Razor project, wait for it to colorize.
2. Paste in:

```razor
@code {
    class Impl
    {
        public Impl(object obj1, object obj2)
        {

        }
    }
}
```
3. Start PerfView.
4. Click on `obj1`, click on the "paint brush" code action icon, and select the first (`Add null check`) code action. A preview should pop up (aka. this runs through Code Action Resolve)
5. Stop collection.


### Perf View
Overall there weren't any major actionable items on Razor found in perf view memory/cpu/event profiles. This is likely stemming from the fact that once we get into the O#.HandleRequest call, the direct trace relationship / call stack information is lost due to the async nature of the request.

Newtonsoft did seem to spike for a bit, taking about 60% of the max memory utilization for a brief moment. Tracing this, it came from the request stream deserialization handled by System.IO.Pipelines. There wasn't any visibility into which request/object deserialization resulted in this spike in requirements.
![image](https://user-images.githubusercontent.com/14852843/113458024-4e378080-93c6-11eb-8d74-136b6def6da5.png)

LiveShare was a **major** component of this trace. This is despite running this in a local session. Is this expected?
![image](https://user-images.githubusercontent.com/14852843/113451774-8e433700-93b7-11eb-8f7e-bc8499217676.png)

### Using VS Performance Profiler
:bulb: [Formatting](https://github.com/dotnet/aspnetcore-tooling/blob/436191f0c5aeb836e87547aa8b5bf73909687254/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionResolver.cs#L126-L133) **absolutely dominates** the perf of Code Action Resolve. Looking at the CPU Usage details below we see formatting is responsible for 7.39% of compute time within the sequence under examination. In contrast to the request we dispatch to Roslyn to compute the resolved code action which only takes about 1-2%. I believe this is a result of us doing full document formatting everytime, which would be especially costly in large documents. Range formatting comes to mind as the most direct solution, however I don't believe we have that directly implemented yet. I wonder if we could leverage [onTypeFormatting](https://github.com/dotnet/aspnetcore-tooling/pull/2213) here?

![image](https://user-images.githubusercontent.com/14852843/113464288-5d2b2c80-93e0-11eb-9471-f147273dd926.png)

**Comment by TanayParikh** [comment] 2021-04-03 03:30
### OnAutoInsert Scenario:
1. Open a default Razor project.
2. Paste in:

```razor
@code {
    class Impl
    {

        public Impl(object obj1, object obj2)
        {

        }
    }
}
```
3. Start PerfView.
4. Above `public Impl` type in `///` to trigger `OnAutoInsert`. You should get:

```csharp
        /// <summary>
        /// 
        /// </summary>
        /// <param name="obj1"></param>
        /// <param name="obj2"></param>
        public Impl(object obj1, object obj2)
...
```

5. Stop collection.

### Using VS Performance Profiler
Actually not seeing anything too alarming on the OnAutoInsert front, _however_ `DefaultLogHubWriter.TraceInformation` does stand out.

![image](https://user-images.githubusercontent.com/14852843/113466260-46d89d00-93ef-11eb-9485-8b1418dc69d0.png)

This `TraceInformation` call takes about the same time as the `RequestServerCoreAsync`. However keep in mind this is `TraceInformation` across all the requests (each request performs multiple `TraceInformation` calls and there are multiple requests (hover, completion, onautoinsert, etc.)) so it's not a 1:1 comparison. 

Repeating a similar set of steps with razor comments (write `@*` wait for completion of `*@`), I see similar results. This confirms the `RazorLanguageServer` `OnAutoInsertEndpoint` is similarly performant not raising any new concerns. Note however the `TraceInformation` call is once more prominent in terms of total CPU time.

![image](https://user-images.githubusercontent.com/14852843/113466635-2a8a2f80-93f2-11eb-8057-af2e4a7527da.png)

**Comment by NTaylorMullen** [comment] 2021-04-04 20:53
Great insight @TanayParikh!

> LiveShare was a **major** component of this trace. This is despite running this in a local session. Is this expected?

I started a thread, this seems quite concerning and I wouldn't imagine it'd be expected. Nice callout.

> 💡 [Formatting](https://github.com/dotnet/aspnetcore-tooling/blob/436191f0c5aeb836e87547aa8b5bf73909687254/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionResolver.cs#L126-L133) **absolutely dominates** the perf of Code Action Resolve. Looking at the CPU Usage details below we see formatting is responsible for 7.39% of compute time within the sequence under examination.

I'd be curious if C# had similar issues when formatting their own edits and possibly is more indicative of us needing to invest cycles into improving formatting perf.

> I believe this is a result of us doing full document formatting everytime, which would be especially costly in large documents. Range formatting comes to mind as the most direct solution, however I don't believe we have that directly implemented yet.

Unfortunately our range formatting impl just does a document format and then pulls the edits within the range 😢, something we may need to dig further into.

> I wonder if we could leverage [onTypeFormatting](https://github.com/dotnet/aspnetcore-tooling/pull/2213) here?

Hmmm, unfortunately I think that'd go too much in the other direction where we weren't formatting enough. Given the complexity of light bulbs I'd imagine them spitting out a good amount of code which we'd then need to properly react to / ensure fit in the overall form of the document. I think in the end you had some great insight into how our formatting leaks into several layers of Razor but ultimately can be really concerning from a perf perspective. FYI @davidwengier if you're curious 😉

**Comment by NTaylorMullen** [comment] 2021-04-04 20:55
> This `TraceInformation` call takes about the same time as the `RequestServerCoreAsync`. However keep in mind this is `TraceInformation` across all the requests (each request performs multiple `TraceInformation` calls and there are multiple requests (hover, completion, onautoinsert, etc.)) so it's not a 1:1 comparison.

Although it's used across several requests having logging breach the 1% boundary still seems concerning. Especially over longer usage scenarios. In the end I feel like it'd be reasonable for us to say that logging could significantly contribute to the melting of peoples CPUs 😆. Something we should think more about and potentially scale back our logging to not be repetitive/ in general be more targeted towards actionable insight.

**Comment by TanayParikh** [comment] 2021-04-05 19:40
Thanks Taylor. 

Created https://github.com/dotnet/aspnetcore/issues/31542 to track investigations into Razor Formatting / Range Formatting to improve the overall perf in that area.

Created https://github.com/dotnet/aspnetcore/issues/31541 to track adding a `/log` command line argument to indicate we want to log `TraceInformation` calls.

**Comment by TanayParikh** [comment] 2021-04-05 19:40
Adding back assignments as the task is done 😄

**Closed by TanayParikh** 2021-04-05 19:40 UTC
Labels: Perf, area-razor.tooling, feature-razor.vs
