### ISSUE TITLE
Publishing App For Blazor WASM (should generate all index file for each routes)

### ISSUE THREAD

**Issue by taprom** [dotnet/aspnetcore#40386] opened 2022-02-24 01:51 UTC
## Summary

I am describing only for blazor WASM. I have issues when pushing blazor wasm project because it only generate the index file for only the index.html. This approach is not working well when you go to the non-index route after refresh. There microsoft has introduce the redirect2 moudle specifically for the IIS hosting configuration. By that means it will yet still difficult to host in nginx or apache or github page or any other static web hosting. A better approach, blazor wasm should atomatically generate routing file for mean to serve the application routing when the user try to refresh the no-index.html page.

## Motivation and goals

In Nuxt.js, Next.js when publishing projects. There are routing index file for each route atomatically generated.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples
This is how the application files for blazor wasm files after published.
![Screenshot 2022-02-24 085033](https://user-images.githubusercontent.com/48086753/155441933-f9fa54ea-ea01-4d48-878e-4b0be084d82a.png)

**Comment by mkArtakMSFT** [comment] 2022-02-24 17:41
Thanks for contacting us. This is a dupe of https://github.com/dotnet/aspnetcore/issues/38114
Please upvote the linked one so that we can better prioritize it in the future.

**Closed by mkArtakMSFT** 2022-02-24 17:41 UTC
Labels: area-blazor, design-proposal
