### ISSUE TITLE
Make ASP.NET Core more trimmable

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#27349] opened 2020-10-29 18:25 UTC
This is more than just annotation of the framework types, which is tracked at: https://github.com/dotnet/aspnetcore/issues/27384

**Comment by mkArtakMSFT** [comment] 2020-11-04 19:33
@assigning engineers to fill in more details for this issue. Please feel free to update the description of this issue.

**Comment by davidfowl** [comment] 2020-11-11 20:40
Closing as dupe of #27384

**Closed by davidfowl** 2020-11-11 20:40 UTC
Labels: Theme: cloud native, enhancement, linker-friendliness
