### ISSUE TITLE
[Server-side] Adding 'namespace' will prevent the debug session from continuing.

### ISSUE THREAD

**Issue by vertonghenb** [dotnet/aspnetcore#5621] opened 2018-10-30 01:43 UTC
When debugging from time-to-time (especially when debugging components) 
The following error pops-up:
> Adding 'namespace' will prevent the debug session from continuing.

Although I haven't changed anything to the codebase, only stepping into and over functions.

The component itself is a GenericComponent introduced in Blazor 0.6.0.
Restarting Visual Studio, seems to solve the problem but from time-to-time the issue rises again.

Edit:
Removed component code, doesn't help at all.

**Comment by vertonghenb** [comment] 2019-01-22 16:57
Seems to be a tooling issue, maybe close this one in favor of this: https://github.com/aspnet/AspNetCore/issues/5017

**Comment by baartho** [comment] 2019-08-13 21:25
This issue is still happening in preview 8. It is a huge productivity breaker. It would be greatly appreciated if this was fixed.

**Comment by loganmarshall1** [comment] 2019-09-24 15:13
Still not fixed in 16.3.0

**Comment by alexveya** [comment] 2019-10-02 09:00
Very annoying error. Need to stop debug every time you open a new file during debuging.

Would you ever fix it?

**Comment by loganmarshall1** [comment] 2019-10-02 12:04
Agreed! Super Annoying!  If Microsoft cares about global developer productivity with core/mvc it would be important to them to fix.  So I know a fix is coming. :)

As a temporary poor work around we run without debugging so we can edit razor files without this error.

We also debug run the project in VS Code and edit the razor files in VS 2019.

Hope these 2 poor work around are helpful to people that are tired of this error not being a priority to be fixed.

Thanks!

Logan

On Oct 2, 2019, at 5:02 AM, alexveya <notifications@github.com> wrote:

﻿

Very annoying error. Need to stop debug every time you open a new file during debuging.

Would you ever fix it?

**Comment by shapeh** [comment] 2019-10-11 06:58
Getting the same in VS 2019 Community - v. 16.3.3. Windows 10 Professional.
It happens in .cshtml files and standard .cs classes.

![edit-and-continue](https://user-images.githubusercontent.com/29387615/66630726-21594180-ec05-11e9-97aa-4a1738cd29ec.PNG)

**Comment by loganmarshall1** [comment] 2019-10-15 22:43
Still not fixed 16.4 Preview 2.

Millions of global dotnet core/mvc/c#/razor developers effected.  

Billions of hours lost to having to restart build because of breakpoints.

**Comment by JasSra** [comment] 2019-10-16 01:39
Can we have a fix please, loosing too much of time in tooling rather than focusing on development

**Comment by TPucke** [comment] 2019-10-21 21:31
+1 for priority here

**Comment by satyambhatt** [comment] 2019-10-22 11:00
Same Problem I found my VS2019
![image](https://user-images.githubusercontent.com/18749122/67279733-3aa59c00-f4e9-11e9-9e21-f9127071dd7d.png)

**Comment by MiheevN** [comment] 2019-10-29 09:40
16.3.6... Why...😣😥😥😥😭

**Comment by wangpengzong** [comment] 2019-10-31 11:47
have the same problem here, I can see the error message only when debugging.

My friend told me that there may be the following reasons:
1. Changed the code inside the delegate;
2. Introduced a new namespace;

But these two actions in the project can not be avoided, how to solve?

![image](https://user-images.githubusercontent.com/29770198/67944350-3a0eb300-fc17-11e9-9219-2a49404682da.png)

**Comment by staa99** [comment] 2019-11-06 00:13
It's still here in 16.3.1
Why isn't it fixed yet? this issue has been around for over a year.

**Comment by Seabizkit** [comment] 2019-11-13 14:15
is this still a thing?

**Comment by loganmarshall1** [comment] 2019-11-13 15:49
Still not fixed in 16.3.9.

Apparently the fix is in 16.4 previews right now, but when we tested those previews this bug was still happening.

Let's pray it gets fixed in 16.4 GA.  :)

Logan

On Nov 13, 2019, at 9:16 AM, Seabizkit <notifications@github.com> wrote:

﻿

is this still a thing?

**Comment by FTalour** [comment] 2019-11-27 10:35
Temporary fix :

To continue your debug session click on the error and then delete the generated code. 

Hope it helps you.

![image](https://user-images.githubusercontent.com/19305749/69716208-e4400480-1109-11ea-89e7-b5de0d6c1267.png)
![image](https://user-images.githubusercontent.com/19305749/69716242-f3bf4d80-1109-11ea-90fb-d38a3d2970bd.png)

**Comment by Enriquecerviro** [comment] 2019-12-19 15:49
Is this still alive? not the thread, the feature I mean

**Comment by Seabizkit** [comment] 2019-12-20 11:58
> Is this still alive? not the thread, the feature I mean

bug you mean, and I'm pretty sure that the 

> Temporary fix :
> 
> To continue your debug session click on the error and then delete the generated code.
> 
> Hope it helps you.
> ...

does not work, as the issue is it randomly detects changes in JS, files or what ever file, aka there is no change, there is nothing to undo. I think you maybe experiencing something else.

now i come into this issue when i started working on another teams code, which was all over the place.... in terms of having what i consider weird ways of working, anyway i have not been active in the code base, so cant say whether or not it has been dealt with.

**Comment by Speedocs** [comment] 2019-12-31 09:31
This bug is still there in VS Enterprise 2019 16.3.10.

For me it only happens if I break inside a cshtml file, and if I remove the breakpoint I can continue normally.

This is a terrible productivity killer and it is unfortunate that this bug has not been resolved in over a year.

**Comment by loganmarshall1** [comment] 2019-12-31 13:39
It's fixed in 16.4 please update.  We've been setting break points in razor and it works great! :)

Logan

On Dec 31, 2019, at 4:31 AM, Ido Kalir <notifications@github.com> wrote:

﻿

This bug is still there in VS Enterprise 2019 16.3.10.

For me it only happens if I break inside a cshtml file, and if I remove the breakpoint I can continue normally.

This is a terrible productivity killer and it is unfortunate that this bug has not been resolved in over a year.

**Comment by SteveSandersonMS** [comment] 2020-10-06 12:51
I believe this was fixed a while ago, and VS WebAssembly debugging has moved on a long way since then. Closing.

**Closed by SteveSandersonMS** 2020-10-06 12:51 UTC
Labels: area-blazor, bug
