### ISSUE TITLE
Minimal api allows to describe response types 

### ISSUE THREAD

**Issue by uabarahona** [dotnet/aspnetcore#43708] opened 2022-09-02 01:15 UTC
### Description

Right now, it is possible to add description to response types by using `WithOpenApi`:

```csharp
.WithOpenApi(options =>
{
    options.Responses["400"].Description = "Describe what would cause this.";
    return options;
});
```

though I think a more concise way of doing it seems to be missing here, like on MVC:
![image](https://user-images.githubusercontent.com/15148088/188038296-133532bb-6f42-4006-a659-8506a53602b8.png)

✏️ Minimal APIs are looking awesome!!

**Comment by BrennanConroy** [comment] 2022-09-02 15:36
Possible dupe of https://github.com/dotnet/aspnetcore/issues/39927

**Comment by rafikiassumani-msft** [comment] 2022-09-06 22:23
Triage: Closing as a dupe.

**Closed by rafikiassumani-msft** 2022-09-06 22:23 UTC
Labels: area-web-frameworks
