### ISSUE TITLE
Blazor InputBase binding not firing NotifyFieldChanged on EditContext

### ISSUE THREAD

**Issue by partyelite** [dotnet/aspnetcore#19527] opened 2020-03-03 12:46 UTC
I'm using InputText and two way binding. 

`<InputText @bind-Value="@myValue" ></InputText>` 

when I type something in the input field the NotifyFieldChanged on CascadedEditContext is fired.

But when I change `myValue` variable from code, the value gets updated but NotifyFieldChanged is not fired.

`
@code {

    public string myValue { get; set; }

    public void Change()
    {
        myValue = Guid.NewGuid().ToString();
    }
}
`

**Comment by mkArtakMSFT** [comment] 2020-03-03 17:35
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.
The component is responsible for firing the `NotifyFieldChanged` event, not the other way around.

**Closed by mkArtakMSFT** 2020-03-03 17:35 UTC
Labels: area-blazor
