### ISSUE TITLE
Email change encounters error in Asp.net core Identity UI version 3.10

### ISSUE THREAD

**Issue by ni-fara** [dotnet/aspnetcore#28143] opened 2020-11-25 09:54 UTC
In Asp.net core Identity UI version 3.10, email change can't be accomplished successfully.

To Reproduce:
Create an ASP.NET CORE Web Application -> Web Application (Model-View-Controller) with these settings:
ASP.NET Core 3.1
Authentication sets to Individual User Accounts
Then add Identity through scaffolding.
Run the app, register a user, then try changing the user email.

Reason and solution:
In file Areas/Identity/Pages/Account/Manage/Email.cshtml.cs , method OnPostChangeEmailAsync() there should be some code to encode generated email change token, but there isn't. This code:
`code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));`
So the code doesn't get encoded and sent to user, user clicks the link in his mailbox and in ConfirmEmailChangeModel.cshtm.cs file the none encoded token gets decoded and ChangeEmailAsync fails.

In Microsoft.AspNetCore.Identity.UI version 5 it's correct but in versions 3.9 and 3.10 which i checked error exists.

**Comment by javiercn** [comment] 2020-11-25 10:53
@ni-fara thanks for contacting us.

@HaoK do you have any thoughts?

**Comment by HaoK** [comment] 2020-11-25 19:25
This is a dupe of https://github.com/dotnet/aspnetcore/issues/23438 @deepchoudhery can you confirm that fix was also included in a 3.1 servicing release?

**Closed by HaoK** 2020-11-25 19:25 UTC
Labels: area-identity
