### ISSUE TITLE
Does healthcheck close the connection properly?

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#47989] opened 2023-04-30 04:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I hit this error from pgadmin4 web connecting to an AWS RDS cluster of 2 nodes. There are on average 5 connections to the write instance. 

https://docs.sqlalchemy.org/en/20/errors.html#error-3o7r

`program.cs`:
```
    builder.Services.AddHealthChecks()
        .AddLivenessHealthCheck("Liveness", HealthStatus.Unhealthy, new List<string>() { "live" })
        .AddReadinessHealthCheck("Readiness", HealthStatus.Unhealthy, new List<string> { "ready" })
        .AddNpgSql(builder.Configuration["ConnectionStrings:Default"], "SELECT 1;", null, "PostgreSQL Health Check", HealthStatus.Unhealthy, new List<string> { "Database" })
        .AddDbContextCheck<MyDbContext>("MyDbContext", HealthStatus.Unhealthy, new List<string> { "DbContext" })
        .AddDbContextCheck<MyIAMDbContext>("MyIAMDbContext", HealthStatus.Unhealthy, new List<string> { "DbContext" });
    app.MapHealthChecks("/health/live", new HealthCheckOptions()
    {
        AllowCachingResponses = false,
        Predicate = healthCheck => healthCheck.Tags.Contains("live") || healthCheck.Tags.Contains("Database") || healthCheck.Tags.Contains("DbContext")
    });
    app.MapHealthChecks("/health/ready", new HealthCheckOptions()
    {
        AllowCachingResponses = false,
        Predicate = healthCheck => healthCheck.Tags.Contains("ready") || healthCheck.Tags.Contains("Database") || healthCheck.Tags.Contains("DbContext")
    });
```
k8s healthcheck frequency is 5 seconds.

### Expected Behavior

Healthcheck service to properly close connections.

### Exceptions (if any)

```
[pgadmin-0] 2023-04-28 09:03:33,207: ERROR	pgadmin:	QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[pgadmin-0] Traceback (most recent call last):
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask/app.py", line 1821, in full_dispatch_request
[pgadmin-0]     rv = self.preprocess_request()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask/app.py", line 2312, in preprocess_request
[pgadmin-0]     rv = self.ensure_sync(before_func)()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_principal.py", line 477, in _on_before_request
[pgadmin-0]     identity = loader()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_security/core.py", line 708, in _identity_loader
[pgadmin-0]     if not isinstance(current_user._get_current_object(), AnonymousUserMixin):
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/werkzeug/local.py", line 520, in _get_current_object
[pgadmin-0]     return get_name(local())  # type: ignore
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_login/utils.py", line 25, in <lambda>
[pgadmin-0]     current_user = LocalProxy(lambda: _get_user())
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_login/utils.py", line 372, in _get_user
[pgadmin-0]     current_app.login_manager._load_user()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 364, in _load_user
[pgadmin-0]     user = self._user_callback(user_id)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_security/core.py", line 638, in _user_loader
[pgadmin-0]     user = _security.datastore.find_user(fs_uniquifier=str(user_id))
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/flask_security/datastore.py", line 782, in find_user
[pgadmin-0]     return query.filter_by(**kwargs).first()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2752, in first
[pgadmin-0]     return self.limit(1)._iter().first()  # type: ignore
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2855, in _iter
[pgadmin-0]     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
[pgadmin-0]     return self._execute_internal(
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2114, in _execute_internal
[pgadmin-0]     conn = self._connection_for_bind(bind)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1981, in _connection_for_bind
[pgadmin-0]     return trans._connection_for_bind(engine, execution_options)
[pgadmin-0]   File "<string>", line 2, in _connection_for_bind
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
[pgadmin-0]     ret_value = fn(self, *arg, **kw)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
[pgadmin-0]     conn = bind.connect()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3251, in connect
[pgadmin-0]     return self._connection_cls(self)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
[pgadmin-0]     self._dbapi_connection = engine.raw_connection()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3275, in raw_connection
[pgadmin-0]     return self.pool.connect()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 455, in connect
[pgadmin-0]     return _ConnectionFairy._checkout(self)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1271, in _checkout
[pgadmin-0]     fairy = _ConnectionRecord.checkout(pool)
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
[pgadmin-0]     rec = pool._do_get()
[pgadmin-0]   File "/venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 157, in _do_get
[pgadmin-0]     raise exc.TimeoutError(
[pgadmin-0] sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[pgadmin-0] 118.201.248.18 - - [28/Apr/2023:09:03:33 +0000] "GET / HTTP/1.1" 500 206 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.3
```

### .NET Version

7.0.105

### Anything else?

```
.NET SDK:
 Version:   7.0.105
 Commit:    e1bc5e001c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.105/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.105 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by davidfowl** [comment] 2023-04-30 19:07
You're asking about the DbContextCheck right?

**Comment by mitchdenny** [comment] 2023-05-01 01:17
@khteh there isn't really much for us to go on here. The stack trace you are providing isn't from the ASP.NET Core application so we don't know what exception (if any) is being thrown. Additionally, the following aren't part of our API surface:

* AddLivenessHealthCheck(...)
* AddReadinessHealthCheck(...)
* AddNpgSql(...)

We would need a self-contained repro in order to investigate this issue more closely. Looking at the code for ```DbContextHealthCheck```, I doubt the problem is there. It takes a DbContext as a generic constructor argument and invokes the query callback that is supplied by the developer. It doesn't directly manage connection lifetimes.

(FWIW, you generally don't want to close connections since they are pooled, and EF abstracts a lot of that away for you).

**Comment by davidfowl** [comment] 2023-05-01 05:06
Where does AddNpgSql come from?

**Comment by khteh** [comment] 2023-05-01 05:12
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/1808

**Comment by davidfowl** [comment] 2023-05-01 05:20
Excellent. Can you close this issue?

**Comment by khteh** [comment] 2023-05-01 05:21
How sure are you this is none of the ASP.Net Core 7 issue?

**Comment by davidfowl** [comment] 2023-05-01 05:25
The only health check shipped in ASP.NET Core is the AddDbContextCheck, and I'm not sure I've seen any proof that it's causing you issues. If you can narrow down the reproduction with just that health check, then we can take another look and see what EF might be doing, or how it's configured in your application. Until then, I'm not sure what we'd investigate.

**Closed** 2023-05-01 05:28 UTC
Labels: area-healthchecks
