### ISSUE TITLE
 error ASP0023: Route '[action]' conflicts with another action route

### ISSUE THREAD

**Issue by xavierjohn** [dotnet/aspnetcore#52110] opened 2023-11-16 01:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a sample code where routes are defined as
```
[ApiController]
[Route("[controller]")]
public class AuthenticationController : ControllerBase
{
#pragma warning disable ASP0023 // Route conflict detected between controller actions
    [HttpPost("[action]")]
    public ActionResult<User> Register([FromBody] RegisterUserRequest request) =>
        FirstName.TryCreate(request.firstName)
        .Combine(LastName.TryCreate(request.lastName))
        .Combine(EmailAddress.TryCreate(request.email))
        .Bind((firstName, lastName, email) => SampleWebApplication.User.TryCreate(firstName, lastName, email, request.password))
        .ToOkActionResult(this);

    [HttpPost("[action]")]
    public ActionResult<User> RegisterCreated([FromBody] RegisterUserRequest request) =>
        FirstName.TryCreate(request.firstName)
        .Combine(LastName.TryCreate(request.lastName))
        .Combine(EmailAddress.TryCreate(request.email))
        .Bind((firstName, lastName, email) => SampleWebApplication.User.TryCreate(firstName, lastName, email, request.password))
        .Finally(result => result.IsSuccess
            ? CreatedAtAction("Get", new { name = result.Value.FirstName }, result.Value)
            : result.ToErrorActionResult(this));
```

This gives the following error
```
AuthenticationController.cs(11,15,11,25): error ASP0023: Route '[action]' conflicts with another action route. An HTTP request that matches multiple routes results in an ambiguous match error. Fix the conflict by changing the route's pattern, HTTP method, or route constraints. (https://aka.ms/aspnet/analyzers)
AuthenticationController.cs(19,15,19,25): error ASP0023: Route '[action]' conflicts with another action route. An HTTP request that matches multiple routes results in an ambiguous match error. Fix the conflict by changing the route's pattern, HTTP method, or route constraints. (https://aka.ms/aspnet/analyzers)
```

The code works in .net 7. It started to fail after upgrading to .net 8.

Here is the original sample code.
https://github.com/xavierjohn/FunctionalDDD/blob/net8/Examples/SampleWebApplication/src/Controllers/AuthenticationController.cs

### Expected Behavior

The code to compile fine in .net 8 just as it did in .net 7.

### Steps To Reproduce

Have a controller with two methods having the same HTTP attribute like 
[HttpPost("[action]")]

### Exceptions (if any)

none.

### .NET Version

8.0.100

### Anything else?

 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.8d38d0cc
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by xavierjohn** [comment] 2023-11-16 01:12
My current workaround is to suppress it
```
#pragma warning disable ASP0023 // Route conflict detected between controller actions
```

**Comment by martincostello** [comment] 2023-11-16 07:09
Duplicate of #49777 and #52066.

**Closed** 2023-11-17 10:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-web-frameworks
