### ISSUE TITLE
Incorrect swagger.json causing application hang in Minimal API when using WithOpenApi extension method with DateTime query parameter

### ISSUE THREAD

**Issue by marcominerva** [dotnet/aspnetcore#45305] opened 2022-11-28 09:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using .NET 7.0. I have created a Minimal API with the following endpoint:

```
app.MapPost("/api/people", (Person person, DateTime? dateTime) =>
{
    return TypedResults.NoContent();
});

public record class Person(string FirstName, string LastName);
```

The corresponding **swagger.json** contains the following definition:

```
"parameters": [
  {
    "name": "dateTime",
    "in": "query",
    "style": "form",
    "schema": {
      "type": "string"
    }
  }
]
```

If, however, I add a call to `WithOpenApi` extension method after the `MapPost`:

```
app.MapPost("/api/people", (Person person, DateTime? dateTime) =>
{
    return TypedResults.NoContent();
}).WithOpenApi();
```

Then the **swagger.json** changes in this way:

```
"parameters": [
  {
    "name": "dateTime",
    "in": "query",
    "style": "form",
    "schema": {
      "type": "string"
    },
    "content": {
      "application/json": { }
    }
  }
]
```

The **content** section has appeared. The result is that, if I try to call the endpoint using Swagger, with no _dateTime_ query parameter, the Minimal API totally hang. If, instead, I specify a value (let's say _2020-01-01_), the endpoint is correctly invoked. 
After that, if I try to call again the endpoint, with no query parameter, now the API is reached as expected.

### Expected Behavior

Endpoint with optional `DateTime` query parameter should not hang at the first call when I use the `WithOpenApi `extension method.

### Steps To Reproduce

Minimal repro here: https://github.com/marcominerva/MinimalApiHang.

### .NET Version

7.0.100

### Anything else?

Visual Studio 2022 17.4.1

.NET SDK:
Version: 7.0.100
Commit: e12b7af219

Ambiente di runtime:
OS Name: Windows
OS Version: 10.0.22621
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\7.0.100\

Host:
Version: 7.0.0
Architecture: x64
Commit: d099f075e4

.NET SDKs installed:
7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
x86 [C:\Program Files (x86)\dotnet]
registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
Not set

global.json file:
Not found

**Comment by captainsafia** [comment] 2022-12-01 06:01
This looks like it might be a dupe of https://github.com/dotnet/aspnetcore/issues/45365.

Omitting the `Content` property causes the UI to execute the request correctly. This behavior only happens when sending requests via the Swagger UI so I suspect that there might be an issue there.

More comments to follow in the issue linked above.

**Closed by captainsafia** 2022-12-01 06:01 UTC
Labels: area-web-frameworks
