### ISSUE TITLE
Remove -internal archives

### ISSUE THREAD

**Issue by mmitche** [dotnet/aspnetcore#27686] opened 2020-11-10 19:02 UTC
Once https://github.com/dotnet/installer/issues/9042 is completed, the -internal archives should be removed from aspnetcore. This will reduce the total artifact size, which is great.

**Comment by dougbu** [comment] 2021-06-22 21:23
@wtgodbe you're the right assignee for this. Will it happen during Preview 7❔

**Comment by wtgodbe** [comment] 2021-06-22 21:28
We can't do this until https://github.com/dotnet/installer/issues/9042 is done, I just asked the same question on that issue

**Comment by AraHaan** [comment] 2021-12-27 16:41
Could this be why I cant build the 7.0.0-dev installers now for the runtime and targeting packs resulting in build errors on tip of the main branch on all of my computers?

**Comment by wtgodbe** [comment] 2021-12-29 18:13
We haven't made this change yet, I'm not sure what's causing your errors - could you share what commands you're running to do your build, and whether those commands used to work on older runtimes (6.0, 5.0, etc) ?

**Comment by AraHaan** [comment] 2021-12-29 19:18
I was using the same commands as shown in the BuildFromSource docs on the repository, what worked was to open src/Framework/ using the startvs.bat file located there and then right click on the ref project and press build, if that did not work then I would I would right click on the Runtime project and press rebuild, then after that successfully runs it would instantly successfully pack the ref zip file when I redo the right click on the ref project and click build. After that running the last command in the docs would magically start to work without any errors. Perhaps the issue is the webpack errors causing the Microsoft.AspNetCore.Components.Authorization project to fail in command line build but magically work in VS2022 build. Although I did install NodeJS 17.3 so that might be some of the issues as well. I also updated some of the files so then I would not need to install the Windows SDKs that are older than `10.0.22000.0`. Yes I like to only have a single copy of the Windows SDK installed at all times.

**Comment by wtgodbe** [comment] 2022-09-07 21:22
@mmitche do we still need to do this?

**Comment by mmitche** [comment] 2022-09-08 17:06
I'd like to. Any removal of artifacts is good.

**Comment by ViktorHofer** [comment] 2023-01-13 09:06
Just removed the  blocked label as the SDK issue is already long merged.

**Comment by mmitche** [comment] 2023-08-04 21:40
@wtgodbe I am taking a look at this.

**Comment by wtgodbe** [comment] 2024-01-30 17:44
Done by https://github.com/dotnet/aspnetcore/pull/49879

**Closed by wtgodbe** 2024-01-30 17:44 UTC
Labels: area-infrastructure, feature-installers, severity-minor
