### ISSUE TITLE
OpenApi work with JsonPolymorphic OpenApiSchemaStore has repeat schemas

### ISSUE THREAD

**Issue by huiyuanai709** [dotnet/aspnetcore#59299] opened 2024-12-04 03:43 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

OpenApi OpenApiSchemaStore has repeat schemas

```bash
System.ArgumentException: An item with the same key has already been added. Key: MigrationOperationAlterTableOperation
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaReferenceTransformer.TransformAsync(OpenApiDocument document, OpenApiDocumentTransformerContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.ApplyTransformersAsync(OpenApiDocument document, IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)

```

![Image](https://github.com/user-attachments/assets/6bb0da3a-a1ba-4041-9a07-f9214ff2749d)

### .NET Version

9.0.100

**Comment by huiyuanai709** [comment] 2024-12-04 06:07
OpenApiSchema differences
![Image](https://github.com/user-attachments/assets/981ecc1b-a9e1-49cf-9bd9-6d7f329ae0df)

**Comment by martincostello** [comment] 2024-12-04 07:17
Duplicate of #58213

**Closed** 2024-12-04 08:26 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-mvc, Status: Resolved, feature-openapi
