### ISSUE TITLE
ManifestEmbeddedFileProvider errors when also embedding a resx.

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#29305] opened 2021-01-14 14:45 UTC
<!--

More information on our issue management policies can be found here: https://aka.ms/aspnet/issue-policies

### Describe the bug
I am seeing the same issue that was described here: https://www.gitmemory.com/issue/aspnet/Extensions/1333/507701113
II get a runtime exception constructing the `ManifestEmbeddedFileProvider` because it complains that the format of it's embedded manifest file is wrong - even though this is produced for me (i.e by the build task).

![image](https://user-images.githubusercontent.com/3176632/104605573-94f2c580-5676-11eb-93b8-1fc90e31ed31.png)

On looking around I came accross the above link and can confirm it only happens in the project on which I also am embedded a resx file i.e I have these additional csproj entries:

```
 <ItemGroup>
        <Compile Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>PlatformSeedData.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>PlatformSeedData.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

```

### To Reproduce
Create a vanilla csproj project, include the `ManifestEmbeddedFileProvider` but also set up an embedded RESX file like so:

```
 <ItemGroup>
        <Compile Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>PlatformSeedData.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Apps\PlatformSetup\Services\Resources\PlatformSeedData.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>PlatformSeedData.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
```

Start your application and create an instance of the file provider. 

### Exceptions (if any)
As shown above.

### Further technical details
- ASP.NET Core version: 3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by javiercn** [comment] 2021-01-14 15:06
Dupe of https://github.com/dotnet/aspnetcore/issues/29306

**Closed by javiercn** 2021-01-14 15:06 UTC
