### ISSUE TITLE
Blazor WASM 3.2.0-preview3 VS2019 Debugging not working on Edge

### ISSUE THREAD

**Issue by vulcanlee** [dotnet/aspnetcore#20263] opened 2020-03-28 03:44 UTC
### Describe the bug
I have upgrade to Visual Studio 2019 16.6 Preview 2 and confirm .NET Core 3.1 SDK is Version 3.1.201 and the Blazor WebAssembly template also upgrade.

If I create a Blazor WebAssembly project and run on Edge Browser and set breakpoint on Visual Studio , the debug function not working.

But if I run the same project on Chrome Browser, it is working fine and the break point also work fine.

### To Reproduce

* Create a new Blazor WebAssembly (without choice ASP.NET Core hosted)
* To start this project on Microsoft Edge browser
* Set a breakpoint in Counter.razor in the IncrementCount method.
* Browser to the Counter tab and click the button and the breakpoint will not work.
* Stop the project 
* And re-start this project on Google Chrome browser
* Set a breakpoint in Counter.razor in the IncrementCount method.
* Browser to the Counter tab and click the button to hit the breakpoint

Following is my operation recording

[Recording Video (no sound)](https://vulcanfiles.blob.core.windows.net/$web/Share/2020/Blazor%20WASM%203.2.0-preview3%20VS2019%20Debugging%20not%20working%20on%20Edge.mp4)

### Further technical details

* VS 2019 pro PREVIEW 16.6.0 Preview 2.0

* Windows 10 Pro build 18363.720

* MS Edge Version 80.0.361.69 (Official build) (64-bit)

* Google Chrome Version 80.0.397.149

* .NET Core SDK Version: 3.1.300-preview-015048

**Comment by mkArtakMSFT** [comment] 2020-03-30 16:40
Thanks for contacting us.
Unfortunately, we are unable to reproduce this behavior to be able to investigate this.
Can you please reinstall Edge browser (in case there are some settings which got messed up).
And second option, try to repair the VS installation.

This is experimentation, as we couldn't reproduce this.

**Comment by vulcanlee** [comment] 2020-04-01 02:08
@mkArtakMSFT 

I have reinstall Edge browser and repair the VS installation, but the problem is not solve.

When I run by Edge browser, the breakpoint of Visual Studio show following message:

**The breakpoint will not currently be hit. No symbols have been loaded for this document.**

But I run by Chrome browser, the breakpoint will work fine.

![](https://vulcanfiles.blob.core.windows.net/$web/Share/2020/The_breakpoint_will_not_currently_be_hit.png)

**Comment by vulcanlee** [comment] 2020-04-01 14:15
@mkArtakMSFT 

I tried to build the Blazor WebAssembly App with or without ASP.NET Core hosted mode, and both of them executed the project under IIS.

The test result is that when the browser used is Edge, the breakpoint set by Visual Studio is invalid.

**Comment by mkArtakMSFT** [comment] 2020-04-01 16:30
Thanks for the details, @vulcanlee.
Unfortunately we are unable to reproduce this issue to help you out.
If you can come up with some instructions on how to get to the same state, we will happily investigate.
For now, however, given that we are unable to move forward here, I'm going to close this issue.

**Call to others**": If you happen to face the same issue and have some more information to add, please share.

**Closed** 2020-04-01 16:31 UTC
Labels: Needs: Attention :wave:, area-blazor, blazor-wasm, investigate
