### ISSUE TITLE
VSCode: Razor implicit/explicit expressions in HTML attributes are not colored properly

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#36822] opened 2021-09-21 22:32 UTC
This was originally fixed by updating the textmate grammar to account for implicit/explicit expressions in HTML attributes. If my memory serves me correctly, the textmate grammar was removed at some point due to semantic colorization. As a result, we don't have colorization in attributes again. Didn't see another issue for this already, so created this.

![image](https://user-images.githubusercontent.com/14852843/134256206-fd64cc8c-d6cd-4db7-91fd-94a7ab177ea7.png)

Original Issue: https://github.com/dotnet/aspnetcore/issues/20140
Fix PR: https://github.com/dotnet/aspnetcore-tooling/pull/1824

**Comment by ryanbrandenburg** [comment] 2021-09-23 21:07
Dupe of https://github.com/dotnet/aspnetcore/issues/26479.

**Closed by ryanbrandenburg** 2021-09-23 21:07 UTC
Labels: bug, :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-razor.tooling, feature-razor.vscode
