### ISSUE TITLE
IHubContext<out THub>

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/aspnetcore#30542] opened 2021-03-01 03:13 UTC
I have these two classes:
1. `HubBase`: abstract hub base class in a library
2. `DerivedHub`: hub that derives from it in an app

I must accept `IHubContext` via dependency injection.  A constructor with a parameter of type `IHubContext<HubBase>` corresponds to the wrong hub type.  I need it to be of type `IHubContext<DerivedHub>`.  That part is doable but a problem arises with then passing the hub context to my library code.  My library only knows about `HubBase`.  To be able to pass the `HubContext`, it needs to be defined as `IHubContext<out THub>`.  Its declaration currently lacks the `out`.  Please add it.

**Comment by BrennanConroy** [comment] 2021-03-01 21:12
Dupe of https://github.com/dotnet/aspnetcore/issues/30167

**Comment by HappyNomad** [comment] 2021-03-01 21:40
@BrennanConroy Well, it's an alternative approach for tackling the same problem.  The non-generic `IHubContext` idea mentioned there would work for me, too.

**Closed** 2021-03-03 21:02 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-signalr
