### ISSUE TITLE
IIS is stuck while restarting local server

### ISSUE THREAD

**Issue by vonzshik** [dotnet/aspnetcore#25163] opened 2020-08-23 13:32 UTC
### Describe the bug
IIS is stuck while restarting local server. As long as there is one client application, which has undisposed `HttpClient`, IIS would be stuck.

### To Reproduce

Only reproducible on Windows 10 2004.
https://github.com/vonzshik/AspNetCoreBug

Publish asp project, then start it from IIS. After that, start client app. While it's waiting after successful request, restart through IIS local server. Until client app is closed, IIS would be stuck restarting. The problem seems to be from `HttpClient`.

### Further technical details
- ASP.NET Core version
5.0.0-preview.5.20279.2
- Include the output of `dotnet --info`
[dotnet-info.txt](https://github.com/dotnet/aspnetcore/files/5113975/dotnet-info.txt)
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
Visual Studio 16.7.0

**Comment by jkotalik** [comment] 2020-08-24 20:10
@vonzshik we have been internally investigating this issue as well; the parameters you have set match the behavior issues I'm hitting as well.

Would it be possible for you to try a few different configurations:
1. Change the client app to target 3.1
2. Change the server app to target 3.1
3. If you see the same behavior between IIS and IISExpress.

At this moment we don't believe it's an issue in ANCM or anything in the AspNetCore stack.

**Comment by jkotalik** [comment] 2020-08-24 20:19
Also, could you get the exact windows version by running winver and getting the entire string after Version 2004.

**Comment by vonzshik** [comment] 2020-08-26 09:20
> 1. Change the client app to target 3.1
> 2. Change the server app to target 3.1
> 3. If you see the same behavior between IIS and IISExpress.

Yes, same issue for both IIS and IISExpress. Checked for .net 5 and .net core 3.1.

> Also, could you get the exact windows version by running winver and getting the entire string after Version 2004.

Windows 10 Pro 2004 (OS Build 19041.450)

**Comment by jkotalik** [comment] 2021-02-10 21:29
@vonzshik are you still able to reproduce this? We have seen this not repro after future updates to windows. We originally had issues on our CI, but they went away after updates.

**Comment by vonzshik** [comment] 2021-02-11 11:45
@jkotalik just a few moments ago I did update to the latest available version (20H2, 19042.804), and the problem is still reproducible :(

**Comment by adityamandaleeka** [comment] 2021-09-08 20:48
@HaoK Can you please investigate this when you have some time?

**Comment by HaoK** [comment] 2021-09-14 21:49
So the behavior I see when I tried this today on my laptop: Win10 21H1 Build 19043.1165

I see the first IIS attempt gives an error, but a second iisreset will work:

C:\TestSite\logs> iisreset

Attempting stop...
Restart attempt failed.
Access denied, you must be an administrator of the remote computer to use this
command. Either have your account added to the administrator local group of
the remote computer or to the domain administrator global group.
C:\TestSite\logs> iisreset

Attempting stop...
Internet services successfully stopped
Attempting start...
Internet services successfully restarted
C:\TestSite\logs>

@Tratcher does this behavior seem reasonable?  Note I'm running as administrator, so the first iisreset error is a bit misleading, but that could be failing due to the HttpClient client, as it seems to timeout, and then the second run succeeds immediately

**Comment by Tratcher** [comment] 2021-09-14 22:19
That's problematic, but it's at least a workaround.

We still want to figure out why we get the first error. This sounds a lot like the issue we have in unit tests where the server won't shutdown.

**Comment by HaoK** [comment] 2021-09-14 22:30
Yeah it does, I should see if a double iisreset helps with our unit tests too

**Comment by vonzshik** [comment] 2021-10-07 06:22
@HaoK it does timeout after about 90 seconds.

**Comment by HaoK** [comment] 2022-02-14 22:56
Tracking this as a dupe of https://github.com/dotnet/aspnetcore/issues/25107

**Closed by HaoK** 2022-02-14 22:56 UTC
Labels: bug, External, area-runtime, Needs: Attention :wave:, affected-few, severity-major
