### ISSUE TITLE
[Blazor] Support for rendering client-side components from MVC

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#14434] opened 2019-09-25 18:40 UTC
As we look forward to ship blazor client-side support in May, we want to provide a great experience when using blazor in ASP.NET Core 3.0

As part of that experience we want ASP.NET Core applications to be able to render one or more blazor client-side components with parameters into the page. 

To avoid having to create an additional package or have a subpar experience during the initial release, we want to include the pieces needed in MVC to support rendering client side components from the server.

The idea is that it reuses the same infrastructure we already have in place for server-side blazor and we simply create a new type of descriptor that renders the component into the page.

As part of this work, we only plan to do the minimal thing required to avoid having to ship either an interim release of ASP.NET Core before 5.0 or to have to ship one-time separate package.

The work here simply consists in adding a couple of values to an existing enumeration (Client, ClientPrerendered) and when those are specified, generate the required HTML output (very similar to the one we generate for server-side components) into the page.

**Comment by mkArtakMSFT** [comment] 2019-10-01 22:17
Per the discussion in the PR moving this to 5.0

**Comment by mkArtakMSFT** [comment] 2020-01-10 18:40
@javiercn what's the status here?

**Comment by javiercn** [comment] 2020-01-10 18:53
@mkArtakMSFT We didn't do this for 3.1, but I want to tackle this in some form as part of the blazor-wasm release by adding helpers on the Blazor.Server package.

On the 5.0 timeframe we can move this to MVC itself

**Comment by Tealons** [comment] 2020-05-07 08:10
We want to start converting our existing MVC application to Blazor + Azure Functions, however we want to do this step by step. Currently we see no way of doing this? Will this issue help enable this scenario?

**Comment by mkArtakMSFT** [comment] 2020-07-28 17:00
This is a dupe of https://github.com/dotnet/aspnetcore/issues/24098

**Closed by mkArtakMSFT** 2020-07-28 17:00 UTC
Labels: area-blazor, enhancement
