### ISSUE TITLE
Loop within RenderTreeBuilder causes endless loading 

### ISSUE THREAD

**Issue by colosso** [dotnet/aspnetcore#50659] opened 2023-09-12 14:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a custom component called "RadioButtonList". This control overrides RenderTreeBuilder to create a list of radio button Controls by looping through a string List of strings to create one radio button for each string.

This does basically work but it seems only to work until a certain point: If there are more than ~16 (somtimes 30, sometimes 60) iterations within the override, it causes the application to  load forever. There is no error, no message, neither in VS nor in the browser. Not even something visible in the network log.

It seems to work if the Components that are generated are in RenderModeWebassembly, but that would make it impossible to trigger serverside methods...

### Expected Behavior

The RenderTreeBuilder should build the Page and load it correctly, instead it gets stuck in a loading loop without any trace what is happening.

### Steps To Reproduce

Minimal Example: https://github.com/colosso/Net8LoopError
(uncomment Line 19 in RadioButtonList.cs to cause the bug to appear)

or Manually:
1. Create Blazor App with .NET Preview 8
2. Create a class that Implements "ComponentBase", Override RenderTreeBuilder
```
 public class Test : ComponentBase
 {

     protected override void BuildRenderTree(RenderTreeBuilder builder)
     {
```
4. Within the RenderTreeBuilder, add:
```
 base.BuildRenderTree(builder);
 int y = 0;
 for (int i = 0; i < 70; i++) 
 {
     builder.OpenComponent(y++, typeof(LabelX));
     builder.CloseComponent();
 }
```
"LabelX" can be replaced with any type of control that uses `@attribute [RenderModeServer]`

5. Application will not load anymore

### Exceptions (if any)

Would be great to know why this happens and how to keep it from happening

### .NET Version

8.0.100-preview.7.23376.3

**Comment by javiercn** [comment] 2023-09-12 16:38
@colosso thanks for contacting us.

We believe this is a dupe of https://github.com/dotnet/aspnetcore/issues/50640

It's fixed in RC2.

In addition to that, 

```
 for (int i = 0; i < 70; i++) 
 {
     builder.OpenComponent(y++, typeof(LabelX));
     builder.CloseComponent();
 }
```

Will not result in good diffing behavior.

**Comment by javiercn** [comment] 2023-09-12 16:38
See https://learn.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-7.0#sequence-numbers-relate-to-code-line-numbers-and-not-execution-order and https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0006?view=aspnetcore-7.0

**Closed** 2023-09-12 16:39 UTC
Labels: area-blazor
