### ISSUE TITLE
What does the descriptor property of StartCircuit arguments represent?

### ISSUE THREAD

**Issue by jababda** [dotnet/aspnetcore#26040] opened 2020-09-18 00:59 UTC
Context, we're getting an odd issue occurring in Chrome where after navigating to our server side blazor page, leaving the page for ~5 mins in the same tab and then returning to page using the **back button**.

Running Net Core 3.1 in IISExpress using windows auth with no anon access. 
VS 2019 Pro
dotnet --info
Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

The error being logged is:
`System.Security.Cryptography.CryptographicException: The payload expired at 16/09/2020 7:07:13 AM +00:00.
   at Microsoft.AspNetCore.DataProtection.TimeLimitedDataProtector.UnprotectCore(Byte[] protectedData, DateTimeOffset now, DateTimeOffset& expiration)
   at Microsoft.AspNetCore.DataProtection.TimeLimitedDataProtector.Unprotect(Byte[] protectedData, DateTimeOffset& expiration)
   at Microsoft.AspNetCore.DataProtection.TimeLimitedDataProtector.Microsoft.AspNetCore.DataProtection.IDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Components.Server.ServerComponentDeserializer.DeserializeServerComponent(ServerComponentMarker record)`

The only shared component between the requests is the value of **descriptor** in the logged message (Using Serilog)
`(Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher) Received hub invocation: InvocationMessage { InvocationId: "0", Target: "StartCircuit", Arguments: [ https://localhost:44352/dashboard/, https://localhost:44352/dashboard/, [{"type":"server","sequence":0,"descriptor":"<value here>"}] ], StreamIds: [  ] }.`

We get a different error in edge when we run the same scenario but much further into the application after we impersonate a windows user to make a web request to our api server so I suspect the problem stems from the browsers doing some odd caching of the windows auth that get provided via the descriptor value. 

I don't know if this is expected behavior or not but without understanding exactly what the descriptor property represents I don't think I can fix the route cause.

Any help or direction would be hugely appreciated!

**Comment by jababda** [comment] 2020-09-18 01:01
Migrating over from https://github.com/dotnet/aspnetcore/discussions/25947.

**Comment by captainsafia** [comment] 2020-09-22 16:40
Thanks for migrating this issue over. It looks like it's a duplicate of #24626. We'll use the original issue to track/

**Closed by captainsafia** 2020-09-22 16:40 UTC
Labels: area-blazor
