### ISSUE TITLE
Why does ForwardedHeadersMiddleware remove headers from the request?!

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#43344] opened 2022-08-17 10:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I see middleware [removes](https://github.com/dotnet/aspnetcore/blob/9b736b467a87494c28cf8a3d77cd4e6f9ffd2e86/src/Middleware/HttpOverrides/src/ForwardedHeadersMiddleware.cs#L356) header it consumed.

Nowhere in documentation it is said the headers will be removed. Is it a necessity?

### Describe the solution you'd like

Well, at least I'd expect a clear indication of this behavior either from method name or in the docs.
If this behavior is optional and there's no fundamental requirement to always drop the headers, I'd like to have a configuration parameter for it.

**Comment by Tratcher** [comment] 2022-08-17 16:14
Yeah, manipulating the headers was in hindsight a bad design. Duplicate of https://github.com/dotnet/aspnetcore/issues/39423

**Closed** 2022-08-18 19:01 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime, Status: Resolved
