### ISSUE TITLE
IHtmlContent can break ExceptionHandlerMiddleware and DeveloperExceptionPgaeMiddleware. Resulting in a blank page in production.

### ISSUE THREAD

**Issue by Banner-Keith** [dotnet/aspnetcore#50825] opened 2023-09-19 21:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have encountered a scenario where we have an old HTML helper that doesn't really fit in the tag helper box very well. I don't want to go into why in this ticket. We ported it to core and have the Helper class implement `IHtmlContent`

If an exception is thrown inside of the helper it returns a blank page to the end users. This can happen when debugging locally or in production.

What seems to be happening is that some middleware is starting a response before the error is handled by the `ExceptionHandlerMiddleware`  or the `DeveloperExceptionPageMiddleware`.

If you look at the debug window or console output you'll see one of these two errors:

`Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Warning: The response has already started, the error handler will not be executed.`

OR

`Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Warning: The response has already started, the error page middleware will not be executed.`

This is a critical issue as it impacts deployed production sites in addition to local development.

### Expected Behavior

For local debugging the Developer Exception page should be displayed.

For production the Exception Handler should execute.

### Steps To Reproduce

Here's a minimal example of the problem. This consists of a brand new MVC project targeting .net 6 although it also happens in .net 7. I simply added an example class that implements `IHtmlContent` and throws an exception. All that is needed is to construct an instance of that class in a view, although a more real-world use case is to use an `IHtmlHelper` extension method so I have included that commented out.

*IMPORTANT*
I have included two profiles in `launchsettings.json`. One runs in development mode to demonstrate the developer exception page issue. The other is in production mode to demonstrate the exception handler issue.

https://github.com/Banner-Keith/DeveloperExceptionPageRepro

In Main method:
``` C#
if (app.Environment.IsDevelopment())
{
	app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Error");
}
```

New classes
``` C#
public class TestHtmlWriter : IHtmlContent
{
	public void WriteTo(TextWriter writer, HtmlEncoder encoder)
	{
		throw new InvalidOperationException("Test");
		writer.Write(new StringBuilder("<h1>Hello World!</h1>"));
	}
}

// Optional Extension Method
public static class TestHtmlHelperExtensions
{
	public static TestHtmlWriter TestHtmlWriter(this IHtmlHelper helper)
	{
		return new TestHtmlWriter();
	}
}
```
And in the view:
```razor
@(new TestHtmlWriter())
@* Optional extension method example *@
@Html.TestHtmlWriter()
```

### Exceptions (if any)

System.InvalidOperationException: Test
   at WebApplication1.TestHtmlWriter.WriteTo(TextWriter writer, HtmlEncoder encoder) in C:\Users\BANNKN\OneDrive - Idaho National Laboratory\Documents\My Web Sites\WebApplication1\WebApplication1\Program.cs:line 45
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers.ViewBuffer.WriteToAsync(TextWriter writer, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Warning: The response has already started, the error page middleware will not be executed.
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

### .NET Version

7.0.400 and 6.0.414

### Anything else?

.NET 6.0.22 and 7.0.11

Visual Studio Version 17.7.3

.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  6.0.414 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by mkArtakMSFT** [comment] 2023-10-10 17:03
Thank you for your feedback.
We're closing this issue as the behavior discussed is by design.

The best practice to do anything that might throw an exception before starting rendering, because at that point it's too late to render an error page. This is because some content has already been written to the response stream and you can't mix up content.

**Closed by mkArtakMSFT** 2023-10-10 17:03 UTC
Labels: area-ui-rendering
