### ISSUE TITLE
[Feature Request] Remove magic strings from RazorPages routing

### ISSUE THREAD

**Issue by lonix1** [dotnet/aspnetcore#41930] opened 2022-05-31 00:49 UTC
ASP.NET Core 6

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

A RazorPages route can be defined like this:
````razor
@page "/Foo"
````
But these magic strings are bad, let alone in a large system where there are hundreds of them. I want to define them as constants in a central location.

There are StackOverflow questions with **many** creative solutions, but none work, e.g. [1](https://stackoverflow.com/q/66894753), [2](https://stackoverflow.com/q/54941524).

### Describe the solution you'd like

I want to be able to do something like this:
- define my routes
  ````cs
  public static class Routes {
    public const Foo = "/Foo";
    public const Bar = "/Qux/Bar";
  }
  ````
- use route in page
  ````razor
  @page @Routes.Foo
  ````

I can use `Routes` from the pages themselves, but also for generating links and everywhere else. No magic strings anymore.

Alternative:
````razor
@page @ROUTE
@functions { public const string ROUTE = "/Foo"; }
````

### Additional context

I understand that the runtime needs to build a routing table on start, so they need to be compile-time constants. So meet us halfway and allow some mechanism to use constants instead of magic strings. The current mechanism is very hard to manage when scaling beyond a few pages.

**Comment by davidfowl** [comment] 2022-05-31 02:24
Any reason not to declare the routes centrally:

```C#
builder.Services.AddRazorPages(options =>
{
    options.Conventions.AddPageRoute("/Foo", "/foo"); // Redundant
    options.Conventions.AddPageRoute("/Qux", "/something/else"); // Redundant
});
```

**Comment by lonix1** [comment] 2022-05-31 02:38
Like others in those linked SO questions (~ 3k views), I'd prefer to do it per-page as I showed in the sample code above. Then every page is self contained and I don't need to configure it in two places. Also there is only one string per page whereas in that lambda there are two, and one is path-dependent; so more can change/fail.

Nonetheless... your solution helps - thanks!

The way I described above though, with a constant used in the razor page `@page Routes.Foo.Bar` or `@page ROUTE` - is it not possible due to a technical limitation?

**Comment by davidfowl** [comment] 2022-05-31 04:12
Help me understand, are you saying you want to declare the route in every page but then centrally manage a list of constants? Or is that list not central? I'm not debating if this feature is useful or not but I'm trying to understand. Is it about the page name or the page route? Is it about centralizing configuration or something else?

**Comment by javiercn** [comment] 2022-05-31 08:49
@lonix1 thanks for contacting us.

This is a dupe of https://github.com/dotnet/aspnetcore/issues/8065. Our tooling relies on being able to know the route without having to compile time evaluate C#, which is why we don't support this.

**Comment by lonix1** [comment] 2022-05-31 08:53
@javiercn Yes I know that is a good technical reason. But I couldn't understand why we can't use `const` variables.

````razor
@page @MyRoute
@functions { public const string MyRoute = "/Foo"; }                  <---- constant
````

or 

````razor
@page @Routes.MyRoute                             <---- constant defined in other static class
````

or one of the other solutions I found on StackOverflow. Like using the routing attributes, etc.

In all cases I tried compile-time constants.

**Closed** 2022-06-01 10:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-mvc, feature-razor-pages, Status: Resolved

**Comment by lonix1** [comment] 2022-06-15 12:44
I've deleted the old comments which are long enough to ensure they are never read.

We must use constants. So why can't we do this:

````razor
@page @MyRoute
@functions { public const string MyRoute = "/Foo"; }                  <---- constant
````

or 

````razor
@page @Routes.MyRoute                             <---- constant defined in other static class
````

or one of the other solutions on StackOverflow. Like using the routing attributes, etc.
