### ISSUE TITLE
Dotnet new react template using function components

### ISSUE THREAD

**Issue by devklick** [dotnet/aspnetcore#43770] opened 2022-08-14 16:05 UTC
### Is your feature request related to a problem? Please describe.
Using the `dotnet new react` template generates a client app that uses class-based components. As far as I can tell, there is no option to generate function components when using this template. As it seems like the go-to approach for building react applications these days is using function components, I think it would be useful to support this option (perhaps even use it as the default).

### Describe the solution you'd like
Have I missed something - is it possible to create function components rather than class components when using the `dotnet new react` template? 

If not, perhaps this could be considered in a future update.

### Additional context

**Comment by vlada-shubina** [comment] 2022-09-06 07:47
Team, we got the issue on `react` template, could you please check it and see if this enhancement is visible? Thank you

**Comment by javiercn** [comment] 2022-09-07 11:17
@vlada-shubina thanks for redirecting.

@devklick this is not currently possible with our out of the box template. There is some ongoing community work to update the current react template to support this, but it won't be part of .NET 7.0

**Comment by javiercn** [comment] 2022-09-07 11:18
This is a dupe of https://github.com/dotnet/aspnetcore/issues/40540

**Closed by javiercn** 2022-09-07 11:18 UTC
Labels: area-mvc, untriaged
