### ISSUE TITLE
.net core web

### ISSUE THREAD

**Issue by tbluesky2012** [dotnet/aspnetcore#33682] opened 2021-06-19 14:30 UTC
![image](https://user-images.githubusercontent.com/12482184/122645560-8b9de580-d14d-11eb-9461-dfd5009324bd.png)
![image](https://user-images.githubusercontent.com/12482184/122645593-a708f080-d14d-11eb-8753-ea446ff62a9c.png)
These code can run without errors, but when i scan this websit in my browser, it throws an error as the following:
     'Object reference not set to an instance of an object'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceStart(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)
   at ConsoleApp.NetCore.Startup.<>c.<<Configure>b__1_0>d.MoveNext() in D:\PersonalSpace\ConsoleApp.NetCore\ConsoleApp.NetCore\Startup.cs:line 16

**Comment by BrennanConroy** [comment] 2021-06-21 20:25
Can you please include what version of ASP.NET Core you're using? And if possible provide a minimal GitHub repo that reproduces the issue?

**Comment by BrennanConroy** [comment] 2021-06-21 20:28
This looks like a dupe of https://github.com/dotnet/aspnetcore/issues/28112

The issue was referencing old packages https://github.com/dotnet/aspnetcore/issues/28112#issuecomment-733662430

**Closed** 2021-06-28 22:00 UTC
Labels: Needs: Author Feedback, Status: No Recent Activity, area-runtime
