### ISSUE TITLE
Not able to debug blazorwasm project in VSCode

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/aspnetcore#40568] opened 2022-03-07 08:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Continuation of https://github.com/dotnet/aspnetcore/issues/28755. 
The problem still persists, even sample application cannot get debugged. Both configurations: of blazorwasm type and suggested by @[captainsafia](https://github.com/captainsafia) two step configuration. In both cases, the application launches but no symbols get loaded for Client.csproj.

VS Code: 1.64
Dotnet: 6.0.1

All the reproduction steps given in the referenced issue.

**Comment by TanayParikh** [comment] 2022-03-07 17:05
We believe this is a duplicate of https://github.com/dotnet/aspnetcore/issues/38413. Can you please confirm all your extensions (primarily O#) are updated to the latest. If not, please try the VSCode Insiders build which will should have the requisite fix in https://github.com/microsoft/vscode-js-debug/issues/1190.

**Closed** 2022-03-14 19:00 UTC
Labels: Needs: Author Feedback, area-blazor, blazor-wasm, Status: No Recent Activity, feature-blazor-debugging
