### ISSUE TITLE
Link is mis-rendering based on the current page

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#24455] opened 2020-07-30 23:20 UTC
I have a Razor Pages application with the following markup in my **_Layout.cshtml** file.

    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Reports
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" asp-area="Reports" asp-page="/Invoice/Index">Invoices</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Reports" asp-page="/ProfitabilityByCustomer/Index">Profitability by Customer</a>
            <a class="dropdown-item" asp-area="Reports" asp-page="/ProfitabilityByLocation/Index">Profitability by Location</a>
            <a class="dropdown-item" asp-area="Reports" asp-page="/CostAudit/Index">Cost Audit</a>
            <a class="dropdown-item" asp-area="Reports" asp-page="/ChangeLogs/Index">Change Logs</a>
        </div>
    </li>

Notice the last link (to **/ChangeLogs/Index**). This page has a page route (`@page "{id?}"`).

This markup appeared to be rendering correctly. But then I manually navigated to **/Reports/ChangeLogs/61**, and the markup above rendered as:

    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Reports
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/Reports/Invoice">Invoices</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/Reports/ProfitabilityByCustomer">Profitability by Customer</a>
            <a class="dropdown-item" href="/Reports/ProfitabilityByLocation">Profitability by Location</a>
            <a class="dropdown-item" href="/Reports/CostAudit">Cost Audit</a>
            <a class="dropdown-item" href="/Reports/ChangeLogs/61">Change Logs</a>
        </div>
    </li>

Notice the route value of the current page was appended to that last link. Somehow, the fact that the current page is **/Reports/ChangeLogs/61**, is causing the link in the menu to render with this route value!

I can't explain this. And I need to stop it from happening.

### Further technical details
- ASP.NET Core 3.1
- Visual Studio 16.6.4 (Windows)
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment] 2020-08-04 16:49
Thanks for contacting us. @javiercn do we have a separate issue tracking this?

**Comment by MackinnonBuck** [comment] 2022-11-10 17:01
I was able to reproduce this behavior, but I'm not necessarily convinced it's a bug. Route values from the current request are reused in link generation (see https://learn.microsoft.com/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#ambient-values-and-explicit-values), and I think that might apply to this case as well. You can override route values in the link by adding attributes to the `<a>` tag like `asp-route-<name>="<value>"` where 'name' and 'value' correspond to the name of the route value and its actual value respectively.

@javiercn Does my assessment seem correct that this is by design?

**Comment by MackinnonBuck** [comment] 2022-11-10 19:10
@SoftCircuits does the [`asp-route-{value}`](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-6.0#asp-route-value) workaround address your needs?

**Comment by SoftCircuits** [comment] 2022-11-10 19:47
@MackinnonBuck I don't know what I would specify for `{value}`. I don't want any parameter passed. The parameter is optional on that page, and I don't want to specify any parameter here. I want the URL to just be */Reports/ChangeLogs*.

This is from 2 1/2 years ago. I don't recall exactly how I worked around it.

**Comment by MackinnonBuck** [comment] 2022-11-10 20:51
@SoftCircuits if the `/ChangeLogs/Index` page has a route pattern defined like `@page "{id?}"`, then you could change its corresponding `<a>` in `_Layout.cshtml` to:

```razor
<a class="dropdown-item" asp-area="Reports" asp-page="/ChangeLogs/Index" asp-route-id="">Change Logs</a>
```

> This is from 2 1/2 years ago. I don't recall exactly how I worked around it.

That's fine! I'm going to close this issue as by-design for now, but we can reopen it if we get more feedback from the community that we should improve this behavior. Thanks!

**Closed by MackinnonBuck** 2022-11-10 20:51 UTC
Labels: bug, area-mvc, triaged, feature-routing, affected-most, severity-minor
