### ISSUE TITLE
HTTP logging + response body logging breaks gRPC.

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#48824] opened 2023-06-15 05:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/grpc/grpc-dotnet/issues/2160

### .NET Version

7.0.107

**Comment by BrennanConroy** [comment] 2023-06-15 16:19
Looks like a dupe of https://github.com/dotnet/aspnetcore/issues/39317

**Closed** 2023-06-16 19:00 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-middleware
