### ISSUE TITLE
Improve handling of JSDisconnectedExceptions

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#53571] opened 2024-01-23 16:20 UTC
Reported by @denisbredikhin:

Currently this exception is thrown every time when web socket is already disconnected, by any reason, and when we perform some communication with JS runtime. This exception is not thrown to end-user, but it clogs log files and hinders debugging. In a complex application with a lot of third-party components it is almost impossible to know which code will perform communication with JS runtime. As a result, if we want to avoid this exception, we need to add try/catch to all the places of our code.

**Comment by javiercn** [comment] 2024-01-24 11:45
@danroth27 isn't this a dupe of https://github.com/dotnet/aspnetcore/issues/45267 which was fixed and patched in https://github.com/dotnet/aspnetcore/pull/53297

**Closed** 2024-01-24 18:03 UTC
Labels: enhancement, area-blazor
