### ISSUE TITLE
SystemTextJsonInputFormatter model state key is not equal to model property name

### ISSUE THREAD

**Issue by tai-yi** [dotnet/aspnetcore#24104] opened 2020-07-20 07:51 UTC
### Describe the bug
different behavior between `SystemTextJsonInputFormatter`  and `NewtonsoftJsonInputFormatter`

NewtonsoftJsonInputFormatter
```C#
var key = ModelNames.CreatePropertyModelName(context.ModelName, path);
exception = eventArgs.ErrorContext.Error;
var metadata = GetPathMetadata(context.Metadata, path);
var modelStateException = WrapExceptionForModelState(exception);
context.ModelState.TryAddModelError(key, modelStateException, metadata);
...
```
SystemTextJsonInputFormatter
```C#
try
{
    model = await JsonSerializer.DeserializeAsync(inputStream, context.ModelType, SerializerOptions);
}
catch (JsonException jsonException)
{
    var path = jsonException.Path;

    var formatterException = new InputFormatterException(jsonException.Message, jsonException);

    context.ModelState.TryAddModelError(path, formatterException, context.Metadata);

....
```

### To Reproduce

```C#
//API request model
public class MyModel{
     public string Name{get;set;}

     public byte[] Image{get;set;}
}

//Controller Action
[ApiController]
public class MyController: ControllerBase{

  [HttpPost]
  public IActionResult Post(MyModel model){
      return Ok();
  }
}
```

send error json request as below

```JSON
{
   "name":"sample-user",
   "image":"fake-base64"
}
```

the error response show as below

```JSON
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|245bf394-4765b0623a867ba1.",
  "errors": {
    "$.image": [
      "The JSON value could not be converted to System.Byte[]. Path: $.image | LineNumber: 0 | BytePositionInLine: 42."
    ]
  }
}
```
expect key in errors is `Image`, but got `$.image`

### Further technical details
- ASP.NET Core version
`3.1.x`

**Comment by captainsafia** [comment] 2020-07-21 16:48
Thank you for your feedback. We're closing this issue as the behavior discussed is by design.

**Closed by captainsafia** 2020-07-21 16:48 UTC
Labels: area-mvc
