### ISSUE TITLE
Could not find aspnetcorev2_inprocess.dll when running AspNetCore\src\Mvc\samples\MvcSandbox

### ISSUE THREAD

**Issue by dshyryayev** [dotnet/aspnetcore#16976] opened 2019-11-11 14:49 UTC
I have installed fresh Windows 10, .net core sdk 3.0.100, checkout release/3.0 from AspNetCore project.
I was going to run MvcSandbox project and I've got 500.33 error
Specific error detected by ANCM:
Could not find the assembly 'aspnetcorev2_inprocess.dll' referenced for the in-process application. Please confirm the Microsoft.AspNetCore.Server.IIS or Microsoft.AspNetCore.App is referenced in your application.

![Image 034](https://user-images.githubusercontent.com/5845770/68596022-62848180-044f-11ea-8e3f-47ed39659779.png)

When I run the ".\build.cmd", on Mvc project, I am getting this:

C:\Users\dima\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj : error : Version 3.0.100
 of the .NET Core SDK requires at least version 16.3.0 of MSBuild. The current available version of MSBuild is 16.0.461
.62831. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version current
ly available.
C:\Users\dima\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19474.3\tools\Tools.proj : error MSB4236: The SDK
'Microsoft.NET.Sdk' specified could not be found.
Build failed.

**Comment by javiercn** [comment] 2019-11-11 15:13
@dshyryayev thanks for contacting us.

This is likely due to a mistmatch between some bits in our dev environment. Normally I run things directly on kestrel.

@jkotalik or @aspnet/build can probably help with the steps to get this right.

For me this happens pretty much always.

**Comment by dshyryayev** [comment] 2019-11-11 16:07
@jkotalik What should I do to setup the MvcSandbox to run directly on kestrel? I could see that CreateWebHostBuilder build a new WebHostBuilder makes a call to UseKestrel() function, but I guess it's not enough? Any advice will be appreciated.

**Comment by javiercn** [comment] 2019-11-11 16:09
@dshyryayev I assume you are running this from Visual Studio? Just go to the run Dropdown and pick the one with the app name.

**Comment by dshyryayev** [comment] 2019-11-11 16:55
When I run in powershell dotnet run, I am getting this error:
AspNetCore\src\Mvc\samples\MvcSandbox> dotnet run
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Hosting.Abstractions, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at MvcSandbox.Startup.Main(String[] args)

Same happens when I run in VS 2019: On startup process I am getting the same error:
![Image 035](https://user-images.githubusercontent.com/5845770/68605088-adf35b80-0460-11ea-8061-6776ca8e3c5f.png)

So, I though I need to build by using ".\build.cmd" command, but when I run "\.build.cmd", I am getting another error:
![Image 036](https://user-images.githubusercontent.com/5845770/68605324-104c5c00-0461-11ea-8d4f-5abe19b1fa1f.png)

**Comment by jkotalik** [comment] 2019-11-11 16:59
@javiercn we haven't done the work to get inprocess working in samples because we removed the dependency on building native by default.

@dshyryayev I think you need to fix the build.cmd error first. I believe you need to update your version of VisualStudio and then enable preview features: https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#common-error-cs0006

**Comment by dshyryayev** [comment] 2019-11-11 17:04
@jkotalik , I have installed latest VS 2019 yesterday so it was 10-Nov-2019, I think it's the latest.
I am looking into how to enable preview features!
jkotalik and javiercn, than you both for the help, I am a little surprised that I am getting responses so quickly! That's impressive!

**Comment by dshyryayev** [comment] 2019-11-11 21:01
@jkotalik 
I have re-installed Windows, installed VS2019 and other tools by looking into link you provided:
https://github.com/aspnet/AspNetCore/blob/master/docs/BuildFromSource.md#common-error-cs0006
Please look at my screenshot, you can see that after running .\restore.cmd at the end of this process, there is an error message.
And this error message persist all the time:
![error-16 3 0-ms-build](https://user-images.githubusercontent.com/5845770/68620942-6df1a000-0483-11ea-9ba1-fa5a10d0c8d3.png)

**Comment by dougbu** [comment] 2020-10-21 22:55
Looks like a dupe of #24304 and that was fixed.

**Closed by dougbu** 2020-10-21 22:55 UTC
Labels: area-infrastructure
