### ISSUE TITLE
Add TemplateRow in Blazor QuickGrid

### ISSUE THREAD

**Issue by josago97** [dotnet/aspnetcore#49004] opened 2023-06-24 11:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

A typical use of tables is that you can navigate to other pages by clicking on an element in a column or row.

Currently, QuickGrid allows the option to customize the columns and to be able to add an "a" element with a url. However, if we want that same behavior for rows, (wrapping the content of a row in an "a" element so that it can be navigated by clicking on the row) it can't be done quite so easily.

One possible solution that can be done (and I am doing) is to wrap the TemplateColumn content in an "a" element with the same path, but this solution is not the most suitable.

### Describe the solution you'd like

I suggest creating a TemplateRow component that allows the programmer to define some logic for the table rows. As a minimum data I think that the element associated with the row (context) and the index of the element in the collection (index) should be provided. For example, if I want to make the rows of a table navigate to another view determined by the position of the task in the collection when clicked and also have a different style depending on its state:

```xaml
<QuickGrid Items="@MyTasks">
 <TemplateRow>
  <a href=@($"task/{index}")>
   <div class="@(context.Status == Status.Done ? "done" : "doing")">
    @content <!-- here the columns are rendered -->
   </div>
  </a>
 </TemplateRow/>
  <PropertyColumn Property="@(t => t.Name)" />
  <PropertyColumn Property="@(t => t.Status)" />
</QuickGrid>
```

**Comment by simeyla** [comment] 2023-06-30 02:10
Are there plans for ANY 'row' behavior anytime soon?

There are several related issues:

- Callback for clicking on a row https://github.com/dotnet/aspnetcore/issues/44899
- Add css class to a row https://github.com/dotnet/aspnetcore/issues/45477

I'm new to Blazor and gravitated to QuickGrid. The docs current say:

**Comment by simeyla** [comment] 2023-06-30 02:32
Are there plans for ANY kind of 'row' behavior anytime soon ?

I'm new to Blazor and gravitated to QuickGrid because it's listed [prominently in the docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-7.0). 

It currently doesn't really have any row functionality. Related issues:

- Callback for clicking on a row https://github.com/dotnet/aspnetcore/issues/44899
- Add css class to a row https://github.com/dotnet/aspnetcore/issues/45477

The product description currently says:

> There aren't current plans to extend QuickGrid with features that full-blown commercial grids tend to offer, for example, hierarchical rows, drag-to-reorder columns, or Excel-like range selections. If you require advanced features that you don't wish to develop on your own, continue using third-party grids.

That sounds great to me! I don't need those - but it never occurred to me that 'selected row' wasn't yet an option (especially since the [demo site looks so beautiful](https://aspnet.github.io/quickgridsamples/)). 

If it is only intended to be useful for static data maybe this description needs adjusting to avoid disappointment for new users. I know it's experimental but an event to detect a click on a row, with a corresponding 'rowClass' isn't asking for much. 

-----

To anyone needing to highlight a row I've added a workaround to issue 45477.

**Comment by SteveSandersonMS** [comment] 2023-07-04 17:01
The concept of wrapping an `<a href=@($"task/{index}")>...</a>` around the `<tr>` unfortunately doesn't work as that wouldn't be valid HTML. In general you can't add extra elements around the `<tr>`, so `TemplateRow` as described here wouldn't be a useful feature (at least, not with that usage pattern).

I understand your original objective is to support selecting rows. That's definitely a reasonable requirement! I think it's already covered by the two issues mentioned above (https://github.com/dotnet/aspnetcore/issues/44899 and https://github.com/dotnet/aspnetcore/issues/45477).

> Are there plans for ANY kind of 'row' behavior anytime soon ?

The team is 100% occupied delivering the full-stack Blazor web app functionality for .NET 8 (the thing we called Blazor United earlier), so unfortunately we can't do anything on QuickGrid in the next few months. Once .NET 8 ships we have more flexibility to pick other priorities.

**Comment by SteveSandersonMS** [comment] 2023-07-04 17:02
Closing as duplicate of https://github.com/dotnet/aspnetcore/issues/44899 and https://github.com/dotnet/aspnetcore/issues/45477 - hope that's OK but let us know if not.

**Closed by SteveSandersonMS** 2023-07-04 17:02 UTC
Labels: enhancement, area-blazor, feature-blazor-quickgrid
