### ISSUE TITLE
The "CreateAppHost" task failed unexpectedly. (Version 16.8.4)

### ISSUE THREAD

**Issue by willydavidjr** [dotnet/aspnetcore#29965] opened 2021-02-07 09:30 UTC
### Describe the bug

Hi,

I am trying to run ASP.NET Core Build on my machine.  I followed the exact instruction as stated on this link: 

https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md

But still every time I run Visual Studio using MvcSandbox as Startup project and MvSandbox as Kestrel web host, it still generates this error:

```
Error	MSB4018	The "CreateAppHost" task failed unexpectedly.
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at Microsoft.NET.HostModel.AppHost.MachOUtils.RemoveSignature(String filePath)
   at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RemoveSignatureIfMachO|2()
   at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func)
   at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom)
   at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

MvcSandbox	C:\src\aspnetcore\.dotnet\sdk\6.0.100-preview.1.21073.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	512	
```
I tried to run command prompt and Visual Studio in Administrator mode, disabled all my anti-virus as was suggested here: https://github.com/dotnet/sdk/issues/10708 but still, the error still persist. 

This is the related images of the result of my build:

![image](https://user-images.githubusercontent.com/20619236/107142351-5399c100-6969-11eb-97a2-027ca84ecf56.png)

![image](https://user-images.githubusercontent.com/20619236/107142358-6613fa80-6969-11eb-8406-e98a70cc58f8.png)

### To Reproduce
I followed the exact instruction as stated on this link: 

https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md

### Further technical details
I am using the following software:

Visual Studio 2019, version 16.8.4
Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

My Device Specifications are the following:

Processor: Intel Core i7-9750H CPU @2.60GHz
Installed RAM: 16.0 GB

Microsoft OS: Windows 10 Home Single Language
Version: 1909
All updates on this specific version were already up to date. So no updates are still pending.

**Comment by MCCshreyas** [comment] 2021-02-07 10:57
Build from commandline! It works!

**Comment by Pilchie** [comment] 2021-02-08 04:48
This is a duplicate of https://github.com/dotnet/sdk/issues/12125

**Closed by Pilchie** 2021-02-08 04:48 UTC
