### ISSUE TITLE
ServerReset_BeforeRequestBody_ClientBodyThrows

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#23540] opened 2020-06-30 21:28 UTC
```
ServerReset_BeforeRequestBody_ClientBodyThrows(scheme: "http")
Assert.Throws() Failure
Expected: typeof(System.Threading.Tasks.TaskCanceledException)
Actual: typeof(System.TimeoutException): The operation at //src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:27 timed out after reaching the limit of 30000ms.
---- System.TimeoutException : The operation at //src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:27 timed out after reaching the limit of 30000ms.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=710902&view=ms.vss-test-web.build-test-results-tab&runId=22033980&resultId=113842&paneView=debug

```
[0.002s] [TestLifetime] [Information] Starting test ServerReset_BeforeRequestBody_ClientBodyThrows-http at 2020-06-30T06:55:39
[0.007s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.011s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:58255
[0.011s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Interop.FunctionalTests
[0.012s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.012s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.012s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /private/tmp/helix/working/C7D50A8A/w/B3BF09A9/e/
[0.012s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.013s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0SOAC17BMA" accepted.
[0.034s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0SOAC17BMA" started.
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" received HEADERS frame for stream ID 1 with length 35 and flags END_HEADERS
[0.036s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 POST http://127.0.0.1:58255/ - -
[0.036s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
[0.038s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" sending HEADERS frame for stream ID 1 with length 53 and flags END_HEADERS
[0.043s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Trace id "0HM0SOAC17BMA:00000001": HTTP/2 stream error "CANCEL". A Reset is being sent to the stream.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 stream was reset by the application with error code CANCEL.
[0.043s] [Microsoft.AspNetCore.Server.Kestrel] [Verbose] Connection id "0HM0SOAC17BMA" sending RST_STREAM frame for stream ID 1 with length 4 and flags 0x0
[0.044s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 POST http://127.0.0.1:58255/ - - - 200 - text/plain 8.3004ms
[0.044s] [Microsoft.AspNetCore.Server.Kestrel] [Information] Connection id "0HM0SOAC17BMA", Request id "0HM0SOAC17BMA:00000001": the application completed without reading the entire request body.
[30.110s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HM0SOAC17BMA" received FIN.
[30.110s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0SOAC17BMA" is closing.
[30.110s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0SOAC17BMA" is closed. The last processed stream ID was 1.
[30.110s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HM0SOAC17BMA" sending FIN because: "The client closed the connection."
[30.115s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Some connections failed to close gracefully during server shutdown.
[30.118s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0SOAC17BMA" stopped.
[30.120s] [TestLifetime] [Information] Finished test ServerReset_BeforeRequestBody_ClientBodyThrows-http in 30.1132513s
```

**Comment by JamesNK** [comment] 2020-09-03 01:21
I put this test in a loop and ran it 10,000 times. It passed successfully. Also it has no reported failures in the CI quarantine build.

This test uses HTTP/2 + HttpClient, so a bug added to the client and then fixed was likely the cause.

Closing.

**Closed by JamesNK** 2020-09-03 01:21 UTC
Labels: area-servers, test-failure
