### ISSUE TITLE
Kestrel NullReferenceException at GetCurrentReadOnlySequence

### ISSUE THREAD

**Issue by ipax77** [dotnet/aspnetcore#34032] opened 2021-07-02 11:36 UTC
### Describe the bug
I am running a dotnet 6 preview 5 Blazor wasm hosted project on my Ubuntu 18.04 Server in a docker-container (mcr.microsoft.com/dotnet/sdk:6.0)

After every HttpClient requests (noauth) I get a warning log:
```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
       Connection processing ended abnormally.

```
I never saw this warning in development nor in my dotnet core 3/5 projects

### To Reproduce
Run new dotnet 6 preview 5 Blazor wasm hosted project in a docker-container (mcr.microsoft.com/dotnet/sdk:6.0) open Tab 'Fetch data' and wait ~10sec

### Exceptions (if any)
```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at System.IO.Pipelines.StreamPipeReader.GetCurrentReadOnlySequence() in System.IO.Pipelines.dll:token 0x6000123+0x22
         at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|36_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken) in System.IO.Pipelines.dll:token 0x600012a+0x2ba
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x6000d24+0x54c
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x6000d23+0x1fe

```
### Further technical details
- ASP.NET Core version 6.0.0-preview.5.21301.17
- Include the output of `dotnet --info`
- .NET SDK (gemäß "global.json"):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
VS Version 17.0.0 Preview 1.1

**Comment by Tratcher** [comment] 2021-07-02 16:40
This looks like a duplicate of https://github.com/dotnet/runtime/issues/53451 and should be fixed in preview6.

**Closed** 2021-07-07 20:32 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, area-runtime
