### ISSUE TITLE
Opting out of Developer exception page during development

### ISSUE THREAD

**Issue by jez9999** [dotnet/aspnetcore#43870] opened 2022-09-09 10:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'd like a way to opt out of the Developer exception page during development.  The new "opt in by default" is great because it saves massive amount of code, like 4 lines or something, which made my startup looked very cluttered.  Unfortunately, it also took away the ability for me to opt out if I wanted just by commenting 4 lines out.

### Describe the solution you'd like

A way to opt out of the Developer exception page middleware during development.

**Comment by Tratcher** [comment] 2022-09-09 17:18
Can you give more information about why you'd want to opt out? Is it interfering with your app in some way?

**Comment by jez9999** [comment] 2022-09-09 17:37
To test the production error page during debug mode, or create my own error page.  I mean, I'm not sure why I have to justify it.  ASP.NET core always gave the developer the power to structure their pipeline however they wanted and you seem to be moving towards taking that away.

**Comment by Tratcher** [comment] 2022-09-09 17:42
The explanations help us work out the solutions.

To test the production error page you can change the Environment to something like `Staging`.

If you created your own error page it would take precedence over the default one. There shouldn't be any conflict here.

**Comment by jez9999** [comment] 2022-09-09 17:47
Does .NET 6 opt-in to the developer page middleware when you use the `IHostBuilder.CreateDefaultBuilder`, or are you telling me it's only when you use `WebApplication.CreateBuilder`?  If so, I'd say [this documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-6.0) could do with updating as it doesn't make that distinction, saying "ASP.NET Core apps enable the developer exception page by default when running in the Development environment".

**Comment by Tratcher** [comment] 2022-09-09 22:42
`IHostBuilder.ConfigureWebHostDefaults` used for setting up a default web app with the generic IHostBuilder does not include the DevExceptionPageMiddleware. Yes that should be clarified in the doc.

https://github.com/dotnet/aspnetcore/blob/349ddc9b8bf8255166f87899d7905510f362a5d5/src/DefaultBuilder/src/GenericHostBuilderExtensions.cs#L61-L73
It does include things like Kestrel, IIS (in-proc and out-of-proc),  host filtering, and forwarded headers. https://github.com/dotnet/aspnetcore/blob/349ddc9b8bf8255166f87899d7905510f362a5d5/src/DefaultBuilder/src/WebHost.cs#L216-L253
If you don't want to use those you're free to use ConfigureWebHost directly.

**Comment by davidfowl** [comment] 2022-09-10 06:58
We could treat this as a dupe of https://github.com/dotnet/aspnetcore/issues/32485

**Closed** 2022-09-15 21:08 UTC
Labels: Docs, area-runtime
