### ISSUE TITLE
Using bind and onblur event on the input element cause "Uncaught (in promise) Error: System.ArgumentException: There is no event handler associated with this event. EventId: '4'"

### ISSUE THREAD

**Issue by PonmaniMurugaiyan** [dotnet/aspnetcore#28179] opened 2020-11-26 12:21 UTC
**Issue Description**

When using bind attribute and onblur event on the input element cause `Uncaught (in promise) Error: System.ArgumentException: There is no event handler associated with this event. EventId: '4`.

**Sample:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/BlazorApp531274741370 

**Replication procedure**

1.	Run the sample
2.	Click the Navigate button for go to Counter page
3.	Then enter anything in the TextBox which is rendered in the Counter page
4.	Now, press the back button on chrome browser.
5.	Now, see the console for error

**Screenshot**

![image](https://user-images.githubusercontent.com/61738415/100349977-33679080-300f-11eb-997b-0a6db13d5b30.png)

**Code Snippet**

```
<input @bind="val" @onblur="blurevent" />

@code{
    public void blurevent(FocusEventArgs args)
    {
    }
    public string val { get; set; }
}
```

**Comment by javiercn** [comment] 2020-11-27 13:06
@PonmaniMurugaiyan thanks for contacting us.

We believe this is a duplicate of https://github.com/dotnet/aspnetcore/issues/26838

**Closed** 2021-01-15 11:52 UTC
Labels: :heavy_check_mark: Resolution: Duplicate, Status: Resolved, area-blazor
