### ISSUE TITLE
Razor Pages: Page title shows incorrect symbols for Russian characters retrieved from JSON configuration file 

### ISSUE THREAD

**Issue by JohnyL** [dotnet/aspnetcore#21830] opened 2020-05-14 16:24 UTC
I have the following `appsettings.json` configuration file:
```
{
    "Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "AllowedHosts": "*",
    "Title": "Поиск"
}
```
`_Layout.cshtml` file:
```
!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
</head>
```

Here's the Razor page which sets the title for `_Layout.cshtml`:
````
@page
@model FLWebApp.Pages.SearchModel
@using Microsoft.Extensions.Configuration;
@inject IConfiguration Configuration

@{
    ViewData["Title"] = Configuration["Title"];
    //ViewData["Title"] = "Поиск";
}
````
As you can see, on the first line I get the text for the title from configuration file.
I get abracadabra in the title:

![IMG1](https://wpxfkw.db.files.1drv.com/y4myZSc7ydxNYq6ayt6S7ukDJnO81UUEyVDKRUjSlaJc1enNWs_4Wl9ujW0756iced0KLlQIsYfrh6WqPzxiCHtW4NEBHyS81Ny0HEtTzfCjrc6RdTLCURTLELwoRMrJb-fGdKzghqPFh_hl2fYj0U9uGxs2RLFU5ctS3-VcmRv4OJYhrHXbY7pGNO2ixh6aTVMJgCk2pdb--nY5gqA9rkObg?width=279&height=47&cropmode=none)

However, if I comment first line and uncomment second line (i.e. will use the word "Поиск" directly), everything is OK:

![IMG2](https://wpzgbw.db.files.1drv.com/y4msp8wVRCJDuGHVP6PArr8T9BGz91yjiWyejqSKhC-7-FDTZLGimnjs3gbDUTh7kaDpYXONfBkoF3Cnn39HhFKIdDaGFgY5oCMUTzl-1AQMKOEQL5IYrjr6x5XyYa2lly15QlqTjqPEGRSxiy9ZZncU5QYgZlCttQqvKTzoVB8yuxf8190gOFyfTaLkVgN2BEUfJGisn5ml6VrCRlpSXDSvw?width=282&height=44&cropmode=none)

I have tried to set `<meta charset="windows-1251" />`, but alas - the same result.

### Further technical details
- ASP.NET Core version: 5.0.100-preview.3.20216.6
- The IDE (VS / VS Code/ VS4Mac): VS 2019 16.6.0 Preview 6.0
- Include the output of `dotnet --info`:

Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   5.0.100-preview.3.20216.6
 Commit:    9f62a32109

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.3.20216.6\

Host (useful for support):
  Version: 5.0.0-preview.3.20214.6
  Commit:  b037784658

.NET SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.3.20216.6 [C:\Program Files\dotnet\sdk]

**Comment by Sm1le291** [comment] 2020-05-14 16:52
Hi! First of all, as I know Blazor does not work officially with .net 5.0
Try to create in notepad++ or somewhere else file  with UTF8 encoding, enter text there and copy from there to VS. I think problem will be gone. 
Check that ~\Server\wwwroot\index.html contains <meta charset="utf-8">
win-1251 obviously not correct

**Comment by JohnyL** [comment] 2020-05-14 17:03
@Sm1le291 Beg your pardon, but you didn't read my question at all. For instance, my question is about Razor Pages - not Blazor.

**Comment by Sm1le291** [comment] 2020-05-14 17:11
@JohnyL sorry for this. But nothing changed, the problem is that:
1) you somewhere forced to use invalid encoding using wrong meta encoding tag
2) one of your file was saved in invalid encoding, double check that all .cshtml or .razor has UTF-8 (try with BOM and without) encoding.
3) If you pasted text somewhere, you did it in wrong encoding

**Comment by JohnyL** [comment] 2020-05-14 17:26
@Sm1le291 
1. All encodings are in question. Please, point to something invalid.
2. The encoding of the cshtml page itself has nothing to do with the problem. And I didn't change it since the project has been created.
3. The text in `appsettings.json` was entered manually - nothing was pasted.

**Comment by Sm1le291** [comment] 2020-05-14 17:30
@JohnyL choose file, Save As and then Save With Encoding in dropdown, try UTF-8 with or wothout signature

**Comment by Sm1le291** [comment] 2020-05-14 17:38
@JohnyL I checked in my project, encoding of appsettings.json is win-1252. That's your problem. Just save it in Utf-8

**Comment by JohnyL** [comment] 2020-05-14 17:40
@Sm1le291 Yes, UTF-8 did help! Thanks! 😉

**Closed** 2020-05-14 17:47 UTC
Labels: area-mvc
